### ISSUE TITLE
What are the main languagetool limitations to be aware of?

### ISSUE THREAD

**Issue by brupelo** [languagetool-org/languagetool#1000]
Hi, this is the first time I'm using Languagetool, I've downloaded the latest [standalone version](https://languagetool.org/download/LanguageTool-4.1.zip) v4.1 and gave it a fast shot.

I'm not a native English speaker but I'd like to use this tool mainly as an assistant, so I'll be able to learn a little more about my grammar mistakes. I have noticed the tool isn't detecting basic grammar errors, like the correct usage of prepositions... I'd like to know what to expect from it and what not.

Let me put it differently, I've seen in the options there are two tabs Grammar rules and Style rules, is the software sticking to these rules and that's it or by contrary it is doing something else?

**Comment by danielnaber** [comment]
You can check out all rules at https://community.languagetool.org/rule/list?lang=en. There's no further formal definition of what can be detected and what cannot be detected.

If you have further questions, please post them to the forum at https://forum.languagetool.org, as we use the github issue tracker only for bugs.
