### ISSUE TITLE
[DE] Fehler bei der Deklination mit "Druckerpresse"

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#10018]
Moin liebes LanguageTool-Team

Er las die aktuelle Zeitung, die nicht über die verwüsteten Verstecke sprach, weil diese Informationen zu spät bei **den Druckerpressen** erschien.
LT: "Möglicherweise passen das Nomen und die Wörter, die das Nomen beschreiben, grammatisch nicht zusammen."
LT-Vorschlag: "dem Druckerpressen"

Laut [Duden](https://www.duden.de/deklination/substantive/Druckerpresse) gibt es keinen Dativ mit "dem" bei Druckerpresse.

Bitte diesen Fehler fixen.

Grüße Dallun511

**Comment by danielnaber** [comment]
Danke, ist behoben.
