### ISSUE TITLE
[pt] Too many zeros in PD.+ ?

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#10024]
Heya, @susanaboatto and @p-goulart 

Does it have too many zeros in the postag?

![Screenshot 2024-01-02 at 12-08-17 Análise de Texto - LanguageTool](https://github.com/languagetool-org/languagetool/assets/5192600/206117e2-63bf-4dcf-b6c1-e1685ccdce7d)

Thanks!

**Comment by p-goulart** [comment]
No, but I understand the confusion as I went through this a couple of days ago.

Pronouns have **eight** slots, not seven, this just isn't described in the `tagset.txt` file. I aim to rectify that soon.

As luck would have it, a big part of the current work I'm doing with the dictionaries includes revising the POS tagger's dictionary's tags.

---

The current slots are the following, per Spanish:
```
6. PRONOMBRES
Pos. 	Atributo 	Valor 	Código
1 	Categoría 	Pronombre 	P
2 	Tipo 		Personal 	P
			Demostrativo 	D
			Posesivo 	X
			Indefinido 	I
			Interrogativo 	T
			Relativo 	R
			Numeral 	N
			Exclamativo 	E
3 	Persona 	Primera 	1
			Segunda 	2
			Tercera 	3
4 	Género 		Masculino 	M
			Femenino 	F
			Común 	C
			Neutro 	N
5 	Número	 	Singular 	S
			Plural	 	P
			Invariable 	N
6 	Caso 		Nominativo 	N
			Acusativo 	A
			Dativo	 	D
			Oblicuo 	O
7 	Poseedor 	Singular 	S
			Plural	 	P
8 	Politeness 	Polite	 	P

Ejemplo: Ella, PP3FS000
```

**Comment by p-goulart** [comment]
Fixing the tagging of the pronouns led to some rules needing to be tweaked, btw. Please don't do anything radical, I'm taking care of it on my end.
