### ISSUE TITLE
fr-CA locale not supported

### ISSUE THREAD

**Issue by Pierre-Thibault** [languagetool-org/languagetool#10031]
I have this error on my machine.

'fr-CA' is not a language code known to LanguageTool.

I am running LanguageTool 6.1.1 on Linux with Java 17.0.2.

Can you add this locale ?

**Comment by danielnaber** [comment]
@FredKruse

**Comment by FredKruse** [comment]
@Pierre-Thibault This is a known bug in LT 6.1.1. Please install the current version LT 6.3.1

**Comment by Pierre-Thibault** [comment]
I did the upgrade suggested, and the issue is gone.

😀
