### ISSUE TITLE
What is the best "health check" for language tool?

### ISSUE THREAD

**Issue by sdole** [languagetool-org/languagetool#1004]
Hello,

How CPU intensive is the GET /v2/languages request? I have that configured as the periodic health check on an AWS Load Balancer and I am seeing frequent timeouts of 5 seconds or more when language tool is under severe load. Is there a better URL that can serve as a proper ALB healthcheck?

Thanks in advance!

--Sachin

**Comment by danielnaber** [comment]
I use the `check` endpoint with a very short sentence. How exactly have you set up the health check? If LT is under load so that the health check becomes slow, isn't that expected behavior?

**Comment by sdole** [comment]
Right now, the healthcheck is very relaxed and I will likely change it. I have it here since you asked. For the expected behavior, yes, under load it will become slow and that is expected. However, I am seeing that under load (during a load test), LT seems to chug along decently well, but, the `/v2/languages` seems to slow down more than I expect it to.

```
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /v2/languages
      HealthCheckPort: 8080
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
```

**Comment by danielnaber** [comment]
After the first call, I don't see anything which could be slow (https://github.com/languagetool-org/languagetool/blob/master/languagetool-server/src/main/java/org/languagetool/server/ApiV2.java#L119-L133).

**Comment by sdole** [comment]
thank you.
