### ISSUE TITLE
[LO Extension] Accept: is_goal_specific="true" — 2024-01-08

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#10059]
Hello @FredKruse 

Months ago, I asked if the rules with the token above would work in the LibreOffice add-on, and a developer said they would only work in the on-line Editor.

Would it be possible for you to create a checkbox on the preferences of the LibreOffice add-on to make it use those rules, just like if they were normal rules?

Thank you!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by FredKruse** [comment]
I have tried to install the feature. But I got the problem, that I can't test it because goal-specific rules seam not to be used in English or German. Please test it for your specific cases and give me feedback. 
You can activate the rules by setting the checkbox in the general option panel.

**Comment by marcoagpinto** [comment]
@FredKruse 

Thank you, I will test it tonight.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
Heya, @FredKruse 

It worked, but it threw an exception while I was writing the text:

![Screenshot 2024-01-09 053226](https://github.com/languagetool-org/languagetool/assets/5192600/84161a3f-7738-4c92-8f3f-472d7b714603)

Here is the rule I triggered:
```
        <rule id='APAGAR_INDELÉVEL' name="[Universitário][Científico] Não conseguir apagar → Indelével" tone_tags="academic" is_goal_specific="true" default="temp_off">
            <pattern>
                <marker>
                    <token>que
                        <exception scope="previous" postag_regexp='no' postag='SENT_START'/>
                    </token>
                    <token>não</token>
                    <token>se</token>
                    <token postag='V.+' postag_regexp='yes'/>
                    <token>apagar</token>
                </marker>
            </pattern>
            <message>Num contexto formal/científico, é preferível escrever &quot;indelével&quot;.</message>
            <suggestion>indelével</suggestion>
            <example correction="indelével">O passado é algo <marker>que não se consegue apagar</marker>.</example>
        </rule>
```

And here is a screenshot of it working:
![Image1](https://github.com/languagetool-org/languagetool/assets/5192600/9afe1fd2-ac05-4bdf-a193-a27404577f61)

Excellent work!

Thank you!

**Comment by maphjo** [comment]
Just a quick comment from the LT crew:
Can you confirm that the default for the LO extension still is the `is_goal_specific` rules are not active? This would be the intended behavior. :wink: And @marcoagpinto can still turn them on for his usage. :relaxed: 

And to make it even more **as intended**, instead of making `is_goal_specific` rules available with out a Writing Goal selected, you could let users choose the Writing Goal they want to use and enable the respective rules.

Here is the documentation of the toneTags to the Writing Goals. https://dev.languagetool.org/style_tone_tags

Let me know if there are any questions.

**Comment by FredKruse** [comment]
> Just a quick comment from the LT crew: Can you confirm that the default for the LO extension still is the `is_goal_specific` rules are not active? This would be the intended behavior. 😉 And @marcoagpinto can still turn them on for his usage. ☺️
> 
> And to make it even more **as intended**, instead of making `is_goal_specific` rules available with out a Writing Goal selected, you could let users choose the Writing Goal they want to use and enable the respective rules.
> 
> Here is the documentation of the toneTags to the Writing Goals. https://dev.languagetool.org/style_tone_tags
> 
> Let me know if there are any questions.

Yes, I can confirm that the switch on of goal_specific rules is only an optional adjustment in the option panel. For default, the goal_specific rules are switched off.
Yes, it is a good idea, to turn on and off one or more tone_tags, but this additional work in the option panel. I added it to my list ;)
The concept of tone_tags is very interesting. But what's the matter with literary texts like novels? What tone_tag should be used.

**Comment by FredKruse** [comment]
@marcoagpinto I know the bug, and I'm working on it since yesterday. It's a little bit complicated. Please test the next nightly. I'm not really sure, that it is solved.

**Comment by marcoagpinto** [comment]
> @marcoagpinto I know the bug, and I'm working on it since yesterday. It's a little bit complicated. Please test the next nightly. I'm not really sure, that it is solved.

Sure, thanks!

**Comment by maphjo** [comment]
> But what's the matter with literary texts like novels? What tone_tag should be used.

--> The writing goal would be "Original & Expressive". We have not yet defined exclusive toneTags for this writing goal.

**Comment by marcoagpinto** [comment]
@FredKruse 

Heya,

The issue seems fixed, but there was a pause (only once) while I was writing the text.

Thanks!


https://github.com/languagetool-org/languagetool/assets/5192600/f30baaf0-7584-4343-b6a7-04b88433c8d6

**Comment by FredKruse** [comment]
@marcoagpinto 
The enhancement is done, I think. Can we close the issue?

**Comment by marcoagpinto** [comment]
Sure! Thanks!
