### ISSUE TITLE
spelling_en-US.txt etc ignored for generating suggestions

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1005]
See https://forum.languagetool.org/t/new-word-in-spelling-txt-not-available-as-suggestion/2996

The problem seems to be in `MorfologikMultiSpeller`:

```
new BufferedReader(new InputStreamReader(JLanguageTool.getDataBroker().getFromResourceDirAsStream(plainTextPath), "utf-8"))
```

Both files need to be considered here (and e.g. appended with `SequenceInputStream`).

**Comment by kapilgupta77** [comment]
Hi Daniel,

Thank you for the response. 
Your reply suggests that the issue is not specific to a particular word but the whole list in spelling.txt is not considered for generating suggestions?
I noticed that same issue is reproducable for en-GB language as well.

Thanks

Kapil
