### ISSUE TITLE
Clarification on LanguageTool Maven repositories and version availability

### ISSUE THREAD

**Issue by pereorga** [languagetool-org/languagetool#10091]
I am currently using LanguageTool in my projects and have noticed a discrepancy in the versioning. According to my [Maven setup](https://github.com/pereorga/pccd-lt-filter/blob/master/pom.xml), I am using LanguageTool version 6.4.11. However, the latest official release listed on the [Release Roadmap](https://dev.languagetool.org/roadmap.html) and the Maven Central Repository appears to be version 6.3. ([GitHub also seems to indicate latest version is 6.3](https://github.com/languagetool-org/languagetool/tags), but see https://github.com/languagetool-org/languagetool/issues/10073)

1. Is Maven repository https://repo.languagetool.org/artifactory/languagetool-os-release/ an official repository from the LanguageTool team?
2. If so, are releases seen in https://mvnrepository.com/artifact/org.languagetool/languagetool-core?repo=languagetool-os-release development versions or snapshots? I noticed these versions get updated more frequently.

**Comment by danielnaber** [comment]
> Is Maven repository https://repo.languagetool.org/artifactory/languagetool-os-release/ an official repository from the LanguageTool team?

That's our repo, but it's not official. The releases there are not necessarily stable. We provide stable releases on Maven Central, but no official snapshots for Maven.
