### ISSUE TITLE
ArrayIndexOutOfBoundsException in GermanWordRepeatRule

### ISSUE THREAD

**Issue by ronnystandtke** [languagetool-org/languagetool#1010]
We are allowing LanguageTool for some schools in Switzerland during exams and I just got a call that our Linux based exam environment produced a horrible error message on some students laptops that just really scared them.

I could reproduce the problem by just typing the following words (in German) in LibreOffice: "Hat sie sie"
This caused this big error message with a stack trace that boils down to an ArrayIndexOutOfBoundsException in GermanWordRepeatRule at line 78.

Thank you for your great work on LanguageTool and thanks for fixing this bug.

**Comment by f-knorr** [comment]
Sorry for the inconveniences. The error is fixed in the repository. It turned out there was '+'-sign where a '-'-sign should have been...Small error, big error message.
