### ISSUE TITLE
[en] Rule assumes, first letter is pronounced as a vowel, but despite being one, it's pronounced like a consonant

### ISSUE THREAD

**Issue by shaedrich** [languagetool-org/languagetool#10182]
The example even lists the opposite case "an hour", which indicates, that it's not the literal letter, that's important, but the actual pronounciation is `ˈwidʒə`, so it actually is pronounced starting with a `ˈw`, which is a consonant.

![grafik](https://github.com/languagetool-org/languagetool/assets/11225821/2989e6b2-0d45-4499-adb4-b2812dabab36)

**Comment by evan-defran-lt** [comment]
Hi @shaedrich, thanks for flagging this to us. I've added an exception to the rule. Please allow 24-36 hours before you see the fix implemented in LT.

**Comment by shaedrich** [comment]
Thanks for the quick fix! 👍🏻
