### ISSUE TITLE
[de] spell checker: problem with the word 'Regenrinne'

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#1019]
On the LT website, I'm experiencing a minor but confusing issue: The spell checker does not accept the word 'Regenrinne', but it suggests that very same word as a correction for itself.
When I choose the suggestion from the list and re-run the check, the word is rejected again.
![2018-06-05-125808_1024x768_scrot](https://user-images.githubusercontent.com/4381288/40973148-750e5bba-68c3-11e8-9220-96608ad2f6c4.png)

**Comment by danielnaber** [comment]
Should be fixed now.
