### ISSUE TITLE
language-uk: "There are test failures"

### ISSUE THREAD

**Issue by sylvainhalle** [languagetool-org/languagetool#1021]
Steps to reproduce (as per `Readme.md`):

1. Clone repo with `git clone --depth 5 https://github.com/languagetool-org/languagetool.git`
2. Run `mvn clean test`

The thing runs for a couple minutes, and you get:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project language-uk: There are test failures.
[ERROR]
[ERROR] Please refer to /home/sylvain/Workspaces/languagetool/languagetool-language-modules/uk/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
```

The folder `...languagetool-language-modules/uk/target/surefire-reports` has a couple of text files, two of which report test failures (see attached files).

Environment:
- Ubuntu 18.04
- Java 8 (Sun)
[org.languagetool.rules.uk.TokenAgreementAdjNounRuleTest.txt](https://github.com/languagetool-org/languagetool/files/2096261/org.languagetool.rules.uk.TokenAgreementAdjNounRuleTest.txt)
[org.languagetool.rules.uk.UkrainianPatternRuleTest.txt](https://github.com/languagetool-org/languagetool/files/2096262/org.languagetool.rules.uk.UkrainianPatternRuleTest.txt)

**Comment by danielnaber** [comment]
When you check out with that git command, you won't get the latest release but the current state. To build the release, use `git checkout v4.1` first.

**Comment by TiagoSantos81** [comment]
One of these commits introduced the error:
https://github.com/languagetool-org/languagetool/commit/c8c994216ddc4e981050a7fdd944d1b5f6afc48b
https://github.com/languagetool-org/languagetool/commit/ecceb7aee043510db0255d008316fe2ae7b8ce05
https://travis-ci.org/languagetool-org/languagetool/builds/391011806?utm_source=github_status&utm_medium=notification

https://github.com/languagetool-org/languagetool/commit/c8c994216ddc4e981050a7fdd944d1b5f6afc48b#comments
