### ISSUE TITLE
Underline color: Java error if there is a comma in category name

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#1022]
I changed the name in category id="STYLE" to name="Rule 4, Style" to show the problem.

I changed the underline colour in the GUI:
![image](https://user-images.githubusercontent.com/5816160/41355899-6993dfa0-6f1a-11e8-98b7-aff00f4ce8bd.png)

LT works fine and the offending text has a coloured underline.

Close LT and start it again. I get this Java error:
![image](https://user-images.githubusercontent.com/5816160/41356003-b26eea76-6f1a-11e8-8fa9-38cfcdae5b50.png)

I did not do a test to see if the problem occurs with other characters that are valid in a category name.

**Comment by MikeUnwalla** [comment]
Will this bug be corrected before the LT 4.2 release? (Nobody is assigned to it.)

If a correction is not possible, or if a comma is now not a valid character in a category name, can someone (@danielnaber ?) please add a check to testrules to say "do not use a comma in a category name"? Thanks.

**Comment by f-knorr** [comment]
Hi @MikeUnwalla , can you confirm that the problem is solved?

**Comment by MikeUnwalla** [comment]
@f-knorr , problem solved. Thank you very much.
