### ISSUE TITLE
[de] False negative bei "weder noch" mit eingeschobenen Nebensatz

### ISSUE THREAD

**Issue by shaedrich** [languagetool-org/languagetool#10229]
[Diese Regel](https://languagetool.org/insights/de/beitrag/kommas-konjunktionen/) scheint hier nicht zu greifen, wenn ein eingeschobener Nebensatz(?) vorliegt:

![Languagetool_weder_noch](https://github.com/languagetool-org/languagetool/assets/11225821/0243d19b-37e1-4a5a-94db-1f7d1ffa5699)

**Comment by Luisa-LT** [comment]
Hi @shaedrich, danke für das Issue. Allerdings konnte ich das False Positive nicht reproduzieren: 
![image](https://github.com/languagetool-org/languagetool/assets/115984740/ee3ba709-7e42-4496-a606-7d6ae5e8ba56)

Könntest du es erneut versuchen bzw. uns vielleicht mal den ganzen Satz schicken?

**Comment by shaedrich** [comment]
Der komplette Satz lautet "Allerdings trug er gerade weder die Maske der Coolness, die er
sonst jeden Tag trug, noch hatte er sie völlig fallen lassen wie in dem Moment am Teich.".

Spannend, auf languagetool.org wird der Fehler nicht angezeigt

![grafik](https://github.com/languagetool-org/languagetool/assets/11225821/f7e8762b-178d-4429-b4ea-bdbdeeaace0e)

Nur in der Firefox-Erweiterung 🤔 

![grafik](https://github.com/languagetool-org/languagetool/assets/11225821/1455a24d-d399-4fa2-a551-55bec8d32dee)

**Comment by Luisa-LT** [comment]
Danke, kann es sein, dass im zweiten Screenshot ein Zeilenumbruch nach „er“ kommt? Dann schlägt die Regel auch bei mir an, da durch einen Zeilenumbruch das Ende des Satzes markiert wird.

**Comment by shaedrich** [comment]
Oh, ja, der war nicht sichtbar. Dann sorry für den Fehlalarm 😬 😅

**Comment by Luisa-LT** [comment]
Kein Problem! Happy to help :-)
