### ISSUE TITLE
[nl] disambiguation bug?

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#10230]
I had problems with this disambig rule:
```
	<rule id="NEW_444" name="-">
        <pattern>
			<token postag="WKW:TGW:3EP"><exception negate_pos="yes" postag="WKW:TGW:3EP"/></token>
			<token postag="BYW"><exception negate_pos="yes" postag="BYW"/></token>
			<marker>
				<token postag_regexp="yes" postag="WKW:TGW:1EP|BNW:STL:ONV"><exception negate_pos="yes" postag_regexp="yes"  postag="WKW:TGW:1EP|BNW:STL:ONV"/></token>
			</marker>
			<token postag="SENT_END" regexp="yes">[.!?]</token>
		</pattern>
        <disambig action="remove" postag="BNW:STL:ONV"/>
    </rule>
```
The result of this is not that just BNW:STL:ONV is removed, but both tags.

I work around it by re-assigning the tag, but I guess this is not as intended. When one tag is specified for deletion,. not both of them should be removed.

**Comment by baarsrj** [comment]
@Luisa-LT This bug is not just Dutch.

**Comment by Luisa-LT** [comment]
Thanks! We will look into it.

**Comment by jaumeortola** [comment]
I cannot reproduce the problem in other languages. 
Please post a sentence in Dutch that matches this pattern. @baarsrj

**Comment by baarsrj** [comment]
This is what is the result of the above rule (I had to recompile the version locally)
Example patterns for this are:

 is nog lang.
 is nog open.
 is nu open.
 is er zeker.
 is nog bezig.

The strangest thing about this, is the postag that should be removed, is the one remaining.

![afbeelding](https://github.com/languagetool-org/languagetool/assets/8479998/6474fcd3-4c32-42c5-88aa-72148d73fc39)

**Comment by jaumeortola** [comment]
The problem is that there is another rule with the same ID in line 10345.

```
<rule id="NEW_444" name="-">
        <pattern>
			<token postag="WKW:TGW:3EP"><exception negate_pos="yes" postag="WKW:TGW:3EP"/></token>
			<token postag="BYW"><exception negate_pos="yes" postag="BYW"/></token>
			<marker>
				<token postag_regexp="yes" postag="WKW:TGW:1EP|BNW:STL:ONV"><exception negate_pos="yes" postag_regexp="yes"  postag="WKW:TGW:1EP|BNW:STL:ONV"/></token>
			</marker>
			<token postag="SENT_END" regexp="yes">[.!?]</token>
		</pattern>
        <disambig postag="BNW:STL:ONV"/>
    </rule>
```

If you rename the rule, it works as expected. 

Having two rules with the same ID causes an exception: 
> Caused by: org.xml.sax.SAXParseException; lineNumber: 10357; columnNumber: 30; cvc-id.2: There are multiple occurrences of ID value 'NEW_444'.

**Comment by baarsrj** [comment]
2 rules with the same id is reported when compiling. Locally, there are no 2 rules NEW_444. I don´t see 2 on github either...

**Comment by baarsrj** [comment]
It is exactly that rule that is malfunctioning. That can only be seen by editing it to the rule as mentioned above.

**Comment by baarsrj** [comment]
There is a long list of commits pending now. Those will be committed tomorrow. I will ad a test rule for you at the end, having the ID_BUG_DEMO.

**Comment by jaumeortola** [comment]
The duplicate ID is confusing. Sorry about it. It was just how I found the problem while debugging. 


The current rule NEW_444 is
```
<rule id="NEW_444" name="-">
    <pattern>
		<token postag="WKW:TGW:3EP"><exception negate_pos="yes" postag="WKW:TGW:3EP"/></token>
		<token postag="BYW"><exception negate_pos="yes" postag="BYW"/></token>
		<marker>
			<token postag_regexp="yes" postag="WKW:TGW:1EP|BNW:STL:ONV"><exception negate_pos="yes" postag_regexp="yes"  postag="WKW:TGW:1EP|BNW:STL:ONV"/></token>
		</marker>
		<token postag="SENT_END" regexp="yes">[.!?]</token>
	</pattern>
    <disambig postag="BNW:STL:ONV"/>
</rule>
```
It works as expected. It replaces (default action is "replace") the existing POS tags with `BNW:STL:ONV`. 

If you want to remove this tag, you need to change the action:
```

**Comment by baarsrj** [comment]
That was my problem. remove did not work. But anyway... I just added a debug rule, and that one worked as expected. I am totally lost now.
I am closing this, unitl I can easily reproduce the issue, if still there.
