### ISSUE TITLE
Add Only Office plugin on the list of office plugins on the Website

### ISSUE THREAD

**Issue by MariMightyMedia** [languagetool-org/languagetool#10236]
I just saw that on the list of office plugins Only Office is not listed

[Google Docs](https://languagetool.org/google-docs)
[Microsoft Word](https://languagetool.org/word)
[Apple Pages](https://languagetool.org/mac-desktop)
[OpenOffice](https://languagetool.org/open-office)
[LibreOffice](https://languagetool.org/libre-office)

even tough, it exists:
https://www.onlyoffice.com/app-directory/de/languagetool

I nearly was about to choose a different tool because it doesn't have the integration, but it has, so just please add it.

**Comment by danielnaber** [comment]
It's listed at https://dev.languagetool.org/software-that-supports-languagetool-as-a-plug-in-or-add-on, where all the community-contributed tools are listed.
