### ISSUE TITLE
Color parameter outside of expected range: Green

### ISSUE THREAD

**Issue by deanqx** [languagetool-org/languagetool#10258]
I use the Code Highlight 2 extension.
When I click on Recheck Document this pops up:
![image](https://github.com/languagetool-org/languagetool/assets/110404616/34091c84-2fba-4d6d-bc39-d9697f042957)

**Comment by revolver-ocelot-saa** [comment]
I am also seeing the same error using the LanguageTool 6.3.1 extension with the Flatpak version of Libreoffice 24.2.0.3 from build [da48488a73ddd66ea24cf16bbc4f7b9c08e9bea1](https://git.libreoffice.org/core/+log/da48488a73ddd66ea24cf16bbc4f7b9c08e9bea1)

![image](https://github.com/languagetool-org/languagetool/assets/54005036/512e39bd-1ba5-4a96-b1c0-78ac9dab9a3d)

**Comment by FredKruse** [comment]
The bug should be solved in the 6.4 version. You can find the current developer version here:
https://internal1.languagetool.org/snapshots/
Please test it and close the issue if the two errors no longer occur in 6.4.

**Comment by revolver-ocelot-saa** [comment]
I tested with the LanguageTool-20240220-snapshot.oxt at the link you provided. That appears to have completely resolved the issue. Thank you for posting that and replying!

**Comment by deanqx** [comment]
I will test it in some weeks
