### ISSUE TITLE
[en] The word "Belorussian" is incorrect

### ISSUE THREAD

**Issue by ssvb** [languagetool-org/languagetool#10269]
I see that a lot of people are writing "Belorussian" instead of "Belarusian" in various forums. And suspect that the spellcheckers, such as LanguageTool, are contributing to this. It would be nice to get this issue resolved.

**Comment by evan-defran-lt** [comment]
Thank you for your comment.
[M-W](https://www.merriam-webster.com/dictionary/Belorussian), [Cambridge](https://dictionary.cambridge.org/us/dictionary/english/belorussian?q=Belorussian) and [Oxford](https://www.oed.com/search/dictionary/?scope=Entries&q=Belorussian) dictionaries accept 'Belorussian' as an alternative spelling of 'Belarusian'.

Additionally, according to Google n-gram data, 'Belorussian' occurs with enough frequency in published materials that it seems we should accept it as a spelling.

If we can find an authoritative source that indicates that 'Belarusian' is the internationally preferred spelling in modern contexts, we can suggest that writers change 'Belorussian' to 'Belarusian'. But for the time being, we will not flag 'Belorussian' as a spelling mistake, as it is an accepted spelling according to major, authoritative English dictionaries.
