### ISSUE TITLE
[DE] "(k)einen, (k)einem, (k)ein" LanguageTool-Fehlermeldungen

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1026]
Moin, liebe Community

"Die Baufirma wollten erstmal einen Architekten und **einen** Sachverständiger losschicken."
"Die Baufirma wollten erstmal einen Architekten und **einem** Sachverständiger losschicken."

LanguageTool-Fehlermeldung: "Möglicherweise fehlende grammatische Übereinstimmung zwischen Artikel und Nomen ..."

Hier ist noch ein Fehlalarm. Das LanguageTool erlaubt mir nur "ein Sachverständiger", obwohl "einen" erlaubt ist, was mir Jan Schreiber mitgeteilt hat.

Grüße Dallun511

**Comment by janschreiber** [comment]
Not a false alarm.
