### ISSUE TITLE
Rejected Word: LANCOM / Abgelehntes Wort: LANCOM

### ISSUE THREAD

**Issue by EaryTide** [languagetool-org/languagetool#10293]
Das Wort bzw. der Name LANCOM der zu einer Firma für Netzwerkkomponenten gehört, wurde abgelehnt. Da es sich um einen Namen handelt und im Netzwerkbereich dieser nicht unbekannt ist, würde ich diesen bitte ins Wörterbuch mit aufnehmen lassen.

Mit Freundlichen Grüßen
EaryTide
---

The word or the name LANCOM
 which belongs to a company for network components, was rejected. Since 
name and it is not unknown in the network sector, I would like to have it 
unknown in the networking sector, I would like to have it included in the dictionary.

with best Regards
EaryTide

**Comment by Luisa-LT** [comment]
Danke @EaryTide, wir haben es hinzugefügt. Die Änderungen werden nach dem nächsten Update live sein :-)
