### ISSUE TITLE
[de] Wrong correction with rule ARTNOMSIN_SUBNOMSIN_VERPLU 

### ISSUE THREAD

**Issue by SolidTux** [languagetool-org/languagetool#10295]
When checking a sentence like

```
Tom und der Hund spielen zusammen.
```

the sentence is incorrectly corrected to

```
Tom und der Hund spielt zusammen.
```

**Comment by Luisa-LT** [comment]
Hi @SolidTux, thank you for pointing this out. It should be solved after the next premium update.

**Comment by SolidTux** [comment]
Thanks for fixing it that fast! Just out of curiosity: Where is the logic for this located?

**Comment by Luisa-LT** [comment]
It's a premium rule, that's why it is not accessible from the OS code.

**Comment by SolidTux** [comment]
Ah, that makes sense.
