### ISSUE TITLE
[DE] Fehlalarlm mit widersprüchigen Fehlerbeschreibung

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#10299]
Moin liebes LanguageTool-Team

Aber ich bekomme ein neues Versteck und muss mir **kein** neues suchen.
LT: "Meinten Sie „kann“?"

"Kein neues" bezieht sich auf den Hauptsatz auf den Punkt "ein neues Versteck". Aus diesem Grund ergibt "kann" keinen Sinn, weil zudem die Verben bereits vorhanden sind.

Aber ich bekomme ein neues Versteck und muss mir **kann** neues suchen.
LT: "Dieses Verb sieht falsch platziert oder unnötig aus. Überlegen Sie, es zu löschen."

Sollte man diesen Schritt folgen, ergibt der Satzteil nach dem "und" keinen Sinn mehr. "... und muss mir neues suchen."

Diesen Fehler bitte beheben.

Grüße Dallun511

**Comment by Luisa-LT** [comment]
@MasterDallun511, danke für den Hinweis. Das sollte nach dem nächsten Update behoben sein.
