### ISSUE TITLE
Can't update in LibreOffice 

### ISSUE THREAD

**Issue by sojusnik** [languagetool-org/languagetool#1032]
On LibreOffice 6.0.4.2 under Ubuntu 18.04 with LanguageTool 4.1 [this](https://i.imgur.com/hn026PG.png) is shown in the Extension Manager window when updating:

> Es ist ein Fehler aufgetreten:
> Premature end of data in tag html line 2
> Line: 1233
> Column: 1

It works nevertheless, but with each new version of LanguageTool I have to delete the extension and add the new one manually, loosing all my settings.

**Comment by danielnaber** [comment]
http://www.languagetool.org/languagetool.update.xml was missing on our server, this might have been the reason. I have re-added it now.

**Comment by sojusnik** [comment]
Yeah, works fine now, thanks!
