### ISSUE TITLE
[DE] Fehlalarm mit "das ist heiliges Gebiet" im Nebensatz

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#10328]
Liebes LanguageTool-Team

Aus diesem Grund sind hier sehr viele Mitglieder von den verschiedenen **Mafias** vertreten, denn für die Mafia ist **das heiliges Gebiet**.
LT: "Diese Adjektivform sieht falsch aus. Überlegen Sie, sie zu ersetzen."
Das fungiert in diesem Fall nicht als Artikel, sondern als ein "es oder dies" gewertet werden kann, (den Fachbegriff weiß ich gerade nicht), weswegen "heiliges Gebiet" richtig ist.

Zu "Mafias", Token sind vorhanden, aber das Wörterbuch kennt das Wort nicht. Das könnte ich hinzufügen oder ihr macht das.

Grüße Dallun511

**Comment by MasterDallun511** [comment]
#10329 wird Mafias ins Wörterbuch hinzugefügt.

**Comment by Luisa-LT** [comment]
Hi @MasterDallun511, danke für das Hinzufügen des Wortes zu spelling.txt; ich habe den PR gemergt. Wir werden uns um den oben beschriebenen Fehlalarm kümmern. 👍

**Comment by Luisa-LT** [comment]
Update: Fehlalarm sollte nach dem nächsten Update verschwunden sein :-)
