### ISSUE TITLE
[RU] Two dots with punctuation marks.

### ISSUE THREAD

**Issue by Disinterpreter** [languagetool-org/languagetool#1033]
Current rules (i tested on site languagetool) check two dots incorrect.

In case on example !.. ?.. - correct grammar. see: 
http://new.gramota.ru/spravka/buro/search-answer?s=%D0%B4%D0%B2%D0%B5+%D1%82%D0%BE%D1%87%D0%BA%D0%B8 qustion number 294634
Examples: 
![default](https://user-images.githubusercontent.com/3816155/41818942-f3059252-77c0-11e8-95df-e02b98c5feb2.png)

**Comment by yakovru** [comment]
Now I'm looking for a way to fix it.

**Comment by yakovru** [comment]
Fixed.

**Comment by Katzen-Gott** [comment]
It still says there's an error sometimes. I caught it once at the end of a line (in Google Docs, but it's gone now), but it's stably reproducible when in quotes.
<img width="464" alt="Screenshot 2020-02-12 at 02 50 27" src="https://user-images.githubusercontent.com/683504/74290280-712a4f80-4d42-11ea-929d-d9ebbfabb32a.png">
