### ISSUE TITLE
Use later version of lucene to address security issue

### ISSUE THREAD

**Issue by harrisa-opentext** [languagetool-org/languagetool#10345]
The LanguageTool pom.xml file is using Lucene version 5.5.5.  This version is from 2017 and has a security issue [PRISMA-2021-0081](https://issues.apache.org/jira/browse/LUCENE-9981).  This issue is fixed in version 8.10.0, but the latest available version is 9.10.0.  I'd like to request that this version be changed to at least 8.10.0.

**Comment by SteVio89** [comment]
Lucene is only used in some classes for developers (see module languagetool-dev) to create the ngram files that you can optionally enable.

I think the [vulnerability](https://issues.apache.org/jira/browse/LUCENE-9981) is not relevant for LanguageTool.

Updating Lucene to the latest version has actually not a high priority, as this probably needs some code changes, besides increasing the version number in the pom.xml file.

You are welcome to open a PullRequest for this change.
