### ISSUE TITLE
[en] False Positive CD_NN

### ISSUE THREAD

**Issue by W1zzardTPU** [languagetool-org/languagetool#10353]
The ATX spec allows a ripple of up to 120 mV for the +12 V rail and 50 mV for the minor rails.

Possible agreement error. The noun ‘rail’ seems to be countable.

This is correct within the technical jargon, but I see why it gets flagged.

If needed, I can dig up share text samples from our power supply related content

**Comment by tiff** [comment]
This has recently been fixed
