### ISSUE TITLE
[DE] LanguageTool "Fehlalarme Relativsätze"

### ISSUE THREAD

**Issue by Black56651** [languagetool-org/languagetool#1035]
**Moin liebes LanguageTool-Team**
 
**Hier werden nur "Fehlalarme für Relativsätze" regitriert!**
****
- [x] **Fehler R1**
Es kam eine Polizistin in den Verhörraum, **die** Nozomi aufforderte, die Wahrheit zu sagen, weil sie erst dann verhandeln können.
**LanguageTool-Fehlermeldung:** "Fehlende Übereintstimmung zwischen Substantiv und Relativpronommen. Meinten Sie "der"?"
**Begründung:** "Die" bezieht sich auf die Polizistin.
****
- [x] **Fehler R2**
Erik ließ Leonie los und sagte: „Ich habe die Beziehung beendet, weil du nicht das bist, was ich suche. Du kannst so viel trainieren, wie du willst, aber ich suche nicht ein Mädchen, **die** eine Kampfkraft von Millionen hat, sondern ein Mädchen, dass so ist, wie es ist.“
**LanguageTool-Fehlermeldung:** "Fehlende Übereintstimmung zwischen Substantiv und Relativpronommen. Meinten Sie "das"?"
**Begründung:** "Die" bezieht sich auf ein Mädchen.
****
- [x] **Fehler R3**
Aber welche Fragen **waren** in der Umfrage vertreten?
**LanguageTool-Fehlermeldung:** “Ein Komma hinzufügen (Relativsatz)”
**Begründung:** Hinter waren muss kein Komma.
****
- [x] **Fehler R4**
Herr Grey sagte: „Ich erwartet am Freitag Sie und ihre Schwester, **welche ist** Ihnen überlassen.“
**LanguageTool-Fehlermeldung:** “Ein Komma hinter "ist" einfügen (Relativsatz)”
****

**Letzte Aktulisierung: 27.03.2020**
**Zuletzt alle Fehler überprüft: 27.03.2020**

**Mit freundlichen Grüßen Euer Black5661**

**Comment by Dallun511** [comment]
**Fehler R5**

Herr Grey sagte: „Ich erwartet am Freitag Sie und ihre Schwester, **welche ist** Ihnen überlassen.“

“Ein Komma hinter "ist" einfügen (Relativsatz)”

**Comment by Dallun511** [comment]
**Fehler R6a**

In der Mitte des zentralen Parks von Goldcity trafen sie den Vater mit mehren Geldkoffern, die das Lösegeld **waren**.

LanguageTool: "Bitte prüfen, ob hier "war" stehen sollte."

**Fehler R6b**

In der Mitte des zentralen Parks von Goldcity trafen sie den Vater mit mehren Geldkoffern, welche das Lösegeld **waren**.


LanguageTool: "Bitte prüfen, ob hier "war" stehen sollte."

In beiden Fällen bezieht sich die/welche auf die Geldkoffer, welche Mehrzahl sind, also ist "waren" richtig.

**Comment by Dallun511** [comment]
**Der Zwischenbericht für "Fehlalarme Relativsätze"**

**Fehler R1**

Es kam eine Polizistin in den Verhörraum, **die** Nozomi aufforderte, die Wahrheit zu sagen, weil sie erst dann verhandeln können.

LanguageTool sagt: "Fehlende Übereintstimmung zwischen Substantiv und Relativpronommen. Meinten Sie "der"?"

"Die" bezieht sich auf die Polizistin.


**Fehler R2**

Lucia betrat dann das Büro vom Herrn Zero und setzte sich auf dem freien Stuhl hin. Vinzenz sagte nichts, weil er keinen Fehler begehen wollte, den seiner Mandantin schaden könnten und ließ Herrn Zero das Wort, **der** zu Lucia sagte, dass sie auf ihren Vater warten, der auf dem Weg ist und dann gemeinsam beginnen werden.

LanguageTool sagt: "Fehlende Übereintstimmung zwischen Substantiv und Relativpronommen. Meinten Sie "das"?"

"Der" bezieht sich auf "der Herr Zero".


~~**Fehler R3**~~

~~Erik ließ Leonie los und sagte: „Ich habe die Beziehung beendet, weil du nicht das bist, was ich suche. Du kannst so viel trainieren, wie du willst, aber ich suche nicht ein Mädchen, **die** eine Kampfkraft von Millionen hat, sondern ein Mädchen, dass so ist, wie es ist.“~~

~~"Die" bezieht sich auf ein Mädchen.~~

~~**Fehler R4**~~

~~Aber welche Fragen **waren** in der Umfrage vertreten?~~

~~“Ein Komma hinzufügen (Relativsatz)”~~

~~Hinter waren muss kein Komma.~~

**Fehler R5**

Herr Grey sagte: „Ich erwartet am Freitag Sie und ihre Schwester, **welche ist** Ihnen überlassen.“

“Ein Komma hinter "ist" einfügen (Relativsatz)”

**Fehler R6a**

In der Mitte des zentralen Parks von Goldcity trafen sie den Vater mit mehren Geldkoffern, die das Lösegeld **waren**.

LanguageTool: "Bitte prüfen, ob hier "war" stehen sollte."

**Fehler R6b**

In der Mitte des zentralen Parks von Goldcity trafen sie den Vater mit mehren Geldkoffern, welche das Lösegeld **waren**.

**Comment by Dallun511** [comment]
Fehler R7

Sie teilten sich auf und holten Lucia aus dem Fahrzeug, **die** einen Schock hatte und gar nicht mehr ansprechbar war.

LanguageTool sagt: "Fehlende Übereintstimmung zwischen Substantiv und Relativpronommen. Meinten Sie "das"?"

"die" bezieht sich auf "Lucia", was eine "die" ist.

**Comment by Dallun511** [comment]
**Der Zwischenbericht für "Fehlalarme Relativsätze"**

**Fehler R1**

Es kam eine Polizistin in den Verhörraum, **die** Nozomi aufforderte, die Wahrheit zu sagen, weil sie erst dann verhandeln können.

LanguageTool sagt: "Fehlende Übereintstimmung zwischen Substantiv und Relativpronommen. Meinten Sie "der"?"

"Die" bezieht sich auf die Polizistin.


**Fehler R2**

Lucia betrat dann das Büro vom Herrn Zero und setzte sich auf dem freien Stuhl hin. Vinzenz sagte nichts, weil er keinen Fehler begehen wollte, den seiner Mandantin schaden könnten und ließ Herrn Zero das Wort, **der** zu Lucia sagte, dass sie auf ihren Vater warten, der auf dem Weg ist und dann gemeinsam beginnen werden.

LanguageTool sagt: "Fehlende Übereintstimmung zwischen Substantiv und Relativpronommen. Meinten Sie "das"?"

"Der" bezieht sich auf "der Herr Zero".


~~**Fehler R3**~~

~~Erik ließ Leonie los und sagte: „Ich habe die Beziehung beendet, weil du nicht das bist, was ich suche. Du kannst so viel trainieren, wie du willst, aber ich suche nicht ein Mädchen, **die** eine Kampfkraft von Millionen hat, sondern ein Mädchen, dass so ist, wie es ist.“~~

~~"Die" bezieht sich auf ein Mädchen.~~

~~**Fehler R4**~~

~~Aber welche Fragen **waren** in der Umfrage vertreten?~~

~~“Ein Komma hinzufügen (Relativsatz)”~~

~~Hinter waren muss kein Komma.~~

**Fehler R5**

Herr Grey sagte: „Ich erwartet am Freitag Sie und ihre Schwester, **welche ist** Ihnen überlassen.“

“Ein Komma hinter "ist" einfügen (Relativsatz)”

**Fehler R6a**

In der Mitte des zentralen Parks von Goldcity trafen sie den Vater mit mehren Geldkoffern, die das Lösegeld **waren**.

LanguageTool: "Bitte prüfen, ob hier "war" stehen sollte."

**Fehler R6b**

In der Mitte des zentralen Parks von Goldcity trafen sie den Vater mit mehren Geldkoffern, welche das Lösegeld **waren**.

LanguageTool: "Bitte prüfen, ob hier "war" stehen sollte."

In beiden Fällen bezieht sich die/welche auf die Geldkoffer, welche Mehrzahl sind, also ist "waren" richtig.

**Fehler R7**

Sie teilten sich auf und holten Lucia aus dem Fahrzeug, **die** einen Schock hatte und gar nicht mehr ansprechbar war.

LanguageTool sagt: "Fehlende Übereintstimmung zwischen Substantiv und Relativpronommen. Meinten Sie "das"?"

"die" bezieht sich auf "Lucia", was eine "die" ist.

**Letzte Prüfung 20.11.2018 15:30 Uhr**
