### ISSUE TITLE
[en] False Positive UPPERCASE_SENTENCE_START

### ISSUE THREAD

**Issue by W1zzardTPU** [languagetool-org/languagetool#10351]
The product's MSRP is US$199.99 excl. taxes.

"This sentence does not start with an uppercase letter" on "taxes". 

Writing "... etc. taxes" isn't flagged, so I think UPPERCASE_SENTENCE_START is missing an exclusion rule for "excl."

**Comment by danielnaber** [comment]
Thanks, should be fixed with the next update
