### ISSUE TITLE
[en] false positive ADJECTIVE_ADVERB

### ISSUE THREAD

**Issue by W1zzardTPU** [languagetool-org/languagetool#10367]
`The biggest issue is its tendency to succumb to unintentional double-clicking.`

The word “unintentional” is an adjective and doesn’t fit in this context. Did you mean the adverb “unintentionally”?

**Comment by tiff** [comment]
Thanks. Fixed as part of https://github.com/languagetool-org/languagetool/commit/f93ffa0838cf92ae8df4a395307dc86dfd033672
