### ISSUE TITLE
Can this project achieve a similar inspection effect as unregistered use on the official homepage?

### ISSUE THREAD

**Issue by lpcy** [languagetool-org/languagetool#10361]
I installed a self hosted service through Docker and accessed it using the official browser plugin. When switching to self hosted services, there are very few grammar errors that can be checked, but these errors can be detected on the official website homepage. Is there an issue with my deployment or is it not supported by the project itself?

**Comment by danielnaber** [comment]
The AI-based rules are missing for a local installation (and they are not part of the Open Source version).
