### ISSUE TITLE
academic abbreviation

### ISSUE THREAD

**Issue by GuShaocheng** [languagetool-org/languagetool#10373]
Hi,

I run Languagetool in a docker.  I found it treats the following words (bold parts) as wrong spelling.

The article studies cyt. **c** in S. **cerevisiae**.

In fact, "cyt. c" and " S. cerevisiae" are correct words. I have many other abbreviation. May I ask a way to deal with this issue.
Thank you very much!

**Comment by evan-defran-lt** [comment]
Hi @GuShaocheng, we will soon recognize some 800 Linnaean taxonomic abbreviations: https://github.com/languagetool-org/languagetool/commit/76580be18140f14d1eaf368e87078e36742116fa

I will also go ahead and add `cyt. c` to our English dictionary.

You can also add individual words to your personal dictionary. Simply click on the dictionary icon in the upper-righthand corner of the error card when the spelling suggestion pops up. This will add the word to your personal dictionary. 
<img width="332" alt="Screenshot 2024-03-19 at 15 15 32" src="https://github.com/languagetool-org/languagetool/assets/112640985/495a31ab-9c5c-4df7-b2e2-7091bd7cdf28">

We are always looking to improve our dictionaries, so if you have any suggestions, please let us know.
