### ISSUE TITLE
Update the rule for "Concordancia en Determinante + nombre" [Spanish]

### ISSUE THREAD

**Issue by alxmz2** [languagetool-org/languagetool#1037]
The rule detects

La sillas /  Las silla

but it does not detect some words like

La cosas / La casas

**Comment by TiagoSantos81** [comment]
Very difficult to disambiguate. 
Quiero que la cosas (la blusa). (coser verb)
Si besas mi hija, la casas. (casar verb)
I would close this issue because it might not be solvable.

**Comment by alxmz2** [comment]
Por qué si funciona con "La sillas"? Digamos que no se analiza si son
verbos, pero con sustantivos debería funcionar al menos...

**Comment by jaumeortola** [comment]
Now, the error in "la cosas" can be detected in most contexts considering that the verb is subjunctive.  "Las casa" can be detected in some contexts, for example after a preposition (`en las casa`) or with a verb (`Las casa son blancas`).
