### ISSUE TITLE
Not able to install Languagetools to LibreOffice

### ISSUE THREAD

**Issue by Mannshoch** [languagetool-org/languagetool#1038]
LibreOffice Version: 6.0.3.2
Build-ID: 1:6.0.3-0ubuntu1
Languagetools Version: https://extensions.libreoffice.org/extensions/languagetool/4.2

```(com.sun.star.uno.RuntimeException) { { Message = "[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.NoClassDefFoundError: com/sun/star/task/XJobExecutor\X000ajava stack trace:\X000ajava.lang.NoClassDefFoundError: com/sun/star/task/XJobExecutor\X000a\X0009at java.base/java.lang.ClassLoader.defineClass1(Native Method)\X000a\X0009at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)\X000a\X0009at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)\X000a\X0009at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)\X000a\X0009at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)\X000a\X0009at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)\X000a\X0009at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)\X000a\X0009at java.base/java.security.AccessController.doPrivileged(Native Method)\X000a\X0009at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:553)\X000a\X0009at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:890)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)\X000a\X0009at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:53)\X000a\X0009at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:376)\X000aCaused by: java.lang.ClassNotFoundException: com.sun.star.task.XJobExecutor\X000a\X0009at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)\X000a\X0009... 15 more\X000a", Context = (com.sun.star.uno.XInterface) @0 } }```

**Comment by Mannshoch** [comment]
I detected that Language tool had installed and also work, but LibreOffice do not show Language tool in it's extension manager. 

I looked into the link. Interesting list of errors, much work to do for Language tools. But I'm not sure if one of these Error fits into this one.

**Comment by dpelle** [comment]
@danielnaber wrote:
> Have you checked https://languagetool.org/issues?

In above page https://languagetool.org/issues the link which says "see screenshot" points to https://languagetool.org/images/class_not_found.png  which does not exist anymore.

**Comment by dpelle** [comment]
Installing this package should fix this issue of @Mannshoch:
```
$ sudo apt-get install libreoffice-java-common
```

**Comment by Mannshoch** [comment]
Yes it seems that this package is missing. 

If it's not needed for Running it in LibreOffice, Is this an Error of LibreOffice that it need this package only for being able to view it correct?

**Comment by danielnaber** [comment]
> In above page https://languagetool.org/issues the link which says "see screenshot" points to https://languagetool.org/images/class_not_found.png which does not exist anymore.

This has now been fixed.

**Comment by danielnaber** [comment]
I understand this was fixed by installing the missing package, so I'll close this issue.
