### ISSUE TITLE
German grammar errors are not detected in the self hosted version.

### ISSUE THREAD

**Issue by Kai-Piontek** [languagetool-org/languagetool#10395]
I am running the selfhosted version of language tool and it does not detect the following errors:

Correct sentence:
Es geht darum, anders zu sein.  

Not detected wrong errors:
- Es gehen darum, anders zu sein.  
- Es geht darum, anders zu ist.  

I am a bit confused as on the languagetool.org website the errors are detected, but in the self hosted version they are not detected. 
I also cross checked with the tinymce demo here: https://knowzero.github.io/tinymce4-languagetool/TinyMCE5/demo.html

The errors are also not detected.

Am I doing something wrong? How could I fix this?

Best regards,
Kai

**Comment by danielnaber** [comment]
> I am a bit confused as on the languagetool.org website the errors are detected, but in the self hosted version they are not detected.

The self-hosted version doesn't have the AI-based rules that are active on languagetool.org.

**Comment by Kai-Piontek** [comment]
Thank you for clarifying!
