### ISSUE TITLE
[EN] False positive EN_UNPAIRED_BRACKETS

### ISSUE THREAD

**Issue by pzogel** [languagetool-org/languagetool#10409]
>After enabling "Advanced Debounce Settings," a host of additional options becomes available, allowing one to modify debounce before and after the click, both for press and release, and during lift-off.

Unpaired symbol: '"' seems to be missing.

In AE, the comma is put inside the quotation marks, resulting in the tool failing to recognize that the closing quote is indeed present.

**Comment by evan-defran-lt** [comment]
Hi @pzogel, I'm not able to reproduce the FP that you're seeing. 

Could you let me know where you are using LanguageTool? (e.g., in the browser, Chrome extension, etc.)

<img width="1293" alt="Screenshot 2024-03-18 at 15 30 37" src="https://github.com/languagetool-org/languagetool/assets/112640985/ee8c42f7-3469-4750-b70a-7f1405ad3a67">

**Comment by pzogel** [comment]
Been able to confirm that it's unrelated to LanguageTool.
