### ISSUE TITLE
LanguageTool does not recognize the latex command `\newpage`, and in particular, the first command in the document get recognized as a typo. This occurs in Overleaf. 

### ISSUE THREAD

**Issue by AKissMail** [languagetool-org/languagetool#10410]
LanguageTool does not recognize the latex command `\newpage`, and in particular, the first command in the document get recognized as a typo. This occurs in Overleaf. 

How to reproduce it: 

What I did: 
On macOS Sonoma and the latest Firefox with the LT plugin, I opened an Overleaf project and wrote my thesis in English, with some German comments here and there. I have set the default of the document to English. I am working on a file that is a pat of the document and get imported in a place in the document. 

Expected behavior: 
I see suggestions for my typos, and my German nodes that got not recognizes as a word. I didn't get any suggestion for the syntax. 

Observed behavior:   
The first command in a document get not recognizes as syntax and I get a suggestion for the command `\newpage` to `new page`.   

The Input out of my document: 
\newpage ← Suggestion for ´new page´
\subsection{Iteration 2}
\subsubsection{Status of the Development}
% Crazy smart research. 
\begin{enumerate}
\item Hier die Liste xyz einfügen. ← My German nodes.
\end{enumerate}

**Comment by evan-defran-lt** [comment]
Hi @AKissMail, I'm unfortunately not able to reproduce the behavior that you're seeing. Could you share a screenshot?

**Comment by AKissMail** [comment]
Sure: 
<img width="602" alt="Screenshot 2024-03-19 at 15 46 33" src="https://github.com/languagetool-org/languagetool/assets/69756846/cdab73b3-c097-4961-aacb-66cb1fe36b93">

**Comment by tiff** [comment]
Hey, can you check if this still happens with the version of our Firefox add-on that we released yesterday?

**Comment by AKissMail** [comment]
Just check, looks fine! Fantastic job!
