### ISSUE TITLE
A bug in parsing dates in `UkrainianWordTokenizer`

### ISSUE THREAD

**Issue by ddashenkov** [languagetool-org/languagetool#10462]
I have discovered a bug in the [`UkrainianWordTokenizer`](https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/uk/src/main/java/org/languagetool/tokenizers/uk/UkrainianWordTokenizer.java) class.

I use LanguageTool of the version 6.4

Here is a little test to replicate the error:
```java
@Test
void test() {
    var tokenizer = new UkrainianWordTokenizer();
    var tokens = tokenizer.tokenize("1814.03.09");
    Assertions.assertEquals("1814.03.09", tokens.get(0));
}
```
I'm expecting the test to pass. Instead, I get the following error: `expected: <1814.03.09> but was: <..>`, i.e. the token contains no digits, just the two dots.

This behaviour is not limited to actual dates and may manifest in strings where a substring looks like a date, for example "12345.00.01"

After a little bit of digging, I've discovered that the `UkrainianWordTokenizer` attempts to match replace dates with a regular expression. This issue is that the regex has 9 groups, 3 per each alternative date format (`dd.mm.yyyy`, `yyyy.mm.dd`, and `yyyy-mm-dd`). However, the replacement pattern only uses `$1`, `$2`, and `$3`. Thus, the second and the third date formats are never replaced correctly.

if you (the maintainers) wish, I could make a PR later to fix this issue, or I'll just leave it up to you.

**Comment by danielnaber** [comment]
@arysin

**Comment by arysin** [comment]
I can reproduce it, will take a look.

**Comment by arysin** [comment]
@ddashenkov  I've pushed the fix, thanks for the report!
Somehow that date handling was not really necessary, I suspect some other rules took over that case with time.
Please let me know if you still see a problem.
