### ISSUE TITLE
A question about rule "SUPERLATIVE_THAN"

### ISSUE THREAD

**Issue by yanshengjia** [languagetool-org/languagetool#1048]
When I used languagetool to check a sentence including "superior than", it gave me a message ""message": "Use \"(superior)\" to make a comparison with this adjective.".

I am a little bit confused, why "(superior)"?

Besides, "superior than" doesn't seem to include grammar errors.

Here is my full json result:

```
{
    "message": "Use \"(superior)\" to make a comparison with this adjective.",
    "shortMessage": "",
    "replacements": [
        {
            "value": "(superior)"
        }
    ],
    "offset": 444,
    "length": 8,
    "context": {
        "text": "...dition to, some people think English is superior than Chinese. In me opinion, though Eng...",
        "offset": 43,
        "length": 8
    },
    "sentence": "In addition to, some people think English is superior than Chinese.",
    "rule": {
        "id": "SUPERLATIVE_THAN",
        "subId": "1",
        "description": "SUPERLATIVE + THAN, e.g. worst (worse) than",
        "issueType": "grammar",
        "category": {
            "id": "GRAMMAR",
            "name": "Grammar"
        }
    }
}

**Comment by TiagoSantos81** [comment]
Superior is a special adjective that does not have a comparative (it is a comparative in itself).
However the sentence is not grammatically correct. It should be 'superior to'.
https://forum.wordreference.com/threads/far-more-superior-to-vs-than.2866500/
Leave this open and a rule will be created for these situations.

**Comment by yanshengjia** [comment]
Thx.

So why the replacements is "(superior)" with brackets？Is this a bug?

**Comment by TiagoSantos81** [comment]
There is arule that tests JJ (normal adjective) + THAN
"He is superior than you."
```
He[he/PRP,B-NP-singular\|E-NP-singular] |  
-- | --
is[be/VBZ,B-VP] |  
superior[superior/JJ, superior/NN,B-ADJP] |  
than[than/IN,B-PP] |  
you[you/PRP,B-NP-singular\|E-NP-singular] |  
.[./., </S>,O]


```

**Comment by yanshengjia** [comment]
Yeah, I know "than" should be replaced with "to".

My question is ... why "superior" is in **parentheses**?

Here is the screenshot from my demo.
![image](https://user-images.githubusercontent.com/8682800/42691139-66b1c8de-86d9-11e8-9948-f2bd09c6d779.png)

**Comment by TiagoSantos81** [comment]
> Besides, "superior than" doesn't seem to include grammar errors.

If you say so...

> Yeah, I know "than" should be replaced with "to".

Regarding the parenthesis, it is probably answered in other places as well, but this should suffice:
https://forum.languagetool.org/t/strange-false-positive-owner-of/2979/3
https://github.com/languagetool-org/languagetool/issues/820

**Comment by yanshengjia** [comment]
Thx!
