### ISSUE TITLE
Not useful Error message while Installing Languagetools appear

### ISSUE THREAD

**Issue by Mannshoch** [languagetool-org/languagetool#1052]
Based on Discussion on #1038 I created here a new Issue to get ride of this error message

`(com.sun.star.uno.RuntimeException) { { Message = "[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.NoClassDefFoundError: com/sun/star/task/XJobExecutor\X000ajava stack trace:\X000ajava.lang.NoClassDefFoundError: com/sun/star/task/XJobExecutor\X000a\X0009at java.base/java.lang.ClassLoader.defineClass1(Native Method)\X000a\X0009at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)\X000a\X0009at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)\X000a\X0009at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)\X000a\X0009at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)\X000a\X0009at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)\X000a\X0009at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)\X000a\X0009at java.base/java.security.AccessController.doPrivileged(Native Method)\X000a\X0009at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:553)\X000a\X0009at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:890)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)\X000a\X0009at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:53)\X000a\X0009at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:376)\X000aCaused by: java.lang.ClassNotFoundException: com.sun.star.task.XJobExecutor\X000a\X0009at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)\X000a\X0009at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)\X000a\X0009... 15 more\X000a", Context = (com.sun.star.uno.XInterface) @0 } }`

**Comment by danielnaber** [comment]
I'm not sure - is the issue that you still get this error or do you suggest to simply improve the error message?

**Comment by Mannshoch** [comment]
Simply improve the Error message. As you could see in #1038 I was able to install Language and use the Languagetool addon even the package was missing. But It was not appearing correct in the Extension manager.
I would prefer to find a solution without this package, why should I install this, only to get it appear correct in extension manager? Or is there more behind this than I'm able to see?
In any way, this error message is not an error message for a normal user. It's a Message for a Developer.

Do as you wish, but prevent somehow to show normal user this kind of error.

**Comment by danielnaber** [comment]
The error doesn't come from LanguageTool but from LibreOffice. I'm quite sure LT hasn't even started when this error appears, so there's nothing we can do about it. You might want to report this at LibreOffice.

**Comment by Mannshoch** [comment]
Oh good. I followed the Advice from https://github.com/LibreOffice/core to https://gerrit.libreoffice.org website is a kind of shit software. I'm looking around since a while and not get a clue how to report a bug there.

**Comment by TiagoSantos81** [comment]
@Mannshoch 
You can report bugs on LibreOffice on https://bugs.documentfoundation.org/.
"QA assurance volunteers" tend to disregard, deny and close bug reports instead of following the bug reproduction procedure, nor fixing them, but you might have a better experience than me.
