### ISSUE TITLE
ExceptionInInitializerError on version 6.4

### ISSUE THREAD

**Issue by binarynoise** [languagetool-org/languagetool#10555]
after uptating my server to 6.4, languagetool now crashes on startup.

```
[languagetool@languagetool ~]$ languagetool --http -p 8000 --public --allow-origin "*" --config /home/languagetool/languagetool.conf
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.languagetool.JLanguageTool.<clinit>(JLanguageTool.java:84)
	at org.languagetool.Premium.isPremiumVersion(Premium.java:64)
	at org.languagetool.server.DatabaseAccess.init(DatabaseAccess.java:57)
	at org.languagetool.server.HTTPServer.main(HTTPServer.java:171)
Caused by: java.lang.NullPointerException: text
	at java.util.Objects.requireNonNull(Objects.java:228)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1848)
	at java.time.OffsetDateTime.parse(OffsetDateTime.java:402)
	at org.languagetool.LtBuildInfo.<init>(LtBuildInfo.java:64)
	at org.languagetool.LtBuildInfo.<clinit>(LtBuildInfo.java:37)
	... 4 more
[languagetool@languagetool ~]$ cat languagetool.conf
languageModel=/home/languagetool/ngram
fasttextModel=/home/languagetool/lid.176.bin
fasttextBinary=/usr/bin/fasttext
pipelineCaching=true
pipelinePrewarming=true
maxPipelinePoolSize=500
cacheSize=2
```

Downgrading to 6.3.a does not crash.
I'm using the binary provided by the arch linux package

**Comment by danielnaber** [comment]
I cannot reproduce that when starting the JAR from the LT 6.4 ZIP files we provide. It looks like a packaging issue. Do you know what the actual commend is that gets executed by `languagetool`?

**Comment by binarynoise** [comment]
`languagetool` looks like a shell script to build the java command and eventually runs 
```
/bin/java
-cp /usr/share/languagetool:/usr/share/java/languagetool/languagetool-commandline.jar:/usr/share/java/languagetool/languagetool-server.jar:/usr/share/java/languagetool/languagetool.jar
org.languagetool.server.HTTPServer
-p 8000 --public --allow-origin * --config /home/languagetool/languagetool.conf
```
(wrapped for readability)

**Comment by binarynoise** [comment]
here's the source for the wrapper:
https://gitlab.archlinux.org/archlinux/packaging/packages/languagetool/-/blob/main/languagetool.sh

I'll try to build the package myself and see how that goes

**Comment by danielnaber** [comment]
Does it make a difference if you run the command from the directory that contains `languagetool-commandline.jar`? Or from `/usr/share/languagetool`?

**Comment by binarynoise** [comment]
It does not seem to make a difference from where I run the full command.

**Comment by binarynoise** [comment]
looking at the code, it looks like git.properties isn't found

**Comment by binarynoise** [comment]
the file is where it should be, so it's probably a problem with invoking the jars

**Comment by binarynoise** [comment]
It's definitely some kind of packaging thing.
Downloading the release zip, extracting it and running the command [as in the docs](https://dev.languagetool.org/http-server) successfully starts the server.

**Comment by binarynoise** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/languagetool/-/issues/2

**Comment by binarynoise** [comment]
I just found the reason.
There was a stray, empty `git-premium.properties` in /usr/share/languagetool, getting rid of that solves the issue.
