### ISSUE TITLE
English word Enablement shown as error

### ISSUE THREAD

**Issue by kapilgupta77** [languagetool-org/languagetool#1055]
Hi,

The English word "Enablement" is not passed by LT though it is a legitimate word in English language.

Thanks

Kapil

**Comment by marcoagpinto** [comment]
@kapilgupta77 

It is available in the GB speller which is maintained by me.

US+CA+AU by Kevin Atkinson don't have it.

You can open the wordlists yourself to check:
https://github.com/marcoagpinto/aoo-mozilla-en-dict

Please report the word as missing in Kevin's GitHub.

**Comment by MikeUnwalla** [comment]
@kapilgupta77 wrote "it is a legitimate word in English language." The word is not in Merriam Webster's (American) dictionary: https://www.merriam-webster.com/dictionary/enablement

**Comment by kapilgupta77** [comment]
Sorry @MikeUnwalla for not checking the Merriam Webster's dictionary before reporting it. Actually I got confused with MS Word as it did not mark the word as incorrect though my proofing language is set to American English.

**Comment by MikeUnwalla** [comment]
@kapilgupta77 , I don't know certainly that the word is not standard AmE. Possibly, it is. I just looked on https://corpus.byu.edu/coca/ and found 43 instances in American texts.

**Comment by marcoagpinto** [comment]
Well, it exists in English GB: https://en.oxforddictionaries.com/definition/enablement

**Comment by MikeUnwalla** [comment]
@marcoagpinto , sorry. I did not mean to suggest that the word is not BrE.
