### ISSUE TITLE
What's wrong with "der Ergebnisse"?

### ISSUE THREAD

**Issue by orschiro** [languagetool-org/languagetool#10558]
<img width="287" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/f6a0ad37-e2bd-48fc-880f-72126b7cd952">

**Comment by BellaDiekmann** [comment]
Hello,

**Comment by BellaDiekmann** [comment]
Hello, There is nothing wrong with the German expression "Auswertung der Ergebnisse". The selected language seems to be English, not German. That's the reason why "der" is highlighted as error.

**Comment by BellaDiekmann** [comment]
The text is too short for LanguageTool to recognize it as a different language. If you add one more word, it will be recognited. I hope that helps. 
![screenshot-language-recognition](https://github.com/languagetool-org/languagetool/assets/102814507/6bc74ca3-fac8-4391-98b8-956018dca4ee)

**Comment by orschiro** [comment]
Understood, thanks!
