### ISSUE TITLE
Missing suggestion for "werrden"

### ISSUE THREAD

**Issue by orschiro** [languagetool-org/languagetool#10557]
I expected to see the suggestion "werden" which is not present.

<img width="204" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/9e83686c-9581-4f14-95a1-9a23cef56419">

**Comment by Luisa-LT** [comment]
Thank you! Fixed here: https://github.com/languagetool-org/languagetool/commit/b5245ee5dfded948de8194318dade34bd776c127

**Comment by orschiro** [comment]
Another one.

I am missing the obvious "erkläre".

[image: image.png]

**Comment by Luisa-LT** [comment]
Sorry @orschiro, I cannot see the images. Without context, it is very difficult to determine the error. 
For example: "Mein Fragen brachte mich weiter." is perfectly grammatical (nominalized verb). Please send the images again (best would be to past them directly in the issue as a comment)  and please include also a copy of the input sentence. Thanks!

**Comment by orschiro** [comment]
Sorry! I added them in. Apparently, images don't come through if I reply over email. :)

**Comment by Luisa-LT** [comment]
Thanks for the screenshots and context.

Regarding the first one ("erkäre") I added the correction here: 

Regarding the second one: As I mentioned before, the structure itself is not ungrammatical (see e.g., "Mein Coach gibt mir Tipps und beantwortet **mein Fragen** und versteht **mein Zweifeln**.").

However, if you try it in the [LT Editor](https://languagetool.org/) you will see that both errors are already corrected there.

**Comment by orschiro** [comment]
@Luisa-LT found another issue. :)

![image](https://github.com/languagetool-org/languagetool/assets/170947/755de766-8ad0-48de-932f-b73012147ebd)

**Comment by Luisa-LT** [comment]
Also, this example is already corrected in the editor: 
![image](https://github.com/languagetool-org/languagetool/assets/115984740/9a118f77-f902-4d93-8971-202e910413d0)

**Comment by orschiro** [comment]
Could we suggest "Durchschnittsbeitrag" here?

<img width="249" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/22731e8c-c8ca-4798-a077-65f26cbb76a9">

**Comment by orschiro** [comment]
Can you please add the word "Pezziball" and plural "Pezzibälle"?

Thank you!

<img width="338" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/cf3b649f-553d-42e7-bb0b-1107c3e9fa98">

**Comment by orschiro** [comment]
<img width="229" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/a17a3428-9b62-45fc-888a-27a038a977c6">

Can we add a suggestion for "Fitnesszustand"?

**Comment by orschiro** [comment]
<img width="384" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/53a5e9d4-3491-4d14-bf2f-2bf884dba55e">

I am not sure this suggestion is correct.

"Verwenden Sie für Übungen in Rückenlage eine Yogamatte zur bequemen Ausführung und ein Kissen, um den Kopf nicht zu überstrecken"

**Comment by Luisa-LT** [comment]
> Durchschnittsbeitrag
Für den Speller ist der Abstand zwischen "Durchschnittsbeitrag" und "Durschnichtsbeitrag" zu groß (=zu viele verschiedene Fehler), um die richtige Korrektur zu liefern. Im Editor wird jedoch durch Unterstützung von KI die richtige Korrektur vorgeschlagen. 
![image](https://github.com/languagetool-org/languagetool/assets/115984740/f9ca2438-eb77-4759-b700-1d78459dce08)

Theoretisch könnte man jede beliebige Falschschreibweise eines Wortes manuell zum Wörterbuch hinzufügen, praktisch wäre das jedoch nicht effizient. Wichtig ist, dass der Speller einen Fehler erkennnt und der User darauf hingewieesen wird. Dennoch vielen Dank für die Rückmeldung 😸

**Comment by Luisa-LT** [comment]
> Can you please add the word "Pezziball" and plural "Pezzibälle"?

Hinzugefügt, danke :-)

**Comment by Luisa-LT** [comment]
> Can we add a suggestion for "Fitnesszustand"?

Gleicher Fall wie „Durschnichtsbeitrag“: https://github.com/languagetool-org/languagetool/issues/10557#issuecomment-2106904210

**Comment by Luisa-LT** [comment]
> "Verwenden Sie für Übungen in Rückenlage eine Yogamatte zur bequemen Ausführung und ein Kissen, um den Kopf nicht zu überstrecken"

Das ist tatsächlich ein Fehlalarm, werde ich weitergeben. Danke!

**Comment by orschiro** [comment]
<img width="453" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/bbc1dd02-c967-4314-aef9-6960a64d4bf4">

Können wir hier den Vorschlag "vorbereiten" anbringen? :)

Danke!

**Comment by Luisa-LT** [comment]
Ich habe es hinzugefügt 👍

**Comment by orschiro** [comment]
<img width="266" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/16598650-fa10-422f-bc30-819f265e561b">

Könnt ihr bitte "Scrollposition" aufnehmen?

Danke!

**Comment by maphjo** [comment]
Es wurde automatisch Englisch als Sprache detektiert. ;-) 
Entweder manuell umstellen oder weiterschreiben mit mehr eindeutig deutschen Wörtern. :relaxed:

**Comment by orschiro** [comment]
Aah, danke! :)

**Comment by orschiro** [comment]
<img width="470" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/b50c7132-a20c-449b-8cda-d84a207e58f5">

Können wir hier den Vorschlag "abgeschnittene" einbauen?

**Comment by Luisa-LT** [comment]
Akzeptiert man den ersten Vorschlag, wird das Genus im Editor im zweiten Schritt bereits korrekt berichtigt. Gleicher Fall wie siehe oben: „Durschnichtsbeitrag“: https://github.com/languagetool-org/languagetool/issues/10557#issuecomment-2106904210. Noch dazu handelt es sich hier eher um einen Deklinationsfehler als um einen Rechtschreibfehler. Aber danke!

**Comment by orschiro** [comment]
@Luisa-LT hier ein anderes offensichtliches Beispiel, bei dem ich einen korrekten Vorschlag erwartet hätte, danke!

<img width="260" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/2c17808f-a088-467b-be4e-50f3d2e4afbc">

**Comment by Luisa-LT** [comment]
Wird von der AI-gestützten Rechtschreibprüfung im Editor bereits gefunden und korrigiert.
![image](https://github.com/languagetool-org/languagetool/assets/115984740/ab365186-10bb-4183-b961-6e25bf758725)

**Comment by orschiro** [comment]
Warum wird das nicht als Fehler erkannt?

Das sollte eigentlich "Button" heißen.

<img width="184" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/bf394bd9-fff0-4999-9bdd-b63ef0efa84e">

**Comment by Luisa-LT** [comment]
"Butten" ist ein valides Substantiv (Akkusativ-Plural von "Butt") siehe https://www.duden.de/deklination/substantive/Butt
