### ISSUE TITLE
[en] Issue with "a" - 2024-05-04

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#10567]
Heya,

See the sentence below, LanguageTool on the browser suggests removing “a”, “good knowledge”, since “knowledge” is an uncountable noun, but after we make the correction, it suggests that “a” is missing.

“No special skills are needed for it except having a good knowledge of English and check which words appear as typos and look for them in credible sources.”

**Comment by evan-defran-lt** [comment]
Thanks for flagging! This should be fixed with the next premium deploy.
