### ISSUE TITLE
[ru] Multiple nouns and verb

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1056]
WRONG Вклад мультиполей высших порядков и большое число
параметров модели делает явное решение труднореализуемым 
CORRECT Вклад мультиполей высших порядков и большое число
параметров модели делают явное решение труднореализуемым

WRONG Мальчик с девочкой играла в шахматы
WRONG Дети и собака играла в догонялки

**Comment by yakovru** [comment]
Fixed.
