### ISSUE TITLE
Languagetool extension 6.4 makes multiFormatSave extension 1.5.6 crash.

### ISSUE THREAD

**Issue by BrianG61UK** [languagetool-org/languagetool#10579]
I am running LibreOffice 24.2.3.2 (X86_64) on Windows 11 23H2.

I have to disable Languagetool 6.4 in order to save my spreadsheet using multiFormatSave extension otherwise an error occurs:

![error1](https://github.com/languagetool-org/languagetool/assets/6334848/f32b0ef8-dae5-48a6-a51c-20a61bb12126)

multiFormatSave extension is this:
https://extensions.libreoffice.org/en/extensions/show/multisave-1
https://github.com/ertaiNL/multiformatsave

**Comment by BrianG61UK** [comment]
I'm going back to LanguageTool 6.3.1 for now, which fixes the problem.

**Comment by BrianG61UK** [comment]
> The issue is solved. Please test it with tomorrow's snapshot. You find it here: https://internal1.languagetool.org/snapshots/

It does solve the issue.
Thank you.

**Comment by birquito** [comment]
Same problem here: Windows 10 pro 64 with LO 24.2.3.2. 
![Screenshot 2024-06-13 101658](https://github.com/languagetool-org/languagetool/assets/8320462/2ef3484c-56f7-465a-aac5-2863735463e7)
LanguageTool 6.3.1 ist working properly - LanguageTool 6.4 and latest Build LanguageTool-20240613-snapshot lead to the shown error message if I save the file. I have MultiFormatSave 1.5.6 installed too.

**Comment by BrianG61UK** [comment]
Seems okay again with **LanguageTool-20240615-snapshot.oxt**.

**Comment by birquito** [comment]
Sems to be ok. Thank you for the quick solution.
