### ISSUE TITLE
[ru] Wrong prep

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1058]
WRONG Увеличение общей толщины покрытия приводит к переходу от дизайнов в одной такой группой к дизайнам с двумя группами
CORRECT Увеличение общей толщины покрытия приводит к переходу от дизайнов c одной такой группой к дизайнам с двумя группами.

WRONG Хлеб в маслом
CORRECT Хлеб c маслом

CORRECT Ручка за дверью
CORRECT Ручка под дверью
WRONG Ручка у дверью

**Comment by kostyfisik** [comment]
WRONG
Сфера со покрытием
CORRECT
Сфера с покрытием

**Comment by yakovru** [comment]
Mostly fixed via https://github.com/languagetool-org/languagetool/commit/66640aa08b9cab7075ea3146f81490570155bd26 , but  some examples need additional symbol at end like " Ручка у дверью." for triggering rule.
(bug https://github.com/languagetool-org/languagetool/issues/1205)
Not fixed: "Увеличение общей толщины покрытия приводит к переходу от дизайнов в одной такой группой к дизайнам с двумя группами."

**Comment by yakovru** [comment]
Done. Closed.
