### ISSUE TITLE
Дніпровщина

### ISSUE THREAD

**Issue by MortalEngineXXII** [languagetool-org/languagetool#10587]
Dnipropetrovska oblast has not been renamed, so the correction of «Дніпропетровщина» to «Дніпровщина» is incorrect

[languagetool-language-modules/uk/src/main/resources/org/languagetool/rules/uk/replace_renamed.txt](https://github.com/languagetool-org/languagetool/blob/a607538cbc91b28cf58ef13843d7e4f3dea3bfde/languagetool-language-modules/uk/src/main/resources/org/languagetool/rules/uk/replace_renamed.txt#L4)

**Comment by arysin** [comment]
З одного боку так, область ще в Конституції не перейменували, але «Дніпропетровщина» не є офіційною назвою, тож її вжиток не фіксується Конституцією, тож у неофіційному вжитку  ми надаємо перевагу «Дніпровщина»
