### ISSUE TITLE
LO extension: Error Message (Crash?) on saving new documents

### ISSUE THREAD

**Issue by ColeBantam** [languagetool-org/languagetool#10585]
In both, 6.4 and current 6.5 Snapshot, LT shows an error-message immediately after saving new (unsaved) documents.

![LT_Crash_Writer_DirectlyAfterSave](https://github.com/languagetool-org/languagetool/assets/34094836/3f63d66b-8a65-4d10-b34b-922f1cdd56d0)
![LT_Crash_Writer_DirectlyAfterSave_Snapshot](https://github.com/languagetool-org/languagetool/assets/34094836/5be2d16a-2536-450c-a923-795f1627c779)

Steps to reproduce:

1.) Create a new empty LibreOffice Writer document and type some text
2.) Choose "Save as", enter a filename and click "Save".
-> The error-message is displayed.

Used LibreOffice Version is 7.6.6.3 x64 on Windows 10.

**Comment by FredKruse** [comment]
The issue should be solved. Please test it with the snapshot tomorrow and close the issue.

**Comment by ColeBantam** [comment]
Hi Fred. Snapshot 6.5 (2024-06-18 19:02:03 +0200, ed5456c) seems to have fixed that bug and not introduced any new bugs. So this build looks fine so far :)

**Comment by ColeBantam** [comment]
fixed, closed

**Comment by ColeBantam** [comment]
fixed, closed
