### ISSUE TITLE
[ru] тут и здесь

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1059]
warn about тут - разговорное

**Comment by kostyfisik** [comment]
Важной характеристикой работы любой программы является её
быстродействие, тут существенное значение оказывает выбор
языка программирования.

Вариант замены "в этом случае"
Better:
Важной характеристикой работы любой программы является её
быстродействие, в этом случае существенное значение оказывает выбор
языка программирования.

**Comment by yakovru** [comment]
Правило создано, но отключено по умолчанию.

**Comment by kostyfisik** [comment]
@yakovru Спасибо!
