### ISSUE TITLE
New German suggestion(s)

### ISSUE THREAD

**Issue by orschiro** [languagetool-org/languagetool#10639]
Hi team, 

Can you please add the word "Erdenmensch"?

Thank you!

<img width="295" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/4e490e11-50bd-40e5-8f11-27d2afacd630">

**Comment by orschiro** [comment]
Why does the editor complain here? This sentence sounds grammatically completely correct.

<img width="518" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/9fb8f232-c4e9-43db-8f4a-6d8e39a1a7a6">

**Comment by orschiro** [comment]
And why does the editor suggest me to capitalise the word here?

<img width="526" alt="image" src="https://github.com/languagetool-org/languagetool/assets/170947/2758cea8-300a-4274-9304-48a7f9c2630c">

**Comment by Luisa-LT** [comment]
Hi @orschiro, thanks for bringing these false alarms to our attention. We will implement the necessary fixes.
