### ISSUE TITLE
[ru] Тире и дефис

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1066]
Сейчас не различаются в LT
CORRECT: 
А гений и злодейство — две вещи несовместные
WRONG: 
А гений и злодейство - две вещи несовместные
WRONG:
А гений и злодейство две вещи несовместные

https://ru.wikipedia.org/wiki/%D0%A2%D0%B8%D1%80%D0%B5#%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%B2_%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%BC_%D1%8F%D0%B7%D1%8B%D0%BA%D0%B5

https://ru.wikipedia.org/wiki/%D0%94%D0%B5%D1%84%D0%B8%D1%81#%D0%94%D0%B5%D1%84%D0%B8%D1%81_%D0%B2_%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%B9_%D0%BF%D0%B8%D1%81%D1%8C%D0%BC%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8

**Comment by yakovru** [comment]
There is a rule  "Дефис вместо тире" (TIRE) already, but it set off by default.

**Comment by yakovru** [comment]
Правило "Дефис вместо тире" (TIRE) улучшено и активировано.

**Comment by kostyfisik** [comment]
@yakovru Спасибо!
