### ISSUE TITLE
[pt] Idea for rule: “naquele” → “no” — 2024-06-25

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#10679]
Heya, @ricardojosehlima

I apologise for my silence.

I had an idea for a rule:
naquel[ae][s] → n[ao][s]

“Desenvolvemos uma equação baseada NAQUELA desenvolvida por cientistas de topo.” → “NA”

Does it sound good?

Thanks!

**Comment by ricardojosehlima** [comment]
Hi, I don't know, it seems to be something missing in "na desenvolvida"... Maybe for pt-pt

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I am giving up:
![Screenshot 2024-06-25 at 15-55-05 ChatGPT](https://github.com/languagetool-org/languagetool/assets/5192600/775218b3-170e-4130-88f2-d400c418c714)

Thanks for your comments.
