### ISSUE TITLE
[ru] как правило incomplete rule

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1067]
Depends on the context the rule may or may not trigger.
![screenshot from 2018-07-22 15-53-19](https://user-images.githubusercontent.com/5239997/43045765-62805dc6-8dc7-11e8-80d2-e2e5ef684225.png)

**Comment by yakovru** [comment]
Fixed. Closed.

**Comment by kostyfisik** [comment]
@yakovru Спасибо!
