### ISSUE TITLE
Buggy interaction with Teams Web V2

### ISSUE THREAD

**Issue by edwinans** [languagetool-org/languagetool#10697]
Recently, after a Teams web update I think, LanguageTool Chrome extension doesn't interact well with the chat box and move permanently after writing several lines of text; this make it impossible to use LanguageTool in practice:
- https://teams.microsoft.com/v2/
![lt_bug](https://github.com/languagetool-org/languagetool/assets/30560280/6deb6d9b-1b7d-4158-b55f-bbae0fbc8b39)

Sample text:
```
Il avait d’abord commencé par récupérer des informations depuis l’ordinateur de David, puis il était allé les chercher sur Internet. Il avait lui-même programmé l’ordinateur de David afin d’avoir un premier lien vers le monde extérieur : la voix.
```
Developer tools error log:
![image](https://github.com/languagetool-org/languagetool/assets/30560280/f9784596-582f-41a5-927e-d8fac8748346)

Google Chrome for Windows: 126.0.6478.127 (Official Build) (64-bit) (cohort: Stable)

**Comment by edwinans** [comment]
I've also submitted a feedback on Microsoft Teams and mentioned this issue.

**Comment by danielnaber** [comment]
Thanks for the report. This should already be fixed. Could you please try with the latest version? You'll automatically get it when you uninstall and re-install the LT add-on.

**Comment by edwinans** [comment]
> Thanks for the report. This should already be fixed. Could you please try with the latest version? You'll automatically get it when you uninstall and re-install the LT add-on.

I confirm that the issue is resolved after an uninstall/re-install, I had supposed that extensions are updated dynamically without needing to do a hard update.
I thank the LanguageTool team!
