### ISSUE TITLE
Night results appear blank — 2024-06-28

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#10691]
Heya,

https://internal1.languagetool.org/regression-tests/via-http/2024-06-27/pt-PT/

![Screenshot 2024-06-28 at 07-53-13 Overview of regressio](https://github.com/languagetool-org/languagetool/assets/5192600/54c52c43-54c1-416b-8533-4ce1225d09e2)

**Comment by susanaboatto** [comment]
There will be no diff today. We'll have to check again tomorrow.
