### ISSUE TITLE
[de] false positive for Getrenntschreibung in "und los ging’s"

### ISSUE THREAD

**Issue by rillig** [languagetool-org/languagetool#10733]
> Wir gaben ihr und ihrer Mama ein 9×9-Go-Brett und Steine, erklärten, worum es geht und los ging’s.

LanguageTool warns:
> Falls Sie eine Form des Verbs ‚losgehen‘ meinten, wird diese zusammengeschrieben.

Even though I indeed mean a "form of the verb", it's written in separate words, due to the apostrophe following.

**Comment by tiff** [comment]
Das ist mittlerweile behoben
