### ISSUE TITLE
[ru] Missing preposition

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1073]
WRONG:
Дело в том, что функции Риккати-Бесселя могут быть записаны в виде обратной рекуррентной последовательности с хорошей сходимостью для более широкого диапазона аргументов по сравнению сферическими функциями Бесселя следующим образом:

CORRECT
Дело в том, что функции Риккати-Бесселя могут быть записаны в виде обратной рекуррентной последовательности с хорошей сходимостью для более широкого диапазона аргументов по сравнению со сферическими функциями Бесселя следующим образом:

WRONG: Я пошёл речке
CORRECT: Я пошёл к речке

related to #1058 ?

**Comment by yakovru** [comment]
Fixed. Closed.

**Comment by kostyfisik** [comment]
@yakovru Спасибо за работу!
