### ISSUE TITLE
[en] unexpected Checkout splitting suggestion on a proper name

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#10820]
Feedback from https://youtrack.jetbrains.com/issue/IJPL-89620/LanguageTool-nouns:
> LanguageTool should tread capitalized words in the middle of sentences as nouns. In this context, Checkout refers to checkout.com

`Send payment details to Checkout.`

**Comment by evan-defran-lt** [comment]
https://github.com/languagetool-org/languagetool/pull/10827

Please allow until the next deploy for changes to be live.
