### ISSUE TITLE
[pt] Idea for rule “estar” → “ir” — 2024-08-12

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#10825]
Heya, @ricardojosehlima

Sorry for being silence.

Is it possible for you to tell if the following rule is pt-PT only, or if it also applied to pt-BR?

For example:
`V_ESTAR AQUI PARA + Verbo_Infinitivo → V_IR + Verbo_Infinitivo`

For example:
`“Estou aqui para defender a minha tese.”` → `“Venho defender a minha tese.”`

ChatGPT already gave me a list of some of the verbs that work with this structure.

@susanaboatto and @p-goulart must be on holidays, so I have no one to approve my PT rules.

But Pedro told me that for the pt_PT rules, I can approve them myself.

Thanks!

**Comment by p-goulart** [comment]
We're not on holiday, you just haven't been raising any PRs for `pt` rules, only `pt-PT`.

IMO this seems like a valid one for `pt-BR` as well, though. I'd probably tag it as `formal`, though.

**Comment by marcoagpinto** [comment]
@p-goulart 

Pedro, thank you!

I will code it today.

I already know a list of verbs that will work with it (ChatGPT 4o), but my greatest doubt was if was only valid in pt-PT.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
@p-goulart 

I have a pull request open for two or three weeks "removed temp_off of rules ID: blah blah", so I thought both of you were on holiday.

**Comment by ricardojosehlima** [comment]
@marcoagpinto I agree that it serves for pt-Br and in formal contexts

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Thank you, I created a pull request minutes ago:
https://github.com/languagetool-org/languagetool/pull/10826

All the hits except one happened with the verb “ajudar”.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️
