### ISSUE TITLE
[ru] Переменная как существительное

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1083]
В контексте программирования слово "переменная" имет смысл существительного

Среди собственных переменных функции была объявлена специальная переменная.
Среди собственных переменных класса была объявлена специальная переменная.
Среди собственных переменных модуля была объявлена специальная переменная.

![screenshot from 2018-07-22 20-47-39](https://user-images.githubusercontent.com/5239997/43048474-b1e7153e-8df0-11e8-8599-38929cdb3c87.png)

**Comment by yakovru** [comment]
Fixed.
