### ISSUE TITLE
[ru] false positiv

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1084]
Вроде переформулировать без искажения смысла и раздувания фразы не очень получается да и не зачем:

В случае, если локальные минимумы сильно отличаются друг от друга, то предсказание становится затруднительным.

В случае если верхняя часть у первого локального минимума во много раз больше, чем ширина второго, а у него, в свою очередь, подобного расширения нет, то ситуация становится
неоднозначной.

![screenshot from 2018-07-22 20-52-46](https://user-images.githubusercontent.com/5239997/43048505-6bff2fb0-8df1-11e8-806f-717b291b4881.png)

**Comment by kostyfisik** [comment]
CORRECT
Выявлено небольшое число дизайнов с маскирующим эффектом в случае толщины покрытия значительно меньше критической.

**Comment by kostyfisik** [comment]
CORRECT
Маскирующие возможности всех вариантов оказываются идентичными.

**Comment by kostyfisik** [comment]
CORRECT
В нашем случае наличие антипараллельных векторов локальной поляризуемости вызвано наличием переключающих слоёв, приводящих к изменению направления вектора электрического поля на противоположное.

**Comment by yakovru** [comment]
Fixed.
