### ISSUE TITLE
[Firefox] “Check text in editor” no longer works

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#10849]
Heya,

For a few weeks that if I select text in the most recent version of Firefox with a right-click “Check text in Editor”, it no longer pastes the text in the editor.

Thanks!

**Comment by danielnaber** [comment]
@tiff I can confirm. The editor gets opened with e.g. "https://languagetool.org/editor/new?temp_text_id=28618%3A1724837171991" but the text is empty.

**Comment by tiff** [comment]
@danielnaber @marcoagpinto we have fixed this by deploying a new version of our website. Can you confirm that the issue is fixed?
