### ISSUE TITLE
"Stents" has already been rejected - Català

### ISSUE THREAD

**Issue by Alejandroveemo** [languagetool-org/languagetool#10854]
"Stents" is the plural for "stent", a metalic, flexible tube which supports some veins structure. Stent is also not in the dictionary.
![Stent-coronario](https://github.com/user-attachments/assets/45b0a34a-4792-4c82-b07c-e2726216bb6c)

**Comment by jaumeortola** [comment]
Thank you. Done here: https://github.com/languagetool-org/languagetool/commit/cac08d8b028f7ece142c3b55a68da25eb3291a37
