### ISSUE TITLE
False alarm reporting

### ISSUE THREAD

**Issue by TeresaPelka** [languagetool-org/languagetool#1089]
LT message: "Report **the error and this sentence** to LanguageTool as a false alarm, **i.e. a misleading error**?" 

The message suggests a sentence or another language item might be a (misleading) error, whereas the error is (potentially) in LT rule implementation, i.e. it is a false alarm. :)

My suggestion is: "Report a potential error in LT rule implementation?"
Teresa

**Comment by danielnaber** [comment]
Closing, as this seems to refer to the old homepage
