### ISSUE TITLE
Incorrect: Status Quo

### ISSUE THREAD

**Issue by gdude2002** [languagetool-org/languagetool#10927]
Hi! I couldn't figure out where else to bring this up, so I figured this might be the best option.

When editing a header on my blog in Notion, this warning appeared. However, "status quo" is [very much a common term](https://en.wikipedia.org/wiki/Status_quo). This also happens in GitHub Issues.

![image](https://github.com/user-attachments/assets/1dfda79e-2575-47fb-9abb-79942086682c) ![image](https://github.com/user-attachments/assets/58a94636-d7eb-4a80-a43a-f676ed1a408c)

I did a quick search, and at a guess, this seems to think I'm referring to [this random blog on Substack](https://statuskuo.substack.com/)? I don't really understand, but I can't find anything else when searching "Status Kuo" online. In fact, while writing this issue, LanguageTool correctly identified a typo! 

![image](https://github.com/user-attachments/assets/ca07c7ee-814a-4646-a16d-3676a685ca27)

I'm a Premium subscriber, if that's relevant to the issue - I'm not sure whether this rule is premium-only or not.
Thanks!

**Comment by danielnaber** [comment]
Thanks, this should be fixed with the next update.
