### ISSUE TITLE
ngrams-en-20241009.zip appears to be corrupt

### ISSUE THREAD

**Issue by Bigsy** [languagetool-org/languagetool#10930]
ngrams-en-20150817.zip downloads fine for me but but no way I can find a way to extract ngrams-en-20241009.zip. I even tried a different computer and unzip each time reports that 
```Archive:  ngrams-en-20241009.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ngrams-en-20241009.zip or
        ngrams-en-20241009.zip.zip, and cannot find ngrams-en-20241009.zip.ZIP, period.```

**Comment by danielnaber** [comment]
Have you tried downloading again? If that doesn't help, can you tell us the exact file size and checksum of the file you downloaded?

**Comment by Bigsy** [comment]
Apologies there must have been something bad cached yesterday as I tried multiple machines but today a fresh DL is fine
