### ISSUE TITLE
n-gram data continuously changing

### ISSUE THREAD

**Issue by marvin-te** [languagetool-org/languagetool#10936]
Hi there,

for some reason, every time I reload https://languagetool.org/download/ngram-data/, file sizes and modification timestamps for the 2024xxyy ngram files are changing. Downloading leads to verious corrupted files (tested with the German archive).

I don't believe this is intended behaviour, is it? It is very confusing and took me a day of debugging on another end, before noticing this behaviour on your website.

Thanks for looking into this.
Cheers.

**Comment by danielnaber** [comment]
BTW, there's no reason to download the 2024xxyy files until https://github.com/languagetool-org/languagetool/pull/10810 is merged.
