### ISSUE TITLE
Delta between open source and premium behavior vs. enabling more rules

### ISSUE THREAD

**Issue by tleyden** [languagetool-org/languagetool#10944]
I noticed that when I run the open source version via docker with n-grams enabled, it won't flag the following sentence with any grammar errors for this sentence:

> Anna and Mike is going skiing.

However on the [languagetool.org](https://languagetool.org/), with the same sentence it will flag:

> Incorrect form of “be”
> The verb “is” doesn’t seem to fit in this context, “are” is probably more formally correct.

Is this likely a limitation of the open source vs the premium version, or do I just need to enable more rules?

## Repro details

Run docker container:

```
docker run --rm -p 8010:8010 -v `pwd`/ngrams:/ngrams silviof/docker-languagetool
```

Query via curl:

```
curl --data "language=en-US&text=Anna and Mike is going skiing." http://localhost:8010/v2/check | jq .
```

<details>
<summary>LanguageTool Output</summary>

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   633  100   583  100    50  12537   1075 --:--:-- --:--:-- --:--:-- 13760
{
  "software": {
    "name": "LanguageTool",
    "version": "6.4",
    "buildDate": "2024-03-28 14:05:28 +0100",
    "apiVersion": 1,
    "premium": false,
    "premiumHint": "You might be missing errors only the Premium version can find. Contact us at support<at>languagetoolplus.com.",
    "status": ""
  },
  "warnings": {
    "incompleteResults": false
  },
  "language": {
    "name": "English (US)",
    "code": "en-US",
    "detectedLanguage": {
      "name": "Tagalog",
      "code": "tl-PH",
      "confidence": 0.9999998,
      "source": "+fallback"
    }
  },
  "matches": [],
  "sentenceRanges": [
    [
      0,
      30
    ]
  ],
  "extendedSentenceRanges": [
    {
      "from": 0,
      "to": 30,
      "detectedLanguages": [
        {
          "language": "en",
          "rate": 1
        }
      ]
    }
  ]
}
```
</details>

**Comment by danielnaber** [comment]
> Is this likely a limitation of the open source vs the premium version

Yes, the open source version doesn't contain the AI rules that detect this.

**Comment by tleyden** [comment]
Thank you for clarifying this!
