### ISSUE TITLE
Un quart d’heure

### ISSUE THREAD

**Issue by Bricolas** [languagetool-org/languagetool#10962]
This is a small error : 

<img width="427" alt="image" src="https://github.com/user-attachments/assets/702f6bb9-d0ca-458d-b29e-66e27d0df932">

“quart-d'heure” should be corrected by “quart d’heure” and not “quart-d' heure”.

**Comment by LucieSteib** [comment]
Merci Bricolas ! C'est, en effet, une curieuse suggestion, on va arranger ça en essayant de ne pas trop passer un « sale quart d'heure ».
