### ISSUE TITLE
Broken deep link while opening LanguageTool for Desktop

### ISSUE THREAD

**Issue by AKissMail** [languagetool-org/languagetool#10970]
**What I observed / What I did:**
When I open LanguageTool for Desktop, my system browser automatically opens this link:
`https://www.googletagmanager.com/static/service_worker/4al0/sw_iframe.html?origin=https%3A%2F%2Flanguagetool.org `

I then see the following system prompt:

<img width="259" alt="Screenshot 2024-10-27 at 17 49 29" src="https://github.com/user-attachments/assets/26a5041e-0727-41ee-b9c0-8c047e5f7496">

If I cancel the system prompt, I can continue using the application without any issues.

**System details:**
-     macOS version: 15.0.1 (24A348)
-     LanguageTool for Desktop version: 1.8.0 (127)

**Comment by tiff** [comment]
@AKissMail thanks for reporting. Can you restart the app and try again? We believe that we were able to fix this.

**Comment by AKissMail** [comment]
Hi @tiff, yes it is fixed!
