### ISSUE TITLE
Text Analysis outdated — 2024-11-02

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#10976]
Heya,

I have been trying to fix false positives in the disambiguator, but I just noticed that the Text Analysis is outdated, making it an impossible task to accomplish:
![Screenshot 2024-11-02 064520](https://github.com/user-attachments/assets/cfbe0cdc-55ff-4f4d-9ca3-c6d13ee11b8b)

**Comment by SteVio89** [comment]
https://community.languagetool.org/ did not work with jdk17. We're currently updating the code see: https://github.com/languagetool-org/languagetool-community-website2

**Comment by danielnaber** [comment]
Should be fixed now.
