### ISSUE TITLE
[ru] Лишняя запятая

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1098]
WRONG
В случае рассмотрения резонансных структур, это приводит к существенным ошибкам в вычислении поля на границе раздела между слоями
CORRECT
В случае рассмотрения резонансных структур это приводит к существенным ошибкам в вычислении поля на границе раздела между слоями

**Comment by yakovru** [comment]
Fixed.Closed.

**Comment by kostyfisik** [comment]
@yakovru Thanks!
