### ISSUE TITLE
Problem mit "Wie viele Erwerbstätige sind im Gesundheitswesen beschäftigt?"

### ISSUE THREAD

**Issue by orschiro** [languagetool-org/languagetool#10984]
Hi zusammen, 

was ist hier das Problem?

Wie viele Erwerbstätige sind im Gesundheitswesen beschäftigt?

<img width="408" alt="image" src="https://github.com/user-attachments/assets/dcc61599-6f60-4357-abd4-ae7ceb9b1338">

**Comment by tiff** [comment]
Auch das Problem sollte nun behoben sein, danke!
