### ISSUE TITLE
[pt] Fix in Premium — 2024-11-06

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#10994]
Heya, @jaumeortola , @susanaboatto and @p-goulart ,

I know you are very busy, but this is an issue that involves the Premium version of LanguageTool.

This disambiguator rule breaks the Premium version:

```
    <rule> <!-- Used ChatGPT 4o to verify the 3217 results -->
      <pattern>
        <token postag="V.+" postag_regexp="yes"><exception postag_regexp='yes' postag='CS|RG|NC.+|AQ.+|CC|SPS.+|[DP].+'/></token>
        <token regexp='yes' inflected='yes'>um|muito|pouco|vários|diversos|tal</token> <!-- Special PI.* that don't break rules -->
        <marker>
          <and>
            <token postag="VMIP3S0|VMM02S0|VMSP2S0|VMIP2S0|VMN02S0|VMSF2S0|VMIP1S0|VMP00SM" postag_regexp="yes"/>
            <token postag="NC.+" postag_regexp="yes"/>
          </and>
        </marker>
      </pattern>
      <disambig action="remove" postag="V.*"/>
    </rule>
```

Examples of its usage:
```
        <example correction=''>Quero muitos <marker>marines</marker>.</example>
        <example correction=''>Quero vários <marker>marines</marker>.</example>
        <example correction=''>Terminar tal <marker>curso</marker>.</example>
        <example correction=''>Terminar um <marker>doutorado</marker>.</example>
        <example correction=''>Vendeu pouco <marker>mercado</marker>.</example>
        <example correction=''>Vendeu muito <marker>mercado</marker>.</example>
```

Could one of you make changes in Premium so that I may implement it?

Thanks!

❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
Here are the sentences it fixes:


[1.txt](https://github.com/user-attachments/files/17643776/1.txt)

**Comment by p-goulart** [comment]
[EUAI-32](https://quillbot.atlassian.net/browse/EUAI-32).

@marcoagpinto I will have a look. If it's a simple fix on the premium LT repo, I will implement it. Otherwise, the rule will need to be reverted.

**Comment by marcoagpinto** [comment]
@p-goulart 

I reverted it already. 😛 

But it would be great if we could have it since it is a great rule.

❤️ ❤️ ❤️

**Comment by p-goulart** [comment]
Can you point me to the CircleCI build where the premium build fails because of it?

**Comment by marcoagpinto** [comment]
Or this:
https://github.com/languagetool-org/languagetool/pull/10992
(the revert of the rule)

**Comment by p-goulart** [comment]
> The URL you posted above, what shall I do?

Ticket for internal tracking, don't worry about it.

**Comment by p-goulart** [comment]
[This](https://app.circleci.com/pipelines/github/languagetooler-gmbh/languagetool-premium-modules/23280/workflows/ec19fd81-3296-4627-ab44-b41b31c171a2/jobs/23471) is the failing pipeline, btw.

**Comment by marcoagpinto** [comment]
> [This](https://app.circleci.com/pipelines/github/languagetooler-gmbh/languagetool-premium-modules/23280/workflows/ec19fd81-3296-4627-ab44-b41b31c171a2/jobs/23471) is the failing pipeline, btw.

I have no access to it.

**Comment by p-goulart** [comment]
```
[/SENT_START*] Semana[semana/NCFS000*]  [ /null*] que[que/CS,que/PE0CN000,que/PR0CN000,que/PT0CN000]  [ /null*] vem[vir/VMIP3S0,vir/VMM02S0]  [ /null*] estarei[estar/VMIF1S0]  [ /null*] muito[muito/DI0MS0,muito/NCMS000,muito/PI0MS000,muito/RG]  [ /null*] ocupado[ocupado/AQ0MS0,ocupado/NCMS000] .[./SENT_END*,./_PUNCT_PERIOD*,./_PUNCT*]
```

The original rule required 'ocupado' to be a participle. IMO I don't think that's a bad thing.

**Comment by p-goulart** [comment]
Okay, thanks! Do that and let me know. If you don't have access to the CircleCI pipelines for premium, I suppose I'll keep an eye on it.

(Do note, though, that it's not that trivial. I notice some of the sentences you have there include 'doutorado', which might be affected by removal of the participles.)
