### ISSUE TITLE
[ru] Missing preposition в виде

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1100]
WRONG
Во-первых, для моделирования рассеяния на частице, расположенной в бесконечной среде, используется граничное условие виде идеально поглощающего слоя
CORRECT
Во-первых, для моделирования рассеяния на частице, расположенной в бесконечной среде, используется граничное условие в виде идеально поглощающего слоя

**Comment by yakovru** [comment]
Done.
