### ISSUE TITLE
[ru]  Так как ..., то

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1101]
Есть целый ряд устоявшихся конструкций, которые легко восстанавливаются без случайно пропущенной части, например

WRONG
Так отражение от такой границы практически отсутствует, то распределение поля перед ней с хорошей степенью точности совпадает со случаем "открытых" граничных условий, который тождественен бесконечной среде.
СORRECT
Так как отражение от такой границы практически отсутствует, то распределение поля перед ней с хорошей степенью точности совпадает со случаем "открытых" граничных условий, который тождественен бесконечной среде.

Вероятно можно придумать и другие.

**Comment by yakovru** [comment]
Fixed.

**Comment by kostyfisik** [comment]
@yakovru Thank you!
