### ISSUE TITLE
Suggest from personal dictionary

### ISSUE THREAD

**Issue by orschiro** [languagetool-org/languagetool#11012]
Hi team, 

Can the Chrome extension make suggestions based on the personal dictionary?

Example below.

Thank you!

![image](https://github.com/user-attachments/assets/6e9dab12-10f8-411b-8207-355072725e18)

<img width="263" alt="image" src="https://github.com/user-attachments/assets/112b714e-cd13-4a6f-8980-81ea0c45a288">

**Comment by tiff** [comment]
Yes it can, but only the Premium (paid) version.

**Comment by orschiro** [comment]
Good to know, thanks!
