### ISSUE TITLE
Was ist das Problem mit "muskelfördernde"?

### ISSUE THREAD

**Issue by orschiro** [languagetool-org/languagetool#11020]
<img width="322" alt="image" src="https://github.com/user-attachments/assets/dc54c9b1-43ee-415c-8287-4465e5a7006e">

**Comment by tiff** [comment]
Fehlt in unserem Wörterbuch. Hinzugefügt! Danke!

**Comment by orschiro** [comment]
Super, danke! :)

Christopher Blum ***@***.***> schrieb am Fr., 15. Nov. 2024,
13:46:
