### ISSUE TITLE
[ru] в том случае 

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1104]
I was rewriting one into тот момент and finished with a wrong combination not detected by LT
WRONG
Моделирование прекращается в том момент, когда практически вся энергия импульса будет либо рассеяна объектом, либо поглощена. 
CORRECT
Моделирование прекращается в тот момент, когда практически вся энергия импульса будет либо рассеяна объектом, либо поглощена. 

Maybe this can be converted into some generalized unification rule.
WRONG
В том делах нет правды.
Про том времена рассказывают сказки.
CORRECT
В том деле нет правды.
Про те времена рассказывают сказки.

**Comment by yakovru** [comment]
Fixed. Closed.

**Comment by kostyfisik** [comment]
@yakovru Thank you!
