### ISSUE TITLE
[ru]чтобы + два или более глаголов (или форма "нужно", "необходимо", "достаточно") требуют запятой до конца предложения.

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1105]
WRONG
Чтобы получить величину поля для какой-то одной длины волны в точке наблюдения записывается зависимость напряжённости поля от времени.
CORRECT
Чтобы получить величину поля для какой-то одной длины волны в точке наблюдения, записывается зависимость напряжённости поля от времени
OR
Чтобы получить величину поля для какой-то одной длины волны, в точке наблюдения записывается зависимость напряжённости поля от времени

WRONG
Чтобы полететь на луну нужен корабль.
CORRECT
Чтобы полететь на луну, нужен кораль.

WRONG
Чтобы сделать мир светлее достаточно улыбки
CORRECT
Чтобы сделать мир светлее, достаточно улыбки

**Comment by kostyfisik** [comment]
WRONG
Чтобы определить возникновение подобной ситуации необходимо несколько независимых запусков оптимизатора, каждый из которых может выполняться на своём вычислительном ядре.
CORRECT
Чтобы определить возникновение подобной ситуации, необходимо несколько независимых запусков оптимизатора, каждый из которых может выполняться на своём вычислительном ядре.

**Comment by yakovru** [comment]
Fixed.
