### ISSUE TITLE
[ru] Перепутаны инфинитив и 3-е лицо ед. числа 

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1106]
WRONG
Проблема может возникнуть при наличии собственных резонансов в модели, что относиться и к нашему случаю, где частота падающей волны приходится на максимум дипольного отклика частицы.
СORRECT
Проблема может возникнуть при наличии собственных резонансов в модели, что относится и к нашему случаю, где частота падающей волны приходится на максимум дипольного отклика частицы.

WRONG
Он мне приходиться двоюродным племенником.
CORRECT
Он мне приходится двоюродным племенником.

WRONG
Не надо суетится!
CORRECT
Не надо суетиться!

**Comment by yakovru** [comment]
Implemented. Closed.

**Comment by kostyfisik** [comment]
@yakovru Спасибо!
