### ISSUE TITLE
[ru] Ложное вводное "в последнем случае", "в результате" и др.

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1108]
WRONG
В последнем случае, определяющей становится роль теоретического анализа, необходимого для  выделения сути явления из возможных побочных факторов.
СORRECT
В последнем случае определяющей становится роль теоретического анализа, необходимого для  выделения сути явления из возможных побочных факторов.

**Comment by kostyfisik** [comment]
WRONG
В отличие от них, методы роя частиц и дифференциальной эволюции могут работать в непрерывном пространстве вещественных входных параметров естественным образом (используя возможность сложения и вычитания векторов пробных решений), что делает их гораздо более удобными для физических и инженерных задач.
CORRECT
В отличие от них методы роя частиц и дифференциальной эволюции могут работать в непрерывном пространстве вещественных входных параметров естественным образом (используя возможность сложения и вычитания векторов пробных решений), что делает их гораздо более удобными для физических и инженерных задач.

**Comment by kostyfisik** [comment]
WRONG
В противном случае, о наличии сбоя можно будет судить только по итоговому результату работы программы.
CORRECT
В противном случае о наличии сбоя можно будет судить только по итоговому результату работы программы.

**Comment by yakovru** [comment]
Sometimes  phrase "В отличие от *" may be separated by commas:
https://rus-punktuaciya.slovaronline.com/96-%D0%B2%20%D0%BE%D1%82%D0%BB%D0%B8%D1%87%D0%B8%D0%B5%20%D0%BE%D1%82

I set this part of rule off by default: https://github.com/languagetool-org/languagetool/commit/b0400386f66f9b2b2cdd0197a0cbb9ff58ef70a4
