### ISSUE TITLE
[FR] [AGREEMENT] False negative

### ISSUE THREAD

**Issue by MoogyG** [languagetool-org/languagetool#11092]
I make a mistake in the sentence : `Chaque événement est conçu avec soin pour vous offrir une ambiance unique avec des styles musicaux varié`

`varié` should be replaced by `variés`.

Languagetool detects the agreement error with the sentence 
`Chaque événement est conçu avec soin pour vous offrir une ambiance unique avec des styles musicaux varié` 
but not with 
`Chaque événement est conçu avec soin pour offrir une ambiance unique avec des styles musicaux varié`.

I am facing this problem using self-hosted version and public API (https://api.languagetool.org/v2/check) but I notice that the web version of languagetool (https://languagetool.org/fr) detects both. Why this difference?

```JSON
{
    "software": {
        "name": "LanguageTool",
        "version": "6.5",
        "buildDate": "2024-10-01 12:31:12 +0000",
        "apiVersion": 1,
        "premium": false,
        "premiumHint": "You might be missing errors only the Premium version can find. Contact us at support<at>languagetoolplus.com.",
        "status": ""
    },
    "warnings": {
        "incompleteResults": false
    },
    "language": {
        "name": "French",
        "code": "fr",
        "detectedLanguage": {
            "name": "French",
            "code": "fr",
            "confidence": 0.99999374,
            "source": "+fallback"
        }
    },
    "matches": [
        {
            "message": "Vérifiez la concordance de « varié » avec les noms précédents.",
            "shortMessage": "",
            "replacements": [
                {
                    "value": "variée"
                },
                {
                    "value": "variés"
                }
            ],
            "offset": 99,
            "length": 5,
            "context": {
                "text": "...mbiance unique avec des styles musicaux varié",
                "offset": 43,
                "length": 5
            },
            "sentence": "Chaque événement est conçu avec soin pour vous offrir une ambiance unique avec des styles musicaux varié",
            "type": {
                "typeName": "Other"
            },
            "rule": {
                "id": "AGREEMENT_POSTPONED_ADJ",
                "subId": "1",
                "sourceFile": "grammar.xml",
                "description": "concordance adjectif après les noms",
                "issueType": "uncategorized",
                "category": {
                    "id": "AGREEMENT",
                    "name": "Concordances"
                }
            },
            "ignoreForIncompleteSentence": true,
            "contextForSureMatch": -1
        }
    ],
    "sentenceRanges": [
        [
            0,
            104
        ]
    ],
    "extendedSentenceRanges": [
        {
            "from": 0,
            "to": 104,
            "detectedLanguages": [
                {
                    "language": "fr",
                    "rate": 1.0
                }
            ]
        }
    ]
}
```

**Comment by LucieSteib** [comment]
HI @MoogyG :) 
There's one XML rule finding the error in the first sentence with "vous offrir" AGREEMENT_POSTPONED_ADJ indeed. This rule has a lot of anti-patterns to prevent false positives, that's what preventive the error to be found in the second one.
You're lucky to get both of them corrected on the web version (where it's the GEC model finding the first one for me). As the AI models are not 100% deterministic, you might not get exactly the same results as me, but the fact remains that the AI models are only running on the web Editor.
Hope this clarifies :)
![image](https://github.com/user-attachments/assets/2f915311-65fe-4a40-b742-a8aa9e5b7251)

**Comment by Nancomcy-Dev** [comment]
Thanks for your clarification

**Comment by MoogyG** [comment]
Closed
