### ISSUE TITLE
Grails runtime exception

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#1109]
LT standalone, click 'Rule details on community...'. Get a Grails error:

![image](https://user-images.githubusercontent.com/5816160/43191124-6ed7d46e-8ff2-11e8-9146-d955c4720e6b.png)

**Comment by danielnaber** [comment]
All examples are currently broken, should be okay again tonight at about 23:00 CEST with the new version deployed.

**Comment by danielnaber** [comment]
It's working again.
