### ISSUE TITLE
[ru] multiple false positives for rule missing_noun_at_end

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1110]
CORRECT
В случае, если локальные минимумы сильно отличаются друг от друга, то предсказание становится затруднительным.
В результате наиболее универсальным представляется численное решение, когда компьютерная программа выбирает параметры дизайна наночастицы, максимально приближенные к оптимальным.
В случае если верхняя часть у первого локального минимума во много раз больше, чем ширина второго, а у него, в свою очередь, подобного расширения нет (например его стенки являются практически вертикальными), то ситуация становится неоднозначной.
Увеличенная часть рисунка с дополнительными результатами оптимизации (треугольники без заполнения) для случая толщины покрытия меньше критической.
При проведении оптимизации выявлено небольшое число дизайнов с маскирующим эффектом в случае толщины покрытия значительно меньше критической.
Маскирующие возможности всех вариантов оказываются идентичными.
При рассмотрении указанных дизайнов во временной области установление стационарного распределения амплитуды поля займёт больше времени в случае двухдолинного дизайна по сравнению с однодолинным.
В этом случае приходится признать, что предсказательная способность выбранного численного метода ни в чём не уступает другим теоретическим методам, и в рамках использованных допущений получаемые результаты являются достоверными.

**Comment by yakovru** [comment]
Подтверждаю проблему.

**Comment by yakovru** [comment]
Fixed via https://github.com/languagetool-org/languagetool/commit/4acb6c4e3b157ebb13008b131a383a6574e35f22#diff-a8467ecef295a74a410953ed43732c0e , etc.
