### ISSUE TITLE
license issue with org.jpmml

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1113]
See this merge: https://github.com/languagetool-org/languagetool/commit/6171239d0c9965710d8388ad0a6b7b6b7f7bf6f5

This adds https://github.com/jpmml/jpmml-evaluator, which is under AGPL. AGPL code cannot be used in LT, because we're under LGPL.

I see there was later a commit "2f074e: Revert "ML-based suggestions ordering", but that was is a branch? Was this supposed to undo the merge?

**Comment by danielnaber** [comment]
Also, ping to @oserikov - can use of this library be avoided?

**Comment by yakovru** [comment]
I wrote to Oleg ( @oserikov ), he replied that he plans to replace the library with another one.

>Среда, 25 июля 2018, 16:42 +03:00 от Daniel Naber <>:
>
>Also, ping to  @oserikov - can use of this library be avoided?
>

--

Yakov Reztsov

**Comment by danielnaber** [comment]
Could you revert the feature until this is done?

**Comment by yakovru** [comment]
I make PR  https://github.com/languagetool-org/languagetool/pull/1103    for that.
I will apply it today.



>Среда, 25 июля 2018, 18:02 +03:00 от Daniel Naber:
>
>Could you revert the feature until this is done?
>
-- 

Yakov Reztsov
