### ISSUE TITLE
new false alarms English (INTERJECTIONS_PUNCTUATION)?

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1114]
I talked to a native speaker, and he thinks these sentences cause false alarms:

* Oh no, really?
* Oh my gosh!
* Oh please, believe me.

@TiagoSantos81 I think you added that rule? @MikeUnwalla Maybe you can add your opinion?

**Comment by MikeUnwalla** [comment]
Multi-word interjections are possible. Thus, if you parse the sentences as follows, the messages are false alarms:

- (Oh no), really? [https://www.thoughtco.com/interjections-in-english-1692798]
- (Oh my), gosh! [https://en.wiktionary.org/wiki/oh_my] 
- (Oh please), believe me.

But, the alternatives with punctuation are correct:

- Oh, no, really?
- Oh, my gosh!
- Oh, please, believe me.

The message is "Interjections are usually..." So, I think that there is no problem with the rule.

**Comment by TiagoSantos81** [comment]
> The message is "Interjections are usually..." So, I think that there is no problem with the rule.
Thank you @MikeUnwalla
