### ISSUE TITLE
[en] 'second-guessing' recognized as VBZ

### ISSUE THREAD

**Issue by milekpl** [languagetool-org/languagetool#11142]
There's a wrong entry in the English POS tag dictionary:

second-guessing	second-guess	VBZ

The correct value is there as well, it's a trivial fix, just remove this line. I'd do this myself, but I think this is developed now in a separate repository, so I'm leaving this as a bug report.

**Comment by jaumeortola** [comment]
Thank you. Done here: https://github.com/languagetool-org/languagetool/commit/862ff18517e81281b920439e79db67c7ad900f02
In the new repository, the tags are already correct.

**Comment by jaumeortola** [comment]
The current output is here: https://github.com/languagetool-org/english-pos-dict/tree/main/src-dict/output
(The repository certainly needs a cleanup)
```
english-pos-dict/src-dict/output$ grep "\bsecond-guess\b" tagger-dictionary.txt 
second-guess	second-guess	VB
second-guess	second-guess	VBP
second-guessed	second-guess	VBD
second-guessed	second-guess	VBN
second-guesses	second-guess	VBZ
second-guessing	second-guess	VBG
```
