### ISSUE TITLE
[ru] Таким образом,

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1121]
Может быть вводное, может быть часть предложения. Поэтому надо всегда выделять и давать подсказку: "Возможно запятая не нужна, если это не вводное словосочетание. Например, если можно заменить на `в этом случае`", если запятая уже есть  и "Возможно нужна запятая, если это вводное словосочетание, т.е. `таким образом` можно убрать без существенного искажения смысла"

WRONG
После окончания отладки программы и верификации её работы на ряде тестовых примеров есть возможность отключить такие проверки; таким образом, их наличие не скажется на
итоговой производительности программы
CORRECT
После окончания отладки программы и верификации её работы на ряде тестовых примеров есть возможность отключить такие проверки; таким образом их наличие не скажется на
итоговой производительности программы

**Comment by Katzen-Gott** [comment]
Мне кажется, что всегда выделять — это плохая идея. В русском языке полно вещей которые могут быть правильными в одном случае и неправильными в другом. Если всё это будет подчеркиваться, то получится каша. Особенно в художественном тексте. Даже сейчас есть множество "правил" которые больше мешают, чем помогают.
Если есть надежный способ определить когда запятая нужна, а когда нет — такое правило было бы полезно. Но не в формате „чаще запятая нужна, давайте всегда подчеркивать ее отсутствие“

**Comment by kostyfisik** [comment]
@Katzen-Gott Будет здорово, если вы подскажете надёжный алгоритм, который позволит определить необходимость запятой. Если лично вам это правило мешает - его можно отключить в своих настройках. А так, лучше обратить внимание пользователя на место, в котором высока вероятность ошибки.

**Comment by yakovru** [comment]
@Katzen-Gott, бывают и авторские запятые. Такие случаи невозможно 100% проверить автоматически. Существующий набор правил сбалансирован, и правила, которые могут срабатывать не всегда корректно, выключены в дефолтных настройках.

**Comment by Katzen-Gott** [comment]
@kostyfisik, вы как раз подтверждаете мою точку зрения. Формального способа не существует, нужно понимать смысл предложения, а до этого спел чекеры еще не доросли. И именно поэтому подчеркивать все подряд кажется мне плохой идеей.
@yakovru, так и есть. И это опять никак не противоречит моему комменту. Единственное правило, которое, как мне кажется, стоило бы выключить в дефолтных настройках — это "опущено существительное в конце предложения".
Кстати, в данный момент приложение весьма снисходительно к авторским знакам. За что вам большое спасибо.
