### ISSUE TITLE
RuleMatch getSentence() method does not exist in 4.2

### ISSUE THREAD

**Issue by bholland** [languagetool-org/languagetool#1134]
Hello all,

I tried to upgrade from 4.0 to 4.2. Using the API from here:

https://languagetool.org/development/api/org/languagetool/rules/RuleMatch.html

There should be a method for a RuleMatch object. If you download the 4.2 jar file from maven, the RuleMatch.class file does not contain this method but the 4.0 file does. Please fix this. 

Thanks!

**Comment by bholland** [comment]
Normally, I would say you are correct but I am only downloading the maven
jar and using whatever the compiled code is. It also works with 4.0 out of
the box, making me believe that perhaps there was a hidden issue with the
jar packaging?

Thanks,
~Ben

**Comment by danielnaber** [comment]
Have you downloaded the JAR manually instead of relying on Maven to do all the work? Anyway, I know of no changes in this regard and there have been no similar reports.

**Comment by bholland** [comment]
Not yet. Let me dig a bit more on my end then. I download the source files
along with the jars and there might be something there. This was just
really strange.

Alas also, no. I need maven to do most of the work on this project. It has
about 30 dependencies and manually managing that is much harder than having
a package manager do the heavy lifting. I will let you know what I find.
Thanks for the help!

~Ben

**Comment by danielnaber** [comment]
I assume this can be closed.
