### ISSUE TITLE
Underline color: Java error if there is a colon in the category name

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#1139]
Change a category name to include a colon: `<category id="TYPOS" name="Test: Possible Typo" type="misspelling">`
Testrules give no warning. LT operates correctly. Change the colour for the category. No problem:

![image](https://user-images.githubusercontent.com/5816160/43956486-582a71e8-9c9c-11e8-9e09-8d7c8ac34046.png)

Close LT standalone, start LT standalone. Get a Java error:
![image](https://user-images.githubusercontent.com/5816160/43955400-ecf069cc-9c97-11e8-9322-e450f77a6791.png)

Although there is a Java error, testrules gives no warnings.

I guess this problem has the same cause as #1022.

@f-knorr , a comment in the fix (https://github.com/languagetool-org/languagetool/commit/b11e5a897101fb3950032794bff33e8830deb5ff) shows that a colon is used with the hex code for the color. If it is possible for a colon to be in a category name when the underline colors are set by the user, please could you change the code such that there is no Java error? Thanks.

(If it is not possible for a colon to be in a category name when the underline colors are set by a user, testrules should give a warning to say "do not use a colon in a category name".)

**Comment by MikeUnwalla** [comment]
@f-knorr , thank you.

**Comment by f-knorr** [comment]
You're welcome. Glad I could help.
