### ISSUE TITLE
Ignore file names and domain names

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#1141]
In my work I quite often have texts that contain file names. These are always marked as spelling mistakes. I think all words should be ignored that end with `.xxx`, or at least for maybe the most common file types (exe, jpg, mp4 etc.).

**Comment by danielnaber** [comment]
Same for domain names like `languagetoo.org`.

**Comment by MikeUnwalla** [comment]
I added a rule only for file names (https://github.com/languagetool-org/languagetool/commit/477ff67dc1cbdc649a9fb120d15fa5e2c7f6b579), because it was a quick win (I had that rule for the STE checker). Sorry, I don't have time to investigate the extensions for domain names.

**Comment by MikeUnwalla** [comment]
I guess that a Java rule is better, because the ignoring of file names is applicable to many languages. Feel free to revert rule.

**Comment by danielnaber** [comment]
These are our options, I think:

* Just add your change to all languages (a lot of duplication)
* Add a new global `disambiguation.xml` that is used by all languages
* Add it in Java - although the current way to detect URLs is rather hacky

Any opinions?

**Comment by Discostu36** [comment]
IMHO a global file is the best solution. This way, updates to the rule (and possible other rules for that file) only have to be mad once.

**Comment by Discostu36** [comment]
There is now a global disambiguation file for ignoring file and domain names:

https://github.com/languagetool-org/languagetool/blob/master/languagetool-core/src/main/resources/org/languagetool/resource/disambiguation-global.xml
