### ISSUE TITLE
AbstractFillerWordsRule and sub classes have no test

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1149]
@FredKruse The code in `match` is quite complicated, could you maybe add a test for this rule?

**Comment by FredKruse** [comment]
Should a test for the German rule do?

**Comment by danielnaber** [comment]
Yes, as long as the sub classes don't really differ in their logic, it's enough to test one language. The alternative is to create a subclass of the abstract class just for testing.
