### ISSUE TITLE
[DE] "Münde" lösen Fehlalarme aus

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1156]
Moin liebes LanguageTool-Team

Durch einen Zufall habe ich herausgefunden, dass "Münde" nicht als Mehrzahl anerkannt, obwohl der "Duden" mir Münde erlaubt.

Ihre **Münde wurden** mit Tüchern geknebelt.

LanguageTool: "Hier ein Komma einfügen?"

Ihre Münde **worden** mit Tüchern geknebelt.

LanguageTool: "Meinten Sie "wurden" (Hilfsverb für das Präteritum) staat "worden" (Hilfsverb)?"

"Worden" habe ich nur zur Sicherheit getetst, um einen Fehlalarm mit "wurden" auzuschließen.

Grüße Dallun511

**Comment by Dallun511** [comment]
Ist die Regel morgen um 22 Uhr online?

**Comment by f-knorr** [comment]
ja
