### ISSUE TITLE
[en] "They always are."

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1175]
Not sure about this suggestion. I'm not a native English speaker but the text seems right to me but the suggestion not.
![bildschirmfoto 2018-09-10 um 13 07 01](https://user-images.githubusercontent.com/37363/45294128-abaf0d80-b4fa-11e8-8222-917ae98712d5.png)

**Comment by MikeUnwalla** [comment]
@tiff is correct. The text is fine. (Sorry, I don't have time to correct the false message.)

**Comment by osg** [comment]
+1 for _always are_. (Verifying correctness as a native speaker.)

However, the text, "The adverb ... _is usually put_ after the verb ..." sounds unnatural. A more natural sounding alternative is, "The adverb ... _usually goes_ after the verb ..."

The former sounds like someone is picking up an adverb like a piece of furniture and moving it somewhere, like next to a plant. :)
