### ISSUE TITLE
ERROR: could not initialize com.sun.jna.Native

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [languagetool-org/languagetool#1179]
java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081 --public
ERROR: could not initialize com.sun.jna.Native

java version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

OS
CENTOS 6.10

TESTING IN
LanguageTool version 4.2, 4.1, 3.8 and 4.3(after build)

**Comment by danielnaber** [comment]
I cannot reproduce it with OpenJDK 10.0.2 on Ubuntu, can you try with that?
