### ISSUE TITLE
Emojies marked as misspelling in english

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1182]
Just do a spell check with this emoji:
> 🎉

**Comment by tiff** [comment]
maybe related to https://github.com/languagetool-org/languagetool/issues/853

**Comment by danielnaber** [comment]
I cannot yet reproduce that - in which context (add-on, website) does it happen? Can you send a screenshot?

**Comment by tiff** [comment]
<img width="1011" alt="bildschirmfoto 2018-09-16 um 18 35 35" src="https://user-images.githubusercontent.com/37363/45598622-59c92480-b9df-11e8-9f37-2f1e0509270a.png">

**Comment by danielnaber** [comment]
@f-knorr Remember why your change was only implemented for Spanish and Polish (#853)? Because those were the only languages mentioned in the issue? Any reason not to implement the same change for all languages?

**Comment by f-knorr** [comment]
@danielnaber  The fix #853 for Spanish and Polish has been an additional fix to the original problem described in #842 (German)

**Comment by f-knorr** [comment]
For all i know, i did a quick check for English. The emojis that caused spelling errors in Polish and Spanish, did not cause an error in English. Therefore, I limited the fix the 2 languages mentioned in the gh-issue.

**Comment by tiff** [comment]
@f-knorr thanks, once again!
