### ISSUE TITLE
[de] "Das wars"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1186]
Many users at SpellBoy ignore the word "wars", most likely because the suggestions don't include the correct "war es" or "war's".
![bildschirmfoto 2018-09-17 um 08 35 31](https://user-images.githubusercontent.com/37363/45608702-b87cb580-ba54-11e8-9bd3-4caa384b135d.png)

**Comment by tiff** [comment]
I think the issue exists everywhere the German pronoun “es” is contracted to “s”
![bildschirmfoto 2018-09-17 um 16 05 18](https://user-images.githubusercontent.com/37363/45628081-90607700-ba93-11e8-94b4-da959d7f4558.png)

**Comment by Discostu36** [comment]
#1190 beschreibt ein ähnliches Problem

> Moin
> 
> Das **war’s**
> **Geht’s** noch?
> 
> Ist diese Schreibweise nicht sinnvoller? Benutze ich zumindest für meine Texte.

Beides ist erlaubt, man muss den Apostroph nur setzen, wenn es sonst missverständlich oder undurchsichtig ist (vgl. Rechtschreibregeln §96 und §97).

**Comment by osg** [comment]
> Beides ist erlaubt, man muss den Apostroph nur setzen, wenn es sonst missverständlich oder undurchsichtig ist (vgl. Rechtschreibregeln §96 und §97).
In der Regel sprechen wir über Muttersprachlern? Als Nicht-Muttersprachlerin kann es manchmal undurchsichtig sein. :)

**Comment by Discostu36** [comment]
Natürlich. Den Apostroph zu setzen ist ja auch nie falsch, nur nicht immer vorgeschrieben. Wenn Nicht-Muttersprachler die Zielgruppe sind, sollte man es immer setzen.

**Comment by danielnaber** [comment]
> Den Apostroph zu setzen ist ja auch nie falsch, nur nicht immer vorgeschrieben.

Ausnahme sind Wörter wie "ans" etc:

https://www.duden.de/sprachwissen/rechtschreibregeln/apostroph#K13

**Comment by danielnaber** [comment]
As there are thousands of verbs and this could be relevant for many of them (`grep "IMP:SIN" dictionary-de.dump | grep "^[a-zöäü]"`), I will add just these few examples now.
