### ISSUE TITLE
[de] Auslassungen mit Apostroph (z.B. "’nen")

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#1190]
Die verkürzte Wortform in `Gib mir mal ’nen Kugelschreiber` wird als Rechtschreibfehler markiert, obwohl sie umgangssprachlich erlaubt sind. Da ich nicht annehme, dass sich dies durch Editieren der spelling.txt lösen lässt (ohne Apostroph sollte „nen“ schließlich nicht erlaubt werden), müsste das jemand machen, der mehr Ahnung hat als ich.

**Comment by Discostu36** [comment]
Grundsätzlich sind alle Auslassungen betroffen, deren Wortteile nicht im Wörterbuch stehen, z.B. auch die Duden-Beispiele:

`Dass aber der Wein von Ewigkeit sei, daran zweifl’ ich nicht …`
`Ein einz’ger Augenblick kann alles umgestalten.`

**Comment by Dallun511** [comment]
Grundsärtlich gefällt dein Vorschlag sehr und sollte unmgesetzt. Nur ich würde noch bis nach dem Release der Version 4,3 warten, bis die Idee umgesetzt wird.

Grüße Dallun511

**Comment by Discostu36** [comment]
Dieser Fehlalarm wurde behoben.
