### ISSUE TITLE
Date correction doesn't work with th

### ISSUE THREAD

**Issue by Jab2870** [languagetool-org/languagetool#1197]
One of the things that I love about LanguageTool is the ability to correct the date.

![screenshot_2018-09-26_10-16-23](https://user-images.githubusercontent.com/1909202/46070301-4fdcb980-c175-11e8-8aed-c8c2fc8bc888.png)

Unfortunately, if you add `th` to the date, it is no longer piked up.

e.g.
Changing 

> Thursday, 27 June 2017.

to 

>  Thursday 27th June 2017.

Prevents the error being picked up

**Comment by danielnaber** [comment]
I have added the variant with the `th`, but not yet the one without the comma. Is that actually correct or should there be another rule that complains about the missing comma?

**Comment by MikeUnwalla** [comment]
Oxford Manual of Style (2002 edition), section 7.10.1 says, "A named day preceding a date is separated by a comma: _Tuesday, 2 November 1993_."

Possibly, Oxford's recommendation is a style preference, not a grammar rule.

**Comment by danielnaber** [comment]
@MikeUnwalla So would you as a native speaker consider `Tuesday 2 November 1993` or `Tuesday 2nd November 1993` (both without comma) incorrect?

**Comment by MikeUnwalla** [comment]
From a style perspective, my preference is to use a comma. But, I don't know that that _Tuesday 2 November 1993_ is **grammatically** incorrect. (Possibly, it is grammatically incorrect, but I don't know.)

**Comment by danielnaber** [comment]
The variant without comma is now also supported (should be live at languagetool.org tonight).
