### ISSUE TITLE
Grails runtime exception with 'Rule details on community...'

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#1202]
After I click 'Rule details on community...', I see this error message:

![image](https://user-images.githubusercontent.com/5816160/46242788-92e09c00-c3c4-11e8-8f17-f4e613aae4a4.png)

I tried with 3 different rules, and the message always occurred.

I tried with French, and that was OK.

**Comment by danielnaber** [comment]
Fixed now (for now - this relies on an API at community.languagetool.org which is rather fragile).
