### ISSUE TITLE
Why does languagetool fail at this short example text (3 from 19 errors recognized)?

### ISSUE THREAD

**Issue by 1605200517** [languagetool-org/languagetool#1214]
Please consider the following text. Following to the [source](http://goodcontentcompany.com/proofreading-beats-spell-check-microsoft-word-ignores-19-errors), it has **19 errors**.

> Simone pointed his finger the boy and smiled wicked smile. “So you’ve peddled all night to get here?’ He said. “Impressive. We’ve not too far from border here. You may also see also Scotland if you climb up to top of that hill over there too.”
> “Thank you Simon,” replied the boy.
> “One more thing… I cut my knee earlier and hadn’t brought a 1st aid kid along. To be honest, my memory hasn’t been goof over the past few years as it used to be. Do you have one that I could burrow?”

As I check it with the [online demo](https://www.languagetool.org/) for Language Tool (US English), I get just three error hints.

Why so?

**Comment by danielnaber** [comment]
> Why so?

"There are actually 19 deliberate mistakes in this short passage" - these are *deliberate* mistakes, they are usually not the mistakes people actually make. But anyway, feel free to contribute so more mistakes can be found, see http://wiki.languagetool.org/development-overview for an introduction.

**Comment by 1605200517** [comment]
@danielnaber thanks - if I would try to compare LanguageTool with Microsoft Word and Grammarly, is there a standard text to benchmark such tools? In the methodological approach, I think of the ACID test tool for browsers - it was designed in a way it was nearly impossible to get the 100% score.

E.g. current Firefox on Ubuntu gets the score of 97/100.
http://acid3.acidtests.org/

For sure for spell/grammar checks the input is just a text, but nevertheless.

**Comment by danielnaber** [comment]
There are scientific corpora, search for "shared task" and "gec" (grammatical error correction), e.g. https://www.comp.nus.edu.sg/~nlp/conll14st.html, but we don't use them due to the risk of optimizing for that specific corpus.
