### ISSUE TITLE
Testing disambiguation

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#1216]
It would be helpfull if it were possible to check which disambiguation rule(s) affected the input text, if any.

**Comment by danielnaber** [comment]
https://community.languagetool.org/analysis/index?lang=en has that feature

**Comment by baarsrj** [comment]
Is that also available in the local version? I had rather publish after local testing...

**Comment by danielnaber** [comment]
If you use `-v` as an option for the command line version, it should print the disambiguation log.
