### ISSUE TITLE
[de] "Hallo wie geht es dir?"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1220]
> Hallo wie geht es dir?

doesn't show any errors, but shouldn't there be a comma after "Hallo"?

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/47623501-9e81c880-db12-11e8-800d-a1893d17a4c4.png)
Quelle: https://www.duden.de/sprachwissen/sprachratgeber/Anrede-mit-Hallo

Laut dem Duden gehört ein Komma, nach "Hallo, Moin, Guten Tag, etc."

Aber selbst der Duden Mentor merkert nicht, wenn das Komma vergessen wird. Hier sollte trotzdem eine Regel eingefügt werden, wenn ein Programmierer Zeit.

Hiermit sollte es schnell gehen, weil ich die Quelle angegeben habe und der wichtige Teil makiert ist.

Grüße Dallun511

**Comment by tiff** [comment]
@f-knorr this doesn't seem to be working (anymore):

![bildschirmfoto 2019-01-21 um 07 57 47](https://user-images.githubusercontent.com/37363/51457609-4691e100-1d52-11e9-92a0-6fc25772f964.png)

I don't have the permissions to reopen this issue.
