### ISSUE TITLE
Many missing russian words

### ISSUE THREAD

**Issue by atylo** [languagetool-org/languagetool#1223]
Hello. While correcting one of my texts in Russian, I've noticed that several basic words from Russian are missing, and the program suggests to write an issue here. Negative pronouns, like "Нечего", "Некогда", "Некем" and so on. Comparative degree of adverbs, like "подальше", "побыстрее", "получше", "понадеждней".

**Comment by baarsrj** [comment]
At least некем and подальше are accepted by the Hunspell Russian spell checker. It is possible to reduce the difference semi-automatically, Maybe the maintainer is interested?

**Comment by danielnaber** [comment]
Of the given examples, it looks to me only one is not accepted:

![russian2](https://user-images.githubusercontent.com/857004/47606449-17e6c180-da14-11e8-91a7-e57fc2876cb8.png)

@atylo How exactly did you use LT when you found this issue?

**Comment by atylo** [comment]
@danielnaber I was using the offline desktop version from here https://languagetool.org/download/LanguageTool-4.3.zip

**Comment by danielnaber** [comment]
>  I was using the offline desktop version from here https://languagetool.org/download/LanguageTool-4.3.zip

I cannot reproduce it there either. Are you sure you've set the language to Russian?

![russian3](https://user-images.githubusercontent.com/857004/47607661-140e6b80-da23-11e8-86f1-90adba843cef.png)

**Comment by atylo** [comment]
@danielnaber ... I’m gonna pretend you didn’t ask this dull question, okay?

**Comment by baarsrj** [comment]
It is not a dull question; I get the same results as Daniel. In Belarussian all are underlined, in Russian only one.

**Comment by atylo** [comment]
@baarsrj Well, to prove that I'm not making it up
![oics](https://user-images.githubusercontent.com/18141838/47613115-b1a48200-da99-11e8-9f02-668d561a3046.PNG)

**Comment by atylo** [comment]
@baarsrj Indeed, "некогда" and "получше" are not underlined, but I am sure they were by the time I was checking my text with the tool.

**Comment by danielnaber** [comment]
> Yea, "получше" doesn't get along well with a question mark and exclamation point

I cannot reproduce that either - what operating system and Java version do you use? (You can use `java -version` on the command line to find out):

![russian4](https://user-images.githubusercontent.com/857004/47613785-55d7fa00-da95-11e8-8d65-d3679dc8a24c.png)

**Comment by atylo** [comment]
@danielnaber I also enabled every rule in the program, and the version I use is 4.3 (2018-09-28). Perhaps there was a newer release after that?

**Comment by yakovru** [comment]
I added missing forms, but form "понадеждней" is mistake. Right form of this word is "понадёжней".
Fixed.
