### ISSUE TITLE
[nl] url detected as error

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1224]
<img width="840" alt="bildschirmfoto 2018-10-20 um 16 49 13" src="https://user-images.githubusercontent.com/37363/47256965-2703c780-d488-11e8-9421-6ebfecdc084e.png">

**Comment by f-knorr** [comment]
Please don't get me wrong: 
To investigate this issue, any developer will have to reproduce the reported behavior. To do so, (s)he has to copy the url given in the picture. 
So, and here i speak for myself only, I consider this as wasted time. 

Just a hint: The screenshot is good, but the text would really help a lot.

**Comment by tiff** [comment]
@f-knorr I'm really sorry. I was in a rush when I created this issue. 
Basically the issue happens with any URL with 30 or more characters (e.g. "https://forum.languagetool.org")

**Comment by tiff** [comment]
@f-knorr I'm really sorry. I was in a rush when I created this issue. 
Basically the issue happens with any URL with 30 or more characters (e.g. "https://forum.languagetool.org")

**Comment by tiff** [comment]
@f-knorr thank you for looking into this
