### ISSUE TITLE
Closing/Opening Parenthesis not found

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1226]
If you check this text:
> This is a test (e.g. "https://forum.languagetool.org")

...the parenthesis are marked as errors, saying that the corresponding opening/closing parenthesis is missing. Only seems to happen when the text between the parenthesis contains quotes.

I was able to reproduce this also in other languages.

![bildschirmfoto 2018-10-22 um 07 41 29](https://user-images.githubusercontent.com/37363/47279025-ed3cd900-d5cd-11e8-97b3-15c503b749fc.png)

**Comment by danielnaber** [comment]
The problem doesn't seem to be the quotes but the URL. `WordTokenizer` thinks the final `"` is part of the URL.

**Comment by jaumeortola** [comment]
Found a minor problem here after the changes. `www.example.com."` should be split in 3 tokens, but it is split in 2. The last point is joined incorrectly to the URL.

**Comment by jaumeortola** [comment]
Fixed here: https://github.com/languagetool-org/languagetool/commit/6c017d85440e2acf9e08ea0b81eb037ad4be0808
