### ISSUE TITLE
Issue with > character

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#1229]
When using the `>` character on languagetool.org (or languagetoolplus.com), it is converted into `&gt;`. 

![grosser1](https://user-images.githubusercontent.com/30999326/47428117-97655e00-d792-11e8-81a8-51d12904eef4.png)
![grosser2](https://user-images.githubusercontent.com/30999326/47428118-97655e00-d792-11e8-836a-c50f7adc5d23.png)

- This problem does not occur in the Chrome extension. I haven't checked the offline client. 
- This does happen in many languages (English, German, Romanian. ...) but not all of them.

**Comment by ales-blaze** [comment]
I would like to solve this issue!

**Comment by Discostu36** [comment]
This bug does not occur anymore.
