### ISSUE TITLE
Better support for unsupported languages

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1231]
Detect more languages and map them to some kind of "zero rules" languages that doesn't do anything. Helps users who write in a language we don't support and that thus gets misdetected. Clients will need to show some kind of unobtrusive warning.

Source: https://twitter.com/JanBleha/status/1055110608880832514

**Comment by danielnaber** [comment]
This is supported now in the backend, the clients yet need to be adapted.

**Comment by SkyCharger001** [comment]
Will this include support for the no-language option of LO/OO? (I use this to not get spellcheck warnings on text-art I sometimes include.)

**Comment by danielnaber** [comment]
> Will this include support for the no-language option of LO/OO? (I use this to not get spellcheck warnings on text-art I sometimes include.)

No, this is unrelated to the LO/OO add-on
