### ISSUE TITLE
[de] Problem with Ergänzungsstrich

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#1233]
There is some weird problem with the hyphen (Ergänzungsstrich) in "Rechtsanwalts- und Notar­fachan­ge­stellter". 
![reno1](https://user-images.githubusercontent.com/30999326/47502259-a10cc580-d867-11e8-8e48-bb4b7cdbd5fa.png)
![reno2](https://user-images.githubusercontent.com/30999326/47502263-a1a55c00-d867-11e8-9784-3aa12ba68d0c.png)
![reno3](https://user-images.githubusercontent.com/30999326/47502262-a1a55c00-d867-11e8-8d40-17f592fd7bf4.png)
![reno4](https://user-images.githubusercontent.com/30999326/47502292-b2ee6880-d867-11e8-8506-4ae0c050a213.png)

**Comment by danielnaber** [comment]
I think it's more about the soft hyphens probably part of that text. Try typing that text (instead of using copy and paste) and it will work.

**Comment by Discostu36** [comment]
You are right, this was copied from a website, very interesting. But I guess this is no intended behavior? Shouldn't LT treat all hyphens alike (or, as another option, tell me in case I'm using a wrong one)?

**Comment by danielnaber** [comment]
See https://github.com/languagetool-org/languagetool/issues/204 - this has been an open issue for years.

**Comment by Discostu36** [comment]
OK, thanks.
