### ISSUE TITLE
non-breaking space before question mark etc.

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1237]
I wonder whether this rule should maybe be turned off by default at least for the browser add-on? I guess users typically don't enter non-breaking spaces in emails?

![french-rule](https://user-images.githubusercontent.com/857004/47639337-4cb45f00-db61-11e8-8177-2fa261888a34.png)

@dpelle Do you have any opinion on this?

**Comment by PoorPocketsMcNewHold** [comment]
Those special space characters in French, are obviously never used, as this character is a special character hard to type.
But despite that, This is something that we should keep, as it is actually the right way to type. Also, this shouldn’t produce any issues with older devices.

**Comment by danielnaber** [comment]
This rule is not active anymore by default, closing.
