### ISSUE TITLE
Misdetection of unpaired symbol

### ISSUE THREAD

**Issue by jailby** [languagetool-org/languagetool#1248]
Hello,

Language tool is flagging a few `unpaired symbol` errors that should not be flagged:
![example](https://user-images.githubusercontent.com/1370401/48023887-0afd5880-e10d-11e8-9444-301ea179572e.png)

I was using the Firefox plugin and it was flagged in a Wordpress editor.

The following text was flagged (I removed emails):
`[contact-form to='q@q.q' subject='New Message from q.q'][contact-field label='Name' type='name' required='1'/][contact-field label='q' type='text'/][contact-field label='Email Address' type='email' required='1'/][contact-field label='Message' type='textarea' required='1'/][/contact-form]`

Note: it is also flagging it in the Github issue.

I believe it is flagged because it is displayed on multiple lines. 

Let me know if you need additional information.

**Comment by jailby** [comment]
I'm not sure if the question is addressed to me.

This is indeed not natural language. 

I would however recommend resolving the issue instead of removing this part during pre-processing. It would be a more helpful contribution to LT.

I believe that the problem either come from the multi-line display of the text or the special characters in this text.

**Comment by danielnaber** [comment]
LanguageTool needs plain text to work on, so the add-on would need to remove this. I'm not sure what kind of syntax this is. I'll close this, as our ability to support all the world's syntaxes is just too limited.
