### ISSUE TITLE
How to add user defined directory to the number of know words

### ISSUE THREAD

**Issue by vogella** [languagetool-org/languagetool#126]
AFAICS languagetool uses a fixed list of words for its spell check. Is their a way to add words via the API to the check? 

For example I write tutorials for developing with Java. Now I want to tell Languagetool that "IAdaptable" is OK for me.

**Comment by AvinashKalivarapu** [comment]
I am working on adding new words to make a custom dictionary. I found this issue through google.
But this link " [http://languagetool-user-forum.2306527.n4.nabble.com/New-Spell-checking-feature-any-way-to-use-a-custom-dictionary-td4640575.html#a4640577](http://languagetool-user-forum.2306527.n4.nabble.com/New-Spell-checking-feature-any-way-to-use-a-custom-dictionary-td4640575.html#a4640577) " seems broken or missing.
Could you please provide me with the required information.
Thanks

**Comment by danielnaber** [comment]
The link is now https://forum.languagetool.org/t/new-spell-checking-feature-any-way-to-use-a-custom-dictionary/74
