### ISSUE TITLE
[de] False positive for: Die Malerarbeiten

### ISSUE THREAD

**Issue by PAX523** [languagetool-org/languagetool#1267]
A customer reported a false positive for following sentence:

> Als Nachweis zur Schadenhöhe für die Malerarbeiten zukommen lassen.

On https://languagetool.org/ the part ``die Malerarbeiten`` is getting marked as grammar error (issue with noun marker).

**Comment by danielnaber** [comment]
It's a wrong split (`[Mal, erarbeiten]`), will add it to the exceptions.
