### ISSUE TITLE
[DE] "Rückzugsorte" wird falsch erkannt

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1274]
Moin liebes LanguageTool-Team

![grafik|690x367](upload://tZyrNpPRI7M9S3o6rUfSS0gcSOb.png)
![grafik](https://user-images.githubusercontent.com/40240507/48982585-df0a3d00-f0e4-11e8-8e0d-60441184be64.png)

Rückzugsorte ist richtig, weswegen ich diesen Fehlalarm nicht verstehe, aber er ist immerhin selten.

Bitte fixen, wenn ihr Zeit habt.

Grüße Dallun511

Original Therad: https://forum.languagetool.org/t/de-fehlalarm-bei-ruckzugsorte/3471

**Comment by danielnaber** [comment]
Fixed in jwordsplitter

**Comment by janschreiber** [comment]
Can we close this issue?

**Comment by danielnaber** [comment]
It's fixed but the fix is not yet in LT, so maybe we keep it open for now.
