### ISSUE TITLE
[en] countable nouns

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1279]
> Instead of maintaining 6 page templates for each language

"page" is incorrectly detected as an error.

![bildschirmfoto 2018-11-30 um 07 56 25](https://user-images.githubusercontent.com/37363/49273543-a0260f80-f475-11e8-88bf-cacd1511f1b5.png)

**Comment by TiagoSantos81** [comment]
Given that "6 page" is acting as an adjective, shouldn't it be hyphenated? Just like, for example, the "6-meter cable" vs "6 meters of cable". Although the correction suggested is wrong, it is pointing to a real problem, right?

**Comment by tiff** [comment]
@TiagoSantos81 thank you
