### ISSUE TITLE
[fr] Ascii smiley detected as misspelling

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1291]
> Bonjour :)

![bildschirmfoto 2018-12-08 um 19 08 32](https://user-images.githubusercontent.com/37363/49689117-b3437a00-fb1c-11e8-9ed4-14f68f4dd7f8.png)

**Comment by baarsrj** [comment]
This is for all languages, I guess. I guess it could be corrected in the tokenizer, but there is a lot of asci 'art'. And it is not 'normal' text. Nevertheless it would be possible to do so, a bit like is done with urls and mail addresses (stitching together). The smiley would then become full tokens, with consequences for spell checking and more.
