### ISSUE TITLE
[en] "why does implementing"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1293]
The text seems correct. Not sure if this is a bug. (@MikeUnwalla ?)

> Why does implementing or changing XYZ not satisfy the requirements?

![bildschirmfoto 2018-12-09 um 19 20 13](https://user-images.githubusercontent.com/37363/49701068-78f2df00-fbe7-11e8-959a-57accc3ae983.png)

**Comment by MikeUnwalla** [comment]
@tiff , I agree. The text is correct.
