### ISSUE TITLE
[DE]Der Pro/ Das Pro

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1294]
Moin liebes LanguageTool-Team

Der Profi, kurz der Pro wird als Fehler makiert. Mir ist bewusst, dass Ihr mir gesagt habt, dass Ihr dies nicht ändern wollt. Aber selbst Wikipidia nutzt diese Abkürzung.

"Sportler, die ihre Einkünfte in der Hauptsache aus ihrer Sportart beziehen, werden als Berufssportler, kurz (umgangssprachlich) Profisportler bzw. Profi oder **Pro** genannt. So gibt es Fußballprofis (siehe Profifußball), Tennisprofis usw. (siehe Profisport). Während in der Geschichte des Sports bis 1981 zwischen olympischen Amateuren und Profis unterschieden wurde, gibt es seit der Zeit meist gemischte Formen, da die meisten wie ein Kleinunternehmer verschiedene Einkommensformen mischen müssen."
Quelle: https://de.wikipedia.org/wiki/Profi#Profi_und_Amateur_im_Sport

Der Pro ist weit verbreitet im Sport- und Gamebereich. Ich kann verstehen, dass Ihr nicht der Pro aufnehmen wollt, weil das zu nicht gewollten Nebenwirkungen führen kann.

Aber könntet Ihr einige Ausnahme einfügen?

Z.B “Sie ist der stärkste Pro, den ich je gesehen habe.”
„Deine Schülerin ist ein Rookie und sie soll gegen einem Pro kämpfen?“

Was bleiben kann, wäre, wenn das LanguageTool bei “der Pro” trotzdem einen Fehler anzeigt und meldet:
“Wenn Sie der Pro (Profi) meinen, können Sie diese Meldung ignorieren, wenn Sie aber das Pro (Argumentation) meinen, liegt hier ein Fehler vor.”

Was auch eine Möglichkeit wäre, die Möglichkeit, dass diese Regel vom User selbst von Hand erst aktiviert werden muss, damit formelle User nicht beeinträchtigt wird. Ich selbst benutze das Pro sehr, sehr selten, weswegen es mich nervt, dass “der Pro” immer bemängelt werde.

Wahrscheinlich könnte es schwer werden, eine perfekte Lösung zu finden, aber einen Mittelweg zu kreieren, sollte möglich sein. Die Online-Version kann ja diese Regel deaktiviert haben, denn die Regel kann gegebenenfalls separat überprüft werden.

Was halten andere Forumleser von dieser Ausnahme? Oder Haben Sie selbst Vorschläge, wie es möglich ist, dass “Der Pro” und “Das Pro” sinnvoll in einer Regel eingebaut werden kann?

Original Therad https://forum.languagetool.org/t/de-der-pro-das-pro/3595

Grüße Dallun511

**Comment by janschreiber** [comment]
Fixed in 8ace63ea09d02b54cdf6a1fe4ad158bcac8bff66.
