### ISSUE TITLE
[DE] Satzanfang wurde nicht erkannt.

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1298]
Moin liebes LanguageTool-Team

![grafik](https://user-images.githubusercontent.com/40240507/49808488-f5f39500-fd5c-11e8-8f0c-2c17a7dced9f.png)
Ein Threadripper oder doch ein i9 X? **Vielleicht** doch ein Ryzen 7 oder doch ein i7? Ich kann mich nicht entscheiden. Für die Gamer sind die Intel-CPUs die beste Wahl.

Könnte es sein, dass das "X", was für Extreme steht, nicht vom LanguageTool als Abkürzung erkannt wird und deswegen mit dem Fragezeichen einen Fehlalarm auslöst? Ich kann mir nähmlich nicht erklären, warum hier ein Fehlalarm sonst ausgelöst wird.

Grüße Dallun511 Ferewo

**Comment by tiff** [comment]
Ich kann das nicht mehr reproduzieren. @Dallun511 tritt das Problem noch auf?

**Comment by Dallun511** [comment]
@tiff Das Problem ist in der aktullsten Version behoben.
