### ISSUE TITLE
[DE] Ausnahme für „Wirst du sehen.“

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1301]
Moin liebes LanguageTool-Team

Deises Regel: 
https://community.languagetool.org/rule/show/DE_VERBAGREEMENT?lang=de-DE
schlägt beim folgenden Beispiel ein: „Wirst du sehen.“ Egal ob wörtliche Rede oder im normalen Satz.

"Wirst du sehen" ist eine normale Kurzantwort, welche sehr häufig gesagt wird, wenn es schnell gehen soll oder gerade gehen möchte, aber man trotzdem antworten möchte.

Ich bitte für "Wirst du sehen" eine Ausnahme zu erstellen, damit sie nicht als Fehler mehr anerkannt wird.

Grüße Dallun511

**Comment by f-knorr** [comment]
geschlossen, da Duplikat von #1023

**Comment by Dallun511** [comment]
Gut erkannt. Das habe ich glatt vergessen, bei der Anzahl an Meldungen.

Grüße Dallun511
