### ISSUE TITLE
Regeln temporär abstellen

### ISSUE THREAD

**Issue by Black56651** [languagetool-org/languagetool#1302]
Moin

Ich würde mich über eine Funktion freuen, welche das LanguageTool in die Lage versetzt, bestimmte Regeln, wie diese Regel “![grafik](https://user-images.githubusercontent.com/40240507/49810032-a1521900-fd60-11e8-9724-de240c2d788f.png)” zu ignorieren, weil es bestimmte Situationen in einer wörtlichen Rede oder anderen Textsmittel gibt, wo es aus Stillgründen nicht möglich ist, ein Synonym zu benutzen.

Ein Beispiel:
“Du kannst dich hier und jetzt selbst umbringen. Niemand würde es merken, wenn du meinst, dass du vor dir selbst einfach wegrennen kannst, dann bring dich um, dann wird deine Mutter nie wieder zurückkehren und deine Freunde würden sterben und du bist schuld. Du Nozomi Ferewo. Die Schande von Dallun Ferewo. Du hättest niemals geboren werden dürfen, die Welt wäre dir dankbar. Du bist für alles schuld. Du bist schuld, dass Dallun tot ist. Du bist schuld, dass Sakura entführt wurde. Du bist schuld, dass sie sich getrennt. Du bist …”

In diesem Beispiel ist das Personalpronomen "**Du**" gewählt worden, weil es um eine direkte Stellungsnahme über eine andere Person ist, wo ihr erklärt wird, dass sie einen Fehler begangen hat/begehen wird. Ich habe hier nicht wirklich die Wahl ein Synonym einzusetzen. Das LanguageTool erkennt, wie es sich auch gehört, die drei folgenden "**Du’s**" und makiert sie blau, aber hier kann und möchte ich nichts ändern.

LibreOffice bietet mir die Funktion bestimmte Sätze oder Wörter von der Rechtschreibung zu befreien, was das LanguageTool leider mir nicht bietet. zumindest zurzeit, damit Fehler, die beabsichtig sind, ignorniert werden. 

**Es ist nur möglich die Regel für den gesamten Text zu deaktiveren, was nicht vom Vorteil ist.**

Ist es möglich dem LanguageTool mit einer Funktion zu erweitern, womit sich das LanguagTool merkt, dass **ein Fehler gewollt ist** und **dieser Fehler nicht mehr zu berücksichtigen ist**, ohne gleich **die gesamte Regel für alle Dokumente zu deaktivieren**? Oder ist das völlig unmöglich?

Grüße euer Black5661

Orignialer Eintrag: https://forum.languagetool.org/t/de-erinnerung-einer-wunschfunktion/3543
Alter Eintrag: https://forum.languagetool.org/t/de-der-wunsch-einer-neuen-funktion/2654

**Comment by Dallun511** [comment]
@FredKruse 
Ich kann mich erinnern, dass du mir mal gesagt hast, dass man die Regeln temporär abstellen kann, wenn man auf "Regel ignorieren" in der Rechtschreibausgabe klickt. Das stimmt doch. Oder?
