### ISSUE TITLE
[en] "... give it a second try and ..."

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1306]
> I would be happy if you could give it a second try and send me your feedback.

I'm not a native English speaker but I think the text is correct.

![bildschirmfoto 2018-12-12 um 21 13 16](https://user-images.githubusercontent.com/37363/49896192-ea829580-fe52-11e8-8b43-219d435a58b9.png)

**Comment by MikeUnwalla** [comment]
@tiff , yes, in this context, the text is correct.
