### ISSUE TITLE
[DE] Verschiedene Profile für das LanguageTool

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1308]
Moin liebes LanguageTool-Team und LanguageTool-User

Ich habe neue Idee, welche sich spezial an duale Power User wendet, die in zwei Bereichen, wie Schriftsteller, Autoren und Journalisten, arbeiten. Das LanguageTool unterscheidet zwischen Umgangssprache und Bildungssprache oder gehobene Sprache. Ein Schriftsteller und ein Autor kann in vielen Fällen Umgangssprache gebrauchen, weswegen er oder sie diese Regeln, welche auf die Umgangssprache hinweisen, deaktiviert.

Aber was ist, wenn er oder sie einen formellen Brief schreiben will?

Richtig, die formellen Regeln sind deaktiviert und das LanguageTool kann nicht mehr helfen, weil der User die Regeln manuell deaktiviert hat. Also muss er oder sie sie mühsam wieder aktivieren, was ein wenig zeitaufwendig ist.

Wenn der formelle Brief geschrieben und überprüft wurde, müssen die Regeln für das Projekt wieder deaktiviert werden, was wieder zeitaufwendig ist. Sollte das öfter vorkommen, wird es ziemlich nervig, wodurch das LanguageTool zur Qual wird und nicht mehr wirklich hilft, weil der User seine Regel den Umgebungen seines Projektes anpassen muss.

Was ist die Lösung? Ihr könnt sogar selbst daraufkommen. Profile sind die Lösung. Ein formelles Profil für Briefe, Home Office oder Arbeiten an Projekten. Das informelle Profil für das Schreiben von Geschichten, Storys und weiteren literarischen Texten, die Umgangssprache enthalten dürfen. Zusätzlich kann noch ein drittes Profil für den User zur Verfügung stehen, um z. B. Regeln zu testen oder Bugs vom LanguageTool zu analysieren.

Ich bin überzeugt, dass diese Wunschfunktion ein wichtiger Schritt in die Zukunft ist. Es gibt wichtige Dokumente, wo das LanguageTool sein vollstes Potenzial ausschöpfen muss, um den Sachtext so formell wie möglich zu gestalten, während es auch unter uns Personen (wie mich) gibt, welche auch ihre Kreativität walten lassen und viele Regeln deswegen deaktivieren, um nicht gestört zu werden, wenn es sich um Umgangssprache handelt und nicht um einen grammatischen Fehler.

Was haltet Ihr von dieser Wunschfunktion? Ist das realistisch oder nicht möglich? Sind User im Forum, die sich ebenfalls verschiedene Profile wünschen, um für jede Situation gewappnet zu sein?

Ich freue mich schon auf Eure Antworten und ggf. auf die neue Funktion.

Mit freundlichen Grüßen Euer Dallun511 Ferewo

**Comment by baarsrj** [comment]
This could be useful for other languages just as well. I could think of several solutions to achieve this: 
1 create 'hard' profiles in the grammar.xml, and put rules (pointers) in there or not
2 Allow the user to define profiles, all initially filles with all rules; let him/her enable or disable rules. Be sure to add new rules to all profiles when updating; java as well as xml rules.

**Comment by Dallun511** [comment]
Tut mir leid, dass diesen Vorschlag nicht auf Englisch geschrieben habe, aber ich bin dieser Sprache nicht mächtig. Diese Funktion kann das LanguageTool revolutionieren, weil den User in die Lage versetzt, in verschiedenen Situationen die für ihn wichtigen Regeln zu deaktivieren oder aktivieren, um das Beste aus dem LanguageTool herauszuholen. Das LaguageTool hat genug Power, um das zu verwirklichen. Die Frage ist, ob die Entwickler genug Ideen und vor allem genug Power haben, um so eine Funktion zur Verfügung zu stellen, denn das LanguageTool müsste stark angepasst werden.

**Comment by danielnaber** [comment]
Ich schließe das hier mal, weil ich unter #1673 eine genauere Beschreibung angelegt habe.
