### ISSUE TITLE
[FR] grammar errors in wizard step #2 after Firefox extension installation

### ISSUE THREAD

**Issue by MagicFab** [languagetool-org/languagetool#1313]
After installing the Firefox extension, a wizard/tutorial shows up.

Step no. 2 shows this text :

**Maintenant, votre texte va être amélioré
Votre texte sera maintenant _vérifier_ dans tous les champs lors de la frappe.**

1. There is a missing dot to finish the first sentence;
1.  **Vérifier** should be **vérifié**.

**Comment by danielnaber** [comment]
Thanks, this will be fixed in the next release.
