### ISSUE TITLE
[es] false alarm, url detected as error

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1315]
Example url:
> https://www.google.com/analytics/terms/es.html

<img width="967" alt="bildschirmfoto 2018-12-20 um 10 09 47" src="https://user-images.githubusercontent.com/37363/50275416-96257a00-043f-11e9-87aa-4c539e5b1f80.png">

**Comment by baarsrj** [comment]
The maintainer @jmartorell could update the return statement in the tokenizer code to 
    return joinEMailsAndUrls(l);
as used on tokenizers for other languages.
I would not dare to do this, considering possible consequences, this short before a release.

**Comment by tiff** [comment]
Thanks.
@jmartorell can you look into this, or should somebody else take care?
