### ISSUE TITLE
[de] "einen pinken Koffer"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1321]
> Drei Kartons, einige Einkaufstüten, einen pinken Koffer. 

I think this sentence is perfectly fine.

![bildschirmfoto 2018-12-23 um 15 51 40](https://user-images.githubusercontent.com/37363/50384823-b9178e80-06ca-11e9-84f0-a1a8cba762b0.png)

**Comment by f-knorr** [comment]
Sound strange - I know. Everything is fine here (see, e.g., https://www.duden.de/rechtschreibung/pink)
