### ISSUE TITLE
[DE] "Durch" + "Verb" = "Durchverb"

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1326]
**Mon liebes LangaugeTool-Team**

**In diesem Therad geht es um zusammengesetzte Verben mit der Präposition und Adverb "Durch", die laut Duden immer zusammengeschrieben wird.** [Siehe Duden](https://www.duden.de/sprachwissen/rechtschreibregeln/getrennt-und-zusammenschreibung#K50)
****
- [ ] **Wird nicht bemägelt:** durch rennen
- [ ] **Wird nicht bemägelt:** durch sprinten
- [ ] **Wird nicht bemägelt:** durch laufen
- [ ] **Wird nicht bemägelt:** durch rushen [Siehe Wikipedia](https://de.wikipedia.org/wiki/Computerspieler-Jargon#R)
- [ ] **Wird nicht bemägelt:** durch stürmen
- [ ] **Wird nicht bemägelt:** durch schleichen
- [ ] **Wird nicht bemägelt:** durch blicken
- [ ] **Wird nicht bemägelt:** durch schauen
- [ ] **Wird nicht bemägelt:** durch führen
- [ ] **Wird nicht bemägelt:** durch kitzeln
****
**Letzte Aktulisierung: 14.01.2019**

**Mit freundlichen Grüßen Euer Dallun511**

**Comment by Discostu36** [comment]
Doch, wird bemängelt. Zumindest bei den Wörtern, die ich getestet habe, wird gefragt, ob das Wort substantivisch gebraucht wird und deshalb großgeschrieben werden müsste. ("Durch Laufen kann man abnehmen"). Es sollten aber natürlich beide Möglichkeiten vorgeschlagen werden (oder besser noch je nach Kontext nur eine von beiden).

**Comment by Dallun511** [comment]
Laut dem Duden werden die Verben zusammengeschrieben und das wird nicht bemängelt. Es gibt eine Fehlermeldung, aber sie müsste angepasst werden, mit einem Zusatz oder Hinweis.
