### ISSUE TITLE
[DE] Das Verb "Sicherstellen"

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1328]
**Moin liebes LanguageTool-Team**

**In diesem Therad widmen wir uns um das Verb "sicherstellen", das zusammengeschrieben wird.** [siehe Duden](https://www.duden.de/rechtschreibung/sicherstellen)
****
- [ ] **Wird nicht bemängelt** Die Beweise wurden **sicher gestellt**.
- [ ] **Wird nicht bemängelt** Wir haben alles sich **sicher gestellt**.
- [ ] **Wird nicht bemängelt** Ich hoffe, dass mein PC nicht **sicher gesellt** wurde.
- [ ] **Wird nicht bemängelt** Ich denke, er hat nichts zu verbergen, weswegen wir alles **sicher stellen** können.
- [ ] **Wird nicht bemängelt** Sie hat nichts **sicher zu stellen**.
****
**Mit freundlichen Grüßen Euer Dallun511**

**Comment by f-knorr** [comment]
**gesellt** contra **gestellt**

**Comment by Dallun511** [comment]
Rechtschreibfehler lässt grüßen. Dann ist natürlich alles in Ordnung.
