### ISSUE TITLE
[de] "wider" vs. "wieder" 

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#1337]
These mistakes are not detected:
- [ ] Ich mache jetzt Feierabend und bin dann morgen wider da.
- [ ] Bitte komm bald wider.
- [ ] Was soll das jetzt schon wider?

Maybe a confusion pair could be created.

**Comment by Dallun511** [comment]
Das gleiche habe ich für "nichts und nicht" vorgeschlagen. Auf "wider und wieder" bin ich noch nicht gekommen, weswegen ich für deinen Vorschlag bin. Solche Wörter sind leicht zu verwechseln, weil nur ein Buchstabe die Bedeutung entscheiden kann.

Grüße Dallun511
