### ISSUE TITLE
[de] Wrong suggestions: "widerkommen" etc.

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#1338]
![widertreffen](https://user-images.githubusercontent.com/30999326/50729904-6d40fc80-1142-11e9-9a42-38becd08ac93.png)

The word "widertreffen" doesn't exist and therefore shouldn't be suggested.

The same happens for "wider treffen" etc.

**Comment by Dallun511** [comment]
Das stimmt, dass dieses Wort nicht existiert. Hier denkt das LanguageTool nur, dass wider + treffen aufgrund der Regel zusammengeschrieben wird. Das ist leider kein Einzelfall und sollte behoben werden.

Grüße Dallun511
