### ISSUE TITLE
[en] "Did anyone here the noise"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1342]
> Did anyone here the noise?

or 

> Did anyone here gunshots?

or 

> Did you here the noise?

is not detected while 

> Did you here the sound?

is.

**Comment by tiff** [comment]
More examples:
> Can you here the music?
> Can you here the birds?
> Do you here the people sing?

The other way around:
> Come and visit me hear!

**Comment by evan-defran-lt** [comment]
https://github.com/orgs/languagetooler-gmbh/projects/46/views/3?pane=issue&itemId=23817803
