### ISSUE TITLE
[de] "Vielen Dank für Ihre Schreiben"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1345]
> Vielen Dank für Ihre Schreiben

![bildschirmfoto 2019-01-08 um 20 58 45](https://user-images.githubusercontent.com/37363/50855476-3a884580-1388-11e9-9322-2ee334dd3ede.png)

**Comment by danielnaber** [comment]
Hat eine korrekte Lesart, wenn Schreiben plural ist, stimmt es ja.

**Comment by tiff** [comment]
you're right. close?
