### ISSUE TITLE
[de] "Ende diesen Jahres" false alarm?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1347]
> Eigentlich ist der Abschluss erst Ende diesen Jahres fertig.

![bildschirmfoto 2019-01-11 um 09 00 31](https://user-images.githubusercontent.com/37363/51020635-6d485e80-157f-11e9-9597-70a11c9bf438.png)

Not sure but I think "diesen Jahres" is correct here

**Comment by Discostu36** [comment]
No false alarm, but a very common mistake.

https://www.korrekturen.de/beliebte_fehler/diesen_jahres.shtml

**Comment by tiff** [comment]
Very interesting. Thanks!

**Comment by danielnaber** [comment]
I think this is so common we should have a special rule for this that has a more detailed explanation + link.
