### ISSUE TITLE
[de] false alarm "das Wochen dauern"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1348]
> Möglicherweise wird das Wochen dauern.

![bildschirmfoto 2019-01-11 um 09 05 00](https://user-images.githubusercontent.com/37363/51020837-09726580-1580-11e9-8734-38655d749ca4.png)

**Comment by f-knorr** [comment]
fixed with commit 8384617b643c43f1dc0d299814830b6ae3d23965
