### ISSUE TITLE
[de] [it] [fr] [es] domain marked as misspelling

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1350]
> google.com

German: 
![bildschirmfoto 2019-01-11 um 14 22 14](https://user-images.githubusercontent.com/37363/51036074-52d8aa00-15ac-11e9-917c-e1881d6e70e6.png)

Spanish:
![bildschirmfoto 2019-01-11 um 14 21 52](https://user-images.githubusercontent.com/37363/51036108-684dd400-15ac-11e9-87b1-4bf336a5466e.png)

French:
![bildschirmfoto 2019-01-11 um 14 22 05](https://user-images.githubusercontent.com/37363/51036118-700d7880-15ac-11e9-9ec3-98c14b072e24.png)

Italian:
![bildschirmfoto 2019-01-11 um 14 21 36](https://user-images.githubusercontent.com/37363/51036131-77cd1d00-15ac-11e9-9fef-6054e34eecee.png)

**Comment by Dallun511** [comment]
Bei "German" "google.com" liegt das Problem beim Wörterbuch, dass keine "Links" im Wörterbuch aufgenommen hat. Wenn sie Links schreiben wollen, die nicht als Fehler anerkannten werden sollen, empfehle ich ihnen "https://google.com" eingezugeben, wodurch es zu einem Hyperlink wird. Sollten Sie das nicht mögen, empfehle ich ihnen "google.com" ins Benutzerwörterbuch hinzufügen, weil Internetadressen nicht ins offizielle Wörterbuch aufgenommen werden, weil es auf die Dauer keinen Sinn ergibt gibt.

Das gleiche können Sie für die anderen Sprachen übertragen. Kein Wörterbuch braucht "google.com", wenn es die Hyperlink-Funktion gibt. Das gilt auch für das LanguageTool. Ich kann verstehen, dass es sehr nervig ist, wenn der Link als Fehler angesehen wird, obwohl er einer ist, aber damit müssen Sie wahrscheinlich leben. Ich muss auch damit leben, dass meine "Wortneuschöpfungen" oder seltene Wörter nicht mit ins Wörterbuch aufgenommen werden. Ich bitte diese zu entschuldigen.

Grüße Dallun511

**Comment by dpelle** [comment]
Why do I see "(langage: Anglais)" in the French screenshot in the bug report?!

1) language in such context would be "langue"  (not langage)
2) but I don't even understand why the message says that anyway.
3) The name of the language "Anglais" should not be capitalized in French (unlike what is English that capitalize names of languages)
4) Where are those those translations? I briefly looked for them in Transifex but did not find them.

Same for Italian and Spanish screenshots.

**Comment by danielnaber** [comment]
@dpelle They are at webtranslateit.com. I will send you an invitation.

**Comment by tiff** [comment]
oh, thanks for noticing @dpelle !

**Comment by danielnaber** [comment]
@dpelle the keys is `accepted_in_alt_language` in transifex (https://www.transifex.com/dnaber/languagetool/translate/#fr/messagesbundleproperties/153943632?q=key%3Aaccepted_in_alt_language)

**Comment by tiff** [comment]
@dpelle @danielnaber it is still saying `langage`:
![bildschirmfoto 2019-01-19 um 17 58 38](https://user-images.githubusercontent.com/37363/51429892-f4e33c80-1c13-11e9-96b6-839e979cd422.png)

**Comment by danielnaber** [comment]
`langage` -> `langue` will be fixed with next update ("Anglais" is still uppercase, though)

**Comment by danielnaber** [comment]
closing, issue seems to be fixed
