### ISSUE TITLE
[de] false alarm: "Rechnungen für die die Leistung in 2018 erbracht wurde."

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1358]
> Rechnungen für die die Leistung in 2018 erbracht wurde.

<img width="456" alt="bildschirmfoto 2019-01-16 um 10 16 30" src="https://user-images.githubusercontent.com/37363/51238702-d06b3400-1977-11e9-92d3-f12f9e6fc84d.png">

**Comment by janschreiber** [comment]
This is a false alarm and misleading, but please note that adding a comma before the word "für" will remedy the situation. LT will then be able to detect the "für die die..." part as a relative clause.

**Comment by tiff** [comment]
@janschreiber thanks for the heads up.

**Comment by tiff** [comment]
this isn't happening anymore
