### ISSUE TITLE
[pt] potential new words

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1363]
Words that users often add to their dictionary and that are not accepted in Portuguese. @TiagoSantos81 Could we add these to `spelling.txt`?

```
Fortnite
Photoshop
Alexander
Chrome
Andreas
Gmail
Spotify
Xiaomi
Craigslist
DHL
Bing
Minecraft
Snapchat
AutoCAD
Twitch
Alibaba
```

**Comment by marcoagpinto** [comment]
@TiagoSantos81 

Hello!

Tiago, can you confirm if the words above are all names of the kind:
NPMS000
?

If so, I will add their POS tomorrow.

Thank you!

**Comment by TiagoSantos81** [comment]
Thank you @danielnaber
