### ISSUE TITLE
[de] Dr Karl Meier

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1367]
> Dr Karl Meier

I think it should suggest "Dr."

![bildschirmfoto 2019-01-19 um 17 43 53](https://user-images.githubusercontent.com/37363/51429737-df6d1300-1c11-11e9-9e41-2e692c68e73e.png)

**Comment by tiff** [comment]
Same for "Nr"

> Du bist Nr 2837

![bildschirmfoto 2019-01-19 um 17 49 04](https://user-images.githubusercontent.com/37363/51429787-8c479000-1c12-11e9-9fe7-6581ad00e088.png)

**Comment by Dallun511** [comment]
Es heiß **"Nr."** und **"Dr."** Es fehlt der Punkt. Bestimmte Abkürzungen kriegen im deutschen einen Punkt.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/51433596-f3366a80-1c4d-11e9-9ed7-2652e708daf6.png)

**Comment by tiff** [comment]
Hallo @Dallun511, mir ist bewusst, dass es `Dr.`, `Prof.` oder `Nr.` heißen muss. Die Vorschläge, die angezeigt werden, wenn man den Punkt vergessen hat, sind nur leider wenig hilfreich.

Bei dem Wort `bzw` funktioniert das bereits:
<img width="412" alt="bildschirmfoto 2019-01-20 um 00 57 43" src="https://user-images.githubusercontent.com/37363/51433608-75bf2a00-1c4e-11e9-86d6-af69a8b83b0c.png">

**Comment by Dallun511** [comment]
@tiff kann verstehen, dass sie darauf hingewiesen werden möchten, dass der Punkt vergessen wurde. Mit einer Regel wäre das natürlich möglich. Aber ob das vom Wörterbuch übernommen wird, weiß ich nicht.

**Comment by tiff** [comment]
@f-knorr thanks for fixing it. I just realized that this also happens with "Prof", "Ing" (Ingenieur), "Mag" (Magister), "med" (Dr. med.) and probably others
