### ISSUE TITLE
[en] false alarm for "the follow up task"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1371]
> Here's the follow up task.
> Here's a follow up task.

I think it should detect "follow up" and suggest "follow-up" (https://dictionary.cambridge.org/de/worterbuch/englisch/follow-up)

![bildschirmfoto 2019-01-21 um 08 32 58](https://user-images.githubusercontent.com/37363/51458973-42b48d80-1d57-11e9-9dca-8adf503f63d9.png)

**Comment by MikeUnwalla** [comment]
Fixed in https://github.com/languagetool-org/languagetool/commit/4773eab686af7df7bc3a3dbda9484ca3d6930f0f
