### ISSUE TITLE
[de] "Dich hats voll erwischt"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1372]
> Dich hats voll erwischt

I think we should either suggest "hat es" or treat this as being correct. 

See Duden: https://www.duden.de/rechtschreibung/haben_besitzen_aufweisen_erhalten

![bildschirmfoto 2019-01-21 um 13 14 53](https://user-images.githubusercontent.com/37363/51474178-c9309580-1d7e-11e9-8eb4-da0773ba2840.png)

**Comment by f-knorr** [comment]
suggest: "hat es"
