### ISSUE TITLE
[en] "with comma" false alarm?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1375]
> With period or with comma?

<img width="475" alt="bildschirmfoto 2019-01-22 um 09 59 39" src="https://user-images.githubusercontent.com/37363/51523684-82997480-1e2c-11e9-86c4-bbb20f67aa8e.png">

**Comment by danielnaber** [comment]
Very difficult to improve. We already have selected the internal threshold so that this happens rarely. Changing it would mean we find fewer errors (precision/recall trade-off).

**Comment by marshinkar** [comment]
still occurs, however, LT also now suggests "a period". Once this is accepted, LT suggests "a comma" and thereafter no FP occurs.
I am closing this issue.
