### ISSUE TITLE
[en] "Only a reload will fix this." false alarm?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1379]
> Only a reload will fix this.

<img width="391" alt="bildschirmfoto 2019-01-23 um 19 18 57" src="https://user-images.githubusercontent.com/37363/51627868-c59a3b80-1f43-11e9-9ff7-8086bcc02d43.png">

Not sure about this.

**Comment by MikeUnwalla** [comment]
No, not a false alarm. In standard English, 'reload' is a verb. I improved the message.
