### ISSUE TITLE
[nl] "design-analyse" strange false alarm 

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1391]
I don't speak any dutch but this seems to be a wrong suggestion, is it?

![bildschirmfoto 2019-01-29 um 16 16 59](https://user-images.githubusercontent.com/37363/52044271-05fc4980-2542-11e9-89ba-572c05c7a924.png)

**Comment by evs-xsarus** [comment]
Well, it's a combination of English/Dutch. It's becoming more and more the default to use English words for which good Dutch words exist. If it's a good progression, we shouldn't discuss here.

On this suggestion. I would suggest the following: 'ontwerpanalyse'.

**Comment by tiff** [comment]
"ontwerpanalyse" sounds good to me :)

**Comment by baarsrj** [comment]
designanalyse is a valid but ugly compound. Unfortunately, supporting compounds for Dutch requires more sophitication in the routine than is currently supplied. And it is impossible to have all words in a words list.
