### ISSUE TITLE
Context in json response

### ISSUE THREAD

**Issue by enpepet** [languagetool-org/languagetool#1393]
The context shown is wrong when using annotatedtext with markup and interpretAs.
The resulting JSON context is not right.
The problem is that function getTextWithMarkup() returns all text parts  including "interpretAs" and this produces a final text with duplicated parts because there is markup and interpretAs at text used to get the context.
Maybe a solution is to ignore "interpretAs" textparts when building context with markup.

This happens in RuleMatchesAsJsonSerializer.java :
`
 private void writeContext(JsonGenerator g, RuleMatch match, AnnotatedText text, ContextTools contextTools) throws IOException {
    String context = contextTools.getContext(match.getFromPos(), match.getToPos(), text.getTextWithMarkup());
`

And in AnnotatedText.java
`
 public String getTextWithMarkup() {
    StringBuilder sb = new StringBuilder();
    for (TextPart part : parts) {
      sb.append(part.getPart());
    }
    return sb.toString();
  }
`

I think with this change it will work:
`
 public String getTextWithMarkup() {
    StringBuilder sb = new StringBuilder();
    for (TextPart part : parts) {
      if (part.getType() == TextPart.Type.TEXT || part.getType() == TextPart.Type.MARKUP) {
        sb.append(part.getPart());
      }
    }
    return sb.toString();
  }
`

**Comment by danielnaber** [comment]
Thanks for the report, could you post a short unit test that shows the issue?

**Comment by enpepet** [comment]
> Thanks for the report, could you post a short unit test that shows the issue?


I think it can be something like this:

`
public class AnnotatedTextTest {
  
  @Test
  public void test() {
    AnnotatedText text = new AnnotatedTextBuilder().
            addText("hello ").
            addMarkup("<p>","\n\n").
            addText("more xxxx text!").
            build();
    assertThat(text.getPlainText(), is("hello \n\nmore xxxx text!"));
    assertThat(text.getTextWithMarkup(), is("hello <p>more xxxx text!"));
    ContextTools contextTools = new ContextTools();
    assertThat(contextTools.getContext(13, 17, text.getTextWithMarkup()), is("hello <p>more xxxx text!"));
  }

}
`

**Comment by danielnaber** [comment]
Should be fixed now, thanks again for the report.
