### ISSUE TITLE
`get's` not recognized as error

### ISSUE THREAD

**Issue by rico-chet** [languagetool-org/languagetool#1395]
Hello, I am new to the LT, so please bear with me if it's a well-known issue.

## Motivation

Currently, I am looking for a way to make LT analyze git commits and show hints on possible language issues. Here's a [real example](https://review.coreboot.org/c/coreboot/+/30686/32//COMMIT_MSG). Specifically, I expect LT to bark at _get's used_, which it fails to.

A simple test: _The air get's colder._ should be recognized as incorrect.

## Rule approach
So I went on and tried to form a new rule with the [rule editor](https://community.languagetool.org/ruleEditor2) and found that the _part-of-speech_ analysis is broken by the apostrophe. So next best thing would be defining a very verbose regex rule which takes a long list of English verbs and forbids a POS+POS after such a verb. I don't feel this is feasible.

## Possible solution
Is there a way to build the rule using a placeholder for _English verb_ followed by two POS-es to work around the issue with part-of-speech analysis?

**Comment by danielnaber** [comment]
Maybe @MikeUnwalla has an idea. The problem seems to be that `DT_JJ_NN_NN` disambiguates too much in this case.

**Comment by MikeUnwalla** [comment]
I corrected the disambiguation for DT_JJ_NN_NN (https://github.com/languagetool-org/languagetool/commit/112ebef0c6c7aa7172f4b8e404ed995ce5abc926)

**Comment by MikeUnwalla** [comment]
In the next few days, 'll make a rule for "get's", because most instances are likely to be errors. ('get' noun is rare: https://en.oxforddictionaries.com/definition/get).
