### ISSUE TITLE
[de] "Trans- und Homosexuelle" (false alarm)

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1400]
> Trans- und Homosexuelle

![bildschirmfoto 2019-02-03 um 17 13 01](https://user-images.githubusercontent.com/37363/52179158-fba6ad80-27d6-11e9-88de-6f040aa2b44f.png)

**Comment by Dallun511** [comment]
Passiert dieser Fehler nur auf der Homepage oder auch wo anders? Diese Information wäre vielleicht wichtig.

Grüße Dallun511
