### ISSUE TITLE
[de] "vertragsbedingt" (false alarm)

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1404]
> Das ist vertragsbedingt.

![bildschirmfoto 2019-02-03 um 18 00 31](https://user-images.githubusercontent.com/37363/52179689-a7eb9280-27dd-11e9-8564-a5f69459b861.png)

**Comment by f-knorr** [comment]
Please report missing via "Suggest word for dictionary"

**Comment by tiff** [comment]
Done!
