### ISSUE TITLE
[de] "draufstand" (false alarm?)

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1406]
> Während er draufstand.

![bildschirmfoto 2019-02-03 um 18 09 36](https://user-images.githubusercontent.com/37363/52179795-ea619f00-27de-11e9-801a-b770e2f81959.png)

**Comment by f-knorr** [comment]
Please report missing words via "Suggest word for dictionary"

**Comment by tiff** [comment]
Done!
