### ISSUE TITLE
[en] an a priory value

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#1412]
"Particle volume should not be treated as an a priory given value." LT assumes to replace 'an a' by 'a'. @MikeUnwalla, please, confirm that initial test sentence is correct.

**Comment by MikeUnwalla** [comment]
The initial test sentence is not correct. There are 2 articles in sequence (an a). The LT message is correct.

**Comment by MikeUnwalla** [comment]
Ah! Try 'a priori'.

**Comment by MikeUnwalla** [comment]
So, there should be a rule for 'a priory/priori'.

**Comment by kostyfisik** [comment]
Sure! It is not completely a false positive, but the underlining is wrong as soon as the problem was with the 'priory', which is a valid word.

**Comment by kostyfisik** [comment]
@MikeUnwalla Thank you!
