### ISSUE TITLE
[de] rule needed: „sich auf dem/den Heimweg machen“

### ISSUE THREAD

**Issue by Ordoviz** [languagetool-org/languagetool#1414]
„Freddie machte sich auf **dem** Heimweg.“ is not marked as an mistake, though it should be „Freddie machte sich auf **den** Heimweg.“ Matching this pattern is presumably not that easy because „auf dem Heimweg“ is itself not wrong – it’s only wrong if it’s surrounded by a form of „machen“ and „sich“.

**Comment by Discostu36** [comment]
The rule is already there (DEN_DEM [9]), it only needs to be extended to also work with Heimweg.
