### ISSUE TITLE
[de] rule needed: „wach halten/wachhalten“

### ISSUE THREAD

**Issue by Ordoviz** [languagetool-org/languagetool#1415]
The sentence „Man muss die Erinnerung an die Verbrechen der Nazis wach halten.“ doesn’t get marked as wrong (see https://www.korrekturen.de/wortliste/wachhalten.shtml). Any chance a grammar checker can detect this?

**Comment by janschreiber** [comment]
I consider this extremely difficult to do, because it involves semantics. What we could do is a check for tell-tale context words, such as "Interesse", "Erinnerung" etc., but this will very likely cause false positives.

**Comment by Ordoviz** [comment]
It could be solved by informing the user about the two possibilities and let them decide which spelling needs to be chosen.
