### ISSUE TITLE
case insensitive spell check in java

### ISSUE THREAD

**Issue by surekha1317** [languagetool-org/languagetool#1421]
I am trying to do case insensitive spell check using languagetool in java.

I have tried like this but did not work.
        for (Rule rule : langTool.getAllActiveRules()) {			
               if (!(rule instanceof SpellingCheckRule)) {
		     langTool.disableRule(rule.getId());
               }
               if (rule instanceof SpellingCheckRule)
               {
	               ((SpellingCheckRule)rule).setConvertsCase(true);
	              System.out.println(((SpellingCheckRule)rule).isConvertsCase());  //returns true
                }
         }
It is returning true but still failing on words like BLue, THis.
This is really important for me. Please help me.

**Comment by danielnaber** [comment]
I think this was solved in the forum, so I'm closing it.
