### ISSUE TITLE
SIGSEGV (0xb) at pc=0x00007f51eb5d87fe, pid=6, tid=169

### ISSUE THREAD

**Issue by valeriy-dp** [languagetool-org/languagetool#1426]
The last couple of days I have constant issues with language tool.
The last one is the title of this task.
I did not find the guide on how to create issues so please ask me about any additional information you need
```
Langtool v. 4.4-stable
The version of langtool is http server
```
Excerpt from dump
```
# JRE version: OpenJDK Runtime Environment (10.0.2+13) (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
# Java VM: OpenJDK 64-Bit Server VM (10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# J 7685 c2 java.lang.String.replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String; java.base@10.0.2 (149 bytes) @ 0x00007f467e7c98fe [0x00007f467e7c98a0+0x000000000000005e]
```

Here is the full dump https://gist.github.com/valeriy-dp/8d4132d6f29067ce54284a14a09beb07

**Comment by danielnaber** [comment]
Do you use the `-Xmx` parameter to specify the amount of memory for Java? If not, you should probably do that, e.g. like `-Xmx2000M`

**Comment by valVk** [comment]
Here is the command to launch instance of LT-server
```
java -Xmx1G -Xms1G -cp ./languagetool-server.jar org.languagetool.server.HTTPServer ${SP} --port 8081 --public --allow-origin '*' /path/to/ngram &
java -Xmx1G -Xms1G -cp ./languagetool-server.jar org.languagetool.server.HTTPServer ${SP} --port 8082 --public --allow-origin '*'
```

My server has 4GB physical RAM 

Thanks

**Comment by danielnaber** [comment]
I'm not sure, we're using the same OpenJDK version with 3 GB and it works fine. We're not using Docker, but also Ubuntu.

**Comment by valeriy-dp** [comment]
@danielnaber May it be that I'm running 2 instances on different ports but in one container/server?

**Comment by danielnaber** [comment]
> May it be that I'm running 2 instances on different ports but in one container/server?

Running on two ports shouldn't be an issue per se. But as we don't use docker, I cannot comment on the combination of docker / two instances of LT.

**Comment by valeriy-dp** [comment]
Thanks. 
So according to the dump, there is nothing too critical? I'm not a Java expert and it's too hard for me to outline useful information within 1000+ lines of dump

**Comment by danielnaber** [comment]
You're seeing a JVM crash. That's about as critical as it gets :-) But it's a JVM topic, nothing LT can do anything about.

**Comment by valeriy-dp** [comment]
Ok, then I close this issue.

Thanks
