### ISSUE TITLE
Wrong correction for some ' name'

### ISSUE THREAD

**Issue by miluki01** [languagetool-org/languagetool#1427]

**Comment by miluki01** [comment]
I am in a situation that needs to correct the query from the user. However, my database has some words like 'Kuma restaurant' and language tool corrects to 'human' when typing 'kuma'.
Is there any idea that I can fix it?
Thanks

**Comment by danielnaber** [comment]
Add your words to  `./org/languagetool/resource/XX/hunspell/spelling.txt` with `XX` being a language code.
