### ISSUE TITLE
[en] "cancelled" false alarm?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1435]
https://www.grammarly.com/blog/canceled-vs-cancelled/

Only happens for en-US

<img width="345" alt="bildschirmfoto 2019-02-26 um 09 34 26" src="https://user-images.githubusercontent.com/37363/53398366-ba568780-39a9-11e9-975b-d9d622a05463.png">

**Comment by MikeUnwalla** [comment]
What is the problem? 'cancelled' is BrE.

**Comment by tiff** [comment]
I thought both are supported by en-US but apparently that is not the case. Thanks Mike.

**Comment by MikeUnwalla** [comment]
Hi @tiff , sorry. You are correct:
https://ahdictionary.com/word/search.html?q=cancelled
https://www.merriam-webster.com/dictionary/cancelled

The rule MORFOLOGIK_RULE_EN_US is a Java rule, so one of the devs will need to deal with this problem. Daniel added this related rule: https://github.com/languagetool-org/languagetool/commit/61f469e17e1d7553987b21d2a2604dfa94e221ba

**Comment by tiff** [comment]
cc @danielnaber 
"cancelled" is one of the top ignored words in the web extension

**Comment by danielnaber** [comment]
If you want "cancelled" to be accepted for en-US, it should be enough to add it to `/en/hunspell/spelling_en-US.txt` I think.

**Comment by MikeUnwalla** [comment]
@danielnaber , yes! Doh! I will also add word pair in coherency.txt

**Comment by tiff** [comment]
thank you!
