### ISSUE TITLE
[DE] Fehlinterpretation der Regel: "'Mädchenname' statt 'Geburtsname'"

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1446]
Moin liebes LangaugeTool-Team

Ich möchte euch auf eine Fehlinterpretation der [Regel](https://community.languagetool.org/rule/show/MAEDCHENNAME?subId=1&lang=de-DE): "'Mädchenname' statt 'Geburtsname'" aufmerksam machen, die nicht in Vergessenheit geraten soll. Um das Problem genauer zu verstehen, habe ich kleine und einfache Beispiele diesen Therad hinzugefügt.
****
Beispiele:
- [x] Sandra ist **ein offizieller Mädchenname.**
LT: "Evtl. passt der geschlechtsneutrale Begriff "Geburtsname" besser. "

- [x] Sandra ist **kein offizieller Mädchenname.**
LT: "Evtl. passt der geschlechtsneutrale Begriff "Geburtsname" besser. "

- [x] Alex ist sowohl ein Jungs- als auch **ein Mädchenname.**
LT: "Evtl. passt der geschlechtsneutrale Begriff "Geburtsname" besser. "

- [x] Saskia, das ist wirklich **ein lächerlicher Mädchenname.**
LT: "Evtl. passt der geschlechtsneutrale Begriff "Geburtsname" besser. "
****

Bitte, wenn es möglich ist, die Regel schnell verfeinern, weil es sonst zu **Missverständnissen** kommen kann.

Mit freundlichen Grüßen Dallun511 Ferewo

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/54491092-f0599e00-48bb-11e9-9636-1904a39fe359.png)
Warum wurde dieser Therad geschlossen, wenn sich nichts geändert hat?
Das verstehe ich nicht.

**Comment by Discostu36** [comment]
Mh... hier funktioniert's.
![Screenshot_2019-03-18-07-08-35](https://user-images.githubusercontent.com/30999326/54510271-e59b1980-494c-11e9-8296-e9e303a39829.png)

**Comment by janschreiber** [comment]
Merkwürdig. Bei mir triggern die Beispiele nach wie vor die Fehlermeldung.

**Comment by danielnaber** [comment]
Die Server haben derzeit unterschiedliche Versionen von LT, wir arbeiten daran.

**Comment by janschreiber** [comment]
Es scheint jetzt zu klappen.

**Comment by Dallun511** [comment]
Freut mich zu hören.
