### ISSUE TITLE
[de] "Mit einem 100 er bezahlen"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1454]
> Mit einem 100 er bezahlen.

should be

> Mit einem 100er bezahlen.

or maybe:

> Mit einem Hunderter bezahlen.

**Comment by Dallun511** [comment]
Bei mir gibt's eine Fehlermeldung.

![grafik](https://user-images.githubusercontent.com/40240507/53980495-bb598880-4110-11e9-8d3f-4be965275b2b.png)

**Comment by tiff** [comment]
Der Vorschlag bezieht sich aber auf einen anderen Fehler:
![bildschirmfoto 2019-03-07 um 20 07 32](https://user-images.githubusercontent.com/37363/53982226-aa127b00-4114-11e9-9cf3-30d1cbb6f587.png)

**Comment by Dallun511** [comment]
Hoffentlich hast du Glück, das erkannt wird, dass "er" sich auf "100" bezieht und nicht aufs Verb "bezahlen" Aber eine Fehlermeldung ist besser, als keine.

Grüße Dallun511
