### ISSUE TITLE
Reset to default button

### ISSUE THREAD

**Issue by TiagoSantos81** [languagetool-org/languagetool#1456]
When using LanguageTool it is common to disable some rules using the 'Ignore All' function, since some rules do not apply to the text at hand. 
Those rule stay ignored over sessions, and in the plug-ins it is hard to track which rules have been ignored and going back to the options and find them is not always easy.
Adding a 'Reset' or 'Defaults' bottom to LanguagTool menu, or in the 'Options..' in the 'General', 'Grammar', and 'Style' Tabs would solve this issue.

**Comment by FredKruse** [comment]
A default button is added, which set back the profile for that it is used.
@TiagoSantos81: If you agree the issue could be closed

**Comment by TiagoSantos81** [comment]
@FredKruse 
This is very good and solves it for me, but it is not intuitive for the average user. Any chance of adding a ling to this function in the main LanguageTool menu in LibreOffice?
Something explicit along the lines of "Reset/delete Profile".

**Comment by FredKruse** [comment]
@TiagoSantos81 
Thank you for your comments. (I was on vacation so I can answer only now)
In principle it is possible to add a link in the main LanguageTool menu, but the meaning is unclear for me:

- If a delete Profile is done, the next (or default) profile has to be loaded. 
- If a reset is done the actual profile is set back to default options (and is overwritten).

I think it is difficult for a user to get the meaning.

**Comment by TiagoSantos81** [comment]
@FredKruse
Fred, given the way it work and the renaming of the function, I think I now understand better the issue.
So, a new profile is the (now called) 'Default Profile'.
However, once the user makes changes to the enabled rules, they are still saved in the now called 'Default profile'. This default profile with changes would be the user profile, and that is why there is a confusing outcome of the reset profile.
In my limited tests, I think there is a way to move this forward, but it robably it is too much work for this feature,
The compromises need by profiles resets can solved by automatically saving/switching to a 'User Profile ##', once the first rules became disabled. This automatic profile creation would also make it easier for users to create and manage profiles. 
If this is implemented, in the menu, it would be more sensible to just use a 'Switch to default profile', while the function to delete profiles would be hidden  in the 'Options'.

**Comment by FredKruse** [comment]
@TiagoSantos81 
Hi Tiago, I introduced a new Tab, to make the handling of profiles a bit easier to understand. I hope it helps a little.
The "Default profile" are the settings of previous versions of LT. If you create a new profile, then all settings of the current used profile will be adopted. This is to make it easy to create profiles which differs only by single settings.
If you like to create a new profile from the default options, you have to click the button "Apply default options" after you created a new profile. After that you can start to make changes from the default settings.
At last, I introduced a "Change profile to" item in the LT menu (only for LO/OO extension). So it is easy to switch between different profiles direct without run the option panel.

**Comment by TiagoSantos81** [comment]
@TiagoSantos81 
Hi Fred, Sorry for the late reply to https://github.com/languagetool-org/languagetool/commit/0c07cc20229df265bd3f77ac179ed1a1c9e86818#commitcomment-34689348.
I was still trying the new feature, and I still have to work with it a bit more, but so far it look better than what I suggested. New profiles inheritting settings is a well thought out idea.
Your implementation is clean and easy to use, and, from what I have tested, I think it solves the enhancement requests I have done regarding rule management, so I will close those.
If I can suggest one more thing regarding this, can you had an example "pre-configured" profile, so I can see what to edit in order to add Portuguese custom profiles? Is it just editing the default config file (the one shipped with LT)?
