### ISSUE TITLE
[en] false alarm "follow up"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1468]
> Here's the follow up task.

![Bildschirmfoto 2019-03-14 um 12 23 30](https://user-images.githubusercontent.com/37363/54353330-08c77f80-4654-11e9-9972-db206892debe.png)

Similar to https://github.com/languagetool-org/languagetool/issues/1371

**Comment by MikeUnwalla** [comment]
Why is this a false alarm? Suggestion 2 in the message explains the problem.

**Comment by tiff** [comment]
ah sorry, Mike. I was expecting the same behavior as here:

![Bildschirmfoto 2019-03-14 um 13 49 56](https://user-images.githubusercontent.com/37363/54358221-171b9880-4660-11e9-8a00-1099dc0c4cbf.png)

If the behavior is intended, feel free to close this issue.

**Comment by MikeUnwalla** [comment]
@tiff , it would be nice if the message were the same as the second example. (I think the message is good enough, but I'll leave the issue open because someone may disagree with me.)
