### ISSUE TITLE
There are test failures

### ISSUE THREAD

**Issue by angela-zhao** [languagetool-org/languagetool#1471]
After running `mvn clean test`, I get the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project languagetool-server: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/angela.zhao/Documents/Projects/languagetool/languagetool-server/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :languagetool-server
```

I am using Java 8 and have already tried installing an earlier release (v4.1) but am getting the same error. 

I have already read #1021 and #1039.

**Comment by danielnaber** [comment]
The relevant part is somewhere earlier in the output. Best is to post the complete output.

**Comment by angela-zhao** [comment]
@danielnaber The complete output exceeds the character limit for comments so I've attached it here as a text file.

[languagetool-error.txt](https://github.com/languagetool-org/languagetool/files/2968219/languagetool-error.txt)

**Comment by danielnaber** [comment]
These are the relevant lines:

```
org.languagetool.server.PortBindingException: 
LanguageTool HTTP server could not be started on host "localhost", port 8081.
Maybe something else is running on that port already?
```

The tests don't work because something (maybe even an instance of LT) is blocking port 8081.

**Comment by angela-zhao** [comment]
@danielnaber Thanks for your answer.

In my case, port 8081 is running McAfee Agent services (antivirus software) and I don't have the authority to kill the process. Is there any way to launch LanguageTool HTTP server on another port?

**Comment by danielnaber** [comment]
You could try adding `-Dlt.default.port=8082` to set a different port, like this: `mvn -Dlt.default.port=8082 test`

**Comment by angela-zhao** [comment]
> You could try adding `-Dlt.default.port=8082` to set a different port, like this: `mvn -Dlt.default.port=8082 test`

That worked! Thank you very much.
