### ISSUE TITLE
[en] "this happen" false alarm? 

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1477]
I'm not a native speaker but this sentence feels right:
![Bildschirmfoto 2019-03-19 um 07 46 39](https://user-images.githubusercontent.com/37363/54585748-42fd9c00-4a1b-11e9-9b0a-680844fd81f9.png)

> I don't see this happen anymore.

Is it a false alarm?

**Comment by MikeUnwalla** [comment]
The message is a false positive.

(Perhaps a more usual construction is "I don't see this happening anymore", but I can't see anything wrong with the sentence.)

**Comment by ZeeshanA1i** [comment]
That surely is a false-alarm. The actual sentence is a common type, for example, "I see this happen almost daily.". I find gerunds to also be common as in "I see this happening in various places.".

See the frequencies of different forms of a verb in such type of sentences [here](https://books.google.com/ngrams/graph?content=I+see+this+happen%2CI+see+this+happens%2CI+see+this+happening%2CI+see+this+happened&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2CI%20see%20this%20happen%3B%2Cc0%3B.t1%3B%2CI%20see%20this%20happening%3B%2Cc0#t1%3B%2CI%20see%20this%20happen%3B%2Cc0%3B.t1%3B%2CI%20see%20this%20happening%3B%2Cc0).

**Comment by MikeUnwalla** [comment]
The more that I think about this issue, the more confused I become. I searched the web briefly for an answer, but I did not find an answer.

These sentences are all incorrect grammar and LT finds the errors:

- I don't think this happen any more.
- I think this occur almost daily.
- I don't think this occur daily.
- If you think this happen anymore, you are wrong; it doesn't.

I guess that "I [don't] see this happen" is idiomatic. But, I am not sure.

**Comment by ZeeshanA1i** [comment]
It is not idiomatic at all. '[see](https://www.englishgrammar.org/bare-infinitive-2/)' in the sentence is used as a bare-infinitive. Eg: "I **saw** him **pass** along the street, and I **saw** him **come** into our house several times" (from [more](https://www.google.com/search?q=%22saw%20him%20come%22&tbm=bks&lr=lang_en)). [Here ](https://ludwig.guru/s/I+saw+him)are a few more examples.

**Comment by MikeUnwalla** [comment]
@ZeeshanA1i , thanks for the clarification and the links.
