### ISSUE TITLE
False positive in DATUM_ZUKUNFT_VERB_VERGANGENHEIT [14] 

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#1483]
Example: "Eine Veröffentlichung der ersten Version ist für den 25. März 2019 geplant."

Message: "Das Datum liegt in der Zukunft, aber das Verb ist in der Vergangenheitsform."

**Comment by Dallun511** [comment]
Es stimmt, dass das Datum in der Zukunft liegt, nur reden viele auch in der Perfektform in der Zukunft. Wir haben unseren Urlaub für 2020 geplant.

**Comment by xuiqzy** [comment]
Ich verstehe hier die Regel nicht ganz, das planen ist doch richtigerweise in der Vergangenheit im Perfekt? Was wäre denn der korrigierte Satz?

**Comment by danielnaber** [comment]
Ich kann den Fehlalarm nicht mehr nachvollziehen, also schließe ich das issue mal.

**Comment by janschreiber** [comment]
Mit demselben Beispielsatz (nur den Monat habe ich auf Dezember geändert) habe ich das Problem weiterhin.

**Comment by danielnaber** [comment]
Ach so... für "geplant" habe ich mal eine Ausnahme hinzugefügt.

**Comment by Discostu36** [comment]
Hier ein weiterer Beispielsatz, bei dem das Problem auftritt:

> Ab dem 01.01.2022 sind alle Rechtsanwältinnen und Rechtsanwälte verpflichtet, der Justiz Dokumente in elektronischer Form zu übermitteln.

LT scheint zu glauben, das "sind verpflichtet" ein Perfekt ist, obwohl es sich um eine Passiv-Konstruktion handelt.

**Comment by NicoWeio** [comment]
Weitere, vielleicht noch häufiger auftretende Beispiele:

> Die Veranstaltung wird auf den 13. Oktober 2025 verschoben.
> Die Veranstaltung wurde auf den 13. Oktober 2025 verschoben.
