### ISSUE TITLE
[pt] "Facebook" marked as misspelling

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1491]
![Bildschirmfoto 2019-03-29 um 08 57 17](https://user-images.githubusercontent.com/37363/55217827-bdd76b80-5200-11e9-8cb3-beeac383c1db.png)

Happens for all Portuguese variants except Portugal.

**Comment by TiagoSantos81** [comment]
@tiff Thank you for the report. Please, can you test and gather a few dozen corporate names in common usage that are not marked in part of the Portuguese variants, so I can add them to spelling all at once?

**Comment by tiff** [comment]
Here's a list of top 500 companies. Almost every one is marked as a misspelling https://docs.google.com/spreadsheets/d/1sJf9QUZ3S6NmXwzkxQhn6iifakv38PBCBEh-wkUCUaY/edit?usp=sharing

**Comment by TiagoSantos81** [comment]
> Here's a list of top 500 companies. Almost every one is marked as a misspelling https://docs.google.com/spreadsheets/d/1sJf9QUZ3S6NmXwzkxQhn6iifakv38PBCBEh-wkUCUaY/edit?usp=sharing

Perfect! 
Just one last thing, is this list compiled by you? If so, do I have permission to integrate fully in the several languages that LanguageTool uses? If not, under which license is this list?

**Comment by tiff** [comment]
@TiagoSantos81 it's from http://www.opendata500.com/us/list/

For some reason "Facebook" is not in the list...

**Comment by TiagoSantos81** [comment]
Excellent resource and with Creative Commons Attribution-ShareAlike 4.0 International License. I will keep the link. Thank you. I will add de 500+1 list to a few languages ASAP.

**Comment by tiff** [comment]
On second look I think this is only a list of companies contributing to the OpenData foundation.

Here's another one listing the top 500 companies from the US:
https://datahub.io/core/s-and-p-500-companies
https://docs.google.com/spreadsheets/d/1_-HekyDTR__vnNKrhKkxjhvGyqxgqmTJWSC5sb9ZpDc/edit?usp=sharing
