### ISSUE TITLE
[de] KOMMA_VOR_RELATIVSATZ false alarm

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1510]
> Bei einer Befragung der 21-jährigen stellten die Beamten Alkoholgeruch fest und ordneten eine Blutprobe an.

<img width="844" alt="Bildschirmfoto 2019-04-09 um 18 18 49" src="https://user-images.githubusercontent.com/37363/55817094-042ba500-5af4-11e9-8b70-9a0f5083e389.png">

**Comment by f-knorr** [comment]
Hier ist tatsächlich ein Fehler, und zwar müsste "21-jährigen" großgeschrieben werden. Dies wird nun bemängelt.

**Comment by tiff** [comment]
Hm, jetzt markiert er auch nicht mehr den Teil aus dem Screenshot. Danke!
