### ISSUE TITLE
[de] DE_CASE false alarm

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1512]
> Und das belegen Berichte und Gerichtsurteile.

<img width="399" alt="Bildschirmfoto 2019-04-09 um 18 31 45" src="https://user-images.githubusercontent.com/37363/55817959-dba4aa80-5af5-11e9-83b7-1b51ca0a6835.png">

**Comment by tiff** [comment]
Dasselbe passiert bei ähnlichen Sätzen:
> Und das zeigen Beweise.

Hier auch:
> Oder das zeigen Beweise.

Hier allerdings nicht:
> Das zeigen Beweise.

**Comment by tiff** [comment]
Wie immer: Danke für den Fix!

**Comment by tiff** [comment]
@f-knorr behebt dein Fix eigentlich zufällig auch https://github.com/languagetool-org/languagetool/issues/1519?

**Comment by f-knorr** [comment]
@tiff Nein
