### ISSUE TITLE
[de] DE_CASE issue with special character

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1515]
> ▶︎ Dies ist ein Test

> :) Dies ist ein Test

<img width="427" alt="Bildschirmfoto 2019-04-09 um 18 41 48" src="https://user-images.githubusercontent.com/37363/55818593-40143980-5af7-11e9-8d4b-fab00de28a37.png">

**Comment by tiff** [comment]
Selbes Problem:
> \* Dies ist ein Test
> • Dies ist ein Test

**Comment by danielnaber** [comment]
There are probably many more Unicode characters used this way, but I have started by adding those listed here. I'll see if there's a better approach than listing all characters.

**Comment by danielnaber** [comment]
One could use `\p{InGeometricShapes}` to cover all characters of the Unicode "geometric shapes" category, but it doesn't work with `▶︎` when copy-pasted from this page.

**Comment by danielnaber** [comment]
Closing, as the common cases are solved. More cases (other characters) would need to be added.
