### ISSUE TITLE
[DE] "Ich müssen" wird in der wörtlichen Rede nicht als Fehler markiert.

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1521]
Moin LanguageTool-Team

- [ ] **False:** Lucia sagt: „**Ich müssen** zur Schule.“
**True:** Lucia sagt: „**Wir müssen** zur Schule.“
**True:** Lucia sagt: „**Ich muss** zur Schule.“

Schnell fixen.

Grüße Dallun511

**Comment by f-knorr** [comment]
recently fixed
