### ISSUE TITLE
[DE] Regel "brauchen mit Infinitiv mit 'zu" schlägt (fragen) in Klammern vor

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1523]
Moin liebes LanguageTool-Team

Also brauchst du mich nicht **fragen.**
LT: "Die Verwendung von 'brauchen + Infinitiv' (ohne 'zu') ist umgangssprachlich. Standardsprachlich sollte ein erweiterter Infinitiv mit 'zu' verwendet werden."
Vorschlag:
![grafik](https://user-images.githubusercontent.com/40240507/77823678-31a2a180-70fd-11ea-87c8-4ea131442933.png)
Der Vorschlag "(fragen)" sollte entfernt werden.

**Update 2020:** Dieser Fehler ist immer noch vorhanden.

Grüße Dallun511

**Comment by f-knorr** [comment]
Wir haben hier eine Regel, mit der beide Inifinitivvarianten abgedeckt werden.
Deshalb steht hier immer eine Lösung in Klammern.
Bei einem erweiterten Infinitiv mit 'zu' (z. B. "aufzumachen") wäre es genau umgekehrt
