### ISSUE TITLE
Ignore TM

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1527]
e.g `Colorfront Engine™ ` -  a user writes: "Note that this is a UTF-8 encoded Unicode superscript TM codepoint, not an html amper-trade-semicolon combo."

We should ignore `™` I guess?

**Comment by PoorPocketsMcNewHold** [comment]
I suppose yes, since we will have to add a certain list of Companies names to be really a useful rule.

**Comment by TiagoSantos81** [comment]
How many site do not work well with the UTF-8 symbol these days, for this to be relevant?

**Comment by danielnaber** [comment]
Closing, cannot reproduce the problem anymore.
