### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by mfelice** [languagetool-org/languagetool#1529]
Hello,

From the readme:

#### Scripted installation and building
To install or build using a script, simply type:
```
curl -L https://raw.githubusercontent.com/languagetool-org/languagetool/master/install.sh | sudo bash <options>
sudo bash install.sh <options>
```
However, this fails when trying to download https://languagetool.org/download/LanguageTool-stable.zip, since the file doesn't exist any more on the server. Instead, I downloaded "install.sh" and replaced "LanguageTool-stable.zip" with "LanguageTool-4.5.zip", the latest release available at https://languagetool.org/download/. 

I think the installation script should be updated and use a variable for the filename instead of having literal repetitions of the filename throughout the script. In addition, I don't see why you need the second line in the instructions (`sudo bash install.sh <options>`).

Hope this helps!
Mariano

**Comment by TiagoSantos81** [comment]
@mfelice Thank you for your report. The README.md should be clearer now.

**Comment by danielnaber** [comment]
https://languagetool.org/download/LanguageTool-stable.zip is missing because of a server misconfiguration, should be fixed soon.

**Comment by danielnaber** [comment]
Link should be fixed now.

**Comment by TiagoSantos81** [comment]
@danielnaber All reported problems looks fixed now with your change. I am closing this.
