### ISSUE TITLE
[de] "dass" vs "das"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1530]
> Ich weiß, das sie dort festhängt.

Mistake not found.

**Comment by Dallun511** [comment]
@tiff Fallen dir noch mehr Beispiele ein? Daran könnte man ein Muster erkennen, was sicherlich helfen kann.

Grüße Dallun511

**Comment by tiff** [comment]
Nicht erkannt:
> Ich wüsste nicht, das er was damit zu tun hat.

Aber das wird bereits erkannt:
> Ich wusste, das es falsch war

![Bildschirmfoto 2019-04-14 um 16 01 03](https://user-images.githubusercontent.com/37363/56093910-88a06e00-5ece-11e9-9600-60ec9c30d4c5.png)

**Comment by tiff** [comment]
Danke @f-knorr
