### ISSUE TITLE
"Thanks in advance" warned as "wordy"

### ISSUE THREAD

**Issue by ismail** [languagetool-org/languagetool#1531]
How to reproduce:

Go to https://languagetoolplus.com/ , write either "Thanks in advance" or "Thank you in advance" and get the following warning about being wordy:
![lp](https://user-images.githubusercontent.com/4255/56052934-f758bc80-5d52-11e9-92e4-00c0f787e99a.PNG)

What's more troubling here is that the suggestions are grammatically wrong.

**Comment by tiff** [comment]
@MikeUnwalla I think this is something related to languagetoolplus

**Comment by MikeUnwalla** [comment]
@tiff, yes it is. I don't know how to move the issue to the LT Plus Github bug tracker.

**Comment by ismail** [comment]
@MikeUnwalla Fixed or moved to internal tracker?

**Comment by MikeUnwalla** [comment]
@ismail , fixed. The change will be available tomorrow.

**Comment by ismail** [comment]
@MikeUnwalla fwiw this is still not fixed.

**Comment by danielnaber** [comment]
@ismail Fixed means it's fixed in the code, it takes longer for the fix to be deployed.

**Comment by ismail** [comment]
@danielnaber I do know that but please refer to "The change will be available tomorrow." which was 2 days ago, so I assumed deployment was done. I was wrong I guess.

**Comment by danielnaber** [comment]
@ismail The premium version doesn't have an automatic daily deployment of new updates, do it can take a while before a change is online.
