### ISSUE TITLE
Thanks and feedback

### ISSUE THREAD

**Issue by EtienneAb3d** [languagetool-org/languagetool#1536]
LanguageTool is now part of NeuroSpell, here for the English version:
http://neurospell.com/en.php

Thanks to all of you for the very nice work ! LangageTool is incredibly complementary with my experimental neural (Deep Learning) spell corrector !

Here is a small feedback. Perhaps these points are due to the way I read the documentation. You know, It's often hard to read line by line.
- I didn't see quickly that the Java entry point is JLanguageTool or MultiThreadedJLanguageTool. I had to search and browse the web site and the forum discussions. Possibly this link can be put right on the first README page:
http://wiki.languagetool.org/java-api
- it took me some times to discover that, while "fr" is using lexical search, this is not the case for "en". And a bit more time to discover that I needed to use a variant, like "en-GB", to get it working. Possibly it would be nice to add a kind of fallback.
- it was hard to find how to set the NGram path in the Java code. An explanation about activateLanguageModelRules() could be added to this page:
http://wiki.languagetool.org/finding-errors-using-n-gram-data
- I didn't find ConfusionRuleEvaluator to make it working

Be sure I will contribute as soon as I would have something to share.

:+1: 

Etienne

**Comment by danielnaber** [comment]
Hi Etienne, thanks for your feedback. I've added some links to the documentation. I'm not sure what you mean by 
> it took me some times to discover that, while "fr" is using lexical search, this is not the case for "en"."

Could you explain?

**Comment by EtienneAb3d** [comment]
With the default configuration, with this code:
```
		aLngStr = ... ;
		Language aLng = Languages.getLanguageForShortCode(aLngStr);
		JLanguageTool langTool = new JLanguageTool(aLng);
		List<RuleMatch> matches = langTool.check(aSent, false, ParagraphHandling.NORMAL);
```
If **aLngStr** is **fr**, you get rules matching unknown words for a possible misspelling, providing with lexically near words.

If **aLngStr** is **en**, it silently ignore unknown words.

if **aLangStr** is **en-GB**, you also get lexical search, like with "fr".

**Comment by danielnaber** [comment]
I see. I'm not sure how to improve that, though, without breaking the API.

**Comment by EtienneAb3d** [comment]
I would do: 
- if a feature is not defined in the language without the country variant, like "en", and available on a variant like "en-GB", apply a priority set on all variants to get it also working on the main simple language definition, like "en" => "en-GB" => "en-US". This priority set can be defined differently for each available features.
- in the default configuration, at first installation, add a default priority set like: "en" => "en-GB" => "en-US"
- for ascendant compatibility, if the priority set is not defined in the already installed configuration files, do not use the new cascade effect, and keep working without the lacking feature

**Comment by danielnaber** [comment]
I see... however, we're talking about the API here, which doesn't know anything about a configuration. Most people use the HTTP API anyway, so I'm hesitant making changes to the Java API.

**Comment by EtienneAb3d** [comment]
Not sure to understand what is a problem for you:
- the change isn't in the Java API but in the default provided configuration, and the back side behaviour of LT
- on a fresh install, I don't think it's a good thing to have 2 different behaviours in 2 very similar calls (with "fr" and "en")
- if the ascendant compatibility is preserve, no one already using LT would complain about the change

**Comment by danielnaber** [comment]
The thing is that "en" is only visible for developers. As a user, you usually only can set "en-US", "en-GB" etc., so there shouldn't be an issue for users. Or am I missing a case?

**Comment by EtienneAb3d** [comment]
The issue is that I got a problem with this, and possibly others will be in the same case. But, you can consider that people developing with LT, like me, can find out the solution by themselves, like I did.

**Comment by EtienneAb3d** [comment]
NeuroSpell is now an hybrid system, combining a neural network, with LanguageTool lexical search, POS-tagger, grammar rules, and statistical model. I wrote a short explanation on how NeuroSpell is working, here (see "How does it work ?" button):
http://neurospell.com/en.php
Also available in french, here:
http://neurospell.com
LanguageTool is quoted in these explanations, like on the main web page.
Thanks to the LanguageTool team for making all this possible !
