### ISSUE TITLE
Portuguese vs. Brazilian Portuguese (user feedback)

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1548]
Got this user feedback which I'm just passing on:

Not used for Portuguese, only Brazilian:
"compartilhar"
"Mobile phone" = "Telemóvel" not "Celular"
"Registered" = "Registado" not "Registrado"
"Last name" = "Apelido" or "Último nome" not "Sobrenome" 

Also:

"40,000+ caracteres por verificação": "+40,000". Even using the "+" sign the number is incorrect"

**Comment by marcoagpinto** [comment]
> "40,000+ caracteres por verificação": "+40,000". Even using the "+" sign the number is incorrect"

Daniel, "40,000+" is the correct way, since it means "40000 and over"

**Comment by TiagoSantos81** [comment]
@danielnaber I think the user is referring to website translations and he is mostly correct. I would only disagree with:
`"Last name" = "Apelido" or "Último nome" not "Sobrenome"` 
AFAIK, `Sobrenome` can be used in European Portuguese. I use it, at least.
The rest is good advice.
Sorry to disagree @marcoagpinto but thousand separator in Portuguese is either an unbreakable space or a dot. The comma is a decimal separator.
"40,000+ caracteres por verificação" should read "40.000+ caracteres por verificação" the + sign is Ok the way it is.

**Comment by TiagoSantos81** [comment]
@marcoagpinto 
"40,000+ caracteres por verificação" this has slipped me as well, and I am not even sure it I did or touched that translation, so it is an easy to slip mistake. I am not arguing.

**Comment by danielnaber** [comment]
@TiagoSantos81 Thanks, but I'm still not sure where exactly these texts appear. Did you actually see them on the website?

**Comment by TiagoSantos81** [comment]
No, but I assume they are. It seems from a registration form and a front-end.

**Comment by TiagoSantos81** [comment]
Issue solved.
