### ISSUE TITLE
[en] suggestion for "Everytime" not helpful

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1561]
> Everytime you agree.

![Bildschirmfoto 2019-05-03 um 10 54 30](https://user-images.githubusercontent.com/37363/57127841-ea4b4e00-6d91-11e9-9b56-c85d2d20e173.png)

Doesn't seem to happen when it's in the middle of a sentence:

![Bildschirmfoto 2019-05-03 um 10 55 23](https://user-images.githubusercontent.com/37363/57127893-0cdd6700-6d92-11e9-939d-c9d4ada1d4bc.png)

**Comment by danielnaber** [comment]
Quick fix applied, real reason is a bug in Morfologik: https://github.com/morfologik/morfologik-stemming/pull/101
