### ISSUE TITLE
[DE] "Die viele Stunden"

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1565]
Moin liebes LanguageTool-Team

**Die viele Stunden** Arbeit haben sich unserer Meinung nach bisher gelohnt.
LT: "keine Fehler gefunden."
Hier wird nichts gefunden, obwohl es einen Fehler gibt, denn es muss "**die vielen Stunden** heißen.

Bitte ergänzen, soblad ihr die Zeit habt.

Grüße Dallun511

**Comment by baarsrj** [comment]
A typical example of what a 'multi word spell checker' could warn about ;-)
