### ISSUE TITLE
[De] spelling error not detected

### ISSUE THREAD

**Issue by Esokrates** [languagetool-org/languagetool#1570]
The word "Feuerwerksartigel" is not detected as wrong word, seems to be an issue of hunspell.

**Comment by danielnaber** [comment]
Reopening, hoping that we can find a better solution, e.g. "Kühlschrankartigel" is also accepted...

**Comment by Esokrates** [comment]
Might not directly related, but I encountered another one:
"Suchrum" instead of "Suchraum"
