### ISSUE TITLE
[de] false alarms KOMMA_ZWISCHEN_HAUPT_UND_NEBENSATZ

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1571]
> Das minimalistische Design entspricht voll und ganz aktuellen Wohntrends.
<img width="591" alt="Bildschirmfoto 2019-05-06 um 17 56 54" src="https://user-images.githubusercontent.com/37363/57237839-5c3cc500-7028-11e9-9ad9-0180a483779b.png">

> Viele Boxen sind aus recycelten Wertstoffen hergestellt.
<img width="489" alt="Bildschirmfoto 2019-05-06 um 17 56 23" src="https://user-images.githubusercontent.com/37363/57237814-49c28b80-7028-11e9-8896-581324c5e01c.png">

Passiert nicht bei:
> Viele Boxen sind aus schönen Wertstoffen hergestellt.

Wahrscheinlich werden "minimalistische" und "recycelte" nicht als Adjektiv erkannt. 

Original Forumspost: https://forum.languagetool.org/t/fehlalarme-nicht-erkannte-fehler-und-begriffe/4217

**Comment by f-knorr** [comment]
gestern schon gefixt. sollte heute online gehen

**Comment by tiff** [comment]
sehr cool
