### ISSUE TITLE
[en] Missing Rule for "Mothers/Fathers day"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1583]
Correct spelling is:
> Mother's day. 

Common misspelling:
> Mothers day

Also wrong:
> Mothers' day

**Comment by tiff** [comment]
Also: 
* President's Day (public holiday in the US)
* New Year's Day/Eve

**Comment by f-knorr** [comment]
Behoben für: Valentines|Mothers|Fathers|Patricks
President's Day ist nicht so eindeutig: http://www.grammarunderground.com/is-there-an-apostrophe-in-presidents-day.html

**Comment by tiff** [comment]
Vielen Dank
