### ISSUE TITLE
IndexOutBoundsException in getParaPos (SingleDocument.java)

### ISSUE THREAD

**Issue by serval2412** [languagetool-org/languagetool#1586]
Hello,

Reported from Libreoffice bugtracker, https://bugs.documentfoundation.org/show_bug.cgi?id=125292
With languageTool 4.5.1, someone got this crash:
java.lang.IndexOutBoundsException: Index: 2399, Size: 2399
Stacktrace:
java.lang.IndexOutBoundsException: Index: 2399, Size: 2399
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at org.languagetool.openoffice.singleDocument.getParaPos(SingeDocument.java:380)
at org.languagetool.openoffice.singleDocument.getCheckresults(SingleDucument.java:123)
at org.languagetool.openoffice.MultiDocumentHandler.getCheckresults(MultiDucumentHandler.java:129)
at org.languagetool.openoffice.main.doProofreading(Main.java:150)

OS:Windows 7 an amd64, java version 1.8.0_211 from Oracle Corporation

For the moment, no steps found to reproduce this easily

**Comment by serval2412** [comment]
I downloaded the sources and noticed this line in src/main/java/org/languagetool/openoffice/SingleDocument.java might be buggy:
378     if (!chPara.equals(allParas.get(nParas))) {

Indeed, some lines above, there's some bound checking:
348     if (nParas >= 0 && nParas < allParas.size() && chPara.equals(allParas.get(nParas))) {

I'll submit a PR about this after my day-time job.
If someone has another idea or wants to submit a patch, don't hesitate to do it! :-)

**Comment by serval2412** [comment]
PR here: https://github.com/languagetool-org/languagetool/pull/1587

**Comment by FredKruse** [comment]
The problem can only occur, if a text row is added at the end of a document while the check is running. A very rare situation I think, but I have included the possibility now (just committed).
The idea above would produce consecutive faults, I fear. So I choose a solution where a undefined state (only check one paragraph) is returned.
I think the issue could be closed as well as #1587

**Comment by serval2412** [comment]
@FredKruse : thank you for your feedback.
Just for curiosity, taking a look at http://wiki.languagetool.org/roadmap, it seems the fix will be available from the next release end of June with 4.6, is that it?

**Comment by FredKruse** [comment]
Yes that's right. The fix will be available in 4.6 in June

**Comment by serval2412** [comment]
Thank you for your feedback, let's close this one then.
