### ISSUE TITLE
[de] "rumdenken" endless loop

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1590]
![May-21-2019 18-21-18](https://user-images.githubusercontent.com/37363/58113205-4d900980-7bf5-11e9-82bd-24f3b13edf19.gif)

I think we just need to add "rumdenken" to the dictionary, right?

**Comment by Discostu36** [comment]
It would solve the problem, but should we do this? Is this really a correct word?

**Comment by danielnaber** [comment]
I agree with @Discostu36, let's not add it for now.

**Comment by tiff** [comment]
Same happens with:
> Darauf rumhüpfen.
