### ISSUE TITLE
[de] Spelling false positive: Compounds with "Präsentations-"

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#1592]
LanguageTool doesn't know compounds with "Präsentations-". A word like "Präsentationsgerät" is marked as a spelling error.

I thought there was a way to add "Präentations" to LT but only allow it as a compound, not as a separate word. But I forgot how.

**Comment by danielnaber** [comment]
I haven't tried, but the comment in `spelling.txt` says: "# Compound words starting with words listed here will be accepted, too. If this file contains "Secondhand" or "Helizität", then "Secondhandladen" or "Helizitätsoperator" will not be marked as incorrect."

**Comment by Discostu36** [comment]
I know, but I don't want to add "Präsentations" there, because it is only correct within a compound.

**Comment by danielnaber** [comment]
Maybe add it to `de_DE.dic` directly then. It's not that clean, but we have made other changes which we'll need to keep once that file is updated from its original source (which rarely has updates anyway).

**Comment by f-knorr** [comment]
Just add 'Präsentation' to 'spelling.txt'. The internal logic will recognize that a so called Fugen-S is required for compounds and will add internally. (This is the same what happens when you add 'Helizität' and 'Helizitätsoperator' is accepted.)

**Comment by Discostu36** [comment]
So I have to add a word to the dictionary that is actually already in it? Madness! 🙃

**Comment by Discostu36** [comment]
There are hundreds, if not thousands of words that can be deleted out of spelling.txt because of this method.

**Comment by f-knorr** [comment]
> There are hundreds, if not thousands of words that can be deleted out of spelling.txt because of this method.

Yes and no: This approach does not only decrease the system's performance, but you would also open the door to many unreasonable compounds such as 'Präsentationshundebesiter'.

**Comment by Discostu36** [comment]
Ok, I didn't know that. My guess was that a smaller spelling.txt would increase performance. 

Actually I do think that we should allow all compounds that are grammatically correct. And we do that already in most cases, don't we? 

Because most of these don't happen by accident, like your example. Exceptions can be added as entries into prohibit.txt (in case of common typos) or as false friends (in case of false translation from primary language).

But your opinion may differ.

**Comment by baarsrj** [comment]
Beware: (at least in Dutch) it is very easy to have a compound that is very much like a second word, and is technically correct, but still in all practical cases a mistake. Cause are words that differ only one (starting or ending) letter mostly. Had to take care of that in the Dutch Hunspell as well.

**Comment by f-knorr** [comment]
> k, I didn't know that. My guess was that a smaller spelling.txt would increase performance.
> 
> Actually I do think that we should allow all compounds that are grammatically correct. And we do that already in most cases, don't we?
> 
> Because most of these don't happen by accident, like your example. If someone writes "Präsentationshundebesitzer" he does so for a reason.
> 
> Exceptions can be added as entries into prohibit.txt (in case of common typos) or as false friends (in case of false translation from primary language).
> 
> But your opinion may differ.

Sorry! My fault! You're right. This approach increases the system's performance. So, it might be a good idea, if one is willing to pay with a slightly higher rate of false negatives (which can be suppressed with the help of 'prohibit.txt')

**Comment by Discostu36** [comment]
Maybe another approach would be useful for this: One could scan a large corpus of text for compounds and collect these in a file. When LT is used and a compound is found in an entered text that is grammatically correct but not part of the file, it could be marked: “The compound “Präsentationsgurke“ seems to be unusual. Please make sure this is the word you wanted to use.”
