### ISSUE TITLE
LO/OO: ParagraphHandling fails to run only the required rules

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1596]
Even with `ParagraphHandling.ONLYNONPARA` (as called from `org.languagetool.openoffice.SingleDocument#checkSentence`), almost all rules seem to run. `Mode` and `ParagraphHandling` seem to have overlapping meaning. `ONLYNONPARA` not properly working is a problem, as it probably makes the check slow in LO/OO.

Proper solution: clean up `Mode` and `ParagraphHandling`. Potential fast fix/workaround: call `JLanguageTool.check()` with `JLanguageTool.Mode.TEXTLEVEL_ONLY` as ther last parameter when in `ONLYNONPARA` mode.

Also see #194

**Comment by FredKruse** [comment]
It's right, mode and paragraph handling has a overlapping meaning. I changed the handling in that way, that mode is that in the same way as ParagraphHandling, when Mode isn't used.
The overall Performance of LO is increased only a little, but now a full check of the whole text is very fast. It could be the default option.

**Comment by FredKruse** [comment]
The issue can be closed. It's working now.
