### ISSUE TITLE
Custom resource loaders

### ISSUE THREAD

**Issue by slotties** [languagetool-org/languagetool#16]
All code that loads resources currently uses the classloader as resource loader. This is  allows to package all resources within the JARs or somewhere else in the classpath. It's good for standalone applications or plugins, because they can be delivered as packages without any external references. It would be good to abstract the resource loading from the classloader to an own small API/interface to allow API-users custom loading mechanisms, e.g. from a database or a network filesystem instead of the classpath. Additionally the API-user may cache the content of resources, e.g. dictionaries or other huge files, and reduce disk I/O.

The benifit is that in such cases, most likely in server-environments, it's possible to change resources, like the `grammar.xml` or dictionaries, at runtime without the need of a server-restart to update the languagetool JARs.

*Idea*
A new interface `ResourceLoader` will be introduced and provided to both the `Language` and the `JLanguageTool` in a separate constructor. All default constructors will create a default implementation `ClasspathResourceLoader` that implements loading over the classloader. All code that requires to load resources must have access to the resource loader, most likely by requiring it in a constructor. There should be no static references to a _default constructor_ or so, to keep it as flexible as possible.

*Constraints*
- the default should still be the classpath resource loader
- no additional configurations must be required when the default mechanism is used (backward compatibility)

**Comment by danielnaber** [comment]
I'm closing this, as there has been no work done for more than two years.
