### ISSUE TITLE
[en] DO_VBZ "base form" for second person

### ISSUE THREAD

**Issue by shaedrich** [languagetool-org/languagetool#1605]
Instead of "base form" I would be a bit more precise saying: "the -s suffix only applies to third person not second like in this case"

https://github.com/languagetool-org/languagetool/blob/8449cb57ebfcae22dad27c3f0ef80a2ec85b6c99/languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml#L6966

**Comment by danielnaber** [comment]
I agree, @MikeUnwalla what do you think?

**Comment by MikeUnwalla** [comment]
The rule DO_VBZ finds more than only "do + VBZ". For example, it finds the error in "Did it worked correctly?" Thus, we cannot make the message more precise. (For a more precise message, we must make 2 rules.)

**Comment by danielnaber** [comment]
I think the error is common for non-native speakers, so it makes sense here to have two rules with better messages.
