### ISSUE TITLE
[en] PM_IN_THE_EVENING not precise

### ISSUE THREAD

**Issue by shaedrich** [languagetool-org/languagetool#1606]
> Consider using "P.M."

This doesn't explain why this is wrong. So what about

> This is redundant. Consider using "P.M."

And or

> P.M. already indicates that the time is in the afternoon

https://github.com/languagetool-org/languagetool/blob/8449cb57ebfcae22dad27c3f0ef80a2ec85b6c99/languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml#L17399

**Comment by danielnaber** [comment]
Thanks, done.

**Comment by shaedrich** [comment]
You're welcome.
