### ISSUE TITLE
No detection of missing space between 2 sentences in Dutch; it does in English

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#1608]
Is a Java rule missing for Dutch, or is this because of the srx or otherwise?

**Comment by f-knorr** [comment]
Can you please provide example for Dutch (where it does not work) and English (where it works)

**Comment by baarsrj** [comment]
Dit is een zin.En dit ook. 
You can see the results on languagetool.org

**Comment by baarsrj** [comment]
Thanks. I don't have a clue what the code does, but I will test tomorrow.
