### ISSUE TITLE
Adding POS for multi-word terms: use a text file

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#1610]
To add POS information about 1-word terms, we can use added.txt (and we can use disambiguation.xml).

To add POS information about multi-word terms, we must use disambiguation.xml.

Suggestion. Add a file multiword_added.txt that lets us add POS information for multi-word terms.

Possible structure:
`word1 + tab + word2 + tab + [wordn + tab]... POS`

**Comment by baarsrj** [comment]
Should that be 'add' or 'overwrite existing if any'?

**Comment by MikeUnwalla** [comment]
I think that the behaviour should be the same as for added.txt, which is to add the POS.

I thought about the enhancement when I was correcting my errors with multi-word POS for foreign terms (https://github.com/languagetool-org/languagetool/commit/12a75edfa5653054f37cae86192b4144b2157f58). But, I didn't think of the implications.

If we add POS, then unwanted POS remain (but, that is the case with 1-word terms also). It is the job of the disambiguator to disambiguate. (So, my POS additions to the disambiguator are a quick fix, because there is no disambiguation between say the adjectival and the adverbial use of 'ab initio'.)

Maybe having a file in which to add the POS to multi-word terms is not so useful.

**Comment by MikeUnwalla** [comment]
The multi-word disambiguation was available for other languages (but, I didn't know that). Now, we have it for English: https://forum.languagetool.org/t/en-multiwords-txt-for-english/5047
