### ISSUE TITLE
[DE] "seit" +seine/meine/ihre Kindheit = Kein Fehler

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1612]
Moin liebes LanguageTool-Team

Saskia ist **seit ihre Kindheit** sehr schüchtern.
Lennard ist **seit seine Kindheit** sehr schüchtern.
Ich bin **seit meine Kindheit** sehr schüchtern.
LT: "keine Fehler gefunden."

Leider ist alles falsch, denn es muss **"meiner/seiner/ihrer"** heißen und nicht **"meine/ihre/seine".**

Bitte ergänzen.

Grüße Dallun511

**Comment by f-knorr** [comment]
fixed with  9c41c5e

**Comment by Discostu36** [comment]
Or maybe with ab628374d5321b4cfd3f86c740d14b4b030945cf?  :-)
