### ISSUE TITLE
DE_DU_UPPER_LOWER rule is wrong

### ISSUE THREAD

**Issue by shaedrich** [languagetool-org/languagetool#1614]
It's not about consistency. All informal pronouns starting with a lowercase letter and all formal pronouns starting with a capitalized letter. Since 2006 you're allowed to also start informal pronouns in informal text with a capitalized letter, but that's not the recommended way. It works for "Du" (second person singular) because germans do not use the same term for the second person plural, but it does not for "Sie", because it can be third person singular female (starting with a lowercase letter) or second person singular formal (starting with a capitalized letter). This is how they are distinguished. If you mix it up, there's no way to tell what you meant and people get confused.

https://german.stackexchange.com/a/213

**Comment by Discostu36** [comment]
This rule is only about the second person singular and plural, so I don't see a problem here. Or do you have an example of a sentence where this rule creates a false positive or negative?

**Comment by shaedrich** [comment]
Well, you *could* do this, but I wouldn't suggest this because this is not the standard.

**Comment by Discostu36** [comment]
>  In  Briefen  können  die  Anredepronomen du  und ihr mit  ihren  Possessivpronomen auch großgeschrieben werden

([Amtliches Regelwerk, Rat für deutsche Rechtschreibung, §66 E](http://www.rechtschreibrat.com/DOX/rfdr_Regeln_2016_redigiert_2018.pdf#page=71))

LanguageTool doesn't know if you're writing an e-mail or a letter, so I don't think it should prefer one of the two possibilities. But maybe others have a different opinion on that, what do you think @danielnaber @janschreiber ?

**Comment by shaedrich** [comment]
Because it doesn't know the type of text you're writing, it should be oriented towards the standard not the exception.

The message for that rule says literally this:
> The rule allows you to deviate from it so we suggest doing that

**Comment by Discostu36** [comment]
Just to make one thing clear: This is a rule about consistency and it is not oriented towards one of the two possible spellings. It only suggests using the same one in the whole text. So it looks at how the word was written when it was used for the first time in the text and suggests to change later alternative spellings of the word to the original one. So this rule is not "wrong".

What you would like is an additional rule that tells the user that one of the two possibilities is the standard one with a message like this one: 

> Das Personalpronomen "du" darf nur in Briefen großgeschrieben werden.

I'm still not totally sure that we need that rule, but if somebody creates it, we should deactivate it in the MS Word and LibreOffice plugins and activate it for the Browser extensions.

**Comment by shaedrich** [comment]
Okay, an additional rule at least makes sure, the user doesn't always write it in the capitalized way. If the rule is not wrong without that additional rule, it is highly misleading in the way of writing.

**Comment by shaedrich** [comment]
> Or do you have an example of a sentence where this rule creates a false positive or negative?
If you have "Du"/"Sie" at the beginning of a sentence, the rule falsely assumes that if the word reappears somewhere else in a sentence it has to be capitalized. But using it at the beginning of a sentence doesn't indicate if it's formal or informal.

**Comment by danielnaber** [comment]
> If you have "Du"/"Sie" at the beginning of a sentence, the rule falsely assumes that if the word reappears somewhere else in a sentence it has to be capitalized.

I cannot reproduce that. It sounds more as if the sentence boundary detection didn't work. Can you provide the full text to reproduce?

**Comment by shaedrich** [comment]
Interesting &hellip; I can't reproduce it anymore. But I know for sure, I got that annoying error countless times. Did you fix that lately?

**Comment by danielnaber** [comment]
> Did you fix that lately?

The latest change affected only "ihr/Ihr" and was about 2 months ago, I think.

**Comment by shaedrich** [comment]
Ah, okay. Might have been an older fix given that the issue was opened in 2019 :sweat_smile:
