### ISSUE TITLE
Languages that use Latin characters: ignore spelling for text that contains many non-latin characters

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#1615]
LT gives warnings about spelling errors in the following text.

> ... and as Plato said, "ἀγεωμέτρητος μηδεὶς εἰσίτω."

For all languages such as English, French, German that use Latin characters, is it possible to ignore the spelling of text that contains non-latin characters? To prevent false negatives, set a minimum number of characters to ignore (say 5). Fewer than that number can be treated as a spelling error.

Possibly, have a grammar rule that finds the block of text and says "this text is not [Text Language]. Make sure that it is correct."

**Comment by jaumeortola** [comment]
Solved some weeks ago (from another issue).
