### ISSUE TITLE
[DE] Wird "vermehrt" falsch erkannt?

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1618]
Moin liebes LanguageTool-Team

Möglicherweise fehlende grammatische Übereinstimmung zwischen Artikel, Adjektiv und Nomen bezüglich Kasus, Numerus oder Genus. Beispiel: 'mein kleiner Haus' statt 'mein kleines Haus'
Zudem rufen **mich vermehrt Familien** an.

Ich weiß nicht, wo hier der Fehler sein soll. Umgangssprachlich sollte das erlaubt sein, aber wie sieht es mit der normalen Sprache aus?

Was meint ihr? Fehlalarm oder berechtigter Alarm?

Grüße Dallun511 Ferewo

**Comment by Discostu36** [comment]
Der Satz ist korrekt. Vermehrt befindet sich nur als Verb im Wörterbuch, nicht als Adjektiv. Evtl. würde ein neuer Eintrag in added.txt das Problem bereits lösen.

**Comment by Dallun511** [comment]
@Discostu36 Ich danke dir für diese Kenntnis.
