### ISSUE TITLE
[DE][BUG] Falsche Spracherkennung

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1619]
Moin liebes LanguageTool-Team

![grafik|623x419](upload://oHE026NWyxzhiJazcnqKZaHLEnc.png)
![grafik](https://user-images.githubusercontent.com/40240507/59135236-80205d00-897e-11e9-8348-fdd6a023486a.png)

Elle **téléphone** à la

In diesem Bild ist klar zu erkennen, dass es sich um die französische Sprache handelt und nicht um die deutsche, weswegen der Duden nicht zu melden hat, weswegen die Regeln der Duden-Empfehlungen nicht anschlagen dürfen, wenn es sich nicht um die deutsche Sprache handelt.

Grüße Dallun511

**Comment by danielnaber** [comment]
Es gibt in LT für LibreOffice keine autom. Spracherkennung, stattdessen muss die Sprache für Textabschnitte in LO eingestellt werden:

![sprache-lo](https://user-images.githubusercontent.com/857004/67295766-e3eb9280-f4e7-11e9-91d1-cebdfa739e3c.png)

**Comment by Dallun511** [comment]
@danielnaber Warum schlägt dann eine deutsche Regel bei der französischen Sprache an, obwohl alles auf französisch gestellt wurde? Das ist im Bild zu sehen.

**Comment by danielnaber** [comment]
Keine Ahnung, dazu müsste man mal das Original-Dokument sehen oder einen größeren Ausschnitt.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/67336570-dd7c0b80-f525-11e9-9f66-69bf81f8783c.png)

[Dialog in Französisch.zip](https://github.com/languagetool-org/languagetool/files/3758796/Dialog.in.Franzosisch.zip)

In diesem Dokument kommt es zu fehlern, die nicht berechtigt sind.

**Comment by danielnaber** [comment]
Ich kann das mit LibreOffice 5.1 und 6.0 nicht nachvollziehen.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/67337462-65164a00-f527-11e9-98af-44e35c45a310.png)
ich hatte die Fehlermeldung zuerst mit LO 5 und jetzt mit 6.1.2.3.

**Comment by danielnaber** [comment]
Da steht ja auch "Sprache einstellen als: Deutsch", es sollte wohl "Sprache des Dokuments benutzen" sein.

**Comment by Dallun511** [comment]
Es gibt Regeln, die nur anschlagen, wenn die Muttersprache eingestellt ist.
Nennt sich "falsche Freunde".
