### ISSUE TITLE
Portuguese false alarm feedback

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1620]
User feedback:

"O Relatório final da Intervenção elaborado pelo Observatório..."

O aplicativo indica um possível erro de concordância. Todavia, a palavra elaborado concorda com a palavra relatório. Ou seja, o relatório final é elaborado.

Tenho a impressão que o aplicativo analisa a concordância, verbal ou nominal, considerando apenas a palavra imediatamente anterior e, por isso, apresenta erro onde não existem.

**Comment by qgustavor** [comment]
[Fiz alguns testes](https://i.imgur.com/a09v5DQ.png) e parece que o mesmo acontece com outras línguas e aplicativos.

**Comment by TiagoSantos81** [comment]
It is a design solution, Explained thoroughly many times:
https://forum.languagetool.org/t/pt-portuguese-rule-contribution-discussion/1399
This way, the balance between false positives and false negatives is kept at a minimum.

**Comment by TiagoSantos81** [comment]
@qgustavor  
Obrigado pelo feedback.
Quando os grupos nominais são composto ou se ignora todas estas situações, ou se considera alertar para o ponto de erro potencial. Daí a maioria dos programas escolherem alertar para o problema, dado que não é frequente.
