### ISSUE TITLE
[en] "automize" -> "automate"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1625]
The word "automize" is detected as an error. If this in fact is not a word, we should suggest "automate" instead of "atomize". Same for "automized" and "automizes".

**Comment by MikeUnwalla** [comment]
The word 'automize' is BrE: www.lexico.com/en/definition/automize
Not in Webster: www.merriam-webster.com/dictionary/automize

When I added POS/coherency/spelling rules some months ago, I didn't add spellings for some infrequently used words.

My preference is that the spell checker should ignore most valid words (not archaic words or extremely infrequent words). Let other rules or functions find incorrectly used words or words that are easily confused. @danielnaber, I have a list of words that I added, so I can easily add missing spellings. Let me know if you want me to do that. (But, then LT possibly will not give suggestions for rare words that are used incorrectly. I don't want to spend time making rules that find such words.)

**Comment by danielnaber** [comment]
@MikeUnwalla yes, adding the words is fine

**Comment by tiff** [comment]
@MikeUnwalla correct me if I'm wrong but the issue now still exists for AmE and other variants, doesn't it? Suggesting "automate" in AmE would be helpful I think

**Comment by MikeUnwalla** [comment]
@tiff , you are correct. I think that the problem is one for @danielnaber or one of the other Java developers to fix. I don't know how to change the spell checker's suggestions.

**Comment by MikeUnwalla** [comment]
@tiff , @danielnaber , I will still add the words to the applicable spelling files unless you object.

**Comment by danielnaber** [comment]
I have added automate, automated, automates, and automating.
