### ISSUE TITLE
Being able to change language of GUI (instead overriding with -Duser.language)

### ISSUE THREAD

**Issue by ebraminio** [languagetool-org/languagetool#163]
Separated from [this](https://github.com/languagetool-org/languagetool/issues/161). it would be nice language of standalone languagetool could be overrideable inside the app. Users may don't use system wide language setting (may because their language is not support on OS level yet) but would like to see languagetool GUI translated. From code stand view, this probably would need moving all of `Locale.getDefault()` to an abstraction layer.

**Comment by danielnaber** [comment]
See #407
