### ISSUE TITLE
[de] false positive KOMMA_ZWISCHEN_HAUPT_UND_NEBENSATZ

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1630]
> Ich glaube das aktuelle Update wurde veröffentlicht

![Bildschirmfoto 2019-06-14 um 07 36 02](https://user-images.githubusercontent.com/37363/59485722-2ab0e800-8e77-11e9-8fec-b8528985506e.png)

**Comment by Discostu36** [comment]
This is not a false positive. Main clause and subordinate clause have to be separated by a comma, even if the conjunction is missing:
- Ich glaube, das aktuelle Update wurde veröffentlicht.
- Ich glaube, dass das aktuelle Update veröffentlicht wurde.

 See for example here: https://www.lernnetz24.de/regeln/0702.html

**Comment by tiff** [comment]
@Discostu36 danke dir
