### ISSUE TITLE
[de] Kein Vorschlag für Regel "LILANES"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1637]
Für den Standard-Nutzer (wie mich), der nicht versteht, was ein gebeugtes Wort ist. Wäre es super hier einen Vorschlag anzubieten.
Ich frage mich, ob hier "Ein orange Kleid" tatsächlich korrekt wäre.

> Ein orangenes Kleid

Bzw.

> Ein oranges Kleid

<img width="350" alt="Bildschirmfoto 2019-06-18 um 13 55 59" src="https://user-images.githubusercontent.com/37363/59691327-23753b80-91e3-11e9-9502-f17e15eeee7f.png">

**Comment by Dallun511** [comment]
@tiff ein orange Kleid ist wirklich korekt, denn ein "oranges" Kleid ist Umgangssprache.
[Mehr Informationen findest du hier](https://www.spiegel.de/kultur/zwiebelfisch/zwiebelfisch-sind-rosane-t-shirts-und-lilane-leggings-erlaubt-a-292846.html)

**Comment by Discostu36** [comment]
Der Duden erlaubt inzwischen "ein oranges Kleid":
https://www.duden.de/rechtschreibung/orange

Im Übrigen halte ich diese Regel auch standardsprachlich für überholt. Siehe z.B. [diese Trefferliste des DWDS](https://www.dwds.de/r?q=%40pinkes&corpus=public&date-start=1473&date-end=2018&genre=Belletristik&genre=Wissenschaft&genre=Gebrauchsliteratur&genre=Zeitung&format=full&sort=date_desc&limit=50). 

Ich wäre dafür, sie zu deaktivieren bzw. etwas weniger streng zu machen ("oranges" ja, "orangenes" nein).

**Comment by tiff** [comment]
Stimme ich zu

**Comment by danielnaber** [comment]
Kümmere mich drum...

**Comment by danielnaber** [comment]
Fixed in f841ebfc262a7c24a0912c4fbd43b1c52986dfe1
