### ISSUE TITLE
[en] timezone isn't recognized as "NN"

### ISSUE THREAD

**Issue by gosp** [languagetool-org/languagetool#1638]
The sentence:   `It is not a valid timezone.`
The issue about `a valid`: `Probably a noun is missing in this part of the sentence. `
The vocabulary: `timezone` isn't recognized as "NN"

**Comment by danielnaber** [comment]
Thanks, I have added "timezone". But I didn't get the error you quote even before adding it, where exactly  did you see that?

**Comment by gosp** [comment]
@danielnaber 
I downloaded LanguageTool from https://languagetool.org/download/LanguageTool-stable.zip
It's version is 4.5

**Comment by danielnaber** [comment]
Strange, I still cannot reproduce with LT 4.5 either. Anyway, the POS tag has been added and the upcoming snapshot at https://internal1.languagetool.org/snapshots/ should work.

**Comment by gosp** [comment]
In 4.5, you can reproduce it using `It is not a valid timezone` instead of `It is not a valid timezone.`
Issue only exists when punctuation at the end of a sentence is missed.
