### ISSUE TITLE
[en] "Ok"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1640]
<img width="405" alt="Bildschirmfoto 2019-06-19 um 11 58 24" src="https://user-images.githubusercontent.com/37363/59756449-03e51e00-928a-11e9-9379-342d29329c91.png">

I think we should add the lower case version of "OK" to, at least, our AmE dictionary.

Webster lists this form as "less commonly":
<img width="493" alt="Bildschirmfoto 2019-06-19 um 11 57 01" src="https://user-images.githubusercontent.com/37363/59756330-c7192700-9289-11e9-956e-83eaaf54f52f.png">
https://www.merriam-webster.com/dictionary/OK

I'm not sure about British English. What do you think @MikeUnwalla, @danielnaber ?

**Comment by MikeUnwalla** [comment]
In BrE, OK is upper case.

For AmE, if you add lower-case 'ok', I suggest that you write a rule to find lower-case and suggest the upper-case variant as the usual spelling.

**Comment by tiff** [comment]
I did a bit more research here. MS Office, Grammarly and Google Docs all accept both "Ok" and "OK". 
I think a rule that suggests the upper case spelling is a bit too picky. Therefore, I suggest to simply add "Ok" to the AmE dictionary and not write an extra rule.

**Comment by danielnaber** [comment]
@MikeUnwalla Could you add "ok" and add a rule suggesting OK for en-GB only?
