### ISSUE TITLE
[de] "Großes erreichen"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1663]
Ich bin mir hier selber nicht sicher, wird "Großes" hier groß oder kleingeschrieben oder geht beides?

> Wenn du an das glaubst, was du tust, kannst du Großes erreichen

![Bildschirmfoto 2019-06-26 um 07 54 03](https://user-images.githubusercontent.com/37363/60154475-b3b90f00-97e7-11e9-9366-e3270768d1e7.png)

**Comment by Dallun511** [comment]
Hier wird es großgeschrieben. https://www.nabenhauer-consulting.com/neuigkeiten-zur-umsatzsteigerung/wer-gross-denkt-wird-grosses-erreichen/

Aber eine bessere Quelle finde ich nicht. Ich würde es großschreiben, aufgrund deines Beispiels.

Du wirst (**etwas**) Großes erreichen, wenn du an dich glaubst.

**Comment by Discostu36** [comment]
Die Großschreibung ist auf jeden Fall richtig, LT muss hier korrigiert werden.

https://www.duden.de/sprachwissen/rechtschreibregeln/Gro%C3%9F-%20und%20Kleinschreibung#D72
