### ISSUE TITLE
Translation mistake? Only Dutch or other languages too?

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#1664]
There is a mistake in the message for the confusion pair rule.
It now says:
`Bedoelt u wellicht "<alternative>"? <word>=<explanation1>, <word2> <explanation2>`
there should be an = between `<word2>` and `<explanation2>` as well.
If this is a translation error or a mistake in code, I do not know.

**Comment by danielnaber** [comment]
Could you post an example sentence that triggers this issue?

**Comment by baarsrj** [comment]
Zit niet te zuren.

**Comment by danielnaber** [comment]
That is a rule from `grammar.xml` (`"ZEUREN_ZUREN"`), so you can fix its `<message>` there.

**Comment by baarsrj** [comment]
I must be stupid to not have seen this. Sorry for that.
