### ISSUE TITLE
[de] Vorschlag für W-Lan

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1667]
Der Duden kennt nur "WLAN" https://www.duden.de/rechtschreibung/WLAN

Das wird bei "W-LAN" bzw. "W-Lan" allerdings nicht vorgeschlagen.

![Bildschirmfoto 2019-06-27 um 16 16 29](https://user-images.githubusercontent.com/37363/60273803-31b80b80-98f7-11e9-88e2-95923811f811.png)

**Comment by Dallun511** [comment]
**W-LAN** ist erlaubt, aber nicht W-Lan. W-LAN wird zur besseren Lesbarkeit geschrieben.

W-LAN wird wahrscheinlich nicht vorgeschlagen, weil das Wörterbuch **W-LAN/ WLAN** nativ nicht kennt.

Grüße Dallun511

**Comment by tiff** [comment]
@Dallun511 woher kommt diese Info, dass "W-LAN" erlaubt ist?

Google mag "W-LAN" nicht:
![Bildschirmfoto 2019-06-27 um 16 53 47](https://user-images.githubusercontent.com/37363/60276560-287d6d80-98fc-11e9-8b32-60686b412898.png)

**Comment by Dallun511** [comment]
Bindesstrichge sind erlaubt, wenn es für eine bessere Lesbarkeit führt. Das steht im Duden. Das Google das Wort als falsch makiert, wundert mich persönlich nicht.

https://www.duden.de/sprachwissen/rechtschreibregeln/bindestrich
Regel "D22"

Darunter fällt W-LAN

**Comment by Discostu36** [comment]
@Dallun511  Die Regel bezieht sich aber auf zusammengesetzte Substantive (z.B. "Marketing-Abteilung"), nicht auf Abkürzungen. Sonst könnte ich ja auch W-L-A-N schreiben. 

Die Schreibweise W-LAN steht zwar nicht im Duden, ist aber [sehr verbreitet](https://www.google.com/search?q=%22W-LAN%22). Ich bin nicht sicher, ob wir sie überhaupt als Falschschreibung ankreiden sollten. Aber wenn, dann natürlich wirklich mit vernünftigem Korrekturvorschlag.

**Comment by tiff** [comment]
@Discostu36 von mir aus können wir`W-LAN` gerne ins Wörterbuch aufnehmen. Wikipedia listet "W-LAN" auch: https://de.wikipedia.org/wiki/Wireless_Local_Area_Network

Für `W-Lan` sollten wir dann aber den Vorschlag "W-LAN" anzeigen.

**Comment by Dallun511** [comment]
@Discostu36 W-L-A-N ist auch erlaubt. Buchstabieren Sie WLAN: W-L-A-N
Du hast recht, dass sich der Paragraf sich mit zusammengesetzten Nomen bezieht. Dort steht aber auch, dass der Einsatz eines Bindesstriches für die bessere Lesbarkeit erlaubt ist, weswegen ich auf diesem Paragrafen verwiesen habe.

**Comment by tiff** [comment]
https://github.com/languagetool-org/languagetool/commit/40a7ca37f9f25b54090b1156d3622e6eeebc374e
