### ISSUE TITLE
[fr] false positive ACCORD_GENRE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1671]
A user complaint that there's a false positive triggered by:
> Couverture enveloppante nouveau-né

![Bildschirmfoto 2019-06-28 um 15 52 46](https://user-images.githubusercontent.com/37363/60347060-ccc6e900-99bc-11e9-9b02-412a6a9bbbee.png)

cc @vkyfox @PoorPocketsMcNewHold

**Comment by vkyfox** [comment]
This is not in theory a false positive, the phrase in nonsensical ; but as is, it should be "nouveau-née."
