### ISSUE TITLE
[pt] missing error detection in Portuguese

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1676]
User feedback: "(...) The main issue for me is the comma. I didn't type the commas purposefully but LT didn't correct that."

![image-pt](https://user-images.githubusercontent.com/857004/60448471-f8004100-9c25-11e9-8624-dc91a182359a.png)

**Comment by TiagoSantos81** [comment]
This text had already rules disables and has typos that would make the POS analysis fail.
However, a simple rule for enumerations (D N, D N, D N) can be created.
