### ISSUE TITLE
[de] false alarm OBJECT_AGREEMENT?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1682]
> Der Ex-SPD-Chef und ehemalige Präsident des Europaparlaments.

<img width="589" alt="Bildschirmfoto 2019-07-03 um 16 00 15" src="https://user-images.githubusercontent.com/37363/60597766-c6b17d80-9dab-11e9-889d-2a2d8f9a1f67.png">

Bin mir hier nicht ganz sicher. Was meinst du, @Discostu36?

**Comment by Discostu36** [comment]
Ja, ist ein Fehlalarm. Die Regel sieht offenbar nicht, dass sich das "Der" auch auf "ehemalige Präsident" bezieht.
