### ISSUE TITLE
Subject-Verb Agreement issue

### ISSUE THREAD

**Issue by Shakeel87** [languagetool-org/languagetool#1690]
Tool is not able to capture the improper  use of  the verb in complex sentences as below:

**The service we provide are paid through your employer and completely complimentary.**

Tool is saying that no errors however the verb "are" in this sentence should be highlighted with correct suggestion. 

Do we have an easy fix for the same , Or writing rule for these kind of issues would be a bit tricky?

**Comment by danielnaber** [comment]
"The service" is properly detected as a singular (see https://community.languagetool.org/analysis/index?lang=en), so it seems a rule that refers to that should be possible. We have a documentation at http://wiki.languagetool.org/development-overview and http://wiki.languagetool.org/using-chunks, PRs are welcome.

**Comment by Shakeel87** [comment]
@danielnaber  thank you for your prompt response.

will look into the documentation and will try to configure the rule for the same.

**Comment by Shakeel87** [comment]
have created the below rule to handle the above issue, tested for the same . it seems to be working.
can this be included into upcoming release?

<rule id="SINGULAR_NOUN_PLURAL_VERB" name="check for singular noun and plural verb">
            <pattern>
                <token postag= "SENT_START"></token>
                <token>The</token>
				<token chunk="E-NP-singular"/>
				<token regexp="yes">you|we|they</token>
				<token chunk="B-VP"></token>
                <marker>
                    <token regexp="yes">are</token>
                </marker>
            </pattern>
            <message>Possible subject/verb agreement Issue</message>
            <suggestion>is</suggestion>
			<example correction="is">The service we provide <marker>are</marker> free of cost.</example>
			<example correction="is">The service you provide <marker>are</marker> useless.</example>
			<example correction="is">The service they provide <marker>are</marker> of no use.</example>
			<example >The service they provide <marker>is</marker> good!</example>
		</rule>
