### ISSUE TITLE
[nl] false alarm comma rule

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1692]
From a dutch user of our browser plugin:
> In deze context is dit volgens mij fout. Hier hoort helemaal geen komma te staan.

![Schermopname (74) Kopie](https://user-images.githubusercontent.com/37363/60823692-6c982a00-a1a8-11e9-892b-ffd922106491.png)

@baarsrj is this something for you?

**Comment by tiff** [comment]
Sentence:
> Ik had het gevoel dat het restaurantgedeelte werd verwaarloost en men eerder voorrang gaf aan de bediening aan de buffetten. 

Rule: KOMMA_ONTBR

**Comment by baarsrj** [comment]
It is, but I am on holiday. The real issue in the sentence is that 'verwaarloost' should be 'verwaarloosd'.

Apart from that, there are no exact rules for comma placement; you put one in a place where you pause when saying it.

Verzonden van mijn mobiele telefoon.

**Comment by baarsrj** [comment]
If you move it to the Dutch section of the forum (?), I can check when I am back home in 1 week.

Verzonden van mijn mobiele telefoon.

**Comment by tiff** [comment]
Sure! Here it is https://forum.languagetool.org/t/nl-dutch-comma-false-alarm/4443

Enjoy your holidays!
