### ISSUE TITLE
[de] "läufts" 

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1697]
Fehler, oder nicht?
> Hier läufts gut.

<img width="370" alt="Bildschirmfoto 2019-07-09 um 17 07 21" src="https://user-images.githubusercontent.com/37363/60900169-0e347f80-a26c-11e9-8004-702fe479df40.png">

Wenn ja sollten wir hier "läuft es" vorschlagen, wenn nicht dann ins Wörterbuch aufnehmen.

**Comment by Dallun511** [comment]
Da es sich um fehlendes "es" handelt, dass bei läuft**s** mit dem -s am Ende ergänzt wurde, liegt es an der Rechtschreibprüfung, was bei allen Verben und ähnlichen verbindlichen Abkürzungen.

Grüße Dallun511

**Comment by tiff** [comment]
@danielnaber hier muss ich doch bestimmt nur "läufts" in die spelling.txt aufnehmen, so wie die anderen, oder? https://github.com/languagetool-org/languagetool/blob/5f1d46a9892fff7309dc3a281ae0187e551c0226/languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt#L9011-L9040

**Comment by Dallun511** [comment]
Jep. außer du willst, dass das LanguagueTool auch falsche Formen des Verbs erkennt.

**Comment by Dallun511** [comment]
Bestimme Formen mit einem mit abgekürzten -es eines Verb habe ich noch nie gehört, wie sagts oder hilfts.
werds halte ich sogar für einen Rechtschreibfehler

**Comment by danielnaber** [comment]
@tiff ja, mit `#ugs` (tag derzeit noch nicht beachtet)

@Dallun511 siehe https://github.com/languagetool-org/languagetool/issues/1186#issuecomment-423133857

**Comment by Dallun511** [comment]
@danielnaber ich kenne den Therad. Ich finde nur einige Verben mit abgekürzten -es ziemlich merkwürdig, weil ich sie noch nie gehört habe.

**Comment by tiff** [comment]
https://github.com/languagetool-org/languagetool/pull/1704

**Comment by tiff** [comment]
Behoben via https://github.com/languagetool-org/languagetool/commit/c2b399993c9d9d62fa64fdba0d2ca58714329e65
