### ISSUE TITLE
Fixed Width Expert Rule Editor

### ISSUE THREAD

**Issue by topada** [languagetool-org/languagetool#1699]
I'm suggesting a quick fix for the Expert Rule Editor. Testing a Rule can be cumbersome if the Disambiguator log gets super wide, stretching the Rule Editor Textarea aswell.

`#editor {
    **width: 1024px;**
    height: 300px;
    font-size: 14px;
}`

I know its not mobile friendly, responsive, but who is editing rules below 1024px anyway?
--JK

**Comment by danielnaber** [comment]
Thanks, I've added `max-width: 1024px;`, should be online tomorrow.
