### ISSUE TITLE
In english, false alarm 'YOUR'

### ISSUE THREAD

**Issue by yashchoubey** [languagetool-org/languagetool#1709]
Your writing
Your understanding
Your flowing hair,
Your handwriting
Your adorning words

**Comment by MikeUnwalla** [comment]
If the sentences are split with two line breaks, we _could_ use SENT_END to prevent a warning. BUT, LT cannot know the writer's intention. Possibly, "Your writing" is correct, but it is an error if the writer means "You're writing."

For sentences that are split with only one line break, it's not possible to prevent the warning. (We don't have a way to find an LF/CR character.)

In general, LT needs complete sentences (ending with a full stop) to analyse text.
