### ISSUE TITLE
[pt] user feedback: "prévios um"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1712]
From a Portuguese user of our browser addon:
> No trecho de frase "tampouco como era implementado e de quais conhecimentos prévios um profissional precisaria", foi indicado que "prévios um" é um possível erro de concordância, mas não parece ser o caso.

Not sure exactly what he manes but I think it's a false alarm

**Comment by TiagoSantos81** [comment]
This is a true positive, it is missing a comma.
