### ISSUE TITLE
[ru] запятая

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1720]
Feedback from a user:

> Виталик купил дом в садоводстве и после отпуска уезжает.
> Виталик купил дом в садоводстве, и после отпуска уезжает.
>
> Зачем перед союзом и запятая, если никогда она перед ним в таких случаях не > ставится. Одно подлежащее, два сказуемых. Кто у вас такой грамотей?

**Comment by yakovru** [comment]
False alarm. Need to improve disambiguation. (remove tag      NN:Inanim:Masc:PL:Nom     for    "отпуска" in  "после отпуска"  )


>Среда, 17 июля 2019, 8:32 +03:00 от Christopher Blum :
>
>Feedback from a user:
>>Виталик купил дом в садоводстве и после отпуска уезжает.
>>Виталик купил дом в садоводстве, и после отпуска уезжает.
>>Зачем перед союзом и запятая, если никогда она перед ним в таких случаях не > ставится. Одно подлежащее, два сказуемых. Кто у вас такой грамотей?
>
