### ISSUE TITLE
[es] single letters marked as mistake

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1721]
> Un B
> 4 x 4

![Bildschirmfoto 2019-07-17 um 16 59 01](https://user-images.githubusercontent.com/37363/61386258-43684f80-a8b4-11e9-8717-f433c50c4ce3.png)

![Bildschirmfoto 2019-07-17 um 17 00 47](https://user-images.githubusercontent.com/37363/61386364-73afee00-a8b4-11e9-9c8b-c5d2dd0f0f3a.png)

@danielnaber Shall I just add the letters to the spelling.txt or is there a smarter way of solving this?

**Comment by danielnaber** [comment]
Best might be to accept them and then have a rule like `SINGLE_CHARACTER` in English that complains about single chars, but minus many (language-specific) exceptions.

**Comment by tiff** [comment]
BTW: One letter words in all languages: https://jalu.ch/languages/one_letter_words.php

**Comment by danielnaber** [comment]
So "Ñ" etc. was added by users to be ignored? I'm asking because it's not listed at https://jalu.ch/languages/one_letter_words.php for Spanish

**Comment by danielnaber** [comment]
Done - keep open until I can add more antipattern from Wikipedia check

**Comment by tiff** [comment]
@danielnaber can we close this now?
