### ISSUE TITLE
better suggestions for split words and wrong space positions

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1729]
e.g. `I'm g oing` ("going") or `thef eedback` ("the feedback")

**Comment by danielnaber** [comment]
Partially implemented. `I'm g oing` doesn't work yet. Also, as there can now be overlapping spell suggestions ("She awaked" -> "Shea waked" + "awoke"), we'll need to better way to rank them.

**Comment by jaumeortola** [comment]
In tests, I have found results like this:

```
 Rule ID: MORFOLOGIK_RULE_CA_ES
 Message: Possible error ortogràfic
-Suggestion: Un; Són; On; Món; Bon; Con; Son; Mon; Don; Roc; Rus; Rol; Ros; Fon; Pon; Ran; Rom; Ruc; Runa; Ton; Rua; Tron; Irun; Rin; Rof; Rut; Roí; Ro; Hun; Ren; Rot; Rou; Roín; Ruf; Nun; Rod; Roin; Ronc; Bonn; Brun; Môn; Non; ROM; Roní; Ru; Ruan; Cron; Dron; Pron; Raon; Rob; Rond; Ronx; Rony; Ruà
-... va veure la capsa oberta sobre el llit d'en Ron i el va colpir la certesa del que havia pass...
-                                                ^^^                                             
-
-Rule ID: MORFOLOGIK_RULE_CA_ES
-Message: Possible error ortogràfic
-Suggestion: trull; Trull; rull; toll; roll; brull; Turull; trulls; broll; Brull; Rull; Toll; Trill; Trulla; Trulls; Trulló; trall; trill; trol; trols; trulla; trulle; trulli; trullo; trullà; trullí; rotll; rutll; tritll; trotllo; trol l
-...rtesa del que havia passat amb la força d'un troll quan envesteix. 
-                                                ^^^^^                 
+Suggestion: unt roll
+... va veure la capsa oberta sobre el llit d'en Ron i el va colpir la certesa del que havia passat amb la força d'un troll quan envesteix. 
+                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
 
```

It doesn't make sense. Perhaps you need to check that every word in between is a misspelled word, and/or limit the number of words in the error to 2 or 3 (more words is very unlikely).

**Comment by jaumeortola** [comment]
This fixes the problem I reported: https://github.com/languagetool-org/languagetool/commit/26b4a72962937fd4df935115b13cdb7ed6788447

A further improvement would be to give suggestions even if one of the word is correct. For example (in Catalan):
* `unah ora`: only the first word is a misspelled word, but the best suggestion would be: `una hora`
* `el sinteressos`: only the second word is a misspelled word, but the best suggestion would be: `els interessos`

**Comment by danielnaber** [comment]
@jaumeortola Thanks for your fixes! Could you check why "g oing" → "going" works well for en-US but not for en-GB?

**Comment by jaumeortola** [comment]
In en-US "ing" is a misspelling, but not in en-GB. Perhaps "ing" should be marked as a misspelling also in en-GB.

With the new fix, we'll have "go ing" and "going" as suggestions for British English, and "going" for American English.

**Comment by jaumeortola** [comment]
@MikeUnwalla Should we add "ing" to prohibit.txt?

**Comment by danielnaber** [comment]
Hi @jaumeortola, your commit 424a37b554475d1f6be631abc4a88378bd33b16e introduces a problem with input like `aau kete ta ra d`: `StringIndexOutOfBoundsException: String index out of range: 17` (note: to reproduce, use en-US and make sure there's no whitespace after the `ra d`)

**Comment by jaumeortola** [comment]
TODO: if the previous or the next word is a correct and frequent word, make suggestios keeping this word as it is. For example, for "estimad es" suggest "estima des", "estimades", but also "estimat es".

**Comment by MikeUnwalla** [comment]
> @MikeUnwalla Should we add "ing" to prohibit.txt?

Done (https://github.com/languagetool-org/languagetool/commit/d9a4c4e5f99400ceeeb04e476f8af55ab7283486)

**Comment by jaumeortola** [comment]
@danielnaber I see the error now on the web page: `Error: Internal Error: java.lang.RuntimeException: java.lang.RuntimeException: Could not check sentence (language: English (US)): 'aau kete ta ra d', detected: br-FR`. But I cannot reproduce it in the command line or in the tests.

Certainly, there is an error in the end position of these errors:
```
4.) Line 1, column 13, Rule ID: MORFOLOGIK_RULE_EN_US
Message: Possible spelling mistake found
Suggestion: radio
aau kete ta ra dio in the air 
            ^^^^^             
```

**Comment by danielnaber** [comment]
I can reproduce on the command line (actually the IDE, running `org.languagetool.commandline.Main`) by using `aau kete ta ra d` as input (there must not be a line break after the input - with line break, it will work). If you still cannot reproduce, which OS are you on? I test on Ubuntu with Java 8.

**Comment by jaumeortola** [comment]
I cannot reproduce the error. I am also on Ubuntu with Java 8. 
```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```
Have you tried to do "mvn clean package/install"...?

**Comment by danielnaber** [comment]
Your latest commit fixed it, thanks!

**Comment by danielnaber** [comment]
Should mostly be fixed, closing.
