### ISSUE TITLE
[DE][Fehlermeldung] LanguageTool-Bugmeldung

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1736]
Moin liebes LanguageTool-Team

![grafik](https://user-images.githubusercontent.com/40240507/61659759-95501180-acc8-11e9-9544-5d61c0c7ad17.png)

Wichtige Informationen:
Drei Dokumente waren gleichzeitih offen. 
Zwei kleine und ein größeres Dokument (circa 40 Seiten 29.452 Wörter)
Es wurde ein kleines Stück des großen Dokumentes makiert und anschließend wurde die Rechtschreibprüfung drüberlaufen gelassen, wodurch die Fehlermeldung kam.

GRüße Dallun511

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/61668688-c850d000-acdd-11e9-974e-5dbdaa2e733c.png)

Wichtige Information:
Rechtschreibprüfung wurde gestartet und das Wort: Himmelfahrtkommandos wurde durch Himmelfahrt**s**kommandos ersetzt.
Dadurch kam diese Meldung.

Grüße Dallun511

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/61815651-08819100-ae4b-11e9-9109-37a0cce19786.png)

Das LanguageTool spielt verrückt und ist total verbuggt.

Ich habe jetzt auf die neuste Version upgedatet und hoffe, dass es keine Probleme mehr gibt.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/62089350-e9c73400-b268-11e9-8780-ed464c4ecb17.png)

Das LanguageTool kommt mit Multitasking nicht klar. Es waren zwei Dokumente offen und in einem wurde die Rechtschreibprüfung aktiviert.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/63214315-2030fa00-c117-11e9-9f2f-5ce8c8b25fb7.png)

Das LangaugeTool verträgt kein Multitasking. Ich werde mal demnächst wieder mal updaten, aber ich bezweifel, dass das Problem dadurch verschwindet.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/63378392-6ba30c80-c392-11e9-80e0-959506a775d9.png)

Problem besteht weiterhin.

**Comment by FredKruse** [comment]
Das gerade eingespielte Update sollte den Fehler beseitigen, auch wenn ich mir das Entstehen nicht vollkommen erklären kann.
Also bitte nochmal ausgiebig testen!
Morgen sollte der snapshot zur Verfügung stehen.

**Comment by Dallun511** [comment]
@FredKruse Das Problem scheint gelöst zu sein. Ich möchte mich aber noch nicht festhalten und genauer testen. Bisher kam zuminstest keine Fehlermeldung.

**Comment by Dallun511** [comment]
Bisher ist die Fehlermeldung nicht mehr aufgetaucht.
