### ISSUE TITLE
weird false alarm THE_WORSE_OF

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1737]
> We are featured for one week in the header of the start page.

<img width="620" alt="Bildschirmfoto 2019-07-22 um 22 42 39" src="https://user-images.githubusercontent.com/37363/61663950-0fd15f00-acd2-11e9-867d-23de8d869099.png">

**Comment by tiff** [comment]
cc @TiagoSantos81

**Comment by MikeUnwalla** [comment]
It's probably a postag problem. The word 'header' is not a comparative adjective.

**Comment by tiff** [comment]
Thanks Mike.
