### ISSUE TITLE
Solve Maven dependency convergence issues

### ISSUE THREAD

**Issue by retomerz** [languagetool-org/languagetool#1745]
At the moment it is no possible to add a dependency to "org.languagetool:language-all:4.6"
to a clean maven project (=which passes the dependency convergence rule) without warnings.

Master branch is also affected by this issue (testet with rev e70fcb9c3421ed5b694aef0d4f6df79f7c98d8cb).

Please add maven-enforcer-plugin [1] to your project and fix the issues. Enforcer plugin can
be added to the languagetool-parent like this:

    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>3.0.0-M2</version>
        <executions>
            <execution>
                <id>enforce</id>
                <configuration>
                    <rules>
                        <dependencyConvergence/>
                    </rules>
                </configuration>
                <goals>
                    <goal>enforce</goal>
                </goals>
            </execution>
        </executions>
    </plugin>

This will cause warnings like this:

    [WARNING]
    Dependency convergence error for com.google.guava:guava:21.0 paths to dependency are:
    +-org.languagetool:languagetool-core:4.7-SNAPSHOT
      +-com.google.guava:guava:21.0
    and
    +-org.languagetool:languagetool-core:4.7-SNAPSHOT
      +-com.optimaize.languagedetector:language-detector:0.6
        +-com.google.guava:guava:18.0

One way is to fix such warnings is to check if there is a newer version of that dependency which matches with its transitive dependencies. Another way is to exclude it:

    <dependency>
        <groupId>com.optimaize.languagedetector</groupId>
        <artifactId>language-detector</artifactId>
        <version>0.6</version>
        <exclusions>
            <exclusion>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

[1] https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html

**Comment by danielnaber** [comment]
Thanks, this should be solved now.
