### ISSUE TITLE
[en] "verifys" -> "verifies"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1765]
We don't provide the correct suggestion for misspelled words ending in "ys".

![Bildschirmfoto 2019-07-30 um 12 23 59](https://user-images.githubusercontent.com/37363/62121993-06915500-b2c5-11e9-929f-f2a131693f73.png)

Seems to happen for all words: qualifys, beautifys, magnifys ...

**Comment by tiff** [comment]
fixed via https://github.com/languagetool-org/languagetool/commit/679d384616b42cc1545b522b006b17c6047c5702

**Comment by danielnaber** [comment]
Please try `./build.sh en test`, as this change seems to fail the tests. Sorry, didn't notice because the CI had a different issue and I just assumed it would be okay.

**Comment by tiff** [comment]
Done
