### ISSUE TITLE
[en] "He verifys it"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1766]
Wrong suggestion offered:
![Bildschirmfoto 2019-07-30 um 12 23 36](https://user-images.githubusercontent.com/37363/62122099-3d676b00-b2c5-11e9-9da8-b8b37cd2f0f2.png)

I think we should also suggest the suggestions generated for "verifys".

So expected suggestions would be:
* verify sit
* verifies it

**Comment by tiff** [comment]
Problem does not only exist for English. Here's a strange German example:
![Bildschirmfoto 2019-08-21 um 17 11 47](https://user-images.githubusercontent.com/37363/63444450-e9b8ef00-c436-11e9-8f86-084aa97c1321.png)

I would have expected the suggestion "u.a. Gmail"

**Comment by tiff** [comment]
Another example from https://forum.languagetool.org/t/non-existent-word/4765/2

> He wanted **to thow** us under the bus

**Comment by jaumeortola** [comment]
This is to be fixed here: https://github.com/languagetool-org/languagetool/blob/master/languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/MorfologikSpellerRule.java#L281

We added suggestions for split words not so long ago. But when one of the two words is a very frequent word (it, to, the...), then we need to provide also suggestions with this word unchanged "to thow" > "to + ...".

**Comment by jaumeortola** [comment]
Fixed here: https://github.com/languagetool-org/languagetool/commit/e7410e2a4a830da5779c9de47c33f3e810265877

But when a SuggestionOrderer is used here: https://github.com/languagetool-org/languagetool/blob/e7410e2a4a830da5779c9de47c33f3e810265877/languagetool-core/src/main/java/org/languagetool/rules/spelling/SpellingCheckRule.java#L128-L129

it will not work. Now the "split word suggestion" is ignored.
