### ISSUE TITLE
[pt] common mistakes "n" / "q"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1778]
Feedback from a user:

> there is any way to put the abreviations of a word as wrong like:
> (brazilian portuguese)
> n = não
> q = que
> and others abreviations?
> that's some commom mistakes that every brazilian do because of the internet.

**Comment by TiagoSantos81** [comment]
A replacement rule for abbreviations is a good idea. However 'n' is often used in mathematics and engineering. After the creation of Portuguese profiles for specific writing styles, this will be added.

**Comment by TiagoSantos81** [comment]
Internet abbreviation rule has been added,
