### ISSUE TITLE
[de] improve KOMMA_ZWISCHEN_HAUPT_UND_NEBENSATZ

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1782]
Zwei ähnliche Sätze und nur in einem wird das fehlende Komma gefunden:

> Das ist schön wie er das macht.
> Das ist schön wie er sein Geld verdient.

![Bildschirmfoto 2019-08-01 um 12 29 23](https://user-images.githubusercontent.com/37363/62286489-17260480-b458-11e9-8125-1b7a64c791ad.png)

**Comment by Ordoviz** [comment]
Ich denke, die Regel, die in diesem Fall angepasst werden muss, heißt INDIREKTE_FRAGE. Für diesen Fall haben wir auch schon https://github.com/languagetool-org/languagetool/issues/228#issuecomment-363363383; man könnte den Issue hier also schließen.
