### ISSUE TITLE
[de] false alarm UPPERCASE_SENTENCE_START

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1795]
Passiert mit:

> Bzw. war das Tool kaputt.

aber nicht mit:

> Prof. war heute nicht da.

<img width="363" alt="Bildschirmfoto 2019-08-06 um 20 07 35" src="https://user-images.githubusercontent.com/37363/62564989-2bb63280-b886-11e9-9e6d-aaf69f03cbda.png">

**Comment by danielnaber** [comment]
"Bzw." am Satzanfang ist schon *sehr* umgangssprachlich... habe es aber mal erlaubt.
