### ISSUE TITLE
[fr] bad suggestions for accidentally compounded words

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1797]
> Parcontre

doesn't suggest the word "par contre"

![Bildschirmfoto 2019-08-07 um 10 17 06](https://user-images.githubusercontent.com/37363/62606438-88eccb00-b8fc-11e9-955a-9d0557dcba87.png)

> Àla carte

doesn't suggest "À la"

![Bildschirmfoto 2019-08-07 um 10 16 13](https://user-images.githubusercontent.com/37363/62606444-8ee2ac00-b8fc-11e9-9e86-ac3d5f1ac4e5.png)

> Jesuis

doesn't suggest "Je suis"

> Monamie

doesn't suggest "Mon amie"

**Comment by tiff** [comment]
This works in other languages (I tested English and German) for common words

**Comment by danielnaber** [comment]
`fsa.dict.speller.runon-words=true` in `fr_FR.info` fixes that but the suggestion comes too far at the end so it doesn't really help... needs more debugging.

**Comment by danielnaber** [comment]
Should be fixed/improved now.

**Comment by tiff** [comment]
Closing this.
