### ISSUE TITLE
[es] "sandwich" or "sándwich"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1798]
Feedback from a user:
> Sándwich va con acento y no marca el error

Should we add "sandwich" to the prohibit.txt?

**Comment by tiff** [comment]
https://dle.rae.es/ doesn't have an entry for "sandwich" but for "sándwich". So I suggest we remove "sandwich". Unfortunately there's no "prohibit.txt" for "es". So I added it, but it doesn't seem to work: https://github.com/languagetool-org/languagetool/commit/f401238020bcf6aca34841b110860b7e0a2cf7c3

**Comment by danielnaber** [comment]
Should be fixed now (https://github.com/languagetool-org/languagetool/commit/3d3a2a624e84b0eb0c8a9e9cb710e4fb5c3959e2)
