### ISSUE TITLE
exceptions for UPPERCASE_SENTENCE_START?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1799]
> iPhone is better than the Samsung Galaxy.
![Bildschirmfoto 2019-08-08 um 12 24 47](https://user-images.githubusercontent.com/37363/62695920-a0e54d00-b9d7-11e9-8fab-34bee78788db.png)

Writing "IPhone" or "IOS" feels strange. Not sure.

See: https://english.stackexchange.com/questions/9063/how-do-you-capitalize-a-proper-noun-such-as-iphone

Similar words:
* eBay
* iOS
* iPad
* iPod
* iCloud
* iRobot

**Comment by MikeUnwalla** [comment]
A possible general solution is to add an antipattern for the first word if the first letter is lower case and the second letter is upper case. Make a rule that finds those excepted words, and give the message "Make sure that the typography is correct."

I am busy with other things now, so I won't assign myself.
