### ISSUE TITLE
[fr] "Patronnage"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1805]
Feedback from a French user of [SpellBoy.com](https://www.spellboy.com)
> Pourriez-vous ajouter le mot "patronnage" dans votre dictionnaire ? Quand ce mot prend un 2nd "n" il définit un terme professionnel du métier de styliste modéliste. Je trouve de plus en plus souvent cette faute d'orthographe dans les contenus postés sur le web par des professionnels du métiers qui vont sûrement vérifier sur les correcteurs en ligne ... et qui se trompent.
> Je vous remercie par avance de prendre en compte ma demande.

@vkyfox does this make sense? can we implement it?

**Comment by vkyfox** [comment]
It does make sense, I've added it and will try to implement rules around it.
