### ISSUE TITLE
[DE] Alle Formen von "scheißen" werden nicht als vugälre Sprache markiert!

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1806]
Moin liebes LanguageTool-Team

Alles ist scheiß egal.
Sie haben wortwörtlich verschissen.
Ihr schisst um die Ecke.
Habt ihr geschissen?
Wenn wir alle anfangen zu scheißen, brauchen wir gar nicht erst gehen.
LT: "Keine Fehler gefunden!"

[Duden scheißen](https://www.duden.de/rechtschreibung/scheiszen)

Grüße Dallun511

**Comment by danielnaber** [comment]
Duplikat von #1600. Es gibt derzeit keine Regeln, die vulgäre Sprache erkennen.
