### ISSUE TITLE
No error for "Ur a nice guy"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1826]
Shouldn't we have a rule here that suggests "You're" for "Ur"? @MikeUnwalla What do you think?

**Comment by tiff** [comment]
It works for: 
> I wish ur dad were still here.

Problem seems to happen when it's capitalized.

**Comment by MikeUnwalla** [comment]
@danielnaber , yes. A POS-aware rule would be good:

> Ur was a city in what is now Iraq (www.merriam-webster.com/dictionary/ur).
