### ISSUE TITLE
WARN logging on XGBoostSuggestionsOrderer

### ISSUE THREAD

**Issue by dewos** [languagetool-org/languagetool#1833]
https://github.com/languagetool-org/languagetool/blob/d18b3e09019c36759b822324e38e9567034f866d/languagetool-core/src/main/java/org/languagetool/rules/spelling/suggestions/XGBoostSuggestionsOrderer.java#L110

Hello there. This should be a logger.warn instead of a Sys error, in order to allow the management.

**Comment by danielnaber** [comment]
Closing, as this code has been removed.
