### ISSUE TITLE
[en] wrong category for RATHER_THEN?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1839]
> The window was different than the door.

The message indicates that it's an optional correction based on the type of text.
Do we have to change the category to "STYLE"?
<img width="532" alt="Bildschirmfoto 2019-08-21 um 13 30 49" src="https://user-images.githubusercontent.com/37363/63428525-0b56ae00-c418-11e9-9bcb-04befb0d4242.png">

**Comment by MikeUnwalla** [comment]
The first rule in RATHER_THEN is a grammar/spelling rule, not a style rule. The second rule is a style rule. I suggest that you remove the second rule from RATHER_THEN and put it in the style category.
