### ISSUE TITLE
[de] strange suggestion for spelling error at end of sentence

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1842]
![Bildschirmfoto 2019-08-21 um 19 48 16](https://user-images.githubusercontent.com/37363/63455238-b2edd380-c44c-11e9-9942-8c8f8415a3cb.png)

Not sure why we suggest the extra dots. 
Easy to reproduce:

> Das werkzeug.

> Der hammer.

> Das tier.

Doesn't seem to be caused by Hunspell.

**Comment by tiff** [comment]
It still happens. One dot less, though.
![Aug-23-2019 10-40-47](https://user-images.githubusercontent.com/37363/63579258-7fb55c80-c592-11e9-8da6-33346cdb469f.gif)

**Comment by danielnaber** [comment]
The fix was probably after deployment, please check once more in 24 hours.

**Comment by tiff** [comment]
Tested it locally. Looks good.
