### ISSUE TITLE
[LibreOffice] Choose underline style

### ISSUE THREAD

**Issue by TiagoSantos81** [languagetool-org/languagetool#1845]
The new LibreOffice 6.3 allows to chose the underline style in addition to the color of the underline, which was incepted in 6.2. Grammallecte already uses this feature. 
It would be nice to have a similar feature in LanguageTool, since the default wiggly lines are too thin on high resolution screens, therefore, not providing ergonomic feedback.
LanguageTool
![Default wiggly lines](https://user-images.githubusercontent.com/22968614/63524865-a3c26080-c4f4-11e9-8e8c-414b34bc3f6f.png)
(Note that these false detections are only a LibreOffice graphical bug. They do not appear when LanguageTool is set to the main grammar engine in the Options)
Grammalecte
![Grammallecte](https://user-images.githubusercontent.com/22968614/63524873-a6bd5100-c4f4-11e9-9d0b-2e0ba22bb390.png)

.

**Comment by TiagoSantos81** [comment]
Most relevant Grammalecte commits related to this function (Python):
http://code.grammalecte.net:8080/info/efad935afcbfcef5


```
gc_core/py/lang_core/gc_engine.py.

# Writer underlining style
_bMulticolor = True
_nUnderliningStyle = 0

(...)

def setWriterUnderliningStyle (sStyle="BOLDWAVE", bMulticolor=True):
    "set underlining style for Writer (WAVE, BOLDWAVE, BOLD)"
    global _nUnderliningStyle
    global _bMulticolor
    # https://api.libreoffice.org/docs/idl/ref/FontUnderline_8idl.html
    # WAVE: 10, BOLD: 12, BOLDWAVE: 18 DASH: 5
    if sStyle == "WAVE":
        _nUnderliningStyle = 0  # 0 for default Writer setting
    elif sStyle == "BOLDWAVE":
        _nUnderliningStyle = 18
    elif sStyle == "BOLD":
        _nUnderliningStyle = 12
    elif sStyle == "DASH":
        _nUnderliningStyle = 5
    else:
        _nUnderliningStyle = 0
    _bMulticolor = bMulticolor

(...)

        if _nUnderliningStyle:
            lProperties.append(PropertyValue(Name="LineType", Value=_nUnderliningStyle))
        if _bMulticolor:
            lProperties.append(PropertyValue(Name="LineColor", Value=_dOptionsColors.get(sOption, 33023)))

```

```
gc_core/py/oxt/Grammalecte.py

        # underlining options
        self.setWriterUnderliningStyle()

(...)

    def setWriterUnderliningStyle (self):
        try:
            xSettingNode = helpers.getConfigSetting("/org.openoffice.Lightproof_grammalecte/Other/", False)
            xChild = xSettingNode.getByName("o_${lang}")
            sLineType = xChild.getPropertyValue("line_type")
            bMulticolor = bool(xChild.getPropertyValue("line_multicolor"))
            gce.setWriterUnderliningStyle(sLineType, bMulticolor)
        except:
            traceback.print_exc()
```

Other related commits:
http://code.grammalecte.net:8080/info/6e1bbe2d58ceeea9

**Comment by FredKruse** [comment]
The underline style can be selected in the option panel since LT 4.9
@danielnaber: The issue can be closed
