### ISSUE TITLE
Language tool adds canvas tag to MS SharePoint wiki pages

### ISSUE THREAD

**Issue by cverbiest** [languagetool-org/languagetool#1855]
If you edit a SharePoint wiki page using Firefox browser with Language Tool addon following tag is saved to the wiki page html

`<canvas class="lt-highlighter__canvas" width="1592" height="283" style="margin-top: 0px !important; margin-left: 0px !important;"></canvas>`

This should not be part of the saved wiki, it causes the resulting wiki page to start with a huge empty header

**Comment by cverbiest** [comment]
Same issue occurs with Chrome

**Comment by tiff** [comment]
Hi @cverbiest I will have a look. Thanks for the bug report.

**Comment by tiff** [comment]
@cverbiest this should have been fixed with v2.3.4 - can you check and confirm?

**Comment by danielnaber** [comment]
There was no feedback - I assume it has been fixed, so I'm closing this.
