### ISSUE TITLE
[de] BRAUCHEN_ZU suggestion in parenthesis 

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1865]
> Du brauchst nichts mehr machen.

![Bildschirmfoto 2019-08-26 um 16 50 29](https://user-images.githubusercontent.com/37363/63699734-b654d680-c821-11e9-8c86-ff9f2b731666.png)

**Comment by f-knorr** [comment]
@tiff : Wo ist hier Problem? Die Fehlermeldung ist vollkommen zutreffend?

**Comment by tiff** [comment]
Der zweite Vorschlag steht in Klammern

**Comment by f-knorr** [comment]
Wir haben hier eine Regel, mit der beide Inifinitivvarianten abgedeckt werden.
Deshalb steht hier immer eine Lösung in Klammern.
Bei einem erweiterten Infinitiv mit 'zu' (z. B. "aufzumachen") wäre es genau umgekehrt

**Comment by f-knorr** [comment]
closed as duplicate of #1523
