### ISSUE TITLE
[en] false alarm PRONOUN_NOUN

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1869]
> He was calling you several times today.

![Bildschirmfoto 2019-08-27 um 08 07 19](https://user-images.githubusercontent.com/37363/63745131-b5fc2000-c8a1-11e9-9a1f-c752e08fe6f7.png)

**Comment by kostyfisik** [comment]
It probably should be: 
He called you several times today.

**Comment by MikeUnwalla** [comment]
@kostyfisik , I corrected the false positive. It is not possible to give a suggestion with the rule PRONOUN_NOUN. (Depending on the meaning, I think that there is no problem with "He was calling you several times today.")
