### ISSUE TITLE
[en] "I do not forgot."

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1871]
We don't find an error in:
> I do not forgot.
> He does ran fast.

**Comment by MikeUnwalla** [comment]
- [ ] I do not forgot.
- [ ] He does ran fast.
- [ ] I do forgot to do the work.
- [ ] She does forgot to do the work.
- [ ] I do forgets to do the work.
- [ ] Sometimes, they do forgets to correct the errors.
- [ ] I do sometimes forgets to do the work.

**Comment by MikeUnwalla** [comment]
@tiff, @danielnaber, I had thought about trying to add 'do' to DID_BASEFORM[1]. But, because of #2068, I think a safer and faster option is to make a new rule. If you don't agree, please tell me.

**Comment by tiff** [comment]
I agree with you :)

**Comment by MikeUnwalla** [comment]
I closed the issue, but there are 2 errors that I do not know how to find:
- [ ] I did _copying_ and paste the code that you recommended to create the app but I am getting this error:
- [ ] If technicians who are rather lazy do sometimes (more like every day! lol) _forgets_ to do the work, tell the manager.
