### ISSUE TITLE
[fr] false alarm FRENCH_WHITESPACE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1872]
![Bildschirmfoto 2019-08-27 um 15 07 53](https://user-images.githubusercontent.com/37363/63773933-7e5e9980-c8dc-11e9-9102-bc4d867c6cf2.png)

Please note: FRENCH_WHITESPACE is currently disabled by default on languagetool.org

**Comment by vkyfox** [comment]
This is very strange. I have been unable to reproduce the error and the only error messages containing "insécable" in grammar and grammar_premium are
> Il faut utiliser une espace insécable avant l’unité. Voulez-vous écrire <suggestion><match no="1" regexp_match="(\d+)(.*)" regexp_replace="$1 $2"/></suggestion> ?

and
> Il faut utiliser une espace insécable avant le symbole des pourcentages. Voulez-vous écrire <suggestion><match no="1" regexp_match="(\d+)%" regexp_replace="$1 %"/></suggestion> ?

**Comment by tiff** [comment]
Seems like this is a java rule. @danielnaber I think you have to take care. QuestionWhitespaceRule.java seems to be the place where this needs to be fixed.

**Comment by tiff** [comment]
BTW: the rule also matches when the sentence ends with more than one exclamation or question mark. I think it's not very likely that there needs to be a space in between. 
![Bildschirmfoto 2019-09-02 um 11 12 51](https://user-images.githubusercontent.com/37363/64103473-a2096000-cd72-11e9-9f4a-e4112064d3fa.png)
