### ISSUE TITLE
[pt] wrong suggestion GENERAL_NUMBER_FORMAT

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1873]
@TiagoSantos81 shouldn't the suggestion be: "60 449 079"?

![Bildschirmfoto 2019-08-27 um 16 14 32](https://user-images.githubusercontent.com/37363/63778848-e1086300-c8e5-11e9-8314-cb66a8470686.png)

**Comment by ijakpa2** [comment]
Stop sending me this mail

**Comment by TiagoSantos81** [comment]
@ijakpa2 Buddy, check you GitHub setting.
