### ISSUE TITLE
[es] "¿Como estas?" not detected

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1876]
The missing accents are not detected:
> ¿Como estas?

It should be:
> ¿Cómo estás?

**Comment by TiagoSantos81** [comment]
¿Como estas? -> Do I eat those?
¿Cómo estás? -> How are you?

Nothing to fix here.

**Comment by jaumeortola** [comment]
`¿Como estas?` could be translated as `Do I eat those?`, yes. But it is very unusual. More commonly it means `Like these?` (= similar to these?).
