### ISSUE TITLE
[DE] "ihr endlich Vertrauen"

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1889]
Moin liebes LanguageTool-Team

Lilith sagte: „Dallun zweifelt an Nozomi und ich möchte diese Zweifel beenden, damit er **ihr endlich Vertrauen** kann.“
LT-Fehlermeldung: "Möglicherweise fehlende grammatische Übereinstimmung zwischen Artikel, Adjektiv und Nomen bezüglich Kasus, Numerus oder Genus. Beispiel: 'mein klein Haus' statt 'mein kleines Haus'"
"endlich" hat keine reflektierte Form, zumindest kenne ich keine.

Grüße Dallun511

**Comment by janschreiber** [comment]
Der Fehler verschwindet, wenn du "vertrauen" kleinschreibst, wie es richtig ist.
