### ISSUE TITLE
[pl] feedback ZDANIA_ZLOZONE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1892]
From a user of our browser addon:

> This rule ```Punctuation W tym zdaniu złożonym brakuje przecinka lub spójnika między jednym czasownikiem („ma”) a drugim („upoważnia”).``` should not be taken into account if "i" conjuction occurs between verbs.

**Comment by kam193** [comment]
Another example of false alert from this rule:

Sentence: `To działa jak chce.`
The rule detects it as complex sentence and propose inserting coma, but it's a comparison and shouldn't have coma (see: https://sjp.pwn.pl/poradnia/haslo/Przecinek-przed-jak;16291.html).

**Comment by milekpl** [comment]
It's not a false alarm. There should be a comma (the example mentioned on the website does not contain a complete subordinate statement). The first one is not actionable because no example was given.
