### ISSUE TITLE
[pt] missing words from dictionary

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1894]
A user of our browser add-on complained that the words "recepção" and "associação" are missing in our dictionary.

**Comment by TiagoSantos81** [comment]
Which Portuguese variant? And which plugin? I see nothing on https://chrome.google.com/webstore/detail/grammar-and-spell-checker/oldceeleldhonbafppcapldpdifcinji

**Comment by tiff** [comment]
Hm, I just checked. I can't reproduce either. She used pt-PT

**Comment by tiff** [comment]
I have asked the user.

**Comment by TiagoSantos81** [comment]
'recepção' is only used in the old (AO45) Portuguese spelling. Either way, if this is **lt-premium** user complaints, the bug report should go to that project issue tracker.

**Comment by tiff** [comment]
It isn't premium related.

**Comment by TiagoSantos81** [comment]
False report. Closing.
