### ISSUE TITLE
[ru] letter Ё

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1895]
Feedback from a user:
> Считает употребление буквы Ё или ё ошибкой.

**Comment by kostyfisik** [comment]
duplicate of #454 ?

**Comment by tiff** [comment]
Ah sorry. Probably.

**Comment by kostyfisik** [comment]
![Screenshot from 2019-09-02 12-17-03](https://user-images.githubusercontent.com/5239997/64103815-aa19cd80-cd7b-11e9-8080-5cde60ca983a.png)

**Comment by tiff** [comment]
The user who contacted us was using latest LT version (that was deployed yesterday). Should I ask for an example sentence?

**Comment by kostyfisik** [comment]
Yes, sure. You can add it to the original issue on letter Ё.
