### ISSUE TITLE
[de-at] Austriazismen

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1896]
Many Austrian words "Austriazismen" are not in our dictionary.

e.g.

* Bankomatkarte
* Aufpudler
* Aviso
* Dolm
* zersprageln

Full lists:
https://www.openthesaurus.de/synset/variation/at?offset=0&max=20
https://de.wikipedia.org/wiki/Liste_von_Austriazismen
https://www.korrekturen.de/synonyme/austriazismen.php

**Comment by danielnaber** [comment]
Should be much better now that we have manually imported words from OpenThesaurus to `spelling.txt`. I'll go once more over the list in Wikiepdia.
