### ISSUE TITLE
[en] FEWER_LESS question

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1905]
I see many users disable the rule for "FEWER_LESS" the phrase "stars or less".

> I would only give that hotel 3 stars or less.

For me as a non-native speaker, it feels strange to replace "less" with "fewer".

<img width="572" alt="Bildschirmfoto 2019-09-04 um 08 48 15" src="https://user-images.githubusercontent.com/37363/64231889-06eac480-cef1-11e9-8620-7e2aff1eb0de.png">

@MikeUnwalla I would be happy to hear your opinion

**Comment by MikeUnwalla** [comment]
@tiff, I agree with you.

Our competition has a good explanation: https://www.grammarly.com/blog/fewer-vs-less/

**In this context**, you can think of '3 stars' as non-countable quantity.

**Comment by tiff** [comment]
Thanks. I will add "stars" to the exceptions.

**Comment by tiff** [comment]
https://github.com/languagetool-org/languagetool/commit/f9e88b500d78a91fb256f9d265682e68da6ab308
