### ISSUE TITLE
CORS preflight OPTIONS request answered 400

### ISSUE THREAD

**Issue by black-snow** [languagetool-org/languagetool#1908]
It seems like the automatic preflight request that's issued by the browser when firing a CORS request is answered with a status code 400 instead of 200.

Also the server complains:
> 2019-09-04 14:40:10 +0000 An error has occurred: 'Missing 'text' or 'data' parameter', sending HTTP code 400.

Glancing at the code it seems like there's actually no handling for preflight requests yet. So when I issue a request against `/v2/check` the browser sends an OPTIONS request to `/v2/check` but languagetools behaves as if it was a POST request and for there are no parameters (`text`) it answers the preflight request with `400`.

The check handler should check if the http method is OPTIONS and answer accordingly. The same is probably true for any other endpoints. So it might be useful to handle OPTIONS requests further up the chain.

**Comment by danielnaber** [comment]
Thanks for your report. When you say

> So when I issue a request against /v2/check

how exactly do you send that request? Can you post some code?

**Comment by black-snow** [comment]
Sadly, I have to use [prototypejs](http://api.prototypejs.org/ajax/) (which also by default adds custom headers, that force the preflight request in the first place). However, I guess we should handle those preflight requests.

I added some basic handling (will file a PR) but the latest 4.7 snap seems to be broken - my request breaks with:

```
Exception in thread "lt-server-thread-1" java.lang.NoSuchMethodError: org.languagetool.UserConfig.<init>(Ljava/util/List;Ljava/util/Map;ILjava/lang/String;Lorg/languagetool/LinguServices;Z)V
        at org.languagetool.server.TextChecker.checkText(TextChecker.java:213)
        at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:119)
        at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:70)
        at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:154)
```
The request was to `...:8081/v2/check` with parameters `text=abc&language=de-DE`.

**Comment by black-snow** [comment]
Actually, it works fine without the custom headers added by prototypejs as there's no preflight request without them.

**Comment by danielnaber** [comment]
Frankly, we consider this more to be a prototypejs issue. As there's a workaround for your side, we think it wouldn't make much sense to implement the OPTIONS request in LT.

**Comment by black-snow** [comment]
@danielnaber thanks for your quick replies!

I'm not sure if there aren't more cases where a preflight request will be issued. As soon as you send a cookie a preflight request should be issued. For now I am fine with surpressing the additional headers but why shouldn't we handle OPTIONS requests as they should be? It's not much code and *imho* makes LT an *even better* tool.

**Comment by danielnaber** [comment]
We hardly get any of those `Missing 'text' or 'data' parameter'` errors in our logs, so this doesn't seem to be a widespread problem.

**Comment by black-snow** [comment]
Well, it's your call. I'd appreciate it - removes some headaches in edge cases. I do understand, though, that you might not want to bloat the code with stuff that'll probably barely be used.
