### ISSUE TITLE
Command line option to use other false friend files 

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#192]
[copied from http://sourceforge.net/p/languagetool/bugs/144/]

Please offer an option so that LanguageTool will not use the [languagecode]/grammar.xml and false-friends.xml files but files specified in options on the command line. I would like to propose these options:
--override-grammar-xml FILE (e.g. /tmp/languagetool/rules/nl/grammar.xml)
--override-ff-xml FILE (e.g. /tmp/languagetool/rules/false-friends.xml)

For more intensive testing, I would like to propose this option:
--override-rules-path PATH (e.g. /tmp/languagetool/rules)

Implementing this to be able to override to use which XML files will make development and testing of rules more easier.

**Comment by milekpl** [comment]
Added --rulefile to implement the first option. The false friend file support needs to be reworked anyway...

**Comment by milekpl** [comment]
Implemented.
