### ISSUE TITLE
[de] wrong suggestion F_ANSTATT_PH

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1920]
> Der PARAGRAPH ganz unten!

<img width="368" alt="Bildschirmfoto 2019-09-06 um 11 17 59" src="https://user-images.githubusercontent.com/37363/64416811-2bcd6c00-d098-11e9-82e3-c904c6b54bbc.png">

Same word is suggested again.

**Comment by danielnaber** [comment]
@f-knorr Your change also removes the (correct) suggestion for "Paragraph", though. I think the issue @tiff here has is that the suggestion doesn't work because of the uppercase characters.

**Comment by f-knorr** [comment]
> @f-knorr Your change also removes the (correct) suggestion for "Paragraph", though. I think the issue @tiff here has is that the suggestion doesn't work because of the uppercase characters.

Yes, you're right. Actually, I was not aware that 'Paragraf' is correct.
