### ISSUE TITLE
Adding custom disambiguations from CLI

### ISSUE THREAD

**Issue by JeanMertz** [languagetool-org/languagetool#1922]
I'm looking into integrating the `languagetool` CLI into my Vim editor where I do most of my (technical) writing.

I've got it integrated using the [ALE](https://github.com/dense-analysis/ale) plugin for Vim, but I'd like to customise its functionality.

Specifically, I would like specific patterns to never match when checking a document.

If my understanding after reading (parts of) the documentation is correct, I should be able to do this using disambiguations.

For example, in my technical (Markdown-based) writing, I want languagetool to ignore anything in-between code blocks, and so I've started writing a custom rule like so:

```xml
<rules lang="en-GB">
    <category name="trivial category">
        <rule name="ignore code" id="IGNORE_CODE">
            <pattern>
                <token regexp="yes">```\w* [\s\S]*?```</token>
            </pattern>
            <disambig action="immunize"/>
        </rule>
    </category>
</rules>
```

Which would ignore anything except the first and last line in an example like this one:

```
hello world

\```json
{ "test": "test" }
\```

test
```

The regex pattern might not be exactly what I want yet, but it's a start, and I want to see if this works.

However, I'm having difficulty understanding how I can use this new disambiguation combined with any already existing ones, in this case for `en-GB`.

I tried running the CLI like this:

```
languagetool --language en-GB --encoding utf-8 --rulefile ~/.config/languagetool/en-GB.xml test.md
```

But I'm pretty sure the `--rulefile` is not meant to be used for disambiguations (if it is, then there's probably something wrong with my rule, as it's not ignoring my code blocks).

I couldn't find any existing requests for this feature, or how to do this without writing custom Java code (which is what the wiki states I should do).

Is this at all possible using the technique I described, or perhaps some other way?

**Comment by danielnaber** [comment]
Your `<token>` will not work because it contains whitespace. See https://community.languagetool.org/analysis/index?lang=en for how text is tokenized. As far as I remember, there's no command-line switch to specify a disambiguation file. I think you'll need to modify the existing `disambiguation.xml`.
