### ISSUE TITLE
[es] Spanish names with "acento"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1926]
Feedback from a user:
> Spanish names such as Tomas and Hector which in Spanish have an "acento" are not detected by the software as mistakes when there is no"acento" 

I can confirm:
![Bildschirmfoto 2019-09-09 um 18 37 44](https://user-images.githubusercontent.com/37363/64549410-f0999a00-d330-11e9-8c49-80546d109968.png)

**Comment by tiff** [comment]
Another user report:
> Don't show possible error with "Maquina", correct should be Máquina with accent on the first a

Is this maybe a general problem?

**Comment by tiff** [comment]
I added "maquina" to the "prohibited.txt" and "máquina" to the spelling.txt.
This worked. However, the same approach didn't work for "Hector".

**Comment by jaumeortola** [comment]
"maquina" is a valid form of the verb "maquinar" ("él/ella maquina" ~ "he/she devises"). Anyway, "máquina" (noun) is more frequent than "maquina" (verb). To solve this issue properly, what is needed is a rule like PortugueseAccentuactionCheckRule.java or CatalanAccentuactionCheckRule.java. I think the rule can be just copied as it is. We only need to generate a list of matches like "maquina/máquina",  verbs-nouns or verbs-adjectives.
