### ISSUE TITLE
[de]Standard is flagged as wrong, Stand is suggested as correct

### ISSUE THREAD

**Issue by siduxdevil** [languagetool-org/languagetool#1928]
Happened in the following sentence: Verläuft dies problemlos, soll DoH zeitnah bei Firefox zum Standard werden. 

![standard-stand](https://user-images.githubusercontent.com/194450/64598219-a6a7c700-d3b7-11e9-8795-4c072d9acdb0.png)

**Comment by tiff** [comment]
Hi @siduxdevil I think there's some kind of invisible space (maybe a zero-width-space) in between "Standa" and "rd".

I can't reproduce the issue with the sentence.
