### ISSUE TITLE
Better cooperation with LightProof extension 

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#193]
[copied from https://sourceforge.net/p/languagetool/bugs/143/, also see old comments there]

Currently our users need to manually disable LightProof after installing LT in LibreOffice, which is a bad user experience: they first need to know what to do, then find the option, and then see if everything works now. What could we do to improve that?
- automatically disable LightProof when LT gets installed? Requires using the API to modify XML configuration. This didn't work well when I last tried.
- change LP to optionally use LT internally, if it is installed
- change LO so it can use several checkers at the same time. Conflicts will need to be resolved, i.e. there would need to be an order if both grammar checkers complain about the same text. What to do with partially overlapping errors?

Any suggestions and opinions are welcome.

**Comment by FredKruse** [comment]
The first bullet is implemented now, by switching the configured proofread services to LT (disable Lightproof). Please test it. My installation had always preferred LT.

**Comment by FredKruse** [comment]
@danielnaber Do you think, we can close this issue?

**Comment by danielnaber** [comment]
@FredKruse sorry, I lack the time to test this now.

**Comment by FredKruse** [comment]
I'm closing the issue as resolved. If necessary, please open a new one with the current versions (LO and LT).
