### ISSUE TITLE
[en] "a scissor"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1932]
> He grabs a scissor and cuts

![Bildschirmfoto 2019-09-12 um 07 41 31](https://user-images.githubusercontent.com/37363/64756908-c31b3f00-d530-11e9-9ffa-967b8fcf7d5a.png)

Can a native English speaker tell me whether this is a false alarm, or if "a scissor" is really not correct. If not correct what would be the correct way of saying it?

**Comment by MikeUnwalla** [comment]
I think the warning is not a false alarm. The usual term is 'a pair of scissors' or 'scissors'.
