### ISSUE TITLE
cleanup for CHILDISH_LANGUAGE

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1937]
List cleaned by our native speaker:

[Childish_filtered.txt](https://github.com/languagetool-org/languagetool/files/3610019/Childish_filtered.txt)

**Comment by tiff** [comment]
The list contains "so there", "number one" and "number two". As said I'm not sure about those terms being childish. See regressions: https://internal1.languagetool.org/regression-tests/20190911/result_en_20190911.html

**Comment by danielnaber** [comment]
Next attempt - assumes matching is case-sensitive, as otherwise titles and name like "Skellington" would match:

[Childish(1).txt](https://github.com/languagetool-org/languagetool/files/3610250/Childish.1.txt)

**Comment by tiff** [comment]
@TiagoSantos81 I'm sorry to bring this up again and to be so picky.
As far as I understand the new fix, you are now marking "so there", "number one" and "number two" as childish, when they are at the end of a sentence or a followed by a comma.

I found many examples where "number one" at the end of a sentence isn't childish.

* "... the former of which made him the only artist in UK chart history to have two songs spend at least nine weeks at number one." (https://en.wikipedia.org/wiki/List_of_UK_Singles_Chart_number_ones_of_the_2010s) 
* "The UK Albums Chart is a record chart based on weekly album sales in the United Kingdom; during the 1960s, a total of 57 albums reached number one." (https://en.wikipedia.org/wiki/List_of_UK_Albums_Chart_number_ones_of_the_1960s)
* "This allowed several tracks to debut at number one." (https://en.wikipedia.org/wiki/Billboard_charts)

Example of "so there" followed by punctuation:

* "we did not go out a lot when we during our first year or so there." (https://books.google.de/books?id=I3nYBQAAQBAJ&pg=PA136&dq=%22so+there%22&hl=en&sa=X&ved=0ahUKEwjIncTGhs7kAhXu0aYKHZk8AS0Q6AEIXDAH#v=onepage&q=%22so%20there%22&f=false)

These are just a few examples. I would suggest removing them completely from the rule.

**Comment by tiff** [comment]
Ah, I might have misunderstood the regexp.

**Comment by danielnaber** [comment]
Running the rule over Tatoeba, I found these false alarms:

* This guy is really wishy-washy.
* Jane's dream was to find herself a sugar daddy.
* Sho was 12 years old, ...
* ...was one of the defining mistakes of Dolly's brief career as president...
* A doodle is a drawing made while a person's attention is otherwise occupied. (not sure about this one)
* Would you like to taste this yummy cake? (not sure about this one)

**Comment by TiagoSantos81** [comment]
All casses and a few more solved. Closing.
