### ISSUE TITLE
clean up for PROFANITY

### ISSUE THREAD

**Issue by TiagoSantos81** [languagetool-org/languagetool#1938]
Clean-up from regressions
[profanities.txt](https://github.com/languagetool-org/languagetool/files/3610889/profanities.txt)

**Comment by danielnaber** [comment]
Here's a list of what sound like false alarms to me (`PROFANITY` and `RUDE_SARCASTIC`, from Tatoeba):

```
It's fine, just make sure you don't say that again.
God was truly glorified today!
What's new?
When the dog tried to bite me, I held him down by the neck...
Yes, sausage and sauerkraut please.
A single ray of sunlight shone through a chink in the shuttered window.
We have to nip this problem in the bud before it gets any worse....
Squaw Valley, California
illegal immigrant
...the middle finger, the ring finger, and the pinky.
What do you know about Tom's girlfriend?
knock up
Tom graduated with Magna Cum Laude.
I hope you're happy together.
transgender
Thanks a heap.
I have to change the baby's nappy.
get screwed
She has snow-white skin.
...the tick of the clock, the whoosh of cars passing by the house.
So what else is new?
genderqueer
One day our children will take over our paddy planting.
```

The following ones might not be false alarms, but they show that the current message isn't specific enough. It needs to explain more about why the term can be inappropriate, and possibly suggest alternatives:

```
Deaf-mute people talk using sign language.
The Koran does not permit Mohammedans to drink.
My aunt is from Somalia. She is Somalian.
Can I scrounge a fag?
```

**Comment by danielnaber** [comment]
More potential false alarms for `PROFANITY` from https://internal1.languagetool.org/regression-tests//20190913/result_en_20190913.html:

* Additional Jim Crow laws were passed after the start of the 20th cent...
* ...as placed aboard by the ship's crane, placed on a dolly and moved next to the MQF.
* ...stop in a 13.5 foot (4.05 meters) sailboat named "Tinkerbell".
* Pathe De Munt is modern and is located at the Muntplein.
* Anatolian black pine (Pinus nigra)
* ...was written by John Phillips of the Mamas and the Papas.
* Winnie-the-Pooh
* Willy DeVille, American singer-songwriter and guitarist...
* willy nilly
* Vinny Del Negro, American basketball player and coach

**Comment by TiagoSantos81** [comment]
Yesterday a few words that I though removed passed through (e.g. illegal immigrants). Should be fixed now.
Regarding this last list that I did not handle. Scientific, regional and foreign names were already tagged (but as generic spelling errors). They are rare occurrences, even for specialized writers, the writer is well aware of the special meaning it is using it and they can be basically anything. 
In countries were naming conventions are not mandatory for children's name registry you can have names. Tranlate https://www.techtudo.com.br/noticias/noticia/2014/07/facebook-exclui-perfis-de-usuarios-brasileiros-com-nomes-estranhos.html if you are in for a laugh.
Informal formal are not yet handled, but in the coming days I will push that as well. For now, lowercase 'willy' should be tagged as something wrong, same as 'willy nilly' is.

Of course, if you think that words as "negro" is not offensive, and "mama" and "papa" is not childish, go ahead and remove than. That is on you, but I won't do it, since I would be doing noone I care about a favor.

**Comment by TiagoSantos81** [comment]
All casses and a few more solved. Closing.
