### ISSUE TITLE
[es] Gender and number mistakes not being caught 

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#195]
[copied from http://sourceforge.net/p/languagetool/bugs/97/]

I've just installed the tool, and I've been running tests to see if the mistakes are caught. The mistakes in these sentences were not caught by the tool:

Los hombres tiene sed. Un mujer sabe lo que hace. La personas no saben lo que hacen. Las persona no saben lo que hacen. No saben lo que hacen la personas que viven aquí. La personas fueron allá. Los hombre comieron.

**Comment from Juan:** Need deep disambiguator debugging. Those are words with noun + verb and noun + interjection PoS values.

**Comment by jaumeortola** [comment]
All the errors in the these sentences are caught now. The rules for subject-verb agreement will work only in very restricted contexts (short and simple sentences). Otherwise, they would produce false alarms.
