### ISSUE TITLE
Error message when launching LT

### ISSUE THREAD

**Issue by JosepVentura** [languagetool-org/languagetool#1950]
Hi, 

I have just installed my trial version of LT with STE checker, and it will not launch.

I get the following error message:
<img width="454" alt="2019-09-18" src="https://user-images.githubusercontent.com/55494176/65149727-ec513900-da22-11e9-8234-4e9482917345.png">

Thank you for your help!

**Comment by MikeUnwalla** [comment]
@JosepVentura , this forum is not for the term checker. Contact me directly.
