### ISSUE TITLE
[en] false alarm IT_VBZ?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1960]
> I'm not paying to have it continue

Not sure about this. A user complained that it suggests "continues".

![Bildschirmfoto 2019-09-23 um 07 56 52](https://user-images.githubusercontent.com/37363/65404190-d901ed00-ddd7-11e9-9f72-c6f3e9e2e7e5.png)

**Comment by MikeUnwalla** [comment]
> Not sure about this. 

The user is correct. The LT message is not correct for BrE (https://dictionary.cambridge.org/grammar/british-grammar/have-something-done). I don't know about AmE.

**Comment by tiff** [comment]
If it helps: The user is from the United States
