### ISSUE TITLE
[de] false alarm PUNCTUATION_PARAGRAPH_END

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1962]
<img width="421" alt="Bildschirmfoto 2019-09-23 um 13 54 13" src="https://user-images.githubusercontent.com/37363/65423581-b38dd700-de09-11e9-845c-aa19812673aa.png">

> Da werde ich leicht sehr sauer. Möchtest du das?
> Gruß vom Bruno

**Comment by tiff** [comment]
Related to: https://github.com/languagetool-org/languagetool/issues/1951

**Comment by Dallun511** [comment]
#1270 zeigt den gleichen Fehler.

**Comment by Dallun511** [comment]
Das wurde behoben.
