### ISSUE TITLE
support custom word

### ISSUE THREAD

**Issue by daixiang0** [languagetool-org/languagetool#1965]
Some word like user name or specify meaning or new created in some area may be not in word list, it would be good for users to support add own custom word list, then those word would not get warnings.

**Comment by daixiang0** [comment]
@MikeUnwalla any input?

**Comment by MikeUnwalla** [comment]
-  You can buy a subscription to LanguageTool Plus: https://languagetoolplus.com/

- You can use an external file: http://wiki.languagetool.org/tips-and-tricks#toc10

In disambiguation.xml, include an entity reference to your xml file. In that file, make one or more rules to ignore the spelling of your words. For examples, in disambiguation.xml, search for  `<disambig action="ignore_spelling"/>`

For 1-word (1-token) terms, only one rule is necessary. Add all the terms in a regular expression.

For each multi-word term, you will need a separate rule.

The only problem is that each time you update LT, you must add the entity reference again to the new disambiguation.xml file.
