### ISSUE TITLE
[de] "gleichzubehandeln"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1966]
Hier stimmt was nicht:

> Die sind erstmal gleich zu behandeln.

<img width="450" alt="Bildschirmfoto 2019-09-25 um 10 54 26" src="https://user-images.githubusercontent.com/37363/65585559-f2936800-df82-11e9-88e0-90cbc13abbbd.png">

> Die sind erstmal gleichzubehandeln.

<img width="476" alt="Bildschirmfoto 2019-09-25 um 10 55 25" src="https://user-images.githubusercontent.com/37363/65585593-0048ed80-df83-11e9-99e0-be61a9092287.png">

Mal abgesehen davon, ob die Regel hier Sinn ergibt: Ist "gleichzubehandeln" ein Wort, dass ich unserem Wörterbuch hinzufügen kann?

**Comment by tiff** [comment]
Hey @Discostu36 hast du hier vielleicht eine Meinung zu?

**Comment by Discostu36** [comment]
Ich bin nicht zu 100 % sicher, aber ich denke, dass, wenn das Wort im Infinitiv zusammengeschrieben wird (und das ist so [laut Duden](https://www.duden.de/node/142079/revision/142115)), dann gilt das auch für den erweiterten Infinitiv

**Comment by tiff** [comment]
Ergibt Sinn. Der Duden Mentor sagt auch, dass das Wort korrekt ist. Finde auch sehr viele Vorkommen im Netz auf Wikipedia und anderen seriösen Seiten. Ich habs einfach mal aufgenommen.
