### ISSUE TITLE
[pt] Weasel words suggestion should be only on the message string

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1969]
Feedback from a Brazilian user:

> Algumas palavras como: (mesmo que ninguém mais)pensa-se (o mesmo) ou(o sol) se pos são ditas como erradas, ou ambíguas.

I don't understand what he means (because I don't speak Portuguese) but the suggestion provided for "pensa-se" looks a little strange:
<img width="912" alt="Bildschirmfoto 2019-09-26 um 18 34 14" src="https://user-images.githubusercontent.com/37363/65707222-5eadc300-e08c-11e9-9bd2-ddc0fcdc9ec1.png">

**Comment by TiagoSantos81** [comment]
Perfectly valid. This is the rule ['weaselWords](https://en.wikipedia.org/wiki/Weasel_word)'. The ones that don't use it can just disable the rule.

**Comment by tiff** [comment]
@TiagoSantos81 have you seen the suggestion for "pensa-se" (which apparently means "think")  in the screenshot? "Quem? Como sabem?" looks not like a replacement to me. Please correct me if I'm wrong.

**Comment by TiagoSantos81** [comment]
It is not. It is just a custom message. The sentence needs to be rephrased.

**Comment by tiff** [comment]
Okay, I get it. Thanks for clarifying. I think it shouldn't be in the `<suggestion>` but part of the message. Thanks for changing the title. Makes more sense now.

**Comment by TiagoSantos81** [comment]
It is a Java rule based on AbstractSimpleReplaceRule. There may be some valid replacement suggestions, but most are not. Even with a creation of a specific third AbstractSimpleReplaceRule, the database issue would still be there.
