### ISSUE TITLE
Allow selecting native language in web GUIs

### ISSUE THREAD

**Issue by PanderMusubi** [languagetool-org/languagetool#198]
Please allow selecting native language (mother tongue or first language) in web GUIs. By default, this setting would not be set and be called "non selected". The other options would be all the languages for which false friends exist.

Additional functionality would be that the language selected for the text is not in this list. This can be hidden in the front-end by JavaScript. It has, correct me if I am wrong, no use setting native language identical to the selected language for the text. When changing the language for text, the options for native language should be updated and selection should be dropped if that language is no longer in the list to choose from.

Implementing this would enable users to choose native language, other than the language selected for the text and get reporting on any false friends found in the text. This would not be enabled if no native language is selected.

The example text in the GUI should also contain a false friend which most number of native language would report.

**Comment by danielnaber** [comment]
This has been implemented for LT 3.4.
