### ISSUE TITLE
[API] language parameter ignored?

### ISSUE THREAD

**Issue by black-snow** [languagetool-org/languagetool#1995]
I wonder what the `language` parameter for `/v2/check` does. I've built my own dictionary for my own "language" but I seem to receive suggestions from other languages when I query the server.

I named my German language variant `de-AD`.
When I query the server for "Baureinigung", which is neither in the de-DE nor my de-AD dict, I get:

```json
"language": {
    "name": "German (DTAD)",
    "code": "de-AD",
    "detectedLanguage": {
      "name": "German (Germany)",
      "code": "de-DE",
      "confidence": 0.99999493
    }
  },
  "matches": [
    {
      "message": "Möglicher Rechtschreibfehler gefunden",
      "shortMessage": "Rechtschreibfehler",
      "replacements": [
        {
          "value": "Badreinigung"
        }
      ],
      "offset": 0,
      "length": 12,
      "context": {
        "text": "baureinigung",
        "offset": 0,
        "length": 12
      },
      "sentence": "baureinigung",
      "type": {
        "typeName": "UnknownWord"
      },
      "rule": {
        "id": "GERMAN_SPELLER_RULE",
        "description": "Möglicher Rechtschreibfehler",
        "issueType": "misspelling",
        "category": {
          "id": "TYPOS",
          "name": "Mögliche Tippfehler"
        }
      },
      "ignoreForIncompleteSentence": false,
      "contextForSureMatch": 0
    }
```

although I explicitly send `language=de-AD`.
Am I missing something? Is there any way to query my language only? Do I have to create a completely new "language" instead of a variant?

Thanks in advance!

**Comment by danielnaber** [comment]
> When I query the server for "Baureinigung", which is neither in the de-DE nor my de-AD dict, I get:

`language.code` is the language that's used. `language.detectedLanguage` is just for information (and will not work well with variants).

**Comment by black-snow** [comment]
Thanks for the quick reply!

I then wonder where this suggestions comes from. `reinigung` is found in my dict but `bad` is not and neither is `badreinigung`. When building my language I also used an empty file for the _additional dict file_ and _unknown to hunspell_ file. Any guess how LT comes up with this suggestion?

**Comment by danielnaber** [comment]
Hunspell (and thus LT) has its own logic to create suggestions for compounds. "Bad" and "Reinigung" can both be used in compounds, so compounds like "Badreinigung" are generated.

**Comment by black-snow** [comment]
Thanks again for your very fast replies! @danielnaber 

Do you see any easy way for me to suppress this? Sure, I could compare the suggestions to my original dict and filter but then again I could've just done that in the first place. But I do want some of (most of) the features LT/Hunspell offers.

I'll close this for now for my initial assumption was wrong.

**Comment by danielnaber** [comment]
I don't know of a single flag that turns off compound suggestions. You could remove the compound flags from all words in `de_DE.dic` but then compounds would not even be recognized anymore.
