### ISSUE TITLE
[de] false alarm USA_PLURAL

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#1998]
> Die USA will er dabei ausgrenzen.

<img width="446" alt="Bildschirmfoto 2019-10-02 um 17 57 28" src="https://user-images.githubusercontent.com/37363/66060548-20a61880-e53e-11e9-8e28-2abb5640bf6a.png">

**Comment by Dallun511** [comment]
https://www.duden.de/rechtschreibung/USA
Laut dem Duden handelt es sich um ein reines Pluralwort, weswegen Einzahl nicht erlaubt ist.
Ich würde das nicht als Fehlalarm unterstreichen, sondern als normaler gemeldetete Fehler.

Es sind schließlich die "Ver­ei­nig­ten Staa­ten von Ame­ri­ka"

**Comment by tiff** [comment]
Danke!
