### ISSUE TITLE
[de] false positive DE_VERBAGREEMENT 

### ISSUE THREAD

**Issue by Ordoviz** [languagetool-org/languagetool#2004]
> Wie ich sehe, benötigt ihr Nachschub.

„sehe“ löst den Fehler aus, obwohl es in der Textanalyse korrekt als 1. Person Singular erkannt wird. Der Teil nach dem Komma ist irrelevant.

**Comment by Dallun511** [comment]
**Fehler 30a** 
BigDaddy sagte düster: „Wie ich **sehe**, hast du überlebt und damit hast du das Kampftraining bestanden.“
****LanguageTool-Fehlermeldung:** "Möglicherweise** fehlende grammatische Übereinstimmung zwischen Subjekt und Prädikat (sehe) bezüglich Person oder Numerus (Einzahl, Mehrzahl - Beispiel: 'Max bist' statt 'Max ist'). "
#1431 
Der Fehler ist schon länger bekannt. Ich hoffe, der Fehler wird bald behoben.
