### ISSUE TITLE
Rewrite the tool in Rust (or Kotlin/Native)

### ISSUE THREAD

**Issue by XVilka** [languagetool-org/languagetool#2006]
There is [automated Java to Rust converter](https://users.rust-lang.org/t/java-to-rust-converter/6546), so it would be amazing to be able to compile the tool and avoid unnecessary memory and CPU consumption.
Consider this example of conversion:
```java
class A {
     public A() {
       int i = 10;
       double f = 1;
       for (int i = 10; i < 100; i++) {
         f += i;
       }
   }
}
```
becomes:
```rust
struct A {
}

impl A {

  pub fn new() -> A {
     let i: i32 = 10;
     let mut f: f64 = 1;
     {
        let mut i: i32 = 10;
        while i < 100 {
            {
                f += i;
            }
            i += 1;
         }
     }
}
```
Another possibility is to convert to [Kotlin](https://kotlinlang.org/) which has the ability to compile to the native code - [Kotlin/Native](https://kotlinlang.org/docs/reference/native-overview.html)
Both ways are a way better than the current status quo. 

## Why Kotlin/Native?

Kotlin/Native is primarily designed to allow compilation for platforms where virtual machines are not desirable or possible, for example, embedded devices or iOS. It solves the situations when a developer needs to produce a self-contained program that does not require an additional runtime or virtual machine.

## Target Platforms

Kotlin/Native supports the following platforms:
- iOS (arm32, arm64, simulator x86_64)
- MacOS (x86_64)
- Android (arm32, arm64)
- Windows (mingw x86_64, x86)
- Linux (x86_64, arm32, MIPS, MIPS little endian, Raspberry Pi)
- WebAssembly (wasm32)

## Interoperability

Kotlin/Native supports two-way interoperability with the Native world. On the one hand, the compiler creates:
- an executable for many platforms
- a static library or dynamic library with C headers for C/C++ projects
- an Apple framework for Swift and Objective-C projects

On the other hand, Kotlin/Native supports interoperability to use existing libraries directly from Kotlin/Native:
- static or dynamic C Libraries
- C, Swift, and Objective-C frameworks

## Conversion

![image](https://user-images.githubusercontent.com/203261/66292445-e7432380-e916-11e9-8007-77a722717f64.png)

https://www.jetbrains.com/help/idea/converting-a-java-file-to-kotlin-file.html

**Comment by vigoux** [comment]
That's an awesome idea !

If the maintainers don't have time to invest in translating LanguageTool to rust, is it possible to have an overview of how LanguageTool works, to try reimplementing it in rust ?

**Comment by danielnaber** [comment]
I think https://github.com/bminixhofer/nlprule does this (although not using an automatic conversion).

**Comment by davdwhyte87** [comment]
My issue with Kotlin native is that it has auto-memory management. I wish they gave the option of pointers like in C

**Comment by Nyabinary** [comment]
@danielnaber Would it be possible for future contributions to be in Rust?

**Comment by danielnaber** [comment]
@Nyabinary no, there are no plans to switch to Rust

**Comment by Nyabinary** [comment]
@danielnaber Didn't mean to completely rewrite to Rust or mainly use Rust just accept contributions in Rust seeing as there Python, Perl aside from just Java, would be nice if I could contribute to LanguageTool :), Kotlin as well.

**Comment by danielnaber** [comment]
@Nyabinary we don't use Rust anywhere, so it wouldn't make sense to contribute Rust code (neither do we use Perl, other than for legacy code maybe)
