### ISSUE TITLE
[en] Unknown word 'spiers' causes a spelling error for 'sharp spiers'

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#2007]
The word 'spiers' is not known in LT. (The word is American English: www.merriam-webster.com/dictionary/spier). The word causes a spelling error for the previous word if the previous word is on the same line or the immediate next line:

![image](https://user-images.githubusercontent.com/5816160/66320287-7865ca80-e916-11e9-86e8-2e6f0c6fcba4.png)

I *think* that the problem is only with 'sharp spiers'. With 'These sharpened spiers are ...', there is no spelling error for 'sharpened'.

**Comment by jaumeortola** [comment]
This is intended. We try to make suggestions for wrongly split words:
```
thanky ou > thank you
```
So:
```
sharp spiers > sharps piers (two valid words)
```
Perhaps it can be confusing in some contexts.

**Comment by MikeUnwalla** [comment]
> Perhaps it can be confusing in some contexts.

@jaumeortola , thanks. That makes sense. 

This problem was found by a user.

Although 'spier' is in Webster and singular postag is in LT, I am not sure about adding NNS and spellings, because the word is not in https://ahdictionary.com. I did not find the common noun 'spier' on https://www.english-corpora.org/coca/, although there are approximately 80 results for each proper noun Spier and Spiers.
