### ISSUE TITLE
[fr] words in spelling.txt are not used as suggestion

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2010]
The word "Skype"(capitalized) is in the French spelling.txt.
If you write "skype" (all lower case), it doesn't suggest "Skype".

<img width="355" alt="Bildschirmfoto 2019-10-08 um 15 26 00" src="https://user-images.githubusercontent.com/37363/66399607-386b1a00-e9e0-11e9-9c10-e1f5b0189279.png">

The word "Instagram" (capitalized) is in the French spelling.txt.
If you write "instagram" (all lower case), the last suggestion that appears is "Instagram".
<img width="384" alt="Bildschirmfoto 2019-10-08 um 15 23 20" src="https://user-images.githubusercontent.com/37363/66399621-3c973780-e9e0-11e9-843e-25ccc1aa96c3.png">

**Comment by danielnaber** [comment]
"Fixed" by adding another hack... The problem was that `Skype` comes from `spelling.txt` and it results are just appended to the "regular" results, no matter how good they are.
