### ISSUE TITLE
[en] false alarm PRONOUN_NOUN

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2013]
> And he held it high up.

<img width="437" alt="Bildschirmfoto 2019-10-10 um 10 47 45" src="https://user-images.githubusercontent.com/37363/66553473-76388180-eb4b-11e9-8c38-eae2b031bdd7.png">

**Comment by tiff** [comment]
Another one I'm not so sure about:

> He so wants to finish his homework.
<img width="396" alt="Bildschirmfoto 2019-10-10 um 10 49 08" src="https://user-images.githubusercontent.com/37363/66553561-a41dc600-eb4b-11e9-90d9-e4dc28c2af5f.png">

**Comment by tiff** [comment]
@MikeUnwalla is "so" an adverb in the sentence "He so wants to ..."?
I noticed that "so" doesn't have the "RB" tag but according to Merriam it also is an adverb.

**Comment by MikeUnwalla** [comment]
'So' is an adverb. More references:
https://www.lexico.com/en/definition/so
https://www.collinsdictionary.com/dictionary/english/so
https://www.ldoceonline.com/dictionary/so

The Lexico page shows 'so' as an adverb in similar contexts to your example sentence. Refer to definition 1.2. (Yes, I am hedging! I *think* it's an adverb in your example sentence.)

**Comment by tiff** [comment]
Actually "high" (from the first example) can also be an adverb but it isn't tagged as one. Not sure though if it is an adverb in the sentence.

**Comment by MikeUnwalla** [comment]
These false alarms do not occur now (2019-11-11).
