### ISSUE TITLE
[nl] "Je" marked as spelling mistake

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2015]
@baarsrj the word "Je" at the beginning of a sentence is marked as a spelling mistake. Is this a similar problem as https://github.com/languagetool-org/languagetool/issues/2012 ?

**Comment by baarsrj** [comment]
It is. I wil correct it.

**Comment by tiff** [comment]
@baarsrj still happens:
<img width="357" alt="Bildschirmfoto 2019-10-12 um 19 48 30" src="https://user-images.githubusercontent.com/37363/66705607-51016a00-ed29-11e9-8104-4ad00262fa90.png">

**Comment by baarsrj** [comment]
Found the mistake in dictionary generation; solved.
