### ISSUE TITLE
MISSING_APOSTROPHE_T possibly returns incorrect length

### ISSUE THREAD

**Issue by jamesllewellyn** [languagetool-org/languagetool#2033]
I'm having some issues around the correction of apostrophes. 

When checking "hasn‘t" the returned length from the API is 4. This is leading to only "hasn" being highlighted and then corrected to either a straight quote or curly quote it is changed to "hasn't‘t"

<img width="945" alt="Screenshot 2019-10-15 at 14 46 02" src="https://user-images.githubusercontent.com/3028920/66860747-bf2d7300-ef5b-11e9-9680-4953f6b963d7.png">

<img width="947" alt="Screenshot 2019-10-15 at 14 46 10" src="https://user-images.githubusercontent.com/3028920/66860761-c5235400-ef5b-11e9-9a3f-bb1a0dd8747f.png">

<img width="947" alt="Screenshot 2019-10-15 at 14 46 32" src="https://user-images.githubusercontent.com/3028920/66860769-ca809e80-ef5b-11e9-9210-1145e8b6208a.png">

Here is the API response 
```
{
"message":"The abbreviation is not correct. Did you mean \"hasn't\" (straight quote) or \"hasn’t\" (curly quote).",
"shortMessage":"Grammar error",
"replacements":[{"value":"hasn't"},{"value":"hasn’t"}],
"offset":1466,
"length":4,
"context":{"text":"...something completely unnecessary. There hasn‘t been camera-worthy trouble in classro...","offset":43,"length":4},
"sentence":"There hasn‘t been camera-worthy trouble in classrooms.",
"type":{"typeName":"Other"},
"rule":{"id":"MISSING_APOSTROPHE_T","subId":"1","description":"Missing: 't",
"issueType":"grammar",
"category":{"id":"GRAMMAR","name":"Grammar"},"isPremium":false},"ignoreForIncompleteSentence":false,"contextForSureMatch":3}
```

**Comment by tiff** [comment]
I think it's the apostrophe. It's an unusal one. I'm looking into it.

**Comment by jamesllewellyn** [comment]
@tiff thanks a lot, yeah it is a strange apostrophe. It does seem to get correct right when followed by an 's' not a 't'.

Heres an example with "teacher's"

 
<img width="952" alt="Screenshot 2019-10-15 at 16 00 38" src="https://user-images.githubusercontent.com/3028920/66865491-5814bc00-ef65-11e9-8060-ca87666e74d2.png">

<img width="958" alt="Screenshot 2019-10-15 at 16 00 47" src="https://user-images.githubusercontent.com/3028920/66865503-5f3bca00-ef65-11e9-847c-ebef831a173e.png">

<img width="956" alt="Screenshot 2019-10-15 at 16 00 56" src="https://user-images.githubusercontent.com/3028920/66865513-64991480-ef65-11e9-8a0f-836d0d60162c.png">

Api response 

```
{
"message":"The word 'teacher‘s' is not standard English. Did you mean \"teacher’s\" (curly apostrophe) or \"teacher's\" (straight apostrophe)?",
"shortMessage":"Possible typo",
"replacements":[{"value":"teacher’s"},{"value":"teacher's"}],"offset":1006,"length":9,"context":{"text":"...re because people talk a lot. It is the teacher‘s job to keep people quiet. If something ...","offset":43,"length":9},
"sentence":"It is the teacher‘s job to keep people quiet.",
"type":{"typeName":"Other"},
"rule":{"id":"NON_STANDARD_WORD",
"subId":"1",
"description":"Non-standard word",
"issueType":"misspelling",
"category":{"id":"TYPOS","name":"Possible Typo"},"isPremium":true},
"ignoreForIncompleteSentence":true,
"contextForSureMatch":4}
```

**Comment by tiff** [comment]
It will take a few days until the fix is available on languagetool.org and languagetoolplus.com.
