### ISSUE TITLE
[pt] words missing in dictionary?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2040]
@marcoagpinto some more commonly ignored words:
* iFood
* Outlook
* Nathalia
* Chromecast

Also:
* Whatsapp
* whatsapp (all lowercase)
* instagram (all lowercase)
* facebook (all lowercase)

I think we need rules for them because their correct spelling isn't suggested at least not in pt-br.

**Comment by marcoagpinto** [comment]
Well, the proper way to write the last four is in uppercase.

I will add in uppercase.

**Comment by tiff** [comment]
I think they are already in the dict in uppercase. The problem is rather that the correct word isn't suggested:
<img width="365" alt="Bildschirmfoto 2019-10-17 um 12 50 06" src="https://user-images.githubusercontent.com/37363/67002656-ab5d4a80-f0dc-11e9-9c71-1966a7b492fd.png">

I would suggest creating simple XML rules for those 4 terms. (also Whatsapp should be WhatsApp)
