### ISSUE TITLE
[DE] Problem "dm", die Drogeriemarke

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#2041]
Moin LanguageTool-Team

Es wurde zwar bereits in diesem [Therad](https://forum.languagetool.org/t/de-mit-dm-eure-meinung/4402) über das Problem **dm** diskutiert, aber bisher ist noch keine Lösung gefunden worden.

***
Erstes Beispiel:
Ich verkündige euch heute, dass wir **mit dm LanguageTool** viel erreicht haben, leider sind immer noch leichte Fehler vorhanden.
***
Was muss die Regel beherrschen?
***
- [ ] **mit dm** + Nomen sollten **als Fehler** erkannt werden.
Beispiele:
Ich fahre **mit dm** Bus in die Schule.
Ich bin **mit dm** Wagen nach Hause gefahren.
***
- [ ] **mit dm** + Verb sollte keinen Fehlalarm auslösen.
Beispiele:
**Mit dm** habe ich gute Erfahrungen gemacht.
**Mit dm** sind wir glücklicher, als vohrer.
Wir sind **mit dm** glücklich.
Aber **mit dm** werde ich mich nicht anlegen.
***

Ich habe weitergedacht und noch weitere Probleme entdeckt, die **unbedingt** berücksichtigt werden müssen.

***
- [ ] auf + **dm** + **Nomen** + Verb = **Alarm**:
Beispiele:
**Auf dm Rücken** liegt das Problem.
**Auf dm Parkplatz** wurde scharf geschossen.
**Auf dm Gelände** müssen folgende Regeln beachtet werden.
***
 [ ] auf + **dm** + Verb = darf **kein Alarm** folgen.
Beispiele:
**Auf dm** ist Verlass.
**Auf dm** werde ich zukünftig verzichten.
**Auf dm** wurde ich gestern erst aufmerksam.
***

Adjektive:
- [ ] mit/ auf/ über + **dm** + Adjektiv + Nomen = **immer Fehler**
Beispiele:
**Auf dm schlechten Parkplatz** konnte ich nicht sehen.
**Mit dm langsamen Wagen** komme ich nie nach Hause.
**Über dm schlechten Tag** möchte ich nicht reden.
**Bemerkung:** Die Beschreibung der Fehlermeldung soll darauf hinweisen, dass es **entweder mit dem/ auf dem/ über den oder dms** heißen muss, wenn wirklich dm gemeint ist.

**Ausnahme!**
Auf **dms** schlechten Parkplätzen kam es zum Unfall.
**Bemerkung:** Hier darf es nicht zu einem Alarm kommen, denn dm liegt hier im Genitiv vor.

***
**Besonderheiten!**
- [ ] Sonderfälle: **Wichtig Bemerkung lesen**
**Mit dm dm** werde ich mich nicht anlegen.
**Bemerkung:** Hier sollte **nicht** die "**Wortwiederholungsregel**" anschlagen, sondern eine gesonderte Regel, die fragt: "Meinten sie **mit dem dm**?"

Ich habe viel **über dm dm** gehört.
**Bemerkung:** Hier sollte **nicht** die "**Wortwiederholungsregel**" anschlagen, **sondern eine andere Regel,** die darauf aufmerksam macht, dass hier der Akkusativ erforderlich ist.
***

Das sind die Probleme, die mir eingefallen sind. Wenn ihr Ergäzungen oder mehr Beispiele habt, nur her damit. Ich habe ein großes Interesse, dass dieses Problem gelöst wird.

Grüße Dallun511 Ferewo

**Comment by danielnaber** [comment]
Sollte mit dem nächsten Deployment (heute Nacht) behoben sein, wobei Spezialfälle wie "Mit dm dm werde ich mich nicht anlegen" nicht gesondert betrachtet werden.
