### ISSUE TITLE
[DE] Wo soll hier noch ein Komma hin?

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#2054]
Moin liebes LanguageToo-Team

***
- [ ] Anastasia und Leonie **hatten nichts weitererzählt, dass Sandra Lucia entführt hat, weswegen die Klasse keinen Groll auf Sandra hatte.** 
LT: "Hier sollte ein Komma eingefügt werden, wenn es sich bei dem hinteren Satzteil um einen Nebensatz handelt."
***
- [ ] Das **hatte die Folge, dass er für alles beschuldigt wurde, wofür es keine Antworten gab**, wenn der Herrscher seine Soldaten losschickte, um ihn töten zu lassen.
LT: "Hier sollte ein Komma eingefügt werden, wenn es sich bei dem hinteren Satzteil um einen Nebensatz handelt."
***
- [ ] Dark Dallun **nahm Nozomi mit, als sie besiegt wurde und Nozomi wachte** in der Waldhütte von Dark Dallun wieder auf. 
LT: "Hier sollte ein Komma eingefügt werden, wenn es sich bei dem hinteren Satzteil um einen Nebensatz handelt."
***
- [ ] B-Black Dallun **zog das Ritual durch, um seine Waffe mit seiner Seele zu binden, indem er das Katana, was der Schmied hundert Jahre lang geschmiedet hatte, mitten in seinem Herz einsticht.**
LT: "Hier sollte ein Komma eingefügt werden, wenn es sich bei dem hinteren Satzteil um einen Nebensatz handelt."
***
Ich weiß mit besten Gewissen nicht, wo in den Sätzen noch ein Komma hinmüsste. Für mich sind das Fehlalarme, die sich beim Update hereingeschlichen haben, denn vorher gab es mit diesen Sätzen keine Probleme.

[LT_Regel: **"Fehlendes Komma zwischen Haupt- und Nebensatz oder zwei Hauptsätzen"**](https://community.languagetool.org/rule/show/KOMMA_ZWISCHEN_HAUPT_UND_NEBENSATZ?subId=7&lang=de-DE)
Stimmt irgendwas mit dieser Regel nicht?

Ich hoffe, ihr kiregt dieses Problem gelöst.

Grüße Dallun511

**Comment by AgnesKleinhans** [comment]
Alle Fehler sind inzwischen behoben! :-)

**Comment by Dallun511** [comment]
Da habe ich einen Patch verpasst, aber ich bedanke mich, dass Sie mich darauf aufmerksam machen.
