### ISSUE TITLE
[DE] Problem "de"

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#2055]
Moin liebes LanguageTool-Team

Heute habe ich ein Problem gefunden, welches sich nicht einfach lösen lässt. Es geht um "**de**". **.de** ist unsere Top-Level-Domain, weswegen sie nicht als Rechtschreibfehler gekennzeichnet werden kann. Weswegen es nur als Grammatikfehler gelten kann. Ein weiteres Problem könnten legendäre Gebäude haben, die ein **de** im Namen haben, weswegen dafür eine Sonderregel/Ausnahme hermüsste.

Als Beispiel für einen einfachen Grammatikfehler, der noch nicht gefunden wird.
Die Oberinspektorin verließ **de Verhörraum** und ließ Anastasia allein.

Es würde schon reichen, wenn Kasus, Adjektiv und Nomen blau markiert werden, damit dieser Fehler nicht untergehen kann. **Es müssen keine Vorschläge gemacht werden.** Er kann entstehen, wenn zu schnell getippt wird, wodurch ein oder mehrere Buchstaben verschlugt werden oder weil im falschen Moment der Auto-Save kam, wodurch das schreiben blockiert wurde.

Glaubt ihr, dass ihr das hinbekommt?

Grüße Dallun511

**Comment by danielnaber** [comment]
Auf languagetool.org wird der Fehler gefunden und die Regel dafür gibt es auch schon länger:

![de](https://user-images.githubusercontent.com/857004/67379460-4052be80-f589-11e9-8245-777182f2d4b1.png)

Nur die Vorschläge sind noch nicht so gut.

**Comment by Dallun511** [comment]
Hm! merkwürdig, weil die Regel auf LibreOffice nie angeschlagen ist, egal welche Version.

Zu den Vorschlägen kann ich nur sagen, dass sie **mir** nicht so wichtig sind, solange die Regel anschlägt

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/87782376-ad526680-c832-11ea-98ff-37b306c26130.png)
Funktioniert mittlerweile auch in LibreOffice.
Wahrscheinlich schon länger
