### ISSUE TITLE
[en] move "ADMIT_ENJOY_VB" to the style category?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2058]
To me it seems that the suggestions made by ADMIT_ENJOY_VB are about improving the style not fixing the grammar. What do you think @MikeUnwalla ?

**Comment by MikeUnwalla** [comment]
I am not sure that the rule is about style.

"I enjoy to run" sounds wrong (as in grammatically incorrect, not just a style choice).

**Comment by tiff** [comment]
Ok :)
