### ISSUE TITLE
[es] improve UNPAIRED_BRACKETS

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2062]
This suggestion can be quite annoying because it forces the user to find the beginning of the sentence and insert the inverted question mark "¿". In fact, it's by far the most disabled rule in the Spanish language.

<img width="467" alt="Bildschirmfoto 2019-10-23 um 12 13 14" src="https://user-images.githubusercontent.com/37363/67385088-a859d280-f592-11e9-829b-c848400e639c.png">

We should just highlight the first word of the sentence and offer the insertion a "¿".

**Comment by danielnaber** [comment]
I just found this and I wonder whether it's okay: `Hola, ¿cómo estás?`. I will ask our Spanish translator.

**Comment by jaumeortola** [comment]
Most times, the symbol ¿ or ¡ is at the sentence start. But sometimes not, like in `Hola, ¿cómo estás?`. You can look for the POS tags PT.* (cómo, cuál, dónde, qué...). In a few cases it can be difficult or impossible to decide the correct position. 
`¿` is mandatory in Spanish. In Catalan, it is optional (there is an optional rule in LanguageTool). I will copy the Spanish solution.

**Comment by danielnaber** [comment]
@jaumeortola Do you think the rule is okay now so we can close this issue?
