### ISSUE TITLE
[en] false alarm EN_GB_SIMPLE_REPLACE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2076]
> There are fears the flames could cross the 101 highway and enter areas that have not seen wildfires since the 1940s.

The 101 highway is a proper noun here: https://en.wikipedia.org/wiki/U.S._Route_101

<img width="674" alt="Bildschirmfoto 2019-10-29 um 07 50 15" src="https://user-images.githubusercontent.com/37363/67744129-ee92b400-fa20-11e9-9b60-b5f1d6f88346.png">

I think we should have an exception for numbers before and after the word "highway"

**Comment by MikeUnwalla** [comment]
"101 highway" is not a proper noun. The proper nouns (with capitalization) are:
U.S. Route 101
U.S. Highway 101 (US 101)

**Comment by tiff** [comment]
Thanks for clarifying. The issue also happens with "U.S. Highway 101"

<img width="366" alt="Bildschirmfoto 2019-10-29 um 10 03 29" src="https://user-images.githubusercontent.com/37363/67752512-61a52600-fa33-11e9-85a6-7706ea817ced.png">

**Comment by MikeUnwalla** [comment]
I added a rule for the proper nouns, but EN_GB_SIMPLE_REPLACE does not ignore proper nouns. I opened issue #2079 to ask that proper nouns are ignored.

For now, I suggest that in `replace.txt` we don't put `highway=main road` into comments.

**Comment by MikeUnwalla** [comment]
To do: Add _US 101_ as a proper noun.

**Comment by MikeUnwalla** [comment]
2021-04-26 LT does not give a warning for the test sentence.
