### ISSUE TITLE
[pt] wrong suggestion A_NOUN_VERB

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2081]
> As correções estão indicando sugestões erradas.

The suggestion is the same as the error:
<img width="431" alt="Bildschirmfoto 2019-10-29 um 15 28 22" src="https://user-images.githubusercontent.com/37363/67776612-d773b680-fa60-11e9-9777-c1c2f37a1b52.png">

Happens in pt-pt and in pt-br

**Comment by marcoagpinto** [comment]
@tiff 

How do I fix it?:

>   <rulegroup id='A_NOUN_VERB' name="Erro de concordância de número DETERMINANTE + NOME + VERBO NO">
>       <short>Erro de concordância de número</short>
>     
>     
>     
>     <rule>
>       <pattern>
>           <token>as</token>
>         <marker>
>           <token postag_regexp='yes' postag="NCFS.+"/>
>         </marker>
>           <token postag_regexp='yes' postag="V...3P.+"/>
>       </pattern>
>       <message>Erro de concordância de número: <suggestion><match no='2' postag_regexp= "yes" postag="(N.)FS(.+)" postag_replace="$1FP$2"/></suggestion></message>
>       <example correction="vacas">As <marker>vaca</marker> estão no pasto.</example>
>     </rule>
>     <rule>
>       <pattern>
>           <token>o</token>
>         <marker>
>           <token postag_regexp='yes' postag="NCMP.+"/>
>         </marker>
>           <token postag_regexp='yes' postag="V...3S."/>
>       </pattern>
>       <message>Erro de concordância de número: <suggestion><match no='2' postag_regexp= "yes" postag="(N.)MP(.+)" postag_replace="$1MS$2"/></suggestion></message>
>       <example correction="boi">O <marker>bois</marker> está no pasto.</example>
>     </rule>
>     <rule>
>       <pattern>
>           <token>os</token>
>         <marker>
>           <token postag_regexp='yes' postag="NCMS.+"/>
>         </marker>
>           <token postag_regexp='yes' postag="V...3P."/>
>       </pattern>
>       <message>Erro de concordância de número: <suggestion><match no='2' postag_regexp= "yes" postag="(N.)MS(.+)" postag_replace="$1MP$2"/></suggestion></message>
>       <example correction="bois">Os <marker>boi</marker> estão no pasto.</example>
>     </rule>
>   </rulegroup>

"estão" is a: VMIP3P0

**Comment by marcoagpinto** [comment]
@tiff 

I fixed it:
```
    <rule>
      <pattern>
          <token>as</token>
        <marker>
          <token postag_regexp='yes' postag="NCFS.+"/>
        </marker>
          <token postag_regexp='yes' postag="V...3S.+"/>
      </pattern>
      <message>Erro de concordância de número: <suggestion><match no='2' postag_regexp= "yes" postag="(N.)FS(.+)" postag_replace="$1FP$2"/></suggestion></message>
      <example correction="vacas">As <marker>vaca</marker> estão no pasto.</example>
    </rule>
```

I changed:
`<token postag_regexp='yes' postag="V...3S.+"/>`

But now I get an error with TESTRULES PT in the errors expected

How can I fix it?

Thanks!

**Comment by marcoagpinto** [comment]
@tiff 
I was looking at Tiago's POS above and used the synthesizer and "correções" appears both as singular and plural.

I will make some tests to attempt to fix it.

**Comment by marcoagpinto** [comment]
@tiff 
@TiagoSantos81 
Fixed thanks to Tiago: https://github.com/languagetool-org/languagetool/commit/7b968957f88ff28d2ac4fe9540bc99e902ca1c13
