### ISSUE TITLE
[en] Cannot add some words to spelling.txt

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#2094]
I added POS and spelling in https://github.com/languagetool-org/languagetool/commit/fbe5705f93c0a964f16515b8a3fa9fbe1c178696 for #2051.

I could not add all words to spelling.txt because of Maven error messages. Example:

```
Word 'B?dzin' from en/hunspell/spelling.txt doesn't match regex: [ 0-9a-zA-ZöäüÖÄÜßëçèéáàóòÈÉÁÀÓÒãñíî?&?????????????????
?????????????????????????????????????????????????????????úïÎôêâûÆæÍÚÑõ??·'?ýù?????Åıø?å??Ç??????±?+-./-]+|[khmcdµ]?m[²³]
|°[CFR]|CO?-?.*|mc² - please fix the word or add the character to the language's org.languagetool.rules.WordListValidato
rTest if it's valid
```

These words are not in spelling.txt (the first 3 are not important!)
ǂHõã
ǂKxʼaoǁʼae
ǂKxʼauǁʼein
Będzin
Bhagavad-gītā
Brāhmaṇa
Forlì-Cesena
Hárbarðsljóð
Hassānīya
Hyndluljóð
Kazanlǎk
Kesäranta
Kŭrdzhali
Rígsþula
Savitṛ
Vafþrúðnismál
Völundarkviða
Kṛṣṇa

The characters are not standard English, so I don't know whether it makes sense to add them for English.

**Comment by danielnaber** [comment]
I have added these words except the first 3 now (the words, not the characters), so the test should work.

**Comment by MikeUnwalla** [comment]
@danielnaber, thanks. I found a related problem (#2101).
