### ISSUE TITLE
[ca] "recursió"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2097]
Feedback from a user:
> "recursió" (in Catalan) as the translation of the noun "recursion" (in English) is admitted by the IEC and should not be taken as error by LT

**Comment by jaumeortola** [comment]
Thanks. "Recursió" is not documented in any Catalan dictionary. The usual noun is "recursivitat", and the adjective "recursiu". Anyway, I will make a query.

**Comment by jaumeortola** [comment]
Finally, I will add recursió to the Catalan dictionary.
