### ISSUE TITLE
[es] "podras" vs "podrás"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2099]
The word "podras" isn't marked as a misspelling (it should be "podrás"). 

@jaumeortola can I just add the word to the prohibit.txt or does it have a meaning (I couldn't find one)?

**Comment by jaumeortola** [comment]
This four words are wrong in the Spanish dictionary:
```
podra pudrir VMP00SF
podras pudrir VMP00PF
podro pudrir VMP00SM
podros pudrir VMP00PM
``` 

These are the correct ones. They can be added, but it is not critical because they already exist as forms of the infinitive "podrir".
```
podrida pudrir VMP00SF
podridas pudrir VMP00PF
podrido pudrir VMP00SM
podridos pudrir VMP00PM
```

**Comment by tiff** [comment]
Thank you, @jaumeortola
