### ISSUE TITLE
[pl] "tuta"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2100]
Feedback from a user:
> Wpisałem w Messengerze "Tuta jurz", a LT napisał: "Super, nie ma błędów!"... O co chodzi? Tutaj też nie razi go "tuta" - to słowo istnieje, ale jest slangowe - moim zdaniem nie powinno być w słowniku LT, bo częściej doprowadzi do błędu, niż jego brak zwróciłby niepotrzebnie uwagę.

**Comment by milekpl** [comment]
"Tuta" is not slang, it's technical. https://sjp.pl/tuta

I will check whether it's confused frequently.
