### ISSUE TITLE
[en] Some words with diacritics do not appear correctly in GUI

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#2101]
I added the words from #2094. Some of those words do not appear correctly in the GUI, although they appear correctly on languagetool.org.

![image](https://user-images.githubusercontent.com/5816160/67940551-cf845580-fbcb-11e9-9e78-5457d4d978a5.png)

![image](https://user-images.githubusercontent.com/5816160/67940539-c72c1a80-fbcb-11e9-96bb-630f3881fdbc.png)

**Comment by danielnaber** [comment]
I guess this depends on the fonts on your machine, using a different font (see the menu) might help.

**Comment by MikeUnwalla** [comment]
Great, thanks. Fixed by selecting 'Arial Unicode MS'.
