### ISSUE TITLE
[en-gb] "math"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2102]
The word "math" is not in the British dictionary. Is that correct, @MikeUnwalla?

<img width="450" alt="Bildschirmfoto 2019-11-01 um 11 48 55" src="https://user-images.githubusercontent.com/37363/68020085-b3e97f80-fc9d-11e9-8e4e-5a7422dfc228.png">

**Comment by marcoagpinto** [comment]
@tiff 

Because it is a US word: https://www.lexico.com/en/definition/math

In GB it is maths: https://www.lexico.com/en/definition/maths

**Comment by MikeUnwalla** [comment]
I agree with Marco.

**Comment by tiff** [comment]
Ok, I will improve the suggestions to contain "maths"
