### ISSUE TITLE
4.7 hang + huge chunk of RAM

### ISSUE THREAD

**Issue by black-snow** [languagetool-org/languagetool#2104]
I run a local languagetool 4.7 instance (that I downloaded yesterday) and it just keeps hanging. Plus it hangs in a way that I cannot kill it (Ctrl+C, Task-Manager, PowerShell, restart WSL service) - the only option is a reboot.

Here's my setup:

* Running Win10 with Ubuntu WSL
* java 8 inside WSL (openjdk version "1.8.0_222")
* LT running inside WSL with `--public` on port 8081
* python script hosted in PowerShell querying LT on localhost:8081

I added some sleeps between the requests to LT and it seemed to help a little. Still consistently hanging. LT starts with about 120 MB memory and grows to 1.2 GB (!) of memory where it lives a while and then it hangs.

I'll now try the 4.6 and runnign python in the WSL, too.

**Comment by black-snow** [comment]
After about 150 requests and 1.5 GB memory it blew up the WSL again. Will now try 4.6.

**Comment by danielnaber** [comment]
What is the exact command you use to start LT? Have you tried directly under Windows? 1.2 GB isn't uncommon, Java often takes all the memory you allow it to take (using the `-Xmx` switch).

**Comment by black-snow** [comment]
4.6 worked slightly better (might be random) but also hang after ~1k requests. Memory moved up to 1.5 GB and then down to ~550 MB.

**Comment by danielnaber** [comment]
You could try `jstack <pid>` when it hangs to see where the process is stuck. Are you sure LT is hanging and not the whole WSL thing? What's the CPU usage when this happens and which process causes it?

**Comment by black-snow** [comment]
It is the whole WSL that hangs so it's hard to tell. Any other bash window that I open is plain dead. Any other ideas? I'll roll out LT on a unix system and see how this works out.
