### ISSUE TITLE
Fehlendes Komma "Ich bin der Meinung das"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2115]
> Ich bin der Meinung das Pressemitteilungen mit der E-Mail geschickt werden sollten

Das fehlt ein Komma, oder? Dann verschwindet auch der irritierende Fehler, den es dort derzeit gibt.

**Comment by tiff** [comment]
Ich glaube sogar, es müsste "dass" sein

**Comment by tiff** [comment]
Bereits behoben
