### ISSUE TITLE
Internet addresses without http:// are not recognized correctly in some languages

### ISSUE THREAD

**Issue by pjsb** [languagetool-org/languagetool#212]
In English ".tpl" is missing, can be checked "I am a sentnce with an interntr address www.google.com"

In FR and IT "subdomain." and ".tpl" is missing.

German and Spanish seams to work correctly.

We use a disambiguator currently to solve this problem: http://languagetool-user-forum.2306527.n4.nabble.com/Excluding-URLs-with-out-http-td4641788.html

**Comment by f-knorr** [comment]
I am not sure, but I think we can close this issue, can't we?

**Comment by f-knorr** [comment]
No response?! I close this call as "http" is no longer required to identify urls
