### ISSUE TITLE
Server command-line and cors

### ISSUE THREAD

**Issue by alaindebecker** [languagetool-org/languagetool#2132]
Your command line does not work with a Windows server for XMLHttpRequest in Chrome+Firefox (+maybe others).
The error message is : The 'Access-Control-Allow-Origin' header contains the invalid value ''*''.
With quoted quote.

Double quotes "*" instead of simple quotes '*' works.

So, please change your doc with double quotes (after having checked on a linux server of course):

> java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081 --allow-origin "*"

**Comment by danielnaber** [comment]
Thanks for the feedback, which documentation exactly are you referring to?

**Comment by alaindebecker** [comment]
Under the development section, the page under "How to run your own LanguageTool server", linking to [wiki.languagetool.org/http-server](url).

![image](https://user-images.githubusercontent.com/2980348/68580582-f0279780-0476-11ea-9b09-9df0747f555a.png)

**Comment by danielnaber** [comment]
Thanks, fixed. `"*"` works under Linux, too.
