### ISSUE TITLE
extend common_words.txt for Catalan

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2133]
It would be nice to manually extend the list of common words with some words that are often used as openings in emails and chat messages (these might not occur often enough in typical corpora to make it into the top 10K list).

**Comment by jaumeortola** [comment]
In fact, I did it: I added manually some of these words. But it can be improved.

**Comment by jaumeortola** [comment]
Fixed here: https://github.com/languagetool-org/languagetool/commit/ec22aa83703a511b7fdeceec6eda7f397ddc5a6d
