### ISSUE TITLE
[es] "Roman" vs "Román"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2134]
Feedback from a user:
> EN ESTE CASO ROMAN ES APELLIDO Y POR ESA RAZÓN NO LLEVA ACENTO COMO CUANDO SE TRATA DEL NOMBRE ROMÁN, QUE SIEMPRE SE ACENTÚA.

**Comment by jaumeortola** [comment]
The user says Roman is a surname. I wouldn't add it to the dictionary, as it is an unsual word. It's a matter for his/her personal dictionary.
