### ISSUE TITLE
[pt] IRREGULAR_PAST_PARTICIPLES suggestion contains "<mistake/>"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2135]
The suggestion for the error in
> Só quando cheguei ao trabalho percebi que tinha impresso o documento errado.

contains a weird string `<mistake/>`.

I guess this happens because it's trying to convert "impresso" to "impressado" which is not in the dictionary?

<img width="1154" alt="Bildschirmfoto 2019-11-08 um 07 31 18" src="https://user-images.githubusercontent.com/37363/68454776-f826d380-01f9-11ea-8509-2d5d82afd799.png">

@danielnaber is it a common case that `<mistake/>` will appear in the suggestion?

**Comment by danielnaber** [comment]
`<mistake/>` is internally used in the Java code, it if appears it's a bug.

**Comment by jaumeortola** [comment]
The rule has changed and this issue is fixed.

**Comment by marcoagpinto** [comment]
Thank you!

I guess that probably the nightly is already being built and the results will only be seen on Saturday.
