### ISSUE TITLE
[de] "Organisieren" tagged as "SUB:.*"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2136]
Das Verb "Organisieren" ist als Substantiv getagged:
<img width="547" alt="Bildschirmfoto 2019-11-08 um 07 46 02" src="https://user-images.githubusercontent.com/37363/68455575-fe1db400-01fb-11ea-9b58-0d8304a8b6d5.png">

Ist das korrekt?

**Comment by tiff** [comment]
Hm, anscheinend sind alle Verben, die großgeschrieben sind, als Substantiv getagged. Dasselbe für "Laufen", "Kriechen", ...

**Comment by danielnaber** [comment]
> Hm, anscheinend sind alle Verben, die großgeschrieben sind, als Substantiv getagged. Dasselbe für "Laufen", "Kriechen", ...

Ja, das ist auch richtig so (aus Sicht des Taggers), denn es gibt ja "das Laufen", "das Kriechen" etc.  Die Regeln müssen damit umgehen können.

**Comment by tiff** [comment]
Okay, I'm closing this
