### ISSUE TITLE
[EN] False negative for missing plural nouns (possible agreement error)

### ISSUE THREAD

**Issue by rddunphy** [languagetool-org/languagetool#2141]
LT correctly identifies the missing plural in "there are many book". (`Possible agreement error. The noun book seems to be countable; consider using: "many books".`) However, there is no equivalent rule for collective nouns, so the following sentences all have false negatives:

- "The library has a collection of book."
- "Glossary of term and acronyms"
- "A multitude of bird exist."

**Comment by MikeUnwalla** [comment]
Sorry, should not have closed this issue until I removed `temp_off`. Nightly diff shows errors, and I found a bunch more.
