### ISSUE TITLE
[es] "Noviembre"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2150]
User feedback:
> Noviembre se escribe con mayúscula al principio por ser Noviembre un nombre propio, pues es el nombre de un mes

**Comment by jaumeortola** [comment]
That is wrong. Months are capitalized only when they are historical dates, or they are part of place names, proper nouns, etc.  See: https://www.rae.es/consultas/mayuscula-o-minuscula-en-los-meses-los-dias-de-la-semana-y-las-estaciones-del-ano

We could create a rule that requires lowercase months in full dates, e.g. `14 de *Noviembre de 2019` > `14 de noviembre de 2019`.

**Comment by tiff** [comment]
Ok, I'm closing this and will inform the user.

**Comment by jaumeortola** [comment]
The rule I was talking about already exists: https://community.languagetool.org/rule/show/MIN_MESES?subId=1&lang=es
It produces some false alarms (that can be removed), but not with "noviembre":
* de Julio Iglesias (proper noun)
* Dos de Mayo (historical date)
