### ISSUE TITLE
Bug: Inconsistent behaviour of online editor

### ISSUE THREAD

**Issue by ArronWilliams** [languagetool-org/languagetool#2162]
When entering the following rule into maven and running a test, it brings up an error, and I am not entirely sure why. However, the online rule editor doesn't detect any issue. I messaged Mike and sent it to him, and he mentioned to make a bug report. And if you add a correct version of the rule it displays an error. Sorry, that my explanation is rather poor, I genuinely don't understand the issue it is facing nor the correct terminology.

It seems the online editor is inconsistent.

Here is the rule I created:

```
<rule id="LACK_OF_DT_JJ_ONE" name="i saw two cars, and like the small (one)">
    <pattern>
        <token postag="CD"><exception>one</exception></token>
        <token postag_regexp="yes" postag="NNS|NN:UN|NN:U"></token>
        <token min="0">,</token>
        <token postag="CC"></token>
        <token postag_regexp="yes" postag="VB|VBP"></token>
        <marker><token postag="DT"></token>
        <token min="0" postag_regexp="yes" postag="JJ|NN"></token></marker>
    </pattern>
    <message>Did you mean <suggestion><match no="6" /> <match no="7" /> one</suggestion>? In this sentence, The pronoun 'one' is required at the end when distinguishing nouns.</message>
    <example correction="the small one">I saw two cars, and like <marker>the small</marker>.</example>
</rule>
```

**Comment by danielnaber** [comment]
What error does Maven show? If in doubt, paste its whole output.

**Comment by ArronWilliams** [comment]
Okay: I have pasted the error below

[ERROR] Failures:
[ERROR]   EnglishPatternRuleTest.testRules:37->PatternRuleTest.runGrammarRulesFromXmlTest:119->PatternRuleTest.runGrammarRuleForLanguage:131->PatternRuleTest.runTestForLanguage:157->PatternRuleTest.testGrammarRulesFromXML:301->PatternRuleTest.testBadSentences:396 Incorrect input:
  I saw two cars, and like the small.
Corrected sentence:
  I saw two cars, and like the small one.
By Rule:
  LACK_OF_DT_JJ_ONE[1]
The correction triggered an error itself:
  LACK_OF_DT_JJ_ONE[1]:25-34:Did you mean <suggestion>the small one</suggestion>? In this sentence, The pronoun 'one' is required at the end when distinguishing nouns.

[INFO]
[ERROR] Tests run: 104, Failures: 1, Errors: 0, Skipped: 6
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for languagetool-parent 4.8-SNAPSHOT:
[INFO]
[INFO] languagetool-parent ................................ SUCCESS [  0.345 s]
[INFO] LanguageTool Style and Grammar Checker Core ........ SUCCESS [ 14.055 s]
[INFO] English module for LanguageTool .................... FAILURE [01:40 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:55 min
[INFO] Finished at: 2019-11-19T17:02:55Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project language-en: There are test failures.
[ERROR]
[ERROR] Please refer to D:\github2\languagetool-premium\languagetool-language-modules\en\src\languagetool-language-modules\en\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :language-en

**Comment by ArronWilliams** [comment]
I managed to fix the problem, the error was due to the rule not recognizing a sentence where 'one' was already present.

**Comment by MikeUnwalla** [comment]
Paste the rule into https://community.languagetool.org/ruleEditor/expert?devMode=true&factor=10 and check the XML. There is no warning.

But, the rule is not correct (the correction triggers an error). Testrules gives this message:

```
Exception in thread "main" java.lang.AssertionError: Incorrect input:
  I saw two cars, and like the small.
Corrected sentence:
  I saw two cars, and like the small one.
By Rule:
  LACK_OF_DT_JJ_ONE[1]
The correction triggered an error itself:
  LACK_OF_DT_JJ_ONE[1]:25-34:Did you mean <suggestion>the small one</suggestion>? In this sentence, The pronoun 'one' is
 required at the end when distinguishing nouns.
```

Can the online rule editor be made to give the warning?

**Comment by danielnaber** [comment]
This should be fixed now:

![new-error](https://user-images.githubusercontent.com/857004/69232668-ca437680-0b8b-11ea-80cd-6c7afbead0b9.png)

**Comment by MikeUnwalla** [comment]
@danielnaber , thanks. Works for me.
