### ISSUE TITLE
[en] false alarm UNIT_SPACE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2171]
> Meanwhile, the BBC understands the government has “stood down” its Operation Yellowhammer contingency planning for a no-deal exit, while it has also paused its £100m Get Ready for Brexit on 31 October campaign.

It's not "meter" but "million" when there's a currency sign in front
![Bildschirmfoto 2019-11-22 um 15 49 38](https://user-images.githubusercontent.com/37363/69435438-d7a16200-0d3f-11ea-8c28-2d614f593c77.png)

**Comment by MikeUnwalla** [comment]
I tried an antipattern, but got this message:

`Caused by: java.lang.RuntimeException: <regexp> rules currently cannot be used together with <antipattern>. Rule id: UNIT_SPACE[1]
`
@danielnaber , please can we have antipatterns with regexp rules?

**Comment by danielnaber** [comment]
> please can we have antipatterns with regexp rules?

This might not be so easy, please don't expect this anytime soon.
