### ISSUE TITLE
Different antipattern

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#2184]
An antipattern blocks (or should block) when there is overlap between pattern and antipattern.
Example pattern 'foo bar block' is blocked by  'this foo bar'

Sometimes it is more useful to be able to be sure the antipattern overlaps the pattern in full.
'foo bar block' shoul in this case NOT be blocked by 'this foo bar', but it should by 'this foo bar block' or 'foo bar block things' or 'these foo bar block things'.

**Comment by danielnaber** [comment]
Could you provide an example where this would be needed?
