### ISSUE TITLE
"Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo" Not counting as a sentence.

### ISSUE THREAD

**Issue by UltraGamesYT** [languagetool-org/languagetool#2186]
I know it sounds like a joke, but "Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo" is a grammatically correct sentence, but LanguageTool does not find the sentence itself as grammatically correct.

For proof, there's an entire page on wikipedia dedicated to the sentence and how it is structured to give an idea of what the sentence means itself.
https://en.wikipedia.org/wiki/Buffalo_buffalo_Buffalo_buffalo_buffalo_buffalo_Buffalo_buffalo

**Comment by MikeUnwalla** [comment]
Point of order: LT does not say that the sentence is incorrect. It says that a phrase is duplicated, and that you should _probably_ use X.

Here's another example of a phrase that LT thinks is duplicated:

> That _that_ that that writer wrote is not redundant; it's a syntactic cue.
