### ISSUE TITLE
[es] "BACA"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2190]
Feedback from a user:
> No detecta la palabra "BACA" al redactar un correo en Gmail

**Comment by jaumeortola** [comment]
"baca" (pl. "bacas") can be added to the dictionary. 

Then a rule for the confusion baca/vaca (bacas/vacas) will be also needed. Could you try a confusion rule, @danielnaber? 
This baca/vaca issue is a common example given to children learning to write. https://i.pinimg.com/originals/a8/64/01/a86401dec96cbd2b20af36f38f189b9d.png

**Comment by danielnaber** [comment]
I have added baca/vaca, even though recall isn't very good:

`baca; vaca; 10000000;       # p=0.994, r=0.363, f0.5=0.738, 26+431, 3grams, 2019-11-29`

**Comment by jaumeortola** [comment]
Vaca is much more common than baca. Perhaps a simple wrong-word-in-context rule is good enough. That's what I did for Catalan: https://github.com/languagetool-org/languagetool/commit/a85c893430496975af1284e3ff51236fa606c050

**Comment by jaumeortola** [comment]
"Baca" was already in the Spanish dictionary. So probably the user is talking about a false negative  `*baca>vaca` (the user message is unclear).
