### ISSUE TITLE
enabling rules after uploading custom rules file in stand-alone

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#2195]
When a custom rules file (that extends an existing language) is uploaded in the stand-alone program, the rules are not enabled immediately. You need to select another language and then you can select and use the desired language. This behavior is very confusing and should be fixed.

**Comment by danielnaber** [comment]
I haven't tried but maybe the fix is as simple as calling `checkTextAndDisplayResults()` at the end of `addLanguage()` in `org.languagetool.gui.Main`?
