### ISSUE TITLE
[en] false alarm TOO_TO

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2199]
> I too have no idea.

There are two commas missing, but still it's a false positive, I think.

![Bildschirmfoto 2019-11-29 um 12 10 13](https://user-images.githubusercontent.com/37363/69865422-6a428380-12a1-11ea-9e5e-170c7608b596.png)

**Comment by tiff** [comment]
Maybe adding a simple comma rule what also help. I think the case PRP + "too" + VB|MD is quite common.

**Comment by MikeUnwalla** [comment]
@tiff, I cannot reproduce this false alarm on https://languagetool.org/ today (2019-12-02).

I have left the issue open in case anyone wants to write a comma rule.
