### ISSUE TITLE
languagetool-core: .git directory is not found! 

### ISSUE THREAD

**Issue by Fxztam** [languagetool-org/languagetool#2203]
Hi ,

trying on Maven 3.6.3 & Win10 :: > **mvn clean test**
I am getting the Error  :  Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.6:revision 
(get-the-git-infos) on project **languagetool-core**: .git directory is not found! 
Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]

Please help,
Friedhold

**Comment by yakovru** [comment]
Please checkout the source code using git client to fix it.

>Понедельник,  2 декабря 2019, 14:50 +03:00 от Friedhold Matz 
>Hi ,
>trying on Maven 3.6.3 & Win10 :: >  mvn clean test
>I am getting the Error  :  Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.6:revision
>(get-the-git-infos) on project  languagetool-core : .git directory is not found!
>Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
>Please help,
>Friedhold 
-- 

Yakov Reztsov

**Comment by Fxztam** [comment]
Thank you Yakov, it works for me now.
