### ISSUE TITLE
[en] Non-standard characters look like standard characters but cause spelling errors

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#2211]
Source text:
This air‐dried tomato is smaller than that air-dried tomato.
My hоuѕе is smaller than your house.

I found these problems when I was looking at users' suggestions for spelling to add to LT. (I changed the text. Related issue #2208.)

![image](https://user-images.githubusercontent.com/5816160/70608379-ecaf3980-1bf7-11ea-93dc-6e8bdcbb5107.png)

In Microsoft Word, with typeface Bradley Hand IT, it is possible to see the the characters in the first 'hоuѕе' are not the same as in the second 'house':

![image](https://user-images.githubusercontent.com/5816160/70608750-8d9df480-1bf8-11ea-9960-6fab7c6098a9.png)

Strange but true (as the screen shot above shows) is that Microsoft interprets the 'о' as ANSI value 63, which is the value for a question mark (http://ascii-table.com/ascii.php).

Same for e and s:

![image](https://user-images.githubusercontent.com/5816160/70610050-ca6aeb00-1bfa-11ea-832e-e8a85079a851.png)

EditPad Pro shows that the characters are different:

![image](https://user-images.githubusercontent.com/5816160/70611118-97295b80-1bfc-11ea-8fbb-213d831e1dbc.png)

Anyway, I will see if I can make some rules to find these characters and suggest the correct characters.

**Comment by MikeUnwalla** [comment]
I made a rule NON_STANDARD_ALPHABETIC_CHARACTERS that finds the problems that users reported.

There are hundreds, possibly thousands, of characters that will cause similar problems. I took some characters from https://www.utf8-chartable.de/unicode-utf8-table.pl?start=384&number=1024:

U+0185: Is that a ƅat?
U+0410: Аbout these problems...
U+041D: Нot water can scald you.

On languagetool.org, it is possible to see that the characters are not quite right:

![image](https://user-images.githubusercontent.com/5816160/70812183-0a7acb00-1dbf-11ea-84b3-40fc1d5abcdb.png)

But, in the GUI (depending on the font), you cannot:

![image](https://user-images.githubusercontent.com/5816160/70812263-2ed6a780-1dbf-11ea-8ef1-627c12ee2e6d.png)

To make rules for all possible problems is not practical. 

Although the problem is rare, it might be nice to give more help to users. @danielnaber, a possible solution is to add a line in the message and direct people to web page on the wiki that gives examples and tells people to retype the word. (Also include information about other possible causes of the message: the word is incorrectly spelled; the word is incorrect for the locale; the word is missing from LT.)

![image](https://user-images.githubusercontent.com/5816160/70812697-056a4b80-1dc0-11ea-8cb0-590935e22456.png)

**Comment by danielnaber** [comment]
But for the examples you gave, `NON_STANDARD_ALPHABETIC_CHARACTERS` will now provide a better message than in your screenshots, doesn't it?

**Comment by MikeUnwalla** [comment]
If you mean for bat/about/Hot, no, it won't. The rule NON_STANDARD_ALPHABETIC_CHARACTERS only finds 4 characters:
U+043E: о
U+0455: ѕ
U+0435: е
U+0440: р

**Comment by MikeUnwalla** [comment]
Regression test https://internal1.languagetool.org/regression-tests/20191213/result_en_20191213_table.html shows many messages. These are not errors because it does not make sense to replace text in a non-English word.

This is my attempt to prevent FP for words that are probably not English. (It doesn't work if there is more than one non-standard character in an English word.)

```
<rule id="TESTER" name="tester"><!-- Cyrillic small letter o, U+043E -->
    <pattern>
        <or>
            <token postag="UNKNOWN" regexp="yes">[a-zA-Z]+\u043E[a-zA-Z]+</token><!-- Character is in the middle of a word -->
            <token postag="UNKNOWN" regexp="yes">[a-zA-Z]+\u043E</token><!-- Character is at the end of a word -->
            <token postag="UNKNOWN" regexp="yes">\u043E[a-zA-Z]+</token><!-- Character is at the start of a word -->
        </or>
    </pattern>
    <message>The character 'о' is a Cyrillic small letter 'o' (Unicode U+043E), although it can look like an English 'o'. The character can cause a spelling error and disambiguation errors. Use <suggestion><match no="1" regexp_match="([a-zA-Z]*)\u043E([a-zA-Z]*)" regexp_replace="$1o$2"/></suggestion>.</message>
    <example correction="hot">The sun is <marker>hоt</marker> (contains Cyrillic small letter 'o').</example>
    <example correction="open">Please <marker>оpen</marker> the door.</example>
    <example correction="No"><marker>Nо</marker>, thank you.</example>
    <example>The sun is <marker>hot</marker>.</example>
    <example>Cyrillic small letter <marker>о</marker>.</example>
    <example>...of China use astronaut while texts in Russian use <marker>космонавт</marker> (kosmonavt).</example>
    <example>pt: Alien (desambiguação) ru: <marker>Чужой</marker> simple:Alien</example>
    <example>The word '<marker>Hоuѕе</marker>' contains 3 non-standard characters.</example>
</rule>
```
The rule finds the problem words:
![image](https://user-images.githubusercontent.com/5816160/70852110-80516600-1e95-11ea-96a8-9b7da9ee7335.png)

But, the suggestions are not correct. If I select a suggestion, it triggers an error. Testrules gives this message:
```
Exception in thread "main" java.lang.AssertionError: English: Incorrect suggestions: [hot] != [h?t] for rule TESTER[1] o
n input: The sun is h?t (contains Cyrillic small letter 'o'). expected:<[hot]> but was:<[h?t]>
```

I cannot see the problem with my regexp for the suggestion. Do you know what I am doing wrong?

**Comment by danielnaber** [comment]
> I cannot see the problem with my regexp for the suggestion. Do you know what I am doing wrong?

I think the problem is with the `<or>`. Does it work if you have three different rules (in a rulegroup or not).

**Comment by MikeUnwalla** [comment]
> Does it work if you have three different rules (in a rulegroup or not).

Yes, thanks.

**Comment by MikeUnwalla** [comment]
If I use 3 rules for each character, then with 4 characters, we will have 12 rules. If we have more characters, maintenance will become difficult.

Here is an alternative rulegroup that has only 3 rules for 4 (or more) characters (I wrote only one rule for this test):

```
<rulegroup id="NON_STANDARD_ALPHABETIC_CHARACTERS_V2" name="Non-standard alphabetic characters VERSION 2">
    <rule id="NON_ENGLISH_CHARACTER_STARTS_A_WORD" name="Non-standard character starts a word">
        <pattern>
            <token postag="UNKNOWN" regexp="yes">(\u043E|\u0455|\u0435|\u0440)[a-z]+</token><!-- To prevent FP for words that are not standard English such as 'ru', 'kosmonavt' and 'googoogoo', do not use \p{L} -->
        </pattern>
        <message>A character in '\1' is not an English character, although it can look like an English character. The character can cause a spelling error and disambiguation errors. Type the word again.</message>
        <example correction="">Please <marker>оpen</marker> the door. (Contains Cyrillic small letter 'o', Unicode U+043E.)</example>
        <example correction="">Can you <marker>ѕee</marker> it? (Contains Cyrillic small letter 'dze', Unicode U+0455.)</example>
        <example correction="">Did you <marker>еat</marker> the last biscuit? (Contains Cyrillic small letter 'ie', Unicode, U+0435.)</example>
        <example correction="">This is a <marker>рea</marker>. (Contains Cyrillic small letter 'er', Unicode U+0440.)</example>
        <example>The sun is <marker>hot</marker>.</example>
        <example>Cyrillic small letter <marker>о</marker>.</example>
        <example>The sun is <marker>hоt</marker>. (Contains Cyrillic small letter 'o'.)</example>
        <example><marker>Nо</marker>, thank you. (Contains Cyrillic small letter 'o'.)</example>
        <example>...of China use astronaut while texts in Russian use <marker>космонавт</marker> (kosmonavt).</example>
        <example>Russian: <marker>Чужой</marker> simple:Alien</example>
        <example>The word '<marker>Hоuѕе</marker>' contains 3 non-standard characters.</example>
        <example>... <marker>ru</marker>: ....</example>
        <example>Contains Cyrillic small letter '<marker>dze</marker>'.</example>
        <example>... baby's first word "<marker>googoogoo</marker>".</example>
    </rule>
</rulegroup>
```
 The rules will not give as much information about the problem as the current rules.

@danielnaber, do you have a preference about which version of the rules to use?
