### ISSUE TITLE
"Prefilling" incorrectly detected as false

### ISSUE THREAD

**Issue by phillipoertel** [languagetool-org/languagetool#2214]
Looks like there's a problem in the dictionary.
From Google Docs.

![Bildschirmfoto 2019-12-11 um 16 21 32](https://user-images.githubusercontent.com/5188/70634396-72e87180-1c32-11ea-89e8-d0f90171c2a6.png)

**Comment by phillipoertel** [comment]
I just got two more false positives for composite words, see screenshots. Maybe it's a general problem?

<img width="329" alt="Bildschirmfoto 2019-12-12 um 11 31 38" src="https://user-images.githubusercontent.com/5188/70704873-2b65f200-1cd3-11ea-8765-5846cfc17af2.png">
<img width="300" alt="Bildschirmfoto 2019-12-12 um 11 32 01" src="https://user-images.githubusercontent.com/5188/70704874-2b65f200-1cd3-11ea-818b-7e552aad2799.png">

**Comment by MikeUnwalla** [comment]
In British English, the word 'cooperation' is usually used only as a mass noun: 
https://www.ldoceonline.com/dictionary/cooperation
https://www.lexico.com/definition/cooperation

In American English, 'cooperation' can be plural: https://www.merriam-webster.com/dictionary/cooperation.

The spellings for 'rebrand' were missing.

I added the missing parts of speech and the spellings (https://github.com/languagetool-org/languagetool/commit/1a8b46463521e5733117c5b25cf52d563e8e4d72).

@danielnaber, the LT message does not show the locale for the language. To make things clearer, possibly change the message to something like this: Possible spelling mistake found for English (variant).

**Comment by danielnaber** [comment]
> To make things clearer, possibly change the message to something like this: Possible spelling mistake found for English (variant).

I'm not sure... it might also confuse users, as "mistake found for English (US)" doesn't tell anything about whether it's *specific* to en-US.
