### ISSUE TITLE
Russian comma issue

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2215]
Feedback from user:

> Приложение выводит ошибочное сообщение о пунктуационной ошибке. 
Пример   - Пропущена запятая: "присутствует команда, и владелец продукта. Владелец описывает потребности." 
В этом случае не должно быть запятой.

@yakovru Maybe the feedback is useful, otherwise feel free to close.

**Comment by yakovru** [comment]
This error does not appear in the current version of LT. The full text of the example is needed, not just the error message.
В текущей версии LT данная ошибка не появляется. Необходим полный текст примера, а не только сообщение об ошибке.
