### ISSUE TITLE
Rule priority in the GUI

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#2218]
The add-ons and languagetool.org only show one match for a word. Rule priority decides which matches to remove for those UIs that can only show one match per word.

Example text: Be careful，this is not a standard comma. 
Rule priority has no effect for the GUI:

![image](https://user-images.githubusercontent.com/5816160/70851251-bc32fe00-1e8a-11ea-9380-2c7a6d7d7501.png)

It would be nice if the most important message were shown first. (The most important message is the message that is shown in the add-ons and on languagetool.org.)

**Comment by anleu** [comment]
Hi Mike, 
is still issue still valid? I try to reproduce but cannot. 
Best regards
Andy

**Comment by MikeUnwalla** [comment]
Hi @anleu , this issue is fixed (Idon't know by whom or when).
