### ISSUE TITLE
Spanish hyphen usage

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2221]
User feedback:

> Hola, el corrector de LanguageTool no reconoce las acotaciones entre guiones, y los considera como un error gramatical.
Ejemplo: Juan -el menor- jugó a la pelota.

Is that really the correct way in Spanish to use hyphens? No space on one side?

**Comment by jaumeortola** [comment]
The sentence is correct: one space before the opening hyphen and one space after the closing hyphen. In accurate typography, the hyphen should be replaced by an em dash or an en dash. 

What I see is a bug in the tokenizer: these hyphens should be in separate tokens (`<token>-</token><token>el</token>`, not joined with the word (`<token>-el</token>`).

In compound nouns joined with a hyphen, we probably should also split them in different tokens (but other approaches are possible).
