### ISSUE TITLE
false alarm "would have helped"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2253]
> I’m wondering if fatter tires **would have helped** on this occasion.

-> "had helped" is suggested, it's a false alarm according to a user report

**Comment by tiff** [comment]
Also, this rule should be a style rule, or is it grammatically incorrect to say "would have helped"?

**Comment by MikeUnwalla** [comment]
>  or is it grammatically incorrect to say "would have helped"?

In the context of rule IF_WOULD_HAVE_VBN, the error is grammatical. (In other contexts "would have helped" is fine.)
