### ISSUE TITLE
[DE] Sonderegeln

### ISSUE THREAD

**Issue by Black56651** [languagetool-org/languagetool#2254]
Moin liebes LanguageTool-Team

In diesem Therad habe ich besondere Fehlalarme.
***
- [x] **Problem 1** 
Sie fragte verwirrt: „Ist **das Zucker**? Oder ist das Salz?“
**LanguageTool-Fehlermeldung:** Möglicherweise fehlende grammatische Übereinstimmung zwischen Artikel und Nomen bezüglich Genus (männlich, weiblich, sächlich - Beispiel: 'der Fahrrad' statt 'das Fahrrad'). 
**Bemerkung:** Die Regel ist absolut richtig, wenn **das** als Arktiel zu **Zucker** zur Verwendung gekommen wäre.
**das** fungiert als was anderes. Der Fachbegriff ist mir leider nicht bekannt.
***

**Letzte Aktulisierung: 27.12.2019**
**Zuletzt alle Fehler überprüft: 27.12.2019**

Grüße euer Black5661

**Comment by f-knorr** [comment]
commit 1b15f2777bdb45e48eb8cc14a3750a45f388a6c5
