### ISSUE TITLE
[en] false alarm INCORRECT_POSSESSIVE_FORM_AFTER_A_NUMBER

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2256]
> Berry was an asthmatic and claimed that he had his best three night's sleep at Rancho San Pascual.

![Bildschirmfoto 2019-12-27 um 13 38 06](https://user-images.githubusercontent.com/37363/71517396-221d7d80-28ae-11ea-8e05-a09fe5ad0022.png)

**Comment by MikeUnwalla** [comment]
@tiff, why is this a false alarm?

**Comment by tiff** [comment]
Ah sorry. Looking at it again I think I was wrong.
