### ISSUE TITLE
[de] false alarm LINK_LINKS

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2263]
> Bitte in der Regel den Link oben einbinden.

![Bildschirmfoto 2019-12-30 um 10 44 48](https://user-images.githubusercontent.com/37363/71576618-78c6c980-2af1-11ea-9a15-a2f22a04a227.png)

**Comment by f-knorr** [comment]
I cannot reproduce

**Comment by tiff** [comment]
Sorry, already fixed.
