### ISSUE TITLE
Add russian style check.

### ISSUE THREAD

**Issue by socketpair** [languagetool-org/languagetool#227]
Более трёх подряд идущих слова в родительном падеже -- дурной тон. Например, "кнопка выбора пути файла сохранения цвета фона". Возможно, алгоритм поиска этой ошибки должен игнорировать предлоги "для" в цепчке слов. Те "кнопка для выбоа пути файла для сохранения цвета фона" звучит по-прежнему плохо.

**Comment by yakovru** [comment]
Второй вариант звучит плохо из-за наличия двух предлогов "для". А первый пример - обычная фраза. Но лучше будет сказать: "кнопка выбора пути файла для сохранения цвета фона"

**Comment by yakovru** [comment]
Создано правило, находящее 4 слова подряд в родительном падеже.
