### ISSUE TITLE
[de] "hochinnovativ"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2270]
Endless Loop:
![Dec-31-2019 10-23-19](https://user-images.githubusercontent.com/37363/71616654-a5451900-2bb7-11ea-9ead-e58e4b6d4fa7.gif)

@danielnaber sollen wir "hochinnovativ" einfach zum Wörterbuch hinzufügen?

**Comment by danielnaber** [comment]
> sollen wir "hochinnovativ" einfach zum Wörterbuch hinzufügen?

Ja, mache ich mal.
