### ISSUE TITLE
[de] wrong suggestion DE_WORD_COHERENCY

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2271]
Der Vorschlag ist kleingeschrieben, sollte aber groß sein.

![Bildschirmfoto 2019-12-31 um 10 25 13](https://user-images.githubusercontent.com/37363/71616720-fe14b180-2bb7-11ea-84dd-83814ba20cd1.png)

**Comment by Dallun511** [comment]
https://github.com/languagetool-org/languagetool/issues/2022 hier habe ich einen ähnlichen Fall

**Comment by danielnaber** [comment]
Der Bug hatte inzwischen eine Evolution durchlaufen, so dass er nicht weg, aber anders war :-) Sollte jetzt gefixt sein.
