### ISSUE TITLE
[en] British English does not recognize "ageing"

### ISSUE THREAD

**Issue by gensitu** [languagetool-org/languagetool#2280]
British English does not recognize "ageing" as the British version of "aging".

**Comment by MikeUnwalla** [comment]
LT works fine for me:
![image](https://user-images.githubusercontent.com/5816160/71713912-8e930200-2e03-11ea-985c-43148713c3ad.png)

Please give more information and a screen-shot if possible.

**Comment by MikeUnwalla** [comment]
Closed because no further information was given.
