### ISSUE TITLE
Add "screenshot" to the list of words

### ISSUE THREAD

**Issue by vogella** [languagetool-org/languagetool#229]
screenshot is reported as incorrectly spelled in English US. I think that is a valid word: http://en.wikipedia.org/wiki/Screenshot

**Comment by danielnaber** [comment]
It's in Kevin's latest data (http://app.aspell.net/lookup?dict=en_US&words=screenshot) and in Marco's (https://github.com/marcoagpinto/aoo-mozilla-en-dict/blob/master/en_GB%20%28Marco%20Pinto%29%20-%202.20%20-%202015-01-01/README_en_GB.txt) so it will be there once we update the English dictionary.
