### ISSUE TITLE
[de] false alarm OBJECT_AGREEMENT

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2296]
> Bei einem internationalen Spendenaufruf für australische Feuerwehrleute sind bereits knapp 25 Millionen australische Dollar (15,5 Millionen Euro) zusammengekommen

![Bildschirmfoto 2020-01-05 um 17 56 19](https://user-images.githubusercontent.com/37363/71783280-c016f380-2fe4-11ea-9809-a91a1bd685be.png)

**Comment by Dallun511** [comment]
Bei einem internationalen Spendenaufruf für australische Feuerwehrleute sind bereits knapp 25 Millionen **kanadische** Dollar zusammengekommen

Das Gleiche passiert bei "kanadische Dollar"
