### ISSUE TITLE
[pt] Preposition `a Deus` recognized as feminine article

### ISSUE THREAD

**Issue by Konfekt** [languagetool-org/languagetool#2303]
LanguateTool wrongly detects the proposition `a` in  `a Deus` in expressions like `amor a Deus` as feminine article:
```
 ERRO_DE_CONCORDNCIA_DO_GÉNERO_FEMININO_A[1] : Possível erro de concordância de género. : o Deus; a deusa : https://pt.wikipedia.org/wiki/Artigo_(gram%C3%A1tica)
```
Since this is a common construction, perhaps there can be added an exception for this false positive.

**Comment by marcoagpinto** [comment]
@Konfekt 

I will try to fix it tonight or tomorrow.

Thank you for the report.

**Comment by Konfekt** [comment]
Thank you!

**Comment by marcoagpinto** [comment]
@Konfekt 
@TiagoSantos81 

The nightly and the LanguageTool site editor don't report any error with the sentences.

So, I must have fixed it in one of my updates:
![amor_a_deus_20200108](https://user-images.githubusercontent.com/5192600/71989502-b8945c00-3229-11ea-8442-c237a7d50e40.png)

Could you check if the issue still happens?

Thanks!

**Comment by Konfekt** [comment]
I think `ERRO_DE_CONCORDNCIA_DO_GÉNERO_FEMININO_A` is a rule that has to be explictely enabled, exactly due to many false positives.

**Comment by marcoagpinto** [comment]
> 
> 
> I think `ERRO_DE_CONCORDNCIA_DO_GÉNERO_FEMININO_A` is a rule that has to be explictely enabled, exactly due to many false positives.

This is a new laptop I bought days ago.

I haven't changed any settings in LanguageTool.

I just installed the nightly and tested in the LT editor site and it was not flagged.

So, does it mean it is working as it should?

**Comment by Konfekt** [comment]
If you haven't changed any settings, then there is no false positive, because `ERRO_DE_CONCORDNCIA_DO_GÉNERO_FEMININO_A` is a rule that has to be explicitly enabled, exactly due to many false positives.

This issue is about removing this false positive, in case someone wants to check for the wrong gender of feminine articles.
