### ISSUE TITLE
Complaining about "any more" and "anymore" at the same time

### ISSUE THREAD

**Issue by phillipoertel** [languagetool-org/languagetool#2309]
The word is marked as incorrect regardless of how I spell it, and the opposite spelling is suggested -- see screenshots.

----

![Bildschirmfoto 2020-01-08 um 16 00 00](https://user-images.githubusercontent.com/5188/71988343-090eb800-3230-11ea-97c1-7b68df2d2eb3.png)

----

![Bildschirmfoto 2020-01-08 um 15 59 49](https://user-images.githubusercontent.com/5188/71988372-14fa7a00-3230-11ea-98ab-7ef59ed7257d.png)

----

It happens in Google Docs; but I'm not sure the issue is exclusive to that.

**Comment by danielnaber** [comment]
Thanks for the report. @MikeUnwalla The "?" is also missing in the message and it's not the only case - let me take care of fixing those messages.

**Comment by MikeUnwalla** [comment]
@danielnaber, this is what I see in the GUI and on languagetool.org:

![image](https://user-images.githubusercontent.com/5816160/71996958-0ebacc80-3235-11ea-9ada-41d37723a1e6.png)

I don't understand why 'any more' at the end of a sentence with no full stop does not trigger an error. I added examples to en-US/ANY_MORE

**Comment by MikeUnwalla** [comment]
@danielnaber,

> Stop submitting the results, the test will not be completed anymore

I added the sentence to ANYMORE_ADVERB (that is the rule with the message "Make sure that 'anymore' is used as an adverb," The sentence does not trigger an error when I run the Maven tests.

**Comment by danielnaber** [comment]
> I don't understand why 'any more' at the end of a sentence with no full stop does not trigger an error.

It's because of the token that follows which only has any exception:

```
                <token>
                    <exception postag_regexp="yes" postag="SENT_END|PCT|CC|DT|TO|WP|WRB"/>
                </token>
```
This could be removed and turned into an antipattern I guess.

**Comment by MikeUnwalla** [comment]
Hi @danielnaber, ANYMORE_ADVERB operates as I expect. (I edited my message, so I guess you have not seen the changes to that message.)

My confusion is with en-US/ANY_MORE, in which I added examples (https://github.com/languagetool-org/languagetool/commit/23e722b8df39e6438a209eb0fc1b64d88a34aa9b). Here's the pattern:
```
              <pattern>
                  <marker>
                     <token>any</token>
                     <token>more</token>
                  </marker>
                  <token><exception regexp="yes">of|than</exception><exception postag="NN.*" postag_regexp="yes"/></token>
              </pattern>
```

**Comment by MikeUnwalla** [comment]
@phillipoertel, please check tomorrow (Tuesday) to make sure that you get what you expect in Google Docs. Thanks.
