### ISSUE TITLE
consider ignore.txt for generating suggestions

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#231]
Words in `ignore.txt` are accepted, but misspellings of those will not suggest the correct word.

Original report: http://languagetool-user-forum.2306527.n4.nabble.com/Add-words-to-German-dictionary-td4642193.html

**Comment by milekpl** [comment]
This is a regression for me. I have incorrect words in ignore.txt that are caught by SimpleReplaceRule. Please use another filename for the user dictionary. This one should be for silently ignored words.

**Comment by danielnaber** [comment]
Should be fixed now, there's now `ignore.txt` and `spelling.txt`.
