### ISSUE TITLE
[en] "admin" tagged as "VBG"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2311]
> I am using ‘newrelic-admin’.

The word "newrelic-admin" is tagged as VBG. 

I think it's happening because other verbs ending with `in'` (like `goin'`) are by default tagged like that.
@danielnaber where is the piece of code that does that? Can we fix this?
@MikeUnwalla FYI

**Comment by tiff** [comment]
Same for 
> atlas-create-jira-plugin

**Comment by danielnaber** [comment]
The tagging is caused by the disambiguator, rule `VBG_IN`. Maybe @MikeUnwalla can improve that rule.
