### ISSUE TITLE
[nl] words often added dictionary

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2315]
Words that are often added to the user's dictionary.

Many of them I know are names (CSS, Analytics, Javascript, Panasonic, ...)

* Eén
* 1-op-1
* GitHub
* Magento
* API
* 4G
* ROI
* CRM
* Analytics
* CSS
* requirements
* social
* Experience
* influencer
* influencers
* admin
* Group
* CKV
* 2D
* 2x
* 10x
* Advertising
* A2C
* Access
* Advanced
* Peaks
* One
* A2C
* 11u
* 2a
* bevolkingsdiagram
* BM-afdeling
* BM-manager
* CAD
* Bpost
* citrix
* Corporation
* desymbolisatie
* Arial
* Angular
* AG
* backlog
* DJI
* Domagoj
* Dutch
* Excel-bestand
* funnels
* GDPR
* HelloFresh
* Helvetica
* HIIT-training
* hysteriële
* Instagrammers
* Javascript
* klinimetrische
* ongedifferentieerdheid
* minecraft
* Panasonic
* Thunberg
* Rhapsody
* unicef
* Verdana
* vingerbreien
* m²
* OC
* Laertes
* koste

**Comment by baarsrj** [comment]
Eén : In fact unnecessary, since it is possible to type Één these days. But added it
    1-op-1: added
    GitHub : added
    Magento: added
    API; is already in dictionary
    4G; prone to be a mistake, should mostly be attached to other word (4G network) May be make a rule for that?
    ROI ; might be a proper name, or 'return on investment'. Added ROI
    CRM; maybe should be crm; but added it; prone to be a space error too.
    Analytics: not a Dutch word.
    CSS : probably a lot of IT folks using LT ;-)
    requirements: not Dutch
    social: not Dutch, mostly mistakes of social media
    Experience: not Dutch
    influencer : recently accepted by the people
    influencers: ditto
    admin: not Dutch => beheerder
    Group: not Dutch
    CKV: added
    2D; Added, prone to have space mistakes
    2x: wrong
    10x: wrong
    Advertising: not Dutch
    A2C: not Dutch, not a word
    Access: not Dutch
    Advanced: not Dutch
    Peaks: not Dutch
    One: Not Dutch
    11u Missing space
    2a Not a word
    bevolkingsdiagram; added : rare but correct word
    BM-afdeling : not general
    BM-manager: ditto
    CAD: added
    Bpost: not general
    citrix: wrong, should be Citrix
    Corporation: not Dutch
    desymbolisatie: uncommon; added
    Arial; font name, not added
    Angular: 
    AG: not Dutch
    backlog: IT talk
    DJI: short notiation for organisation; added
    Domagoj: unknwon
    Dutch: Engl,ish
    Excel-bestand; would rather see open formats, but added
    funnels; not Dutch
    GDPR; added
    HelloFresh; added company name
    Helvetica; font name, not added
    HIIT-training
    hysteriële
    Instagrammers
    Javascript
    klinimetrische
    ongedifferentieerdheid; added
    minecraft; wrong,
    Panasonic
    Thunberg; lately famous; added
    Rhapsody
    unicef; wrong
    Verdana
    vingerbreien; added
    m²; is in dictionary; could be technical issue behind this...
    OC
    Laertes
    koste; added

**Comment by tiff** [comment]
@baarsrj Thanks. I think the suggestion is wrong sometimes, that's why people add it to the dictionary.

For "unicef" we don't suggest the correct word:
<img width="271" alt="Bildschirmfoto 2020-01-10 um 10 57 28" src="https://user-images.githubusercontent.com/37363/72144060-26f72c80-3398-11ea-8516-d4bbd69c1584.png">

For "minecraft" we don't suggest "Minecraft", same for "citrix" etc.

**Comment by tiff** [comment]
Analytics → Google Analytics (popular tracking tool)

**Comment by danielnaber** [comment]
I will add some of them (the names) to `spelling_global.txt`.

**Comment by baarsrj** [comment]
Company names had better be in the spelling_global, indeed. One issue is that the possessive form is different in English than in Dutch.
