### ISSUE TITLE
[ru] words often added to the dictionary

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2316]
Here's a list (I don't know which of them are valid or not)

* Сулеймани
* Мое
* блогера
* перевыпустить
* Райффайзен
* нахуй
* Бикнюс
* Да-да
* Нямунас
* Санты
* вк
* друг-другу
* интернет-маркетинга
* мое
* постамате
* промо-код
* интернет-магазинов
* тикеты

**Comment by jimregan** [comment]
Definitely ok: 'Сулеймани' (Soleimani) is quite topical, 'блогера' (gen/acc of 'блогер', 'blogger'), 'Нямунас Бикнюс' ('Nemunas Biknius', chairman of Amber Grid). 'нахуй' is a real thing, but it's not really polite, so it might have been left out on purpose.
More than likely wrong: 'Мое'/'мое' should be 'моё', 'друг-другу' is normally written with a space.
'Санты' is (genitive of) 'Santa', but that seems like there should be a suggestion to use 'Санта-Клаус' instead (where 'Санта' does not inflect).

**Comment by jimregan** [comment]
Oh, and 'вк' is an abbreviation of 'vkontakte'

**Comment by tiff** [comment]
@jimregan great thanks. I don't speak a single word Russian. Let's wait what @yakovru has to say. :)

**Comment by tiff** [comment]
@jimregan thanks! Let's wait for @yakovru

**Comment by Katzen-Gott** [comment]
Hi. I'm a native Russian speaker.

Regarding "мое" vs "моё" – Both options are correct. The letter "ё" is a bit discriminated in Russian language, and "е" is quite commonly used instead. BTW, there are some words for which the substitution isn't marked red. It would be great though to have an option to enforce letter "ё".
As for other words not mentioned in comment above +some corrections:

    перевыпустить – perfectly valid word, re-issue (mostly when talking about credit cards)
    Райффайзен – A rather big bank in Russia (Raiffeisen), this is a valid transliteration. Might be considered a stylistic error for official texts, but not in general.
    нахуй – an obscene word. Perfectly valid in terms of grammar. Probably worth changing to a style error
    Да-да – it's a valid construction. Almost any word in Russian can be repeated and connected by a dash (like "далеко-далеко", долго-долго", etc.) and it would all be totally valid.
    интернет-маркетинга – valid, genitive of "итернет-маркетинг" (which is also highlighted with red, even though is a real word). On a second thought it seems to me that almost any pair of words connected with dash could be a valid thing.
    постамате – A case (sorry, I'm bad with linguistic terms) of "постамат"
    промо-код – promotion code (like a coupon)
    интернет-магазинов – genitive of "интернет-магазин"
    тикеты – it's a slang word. Either from '60-'70 meaning transport tickets, or modern IT slang meaning issues or tasks in a task-tracker. Should probably go as a style issue.
