### ISSUE TITLE
m² not accepted on website

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#2319]
It is in the dictionary, but not accepted on the website when checking. Is the info lost in the process somewhere?

**Comment by danielnaber** [comment]
Please send a complete sentence and a screenshot, I cannot reproduce it.

**Comment by baarsrj** [comment]
![afbeelding](https://user-images.githubusercontent.com/8479998/73081557-226a6200-3ec8-11ea-8f90-d44a1b25c021.png)
I think it is caused by internal translation of the square (utf8 superscript) character. Or somewhere in the dictionary creation process.
I tested it in the stand alone version; it is the same there.
So I checked the dictionary again. It is there indeed, but marked to not be included. Do not know how that happened, but the error is completely on my side. I will correct this and test after teh upcoming dictionary update. Sorry I bothered you.
