### ISSUE TITLE
[de] Spell-checker does not allow "CO₂-Ausstoß"

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#2322]
The spell-checker on the website does not accept the compound "CO₂-Ausstoß". "CO₂" in itself is allowed, though.
I could not reproduce the issue with "H₂O-Nachweis". This compound is accepted.

**Comment by danielnaber** [comment]
It's an interesting case: LT tokenizes `CO₂-Ausstoß` so it's one token, but for spell checking, we use (simulate) hunspell tokenizing, where it's more than one token. Solved by a disambiguation rule.
