### ISSUE TITLE
[DE] "Du meins"

### ISSUE THREAD

**Issue by Black56651** [languagetool-org/languagetool#2327]
Moin liebes LanguageTool-Team

Er  sagte: „**Du meins** deine schwarzen Hotpants und dein oranges schwarzes zweiteiliges Kleid.“
Das LanguageTool findet hier keinen Fehler. Dabei ist "du meins" die falsche Verbform. Der Fehler wird wahrscheinlich nicht erkannt, weil die Tags "meins" nicht als Verb sehen, sondern als Personalpronomen.

Das Problem kriegt ihr bestimmt gelöst.

Grüße Black5661

**Comment by tiff** [comment]
Genau, aber:
> Bist du meins?
> Hast du meins genommen?

**Comment by Dallun511** [comment]
Gut, dass du Beispiele hast, denn mir sind keine eingefallen. Zumindest nicht in diesem Moment.

**Comment by Discostu36** [comment]
Dieser Fehler wird inzwischen gefunden.

![grafik](https://github.com/languagetool-org/languagetool/assets/30999326/744675de-7548-4432-a698-c5c4199ee02a)
