### ISSUE TITLE
[de] Detection of incorrect use of ist/sind

### ISSUE THREAD

**Issue by PAX523** [languagetool-org/languagetool#233]
Our customer complains about following example sentence:

    Der Hund sind schön.
    Der Text sind gut.
    Das Auto sind schnell.
    Die Autos ist schnell.

Obiously, the rules don't detect the incorrect usage of ist/sind depending on the plural/singular form of the previous noun.

I think, this would be a good enhancement if such kind of errors will be detected. Is there a special reason to not recognizing such constellations?

**Comment by danielnaber** [comment]
`Der Hund sind schön`, but `Die Katze und der Hund sind schön.` So you first need to find the noun phrase if you want to cover these cases correctly (not just the trivial ones). We don't have noun phrase detection for German yet. You might wand to write a rule like `SENT_START "der|die|das" SUB:.*SIN.* "sind"` so the cases get at least detected at the start of the sentence.

**Comment by PAX523** [comment]
Now, I understand the problem. It seems to be difficult to detect the more complex cases. It's a pitty that MS Word does also detect your example with: ``Die Katze und der Hund ist schön``. Possibly, our grammar rules approach has potential for improvement?

**Comment by milekpl** [comment]
In one of Polish shallow grammar parsers, the strategy is very simple:

define NP as a noun

then NP + "and|or" + NP is NP

and so on. For German, this should work even better because the word order is much more strict than in Slavonic languages, and you can reuse the determiner information. The easiest strategy would be to use unification with determiners (over gender, number and case). This can then be generalized with adjectives easily. This could work beautifully for discarding improper readings during disambiguation as well.

**Comment by milekpl** [comment]
One important issue that I noticed when Daniel linked NP chunkers on the wiki – it's a universal assumption in all standard NP chunkers that an NP phrase *cannot* include another. This is means that the statistical chunkers will *not* work for `Die Katze und der Hund sind schön.`

**Comment by danielnaber** [comment]
I'm playing with the disambiguator and results don't look bad so far. The disambiguation will need to be done in a Java rule or so, as many rules would break once unification is activated.

**Comment by milekpl** [comment]
Well, unification can be used in a single rule only, without disambiguating first. But it would be simply a little slower without precomputation. Anyway, my experience was that if good disambiguation (that cleans up the mess) breaks a rule, then the rule should be fixed first....

**Comment by milekpl** [comment]
I'm apparently quite slow-witted today: do we already have the syntactic sugar for chunking in the disambiguator?

**Comment by danielnaber** [comment]
I don't think so: for testing, I do `<disambig action="unify"/>`and then in another rule e.g. `<disambig action="add"><wd pos="NPS"/><wd pos="NPS"/></disambig>`. (NPS = noun phrase singular)

**Comment by danielnaber** [comment]
This is now being worked on in branch `sv-agreement`.

**Comment by danielnaber** [comment]
This has now been implemented. The implementation is documented at http://wiki.languagetool.org/german-agreement-check. We cannot avoid all false alarms, but I think it's quite okay. In case of problems, please open a new issue.
