### ISSUE TITLE
[en] suggestion in parenthesis

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2332]
> Shelley, I have three PAA's that the North team has done.

<img width="482" alt="Bildschirmfoto 2020-01-14 um 14 32 53" src="https://user-images.githubusercontent.com/37363/72348584-005c2d00-36db-11ea-8e2f-f85a09b4ffde.png">

The `<suggestion>` has `suppress_misspelled=yes`.

Probably related to https://github.com/languagetool-org/languagetool/issues/2226

@danielnaber can you have another look?

**Comment by danielnaber** [comment]
Seems to work when the `suppress_misspelled="yes"` is in the `match`, not in `suggestion`.

**Comment by MikeUnwalla** [comment]
@danielnaber , suggestion: put a check in testrules to give a warning if `suppress_misspelled `is in the `suggestion`. Possibly, make Maven give a failure message.

**Comment by danielnaber** [comment]
> suggestion: put a check in testrules to give a warning if suppress_misspelled is in the suggestion

See #2188
