### ISSUE TITLE
[es] "ultimas" vs "últimas"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2345]
Reported by a user:
> "ultimas" should have accent and application does not mark this error.

@jaumeortola I already found that "ultimas" is the plural of "ultima". Is there a way to detect this based on context?

**Comment by jaumeortola** [comment]
ultimas (verb) vs últimas (adj plural). It is related to #2197.

**Comment by jaumeortola** [comment]
As it is probably a very common error, I will add a specific rule.

**Comment by jaumeortola** [comment]
Fixed with https://github.com/languagetool-org/languagetool/commit/195eec009f1979d4de7d53f75a694d01a2596e24
