### ISSUE TITLE
[de] "nix"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2350]
Das Wort "nix" ist mittlerweile im Duden:
https://www.duden.de/rechtschreibung/nix

LT markiert es aber als Rechtschreibfehler. Sollen wir es aufnehmen und eine einfache Stilregel hinzufügen "nix" → "nichts"?

cc @danielnaber

**Comment by danielnaber** [comment]
Ja, finde ich gut

**Comment by tiff** [comment]
https://github.com/languagetool-org/languagetool/commit/3be13f804c51501e9f9247a3c440625698c850a0
