### ISSUE TITLE
[en] "themself"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2353]
Saw a few users adding "themself" to their dictionary.
It's already in our British dictionary (but not POS-tagged). The American dictionary doesn't have it.

@MikeUnwalla should we add and tag it? Do we need a rule for it?

https://www.lexico.com/definition/themself
Webster says it's "non-standard": https://www.merriam-webster.com/dictionary/themself

**Comment by MikeUnwalla** [comment]
Lexico also says 'themself' is non-standard.

If the word does not give a spelling error, then it should have a postag. I think that a rule to say the term is not standard and not widely accepted is the best solution.

**Comment by tiff** [comment]
I'll take care. Thanks.
