### ISSUE TITLE
[en] false alarm COLLECTIVE_NOUN_VERB_AGREEMENT_VBD?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2354]
> A couple of developers have let me know they are discussing your issue.

<img width="566" alt="Bildschirmfoto 2020-01-22 um 09 27 08" src="https://user-images.githubusercontent.com/37363/72877545-73782b80-3cf9-11ea-8d6b-faf561faa5a0.png">

Is this a false alarm or is "has" necessary because of "couple"?

**Comment by MikeUnwalla** [comment]
I think it is a false alarm. 'Couple' can be treated as singular or plural in some cases (not this one): https://www.lexico.com/definition/couple

**Comment by tiff** [comment]
@MikeUnwalla can you add an antipattern?
