### ISSUE TITLE
[en] false alarm VERB_APOSTROPHE_S

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2358]
> For instance, the 1948 ABL finalist Baltimore Bullets moved to the BAA and won that league's 1948 title

<img width="976" alt="Bildschirmfoto 2020-01-22 um 13 15 27" src="https://user-images.githubusercontent.com/37363/72893562-9a465a00-3d19-11ea-93ec-d85c2a7873b8.png">

**Comment by MikeUnwalla** [comment]
@tiff , it's probably caused by a disambiguation error in NNS_WDT_VBNNS_VBP.
