### ISSUE TITLE
[extension] languagetool breaks CSS-grids

### ISSUE THREAD

**Issue by Christoph-Wagner** [languagetool-org/languagetool#2359]
Tested in both Chrome and FF. 

Example: https://codepen.io/cwagner/pen/qBELvpL (click into the big text editor with LT enabled)

The element `lt-mirror` has `grid-area: none !important;` applied to it. I assume this is supposed to prevent that problem? But according to [the grid-area docs](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-area) `none` is not a valid value.

And while it has `display:none` in its `style`-Attribute, this gets overwritten and so it becomes a part of the grid elements and breaks things. This is even the case when languagetools is disabled for the textfield or domain.

**Comment by tiff** [comment]
@Christoph-Wagner Thanks. We will add "position: absolute" to the `lt-mirror`. 
Next release will contain this fix (~2 weeks). In the future, we will use shadow DOM to overcome such issues.

**Comment by tiff** [comment]
This has been fixed. It's part of the current Chrome release (v3.0.6). Firefox will follow shortly.
