### ISSUE TITLE
Invalid frequency values?

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#236]
Working on https://github.com/morfologik/morfologik-stemming/issues/34#issuecomment-72022411, I found some code that might be wrong: in `DictionaryBuilder`, there's a comment `Convert integers 0-255 to ranges A-Z, and write output`. But nothing seems to ensure that the integer is actually in range 0-255, and if it's not, some special character will be written which later can lead to negative frequency values in Morfologik's `Speller.getFrequency()`. Or am I missing something?

The frequency data is from Mozilla's gaia, which takes it from http://www.spellonit.com/downloads/frequencies/

**Comment by jaumeortola** [comment]
You are right. I have added an exception for out-of-range frequency.

**Comment by baarsrj** [comment]
Was it ever specified as 0-255 ? And if so, which is the highest frequency?

Ruud

**Comment by danielnaber** [comment]
I'll add some code to make sure everything ends up in 0 - 255.
