### ISSUE TITLE
correction loop anymore <-> any more

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2368]
> If we see that your plan isn't a good fit anymore in the long run, we'd contact you.

I see that one of the messages is "Make sure" and the other one "Did you mean", but I hope we can solve this somehow.

**Comment by MikeUnwalla** [comment]
@daniel, both messages have "Did you mean...".

The first sentence of the messaage in ANYMORE_ADVERB is "Make sure that '\1' is used as an adverb, not as an adjective." Let me know if you want me to change that message. Possible change:
"Use '\1' as an adverb, not as an adjective."
