### ISSUE TITLE
"functionalities" marked as incorrect

### ISSUE THREAD

**Issue by vogella** [languagetool-org/languagetool#237]
AFAIK "functionalities" is valid English.

**Comment by danielnaber** [comment]
I've copied the request to https://github.com/kevina/wordlist/issues/95, feel free to submit requests there.

**Comment by marcoagpinto** [comment]
It is in the British dictionary.

On 04/02/2015 14:06, Lars Vogel wrote:
>
> AFAIK "functionalities" is valid English.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/languagetool-org/languagetool/issues/237>.
>


--

**Comment by baarsrj** [comment]
Even though some consider functionality a container word like universe, there are persons considering subfunctionalities as functionalities.

Verzonden van smartphone.

"Marco A.G.Pinto" <notifications@github.com>schreef:

It is in the British dictionary.
On 04/02/2015 14:06, Lars Vogel wrote:
>
> AFAIK "functionalities" is valid English.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/languagetool-org/languagetool/issues/237>.
>

--
