### ISSUE TITLE
[es] "Malaga"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2375]
Feedback from a Spanish user:
> The word Málaga in spanish needs accent, and application do not shows as error.

**Comment by jaumeortola** [comment]
Now it is fixed. But perhaps the message is a bit confusing. (Do you mean "Malaga" in English?). 
![imatge](https://user-images.githubusercontent.com/4289501/77453692-dc624980-6df7-11ea-9857-661afd14534b.png)

**Comment by danielnaber** [comment]
> But perhaps the message is a bit confusing.

Indeed. This "feature" will not make it into the updated homepage, which we're working on.
