### ISSUE TITLE
[en] wrong suggestion EN_WORD_COHERENCY

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2379]
@danielnaber I think this is java-related. It should suggest "reelected"

> He was reelected to the Illinois Senate in 1998, defeating Republican Yesse Yehudah in the general election, and was re-elected again in 2002.

<img width="907" alt="Bildschirmfoto 2020-01-28 um 16 25 13" src="https://user-images.githubusercontent.com/37363/73277832-fcf09780-41ea-11ea-8956-e759dc39a394.png">

**Comment by danielnaber** [comment]
Should be fixed now.
