### ISSUE TITLE
[en] filter "s" entry in spelling suggestion

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2382]
The "timezone s" entry doesn't make any sense:

<img width="402" alt="Bildschirmfoto 2020-01-30 um 16 36 55" src="https://user-images.githubusercontent.com/37363/73464223-d8c5bf80-437e-11ea-8e2f-778f13719672.png">

I think we can filter out suggestions with a lonely single lower case "s". Please also ensure the functionality introduced in https://github.com/languagetool-org/languagetool/issues/2031 does not break.

**Comment by tiff** [comment]
Same with "t"
> He campaignt

**Comment by danielnaber** [comment]
Actually happens with all characters it seems. My fix for now is limited to the contractions: `s|t|d|ll|ve`
