### ISSUE TITLE
[de] wrong suggestion KOMMA_INFINITIVGRUPPEN

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2383]
> Der Notdienst versteht es die Tür des Tresors ohne Schlüssel zu öffnen

<img width="617" alt="Bildschirmfoto 2020-01-30 um 17 02 38" src="https://user-images.githubusercontent.com/37363/73466600-6060fd80-4382-11ea-938c-4b29df922a7b.png">

**Comment by f-knorr** [comment]
There is definitively a comma missing: no false alarm, although the coma should follow "es"

**Comment by tiff** [comment]
@f-knorr thanks. I'm re-opening this because the suggestion is wrong.

**Comment by AgnesKleinhans** [comment]
Das hier kann geschlossen werden :-)
