### ISSUE TITLE
[en] false alarm BORED_OF?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2385]
> By this I came to truly believe that this Qur’an does not wear from continuous repetition, nor will you ever get bored of its speech.

<img width="972" alt="Bildschirmfoto 2020-01-30 um 20 23 16" src="https://user-images.githubusercontent.com/37363/73482743-9613df80-439e-11ea-8005-a8f993f244e2.png">

@MikeUnwalla I think we can move this to "style". What do you think? See https://www.lexico.com/grammar/bored-by-of-or-with

**Comment by MikeUnwalla** [comment]
@tiff , I agree. I'll leave the change to you.

**Comment by tiff** [comment]
Done via https://github.com/languagetool-org/languagetool/issues/2385
