### ISSUE TITLE
[en] wrong disambiguation

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2386]
> They could maybe go and hangout.

"go" is only tagged as NN by NN_CC_NN

Of course, there's a grammar issue: "hangout" (is a noun, but the user probably meant "hang out"). Still I think we should be able to handle this because of the modal verb.

Interestingly it doesn't happen with:
> They maybe go and hangout.

**Comment by MikeUnwalla** [comment]
Another one:

> She might possibly go and hangout.
