### ISSUE TITLE
unification bug

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#239]
This is easy to reproduce but not so easy fixable (for me), so I hope @milekpl can help with this: 

In German (latest source from git required) `Die alten Angst` gets unified, although it shouldn't. The problem seems to be that `getFinalUnificationValue()` returns true. Then, getUnifiedTokens() breaks and returns a "unification" where `alten` has been unified to a different token, namely `Angst`. This can be seens when turning on verbose mode.

**Comment by milekpl** [comment]
We have a bug somewhere, as "alten" gets rewritten:

<S> Die[der/ART:DEF:AKK:SIN:FEM,der/ART:DEF:NOM:SIN:FEM,der/PRO:DEM:AKK:SIN:FEM,der/PRO:DEM:NOM:SIN:FEM,der/PRO:PER:AKK:SIN:FEM,der/PRO:PER:NOM:SIN:FEM,B-NP|NPS] Angst[Angst/SUB:AKK:SIN:FEM,I-NP|NPS] Angst[Angst/SUB:NOM:SIN:FEM,I-NP|NPS].[</S>./PKT,O]<P/> 
Disambiguator log: 

UNIFY_DET_ADJ_SUB:1 Die[der/ART:DEF:AKK:PLU:FEM*,der/ART:DEF:AKK:PLU:MAS*,der/ART:DEF:AKK:PLU:NEU*,der/ART:DEF:AKK:SIN:FEM*,der/ART:DEF:NOM:PLU:FEM*,der/ART:DEF:NOM:PLU:MAS*,der/ART:DEF:NOM:PLU:NEU*,der/ART:DEF:NOM:SIN:FEM*,der/PRO:DEM:AKK:PLU:ALG*,der/PRO:DEM:AKK:SIN:FEM*,der/PRO:DEM:NOM:PLU:ALG*,der/PRO:DEM:NOM:SIN:FEM*,der/PRO:PER:AKK:PLU:ALG*,der/PRO:PER:AKK:SIN:FEM*,der/PRO:PER:NOM:PLU:ALG*,der/PRO:PER:NOM:SIN:FEM*] -> Die[der/ART:DEF:AKK:SIN:FEM*,der/ART:DEF:NOM:SIN:FEM*,der/PRO:DEM:AKK:SIN:FEM*,der/PRO:DEM:NOM:SIN:FEM*,der/PRO:PER:AKK:SIN:FEM*,der/PRO:PER:NOM:SIN:FEM*]

UNIFY_DET_ADJ_SUB:1 alten[alt/ADJ:AKK:PLU:FEM:GRU:DEF,alt/ADJ:AKK:PLU:FEM:GRU:IND,alt/ADJ:AKK:PLU:MAS:GRU:DEF,alt/ADJ:AKK:PLU:MAS:GRU:IND,alt/ADJ:AKK:PLU:NEU:GRU:DEF,alt/ADJ:AKK:PLU:NEU:GRU:IND,alt/ADJ:AKK:SIN:MAS:GRU:DEF,alt/ADJ:AKK:SIN:MAS:GRU:IND,alt/ADJ:AKK:SIN:MAS:GRU:SOL,alt/ADJ:DAT:PLU:FEM:GRU:DEF,alt/ADJ:DAT:PLU:FEM:GRU:IND,alt/ADJ:DAT:PLU:FEM:GRU:SOL,alt/ADJ:DAT:PLU:MAS:GRU:DEF,alt/ADJ:DAT:PLU:MAS:GRU:IND,alt/ADJ:DAT:PLU:MAS:GRU:SOL,alt/ADJ:DAT:PLU:NEU:GRU:DEF,alt/ADJ:DAT:PLU:NEU:GRU:IND,alt/ADJ:DAT:PLU:NEU:GRU:SOL,alt/ADJ:DAT:SIN:FEM:GRU:DEF,alt/ADJ:DAT:SIN:FEM:GRU:IND,alt/ADJ:DAT:SIN:MAS:GRU:DEF,alt/ADJ:DAT:SIN:MAS:GRU:IND,alt/ADJ:DAT:SIN:NEU:GRU:DEF,alt/ADJ:DAT:SIN:NEU:GRU:IND,alt/ADJ:GEN:PLU:FEM:GRU:DEF,alt/ADJ:GEN:PLU:FEM:GRU:IND,alt/ADJ:GEN:PLU:MAS:GRU:DEF,alt/ADJ:GEN:PLU:MAS:GRU:IND,alt/ADJ:GEN:PLU:NEU:GRU:DEF,alt/ADJ:GEN:PLU:NEU:GRU:IND,alt/ADJ:GEN:SIN:FEM:GRU:DEF,alt/ADJ:GEN:SIN:FEM:GRU:IND,alt/ADJ:GEN:SIN:MAS:GRU:DEF,alt/ADJ:GEN:SIN:MAS:GRU:IND,alt/ADJ:GEN:SIN:MAS:GRU:SOL,alt/ADJ:GEN:SIN:NEU:GRU:DEF,alt/ADJ:GEN:SIN:NEU:GRU:IND,alt/ADJ:GEN:SIN:NEU:GRU:SOL,alt/ADJ:NOM:PLU:FEM:GRU:DEF,alt/ADJ:NOM:PLU:FEM:GRU:IND,alt/ADJ:NOM:PLU:MAS:GRU:DEF,alt/ADJ:NOM:PLU:MAS:GRU:IND,alt/ADJ:NOM:PLU:NEU:GRU:DEF,alt/ADJ:NOM:PLU:NEU:GRU:IND] -> Angst[Angst/SUB:AKK:SIN:FEM]

UNIFY_DET_ADJ_SUB:1 Angst[Angst/SUB:AKK:SIN:FEM,Angst/SUB:DAT:SIN:FEM,Angst/SUB:GEN:SIN:FEM,Angst/SUB:NOM:SIN:FEM] -> Angst[Angst/SUB:NOM:SIN:FEM]

UNKNOWN_PKT:1 .[./SENT_END*] -> .[./SENT_END*,./PKT*]

This is quite weird, as the marker seems to be fine.

**Comment by milekpl** [comment]
OK, I have a fix for the issue but tests for the German agreement rule fail with it. I looked at the tags for the failing sentence and my understanding is that the rule has some bug. See the fix here:

https://gist.github.com/milekpl/1aae76888ba9c93e7e4c

It basically adds a boolean sentry "unifiedTokensFound" in two methods to avoid cases that you found.

**Comment by danielnaber** [comment]
Yes, the rule produces a false alarm. Your patch looks fine, please commit it. Thanks!
