### ISSUE TITLE
[en] Add "lbf" to segment.srx

### ISSUE THREAD

**Issue by kijerk** [languagetool-org/languagetool#2392]
Please add "lbf" (Pound-force) as a unit to the english languagerule.

A good insert location would be this rule (in additon to "lb" and "lbs"):

`<beforebreak>\b(pp|[Vv]iz|i\.?\s*e|[Vvol]|[Rr]col|maj|Lt|[Ff]ig|[Ff]igs|[Vv]iz|[Vv]ols|[Aa]pprox|[Ii]ncl?|Pres|[Dd]ept|min|max|[Gg]ovt|lb|ft|c\.?\s*f|vs|dia|lbs|\d+-(:?oz|kc|in|h[rp]|ml)|M?sec)\.\s</beforebreak>
<afterbreak>[^\p{Lu}]|I</afterbreak>`

Thank you!

**Comment by danielnaber** [comment]
Done, thanks.
