### ISSUE TITLE
[en] false alarm POSSESSIVE_APOSTROPHE?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2393]
> He did it via standard Windows deployment tools.

"Windows" is used here as a proper noun (operating system)

<img width="557" alt="Bildschirmfoto 2020-01-31 um 09 59 02" src="https://user-images.githubusercontent.com/37363/73525934-6e5d5f80-4410-11ea-86ac-5eff03699386.png">

**Comment by MikeUnwalla** [comment]
The the cross-reference to 2396 is not correct, but I do not know how to delete it.

**Comment by MikeUnwalla** [comment]
@tiff , I fixed the disambiguation JJ_VBZ_NNS such that it does not remove NNP from Windows. That correction causes POSSESSIVE_APOSTROPHE not to give a warning.

But, I think that the rule should give a warning. Compare:

> He did it using Peters deployment tools.

Correct text is one of these:

> [If the proper noun is Peter] He did it using Peter's deployment tools.
> [If the proper noun is Peters] He did it using Peters' deployment tools.
