### ISSUE TITLE
[en] Add rule: Check "latter" vs "later" when use a "former, latter" structure.

### ISSUE THREAD

**Issue by MayeulC** [languagetool-org/languagetool#2401]
It is quite common to use a "former, latter" sentence structure when contrasting different elements.
As a non-native speaker, I just discovered the difference between "later" (one "T") and "latter" (two "T"s). The former is only used in relation to dates and temporal events, while the latter is used to reference part of the sentence structure.

Had I used "later" in the above sentence, it would have been incorrect, and languagetool is currently unable to spot that. Unfortunately, I am unsure how to contribute that rule.

**Comment by MikeUnwalla** [comment]
@danielnaber , this is a good candidate for the statistics module.

**Comment by danielnaber** [comment]
@MikeUnwalla you're right, I've just checked it. But it's always "**the** former" and "**the** latter", isn't it? In that case, I think a rule could be more robust, i.e. find all errors and yet cause hardly any false alarms. The ngram rule would only find ~ 50% of these errors.

**Comment by MikeUnwalla** [comment]
@danielnaber , I made a general rule for later/latter.

**Comment by MikeUnwalla** [comment]
@MayeulC , this rule will be available tomorrow (Monday).

**Comment by MayeulC** [comment]
Thank you a lot, I wasn't sure such feature requests were appreciated!

**Comment by MikeUnwalla** [comment]
> I wasn't sure such feature requests were appreciated

They are. Thank you.
