### ISSUE TITLE
In the online LT, 'correct' text does not have a highlight, unlike in the GUI

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#2408]
In the GUI, in the correct example, there is a highlight on 'is':
![image](https://user-images.githubusercontent.com/5816160/73731864-1b95e780-4731-11ea-91df-f103afa197b6.png)

With languagetool.org, there is no highlight:
![image](https://user-images.githubusercontent.com/5816160/73731922-310b1180-4731-11ea-8c8f-a4db74a7b2cc.png)

It would be nice to see the highlighted correction on the example.

**Comment by danielnaber** [comment]
Closing, as this refer to the old homepage.
