### ISSUE TITLE
[en] false alarm WHO_WHOM?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2412]
Hey @MikeUnwalla we had a user today who complained about a suggestion that turned "who" into "whom".

Here are a few examples I found that sound right to me but I don't really know if those are false alarms or not:

<img width="523" alt="Bildschirmfoto 2020-02-05 um 18 56 48" src="https://user-images.githubusercontent.com/37363/73868832-7a4e8480-4849-11ea-9786-7c32f7c66ea6.png">

> A search for who we are.
> As for who I am, you wouldn't believe me if I told you.
> They are different and they are important because of who they are.
> Love yourself for who you are.
> Just remember, the universe reflects back to you who you really think you are.

cc @danielnaber

**Comment by MikeUnwalla** [comment]
@tiff , 

Rulegroup `rulegroup id="WHO_WHOM" name="who (whom)" ` contains rules for who>whom and for whom>who. There is also `rulegroup id="WHOM_WHO" name="whom (who)"`, which contains rules only for who>whom (despite its name).

As a precursor to trying to fix the FP, I propose to move the rules into the correct rulegroups. Can you see any problems with that?

**Comment by tiff** [comment]
No. Sounds good to me
