### ISSUE TITLE
[en] wrong tagging and false alarm YOUR_NN

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2421]
> “You're welcome, Tina.”

"welcome" is **only** tagged as "NN:UN"
This doesn't happen without the quote at the beginning.

<img width="413" alt="Bildschirmfoto 2020-02-06 um 16 15 41" src="https://user-images.githubusercontent.com/37363/73950274-f0abbf00-48fb-11ea-8de3-1afbb33e6995.png">

**Comment by danielnaber** [comment]
@MikeUnwalla Could you have a look? It's caused by disambiguation rule `E_NP_NN_VBP`.
