### ISSUE TITLE
[en] error cannot be found due to disambiguation

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2422]
> He is try to make it work.
> He was hope to get it done.

Both "try" and "hope" are **only** tagged as noun by `was_is_VB_NN`. This makes it impossible to catch this mistake, I think. The rule "BEEN_PART_AGREEMENT" would normally catch this.

@MikeUnwalla what do you think, should we remove the disambiguation rule or do you see any way how we can improve it?

**Comment by MikeUnwalla** [comment]
@tiff , in this case, I think an AP (PRP + is/was + VB + to) will solve the problem.

The disambiguation rule correctly disambiguates some text, but there are also incorrect disambiguations (which are in comments). I will see if I can fix them also.

**Comment by tiff** [comment]
I think this will still cause wrong tagging for a sentence like this:
> I was hope my favorite club would win

**Comment by MikeUnwalla** [comment]
I see what you mean. Feel free to remove the rule, because it seems to cause more problems than it solves.

**Comment by tiff** [comment]
Ok, I will check if that's easily possible.

**Comment by tiff** [comment]
I had to revert the removal. BEEN_PART_AGREEMENT is dependent on it: https://github.com/languagetool-org/languagetool/issues/2434

**Comment by MikeUnwalla** [comment]
@tiff , @danielnaber asked me to look at this.

**Comment by MikeUnwalla** [comment]
Incorrect grammar for which verb/noun should not be disambiguated as a noun:
- [ ] He is try to make it work.
- [ ] He was hope to get it done.
- [ ] I was hope my favorite club would win.
- [ ] The criminal was lead into a life of crime by...
- [ ] ... and this was lead into the ...
