### ISSUE TITLE
In additional

### ISSUE THREAD

**Issue by vogella** [languagetool-org/languagetool#243]
As promised a while ago to want to start contributing rules to you. I tried to create a rule which marks "in additional" as incorrect but my rules seems incorrect. Can you tell me what is wrong here?
```xml
<!-- English rule, 2015-03-18 -->
<rule id="ID" name="In additional">
 <pattern>
  <token postag='in' postag='additional'></token>
 </pattern>
 <message>In additional is typically wrong, perhaps you mean <suggestion>in addition</suggestion>?</message>
 <short>Use "in addition</short>
 <example correction=''>In additional this helps.</example>
 <example>In addition this helps.</example>
</rule>
```

**Comment by vogella** [comment]
Sorry don't know how to make Github issue respect line breaks in XML code I paste

**Comment by danielnaber** [comment]
The pattern for `in additional` is simply this:

    <pattern>
      <token>in</token>
      <token>additional</token>
    </pattern>

**Comment by vogella** [comment]
If I try to use this on http://community.languagetool.org/ruleEditor2 I get the following error:

Message: No signature of method: org.languagetool.rules.patterns.PatternRule.getElements() is applicable for argument types: () values: []

**Comment by vogella** [comment]
Maybe the website check is broken? I tried @Mailaender example for "Vogella" from http://blog.vogella.com/2014/05/09/languagetool/ and this is also reported as broken.

**Comment by Mailaender** [comment]
> Sorry don't know how to make Github issue respect line breaks in XML code I paste

Fixed. See https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks

**Comment by vogella** [comment]
Thanks @Mailaender for fixing the example code.  http://community.languagetool.org/ruleEditor2 still reports you and my example XML as incorrect.

**Comment by danielnaber** [comment]
Thanks, the rule editor should work again.
