### ISSUE TITLE
Are Scala jars needed?

### ISSUE THREAD

**Issue by isahb** [languagetool-org/languagetool#2438]
Hello,

I'm packaging LanguageTool in my serverless Lambda(https://github.com/isahb/sls-spellchecker), and my total fat jar size is ~**61 MB**.
Upon investigation, I noticed that the biggest libraries are **scala-compiler**, **scala-reflect**, **akka-actor** totaling more than **20 MB** that are coming as transitive dependencies of **xgboost4j**. 

**scala-library** is excluded though.

Are they necessary? I excluded them and I haven't encountered any `ClassNotFoundException` so far.
It is crucial for the fat jar to be as small as possible to reduce cold start time of the lambda.

**Comment by danielnaber** [comment]
No, the scala JARs should not be needed for normal operation.
