### ISSUE TITLE
Add "runtime" as word for English

### ISSUE THREAD

**Issue by vogella** [languagetool-org/languagetool#244]
See http://www.oxforddictionaries.com/definition/english/runtime

**Comment by danielnaber** [comment]
Please report new words at https://github.com/kevina/wordlist/issues

**Comment by marcoagpinto** [comment]
That word is already in en_GB.

Before suggesting a word, please check the list on:
https://github.com/marcoagpinto/aoo-mozilla-en-dict

And, if not there, please open a case there for en_GB or a case in US/CA (Kevin Atkinson) if it is missing in US/CA.

**Comment by vogella** [comment]
I'm using the daily build of languagetools? Why are these words not in it, if they already available in the directory?

**Comment by danielnaber** [comment]
The English dictionary we use in LT isn't totally up-to-date.
