### ISSUE TITLE
[en] false alarm A_UNCOUNTABLE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2442]
> It was thrown off of a garbage truck

<img width="517" alt="Bildschirmfoto 2020-02-10 um 16 24 29" src="https://user-images.githubusercontent.com/37363/74162910-d5a1bd80-4c21-11ea-918f-c9aff0c1a1f3.png">

> Please focus on a research question

<img width="564" alt="Bildschirmfoto 2020-02-10 um 16 25 19" src="https://user-images.githubusercontent.com/37363/74163004-fd912100-4c21-11ea-923a-80c81436016a.png">

More: 
> Move it into a food processor

> Please keep a food diary.

> They found an alternative accommodation

**Comment by MikeUnwalla** [comment]
If there is a full stop at the end of each sentence, the rule gives a correct analysis. (The last sentence is not a false positive).

Without a full stop, the last sentence is not found.

**Comment by SkyCharger001** [comment]
without "an" "alternative accommodation" should be "alternative accommodations". (on the other hand, the latter is the more common form)
