### ISSUE TITLE
[ru] Headache

### ISSUE THREAD

**Issue by sergus2008** [languagetool-org/languagetool#2443]
Немного поизучал аддон для firefox и собрал несколько ошибок и предложений. Поскольку не умею в программирование, попробовал дать предложения из тех, что на мой взгляд, можно реализовать.

Предложения:

- [ ] 1. Дать возможность корректировать персональный словарь: возможности определения склонений, родов, чисел для внесенных слов и связывать их как "одно и то же слово, разных склонений" и т.п.
- [x] 2. Неуверена ("не уверена", либо "неуверенна"), аналогично неуверено, неуверены http://www.bolshoyvopros.ru/questions/2666147-kak-pishetsja-ne-uverena-ili-neuverena.html
- [x] 3. Неуверен (ошибка "не уверен")
- [x] 4. В правило "Два глагола в личной форме подряд" добавить "необходимо"
- [x] 5. Если (когда) вы ищете (делаете и другие глаголы) - глагол в настоящем времени не может быть в повелительном наклонении ("если ищите" - ошибка). Можно ли реализовать?
- [x] 6. Можно ли реализовать определение отсутствия запятой в сложноподчиненных предложениях, хотя бы в простейшем случае:
Существительное (местоимение) в именительном падеже и глагол(,) пока (если, когда и т.д.) существительное (местоимение) в именительном падеже и глагол. "Я думал о будущем, пока сын жил настоящим". 
- [x] 7. "Как ни странно" пришется через "ни" (ошибка "как не странно")
      8. Запятая перед "как" не ставится: 
 - [ ] 8.1 в начале предложения («с того времени как…», «с той поры как…», «по мере того как…»);
 - [x] 8.2 при двойном союзе «как… так и…» (перед так должна ставиться)
 - [x] 8.3 В сочетаниях «как ни в чём не бывало», «почти как», «вроде как», «как можно», «точь-в-точь как»;
 - [x] 8.4 При наличии отрицательной частицы ("У них все не как у людей") 
         https://mel.fm/pravopisaniye/7841235-commas_kak
 - [x] 8.5 Если в предложении подлежащее и сказуемое - существительные (местоимения) в именительном падеже (можно перед как ставить тире);
 - [x] 8.6 Когда оборот выступает в качестве обстоятельства, простейший оборот "Тропинка извивалась как змея". Первая часть предложения | как | имя существительное в именительном падеже.  
- [x] 9. "Как бы то (там) ни было" Устойчивое словосочетание, не должно быть ошибок вроде "как-бы то..." "как бы-то ни было", "как бы то не было"
- [ ] 10.  После местоимения не должно быть дефиса, если подлежащее местоимение, а сказуемое - существительное. "Он (-) великий человек.
 http://gramota.ru/forum/veche/84515/
- [x] 11. Не должны выделяться запятыми с двух сторон: "в действительности", "в итоге", "в конечном итоге", "в любом случае", "в особенности", "в остальном", "в результате", "в связи с вышеизложенным", "ведь", "вместе с тем", "на всякий случай", "на данный момент", "наверняка", "несмотря ни на что"
 https://obrazovaka.ru/zapyataya
- [x] 12. "До тех пор(,) пока", "лучше(,) чем", "хуже(,) чем", "несмотря на то(,) что" обязательна запятая;
 https://obrazovaka.ru/zapyataya
- [x] 13. "мол" с двух сторон выделяется запятыми
https://obrazovaka.ru/zapyataya
- [x] 14. Дополнить словами "берсерк...", "впечатлены", "голем...", "зачарование...", "культист...", "крысёныш...", "насоздавал...", "неизменившийся...", "необременённый...", По-девичьи, скольки (до скольки), засмущала, какой-никакой, переподписать, подытог
- [x] 15. Всё также как было. ("Так же" раздельно перед "как")
https://yandex.ru/q/question/hw.russian/kak_pishetsia_takzhe_slitno_ili_razdelno_74976736/?utm_source=yandex&utm_medium=wizard&answer_id=ab2bd2ce-2f1e-4066-af79-cce46556d724

Ошибки в имеющихся правилах:

- [ ] 1. "Орфографическая ошибка": для слов с ошибкой не появляются близкие слова, внесенные в персональный словарь
- [x] 2. "В место" всегда определяет как ошибку, даже в предложении "Прибыл в место назначения.", аналогичная ошибка "За место"
- [x] 3. И то и то правда. Замечание: Пропущена запятая:"то и, то правда".
 Во-первых, неправильно определяется, в каком месте должна стоять запятая. Во-вторых "и то и то", "и то и сё", "и то и другое" являются устойчивыми выражениями и не разделяются запятой.
https://elhow.ru/ucheba/russkij-jazyk/punktuacija/kak-pishetsja-i-to-i-to
- [x] 4. "по истинному" Замечание "по-истинному". Не во всех случаях пишется через дефис. Например, "Пойти по истинному пути."
- [x] 5. Орфографическая ошибка "как-будто", стоит предлагать на замену "как будто", сейчас предлагаются "как-то, кому-то"
- [x] 6. Во фразах типа "Серый зол." имеется замечание "Прилагательное не согласуется с существительным по числу.", но здесь нет ошибки. Аналогично "Серый дарит" замечание "Прилагательное не согласуется с существительным по роду"
- [x] 7. «Сперва» замечание "ошибочное слово/фраза, исправление: "сначала". Такое слово существует.
- [x] 8. Замечание "Опущено существительное в конце предложения." необходимо конкретизировать или убрать. Часто появляются замечания, например в предложениях "Попытка использовать его кажется опасной, если не убийственной." "Это свод законов, суровых и справедливых."
- [x] 9. "Замечание "Пропущена запятая: "сделали предложение, и бросили вызов" Они сделали предложение и бросили вызов мне." Если словао "предложение" и "вызов" (или любое другое, например "дом") в винительном падеже, то появляется замечание, которого не должно быть.
- [x] 10 Замечание "Не ставьте два «не» подряд, если это не оправдано смыслом предложения." "Не могу не согласиться." и во многих других случаях также считается ошибкой, чего не должно быть.
- [x] 11. Замечание "Местоимение в конце предложения не употребляется." Насколько мне известно, такого правила не существует. "Сделать меня таким, как он.", и много других предложений выдают ошибки.
- [x] 12. Замечание "Запятая не нужна:"знаю что нужно" срабатывает на предложении "Я не знаю, что нужно сделать."
- [x] 13. Замечание "Существительное не согласуется с глаголом по числу." срабатывает, если существительное заканчивается на "-и", например, в словосочетании "Натали сказала"
- [x] 14. Замечание "Оборот с неопределенной формой глагола со всеми относящимися к ней словами, присоединёнными союзами «чтобы/чтоб»" просит поставить запятую перед "чтобы", даже если предложение начинается с этого слова после знака. Например, (Чтобы... или "Чтобы...
- [x] 15. Отсутствуют слова с буквой "ё", пытается заменить на "е": взад-вперёд.
- [x] 16. Замечание "Притяжательное прилагательное (местоимение) не согласуется с существительным по числу." реагирует на фразы "Два ваших товарища" "три огненных существа"
- [x] 17. Замечание "Запятая не нужна:"не то что"" реагирует на фразу Это не то, что ты думаешь."
- [x] 18. Замечание "Предлог «против» предполагает употребление прилагательного в родительном падеже:"против ." или "." Реагирует на фразу "Я выступаю против."
- [x] 19. Орфографическая ошибка в словах "...-то" "Это я-то?", "кои-то веков"
- [x] 20 Замечание "Он практикуется со своим клинком, ведь, чтобы отбиваться от убийц, он должен держать себя в форме." Без запятой замечание "Оборот с неопределенной формой глагола со всеми относящимися к ней словами" и ставит запятую. С запятой замечание "Слово не является вводным. Запятые не нужны". Сложноподчиненное предложение с придаточным предложением внутри главного.
- [x] 21 Замечание "Пропущена запятая: "Он говорит: ", Когда она позовёт"" Предложение: "Он говорит: "Когда она позовёт меня?"" Не разбирает знаков двоеточия, если поменять на дефис, то реагирует нормально.
- [x] 22. Замечание "Глагол подозревает с предлогом «о» не употребляется." Насколько мне известно, такого правила не существует. https://kartaslov.ru/%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F-%D1%81%D0%BE-%D1%81%D0%BB%D0%BE%D0%B2%D0%BE%D1%81%D0%BE%D1%87%D0%B5%D1%82%D0%B0%D0%BD%D0%B8%D0%B5%D0%BC/%D0%BD%D0%B5+%D0%BF%D0%BE%D0%B4%D0%BE%D0%B7%D1%80%D0%B5%D0%B2%D0%B0%D1%82%D1%8C+%D0%BE+%D0%BA%D0%BE%D0%BC-%D0%BB%D0%B8%D0%B1%D0%BE
- [x] 23. Замечание "Перед глаголом в неопределённой форме должен быть модальный глагол (хочет, будет, должен, может, ...)" реагирует на предложения "Должен ли я остаться здесь?" "Готовы ли вы отложить ваши глупые сомнения?"
- [x] 24. Замечание "Не найдены обязательные зависимые слова: нарушать что (чего)? реагирует на предложение "Это правило я никогда не нарушал."
- [x] 25. Замечание "Нужна запятая или тире: ", им" или " – им"" в предложении "Когда вы находитесь на нашей земле, вы должны подчиняться им, даже если вы служите другим."
- [x] 26. Орфографическая ошибка в "дай-ка", "дайте-ка", "давайте-ка", но "давай-ка" не реагирует http://www.bolshoyvopros.ru/questions/3059636-kak-pishetsja-slovo-daj-ka-dajka-ili-daj-ka-kakoe-znachenie.html
- [x] 27. Замечание "Причастие пишется с «нн», есть зависимые слова: " "" предложения "Раньше в этом регионе добывали большое количество ресурсов." "Вы больше не одиноки в комнате."
- [x] 28. "Предлог «к» предполагает употребление прилагательного в дательном падеже: "к такому" или "такого"" реагирует на фразу "к такого рода обещаниям"
- [x] 29. Замечание "«бежите» — ошибочное слово/фраза, исправление: "бегите"" должно работать только с повелительным наклонением. Не должен реагировать на фразу "Куда бежите? "
- [x] 30.  Замечание "Глагол должен быть в неопределённой форме: "оставить"" в предложении при отсутствии запятой  "Спрашивайте, что вам надо(,) и оставьте меня в покое", но в таких случаях должна быть запятая.
- [x] 31. Замечания, которые определяют правильность падежа, не реагируют несклоняемое слово: "леди"
- [x] 32. Замечание "Пропущена запятая: "Она день, и ночь караулила""  в предложении "Она день и ночь караулила нас.
- [x] 33. Замечание "Грамматическая ошибка в согласовании числа: "больших тени"" в словосочетании "Две больших тени."
- [x] 34. "Смертельно раненный" предлагает писать с одной "н", поскольку нет зависимых слов
- [ ] 35. Ошибка "Логическая ошибка: "сегодня"?"   в словосочетании "Сегодняшний день"
- [x] 36. Замечание "Глаголы – однородные члены предложения: "описывает что, происходит" или "описывает что и происходит"." Предложение "Он подробно описывает что происходит в данный момент." Данное замечание не должно распространяться на сложные предложения.
- [x] 37. Замечание "Требуется запятая до конца предложения" в словосочетании "Чтобы закончить раньше (если вы не хотите" просит поставить запятую, несмотря на скобку, также и с тире.
- [x] 38. Замечание "Запятая не нужна:"неизвестно кто"." реагирует на предложение "До сих пор неизвестно, кто организовал нападение."
- [x] 39. Замечание "Устойчивое выражение "более или менее"" заменяет "более-менее". Имеется такое словосочетание
- [x] 40. Слово "девченки", "девчёнки"  определяется без ошибок

**Comment by yakovru** [comment]
п. 7 "Сперва"
https://russkiiyazyk.ru/question/sperva-ili-snachala-kak-pravilno
Да, такое слово есть, но не рекомендуется к использованию.

**Comment by sergus2008** [comment]
> п. 7 "Сперва"
> https://russkiiyazyk.ru/question/sperva-ili-snachala-kak-pravilno
> Да, такое слово есть, но не рекомендуется к использованию.
Да, слово указывается в словарях как просторечное или разговорное, но оно нередко используется в обычной речи и деловой переписке. 
Я посмотрел, что ещё пишут про это слово, рекомендация на том сайте больше похожа на субъективное мнение автора статьи. 
В текстах, где я проверял, аналог "сначала" не подходил стилистически, как и остальные синонимы. 
Если не нравится это слово, можно мягко предлагать замену с пояснением, что слово является просторечным, и его применение в деловой переписке не рекомендуется. Но не стоит называть это ошибкой.

**Comment by yakovru** [comment]
По п. 8.1, это правило работает не всегда, например:
**С того времени, как** человек стал человеком, с того мгновения, когда он засмотрелся на красоту вечерней зари, он стал всматриваться в самого себя.
см.  https://gia.resobrnadzor.ru/wp-content/uploads/2019/12/%D0%9E%D0%93%D0%AD_%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9-%D1%8F%D0%B7%D1%8B%D0%BA_-9_%D0%91%D0%B0%D0%BD%D0%BA-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B9_2020.pdf

**Comment by sergus2008** [comment]
> По п. 8.1, это правило работает не всегда, например:
> **С того времени, как** человек стал человеком, с того мгновения, когда он засмотрелся на красоту вечерней зари, он стал всматриваться в самого себя.
> см. https://gia.resobrnadzor.ru/wp-content/uploads/2019/12/%D0%9E%D0%93%D0%AD_%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9-%D1%8F%D0%B7%D1%8B%D0%BA_-9_%D0%91%D0%B0%D0%BD%D0%BA-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B9_2020.pdf

Какой-то сомнительный момент. Я бы здесь не стал ставить запятую. Больше похоже на авторскую постановку запятой для эмоциональной окраски, хоть и диктант. Фактически есть такое правило, и оно легко гуглится.

**Comment by yakovru** [comment]
p.1 и p.1 Персональный словарь в расширении для firefox реализован локально, данные на сервер не передаются. Поэтому и невозможно сгенерировать предложения при проверке орфографии или задать принадлежность слова к частям речи.
Но это возможно сделать на серверной части, если при работе расширения использовать локальный LanguageTool сервер.  Для серверной части файлы находятся в каталоге resource/ru/added_custom.txt и added.txt для словаря частей речи;  resource/ru/hunspell/spelling.txt - для орфографической проверки.
(https://github.com/languagetool-org/languagetool/issues/3562  - аналогичное предложение)
Кроме того, после обновления сайта LanguageTool во встроенном редакторе появилась возможность создавать пользовательский словарь,  слова из которого используются для формирования предложений коррекции. 

p.10 - Это рекомендуемое правило, возможна авторская пунктуация.

p.35 Слово "Сегодняшний" уже подразумевает "день", поэтому словосочетание "Сегодняшний день" избыточно,  лучше написать "сегодня".

**Comment by sergus2008** [comment]
> p.1 и p.1 Персональный словарь в расширении для firefox реализован локально, данные на сервер не передаются. Поэтому и невозможно сгенерировать предложения при проверке орфографии или задать принадлежность слова к частям речи.
> Но это возможно сделать на серверной части, если при работе расширения использовать локальный LanguageTool сервер. Для серверной части файлы находятся в каталоге resource/ru/added_custom.txt и added.txt для словаря частей речи; resource/ru/hunspell/spelling.txt - для орфографической проверки.
> (#3562 - аналогичное предложение)
> Кроме того, после обновления сайта LanguageTool во встроенном редакторе появилась возможность создавать пользовательский словарь, слова из которого используются для формирования предложений коррекции.

Здесь (первый p.1) имелась в виду возможность пользователю самому указывать для каждого слова в словаре род, число, может ещё, что-то, ведь для части правил, насколько я знаю, указан код, работающий в зависимости от этих факторов. Предложение конечно не конкретно для русскоязычной версии конкретно, но функционал рассмотреть можно. Я пользуюсь им в свободное время при проверке худ. литературы после перевода, поэтому встречаются такие слова, которые в общем словаре ни к чему. Может, для таких слов создавать словарь или что-то еще.
По второму вопросу (второй p/1) слова во временном словаре где-то хранятся, почему бы в перечень исходных фалов для поиска файлов не внести этот временный словарь.
Правильнее, конечно, внести предложения не по конкретно какому-то языку, а по самому функционалу программы, но у меня с иностранным не очень хорошо для формулирования текста.

 
> p.10 - Это рекомендуемое правило, возможна авторская пунктуация.

Здесь, как и в п. 8.1, может быть, конечно, возможна авторская пунктуация, но в первую очередь программа разрабатывается для определения и исключения ошибок в тексте, написанном пользователем программы. А эти правила можно сделать рекомендуемыми. Если нужно писать какое-то письмо, или другой официальный документ, не должно быть авторской постановки знаков препинания.

> p.35 Слово "Сегодняшний" уже подразумевает "день", поэтому словосочетание "Сегодняшний день" избыточно, лучше написать "сегодня".

Подразумевает, но слово "сегодняшний" в одиночку использовать нельзя в тексте без существительного. Сегодняшним может быть также и хлеб. Сочетание в данном случае может быть неприемлемо только если есть претензия к самому слову "сегодняшний". Тогда правило стоит изменить. Написать, что слово "сегодняшний" колхозное и не стоит использовать. Но я всё-таки считаю, что должна быть возможность без проблем писать про вчерашний, сегодняшний и завтрашний день, поскольку не противоречит никаким правилам и широко употребляется.
