### ISSUE TITLE
[en] tagging for "ain't"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2446]
https://www.merriam-webster.com/dictionary/ain't

It's currently tagged as NN and JJ. I think it should be tagged like "aren't" or "isn't", even if it is informal. @MikeUnwalla what do you think?

**Comment by MikeUnwalla** [comment]
@tiff, 

> I think it should be tagged like "aren't"

I agree.

As best I can tell, ain/JJ is wrong. Ain/NN is possible (as a variant of 'ayin'), but I have not seen it before looking at https://www.collinsdictionary.com/dictionary/english/ain.

We don't have Scottish English in LT, so ain/DT is out of scope.

I'll leave the changes to you.

**Comment by tiff** [comment]
I will take care. https://www.lexico.com/definition/ain't says it is not only "are not" but also "am not" and "is not".
