### ISSUE TITLE
[ar] في

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2449]
Feedback from a user:

> When writing "في" this error appears:
> انتبه لحرف الجر فالمثنى يجر بالياء ""؟ 
> But this error appears every time "في" is written, so it also appears when there's no mistakes in the sentence.

cc @sohaibafifi

**Comment by sohaibafifi** [comment]
@linuxscout can you please check this issue ?

**Comment by KathKal** [comment]
This doesn't seem to be reproducible; at least not in 5.6.
I tried the following (even the wrong grammar is not detected):
في المدرستين طلاب كثر.
رأيته في المكانين.
أتراه في أي من البنايتين؟ أتراه في أي من البنايتان؟
@sohaibafifi [sohaibafifi](https://github.com/sohaibafifi) did you reproduce this?

**Comment by linuxscout** [comment]
fixed.
@danielnaber  please close it.
