### ISSUE TITLE
[de] "Formart"?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2451]
Wenn jemand "Format" falsch schreibt, dann passiert Folgendes:
> Formart

<img width="359" alt="Bildschirmfoto 2020-02-12 um 13 52 45" src="https://user-images.githubusercontent.com/37363/74336662-03604100-4d9f-11ea-9ff4-4dc16c373be3.png">

Es scheint, als wäre das Wort in unserem Wörterbuch?

**Comment by danielnaber** [comment]
Vermutlich Kompositum aus Form + Art. Ich schließe es mal aus.

**Comment by danielnaber** [comment]
Ausschluss via `prohibit.txt` nutzt leider nichts, weil die Agreement-Rule höhere Prio hat als die Spellcheck-Rule...
