### ISSUE TITLE
[de] broken suggestion DE_AGREEMENT

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2452]
@danielnaber 
> Wir gehen ins Fitness Studio

<img width="441" alt="Bildschirmfoto 2020-02-12 um 13 59 29" src="https://user-images.githubusercontent.com/37363/74337088-f1cb6900-4d9f-11ea-9d47-d89ff25ce7d2.png">

Vorschlag sollte "ins Fitnessstudio" sein, nicht "das"

**Comment by danielnaber** [comment]
Should be fixed.
