### ISSUE TITLE
[en] false alarms AUXILIARY_DO_WITH_INCORRECT_VERB_FORM

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2458]
> I just did courses that we discussed.
> You could do so using the Nexmo API.

<img width="488" alt="Bildschirmfoto 2020-02-12 um 16 11 28" src="https://user-images.githubusercontent.com/37363/74348076-6c9d7f80-4db2-11ea-84c2-4b08d644eb5d.png">

**Comment by MikeUnwalla** [comment]
DID_BASEFORM:
> I just did courses that we discussed.
