### ISSUE TITLE
[fr] Bad elision suggestion

### ISSUE THREAD

**Issue by fgm** [languagetool-org/languagetool#2465]
It suggests elision of “de haut” as “d’haut” which is wrong because the “h” is not silent in this specific case

**Comment by tiff** [comment]
cc @vkyfox

**Comment by vkyfox** [comment]
Couldn't replicate the error. I double-checked the xml but "haut" is correctly listed as an exception to the rule. Could you give more details as to how you encountered this error?

**Comment by fgm** [comment]
Here it is. This is  in a LaTeX file.

<img width="623" alt="Capture d'écran 2020-02-14 15 21 48" src="https://user-images.githubusercontent.com/143311/74539102-bff00900-4f3d-11ea-9800-60998e6e5705.png">

**Comment by tiff** [comment]
Which version of LT is this?

**Comment by fgm** [comment]
The one used in JetBrains GoLand 2020 as "Grazie".

**Comment by danielnaber** [comment]
I can confirm it's fixed in current LT. Could you ask JetBrains for an update?

**Comment by fgm** [comment]
Done: I gave the info to @zolotov

**Comment by tiff** [comment]
I'm closing this
