### ISSUE TITLE
[en] Wrong tagging DT_JJ_NN_JJ and DT_JJ_VB_NN

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#2469]
Noted after fixing #2462:

> ... that she brought to the **work make** her the master worker of the genre.

work/JJ and make/NN:U

**Comment by tiff** [comment]
Probably related: https://github.com/languagetool-org/languagetool/issues/2427

**Comment by MikeUnwalla** [comment]
@tiff , thanks. I'll look at #2427 another day.
