### ISSUE TITLE
Online Editor Bug?

### ISSUE THREAD

**Issue by ArronWilliams** [languagetool-org/languagetool#2471]
The expert mode of the online editor isn't working, at least for me. I receive this message, even with the example text or rules that should have no errors.

"Sorry, an error occurred trying to check your rule: No signature of method: org.languagetool.JLanguageTool.checkAnalyzedSentence() is applicable for argument types: (org.languagetool.JLanguageTool$ParagraphHandling, java.util.ArrayList, org.languagetool.AnalyzedSentence) values: [NORMAL, [CONFUSION_OF_BED_BAD_some_string_not_in_any_other_rule_1234[1]@:[bed, English]:confusion of bed/bad], ...] Possible solutions: checkAnalyzedSentence(org.languagetool.JLanguageTool$ParagraphHandling, java.util.List, org.languagetool.AnalyzedSentence, boolean)"

**Comment by danielnaber** [comment]
Probably fixed by https://github.com/languagetool-org/languagetool/commit/c20b6ffcd5ab9213742f84babd916f8957eb6d36

**Comment by ArronWilliams** [comment]
It's fixed now
