### ISSUE TITLE
bad report for spaces around quote

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#2476]
When you have a ' with a space on both sides, like this one, on the web interface there is a bug (object/Object reported), and in the add-in deletion of the ' is reported, instead of quote with space before or space after.

**Comment by mark-baas** [comment]
<img width="349" alt="Screenshot 2023-04-14 at 09 04 40" src="https://user-images.githubusercontent.com/126452841/231923253-974d4e58-7ce0-4450-9735-c3c0af5933a4.png">
Tested on web interface, seems to be resolved.
