### ISSUE TITLE
[en] Detecting sentences that should start with an uppercase letter.

### ISSUE THREAD

**Issue by hiddenspirit** [languagetool-org/languagetool#248]
LanguageTool doesn't find any errors in this example:
The next sentence is not OK. this sentence should start with an uppercase letter.

It seems to fail if the last word from the previous sentence is 2-characters long or shorter.

Tested with LanguageTool 2.9.

**Comment by milekpl** [comment]
It's not a bug, it's a feature. I will add "OK" as an exception but it's designed to catch nonstandard abbreviations.

**Comment by hiddenspirit** [comment]
In that case, you might want to add other two letter words like "me", "us", "is", "am", "it", "be", "do", "at", "of"...
