### ISSUE TITLE
bullet list issue on Google Docs

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#2480]
![afbeelding](https://user-images.githubusercontent.com/8479998/74712933-cd501080-5227-11ea-9b28-ba846655c555.png)
When the dash is at the start of the line, the first word is reported as a spelling error (internally seen as -word); when there is a space before it, it is not.
This does not happen for English, so it could be related to the code that was added to allow for optional dashes in a Dutch word, which is in the disambiguation java code

**Comment by danielnaber** [comment]
That's a real bullet list using dashes, not just dash characters, isn't it? Could you create a document to reproduce it and paste the link here?
