### ISSUE TITLE
Page change bug on Google Docs

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#2482]
When a flowing sentence is broken by a soft page break, this page break is interpreted as a sentence ending, which is incorrect. A Dutch rule signals unexpected sentence end then.
![afbeelding](https://user-images.githubusercontent.com/8479998/74717548-e14c4000-5230-11ea-8729-1db1d9a816f9.png)

**Comment by danielnaber** [comment]
Please provide a link to a document, this will make debugging much easier.
