### ISSUE TITLE
Google Docs page index table error

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#2483]
The whitespace between word and page number is ignored:
![afbeelding](https://user-images.githubusercontent.com/8479998/74718562-c37fda80-5232-11ea-81a9-421bc484fd61.png)

**Comment by danielnaber** [comment]
Please provide a link to a document.

**Comment by baarsrj** [comment]
It looks like very formatting code of an imported ODT (converted from docx) that has soft line of page transitions or tabs (maybe any formatting code) cause issues.
![afbeelding](https://user-images.githubusercontent.com/8479998/74719382-33db2b80-5234-11ea-9a46-0d9c60af3fbd.png)

**Comment by tiff** [comment]
Hi @baarsrj it would be nice to have access to the doc or a similar doc. You can also send it to me via Slack

**Comment by tiff** [comment]
Should be fixed in v3.1.1 of the Firefox Add-on
