### ISSUE TITLE
Italian false alarm

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2489]
User feedback:

--> La tesi dell'autore (correct form)
 
Then it will ask you like:
--> Al tesi dell'autore (wrong form)

**Comment by frigi83** [comment]
The user feedback is right.

**Comment by danielnaber** [comment]
There's not much happening for the Italian support in LT, so pull requests are welcome. We have an overview for manual rule development at http://wiki.languagetool.org/development-overview.

**Comment by frigi83** [comment]
Before I make a pull request I want to try to understand if it's ok. This rule is too specific, or it should be more generalist? (In the meantime I test the LanguageTool extension and how it works)

```xml
<!-- Italian rule, 2020-05-21 -->
<rule id="LA_VS_AL" name="la vs al">
 <pattern>
  <token>Al</token>
  <token>tesi</token>
 </pattern>
 <message>Forse volevi dire "la" tesi?</message>
 <example correction=''><marker>Al tesi</marker> dell'autore</example>
 <example>La tesi dell'autore</example>
</rule>
```

**Comment by danielnaber** [comment]
Although I don't speak Italian, the rule seems too specific indeed. You might want to extend it to all female nouns. You can use https://community.languagetool.org/analysis/index?lang=it to see how "Al tesi" is internally analyzed, i.e. which tags are assigned to "tesi" (`NOUN-F:s` seems to be the relevant part-of-speech tag here, I guess).

**Comment by frigi83** [comment]
It seems that there is already a rule that cover the case ("Al tesi" => "La tesi"). But after the correction there is a suggestion to go back.

How can I see which cover the currently suggestion?

**Comment by danielnaber** [comment]
You can see the matching rule here on languagetool.org:

![screenshot-2020-05-22-09:06](https://user-images.githubusercontent.com/857004/82641160-30c55200-9c0c-11ea-87ea-39116df55984.png)

![screenshot-2020-05-22-09:07](https://user-images.githubusercontent.com/857004/82641181-3753c980-9c0c-11ea-9816-6061b46a1186.png)

In this case, it's https://community.languagetool.org/rule/show/ER_02_002?subId=2&lang=it

**Comment by jaumeortola** [comment]
The problem with "la tesi" is that "tesi" can be "noun feminine", but also "adjective masculine plural". "Noun feminine" is missing in the exceptions to the rule `"la" + aggettivo maschile`. 

You can analyze text here: https://community.languagetool.org/analysis/analyzeText

![imatge](https://user-images.githubusercontent.com/4289501/82649915-34f86c00-9c1a-11ea-8318-2beaa52c8646.png)

**Comment by paolob67** [comment]
This rule was introduced by some contributors because it helps train young student with disabilities that tend to invert letters when typing.

The more generalist rule that checks gender matching for articles is already there.

Paolo

**Comment by jaumeortola** [comment]
I fixed the false alarm, which was unquestionably necessary. You can see how it is done here, @frigi83: https://github.com/languagetool-org/languagetool/commit/f9b6a72e0f381b0178d69eb5ee3b049fbf3e788b
