### ISSUE TITLE
Did you mean sneak peek?

### ISSUE THREAD

**Issue by Mailaender** [languagetool-org/languagetool#249]
A mistake probably often done by Germans (like me) `sneak peak` is spelled `sneak peek` instead. See https://github.com/OpenRA/OpenRAWeb/pull/203#discussion_r28026581 Ordinary spell check can't detect it as `peak` is also a valid word.

**Comment by danielnaber** [comment]
Why don't you just write that rule, shouldn't be much more difficult than writing this bug report :-)

**Comment by Mailaender** [comment]
This is just a quick reminder for myself.

**Comment by Mailaender** [comment]
Also seems to be a common typo for North Americans http://theoatmeal.com/comics/sneak_peek

**Comment by danielnaber** [comment]
The peek/peak error is actually detected now on languagetool.org, where we use the ngram data (http://wiki.languagetool.org/finding-errors-using-big-data).

**Comment by danielnaber** [comment]
Actually there's already a rule `SNEAK_PEAK` which detects this, so I'm closing this issue.
