### ISSUE TITLE
[pt] Some errors are no longer underlined

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#2514]
Hello!

Since the 13th or so that some errors in Portuguese are no longer underlined.

This makes it difficult for me to improve/add rules.

In this sample file, the highlighted words were supposed to trigger errors.

But, see the 4th and 3rd sentence from the bottom of the document: the word "software" doesn't trigger the rule that it is a foreign word and thus should be in italic.

Also, if I select to recheck the grammar it opens a blank window (latest nightly it still happens).

[Missing words 20200213.zip](https://github.com/languagetool-org/languagetool/files/4259441/Missing.words.20200213.zip)

**Comment by danielnaber** [comment]
Could you add the rule ids to the document that are supposed to match?

**Comment by marcoagpinto** [comment]
@danielnaber 

Variamos os argumentos caso estes **representam** resultados fracos.

Variamos os argumentos caso estes **apresentam** resultados fracos.

Variamos os argumentos caso estes **mostram** resultados fracos.

Variamos os argumentos caso estes **facilitam** resultados fracos.


`  <rulegroup id='GENERAL_VERB_AGREEMENT_ERRORS' name="Concordância Verbal: Geral">`



```

<!-- MARCOAGPINTO 2020-02-16 *START* -->
<!-- "Variamos os argumentos caso estes representem resultados fracos." -->
    <rule>
      <pattern>
          <token postag='CS' postag_regexp='no'/>
		  <token postag='PD0MP000' postag_regexp='no'/>
		  <marker>
			<token regexp='yes'>representam|apresentam|mostram|facilitam</token> <!-- MARCOAGPINTO workaround 2020-02-18 -->
<!-- MORPHOLOGIC DICTIONARY IS ALL MESSED UP
			<token postag='VMIP3P0' postag_regexp='no'/>
MARCOAGPINTO 2020-02-18 -->
		  </marker>
      </pattern>
      <message>&MSG_ECV;</message>
        <suggestion><match no='3' postag='VMSP3P0' postag_replace='VMIP3P0' postag_regexp='no'/></suggestion>
      <example correction='representem'>Variamos os argumentos caso estes <marker>representam</marker> resultados fracos.</example>
      <example>Variamos os argumentos caso estes representem resultados fracos.</example>
    </rule>
<!-- MARCOAGPINTO 2020-02-16 *END* -->  

```

**Comment by marcoagpinto** [comment]
It works with the browser (Firefox) add-on.

**Comment by FredKruse** [comment]
Hello,
the problem isn't solved by the last update. I'm working on this. Please disable "check text level rules parallel" in the option panel meanwhile.

**Comment by marcoagpinto** [comment]
Thanks.

**Comment by FredKruse** [comment]
@marcoagpinto please test, if the new release solves this issue

**Comment by marcoagpinto** [comment]
I will test it with tonight's nightly.

So, tomorrow morning we will know.

Thanks!

**Comment by marcoagpinto** [comment]
@FredKruse 

The underlining seems to be fixed.

Thank you for your work!

**Comment by marcoagpinto** [comment]
@FredKruse 

The issue happened again with the latest nightly.

So, it is not 100% fixed.

**Comment by FredKruse** [comment]
@marcoagpinto: Could you please test with the latest nightly.
If the issue happened again, please give me an example.
If not, please close the issue.

**Comment by marcoagpinto** [comment]
@FredKruse 

Yesterday I checked the commits and noticed there were at least three from you.

Not sure if all of them were in time for the nightly build, so it is safer for me to test tomorrow just to play safe.

**Comment by marcoagpinto** [comment]
@FredKruse 
I opened the document in which the issue happened and it didn't seem to happen in my tests any more.

It seems to be fixed.

Thanks!
