### ISSUE TITLE
LT does not recognize double exclamation mark

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#252]
In English, the double exclamation mark (www.w3schools.com/charsets/ref_utf_punctuation.asp) is not recognized by LT as punctuation. Instead, LT gives a 'possible spelling mistake' error message.

![double-punctuation-mark](https://cloud.githubusercontent.com/assets/5816160/7106628/a1676cce-e13f-11e4-9366-62c54f0a11a8.png)

**Comment by danielnaber** [comment]
Thanks for the report. This should be fixed now, I've added these unicode characters:

    ‼ ⁇ ⁈ ⁉
