### ISSUE TITLE
list of irregular verbs

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#253]
Is it possible to create a list of irregular verbs for each language?

For example: Portuguese and English have irregular verbs and it would be nice if we could make a list of them and have an option on LT to access them.

**Comment by baarsrj** [comment]
What is the background if this request? Irregular verbs can be postagged already?

Verzonden van smartphone.

"Marco A.G.Pinto" <notifications@github.com>schreef:

Is it possible to create a list of irregular verbs for each language?
For example: Portuguese and English have irregular verbs and it would be nice if we could make a list of them and have an option on LT to access them.

**Comment by marcoagpinto** [comment]
The idea is simple:

At school, the English teachers would give the students papers with the 
list of the irregular verbs.

It would be great if we could access a document with them and all the forms.

It would be useful too for other languages such as Portuguese, so that 
people would know how to use the verbal forms (conjugations).


On 15/04/2015 19:47, R. Baars wrote:
> What is the background if this request? Irregular verbs can be 
> postagged already?
>
> Verzonden van smartphone.
>
> "Marco A.G.Pinto" <notifications@github.com>schreef:
>
> Is it possible to create a list of irregular verbs for each language?
> For example: Portuguese and English have irregular verbs and it would 
> be nice if we could make a list of them and have an option on LT to 
> access them.
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/languagetool-org/languagetool/issues/253#issuecomment-93529663>.
>


--

**Comment by baarsrj** [comment]
Verbix might help?

**Comment by marcoagpinto** [comment]
But, why can't it be built into LT?

On 15/04/2015 20:05, R. Baars wrote:
> Verbix might help?
>
> > The idea is simple:
> >
> > At school, the English teachers would give the students papers with the
> > list of the irregular verbs.
> >
> > It would be great if we could access a document with them and all the
> > forms.
> >
> > It would be useful too for other languages such as Portuguese, so that
> > people would know how to use the verbal forms (conjugations).
> >
> >
> > On 15/04/2015 19:47, R. Baars wrote:
> >> What is the background if this request? Irregular verbs can be
> >> postagged already?
> >>
> >> Verzonden van smartphone.
> >>
> >> "Marco A.G.Pinto" <notifications@github.com>schreef:
> >>
> >> Is it possible to create a list of irregular verbs for each language?
> >> For example: Portuguese and English have irregular verbs and it would
> >> be nice if we could make a list of them and have an option on LT to
> >> access them.
> >> —
> >> Reply to this email directly or view it on GitHub.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> 
> <https://github.com/languagetool-org/languagetool/issues/253#issuecomment-93529663>.
> >>
> >
> >
> > --
> >
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > 
> https://github.com/languagetool-org/languagetool/issues/253#issuecomment-93533361
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/languagetool-org/languagetool/issues/253#issuecomment-93534589>.
>


--

**Comment by baarsrj** [comment]
I am not saying it cannot. Just wondering why it should. There is no
relations to grammar errors, or is there?

Ruud

**Comment by marcoagpinto** [comment]
Because it is a language tool... an aid to help write documents.

Anyway, I was taking this idea from the Portuguese commercial add-on for 
M$ Office: FLIP: http://www.flip.pt

If they have a commercial add-on with such a feature, why can't our free 
one have it too?


On 15/04/2015 20:47, R. Baars wrote:
>
> I am not saying it cannot. Just wondering why it should. There is no
> relations to grammar errors, or is there?
>
> Ruud
>
> > But, why can't it be built into LT?
> >
> > On 15/04/2015 20:05, R. Baars wrote:
> >> Verbix might help?
> >>
> >> > The idea is simple:
> >> >
> >> > At school, the English teachers would give the students papers with
> >> the
> >> > list of the irregular verbs.
> >> >
> >> > It would be great if we could access a document with them and all the
> >> > forms.
> >> >
> >> > It would be useful too for other languages such as Portuguese, so 
> that
> >> > people would know how to use the verbal forms (conjugations).
> >> >
> >> >
> >> > On 15/04/2015 19:47, R. Baars wrote:
> >> >> What is the background if this request? Irregular verbs can be
> >> >> postagged already?
> >> >>
> >> >> Verzonden van smartphone.
> >> >>
> >> >> "Marco A.G.Pinto" <notifications@github.com>schreef:
> >> >>
> >> >> Is it possible to create a list of irregular verbs for each 
> language?
> >> >> For example: Portuguese and English have irregular verbs and it 
> would
> >> >> be nice if we could make a list of them and have an option on LT to
> >> >> access them.
> >> >> —
> >> >> Reply to this email directly or view it on GitHub.
> >> >>
> >> >> —
> >> >> Reply to this email directly or view it on GitHub
> >> >>
> >> 
> <https://github.com/languagetool-org/languagetool/issues/253#issuecomment-93529663>.
> >> >>
> >> >
> >> >
> >> > --
> >> >
> >> >
> >> > ---
> >> > Reply to this email directly or view it on GitHub:
> >> >
> >> 
> https://github.com/languagetool-org/languagetool/issues/253#issuecomment-93533361
> >>
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> 
> <https://github.com/languagetool-org/languagetool/issues/253#issuecomment-93534589>.
> >>
> >
> >
> > --
> >
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > 
> https://github.com/languagetool-org/languagetool/issues/253#issuecomment-93536092
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/languagetool-org/languagetool/issues/253#issuecomment-93545340>.
>


--

**Comment by danielnaber** [comment]
I don't see how this should be integrated into LT - if a verb is used incorrectly, LT should detect that. If it's used correctly, LT doesn't display anything at all.
