### ISSUE TITLE
Disambiguator adding new postag

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#2532]
I was trying add a postag to multiple words in just one rule. There is no error doing that, but it does not seem to work either. Example:
```
<pattern><token>foo</token><token>bar</token></pattern>
<disambig action="add" ><wd pos="TEST"/></disambig>
```

**Comment by MikeUnwalla** [comment]
Hi @baarsrj , each word in the pattern must have an action. Try this:

`<disambig action="add" ><wd pos="TEST"/><wd pos="TEST"/></disambig>`

**Comment by baarsrj** [comment]
I will. But it is strange there is no warning.

**Comment by baarsrj** [comment]
I tested it, but it did not function.  So to add a flag to a group of words, one needs a disambig rule per word. Unfortunate. But it is the way it is.
