### ISSUE TITLE
[DE] "Geldscheinen", der Plural von "Geldschein"

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#2533]
Moin liebes LanguageTool-Team

Das ist aber merkwürdig, denn auf fast **allen Geldscheinen** sind ihre Fingerabdrücke.
**LT-Fehlermeldung:** "Möglicherweise fehlende grammatische Übereinstimmung des Kasus (Fall: Wer/Was, Wessen, Wem, Wen/Was - Beispiel: 'das Fahrrads' statt 'des Fahrrads') und Numerus (Einzahl, Mehrzahl - Beispiel: 'das Fahrräder' statt 'die Fahrräder')."

Grund sind die Token, die für die Pruralform von "Geldschein" komplett fehlen. Das Gleiche gilt auch für "Euroschein".
![grafik](https://user-images.githubusercontent.com/40240507/75618784-56920c00-5b73-11ea-8c72-b80486638182.png)

Sollen "Euroscheine(n)" und "Geldscheine(n)" in die Added.txt aufgenommen werden? Oder soll das anders gelöst werden? Schließlich sind "Geldscheine/Euroscheine" zusammgesetzte Wörter aus "Geld/Euro" und "Schein".

Grüße Dallun511

**Comment by danielnaber** [comment]
Es reicht, die Pluralformen von "Scheinen" und "Scheine" aufzunehmen, die Zerlegung Euro+scheinen geht nämlich schon.

**Comment by Dallun511** [comment]
#2535 Habe was angelegt und es hilft auch.
Grüße Dallun511

**Comment by Dallun511** [comment]
Das Problem ist auch in der Online-Version behoben
