### ISSUE TITLE
[en] false alarm TO_NON_BASE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2536]
> Can you confirm this only happens to reports when referenced in a book?

<img width="615" alt="Bildschirmfoto 2020-03-02 um 08 14 45" src="https://user-images.githubusercontent.com/37363/75653439-e4e2bc80-5c5d-11ea-8661-a6ad6ce1a1e2.png">

A few more:
> If you don't like the font you can change it back to Times New Roman. 

> Until we agree to rules we cannot give up the tools by which we protect our national interest.

> Please change it from doing to done here

> Apply To Labels

> He sent an invite to networking events

> Marketing to Kids Gets More Savvy with New Technologies.

> And the project he was introduced to was the best

> 13 Questions You Must Ask Prior To Choosing a Karate School

**Comment by MikeUnwalla** [comment]
- [ ] Can you confirm this only happens to reports when referenced in a book?
- [ ] If you don't like the font you can change it back to Times New Roman.
- [ ] Until we agree to rules we cannot give up the tools by which we protect our national interest.
- [ ] Please change it from doing to done here
- [ ] Apply To Labels
- [ ] He sent an invite to networking events
- [ ] Marketing to Kids Gets More Savvy with New Technologies.
- [ ] And the project he was introduced to was the best
- [ ] 13 Questions You Must Ask Prior To Choosing a Karate School
