### ISSUE TITLE
cross-paragraph rules don't always work with command-line version

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#254]
The error in this text (`Delfin` vs. `Delphin`) does not get detected when `Main.runOnFileLineByLine()` is used, but it works with `runOnFileInOneGo()`:

    Ein Test mit Delphin.

    Ein anderer Absatz.

    Hier noch ein Delfin.

~~Part of the problem is that `JLanguageTool.getAllActiveRules()` calls `rule.reset()`, which isn't clean anyway.~~

Also see this thread: http://www.mail-archive.com/languagetool-devel@lists.sourceforge.net/msg04839.html

**Comment by danielnaber** [comment]
Another issue caused by the different modes: http://forum.languagetool.org/t/wrong-fromx-and-tox-positions/738

**Comment by arysin** [comment]
Just a note that some change around this has made checking large files via
command-line very slow. At least for Ukrainian.
The file I have with ~610000 sentences that was taking ~6 min to check
before with latest code takes now more than an hour (and it's still not
finished). It's not about swapping as it uses only ~5G out of 24G I have.


2016-02-20 6:43 GMT-05:00 Daniel Naber <notifications@github.com>:

**Comment by danielnaber** [comment]
Marcin has already added a `--line-by-line` switch to re-activate the old behavior.
