### ISSUE TITLE
[en] false alarm MUCH_COUNTABLE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2541]
<img width="509" alt="Bildschirmfoto 2020-03-03 um 12 59 14" src="https://user-images.githubusercontent.com/37363/75773753-cdcfc780-5d4e-11ea-86cc-c0bb5ae80bd3.png">

> Drinking too much makes us dizzy.

> See how much muffins usually cost.

> Then he pretty much escapes that prison

> Whether measured as how much citizens worry about climate change or whether climate change poses a threat to them or their way of life.

> The supply of a good or service is how much producers are willing to make at a given price.

> Everyone can understand how much humans love themselves

**Comment by MikeUnwalla** [comment]
@tiff , this sentence triggers an error:

> Whether measured as how much citizens worry about climate change or whether climate change poses a threat to them or their way of life.

Possibly, the error message is a false warning, possibly it is correct.
