### ISSUE TITLE
Disambiguation combination bugs (?)

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#2543]
Martin is a first as well as a last name, and is tagged as such. ENM:PER:FST and ENM:PER:LST:
When I use disambiguation to add the more general flag for 'part of name', matching these tags with 'ENM:PER.*', the results in the disambig log contain Martin/NAME_PART twice. 
I think the root-flex-tag combinations should be kept unique. (Bug 1...)

The antipatterns used in the grammar file rule matching this NAME_PART tag does not see this tag when it is there twice: Bug 2

When I add an exception to the disambiguation rule that prevents the creation of the double postag, the NAME_PART is correctly matched in the antipattern rule. So there is a (partial) workaround.

By the way... only an exception prevents adding the double postag. An antipattern in the disambiguator does not prevent it. Which is also weird. Bug 3?

**Comment by danielnaber** [comment]
Please add your disambiguation rules here to make it easier to reproduce the issue.

**Comment by baarsrj** [comment]
I just added 2 rules to demonstrate the issue of creation of double tags by the disambiguator add rule. The rules are at the very end of the Dutch disambiguation file. Only word affected is the non-Dutch word testing.

**Comment by danielnaber** [comment]
I can reproduce "bug 1", could you add a rule (`default=off`) to reproduce "bug 2"?

**Comment by baarsrj** [comment]
I could not reproduce bug two. Nor bug 1 by the way. Did you change something?
