### ISSUE TITLE
[en] incorrect disambiguation was_is_VB_NN

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2544]
> He has been talk to me.
> He was talk to me.
> He is talk to me.

"talk" is only "NN:UN". Therefore, the error is not found.

**Comment by tiff** [comment]
Also:
> I am believe you.

**Comment by MikeUnwalla** [comment]
Also:
> He actually has been talk to the manager.

**Comment by MikeUnwalla** [comment]
Won't fix here, not a disambigation error:

> I am believe you.

Refer to #2547.

**Comment by MikeUnwalla** [comment]
Also need to fix E_NP_NN_VBP after the corrections in was_is_VB_NN.
