### ISSUE TITLE
[en] Testrules does not find an incorrect rule

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#2548]
This is my test rule:

```
<rule id="TEST" name="test">
    <pattern>
        <token case_sensitive="yes">I</token>
        <token>am</token>
        <marker>
            <token>happy</token>
        </marker>
    </pattern>
    <message>My marker test</message>
    <example type="incorrect">I <marker>am sad</marker>.</example>
</rule>
```
This is the testrules result:
![image](https://user-images.githubusercontent.com/5816160/75881182-7c8b0b00-5e16-11ea-8d74-72631d4d71ce.png)

I am now going to re-boot and then try testruls again.

**Comment by MikeUnwalla** [comment]
I re-booted the computer. Testrules does not find the incorrect rule.

**Comment by danielnaber** [comment]
We could reproduce, Fabian will work on a fix (only testrules.sh is affected, that's why we didn't notice it when running in IntelliJ).

**Comment by fabrichter** [comment]
I made a change so that we'll be able to see failures from multiple rules in a single run; that change didn't play well with the way you run the tests, but it should be fixed by my PR.
