### ISSUE TITLE
LT doesn't work when Authenticator.setDefault() is forbidden

### ISSUE THREAD

**Issue by seahrh** [languagetool-org/languagetool#255]
I'm trying to incorporate languagetool in a Google App Engine application. Their sandbox doesn't allow write access to the file system.

I get the following stacktrace:

`[INFO] Caused by: java.security.AccessControlException: access denied ("java.net.NetPermission" "setDefaultAuthenticator")
[INFO] at java.security.AccessControlContext.checkPermission(AccessControlConte
xt.java:372)
[INFO] at java.security.AccessController.checkPermission(AccessController.java:559)
[INFO] at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
[INFO] at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:429)
[INFO] at java.net.Authenticator.setDefault(Authenticator.java:127)
[INFO] at org.languagetool.tagging.disambiguation.rules.DisambiguationRuleLoader.getRules(DisambiguationRuleLoader.java:59)
[INFO] at org.languagetool.tagging.disambiguation.rules.XmlRuleDisambiguator.loadPatternRules(XmlRuleDisambiguator.java:78)
[INFO] at org.languagetool.tagging.disambiguation.rules.XmlRuleDisambiguator.disambiguate(XmlRuleDisambiguator.java:59)`

Similar exception occurs for both JLanguage 2.8 and 2.9.

Not sure if this is related to issue https://github.com/languagetool-org/languagetool/issues/112

I don't know much about the loading process, but would it be possible to allow this (optionally) in memory ? If there is an easy workaround for this that I could use with GAE, please let me know.

**Comment by danielnaber** [comment]
This is not related to the file system. It seems `Authenticator.setDefault(new PasswordAuthenticator())` in our class `DisambiguationRuleLoader` is forbidden.

**Comment by wolpers** [comment]
Other places where the default authenticator is set are PatternRuleLoader.java and XMLValidator.java 

The call to java.net.Authenticator.setDefault(anything) is causing a problem for me, too.  I am attempting to write a NetBeans plugin and include LanguageTool as a library.  Things work quite well so far, except that the applied Authenticator breaks things within the NetBeans platform's Git support.  Generally speaking, this could happen with any application where LanguageTool is included as a library.

**Comment by danielnaber** [comment]
This should now be fixed. We simply don't call the method anymore if it's not allowed. This way we lose a rather exotic feature (passwords for external rule files served via HTTP, see http://wiki.languagetool.org/tips-and-tricks#toc9) but that should affect almost nobody.

**Comment by TanVD** [comment]
@danielnaber It would be nice to have this feature configurable. In IntelliJ IDEA we now have a situation in which LanguageTool sets Authenticator inside the plugin in static and it is pretty weird :) All in all, at least -- may it be configurable on `Tools` object with a feature flag?

**Comment by danielnaber** [comment]
@TanVD Having a static flag also isn't elegant :-) But I agree this call is strange... we'd consider a flag if you submit a PR.
