### ISSUE TITLE
[en] e-Prime rule error, false alarm on `art`

### ISSUE THREAD

**Issue by flhofer** [languagetool-org/languagetool#2559]
Example:

`It analyzes how the state of art deals with the existing cybersecurity issues.`

`art` is signalled as an e-Prime style problem. Although I understand that old forms of English use art as a variant of are, it is probably a bit out of date. ^^

**Comment by danielnaber** [comment]
Where did you get this error? I cannot reproduce on languagetool.org or with our add-on.

**Comment by flhofer** [comment]
Here with the Firefox plugin..
I use the standalone v4.8 with all the rules enabled. Unless you fixed it in the daily builds, it's still there.
![image](https://user-images.githubusercontent.com/16045541/76109016-8173ca00-5f90-11ea-92b6-d13c69ff5b13.png)

**Comment by flhofer** [comment]
Another note, technically it should be `state of the art` or `state-of-the-art`. Then the LT suggestion is to replace it with `latest`, avoiding that the error shows up in the first place.

**Comment by danielnaber** [comment]
Fixed now. @MikeUnwalla "art" has "be" as a base form, should we remove that reading?

**Comment by MikeUnwalla** [comment]
@danielnaber , yes, removing 'art' from 'be' seems reasonable. Nobody uses it now. It's archaic.

**Comment by danielnaber** [comment]
> yes, removing 'art' from 'be' seems reasonable. Nobody uses it now. It's archaic.

Done.  Could you add a rule for the "state of art" issue described above?

**Comment by flhofer** [comment]
Don't know.. is that needed? I mean, `state of art` should not be that frequent. the `the` was missing, which made me just curious :)

**Comment by danielnaber** [comment]
> Don't know.. is that needed? I mean, state of art should not be that frequent

Sorry, I meant @MikeUnwalla, asking him to add a rule.

**Comment by MikeUnwalla** [comment]
@danielnaber , done: https://github.com/languagetool-org/languagetool/commit/2ff4c5095df2455e80198f0e424cb41c519bff30
