### ISSUE TITLE
RPM package

### ISSUE THREAD

**Issue by Mailaender** [languagetool-org/languagetool#256]
It looks like it was dropped twice for @openSUSE. Once as a OpenOffice addon. https://build.opensuse.org/package/show/openSUSE:Dropped/OpenOffice_org-LanguageTool and now as a LibreOffice addon. Last version was https://build.opensuse.org/package/show/openSUSE:13.1/libreoffice-languagetool The packaging process is pretty complicated which is probably the reason it is now unmaintained and excluded from Factory.

**Comment by Mailaender** [comment]
It may also have been dropped due to the lack of compatibility with OpenJDK. https://languagetool.org/issues/ as SUSE is not allowed to ship Oracle Java.

**Comment by danielnaber** [comment]
LT should work fine with OpenJDK. If it doesn't, please open an issue.

**Comment by baarsrj** [comment]
On my machines, it does work finecwith openjdk.

Verzonden van smartphone.

Daniel Naber <notifications@github.com>schreef:

LT should work fine with OpenJDK. If it doesn't, please open an issue.

**Comment by Mailaender** [comment]
My problem does not seem to be covered by the FAQ so I opened https://github.com/languagetool-org/languagetool/issues/257 as requested.

**Comment by danielnaber** [comment]
I'm closing this, as we have already more than enough to do with the existing versions and add-ons.
