### ISSUE TITLE
[en] do not suggest "re" or "pre"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2562]
The spell checker should not suggest "re".

<img width="368" alt="Bildschirmfoto 2020-03-09 um 10 39 30" src="https://user-images.githubusercontent.com/37363/76200659-52f52980-61f2-11ea-9683-a7ea73f6bd42.png">

It's very unlikely that one of these is meant:
https://www.merriam-webster.com/dictionary/re-

@MikeUnwalla what do you think?

**Comment by MikeUnwalla** [comment]
@tiff , I agree that the suggestion is probably not correct. 

I will add POS and spelling for all English language variants:
www.merriam-webster.com/dictionary/reclean 
www.collinsdictionary.com/dictionary/english/reclean

**Comment by tiff** [comment]
@MikeUnwalla thanks. There will be many more cases. Here's a case where "relieved" has been misspelled. The only suggestion that shows up makes it even worse.

<img width="443" alt="Bildschirmfoto 2020-03-11 um 08 42 35" src="https://user-images.githubusercontent.com/37363/76393703-64fed580-6374-11ea-890e-e2561b04f2f5.png">

I think we should never suggest "re" as a single word in our spelling suggestions. @danielnaber can you implement that?

**Comment by danielnaber** [comment]
Also see #2571
