### ISSUE TITLE
remove beautifuler, beautifuller?

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2565]
@MikeUnwalla can we remove those readings? I think it's always "more beautiful", isn't it? Wiktionary says the reading is "obsolete".

**Comment by danielnaber** [comment]
Same for "beautifulest", which is tagged JJS but the spell checker doesn't accept it.

**Comment by MikeUnwalla** [comment]
@danielnaber , the double l versions are not in LT.
