### ISSUE TITLE
LanguageTool does not work with LibreOffice on openSUSE

### ISSUE THREAD

**Issue by Mailaender** [languagetool-org/languagetool#257]
I have problems starting the LibreOffice extension:

![image](https://cloud.githubusercontent.com/assets/756669/7188203/57e449ac-e476-11e4-954e-d4d4235ebde5.png)

![image](https://cloud.githubusercontent.com/assets/756669/7188210/60b1652e-e476-11e4-855e-ee93f67feb23.png)

Could be related to LibreOffice version?

![image](https://cloud.githubusercontent.com/assets/756669/7188255/a3d34868-e476-11e4-94d5-6304d64e4094.png)

I tried multiple OpenJDK and Oracle Java versions:

![image](https://cloud.githubusercontent.com/assets/756669/7188286/d95e60a8-e476-11e4-9e54-0cbbb3635523.png)

**Comment by danielnaber** [comment]
Everything we know about LO integration issues has been documented at https://languagetool.org/issues/.

**Comment by danielnaber** [comment]
Closing this old bug which I have no idea about how to fix it (if still relevant at all).
