### ISSUE TITLE
Give users feedback about their suggestions and ignore previous suggestions

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#2572]
"Admin: Users' spelling suggestions" sometimes contains suggestions that I have previously rejected. It always contains 'detectd'.

If it is possible to record the words that the maintainers reject, then give users feedback when they submit a suggestion:
* For 'detectd': 
This is a test word and has not been sent to the reviewers.
* For other words that were previously rejected: 
Previously, this word was rejected. If you think that the spelling is correct, open an issue on https://github.com/languagetool-org/languagetool/issues/. Give references that show that the spelling is correct. (Make sure that the spelling is correct for the language variant: British English, American English and so on.)

Ignore all the words that a mainainer previously rejected. (That is, don't add the word to the Admin page.)

**Comment by danielnaber** [comment]
Implemented now, should be online tomorrow.
