### ISSUE TITLE
[en] wrong taggings E_NP_NN_VBP

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2584]
> I will be search for you.

"search" is only tagged as "NN:UN" and makes it impossible to create a rule for this error.

**Comment by tiff** [comment]
Another one:
> Peter, wish you good health!

"wish" is only "NN:UN"

**Comment by tiff** [comment]
> Something that you can text on

"text" is only "NN:UN"

**Comment by tiff** [comment]
> Seriously, you better fucking call me.

"call" is only "NN:UN"

**Comment by tiff** [comment]
Also see https://github.com/languagetool-org/languagetool/issues/2570

**Comment by MikeUnwalla** [comment]
Correction #2592 causes these:

> But some call it surfing, while others ...
> But you know some call it surfing, while others ...
