### ISSUE TITLE
[en] interrobang marked as spelling mistake

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2590]
> It suggests correcting relevant‽ to relevant

<img width="492" alt="Bildschirmfoto 2020-03-20 um 10 50 52" src="https://user-images.githubusercontent.com/37363/77152670-b146c580-6a98-11ea-8d5e-cc68f85abb17.png">

**Comment by SkyCharger001** [comment]
That may be due to the fact that the interrobang is an unrecognized/informal punctuation mark.

**Comment by MikeUnwalla** [comment]
Suggestion: make LT accept ‽ as a non-standard English punctuation mark. Add a grammar rule that says it is non-standard.

**Comment by jaumeortola** [comment]
I will add ‽ to the word tokenizers.
