### ISSUE TITLE
[en] remove RB from "needs"?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2593]
Lexico says "needs" is an archaic adverb. Webster doesn't mention the word "needs". 
Should we remove "RB" from it to avoid unexpected false positives/negatives?

Is it nowadays common to use "needs" as an adverb?

https://www.merriam-webster.com/dictionary/needs
https://www.lexico.com/definition/needs

**Comment by MikeUnwalla** [comment]
The Webster example shows 'needs' used adverbially. You could substitute and adverb such as 'actually' or 'necessarily'. Example:  the dangers of global warming must **necessarily** be recognized...

As best I know, 'needs' used adverbially is not very common. You can probably remove it without causing problems. (But, given that it is not archaic in AmE, a better option is to add exceptions or antipatterns to prevent false positives/false negatives.)

**Comment by tiff** [comment]
Thanks!
