### ISSUE TITLE
Crash with the nightly plus huge RAM/CPU usage

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#2594]
I opened my thesis with the latest nightly and it crashed:
![crash_nightly_20200320](https://user-images.githubusercontent.com/5192600/77183512-5a57e500-6ac6-11ea-83ee-0da0b9a31e50.png)

Also, my i7 6-core was having a very high CPU and ~5 GB of RAM usage by LibreOffice, which I saw in the task manager (since the fans started making noise).

**Comment by danielnaber** [comment]
@FredKruse any chance we get this fixed before the release of LT 4.9 on Tuesday?

**Comment by FredKruse** [comment]
@marcoagpinto: Could you please post a screenshot of your general option panel. How many words / character contain your document?
@danielnaber: I will try to do a bug fix till Monday.

**Comment by marcoagpinto** [comment]
Hello @FredKruse 

Here are the screenshots:
![words_thesis_20200321](https://user-images.githubusercontent.com/5192600/77230715-13352700-6b8e-11ea-98c7-8ada67c8266d.png)


![general_options_panel_20200321](https://user-images.githubusercontent.com/5192600/77230719-1af4cb80-6b8e-11ea-9c9f-ca1c52918abd.png)

Does it help?

Thanks!

**Comment by FredKruse** [comment]
@marcoagpinto : Please test the next nightly build

**Comment by marcoagpinto** [comment]
Ok.

Thanks!

**Comment by marcoagpinto** [comment]
@FredKruse 

To make sure I had the latest build I tried it with last night's.

There is still the CPU load problem on my Windows 10 and i7 laptop with 6-cores.

When I open my thesis, the fans start making noise.
![task_manager_20200323](https://user-images.githubusercontent.com/5192600/77294155-a465e400-6cdb-11ea-892d-bdea67c466d9.png)

**Comment by FredKruse** [comment]
I fear this is the normal load produced by LanguageTool checking a huge document. The new version of LT uses two threads to check the document. One to check only for text level rules that have to include more than one paragraph. This should end rather fast, but after that one thread is left. LT includes so many rules that one core works with nearly full load. So 20% by an 6 core CPU is a realistic value.
You could choose "Check only one paragraph" (first radio button) in the general tab of the option pane to reduce all overhead produced by the LO extension. But than all text level rules are reduced to the check of one paragraph. For example Opening and closing of quotes will produce false alarms when they appear in different paragraphs.

**Comment by marcoagpinto** [comment]
@FredKruse 

What if I click in the:
"Use more than one core (faster but higher CPU load)"?

Will it fix the CPU load, and, if so, can I enable the option in computers with just two/four cores?

**Comment by dpelle** [comment]
Marco A.G.Pinto <notifications@github.com> wrote

> @FredKruse <https://github.com/FredKruse>
>
> What if I click in the:
> "Use more than one core (faster but higher CPU load)"?
>
> Will it fix the CPU load, and, if so, can I enable the option in computers
> with just two/four cores?
>
>
> I don't see the point of such an option.
In the end, it would use about the same amount of CPU in total
but would take longer with one core.
And fewer options is better if they don't add enough value.

High CPU usage is not a problem (it a good feature, it's means
code is parallelized) if it's only temporary. I assume LT does
not continuously hog the CPU, but only for a "short" period of
time when it checks the document.

Regards
Dominique

**Comment by marcoagpinto** [comment]
@FredKruse 

I have ticked the option to use multiple cores.

It crashed twice:
![languagetoolcrash_20200323](https://user-images.githubusercontent.com/5192600/77312357-c1111480-6cf9-11ea-8704-eea3fedcfc23.png)

**Comment by danielnaber** [comment]
@marcoagpinto Could you try this potential fix? https://we.tl/t-Ua8xzTB6E8

**Comment by marcoagpinto** [comment]
@danielnaber 

I have tested it.

10 min + 10 min both with normal cores and multiple cores checked.

It didn't crash the document, but it consumed at least 1 GB more than the previous version.

Also, multiple cores had a very high CPU impact.

One CPU:
![task_manager_one_cpu_20200325](https://user-images.githubusercontent.com/5192600/77565888-c8345000-6ebc-11ea-9936-9f0cd2dc39ed.png)


Multiple CPUs:
![task_manager_multiple_cpu_20200325](https://user-images.githubusercontent.com/5192600/77565929-d97d5c80-6ebc-11ea-8115-aded5fe8e014.png)

**Comment by danielnaber** [comment]
I will close this issue, as the original report has been fixed and the performance issue can be tracked in #2614.
