### ISSUE TITLE
[en] false alarm THERE_RE_MANY

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2597]
> There are many small to middle wounds.

<img width="444" alt="Bildschirmfoto 2020-03-23 um 07 26 58" src="https://user-images.githubusercontent.com/37363/77288294-bfcef000-6cd7-11ea-9ce9-1f0922eadee6.png">

**Comment by tiff** [comment]
Another one:

> There are glow up lights

**Comment by tiff** [comment]
Not sure:
> There are other sort of types
> There are four kind of things

**Comment by MikeUnwalla** [comment]
- [ ] There are many small to middle wounds.
- [ ] There are glow up lights
- [x] There are other sort of types. The warning is correct.
- [x] There are four kind of things. The warning is correct.
