### ISSUE TITLE
Portuguese error not detected

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2600]
User Feedback:

> Espero haverem respostas.

> Em português do Brasil, no padrão escrito o verbo haver é impessoal no sentido de existir, não deveria sofrer flexão: Espero haver respostas.

**Comment by marcoagpinto** [comment]
I will fix it either today or tomorrow.

**Comment by marcoagpinto** [comment]
@danielnaber 

Done:
https://github.com/languagetool-org/languagetool/commit/047a9cd27f1ce6eb507ecd914eaa1183245e69a9

**Comment by danielnaber** [comment]
@marcoagpinto  Thanks!
