### ISSUE TITLE
[es] words added to user dictionaries

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2601]
Here's a list of words that our users often add to the personal dictionary of the browser add-on. Mostly names and Anglicisms (many from US, Mexico and Colombia use the add-on). I can't really judge which to add and which not. 

> OMS
> Switch
> tips
> Dani
> classroom
> premium
> Support
> jajaja
> jaja
> antibacterial
> UE
> ERTE
> podés
> Wuhan
> Xsolla
> ARN
> Store
> coronavirus
> Asher
> express
> AT
> SD
> Academy
> hosting
> Action
> Abel
> Ads
> Anderson
> arcoíris
> Battle
> Climax
> coaching
> confirmame
> Danny
> hangouts
> Player
> lead
> Power
> Service
> Brandon
> Design
> FPS
> GPU
> TC
> tag
> Adreno
> Adrian
> Aida
> Alfred
> Alice
> Almudena
> Amazonía
> Andres
> Arthur
> ATP
> firewall
> Frida
> Hilda
> Ext
> Lucila
> Neruda
> Nicole
> Oliver
> porfa
> PSE
> SARS
> SSL
> Trello
> Arial
> Anne
> Astrid
> Austin
> banners
> Blockchain
> Bedoya
> Booking
> brochure
> Brooklyn
> Charlie
> CLUF
> Community
> Computer
> Connor
> CP
> descargable
> devocional
> EE
> Express
> Free
> freelance
> Gabi
> Godoy
> Harvard
> hashtags
> Hey
> Hyperwallet
> influencers
> informacion
> intrafamiliar
> jajajajaja
> King
> KPI
> laptops
> Michel
> Milton
> Moodle
> Nazare
> paper
> permítame
> playlist
> RRSS
> SPA
> Sahara
> Adriano
> Agency
> AAA
> Abigail
> Acrobat
> Adhanom
> Alhambra
> Alienware
> Allison
> AI
> AC
> ABP
> Aceves
> Adler
> Alpha
> Amazonia
> Ambrosio
> Antoni
> Arellano
> Asertividad
> Arreola
> Association
> Atlanta
> Austrias
> AVON
> Aylin
> Barbie
> BC
> BB
> Beijing
> Benchmarking
> Berenice
> Bernhard
> Betancourt
> Black
> CAD
> CDE
> Carl
> Catherine
> Chris
> Cloud
> Company
> Deborah
> Denis
> DUI
> Erik
> Javeriana
> Keywords
> MERS
> Manoli
> INSS
> Group

**Comment by danielnaber** [comment]
@jaumeortola Could you have a look and add useful words to the Spanish `spelling.txt`?

**Comment by jaumeortola** [comment]
Words not added:

English words: Academy, Action, Agency, Alienware, antibacterial, Asher, Association, brochure, classroom, Cloud, Community, Company, Computer, Design, express, Express, Free, Group, Hey, Keywords, lead, paper, Player, Power, Service, Store, Support, Switch, tag, tips

AC, AT, BB, BC, EE ? 
Andres > Andrés
Climax > clímax
confirmame > confírmame
informacion > información
Nazare ?
porfa > colloquialism (others like this: boli, profe, finde...) Could be added?
premium>prémium
Adrian > Adrián

**Comment by tiff** [comment]
@jaumeortola thanks! not sure if you have seen my comment here:
https://github.com/languagetool-org/languagetool/commit/ad5b5d0d788d8eb232ea626fe3047acfb83dcfd6#comments
