### ISSUE TITLE
IndexOutOfBoundsException with LibreOffice add-on

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2602]
With this test document, I get an error: https://github.com/languagetool-org/languagetool/blob/master/languagetool-office-extension/src/test/resources/manual-testing.odt?raw=true

![Bildschirmfoto von 2020-03-23 13-44-17](https://user-images.githubusercontent.com/857004/77318333-31756100-6d0d-11ea-8186-ffa9b2526580.png)

My settings:
![Bildschirmfoto von 2020-03-23 13-47-56](https://user-images.githubusercontent.com/857004/77318342-34705180-6d0d-11ea-9ab7-d1e7bae6f2a6.png)

Using LibreOffice 6.3.4.2 under Ubuntu 18.04. I tried several times and it seems to be reproducible 100%. No editing is needed, the error occurs a few seconds after the document is opened.

@FredKruse Is this easily fixable? As there are other issues, do you think we should postpone the release of LT 4.9?

**Comment by marcoagpinto** [comment]
@danielnaber 

If LT 4.9 is postponed, may I update the spelling.txt and added.txt for Portuguese and also try to release the GB speller update tomorrow and it be included in 4.9?

**Comment by danielnaber** [comment]
> If LT 4.9 is postponed, may I update the spelling.txt and added.txt for Portuguese and also try to release the GB speller update tomorrow and it be included in 4.9?

If the release is postponed, it means the feature freeze will be longer. So adding a few entries to `spelling.txt` is okay, but I don't think we should have dict updates before the release.

**Comment by marcoagpinto** [comment]
@danielnaber 

Thanks.

I have just committed some improvements.

The GB speller will be after 4.9 is released.

**Comment by FredKruse** [comment]
@danielnaber, @marcoagpinto: Yesterday evening, I committed a bug fix which hopefully solves both bugs. Please test it with your examples.

**Comment by marcoagpinto** [comment]
@FredKruse 
The fixes will only be available tonight, I believe, since LanguageTool releases snapshots at around 7pm.

I will only be able to test tomorrow due to that.

**Comment by danielnaber** [comment]
@marcoagpinto I've uploaded a build here, could you test that? My issue (IndexOutOfBounds) is fixed with that: https://we.tl/t-kKghCvzdRj

**Comment by marcoagpinto** [comment]
@danielnaber 

I have just tested it and:
![languagetool_crash_20200324](https://user-images.githubusercontent.com/5192600/77410465-c9795600-6db2-11ea-9b80-5695a9f7fd4b.png)

**Comment by danielnaber** [comment]
@marcoagpinto Does that only happen with your thesis or can you provide another document to reproduce? @FredKruse I'll continue with the 4.9 release, but it will not contain the LibreOffice add-on yet. We can then fix it and publish it separately in a few days.

**Comment by marcoagpinto** [comment]
@danielnaber 
I haven't been writing much with LibreOffice, so,  I am not sure.

I have been using LibreOffice more to create and test LT rules.

**Comment by marcoagpinto** [comment]
I have opened a small .odt with LT 4.9 disabled and then with it enabled, and waited 10 minutes for each.

There is a huge RAM usage difference with LT on.

Disabled:
![task_manager_lt_disabled_20200324](https://user-images.githubusercontent.com/5192600/77417133-df8c1400-6dbc-11ea-9124-5470827a9e81.png)


Enabled:
![task_manager_lt_enabled_20200324](https://user-images.githubusercontent.com/5192600/77417185-f03c8a00-6dbc-11ea-9e84-3884f63fd290.png)


See attached file:
[rule_test_verb_agreements_20200218.zip](https://github.com/languagetool-org/languagetool/files/4374745/rule_test_verb_agreements_20200218.zip)

**Comment by danielnaber** [comment]
> There is a huge RAM usage difference with LT on.

Java takes as much RAM as it can get (put simply). Unless there's a real issue for users, this is nothing to worry about.

**Comment by marcoagpinto** [comment]
Hello!

@danielnaber @FredKruse 

Again:
![lt_crash_20200324](https://user-images.githubusercontent.com/5192600/77419057-b5882100-6dbf-11ea-86f5-48c6be410b8c.png)


Here is a reproducible example, a 400-page sample which is the number of pages of my thesis.

Just open the ODT, wait a couple of minutes, click on the first page, and start scrolling down with the mouse wheel.

It will open a crash window several times.
[Roman_page_numbers_all_over_sections_20200324.zip](https://github.com/languagetool-org/languagetool/files/4374859/Roman_page_numbers_all_over_sections_20200324.zip)

**Comment by danielnaber** [comment]
Closing, as this issue (IndexOutOfBoundsException) is fixed. Everything else should be discussed in separate issues.
