### ISSUE TITLE
[en] improve spelling suggestions by not suggesting wrong words

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2606]
1. "endevours" suggests "en devours" (but not "endeavors", which is a different problem) - I think we should never suggest "en" as a single word, it's not really a common word

2. "intercool" suggests "inter cool" (intercool is missing in our dictionary but that's a different problem) - I think we should never suggest "inter" as a single word, it's not a commonly used word

3. "withstandable" suggests "withstand able" - I think we should never suggest "able" as a single word at the end of a suggestion

4. "preoccupancy" suggests "pre occupancy" (only in en-gb) - I think we should never suggest "pre" as a single word at the beginning of a spelling suggestion

**Comment by tiff** [comment]
@danielnaber @MikeUnwalla what do you think? I think especially non-native speakers who put a lot of trust into LT could make their texts even worse by replacing a word that is just missing in our dict by a suggestion that makes the grammar worse.

**Comment by tiff** [comment]
Another task from this could be to collect all words starting with "pre" and "inter" and add them to our dictionary. Many of them are still missing.

**Comment by MikeUnwalla** [comment]
>  I think especially non-native speakers who put a lot of trust into LT could make their texts even worse by replacing a word that is just missing in our dict by a suggestion that makes the grammar worse.

@tiff, I agree. LT should not suggest incorrect spellings or words that will cause incorrect grammar. It  is better for LT only to find a spelling error and let the user find the correct spelling.

**Comment by tiff** [comment]
@danielnaber can you implement the proposed changes? You already did something similar with "re" https://github.com/languagetool-org/languagetool/commit/5cb1b5880aab947fb93a17dae9b72b73be7f23a3

**Comment by danielnaber** [comment]
"inter" and "pre" words are now logged and I have added "en" etc. as prefixes that may not be part of suggestions.
