### ISSUE TITLE
[es] "haya" vs "halla"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2607]
Feedback from a user:
> No parece que se halla roto nada
> No parece que se haya roto nada

> Ambas me las da como bien. Yo uso esta aplicación para que me ayude con estas cosas, pero no hace nada en muchos casos.

**Comment by jaumeortola** [comment]
This pair (halla/haya) is in CONFUSION_RULE. 
Some simple rules can be added to improve the results. 
But with "se halla/se haya" there is a lot of ambiguity. We'll need some testing and probably many exceptions.

**Comment by jaumeortola** [comment]
Many cases of "se halla/haya + participle" are both grammatically correct and meaningful. The rule could be useful as a warning. We should decide whether to enable it or not.
I have written rules for halla>haya. 
Some rules can be written also in the other sense: haya>halla.

**Comment by danielnaber** [comment]
> The rule could be useful as a warning.

For now, I suggest we don't activate rules that we know have a lot of false alarms. We might have a new mode in the future for users who want to see all errors, including warnings. We can add such rules then.
