### ISSUE TITLE
[fr] false alarm FRENCH_WHITESPACE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2613]
> « Je suis Chris… »
> « Je suis Chris ! »

There's clearly a normal white space before the quote. But still it wants to suggest inserting one.
Please note: This can't be reproduced on languagetool.org because FRENCH_WHITESPACE is, for some reason, disabled there.

![Bildschirmfoto 2020-03-24 um 14 25 42](https://user-images.githubusercontent.com/37363/77430493-94352e00-6ddb-11ea-8575-b9174e0ccee2.png)

**Comment by jaumeortola** [comment]
For checking different kinds of white spaces you can use the filter org.languagetool.rules.WhitespaceCheckFilter. See an example in Catalan grammar.xml. 
```
<rule>
    <pattern>
        <token regexp="yes">\d[\d+\.,]*</token>
        <token postag="Y"/>
    </pattern>
    <filter class="org.languagetool.rules.WhitespaceCheckFilter" args="whitespaceChar:&#x2006; position:2"/>
    <message>Utilitzeu un espai fi entre nombres i unitats.</message>
    <suggestion>\1&#x2006;\2</suggestion>
```

**Comment by tiff** [comment]
@danielnaber I had a quick look at the java rule myself. Unfortunately I can't get the tests (QuestionWhitespaceRuleTest.java) to fail when I add the sentences as test cases. There seems to be something wrong. Can you have a look yourself?

**Comment by dpelle** [comment]
That's not a false positive.  LT expects a non breakable space.
You can reproduce it with the command line with normal spaces:
```
$ echo "« Je suis Chris… »" | java -jar /home/pel/sb/languagetool/languagetool-standalone/target/LanguageTool-5.0-SNAPSHOT/LanguageTool-5.0-SNAPSHOT/languagetool-commandline.jar -c utf-8  -l fr -v -
Expected text language: French
Working on STDIN...
2799 rules activated for language French
<S> «[«/null] Je[je/R pers suj 1 s] suis[être/V etre ind pres 1 s] Chris[Chris/Z m sp]…[</S>] 
Disambiguator log: 

NE_V[1]: suis[suivre/V imp pres 2 s,suivre/V ind pres 1 s,suivre/V ind pres 2 s,être/V etre ind pres 1 s] -> suis[suivre/V imp pres 2 s,suivre/V ind pres 1 s,suivre/V ind pres 2 s,être/V etre ind pres 1 s]
RP-SUIS_EST_SOMMES[1]: suis[suivre/V imp pres 2 s,suivre/V ind pres 1 s,suivre/V ind pres 2 s,être/V etre ind pres 1 s] -> suis[être/V etre ind pres 1 s]
RB-PRO_PERS_V[1]: suis[être/V etre ind pres 1 s] -> suis[être/V etre ind pres 1 s]

<S> »[</S>]<P/> 
Disambiguator log: 

1.) Line 1, column 18, Rule ID: FRENCH_WHITESPACE
Message: Le guillemet fermant est précédé d'une espace insécable.
Suggestion:  »
« Je suis Chris… » 
                 ^ 
Time: 393ms for 2 sentences (5.1 sentences/sec)
```

And with non-breakable spaces there is no error:
```
$ echo "« Je suis Chris… »" | java -jar /home/pel/sb/languagetool/languagetool-standalone/target/LanguageTool-5.0-SNAPSHOT/LanguageTool-5.0-SNAPSHOT/languagetool-commandline.jar -c utf-8  -l fr -v -
Expected text language: French
Working on STDIN...
2799 rules activated for language French
<S> «[«/null] Je[je/R pers suj 1 s] suis[être/V etre ind pres 1 s] Chris[Chris/Z m sp]…[…/null] »[</S>]<P/> 
Disambiguator log: 

NE_V[1]: suis[suivre/V imp pres 2 s,suivre/V ind pres 1 s,suivre/V ind pres 2 s,être/V etre ind pres 1 s] -> suis[suivre/V imp pres 2 s,suivre/V ind pres 1 s,suivre/V ind pres 2 s,être/V etre ind pres 1 s]
RP-SUIS_EST_SOMMES[1]: suis[suivre/V imp pres 2 s,suivre/V ind pres 1 s,suivre/V ind pres 2 s,être/V etre ind pres 1 s] -> suis[être/V etre ind pres 1 s]
RB-PRO_PERS_V[1]: suis[être/V etre ind pres 1 s] -> suis[être/V etre ind pres 1 s]

Time: 369ms for 1 sentences (2.7 sentences/sec)
```

So the ticket can be closed (not a bug).

**Comment by tiff** [comment]
@dpelle The issue is That LT will insert an extra space. It’s totally valid to suggest a non-breaking space but the user will end up having two spaces. One breaking and one non breaking. Correct me if I’m wrong but that shouldn’t be the case, should it?

**Comment by danielnaber** [comment]
> Unfortunately I can't get the tests (QuestionWhitespaceRuleTest.java) to fail when I add the sentences as test cases

Sentence splitting in this test is not as in real use, see https://github.com/languagetool-org/languagetool/commit/74cfd8b493dcf046286715ab757e654452cd7aaf for an example of how to do it right.
