### ISSUE TITLE
[fr] false positive ACCORD_GENRE : confusion with what noun corresponds to the adjective

### ISSUE THREAD

**Issue by bperel** [languagetool-org/languagetool#2615]
I have seen a few false positives for propositions with multiples genres where LanguageTool doesn't refer to the right part of the proposition to determine the genre of the adjective.

Examples : 

---

> Une nouvelle série de dix timbres toujours **imprimée** aux États-Unis sort en 1945.

LanguageTool wants to replace "imprimée" with "imprimé" even though "imprimée" refers to "série" (and not "timbres" like suggested) so it should be feminine.

---

> Très rapidement, l’Afghanistan s’impose comme une puissance militaire de premier ordre **dirigée** par des généraux.

LanguageTool wants to replace "dirigée" with "dirigé" even though "dirigée" refers to "puissance" (and not "ordre" like suggested) so it should be feminine.

> Cependant, les romans publiés avec un nouveau héros rencontrent un succès moindre, si bien que l'écrivain transforme à l'occasion **certains** de ses récits.

LanguageTool wants to replace "certains" with "certaine", which is twice wrong:
- it thinks that it refers to "occasion" whereas "à l'occasion" is an expression which shouldn't be accorded
- even if it referred to "occasion", it should be suggested to replace it with "certaine", not "certaines".

---

> Le prénom « Raoul » a d'ailleurs été à plusieurs reprises **réutilisé**.

LanguageTool wants to replace "réutilisé" with "réutilisée" which is twice wrong : 
- it thinks that it refers to "reprises" whereas it is actually a past participate
- even if it referred to "reprises", it should be suggested to replace it with "réutilisées", not "réutilisée".

I understand that it can be difficult for LanguageTool to spot what should be accorded to what because it lacks context. Any way this could be improved?

**Comment by tiff** [comment]
@bperel many thanks! This is exactly the feedback we like to see. Feel free to collect more of such issues. We will look into them one by one. 👍

**Comment by bperel** [comment]
Thanks! I'm creating a tool to fix spelling and grammar mistakes on Wikipedia articles using LanguageTool, so as I'm developing mine I check yours :smiley:

**Comment by bperel** [comment]
Has there been some progress on this issue? I can provide more examples if needed

**Comment by vkyfox** [comment]
This issue is our top priority to fix. For now, we've suppressed most false positives, and we're working on a complex rule to hopefully tackle down those complex grammatical problems.

**Comment by bperel** [comment]
Is this issue fixed? I've seen some commits pass by on this topic but I'm not sure if it should be considered done

**Comment by vkyfox** [comment]
There are definitely still too many false positives for the issue to be considered done, I think we plan to focus on it again soon.

**Comment by jaumeortola** [comment]
All FPs fixed with the new French agreement rules.
