### ISSUE TITLE
[en] "grandmum" doesn't suggest "grandma" or "grandmother"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2616]
<img width="410" alt="Bildschirmfoto 2020-03-25 um 11 04 36" src="https://user-images.githubusercontent.com/37363/77524896-6e199780-6e88-11ea-8f93-6d86d46a1307.png">

**Comment by MikeUnwalla** [comment]
Possibly, make a style rule to accept informal BrE: https://www.lexico.com/definition/grandmum

**Comment by danielnaber** [comment]
Aready fixed, closing
