### ISSUE TITLE
[pt] words that users often add to their dict

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2619]
Here's a list of words that are often added to the personal dictionary of Portuguese users. A native Portuguese should go over that list and add the valid ones.

Claudia
Nubank
Elizabeth
Bluetooth
Danielle
Ingrid
Kim
Giovanna
SEO
DevOps
HTML
Kelly
ERP
desktop
desktops
dashboard
Home
COVID
Covid
Mayara
Alisson
Check
Coach
Drauzio
NF
Service
Store
Stories
tags
template
ads
Air
Andrea
Andrey
ANVISA
CAC
CFOP
Changelog
Chris
Bombril
Corona
Developer
Energy
Emily
Edilson
Fabio
Gateway
Feed
gif
GM
Gold
Hangout
Hotmart
IRPF
Leads
MEI
Partner
Samara
Academy
AC

**Comment by marcoagpinto** [comment]
Sure, I will look at it tomorrow :-)

**Comment by marcoagpinto** [comment]
@tiff 

I have added several words from there, but not all: some were in English, others were names with accents missing and some were not found on the on-line dictionaries.

https://github.com/languagetool-org/languagetool/commit/45824ebcff936b86796bc95bae7efe602fd83a07

https://github.com/languagetool-org/languagetool/commit/43fc36abd772f31c32c9d0344936d07eaaca8d8a

**Comment by tiff** [comment]
Cool! Thanks
