### ISSUE TITLE
[es] user feedback: Spanish error "expicatorio"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2620]
User Feedback:

> “explicatorio” does exist.
> “explica” does exists too, but “torio” is not a Word.

![6F852B1069154184880AC61563BA2C33](https://user-images.githubusercontent.com/857004/77562282-1bf46880-6ec0-11ea-9736-e49ff7e47463.png)

**Comment by jaumeortola** [comment]
It is an adjective not found in most dictionaries, but well-formed with a suffix.
