### ISSUE TITLE
ngram rule no longer being applied in v4.9

### ISSUE THREAD

**Issue by EricTendian** [languagetool-org/languagetool#2624]
I've downloaded the ngram data from http://wiki.languagetool.org/finding-errors-using-n-gram-data and set it up as documented. I tried out the English test sentences on that list with v4.9 and they did not produce any errors, while the same sentences did produce errors on v4.8. I have not had time to see if other languages were similarly affected.

To reproduce with Docker:

1. Download and extract ngrams into a path of your choice
2. Test out v4.8:

```bash
# Start the server (remember to replace path)
docker run --rm -d -p 8010:8010 --name languagetool-bugtest -e langtool_languageModel=/ngrams -v {path-to-my-ngrams-dir}:/ngrams erikvl87/languagetool:4.8-dockerupdate-1
# Test the API and see results come back for the rule
curl -s --data "language=en-US&text=I can't remember how to go their." http://127.0.0.1:8010/v2/check | grep CONFUSION_RULE
# Stop the container (will be automatically removed)
docker stop languagetool-bugtest
```

3. Test out v4.9:

```bash
# Start the server (remember to replace path)
docker run --rm -d -p 8010:8010 --name languagetool-bugtest -e langtool_languageModel=/ngrams -v {path-to-my-ngrams-dir}:/ngrams erikvl87/languagetool:4.9
# Test the API and see no output
curl -s --data "language=en-US&text=I can't remember how to go their." http://127.0.0.1:8010/v2/check | grep CONFUSION_RULE
# Stop the container (will be automatically removed)
docker stop languagetool-bugtest
```

I'm not sure what would have caused this change - was one of the rules associated with ngrams tweaked? It did seem like some English rules were changed.

**Comment by danielnaber** [comment]
Thanks for noticing. The threshold values were tweaked for LT 4.9. Unfortunately, some pairs were not just changed but got lost during evaluation. I have reverted the change for now this is properly fixed. Tomorrow's snapshot should work better again. "I don't now where it comes from." will still fail, as there's an issue with tokenization.

**Comment by Zplusless** [comment]
Same problem on v4.9 standalone version
Texstudio+LanguageTool v4.6+ngram works well.
![image](https://user-images.githubusercontent.com/10062702/80296168-3f565000-87ab-11ea-8bc2-a649ec0e30bd.png)


Texstudio+LanguageTool v4.9+ngram, it fails to detect errors in example sentences.
![image](https://user-images.githubusercontent.com/10062702/80296170-41201380-87ab-11ea-87f3-c4dbe16ea1d0.png)

**Comment by danielnaber** [comment]
> Same problem on v4.9 standalone version

See my comment above, it's fix [in the current snapshot](languagetool.org/download/snapshots/).

**Comment by EricTendian** [comment]
Closing as this was fixed and released in https://github.com/languagetool-org/languagetool/commit/61ddae09a611f708bd6cd466259baad3b6f38e94 (v4.9.1)
