### ISSUE TITLE
[de-ch] set POS for "ss" words

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2627]
Das Wort "Maßnahmen" ist korrekt getaggt. Das Wort "Massnahmen" nicht. Im Schweizer-Deutsch existiert kein "ß". Ich denke, wir könnten hier einfach maschinell das Tagging verbessern.

**Comment by danielnaber** [comment]
How did you test this? We already have a `SwissGermanTagger` that's supposed to handle exactly these cases (and it works for me when testing on the command line).

**Comment by tiff** [comment]
Ah, I think it works. Sorry, I was using the online text analysis which obvisouly doesn't use de-ch
