### ISSUE TITLE
[fr] verb "se signaler"

### ISSUE THREAD

**Issue by thelittlefireman** [languagetool-org/languagetool#2631]
hi,
In the text "la personne se signal au comptoir", the verb "signal" is marked wrong : the word signal can't follow "se"
But in French we could use the verb "se signaler". [https://la-conjugaison.nouvelobs.com/du/verbe/se_signaler.php](https://la-conjugaison.nouvelobs.com/du/verbe/se_signaler.php)

Thanks
Thomas

**Comment by tiff** [comment]
@vkyfox

**Comment by dpelle** [comment]
The sentence "la personne se signal au comptoir" is a mistake. 
"signal" is a noun, not a verb.  Correct would be:

"la personne se signale au comptoir"

(signal → signale)

The verb "signaler" has no flexion equal to "signal".  See:

https://grammalecte.net/entry.php?prj=fr&id=172624

So LT is correct.
We could argue that proposing a correction would be an improvement here.
