### ISSUE TITLE
add-on crash with NullPointerException

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2637]
I now get this crash when editing the test document:

![Bildschirmfoto von 2020-03-27 15-23-05](https://user-images.githubusercontent.com/857004/77765843-1f622e00-703f-11ea-8437-33b85f786f85.png)

Test document: https://github.com/languagetool-org/languagetool/blob/master/languagetool-office-extension/src/test/resources/manual-testing.odt?raw=true

**Comment by FredKruse** [comment]
@danielnaber row 237 in SingleDocument is just a }. The row 152 is not correct too. Do you have an idea what this could mean? I insert a query for docCursor if it is equal null, but this doesn't solve the problem. I'm helpless.

**Comment by danielnaber** [comment]
line 237 is this one here: `remarkChangedParagraphs(changedParas, docCursor.getParagraphCursor(), flatPara);` - are you sure you have no uncommitted changes?

**Comment by FredKruse** [comment]
Sorry, you are right. I confused two directories. And the bug was what I supposed at first.

**Comment by FredKruse** [comment]
@danielnaber This bug should be solved with the current release
