### ISSUE TITLE
[de] „Schwenks“ not detected as plural.

### ISSUE THREAD

**Issue by Ordoviz** [languagetool-org/languagetool#2639]
This shortened sentence from [Wikipedia](https://de.wikipedia.org/wiki/Kameraschwenk) is marked as wrong:

> Im Amateurfilm sollten zu viele Schwenks vermieden werden.

The issue seems to be that LanguageTool only knows one of the two plural forms listed on [Wiktionary](https://de.wiktionary.org/wiki/Schwenk). Same issue goes for „Kameraschwenk“.

**Comment by danielnaber** [comment]
Danke, ich habe es aufgenommen. Es sollte dann morgen online sein auf languagetool.org.
