### ISSUE TITLE
LibreOffice add-on: flicker on edit

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2641]
Editing text makes the existing underlines disappear and then re-appear:

[LO-flicker.zip](https://github.com/languagetool-org/languagetool/files/4398645/LO-flicker.zip)

**Comment by danielnaber** [comment]
I have also cases where the edit makes the underlines disappear and they don't come back. Another edit then makes one underline come back, but at the wrong position:

[Peek 2020-03-30 17-03.zip](https://github.com/languagetool-org/languagetool/files/4403661/Peek.2020-03-30.17-03.zip)

Settings used:

![Bildschirmfoto von 2020-03-30 17-05-13](https://user-images.githubusercontent.com/857004/77928407-a5cd7880-72a8-11ea-8ac1-76638ac7f7f4.png)

Document used: https://github.com/languagetool-org/languagetool/blob/master/languagetool-office-extension/src/test/resources/manual-testing.odt?raw=true

**Comment by FredKruse** [comment]
- After the code-changes of the last days the flicker don't appear at the first check.
- After change of text in one paragraph the marks can disappear and then appear again. This is a feature of LO.
- If you type very fast, the marks may be displaced a little. This is a bug of LO (sometimes the last version of changed text is not given to LT). So it can't be changed at the extension.
@danielnaber Please close the issue
