### ISSUE TITLE
[es] "my" vs "muy"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2645]
A user wanted to congratulate us for our great tool. He just wrote "my bueno". I think what he meant was "muy bueno", but it seems that we don't detect this mistake. Is "my" even a word in Spanish?

**Comment by jaumeortola** [comment]
"my" is in the Spanish tagger dictionary (POS tag: NCMN000). It could be an old name of the Greek letter "Mu". We should remove it from the dictionary or create a warning rule.

**Comment by tiff** [comment]
If "my" is very uncommon/archaic, I would vote for removing it.
