### ISSUE TITLE
[en] manual setting of best spelling suggestion doesn't work anymore

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2646]
We have big "if/else" block in the "AbstractEnglishSpellerRule.java" where we manually set the best suggestion for certain spelling errors. This somehow stopped working. E.g. for "css" we should suggest "CSS" but that's not the case (anymore).

![Bildschirmfoto 2020-03-30 um 08 09 58](https://user-images.githubusercontent.com/37363/77880838-dcca6c80-725d-11ea-961f-d2d4a2ed2be0.png)

@danielnaber can you have a look?

**Comment by danielnaber** [comment]
That's caused by the resorting. @fabrichter Could you change it so that the "manual" top suggestions are not affected by resorting?
