### ISSUE TITLE
LibreOffice add-on: com.sun.star.uno.RuntimeException: no text selection

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2647]
> After CPU load settled I wanted to open LT options. Upon clicking Extras => LanguageTool => Options…, I got the following error message: com.sun.star.uno.RuntimeException: no text selection

See https://forum.languagetool.org/t/de-lt-fehlermeldung-marz-2020/5448/10

**Comment by FredKruse** [comment]
@danielnaber the issue was solved by the last bug-fixes, please close the issue.
