### ISSUE TITLE
standalone detects errors but standalone fails

### ISSUE THREAD

**Issue by Konfekt** [languagetool-org/languagetool#265]
For example, enable the `Plain English` rules. Then the standalone version (languagetool.jar) marks  `as a matter of fact` as error, but the command line version (languagetool-commandline.jar) not.

**Comment by danielnaber** [comment]
The command line version doesn't consider the configuration of the GUI, that would be too confusing (e.g. scripts suddenly failing because the configuration has been changed). So you need to use the `-e` switch to enable rules for the command line version.

**Comment by Konfekt** [comment]
How about a switch to apply the settings of `languagetool.cfg` to the command line version? 

The configuration file is 2000 bytes long, mostly rules, and never changes. This is more robust than copying the rules to every script that calls the command line version (for example, the Vim language tool plugin).

**Comment by danielnaber** [comment]
A switch might be a good idea. It currently doesn't have priority for me though, so a pull request might speed things up a lot.

**Comment by Konfekt** [comment]
To get things rolling regarding a command-line switch to load `.languagetool.cfg`, I hit on

https://github.com/languagetool-org/languagetool/blob/97d397bd279b879c3ae286004c90fc174905e498/languagetool-standalone/src/main/java/org/languagetool/gui/LanguageToolSupport.java#L281

Would these lines also work in the command-line version ? Adding a switch to the command-line version that triggers `loadConfig()` does not sound so difficult.

**Comment by danielnaber** [comment]
`Configuration` isn't used in the command-line project, it's in a different project that's not a dependency of the command-line project.

**Comment by Konfekt** [comment]
So should `Configuration` be copied, after suitable changes,  from the other project to the command-line project ?

**Comment by danielnaber** [comment]
If `Configuration` gets used in the command-line project, it should probably be moved to languagetool-core, as it's not GUI-specific then anymore.
