### ISSUE TITLE
[ru] activating DashRule

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2650]
The DashRule has been optimized for better performance and could now be activated for Russian. Here are some new matches from the nightly test:

https://internal1.languagetool.org/regression-tests//20200327/result_ru_20200327_table.html

@yakovru Are these valid matches, i.e. can the rule be activated?

**Comment by yakovru** [comment]
> https://internal1.languagetool.org/regression-tests//20200327/result_ru_20200327_table.html
No, these matches are invalid.

**Comment by danielnaber** [comment]
Could these be avoided by antipatterns? Or is there a more general problem with the rule?

**Comment by yakovru** [comment]
This is a more general problem.
The new algorithm uses parts of words, not whole words.
Example:   ведро**м — ра**ботай  
For this example, both words must be in the dictionary compounds.txt written with a hyphen.
But the algorithm finds the word "м-ра", which does not match.

**Comment by yakovru** [comment]
https://internal1.languagetool.org/regression-tests//20200327/result_ru_20200327.html

**Comment by danielnaber** [comment]
I see. This should be fixed now.

**Comment by yakovru** [comment]
Activated. https://github.com/languagetool-org/languagetool/commit/ef4efdf3956529e04e48a00e96f026299e98e4cf
