### ISSUE TITLE
[es] words often added to the dictionaries of users

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2654]
Here's another list @jaumeortola 

> info
> plugin
> plugins
> enrutamiento
> target
> Mark
> American
> videollamada
> engagement
> Howard
> itinerancia
> like
> melatonina
> Renata
> server
> Stalin
> Alvaro
> Anses
> Au
> Azaña
> Ceballos
> Explorer
> Freud
> Generalitat
> Georg
> paVos
> Potter
> sanitización
> Sant
> Store
> tigo
> Alajuela
> Apollo
> AT
> Babú
> Byron
> Bay
> canvas
> ciberseguridad
> CO
> compu
> cópialos
> Elsa
> English
> Gogh
> importantísimo
> Jair
> Jason
> Karl
> Live
> London
> PAC
> Piaget
> screenshot
> Stanley
> power
> torque
> training
> vitae
> Abderramán
> AA
> ABCD
> Abanca
> Abigail
> Alcatel
> Adolf
> Admin
> Alexandre
> Almodóvar
> Amsterdam
> Andreani
> Andreina
> Animation
> Annie
> Antonieta
> Antígona

**Comment by tiff** [comment]
Some more:
> tips
> point
> AT
> Access
> Express
> Orleans
> UCI
> Ulises
> webinars
> Antonella
> Blue
> Big
> Community
> disfuncional
> Eiffel
> Elsa
> Escalabilidad
> Malala
> potencializar
> quiz
> screenshot
> SEPE
> subtemas
> XML
> º
> AB
> Alain
> April
> ATS
> Bernabé
> Buendía
> bro
> Checoslovaquia
> conductuales
> ERP
> Escríbalo
> Francis
> Gaspar
> Intelligence
> Justin
> logs
> Mack
> One
> Rudecindo
> SA
> Shakespeare
> Suzanne
> switch
> Tim
> Toni
> training
> Urano
> Vinci
> Ámsterdam
> Abercrombie
> Administrator
> Airlines
> Ainhoa

**Comment by tiff** [comment]
> interculturalidad
> Kim
> phishing
> ciberdelincuentes
> videollamada
> Amadeus
> Cooper
> fidelizar
> lipidos
> masajear
> Menorca
> SEAT
> subprocesos
> UCR
> Mark

**Comment by jaumeortola** [comment]
Missing words added to the new dictionary.

**Comment by tiff** [comment]
Great! Thanks
