### ISSUE TITLE
[pt] activating DashRule

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2655]
The DashRule has been made much faster. `PostReformPortugueseDashRule` was turned off because of the performance issue, so we can now re-activate it. @marcoagpinto Do you see any issue with re-activating it, Marco?

Here's what the rule does:

> check for compounds written with dashes instead of hyphens (for example, Rabka — Zdrój).

**Comment by marcoagpinto** [comment]
@danielnaber 

I think it should always have been activated.

So, yes, please activate it.

**Comment by danielnaber** [comment]
> So, yes, please activate it.

Done, should be online tomorrow on languagetool.org
