### ISSUE TITLE
Sentences segmentation rules are not working in LO when "Check text level rules parallel" is activated.

### ISSUE THREAD

**Issue by yakovru** [languagetool-org/languagetool#2658]
Sentences segmentation rules are not working in LO extension then option "Check text level rules parallel" activated.
And XML grammar rules apply to the paragraph, not to the sentences, when "Check text level rules parallel" is activated.

**Comment by FredKruse** [comment]
@yakovru There was a lot of changes in LO extension. Please test if the bug appears anyway. 
If it is solved, please close the issue.
If not, please give me an example for testing and developing.

**Comment by yakovru** [comment]
I think that it fixed now.
