### ISSUE TITLE
[en] Hyphenated ordinal numbers not tagged

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#2660]
Rule ORDINAL_NUMBERS tags some hyphenated numbers, but not all:

> Tagged with ORD: Ten seed companies control over **one-third** of the global seed sales.

> Not tagged with ORD: Ten seed companies control over **two-thirds** of the global seed sales.

**Comment by f-knorr** [comment]
What would be the desired behaviour? 'one-third' is no ordinal number.

**Comment by MikeUnwalla** [comment]
@f-knorr , sorry, I did not think clearly when I reported the issue.
