### ISSUE TITLE
[fr] 2sem 3j

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2666]
> 2sem 3j (2 semaines 3 jours)

![Bildschirmfoto 2020-04-01 um 14 12 21](https://user-images.githubusercontent.com/37363/78135849-d89b7c00-7422-11ea-8be4-b22c2c39b0ac.png)

Is "2sem" a valid way of abbreviating "2 semaines" and is "3j" a valid way of abbreviating "3 jours"?

**Comment by dpelle** [comment]
It does not look like a common abbreviation to me.
Closing as not a bug.
