### ISSUE TITLE
[pt-br] - own names - nomes próprios

### ISSUE THREAD

**Issue by pdrogf** [languagetool-org/languagetool#2667]
Então o autor, Pedro Grazziani, se dirigiu ao local.
![image](https://user-images.githubusercontent.com/15107248/78182233-2ec8e900-743c-11ea-93fb-f86a412d5f50.png)

However, it is about the subject, someone's first name.

**Comment by marcoagpinto** [comment]
Done!

https://github.com/languagetool-org/languagetool/commit/7f194bce062874811d7971eb886dec58bd436ef5

https://github.com/languagetool-org/languagetool/commit/b5ce18f350a677974edf704fdafed77f6f029ab5

**Comment by pdrogf** [comment]
Hi, I believe I expressed myself badly. Would there be a way to create a rule to recognize that they are proper names and therefore are not spelling errors?

@danielnaber @marcoagpinto

**Comment by danielnaber** [comment]
@pdrogf The only way I see is to expand the dictionary by a list of names. Any other approach could mean to miss real spelling mistakes.

**Comment by pdrogf** [comment]
@danielnaber 
Understand. In the language is it not possible to add words to the dictionary?
The file is read-only.

**Comment by danielnaber** [comment]
@pdrogf You can just make the file writable, but you'll need to reload LT for it to see changes to the file.

**Comment by pdrogf** [comment]
Ok, thanks!
