### ISSUE TITLE
[en] missing suggestion A_GREAT_NUMBER_OF_NN

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2676]
> The effective temperatures of a great number of peculiar (Ap) and metallic line (Am) stars are reduced to one system

![Bildschirmfoto 2020-04-02 um 13 54 57](https://user-images.githubusercontent.com/37363/78246564-a4d75980-74e9-11ea-9920-f4e479d7d50a.png)

**Comment by MikeUnwalla** [comment]
Also incorrect suggestion:

> A great number of **problem** conditions can arise.

**Comment by MikeUnwalla** [comment]
I changed the incorrect example so that users won't give us grief about whether "a large number of problems" is followed by _have_ or _has_.

The rule probably could be generalized to `a + JJ + number + of + NN`.
