### ISSUE TITLE
[en] missing suggestion HAVE_PART_AGREEMENT

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2678]
> It has begone.

![Bildschirmfoto 2020-04-02 um 13 58 43](https://user-images.githubusercontent.com/37363/78246864-229b6500-74ea-11ea-8856-1d18f275da63.png)

Of course "begun" is meant but I think the tagging of "begone" is incomplete or wrong.

**Comment by MikeUnwalla** [comment]
Webster (www.merriam-webster.com/dictionary/begone) says it's a verb, but used only in the imperative.

These say it's an interjection:
https://www.ldoceonline.com/dictionary/begone
https://www.lexico.com/definition/begone

I suggest that you/I remove the verb POS from begone (and begones).

**Comment by tiff** [comment]
@MikeUnwalla I will take care.
