### ISSUE TITLE
[de] missing suggestion FLEKTIERTES_ADJEKTIV_AM_SATZENDE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2679]
> Können wir Waren zurückschicken?

![Bildschirmfoto 2020-04-02 um 14 00 35](https://user-images.githubusercontent.com/37363/78247028-6aba8780-74ea-11ea-9044-455da9debab9.png)

**Comment by AgnesKleinhans** [comment]
Das issue hat sich bereits erledigt! :-)
