### ISSUE TITLE
[en] "ouut" suggests "Out" first

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2689]
> Don't forget to check ouut our other product

Happens only for en-gb

![Bildschirmfoto 2020-04-03 um 17 17 55](https://user-images.githubusercontent.com/37363/78376782-189f6200-75cf-11ea-8eac-c9e96e840454.png)

**Comment by danielnaber** [comment]
@fabrichter Resort issue:

`org.languagetool.rules.BERTSuggestionRanking Scored suggestions for 'ouut': [out, oust, Out] -> [Out (2,489007e-01), oust (2,002164e-09), out (0,000000e+00)]`

**Comment by fabrichter** [comment]
I investigated a bit; this is a bug in the server that scores the suggestion, I am working on a fix.

**Comment by fabrichter** [comment]
After the fix, the resorted suggestions look like this:
INFO  org.languagetool.rules.BERTSuggestionRanking Scored suggestions for 'oout': [out, bout, gout, tout, Oort, lout, pout, Out, Tout, rout] -> [out (7.336179e-02), Out (7.336179e-02), bout (2.877838e-08), tout (2.370153e-09), Tout (2.370153e-09), lout (6.423269e-10), gout (1.027037e-10), Oort (6.427965e-11), pout (1.468966e-12), rout (5.643951e-13)]

**Comment by danielnaber** [comment]
As `Out` and `out` are now the same value, is it just luck that `out` comes first?

**Comment by fabrichter** [comment]
No, the resorting is stable, i.e. for candidates with equal scores, the previous ordering is preserved.

**Comment by fabrichter** [comment]
The fix is deployed now.
