### ISSUE TITLE
IndexOutOfBoundsException in Cache

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2709]
![ef32e72ec65202975a4a5891c0ccc0736708aace](https://user-images.githubusercontent.com/857004/78554365-4f61bc00-780b-11ea-87ce-dc57393f20f2.png)

See https://forum.languagetool.org/t/de-in-die-unendlichkeit-und-viel-weiter-lt-ddos-angriff/5547

**Comment by FredKruse** [comment]
@danielnaber The bug is corrected. Please close the issue.
