### ISSUE TITLE
[en] false alarm DID_FOUND_AMBIGUOUS

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2716]
> All he did was to help carrying the bags.

![Bildschirmfoto 2020-04-07 um 12 52 04](https://user-images.githubusercontent.com/37363/78661172-98c70f80-78ce-11ea-9340-b499d5b4bcde.png)

**Comment by tiff** [comment]
Same:

> All he did was helping me

**Comment by MikeUnwalla** [comment]
The problem does not occur now (2020-06-08).
