### ISSUE TITLE
[en] false alarms ADVERB_OR_HYPHENATED_ADJECTIVE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2722]
> He was the only one left standing.

> It's a coastal city situated close to the island.

> They were a group called Pariahs.

> It was the initial wound area.

> He was last seen taken care of by his mother.

> It is the so-called personalized treatment

![Bildschirmfoto 2020-04-08 um 08 49 21](https://user-images.githubusercontent.com/37363/78753362-f2cee000-7975-11ea-8bfd-1cb428c23870.png)

**Comment by MikeUnwalla** [comment]
Refer to https://github.com/languagetooler-gmbh/languagetool-premium/issues/250.

**Comment by MikeUnwalla** [comment]
- [ ] He was the only one left standing.
- [ ] It's a coastal city situated close to the island.
- [ ] They were a group called Pariahs.
- [x] It was the initial wound area. This sentence is ambiguous. If 'wound' is a verb, then the warning is correct. If 'wound' is a noun, it's a false positive.
- [ ] He was last seen taken care of by his mother.
- [ ] It is the so-called personalized treatment
