### ISSUE TITLE
[en] broken url in English grammar.xml file

### ISSUE THREAD

**Issue by dpelle** [languagetool-org/languagetool#2726]
I ran a script to find broken links in grammar files.

For English, it found this broken link in languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml:
```
FOUND BROKEN URL [http://andromeda.rutgers.edu/~jlynch/Writing/t.html#that]
```

**Comment by MikeUnwalla** [comment]
Rutgers website is available, but not andromeda.rugters. Try again tomorrow to make sure it's not a temporary fault.
