### ISSUE TITLE
[nl] broken url in Dutch grammar.xml file

### ISSUE THREAD

**Issue by dpelle** [languagetool-org/languagetool#2728]
I ran a script to find broken links in grammar files.

For Dutch, it found these broken links in languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml:
```
FOUND BROKEN URL [https:www.taaladvies.net/vraag/120]
FOUND BROKEN URL [https://onzetaal.nl/taaladvies/welke-die,]
FOUND BROKEN URL [http://www.taalpost.nl/archief/1594.html]
```
For the second link, removing the comma at the end would fix it.

**Comment by baarsrj** [comment]
Most urls had to be updated from http to https, one containted 2 urls (still a missing feature of LT), the other is no longer there. Corrected all.
