### ISSUE TITLE
Strange issue with VON_NOETEN rule, spell checker deletes dot.

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#273]
![lt-bug](https://cloud.githubusercontent.com/assets/4381288/7944867/9b073228-096d-11e5-9981-ab794e920a85.png)
Here is a strange issue I found today. If I type "von nöten" into the standalone GUI version of LT 2.9, this triggers both the (new) rule VON_NOETEN and the spelling rule, as expected, because 'Nöten' is a noun and should be uppercase in German.
Here's the issue:
(1) For some reason, the dot at the sentence end is included in the selection for replacement by the spelling rule. This is somewhat unexpected, but as long as the suggestion includes the dot, it doesn't do any harm.
(2) The screenshot shows that only the first two suggestions (which are, strangely, identical btw) include the dot. If I choose one of the other suggestions, the dot is deleted.
This is not a big deal, but it can transform a correct sentence into an incorrect one. And it is strange: Why would the spell checker mark punctuation for replacement at all?

**Comment by janschreiber** [comment]
A clarification: This problem has actually nothing to do with the VON_NOETEN  rule. It seems to occur whenever a spelling error is the last word of a sentence and the sentence ends with a period. Sentences ending with a question mark or exclamation mark are unaffected. It's for example triggered by the sentence "Das müssen wir um jeden Preis verhindenn."
Also, it affects both the GUI version and the Web interface at the LT homepage.

**Comment by Xaratas** [comment]
Its the same with the commandline. Even if the Word is added to the hunspell user dictionary spelling.txt language tool checks includes the dot and marks it as an error.
(Galawain is a God in the Game Pillars of Eternity)

```
xar@Y4d:~/gitrepos/poe_translation/translation_helper$ echo "Das Haus von Galawain." | java -jar ../../../Downloads/LanguageTool-3.1/languagetool-commandline.jar -l de-DE                     
Expected text language: German (Germany)
Working on STDIN...
1.) Line 1, column 14, Rule ID: GERMAN_SPELLER_RULE
Message: Möglicher Rechtschreibfehler gefunden
Suggestion: Galawain; Galawains; Galawein; Galamain; Galawand; Galamainz; Galawind; Galaweine; Galahain; Galahaine; Galahains; Galamains; Galarain; Galaraine; Galarains; Galasaint; Galawahn; Galawahns; Galawaid; Galawaids
Das Haus von Galawain. 
             ^^^^^^^^^ 
```

**Comment by Xaratas** [comment]
It looks like the fix would be to change line 124 from this file: 
https://github.com/languagetool-org/languagetool/blob/14c3a88025c36ba27cd7a64a812a9366e84473b0/languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java#L124

```java
return (isAlphabetic && !word.equals("--") && hunspellDict.misspelled(word)) || isProhibited(removeTrailingDot(word));
```
Suggested fix:
```java
return (isAlphabetic && !word.equals("--") && hunspellDict.misspelled(removeTrailingDot(word))) || isProhibited(removeTrailingDot(word));
```

**Comment by danielnaber** [comment]
@Xaratas I cannot reproduce the problem you describe with the current version from git, this seems to be fixed already.

**Comment by Xaratas** [comment]
@danielnaber Checked against the latest snapshot. LanguageTool-20151209-snapshot
Its fixed if the word is added to the hunspell spelling.txt. 
Much less important rest issue: If the word is unknown then the error marker includes the point.
```
Das Haus von Galawain. 
             ^^^^^^^^^ 
```

**Comment by janschreiber** [comment]
The command line version of Hunspell shows the same behavior, i.e. effectively deletes the period from the sentence end. This was probably introduced like ten years ago to accommodate for the automatic handling of the period in LibreOffice (and OOo). I found this in the [Hunspell change log](https://github.com/hunspell/hunspell/blob/90ed1539d1653986e31d96b82ae0b36f8f13f089/ChangeLog):

> src/hunspell/{suggestmgr,hunspell}.*: strip periods from suggestions (restore MySpell's original behaviour)
> Rationale: OpenOffice.org has an automatic period handling mechanism and suggestions look better without periods.

**Comment by f-knorr** [comment]
Here is the problem: 
We use this regex to tokenize text in German
`((?![ß\-.])[^\p{L}]|(?<=\d)\-|\-(?=\d+))`
Due to the `.` in this regex, a full stop does not tokenize text (i.e., "Das ist fasch." gets tokenized in "Das, ist, fasch.")
Unfortunately, we get this regex-part directly from the hunspell dictionary (which we read fromthe aff file):
`wordChars = "(?![" + hunspellDict.getWordChars().replace("-", "\\-") + "])";`

The easy fix that i suggest is to add `.` as additional tokenizing character (we could also modify the aff-file, but then we would have to remember this change after every update of the dict)
`((?![ß\-.])[^\p{L}]|(?<=\d)\-|\-(?=\d+)[.])`
Now "Das ist fasch." gets tokenized in "Das, ist, fasch, ."

**Comment by janschreiber** [comment]
Does this change affect the internal handling of abbreviations by Hunspell, such as 'bzw.', 'bzgl.' etc.? I can't test this myself atm, sorry.

**Comment by f-knorr** [comment]
Unfortunately, yes! I have just reverted my change.
These abbreviations would no longer be accepted, if we add `.` as a tokenizing character to the regex.
Hence, we need a more sophisticated fix...

**Comment by f-knorr** [comment]
So, here is another attempt to fix the problem:
First, let's check whether the word to be corrected ends with ".". In this case, add a "." to all suggestions that do not end with ".". (We have to do this check as, for instance, "ec." creates the suggestion "etc.", which already ends with "." -> "Wir brauchen noch Wasser, Limo, Bier etc.")
I have added some checks to prevent a repetition of yesterday's fix attempt.
