### ISSUE TITLE
[pt] false alarms "on"?

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2732]
Hi Marco, "on" is marked even in "on-line", see https://internal1.languagetool.org/regression-tests//20200408/result_pt-BR_20200408_table.html. Although I don't speak Portuguese I guess that's not useful?

**Comment by marcoagpinto** [comment]
I have just removed "on" and "off" from the foreign words:
https://github.com/languagetool-org/languagetool/commit/ae446c813d43a1e1394816f972e11ce9307f657d
