### ISSUE TITLE
[DE] Kritischer Fehler

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#2734]
Moin liebes LangaugeTool-Team

Hiermit übergebe euch die Textstelle, die das Problem verursacht.
![grafik](https://user-images.githubusercontent.com/40240507/79008781-67fd0980-7b5e-11ea-88c2-cce3ac64319b.png)
Diese Textstelle sorgt für komische Bugs und eine Absturzgarantie.

[Bug-Dokument.zip](https://github.com/languagetool-org/languagetool/files/4462561/Bug-Dokument.zip)
Das Dokument ist sehr klein und die Probleme sind groß.

Grüße Dallun511

**Comment by danielnaber** [comment]
@FredKruse Hast du eine Idee? Ich kann das Problem nicht nachvollziehen, kann aber auch daran liegen, dass mein LibreOffice gerade eh gar keine Rechtschreibprüfung machen will.

**Comment by FredKruse** [comment]
Ich kann den Bug auch nicht nachvollziehen. Allerdings habe ich Freitag und Samstag zwei Bug-Fixes eingespielt. Einer von ihnen hat ein Einfrieren in einigen speziellen Konstellationen behoben. Vielleicht hat das das Problem auch schon gelöst.
@Dallun511 Bitte teste das Dokument noch mal mit dem neusten Snapshot.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/79056595-63b51700-7c58-11ea-90b7-66ae78287c20.png)
Leider hängt sich die Aussage auf und fängt sich auch nicht nach fünf Minuten wieder.
So ist das Programm nutzlos und ein Risiko, da hier sehr schnell Datenverlust entstehen kann.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/79223931-8b73cd00-7e5a-11ea-9f4a-39e8e1269452.png)

Getestet mit LanguageTool-20200413-snapshot
Hängt sich nur auf und fängt sich nicht mehr auch nicht nach 2 Stunden.

Dadurch ist das LT komplett nutzlos.

**Comment by FredKruse** [comment]
Den Fehler, so wie er in der Grafik dargestellt ist, kann ich nach wie vor nicht nachvollziehen, konnte aber mit dem Beispieltext einen ähnlichen Fehler reproduzieren. Bei mir läuft es jetzt.
@Dallun511 Bitte mit der nächsten Version morgen noch einmal testen.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/79299281-f0273a00-7ee3-11ea-81a5-c1e0923aac7f.png)

Das Bug-Dokument lässt sich wieder prüfen. Aber ich werde es noch weiter testen.
Grüße Dallun511

**Comment by FredKruse** [comment]
Der Fehler wurde behoben.
@Dallun511 bitte schließe dieses issue
