### ISSUE TITLE
[es] "recipiente"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2737]
User feedback:
> La palabra "recipiente" existe en español pero la detecta como errónea y sugiere cambiarla por palabras en ingles como "recipient".

**Comment by jaumeortola** [comment]
There is no problem with this word in Spanish. It seems that the user is getting corrections for English when checking  for Spanish is expected. The problem is probably with language detection/selection.

If we want to improve language detection, we need to know the whole sentence.

**Comment by jaumeortola** [comment]
If we don't have more information from the user, we can close this issue.

**Comment by tiff** [comment]
Thanks for looking into it. User's unfortunately don't answer to our questions
