### ISSUE TITLE
[en] "gif" doesn't suggest "GIF"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2738]
<img width="384" alt="Bildschirmfoto 2020-04-13 um 18 04 50" src="https://user-images.githubusercontent.com/37363/79136460-57909d00-7db1-11ea-9f5d-e484d537234a.png">

@fabrichter @danielnaber doesn't happen with the browser add-on. Is it related to the suggestion re-ordering?

**Comment by tiff** [comment]
Same with "csv"

**Comment by danielnaber** [comment]
Unfortunately, in this case (`gif`), the resorted result is worse than without resort. @fabrichter Could you see if that's a bug?

**Comment by fabrichter** [comment]
These are the probabilities output by BERT: 
org.languagetool.rules.BERTSuggestionRanking Scored suggestions for 'gif': [GIF, if, gift, gig, GI, Gil, gin, AIF, GDF, GAF] -> [if (1.079644e-02), gift (6.779396e-06), GI (4.506496e-06), Gil (2.817510e-06), gin (2.429262e-06), gig (7.831370e-07), GIF (3.049836e-08), GAF (2.709551e-08), AIF (7.117823e-09), GDF (4.597166e-09)]

So GIF is just rated very low by BERT. As it happens, 'if' and 'gift' are encoded as one token in BERT, whereas GIF takes two tokens. Our formula two combine probabilities for multi-token suggestions currently is biased towards fewer tokens, so that will play a part, but the example sentence also seems pretty hard for a language model to deal with.

**Comment by tiff** [comment]
@fabrichter here's another case: "And btw I have no idea."

"btw" doesn't suggest "BTW". Should we set the top suggestion manually in such cases?

**Comment by tiff** [comment]
Another idea: if the same word in uppercase is in the suggestions, we could increase its score manually?

**Comment by fabrichter** [comment]
Instead of increasing its score, I would suggest putting these into the list of suggestions that are inserted at the top before the regularly scored suggestions, since that is already implemented and figuring out an amount/factor for increasing the score would be tedious/difficult. 

Another question: Should we only do this for lower → uppercase (in one/both directions) or just all cases where only the case differs?

**Comment by tiff** [comment]
@fabrichter sounds good. I would suggest doing it only for lower → uppercase (one direction).

**Comment by tiff** [comment]
Same happens with "ai" and "ip":

![Bildschirmfoto 2020-04-20 um 10 57 29](https://user-images.githubusercontent.com/37363/79733681-cca22c00-82f5-11ea-83f4-9a8b32131397.png)

**Comment by tiff** [comment]
"vpn" vs. "VPN"

![Bildschirmfoto 2020-04-21 um 15 22 27](https://user-images.githubusercontent.com/37363/79870948-ffc2e900-83e3-11ea-873d-af824a2e30fb.png)

**Comment by tiff** [comment]
"usd" vs "USD"

![Bildschirmfoto 2020-04-21 um 15 42 11](https://user-images.githubusercontent.com/37363/79872950-b7f19100-83e6-11ea-9fc5-9aa2c75abd0f.png)

![Bildschirmfoto 2020-04-21 um 15 44 20](https://user-images.githubusercontent.com/37363/79873151-fdae5980-83e6-11ea-8004-7f8cdac0521e.png)

**Comment by danielnaber** [comment]
@fabrichter please check again whether lowercase -> uppercase work (usd, vpn, etc)

**Comment by danielnaber** [comment]
For comparison, some numbers from the ngram data (which is based on different data than BERT, but still interesting):

```
[The, GIF, is] -> count:103, 2.133727946705021E-16, coverage=1.0, log:-36.083490828295005
[The, gif, is] -> count:0, 5.990993701844375E-20, coverage=0.6666667, log:-44.261444568049185
[The, IF, is]  -> count:576, 7.252842180893372E-15, coverage=1.0, log:-32.557382977915
[The, if, is]  -> count:211, 2.4581636103811045E-15, coverage=1.0, log:-33.63936182358125

[The, IP, is] -> count:949, 2.329874603637398E-14, coverage=1.0, log:-31.390376853968654
[The, ip, is] -> count:0, 1.2662320586779555E-18, coverage=0.6666667, log:-41.21048606627487
[The, IT, is] -> count:164, 2.9907573656504326E-15, coverage=1.0, log:-33.44324974003437
[The, it, is] -> count:592, 1.9672097998962485E-15, coverage=1.0, log:-33.86216020135611

[many, USD, do] -> count:0, 4.522815263251364E-21, coverage=0.33333334, log:-46.84515230706672
[many, usd, do] -> count:0, 4.522815263251364E-21, coverage=0.33333334, log:-46.84515230706672
[many, US, do] -> count:0, 1.976470270040846E-18, coverage=0.6666667, log:-40.765219111971135
[many, us, do] -> count:0, 4.957005528523494E-18, coverage=0.6666667, log:-39.845729839558764
```

**Comment by tiff** [comment]
![Bildschirmfoto 2020-04-27 um 13 19 09](https://user-images.githubusercontent.com/37363/80366589-ced23080-8889-11ea-8b11-b45494762364.png)

Also see https://github.com/languagetool-org/languagetool/issues/2766

**Comment by tiff** [comment]
<img width="518" alt="Bildschirmfoto 2020-05-05 um 12 59 11" src="https://user-images.githubusercontent.com/37363/81059177-429abb80-8ed0-11ea-9021-0e6bb16ff0c7.png">

**Comment by tiff** [comment]
@danielnaber @fabrichter Actually, I think this applies to all cases where case differs

In this example "Firefox" should be the first suggestion:
![Bildschirmfoto 2020-06-15 um 18 18 03](https://user-images.githubusercontent.com/37363/84681594-a59e5a00-af34-11ea-88d3-52d2423a5c02.png)

Another example:
![Bildschirmfoto 2020-06-15 um 11 21 36](https://user-images.githubusercontent.com/37363/84681646-b8189380-af34-11ea-8870-a1f1bfff5560.png)

@fabrichter The logic should be kept simple. My recommendation: If word has more 2 characters prefer the suggestion that matches case insensitively. What do you think?

**Comment by danielnaber** [comment]
Maybe we could do that for German and English. For e.g. French, it's not that trivial: Someone writing "ca" expects "ça" as a correction, but would get "cA" (also in the dictionary). So maybe ignore case, but only if there's no other suggestions that is the same when diacritics are removed...

**Comment by danielnaber** [comment]
Closing, the examples all work better now (uppercase suggestion on first place).
