### ISSUE TITLE
[nl] missing suggestion SEKSE_LIJK

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2739]
> ... met een vrouwelijk politie ...

<img width="421" alt="Bildschirmfoto 2020-04-13 um 18 50 13" src="https://user-images.githubusercontent.com/37363/79140081-bbb65f80-7db7-11ea-8a66-aa13d6270595.png">

Also happens with these words:
* mannelijke
* mannelijk
* vrouwelijke

@baarsrj

**Comment by baarsrj** [comment]
This correct.
