### ISSUE TITLE
[es] "usa"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2743]
The lowercase "usa" seems to be a Spanish word: https://es.wiktionary.org/wiki/usa

We seem to think the user means the country.

![Bildschirmfoto 2020-04-14 um 11 23 11](https://user-images.githubusercontent.com/37363/79208471-5eb3bb80-7e42-11ea-9c62-9140b38e6d60.png)

@jaumeortola could you check?

**Comment by jaumeortola** [comment]
Yes, you are right. I saw it in the nightly tests. (I have to remember to put always default="temp_off", even in the simplest rules).
