### ISSUE TITLE
[fr] "déconfinement" and "corona"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2746]
I see many people adding the word "déconfinement" to their personal dictionary.
@dpelle is this a word missing in our dictionary?

I couldn't find it at larousse.fr but at the [French Wiktionary](https://fr.wiktionary.org/wiki/d%C3%A9confinement).

**Comment by dpelle** [comment]
The word is in many newspapers these days with the Coronavirus pandemic.
It's the process of undoing "confinement".  It's a recent neologism.

I only see it in https://fr.wiktionary.org/wiki/d%C3%A9confinement

To check French words, I recommend going to https://www.lexilogos.com/francais_dictionnaire.htm which has links to many French dictionaries.

I'll propose an addition to the Dicollecte French dictionary (which is used not only by LT but also OpenOffice, Firefox, etc.)

**Comment by tiff** [comment]
Thanks

**Comment by dpelle** [comment]
@dpelle wrote:

> I'll propose an addition to the Dicollecte French dictionary

I see that it was already added recently to Dicollecte (on March 31, 2020).
Here is the entry: https://grammalecte.net/entry.php?prj=fr&id=235146

Of course, LT will need to wait until the next release of Dicollecte is imported in LT.
In the meant time, it's a good word to whitelist in LT.

**Comment by tiff** [comment]
Ok, speaking of it: I also see the word "corona" often added to the dictionary. Many newspapers seem to also use the word (without "virus"). Should we whitelist it as well?

**Comment by dpelle** [comment]
tiff wrote:

> I also see the word "corona" often added to the dictionary.

That seems to be a mistake. The word should be "coronavirus" which existed in dictionaries well before the recent pandemic.  It's e.g. in Dicollecte since 2011.

I'll double check later, but I think that the best will be to add a grammar rule to
suggest "coronavirus" when typing "corona virus" or "corona-virus".

**Comment by dpelle** [comment]
About "corona virus", there's a lot of hits in google (for English or other languages) for mistakes like:
* coronovirus
* corona virus
* coronnavirus
* etc.

In Google search, one needs to select: Tools → Verbatim → Verbatim otherwise Google auto-magically corrects mistakes which is annoying and prevents finding mistakes.

**Comment by tiff** [comment]
@dpelle we already have a rule that suggests "coronavirus" for "corona virus". I added it a couple of weeks ago.

![Bildschirmfoto 2020-04-14 um 17 20 50](https://user-images.githubusercontent.com/37363/79242266-60967280-7e74-11ea-9035-90c7e8997daa.png)

I was referring to "corona" being used without "virus". At least in German, many people (also serious newspapers) use "corona" as a short form of "coronavirus"

**Comment by dpelle** [comment]
> I was referring to "corona" being used without "virus".

I would say it's not correct in French to just write "corona" when talking about coronavirus.
"corona" is currently highlighted as a spelling mistake which is fine in my opinion.
"Corona" is a Latin word and a Mexican beer among other things, but that does really not justify adding it to the dictionary.

Various uses of the word "Corona" in the French wikipedia: https://fr.wikipedia.org/wiki/Corona

**Comment by tiff** [comment]
Ok, thanks for clarifying. I'm closing this
