### ISSUE TITLE
multiple part compounds rule

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#2747]
Idea: a rule that tries all compounded variants of a set of words and if so, offers an explanations why these should be written together.

lange afstand loper|persoon die lange afstanden loopt
should warn for
- lange afstandloper
- langeafstand loper
- lange afstand loper
and suggests langeafstandloper (persoon die lange afstanden loopt)
Initial list of words and explanations added (from onzetaal.nl)
[multipartcompounds.zip](https://github.com/languagetool-org/languagetool/files/4475498/multipartcompounds.zip)

**Comment by danielnaber** [comment]
The rule now exists, but it's still off by default. Still needed:

- [ ] Dutch short description (e.g. "Detects missing space in some nouns")
- [ ] Message: show only the second column? Or is there a static text in front of it?
- [ ] add data to `multipartcompounds.txt`, but only once you have made sure the license is okay
- [ ] briefly document `multipartcompounds.txt` (see "TODO" on top of the file)
