### ISSUE TITLE
Please document the rules

### ISSUE THREAD

**Issue by iio7** [languagetool-org/languagetool#2749]
In the documentation at http://wiki.languagetool.org/command-line-options it provides the `-e` which is *Enable only specified rules, delimited with a comma and without spaces after the comma. Note: you cannot specify both enabled and disabled rules at the same time.*

Could you PLEASE document the rules? I haven't been able to find those anywhere.

**Comment by danielnaber** [comment]
The rules are listed at https://community.languagetool.org/rule/list?lang=en

**Comment by iio7** [comment]
Then please document this, don't just close this. Bad documentation is a bug!
