### ISSUE TITLE
German word "sonne" is not being corrected to "Sonne"

### ISSUE THREAD

**Issue by CoalaJoe** [languagetool-org/languagetool#275]
http://127.0.0.1:8001/?language=de-DE&text=Die+sonne+scheint

<matches software="LanguageTool" version="2.9" buildDate="2015-03-30 09:24">
<language shortname="de-DE" name="German (Germany)"/>
</matches>

**Comment by danielnaber** [comment]
Thanks, I'm merging this into #228.

**Comment by janschreiber** [comment]
This sentence is already covered by the rule SUBSTANTIVE_KLEIN.

**Comment by danielnaber** [comment]
@janschreiber SUBSTANTIVE_KLEIN only seems to cover `sonnen`, not `sonne`. At least this error is not found yet.

**Comment by janschreiber** [comment]
@danielnaber I tested it again today and indeed, if you leave out the dot at the end of the sentence, as @CoalaJoe did, the rule is not  triggered for some reason, but it works if you add the dot. `sonne` appears in the huge femsubklein entity defined at the top of grammar.xml, and the sub-rule that is intended to cover cases like that is in line 14056. We could remove the SENT_START token from the rule and run a corpus test to see if this generates false positives, but I wonder if it's worth the effort.
