### ISSUE TITLE
[de] use prefix_verb syntax in German POS tagger

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2751]
Use entries like `herum_geben` from `spelling.txt` in the German POS tagger, so they are tagged without being added to `added.txt`.

Source: https://forum.languagetool.org/t/de-verben-mit-he-rum-z-b-geben/5572

**Comment by Dallun511** [comment]
Durch die neue Version des Taggers, werden enige Wörter mit dem Präfix "herum" erkannt.
Immer noch nicht alle, aber immerhin mehr, als vorher.

Die erkannt werden, habe ich angekreuzt
