### ISSUE TITLE
[es] false alarms DET_NOM_FEM?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2753]
The rule called "DET_NOM_FEM" is the most ignored/disabled rule by our users.

Here are some cases when the user decided to ignore it:
![Bildschirmfoto 2020-04-15 um 14 49 06](https://user-images.githubusercontent.com/37363/79338982-76656f80-7f28-11ea-99b6-2c879627aef2.png)

@jaumeortola does that help? Do you need more? If so, I can provide you with access to the tool where we collect that data.

**Comment by tiff** [comment]
I see that the rule doesn't provide a suggestion. Does it make sense to add some simple rules with suggestions that cover the most common cases?

**Comment by jaumeortola** [comment]
I have written a new rule group (AGREEMENT_DET_NOUN), which will replace these rules. 
The new rules will provide suggestions. But some more work is needed before activating them.

**Comment by jaumeortola** [comment]
Fixed replacing the rule with AGREEMENT_DET_NOUN.

**Comment by tiff** [comment]
Many thanks!
