### ISSUE TITLE
[DE] Fehlalarm "meine"

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#2761]
Moin liebes LanguageTool-Team

Schade, **dass ich meine** zu Hause gelassen habe.
LT: Überprüfen Sie die Reihenfolge von Subjekt und Prädikat. 
meine fungiert nicht als Verb.

Grüße Dallun511

**Comment by tiff** [comment]
Der Fehler wurde mittlerweile behoben
