### ISSUE TITLE
[en] no suggestion OXFORD_SPELLING_ADJECTIVES

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2764]
> unadvertised

> comprised

**Comment by tiff** [comment]
@MikeUnwalla I think if you also put the `suppress_misspelled="yes"` on the `<suggestion>` the rule will not match anymore for words that we can't generate a suggestion for.

**Comment by tiff** [comment]
(only works when the `<suggestion>` is part of the `<message>`)

**Comment by MikeUnwalla** [comment]
I will also fix the other rules.

**Comment by tiff** [comment]
@MikeUnwalla let's wait one day before adjusting all the rules. I'm not sure if this really works. (I know it worked for "CD_NN")

**Comment by MikeUnwalla** [comment]
OK, I will wait.

**Comment by tiff** [comment]
@MikeUnwalla seems to work, can you also check and adjust the other rules accordingly? Thanks

**Comment by MikeUnwalla** [comment]
@tiff, I fixed the other rules.

Possibly, there will be other words for which there is no suggestion because `suppress_misspelled="yes"` in the suggestion does not always work. For the known cases, I added an exception.
