### ISSUE TITLE
[fr] Rule CIMETIERE_MILITAIRE is inverted.

### ISSUE THREAD

**Issue by ElieGouzien** [languagetool-org/languagetool#2767]
Rule [CIMETIERE_MILITAIRE](https://community.languagetool.org/rule/show/CIMETIERE_MILITAIRE?lang=fr&subId=1) is inverted.

**In**correct form is "cimetière de guerre" while correct form is "cimetière militaire".

**Comment by vkyfox** [comment]
Fixed! Thank you for the feedback
