### ISSUE TITLE
[DE] Fehlalarm Kommaregel

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#2776]
Moin liebes LanguageTool-Team

- [x] Tessa und Gerard **waren sehr erfahren und sehr gut trainiert, weswegen sich der Kampf in die Länge zog.**
LT: "Hier sollte ein Komma eingefügt werden, wenn es sich bei dem hinteren Satzteil um einen Nebensatz handelt."

- [x] Olivia **sagte total erschöpft: „Ich hoffe, sie ist** zufrieden.“
LT: "Hier sollte ein Komma eingefügt werden, wenn es sich bei dem hinteren Satzteil um einen Nebensatz handelt."

Grüße
Dallun511

**Comment by AgnesKleinhans** [comment]
Diese Fehlalarme dürften künftig nicht mehr erscheinen :-)

**Comment by Dallun511** [comment]
Das hoffe ich. Die Regel behindert mehr, als sie hilft. Ich war schon am Überlegen, die Regel zu deaktivieren, da sie sehr stark Fehlalarme produziert.

**Comment by Dallun511** [comment]
Alle Fehler sind behoben.
