### ISSUE TITLE
[en] endless loop ANYMORE_ADVERB

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2779]
> you don't have to take care of them anymore

will suggest "any more", then "anymore" again

![Bildschirmfoto 2020-04-21 um 10 29 44](https://user-images.githubusercontent.com/37363/79843863-1d2f8d00-83bb-11ea-8cfb-09b952d773f0.png)

**Comment by MikeUnwalla** [comment]
@tiff, I cannot reproduce this error. Please give more details.

**Comment by tiff** [comment]
@MikeUnwalla try to add a space or line break at the end.
