### ISSUE TITLE
false alarm: "...noticed that the version I sent you..."

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2783]
> I just noticed that the version I sent you doesn't contain the replace.txt yet for English.

`NON3PRS_VERB[5]` matches

**Comment by tiff** [comment]
A few more:
> That they welcome you isn't always good.

> Because you ain't me.

> The I stands for International

**Comment by tiff** [comment]
The suggestions don't really make sense here:
<img width="410" alt="Bildschirmfoto 2020-04-21 um 18 55 24" src="https://user-images.githubusercontent.com/37363/79891743-b84b5580-8401-11ea-9b27-1695dd795ec4.png">

<img width="498" alt="Bildschirmfoto 2020-04-21 um 18 56 04" src="https://user-images.githubusercontent.com/37363/79891789-c600db00-8401-11ea-8734-b558a0db17b6.png">

**Comment by tiff** [comment]
I was able to fix the issues with "ain't" mentioned above. See https://github.com/languagetool-org/languagetool/commit/918ea2384fe4ac9849b720a57006d0f5edaa941e#diff-2962df669a1a4fe505f24f8f14809affL1840-R1856
