### ISSUE TITLE
MIT_FREUNDLICHEN_GRUESSE not triggered on misspell

### ISSUE THREAD

**Issue by CoalaJoe** [languagetool-org/languagetool#279]
http://127.0.0.1:8001/?language=de-DE&text=Mit+freundlichen+gr%C3%BCssen

There is only a suggestion for the typo ss => ß but if you give the result back in, it finally triggers the MIT_FREUNDLICHEN_GRUESSE rule.

**Comment by danielnaber** [comment]
Well, I don't think it makes sense to add misspelling to all our rules. This is what we have the spell checker for.
