### ISSUE TITLE
[pt] accents not corrected

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2791]
User feedback via Google Store support:

> a extensão não está corrigindo alguns acentos. Por exemplo o da palavra MUSICA - Música gostaria de saber se devo fazer alguma configuração extra. 

@marcoagpinto @jaumeortola any idea whether this is a valid report and what we can do about it?

**Comment by tiff** [comment]
Another one:
> Não está corrigindo acentos de algumas palavras.
> Vídeo, musica.

**Comment by jaumeortola** [comment]
There is exactly the same issue in Spanish and Catalan. There are some rules for detecting the confusion musica (verb) / música (noun). The rule "Accentuation check" (which should be renamed "diacritics check" by the way) and some other rule could be adapted to Portuguese. 

There are already many rules in Portuguese for this kind of errors. Anyway, as "música" (noun) is much more frequent than "musica" (verb), we could just write more specific rules for this word. I will add some rules.

**Comment by marcoagpinto** [comment]
"musica" is also a verb: https://dicionario.priberam.org/musica

**Comment by marcoagpinto** [comment]
@jaumeortola 
Will you commit them to the pt grammar.xml?

**Comment by jaumeortola** [comment]
> Will you commit them to the pt grammar.xml?
Yes. I plan to write a rule that almost always recommends musico>músico, musica> música, with very few exceptions.

**Comment by marcoagpinto** [comment]
Thank you, @jaumeortola

**Comment by jaumeortola** [comment]
Done here: https://github.com/languagetool-org/languagetool/commit/c44fb86b7a7786302e5db432c79dc8867d765132

Expect many true positives, and very few false positives. Take a look at the regression tests, @marcoagpinto.

**Comment by marcoagpinto** [comment]
@jaumeortola 

Thanks!
