### ISSUE TITLE
[en] translations don't preserve capitalization

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2793]
<img width="400" alt="Bildschirmfoto 2020-04-24 um 13 06 59" src="https://user-images.githubusercontent.com/37363/80206421-89fd8e00-862c-11ea-9759-d297d96a7141.png">

**Comment by danielnaber** [comment]
Trying with this:, the bug seems to be fixed, so I'm closing this.

> Grandioses Tool. This is an English text.
