### ISSUE TITLE
[en] add "ok" / "okay" to coherency?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2799]
@MikeUnwalla do you think it makes sense to add "OK" and "okay" to the coherency.txt?

**Comment by MikeUnwalla** [comment]
@tiff, I think it's not a good idea to add to coherency because each term has more than one part of speech. Also, there is no way to deal with terms such as **OK button**, which should be out of scope.

**Comment by tiff** [comment]
Ok, thanks for your opinion. I'm closing this.
