### ISSUE TITLE
Support for using .langaugetool.cfg with languagetool-server.jar

### ISSUE THREAD

**Issue by tingley** [languagetool-org/languagetool#280]
Issue corresponding to [this thread](http://languagetool-user-forum.2306527.n4.nabble.com/Using-langaugetool-cfg-with-languagetool-server-jar-tc4642928.html) on the forums.
> I'm attempting to deploy LanguageTool in server mode for use by multiple users, with a single, centralized configuration.  I've done this successfully by configuring rules for multiple languages through the UI to create a ~/.languagetool.cfg, and then starting the server from the UI. 
>
> This works great, except for one thing: it requires the UI.  I'd like to do the same thing using languagetool-server.jar, so that I can wrap LT as a service and have it start automatically, etc. 
>
> However, when launched via the HTTPServer/HTTPSServer classes, it it looks like this configuration is ignored.  (The file is parsed, but ignored unless the internalServer flag is set -- see LanguageToolHttpHandler.java.) 

I have a patch for this, I'll open a pull request.

**Comment by danielnaber** [comment]
Closing this issue, as the pull request has been merged.
