### ISSUE TITLE
[en] false alarms TO_NON_BASE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2800]
> They sent claims to doctors that even made us stunned.

<img width="580" alt="Bildschirmfoto 2020-04-26 um 14 40 31" src="https://user-images.githubusercontent.com/37363/80307838-e5b24d80-87cb-11ea-842c-e3a3e91c2ba2.png">

> They wanted to know what happens to dreams that are not remembered anymore.

> He agrees to services, terms and conditions.

> Who we relate to makes a difference in how we develop and mature

> We really want to switch to hosted connections [MFU 2020-05-12: No error now]

**Comment by tiff** [comment]
> It was offered to grades 9-10.

**Comment by tiff** [comment]
> He was mean to kids.

**Comment by MikeUnwalla** [comment]
> This is similar to what happens to books: they become mouldy.
