### ISSUE TITLE
[pt-br] "planejamento"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2801]
Feedback by a user from Brazil

> Marcou “planejamento” como palavra arcaica, mas não é!

Is "planejamento" really archaic (in Brazil), @marcoagpinto ?

**Comment by tiff** [comment]
... and if so, can we suggest an alternative?

**Comment by marcoagpinto** [comment]
@tiff 

https://dicionario.priberam.org/planejamento

There is no mention in the Priberam dictionary about it being archaic.

**Comment by tiff** [comment]
Ok, so we should remove it from the rule, I guess?

**Comment by marcoagpinto** [comment]
Sure.

Where is it?

:-)

**Comment by marcoagpinto** [comment]
ahhhh... I believe I found it.... give me a minute

**Comment by tiff** [comment]
rule id ARCHAISMS

**Comment by marcoagpinto** [comment]
yes

Done:
https://github.com/languagetool-org/languagetool/commit/8d2696a6e8fcc244bccaca0871ea151f90fddb8a

**Comment by tiff** [comment]
Great, thank you so much
