### ISSUE TITLE
LO/OO spelling dialog doesn't work correct for LT-4.7+

### ISSUE THREAD

**Issue by yakovru** [languagetool-org/languagetool#2802]
"Ignore Once" work incorrectly in LO/OO for LT-4.7+.
If the text contains newline characters, an unexpected text change occurs when the button "Ignore Once" is clicked.
[LT bug_en.docx](https://github.com/languagetool-org/languagetool/files/4535752/LT.bug_en.docx)

![Text_before_change](https://user-images.githubusercontent.com/5228814/80312757-b6153c80-87ef-11ea-86a8-2c4125931f6a.jpg)

![Text_after_change](https://user-images.githubusercontent.com/5228814/80312743-a564c680-87ef-11ea-82a4-dc4bfcbf0705.jpg)

May be related to
https://github.com/languagetool-org/languagetool/issues/125

**Comment by FredKruse** [comment]
@yakovru: Did you use the spelling dialog or the context menu (right mouse click) to run "Ignore Once"?

**Comment by yakovru** [comment]
I use spelling dialog

**Comment by FredKruse** [comment]
This is a bug in the LO/OO spelling dialog box. It is not related to LT directly. There are two possibilities to solve the problem:

1. Address the bug to LibreOffice (As far as I know, there is no further development in OpenOffice).
2. Development of an own LT spelling and grammar checking dialog. This is a bigger project. I am thinking about that, but it will take some time.

**Comment by yakovru** [comment]
https://bugs.documentfoundation.org/show_bug.cgi?id=132922

**Comment by yakovru** [comment]
New comment in LO bugtracker
https://bugs.documentfoundation.org/show_bug.cgi?id=132922#c3

**Comment by FredKruse** [comment]
solved by issue #3250
