### ISSUE TITLE
[de] false alarm RUND_UM

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2818]
> Wirecard sieht sich durch den KPMG-Bericht hinsichtlich der Vorwürfe rund um mutmaßliche Bilanzfälschungen insgesamt entlastet.

<img width="869" alt="Bildschirmfoto 2020-04-28 um 11 21 55" src="https://user-images.githubusercontent.com/37363/80470561-7b6fe900-8942-11ea-8292-cc508b6826c7.png">

**Comment by f-knorr** [comment]
no longer reproducible.
