### ISSUE TITLE
Should we accept "tis"?

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2821]
> What would the rule editor do on tis warning?

Common misspelling of "this". Should we accept "tis" at all? Or could there be a rule?

**Comment by tiff** [comment]
I would suggest adding a rule that catches any use of "Tis" and "tis" (but not "TIS"). Through antipatterns we can avoid false alarms where "tis" was actually meant (rare cases I suppose).

**Comment by MikeUnwalla** [comment]
'tis' (plural of 'ti') is possible. It is a plant:
www.collinsdictionary.com/dictionary/english/ti
https://ahdictionary.com/word/search.html?q=ti
www.merriam-webster.com/dictionary/tis

For the literary 'tis (it is), Collins also suggests that the form without apostrophe is possible: https://www.collinsdictionary.com/dictionary/english/tis

The musical note ti is (I think) non-count only.

I will make a rule to say "make sure..."
