### ISSUE TITLE
Should we accept "er"?

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2822]
"er" is accepted as a word, but many words end with "er" and are still valid words once you remove the "er", making spaces accepted in e.g. "worship er" instead of "worshiper". I found ~ 4000 of those words. Should be keep accepting "er"?

**Comment by MikeUnwalla** [comment]
I think we should continue to accept 'er'. I will add a missing postag.

Also, 'Er' with initial caps is the chemical symbol for erbium. 'ER' is an abbreviation for Emergency Room (and other terms).

The suggestion  "worship er" is not good. Is it possible to prevent the spell checker from suggesting "X er"?

**Comment by MikeUnwalla** [comment]
@danielnaber , I propose to close this issue. Is that OK?

**Comment by danielnaber** [comment]
Sorry, "worship er" was not meant as a suggestion example, but as an example for an error we don't find. "ER" should be accepted, but "er" seems rare and very colloquial?

**Comment by MikeUnwalla** [comment]
It think that 'er' is no more rare or colloquial than many other interjections that LT accepts (um, uh, huh).

Possibly, a quick win is to have a rule that finds all POS=UH and tell people not to use the word in formal text. The rule could have exceptions for text within quote marks.

**Comment by danielnaber** [comment]
"er" is a more common suffix that leaves valid words when split from the end:

4219 matches for suffix er
136 matches for suffix um
3 matches for suffix uh
1 matches for suffix huh

What about a rule that finds "(word) er" and suggests "(word)er", with a lower priority than the spelling rule and maybe some antipatterns?

**Comment by MikeUnwalla** [comment]
> What about a rule that finds "(word) er" and suggests "(word)er",

Yes, that should be fine. I will do that.
