### ISSUE TITLE
Addin disables accessing Extended ASCII characters using ALT codes

### ISSUE THREAD

**Issue by McBobb** [languagetool-org/languagetool#2824]
While your app is active, I cannot use ALT+(4 digit code) to produce Extended ASCII characters like ½, —, °, etc.

When I hold the ALT key, as soon as I hit any numpad key (which you need to use to use ALT codes), my browser immediately jumps forward to the next tab

[Firefox Troubleshooting Info.txt](https://github.com/languagetool-org/languagetool/files/4549678/Firefox.Troubleshooting.Info.txt)

**Comment by tiff** [comment]
@McBobb I'm not sure if this is related to the add-on. can you still reproduce this when you disable/uninstall our add-on?

**Comment by tiff** [comment]
Closing this as we got no response from the issuer.
