### ISSUE TITLE
[fr] French punctuation rule - spaces before/after quotes, '?' '!' - option to disable

### ISSUE THREAD

**Issue by Anatoly-IVANOV** [languagetool-org/languagetool#2827]
The classical French rule (depending on the country, but mostly in France and Switzerland), calls for thin-space:

- around quotes
- before questions marks
- before exclamation mark
- before semi-column
- before column

That's cool in Adobe InDesign or Illustrator os some such pro application (hell, I'm a designer and typography nerd since 1999 and get paid per thin-space :D ).

HOWEVER: most non-pro apps and UIs today have no such option. As of now, Language Tool replaces a **thin** space with a **thick** (standard) space. Which is:

1) typographically incorrect
2) not beautiful

I think we'd all appreciate a way to disable this "should contain a whitespace" rule for French French. And even more importantly, for Canadian French.

See: https://fr.wikipedia.org/wiki/Ponctuation#En_français

— also, I might be missing something, because this LT rule appears and disappears for me, sorry for the confusion —

Might be related to #2191 .

**Comment by vkyfox** [comment]
Hello!
Maybe we could replace the non-breakable space that we suggest in those occurrences with a thin space if it has the same non-breakable propriety. Is there even a special character for it? What do you think @Anatoly-IVANOV?

**Comment by Anatoly-IVANOV** [comment]
That'd be cool!

If the font supports it (and it should).

Here's the spec: https://www.compart.com/en/unicode/U+2009

**Comment by vkyfox** [comment]
Is it non-breakable as well?

**Comment by Anatoly-IVANOV** [comment]
Seems like it, from my quick tests in Chrome's div contenteditable=true nodes.

**Comment by vkyfox** [comment]
Perfect then! I'll let you know here once I've fixed it.
Thank you for your feedback!

**Comment by Anatoly-IVANOV** [comment]
Thank _you_, @vkyfox !

Sorry I just can't jump into code… time crunched and would need to dust-off my Java basics, I guess. :D

**Comment by vkyfox** [comment]
And done! Thank you for your feedback @Anatoly-IVANOV

**Comment by Anatoly-IVANOV** [comment]
@vkyfox — I took some time to test it around, sorry for not replying immediately!

So far, so good! Even the dialogue box is perfect (espace fine non sécable).
![Screen Shot 2020-05-12 at 08 49 12](https://user-images.githubusercontent.com/19234031/81647741-d0752a00-942d-11ea-8da8-3f83c009d9d8.png)
