### ISSUE TITLE
[en] false alarm MUCH_UNCOUNTABLE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2828]
> Consumers get good or bad deals from sellers depending on (a) how much they know about the offerings of different firms and, conversely, (b) how much firms know about consumer preferences.

<img width="908" alt="Bildschirmfoto 2020-04-29 um 12 40 35" src="https://user-images.githubusercontent.com/37363/80587555-0d492600-8a17-11ea-9145-7a5e000617bb.png">

**Comment by MikeUnwalla** [comment]
Also, false alarm with a simpler version of the sentence:

> Consumers get good or bad deals from sellers depending on how **much** firms know about consumer preferences.
