### ISSUE TITLE
[DE] Imperativ-Lesart fehlt für "mach" und vermutlich andere (Fehlalarm trotz Apostroph)

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#2829]
Moin liebes LanguageTool-Team

![grafik](https://user-images.githubusercontent.com/40240507/80591475-0d98ef80-8a1e-11ea-94ba-3743d892c471.png)

Dallun sagt: „Vertraue mir. Freundschaft ist was Schönes und jetzt **mach’** dich **auf dem Weg** zur Schule. Du kommst sonst noch zu spät.“
LT: "Möglicherweise fehlende grammatische Übereinstimmung zwischen Subjekt und Prädikat (mach) bezüglich Person oder Numerus (Einzahl, Mehrzahl - Beispiel: 'Max bist' statt 'Max ist')."

In diesem Beispiel wird die Verbform bemängelt, obwohl für das fehlende "-e" ein Apostroph gesetzt wurde. Stattdessen wurde ein wahrer Fehler vergessen.

Dallun sagt: „Vertraue mir. Freundschaft ist was Schönes und jetzt **mache** dich **auf dem Weg** zur Schule. Du kommst sonst noch zu spät.“
Ersetzt man das Apostroph durch ein -e, wird der Fehler normal gefunden.

Bitte beheben.

Grüße Dallun511

**Comment by danielnaber** [comment]
Danke, sollte ab Übermorgen behoben sein. Betrifft leider sicher noch andere Verben, denn die Imperativ-Form fehlt oft im Lexikon. (Hier: `VER:IMP:SIN:SFT`)

**Comment by Dallun511** [comment]
Gut, ich werde mir mal demnächst meine Verben ansehen, die ich sehr häufig benutze, um danach zu überprüfen, ob ihr Imperativ eingetragen ist.

Wenn dieser nicht eingetragen ist, kommt das Verb in diese Liste #2838 
Dort habe ich schon "renn" und "mach" als abgeschlossen eingetragen. Weitere Verben werden folgen, sobald ich eines finde.

Die wichtigen Verben, die sehr häufig genutzt werden, haben dann voran.
