### ISSUE TITLE
Memory leaks LO v3.0

### ISSUE THREAD

**Issue by Yanpas** [languagetool-org/languagetool#283]
Using latest 3.0 version. LO 4.4.4.3
If I disable this extension - no problems.

Behavior:
1) Open LO Writer 136 MB RAM
2) Open Calc, Impress and Draw 200 MB RAM
3) Close Calc, Impress and Draw 183 MB RAM
4) Open in writer odt file (46kB) 231 MB RAM
5) Closed this doc 223 MB RAM
6) Open in writer 410kB ODT 936 MB RAM
7) Waiting 1 minute; Closing this doc; 937 MB RAM

Fresh booted system.

**Comment by danielnaber** [comment]
We're just an add-on in LO, so we cannot control when LO starts and stops our code or the JVM needed to run our code. You could open a bug report at LO, but I'm not sure if this is a bug: there are probably reasons to keep a JVM running and to accept the memory usage, e.g. improved performance.
