### ISSUE TITLE
user feedback het/de

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2831]
User feedback about error not found:

Gelet op het feit dat **het** firma bij het begin van

=> Gelet op het feit dat **de** firma bij het begin van

**Comment by baarsrj** [comment]
Should have been found. Adding a rule for it right now. Might need tuning, but that has to wait for tonight's run. Can't locally test it now without stopping the test that has to run a long time.

**Comment by baarsrj** [comment]
It is not eays, due to lots of exceptions, like 'het Koning Astridplein', while it is 'de keizer'. And ' het was gisteren', while it is 'de was'. Takes more time. To be continued in a week.

**Comment by baarsrj** [comment]
Most falses seem to have been killed
