### ISSUE TITLE
[en] not found: "Here#s"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2833]
> Here#s a link where you get

Not so uncommon, as on German keyboards `'` and `#` share the same key.

**Comment by MikeUnwalla** [comment]
@danielnaber , found by LT Premium.

![image](https://user-images.githubusercontent.com/5816160/80794836-c8e29500-8b92-11ea-87c4-fd817c7819b6.png)

If you want me to copy the Premium rule to open-source LT, tell me. Otherwise, please close this issue.

**Comment by danielnaber** [comment]
Oh, I should have noticed that. Please move the rule to Open Source.
