### ISSUE TITLE
[DE] Wörter ohne Token! (Imperativ von Verben)

### ISSUE THREAD

**Issue by Black56651** [languagetool-org/languagetool#2838]
Moin liebes LanguageTool-Team

Auf dieser Liste erscheinen nur Imperative von Verben, die keine Token/Tags haben.

[abgeschlossene Imperative] **#3907**

***
- [x] informier (informieren)
***
- [ ] verhaft (verhaften)
***
- [x] enttäusch (enttäuschen)
***
- [x] tausch (tauschen)
***
- [x] tauch (tauchen)
***
- [x] drück (drücken)
***
- [x] dreh (drehen)
***
- [ ] leg (legen)
***
- [x] pack (packen)
***
- [x] salutier (salutieren)
***
- [x] präsentier (präsentieren)
***
- [x] rüst (rüsten)
***
- [x] hoff (hoffen)
***
- [x] bezweifl (bezweifeln)
https://www.verbformen.de/konjugation/?w=bezweifeln
***
- [x] begeister (begeistern)
***
- [x] kämpf (kämpfen)
***
- [x] peitsch (peitschen)
***
- [x] stell (stellen)
***
- [x] servier (servieren)
***
- [x] erstatt (erstatten)
***
- [x] hör (hören)
***
- [x] verhandel (verhandeln)
***
- [ ] sichr (sichern)
- [ ] sichre (sichern)
***
- [x] versicher (versichern)
- [ ] versichr (versichern)
- [ ] versichre (versichern)
***
- [x] interpretier (interpretieren)
***
- [x] programmier (programmieren)
***
- [x] entwickel (entwickeln)
- [ ] entwickl (entwickeln)
***
- [x] reparier (reparieren)
***
- [x] spiel (spielen)
***
- [x] unterricht (unterrichten)
***
- [x] bau (bauen)
***
- [ ] verbesser (verbessern)
- [ ] verbessre (verbessern)
- [ ] verbessr (verbessern)
***
- [ ] heil (heilen)
***

Grüße Black5661

**Comment by Dallun511** [comment]
@danielnaber mir ist aufgefallen, dass sehr viele Imperative nachgetragen wurden.
Ich werde diese später abhaken.
