### ISSUE TITLE
LT 3.0 false warning 'unpaired symbol' 

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#284]
Sample text:
You can write 'http://' in front of 'www' to show…

LT error message:
1. Line 1, column 14
Message: Unpaired symbol: ''' seems to be missing (deactivate)

![false-warning-unpaired-symbol](https://cloud.githubusercontent.com/assets/5816160/8425982/9b7c40ee-1f03-11e5-9352-32499620cbd4.png)

**Comment by danielnaber** [comment]
Thanks for the report, this has been fixed now (at least for the simple cases where the opening quote is the same as the closing quote).
