### ISSUE TITLE
[de] "verswund" is tagged

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2840]
Das Wort:
> verswunden

hat bei uns Tagging:

<img width="717" alt="Bildschirmfoto 2020-04-30 um 17 23 11" src="https://user-images.githubusercontent.com/37363/80728587-63959200-8b07-11ea-887c-11f4d35d72dd.png">

Konnte dazu keine Quelle finden...

**Comment by danielnaber** [comment]
It's analyzed as `vers` + `wund`. I think we'll have to live with that unless we spend a lot of time into making the compound splitter more strict.

**Comment by Dallun511** [comment]
Das Wörterbuch (Rechtschreibung) kennt das Wort nicht, weswegen das kein Problem sein sollte.
