### ISSUE TITLE
[en] prohibit "somethings", "someones"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2841]
@MikeUnwalla currently "someones" has NNS and is not marked as a spelling mistake (at least in en-US). I couldn't find a source for this. 

Also, "somethings" and "anythings" is accepted (but not tagged).

Can we remove it?

**Comment by tiff** [comment]
All of them are not accepted in en-GB.

**Comment by MikeUnwalla** [comment]
@tiff, feel free to prohibit the plural readings. (I haven't checked, but I don't think those words are used as plurals.)
