### ISSUE TITLE
Command-line version of LT 3.0 puts the ^^^^ error marker in the wrong place

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#285]
When I run LT 3.0 with the following command
`java -jar languagetool-commandline.jar -l de-DE test.txt > out.txt`

out.txt contains the following text:
```
Working on test.txt...
1.) Line 1, column 25, Rule ID: SCHWAECHE_SUBST[7]
Message: Bitte prüfen Sie, ob 'Schwäche' hier als Substantiv gebraucht wird und daher großgeschrieben werden muss.
Suggestion: Schwäche
Das ist ein Zeichen von schwäche.
 Da hat er in der scheiße gesessen.
 Sie ha...
                        ^^^^^^^^                                             

2.) Line 2, column 18, Rule ID: IN_DER_KLEMME[1]
Message: Bitte prüfen Sie, ob 'Scheiße' hier als Substantiv gebraucht wird und daher großgeschrieben werden muss.
Suggestion: Scheiße
... ein Zeichen von schwäche.
 Da hat er in der scheiße gesessen.
 Sie hatte Kinder aus erster ehe.
...
                                                ^^^^^^^                                             
```
The ^^^^^^^^ do not identify the errors properly.

**Comment by danielnaber** [comment]
Could you provide the full test file you're using?

**Comment by janschreiber** [comment]
I sent it via e-mail, since I don't know how to attach files here.

**Comment by danielnaber** [comment]
Are you running this on Windows? The file you sent has Windows line ending, so it should work under Windows. It doesn't work for me under Ubuntu, not sure if it should considering the wrong line endings from Ubuntu's point-of-view.

**Comment by janschreiber** [comment]
Yes, I'm using Windows 7.

**Comment by danielnaber** [comment]
I think I could reproduce this on Ubuntu with `System.setProperty("line.separator", "\r");`. It might be fixed now, can you try again?

**Comment by janschreiber** [comment]
I'll have to wait for the nightly build. I can't compile on this machine.

Am 01.07.2015 17:59, schrieb Daniel Naber:
> I think I could reproduce this on Ubuntu with
> |System.setProperty("line.separator", "\r");|. It might be fixed now,
> can you try again?
>

**Comment by danielnaber** [comment]
Can you close this issue if it's fixed now?

**Comment by janschreiber** [comment]
I'll test it tonight.

**Comment by janschreiber** [comment]
It's fixed in last night's build.
