### ISSUE TITLE
[de] false alarm VERB_AGREEMENT

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2851]
> Ich hoffe Du auch.

<img width="418" alt="Bildschirmfoto 2020-05-03 um 15 08 20" src="https://user-images.githubusercontent.com/37363/80915070-f163be00-8d4f-11ea-91b4-dca4828143f9.png">

**Comment by tiff** [comment]
<img width="517" alt="Bildschirmfoto 2020-05-03 um 15 09 10" src="https://user-images.githubusercontent.com/37363/80915085-10fae680-8d50-11ea-9eb7-4df4c8ace4fd.png">

**Comment by tiff** [comment]
<img width="450" alt="Bildschirmfoto 2020-05-03 um 15 10 15" src="https://user-images.githubusercontent.com/37363/80915106-3556c300-8d50-11ea-866c-71f70492985b.png">

**Comment by danielnaber** [comment]
- [x] Ich hoffe Du auch.
- [ ] um 10 Uhr geh ich essen.
- [x] Hab einen schönen Sonntag.

**Comment by danielnaber** [comment]
Closing, these all seem to be fixed.
