### ISSUE TITLE
[fr] False alarm : Nombre pluriel suivi du singulier

### ISSUE THREAD

**Issue by bperel** [languagetool-org/languagetool#2853]
> Le terminal 4 inauguré le 29 avril 2019

LanguageTool suggests adding an "s" to "inauguré" because it thinks that it should be accorded with "4", which is incorrect because "Terminal 4" is the name of the terminal so it shoudn't be accorded.

**Comment by tiff** [comment]
@vkyfox rule is "ACCORD_NOMBRE" (sub id 2)

**Comment by vkyfox** [comment]
Added correction to pull request.

**Comment by bperel** [comment]
Should this be closed?
