### ISSUE TITLE
Ausnahmen für case rule durch POS-Tags verallgemeinern

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#286]
Aus meiner Sicht könnte es wünschenswert sein, mit Hilfe von POS-Tags allgemein formulierte Ausnahmen von der case rule zuzulassen, insbesondere für substantivierte Adjektive, denn da gibt es zur Zeit noch viele Fehlalarme. Zur Zeit haben wir in case_rule_exceptions.txt z. B. folgende Ausnahmen: 
* nichts Besseres
* nichts Neues
* nichts Schöneres
* nichts Wichtigeres

Allgemeiner könnte man solche Ausnahmen vielleicht so fassen: 
kaum|wenig|etwas|nichts|viel - ADJ:NOM:SIN:NEU.* - VER:.*
Das deckt z. B. Fälle ab wie "Ich kann der Sache nicht viel Positives abgewinnen", trotzdem schlägt die case rule noch an bei *"es gab viel Positives Feedback".

**Comment by janschreiber** [comment]
Siehe auch http://languagetool-user-forum.2306527.n4.nabble.com/Feststehende-Begriffe-tp4642612p4642977.html

**Comment by danielnaber** [comment]
Ist nicht so einfach wie gedacht: `Positives` (großgeschrieben) hat kein POS-Tag, allein deshalb kann man dafür auch kein Antipattern schreiben. Für `case_rule_exceptions.txt` habe ich jetzt immerhin mal auf reguläre Ausdrücke umgestellt. Und komplexere Ausnahmen kann man jetzt unter https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CaseRule.java#L61 einbauen.
