### ISSUE TITLE
Adding words to LibreOffice personal dictionary

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#2874]
@FredKruse 

Hello!

The adding of words doesn't seem to work with words which have a hyphen.

For example:
e-learning

I added this word both to the Portuguese spelling.txt and added.txt and I installed the nightly add-on for LibreOffice and the word is still flagged as a typo.

**Comment by marcoagpinto** [comment]
Ahhh..

Somehow it just doesn't recognise the word after the hyphen:
"e-learning"

It flags "learning" as unidentified and ignores the "e-".

It is strange.

**Comment by FredKruse** [comment]
I tested the dictionary. It stores the words with hyphen. For German texts it seems LT runs without any problem. I typed in e-learning and switch to Portuguese. There is shown an error, but it seems to be a LT problem: Erro tipográfico. I don't speak Portuguese, but it seems to be no spelling error.
