### ISSUE TITLE
[en] Word not flagged

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#2876]
@MikeUnwalla 

Hello!

The following sentence doesn’t flag the error “don’t aren’t”:
“Now most videos there don’t aren’t recognised by the add-on.”

**Comment by tiff** [comment]
If it's ok, I will have a look. Looks easy to do :)

**Comment by tiff** [comment]
Implemented via https://github.com/languagetool-org/languagetool/commit/7ee379d9cc660654506f8318d617d92963d131ab#diff-2e4126723233b9f262d8cd599fdaee03R11512-R11535
