### ISSUE TITLE
[fr] sentence splitting is wrong

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2877]
This is one sentence:
> Le discours de E. Philippe devrait nous éclairer (un peu, beaucoup, ... ?) sur ce qui nous attend.

However, LT splits it into 4 sentences and therefore creates false positives.

**Comment by tiff** [comment]
@jaumeortola @danielnaber do you have an idea?

**Comment by tiff** [comment]
A similar formatted sentence in English is treated as one sentence:
> I'm E. Philippe (a little, more, ... ?) something, something.

How do we know which segmentation rules were applied?

**Comment by tiff** [comment]
Another sentence with incorrect sentence splitting:
> Ph.D. est un groupe de musique britannique, connu notamment pour son tube I Won't Let You Down, qui a atteint le UK Top 10 en avril 19821, bien que la chanson ait déjà connu un certain succès l'année précédente dans le reste de l'Europe

Can we just adopt the segmentation rules from English to French?

**Comment by danielnaber** [comment]
> How do we know which segmentation rules were applied?

You could try adding a break point in net.loomchild.segment.srx.RuleMatcher.find().
