### ISSUE TITLE
[pt] feedback GENERAL_VERB_AGREEMENT_ERRORS

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2878]
From a user:
> In the Portuguese sentence:
> "As pessoas no meu trabalho infelizmente não falam Alemão, apenas português."
> LT thinks the ver "falar" has "trabalho" as the subject. In fact, the subject is "as pessoas".
> LT suggests changing the verb to the singular form, because "trabalho" is singular. But the correct is the plural form as it is.

**Comment by marcoagpinto** [comment]
@tiff 

I don't have a clue yet on how to deal with such a large set of words

**Comment by marcoagpinto** [comment]
```
@tiff 

What about this approach?:

      <antipattern>
          <token postag='SENT_START'/>
           <token>"as" (get postag)</token>
           <token>"pessoas" (get postag) </token>

            <token max="1" postag="V*" postag_regexp="yes"/></token>
            AND postag=falam (replace falam with postag)

           <token regexp='yes'>[.!?]</token>
           <token postag='SENT_END'/>
     </antipattern>
```
How do I code it properly?

Thanks!

**Comment by marcoagpinto** [comment]
@tiff 
My doubt above is the token max "1" and the use of AND VERB= blah blah regarding the max

**Comment by marcoagpinto** [comment]
@yakovru 
@jaumeortola 
@danielnaber 

Could one of you help me with the antipattern above?

Thanks!

**Comment by marcoagpinto** [comment]
Ahhhh... it was easier than I thought!

Fixed: https://github.com/languagetool-org/languagetool/commit/18d5b7dbc8ebcbeb2862a08f4b5fcc818bceaacf
