### ISSUE TITLE
Use continuous integration against Windows

### ISSUE THREAD

**Issue by sils1297** [languagetool-org/languagetool#288]
Would be nice to let your users know that LanguageTool works reliable against linux and windows. On top of your existent Travis CI I'd recommend using AppVeyor for windows integration. We're doing the same at the coala project (https://github.com/coala-analyzer/coala/), I'd be happy to help out here and there if questions arise although I don't have the time to do that for you.

**Comment by danielnaber** [comment]
Sorry, closing the "it would be nice" issues that nobody seems to be working on.
