### ISSUE TITLE
[en] false alarm TIS

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2882]
> Anyone, ‘tis all

<img width="447" alt="Bildschirmfoto 2020-05-08 um 08 33 15" src="https://user-images.githubusercontent.com/37363/81377906-adcdd300-9106-11ea-8616-c78e158be763.png">

@MikeUnwalla I think we just need to add an antipattern for all apostrophes.

**Comment by MikeUnwalla** [comment]
@tiff , the first AP in the rule should prevent this false alarm. I don't know why it does not work. Can you look to see if I made a stupid mistake?

**Comment by MikeUnwalla** [comment]
@tiff , don't look. I found my stupid mistake.

**Comment by MikeUnwalla** [comment]
@tiff , I changed the rule and made it ignore all apostrophe-like marks. Other rules should find an incorrect apostrophe. Refer to  #2890.
