### ISSUE TITLE
[pl] Missing words 

### ISSUE THREAD

**Issue by kam193** [languagetool-org/languagetool#2885]
In Polish dictionary some words are missing. 

Following are international/name marked by LanguageTool as spelling mistake: 
- [x] SSH
- [x] GPG

Open question: is there any easy way to report missing worlds? Is adding to the personal dictionary a solution to improve LT? I mean: are words from user's dictionary collected and used to improve base LT dictionary, or we should report every missing word as an issue?

**Comment by tiff** [comment]
@kam193 thanks for your feedback. "SSH" is already in our global spelling file (it was recently added): 
https://github.com/languagetool-org/languagetool/blob/master/languagetool-core/src/main/resources/org/languagetool/resource/spelling_global.txt#L679

I will add GPG as well. Feel free to collect and report missing words here. I'd be happy to add them.

**Comment by kam193** [comment]
Thanks for update and change the title :D
