### ISSUE TITLE
[DE] LT-Fermeldungen Mai 2020

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#2888]
Moin liebes LanguageTool-Team

![grafik](https://user-images.githubusercontent.com/40240507/81428992-6cb4dd80-915d-11ea-917f-c8c0ee29d3ce.png)
Diese Fehlermeldung kam beim normalen Tippen.
Es waren fünf Dokumente gleichzeitig offen.

Grüße Dallun511

**Comment by FredKruse** [comment]
@Dallun511 Der Fehler sollte behoben sein. Bitte mit dem morgigen release testen.
