### ISSUE TITLE
[en] Smart quote link

### ISSUE THREAD

**Issue by shamisen** [languagetool-org/languagetool#289]
The anchor link "https://en.wikipedia.org/wiki/Quotation_mark#Typing_quotation_marks_on_a_computer_keyboard" associated to smart quote opening and closing messages does not exist anymore, e.g.:
> Message: Use a smart opening quote here: “. (deactivate) 
> Correction: “ 
> Context: "test" 
> More info: https://en.wikipedia.org/wiki/Smart_quote#Typing_quotatio...

**Comment by danielnaber** [comment]
Thanks for notifying us. Can you suggest an alternative anchor link in that document?

**Comment by shamisen** [comment]
Dear Daniel, you are welcome. It is I who should thank you and the development team for such useful tool :)
I guess the link https://en.wikipedia.org/wiki/Smart_quote#Electronic_documents could be appropriate.

**Comment by danielnaber** [comment]
Thanks, I've used that new URL.
