### ISSUE TITLE
[en] false alarms and missing suggestion THERE_RE_MANY

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2897]
* [ ] There are very few left by what I understand.

* [ ] There are only a few of them

* [ ] There are Christmas, Easter and Mother's Day.

* [ ] There are a few letter sounds we can use.

* [ ] There are a group of people.

<img width="519" alt="Bildschirmfoto 2020-05-11 um 08 09 17" src="https://user-images.githubusercontent.com/37363/81529276-d6e8a080-935e-11ea-85a2-1e613af2607f.png">

@MikeUnwalla I'm assigning this to you, as it is kind of a follow-up of https://github.com/languagetool-org/languagetool/issues/2787

**Comment by MikeUnwalla** [comment]
Also false negatives caused by this exception:
`<exception regexp="yes">variety|number|couple|pair|boatload|litany|lot</exception><!-- there are a number of -->`
