### ISSUE TITLE
Using Gradle instead of Maven

### ISSUE THREAD

**Issue by DoS007** [languagetool-org/languagetool#290]
The title says it already. Gradle is shorter, clearer more powerful.

**Comment by danielnaber** [comment]
See http://www.mail-archive.com/languagetool-devel@lists.sourceforge.net/msg03361.html. If you're willing to do the complete migration including stuff like Java Webstart that would be welcome.

**Comment by miurahr** [comment]
I have a fork project which has been migrated on Gradle.  I think it is good start point for person who want to support Gradle for LanguageTool.

See https://github.com/miurahr/languagetool/tree/omegat-6.5
