### ISSUE TITLE
[fr] word in spelling.txt still marked as spelling error

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2902]
It seems that words that are in our French spelling.txt and that are used at the beginning of a sentence (and therefore capitalized) are still marked as spelling error.

Example: We have the word "déconfinement" in our spelling.txt, but if you use it at the beginning of a sentence it is still marked as a spelling error.

<img width="465" alt="Bildschirmfoto 2020-05-11 um 11 33 17" src="https://user-images.githubusercontent.com/37363/81546840-3c4a8a80-937b-11ea-89ec-60a050c06364.png">

**Comment by danielnaber** [comment]
Fixed the easy way, i.e. assuming that words at position 0 are at sentence start and can thus be uppercased. Not always true (e.g. then there's a quote), but good enough for now.

**Comment by jaumeortola** [comment]
Hunspell is not used anymore in French.
