### ISSUE TITLE
[fr] start using multiwords.txt

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#2903]
Instead of adding multi-words as exceptions in rules (i.e. `social media`, `National Geographic`), it would be much better to use the file multiwords.txt. This way the added multi-words can be re-used in all rules, and they also can be used as exceptions to the spelling rules. 

Multiwords.txt can be used in different ways:
* You can remove or not the tags assigned to the tokens (if any). I prefer to remove automatically all the other tags. If the tagging depends on the context, then it should be done in disambiguation.xml, not in multiwords.txt.
* The spelling rules can be configured to ignore all properly tagged words, and multi-words will be ignored. I think that is a good idea. 

If it's OK, I can prepare it to work that way. @tiff @dpelle @vkyfox

**Comment by tiff** [comment]
Sounds good to me

**Comment by vkyfox** [comment]
Sounds good to me as well.

**Comment by jaumeortola** [comment]
Currently, multiwords.txt is used for tagging words with apostrophe. We need to do this differently. My proposal is to tokenize the words this way: `<token>l'</token><token>oeil</token>` in the tokenizer, and tag them appropriately. I can take care of it (it is already done this way in other languages). I will take care also of making the adaptations in the rules. Is that okay, @dpelle?

**Comment by jaumeortola** [comment]
The branch with the new tokenizer is here: https://github.com/languagetool-org/languagetool/commits/fr-tokenizer
