### ISSUE TITLE
Example of russian self-descriptive text with common errors

### ISSUE THREAD

**Issue by socketpair** [languagetool-org/languagetool#291]
Правила русского языка для учивших, забывших и никогда не знавших.

1. Помните о том, что в большинстве случаев связку «о том» можно исключить. 
2. Страдательный залог должен быть избегаем. 
3. Уточнения в скобках (хоть и существенные) бывают (обычно) излишними. 
4. Плохо зная грамматику, сложные конструкции должны употребляться с осторожностью. 
5. Что касается незаконченных предложений… 
6. Тех, кто заканчивает предложение предлогом, посылайте на. Не грубости ради, но порядка для. 
7. Предложение из одного слова? Плохо. 
8. И не начинайте предложение с союза. 
9. НИКОГДА не выделяйте слова заглавными буквами. 
10. Провиряй по словарю напесание слов. 
11. Метафора — это гвоздь в ботинке, и лучше её выполоть. 
12. Преувеличение в миллион раз хуже преуменьшения. 
13. Ненужная аналогия в тексте — как шуба, заправленная в трусы. 
14. Не применяйте длинные слова там, где можно применить непродолжительнозвучащие. 
15. Кому нужны риторические вопросы? 
16. Маленькое замечание о повторениях, которые иногда встречаются в статьях, которые появляются в изданиях, которые и так переполнены цитатами, которые иногда затуманивают мысль, которую хотел высказать автор, о которой мы и хотели сделать это замечание. 
17. Сюсюканье — фу. Оставь его лялечкам. 
18. Позаботься о благозвучии фразы, у тебя ж опыта больше. 
19. Небезинтересно было бы взымать штраф с безолаберных за неверное написание гласных после приставок. 
20. Не следует пытаться не избегать двойных отрицаний.
21. Не ставьте два "не" подряд, если это не необходимо. 
22. У слова "нет" нету форм изменения. 
23. Коллеги обращения надо как-то выделять. 
24. Которые являются придаточными предложениями, составлять надо правильно. 
25. Мы хотим отметить, что менять лицо, от имени которого ведётся изложение, автор этих строк не рекомендует. 
26. Заканчивать предложение местоимением – дурной стиль, не для этого оно. 
27. Если неполные конструкции, – плохо. 
28. Правило гласит, что "косвенная речь в кавычки не берётся". 
29. Числительные до 10-ти включительно лучше писать прописью. 
30. Склонять числительные можно сто двадцать пятью способами, но только один из них правильный 
31. Сдержанность изложения – всегда абсолютно самый лучший способ подачи потрясающих идей. 
32. Будьте более или менее конкретны. 
33. Слов порядок речи стиля не меняет? 
34. Это тебе, автор, (нельзя прерывать повествование в неожиданном месте) понятно о чём пойдёт дальше речь, но пожалей людей, не вынуждай перечитывать. 
35. Применяя деепричастный оборот всегда выделяйте его запятыми. 
36. Ставьте правильные чёрточки-тире длинное, с пробелами, а дефис чуть — чуть покороче, без пробелов.
37. Ответ отрицательный на вопрос о том, ставится ли вопросительный знак в предложении с вопросительной косвенной речью? 
38. Повторно повторять все повторяющиеся однокоренные слова – это тавтология – лишнее излишество.

**Comment by socketpair** [comment]
Не плохо бы чтобы ваша тулза умела такое находить! Текст взят из пабликов в интернете, но тем не менее, содержит годные сведения о том какие ошибки нужно проверять и сама является примером таких текстов.

**Comment by yakovru** [comment]
Не все из этих примеров можно распознать с помощью правил. Однако, я создал правила для примеров № 6,21,22,26, которые войдут в версию 3.1 LT.
Некоторые ошибки из предложенного списка определяются и текущей версией LT 3.0.

**Comment by socketpair** [comment]
А можно тогда список "недоделок" ? я их вынесу в отдельную задачку.

**Comment by socketpair** [comment]
С помощью этого списка я хотел указать на типичные проблемы в текстах. Если пункты этого списка не распознаются -- ничего страшного.

**Comment by yakovru** [comment]
Наиболее интересным для анализа является 35 пример. Но необходимые механизмы пока не реализованы в ядре LT.

**Comment by yakovru** [comment]
Добавил  правила для примеров №29 и №1.

**Comment by socketpair** [comment]
Переоткройте, пожалуйста, так как не все пункты закрыты.

**Comment by yakovru** [comment]
Создал новую заявку по пункту 35.
https://github.com/languagetool-org/languagetool/issues/304

По остальным пунктам списка ошибки либо определяются существующими правилами,  либо плохо формализуются для их обработки.
