### ISSUE TITLE
[en] false alarm ALLOW_TO_DO

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2919]
> Spacing the plants three feet apart allows them **room** to grow.

> The uses allowed **are** those listed above

> The security guard thought nothing of it since he had entered the correct code that allowed him **entrance**.

<img width="569" alt="Bildschirmfoto 2020-05-12 um 18 19 16" src="https://user-images.githubusercontent.com/37363/81719242-1b6a5e00-947d-11ea-8373-fc50ac7674af.png">

**Comment by MikeUnwalla** [comment]
Partly caused by incorrect tagging in PRP_NN_VBP.
