### ISSUE TITLE
spelling.txt does nothing on OpenOffice 4.1.1

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#292]
If you well remember, a couple of days ago or so I added words to pt_PT (Portuguese) in:
- spelling.txt
- replace.txt

Minutes ago I installed the latest daily build and this only works in the stand-alone tool.

If in OpenOffice I write, for example:
"Onde estão os devices?"
The word "devices" is marked as a typo and there is no suggestion to replace it with the word "dispositivos".

**Comment by danielnaber** [comment]
If OO marks it as a typo that's a OO feature. The OO underline of the typo probably overwrites all the errors LT finds (you cannot have two underlines under one word). I don't see what we could do against that.

**Comment by marcoagpinto** [comment]
Daniel,

I have just spoken with JZA (Alexandro Colorado from Apache Foundation) on IRC.

He told me that the best to do is to use wordbooks:
[18:15] <JZA> they are the user-defined dictionaries.
[18:16] <JZA> Tools -> options -> Language Settings -> Writing Aids -> User-defined Dictionaries.

Could LanguageTool automatically create a wordbook for each language based on the lists we created on the .txt's?

It seems like a possible solution.

Thanks!

**Comment by danielnaber** [comment]
I don't know, if there's an API for that it might be possible (I don't have to do this, or to research how it could be done).

**Comment by marcoagpinto** [comment]
Erack from LibreOffice told me moments ago on IRC after I asked him: "Is there an API for LO that allows to create wordbooks?"
[17:28] <@erAck> marcoagpinto: looks like http://api.libreoffice.org/docs/idl/ref/interfacecom_1_1sun_1_1star_1_1linguistic2_1_1XConversionDictionaryList.html
[17:29] <@erAck> marcoagpinto: or somethig else of http://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1linguistic2.html

**Comment by FredKruse** [comment]
Local temporary dictionaries are added to LT. They are loaded only for used languages inside the text, and they are loaded only once. The dictionary is generated from the words inside the file added.txt. The  words of the spelling.txt are added too. The spelling.txt exist e.g. for Portuguese but not for e.g. English or German.
@marcoagpinto: Please test the new feature for a Portuguese document.
@danielnaber: in English and German there exist a file spelling.txt in the subdirectory hunspell. This subdirectory is not included in the office-extension. Are there additional words in this file or contains the added.txt all needed words?

**Comment by danielnaber** [comment]
`added.txt` is for spelling only and has no impact on spell checking (for most languages). So yes, `spelling.txt` would be needed. But even then, LT has made some minor changes made to de_DE.dic, so you cannot get 100% the behavior from LT, unless we include all the hunspell dicts (making the download much larger).

**Comment by marcoagpinto** [comment]
@FredKruse 

It worked partially.

What is the criterium for the words from spelling.txt to appear in LibreOffice.

I copied and pasted the words below from PT spelling.txt:
```
off
on
OpenPGP
overwrite
PDA
PDAs
petabit
petabits
petabyte
petabytes
PGP
Pootle
PowerPC
SeaMonkey
SEO
SSL
tablet
tablets
tag
tags
template
templates
terabit
terabits
terabyte
terabytes
WebTranslateIt
Xubuntu
yottabit
yottabits
yottabyte
yottabytes
zettabit
zettabits
zettabyte
zettabytes
```

A few still appeared as typos:
OpenPGP
overwrite
SEO
SSL
WebTranslateIt

But your idea is excellent.

Thank you for the good work!

**Comment by yakovru** [comment]
I think that custom dictionary that is created in LO should consist of words from the /hunspell/spelling.txt , but not from added.txt

**Comment by FredKruse** [comment]
A bug was fixed in adding spelling.txt. Also, hunspell/spelling.txt was added. In addition, for local variants the hunspell/spelling_LANGUAGE-COUNTRY.txt and the hunspell/spelling-LANGUAGE-COUNTRY.txt was added (LANGUAGE and COUNTRY stands for the two character code).
@marcoagpinto and @yakovru: Please test and close issue, if it works.

**Comment by FredKruse** [comment]
see #3202
