### ISSUE TITLE
[en] wrong tagging JJ_NN_JJ

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2921]
> Generally speaking, any talents that happen after an enemy dies are too slow to matter.

"enemy" is only tagged as "JJ".

**Comment by tiff** [comment]
> It’s also handy to see how the cost of a given service increases as the month goes by.

"service" is only JJ

**Comment by MikeUnwalla** [comment]
Related tagging error in NNS_ARE_WERE. Must correct this to make an AP in JJ_NN_JJ.
