### ISSUE TITLE
[en] incorrect tagging "E_NP_VBP"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2923]
> A martial arts strike

"strike" is only tagged as VBP

**Comment by tiff** [comment]
Same:
> You would need a simple mains relay such as

"relay" is only VBP

**Comment by tiff** [comment]
@MikeUnwalla here's another one:
> I don’t know of any way to trigger a Synthetics check programmatically.

"check" is only VBP

**Comment by tiff** [comment]
And: 
> I agree that this would be a useful Insights feature.

**Comment by tiff** [comment]
And:
> It was 15 minutes too long.

"long" is only VBP

**Comment by tiff** [comment]
> My biggest concern with smart switches is that technology makes advancements too fast.

"fast" is VBP

**Comment by MikeUnwalla** [comment]
@tiff,

> I agree that this would be a useful Insights feature.

I can't see a problem.

**Comment by tiff** [comment]
Oh, ok, then feel free to ignore this sentence.
