### ISSUE TITLE
Fehlalarm in der Web-Version

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#293]
Siehe Screenshot: ![lt-err](https://cloud.githubusercontent.com/assets/4381288/8889429/dfbc29fa-32da-11e5-8773-b70b8df9aff5.png)

**Comment by janschreiber** [comment]
In der Desktopversion scheint das Problem nicht aufzutreten.

**Comment by danielnaber** [comment]
Might be a problem with invisible special characters or so, because I cannot reproduce the problem. Can you, if you enter the text again (not by copy and paste)?

**Comment by janschreiber** [comment]
Indeed, it's gone now. Sorry for the false alarm.
