### ISSUE TITLE
[es] "Normalito" (Normal + diminutive) is detected as wrong.

### ISSUE THREAD

**Issue by dmarman** [languagetool-org/languagetool#2934]
![image](https://user-images.githubusercontent.com/19510612/81959795-476a1880-9610-11ea-8a8c-c550d5c444cf.png)

"Normalito" is a correct word for Spanish.
"Norma lito" doesn't make sense as a replacement nor is correct in Spanish.

Normal = Normal + -ito(diminutive)

**Comment by jaumeortola** [comment]
Thanks. Added to the dictionary. I will remove also the verb 'litar', which is very unusual.
