### ISSUE TITLE
[pt] suggestion same as underlined text (irregular participles)

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#2938]
> A piscina foi enchida o mês passado.

`IRREGULAR_PAST_PARTICIPLES` matches at "foi enchida", but the suggestion is again "foi enchida".

**Comment by marcoagpinto** [comment]
@danielnaber 

I will take a look at it tomorrow or so.

**Comment by jaumeortola** [comment]
It seems difficult or impossible to convert between regular and irregular participle forms with simple regular expressions. Unfortunately they have the same POS tag. 
I would create a Java filter that makes the conversion in both senses and that can be used in different rules. The filter would do this:
1. Check if the participle is regular and convert it to irregular, or
2. Check if the participle is irregular and convert it to regular.

**Comment by marcoagpinto** [comment]
@jaumeortola 

I don't know Java :(

**Comment by jaumeortola** [comment]
@marcoagpinto I will write the Java filter and you will adjust the XML rules.

**Comment by marcoagpinto** [comment]
Thank you!

**Comment by jaumeortola** [comment]
It seems that some irregular participle forms are tagged so in the dictionary, but not all. We need a complete list of regular/irregular participles. Can we take this list of "verbos abundantes"? http://radames.manosso.nom.br/linguagem/gramatica/morfologia/verbos-abundantes/

**Comment by marcoagpinto** [comment]
@jaumeortola 

Sure, I will do it tomorrow morning :)

**Comment by jaumeortola** [comment]
@marcoagpinto Please, watch the test results after this change. I can't say anything about the exceptions to these rules (see: https://ciberduvidas.iscte-iul.pt/consultorio/perguntas/os-participios-passados-regulares-e-irregulares/20960).

**Comment by marcoagpinto** [comment]
@jaumeortola 

I gave a quick look in the diffs and it seemed okay, I guess :-)
