### ISSUE TITLE
Inefficient code in rule timing

### ISSUE THREAD

**Issue by arysin** [languagetool-org/languagetool#2943]
https://github.com/languagetool-org/languagetool/blob/2b71bc2e57d7e0459438d4907518fa148bfc901b/languagetool-core/src/main/java/org/languagetool/JLanguageTool.java#L966

Hey @danielnaber @fabrichter 

I was profiling the code recently and found that this line has performance problem - it calls analyzedSentence.getText().length() for every rule even if we don't do any logging. Note that analyzedSentence.getText() is not trivial code - it appends all token in the sentence together before returning the length. So we are concatenating token strings potentially hunderds of times. BTW we're also concatenating debug string (with +) in RuleCheckTimeMessage() constructor even if logging is off.

We could just calculate sentence length once before the loop (which I could do) but it's also better to move all logging construction inside the logger so it only creates strings if logging is happening (which is a bit more involving).

**Comment by danielnaber** [comment]
Thanks for noticing. The code was outdated anyway, I have removed it (https://github.com/languagetool-org/languagetool/commit/553ee42c48cde2ce6ee6356e307a50a6391f8e35).
