### ISSUE TITLE
UPPERCASE_SENTENCE_START false positive for (sub)species abbreviations

### ISSUE THREAD

**Issue by Mailaender** [languagetool-org/languagetool#295]
This is an issue in scientific texts using `spp.` (species pluralis) frequently.

Example:

> Mit Erde und Staub belastete Lebensmittel können Bacillus spp. tragen.

It is a Java rule. Not sure how to add this as an exception.

**Comment by danielnaber** [comment]
If `spp.` is a common abbreviation, you can add it to `segment.srx` (search `Dez` in that file to get roughly to the right place).

**Comment by Mailaender** [comment]
I knew there had to be some kind of list for exceptions. Filed https://github.com/languagetool-org/languagetool/issues/296.

**Comment by danielnaber** [comment]
Feel free to commit directly.
