### ISSUE TITLE
[pt-br] The adverb "daqui" not always requires preposition

### ISSUE THREAD

**Issue by hmslima** [languagetool-org/languagetool#2950]
Test this passage from the Bible:

> Respondeu Jesus: O meu reino não é deste mundo; se o meu reino fosse deste mundo, pelejariam os meus servos, para que eu não fosse entregue aos judeus; mas agora o meu reino não é daqui.

LanguageTool suggests replacing "daqui" for "daqui a", but as far as I know, this use of the word "daqui" is correct, it's like the expression "from here" from English.

**Comment by marcoagpinto** [comment]
Fixed: https://github.com/languagetool-org/languagetool/commit/140b37eb51222d9281a61536be46eacf970dd87d

**Comment by marcoagpinto** [comment]
Also improved it also to accept ",": https://github.com/languagetool-org/languagetool/commit/10eb0993b319ada0f3d349b2596bac6539b97973
