### ISSUE TITLE
LT 4.9.1 is missing in Maven Central

### ISSUE THREAD

**Issue by valentjn** [languagetool-org/languagetool#2957]
LT 4.9.1 seems to be missing in Maven Central. According to http://wiki.languagetool.org/how-to-make-a-languagetool-release, new releases should be uploaded there. Does this only apply to major/minor point releases like 4.9, and not to patch releases like 4.9.1?

Related: #2803

**Comment by danielnaber** [comment]
The next release on Maven will indeed be 5.0.

**Comment by valentjn** [comment]
Too bad. Thanks anyway!

**Comment by danielnaber** [comment]
BTW, 5.0 is just a few weeks away: http://wiki.languagetool.org/roadmap
