### ISSUE TITLE
[de] incorrect offset calculation

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2958]
> Er leitet seit 2007 das Internetportal wirtschafts­Wunder.

![Bildschirmfoto 2020-05-22 um 15 16 18](https://user-images.githubusercontent.com/37363/82671606-6afc1700-9c3f-11ea-9946-21d0a0384f81.png)

The "r" is not covered by the marker.

Most likely because "wirtschaftsWunder" contains a soft hyphen (invisble character) https://en.wikipedia.org/wiki/Soft_hyphen

**Comment by jaumeortola** [comment]
It is fixed, thanks to https://github.com/languagetool-org/languagetool/pull/6932

![imatge](https://user-images.githubusercontent.com/4289501/180758740-807b771d-b276-4cb4-91eb-086c8a806642.png)
