### ISSUE TITLE
[en] false alarms THERE_RE_MANY

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2966]
> There are only few who do this.

![Bildschirmfoto 2020-05-25 um 07 17 51](https://user-images.githubusercontent.com/37363/82780565-e7694280-9e57-11ea-8fb3-567a720fef00.png)

> There are a few out there.

![Bildschirmfoto 2020-05-25 um 07 18 45](https://user-images.githubusercontent.com/37363/82780595-fc45d600-9e57-11ea-9c3f-a9955705703b.png)

> There are several, including one by Millais. 

![Bildschirmfoto 2020-05-25 um 07 19 18](https://user-images.githubusercontent.com/37363/82780618-0ff13c80-9e58-11ea-9034-22f49a87b5a9.png)

> There are just the two of us here.

![Bildschirmfoto 2020-05-25 um 07 19 39](https://user-images.githubusercontent.com/37363/82780633-1ed7ef00-9e58-11ea-9c34-43d15809ef00.png)

> There are a large number of other dodecahedra.

> There are an infinite number of numbers.

> There are 101 file sharing services out there already.

> However, there are a vast variety of metal discuses to choose from.

> And there are two inside.

> There are no:

> There are a good deal of books you can buy

> But there are other, far more compelling reasons.

**Comment by MikeUnwalla** [comment]
- [ ] There are only few who do this.
- [ ] There are a few out there.
- [ ] There are several, including one by Millais.
- [ ] There are just the two of us here.
- [x] There are a large number of other dodecahedra. Not found 2020-05-25.
- [x] There are an infinite number of numbers. Not found 2020-05-25.
- [ ] There are 101 file sharing services out there already.
- [x] However, there are a vast variety of metal discuses to choose from. Not found 2020-05-25.
- [ ] And there are two inside.
- [ ] There are no:
- [ ] There are a good deal of books you can buy
- [ ] But there are other, far more compelling reasons.
