### ISSUE TITLE
[es] "Ola" vs "Hola"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2967]
Feedback from a user:
> no entiendo como para la Prueba coloco Ola como estas ? y me dice que la palabra está correcta si NO ES Ola es HOLA 

@jaumeortola

**Comment by jaumeortola** [comment]
I will add a rule. But with so many errors, it becomes tricky. We have already several rules for "cómo estás":
```Ola como estas? (= Wave like these) > Hola, ¿cómo estás? (Hi, how are you?)```

**Comment by tiff** [comment]
Thanks @jaumeortola
