### ISSUE TITLE
[es] user feedback "Colaboro"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2976]
The user only said:
> Colaboro no se corrigió

@jaumeortola do you understand what he meant?

**Comment by jaumeortola** [comment]
He means probably the confusion "colaboro/colaboró" (=I collaborate/he collaborated). But both forms are correct and usual. They can be disambiguated only in some contexts. Could you ask for the context?

![imatge](https://user-images.githubusercontent.com/4289501/83003099-2214db80-a00e-11ea-85dc-ee5ae0286647.png)

**Comment by jaumeortola** [comment]
Some more contexts have been added:
`La comunidad *colaboro>colaboró con la policía`
