### ISSUE TITLE
[fr] "alloo" doesn't suggest "allo"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2977]
Feedback from a user:
> Quand on écrit "alloo" ça propose des mots anglais et même en passant en français ça ne propose pas "allo"

**Comment by jaumeortola** [comment]
The suggestions for "alloo" have not improved with the new speller rule (`Suggestion: alto; clou; flou; Aldo; aloi; allô; algo; allo; alloc; aloyau; allo o`). The word "allo" is not in the [frequency word list we use](https://github.com/languagetool-org/french-pos-dict/blob/master/build-from-dicollecte/fr_wordlist.xml). There is "allô", but not "allo" (Does it make sense, @vkyfox?). 

But the suggestions don't seem good to me. "alto, clou, flou..." have distance>1, but "allo" and "allô" have distance=1 and should come first. Any clue about what's going on here? @danielnaber

**Comment by danielnaber** [comment]
Have you tried without `fsa.dict.speller.replacement-pairs`? There might be pairs in it that make the result worse?

**Comment by jaumeortola** [comment]
> Have you tried without `fsa.dict.speller.replacement-pairs`? There might be pairs in it that make the result worse?

Yes, I had tried, and the results were the same. I expected some difference because of the pair ll->l. 

Generally the results seem good. But this case is inexplicable.

**Comment by jaumeortola** [comment]
It could be related to: https://github.com/morfologik/morfologik-stemming/issues/30#issuecomment-54267720
Some issues when the lenghts of word and candidate are not the same.

**Comment by vkyfox** [comment]
From a spelling point of view, the only correct orthography for the word is "allô". However, as it is almost only ever used verbally (salutation on answering the phone), it would make sense that common use tends to drop the special accent on it.
This being said, due to how rarely it should occur, I don't think we have to accept "allo" if we can offer the correct suggestion.
