### ISSUE TITLE
[fr] Confusion with plural + Dutch names

### ISSUE THREAD

**Issue by bperel** [languagetool-org/languagetool#2980]
> Au printemps 1899, Gide se lie avec les époux van Rysselberghe

LanguageTool suggests to add an "s" to "van" because it thinks that it should be accorded with "les époux", but it shouldn't since "van" is part of the family name "van Rysselberghe".

**Comment by tiff** [comment]
@vkyfox this is ACCORD_NOMBRE

**Comment by jaumeortola** [comment]
A list of nouns (van/von+ProperNoun) can be added to disambiguation.xml. The same with Italian names (di/da+ProperNoun). 
"von", "di", "da" are not French words. But we will avoid some spelling false alarms. 
See rules VAN_GOGH, DA_VINCI in Catalan disambiguation.xml.

**Comment by jaumeortola** [comment]
@vkyfox If you do a more complete list with these nouns, we can copy them to other languages or add them to global spelling.

**Comment by jaumeortola** [comment]
Fixed with the new agreement rules. Added tagging for proper nouns van Gogh, da Vinci and similar ones.
