### ISSUE TITLE
[pt-br] Inapropriate correction for some words in Brazilian Portuguese texts

### ISSUE THREAD

**Issue by hmslima** [languagetool-org/languagetool#2984]
**The Portuguese from Brazil has some differences from European Portuguese. There are a lot of words largely used in Brazil that are from foreign origin and were not translated or "portuguesed". I also added two Portuguese words that are taken as informal because of their -inho termination**

<hr>

> videogame

LT (Language Tool) suggests "Jogo de vídeo". But nobody says that in Brazil, just "videogame".

> mouse

LT suggests "rato". But nobody says that in Brazil, just "mouse".

> notebook

LT suggests "portátil". But nobody says that in Brazil, just "notebook".

> laptop

LT suggests "portátil". But nobody says that in Brazil, just "laptop" _(actually people use more the word "notebook", but I never saw anyone using "portátil")_.

> site

LT suggests "sítio web". But nobody says that in Brazil, just "site". When people try to be more formal, they say "web site" or "site web", but never "sítio". The word "sítio" means "ranch" (or "small farm") and "siege" for a Brazilian.

> link

LT suggests "ligação". But nobody says that in Brazil, just "link". Of course that I mean it in the context of websites!

> outdoor

It's not that wrong when LT suggests "cartaz", but everybody (even in formal ambient) only use "outdoor". And when you say "cartaz" I think in something smaller.

> jeans

LT suggests "calças de ganga". But nobody say that in Brazil _(and neither know what that...)_, just "jeans".

> short

LT suggests "calção". But people usually say "jeans". Everybody in my state say "short" and at least all big Brazilian shopping websites use this word, so I think that nobody in Brazil say "calção". Of course that I mean it in the context of clothing!

<hr>

> revista em quadrinhos

LT marks "quadrinhos" as informal word, what is wrong. The expression indeed is "[revista em quadrinhos](https://pt.wikipedia.org/wiki/Revista_em_quadrinhos)"

> covinha

It's not an informal word. ([link](https://pt.wikipedia.org/wiki/Covinha))

**Comment by marcoagpinto** [comment]
@danielnaber @tiff @jaumeortola 

The words above are stored in barbarisms.txt (suggesting replacing with Portuguese words).

Is it possible for one of you to create an exception .txt for Brazilian?

I don't know Java, so I can't do it myself.

Thanks!

**Comment by danielnaber** [comment]
Should there be three files, `barbarisms-pt.txt`, `barbarisms-pt-PT.txt`, and `barbarisms-pt-BR.txt`to avoid duplication? So that entries that apply to both variants belong to `barbarisms-pt.txt`, or doesn't that make sense?

**Comment by marcoagpinto** [comment]
Yes, it makes a lot of sense. :-)

**Comment by danielnaber** [comment]
Okay, I will give it a try.

**Comment by danielnaber** [comment]
Done. Can we keep these strings, or do they need to be adapted to pt-BR, @hmslima ?

> Palavras de origem estrangeira evitáveis

> Estrangeirismo

> '$match' é um estrangeirismo. É preferível dizer $suggestions

**Comment by hmslima** [comment]
These texts are good, @danielnaber.

**Comment by marcoagpinto** [comment]
So, tomorrow I will start working on the new files.

:-)

**Comment by marcoagpinto** [comment]
Fixed!
https://github.com/languagetool-org/languagetool/commit/dc7bfbdef7b31d1ac86c30bfd3c587a3137390c5

https://github.com/languagetool-org/languagetool/commit/0a005cf103906ae3da7be6068e472bc8fc20c652

Reopen if something is missing.

**Comment by jaumeortola** [comment]
I guess that these warnings from Portuguese to English words are not necessary for Brazilian Portuguese. In fact, they will be false alarms. See https://github.com/languagetool-org/languagetool/commit/dc7bfbdef7b31d1ac86c30bfd3c587a3137390c5
```
calças de ganga=jeans
jogo de vídeo=videogame
jogos de vídeo=videogames
portátil=notebook
portáteis=notebooks
rato=mouse
ratos=mouses
```
'Portátil', 'rato' have also other meanings beside "notebook" and "computer mouse". In any case, they are not "barbarisms".
On the other hand, the English words should be added to the spelling.txt file, so that they do not trigger the spelling rule in pt-BR.

**Comment by marcoagpinto** [comment]
@jaumeortola 

Ahhh... ok... let me clear the file.

**Comment by marcoagpinto** [comment]
@jaumeortola 

Done!

https://github.com/languagetool-org/languagetool/commit/1f9702b209d7eeba78d391281d154ae74dad20e0
