### ISSUE TITLE
NullPointerException - 2020-05-29

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#2987]
@FredKruse 

Hello!

The nightly add-on for LibreOffice threw an exception:
![java_exception_20200529](https://user-images.githubusercontent.com/5192600/83223395-a54f4200-a172-11ea-9090-c33707bd4bdf.png)

Could you have a look at it?

Thanks!

**Comment by danielnaber** [comment]
@marcoagpinto Do you have instructions to reproduce?

**Comment by marcoagpinto** [comment]
@danielnaber 

I was kind of stressed and can't remember the exact thing I was doing when it happened.

If it happens again, I will know.

**Comment by FredKruse** [comment]
The issue should be solved. Please test the new version and close the issue.

**Comment by FredKruse** [comment]
Solved!
