### ISSUE TITLE
[en] False warning SENTENCE_FRAGMENT [1] 

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#2989]
This sentence should not trigger a warning:

> **Whether** the Russian Government shares any of the station's radar data with Azerbaijan is unknown.

**Comment by srcmilena** [comment]
Hello, could you tell us what the warning is? Because I don't see an error either. Possibly, if it is taken to the letter, it must be because of the capital "G", or just a bug. If it is fixed, please let us know.

**Comment by MikeUnwalla** [comment]
The incorrect warning by rule SENTENCE_FRAGMENT [1] was for the highlighted word 'Whether' in the example sentence.

But, there is no warning now.
