### ISSUE TITLE
Problem with German rule  VIELZAHL_PLUS_SINGULAR 

### ISSUE THREAD

**Issue by reisenmachtfreude** [languagetool-org/languagetool#299]
"Er erhielt dafür eine außerordentlich hohe Besoldung, unter anderem eintausend Taler, für acht Personen Hofkleidung, Futter für acht Pferde und zahlreiche Naturalien."

The rule VIELZAHL_PLUS_SINGULAR  gives for the word "Naturalien" the message "Möglicher Tippfehler: Müsste dieses Wort im Plural stehen?"

However "Naturalien" is already in "Plural".

**Comment by janschreiber** [comment]
Thank you so much for this error report! We can't improve the software
without feedback from the community.

Am 07.08.2015 23:45, schrieb reisenmachtfreude:

**Comment by danielnaber** [comment]
Fixed, thanks for the report.
