### ISSUE TITLE
LibreOffice add-on still doesn't refresh paragraph after correcting words

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#2990]
Hello @FredKruse 

I can't find the issue I opened months ago, so here is a new one.

In this sample I am providing, when you right-click in the first "febre amarela" and fix it, it no longer refreshes the other underlines.

[FCR_WORDS_febre-amarela_20200530e.zip](https://github.com/languagetool-org/languagetool/files/4705489/FCR_WORDS_febre-amarela_20200530e.zip)

Also, see the video of it happening:
https://youtu.be/C7oRnOHjZMc

This is a long-standing issue in the add-on and I hope that this sample can help fix it for good.

**Comment by FredKruse** [comment]
Hello @marcoagpinto,
the issue should be solved. Please test it and close the issue.

**Comment by marcoagpinto** [comment]
@FredKruse 

Great news, Fred,

I will test it tomorrow after the nightly is released.

:-)

Thanks!

**Comment by marcoagpinto** [comment]
@FredKruse 

Hello!

It is working!

Thanks for fixing it!
