### ISSUE TITLE
Usage of --neuralnetworkmodel

### ISSUE THREAD

**Issue by zuxfoucault** [languagetool-org/languagetool#2992]
Thanks for the work!  I could find an introduction for [--word2vecmodel](https://github.com/gulp21/languagetool/tree/neuralnetworkrule), but how to use [--neuralnetworkmodel](https://github.com/languagetool-org/languagetool/pull/1252/files#diff-d3affb005560557d5bf9fc3a55f74cffR228)? What kind of file type it is expected?

**Comment by danielnaber** [comment]
It's outdated. I'll mark it as deprecated for the next release.

**Comment by zuxfoucault** [comment]
Thanks for the prompt reply! Also, just to clarify the usage, `--fasttextbinary` is mostly for language detection not for error correction?

**Comment by danielnaber** [comment]
> --fasttextbinary is mostly for language detection not for error correction?

Yes.
