### ISSUE TITLE
LibreOffice [Feature Request] - Ability to send to remote server variables like filename and path

### ISSUE THREAD

**Issue by KnowZero** [languagetool-org/languagetool#3009]
I would like to be able to send some more variables to the remote server on the libreoffice plugin. The two I am most interested is:

1) File name and path

2) If document is being scanned on open or not - I don't know if this is possible or not but if it is it would help.

Obviosuly these things would be optional.

The reason for these variables is that I have ngrams and word2vec installed, opening a file with over 1 million words means I leave the PC on for an hour or 2 and come back when its done because it puts a big load on my system. This gets even worse when I gotta open multiple such big files at once.

So what I want to do is create a local cache server that would cache the requests so that when I open the file, the parts that have not been changed will load from cache instead of running the whole program over again. This is useful when I gotta restart my pc due to updates or crashes or other reasons and don't need to wait for the huge file to be scanned. I can just return to where I was proofreading and all non-changes would be loaded from the local cache server.

I got a sample of it working and all, but the problem is my cache is universal and not per file. And I gotta flush the cache when it goes over a certain amount of space as the amount of changes increase. If I can get at least the name of the file and its path sent, I can limit the amount of cache per file. But ideally I would also like to get a bolean of if it first opened or not. This way I can simply only cache things on first open and not every single time I make a change.

**Comment by danielnaber** [comment]
This seems very specific to your use case. Frankly, it sounds more like something to keep in a local patch than as an option in LT.

**Comment by KnowZero** [comment]
@danielnaber  hmm, what about at least an option to check paragraphs not on text change but on navigate with cursor or whats on my screen? This way I wouldn't need to cache the whole thing as I can simply go paragraph by paragraph?

**Comment by danielnaber** [comment]
Maybe @FredKruse can comment on that. I think we have something like that already, but it probably doesn't apply when the text is loaded the first time.

**Comment by KnowZero** [comment]
The current one is option to check the entire document or not and on text change. So the part of not scanning entire documents on load is there, but no option to check based on cursor ot screen position.

Only on text change, which means I would have to manually modify each page to have it run on what I see. So effectively it is virtually same as not having grammar checker on until I start editing stuff which doesn't quite work for proofreading purposes.

**Comment by FredKruse** [comment]
I'm not sure, if I understand the full idea.

First some background to the extension:
The LO extension uses the LO-interface for grammar checking. It works in that way that in a background task paragraph by paragraph (Within a paragraph sentence by sentence) is checked. We use LT as engine to do the grammar check. The curvy underlining is shown as soon as the check of a paragraph is done. The order in which the paragraphs are checked are managed by the LO-interface. Generally it begins with the first paragraph and works than one by one through the text. If you scroll e.g. to a chapter in the middle of the document. As next paragraph the first visible is selected. So in general you can see what problems are found at the part of text you are just looking. If you do a change of text. The part will be checked as next. So in general you should get what you need.

What I understand is, you got a very huge text. This could take a long time to check and it is done again every time you load the document into LO. I've got two ideas for further development:
1. Save the internal cache of found errors and write it into a file, which can be loaded the next time, the document is edited.
2. Do a check as batch job and save the results in a format which can be loaded into the internal cache.

Both ideas are difficult to realize. It will be a big project. A concept what to save, how to handle changes, etc. has to be prepared. I think this is nothing that can be realized in version 5.1 (maybe later).

**Comment by KnowZero** [comment]
@FredKruse Well having internal cache would be nice, but in the meantime I wanted to do my own cache and just wanted some parameters sent so I can handle it.

But a more simple solution here would be checking based on scroll/cursor instead of text change, this would accomplish 99% of what I want and would be a more general solution.

That said, while testing these things, there seems to be a bug with "Check full text when document is loaded", I disabled that feature but it still scans the entire document when it is loaded.

Here are my settings, it is clearly disabled yet it scanned the entire 4000 word document. There are way more than 10 sentences, I set it to 1 instead of 5 and it still scanned everything.
![lo_error2](https://user-images.githubusercontent.com/1638787/83632817-efb73100-a56d-11ea-95ce-ea9257780fde.png)

**Comment by FredKruse** [comment]
We should differentiate your ideas into two technical complete different solutions:

The scroll/cursor idea:
If I understand you right, you want a grammar check application that  does no check in the background but a check that is initiated by something special on a selected paragraph.
This would be a complete other application as the extension is working by now. LT operates the grammar check interface provided by LO/OO. The check is done automatically in the background. A manual check, like that done by the spelling dialog, uses the results of the automatic background check.
I'm planing to implement one or two ideas for working with dialog at the next version of LT. I will think about a possibility of realizing your request but I'm not sure if I will find a solution.

Send filename and path to the server (also to @danielnaber)  :
Before we can discuss the problem on side of the extension the server side has to be defined. What should happen with the information (e.g. where should it be stored). If this is clarified I could search for a LO-interface which gives back the name and path of the current document. (For a document not open I see no changes to check).

**Comment by danielnaber** [comment]
> Before we can discuss the problem on side of the extension the server side has to be defined.

Frankly, I'm not so happy about this approach. It sounds like we're adding complexity for a very specific case. The complexity we have now has already caused bugs and crashes recently, so I think no more complexity should be introduced.

**Comment by KnowZero** [comment]
For the first thing, is it not possible to just tell the background that there is no errors on paragraphs not selected and only do a check on the selected paragraph?

For the 2nd thing, how about just give an option to send these things via headers? This way the server can choose to use them or ignore them. Like X-FilePath and X-FileName (of course make it optional)


My end goal is really to reduce the load when proofreading large files. The 1st option would limit what is checked other than what I am reading. And the 2nd option I would write my own cache server (I already did write 90% of it, just without being sent the filename/path information, I can't limit the cache per file)

**Comment by FredKruse** [comment]
The new issues #3624 and #3625 describes two ideas to handle the problem of huge documents. The first one is the enhancement I'm just working on.
These solutions will solve this issue, I think. So, if there is no protest, I will close this issue the next days.

**Comment by KnowZero** [comment]
Both solutions sound great, so I'll close this ticket and comment there.
