### ISSUE TITLE
wiki-check enhancement suggestion

### ISSUE THREAD

**Issue by reisenmachtfreude** [languagetool-org/languagetool#301]
I like your wiki-check feature quite much. However there is one annoying thing which makes me feel wasting my time if I want to check a random German article:  I've to click very often till an article appears for which correction suggestions are available: http://community.languagetool.org/wikiCheck/?lang=de

Definitively I would use the feature more often if beside "random page" a link  e.g. "random page containing possible errors"  would be provided.

**Comment by danielnaber** [comment]
Have you seen http://community.languagetool.org/wikiCheck/feedMatches/list?lang=de? Not random articles but recently changed ones with potential errors. Implementing the random feature the way you suggested would require quite some resources (CPU), as we'd have to check a lot of random articles before we find one with errors.

**Comment by reisenmachtfreude** [comment]
Ok, I see. I'm aware of the link you provided  but in this case articles older than 48 hours could not be checked. I will try to implement this locally. Thank you.
