### ISSUE TITLE
[LibreOffice] High memory and CPU usage

### ISSUE THREAD

**Issue by medmedin2014** [languagetool-org/languagetool#3019]
When I use LanguageTool (LT) extension with LibreOffice, The CPU and memory usage is really high with an ODT document that contains only one page. I set LT to use locally ng-rams and word2vect directories for english.
```
LanguageTool Extension: 4.8-1
ngrams-en-20150817.zip
LibreOffice: 6.4.4.2
Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.6.15-1-MANJARO
OS Type: 64-bit
```

[Sample.zip](https://github.com/languagetool-org/languagetool/files/4724622/Sample.zip)

![Screenshot_20200603_165318](https://user-images.githubusercontent.com/7027319/83659264-367f4800-a5bb-11ea-8b03-4ce6e916ed0d.png)

**Comment by FredKruse** [comment]
Please test it again with the latest version.
