### ISSUE TITLE
error types

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#3020]
Errors in a category with `type="misspelling"` are shown under "Grammar and others" in the add-on. See, for example: 
![imatge](https://user-images.githubusercontent.com/4289501/83731334-9ec93a80-a64a-11ea-8a30-bd7fc64bd231.png)
We only show under spelling the errors detected by the main (Morfologik or other) spelling rule. Is this the desired behavior?

**Comment by danielnaber** [comment]
Red color basically mean "this is not even a word". But "hep" is a word and if we start underlining these cases in red, too, I think it becomes very difficult to decide what's a "real" spelling mistake and what is not. For example, "ad" vs. "add" could be both a spelling mistake or a mistake made by someone who confused the two words.

**Comment by jaumeortola** [comment]
That makes sense. I was wondering about Spanish rules like `esta/está`. It is a spelling error, but both words are valid words depending on the context.
