### ISSUE TITLE
[es/ca] incorrect language detection

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3023]
A user from Peru complains that we detect Catalan in this Spanish sentence:
> Una variable categorica es aquella que indica al grupo o categoria a que pertenece determinada observacion

@jaumeortola is there anything we can do?

**Comment by jaumeortola** [comment]
Certainly, there are many common words (Spanish and Catalan) in the sentence. 
The original sentence has 3 spelling errors. One error is a Catalan spelling ("categoria"). 
"Grupo" and "pertenece" are already in the list of common Spanish words. 

The only thing we could do is to add a regexp with some  word endings `ción$` or `cion$` (the second one is a common misspelling), which are clearly Spanish and not Catalan. This would be helpful more generally. But this feature is not implemented yet.

**Comment by tiff** [comment]
Thanks for the explanation. Sounds reasonable to have a reg exp for "ion$"

**Comment by jaumeortola** [comment]
We can add these lines to getKnownWordsPerLanguage(). One point is added to Spanish for -ón endings:
```
      //Spanish
      if (word.toLowerCase().endsWith("ón") || word.toLowerCase().endsWith("cion")) {
        Language lang = Languages.getLanguageForShortCode("es");
        if (result.containsKey(lang)) {
          result.put(lang, result.get(lang) + 1);
        } else {
          result.put(lang, 1);
        }
      }
```

Some patterns like these can be added for Spanish, Catalan or other languages. But we should make sure that the pattern is exclusive of the language. "ón$" is safely Spanish, but "cion$" (a misspelling in Spanish) is not exclusive of Spanish. 

@danielnaber How can we test this language detection? Where and when is the language detection with common words used?

**Comment by danielnaber** [comment]
@jaumeortola I suggest evaluating with `org.languagetool.dev.eval.LanguageDetectionMinLengthEval`. But make sure to adapt and comment in line 52, so FastText is used, like on our servers. The common words are only used if FastText's result doesn't have good confidence (happens often, but not always for short texts).

**Comment by jaumeortola** [comment]
I have added some regular expressions to improve Spanish auto-detection, but it is difficult to know if it will make a difference.
