### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#3024]
The message for the spell checker for Dutch is not optimal.
I used to know where to correct that, but not any longer.
It is 'Mogelijke spelfout is gevonden'
Better is: 'Er is een mogelijke spelfout gevonden', or more in heading-style 'Mogelijke spelfout gevonden'

**Comment by danielnaber** [comment]
It can be translated at https://www.transifex.com/dnaber/languagetool/translate/#nl, I have done that now (and added a `.` at the end of the string).
