### ISSUE TITLE
Arabic top matches

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3028]
@sohaibafifi

See #3027:

    132 Jar_majrour[1]
    110 AR_SIMPLE_REPLACE
     78 الجزم1[1]
     30 ARABIC_COMMA_PARENTHESIS_WHITESPACE
      8 القيام_ب[5]

Are these all valid matches, or false alarms? We should try hard to avoid false alarms.

Full result:

[out.txt](https://github.com/languagetool-org/languagetool/files/4739888/out.txt)

**Comment by sohaibafifi** [comment]
Thank you! We are working on it. 

@linuxscout I disabled Jazm and Jar (which are still not stable enough) and got these results https://gist.github.com/sohaibafifi/c0464bc45b07dd0e29fe5849e584403c 

Can you please check them?

**Comment by sohaibafifi** [comment]
@linuxscout here is the new output https://gist.github.com/sohaibafifi/a39fa4499a9c95603a36fd32bfe9ab10

**Comment by danielnaber** [comment]
Improved result after https://github.com/languagetool-org/languagetool/pull/3067 has been merged:

Arabic: ø0.12 rule matches per sentence

**Comment by sohaibafifi** [comment]
after https://github.com/sohaibafifi/languagetool/commit/7c7b2e8441f2de3ab050187862590c3176089b29 
https://gist.github.com/89e3d366ad0d643cbb98b9e2807bb7b6

**Comment by linuxscout** [comment]
to be closed

**Comment by linuxscout** [comment]
@danielnaber please close this issue.
