### ISSUE TITLE
Portuguese top matches

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3029]
See #3027, are these maybe mostly false alarms?

     53 EU_NÓS_REMOVAL[1]
     18 ACHO_QUE[125]
     15 EU_NÓS_REMOVAL[2]
     11 SMART_QUOTES[2]
     11 SMART_QUOTES[1]
     11 REPEATED_WORDS[1]
      8 NO_VERB[1]
      7 PT_BARBARISMS_REPLACE

Full result: 
[out.txt](https://github.com/languagetool-org/languagetool/files/4739916/out.txt)

**Comment by marcoagpinto** [comment]
@danielnaber 

Thanks for the list.

It is in my TO-DO list.

But, to be honest, I believe that I will only have the chance to focus hard on them in LT 5.1 since it is almost freeze day, and I am still fixing the tons of number agreement false positives, and after that I will move to the gender agreement false positives.

There is still a long way to go.

**Comment by marcoagpinto** [comment]
@danielnaber 

I will focus on it tomorrow, after adding one more antipattern to the number agreement.

I guess the number agreement is kind of "nice" (acceptable) right now.

**Comment by marcoagpinto** [comment]
@tiff @jaumeortola 

Hello!

I forgot how to use a dot in a token, Christopher one time you told me I needed escaping or something?

Enquanto você estiver aqui, eu fico.
                                        ^^^^^^^ 
I need to do a:
`negate="yes"`
and
`<token>.</token>`

**Comment by marcoagpinto** [comment]
and now that I am at it:

> Ah sim, eu tenho algo amanhã.

I need to:

> , + space + eu + verb

Do I also need the comma escaped?

And how do I do manage the space after the comma?

**Comment by marcoagpinto** [comment]
In fact, I thought it would take weeks or months to fix the EU/NÓS rules, but I found out it is just one rule for EU and one rule for NÓS.

:-)

**Comment by marcoagpinto** [comment]
@danielnaber @tiff @jaumeortola 

Hello!

I have just fixed/improved  id='EU_NÓS_REMOVAL':
https://github.com/languagetool-org/languagetool/commit/870e69cd4fb4944fe0b74f42f6d6eee76a95fe71

**Comment by danielnaber** [comment]
Thanks, but it's still the top-matching rule. Are the remaining matches all valid matches?

     49 EU_NÓS_REMOVAL[1]
     18 ACHO_QUE[125]
     14 EU_NÓS_REMOVAL[2]
     11 SMART_QUOTES[2]
     11 SMART_QUOTES[1]

**Comment by marcoagpinto** [comment]
Well, when we use EU + VERB or NÓS + VERB, we can remove the EU/NÓS.

What I have done was to add antipatterns that make it sound better.

For example, not suggest after a "," and not suggest if before a "." or "!".

This slightly improvements make it sound better in the sentences.

Not much more can be done.

**Comment by marcoagpinto** [comment]
@danielnaber 

I was checking id='ACHO_QUE' and in the results of Wikipedia + Tatoeba, in the quick view I took, it seems okay.

I have however added more suggestions to the rule.

**Comment by marcoagpinto** [comment]
@danielnaber 

I have added also a check for "?" in the EU_NÓS rule:
https://github.com/languagetool-org/languagetool/commit/75743088f725e20f4e7b9789a647f8d1be83f879

What is the ranking now? Slightly better?

**Comment by danielnaber** [comment]
Still "Portuguese: ø0.21 rule matches per sentence", i.e. many more matches than most other languages.

**Comment by marcoagpinto** [comment]
I have spent the last weeks/months removing false positives, but there is still a long way to go. :-)

**Comment by marcoagpinto** [comment]
@danielnaber 

Could you help with this?:
https://forum.languagetool.org/t/pt-cant-find-rule-in-grammar-xml/5767

I am trying to fix more false positives.

Thanks!

**Comment by marcoagpinto** [comment]
@danielnaber 
I have found out: "T-V_DISTINCTION"

**Comment by danielnaber** [comment]
Can we close this issue or is there still work to do?

**Comment by marcoagpinto** [comment]
@danielnaber 

What is the current ø of Portuguese?

I wanted to ask you at the end of the year (December).

**Comment by marcoagpinto** [comment]
I have fixed tons of false positives and still a long way to go.

**Comment by danielnaber** [comment]
Portuguese: ø0.14 rule matches per sentence

Top matches:

```
     90 ACHO_QUE[125]
     55 SMART_QUOTES[2]
     55 SMART_QUOTES[1]
     55 REPEATED_WORDS[1] [temp_off]
     40 NO_VERB[1] [temp_off]
     35 PT_BARBARISMS_REPLACE
     20 PT_WORDINESS_REPLACE
     20 INFORMALITIES[1]
     20 E_NO_COMECO[1]
     15 PT_COMPOUNDS_POST_REFORM
     15 GENERAL_GENDER_AGREEMENT_ERRORS[6]
     15 A_WORD[1]
     10 VERB_COMMA_CONJUNCTION[14]
     10 UPPERCASE_SENTENCE_START
     10 PT_SIMPLE_REPLACE
     10 INTERROGATIVES_PUNTUATION[2]
     10 GENERAL_GENDER_AGREEMENT_ERRORS[1]
     10 DASH_RULE[3]
     10 ALTERNATIVE_CONJUNCTIONS_COMMA[1]
```

**Comment by marcoagpinto** [comment]
@danielnaber 

Ahhh... from ø0.21 to ø0.14.

Great news.

Thanks!

I will close the ticket but will continue fixing/improving the rules that have tons of false positives.
