### ISSUE TITLE
Update German rule

### ISSUE THREAD

**Issue by reisenmachtfreude** [languagetool-org/languagetool#303]
The phrase "x-Jährig" shall contain a J as capital letter. The existing rules don't cover both mistakes in the following sentence: “Eine strikte Einteilung in Klassenstufen nach dem Alter der Schüler findet nicht statt: Es gibt eine Gruppe für die bis 10-jährigen, eine für die 10- bis 12-jährigen sowie thematische Kurse für die älteren Schüler.“

**Comment by baarsrj** [comment]
In Dutch, the spell checker takes care for these compounds by treating the - as a word character; German might need case-sensitivity there.
Op 9 aug. 2015 19:56 schreef reisenmachtfreude <notifications@github.com>:The phrase "x-Jährig" shall contain a J as capital letter. The existing rules don't cover both mistakes in the following sentence: “Eine strikte Einteilung in Klassenstufen nach dem Alter der Schüler findet nicht statt: Es gibt eine Gruppe für die bis 10-jährigen, eine für die 10- bis 12-jährigen sowie thematische Kurse für die älteren Schüler.“

**Comment by danielnaber** [comment]
@reisenmachtfreude Fixing this is not so easy - consider this sentence, which is correct: `Es gibt eine Gruppe für die bis 10-jährigen, eine für die 10- bis 12-jährigen Kinder.`

**Comment by janschreiber** [comment]
@reisenmachtfreude Thanks a lot for your suggestion, much appreciated. Nonetheless, I doubt that your original sentence `Es gibt eine Gruppe für die bis 10-jährigen, eine für die 10- bis 12-jährigen sowie thematische Kurse für die älteren Schüler.` is wrong in the first place.
There is a benevolent reading for it that renders it correct with a lowercase j, much along the lines of Daniel's example: `Es gibt eine Gruppe für die bis 10-jährigen [Schüler], eine für die 10- bis 12-jährigen [Schüler] sowie thematische Kurse für die älteren Schüler.` (I don't have the rule at hand that applies here, though.)

**Comment by danielnaber** [comment]
Closing, see @janschreiber's comment that this is not necessarily an error.
