### ISSUE TITLE
LibreOffice - Unchecking "Check full text when document is loaded" does not work

### ISSUE THREAD

**Issue by KnowZero** [languagetool-org/languagetool#3031]
I disabled that feature but it still scans the entire document when it is loaded.

Here are my settings, it is clearly disabled yet it scanned the entire 4000 word document on load. I tried bigger and smaller documents and same result

![lo_error2](https://user-images.githubusercontent.com/1638787/83961284-93029180-a85f-11ea-93d2-15527cd96f1c.png)

I am on Linux Mint 19.3, using latest snapshot, and libre office 6.4

**Comment by FredKruse** [comment]
This is due to a misunderstanding of the option. This option refer to the handling of text level rules. If you limit the check by text level rules to few paragraphs while text changes, you can decide to do a full text level check at the first iteration of text.
The background iteration can' t be switched off. It is the basis of the application (see also my comment on issue #3009).
Please close the issue!

**Comment by danielnaber** [comment]
But @KnowZero is right that it's easy to misunderstand this. Could we reword the description? (I also wonder what the original reason was to introduce this option?)

**Comment by KnowZero** [comment]
Not only that, if you are saying this is a sub-property of text change, than the indent should reflect that (or it should be within a groupset at the very least). Currently it looks like a top level property at same level as text change.

Also, I am not sure if it is a GTK thing but I can't tell when an option is clickable or not. It doesn't grey out. Look at the "only if as single document is loaded", notice how only the checkbox is lighted out but the text itself is black, not grey? When that box is unchecked, you can't even tell its not selectable so I click on it and wonder why it doesn't work.

Some things should also probably be radioboxes instead of checkboxes. Such as if I select remote server, multiple cores option is disabled. On the 5.0 snapshot, if I select text level rules parallel, I can't even select the check full text is loaded option. So it's not clear that it is this OR this, as checkboxes makes people think it is this AND this.

If it is a matter of trying to save space as options much generally have something selected, than use of a dropdown or subtabs may be a better solution.

**Comment by FredKruse** [comment]
The new issue #3623 describes what is to do out of the discussion within this issue. So I close this issue now.
