### ISSUE TITLE
[en] false alarms THE_SUPERLATIVE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3037]
> It is in our economic best interest.

![Bildschirmfoto 2020-06-08 um 11 43 14](https://user-images.githubusercontent.com/37363/84016271-5331cc00-a97d-11ea-8049-032f352b7c2f.png)

> What's your deepest darkest secret?

> What's your deepest/darkest secret?

> Please order by the most/least expensive

**Comment by MikeUnwalla** [comment]
The first error is caused by incorrect disambiguation in PRPPOSS_JJ_NN.
