### ISSUE TITLE
[en] "the later of"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3042]
See https://internal1.languagetool.org/regression-tests/via-http/2020-06-09/en/result_grammar_THE_LATER_LATTER[1].html

@MikeUnwalla are those false alarms or is it incorrect to say "the later of"?

Two rules mark this as a mistake: THE_LATER_LATTER and ARTICLE_ADJECTIVE_OF

**Comment by MikeUnwalla** [comment]
@tiff, I think that the results are not false alarms.

https://www.lexico.com/definition/later
https://www.lexico.com/definition/latter

The last example is missing an opening quote mark, so I don't think it's a false alarm. But, this sentence is a false alarm:

> They wrote "the later of", which is not correct.

But, many rules don't have exceptions for quoted text.

**Comment by tiff** [comment]
Ok, I will close this then. Thanks for checking it
