### ISSUE TITLE
[en] multiwords.txt does not work correctly

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3044]
Portuguese has the expected POS:
![image](https://user-images.githubusercontent.com/5816160/84131752-e1b95280-aa3c-11ea-9288-1fa990da4946.png)

I added this line to the English multiwords.txt:
`Fat Cat	NNPxy`

English does not have the expected POS:
![image](https://user-images.githubusercontent.com/5816160/84132010-41aff900-aa3d-11ea-969a-c324925f1028.png)

The problem is not merely a display error as suggested in https://forum.languagetool.org/t/en-multiwords-txt-for-english/5047/2.

This is my test rule:
```
<rule id="MULTIWORDS_TEST" name="Multiwords test">
    <pattern>
        <token postag="NNPxy"/>
        <token postag="NNPxy"/>
    </pattern>
    <message>Found: '\1 \2'.</message>
    <example correction="">Did you know that the <marker>Fat Cat</marker> is a pub in Sheffield?</example>
</rule>
```
The GUI does not find the text (refer to the screen shot above). Testrules gives this error message:

```
3632 rules tested.
Exception in thread "main" org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule MULTIWORDS_TEST[1] in file /org/languagetool/rules/en/grammar.xml: Did you know that the Fat Cat is a pub in Sheffield?"
Errors expected: 1
Errors found   : 0
Message: Found: '\1 \2'.
Analyzed token readings: [/SENT_START*] Did[do/VBD*,O]  [ /null*] you[you/PRP,B-NP-singular|E-NP-singular]  [ /null*] know[know/NN,know/VB,know/VBP,B-VP]  [ /null*] that[that/DT,that/RP,that/WDT,that/WP,B-PP]  [ /null*] the[the/DT,B-NP-singular]  [ /null*] Fat[fat/JJ,Fat Cat/<NNPxy>,I-NP-singular]  [ /null*] Cat[Cat/NNP,cat/NN,cat/VB,cat/VBP,Fat Cat/</NNPxy>,E-NP-singular]  [ /null*] is[be/VBZ,B-VP]  [ /null*] a[a/DT,B-NP-singular]  [ /null*] pub[pub/NN,E-NP-singular]  [ /null*] in[in/IN,B-PP]  [ /null*] Sheffield[Sheffield/NNP,B-NP-singular|E-NP-singular] ?[?/SENT_END*,?/PCT*,O]
Matches: []
```

**Comment by jaumeortola** [comment]
The tags added by multiwords are `<NNPxy> </NNPxy>` (with angle brackets), not `NNPxy`. Your rule shoud be something like: 
```
<token postag="&lt;NNPxy&gt;"/>
<token postag="&lt;/NNPxy&gt;"/>
```
In Portuguese, there are disambiguation rules that convert `<NPMS000_></NPMS000_>` into `NPMS000_ NPMS000_`.  In Catalan and Spanish, this conversion is done directly (without disambiguation rules). And all previous tags, if any, are also removed (if an expression needs disambiguation depending on the context, the place to do it is disambiguation.xml not multiwords.txt). 
Related to this, in some languages all tagged words are ignored by the spelling rule. That is not the case in English. If you want to ignore spelling for multiwords, we need to add this "ignore spelling"   someway.

We can do the same in English (all things or some):
* Remove the angular brackets.
* Ignore spelling.
* Remove all previous tags.

Tell us what is your preferred behavior, and I can implement it.

**Comment by MikeUnwalla** [comment]
@jaumeortola , thank you. Now I understand.

- Brackets. Please remove the angle brackets directly (without disambiguation). Many rules have exceptions for NNP. If the angle brackets are removed, then the rules will be able to use the data that is in multiwords.txt.
- ignore spelling. Please don't do anything. We can't ignore all tagged words, because spelling is dependent on the locale (color/colour). My preference is to the ignore spelling of proper nouns. (I can easily do that in disambiguation, and if we do it there, we have more control over the edge cases.)
- Remove all previous tags. I think it makes sense to remove the other tags, but before you do anything, I'd like @danielnaber and @tiff to confirm that they agree.

**Comment by jaumeortola** [comment]
>     * ignore spelling. Please don't do anything. We can't ignore all tagged words, because spelling is dependent on the locale (color/colour). My preference is to the ignore spelling of proper nouns. (I can easily do that in disambiguation, and if we do it there, we have more control over the edge cases.)

It could be "ignore spelling" only of words tagged in multiwords.txt.

**Comment by MikeUnwalla** [comment]
> It could be "ignore spelling" only of words tagged in multiwords.txt.

I would like that. But, @danielnaber , @tiff , please confirm that you agree.

**Comment by MikeUnwalla** [comment]
@jaumeortola , to confirm, please do the following:

- Brackets. Remove the angle brackets directly (without disambiguation).
- Ignore spelling of terms that are in multiwords.txt.
- Remove all previous tags.

**Comment by jaumeortola** [comment]
@MikeUnwalla Done. Check that everything works as expected.

**Comment by MikeUnwalla** [comment]
@jaumeortola , thanks. I'll check with the snapshot tomorrow.

**Comment by MikeUnwalla** [comment]
@jaumeortola , thank you.

Multiwords.txt does exactly what I want/expect. It will be very useful.

**Comment by jaumeortola** [comment]
A precision about case sensitivity. Multiwords is now case-sensitive, but it allows optionally the capitalization of the first letter of the first word. In English, as you can see, this capitalization is enabled now. If you prefer another solution (all uppercase, title case...), we can change it.

**Comment by MikeUnwalla** [comment]
>  In English, as you can see, this capitalization is enabled now.

@jaumeortola , I don't see any changes. Can you post a link to the commit?

**Comment by jaumeortola** [comment]
The capitalization was enabled in the first commit. That means that the entry "ménage à trois" allows "ménage à trois" and "Ménage à trois", but not "Ménage à Trois" or "MÉNAGE À TROIS".

**Comment by MikeUnwalla** [comment]
I see.

To allow all uppercase automatically would be useful. I cannot think of a situation in which either a dictionary term or a proper noun cannot be used correctly in uppercase.

I **think** that to allow title case would be good. (Except for stupid typography [think _iPad_], proper nouns already have an initial upper case letter.)

@tiff, what do you think?

**Comment by tiff** [comment]
@MikeUnwalla I agree, multiwords should automatically allow all-uppercase and title case.

To be clear:
If multiwords contains "Vincent van Gogh" then "Vincent Van Gogh", "VINCENT VAN GOGH" and "Vincent van Gogh" should be tagged.

**Comment by MikeUnwalla** [comment]
> " then "Vincent Van Gogh", 

@tiff, I don't agree.

As best I know, "Vincent Van Gogh" is not correct typography.

**Comment by tiff** [comment]
Then we still have to use disambiguation to ignore spelling or to set POS. Another example: A user uses "Bon Voyage" in a headline (which I think is valid). Currently, this is in a disambiguation rule that ignores case.

**Comment by jaumeortola** [comment]
In my opinion, it would be better to add the POS tags to "Vincent Van Gogh", and deal with the possible typographical errors in different rules. For example, a rule that suggests "Gone with the Wind" to replace "Gone With The Wind" (but there are different criteria for with/With: https://capitalizemytitle.com/ufaqs/do-you-capitalize-with-in-a-title/).

**Comment by MikeUnwalla** [comment]
@tiff, to clarify, I was suggesting different behaviours for different POS.

But, I accept @jaumeortola 's suggestion. So, we are all agreed, I think.

**Comment by jaumeortola** [comment]
Then:
* Allow all uppercase.
* Allow first letter uppercase
* Allow title case (different from first letter). In which style? This is language dependent, and a bit more difficult to implement. If it is going to affect only few cases, maybe it’s not worth it.

**Comment by MikeUnwalla** [comment]
@jaumeortola , I'm struggling, I don't really know. Here are my thoughts:

Title case _could_ affect a large proportion of terms (dictionary terms, not proper nouns). But, title case is (or should be) used only in titles. So, possibly, there won't be a large proportion of errors when we consider a text in its entirety.

As you wrote, there is the problem of style. LT should not impose a style on the users.

For proper nouns, you suggested that the rule could add the POS tags to "Vincent Van Gogh", although the typography is not correct. Then, have a rule that finds the incorrect typography.

So, _in theory_ (I am not suggesting that you do this), we could accept all the various capitalizations. Then, have grammar rules that find non-standard (according to a particlar style guide) capitalizations. 

Even if we did that, we would still want different tagging for dictionary terms and for proper nouns. ('Taj mahal' is always incorrect. It must be 'Taj Mahal' or 'TAJ MAHAL'.)

My suggestion. For proper nouns, if the English maintainers use multiwords.txt only for simple cases such as 'Taj Mahal' (not 'Gone with the Wind'), then I think that the problem goes away. This would work, I think:

- Allow the term with the capitalization that is in multiwords.txt. (Lower case for dictionary terms and initial capitals [usually] for proper nouns.)
- Allow all uppercase for all terms (dictionary terms and proper nouns [NNP/NNPS]).
- Allow first letter uppercase for all terms except those that are tagged NNP/NNPS.

@tiff , your thoughts?

**Comment by jaumeortola** [comment]
It is important to keep it simple and understandable. This is my proposal. We will get more or less the same results that Mike wants.
* For lower case expressions (quid pro quo) allow also sentence case (Quid pro quo), all uppercase (QUID PRO QUO) and first uppercase (Quid Pro Quo).
* For mixed case expressions (Vincent van Gogh; van Gogh; Taj Mahal; Organisation of Islamic Cooperation) allow also sentence case (Van Gogh) and all uppercase (VINCENT VAN GOGH, VAN GOGH; TAJ MAHAL, ORGANISATION OF ISLAMIC COOPERATION). 

Or even simpler (this configuration can be shared by different languages):
* Allow sentence case and all uppercase. 
* Add manually first uppercase when necessary (Quid Pro Quo).

**Comment by MikeUnwalla** [comment]
@jaumeortola , I'm happy with your simpler option that can be shared.

@tiff , what do you say?

**Comment by tiff** [comment]
Sounds good. Go for it!

**Comment by jaumeortola** [comment]
Done here: https://github.com/languagetool-org/languagetool/commit/86972d7ad01f34d3012649483a53a06189f788f4
Only added all uppercase.

**Comment by MikeUnwalla** [comment]
@jaumeortola , great, thank you.
