### ISSUE TITLE
added.txt not taken into account for check

### ISSUE THREAD

**Issue by jnavila** [languagetool-org/languagetool#305]
With languagetool 3.0, I created for French the following `added.txt`:
```
# A part-of-speech dictionary that's used additionally to the binary dictionary (*.dict)
# File Encoding: UTF-8
# Format: three tab-separated fields: fullform baseform postags
Git	Git	Z

Perforce	Perforce	Z e sp

commit	commit	N m s

commits	commit	N m p

rebasage	rebasage	N m s

rebasages	rebasage	N m p

rebasant	rebaser	V ppr

rebase	rebaser	V ind pres 1 s

rebase	rebaser	V ind pres 3 s

rebaser	rebaser	V inf

rebasons	rebaser	V ind pres 1 p

rebasons	rebaser	V imp pres 1 p

rebasez	rebaser	V imp pres 2 p

rebasez	rebaser	V ind pres 2 p
```

when checking inline with -t the following sentence:
```
Dans Git et dans Perforce, il y a deux façons d'intégrer les modifications d'un commit dans un autre : en fusionnant (`merge`) et en rebasant (`rebase`).
```

the words are correctly recognised and tagged. However, when running in check mode, the processing seems to be done as if the `added.txt` file did not exist.

**Comment by danielnaber** [comment]
Thanks for your report. If you want to avoid spelling errors to be report for these words, you'll need to add them to `hunspell/spelling.txt` oder `hunspell/ignore.txt`. Tagging and spelling are handled separately by LanguageTool.

**Comment by jnavila** [comment]
Thank you for the tip.
