### ISSUE TITLE
[fr] use Morfologik rule for French spelling

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#3055]
There are some issues that can't be fixed with the current spelling rule used in French. 

* There are no spelling suggestions for words like *ecoute-moi, *ecrit-il...
* There are problems with suggestions for wrong split words. See #2900.
* The frequency information for sorting spelling suggestions is not used.

We can solve these problems just using the Morfologik rule. Probably, we will need to write some additional rules to detect errors that now are only detected by the current spelling rule (elisions l', d'...; hyphenated pronouns, etc.). Then plan is:

* Use Morfologik spelling rule in French.
* Look at the differences checking a corpus. 
* Add the necessary new rules for undetected errors.

**Comment by jaumeortola** [comment]
See also an alternative to Morfologik: SymSpell.

**Comment by jaumeortola** [comment]
New Morfologik speller in branch: https://github.com/languagetool-org/languagetool/tree/fr-new-speller

**Comment by jaumeortola** [comment]
The dictionary for spelling will be the dictionary used for tagging. There is no need for another binary file because the source is the same (Dicollecte). Frequency data can be added to the tagger dictionary. Is it okay if this new binary file is in an outside dependency (as it is done for Catalan and Spanish dictionaries)? Where is the best place to put this dictionary? Catalan and Spanish are in personal accounts in GitHub and Sonatype. @danielnaber

**Comment by jaumeortola** [comment]
Rules that have to be created:
* [ ] Check incorrect "elision": j'vais, l'descendre
* [ ] Check incorrect "elision" on aspirated 'h': l'hibou (?)

**Comment by danielnaber** [comment]
> Is it okay if this new binary file is in an outside dependency (as it is done for Catalan and Spanish dictionaries)?

Yes, that's okay. Do you want me to open a new repo for that at https://github.com/languagetool-org? Just let me know how you want it to be named.

**Comment by dpelle** [comment]
@jaumeortola wrote:

> Check incorrect "elision" on aspirated 'h': l'hibou (?)

How does it work?  Only Dicollecte knows whether the elision should happen or not in words starting with h.  There is no general rule for this, it has to be tagged for each word. Some examples:
* words where elision must always be done: l'homme,  j'hésite, j'habite, etc.
* words where elision must never be done: le hibou, la Hollande, je hurle, etc.

**Comment by jaumeortola** [comment]
> How does it work? Only Dicollecte knows whether the elision should happen or not in words starting with h. There is no general rule for this, it has to be tagged for each word.

Thanks for the answer, @dpelle. This rule should be the opposite of "ELISION". The exceptions in ELISION are the patterns we need to match. See the patterns at the start of grammar.xml:
```
<!ENTITY exceptions_ELISION1 "onze|onzièmes?...
<!ENTITY exceptions_ELISION2 "haye|avec|hausse|et|hayley...
<!ENTITY H_ASPIRE "habanera|hâbler|hâblerie...
```
Are these patterns exhaustive (or good enough)?
