### ISSUE TITLE
English postag error for 'brief'

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#306]
Hello,

LT gives the word 'brief' the postag VBG (gerunds/present participle).

Regards,

Mike Unwalla

**Comment by danielnaber** [comment]
Fixed in dev version.

**Comment by MikeUnwalla** [comment]
The fix is not in LT 3.1. Should it be in LT 3.1?

**Comment by danielnaber** [comment]
No, it was fixed one day after the release.
