### ISSUE TITLE
[en] false alarm AUXILIARY_DO_WITH_INCORRECT_VERB_FORM

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3061]
> It was strange, but I had great trouble getting to sleep last night and probably only did so minutes before the quake.

From: https://internal1.languagetool.org/regression-tests/via-http/2020-06-11/en/result_grammar_AUXILIARY_DO_WITH_INCORRECT_VERB_FORM[1].html

**Comment by MikeUnwalla** [comment]
Fixed in https://github.com/languagetool-org/languagetool/commit/4661f605f10b91507433e50d0f81f387ae0e91e5

**Comment by MikeUnwalla** [comment]
Sorry, I should have made an issue before I fixed the error.

**Comment by tiff** [comment]
No, no worries :)
