### ISSUE TITLE
[fr] incorrect suggestion for "bonne sante"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3068]
Another one similar to https://github.com/languagetool-org/languagetool/issues/2900
> bonne sante

![Bildschirmfoto 2020-06-12 um 08 11 36](https://user-images.githubusercontent.com/37363/84470869-811c5680-ac84-11ea-998b-84dc5135535b.png)

> qu’il sagissait
![Bildschirmfoto 2020-06-12 um 08 15 05](https://user-images.githubusercontent.com/37363/84471037-d6586800-ac84-11ea-8e09-903e00d53c2b.png)

@jaumeortola can we easily add those cases, so a better suggestion is generated?

**Comment by jaumeortola** [comment]
To get a more complete solution see  #3055
