### ISSUE TITLE
[ar] Missing word?

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3069]
@sohaibafifi 

User feedback:

> mashaallah is an arabic word, please add

**Comment by sohaibafifi** [comment]
It is but using Arabic letters. A sentence of three words by the way.  

The user wants maybe to add it to the global added.txt ?

**Comment by danielnaber** [comment]
So you mean it's already part of the dictionary (with Arabic letters) and we can close this issue?

**Comment by sohaibafifi** [comment]
Yes it is: ما شاء الله
