### ISSUE TITLE
ЕАЭС (Russian) marked as error

### ISSUE THREAD

**Issue by dg333** [languagetool-org/languagetool#308]
Using LT latest 3.1 snapshot (20150908) in LibreOffice 5.0.0.4 / MS Windows 7. For Russian, LT marks as an error the abbreviation of ЕАЭС (= Евразийский экономический союз) issuing the following message:
> Выделение текста ЗАГЛАВНЫМИ буквами

Since the above abbreviation is quite widely used, this error message is obviously incorrect.

I see no option to attach a file, thus a sample text here:

1. Насколько, по Вашему мнению, гармонизировано законодательство в странах ЕАЭС относительно регулирования рынка? Имеются ли законодательные трудности при осуществлении экспортно-импортных операций со странами ЕАЭС?

**Comment by danielnaber** [comment]
Ping @yakovru who can probably help.

**Comment by yakovru** [comment]
I add this word to LT dictionary now. And I improve "ALL_CAPS" rule.
