### ISSUE TITLE
[de] nicht gefunden "Gesetzt"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3087]
Nicht gefunden:
> Das Gesetzt.

**Comment by tiff** [comment]
@danielnaber können wir das einfach auf die prohibit.txt packen oder gibt es einen Fall wo "Gesetzt" großgeschrieben wird?

**Comment by danielnaber** [comment]
"Gesetzt habe ich mich auf den Stuhl" :-) Also eine case-sensitive-Regel wäre sicherer.
