### ISSUE TITLE
[fr] "Cest" should suggest "C'est" first

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3096]
> Cest bien

<img width="415" alt="Bildschirmfoto 2020-06-16 um 10 04 52" src="https://user-images.githubusercontent.com/37363/84748407-e50e8a00-afb8-11ea-8626-434b636c3646.png">

**Comment by tiff** [comment]
@jaumeortola @danielnaber does it make sense to prioritize spelling suggestions if they equal the original word (with apostrophes stripped)?

**Comment by jaumeortola** [comment]
> does it make sense to prioritize spelling suggestions if they equal the original word (with apostrophes stripped)?

Yes, it makes sense. I do it in Catalan (for apostrophes, hyphens or split words). Sometimes they are put in the first position, but sometimes in the second. I can re-use part of the code. 

This is related to #3055. We should decide about the spelling rule first, and then fix the details like "cest>c'est".

**Comment by tiff** [comment]
Ok, agree

**Comment by jaumeortola** [comment]
We are already using the new French speller, and we have suggestions for "lhomme>l'homme". Now we need examples of this kind of spelling errors in order to adjust the spelling rule and improve the suggestions. @vkyfox 

"C'est" needs a specific rule because of the time zone abbreviation.

**Comment by vkyfox** [comment]
There are rules for CEST/C'est.
Do you need examples of misspelled words?

**Comment by jaumeortola** [comment]
The rule for CEST/C'est is OK, I know it. I mean examples like "lhomme>l'homme", "Vouliezvous>Vouliez-vous", suggestions including apostrophe or hyphen. Now we can give better suggestions, but we need to do some adjustments. For example, the best suggestion for "nauriez" should be "n'auriez" (we don't give this one yest), and so on.
