### ISSUE TITLE
[ar] error offsets wrong?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3098]
Take this text:
> عن واستمرت الأوروبيّون أخذ, قد واستمر الجنود باستخدام وتم, المدن القادة محاولات ولم عن. ثم أضف وسمّيت الإقتصادي, أسر كل مليون الخاسرة بالتوقيع. بشكل ليركز لم عدد, تم ودول ساعة للسيطرة الى, المنتصر اليابان بين أم. وقد عل العدّ بمباركة, أخذ و فكان للصين لهيمنة.
و حول دارت واعتلاء, و كما الفترة واشتدّت, الأجل البرية الرئيسية شيء بل. لمّ أدنى اسبوعين مع. ليبين المؤلّفة وصل لم, من ضرب جمعت استرجاع التقليدية. ثم شيء أعمال إستعمل ليرتفع. جهة ان عقبت الخاطفة بولندا،, ٣٠ هاربر انتهت وبحلول بحث.
ذلك مارد السيطرة اليابان، من, بعد أمّا ومطالبة ان, ثم الى استدعى الصعداء الإمداد. حتى لعدم أحكم اعلان بل, خيار إجلاء وإيطالي أم لمّ, تعد عن التي وبدأت ولكسمبورغ. لها بـ أكثر وصغار, ٣٠ مدن إحكام سبتمبر. تم هُزم لغات أسر, به، أن لكون شاسعة. بـ كما يطول الأمور بريطانيا-فرنسا.
بحق مع مايو بشرية. لم وصل وأزيز لعملة, دول مشروط فشكّل عن. غضون فمرّ استبدال من وفي, عن دون جسيمة المضي. جيوب قُدُماً الخارجية عدم عل, وبعض اوروبا وانتهاءً مكن في.

I think the offsets of the errors are wrong:

<img width="903" alt="Bildschirmfoto 2020-06-16 um 11 53 01" src="https://user-images.githubusercontent.com/37363/84760286-18a4e080-afc8-11ea-8596-634e443a7f16.png">

Tested on languagetool.org

cc @danielnaber @sohaibafifi

**Comment by tiff** [comment]
Seems to be caused by the character "و".

As soon as this character is present the offset is incorrect:
![Bildschirmfoto 2020-06-16 um 12 30 19](https://user-images.githubusercontent.com/37363/84763935-3cb6f080-afcd-11ea-98b3-32725e85f0bb.png)

**Comment by sohaibafifi** [comment]
Thank you, I will check this.
Actually it looks like happening when we have diacritics + the character "و" (the and) 
![Capture d’écran 2020-06-16 à 13 15 02](https://user-images.githubusercontent.com/1006521/84767824-64a95280-afd3-11ea-8ea4-42b0355fb928.png)

**Comment by linuxscout** [comment]
fixed, @danielnaber please close it.
