### ISSUE TITLE
nightly diff enhancement 2

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#3104]
It would be great if not only tonight's diff, but also the full output for a rule could be requested.
When a rule is tweaked, it is hard to see what the full result is, since the baseline is gone because the diff is only with yesterday, not with the days before.

**Comment by danielnaber** [comment]
This has been implemented for some time. For example: https://internal1.languagetool.org/regression-tests/via-http/2021-06-24/en-US_full/
