### ISSUE TITLE
[en] False alarm DID_BASEFORM 

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3107]
'Amazing' is an adjective. The sentences are correct:

> What the offensive line did was **amazing**.

> What the team did was **amazing**.

**Comment by tiff** [comment]
Same with:
> What the offensive line did was interesting.

**Comment by SkyCharger001** [comment]
it would be slightly more readable if you put a comma before "was". (also gets rids of the FPs)

**Comment by MikeUnwalla** [comment]
Also: The tests that the technicians sometimes did were fascinating.
