### ISSUE TITLE
False Alarms / Bugs LibreOffice

### ISSUE THREAD

**Issue by AgnesKleinhans** [languagetool-org/languagetool#3109]
<img width="651" alt="Bildschirmfoto 2020-06-17 um 13 30 22" src="https://user-images.githubusercontent.com/52399934/84893258-3ee97f80-b09f-11ea-8ac1-0dd4c4a443a8.png">

LT states Spellchecking is complete, even though it is clearly not (about 40 pages with already found errors left).

<img width="555" alt="Bildschirmfoto 2020-06-17 um 13 18 03" src="https://user-images.githubusercontent.com/52399934/84893282-44df6080-b09f-11ea-8773-393922c8f452.png">
<img width="575" alt="Bildschirmfoto 2020-06-17 um 12 52 01" src="https://user-images.githubusercontent.com/52399934/84894661-6e00f080-b0a1-11ea-9028-4bcf41c09cfc.png">

LT triggers warnings for sentences with no mistakes, also LT suggests the wrong messages + labels wrongly. The error occurred after a few times clicking on "resume" or "ignore once".

**Comment by FredKruse** [comment]
The problem should be solved. Please test it tomorrow and close the issue.
@danielnaber After the last to issues are solved the version can be published, I think.

**Comment by FredKruse** [comment]
The bug is fixed, I close the issue
