### ISSUE TITLE
[en] "litehouse" doesn't suggest "lighthouse"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3116]
![Bildschirmfoto 2020-06-17 um 17 32 33](https://user-images.githubusercontent.com/37363/84918155-8a605580-b0c0-11ea-932f-9e9b1b2f576b.png)

**Comment by danielnaber** [comment]
TODO: add `lite light` to `fsa.dict.speller.replacement-pairs`, but would be nice to have a test corpus first.
