### ISSUE TITLE
[en] false alarm THERE_S_MANY

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3118]
> Per head of population, there is five times as much venture capital available in America as there is in Europe.

Via https://internal1.languagetool.org/regression-tests/via-http/2020-06-18/en/result_grammar_THERE_S_MANY[4].html

**Comment by MikeUnwalla** [comment]
Caused by my change to NUMBER_TIMES (https://github.com/languagetool-org/languagetool/commit/972d22ecb3dc806425b20a4cbc2678654c7bff29)
