### ISSUE TITLE
[en] false alarm YOUR_NN

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3119]
> You're ten times heavier than I am.

Via https://internal1.languagetool.org/regression-tests/via-http/2020-06-18/en/result_grammar_YOUR_NN[1].html

**Comment by MikeUnwalla** [comment]
Caused by my change to NUMBER_TIMES (https://github.com/languagetool-org/languagetool/commit/972d22ecb3dc806425b20a4cbc2678654c7bff29)
