### ISSUE TITLE
[fr] "4g" 

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3127]
For "4g" we currently suggest putting a space in between (ESPACE_UNITES), because we assume the user meant "grams".
However, "4g" Could also be "4G" (cellular communication).
We should have a rule that suggests both "4 g" or "4G".

**Comment by jaumeortola** [comment]
We could use a simple replace Java rule for this kind of things, so we can write:
```
3g=3G|3 g
4g=4G|4 g
5g=5G|4 g
```
This rule doesn't exist in French, but I think it is useful for any language.
