### ISSUE TITLE
testrules: show the progress of the tests for disambiguation

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3129]
In the same way that testrules gives a message for each 100 grammar rules that it tests, make it give a message for each 100 disambiguation rules that it tests.

Reason. When there are many disambiguation rules, nothing seems to happen for a while. It would be nice to to know that all is well.

**Comment by danielnaber** [comment]
Done. However, that part of the test "only" takes 10 seconds for me. If it's much slower for you, let me know, maybe something else is wrong then.

**Comment by MikeUnwalla** [comment]
@danielnaber , wow, that was quick. Thank you!

Nothing is wrong. I just have a lot of complex disambiguation rules. Here are the numbers if there is only 1 grammar rule.

LanguageTool:
```
Checking example sentences of 1 rules for English...
Skipped 0 rules for variant language to avoid checking rules more than once
1 rules tested.
Tests finished!
Running disambiguator rule tests...
Running disambiguation tests for English...
796 rules tested (7162ms)
Disambiguator tests successful.
```


STE term checker
```
Checking example sentences of 1 rules for English...
Skipped 0 rules for variant language to avoid checking rules more than once
1 rules tested.
Tests finished!
Running disambiguator rule tests...
Running disambiguation tests for English...
1124 rules tested (71783ms)
Disambiguator tests successful.
```
