### ISSUE TITLE
[en] no errors on this string

### ISSUE THREAD

**Issue by Tokay2020** [languagetool-org/languagetool#3134]
I tested this comment in LanguageTool Chrome extension support:
«
seeing eye dog cats eye translations for me to use
perhaps a seeing eye dog or a cane to help me comprehend future clues and ability to contact my fold
Posted by AprilDawn Roberts - 2 days ago
»
https://chrome.google.com/webstore/detail/grammar-and-spell-checker/oldceeleldhonbafppcapldpdifcinji?hl=en

It shows no error detected, apart from correcting the uppercase of the first word.

I have also tried it on https://languagetoolplus.com/ with the same results. 

@danielnaber Is this a temporary issue, or is something blocking detection on my browser?

**Comment by danielnaber** [comment]
Even I as a human don't understand what's that supposed to mean. LT works with statistics and patterns, so it requires a text that is at least somewhat close to correct in order to detect errors.

**Comment by Tokay2020** [comment]
Does closing this issue mean that it is working as supposed and English language detection is as it is supposed to be? Nothing to improve?

**Comment by danielnaber** [comment]
Improvements and pull requests are welcome, but I think this issue not specific enough.

**Comment by Tokay2020** [comment]
I get it. Kind of embarrassing to keep it open. Just think about it. Cheers ;)
