### ISSUE TITLE
In french missing a rule for "avoir été", ok for plural, not for "féminin pluriel"

### ISSUE THREAD

**Issue by ArfyFR** [languagetool-org/languagetool#314]
Hi,
If I type "Les voitures sont inventé.", the tool find the typo (missing "es" to "inventé").
If I type "Les voitures ont été inventé." it doesn't detect the error.  It only propose "s" and not "es".
Regards,
Pascal

**Comment by f-knorr** [comment]
Closing this call, as it the errors is detected now:

> Les voitures ont été `inventé.

```
1.) Line 1, column 22, Rule ID: ETRE_VPPA_OU_ADJ[5]
Message: Le mot masculin « inventé » n’est pas accordé en genre avec le mot féminin « voitures ».
Les voitures ont été inventé. 
```
