### ISSUE TITLE
IndexOutOfBoundsException in LibreOffice add-on

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3147]
![Bildschirmfoto von 2020-06-22 16-49-17](https://user-images.githubusercontent.com/857004/85302099-0388ef80-b4a9-11ea-9938-daa6154da0b2.png)

happened when loading https://github.com/languagetool-org/languagetool/raw/master/languagetool-office-extension/src/test/resources/manual-testing.odt and slowly scrolling down (not faster than the blue underlines appeared). Could not reproduce it when trying another time, though.

**Comment by FredKruse** [comment]
The bug is fixed, I close the issue
