### ISSUE TITLE
[DE] Falsche Regel! "zufrieden stellen"

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#3150]
Moin liebes LanguageTool-Team

Thea ist zurückhaltend und gibt ihr Bestes, um mich **zufrieden zu stellen**.
LT: "Wenn der erweiterte Infinitv von dem Verb 'zufriedenstellen' abgeleitet ist, **muss** er zusammengeschrieben werden."
Zuständige Regel "Erweiterter Infinitiv mit zu (Zusammenschreibung)"

Laut [korrekturen](https://www.korrekturen.de/wortliste/zufriedenstellen.shtml) und [Duden](https://www.duden.de/rechtschreibung/zufriedenstellen) muss "zufriedenstellen" nicht zusammengeschrieben werden. Es ist nur eine Empfehlung.

Grüße Dallun511

**Comment by FredKruse** [comment]
Habe das Wort 'muss' im Beschreibungstext zu 'sollte' geändert. Das macht deutlich, dass es nur eine Empfehlung ist.
