### ISSUE TITLE
[en] "230 volt" or "230 volts"?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3157]
> It has 240 volt.

![Bildschirmfoto 2020-06-24 um 14 21 14](https://user-images.githubusercontent.com/37363/85555258-04935b80-b626-11ea-86a8-960ee2a90930.png)

Does it really need to be plural here?
Same applies for "liter", "milligrams", ...

**Comment by MikeUnwalla** [comment]
As best I know (without researching the question), it should be plural.

**Comment by SkyCharger001** [comment]
this reads as a pure count, so plural is how it should be. 
It's when it's used as a modifier that the singular is used. 
(EG: "I've got five 9 Volt Batteries" vs "this wire carries a thousand volts from North to South Dakota")

**Comment by tiff** [comment]
Thanks. I'm closing this then.
