### ISSUE TITLE
[pt] Replacement for "código fonte"

### ISSUE THREAD

**Issue by hmslima** [languagetool-org/languagetool#3159]
LT doesn't know a replacement for the Portuguese expression "código fonte". It's correct form is "[código-fonte](https://pt.wikipedia.org/wiki/C%C3%B3digo-fonte)".

**Comment by marcoagpinto** [comment]
LT 5.0 is to be released on Friday.

Only after its release I will resume fixing/adding rules.

**Comment by marcoagpinto** [comment]
@hmslima 

Fixed: https://github.com/languagetool-org/languagetool/commit/5996e5626ed62c8542dc04a055da06894f356767
