### ISSUE TITLE
[en] false alarm? "How much does that change over time?"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3162]
> How much does that change over time?

LT wants "many", rule `MUCH_COUNTABLE[1]`

**Comment by MikeUnwalla** [comment]
Possibly, the text is correct, possibly, it is not correct. It's a semantic problem, not a grammar problem.

**Comment by MikeUnwalla** [comment]
Fixed (https://github.com/languagetool-org/languagetool/commit/19d5c05ab6a03e28e6fe01741d7c911a9be3d156)
