### ISSUE TITLE
Some emojis not accepted in (at least) English

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3164]
> This is English text 🗺️.

```
1.) Line 1, column 22, Rule ID: MORFOLOGIK_RULE_EN_US prio=-10
Message: Possible spelling mistake found.
Suggestion: ☀️; ✔️; ❤️
This is English text 🗺️. 
                     ^^^  
```

**Comment by Tokay2020** [comment]
I can confirm. It is quite interesting that this one doesn't work, given that the following work well:
🤘 🤙 👉 👈 👆 🖕 👇 🤬 💩 🤑 🧑‍🤝‍🧑 👭 👫 👬
Any good reason for the map symbol to be excluded from the emoji list?

**Comment by Tokay2020** [comment]
Also on the matter:
👉🏼✊🏼💪🏼  - here the ✊🏼 is flagged. No ✊🏼 them.
👉🏼👌🏼- is ok

**Comment by Tokay2020** [comment]
😏 🤸🤾‍♂️ 🤥 🗯😷 🤭🥴 🤢 🤮 is also ok.

**Comment by danielnaber** [comment]
The problem seems to be in `org.languagetool.rules.spelling.morfologik.MorfologikSpellerRule#isSurrogatePairCombination`, which only expects emojis made up of two characters, but the map symbol is made up of three. Maybe @f-knorr has an idea, he wrote that code originally.
