### ISSUE TITLE
LibreOffice in Catalan: not using personal dictionary

### ISSUE THREAD

**Issue by AlbertVR** [languagetool-org/languagetool#3169]
Hello all,

I just installed LanguageTool, it works fine... but for my personal dictionary. I have a couple of them, and all the words in there are underlined as if they do not exist.

LanguageTool version: 4.8
LibreOffice version: 6.0.7.3
O.S.: Ubuntu 18.04.4 LTS

Thanks!

Albert

**Comment by jaumeortola** [comment]
In most languages, LanguageTool doesn't give spelling errors on LibreOffice; spelling is done by the Hunspell dictionary. But in Catalan, the spelling rule is on by default because it is slightly better than Hunspell (but the user needs to disable manually the Hunspell spelling for this to make sense).

The only fix at this time is to disable the LanguageTool spelling rule. Go to Tools  > LanguageTool > Settings  > Grammar rules > "Errors ortogràfics" and disable the rule "Possible error ortogràfic". 

We should think a better way to handle this.

**Comment by AlbertVR** [comment]
Done. Thank you very much!

**Comment by AlbertVR** [comment]
It seems to be not working... I even deactivated the whole "Errors ortogràfic" section, and everything is still underlined... :-(

Why don't you check personal dictionaires also? ;-)

**Comment by jaumeortola** [comment]
It works for me. Are you sure the selected language is correct? If everything is underlined you probably are not checking the text in Catalan.

Personal dictionaries depend on the user interface. Different methods are needed for every UI (web, browser extensions, etc.). It is not trivial. And LanguageTool on LibreOffice doesn't do spelling for most languages.

**Comment by AlbertVR** [comment]
Yes, the proper language is selected, it is only the words in my personal dictionary that are underlined (and my wrong typings, of course :-)   )

**Comment by jaumeortola** [comment]
Is the underline in your personal words red or blue? If the settings are not changed, red is Hunspell and blue is LanguageTool.

It works for me with words in my personal dictionary. But I am using a newer version of LanguageTool. You can try with 5.0, the version just released: https://languagetool.org/#libreoffice

**Comment by AlbertVR** [comment]
It is blue.
Did you just release this version? I downloaded the plugin yesterday! :-)

It tried the new version in my desktop (Ubuntu) -> Not working.
I tried in my laptop (Windows 10) -> Working perfectly.

So it is either a Linux Issue, or something wrong in my desktop... (version 4.8 did not behave as expected in both computers)

Anything you feel I might check?

Thanks!

**Comment by jaumeortola** [comment]
You can try this:
* remove the old configuration file: /home/username/.languagetool-ooo.cfg
* remove the new configuration file: /home/username/.config/LanguageTool/LibreOffice/Languagetool.cfg
* disable again the rule "Possible error ortogràfic" in the LanguageTool settings

**Comment by AlbertVR** [comment]
Now it works as expected! Thank you very much!
