### ISSUE TITLE
[LibreOffice GUI] Inconsistent user interface, very different user experience

### ISSUE THREAD

**Issue by genodeftest** [languagetool-org/languagetool#317]
The LanguageTool GUI in LibreOffice feels alien: It looks very different in that it uses a LookAndFeel that isn't even trying to resemble LibreOffice's theme or the current Gtk theme. The scroll behavior in this L&F is also quite inconsistent to most other desktop applications. How about using the system's native LookAndFeel?

**Comment by danielnaber** [comment]
Fixed by https://github.com/languagetool-org/languagetool/commit/dae781f7cf1ee7b156a884ae525cfc5306ad6f6c
