### ISSUE TITLE
[de] Missing words: Apraxie and Apraxien

### ISSUE THREAD

**Issue by sb0stn** [languagetool-org/languagetool#3175]
The tool is missing the word "Apraxie" and its plural form "Apraxien", a motor disorder. 

See the following article in the Duden: https://www.duden.de/rechtschreibung/Apraxie

**Comment by danielnaber** [comment]
Could you send a screenshot? The words are properly detected for me. How do you use LT, as an add-on or on the website?

**Comment by Dallun511** [comment]
@danielnaber 
Für Webseite
![grafik](https://user-images.githubusercontent.com/40240507/86079822-b05b0200-ba91-11ea-922e-602fa7ece6cf.png)

Und für die Token
![grafik](https://user-images.githubusercontent.com/40240507/86079844-bf41b480-ba91-11ea-9bb5-81f82454e376.png)

Die Bilder. Ich hoffe, du kannst damit arbeiten.

**Comment by Dallun511** [comment]
PR #3178 & #3177 sind bereit. Damit sollte das Wort erkannt werden.

**Comment by danielnaber** [comment]
@Dallun511 weißt du noch, wann genau du den Screenshot gemacht hast? Weil @janschreiber hat "Apraxie" am 27.6. hinzugefügt, es sollte jetzt akzeptiert werden. Kannst du es nochmal testen?

**Comment by sb0stn** [comment]
@danielnaber Danke für Deine Antwort. Ich habe mal versucht das Problem zu nochmal zu erzeugen und stellte fest, das Problem tritt nur in der Premium Version auf. Ich hoffe das Issue war daher hier nicht falsch... 

Für mich tritt es in der Premium Version auf, da der Request an `https://api.languagetoolplus.com/v2/check` geht statt `https://api.languagetool.org/v2/check`, wo ne ältere Version installiert ist.

**Comment by danielnaber** [comment]
@sb0stn Die Premiumversion wird immer etwas länger getestet, deshalb sind die Änderungen dort nicht sofort sichtbar. Aber nächste Woche sind die neuen Wörter dann auch dort angekommen.

**Comment by Dallun511** [comment]
@danielnaber 30.06.2020 5:20 
Das weiß ich sogar genau, weil ich den Screenshot ein paar Minuten später hochgeladen habe.

Grüße Dallun511

**Comment by danielnaber** [comment]
@Dallun511 Hast du das Wort per Copy/Paste eingefügt oder eingetippt? Ich kann das nämlich nicht nachvollziehen:

![Bildschirmfoto von 2020-06-30 15-27-27](https://user-images.githubusercontent.com/857004/86132003-a0b9d880-bae6-11ea-9d65-65d50d200c5a.png)

**Comment by Dallun511** [comment]
Das funktioniert auch nicht mehr.
Ja, ich habe Copy/Paste verwendet.
![grafik](https://user-images.githubusercontent.com/40240507/86132384-18880300-bae7-11ea-9d38-cef87dde3f58.png)
Wie bei diesem Screenshot auch (wurde gerade erstellt)

Das Wort habe ich zuerst in LO geschrieben und von dort aus Copy/Paste auf die Webseite ausgeführt.
Um 5 Uhr morgens wurde das Wort als Fehler markiert. Vielleicht war ich zu früh oder mein Cashe war schuld.
Ich besuche schließlich eure Webseite sehr häufig, da kann das passieren.
