### ISSUE TITLE
[de] wrong suggestion DE_AGREEMENT

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3184]
> Danke für Ihren Verständnis.

<img width="444" alt="Bildschirmfoto 2020-06-30 um 17 50 48" src="https://user-images.githubusercontent.com/37363/86147945-4c205880-bafa-11ea-9bff-8f79384f78a0.png">

**Comment by Dallun511** [comment]
Heiß das nicht eigentlich "Danke für Ihr Verständnis"?
