### ISSUE TITLE
[DE] Fehlalarm "Die Ruhe"

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#3187]
Moin liebes LanguageTool-Team

Ferewa sagte: „Ich muss telefonieren und dafür brauche ich (meine) **Ruhe**.“
LT: "Meinten Sie die Verbform "ruhe", die dann kleinzuschreiben ist?"

Wenn man den Vorschlag befolgen würde, passiert das.
Ferewa sagte: „Ich muss telefonieren und dafür **brauche ich ruhe**.“
LT: "Hier sollte ein Komma eingefügt werden, wenn es sich bei dem hinteren Satzteil um einen Nebensatz handelt."

Bitte beheben, wenn ihr gerade Zeit habt.

Grüße Dallun511

**Comment by danielnaber** [comment]
Das erste kann ich nicht nachvollziehen auf languagetool.org, ich nehme an, es passiert dir in LibreOffice?

**Comment by Dallun511** [comment]
Ferewa sagte: „Ich muss telefonieren und dafür brauche ich Ruhe.“
nimmt "meine" weg und es kommt der Fehlalarm. 
Meine ist nur eingeklammert, da man auch meine Ruhe schreiben kann.
Nur das weglassen von meien Ruhe löst einen Fehlarm aus.

**Comment by danielnaber** [comment]
> dafür brauche ich Ruhe

Den Fehlalarm habe ich behoben, bleibt noch der mit dem Komma.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/86513769-2ef6cd00-be0d-11ea-8a0f-f09372a24cb4.png)
Kann es sein, dass du das Problem gelöst hast?

**Comment by Dallun511** [comment]
> Den Fehlalarm habe ich behoben, bleibt noch der mit dem Komma.
Der Alarm mit dem Komma ist kein Fehlalarm, da **ruhe** großgeschrieben werden muss, weswegen ich diesem Problem als behoben schließe.
