### ISSUE TITLE
[pt] incorrect upper/lowercase suggestion

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3193]
> AS LETRAS ESTÃO TODAS MAIÚSCULAS MAS ELE ME SUGERE QUE 01 PALAVRA FIQUE MINÚSCULA?

![Bildschirmfoto von 2020-07-02 12-27-26](https://user-images.githubusercontent.com/857004/86348037-6c1d5c80-bc5f-11ea-8097-aac327713d33.png)

`VERB_COMMA_CONJUNCTION [14] `

**Comment by jaumeortola** [comment]
We should preserve the case. If we want to suggest changing the case ", Mas" > ", mas" (which makes sense), then we need another rule.
