### ISSUE TITLE
user feedback "commentor"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3195]
A user writes:

> Correct words are:
·       commentator
·       commenter
But your service insist that commenter be changed to the non-existent word commentor:

![image002](https://user-images.githubusercontent.com/857004/86388256-bff66880-bc94-11ea-8cf3-eef309f7f213.jpg)

**Comment by MikeUnwalla** [comment]
'Commentor' is AmE:
https://www.lexico.com/definition/commenter
https://www.merriam-webster.com/dictionary/commenter
