### ISSUE TITLE
[en] False warnings caused by several/DT

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3199]
Yesterday (2020-07-02) I added the postag DT to 'several' (https://github.com/languagetool-org/languagetool/commit/c49bacff21856e55d834eb927a894a520586e2d1).

References:
www.lexico.com/definition/several
www.merriam-webster.com/dictionary/several

That change causes many false warnings. What is the best way to deal with the problem? 

- Revert the change.
- Try to fix the false warnings (not necessary a quick or easy job)

@tiff , @danielnaber , what do you say?

**Comment by danielnaber** [comment]
I'd say revert it for now.
