### ISSUE TITLE
Using LT dictionary in LibreOffice with hyphenated words starting in uppercase

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#3200]
Hello @FredKruse 

I was trying to figure out why hyphenated words that I have added to the Portuguese added.txt and spelling.txt, such as:
COVID-19
Al-Qaeda

were not properly detected in LibreOffice.

Then I noticed that I added:
al-Assad

and it is recognised.

So, the only possible answer is that if the first part of the word uses uppercase, somehow is not used by LibreOffice.

Could you take a look?

Thanks!

**Comment by jaumeortola** [comment]
Spell-checking in LibreOffice is not done by LanguageTool, it is done by Hunspell dictionaries (see #3202). I guess you have a Hunspell spell checker enabled. What Portuguese Hunspell dictionary should I install for testing?[ This one](https://natura.di.uminho.pt/wiki/doku.php?id=dicionarios:main)? 

What do you mean exactly by "properly detected" or "recognized"? Not underlined as errors?

**Comment by FredKruse** [comment]
@marcoagpinto The spelling.txt words are stored in the dictionary that begins with the characters __LT_ 
Please open this dictionary and control if it contains the words you mentioned.

**Comment by marcoagpinto** [comment]
@FredKruse 

I have just checked.

"Al-Qaeda" is there in the personal dictionary, so I wonder why it is not fully recognised :-(

**Comment by jaumeortola** [comment]
> "Al-Qaeda" is there in the personal dictionary, so I wonder why it is not fully recognised

The reason can be the tokenization used by LibreOffice. If LibreOffice splits the word at the hyphen, there is no way to match the word.

**Comment by FredKruse** [comment]
This is LO problem, I think. So we should close the issue.
