### ISSUE TITLE
[pt] Portuguese tokenizer

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#3203]
Probably related to #3200.

Words with hyphens like "Al-Qaeda" are tokenized as ```<token>Al</token><token>-</token><token>Qaeda</token>```. If we add them to added.txt, they are not tagged appropriately. They need to be put in multiwords.txt.

Another solution is to make the tagger more intelligent, so that if a word with hyphens exists in the dictionary, it is tokenized as one token.

**Comment by marcoagpinto** [comment]
@jaumeortola 

But, if the word on the left of the hyphen is all in lowercase, it works.

I wrote in the ticket examples.

**Comment by Tokay2020** [comment]
Does this actually solve any issue, given that multiwords does that specific job without ambiguities?

**Comment by jaumeortola** [comment]
> Does this actually solve any issue, given that multiwords does that specific job without ambiguities?

There are several hundred words with hyphen in the Portuguese tagger dictionary that now are not properly tagged, and some rules will work better without further adjustments. Not much, but it is easy to implement. We just need to copy the code used in other languages.

**Comment by marcoagpinto** [comment]
@jaumeortola 

Please improved the code!

:-)

Thanks!

**Comment by jaumeortola** [comment]
In some languages (Spanish, Catalan, French), a speller or a tagger is used to decide how to tokenize some words (for example, words with hyphen). Now I want to do the same for Portuguese copying the code from the French tokenizer. But, although the code seems the same, the compiler asks to add IO exceptions. I am not sure why. The other languages don't require these exceptions. 

What is the proper way to do this, @danielnaber? See Spanish, Catalan and French word tokenizers.

**Comment by danielnaber** [comment]
@jaumeortola Can you try again now? `PortugueseTagger` declared throwing `IOException` but didn't.

**Comment by jaumeortola** [comment]
@marcoagpinto Done. Now, words that contain hyphens will be tokenized correctly (sex-appeal, Al-Qaeda, Montemor-o-Novo, etc.). But the words have to be in the tagger dictionary or in added.txt (properly tagged). It is not enough that they are in spelling.txt.

**Comment by marcoagpinto** [comment]
Thank you, Jaume!

**Comment by marcoagpinto** [comment]
What is the "tagger dictionary"?

**Comment by jaumeortola** [comment]
> What is the "tagger dictionary"?

It is the dictionary with contains the part-of-speech tags (portuguese.dict). You cannot edit it (but it can be updated from time to time). You can add tagged words to the file added.txt or remove words in removed.txt.
