### ISSUE TITLE
[ru] нет проверки на правильное использование дефиса и тире

### ISSUE THREAD

**Issue by socketpair** [languagetool-org/languagetool#321]
https://github.com/languagetool-org/languagetool-website/pull/11 Например.

А конкретнее — https://www.artlebedev.ru/kovodstvo/sections/97/ и https://www.artlebedev.ru/kovodstvo/sections/158/
http://new.gramota.ru/spravka/rules/158-tire

Ещё нужно обратить внимание на расстановку пробелов вокруг дефиса и тире. По-моему, вокруг дефиса никогда не бывает пробелов. А вокруг тире — всегда.

**Comment by yakovru** [comment]
Такая проверка не осуществляется, так как существуют тексты, набранные в восьмибитных кодировках (KOI8-R, CP866). А в них нет такого символа как тире! Нет технической возможности его набрать!

**Comment by socketpair** [comment]
Ребят. С разморозкой. Давно таких текстов нет. А если есть — не плохо бы указать на неверную пунктуацию. А дальше автор текста пусть сам решает что ему с этим делать. Русский язык не должен страдать из-за технических особенностей.

**Comment by socketpair** [comment]
Ну а вообще — ответ странный. По идее, вы должны работать с юникодными строками, а не с байтами в какой-то там кодировке. Поэтому какая там была кодировка на входе в движок вас волновать не должно. Исходники не смотрел — джаву ненавижу.

**Comment by yakovru** [comment]
Словарь используется в кодировке KOI8-R.  Так работает быстрее и занимает минимум места.
Внутри идёт обработка в кодировке KOI8-R. Но для правил используется Unicode, и задачу я реализую в текущей версии.

**Comment by socketpair** [comment]
Это хорошо, про текущую версию. А нет в планах и однобайтовые кодировки выпилить? Бенчмарки есть по скорости и по памяти? Что-то мне подсказывает, что память может и будет затрачена и в 4 раза больше в худшем случае, но абсолютное значение не такое уж большое должно быть. Ну а по скорости — думаю там нанопроценты.

**Comment by yakovru** [comment]
Словарь в кодировке Unicode в 1,8 раза больше, чем в KOI8-R. И быстродействие с кодировкой UTF-8 в 2 раза меньше.

**Comment by socketpair** [comment]
Есть серьезное мнение, что в программе путаница между UTF-8 и UNICODE. В первом случае - это способ кодирования UNICODE в набор байтов для сохранения в файле например. Второе - это способ представления букв в памяти (обычно -- 4 байта на букву).


Так вот. По идее, все операции должны проводиться на UNICODE. Другими словами, сначала текст должен из какой-то кодировки (KOI8-R или UTF-8, например) преобразоваться в UNICODE, а затем над текстом должен проводиться анализ. После чего если нужно куда-то обработанный текст деть, то кодируем это в нужную кодировку на выходе (опять таки KOI8-R или UTF-8) и выдаём.

В частности, побуквенная работа с куском памяти (не буду называть это строкой) в кодировке UTF-8 невозможна. Ну, php это делает (mbstring который). но это ж php.

**Comment by socketpair** [comment]
Итого - словарь должен на диске храниться в UTF-8, в памяти в UNICODE.

Тоесть, на диске он займет примерно в 2 раза больше чем KOI8-R, а в памяти примерно в 4 (ну или как там джава у себя это делает, у питона -- оптимизация, у джавы - хз)

**Comment by yakovru** [comment]
Правило "Дефис вместо тире" добавлено, но в начальных настройках выключено, так как при обработке тестовой выборки с данными из Wikipedia  правило находит 103 ошибки.
