### ISSUE TITLE
correction loop: soweit / so weit

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3213]
> War soweit ich das beurteilen kann einer der engagierteren.

Suggests "so weit", then "soweit" again (`SO_WEIT`)

**Comment by NicoWeio** [comment]
Still reproducible. Here's another example:
> Abgesehen von Word, wofür Sie **so weit** ich weiß keine Lizenz haben, sollten die Programme laufen. 
> Abgesehen von Word, wofür Sie **soweit** ich weiß keine Lizenz haben, sollten die Programme laufen.

**Comment by udomai** [comment]
@NicoWeio, danke für den Beispielsatz – wird ab morgen nicht mehr passieren :)

**Comment by NicoWeio** [comment]
Danke! Ich habe auf https://languagetool.org/de/ verifiziert, dass der Fehler nicht mehr auftritt. Dieses Issue kann nun geschlossen werden, denke ich.
