### ISSUE TITLE
[en] incorrect tagging DT_JJ_NN_JJ

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3215]
> Please lay down your coat.

"lay" is only tagged as VBD

**Comment by tiff** [comment]
Same for:
> Please **cut** short your vacation and return.
> Can you please **cut** down on the swearing?
> Also please **lay** out a schematic of the hardware configuration between Enron, Louisiana and AEP's offices for this solution.

**Comment by MikeUnwalla** [comment]
@tiff, are you sure? In today's snapshot (2020-07-06), the verbs have other POS, not only VBD. (They should be VB, but that's a different problem.)

**Comment by tiff** [comment]
@MikeUnwalla sorry for not being clear: the problem I tried to describe is that the verbs don't have the "VB(P)" tagging.

**Comment by tiff** [comment]
This is what I see. "lay" should also have VB 
<img width="848" alt="Bildschirmfoto 2020-07-07 um 10 00 54" src="https://user-images.githubusercontent.com/37363/86742932-c68c3380-c038-11ea-8499-daea14e5f853.png">
