### ISSUE TITLE
[en] false alarms MISSING_PAST_TENSE 

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3217]
> I couldn't go to Australia last year.

<img width="533" alt="Bildschirmfoto 2020-07-07 um 10 03 48" src="https://user-images.githubusercontent.com/37363/86743457-2da9e800-c039-11ea-8a58-a6eb9ded04b4.png">

> I’m quitting Starbucks and this is my last week.

> Dave, I am sending you my accomplishments for the last year.

> Kevin, I want to apologize for not attending the meeting last week.

> What a great performance by the rookie WR last week.

> That is down from 8.54% last week.

> Everybody, Here are my notes from our meeting last week.

**Comment by MikeUnwalla** [comment]
Regression 2020-0607:

> I was a first year student last year.
