### ISSUE TITLE
Много информации про использование чисел и знаков

### ISSUE THREAD

**Issue by socketpair** [languagetool-org/languagetool#322]
https://www.artlebedev.ru/everything/izdal/spravochnik-izdatelya-i-avtora/Milchin-Numbers.pdf

**Comment by socketpair** [comment]
А еще можно купить за 600 р. Вот это https://www.artlebedev.ru/everything/izdal/spravochnik-izdatelya-i-avtora-2014/ там вообще тонны правил.

**Comment by stereobooster** [comment]
Правила описанные Лебедевым больше относятся к типографике. Небольшой набор правил по типографике и сравнение типографов смотри [здесь](http://www.typograf.ru/flog/). Английский аналог SmartyPants - довольно примитивный по сравнению с русскими аналогами.

Как насчет стилистики? Например, [главред](https://glvrd.ru/).

**Comment by yakovru** [comment]
Для  OpenOffice (и LibreOffice) созданы как минимум 2 расширения, приводящие текст к типографским стандартам:
1.  MiniCorrector — http://extensions.openoffice.org/en/project/minicorrector
2. OOoТипографика — http://extensions.openoffice.org/en/project/oootypographica-tool-bring-text-according-grammar-rules-russian-and-ukrainian-languages

А сравнение типографов интересное.
