### ISSUE TITLE
[en] incorrect tagging VBN_VBD

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3220]
> If you have questions please let me know.

"let" is only tagged as VBN

**Comment by MikeUnwalla** [comment]
Seems to be related to #3223.

**Comment by MikeUnwalla** [comment]
Also:

> If there are problems immediately **put** me in touch with the manager.

> If there are problems please **put** the manager in the loop.

> If you were having ideas quickly **set** all of them aside.

**Comment by tiff** [comment]
Thanks!
