### ISSUE TITLE
[fr] Wrong suggestion : genre change is rightfully suggested but singular/plural is not suggested on the same word

### ISSUE THREAD

**Issue by bperel** [languagetool-org/languagetool#3221]
On the following sentence : 

> Ils sont même devenus Champions par équipe de la WWF en 1976 en tant que l'équipe masqués des Executioners.

LanguageTool suggests to replace "masqués" with "masquées" which is half correct : "équipe" is feminine but also singular, so the suggestion should be "masquée".
If I apply the "masquées" suggestion and run the text check again, LanguageTool doesn't detect that there is something wrong, where it should suggest "masquée".

**Comment by jaumeortola** [comment]
Done by the rule AGREEMENT_POSTPONED_ADJ[
