### ISSUE TITLE
[fr] False positives on "divers droite"

### ISSUE THREAD

**Issue by bperel** [languagetool-org/languagetool#3222]
> Elle est élue en 1989 sur une liste divers droite.

2 suggestions are raised : 
- "Divers" doesn't have the proper genre : LanguageTool thinks that it should be accorded with "liste" which is feminine.
- "Droite" doesn't have the proper genre : LanguageTool thinks that it should be accorded with "divers" which is masculine.

"Divers droite" in this context means "Various right-wing" or something like that and is an expression so it should just stay as is.

**Comment by jaumeortola** [comment]
I will add "divers droite" to multiword.txt as invariant adjective. But is there any case when "divers droite" can be an error?

**Comment by bperel** [comment]
It can if it's taken literary : "droite" can also mean "right"' as in "not left" or as in "punch with the right fist". I can't find very good examples though : I can think of : 
> Il reçut diverses droites en pleine face
(He received various right fist punches in the face), where the plural and feminine should be respected.

**Comment by jaumeortola** [comment]
Thank you. Then it is improbable that we will miss other errors, and we can consider that it is safe enough.
