### ISSUE TITLE
[en] False warnings caused by the change of POS for 'please'

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3223]
The correction of the POS for 'please' (https://github.com/languagetool-org/languagetool/commit/f05df00a9bd032438c590d3933684f294c7c18db) causes many false warnings.

@tiff and I decided on this plan of action:

- Keep RB for "please".
- But: Temporarily remove it until we have fixed all regressions.

**Comment by MikeUnwalla** [comment]
Open-source rules that have FP or FN (https://internal1.languagetool.org/regression-tests/via-http/2020-07-08/en/index.html):

- [ ] ADVERB_VERB_ADVERB_REPETITION
- [ ] AFFORD_VB
- [ ] ALLOW_TO_DO
- [ ] A_RB_NN
- [ ] BEEN_PART_AGREEMENT[1]
- [ ] HAVE_PART_AGREEMENT[2] 
- [ ] HE_VERB_AGR[1]
- [ ] HE_VERB_AGR[3]
- [ ] IT_VBZ
- [ ] MASS_AGREEMENT[5]
- [ ] MD_BE_NON_VBP[1]
- [ ] MISSING_COMMA_WITH_NNP[3]
- [ ] MISSING_TO_BEFORE_A_VERB[3]
- [ ] SOME_NN_VBP[1]

Premium rules that have FP or FN (https://regression.languagetoolplus.com/via-http/2020-07-08/en/):

- [ ] BE_WITH_WRONG_VERB_FORM[1]
- [ ] NNP_VBP_TO_VBZ[1]
- [ ] IF_DT_NN_VBZ[1] 
- [ ] PRP_HAVE_VBD_DT[1]
- [ ] SINGULAR_NOUN_AGREEMENT_DONT[1] 
- [ ] THIS_RB_VB_IN[1]
- [ ] VB_A_JJ_NNS[1]
- [ ] WRB_QUESTION_MARK[1]
- [ ] FOR_NOW_COMMA[2]

**Comment by MikeUnwalla** [comment]
@tiff , if we remove the POS for RB temporarily, I think we should also revert the JJ. (If we don't, it is possible for a rule to give incorrect warnings or to have false negatives because of the 'missing' JJ.) Please confirm.

**Comment by tiff** [comment]
I saw some false alarms with "please" that were gone after JJ was removed:
e.g. https://internal1.languagetool.org/regression-tests/via-http/2020-07-08/en/result_grammar_A_INSTALL[3].html

I would vote for removing JJ already. I don't see any issues with it.

**Comment by MikeUnwalla** [comment]
@tiff , I removed JJ (https://github.com/languagetool-org/languagetool/commit/497880b0d9086a71e12aef9ee451a1410e536bf8)

**Comment by tiff** [comment]
I added a fix for the false positive in IT_VBZ: https://github.com/languagetool-org/languagetool/commit/d69f55ee3a757dd2772596b79113013736d2a6fa#diff-2e4126723233b9f262d8cd599fdaee03R27119
