### ISSUE TITLE
[de] strange false alarm DE_CASE 

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3224]
> Die Versicherung und Sach­mangelhaftung.

![Bildschirmfoto 2020-07-08 um 18 18 54](https://user-images.githubusercontent.com/37363/86944108-8ff10e80-c147-11ea-8868-67fcf71d85b5.png)

@danielnaber not sure if this is related to POS Update.

**Comment by danielnaber** [comment]
It's somehow caused by the soft hyphen in the word, not related to the dict update...

**Comment by danielnaber** [comment]
I've added a quick workaround. The proper solution would be to normalize input text as the first step, before LT does anything else (#204).
