### ISSUE TITLE
[de] wrong suggestion "Mitgleiderinnen"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3231]
> Liebe Mitgleiderinnen

![Bildschirmfoto 2020-07-09 um 10 55 59](https://user-images.githubusercontent.com/37363/87019394-d770ac80-c1d2-11ea-97a2-1268a4ea2632.png)

Der Vorschlag mit Bindestrich macht nicht wirklich Sinn.

**Comment by tiff** [comment]
Sehe gerade, dass "Mitgliederin" und "Mitgliederinnen" nicht im Duden und auch nicht in unserem Wörterbuch ist.

@janschreiber @danielnaber @Dallun511 was denkt ihr?

**Comment by danielnaber** [comment]
Hier steht auch explizit, dass es das nicht gibt: https://www.duden.de/sprachwissen/sprachratgeber/%E2%80%9ELiebe-Mit%C2%ADglieder%C2%ADinnen-und-Mit%C2%ADglieder%E2%80%9C-%E2%80%93-Personen%C2%AD%C2%ADbezeich%C2%ADnungen

**Comment by Dallun511** [comment]
https://www.duden.de/sprachwissen/sprachratgeber/%E2%80%9ELiebe-Mit%C2%ADglieder%C2%ADinnen-und-Mit%C2%ADglieder%E2%80%9C-%E2%80%93-Personen%C2%AD%C2%ADbezeich%C2%ADnungen
Der Duden nutzt das Wort, hat nur kein Eintrag

**Comment by janschreiber** [comment]
"Mitgliederinnen" ist ganz sicher kein Wort. Absurder geht es kaum. Das Wort "Mitglieder" ist kein _nomen agentis_, sondern der Plural von "Mitglied". Wer denkt sich bloß so einen Unfug aus?

**Comment by Dallun511** [comment]
Ich kriege deinen Daumen runter. Vermutlich habe ich mich nicht klar ausgedrückt.
Ich meinte mit Beispiele für Nomen, die nicht mit -in verseht werden. Z. B. Waisin.

Zu Mitgliederinnen kann ich nur sagen, ich wurde es bringen, wenn ich mir unsicher bin.
Es ist sehr beliebt geworden -innen an Wörter anzuhängen, weil viele Angst haben, jemanden zu beleidigen.
Mit "Mitgliederinnen" wäre man auf der sicheren Seite, auf wenn das Wort nicht existiert.

Ein Beispiel: http://www.journalismus-handbuch.de/anne-will-in-der-gender-falle-mitgliederinnen-und-mitglieder-9442.html
Bei Unsicherheit und Wissenheit können Wörter wie "Mitgliederinnen" entstehen.

Grüße Dallun511

**Comment by tiff** [comment]
Scheint ein häufiger Fehler zu sein. Ich habe hierfür mal eine Regel angelegt, die den Fall abdeckt und das Problem dem Nutzer erklärt. https://github.com/languagetool-org/languagetool/commit/22af35bf97ba647573abb023165704597d00dfc3#diff-c0828a59af0d92c57ba5dd01cf6c4068R33623-R33657
