### ISSUE TITLE
[pt] user feedback about agreement error

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3234]
User feedback:

> O corretor não identificou o erro de concordância básico: "Você pode VIM¨.

**Comment by marcoagpinto** [comment]
Yes, I will fix it tomorrow or Saturday.

I have been fixing the most important rules.

Gender agreement rule are also very important, but I will focus on them after the number agreement.

**Comment by marcoagpinto** [comment]
So, I spent 30 minutes creating the rule just to find out that the current rules would detect the issue:
![pode_vim](https://user-images.githubusercontent.com/5192600/87132875-68f12480-c28e-11ea-9de2-afb3af4815a5.png)

I don't know where the user got his results from.

**Comment by marcoagpinto** [comment]
Ahhhhh... @danielnaber 

It is possible that the antipatterns I have been implementing to fix false positives may have fixed that particular rule.
