### ISSUE TITLE
Alllower and firstupper issue

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#3241]
Writing a word like 'UGLINESS' in capitals, longer than 5 characters, is considered 'ugly' in Dutch text books.
At the start of a sentence, a word like that should have the suggestion 'Ugliness', in the middle of the sentence 'ugliness'. Unless it is a proper name, when it should be 'Ugliness'. (Sounds like a Scottish place. But no, I love Scotland...)

So there are 2 subrules, one for start of sentence, and one for words before the UGLINESS.
But alllower makes the word completely lowercase, so not fit for start of sentence. Startupper however does only turn the first char in uppercase; it does not lowercase the rest. I would need firstupper of alllower
Maybe this can be achieved using regexp_match and regexp_replace?

The same trick is needed for proper names in the middle of a sentence..

**Comment by yakovru** [comment]
New value "firstupper" for "case_conversion" attribute in grammar.xml added.

**Comment by baarsrj** [comment]
Thanks, Yakov, I am implementing it right away.
