### ISSUE TITLE
[fr] wrong and missing suggestions

### ISSUE THREAD

**Issue by thelittlefireman** [languagetool-org/languagetool#3246]
```
Il y a peu être du pain. Certains services et certaines applications est mal construites.
Certains services est mal construits.
Chaque services et chaque applications sont unique.
```
In this text : "peu" should be "peut-" but it's not suggested. Both "est" should be "sont" but it's not suggested too.
And in the last sentence "chaque" is suggested to be replaced by "chaqueS" and that’s not correct because "chaque" should be never written in plurals.

![](https://i.ibb.co/0Kc2WGs/ltf.jpg)

**Comment by thelittlefireman** [comment]
Perfect thanks you :) 

I retry with `Chaque services et chaque applications sont unique.` 

There is suggestion to change the sentence to this one : `Chaque service et chaque application sont unique.`

But now there is no suggestion to change the `sont` to `est`.

**Comment by jaumeortola** [comment]
> Chaque services et chaque applications sont unique.

Done in rule CHAQUE_ET_CHAQUE
