### ISSUE TITLE
Save as doesn't safe as .txt file

### ISSUE THREAD

**Issue by Maxaxa** [languagetool-org/languagetool#325]
I found a possible bug in the standalone Tool.
The file I get when i use "safe as" has not the file-ending .txt (as the window  under file type suggests). I tested it on Windows10 and Ubuntu. Still it is a plain-text-file and can be opened like one. I don't know how it was intended to look like.

**Comment by danielnaber** [comment]
The `*.txt` is just a filter for the files displayed. It's a matter of taste whether `.txt` gets appended, I don't think it should.
