### ISSUE TITLE
[en] wrong tagging DT_NN_SENT_END

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3257]
> I still have many left.

"left" is only NN:UN

**Comment by tiff** [comment]
Also:
> There were not many present.

**Comment by MikeUnwalla** [comment]
Also:
> Our windows were dirty, but this product is excellent; it has made many cleaner.

**Comment by tiff** [comment]
@MikeUnwalla also I think the tagging for "unemployed" is wrong. It has "unemployeds" as NNS. I doubt that this is correct.

**Comment by MikeUnwalla** [comment]
@tiff, I will check unemployeds/NNS.

**Comment by MikeUnwalla** [comment]
unemployed/NN is also wrong, because the phrase is 'the unemployed'. We never say, "He is an unemployed." For now, I won't make changes.
https://www.collinsdictionary.com/dictionary/english/unemployed
https://www.ldoceonline.com/dictionary/unemployed

**Comment by tiff** [comment]
Is it a plural noun? If so, "wounded" is the same case (it is "NN"). How do we tag plural nouns?
https://www.merriam-webster.com/dictionary/wounded

**Comment by MikeUnwalla** [comment]
@tiff , yes, you are right, 'the unemployed' is a plural noun. As best I know, we don't have disambigation for the phrase or similar phrases.

But, there is an entity `plural_adjectival_nouns`. There is an example of the entity in an AP in disambiguation DT_JJ_VB_NN.
