### ISSUE TITLE
[en] false alarm APOSTROPHE_PLURAL

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3259]
> Tom's double-parked.

Not sure what the sentence is trying to express... the error happens now because I tagged "double-park" as a verb (https://www.lexico.com/definition/double-park)

<img width="412" alt="Bildschirmfoto 2020-07-15 um 08 02 41" src="https://user-images.githubusercontent.com/37363/87509323-957fb480-c671-11ea-8aad-dace31f3049c.png">

**Comment by MikeUnwalla** [comment]
The sentence means that Tom has parked his car next to another car in a location that is not permitted.

The FP seems to occur with past participles that do not have other parts of speech. Examples:

> Tom's succeeded.

> Tom's died.

> Tom's remarried.

**Comment by tiff** [comment]
Closed as part of https://github.com/languagetool-org/languagetool/commit/2c91733d3f70d908dae4b1235a2f7b3c99479db1
