### ISSUE TITLE
[en] Wrong tagging WILL_MD

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3262]
'Will' is incorrectly tagged as MD, but it is NNP:

> **Will** did not leave any information on the babies, just that they are very small.

> **Will** stood still an instant looking at her, then seated himself beside her, 

> **Will** became frightened.

> 2020-07-06 MFU adds: **Will** became the most important thing for her; she loved him deeply.

Also, tagged as MD but is a noun:

> But, her **will** was invalidated by Parliament in 1274.

> The Bible is clear that humans do not achieve greatness without having their sinful **will** broken.

> 2020-07-06 MFU adds: Unfortunately, this **will** happened to be wrong, because the legal team was careless. 

> 2020-07-06 MFU adds: **Will** became the most important thing for him; he wanted to rule the world!

**Comment by MikeUnwalla** [comment]
I think that WILL_MD does more harm than good. (I wrote the comment in the rule about 'will designated'; it's time to deal with the problem fully!)

The wrong tagging for 'Will' causes 3 false warnings (on the verb) in open-source DID_BASEFORM [1] (and it also causes false warnings in Premium MD_VBD).

Removal of WILL_MD has these effects:
* The 3 false warnings in DID_BASEFORM[1] go away.
* One new false warning occurs in DID_BASEFORM[1] for "Will became **frightened**."
* DID_BASEFORM[1] does not find "A proposed northern bypass of Birmingham will **designated** as I-422." (But, Premium MD_VBD finds the sentence.)

I think that we can delete WILL_MD because CAN_WILL_MD applies the correct POS if the grammar is correct.

But, an alternative to removing the rule is to change the token for the verb such that rule applies a postag only if the grammar is correct. Change:
`<token postag="VB.*" postag_regexp="yes"/>`
to
`<token postag="VB[P]*" postag_regexp="yes"/>`

@tiff , @danielnaber , what do you think is the best option?

**Comment by tiff** [comment]
Feel free to remove

**Comment by MikeUnwalla** [comment]
I tested the proposed deletion on100,000 sentences. There were no changes to the results, so I deleted the rule.

I will leave this issue open until I have checked the regression errors tomorrow.

**Comment by MikeUnwalla** [comment]
My change causes many false negatives (https://internal1.languagetool.org/regression-tests/via-http/2020-07-16/en/result_grammar_DID_BASEFORM[1].html).

We have 2 options:
- Revert my change.
- Change DID_BASEFORM such that it does not ignore the incorrect text.

If we revert the change, we accept that sometimes for convenience, we parse incorrect text. We could have a policy that says "parse until an error occurs." We could say that up to the modal 'will', the sentence "A proposed northern bypass of Birmingham will designated as I-422." is correct. Thus, we parse as will/MD. (But, if we do that, we must fix all the other errors caused by wrong tagging in WILL_MD.

My preferred option is to fix the grammar rule DID_BASEFORM such that it continues to find the errors. Not finding 'will designated' is related to this exception:
`<exception scope="previous" negate_pos="yes" postag_regexp="yes" regexp="yes" postag="MD|RB|VBD"/>`
I don't understand the exception (I still have not got my head around 'exception + negate pos').

@tiff , @danielnaber what do you think is the best long-term strategy?

**Comment by danielnaber** [comment]
negate_pos + exception is documented at http://wiki.languagetool.org/tips-and-tricks#toc25

**Comment by MikeUnwalla** [comment]
@danielnaber , yes, it is documented AND I the last time that I looked, I did not understand.

**Comment by danielnaber** [comment]
> My preferred option is to fix the grammar rule DID_BASEFORM such that it continues to find the errors

Yes, feel free to do so.

**Comment by tiff** [comment]
@danielnaber feel free to go with your preferred solution. If it takes a little longer I would suggest reverting the commit temporarily.
Also, please add some of the false negatives as examples to the rule, so we get feedback earlier, the next time we make a similar change.

**Comment by tiff** [comment]
sorry, I mean @MikeUnwalla not @danielnaber

**Comment by MikeUnwalla** [comment]
@tiff , @danielnaber , thanks. 

I will revert the change and add the false negative examples (one for each grammar structure).

**Comment by MikeUnwalla** [comment]
When I added examples for https://github.com/languagetool-org/languagetool/commit/972d35f2f1bb671a9ac58a401ba2beab63aee1f9, I meant to add them to grammar/DID_BASEFORM, so that changes to disambiguation/WILL_MD don't prevent the rule from finding the errors.

But, I added the examples to grammar/MD_BASEFORM[2]. Doh!

So, I can safely remove WILL_MD because the errors are found by MD_BASEFORM.

**Comment by MikeUnwalla** [comment]
I will leave this issue open until after I check the regression.
