### ISSUE TITLE
[it] New word

### ISSUE THREAD

**Issue by mzzntn** [languagetool-org/languagetool#3266]
It seems that the Italian dictionary doesn't recognize attrattività as a word.
![Screenshot from 2020-07-15 15 14 19](https://user-images.githubusercontent.com/37122612/87549516-342a0680-c6ae-11ea-94ae-7eb76c83b602.png)

**Comment by danielnaber** [comment]
Thanks for the report! @jaumeortola has already added it, it should be live on languagetool.org tonight.
