### ISSUE TITLE
[en] false alarm MANY_NN

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3271]
> And a few affect both.

![Bildschirmfoto 2020-07-15 um 17 36 42](https://user-images.githubusercontent.com/37363/87565331-cb4c8980-c6c1-11ea-93b2-c687baf3fe2d.png)

**Comment by MikeUnwalla** [comment]
Also:

> There are very few tariff or non-tariff barriers to trade with...

> There are a few tariff and non-tariff barriers to deal with.

I will copy the AP from #3275
