### ISSUE TITLE
[en] wrong tagging NNJJ_NN_JJ / JJ_VBZ_NNS

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3272]
> Loop until a number variable reaches 4.

"variable" is only tagged JJ, "reaches" is only tagged NNS

**Comment by tiff** [comment]
> I once had someone break into a **convertible** years ago.

"convertible" is only tagged JJ

**Comment by MikeUnwalla** [comment]
Also: I thought about buying her **convertible** days before this coronavirus crisis started.

**Comment by MikeUnwalla** [comment]
The FP in grammar A_NUMBER_NNS is not caused only by the tagging. I will fix the FP.
