### ISSUE TITLE
[en] false alarms THERE_RE_MANY

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3275]
> There are many kind of computer vision systems, nevertheles...

> There are very few tariff or non-tariff barriers to trade with Bo...

via: https://internal1.languagetool.org/regression-tests/via-http/2020-07-16/en/result_grammar_THERE_RE_MANY[3].html

**Comment by MikeUnwalla** [comment]
Not caused by a recent change. I see the same results in LT 5.0.

**Comment by MikeUnwalla** [comment]
'many kind of computer vision systems' is not correct. LT's suggestion 'many kinds' is correct. Refer to https://www.lexico.com/definition/kind.
