### ISSUE TITLE
Latest Build

### ISSUE THREAD

**Issue by IWriteThings** [languagetool-org/languagetool#328]
Would it be possible for you all to host a copy of languagetool with a file name like 'Latest.zip' or something static? I am using Vagrant and I am integrating languagetool into it. It would help me tremendously if I simply had to download 'languagetool.com/latest.zip' each time instead of pulling source and compiling or having to edit the file name / url every time you all do an update.

This would be very similar to how WordPress hosts a latest.tar.gz file for their releases. You can always wget https://wordpress.org/latest.zip that URL to get the newest version of WordPress. I humbly ask that you provide something similar for languagetool.

**Comment by danielnaber** [comment]
We already do this: https://languagetool.org/download/LanguageTool-stable.zip and https://languagetool.org/download/LanguageTool-stable.oxt

**Comment by IWriteThings** [comment]
Thanks a bunch!
