### ISSUE TITLE
[de] wrong tagging "Dachdeckerarbeiten"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3284]
> Die Dachdeckerarbeiten

"Dachdeckerarbeiten" ist anders getaggt als "Maurerarbeiten"... 
@danielnaber hast du eine Idee?

<img width="717" alt="Bildschirmfoto 2020-07-17 um 15 05 22" src="https://user-images.githubusercontent.com/37363/87789232-ff00ee00-c83e-11ea-9847-9955540c7bcd.png">

**Comment by danielnaber** [comment]
Falsche Zerlegung, kümmere ich drum:

[Dach, deck, erarbeiten]
[Maurer, arbeiten]
