### ISSUE TITLE
[pt-BR] "porque", "por que", "por quê"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3300]
User feedback:

> Brazilian Portuguese: the "porque", "por que", "por quê", are not being corrected.

**Comment by marcoagpinto** [comment]
@danielnaber 

If I well remember, someone reported it months ago and @jaumeortola said that there are different ways of using them for Portuguese language variances and that was better not to try to fix it.

Also, I always had the same question on how to use them.

**Comment by danielnaber** [comment]
Indeed, this is a duplicate of https://github.com/languagetool-org/languagetool/issues/2962
