### ISSUE TITLE
Possible false positive on COMMA_PARENTHESIS_WHITESPACE with mix of HTML tags

### ISSUE THREAD

**Issue by bperel** [languagetool-org/languagetool#3301]
There seems to be an error when parsing the following text : 
`A, B, C,<tag> </tag><tag>etc.</tag>`

As far as I know, the fact hat there are HTML tags around some parts of the text shouldn't influence its interpretation, and it should be parsed as : 
`A, B, C, etc.`

However, this is not the case : only the first text here reports : 
```json
{
    "matches": [
        {
            "message": "Put a space after the comma",
            "shortMessage": "",
            "replacements": [
                {
                    "value": ", <"
                }
            ],
            "offset": 7,
            "length": 2,
            "context": {
                "text": "A, B, C,<tag> </tag><tag>etc.</tag>",
                "offset": 7,
                "length": 2
            },
            "sentence": "A, B, C,<tag> </tag><tag>etc.</tag>",
            "type": {
                "typeName": "Other"
            },
            "rule": {
                "id": "COMMA_PARENTHESIS_WHITESPACE",
                "description": "Use of whitespace before comma and before/after parentheses",
                "issueType": "whitespace",
                "category": {
                    "id": "TYPOGRAPHY",
                    "name": "Typography"
                }
            },
            "ignoreForIncompleteSentence": false,
            "contextForSureMatch": 0
        }
    ]
}
```

Is there an issue with the way LanguageTool parses this text?

**Comment by danielnaber** [comment]
LT doesn't expect HTML code in the input, you'd have to use the `data` parameter to define what is text and what is markup: https://languagetool.org/http-api/swagger-ui/#!/default/post_check

**Comment by bperel** [comment]
What does it mean in practice that LT doesn't "expect" HTML code? It still seems to process the content inside the tags somehow

**Comment by danielnaber** [comment]
> What does it mean in practice that LT doesn't "expect" HTML code?

It doesn't support HTML, it only expects plain text. Your HTML tags would be checked as if they were text if you're not using `data`.

**Comment by bperel** [comment]
That's what I had understood. But then how come this text : 
```
A, B, C,<tag> </tag><tag>etc.</tag>
```
is shown as having issues? If it is interpreted like you say, just removing the HTML tag wraps and keeping the tag's contents (including the one that only has a space in it), then it should be the equivalent of : 
```
A, B, C, etc.
```
and hence LT should not throw any issue.

**Comment by danielnaber** [comment]
> then just removing the HTML tag wraps and keeping the tag's contents

But that's not what LT does by default, it doesn't ignore text in `<...>`. You need to use the `data` parameter if you send anything that's not plain text. If your input is `C,<tag`, then LT will complain about the missing space after the comma because it doesn't know `<` is the start of a tag.

**Comment by bperel** [comment]
So you mean that LT basically just replaces "<" with ""?

**Comment by danielnaber** [comment]
No, LT doesn't parse or interpret HTML in any way. It treats `<` as `<`.

**Comment by bperel** [comment]
Alright. Thank you for the explanations, closing the ticket.
