### ISSUE TITLE
[fr] ACCORD_NOM_VERBE disable ==> lots of errors

### ISSUE THREAD

**Issue by thelittlefireman** [languagetool-org/languagetool#3306]
hi,

Lots of errors are not warn.

Example :

`Mes pantoufles se déplace`, `Cette solution permets de manger`, `Cette voiture es propre`.

Should be : `Mes pantoufles se déplacent`, `Cette solution permet de manger`, `Cette voiture est propre`

**Comment by thelittlefireman** [comment]
Up ?
Can we re-enable this rule ? Or could you please tell me some Examples of false positive, i Will try to fix them ?

**Comment by jaumeortola** [comment]
I will provide a list of rule matches.

**Comment by thelittlefireman** [comment]
Thanks :) I'll wait for your list

**Comment by jaumeortola** [comment]
This is a file with 97 matches of the rule ACCORD_NOM_VERBE. [ACCORD_NOM_VERB_matches.txt](https://github.com/languagetool-org/languagetool/files/5018343/ACCORD_NOM_VERB_matches.txt)
The first thing to do is to classify the matches in true and false positives. 

In my experience (in Spanish and Catalan), the rules for agreement between subject and verb are very hard to implement. What I have done in these languages is to detect the disagreement only in limited contexts (only short and simple subjects at the start of the sentence) and with many exceptions. See the rules AGREEMENT_SUBJECT_VERB_SG_PL and AGREEMENT_SUBJECT_VERB_PL_SG in Spanish.

**Comment by jaumeortola** [comment]
Fixed with the new rule ACCORD_SUJET_VERBE.
