### ISSUE TITLE
[pt] "Viagem"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3308]
User feedback:

> In portuguese, the word "viagem" is being corrected wrongly: LT is correcting as 'viajem', but that's wrong. The correct way is "viagem".

![Bildschirmfoto von 2020-07-21 08-40-34](https://user-images.githubusercontent.com/857004/88021542-edb12d80-cb2d-11ea-82e9-af6b8ca90a0c.png)

**Comment by jaumeortola** [comment]
The rule depends on the context. "Viagem" is a noun, "viajem" is a verb. It would be useful to know the context where the problem was found. Any way we can try to improve the rule.

**Comment by danielnaber** [comment]
I think it was in a headline - there was no context, just that word.
