### ISSUE TITLE
False alarm on "Cao Cao"

### ISSUE THREAD

**Issue by bperel** [languagetool-org/languagetool#3312]
Cao Cao was a [Chinese poet](https://en.wikipedia.org/wiki/Cao_Cao). 

Writing this text in LanguageTool triggers a ENGLISH_WORD_REPEAT_RULE error, and the equivalent of this error in the other languages.

**Comment by bperel** [comment]
It's not just English that's related to this false alarm

**Comment by jaumeortola** [comment]
It is sometimes transcribed Cáo Cāo. 
We could add an exception to the global rule WORD_REPEAT_RULE, or fix it language by language.
