### ISSUE TITLE
[ru] false alarm on words with "-то"

### ISSUE THREAD

**Issue by Katzen-Gott** [languagetool-org/languagetool#3319]
Any (or at least almost any) Russian word can have "-то" added to it. However, almost always it'll be marked red. Please fix.

**Comment by yakovru** [comment]
Fixed for most part of speech. Please, test it.

**Comment by Katzen-Gott** [comment]
Works for nouns, but not for names. I'll also need to test with words from personal dictionary. Thanks for quick fix anyway.

**Comment by Katzen-Gott** [comment]
Awesome! Thank you very much!
