### ISSUE TITLE
Fehlalarme Deutsch

### ISSUE THREAD

**Issue by textleister** [languagetool-org/languagetool#332]
~~Die Noten von **s**chwarzer Johannisbeere duften gut. → Fehlermeldung: „Zu mehrteiligen Namen gehörende Adjektive werden großgeschrieben.“~~

~~Ändert man die Schreibweise in groß:
Die Noten von **S**chwarzer Johannisbeere duften gut. → Fehlermeldung: „Außer am Satzanfang werden nur Nomen und Eigennamen großgeschrieben“~~

**Comment by danielclipnow** [comment]
Ist behoben - ich lasse das Issue aber auf für weitere Fälle.

**Comment by danielnaber** [comment]
Ist behoben - ich lasse das Issue aber auf für weitere Fälle.

**Comment by textleister** [comment]
Bei mir kommen viele Duftbeispiele, nicht wundern :)
Der Honig schließt die Kopfnote mit seiner herben Süße aromatisch ab. → angebliche falsche Kongruenz.
Der Honig schließt die Kopfnote mit seiner herben Süßen aromatisch ab. → kein Fehler angezeigt, in diesem Zusammenhang aber falsch.

Die Süße, im Sinne von Süßsein → mit seiner Süße
Die Süße, im Sinne von Freundin, Geliebten → mit seiner Süßen

http://www.duden.de/rechtschreibung/Suesze

**Comment by textleister** [comment]
Frisch gemahlener **S**chwarzer Pfeffer. → Gleiche Geschichte wie bei Schwarzer Johannisbeere.
Schwarzer, Weißer, Roter, Grüner, Rosa … Pfeffer

**Comment by danielnaber** [comment]
Laut Duden ist "schwarzer Pfeffer" richtig: http://www.duden.de/rechtschreibung/Pfeffer. Den Fehlalarm mit "Süße" habe ich korrigiert (und streiche es gleich durch), den nicht erkannten Fehler in "Der Honig schließt die Kopfnote mit seiner herben Süßen aromatisch ab." kann man nicht so ohne weiteres erkenne, da es ja eine Frage der Semantik ist.

**Comment by textleister** [comment]
Beim Pfeffer habe ich mich geirrt, tut mir leid. Wikipedia: „Je nach Erntezeitpunkt und weiterer Behandlung haben die Pfefferkörner verschiedene Färbungen: grüner Pfeffer, schwarzer Pfeffer, weißer Pfeffer, roter Pfeffer.“  Damit sind es keine verschiedenen Arten, was die sonst geltende Duden-Regel aushebelt: „In der Botanik und Zoologie werden die deutschen Bezeichnungen der Arten, Unterarten und Rassen konsequent großgeschrieben.“ Ganz schön knifflig.

**Comment by textleister** [comment]
Das *tiefdunkle* Blau. → tiefdunkel bitte hinzufügen
http://www.duden.de/rechtschreibung/tiefdunkel

**Comment by textleister** [comment]
Côte d’Azur →  streicht „Côte“ an
http://www.duden.de/rechtschreibung/Cote_d_Azur

**Comment by textleister** [comment]
Sonnenbaden, ohne der Haut zu schaden. → „der Haut“ wird bemängelt und ein Akkusativ gefordert.

**Comment by textleister** [comment]
Wirkstoffkomplex

**Comment by textleister** [comment]
Applikator
http://www.duden.de/rechtschreibung/Applikator

**Comment by danielnaber** [comment]
For simple spell checker problems, please add the words on languagetool.org, click on the "error" and select "Word zur Aufnahme vorschlagen..." instead of reporting them here. That makes it easier for us.

**Comment by textleister** [comment]
Selbstreflektion → wird fälschlicherweise als korrekt angezeigt → Selbstreflexion
http://www.duden.de/rechtschreibung/Selbstreflexion

**Comment by textleister** [comment]
Habe „Anti-Aging“ als Wort bereits vorgeschlagen. Hier müsste man außerdem schauen, dass Konstruktionen wie Anti-Aging-Wirkstoffe durchgekoppelt werden.
http://www.duden.de/rechtschreibung/Anti_Aging

**Comment by textleister** [comment]
Feldbefehle werden in Libre Office 5.0.0.2 als Leerzeichen behandelt.
Seite 2 von 4 [→ „mehr als ein Leerzeichen hintereinander“]

**Comment by f-knorr** [comment]
Das ist ein von vielen bewundertes Haus. -> Fehlalarm wegen Rule "Kongruenz von Nominalphrasen (unvollständig!), z.B. 'mein kleiner(kleines) Haus'"
Trüffel sind teuer. -> Fehlalarm wegen Rule "Kongruenz von Subjekt und Prädikat (unvollständig)"
Er will ihm all das beibringen, was er wissen muss. -> Fehlalarm wegen Rule "Großschreibung von Nomen und substantivierten Verben"

**Comment by danielnaber** [comment]
@f-knorr: I'll try to fix these and strike through those that are fixed.

**Comment by Atalanttore** [comment]
Zungenbrecher:
"Wenn Hessen in *__Essen Essen__* essen, essen Hessen Essen in Essen."

In diesem Satz wird fälschlicherweise ein Fehler angezeigt.

**Comment by textleister** [comment]
Kostbare Säfte und Harze. → Harze wird nicht als Plural von Harz erkannt.
http://www.duden.de/rechtschreibung/Harz_Saft_Material

**Comment by textleister** [comment]
„Wachse“ wird nicht als Plural von Wachs erkannt.

**Comment by danielnaber** [comment]
Closing this issue, as it's getting too messy. Please open a new one if you find more cases.
