### ISSUE TITLE
Избыточность речи. Плеоназм.

### ISSUE THREAD

**Issue by mqklin** [languagetool-org/languagetool#334]
Плеоназм – употребление в речи близких по смыслу и потому логически излишних слов. Плеоназмы могут являться причинами неточности и неясности текста.

Примеры плеоназмов:
Главная суть, толпа людей, лично я, немного приоткрыть, свободная вакансия, возвращаться обратно, в общем и целом, поступательное движение вперёд, рыбная уха, впервые знакомиться, чрезвычайно громадный, очень крохотный, несколько побыстрее, ценные сокровища, тёмный мрак, повседневная обыденность, вернуться обратно, упал вниз, жестикулировать руками, топтать ногами, предчувствовать заранее, бесполезно пропадают, лучше предпочитает, в мае месяце, так например, планы на будущее, неиспользованные резервы, простаивать без дела, памятные сувениры, в конечном итоге, демобилизоваться из армии, травматическое повреждение, огромная махина, коллега по профессии.

Ссылка на статью: http://eyange.livejournal.com/96441.html

В статье есть другие разновидности избыточности речи -- тавтология и повтор слов. Если необходимо, могу создать отдельные тикеты для них.

**Comment by yakovru** [comment]
Программа умеет определять этот тип ошибок, однако часть представленных примеров действительно не определяются.
Некоторые примеры являются уже устойчивыми выражениями (например, очень часто встречается выражение "свободная вакансия"), и очень часто употребляются в речи.

**Comment by yakovru** [comment]
Правила созданы.
