### ISSUE TITLE
Kartoffelstampf

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#3345]
I tried to suggest "Kartoffelstampf" today, but the websites informs me that it has been suggested before and was rejected. This word does not appear in Duden but is a colloquial (maybe regional?) word for mashed potato.

## Examples:
[Geman Wikipedia](https://de.wikipedia.org/wiki/Kartoffelp%C3%BCree):
> Kartoffelpüree, Kartoffelbrei, Stampfkartoffeln, Kartoffelmus oder Kartoffelstampf, in Ostösterreich Erdäpfelpüree, schweizerhochdeutsch Kartoffelstock, ist ein Brei aus gekochten, zerdrückten und verrührten Kartoffeln sowie anderen Zutaten. Kartoffelpüree dient üblicherweise als Beilage. 

[Hamburger Abendblatt](https://www.abendblatt.de/ratgeber/kueche-und-genuss/article229552390/gerd-Rindchen-Restaurant-Cornelia-Poletto-hamburg-eppendorf.html):
> Eine gemütliche Wohlfühl-Kombination mit sinnensatten, intensiven Geschmackskomponenten ist das delikate Mangalitza Wollschwein mit Bohnen-Casserole, Kartoffelstampf und Vierländer Apfel (€ 38,-). 

[Der Tagesspiegel](https://www.tagesspiegel.de/themen/genuss/die-restaurantkritik-wilde-klosterkueche-neuzelle-fuer-foodies/26034206.html):
> Schließlich geht es ganz nah an die Tradition mit einem Teller, auf dem nur Kartoffelstampf, cremiger Quark, Leinöl und Kresseblätter liegen, ebenso einfach wie köstlich wegen der herausragenden Produkte, das geht durchaus.

**Comment by danielnaber** [comment]
Thanks, I have added it.
