### ISSUE TITLE
[en] incorrect tagging "VBZNNS_DT_NN"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3346]
> We are having classes this week.

> We have classes this week.

"classes" is only VBZ

**Comment by MikeUnwalla** [comment]
Also:

> We are taking classes this week, aren't we?

> The technicians are giving lectures next month at the university.

> The careless technicians were testing samples the night that the explosion occurred.

**Comment by MikeUnwalla** [comment]
Also: 

> I had **classes** the week my cat died. 

> She has **tests** a week from now.

These examples cause FN in PRP_HAVE_VB [1]. I will fix these FP also.
