### ISSUE TITLE
Unterschied 3.1: Desktop (fehlerhaft) und Libre-Extension (okay)

### ISSUE THREAD

**Issue by pauleamca** [languagetool-org/languagetool#335]
«, wird in der Desktop-Version als « , Fehler bemängelt
inder Datei .txt steht «, richtig
der gleiche Text als .odt findet keine Bemängelung in der Libre-Extension

**Comment by danielnaber** [comment]
Ich kann das Problem nicht nachvollziehen oder vielleicht verstehe ich es nicht richtig. Wie ist denn der komplette Eingabetext?

**Comment by pauleamca** [comment]
»Ich bin kein verkleideter Spitzbub«, antwortete ich, »sondern ein armer, frommer Pilger.«

Außerdem wird bei Absatzübergreifender wörtlicher Rede auch in der Libre-Extension bemägelt, dass ein einleitendes » kein abschließendes Gegenstück « findet.

In der Desktop-Version wird auch das ß bemängelt. Bei lang gesprochenen Silben kommt m.E. ein ß vor, wie bei Straße oder Spaß, schießen … bei kurzen ist es ss: dass oder Schuss.
Bei Libre wird diese Regeln akzeptiet.

**Comment by danielnaber** [comment]
Ich kann das Problem noch nicht nachvollziehen. Auf welchem Betriebssystem und mit welcher Java-Version (`java -version` auf der Kommandozeile) passiert das? Ein Screenshot von dem Fehler in der Desktop-Version könnte auch helfen.

**Comment by danielnaber** [comment]
Da bisher keine Antwort kam und ich das nicht reproduzieren kann, schließe ich das Issue.
