### ISSUE TITLE
[en] endless loop ANY_MORE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3350]
> No-one goes there anymore - it’s too crowded.

**Comment by tiff** [comment]
Another one:
> What was the purpose of that event (once upon a time it was mostly to show the clothes to US department store buyers - not anymore)?

**Comment by MikeUnwalla** [comment]
I cannot see how to fix this problem.

I think we might need to move ANYMORE_ADVERB from the general rules for EN. Make different versions for AmE and BrE.

**Comment by tiff** [comment]
@MikeUnwalla in both sentence "anymore" is the last word in a phrase. The phrase then either ends with a dash or a closing parenthesis. 

The issue doesn't happen when the dash is replaced by a comma:
> No-one goes there anymore, it’s too crowded.

So, I will add "-" and the closing ")" as exceptions.

**Comment by tiff** [comment]
Fixed, see latest regressions: https://internal1.languagetool.org/regression-tests/via-http/2020-07-30/en/result_grammar_ANYMORE_ADVERB[1].html
