### ISSUE TITLE
[Suggestion] Language tool working on https://pad.riseup.net/

### ISSUE THREAD

**Issue by pbaesse** [languagetool-org/languagetool#3360]
Hej everyone,

First congrats on the amazing project! I highly recommend it to all my friends and students :)

Secondly, I would be nice if it worked on https://pad.riseup.net/. I'm guessing it might not work on other pads as well.

Thanks

**Comment by tiff** [comment]
@pbaesse thanks for reporting this. It happens because pad.riseup.net has set "spellcheck=false" on its text fields. Which disables all spell checkers. From the next release of our add-on, we will ignore this. Might take 3-4 weeks until the new version is released.
