### ISSUE TITLE
[fr] Replacement string for "group" is the same as original

### ISSUE THREAD

**Issue by bperel** [languagetool-org/languagetool#3378]
LanguageTool reports that "group" is an anglicism, but the replacement that it suggests is the same as the original : "group".

![image](https://user-images.githubusercontent.com/1484692/89103238-97d36400-d410-11ea-9be0-6fbff367fcff.png)

**Comment by bperel** [comment]
Thank you for the quick fix!

**Comment by tiff** [comment]
@bperel No thank you. Please keep on reporting issues that you find. We need this feedback.
