### ISSUE TITLE
Too few/to few

### ISSUE THREAD

**Issue by gerhardkurz** [languagetool-org/languagetool#338]
The following examples give a warning suggesting to replace "to" with "too" even though "to" is correct:

It is restricted to few objects.

It is limited to few objects.

It is applicable to few objects.

**Comment by danielnaber** [comment]
Thanks - are you a native English speaker (I'm not)? Shouldn't it be "**a** few objects"? Then there's no alarm.

**Comment by gerhardkurz** [comment]
I'm not a native speaker either, but there is a difference between "few" and "a few", see for example
https://dictionary.cambridge.org/grammar/british-grammar/little-a-little-few-a-few

**Comment by danielnaber** [comment]
I see. It's fixed and the fix will soon be active on languagetool.org.
