### ISSUE TITLE
Windows 10 : Segmentation error vmState=0x00040000

### ISSUE THREAD

**Issue by survivant** [languagetool-org/languagetool#3382]
I just ran the demo : org.languagetool.clientexample.Example

and I got this error

`org.languagetool.clientexample.Example
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
This example will test a short string with all languages known to LanguageTool.
It's just a test to make sure there's at least no crash.
Using LanguageTool 5.0 (2020-06-26 20:25)
Supported languages: 45
Unhandled exception
Type=Segmentation error vmState=0x00040000
Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFE7B7B7A33 ContextFlags=0010005f
Handler1=00007FFE7B7AE940 Handler2=00007FFE843AAB20 InaccessibleReadAddress=0000000000000010
RDI=0000000000019A00 RSI=0000000000000000 RAX=000000EF28DFE278 RBX=000002A6BF010E18
RCX=0000000000019A00 RDX=000002A6A1ADE628 R8=0000000000000000 R9=00007FFE7B893610
R10=000002A6BF010000 R11=00007FFE7B893610 R12=000002A6A1ADE628 R13=000002A6A1ADE660
R14=000002A6A1ADE628 R15=000002A69EC54AB0
RIP=00007FFE7B7B7A33 RSP=000000EF28DFE200 RBP=0000000000000000 GS=002B
FS=0053 ES=002B DS=002B
XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM2 4024000000000000 (f: 0.000000, d: 1.000000e+01)
XMM3 43f0000000000000 (f: 0.000000, d: 1.844674e+19)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM7 0032003900370032 (f: 3604530.000000, d: 1.001332e-307)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=C:\dev\jdk11\bin\compressedrefs\j9vm29.dll
Module_base_address=00007FFE7B730000 Offset_in_DLL=0000000000087a33
Target=2_90_20200422_551 (Windows 10 10.0 build 10240)
CPU=amd64 (8 logical CPUs) (0x7f73e8000 RAM)
----------- Stack Backtrace -----------
(0x00007FFE7B7B7A33 [j9vm29+0x87a33])
Java_org_bridj_JNI_bindJavaMethodsToCFunctions+0x255 (0x00007FFEA7E368E5 [bridj+0x68e5])
J9_GetInterface+0x9e303 (0x00007FFE7B859E53 [j9vm29+0x129e53])
J9_GetInterface+0x9dd58 (0x00007FFE7B8598A8 [j9vm29+0x1298a8])
(0x00007FFE7B745F51 [j9vm29+0x15f51])
(0x000000EF28DFE630)
(0x000002A69EC54AB0)
(0x000000000000000D)
(0x000002A6A9840D2D)
(0x000000EF28DFE4D0)
(0x0000000000000010)
(0x000002A6A1A3ADF0)
(0x000000EF28DFE758)
(0x000000EF28DFE740)
(0x000000EF28DFE768)
(0x000000EF28DFE750)
(0x000000EF28DFE748)
(0x0000000001000188)
(0x0000000000000008)
(0x0000000000000008)
---------------------------------------
JVMDUMP039I Traitement de l'�v�nement de vidage "gpf", d�tails "" � 2020/08/03 10:19:11 - Veuillez patienter.
JVMDUMP032I La machine virtuelle Java a demand� un vidage System en utilisant 'F:\workspace-opensource\languagetool\core.20200803.101911.25284.0001.dmp' en r�ponse � un �v�nement
JVMDUMP010I Vidage System �crit dans F:\workspace-opensource\languagetool\core.20200803.101911.25284.0001.dmp
JVMDUMP032I La machine virtuelle Java a demand� un vidage Java en utilisant 'F:\workspace-opensource\languagetool\javacore.20200803.101911.25284.0002.txt' en r�ponse � un �v�nement
JVMDUMP010I Vidage Java �crit dans F:\workspace-opensource\languagetool\javacore.20200803.101911.25284.0002.txt
JVMDUMP032I La machine virtuelle Java a demand� un vidage Snap en utilisant 'F:\workspace-opensource\languagetool\Snap.20200803.101911.25284.0003.trc' en r�ponse � un �v�nement
JVMDUMP010I Vidage Snap �crit dans F:\workspace-opensource\languagetool\Snap.20200803.101911.25284.0003.trc
JVMDUMP007I JVM demandant un vidage JIT en utilisant 'F:\workspace-opensource\languagetool\jitdump.20200803.101911.25284.0004.dmp'
JVMDUMP010I Vidage JIT �crit dans F:\workspace-opensource\languagetool\jitdump.20200803.101911.25284.0004.dmp
JVMDUMP013I Ev�nement de vidage trait� "gpf", d�tails "".

Process finished with exit code -1
`

**Comment by danielnaber** [comment]
As a JVM crash is usually not something we can do anything about, I'm closing this.
