### ISSUE TITLE
[fr] Replacement string for "Shop" and "Forms" is the same as the original text

### ISSUE THREAD

**Issue by bperel** [languagetool-org/languagetool#3386]
A similar issue as #3378 :  the replacement that it suggests is the same as the original.
This only happens when the word with the first letter in uppercase is used.

> Un missile que le Shop cherche à lancer sur la flotte américaine.
> Remplir des Forms à longueur de journée m'ennuie.

![image](https://user-images.githubusercontent.com/1484692/89264331-01cb5380-d633-11ea-9926-038a220088ee.png)

Note that the "Forms" suggestion is also indicated 3 times.

**Comment by jaumeortola** [comment]
Related to #3273. I will try to fix these issues with a new simple replace Java rule.
