### ISSUE TITLE
Missing scroll bar in LT 3.1 GUI

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#339]
Sometimes, in LanguageTool Options and on the main screen, the vertical scroll bar disappears. I cannot consistently reproduce the problem.
![missing-vertical-scroll-bar](https://cloud.githubusercontent.com/assets/5816160/11564643/2bb4f4dc-99d2-11e5-916d-1b535844e3f6.png)

**Comment by danielnaber** [comment]
@pminos Panagiotis, I think you know more about Swing than most other devs on the LT team do, do you have any idea how to fix this?

**Comment by pminos** [comment]
I remember this issue, I tried to reproduce it but I couldn't. I will give one more try.

**Comment by pminos** [comment]
@MikeUnwalla can you tell me what operating system you use and the version of Java?

**Comment by danielnaber** [comment]
I can reproduce it (in the main window), it might depend on the length of the text. E.g. if you go to https://de.wikipedia.org/wiki/Regierungsbezirk_Detmold and copy all the page and paste it to the window (set to German), the scroll bar gets lost.

**Comment by MikeUnwalla** [comment]
Operating system: Windows 7 Professional, Version 6.1
Java version: Version 8 Update 71

Regards,

Mike Unwalla
Contact: www.techscribe.co.uk/techw/contact.htm 

-----Original Message-----

**Comment by pminos** [comment]
When using Nimbus L&F, the scrollbar thumb disappears when it becomes too small. This is a [JDK bug](https://bugs.openjdk.java.net/browse/JDK-8134828) that introduced in version 8u60.

The only solution is to update to Java 8u72, or downgrade.

**Comment by pminos** [comment]
@MikeUnwalla and @danielnaber is this happening with another L&F?
@MikeUnwalla if you update to Java 8u72, can you see the thumb?

**Comment by MikeUnwalla** [comment]
The scroll bar is available if I change to a different L&F (not Nimbus).

With Java 8u72 and Nimbus L&F, the scroll bar is available.

Thanks and regards,

Mike Unwalla
Contact: www.techscribe.co.uk/techw/contact.htm 

-----Original Message-----

**Comment by danielnaber** [comment]
I can confirm it works with style "Metal", so I'm closing this issue.
