### ISSUE TITLE
Handling apostrophes, quotes and other typography issues (French, Catalan...)

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#3390]
There are two valid apostrophe characters: `'` (typewriter apostrophe) and `’` (typographical apostrophe). Handling them appropriately everywhere in LanguageTool can be really annoying. I have implemented some methods to simplify the work: 
1. In the tokenizer, convert typographical apostrophe to typewriter apostrophe, and add a tag to indicate what was the original apostrophe. (It is not converted if it is used as a closing quotation mark)
2. Everything inside LanguageTool works with typewriter apostrophes: dictionaries, multiwords, disambiguation, rules, suggestions... 
3. If the rule that requires a typographical apostrophe is enabled, then apostrophes in suggestions are converted to typographical apostrophes. 

Points 1 and 2 are already implemented in French and Catalan. Point 3 is implemented only in Catalan, and it could be done also in French. The rule that requires typographical apostrophes should be an optional rule or "picky mode" rule. But this is a different question: when and how should this rule be enabled.

Accurate typography (curly apostrophes, curly quotes, thin spaces...) could be used also in rule messages. But writing and maintaining messages this way needs a lot of work and it is error-prone. I think the best solution is to write and keep the messages in plain text (straight apostrophes and quotes, normal white spaces...) and add the accurate typography automatically, the same way it is done by the autocorrect feature in word processors. It would be a language-dependent method, and it would be applied to all messages before being shown to the user. 

The same method could be used if we implement someday an autocorrect feature.

**Comment by jaumeortola** [comment]
@danielnaber @udomai @vkyfox This is related to the "espace insécable" in French. I think it would be much better to do all "advanced typography" automatically and not manually.

**Comment by udomai** [comment]
@jaumeortola That would be great...how much time would it take to replace every space before ?!:; in the <message> sections with espaces insécables (&#8239;)? Is it a very time-intensive task? And: are espaces insécables inside of guillemets even relevant for <message> text?

**Comment by jaumeortola** [comment]
What I propose is to add a Java method that converts all messages to "advanced typography" before showing the message to the user. XML rules can be left as they are. We only need a few lines of Java code (customized for every language). 

XML rules could be changed with a few "search & replace all" commands. But we would need to do this periodically to check if new rules are right. It is not a definitive solution.

**Comment by udomai** [comment]
Hi Jaume! Your proposal with a Java method converting the message before they are shown to users sounds fantastic! It would automatically insert the NNBSP before all question marks etc.? That would indeed be a way more definitive solution!!

**Comment by jaumeortola** [comment]
Started advanced typography here for French: https://github.com/languagetool-org/languagetool/commit/b8ac25c8f41f18432db16389907703a89aafbf6a
Catalan and Spanish: https://github.com/languagetool-org/languagetool/commit/3a3bdc2c17855528df75fa1872b88c03c52e8703

Perhaps it is not exhaustive, and we need some more tests.

**Comment by jaumeortola** [comment]
This is almost finished. But we could still find examples where the conversion is not done correctly.

This feature can be used by other languages. For example, in English the rule for "smart quotes" is enabled by default, but the LanguageTool messages don't use smart quotes. Now, smart quotes could be added automatically to messages. @udomai @MikeUnwalla

**Comment by MikeUnwalla** [comment]
@jaumeortola ,

> Now, smart quotes could be added automatically to messages.

That would be great.

**Comment by udomai** [comment]
@jaumeortola , I agree, that would be wonderful!!

**Comment by jaumeortola** [comment]
Done here for English (I mistyped the language code): https://github.com/languagetool-org/languagetool/commit/c3d5f35acc3f5a8a8f79015ed85f55f8984135e0

**Comment by udomai** [comment]
Did it not pass the check?
