### ISSUE TITLE
Error installing LT extension.

### ISSUE THREAD

**Issue by vishne-aleksandr** [languagetool-org/languagetool#3393]
Hello.
When installing the LanguageTool 5.0.1 extension for LibreOffice 7.0.0.3 (x64), a file path error message is displayed. Java 1.8.0_261 is installed for both 64 bit and 32 bit systems. Other extensions downloaded from the libreoffice site were installed without problems. The old LanguageTool 4.8 extension installed with an older version of LibreOffice worked and installed fine. Now it is not installed either, the same error message appears. How to overcome this problem?
![Безымянный](https://user-images.githubusercontent.com/69267453/89456384-77870a80-d76c-11ea-8635-5455a6de86a6.jpg)

**Comment by theinfinityproject** [comment]
Macos 10.15.6
LibreOffice 7.0.0 x86-64
Java 14.0.2
LanguageTool 5.0.1.

Same Problem after upgrading from 6.4 LibreOffice to 7.0

Attempted to reinstall after removing LanguageTool 5.0.1.

Error Msg:

Could not create Java implementation loader

**Comment by danielnaber** [comment]
Have you checked the common issues at https://languagetool.org/issues#office?

**Comment by theinfinityproject** [comment]
@danielnaber yes, I did.  LibreOffice 6.4.5 x86-64 with Java 14.0.2 and LanguageTool 5.0.1 was perfectly working. Only Upgrading changed that. 

Error Msg: LibreOffice requires a Java runtime environment (JRE) to perform this task. The selected JRE is defective. Please select another version or install a new JRE and select it under LibreOffice - Preferences - LibreOffice - Advanced.

Reinstalling LanguageTool 5.01 on LO 7.0: see my first post
Reverting back to 6.4.5 and reinstalled LT 5.01: no error msg; works as intended

**Comment by vishne-aleksandr** [comment]
The problem has been resolved. You need to reset your user profile in LibreOffice 7.0.3. How to do this I give links.
https://ask.libreoffice.org/en/question/258907/installing-the-languagetool-extension/
https://wiki.documentfoundation.org/UserProfile/ru
