### ISSUE TITLE
[en] Proper nouns and spelling

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3395]
I tried to add the spelling for the proper noun **Fríður** to spelling.txt. Maven gave this warning:

```
[ERROR]   EnglishTest.testLanguage:47->LanguageSpecificTest.runTests:48 Word 'Fríður' from en/hunspell/spelling.txt doesn't match regex: [ 0-9a-zA-ZöäüÖÄÜßëçèéáàóòÈÉÁÀÓÒÍãñíî?&Ææ?ýÅåø?ùçı??ö??????????????????????????????????????????????????????????????????????????úïÎôêâû'?./-]+|[khmcdµ]?m[²³]|°[CFR]|C?O?-?.*|mc² - please fix the word or add the character to the language's org.languagetool.rules.WordListValidatorTest if it's valid
[INFO]
```

Would it make sense for the Maven check to ignore all the characters in a word that is tagged as a proper noun (NNP)?

**Comment by tiff** [comment]
@MikeUnwalla in order to make the tests work, just add the word to this list:
https://github.com/languagetool-org/languagetool/blob/master/languagetool-core/src/test/java/org/languagetool/rules/WordListValidatorTest.java#L113

**Comment by MikeUnwalla** [comment]
@tiff , thanks, done.

Not sure whether to leave this issue open, because manually adding a known good word to a list seems unnecessary work. What do you think?

**Comment by tiff** [comment]
I think the test is helpful because it will warn you when you accidentally inserted exotic characters into a word

**Comment by MikeUnwalla** [comment]
OK, thanks. I will close this issue.
