### ISSUE TITLE
MacOS LO 7.03 JAVA Issues

### ISSUE THREAD

**Issue by theinfinityproject** [languagetool-org/languagetool#3400]
I open this as reference for other users that might be affected, since #3393 got already closed. 
Fyi: For anyone affected by 

> LibreOffice requires a Java runtime environment (JRE) to perform this task. The selected JRE is defective. Please select another version or install a new JRE and select it under LibreOffice - Preferences - LibreOffice - Advanced

after upgrading to LO 7.03. It is not LanguageTool but LO itself, see: [LO Bug 135462](https://bugs.documentfoundation.org/show_bug.cgi?id=135462)

**Comment by FredKruse** [comment]
I'm closing the issue as resolved. If necessary, please open a new one with the current versions (LO and LT).
