### ISSUE TITLE
English false alarms

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#343]
Copied from http://languagetool-user-forum.2306527.n4.nabble.com/Bugs-and-and-Rule-Suggestions-td4643466.html:

- [x] I choose uniform objects.
- [x] I can afford uniform objects. 
- [x] It has an advantage compared to objects that make something.
- [x] It has an advantage compared to approaches that make something.
- [x] It is compared to objects that make something.

**Comment by danielnaber** [comment]
Fixed - keeping this issue open for future errors.

**Comment by rcrath** [comment]
from https://bugs.documentfoundation.org/show_bug.cgi?id=96837 . Screen Capture Here:
[whoisare.mov.zip](https://github.com/languagetool-org/languagetool/files/77308/whoisare.mov.zip)
)

The grammar checker sees "who are blah blah blah", mistakes "are" for a noun, and suggests "who is are blah blah blah as correction.

Reproducible: Always

Steps to Reproduce:
1. write "The students, who are, after all, just learning too" and observe grammar correction wavy lines
2. open correction window, which IDs "are" as a noun and suggests "who is are..." as replacement
3.seems to be triggered by the commas.  

Actual Results:  
bad substitution

Expected Results:  
no grammar correction for this phrase

Language tool 3.1

[Information automatically included from LibreOffice]
Locale: en-US
Module: TextDocument
[Information guessed from browser]
OS: Linux (All)
OS is 64bit: yes
