### ISSUE TITLE
[en] false alarms PROGRESSIVE_VERBS

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#3432]
The rulegroup id="PROGRESSIVE_VERBS" in grammar.xml is being triggered too often. The (temporary or permanent) deactivation rate for this rule is way above average. This rulegroup needs to be "softened" so that especially native speakers do not perceive it as pesky.

If we add a number of antipatterns, we can measure if that has any effect on deactivation rates. Let's start with the following exceptions for the progressive verbs rule:

- [x] loving, concerning, pleasing (used as adjectives)

- [x] is VBG (as in: “The first step is admitting you’re wrong”)

- [x] sound (as in: I know I’m sounding like a tory, but...)

- [x] hear (as in: He’s hearing voices...)

- [x] deny (as in: I am not denying that, all I’m saying is...)

- [x] I‘m understanding (as in: If I’m understanding you correctly, what you’re saying is...)

- [ ] constantly/increasingly VBG

- [x] won‘t be needing / will be needing: MD be VBG? To also cover for “you might be needing an umbrella” (is that even a thing?)

I have attached a file containing (brief) contexts in which the PROGRESSIVE_VERBS rule has been deactivated. I have used those to extrapolate the most frequent contexts for false positives. We can use that for further reference when fine-tuning the rule – and I can get more examples if needed.

[Notes PROGRESSIVE_VERBS.docx](https://github.com/languagetool-org/languagetool/files/5062884/Notes.PROGRESSIVE_VERBS.docx)

**Comment by MikeUnwalla** [comment]
Lists of stative verbs:

- https://www.gingersoftware.com/content/grammar-rules/verbs/stative-verbs/
- https://www.perfect-english-grammar.com/stative-verbs.html
- https://www.thoughtco.com/differences-between-action-and-stative-verbs-1211141

**Comment by udomai** [comment]
Those are interesting! But they have the same problem of over-generalizing the stative nature of those verbs (as in incompatibility with the progressive form): Perfect English Grammar has "realize". I can find normal-sounding counter-examples like "I am just now realizing why people didn't like Double Agent." ThoughtCo has "think" – but "I'm still thinking about it too much" can be found.
However, in those articles, we might find some useful indications about the contexts in which the progressive form can be used legitimately.

**Comment by MikeUnwalla** [comment]
Agreed. For starters, I will change the message to emphasise that ~ing is not wrong. Depends on the intended meanin of the text.

**Comment by MikeUnwalla** [comment]
~ing used as an adjective. The context is important, but rules cannot span sentence boundaries.

Verb, incorrect: Although you explained this many times, I **am not understanding**. Please explain again.

Adjective, correct: As you said many times, I am not understanding. Nor do I have tolerance, patience, or kindness.

**Comment by MikeUnwalla** [comment]
The rule editor (https://community.languagetool.org/ruleEditor/expert?devMode=true) gives more than 1900 warnings for rule 1:

[rule-editor-rule1-results.txt](https://github.com/languagetool-org/languagetool/files/5073807/rule-editor-rule1-results.txt)

**Comment by udomai** [comment]
Ooooo...and so many juicy FPs! I think Rule 1's five antipatterns are far from being complete. The third antipattern should add _voices_ at \3, for example...

**Comment by udomai** [comment]
I have decided to commandeer this matter ;) some more drastic measures are required, I'm taking over!
