### ISSUE TITLE
Command line tool enhancements 

### ISSUE THREAD

**Issue by stereobooster** [languagetool-org/languagetool#344]
- color support.
- interactive mode: it will be possible to add words to ignore list.
- per folder/project settings: to ignore words, to ignore style rules, to set default language.

Something like [mdast-lint](https://github.com/wooorm/mdast-lint) or [eslint](http://eslint.org/docs/user-guide/command-line-interface) or [rubocop](https://github.com/bbatsov/rubocop), but for natural language.

![68747470733a2f2f63646e2e7261776769742e636f6d2f776f6f6f726d2f6d646173742d6c696e742f6d61737465722f73637265656e2d73686f742e706e67](https://cloud.githubusercontent.com/assets/179534/11770033/befb65ec-a205-11e5-8e5b-e9adb30f5bcb.png)

Extracted from here: http://stereobooster.github.io/spell-grammar-style-checkers/#what-do-i-want

**Comment by DancingQuanta** [comment]
Another ideas could be a step through each issue highlighted by LanguageTool and offers any corrections in similar fashion to [texspell](https://www.ctan.org/pkg/texspell?lang=en) where an issue would be ignored once or for whole document, added to a personal dictonary or insert correction manually on the fly.

**Comment by stereobooster** [comment]
@DancingQuanta is right. Some time after using `aspell`, I can say this is quite convenient way to work.
