### ISSUE TITLE
Proofread all rule messages of a language

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#3442]
It could be a script that extracts in plain text all rule messages of a language (as exhaustively as possible). The extracted text can be checked using LanguageTool.

Or it could be a method in which LanguageTool checks all its own messages.

**Comment by jaumeortola** [comment]
Developing the idea. 

We can extract text from everywhere: XML and Java rules, messages, short messages... Perhaps also rule names, but rule names sometimes include the error detected by the rule, and we will get many positives. 

To check regularly any change in the messages, we could extract all texts, check them and show the differences in the same way we do with the nightly differences.  

I can add a method inside language-dev that does all the checking for every language. Then we can show the results as nightly differences.

**Comment by danielnaber** [comment]
Sounds like a good idea!

**Comment by baarsrj** [comment]
Will give some positives certainly, since some rules are not that 'hard' and require a human check, for meaning e.g.

**Comment by jaumeortola** [comment]
Started here: https://github.com/languagetool-org/languagetool/commit/0c08c1121c18dbffd1951759bb7c82366ea40499

Expect a number of positives in many languages: messages include the errors detected, abbreviations, meta-language (talking about language), etc.

**Comment by jaumeortola** [comment]
We could discard the match if the rule ID is the same ID of the rule being checked. For example, in French, discard the rule BACKGROUND when checking the message of the same rule (`« Background » est un anglicisme.`).

**Comment by jaumeortola** [comment]
@danielnaber I can run the program inside an IDE, but in the command line I get this error:
```
$ java -cp languagetool-dev-5.1-SNAPSHOT-shaded.jar org.languagetool.dev.checkLTmessages.checkLTmessages en
Exception in thread "main" java.lang.IllegalArgumentException: 'en' is not a language code known to LanguageTool. Supported language codes are: ar. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See http://wiki.languagetool.org/java-api for details.
	at org.languagetool.Languages.getLanguageForShortCode(Languages.java:218)
	at org.languagetool.Languages.getLanguageForShortCode(Languages.java:195)
	at org.languagetool.dev.checkLTmessages.checkLTmessages.main(checkLTmessages.java:54)
```

**Comment by jaumeortola** [comment]
Finished. Some comments:

- Messages, short messages and rule descriptions are checked. 
- Rule matches with the ID of the rule being checked are ignored. Example: French rule BACKGROUND is ignored when checking the message `« Background » est un anglicisme.`.
- UPPERCASE_SENTENCE_START is ignored in rule descriptions.
- Adjustments will be needed for some languages. For example, in English the rule EN_QUOTES gives many positives. Solution: change the messages (using `toAdvancedTypography`), or ignore the rule.
- The first time the program is run someone has to check thoroughly the results and fix the typos for every language. Afterwards, we can focus on differences. 

@danielnaber Can you show these results as nightly differences?
@udomai

**Comment by danielnaber** [comment]
> I can run the program inside an IDE, but in the command line I get this error:

I think you need to build with `mvn clean compile assembly:single` in `languagetool-dev`. The result is `target/languagetool-dev-5.1-SNAPSHOT-jar-with-dependencies.jar`

**Comment by danielnaber** [comment]
@jaumeortola Just so we stick to the Java conventions, could you rename class `checkLTmessages` to `LTMessageChecker`?

**Comment by danielnaber** [comment]
First run (with empty diff) is now being stored to https://internal1.languagetool.org/regression-tests/message-spelling/. Note that special chars might be displayed incorrectly when opening the files in the browser (download it instead and open as UTF-8).

**Comment by udomai** [comment]
Thank you, this is really cool! One thing about the de-DE.txt: I've seen that it's enormous and that most errors were due to advanced typography. We don't need to check for that, right? Could we make it so rules like
```
TYPOGRAFISCHE_ANFUEHRUNGSZEICHEN
ABKUERZUNG_LEERZEICHEN
AUSLASSUNGSPUNKTE
```
are not applied for this check?

**Comment by jaumeortola** [comment]
Thank you! 
Obviously, we should keep the full results available because it is impossible that every language is checked exhaustively the first time. To look at the results regularly, it would be helpful if the web server shows the results in UTF-8.

**Comment by jaumeortola** [comment]
> Could we make it so rules like... are not applied for this check?

We could add exceptions. Or maybe we could sort the rules by ID, as in the other nightly tests.

But, any way, it is strange that LanguageTool recommends something that LanguageTool itself doesn't apply, isn't it? Now, we can use advanced typography in all messages automatically. You just need to tell me what characters you want for each language: opening and closing single quotes, opening and closing double quotes, spaces, etc.

**Comment by danielnaber** [comment]
> it would be helpful if the web server shows the results in UTF-8.

done

**Comment by jaumeortola** [comment]
Use advanced typography in rule descriptions to avoid too many positives: https://github.com/languagetool-org/languagetool/commit/c8346cdbccf857feed9929bdebc676c51b9b33f1

**Comment by danielnaber** [comment]
I've moved the results to their own folder so the list doesn't look as cluttered: https://internal1.languagetool.org/regression-tests/message-spelling/result/. It's also HTML with syntax highlighting now.

**Comment by baarsrj** [comment]
What is 'advance typography, and what is it for? Was there any info shared somewhere that I missed? What is expected from rule maintainers?

**Comment by baarsrj** [comment]
By the way... most style rules are just a matter of taste and audience. I think those should not be checked at all. Just the 'hard' errors.

**Comment by udomai** [comment]
> What is 'advance typography, and what is it for? Was there any info shared somewhere that I missed? What is expected from rule maintainers?

Hi Ruud! Advanced typography is about typographical apostrophes and quotation marks `(Who's vs. Who’s)`. It is also about ellipses as one character instead of three periods, non-breaking spaces and non-breaking non-spaces (so a line does not end between e. and g. in the abbreviation e.g., for example (see also above)). We have decided to adopt it in our <message> texts. Has this been done for Dutch, too? @jaumeortola 
Anyway, rule maintainers don't have to worry about this (Jaume, please correct me if I'm wrong).

**Comment by jaumeortola** [comment]
@baarsrj I wrote a post [on the forum](https://forum.languagetool.org/t/to-language-mantainers-advanced-typography-in-lt-messages/6068) for all language maintainers to see.

**Comment by danielnaber** [comment]
One more change: The results in https://internal1.languagetool.org/regression-tests/message-spelling/result/ now get saved to a subdirectory with the date as a name, so old results are not lost

**Comment by jaumeortola** [comment]
A few things to wind up this issue:
- Check also Premium rules.
- Send a daily message to maintainers (or add it to existing messages), when there are relevant differences.
- Remember maintainers that the full results need to be checked. Nightly differences only show new errors.

**Comment by danielnaber** [comment]
I think this can be closed now?
