### ISSUE TITLE
Gender-bias correction

### ISSUE THREAD

**Issue by Pawtiko** [languagetool-org/languagetool#346]
I think it would be a good idea for gender-biased words and phrases such as 'mankind' and 'common man' to be replaced with things like 'humans' and 'average person', to help writers remain neutral. Another open-source project implements this function, and I think it is extremely useful.

**Comment by dpelle** [comment]
This is bad ideas in my opinion.
Such warnings, for things which are not errors, will turn off most users.
There is nothing wrong with a word like "mankind".

There are still plenty of real mistakes to be detected by
LanguageTool. For English, it's easy to find examples of
errors. For example:
http://public.wsu.edu/~brians/errors/errors.txt

**Comment by Pawtiko** [comment]
Many people have no problem with it, but some do, and I think there is no harm in at least providing it as an option. You're right though that it should not be a focus in development as long as other more commonly accepted errors are still no found.

**Comment by danielnaber** [comment]
Currently we mark spelling errors with red and other errors with orange (at least on languagetool.org). I think we should have a third color for style problems that's more subtle (maybe a light yellow). Plus if we had an easy way to not only turn off single rules but classes of rules we could add more rules of this kind without annoying users who are not interested in those rules.
