### ISSUE TITLE
[DE][LibreOffice] "bereit zu sein" Fehlalarm

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#3471]
Moin liebes LanguageTool-Team

Dallun sagte: „Das Training hat leider voran, denn wir müssen Erfahrungen sammeln, um irgendwann bereit zu sein, um uns diesem Kidnappernetzwerk stellen zu können.“
LT: ![grafik](https://user-images.githubusercontent.com/40240507/90972032-fd99a400-e515-11ea-8136-73ffd37b98ab.png)

https://www.duden.de/rechtschreibung/bereit#rechtschreibung
Laut Duden muss **bereit sein** getrennt geschrieben werden. Nur in LibreOffice tritt der Fehler auf, nicht auf der Homepage.

Grüße Dallun511

**Comment by FredKruse** [comment]
Auch diesen Fehler kann ich nicht nachvollziehen. Er muss die gleiche Ursache haben wie #3575.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/94361813-6812a680-00b7-11eb-9489-3e008e6ee255.png)
Die Kleischreibung und Zusammenschreibung wird von Wörterbuch verneint. Bisher war das immer der Fall, dass das Wörterbuch die Zusammenschreibung nicht. Auch bei Wörter, die wirklich existieren.
