### ISSUE TITLE
[fr] make the anglicism messages nicer

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#3472]
I noticed that the messages for anglicisms in French were very harsh: "XY est un anglicisme. Employez Z".
Deactivation-wise, those rules are not doing well. Many of them will have to be tagged as picky.

As a first step, please make the message for the rules

- HELLO
- BACKGROUND

nicer, along the lines of "XY est un anglicisme – vous pourriez vous servir de 'Z' à la place".

Can we also change the message of the FR_SIMPLE_REPLACE_ANGLICISM? For now, it says "Cette expression est un anglicisme" – it might say something like "Alternatives possibles pour cet anglicisme :"

I think that some of our users need LT in contexts where some anglicisms are the standard, so we should not scold them ;)

@vkyfox @jaumeortola

**Comment by udomai** [comment]
Thank you @jaumeortola!

@vkyfox, there's only the rule id="HELLO" left, could you make that message softer? Whoever uses that word probably knows what they're doing, so the message should not be so harsh. It should rather be helpful inasmuch as it offers alternatives.

**Comment by vkyfox** [comment]
Adjusted! https://github.com/languagetool-org/languagetool/pull/3521

**Comment by udomai** [comment]
Phenomenal! Thank you both!!
