### ISSUE TITLE
Send api requests to stdin

### ISSUE THREAD

**Issue by vigoux** [languagetool-org/languagetool#3475]
Hey there, and thanks for the awesome tool !

When building a plugin for neovim, I would like to send requests to the languagetool server via stdin instead of HTTP.

How can I do that ? Is that even possible ?

**Comment by danielnaber** [comment]
There's `languagetool-commandline.jar` but it has a slow start-up time, so using the HTTP server (even if locally) is heavily recommended.

**Comment by vigoux** [comment]
No no way for me to have a server to which I send requests via stdin ?

**Comment by danielnaber** [comment]
> No no way for me to have a server to which I send requests via stdin ?

I don't think so.
