### ISSUE TITLE
[es] not found: "ensenar"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3476]
User report:

> It does not correct the Spanish word ensenar. It should have spanish n with tilde.

**Comment by jaumeortola** [comment]
"Ensenar" is a correct verb, much less frequent than the verb "enseñar" (to teach). So, I will start with a rule that always suggests "enseñar".

**Comment by danielnaber** [comment]
Thanks. Are there many of these cases? Would it make sense to search for them systematically, by iterating over all words in the dictionary to see which word with special characters also appears without special chars?

**Comment by jaumeortola** [comment]
> Are there many of these cases? Would it make sense to search for them systematically, by iterating over all words in the dictionary to see which word with special characters also appears without special chars?

I'm looking at it. There are around 30 lemmas like this (ensenar/enseñar, ano/año...). Some are very infrequent words and I will add simple rules suggesting the most frequent word. Others depend on the context (some are already detected by existing rules).

**Comment by jaumeortola** [comment]
>  There are around 30 lemmas like this (ensenar/enseñar, ano/año...).

This number was wrong. There are around 150 lemmas. But I think that not much more can be done.
