### ISSUE TITLE
Catalan ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3478]
Very easy to reproduce, just check `D` and nothing else:

```
Aug 25 08:33:20 api18 languagetool-api[454]: Caused by: java.lang.RuntimeException: Could not check sentence (language: Catalan): <sentcontent>D</sentcontent>
Aug 25 08:33:20 api18 languagetool-api[454]: #011at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1747)
Aug 25 08:33:20 api18 languagetool-api[454]: #011at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1625)
Aug 25 08:33:20 api18 languagetool-api[454]: #011at org.languagetool.JLanguageTool$TextCheckCallable.call(JLanguageTool.java:1582)
Aug 25 08:33:20 api18 languagetool-api[454]: #011at org.languagetool.JLanguageTool.performCheck(JLanguageTool.java:1117)
Aug 25 08:33:20 api18 languagetool-api[454]: #011... 10 more
Aug 25 08:33:20 api18 languagetool-api[454]: Caused by: java.lang.RuntimeException: Error analyzing sentence: '<S> D[</S>D/AO0CN0,<P/>]' with rule CONTRACCIONS[1]
Aug 25 08:33:20 api18 languagetool-api[454]: #011at org.languagetool.rules.patterns.PatternRule.match(PatternRule.java:227)
Aug 25 08:33:20 api18 languagetool-api[454]: #011at org.languagetool.JLanguageTool.checkAnalyzedSentence(JLanguageTool.java:1167)
Aug 25 08:33:20 api18 languagetool-api[454]: #011at org.languagetool.JLanguageTool$TextCheckCallable.getOtherRuleMatches(JLanguageTool.java:1703)
Aug 25 08:33:20 api18 languagetool-api[454]: #011... 13 more
Aug 25 08:33:20 api18 languagetool-api[454]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
Aug 25 08:33:20 api18 languagetool-api[454]: #011at org.languagetool.AnalyzedSentence.getOriginalPosition(AnalyzedSentence.java:167)
Aug 25 08:33:20 api18 languagetool-api[454]: #011at org.languagetool.tagging.disambiguation.rules.DisambiguationPatternRuleReplacer.executeAction(DisambiguationPatternRuleReplacer.java:360)
Aug 25 08:33:20 api18 languagetool-api[454]: #011at org.languagetool.tagging.disambiguation.rules.DisambiguationPatternRuleReplacer.replace(DisambiguationPatternRuleReplacer.java:149)
Aug 25 08:33:20 api18 languagetool-api[454]: #011at org.languagetool.tagging.disambiguation.rules.DisambiguationPatternRule.replace(DisambiguationPatternRule.java:94)
Aug 25 08:33:20 api18 languagetool-api[454]: #011at org.languagetool.rules.Rule.getSentenceWithImmunization(Rule.java:195)
Aug 25 08:33:20 api18 languagetool-api[454]: #011at org.languagetool.rules.patterns.PatternRule.match(PatternRule.java:223)
Aug 25 08:33:20 api18 languagetool-api[454]: #011... 15 more
```

**Comment by jaumeortola** [comment]
I can't reproduce the error on the command-line. But it happens when <example>D</example> is added to the rule  `CONTRACCIONS[1]`.

**Comment by danielnaber** [comment]
I could reproduce using the API (https://api.languagetool.org/v2/check?text=D&language=ca)

**Comment by jaumeortola** [comment]
There was a wrong antipattern that made no sense. But I don't know the exact reason for the exception here: https://github.com/languagetool-org/languagetool/blob/master/languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/rules/DisambiguationPatternRuleReplacer.java#L148

**Comment by danielnaber** [comment]
Reopening, because the same thing happens with `*I+D/R+D` (only if there's no line break at the end).

**Comment by jaumeortola** [comment]
I can reproduce the error on the API: https://api.languagetool.org/v2/check?text=I%2BD&language=ca, but not onn the command-line or in the rule examples.

**Comment by jaumeortola** [comment]
I don't know the real cause of the error. One possible explanation is that the character `+` is misinterpreted at some point as a special character in regular expressions. 
(In Spanish, there are problems synthesizing POS tags that contain the character `+`. I will probably change it for another character in the dictionary.)

**Comment by jaumeortola** [comment]
Strangely, there is no error in the softcatala.org API: https://www.softcatala.org/languagetool/api/v2/check?text=I%2BD&language=ca

**Comment by danielnaber** [comment]
> Strangely, there is no error in the softcatala.org API

Maybe the error was introduced very recently? softcatala uses an API that's 5 days old.

**Comment by danielnaber** [comment]
We should find the underlying cause, as here's yet another example:

http://localhost:8081/v2/check?text=Q.P.D&language=ca

**Comment by jaumeortola** [comment]
The error is caused by this antipattern:
```
<antipattern>
    <token case_sensitive="yes">D<exception scope="previous" postag="SENT_START"/></token>
</antipattern>
```
The problem goes away changing the antipattern a bit:
```
<antipattern>
    <token case_sensitive="yes">D<exception scope="previous" postag="SENT_START"/></token>
    <token regexp="yes">el|els|al|als</token>
</antipattern>
```
or
```
<antipattern>
    <token><exception postag="SENT_START"/></token>
    <token case_sensitive="yes">D</token>
</antipattern>
```

**Comment by danielnaber** [comment]
Same for `I+D`

**Comment by jaumeortola** [comment]
The errors have disappeared. But I have not pinpointed the exact cause of the bugs, which is inside this method, as said before: https://github.com/languagetool-org/languagetool/blob/master/languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/rules/DisambiguationPatternRuleReplacer.java#L148

**Comment by danielnaber** [comment]
Same problem for `°` - sorry, I didn't have time to look for the actual cause yet.

**Comment by jaumeortola** [comment]
The problem seems to be in antipatterns with only one token like this: https://github.com/languagetool-org/languagetool/commit/cc010aa8afad6b3858301a2b93618607100cf49c
I will avoid these patterns: https://github.com/languagetool-org/languagetool/commit/1452f26fc2ac9a476dabb9000a24e6b45373b663

**Comment by danielnaber** [comment]
Old issue, closing
