### ISSUE TITLE
Unnecessary "switch to Catalan" when checking in Valencian

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#3483]
It is not necessary to "switch to Catalan" (code: ca-ES) when checking in Valencian (code: ca-ES-valencia).

![imatge](https://user-images.githubusercontent.com/4289501/91198432-d4873800-e6fc-11ea-84c7-13040562d9b4.png)

**Comment by danielnaber** [comment]
should be fixed by https://github.com/languagetool-org/languagetool-website-2018/commit/42d5a4f47c938b1ac24df1e469c408e469097515
