### ISSUE TITLE
[es] not found "que"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3485]
User reported that on this page: https://www.spellboy.com/acerca-de/
We don't find the second mistake with "qué". Not sure if correct or not, @jaumeortola 
![image](https://user-images.githubusercontent.com/37363/91305744-c5ab8e80-e7ab-11ea-9099-49396dbc0001.png)

Full sentence:
> Pruébalo y sabrás por qué millones de personas en todo el mundo han depositado su confianza en nuestro servicio.

**Comment by tiff** [comment]
Hm, it seems correct because if I change it to "que" then we suggest "qué". Is there maybe a different error in that sentence?

**Comment by jaumeortola** [comment]
"Sabrás por qué" (= "sabrás por qué razón", you will know why) is correct.

**Comment by tiff** [comment]
Ok, thanks. Then ignore it.
