### ISSUE TITLE
conflicting pronouns...

### ISSUE THREAD

**Issue by stands4** [languagetool-org/languagetool#349]
This sentence returns no errors:

    "A person should get their own job."

Clearly, we have conflicting pronouns ... singular vs plural.

Please advise.
[Grammar.com](http://www.grammar.com)

**Comment by danielnaber** [comment]
I don't see why that sentence should be considered incorrect. See https://en.wikipedia.org/wiki/Singular_they

**Comment by stands4** [comment]
Ah! Sorry, taking it back... thanks for the super-fast response!
