### ISSUE TITLE
[en] MD_BASEFORM[2] gives out wrong messages

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#3492]
![grafik](https://user-images.githubusercontent.com/67792088/91451905-3cb15780-e87e-11ea-897e-b2728518d2df.png)

This happens for errors like "She can does that now." Or "He won't says a word."

The message will look like this: "The modal verb ‘ca’ requires the verb’s base form." and The modal verb ‘wo’ requires the verb’s base form.

**Comment by udomai** [comment]
I would change this line

<message>The modal verb '<match no="1" regexp_match="n$" regexp_replace="" />' requires the verb's base form.</message>

to this:

<message>The modal verb '<match no="1" postag="VB" />' requires the verb's base form.</message>

**Comment by tiff** [comment]
@udomai @udomai I suggest changing it to:
```
<message>The modal verb '<match no="1" regexp_match="dn$" regexp_replace="d" />' requires the verb's base form.</message>
```

shouldn → should
wouldn → would
will → will
can → can
won → won (not ideal, but better than before)

**Comment by tiff** [comment]
Can be closed now
