### ISSUE TITLE
[de] Browser-Add-on: Regel-Loop bei "Home-Office"

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#3493]
Das Browser-Add-on moniert ab der ersten Okkurrenz den uneinheitlichen Gebrauch von _Home-Office_ und dasselbe Wort wird vorgeschlagen:

![grafik](https://user-images.githubusercontent.com/67792088/91533209-c9582600-e90f-11ea-95a8-a50b9cfe6aac.png)

**Comment by tiff** [comment]
Das Problem ist nicht nur im Browser-Add-on. Auch auf languagetool.org

**Comment by tiff** [comment]
@danielnaber das Problem tritt auf, weil die Base-Form von "Home-Office" nicht nur "Home-Office", sondern auch "Homeoffice" ist. Ich würde vorschlagen nicht nur die Tags zu korrigieren, sondern auch diesen Fall im Code abfangen. Ich gehe mal davon aus, dass das bei anderen Wörtern auch passiert.

**Comment by tiff** [comment]
POS korrigiert via https://github.com/languagetool-org/languagetool/commit/51b2c543bc31b6d1a5ca9bb53b06d4963853eb5a

**Comment by udomai** [comment]
> Das Problem ist nicht nur im Browser-Add-on. Auch auf languagetool.org


Seltsam, heute Morgen konnte ich das Problem auf LT.org nicht reproduzieren, jetzt aber schon...
