### ISSUE TITLE
[de] Ofengasse is not recognized

### ISSUE THREAD

**Issue by ismail** [languagetool-org/languagetool#3497]
![Capture](https://user-images.githubusercontent.com/4255/91635605-1e706680-e9fa-11ea-95cc-2a844ff1fc5b.PNG)

https://www.meinestadt.de/schwaebisch-gmuend/stadtplan/strasse/ofengasse is a valid street :)

**Comment by Dallun511** [comment]
Wurde eingetragen und ist morgen online.
