### ISSUE TITLE
Error message in LibreOffice

### ISSUE THREAD

**Issue by sojusnik** [languagetool-org/languagetool#3509]
I'm getting the following error message (RuntimeException/ExecutionException/IllegalArgumentException) in `LibreOffice Writer` (Version: 6.4.6.2) on `Ubuntu 20.04` with `openjdk-13-jre` (13.0.3+3-1ubuntu2 amd6):

![grafik](https://user-images.githubusercontent.com/1245718/91844676-2cbbbe00-ec58-11ea-8580-f864065ca941.png)

What's the best way to debug this, since the content of the document is confidential?

**Comment by sojusnik** [comment]
Updated to `openjdk-14-jre`, but it didn't help.

**Comment by danielnaber** [comment]
It's probably caused by some special characters (like soft hyphens) in the document. You could maybe shorten the document until you get the shorted document that still shows the errors and send that with confidential data removed.

**Comment by sojusnik** [comment]
I was able to pinpoint the problematic part!

If there is a new line after the first two sentences in the following document, then the error appears. You have to enable all rules for the Russian language, otherwise it won't work.

Get the document from [here](https://mega.nz/file/3k4zHTYJ#rCVh17PQjmxyal1GSzaGqFS1j0tOP22iUhBam83-iZw).

And this is the error message:
![grafik](https://user-images.githubusercontent.com/1245718/91881193-681eb280-ec81-11ea-8946-010b2d2d2fb0.png)

**Comment by yakovru** [comment]
I can't reproduce it on OpenOffice 4.1.7 with  Java 8.0_144 (Oracle) on Win 32 bit.

**Comment by yakovru** [comment]
This problem seems to be in ParagraphRepeatBeginningRule.java.

**Comment by FredKruse** [comment]
@yakovru: I solved the problem inside the ParagraphRepeatBeginningRule. So, you could try to activate the rule for ru again. I couldn't reproduce the error. Perhaps you could test it again.
