### ISSUE TITLE
[es] feedback from a user

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3513]
Only one out of 5 errors are detected in this text:

> La observación sería válida si Rusia hubiese desatendido el asunto de la pandemia, pero como no es así la crítica que haces está completamente fuera de lugar. De otra parte, Rusia tiene otros asuntos que atender, entre ellos el de la defensa nacional.

Original user message:
> El programa, sin duda alguna  es bueno, pero tiene  fallas en el proceso de detección de errores que merecen atención. Sometimos a prueba una oración con cinco errores provocados, de los cuales el programa solo captó uno. Ver imagen anexa.

**Comment by jaumeortola** [comment]
I don't see obvious errors in these sentences, a part from some doubtful punctuation marks. Do you have the "attached image"?

**Comment by tiff** [comment]
Ah sorry. Now I understand that he provided the correct sentence and the screenshot shows the incorrect sentence:

![3355676EEA0740FA9C351830003AC87D](https://user-images.githubusercontent.com/37363/91980320-55f74f80-ed27-11ea-8d9a-7a8b8a517ff2.png)

Screenshot is from SpellBoy.com (which uses the latest version of LanguageTool)

**Comment by jaumeortola** [comment]
Thanks. I copy the text here for reference: 
> La observación seria valida si Rusia hubiese desatendido el asunto de la pandemia, pero como no es asi la critica que haces esta completamente fuera de lugar. De otra parte, Rusia tiene otros asuntos que atender, entre ellos el de la defensa nacional. 

We have rules for all of these errors, but in these particular contexts they don't work (because of the risk of false positives). I will try to improve the rules. It will be difficult when there are two adjacent problems as in "seria valida / sería válida".

**Comment by udomai** [comment]
Oh yes, those are difficult... seria vs. sería, valida vs. válida... when in doubt, you could make the suggestions somewhat conditional: "If this is a form of the verb 'ser', it is written with an accent" or something like that. That wouldn't fix massive FPs, but any occasional FP would be less serious...

**Comment by tiff** [comment]
Great, thanks!
