### ISSUE TITLE
[en] False warning HAVE_PART_AGREEMENT 

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3516]
HAVE_PART_AGREEMENT suggests 'been':

> Layla wasn't an educated woman and all she had **was** her virtue.

**Comment by tiff** [comment]
@MikeUnwalla same happens with:
> Layla wasn't an educated woman and all **that** she had was her virtue.

> Layla wasn't an educated woman and all **the things** she had was her virtue.
