### ISSUE TITLE
[en] "thee"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3520]
I just made this misspelling "Thee cat".

LanguageTool didn't catch this mistake.

"thee" seems to be an archaic pronoun.
https://www.merriam-webster.com/dictionary/thee

Should we add it to "prohibit.txt" (words that we blacklisted) or write a simple rule?

One potential antipattern:
"Megan Thee Stallion" (currently very famous singer from the US)

@MikeUnwalla @udomai

**Comment by MikeUnwalla** [comment]
I prefer a rule. The word is used in the north of England.

Also, see https://www.lexico.com/definition/thee

**Comment by tiff** [comment]
So at least for AmE this rule could be very simple.

**Comment by tiff** [comment]
@udomai @MikeUnwalla I have created a simple rule exclusively for en-US, see:
https://github.com/languagetool-org/languagetool/commit/e1ee481ab1bc24cf6066415bd970860f9fd517e9

It's "temp_off" until regression test results and your feedback has been provided

**Comment by MikeUnwalla** [comment]
@tiff, the rule looks fine to me (but I agree with Udo's comment about the message).
