### ISSUE TITLE
[de] words in angle brackets are deleted in suggestions

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#3523]
Hi @jaumeortola,

Sebastian spotted the following issue in German:

_Updates zu veredelten Bäumen führen den Tag **<Baumporträt>.**_

The java rule COMMA_PARENTHESIS_WHITESPACE gives the suggestion to replace `<Baumporträt>.` with just `.` .

Can this be fixed quickly? If it would take a lot of time to fix, please disregard and close the issue, since it is a very niche error.

**Comment by udomai** [comment]
All right, I'll leave the ticket here so we can try and fix it at some point in the future for the add-on.

**Comment by tiff** [comment]
@udomai in fact that's only happening with the browser-add-on which should be a little smarter in handling words in brackets.

**Comment by tiff** [comment]
I fixed this. It will be available in the next version of our browser add-on
