### ISSUE TITLE
[nl] potential typos in names and messages

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3526]
Found by `LTMessageChecker`:

U **bedoeltvast** “echt”? Eggen is ploegen.
Het **werkword** diggen is erg zeldzaam.
Bedoelt u misschien “doorligt” (**ligwond** krijgen)? Of toch onderzoeken?
Berijdbaar=kan op **geredenworden**; bereidbaar=kan gemaakt worden (eten).
Wanneer u ‘onderbouwd’ **bedoet** herschrijf dan met ‘onderbouwd’,
**Sommgen** vinden dit geen standaardtaal;
Eeen **woor dmet** een underscore
(**leggeld** voor schip, extra betaling)
**Bedooelt** u misschien “precedent” (eerste geval)
Overigens wordt het gebruik van deze **vultekst** afgeraden.

**Comment by baarsrj** [comment]
Processed.
