### ISSUE TITLE
[en] False warnings MD_BASEFORM 

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3527]
MD_BASEFORM gives warnings for these sentences:

- [x] The Bible is clear that humans do not achieve greatness without having their sinful will **broken**. [Also false warning by PRP_PAST_PART]
- [ ] One's own will **overrides** any command.
- [x] What will **losing** the war mean to us?
- [ ] Unfortunately, this will **happened** to be wrong, because the legal team was careless.

(Not caused by the removal of disambiguation/WILL_MD in #3262.)

**Comment by tiff** [comment]
@MikeUnwalla 
> What will losing the war mean to us?

is probably caused because "mean" is not tagged as a verb.

**Comment by MikeUnwalla** [comment]
Also:

> I made sure he had his sinful evil nasty will **changed**! [Also in WILL_BASED_ON]
