### ISSUE TITLE
POS Tagger erzeugt fehlerhaftes Output für das Satzende

### ISSUE THREAD

**Issue by ozz-project** [languagetool-org/languagetool#353]
Der POS Tagger erzeugt fehlerhaftes Output für das Satzende. Dieser landet mitten in den Attributen. 

z.B. [&lt;/S>,O] ? Close Tag mitten in einem Attribut ?
Ich habe zwei Bespiele angehängt. Es ist immer die ganze Zeile des Originals angeben!
Original
*   Roveredo ai 26. Ottobre 1756._

output 
* &lt;S>Ottobre[Ottobre/null,O] 1756[1756/null,O].[./PKT,O]_[&lt;/S>,O]

(hier wird außerdem der Punkt am 26. fehlerhafterweise als Satzende interpretiert.)

Beispiel zwei
Original
* 
königl.

output 
* königl[königl/null,O].[&lt;/S>./PKT,O]  

schaut euch das mal an. Zum testen habe ich den Artikel verwendet.
https://www.gutenberg.org/ebooks/39189.txt.utf-8

**Comment by danielnaber** [comment]
Ja, das Satzende-Tag liegt immer auf dem letzten Wort des Satzes. `königl` ist jetzt verbessert, so dass es nicht mehr als Satzende erkannt wird. Das andere Beispiel ist Italienisch, oder?

**Comment by ozz-project** [comment]
das andere Beispiel ist italienisch. Es ist ein Zitat in dem Artikel (siehe Link an Ende es ersten Kommentars). Allerdings ist die Satzendeerkennung an dem Daten gescheitert. 26. Oktober.

**Comment by danielnaber** [comment]
In dem verlinkten Text finde ich jetzt kein `26. Ottobre`. Aber wenn der Text sonst deutsch ist, würden die italienischen Regeln ohnehin nicht greifen. Ich spreche zwar kein Italienisch, aber ich finde im Web nur Beispiele ohne Punkt, also `26 Ottobre`.

**Comment by ozz-project** [comment]
Danke, habe mich bein Link vertippt.
http://www.gutenberg.org/ebooks/30886
Kannst das als erledigt ansehen.
