### ISSUE TITLE
"Explain..." Link takes user to Unexpected Page

### ISSUE THREAD

**Issue by SethiPandi** [languagetool-org/languagetool#3533]
When using a term like "curriculum vitae", it prompts a warning that the terminology may not be clear to all readers.  
The "Explain..." link doesn't seem to take the user to a page that makes sense.

When clicking "Explain..." I am taken to:
https://www.lexico.com/definition/ad_hoc

![image](https://user-images.githubusercontent.com/22801583/92339221-4d9b6d80-f0b5-11ea-8b99-65f904b158a0.png)

I'm not entirely certain what the intended behavior was, but as the link is unexpected, and unhelpful, so I just assumed it was a bug.
Please let me know if this is incorrect.

**Comment by danielnaber** [comment]
Thanks, the link was probably a copy-and-paste error, it will be fixed soon.
