### ISSUE TITLE
Server crashes on hidden char

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#3534]
[LT-crash.zip](https://github.com/languagetool-org/languagetool/files/5181093/LT-crash.zip)

By the way, in Kubuntu, these hidden chars show up when pasted into the local interface of LT

**Comment by danielnaber** [comment]
I cannot reproduce it with that sentence alone, do you also have the rest of the text?

**Comment by dpelle** [comment]
Title says "on hidden char #3534".  Not sure what you mean by that characters.

The sentence in the zip file contains Unicode characters U+00AD (SOFT HYPHEN).
Maybe that's triggering the issue?

**Comment by baarsrj** [comment]
I guess it is, since when pasting the text in the zip into the LT stand alone, it showed some kind of hyphens.

**Comment by baarsrj** [comment]
Anyway, this is the complete sentence:
<sentcontent>Bij het ontwerpen van de presentaties van het VO liggen dezelfde ontwerptech­nis­che uit­gangspun­ten voor als bij het ontwerpen van het SO.</sentcontent>

**Comment by danielnaber** [comment]
> Anyway, this is the complete sentence:

But can you reproduce the problem when just checking that single sentence? I can't.

**Comment by jaumeortola** [comment]
This was the sentence (with several soft-hyphens): 
> Bij het ontwerpen van de presentaties van het VO liggen dezelfde ontwerptech­nis­che uit­gangspun­ten voor als bij het ontwerpen van het SO.

It is fixed now.
