### ISSUE TITLE
error in libreoffice 5.0.xx when updating extension from 3.1 to 3.2

### ISSUE THREAD

**Issue by rcrath** [languagetool-org/languagetool#354]
language tools 3.1, trying to update to 3.2

Libreoffice:
```
Version: 5.0.3.2
Build ID: 5.0.3.2 Arch Linux build-2
Locale: en-US (en_US.UTF-8)
```
steps to reproduce on libreoffice 

1. open extension manager in libreoffice and check for updates
2. choose to update language tools
3. get following error:

```
Error while installing extension LanguageTool. Open source language checker. The error message is: [jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.UnsupportedClassVersionError: org/languagetool/openoffice/Main : Unsupported major.minor version 52.0
java stack trace:
java.lang.UnsupportedClassVersionError: org/languagetool/openoffice/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:793)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:52)
	at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:380)

The extension will not be installed.
```

**Comment by arysin** [comment]
You need java8 to run LT 3.2

Regards,
Andriy

**Comment by rcrath** [comment]
Hi, @arysin and @danielnaber,   
Thnx.  running manjaro (arch-flavored) linux.  Had oracle jrt 8 installed, but not set as default.  changed default environment.  we'll see if that borks something that wants 7 :)  Language tools working now.  SHouldn't there be some kind of check of the environment in the installer?

**Comment by danielnaber** [comment]
The installer could check that, but that's an LibreOffice issue and then it would also need to know the minimum requirement for the JVM, which currently isn't stored anywhere in the LibreOffice-related files I think.

**Comment by iamit** [comment]
Have the same problem. Extension (v3.2) just downloaded and installed in libre office 4.4 (ubuntu 14.04). see http://extensions.openoffice.org/en/project/languagetool

this is my error:
(com.sun.star.uno.RuntimeException) { { Message = "[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.UnsupportedClassVersionError: org/languagetool/openoffice/Main : Unsupported major.minor version 52.0\X000ajava stack trace:\X000ajava.lang.UnsupportedClassVersionError: org/languagetool/openoffice/Main : Unsupported major.minor version 52.0\X000a\X0009at java.lang.ClassLoader.defineClass1(Native Method)\X000a\X0009at java.lang.ClassLoader.defineClass(ClassLoader.java:643)\X000a\X0009at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)\X000a\X0009at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)\X000a\X0009at java.net.URLClassLoader.access$000(URLClassLoader.java:73)\X000a\X0009at java.net.URLClassLoader$1.run(URLClassLoader.java:212)\X000a\X0009at java.security.AccessController.doPrivileged(Native Method)\X000a\X0009at java.net.URLClassLoader.findClass(URLClassLoader.java:205)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:323)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:316)\X000a\X0009at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:619)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:268)\X000a\X0009at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:52)\X000a\X0009at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:380)\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

**Comment by danielnaber** [comment]
@iamit you need to have Java 8 installed *and* it needs to be activated in LibreOffice (`Tools -> Options -> Advanced`).

**Comment by lepidopteralady1781** [comment]
I have Java 9 and get this error. Should I step down?

**Comment by danielnaber** [comment]
Java 9 doesn't seem to work without additional options, see http://forum.languagetool.org/t/lt-and-java-9/1588. If you cannot specify in LO, I guess the only fix for now is to go back to Java 8.
