### ISSUE TITLE
Duplication of words when correcting them in Medium

### ISSUE THREAD

**Issue by brunopulis** [languagetool-org/languagetool#3545]
**Description**
When trying to correct a grammatical error in Portuguese, it does not replace the word, but complements it by duplicating it.

**To reproduce**:

1. Enable the LanguageTool in Brazilian Portuguese;
2. Go to this [post](https://medium.com/@brunopulis/seis-maiores-erros-de-acessibilidade-digital-c708d313eb7d) on Medium;
3. Click in "Response", make a comment with this incorrect grammar **"O seu texto precisa de uma correcao gramatical."*;
4. The LanguageTool notifies you with the word "correcao" is wrong;
5. Fix the wrong word, the output should be "correção";
6. Check the output of the correction.

**Expected behavior**:
When applying the word correction it should be replaced the word and not duplicated them.

**Screenshots**

**Before correction is applied**

![before](https://user-images.githubusercontent.com/1204692/92593988-7750c200-f278-11ea-875b-ab0581e89264.png)

**After correction is applied**

![after](https://user-images.githubusercontent.com/1204692/92594046-98191780-f278-11ea-87eb-e99225ff5dae.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Browser [Chrome]
 - Version [85.0.4183.83]

 
**Details**:
This behavior occurs only on Medium

**Comment by apobrt** [comment]
It's me or you are using Grammarly, and not LanguageTool?

**Comment by tiff** [comment]
Thanks @brunopulis, I was able to reproduce the issue.

**Comment by brunopulis** [comment]
> It's me or you are using Grammarly, and not LanguageTool?

Hey @apobrt Yes I use Grammarly too, however, this inconsistency happened before using Grammarly

**Comment by tiff** [comment]
This will be fixed once we release the next version of our add-on (v3.1.14)
