### ISSUE TITLE
LanguageTool extension for LibreOffice: Installation error com.sun.star.uno.RuntimeException

### ISSUE THREAD

**Issue by Atalanttore** [languagetool-org/languagetool#355]
Hi,

the extension manager of LibreOffice 5.0.4.2 (on Ubuntu 15.10 x64 with Java 8u66) is reporting the following error message when trying to install LanguageTool-3.2.oxt.

(com.sun.star.uno.RuntimeException) { { Message = "[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.UnsupportedClassVersionError: org/languagetool/openoffice/Main : Unsupported major.minor version 52.0\X000ajava stack trace:\X000ajava.lang.UnsupportedClassVersionError: org/languagetool/openoffice/Main : Unsupported major.minor version 52.0\X000a\X0009at java.lang.ClassLoader.defineClass1(Native Method)\X000a\X0009at java.lang.ClassLoader.defineClass(ClassLoader.java:800)\X000a\X0009at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)\X000a\X0009at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)\X000a\X0009at java.net.URLClassLoader.access$100(URLClassLoader.java:71)\X000a\X0009at java.net.URLClassLoader$1.run(URLClassLoader.java:361)\X000a\X0009at java.net.URLClassLoader$1.run(URLClassLoader.java:355)\X000a\X0009at java.security.AccessController.doPrivileged(Native Method)\X000a\X0009at java.net.URLClassLoader.findClass(URLClassLoader.java:354)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:425)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:412)\X000a\X0009at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:793)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:358)\X000a\X0009at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:52)\X000a\X0009at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:380)\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

Regards,
Ettore

**Comment by danielnaber** [comment]
You don't just need Java 8 installed, it also needs to be configured in LibreOffice (`Tools -> Options -> Advanced`).

**Comment by Atalanttore** [comment]
Thanks. I've added this step to the german [LanguageTool installation tutorial](http://wiki.ubuntuusers.de/LanguageTool/#LanguageTool-als-Erweiterung) from Ubuntuusers.de.

Regards,
Ettore

**Comment by danielnaber** [comment]
Thanks. There are other places in that tutorial that still mention Java 7. It would be great if you could update those too.

**Comment by Atalanttore** [comment]
Done.

**Comment by danielnaber** [comment]
Sorry, one more thing: Web start probably shouldn't be mentioned anymore, we'll probably not update it anymore.

**Comment by Atalanttore** [comment]
Okay.

**Comment by ascavalcante80** [comment]
Thanks, @danielnaber ! I had the same problem, but I've just change the java version in (Tools -> Options -> Advanced) like you proposed and it worked.

**Comment by danger89** [comment]
Thanks, selecting 1.8 fixed it indeed.

**Comment by lacikae** [comment]
Trying the (Tools -> Options -> Advanced) crashes  Libreoffice 5.0.3.2. Any solution to set up manually?
