### ISSUE TITLE
Possible to ignore a regex?

### ISSUE THREAD

**Issue by gregeinfrank** [languagetool-org/languagetool#356]
I'd like to ignore some slang words such as "lol" or "haha" (or "hahahaha" etc).

Is it possible to set a rule to "whitelist" regular expressions (something like /^(ha)+$/) or add a regular expression to some ignore file?

Thanks!

**Comment by danielnaber** [comment]
You will need to edit the disambiguation rule for that. Here's an example for German: https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/disambiguation.xml#L306

**Comment by gregeinfrank** [comment]
Thanks @danielnaber ! Is there any documentation on how do write disambiguation files? I'm looking for another rule that only ignores spelling for certain words if it is not the first word in a sentence. Any help would be greatly appreciated! 

Greg

**Comment by danielnaber** [comment]
The syntax is documented at http://wiki.languagetool.org/developing-a-disambiguator#toc3

**Comment by gregeinfrank** [comment]
Thanks @danielnaber It's not clear to me though if there's a way to conditionally ignore spelling if it's not the first word in a sentence. Any insight on this?

**Comment by danielnaber** [comment]
Maybe using `<token negate_pos="yes" postag="SENT_START">wordtoignore</token>` or `<token/><token>wordtoignore</token>`, but I haven't tried it.

**Comment by gregeinfrank** [comment]
Thanks for the help @danielnaber !!

**Comment by gregeinfrank** [comment]
@danielnaber FYI Here's the code that ended up working:

```xml
    <rule name="Proper Case Ignore" id="IGNORE_PROPERCASE">
        <pattern case_sensitive="yes">
            <token negate_pos="yes" postag="SENT_START"/>
            <marker>
                <token regexp="yes">[A-Z]\w+</token>
            </marker>
        </pattern>
        <disambig action="ignore_spelling"/>
    </rule>
```
