### ISSUE TITLE
[en] translations give confusing suggestions

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3563]
> The tv is on

The correct suggestion is 4th in the list. I think this is a common mistake.
Also, why are "scriptwriter", "production company" and "be on" translations for "tv"?

I think we should not make any translation suggestions if the word is known to English (case-insensitive)

![Bildschirmfoto 2020-09-13 um 15 34 24](https://user-images.githubusercontent.com/37363/93019335-9fbd2100-f5d6-11ea-986d-8c21c77e0c3e.png)

**Comment by tiff** [comment]
Also, some strange results are created via:
> I checked the dvd
> Have you inserted the cd

**Comment by danielnaber** [comment]
This has now been solved by activating BERT resorting on premium.
