### ISSUE TITLE
[en-gb] "analyzed"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3564]
I'm a little confused:
I thought we are suggesting to change "ise" spellings to "ize" (Oxford), but for this word (and maybe others?) it is not the case:
>He analyzed it.

<img width="353" alt="Bildschirmfoto 2020-09-13 um 15 50 03" src="https://user-images.githubusercontent.com/37363/93019716-02afb780-f5d9-11ea-971b-4ccb7a5e4840.png">

At the same time we accept this, without giving a suggestion to change it:
> He analysed it.

Here's an example where the "ise" spelling is changed to "ize".

<img width="387" alt="Bildschirmfoto 2020-09-13 um 15 53 59" src="https://user-images.githubusercontent.com/37363/93019767-5ae6b980-f5d9-11ea-82b6-78b1812a7883.png">

@udomai @MikeUnwalla

**Comment by tiff** [comment]
Dumb idea: Is this maybe happening because "analyze" doesn't end with "ize" but with "yze"?

**Comment by MikeUnwalla** [comment]
@tiff, not all ~ize spellings are correct BrE. The correct BrE spelling is 'analyse' (https://www.lexico.com/definition/analyse).

Also, for BrE, 'catalyse' is correct (https://www.lexico.com/definition/catalyse).

The link in grammar rule OXFORD_SPELLING_ISE_VERBS gives basic information: https://www.lexico.com/grammar/ize-ise-or-yse

**Comment by marcoagpinto** [comment]
Most GB verbs accept -ize and -ise.

For "analyze" the dictionaries say it is US only.

This means that for GB it only accepts -ise for this verb.

**Comment by udomai** [comment]
> Dumb idea: Is this maybe happening because "analyze" doesn't end with "ize" but with "yze"?
> 
> Same seems to happen with other verbs ending in "yze":
> 
> ![Bildschirmfoto 2020-09-14 um 07 36 11](https://user-images.githubusercontent.com/37363/93047529-fec57900-f65c-11ea-8cd7-5eeaf9dbb586.png)

Exactly right. Oxford spelling is about verbs ending in -ize and is based in their (somewhat questionable) Greek etymology. This etymology is different for verbs ending in -ly[sz]e and, generally, in -y[sz]e. That is why Oxford spelling has "organize", but "analyse", "catalyse" etc.

Ergo: our suggestion is correct in regard to the Oxford standard.

**Comment by tiff** [comment]
Ok, I'm closing this. Thanks to everyone for enlightening me. I'm still irritated that Oxford prefers "yse" but not "ise".  :)
