### ISSUE TITLE
Browser add-on (tested with Firefox 80.0.1)

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#3567]
Hello!

I noticed lately that the browser add-on says there are errors, for example, while using Facebook.

But they don't get highlighted, except if I click in the circle.

It seems the underlining no longer fits the string gadgets of some sites.

**Comment by danielnaber** [comment]
Could you attach a screenshot? Which browser do you use?

**Comment by tiff** [comment]
Yes, screenshot, please. Also, is it the new or the old Facebook?

**Comment by marcoagpinto** [comment]
@danielnaber @tiff 

![browser_addon_bug_facebook_20200914](https://user-images.githubusercontent.com/5192600/93092515-6ef0f080-f697-11ea-8fd7-82f5576009c0.png)

**Comment by tiff** [comment]
@marcoagpinto thanks, I do see the underline in the same input (however, it's very thin). Does the underline appear once you add a new line (SHIFT + Enter)?

**Comment by marcoagpinto** [comment]
@tiff 

Yes, if I hit SIFT + Enter, we see the underline.
