### ISSUE TITLE
Portuguese converter for prereform < > postreform

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#357]
Could we have an option for this for the Portuguese language (probably other languages also have language agreements like us)?

The commercial tool FLIP for Microsoft Office:
http://priberam.pt/Produtos/FLiP.aspx
In the bottom of the page they say:
"No site do FLiP estão disponíveis gratuitamente versões on-line de algumas das ferramentas incluídas nos produtos acima referidos: auxiliares de tradução, conjugador de verbos, conversor para o Acordo Ortográfico e corrector ortográfico e sintáctico."

"On the site of FLiP are available for free online versions of some of the tools included in the above mentioned products: translation aids, conjugating verbs, converter for Spelling Agreement and speller and syntactic."

**Comment by danielnaber** [comment]
I'm not sure why this would be needed, we already have the `--apply` parameter, see http://wiki.languagetool.org/command-line-options
