### ISSUE TITLE
[pt] ''Olá'' tem acento…

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3570]
User feedback:

> ''Olá'' tem acento…

![Bildschirmfoto von 2020-09-14 19-05-18](https://user-images.githubusercontent.com/857004/93116211-42e86600-f6bd-11ea-95fc-1da37d872893.png)

**Comment by marcoagpinto** [comment]
@danielnaber 

https://dicionario.priberam.org/ola

"ola" is also a Portuguese word.

Maybe I should try to create a rule for it.

@jaumeortola Any guiding tips?

Thanks!

**Comment by jaumeortola** [comment]
You can write a rule that recommends "olá" at the start of a sentence with some exceptions if necessary, and in other contexts like "dizer olá".

**Comment by marcoagpinto** [comment]
Thank you, Jaume, I will create the rule tomorrow morning.

**Comment by marcoagpinto** [comment]
@danielnaber @jaumeortola 

Done!

https://github.com/languagetool-org/languagetool/commit/d92ada3dc39178275fe59a625f37c35a04d94430
