### ISSUE TITLE
[DE][LibreOffice] Fehlalarm "gut zu sehen"

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#3575]
Moin liebes LanguageTool-Team

Das Foto wurde seitlich von Leandros Bettseite geschossen, sodass alle drei Personen auf dem Foto halbwegs **gut zu sehen** waren.
LT: ![grafik](https://user-images.githubusercontent.com/40240507/93266922-24f92f00-f7ab-11ea-9456-305a834f0761.png)

Laut [Duden](https://www.duden.de/rechtschreibung/gut#bedeutungen) wird es getrennt geschrieben. Laut dem LanguageTool in LibreOffice und ich wiederhole nur in LibreOffice soll es zusammengeschrieben werden.

Grüße Dallun511

**Comment by danielnaber** [comment]
> Laut dem LanguageTool in LibreOffice und ich wiederhole nur in LibreOffice soll es zusammengeschrieben werden.

Bist du sicher, dass du die gleiche Version vergleichst? D.h. welche Version nutzt du in LibreOffice, und welche außerhalb von LibreOffice?

**Comment by Dallun511** [comment]
Der Fehler kam bei LT-Version LanguageTool-20200908-snapshot.oxt. Verglichen mit der LT-Version auf der Homepage, wie immer eigentlich, weil diese die aktuellste ist.

![grafik](https://user-images.githubusercontent.com/40240507/93361887-a69d9b00-f845-11ea-9c7a-d6d0c8e1704d.png)
Hier war die aktuellste Version im Einsatz. LanguageTool-20200915-snapshot

Komischerweise kommt bei diesem Satz zu keinen Fehlalarm:
Violetta war auf jedem Bild halbwegs **gut zu sehen**.

Hier der Text in LO:
![grafik](https://user-images.githubusercontent.com/40240507/93362195-fd0ad980-f845-11ea-80d7-776df0efa4e4.png)

**Comment by FredKruse** [comment]
Auch für mich ist dieser Fehler nicht nachzuvollziehen. Der Fehler erklärt sich nur dadurch, dass in irgendeinem deiner Wörterbücher "gutsehen" als korrektes Wort abgespeichert ist. Bitte überprüfe das einmal. Im Standardwörterbuch ist dieses (falsch geschriebene) Wort nicht enthalten (Es geht um das kleingeschriebene Wort. Das Wort "Gutsehen" (Guts-ehen) gibt es als Substantiv tatsächlich). 
Zum Hintergrund:
Die Funktion untersucht (unter anderem), ob ein zusammengesetztes Wort aus dem Verb hinter dem "zu" und einem Zusatz vor dem "zu" im Wörterbuch existiert. Nur dann wird diese Meldung angezeigt.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/94361866-ae680580-00b7-11eb-9b57-852837c80ab7.png)
"gutzusehen" ist falsch und das Wörterbuch schlägt sofort an, wenn ich diesen Vorschlag akzeptiere. Bevor ich ein Wort bei mir eintrage, überprüfe ich dieses und hier war schnell abgeklärt, dass es falsch ist.

Wäre das Wort fehlerhaft als richtig markiert wurden, hätte ich es in die verbortenen Wörter eingetragen, wodurch das Wörterbuch wiederum gesagt hätte, dass es falsch ist.

Ich muss zugeben, dass es bei gutzusehen nicht einfach herzustellen ist.

In LibreOffice:
Dallun sagte: „Das Training hat leider voran, denn wir müssen Erfahrungen sammeln, um irgendwann bereit zu sein, um uns diesem Kidnappernetzwerk stellen zu können.“

Violetta war auf jedem Bild halbwegs gut zu sehen. Sie lag auf einem verrosteten Bett und war mit Handschellen an den Händen und Füßen an die jeweiligen Bettpfosten gekettet. Mit zusätzlichen Ketten und Seilen wurde ihre Oberkörper und ihre Unter- und Oberarme sowie Unter- und Oberschenkel an die Matratze fixiert und ihre Kleidung lag zerstreut in dem alten maroden Keller. Violetta trug nur eine dunkelblaue Panty und einen schwarzen BH. Leandro saß offenbar mit ein wenig Abstand vom Bett auf einem Klappstuhl und hatte den besten Blick zum Bett. Ein Mitglied stand neben dem Bett auf der linken Bettseite, während Leandro mit Anstand von der rechten Bettseite saß. Die Fotos wurden seitlich von Leandros Sitzposition geschossen, sodass alle drei Personen auf dem Foto halbwegs gut zu sehen waren.

Der Text sollte ausreichen, um den Fehlalarm auszulösen. Zumindest bei mir reicht das voll aus.

![grafik](https://user-images.githubusercontent.com/40240507/94361960-46fe8580-00b8-11eb-9d9a-bdf4d8842f87.png)

**Comment by Dallun511** [comment]
Was ich ebenfalls ausschließen kann, sind meine Wörterbücher. Ich habe mal alle deaktiviert und der Fehlalarm bleibt bei mir erhalten.

![grafik](https://user-images.githubusercontent.com/40240507/94362031-c724eb00-00b8-11eb-83eb-df4347b7d38e.png)

**Comment by Dallun511** [comment]
@FredKruse #3411 der gehört ebenfalls dazu und ist mehrere Monate alt.

**Comment by FredKruse** [comment]
Du hast recht, die drei Fehler sind alle auf die gleiche Regel zurückzuführen und gehören deshalb zusammen.
Die Regel prüft nicht den erweiterten Infinitiv, also z.B. 'aufzustehen', sondern das dazugehörige zusammengesetzte Verb 'aufstehen'. Nur, wenn das im Wörterbuch existiert, schlägt die Regel an. (Das habe ich so gemacht, weil in einigen Fällen der zugehörige zusammengesetzte Infinitiv fälschlicherweise im Wörterbuch fehlt.)
Bitte lade folgende Zeile in ein LO-Dokument:
**Worte prüfen: bereitsein, gutsehen, totsein.**
Alle drei Worte müssen rot unterstrichen sein (sind sie bei mir und auch in der LT-Server-Version), ansonsten arbeitest du mit einem falschen, wahrscheinlich veralteten Wörterbuch. Die LO-Erweiterung von LT arbeitet im Gegensatz zur Server-Version mit dem in LO installierten Wörterbuch (einschließlich der Benutzerwörterbücher). Das ist der einzige Unterschied.
Du solltest das folgende Wörterbuch installiert haben:
https://extensions.libreoffice.org/en/extensions/show/german-de-de-frami-dictionaries

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/94455331-38e15f80-01b3-11eb-88a8-b30d7dae15a4.png)
Ich habe das aktuellste Wörterbuch, dass es überhaupt gibt. Ich stehe mit den Entwickerln des Wörterbuches in Kontakt und das nicht  erst seit gestern, weil meine Benutzerwörterbücher immer voller und voller werden und ein Update ein wahrer Segen wäre. Leider kann mir bir heut kein grobes Datum genannt werden, wenn ein Update erscheinen könnte.

zu den Wörtern kann ich nur sagen, dass sie als falsch markiert werden.
![grafik](https://user-images.githubusercontent.com/40240507/94455681-9d9cba00-01b3-11eb-84af-2692ebdcfe38.png)
Hier der Beweis

**Comment by Dallun511** [comment]
Ich habe es noch einmal ohne meine Benutzerwörterbücher ausprobiert.
Das Ergebnis bleib unverändert, weswegen wir immer noch auf der Fehlersuche sind.

@FredKruse Wenn du noch weitere Ideen hast, die ich ausprobieren kann, gebe mir Bescheid, denn es ist in meinem Interesse, dass dieser nervig Bug endlich behoben wird, weil mich nur noch nervt.

**Comment by FredKruse** [comment]
Leider kann ich den Bug noch immer nicht nachvollziehen. Ich habe eine kleine Änderung an der Regel durchgeführt, die morgen zur Verfügung steht. Allerdings sollte der geänderte Fall gar nicht auftreten, weswegen ich wenig Hoffnung habe, dass die Änderung das Problem löst. Bitte probiere es nach dem nächsten Update morgen einmal aus.
Wenn das nicht hilft, bin ich mit meinem Latein am Ende. Dann kannst du die Regel nur noch deaktivieren.

**Comment by Dallun511** [comment]
Zwei Tage gewartet und die aktuellste Version installiert.
![grafik](https://user-images.githubusercontent.com/40240507/94794404-18481e00-03dc-11eb-9a0e-2d589a47ef27.png)

Fehlalarme immer noch vorhanden,

**Comment by FredKruse** [comment]
Könntest du einen Screenshot von den LO-Einstellungen unter Optionen/Spracheinstellungen/Linguistik posten?
Bei meinen Tests unter Linux und Windows gibt es mit exakt dem gleichen Text keinen Fehlalarm.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/94943064-74dc3380-04d7-11eb-8f9a-36bbea4780d6.png)
Ich kann nicht nur, sondern ich mache es auch.

**Comment by FredKruse** [comment]
Das war eine harte Nuss, aber das Problem ist gelöst. Bitte teste den nächsten Snapshot ab morgen und schließe die issues, wenn die Fehlalarme nicht mehr auftauchen.

**Comment by Dallun511** [comment]
Ich werde gespannt mir diesen Snasphot ansehen.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/95031494-8e87a180-06b6-11eb-8d03-e164aa5c8ff0.png)
Die Mission ist geglückt. Keine Fehlalarme mehr. Wo lag denn das Problem? Das würde mich interessieren.
