### ISSUE TITLE
[de] false alarm DASS_STATT_DAS_RELATIVPRONOMEN

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3576]
>  Der Bedeutungsverlust nach dem Ende des Zweiten Weltkrieges hat für die Altertumswissenschaften allerdings immerhin den Vorteil, dass nun ein unverstellterer, neutraler Blick auf die Antike leichter möglich ist.

via https://internal1.languagetool.org/regression-tests/via-http/2020-09-16/de-DE/result_grammar_DASS_STATT_DAS_RELATIVPRONOMEN[1].html

**Comment by udomai** [comment]
Das ist ja komisch! Kann es sein, dass es ein Bug im Diff ist? Ich kann den Fehler weder mit der OS noch mit Premium reproduzieren...

**Comment by tiff** [comment]
Ich glaube das kommt, weil @danielnaber die Änderungen (die dazu geführt haben) schon zurückgerollt hat.

**Comment by danielnaber** [comment]
> Ich glaube das kommt, weil @danielnaber die Änderungen (die dazu geführt haben) schon zurückgerollt hat.

Ja, kann ich bestätigen.
