### ISSUE TITLE
[de] false alarm GEKOMMEN_KONNTE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3577]
> Während das Ministerium mauert und viele der offenen Fragen unbeantwortet lässt, beruft sich die Rentenversicherung selbst auf die Schweigepflicht in einem laufenden Verfahren.

via https://internal1.languagetool.org/regression-tests/via-http/2020-09-16/de-DE/result_grammar_GEKOMMEN_KONNTE[1].html

@f-knorr probably related to your changes

**Comment by f-knorr** [comment]
@tiff : I do not see a problem here. Could you please elaborate: what is the problem here.

**Comment by danielnaber** [comment]
@f-knorr Hier war der Vorschlag mit dem Fehlertext identisch (und die Fehler wohl auch Fehlalarme), aber das scheint sich gelöst zu haben.
