### ISSUE TITLE
[pt] "bit" and "bits" don't appear as foreign words

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#3578]
Hello!

I have "bits?" in the grammar.xml:
` <!ENTITY barbarismos3 "aliens?|applets?|backbones?|baconburgers?|bits?|bluetooth|bogie|bookmarks?|bullying|burnouts?|cameraman|carjacking|crackers?|cracking|cyberbullying|czar|czares|demand|e[-]bullying|e[-]commerce|e[-]learning|e[-]manuals?|e[-]newsletters?|e[-]readers?|exabits?|exabytes?|fair[-]play|faxes|feeders?|flyers?|forward|führers?|gigabits?|gigabytes?|homebanking|homepages?|hosts?|idem|jiu[-]jitsu|kilobits?|kilobytes?|know[-]how|KO|lob|loops?|marketeers?|maydays?|megabits?|megabytes?|milkshakes?|newsgroups?|nicknames?|offside|overflows?|pens?|petabits?|petabytes?|roadmaps?|royalty|royalties|scams?|scammers?|screenshots?|shell|smartphones?|sockets?|stalking|strings?|tablets?|tags?|takeovers?|terabits?|terabytes?|toolkits?|tracking|tweeters?|Unicode|Usenet|warm[-]up|webmasters?|webpages?|wireless|woofers?|yes[-]man|yottabits?|yottabytes?|zettabits?|zettabytes?">`

But LT doesn't suggest to use italic nor quotes.

Does anyone know what is wrong with it?

Thanks!

**Comment by jaumeortola** [comment]
There is an exception to the rule BARBARISMS:
`<exception regexp='yes'>(?:bit|kilo(?:bit|byte|volt|watt)|giga(?:byte|watt)|quilohertz|out)s?|versus</exception></token><!-- XXX remove after regenerating regexp -->`

**Comment by marcoagpinto** [comment]
Ohhhhh...

https://dicionario.priberam.org/bit

It is a foreign word.

I will fix it soon.

Thank you!

**Comment by jaumeortola** [comment]
But does "bit" really need to be in italics or between quotes? To me, it seems picky or even wrong.

**Comment by marcoagpinto** [comment]
ahhhh... okay... I won't change it.

I was adding it as a foreign word after finding it in the Priberam dictionary months ago.
