### ISSUE TITLE
Rule DE UPPERCASE_SENTENCE_START and …

### ISSUE THREAD

**Issue by Xaratas** [languagetool-org/languagetool#358]
Languagetool Version: 3.2

Uppercase Sentence start is to hard on an ellipsis. The ellipsis can show a break in the speaking action, which does not lead to a new Sentence.
https://de.wikipedia.org/wiki/Auslassungspunkte#Anzeige_von_Pausen_und_Unterbrechungen

Surrounding this „new sentence“ some other rules can see a violation. Like DE_AGREEMENT

```
Rule ID: UPPERCASE_SENTENCE_START
Message: Dieser Satz fängt nicht mit einem großgeschriebenen Wort an
Suggestion: So
...n Besitzer. Zahua ist ein freier Mann. Nun … so frei, wie wir alle eben sind.“ 
                                                ^^
```

**Comment by f-knorr** [comment]
I can no longer reproduce the reported error. Can we close it?
