### ISSUE TITLE
[en] inflected form not suggested

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3588]
> The movies

![Bildschirmfoto 2020-09-17 um 16 15 56](https://user-images.githubusercontent.com/37363/93483527-30f70500-f901-11ea-9a6b-b5f531697ea8.png)

It suggests "film", expected would be "films"

cc @danielnaber

**Comment by danielnaber** [comment]
Besides the bug, does the pair movie/film make sense? Google Books has not much difference. What do you think, @MikeUnwalla ?

![Bildschirmfoto von 2020-09-18 16-38-09](https://user-images.githubusercontent.com/857004/93610493-6bc66f00-f9cd-11ea-8dc6-e32f8578f6bc.png)

**Comment by danielnaber** [comment]
Should be fixed, although there's another issue: #3599

**Comment by MikeUnwalla** [comment]
To my ears, 'movie' sounds American. Nobody I know would say, "Shall we watch a movie?"
