### ISSUE TITLE
[en] incorrect tagging NN_are_NNS

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3589]
> They class people.

"class" is only NNS, which is confusing because it originally doesn't have this tag.

![Bildschirmfoto 2020-09-17 um 19 48 30](https://user-images.githubusercontent.com/37363/93508542-c8b71c00-f91e-11ea-91b4-ad677f0d942d.png)

**Comment by MikeUnwalla** [comment]
Death the to running-dog lackeys of semantic imperialism!

I propose that we remove the rule. Whether we say "The committee are" or "The committee is" depends on the locale (https://www.lexico.com/grammar/types-of-noun).

**Comment by tiff** [comment]
Ok, I will do

**Comment by MikeUnwalla** [comment]
I'm having second thoughts about my suggestion to remove the rule. In the context of "the committee are", the NNS analysis is correct.
