### ISSUE TITLE
English: New rule for redundancy: Sufficient enough

### ISSUE THREAD

**Issue by Siedlerchr** [languagetool-org/languagetool#359]
Hi,
I created a rule to mark "sufficient enough" as redundant:
Sufficient and enough are synonyms, but it is used very often together, e.g. "not sufficient enough"

Src: 
http://english.stackexchange.com/questions/139595/can-i-say-sufficient-enough-here
http://www.bbc.co.uk/worldservice/learningenglish/grammar/learnit/learnitv320.shtml

```xml
<!-- English rule, 2016-01-14 -->
<rule id="SUFFICIENTENOUGHREDUNDANCY" name="SufficientEnoughRedundancy">
 <pattern>
  <marker>
  <token>sufficient</token>
  <token>enough</token>
  </marker>
 </pattern>
 <message>Sufficient enough is redundant. Use only <suggestion>sufficient</suggestion></message>
 <url>http://english.stackexchange.com/questions/139595/can-i-say-sufficient-enough-here</url>
 <short>Redundancy detected</short>
 <example correction=''>The money is <marker>sufficient enough</marker> to buy the pullover.</example>
 <example>The money is sufficient to buy the pullover.</example>
</rule>
```

**Comment by danielnaber** [comment]
Thanks! I've just added this rule. It will become part of the next LT release and it will be live on https://languagetool.org in a few hours. More contributions are very welcome.
