### ISSUE TITLE
Плагин версии 3.2 для LibreOffice крашится

### ISSUE THREAD

**Issue by InterVi** [languagetool-org/languagetool#360]
версия либры: 5.0.4.2
id сборки: 00m0(Build:2)

краш:
(com.sun.star.uno.RuntimeException) { { Message = "[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.UnsupportedClassVersionError: org/languagetool/openoffice/Main : Unsupported major.minor version 52.0\X000ajava stack trace:\X000ajava.lang.UnsupportedClassVersionError: org/languagetool/openoffice/Main : Unsupported major.minor version 52.0\X000a\X0009at java.lang.ClassLoader.defineClass1(Native Method)\X000a\X0009at java.lang.ClassLoader.defineClass(ClassLoader.java:800)\X000a\X0009at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)\X000a\X0009at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)\X000a\X0009at java.net.URLClassLoader.access$100(URLClassLoader.java:71)\X000a\X0009at java.net.URLClassLoader$1.run(URLClassLoader.java:361)\X000a\X0009at java.net.URLClassLoader$1.run(URLClassLoader.java:355)\X000a\X0009at java.security.AccessController.doPrivileged(Native Method)\X000a\X0009at java.net.URLClassLoader.findClass(URLClassLoader.java:354)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:425)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:412)\X000a\X0009at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:793)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:358)\X000a\X0009at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:52)\X000a\X0009at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:380)\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

версия 3.1 встала нормально

**Comment by arysin** [comment]
LT 3.2 requires java8

**Comment by InterVi** [comment]
root@Hard:/home/alex# java -version
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by yakovru** [comment]
LibreOffice имеет разрядность 64 бита?
В настройках LibreOffice выбрана нужная версия Java?
Для LanguageTool 3.2 требуется как минимум Java 8.
Для LanguageTool 3.1 работала и с Java 7 и с Java 8.


>Четверг, 14 января 2016, 3:36 -08:00 от InterVi <notifications@github.com>:
>
>версия либры: 5042
>id сборки: 00m0(Build:2)
>краш:
>(comsunstarunoRuntimeException) { { Message = "[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: javalangUnsupportedClassVersionError: org/languagetool/openoffice/Main : Unsupported majorminor version 520\X000ajava stack trace:\X000ajavalangUnsupportedClassVersionError: org/languagetool/openoffice/Main : Unsupported majorminor version 520\X000a\X0009at javalangClassLoaderdefineClass1(Native Method)\X000a\X0009at javalangClassLoaderdefineClass(ClassLoaderjava:800)\X000a\X0009at javasecuritySecureClassLoaderdefineClass(SecureClassLoaderjava:142)\X000a\X0009at javanetURLClassLoaderdefineClass(URLClassLoaderjava:449)\X000a\X0009at javanetURLClassLoaderaccess$100(URLClassLoaderjava:71)\X000a\X0009at javanetURLClassLoader$1run(URLClassLoaderjava:361)\X000a\X0009at javanetURLClassLoader$1run(URLClassLoaderjava:355)\X000a\X0009at javasecurityAccessControllerdoPrivileged(Native Method)\X000a\X0009at javanetURLClassLoaderfindClass(URLClassLoaderjava:354)\X000a\X0009at javalangClassLoaderloadClass(ClassLoaderjava:425)\X000a\X0009at javalangClassLoaderloadClass(ClassLoaderjava:412)\X000a\X0009at javanetFactoryURLClassLoaderloadClass(URLClassLoaderjava:793)\X000a\X0009at javalangClassLoaderloadClass(ClassLoaderjava:358)\X000a\X0009at comsunstarcomploaderRegistrationClassFinderfind(RegistrationClassFinderjava:52)\X000a\X0009at comsunstarcomploaderJavaLoaderwriteRegistryInfo(JavaLoaderjava:380)\X000a", Context = (comsunstarunoXInterface)  @0 } }
>версия 31 встала нормально
>—
>Reply to this email directly or  view it on GitHub .


-- 

Yakov Reztsov

**Comment by InterVi** [comment]
не знал про настройки, выбрал там 8 джаву и теперь все работает :)

**Comment by hellboy81** [comment]
ППКС
