### ISSUE TITLE
[en] should we accept "mt?"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3602]
> Hi, mt name is Carol Miller and I ...

We don't detect "mt" as an error. It seems rare (at least when lowercase), should we really accept it?

**Comment by MikeUnwalla** [comment]
Webster (www.merriam-webster.com/dictionary/mt) accepts 'mt' as an abbreviation for 'mountain'. 

American Heritage (https://ahdictionary.com/word/search.html?q=mt) uses 'Mt' (same as Lexico).

www.collinsdictionary.com/dictionary/english/mt says 'mt' is an American abbreviation for 'metric ton'.

I'll remove the spelling for lower case 'mt'. If necessary, we can make a disambiguation rule that ignores spelling for `digit + mt`.
