### ISSUE TITLE
"Nao" doesn't have a good suggestion for pt-BR

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3608]
"Nao" is not corrected properly to "Não" in pt-BR, but it is in pt-PT. Would an update of the hunspell dictionary maybe help? @jaumeortola, what do you think?

**Comment by jaumeortola** [comment]
I see. There are fewer lines MAP in pt_BR.aff. Adding  `MAP nN` fixes the problem.

**Comment by jaumeortola** [comment]
Added here: https://github.com/languagetool-org/languagetool/commit/752e12e99925173a372d281f4d5c5cb1d5cb5382
