### ISSUE TITLE
feedback: 'idiocy' can be used as a mass noun

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3618]
>  In English, LanguageTool marks 'plenty of idiocy' and suggests 'plenty of idiocies'. At least for me, 'plenty of idiocy' is entirely grammatical, as 'idiocy' can also be used as a mass noun.

**Comment by MikeUnwalla** [comment]
Longman agrees: https://www.ldoceonline.com/dictionary/idiocy

I'll add the POS after the LT release.
