### ISSUE TITLE
[en] No error detected in "It's perfectly possible calculate with..."

### ISSUE THREAD

**Issue by hmslima** [languagetool-org/languagetool#3622]
LT doesn't detect any error in the sentence below:

> It's perfectly possible calculate with Roman numerals

But it should be

> It's perfectly possible **to** calculate with Roman numerals

**Comment by tiff** [comment]
I have added a rule (`MISSING_TO_BETWEEN_BE_AND_VB`) for this. The rule will be active from tomorrow on.
