### ISSUE TITLE
parent in pom.xml , sonatype oss parent is deprectated 

### ISSUE THREAD

**Issue by nicenemo** [languagetool-org/languagetool#3626]
I tried to build Language tool from sources with a personal version.

I noticed that the parent in the _pom.xml_ was deprecated.
According to [Sonatype](https://github.com/sonatype/oss-parents) it is no longer supported.
```
  <parent>
    <groupId>org.sonatype.oss</groupId>
    <artifactId>oss-parent</artifactId>
    <version>7</version>
  </parent>
```

**Comment by danielnaber** [comment]
Thanks for letting us know, but removing this didn't work, I couldn't close the artifact anymore in the staging repo on oss.sonatype.org (I got `Event: 1 rule failed: Central Sync Requirement` and `com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed`). I've made the 5.2 release now with the parent again.
