### ISSUE TITLE
What is this trying to tell me? I know it means since.

### ISSUE THREAD

**Issue by un71** [languagetool-org/languagetool#3632]
![Capture](https://user-images.githubusercontent.com/58738226/94508368-db173c80-01df-11eb-81e5-47efe027c09b.PNG)

**Comment by danielnaber** [comment]
We have some false friend warnings in the system for English native speakers writing a French text, but this pair doesn't seem to make sense. I have removed it, the fix will probably be online tomorrow (until then, you can just "turn off rule everywhere").
