### ISSUE TITLE
split support for Dutch into nl-NL and nl-BE

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3634]
Could be done like this: https://gist.github.com/danielnaber/ed4d423deaf21338f97ff547e7dabbee

However, it has at least the side effect that Dutch is now detected as `nl-NL` in the JSON instead of just `nl`, so this would require migration for API users.

**Comment by baarsrj** [comment]
maybe it could be worked around by:
a) using nl_NL internally when nl is used (largest number of language users)
b) choosing NL or BE by country calling
