### ISSUE TITLE
[de] “Raussuchen”: Suggested replacement is same as original word

### ISSUE THREAD

**Issue by NicoWeio** [languagetool-org/languagetool#3636]
As can be seen [here](https://languagetool.org/?text=Raussuchen) and in the Chrome extension, LanguageTool suggests replacing the colloquial word “Raussuchen” with itself. 
I have very little knowledge of LanguageTool's inner workings, so I don't know how to fix it. Maybe there should be a check for every suggestion in general, since I can't imagine any case where replacing a token with strictly itself would be useful.

**Comment by danielnaber** [comment]
Thanks, will be fixed with the next update.
