### ISSUE TITLE
[en] need a new rule (error not found by the right rule)

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#3646]
In sentences like:

_It's possible do it_

The IT_IS_2 rule is triggered. That's because some adjectives (e.g. _good_ and _possible_ are tagged also as NN). I've fixed that, these cases won't trigger IT_IS_2 any longer.

But this made me notice that we don't catch another kind of error:

_It's **possible do** it_ --> _**possible, do**_ or _**possible to do**_

Can you write a rule that catches errors like this? More examples:

_It's not recommendable go there at night.

I don't think it is very expensive book a flight._

**Comment by tiff** [comment]
@MikeUnwalla @udo the rule for this has already being created by me (it will be activated from tomorrow on). See https://github.com/languagetool-org/languagetool/issues/3622

**Comment by udomai** [comment]
@tiff Cool, thank you :)
