### ISSUE TITLE
rule with <regexp> not last causes duplicate ID problem during validation

### ISSUE THREAD

**Issue by milekpl** [languagetool-org/languagetool#365]
The rule that has no ID but contains `<regexp>` within a rulegroup causes validation to fail with the message that ID has already been used.

To replicate:

1. Find DATA_NIEMOZLIWA rulegroup in Polish grammar file.
2. Move the first rule to the end of the rulegroup.

**Comment by danielnaber** [comment]
I don't even understand the duplicate id check code anymore, but I think it should be fixed.
