### ISSUE TITLE
[en] An error has occured in LanguageTools 5.1.1 (2020_09_29 14.39)

### ISSUE THREAD

**Issue by Techguyprivate** [languagetool-org/languagetool#3652]
I am attaching a screenshot of the error. 

The error appears in windows 10 1903, ubuntu 18.04.5 and Linuxmint 19.3.
Libreoffice version that I have tested. Libreoffice 7.0.1.2, Libreoffice 7.0.2.2(Beta, pre relase version).

The Java version is latest. In windows it is Java 8 update 261 and in Linux the java version is 11.07.

![Screenshot from 2020-10-02 21-11-03](https://user-images.githubusercontent.com/43615747/94942407-e3c78580-04f3-11eb-841d-3385179ad5a4.png)
![2020-10-02 15_09_32-Untitled 1 - LibreOffice Writer](https://user-images.githubusercontent.com/43615747/94942434-ea55fd00-04f3-11eb-9219-02af56fef99c.png)

**Comment by danielnaber** [comment]
@Techguyprivate Thanks for the report, does version 5.1.2 (https://languagetool.org/download/LanguageTool-5.1.2.oxt) solve this for you?

**Comment by danielnaber** [comment]
Closing, as there was no reply.
