### ISSUE TITLE
Some languages are not detecting missing space and/or capital after full stop

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#3655]
From NNina's message on the forum, it was clear that LT does not detect the error of lowercase after full stop like.this.
Of course, all kinds of file names and URL's are in the way.

For Dutch, I added a rule to catch this kind of mistake:
```

		<rulegroup id="PUNT_GEEN_HL" name="Geen spatie en hoofdletter na punt" default="on">
			<rule>
				<pattern>
					<token spacebefore="yes" regexp="yes" case_sensitive="yes">.*[a-z]$</token>
					<token spacebefore="no">.</token>
					<marker>
						<token spacebefore="no" regexp="yes" case_sensitive="yes">[a-zA-Z].*<exception postag="UNKNOWN"/><exception regexp="yes">dat|doc</exception></token>
					</marker>
				</pattern>
				<message>Zet een spatie en een hoofdletter bij een zinsovergang.</message>
				<suggestion> <match no="3" case_conversion="startupper"/></suggestion>
				<example correction=" En">Dit is een zin.<marker>en</marker> dit ook.</example>
			</rule>
		</rulegroup>
```
This might be useful for other languages as well. The exception has to be tweaked to contain normal words that are also in use as an extension. Testing will show which.

**Comment by danielnaber** [comment]
I've added it here for German, `default=temp_off`: https://github.com/languagetool-org/languagetool/commit/b036a53d56aa1aa663e11f1318ea387c41e17a0b

**Comment by baarsrj** [comment]
You will probably have to add an antipattern for common a.b.d. abbreviations.
At least, I had to.

**Comment by danielnaber** [comment]
@jaumeortola @udomai  What do you think, should it be added for French, too? For German, the rule works nicely. For Spanish, such a rule already seems to exist.

**Comment by jaumeortola** [comment]
> What do you think, should it be added for French, too?

Yes, I added recently the Spanish rule (ESPACIO_DESPUES_DE_PUNTO). It can be copied and adjusted.

**Comment by udomai** [comment]
I concur whole-heartedly :) thank you Jaume!
