### ISSUE TITLE
Version mismatch in LanguageTool releases 5.1.1 and 5.1.2 for the standalone version

### ISSUE THREAD

**Issue by Erikvl87** [languagetool-org/languagetool#3659]
When downloading the 5.1.1 and 5.1.2 releases on https://github.com/languagetool-org/languagetool/releases, the `languagetool-standalone` directory seems to include the `5.1` release instead of the respective `5.1.1` and `5.1.2` versions.

This now breaks my release of a [community contributed Dockerfile for LanguageTool](https://github.com/Erikvl87/docker-languagetool).

```
Step 9/23 : WORKDIR /languagetool
 ---> Running in 505d7140bdc4
Removing intermediate container 505d7140bdc4
 ---> b55bd79bbe0b
Step 10/23 : RUN ["mvn", "--projects", "languagetool-standalone", "--also-make", "package", "-DskipTests", "--quiet"]
 ---> Running in e157ca2b1c9c
Removing intermediate container e157ca2b1c9c
 ---> d96f1a571378
Step 11/23 : RUN unzip /languagetool/languagetool-standalone/target/LanguageTool-${LANGUAGETOOL_VERSION}.zip -d /dist
 ---> Running in 3b96b9b3fd3c
unzip:  cannot find or open /languagetool/languagetool-standalone/target/LanguageTool-5.1.2.zip, /languagetool/languagetool-standalone/target/LanguageTool-5.1.2.zip.zip or /languagetool/languagetool-standalone/target/LanguageTool-5.1.2.zip.ZIP.
The command '/bin/sh -c unzip /languagetool/languagetool-standalone/target/LanguageTool-${LANGUAGETOOL_VERSION}.zip -d /dist' returned a non-zero code: 9

Error: Process completed with exit code 9.
```

I can update my script to find the available zip file but I am not sure if I should. Is this by design? Previously that folder always seemed to contain the patch release as well.

**Comment by danielnaber** [comment]
The 5.1.1 and 5.1.2 releases are only relevant for LibreOffice/OpenOffice (.oxt), so there's no need to use them for anything else.

**Comment by Erikvl87** [comment]
Thank you for your quick response @danielnaber. I could have guessed that after reading the changelog. 

So I will need to assume that this can happen in the future as well? For me I just run the pipeline on all of t he releases since that is easier for me than verifying if a release contains changes that would have been relevant for the standalone version.

**Comment by danielnaber** [comment]
> So I will need to assume that this can happen in the future as well when a patch release doesn't affect the standalone version?

Yes.

**Comment by Erikvl87** [comment]
Alright, thanks Daniel! Closing this issue. I will change my scripts to take that into consideration.

**Comment by Erikvl87** [comment]
@danielnaber although the issue is closed, may I ask, can I assume the version in that folder from the `pom.xml` file at XPath `//project/parent/version`?

**Comment by danielnaber** [comment]
The main location for the version is `//project/properties/languagetool.version` in the top-level `pom.xml`.
