### ISSUE TITLE
[de] false alarm BRAUCHEN_ZU

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3664]
> Den brauchen die um sich mit unserem Tool auseinanderzusetzen

<img width="725" alt="Bildschirmfoto 2020-10-08 um 16 42 32" src="https://user-images.githubusercontent.com/37363/95474400-58cc0c80-0985-11eb-9f02-826800fb0f1d.png">

**Comment by tiff** [comment]
@danielnaber sieht so aus als wäre POS falsch:

<img width="535" alt="Bildschirmfoto 2020-10-08 um 16 45 41" src="https://user-images.githubusercontent.com/37363/95474721-c1b38480-0985-11eb-9b98-078327f556e9.png">

**Comment by danielnaber** [comment]
Problem war, dass es als auseinander + zusetzen interpretiert wurde. Quick fix gemacht: zur `added.txt` hinzugefügt.
