### ISSUE TITLE
LibreOffice Writer hangs with the latest nightly

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#3675]
Hello!

I spent a week or two without updating my LO add-on with the nightly.

I did it minutes ago and tried to open the attached document with LO 7.0.2 and it hangs.

The only solution is to force a close of LO.

[MCAT_Translation_51PT_unsent.zip](https://github.com/languagetool-org/languagetool/files/5364499/MCAT_Translation_51PT_unsent.zip)

**Comment by FredKruse** [comment]
@marcoagpinto Did you have the LT-logfile? Could you post it?

**Comment by marcoagpinto** [comment]
@FredKruse 

Ohhh... only now I saw your reply... it is strange... where can I find the log file?

**Comment by marcoagpinto** [comment]
@FredKruse @danielnaber 

I installed the last nightly and now everything works fine again.

I don't know what was changed in the  code.
