### ISSUE TITLE
Checks for first capital letter, but do not checks for full stop.

### ISSUE THREAD

**Issue by socketpair** [languagetool-org/languagetool#369]
Online verification form on your website checks for capital letter at the start of a sentence. But do not checks for full stop (`.`) at the end. Do not know if that is a bug or feature…

This happen at least on Russian page for Russian sentencies.

**Comment by danielnaber** [comment]
Some "sentences" like headlines don't need a full stop, so this is tricky to implement without causing false alarms. I think checking the capital letter at the following sentence should thus be enough.
