### ISSUE TITLE
[pt] feedback about "travesti"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3703]
User feedback:

> In Portuguese language tool the therm transvestite (travesti) is marked as a masculine noun, but considering it is a feminine identity in Brazil it's better to correct your algorithms to mark the Portuguese word 'travesti'as a feminine noun, instead of masculine.

**Comment by marcoagpinto** [comment]
@danielnaber 

According to Priberam, it is a two gender word:
https://dicionario.priberam.org/travesti

So, I removed the incorrect POS from:
https://github.com/languagetool-org/languagetool/commit/f24fb65355370a33a8d8fce5fc2055ec039e8407

And added the correct to:
https://github.com/languagetool-org/languagetool/commit/305fe5992af9adbdf0ccb967ef76a49b63d14a06
