### ISSUE TITLE
Spelling suggestions for all upper-case words. 

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#3705]
I think this issue is common to many languages. 

When all upper-case words are misspelled, the suggestions are first letter upper-case words (*THIZ > This). Obviously, all upper-case is not usual and is not recommended. But in these cases users probably expect all upper-case suggestions (THIS).

Should we provide all upper-case suggestions? In all languages?

**Comment by tiff** [comment]
I can say that this would be very helpful for English and German.

**Comment by udomai** [comment]
It would make an awful lot of sense for French as well. Uppercase letters with accents are really hard to type (because the French keyboard doesn't have keys for that).

**Comment by jaumeortola** [comment]
There are some questions to be answered before implementing it, @danielnaber 

I have made some tests in French generating all upper-case suggestions when the original is all upper-case. We will need to deal with exceptions somehow. In French, I found problems in the rule for PM (PM -> de l’après-midi|du soir), and for suggestions containing numbers (14 MB -> 14 Mo, Covid 19->COVID-19|Covid 19...). In other languages the problems are similar: abbreviations, short words, etc. 

- Should we enable it for all languages or language by language?
- For just the spelling rule or for all rules (in RuleMatch)?
- How to deal with exceptions?

Sometimes (not only for this issue), I feel we need something like `<suggestion preserve_case="yes">pH</suggestion>` to simplify the casing in suggestions. This could be a good solution.

**Comment by jaumeortola** [comment]
> Sometimes (not only for this issue), I feel we need something like `<suggestion preserve_case="yes">pH</suggestion>` to simplify casing in suggestions. This could be a good solution.

This can be already achieved this way. It is just a bit verbose. 
`<suggestion><match no="1" regexp_match="^.*$" regexp_replace="pH" case_conversion="preserve"/></suggestion>`

**Comment by jaumeortola** [comment]
Added all upper case suggestions for the Morfologik spelling rule here: https://github.com/languagetool-org/languagetool/commit/5ad0bf718683b2027aa455a73671d7056cefa66d This will cover most cases in languages using Morfologik. 
For Java and XML rules, other solutions are needed.
