### ISSUE TITLE
[pt] "Se caso"

### ISSUE THREAD

**Issue by hmslima** [languagetool-org/languagetool#3714]
Look the sentence below:

> Se caso eles vierem, não os atenda.

LT doesn't detect any error.

The construction "se caso" is wrong. The correct is one of the sentences below:

> **Se eles vierem, não os atenda** = If they come, don't answer them

> **Caso eles vierem, não os atenda** = If they come, don't answer them

<hr>

The problem is to differentiate it from the case when this "caso" is a conjugation of the verb "casar". The sentence below is correct because "caso" is a verb, not a conjunction:

> **Se caso com ela, herdarei uma fortuna** = If I marry her, I will inherit a fortune

But I don't think it's a problem impossible to solve. Usually the verb "casar" comes with the preposition "com".

> Os Wodaabe não são polígamos, então para casar com um novo parceiro é preciso deixar o anterior.

Or it is intransitive and comes with some preposition:

> A atriz de 28 anos revelou que, tal como sua personagem em "O Astro", sonha casar de véu e grinalda.

> Para não perder a festa que organizaram, dois pacientes da clínica decidem casar no lugar dos noivos. 

When "se caso" is actually composed by two conjunctions, which is wrong, it will usually be followed by a pronoun or article:

> **Se caso eles vierem, não os atenda** = If _if_ they come, don't answer them.
Followed by a pronoun

> **Se caso o juiz vier, diga que estive à procura dele** = If _if_ in case the judge comes, say that I was looking for him
Followed by an article

But it is not a perfect rule, because "casar" may work as a direct transitive verb, like in the sentence just below that is correct:

> **Se caso a princesa com o rei, conseguirei unir duas dinastias** = If I marry the princess with the king, I will be able to unite two dynasties

My suggestion is to not classify it as an error, but as a _possible_ error. LT just would give a message asking the user whether that expression is really what he or she meant. Here is my pseudo-code for this situation:

    if ("se caso" + ("com" OR "de"))
    {
        // Do nothing, much probably "caso" is a verb
    }
    else if ("se caso" + (pronoun OR article))
    {
        message ("Se \"caso\" for uma conjunção em vez de um verbo, esta frase está errada. É equivocada a construção \"se caso" para expressar uma condição. Por exemplo, uma frase como \"Se caso eles vierem, não os atenda.\" deveria ser reescrita como ou \"Se eles vierem, não os atenda.\" ou \"Caso eles vierem, não os atenda.\"");
    }

**Comment by marcoagpinto** [comment]
Thanks!

I will code it tomorrow.

**Comment by marcoagpinto** [comment]
@jaumeortola 

Hello!

What is wrong with this rule creation:
```
    <!-- SE CASO caso -->
	<!--      Created by Marco A.G.Pinto, Portuguese rule 2020-10-20 (2-JUL-2020+)     -->	
    <rule id='SE_CASO-CASO' name="Se caso -> caso">
    <!--      Created by Marco A.G.Pinto, Portuguese rule      -->
      <pattern>
		  <marker>
			<token>se</token>
			<token>caso</token>
		  </marker>		  			
		  <token min="1" max="2">
			<exception regexp='no'>com</exception></token>
		  <token postag='V.+' postag_regexp='yes'/>		  
      </pattern>
      <message>Substitua por <suggestion>caso</suggestion>.</message>
      <example correction="Caso"><marker>Se caso</marker> eles vierem, não os atenda.</example>
    </rule>
```

TESTRULES PT gives a ton of warnings:

> Skipped 0 rules for variant language to avoid checking rules more than once
> 2580 rules tested.
> Exception in thread "main" org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule SE_CASO-CASO[1] in file /org/languagetool/rules/pt/grammar.xml: Se caso eles vierem, n?o os atenda."
> Errors expected: 1
> Errors found   : 0
> Message: Substitua por <suggestion>caso</suggestion>.
> Analyzed token readings: [/SENT_START*] Se[se/CS*,se/PP3CN000*]  [ /null*] caso[caso/CS,caso/NCMS000,casar/VMIP1S0]  [ /null*] eles[ele/PP3MP000]  [ /null*] vierem[vir/VMSF3P0] ,[,/_PUNCT*]  [ /null*] n?o[n?o/RN]  [ /null*] os[o/PD0MP000,o/PP3MPA00]  [ /null*] atenda[atender/VMSP1S0,atender/VMSP3S0] .[./SENT_END*,./_PUNCT*]
> Matches: []
>         at org.languagetool.rules.patterns.PatternRuleTest.testBadSentences(PatternRuleTest.java:396)
>         at org.languagetool.rules.patterns.PatternRuleTest.testGrammarRulesFromXML(PatternRuleTest.java:318)
>         at org.languagetool.rules.patterns.PatternRuleTest.runTestForLanguage(PatternRuleTest.java:169)
>         at org.languagetool.rules.patterns.PatternRuleTest.runGrammarRulesFromXmlTestIgnoringLanguages(PatternRuleTest.java:152)
>         at org.languagetool.rules.patterns.PatternRuleTest.main(PatternRuleTest.java:683)
> Running disambiguator rule tests...

Thanks!

**Comment by jaumeortola** [comment]
Do this or make the third token more specific (e.g. pronouns...): 
```
<rule id='SE_CASO-CASO' name="Se caso -> caso">
    <!--      Created by Marco A.G.Pinto, Portuguese rule      -->
      <pattern>
		  <marker>
			<token>se</token>
			<token>caso</token>
		  </marker>		  			
		  <token min="1" max="2"><exception regexp='no'>com</exception><exception postag='V.+' postag_regexp='yes'/></token>
		  <token postag='V.+' postag_regexp='yes'/>		  
      </pattern>
      <message>Substitua por <suggestion>caso</suggestion>.</message>
      <example correction="Caso"><marker>Se caso</marker> eles vierem, não os atenda.</example>
    </rule>
```

**Comment by marcoagpinto** [comment]
@jaumeortola 

Thank you!

I am now testing it against a 200 000 sentence-corpus.

**Comment by marcoagpinto** [comment]
Done!

https://github.com/languagetool-org/languagetool/commit/a17496b933a085ebb4d044f91e20452202ea5a34
