### ISSUE TITLE
Improving the synthesis options

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#3716]
Sometimes to synthesize a proper suggestion it is necessary to extract information from different tokens. For example, lemma (and POS tag) from token 1, and gender and number from token 2. Now this is not possible. 

The only solution available is to write more and more rules, which sometimes becomes cumbersome.

First, it would be necessary to define the syntax.

**Comment by udomai** [comment]
I recently saw this in a rule:

The postag from \4 is transferred to "wonder" in the suggestion. It's not exactly what you were saying, but I thought maybe this might be pertinent nonetheless. Would it be possible, for example, to replace the string `wondering` in the suggestion with a token (e.g. `\2`)?

```
     <rule id="WAS_WONDERING" name="I was wondering (I wondered) etc.">
            <pattern>
                <token postag="SENT_START|CC" postag_regexp="yes"/>
                <marker>
                    <token postag="PRP|NNPS?" postag_regexp="yes"/>
                    <token regexp="yes" min="0">&apostrophe;</token>
                    <token inflected="yes">be</token>
                    <token>wondering</token>
                </marker>
            </pattern>
            <message>This phrase may be considered to be too colloquial in certain formal contexts. Consider using <suggestion>\2 <match no="4" postag=".*">wonder</match></suggestion> instead.</message>
            <example correction="I wondered"><marker>I was wondering</marker> if you could send me the report for the meeting?</example>
            <example correction="I wonder">But <marker>I'm wondering</marker> if there's any life on Mars.</example>
        </rule>
```

**Comment by jaumeortola** [comment]
Thanks. That makes sense. We could allow a match inside a match to get the desired lemma, and this would be easy to implement. 

`<match no="2" postag =".*([MF][SP]).*" postag_regexp="yes" postag_replace=".*$1.*"><match no="1"/></match>`

I think it will work most times. But the information in `postag_replace` is incomplete because part of the information should come form match no. 1.

**Comment by jaumeortola** [comment]
I made an implementation using a filter. See: https://github.com/languagetool-org/languagetool/commit/a92bf364a3d7a1acf74cd42b3c3213e63624a3ed
It looks like this:
`<filter class="org.languagetool.rules.ca.AdvancedSynthesizerFilter" args="lemma_from:3 lemma_select:V.N.* postag_from:1 postag_select:V.*"/>`
Lemma is taken from a token and POS tag from another one to synthesize the desired suggestion. The lemma_select and postag_select are required to choose one among several possible readings.

**Comment by jaumeortola** [comment]
Continuation here: https://github.com/languagetool-org/languagetool/issues/4325
