### ISSUE TITLE
Error Could not find or load main class org.languagetool.server.HTTPServer after installing from brew

### ISSUE THREAD

**Issue by quentinms** [languagetool-org/languagetool#3719]
After installing using `brew` (`brew install languagetool`),  I get the following error when trying to run the server:

```
languagetool-server --allow-origin "*"
Error: Could not find or load main class org.languagetool.server.HTTPServer
Caused by: java.lang.ClassNotFoundException: org.languagetool.server.HTTPServer
```

If I look at my `/usr/local/Cellar/languagetool/5.1.3/bin/languagetool-server`, I see it calls this jar `/usr/local/Cellar/languagetool/5.1.3/libexec/languagetool-server.jar`, which doesn't exist.

```
$ ls -l /usr/local/Cellar/languagetool/5.1.3/libexec/
-rw-r--r--  1 quentin.mazarssimon  staff  142774437 Oct 15 13:59 LanguageTool-5.1.3.oxt
```

I believe it might be because the `url` in the [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/languagetool.rb) was changed from a `.zip` to `.oxt`.

https://github.com/Homebrew/homebrew-core/pull/62595/files

**Comment by danielnaber** [comment]
> I believe it might be because the url in the formula was changed from a .zip to .oxt.

That change doesn't seem to be correct. `.oxt` is meant only for LibreOffice. You should probably report that to the author of that file.

**Comment by quentinms** [comment]
This has been [fixed](https://github.com/Homebrew/homebrew-core/commit/8a71452df6006dd9383c4861a17f825569ad6aa1) by a `brew` maintainer. They're now building from git instead of downloading the zip (and added a check to make sure it's installed correctly).
