### ISSUE TITLE
Results window shows results from previous run

### ISSUE THREAD

**Issue by ingrid16** [languagetool-org/languagetool#372]
I am a new Language Tool user and installed LT for testing the ASD-STE100 rules from Techscribe.

At one point in time during my tests I got a message in the message line telling me a certain number of problems found. But the results monitor displayed only the results from the previous run. E. g. the message line was: “Problems found 1011”, but the displayed checking results displayed 1858 potential problems in the summary line at the end of the file and documented them. But these 1858 where already reported for the previous run but documented differently.
(I attach a screenshot showing another situation, displaying 151 problems found, which relates properly to the small text portion inserted in the upper window. The results windows shows the results from the previous check run where 1011 problems where reported…)
![ste_tests_01 mar 11 11 36](https://cloud.githubusercontent.com/assets/15126332/13730005/bfc59234-e942-11e5-86ea-6427a5dfb14e.jpg)
Mike Unwhalla pointed out the issue #28 at https://github.com/languagetool-org/languagetool/issues/28 . I read it but found that the reported bug was not followed further on but the discussion obfuscated to more general topics.
I would be grateful if somebody could tell be whether there would be a chance that the issue be solved.
Thank you!
Kind regards
Ingrid. (From Switzerland)

**Comment by danielnaber** [comment]
Mike wrote in #28: "More tests show that problems occur if AutoCheck is selected." - does it help if you de-activate the automatic check and check only manually?

**Comment by ingrid16** [comment]
Hello Daniel,
thank you for the quick response.
No, it did not help clicking the AutoCheck button or selecting the option
from the menu. A few minutes ago I experienced that despite me deactivating
the AutoCheck button half a minute before, the check run started
nevertheless on its own. (??)
I have some other problems with the LT listed here:
- I first selected British English as the text language, not knowing the
TermChecker Tool prefers American English. I tried several times to reset
this after Mike U. pointed this out explicitly. Even after restarting the
machine the setting did not become activated and still displayed British
English.(I tried this several times)
[image: Inline-Bild 1]
- After I changed the setting directly in the .cfg file, the LT still
reported the runs checking with British English (see above screenshot).
- I varied the input to the checker between copy/paste and by selecting a
txt file via the GUI. When changing from input by GUI back to copy/paste,
the window still displayed the previous file title. (minor issue...)
- Sometimes the LT crashed, probably due to the file size or other issuse
(?), but always only after the first run was (in some way or the other)
successful.

I was sometimes suspecting that some of these issues had to do with storing
the settings in the cfg file and recalling them or not (this due to
settings from elsewhere or losing the path). I am running LT from a D:
drive on the same machine as the cfg file is stored on (on C:\Users\Ingrid).

I would love to go on testing systematically and contribute to your efforts
but unfortunately I am running out of time with presenting my STE-specific
test results to my team and have to suspend this now.


*If you have specific questions as to my settings or would like to get to
know the screenshots and cfg versions stored during a period of time please
ask me.*

I started the LT via the command line, too, this was much faster and more
satisfying.

Two additional questions:
1. is there any documentation on the parameters of the cfg file?
2. I worked with txt files converted from the Framemaker format. Some
special character (like some quotation marks) were not displayed properly
in the text file. When pasting them into the GUI they were not shown, but
when opening the file from the LT GUI, they were displayed as some weird
character combinations. Does a hidden existence when pasting or the
explicit display when calling the file has any influence on the term
segmentation and the performance? (Some of the displayed weird characters
were found and objected by the TermChecker...)

Thanks a lot for your attention!
Ingrid.



2016-03-13 18:24 GMT+01:00 Daniel Naber <notifications@github.com>:

**Comment by ingrid16** [comment]
[languagetool.zip](https://github.com/languagetool-org/languagetool/files/171964/languagetool.zip)
I added a zip file containing screenshots and cfg copies reflecting the states after closing sessions.
Kind regards,
Ingrid.

**Comment by ingrid16** [comment]
Sorry! Closed this by mistake...

**Comment by danielnaber** [comment]
About the original issue, maybe @pminos might have some idea (our GUI expert)?

About the crash: what exactly do you mean by crash? Did LT shut down with an error message?

I don't understand the issue about British English vs. American English, the screen shots all seem to show American English set?

> 1. is there any documentation on the parameters of the cfg file?

The `.cfg` file is not documented, there's usually no need to edit it manually.

> Some of the displayed weird characters were found and objected by the TermChecker...

When loading a file from the GUI, the file needs to be in the system's encoding (e.g. UTF-8 on Linux), otherwise you might get false alarms and errors might not be detected. On the command line, you can set the encoding with the `--encoding` switch.

**Comment by pminos** [comment]
@ingrid16 if the last fix does not solve your issue, reopen it.

**Comment by pminos** [comment]
@danielnaber about #28, it is still open because I must remove the Result Area (in fact to hide it and open it on request). But I had the feeling that I solved the issues (apparently not all of them :flushed:).

**Comment by pminos** [comment]
There is a case that the update of the results will not happen.

If the user has autocheck off, a paste to the TextArea will not update the results until the user do a 'check text'. Maybe we should clear the result area?

**Comment by ingrid16** [comment]
About the crash: what exactly do you mean by crash? Did LT shut down with
an error message?

>>>> Twice LT just closed. Several times I had to suspend execution after
about half an hour by killing the java process in the Windows taskmanager.
(I correct myself: LT probably hanged up and did not exactly crash...)

I don't understand the issue about British English vs. American English,
the screen shots all seem to show American English set?
>>>> As the screenshot indicates, the dropdown list setting shows "English
(American)", the message window reports "Starting check in English
(British)". This happened even after closing LT and restarting it after a
machine restart. (See attached Screenshot). Unfortunately, I cannot recall
when the message window started to report again "Starting check in English
(American)".

Additional remark or question: why did (on my installation) the GUI or the
.cfg not keep the reset of the "Automatic Check" button to "not pressed".
When I open the LT, it is always pressed again and the results of the
example sentence are shown?

The .cfg file is not documented, there's usually no need to edit it
manually.
>>>>... without editing it I would not have succeeded in resetting the
language to English(American).

2016-03-14 14:56 GMT+01:00 Daniel Naber <notifications@github.com>:

**Comment by ingrid16** [comment]
Hello Panagiotis,
thank you for the email.
How can I test your fix? Where can I get the updated jar file?
Regards,
Ingrid.

2016-03-14 16:12 GMT+01:00 Panagiotis Minos <notifications@github.com>:

**Comment by pminos** [comment]
@ingrid16 you have to download the source code and compile it. If you are not a Java developer, you can download the latest daily build from [here](https://languagetool.org/download/snapshots/?C=M;O=D). I think that the next build that will include my commit will be available today after 22:00.

As for the "Automatic Check" button state, the GUI doesn't  save it. We never had this feature.

**Comment by danielnaber** [comment]
@ingrid16 In case you run further tests, it would be great if you could start LT from the command line with `java -jar languagetool.jar`. If it crashes again, something might be printed on the command line.

**Comment by ingrid16** [comment]
I started the LT from the command line with the indicated syntax. There
were not messages.


2016-03-14 18:00 GMT+01:00 Daniel Naber <notifications@github.com>:
