### ISSUE TITLE
Getting error messages in English than in French

### ISSUE THREAD

**Issue by Bollegala** [languagetool-org/languagetool#3727]
I am using pylanguage tool to access languagetool (run as a standalone server) and using pylanguagetool.api to analyse French input text. I am getting the errors displayed in French and was wondering whether it was possible to get these displayed in English. For example,

Détection de phase TTL ; 105 points AF, dont 15 d’entre eux sont compatibles avec f/8 ; détection effectuée par le module autofocus Multi-CAM 37K ; réglage précis de l’autofocus possible **** Faute de frappe possible trouvée

Here, I would like to get the error message "Faute de frappe possible trouvée" in English instead of French

**Comment by danielnaber** [comment]
Sorry, this is not possible. The messages are always in the language of the text that is checked.

**Comment by Bollegala** [comment]
Thank you for the quick response! Much appreciated. I decided to prepare a separate mapping between the error messages as a workaround.
