### ISSUE TITLE
ConfusionProbabilityRule shows an empty description in option panel

### ISSUE THREAD

**Issue by FredKruse** [languagetool-org/languagetool#3728]
The ConfusionProbabilityRule gives back a null as general description (inside of matches a special description is generated). In the option panel a description other than null is needed to e.g. deactivate the rule. This is needed for the LO/OO extension but also for the standalone version.

**Comment by danielnaber** [comment]
Should be fixed now, can you confirm?

**Comment by FredKruse** [comment]
Yes, it is fixed now
