### ISSUE TITLE
[de] wrong tagging "Hauptakteurin"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3734]
@danielnaber hier mal wieder was Lustiges:

"Hauptakteurin" wird als maskulin getagged. Wahrscheinlich weil "der Urin".

**Comment by udomai** [comment]
Auch ganz witzig fand ich gestern, dass das "Auskommentieren" (z.B. von Regeln) als SUB:DAT:PLU:NEU getaggt wird, weil vermutlich ein Kompositum aus "Auskommen" und "Tier" zugrunde gelegt wird.
