### ISSUE TITLE
Freeze during install on LO 5.1 and OS X

### ISSUE THREAD

**Issue by lukasamd** [languagetool-org/languagetool#374]
Hello,
I use latest LibreOffice 5.1.1 64-bit on OS X 10.11.3
I tried to install LanguageTool, but without results - install progres stops in about 5-10% and freeze LO - very high cpu usage (and high fan usage), without any errors etc. Finally, I must force close LibreOffice.

I have Apple Java and Java 1.8.0_73 (from JDK x64) installed and active in LO.

**Comment by danielnaber** [comment]
Can you reproduce this, i.e. does it happen again if you try it a second time?

**Comment by milekpl** [comment]
Well, it definitely can work but there are some intermittent problems (I did this myself on a similar config) if you pick the install of the extension for a single user. Probably there's a bug in LO.

**Comment by lukasamd** [comment]
Yep, I can reproduce this and I have new details.
This problem occurs only when I try install extension by running .oxt file (ex. after download) - LO doesn't ask me about install for single user / for all and freeze during installation. I tried first run oxt file and first run LO and then oxt - freeze in both cases.

But... when I run LO, select extensions manager and add LanguageTool, there is selection menu and everything is ok.

**Comment by danielnaber** [comment]
As Marcin said, probably a bug in LO. If you'd like to debug this further for LO, you can call `jps`, then re-produce the issue with the hanging install, call `jps` again. You'll probably see a new number, which is the id of the hanging Java process. You can then `jstack <pid>` with `<pid>` being the new process number and you should get a stacktrace that shows where Java is stuck (although it's not clear it's a Java issue).

**Comment by danielnaber** [comment]
Closing as it's probably an LO issue.
