### ISSUE TITLE
[en] false alarm MASS_AGREEMENT

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3741]
> When the interface clock period is shorter than the largest time difference between signal arrivals, recovery of the transmitted word is no longer possible. 

![Bildschirmfoto 2020-10-21 um 19 45 32](https://user-images.githubusercontent.com/37363/96757639-ff78ca00-13d5-11eb-8018-6d0365a7998d.png)

**Comment by MikeUnwalla** [comment]
Also:

> Your **staff** give excellent service.

https://www.lexico.com/definition/staff
