### ISSUE TITLE
[en] False warning PROFANITY 

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3750]
'Dago' is a family name (https://www.ancestry.co.uk/name-origin?surname=dago). I added the POS info a few minutes ago.

Improve PROFANITY such that it does not give warnings for proper nouns in context:

> Tell **Mr Dago** to come to my office.

> **Pedro L. Dago**, MD is a physician associated with Northwestern Medicine. [https://www.nm.org/doctors/1689637639/pedro-l-dago-md]

**Comment by tiff** [comment]
This is already fixed by your addition of NNP o 'Dago'

**Comment by MikeUnwalla** [comment]
@tiff , sorry. I added the POS in the repo, but saw the error in the GUI.
