### ISSUE TITLE
[DE]verbotene Wörter

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#3751]
Moin liebes LanguageTool-Team

Hier werden Wörter zusammengefasst, die die Endung -erd, -erb, -erz haben, aber keine legitime Wörter sind. Diese Wörter werden hier ohne weiteren Flexionsendungen gesammelt, bis eine Abkürzung gefunden oder die einzelnd eingetragen wirden.

***
**Nicht in der prohibit.txt vorhanden**
Schneiderdsitzposition
Schneiderbsitzposition
Schneiderzsitzposition
Masterzkommando
Masterbkommando
Masterdkommando
***
**in der prohibit.txt vorhanden**
Richterz
Audionerz
***

Grüße Dallun511

**Comment by danielnaber** [comment]
Link zum Original-Report: https://forum.languagetool.org/t/de-erd-erb-erz-in-einer-kompostion/6291/2

**Comment by danielnaber** [comment]
Mehr Fälle hier: https://gist.github.com/danielnaber/03ae6b58302598268e1a72070bc312af
Generiert mit: https://gist.github.com/danielnaber/686f6ef361da1f2240ebf514b0873a00
