### ISSUE TITLE
[pt] user feedback

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3752]
User feedback, not sure if it's useful:

> Alguém poderia explicar se de fato há um erro aí? Até onde me lembre, não fere nenhuma das regras de concordância verbal. Se sim, citar qual, por gentileza

![image](https://user-images.githubusercontent.com/857004/97109087-8fb65800-16d1-11eb-87f2-c8241641a4c2.png)

**Comment by marcoagpinto** [comment]
@danielnaber 

Yes, it is a false positive.

I will try to fix it tomorrow.

**Comment by marcoagpinto** [comment]
Done!

https://github.com/languagetool-org/languagetool/commit/149e91d4054c27c1273dcf79f6db93eb54f43c4a
