### ISSUE TITLE
[pt-br] user feedback "Zezualdo"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3767]
> Olá equipe de desenvolvimento do LanguageTool
>
> Quero pedir para que vocês adicionem ao banco de dados da extensão o nome próprio Zezualdo, para que ele não seja mais considerado como um erro gramatical ou ortográfico. Sei que este nome só não estava inserido como nome próprio pelo fato de ser raramente usado por pessoas no Brasil, porém venho fazer esse pedido a mando de meu pai, cujo tem este nome.
> 
> Antenciosamente, o usuário

@marcoagpinto looks like he wants us to add the name "Zezualdo" to our dictionary. Feel free to close this issue if that name is not really a name ...

**Comment by marcoagpinto** [comment]
Done!

https://github.com/languagetool-org/languagetool/commit/42c346794891192f2c14cb7390fd29a4e20fd990

https://github.com/languagetool-org/languagetool/commit/b5f517588c52d69f9e3bbfcf8e0a93638b33421e
