### ISSUE TITLE
[en] chunker fails to identify contractions

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3772]
> It wouldn't work

"wouldn't" is not detected as a verb chunk

Same for

> It didn't work

This seems to happen with all contractions.

Also:

> I've no idea.

> It's awesome.

**Comment by danielnaber** [comment]
Problem is here: https://github.com/languagetool-org/languagetool/blob/a13cf144d66d403fb4d67de263ffb5bd067e4718/languagetool-language-modules/en/src/main/java/org/languagetool/chunking/EnglishChunker.java#L162-L164 - let's see if I can find a simple fix

**Comment by danielnaber** [comment]
Can this be closed now with the new tokenizer?

**Comment by udomai** [comment]
Yes, this problem has been solved thanks to @jaumeortola's tokenizer magic :)
