### ISSUE TITLE
[es] user feedback regarding accents

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3773]
> Hay tildes que en español no se están corrigiendo bien como "Nóminas"

@jaumeortola I'm not sure what the user exactly meant. He didn't provide an example sentence.

**Comment by jaumeortola** [comment]
It makes sense: "nominas" (verb) vs. "nóminas" (noun). Now, we don't say anything when there is no context. But we'll suggest "nóminas" because it is more common. I will add a rule.

**Comment by jaumeortola** [comment]
Explanation: We catch many diacritics errors on many contexts. But sometimes the context is not definitive enough. 

For some words, a not so unequivocal context could be enough. Anyway, this is a gray zone. At the moment, we don't know how to make something more general, and we just write specific rules.
