### ISSUE TITLE
[de] DE_CASE merkwürdiger Vorschlag

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3779]
> Unser Wärmestrom-Tarif EnBW AktivPrivat WärmeKompakt im Detail

![Bildschirmfoto 2020-10-30 um 11 03 09](https://user-images.githubusercontent.com/37363/97692128-aaa51580-1a9f-11eb-8a29-f81b203f7f00.png)

"WärmeKompakt" ist ein Eigenname und ist nicht in unserem Dictionary, trotzdem will LT es zu "wärmeKompakt" ändern, was auch nicht im Dictionary ist.

@danielnaber vielleicht was für dich?

**Comment by tiff** [comment]
Ähnlicher Fall:
![Bildschirmfoto 2020-10-30 um 11 10 23](https://user-images.githubusercontent.com/37363/97692834-8dbd1200-1aa0-11eb-8a21-cbec09787a31.png)

**Comment by danielnaber** [comment]
Reopening, I had to revert to get the tests stable first...

**Comment by danielnaber** [comment]
Yet another try, should be fixed now.
