### ISSUE TITLE
Included lucene-core does not work under WebStart security

### ISSUE THREAD

**Issue by amake** [languagetool-org/languagetool#378]
Lucene 5.2.1 makes some calls that are disallowed by the Java WebStart security manager, even when the entire application is signed and requests `<security><all-permissions/></security>`. I understand if supporting WebStart directly for LanguageTool is not a priority, but this affects anyone wanting to include LanguageTool in their own WebStart-deployed app.

I have posted a bug with Lucene:
https://issues.apache.org/jira/browse/LUCENE-7135

I also have a fork with a backport to Lucene 5.2.1 of fixes for this:
https://github.com/amake/lucene-solr/tree/v5.2.1-webstart

**Comment by amake** [comment]
Since there has been no response to the bug ticket, we have published our patched version:

- https://bintray.com/omegat-org/maven/lucene-core
- Available in JCenter as {{compile 'org.omegat.lucene:lucene-core:5.2.1'}}

**Comment by amake** [comment]
The bug has been fixed in Lucene 6 and 7. How do you decide which Lucene version to use in LanguageTool? Are there plans to move to 6 or 7 anytime soon?

**Comment by danielnaber** [comment]
There are no plans yet. Previous upgrades had not been so easy, as we use low level APIs in some places. I'll add it to my TODO list.

**Comment by amake** [comment]
This issue is fixed in Lucene 5.5.4, which is a mere bugfix release of 5.5.3 (which you are currently using).

**Comment by danielnaber** [comment]
I've just updated to Lucene 5.5.4, it will be part of the next daily snapshot. I assume we can close this issue then?

**Comment by amake** [comment]
I think so.
