### ISSUE TITLE
[en] Conflicting POS/spelling for 'on-line'

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3789]
I wanted to add POS and spelling for 'on-line' (adjective and adverb):
https://www.ldoceonline.com/dictionary/online
https://ahdictionary.com/word/search.html?q=on-line

The Maven test showed that 'on-line' is in prohibit.txt.

1. Why is it in prohibit.txt?
2. If it should be in prohibit.txt, then why does LT still contain POS `on-line/JJ`?

Are there any objections if I remove 'on-line' from prohibit.txt and add the missing POS/spelling/coherency?

**Comment by tiff** [comment]
@MikeUnwalla I added it there. I only checked Merriam-Webster and Lexico. Now that I see it's listed in other dictionaries, feel free to remove it in prohibit.txt.
