### ISSUE TITLE
Not working in Facebook on Firefox

### ISSUE THREAD

**Issue by MontyFlange** [languagetool-org/languagetool#3795]
The check as you type isn't working now

**Comment by danielnaber** [comment]
Could you send a screenshot and the URL where this is the case?

**Comment by MontyFlange** [comment]
Not really, How do I take a screen shot of something not working ?

All of Facebook. I think it's probably down to the new style

**Comment by tiff** [comment]
It works for me in Firefox, I tested status update and comments. Anyone else who is having this problem?

**Comment by udomai** [comment]
No problems on Firefox here, either (I use the new interface)

**Comment by tiff** [comment]
I'm closing this as we have found no way to reproduce this and we have no other users complaining about this
