### ISSUE TITLE
[trivial] two typos in French website for LanguageTool

### ISSUE THREAD

**Issue by goofy-bz** [languagetool-org/languagetool#380]
![un](https://cloud.githubusercontent.com/assets/858630/14078372/9bec6694-f4f5-11e5-92e5-395169f2039c.png)
![deux](https://cloud.githubusercontent.com/assets/858630/14078374/a2d53e7c-f4f5-11e5-9b7b-8a70bdb8d3ea.png)

**Comment by dpelle** [comment]
I fixed it in the following check-in in git repo https://github.com/languagetool-org/languagetool-website

commit 1d4004afb67383aaac8a83fb907952faae6e8517
Author: Dominique Pelle <dominique.pelle@gmail.com>
Date:   Mon Mar 28 19:43:22 2016 +0200

    [fr] fixed 2 typos.
    
    Kudos to goofy-bz (https://github.com/goofy-bz) for reporting them.
    This fixes https://github.com/languagetool-org/languagetool/issues/380
