### ISSUE TITLE
calcFormHints and OR

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3808]
@donnerpeter I wonder, shouldn't [this test](https://github.com/languagetool-org/languagetool/blob/master/languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternTokenTest.java#L206-L209) case work?

 ```
    token = new PatternTokenBuilder().tokenRegex("an|the").build();
    token.setOrGroupElement(new PatternTokenBuilder().tokenRegex("foo|bar").build());
    assertEquals(Sets.newHashSet("an", "the", "foo", "bar"), token.calcFormHints());
 ```

It fails with:
```
Expected :[the, bar, an, foo]
Actual   :[the, an]
```

**Comment by donnerpeter** [comment]
Yes, I believe you're right and it's a bug. I'll fix it, thanks!
