### ISSUE TITLE
[de] Error with hanging hyphen in "In- und Ausland"

### ISSUE THREAD

**Issue by f-knorr** [languagetool-org/languagetool#381]
In the expression "Im In- und Ausland", the token "In-" is marked wrong.
The reason for this behavior is that "Ausland" is not recognized as a compound (of "aus" and "land").

The easiest fix would probably to add "In-" to spelling.txt, but I do not know whether this also is the best fix

**Comment by danielnaber** [comment]
As this seems to be a common expression, why not add it to `disambiguation.xml` with `ignore_spelling`?
