### ISSUE TITLE
[en] Some missing words from the dictionary

### ISSUE THREAD

**Issue by ismail** [languagetool-org/languagetool#3813]
The following words do not exist in the dictionary, but they are valid:

```
Amytal
Pentothal
Synesthetes
abreaction
anterograde
callasum (from corpus callasum)
diagnosable
disconfirmation
examinee
extramission
glial
herky-jerky
homophily
left-hander
literalism
miniscule (It's a correct variant of "minuscule")
misimpression
neurobiology
polygrapher
pons
projectiological
projectiology
right-hander
speeded-up
strephosymbolia
succinylcholine
unsceptical
unshakeable
```

**Comment by MikeUnwalla** [comment]
@ismail . thank you for your contribution.

I have not added spelling or other information for these terms:

- unsceptical. Although the term has postag JJ in LT, I did not find the term in the standard dictionaries.
- extramission. Not found.
- projectiological. Not sure about the capitalization of this term.
- speeded-up. Not found.

If you want me to add these terms, please re-open this issue. Supply references from high-quality sources. Specify the locales (American English, British English, other). Thank you,

**Comment by ismail** [comment]
Thank you for your fast fix, since I don't know if you have OED (Oxford English Dictionary) access, I'm attaching the screenshots for: unsceptical, extramission and speeded-up

For projectiological it's complicated, it doesn't exist in OED, but it's used in Psychology:

https://consciousnesscongress.org/the-iac/
https://www.iacworld.org/projectiological-phenomena/
https://brill.com/view/book/9789004380110/BP000010.xml

![extramission](https://user-images.githubusercontent.com/4255/98543255-7a752800-2292-11eb-8ebb-f2b25bf5374d.png)
![unsceptical](https://user-images.githubusercontent.com/4255/98543259-7cd78200-2292-11eb-8dde-b3a9c75b298b.png)
![speeded-up](https://user-images.githubusercontent.com/4255/98543266-7e08af00-2292-11eb-89ab-ccfa2b9cf147.png)

**Comment by MikeUnwalla** [comment]
@ismail , thank you.

Usually, we don't add archaic words. Thus, I did not add 'extramission'.

OED is for BrE, thus, for the OED references, I added spellings for BrE only.
