### ISSUE TITLE
[fr] user feedback: (que) nous avons constaté

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3826]
> J'ai simulé une faute de grammaire dans mon texte à vérifier, le correcteur ne l'a pas vu; est ce normal?
> La faute était: nous avons constaté remplacé par nous avons constatés.

Not sure what the user means

**Comment by dpelle** [comment]
I think what is meant is that LT did not find an error in "Nous avons constatés"  (correct would be "Nous avons constaté").
Actually, I just tried it and LT finds the mistake in that sentence and even proposes the expected correction.
I suppose that the sentence of the user was more complex. The feedback is too unclear, without a concrete sentence to reproduce it.

Note that "nous avons constatés" can be correct in a more complex sentences as in this example:
"Les problèmes que nous avons constatés".
