### ISSUE TITLE
[pt-br] user feedback "Diretor executivo"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3827]
> Utilizo a Linguagem Portugues (Brasil pós AO). 
>
> Estou consultando a palavra Diretor executivo
>
> Ele pede para colocar o hifen, e ficaria Diretor-executivo.
>
> Peço que verifiquem pois pós AO, deve ser retirado o hifen... 
>
> Obrigado!

**Comment by marcoagpinto** [comment]
It continues to have an hyphen:
https://dicionario.priberam.org/diretor-executivo

**Comment by tiff** [comment]
Thanks
