### ISSUE TITLE
Rule DE EMAIL[6] targets half words

### ISSUE THREAD

**Issue by Xaratas** [languagetool-org/languagetool#383]
> 2291.) Line 6728, column 20, Rule ID: EMAIL[6]
> Message: Meinten Sie 'E-Mail'?
> Suggestion: E-Mail
> ...Wunden nicht aufhalten.“  Dieser dunkelgrüne emaillierte Stahlbrustpanzer war das Eigentum von ...
>                                                 ^^^^^                                             
> More info: http://www.korrekturen.de/beliebte_fehler/email.shtml
> 

„emaillierte“ ist eindeutig kein Fall von E-Mail

Test mit Languagetool 3.3, ebenso im aktuellen Snapshot:
http://community.languagetool.org/rule/show/EMAIL?lang=de-DE

Bonus: Der korrekte Beispielsatz „Das ist Email.“ in der Regel soll was aussagen? In deutsch ergibt das keinen Sinn. Sollte es „Das ist eine E-Mail.“ sein?

**Comment by danielnaber** [comment]
Danke, ist korrigiert und geht heute Abend online. "Das ist Email" ist schon richtig, z. B. in "Woraus ist das Schild? -- Das ist Email". Ich habe den Satz entsprechend geändert.
