### ISSUE TITLE
[en] Chunker: improve the analysis for singular determiner with a noun can be both singular and plural

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3847]
The plural of 'box' can be 'box', if the word refers to a tree: https://www.merriam-webster.com/dictionary/box. LT has box/NNS, and I do not suggest that we change that POS.

For these sentences, the chunker analyses the noun phrase as plural:
- This is a box.
- This is a small box.
- This is an unusually large box.

![image](https://user-images.githubusercontent.com/5816160/98971805-8caccb80-2509-11eb-8be0-62bd57af2613.png)

Is it possible to change the chunker such that it uses the article to give a better analysis?
`Singular article + adjectives + singular noun = singular noun phrase`

**Comment by danielnaber** [comment]
> Is it possible to change the chunker such that it uses the article to give a better analysis?

Unfortunately, the English chunker is an external component that's difficult to change (it would require training).

**Comment by MikeUnwalla** [comment]
OK, thanks Daniel.
