### ISSUE TITLE
Causes Constant Scrolling

### ISSUE THREAD

**Issue by christopher-taylor** [languagetool-org/languagetool#3849]
In firefox latest when I connect to an EC2 instance on AWS it continually scrolls the viewport ten pixels a second. This makes the extension unusable (I have to connect to EC2 instances in my browser constantly for my job) and I had to uninstall the extension as a result.

Gif of the problem
https://imgur.com/a/2mcjAGz

**Comment by danielnaber** [comment]
Hi Christopher, thanks for the report. Just to make sure, turning off the add-on by clicking the "LT" in the browser's toolbar was not enough?

![screenshot-2020-11-13-00:25](https://user-images.githubusercontent.com/857004/99008612-ccde6f00-2546-11eb-85fd-0059c4649fc8.png)

**Comment by danielnaber** [comment]
Closing, as there was no further feedback.
