### ISSUE TITLE
[ca] user feedback

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3851]
> Problemes amb les subordinades de relatiu. Donada l'oració "Els animals que conviuen a l'hort tenen potes", la màquina entén que després del pronom relatiu "que" cal un substantiu.
A les subordinades de relatiu, com aquesta, no és necessari. 
Gràcies!

**Comment by jaumeortola** [comment]
It makes no sense. The sentence is correct, and LanguageTool says nothing (rightly). Perhaps the user is referring to another sentence, and is making up this one. Can we ask?

**Comment by jaumeortola** [comment]
I close the issue. It makes no sense unless there is more information.

**Comment by tiff** [comment]
@jaumeortola sorry for my delayed response. This user didn't answer me unfortunately.
