### ISSUE TITLE
LibreOffice - Add-on crash

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#3863]
Hello!

Last night there was no nightly, but I have installed the one from two days ago.

It crashed while editing a .docx in LibreOffice:
![lt_libreoffice_addon_crash_20201116](https://user-images.githubusercontent.com/5192600/99224633-9a4ea380-27de-11eb-8c7c-33ffd3e15d00.png)

**Comment by danielnaber** [comment]
Fixed according to commit log, so can this issue be closed?

**Comment by FredKruse** [comment]
The issue is solved. I close it.
