### ISSUE TITLE
[fr] word suggestion: "CNI"

### ISSUE THREAD

**Issue by L0Lock** [languagetool-org/languagetool#3873]
I suggest adding the acronym "CNI" in the French dictionary.

"CNI" stands for « Carte Nationale d'Identité » (National Identity Card), it is the official administrative term for ID cards in France and is very often used in legal or administrative text.

 - « [_Réaliser une pré-demande de carte nationale d'identité (CNI)_](https://passeport.ants.gouv.fr/Vos-demarches/Realiser-une-pre-demande-de-carte-nationale-d-identite-CNI) » - Agence Nationale des Titres Sécurisés
 - « [_Carte nationale d'identité en France_](https://www.wikiwand.com/fr/Carte_nationale_d%27identit%C3%A9_en_France) » - Wikiwand
 - « [_Carte d'identité_](https://www.wikiwand.com/fr/Carte_d%27identit%C3%A9) » - Wikiwand

**Comment by jaumeortola** [comment]
Thank you. I will add it as a feminine and a masculine noun because it can be both: https://fr.wikipedia.org/wiki/CNI
