### ISSUE TITLE
[de] Automatic language detection for de-CH

### ISSUE THREAD

**Issue by ced-mos** [languagetool-org/languagetool#3879]
Currently for the following text the automatic language detection would recognize 'de-DE' where it should be 'de-CH', due to the missing ß in grosses.

> Grosses entsteht im Kleinen.

As a workaround I found the parameter 'preferredVariants', where I could add 'de-CH' and it would prefer 'de-CH' instead of 'de-DE'. 

Would it be possible to change the automatic recognition to differentiate between de-CH and de-DE? As I understand a simple detection could be to count the number of ß per two ss's in the text and select for 'de-CH' if the fraction is lower than a given threshold (e.g. 0.2).

**Comment by danielnaber** [comment]
> Would it be possible to change the automatic recognition to differentiate between de-CH and de-DE?

I'm not convinced we should do that. We want detection to work with very short text, too. These text might not have a single instance of ss/ß, or it might even be from Germany with someone misspelling "ß" as "ss" (quite common).

**Comment by ced-mos** [comment]
As you mentioned, my idea would only work if the text is longer and would contain multiple 'ß's. In addition I am not aware how common the misspelling of using 'ss' instead of 'ß' for "original" german writer is.

My question is mainly about if you could add some "hard" coded rules to make the prediction better for longer texts without breaking the whole structure code? I ask because I don't know how the automatic recognition currently works.

In addition my intention was not create a perfect but a better recognition. If I assume that the misspelling for German writers from Germany is only done occasionally, you could set the threshold that in case of doubts you would always pick 'de-DE'.

**Comment by danielnaber** [comment]
The language detection is quite complicated already, but it's based on the assumption that we shouldn't even try to detect variants. We can get indicators elsewhere, e.g. the user's browser settings. This is more predictable than using another threshold.

**Comment by ced-mos** [comment]
Sounds reasonable. This would not work in my case because I use your local server installation in addition with a Visual Studio Code plugin.

How does it work for the English language? Do you always pick the American English or do you distinguish between American, British, ... English?

**Comment by danielnaber** [comment]
For English, we also rely on external data (browser settings) to "detect" (i.e. pre-select) a variant.

**Comment by ced-mos** [comment]
Do you rely on the header information of the request or do you use your API variables such as 'altLanguages', 'motherTongue' or 'preferredVariants' and fill those before submitting?

I just tried with the following command if it detects that the given text should be 'en-GB' but it always recognizes 'en-US'.

`curl --data "language=auto&text=My beloved colour is red. Why do you organise the party that late? I’ve eaten too much." http://localhost:8081/v2/check -v -H 'Accept-Language: en-GB' -A "Mozilla/5.0 (Windows NT 6.1;en-GB ;Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"`

**Comment by danielnaber** [comment]
We set `preferredVariants` for each request.

**Comment by ced-mos** [comment]
Oke, slowly I see what could work and what not.

> > Would it be possible to change the automatic recognition to differentiate between de-CH and de-DE?
> 
> I'm not convinced we should do that. We want detection to work with very short text, too. These text might not have a single instance of ss/ß, or it might even be from Germany with someone misspelling "ß" as "ss" (quite common).

As I understand it, my explained rule could work for longer texts. But this would mean that you would have a different recognition algorithm for shorter and longer texts, which does not make it easier to debug and explain them to other people.

Therefore I would also argue to leave it as it is and close the issue, if you don't see a reliable solution for longer texts.
