### ISSUE TITLE
LibreOffice add-on: Doesn't detect all errors in Portuguese

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#3881]
Hello!

I saw this happening when I tested it a few nightlies ago, but since there were major improvements going on in the add-on, I decided to wait for the last nightly.

The add-on isn't detecting all errors, at least in PT.

The last paragraph of the attached ODT has a few hits but none is shown:
![LT_nightly_20201117](https://user-images.githubusercontent.com/5192600/99499596-0c56f200-2971-11eb-9cb2-6a0e56c968a6.png)

If you copy/paste the paragraph into the LT site it will show more hits.

See attached document (it is huge because it has HD images).
[MCAT_Translation_60PT_unsent.zip](https://github.com/languagetool-org/languagetool/files/5558475/MCAT_Translation_60PT_unsent.zip)

**Comment by marcoagpinto** [comment]
@FredKruse 

Any news regarding this issue?

Thanks!

**Comment by FredKruse** [comment]
@marcoagpinto: This bug is a bit complicate. There was a bug in the LO/OO extension regarding language handling. I just commit a fix. But this is only one part of the story. Another problem regards LO itself. The language detection is not the best. The language of the sentence you mentioned above is set to English by LO. There are two possibilities to get the right full check

1. in LO: set the whole text to Portuguese
2. in LT options. Set the language of check to Portuguese (default is use language of text)

So please test the text with the new build tomorrow, but use one of the options.

**Comment by marcoagpinto** [comment]
@FredKruse 

Hello!

Only now I had the chance of testing it.

Even if I change the whole language of the document to pt-PT, it still doesn't detect the three errors in the last paragraph:
"Anon: Tenho usado os anéis faz quase um mês. Fiquei surpreso porque senti os efeitos (efeitos muito óbvios) quase instantaneamente após os colocar. Tive de facto problemas em adormecer com eles no início, mas pareço ter-me habituado agora porque durmo muito bem. Mais ainda, acordo sem problemas quando costumava ter problemas no passado. Também, os problemas de pele que parecia ter, foram-se. E, parece afetar também o estômago, mas de uma forma positiva. Há alguns dias comecei a ter sensações nos meus olhos, mas a minha visão parece ter de facto melhorado, parece agora melhorar gradualmente todos os dias. Uso óculos desde os 6 anos, e tenho agora 19."

**Comment by FredKruse** [comment]
@marcoagpinto 
This is really strange. When I load your document in LO, the two alarms in the first sentence of the last paragraph are not detected. If I switch the language in tools menu for the whole text to Portuguese, the marks are set. I tested with LO 7.0 and 6.2.8 in Linux. 
With LO 7.0 in Windows I got a bit strange behavior of LO. LT doesn't work, till I switched the whole text to Portuguese saved it and load it again. After that LT seams to work correct. I will analyze this problem, but it will take some time.

**Comment by marcoagpinto** [comment]
Thanks for trying to solve it.

**Comment by FredKruse** [comment]
@marcoagpinto: The problems should be solved in the current snapshot. But you have to set the Language of the whole text, or only of the incorrect tested sentence to Portuguese. LO detects this sentence as English, probably because the first word (Anon) is detected as English.
Please test it.

**Comment by marcoagpinto** [comment]
@FredKruse:

Yes, the problem is fixed!

Thanks!
