### ISSUE TITLE
[en] False warning MORFOLOGIK_RULE_EN_US

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#3889]
The spelling 'daddy longlegs' is correct in AmE and Bre:

> Is the spelling **daddy longlegs** or daddy-long-legs?

References
https://www.ldoceonline.com/dictionary/daddy-longlegs
https://www.lexico.com/definition/daddy-long-legs
https://www.merriam-webster.com/dictionary/daddy%20longlegs

**Comment by danielnaber** [comment]
I cannot reproduce anymore, can this issue be closed?

**Comment by MikeUnwalla** [comment]
I cannot reproduce the problem either.
