### ISSUE TITLE
testrules: test all rules, as specified in the documentation

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#389]
Testrules "will always test all rules, so we recommend you use that during rule development" (http://wiki.languagetool.org/development-overview).

In LT 3.3, testrules for English does not check the rules that are in \org\languagetool\rules\en\en-GB\grammar.xml. 

If possible, please make testrules check all the grammar files for a language.

**Comment by danielnaber** [comment]
You're talking about calling `testrules.bat en`, aren't you? I'm not sure, the next person might prefer the current behaviour, as they might *not* want to test the variants. If you always want to test all language variants, you could add your own `.bat` script that just calls `testrules.bat en`, `testrules.bat en-GB`, and `testrules.bat en-US`?

**Comment by MikeUnwalla** [comment]
Thanks. You suggestion solves my problem.
