### ISSUE TITLE
[es] user feedback: "mama" vs "mamá"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3895]
> In Spanish mom has a tilde on the last (a) and language tool overlooked that one word.

> Tu mama está muy enojada. 

@jaumeortola maybe we can do something about this?

**Comment by udomai** [comment]
@jaumeortola, [I just discovered](https://dle.rae.es/mama?m=form) that "mama" (sin tilde) can also be used for "mom", and not just for the organ. But it appears to be less common.

This made me think of your `replace_unusual.txt`, maybe it can be placed in there?

**Comment by tiff** [comment]
Maybe a style rule saying that "mama" is less common than "mamá". We have such rules for other languages as well (German, English)

**Comment by jaumeortola** [comment]
This was asked also in July by a user (Daniel sent me a mail). I created a rule, and it seems to work fine in this sentence.
Why is it not working for this particular user now?

![image](https://user-images.githubusercontent.com/4289501/99782691-cbe6a800-2b19-11eb-8452-6fe00c01760d.png)

**Comment by tiff** [comment]
Hm, sorry. I didn't see that. Closing.

**Comment by udomai** [comment]
P.S.: This is one of those errors that for some unknown reason do not show up on languagetool.org. Once the old website will be replaced, this problem will disappear.
