### ISSUE TITLE
[fr] error not caught "Rend-toi" vs "Rends-toi"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3909]
User feedback
> Il y a une erreur :
> "Rend-toi en boutique !"  n'est pas considéré comme une erreur or il faudrait écrire "Rends-toi en boutique" (impératif des verbes du 3e groupe)

**Comment by jaumeortola** [comment]
I have written rules to check this kind of errors in French. But for this case, I guess we need to know that the verb is pronominal (`se rendre`). Can we create a list of verbs that are usually pronominal, @udomai?

**Comment by udomai** [comment]
@jaumeortola, I think a simple heuristic would do an even better job. This phenomenon is not just about reflexive verbs, but about any enclitic pronouns attached to the imperative. Example: _Rends-moi mes clés !_

We should check for any verb form that is not `V imp.*` directly followed by a hyphen and all the enclitic pronouns (`[mt]oi|l(a|es?)|[nv]ous|leur|en|y) and correct it to the imperative form.

(This mistake will happen mostly for the verbs in _-re_ and in the 2nd person singular.)

**Comment by jaumeortola** [comment]
Yes. There is indeed a TO-DO comment in the rule NONVERB_PRON for this. We need to separate the rule in imperative and interrogative verbs. So:
* imperative verb + `-([mt]oi|l(a|es?)|lui|[nv]ous|leur|en|y)`
* interrogative verb + `-(je|tu|il|elle|nous|vous|ils|elles)`
Is this complete or is something more needed?

**Comment by udomai** [comment]
Cool!

> * interrogative verb + `-(je|tu|il|elle|nous|vous|ils|elles)`
> 
> Is this complete or is something more needed?

This list also needs `on` in it.

So these `-([mt]oi|l(a|es?)|lui|[nv]ous|leur|en|y)` can only follow the imperative form, except for _nous_ and _vous_ which can also have any verb form in the 1st and 2nd person plural.

And, inversely,  these `-(je|tu|il|elle|on|nous|vous|ils|elles)` can only be preceded by a verb form in the corresponding person and number (_-je_: 1st person singular, _-tu_ 2nd person singular, etc.), except except for _nous_ and _vous_ which can also have an imperative before them.
