### ISSUE TITLE
[pt-br] feedback "A familia"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3911]
> Na frase, ''A familia dele é bonita'', o corretor LanguageTool vê na expressão ''A familia'' como errado, não devido à falta do acento (o que deveria ser mostrado isso), mas sim, como uma palavra toda junta: ''afamilia''. Peço encarecidamente que corrijam isso.

cc @marcoagpinto

**Comment by tiff** [comment]
Another similar case:
> Toda vez que você fala ''uma familia'' o corretor acha que está errado.
![screenshot](https://user-images.githubusercontent.com/37363/100062887-9ea73c00-2e30-11eb-93eb-ae4d586b330e.jpg)

**Comment by marcoagpinto** [comment]
I will take a look in a couple of hours.

I was almost the entire night at the computer as I couldn't sleep.

🙂

**Comment by jaumeortola** [comment]
This is related with the "wrong split words" feature. I will take care of it.

**Comment by marcoagpinto** [comment]
@tiff 

I was just checking if "família" was in the speller and it is.
A familia é muito importante.
A família é muito importante.

It must be a LanguageTool issue checking the spelling.

**Comment by jaumeortola** [comment]
I can implement the same fix we applied to French. But a more permanent solution is to use Morfologik instead of Hunspell as a speller. Is there a reason why we use Hunspell and not Morfologik for Portuguese, @danielnaber? We have 4 different Portuguese Hunspell dictionaries.

**Comment by danielnaber** [comment]
> Is there a reason why we use Hunspell and not Morfologik for Portuguese

I don't remember... typical reasons would be the need to compounds, but I guess Portuguese doesn't have them? If you try Morfologik, please make sure to run regression tests with enough data before you activate it (and maybe search the forum and bug tracker to see if this has been discussed before).

**Comment by jaumeortola** [comment]
This issue is fixed. I open a new one for trying the Morfologik speller.  #3925
