### ISSUE TITLE
[es] "en base a"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3912]
The user just sent this:
> "en base a" is correct in spanish :)

I'm not sure what he means, feel free to close this issue.

**Comment by jaumeortola** [comment]
Grammars and stylebooks recommend not to use "en base a" (more or less strongly), but it is certainly widely used. 

This is the weakest recommendation I found:
>La construcción 'con base en' resulta preferible a la variante 'en base a', aunque esta ya se encuentra muy extendida en el uso y su empleo no puede censurarse. https://www.fundeu.es/recomendacion/con-base-en-mejor-que-en-base-a/

For me, it makes sense as a style rule. Now we say: “It is preferable to use another expression.” But it could become a picky rule. @udomai
