### ISSUE TITLE
> is incorrectly escaped as &gt; in the online tool

### ISSUE THREAD

**Issue by xPaw** [languagetool-org/languagetool#392]
Language appears to be irrelevant, noticed this when I tried to spell check a sentence which contained `<div>`.

Checking `<>` results in `&lt;&amp;gt;` returned by the API, but should be `&lt;&gt;`, which means there's a double escape going on somewhere.

**Comment by danielnaber** [comment]
Thanks for the report, could you re-open this issue at https://github.com/languagetool-org/languagetool-website/issues?

**Comment by xPaw** [comment]
Sure. https://github.com/languagetool-org/languagetool-website/issues/15
