### ISSUE TITLE
NullPointerException in OO/LO for "Check Text"

### ISSUE THREAD

**Issue by ChristianPervoelz** [languagetool-org/languagetool#3920]
**Steps**

1. Create new writer document in OO/LO
2. Paste this text:

> Er trug ein langes Gewand. Sein Wanderstab war alt.
> Das kann nicht richtig sein.
> Oder etwa doch.
> Ist vielleicht der Text zu kurz, oder zu lang, oder zu wenige Wörter?

3. Click the "Check Text" Button in the toolbar (the magnifier)

**Result**
`paragraphContainer == null - ParagraphCache not initialised
java.lang.NullPointerException
	at org.languagetool.openoffice.SpellAndGrammarCheckDialog$LtCheckDialog.getNextError(SpellAndGrammarCheckDialog.java:1457)
	at org.languagetool.openoffice.SpellAndGrammarCheckDialog$LtCheckDialog.gotoNextError(SpellAndGrammarCheckDialog.java:1288)
	at org.languagetool.openoffice.SpellAndGrammarCheckDialog$LtCheckDialog.show(SpellAndGrammarCheckDialog.java:1192)
	at org.languagetool.openoffice.SpellAndGrammarCheckDialog.run(SpellAndGrammarCheckDialog.java:133)`

In Writer a message dialog pops-up telling the user about that exception.
![NPE_On_Check](https://user-images.githubusercontent.com/24943047/100116489-18144e00-2e74-11eb-801b-91a05c9e459e.PNG)

Although it is not a crashing issue, it might be disturbing for users to see it.

**System**
Windows 10, Java 13, Language Tool 5.1.2, LibreOffice 7.0.3.1

**Comment by danielnaber** [comment]
Could you see if this still happens with 5.1.3 or the latest snapshot (https://internal1.languagetool.org/snapshots/)?

**Comment by ChristianPervoelz** [comment]
Still reproducible with v5.1.3.

Snapshot [LanguageTool-20201128-snapshot.oxt](LanguageTool-20201128-snapshot.oxt) works.

**Comment by FredKruse** [comment]
The problem should be solved with the 5.2-snapshot. Since 5.1 a lot of work is done to make the spelling dialog stable. The info window is correct. There are no errors in your short text (tested using the default options).

**Comment by danielnaber** [comment]
Closing, assuming it has been fixed. Please reopen if it still happens.
