### ISSUE TITLE
[DE] Fehlalarm zur Präsentationszwecken

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#3926]
Moin liebes LangaugeTool-Team

Das Outfit verstößt gegen die Uniformpflicht, aber es gibt eine Ausnahme, nämlich **zur Präsentationszwecken** dürft ihr euch in der Schule umziehen. 
LT: "Möglicherweise fehlende grammatische Übereinstimmung des Numerus (Einzahl, Mehrzahl - Beispiel: ‚das Fahrräder‘ statt ‚die Fahrräder‘)."
![grafik](https://user-images.githubusercontent.com/40240507/100245379-46f3f800-2f38-11eb-94f0-2d95741b72f3.png)

Für mich ist das ein Fehlalarm und die Vorschläge sind hier falsch. Korrigiert mich, wenn ich falsch liege.

Grüße Dallun511

**Comment by danielnaber** [comment]
"zu Präsentationszwecken" wäre richtig, ist also kein Fehlalarm...

**Comment by Dallun511** [comment]
Dann habe ich zu stark auf die Vorschläge geachtet.
