### ISSUE TITLE
New confusion sets on 3.4-SNAPSHOT

### ISSUE THREAD

**Issue by MathieuLoutre** [languagetool-org/languagetool#393]
Hi there,

I'm trying to use the latest snapshot version (3.4) but unfortunately it looks like the new confusion sets aren't working. Do I need to enable these somewhere? Is there additional things to download/build or should it work out of the box?

I can see it does work on the homepage, but no luck locally. Any tips?

This project looks extremely promising and I'm looking forward to being able to contribute back. Thanks for the great work so far!

**Comment by danielnaber** [comment]
Using the confusion sets is documented at http://wiki.languagetool.org/finding-errors-using-n-gram-data

**Comment by MathieuLoutre** [comment]
Thanks for the quick reply @danielnaber. I overlooked that page for some reason.

Sorry if this is inappropriate, but it seems like a strange design decision to still have to carry the 8Gb of n-gram data around to use the confusion sets. Intuitively I thought the sets were used to generate the confusion rules but weren't needed once these were generated. I must confess I'm pretty clueless about the internals of LanguageTool at the moment, but it would be a great step forward if it somehow could be bundled as a smaller ruleset. Do you foresee the n-gram data to still be necessary to include in the future?

**Comment by danielnaber** [comment]
For the ngram rule, the data will be needed. Shrinking it to only the ngrams actually used is too much work and removes all flexibility (like adding new sets without re-generating the whole data set). Data might be smaller in the future if we find a machine learning approach that works as well as or better than the ngram approach. Help with that would be very welcome.

**Comment by MathieuLoutre** [comment]
I've just managed to download and extract the whole n-gram archive on my machine. I'm trying to use it programatically so I'm calling `.activateLanguageModelRulesSync`. However, I get:

```
java.lang.RuntimeException: Not found or is not a directory: ./google-ngram-index/en
	at org.languagetool.languagemodel.LuceneSingleIndexLanguageModel.validateDirectory(LuceneSingleIndexLanguageModel.java:57)
	at org.languagetool.languagemodel.LuceneSingleIndexLanguageModel.doValidateDirectory(LuceneSingleIndexLanguageModel.java:107)
	at org.languagetool.languagemodel.LuceneSingleIndexLanguageModel.<init>(LuceneSingleIndexLanguageModel.java:88)
	at org.languagetool.languagemodel.LuceneLanguageModel.<init>(LuceneLanguageModel.java:65)
	at org.languagetool.language.English.getLanguageModel(English.java:146)
	at org.languagetool.JLanguageTool.activateLanguageModelRules(JLanguageTool.java:298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

There is indeed no `/en` subfolder in what I downloaded. I've tried pointing it to the `3grams` folder without success. What am I doing wrong?

**Comment by danielnaber** [comment]
You need to point it to a directory which contains an `en` folder, which then again contains the `3grams` etc. folders.

**Comment by MathieuLoutre** [comment]
Wonderful! I wonder why I didn't think about this earlier... I thought I could be missing some files. Thanks!

**Comment by danielnaber** [comment]
I guess this issue can be closed.

**Comment by mdasadul** [comment]
I downloaded google n-gram data and I want to use more data along with google data. I am also interested to add more confusion set from my additional data. I can create Lucene index(1-gram,2-gram, 3-gram) from my data. My query is how can I merge google n-gram lucene index and my lucene index

**Comment by danielnaber** [comment]
You can use Lucene's tool for that: http://stackoverflow.com/questions/26051651/ - please post further questions to http://forum.languagetool.org.
