### ISSUE TITLE
[es] user feedback "super suave"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3936]
> Super suave (in spanish) must be accepted and not trying to correct to "supersuave" because it doesn't exist.

**Comment by jaumeortola** [comment]
The user is wrong. It is explained in the message: `Como prefijo de un adjetivo, 'super-' se escribe junto, aunque la palabra resultante no esté en el diccionario.`
I will add the word to the dictionary, and also a URL to the rule.
