### ISSUE TITLE
[DE][BUG] Doppelte Menüzeile unter Ubuntu 20.04 LO 6.4.3.2

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#3938]
Moin liebes LanguageTool-Team

**Wichtig! OpenOffice ist nicht betroffen, nur LibreOffice.**

![grafik](https://user-images.githubusercontent.com/40240507/100528026-65781e80-31d8-11eb-8160-49a0be388444.png)
Auf dem Bild sehen wir, dass die Menüzeile verdoppelt wurde. Das sieht im ersten Moment nach einem Fehler aus, der nicht bei der Arbeit stört. Ich muss ehrlich sagen, zuerst nervt das nicht, bis ich ein wenig herumgespielt habe.

Die Menüzeilen sehen auf dem ersten Blick exakt gleich aus, aber das ist ein Irrtum, denn sie sind verschieden, und zwar im Detail. Die erste Menüzeile ist die echte Menüzeile. Die zweite Menüzeile durch irgendwas genieriert und ist verbuggt. Über die zweite Menüzeile ist es nicht möglich ein neues Dokument zu öffnen. Das funktioniert nur bei der ersten Menüzeile.

![grafik](https://user-images.githubusercontent.com/40240507/100528173-ed125d00-31d9-11eb-8998-732907cbe605.png)
Auch weitere Funktionen sind nicht anwählbar, die zu Komplikationen führen können. Einmal der Bug da, verbleibt er erstmal, bis man anfängt zu arbeiten oder verbleibt, bis man das letzte Dokument beendet.

Beim Öffnen eines weiteren Dokumentes kann es passieren, dass das Dokument so geöffnet wird.
![grafik](https://user-images.githubusercontent.com/40240507/100528291-9c9bff00-31db-11eb-8168-99263b3d336b.png)

**Zur Häufigkeit** kann ich sagen, dass dieser Bug keine Seltenheit ist und im [Ubuntu-Forum](https://forum.ubuntuusers.de/topic/doppelte-menu-zeile-unter-ubuntu-20-04-lo-6-4-/) vertreten ist. Der Bug ist, laut dem Forum, Ubuntu, Xubuntu und Lubuntu vertreten. Xubuntu habe ich getetest und kann bestätigen, dass der Bug vorhanden ist. Im [LanguageTool-Forum](https://forum.languagetool.org/t/doppelte-menu-zeile-unter-ubuntu-20-04-lo-6-4-3-2/5732/1) wurde dieser Bug gemeldet. 

Ich kann sicher sagen, dass Programme nicht Schuld sind. Das System ist frisch und aktuell. Ich habe nur das installiert, was ich brauche, um das LanguageTool zu installieren. Danke @danielnaber, denn ohne ihn hätte ich es nicht geschafft, das LanguageTool unter Linux zu installieren.

**Rekonstruktion des Bugs**
Nachdem das LanguageTool ordnungsgemäßt installiert wurde, wird **der Writter mit einem leeren Dokument gestartet. Das ist sehr wichtig, dass kein fertiges Dokument über den Dateienmgr gestartet wird.** Danach wird die Maus zur Menüleiste navigiert.
Datei -> Öffnen oder STRG + O
Ein Dateimgr. öffnet sich, und zwar der von LO.
Hier wird ein gespeichertes Dokument geöffnet.
Nachdem das Dokument vollständig geladen wurde, entsteht die zweite Menüleiste.

Nach meiner Vermutung liegt das Problem beim Laden eines Dokuments durch den Dateimgr. von LO. Das LanguageTool provoziert hier ein Ereignis, welches die doppelte Menüzeile entstehen lässt. 

Die Frage, die hier ganz wichtig ist. **Wo liegt genau das Problem?** **Muss man mit dem Entwickler von LO oder sogar mit dem Entwickler von Ubuntu zusammenarbeiten?** 

Bisher scheint das Problem nur bei Linux-Version das Licht der Welt zu erblicken, die Ubuntu oder eine auf ein ubuntu-Versionbasierendes Betriebssystem nutzen. Unter Windows 10 gibt es diesem Bug nicht und ihr wisst ja, ich arbeite sehr viel mit dem LanguageTool. So ein Bug hätte ich sonst sofort versucht zu provozieren.

Ich würde mich freuen, wenn ihr das Problem schnellstmöglich beheben könntet.

Mit freundlichen Grüßen
Dallun511 Ferewo

***
**Getestete Versionen**
LanguageTool-20201128-snapshot.oxt
LanguageTool-20201201-snapshot.oxt
LanguageTool-20201216-snapshot.oxt

**Comment by speedy-10** [comment]
Kann ich bestätigen, schon hier geposted und nach Lösungen gesucht:
https://forum.ubuntuusers.de/topic/doppelte-menu-zeile-unter-ubuntu-20-04-lo-6-4-/
LG

**Comment by FredKruse** [comment]
Das Problem ist bekannt. Es hängt mit dem GTK3 unter Linux zusammen. Wenn man das deinstalliert, verschwindet der Fehler, allerdings sieht LibreOffice dann auch nicht mehr gut aus.
Ich habe schon viel Zeit in das Problem gesteckt. Bei mir verschwindet mittlerweile die doppelte Menüleiste nach kurzer Zeit wieder. Daher kann ich momentan auch nichts testen.
@speedy-10 und @Dallun511: Wenn euch ein Zusammenhang auffällt, wann die Leiste erscheint und wann sie wieder verschwindet, meldet das bitte hier. Vielleicht kommt mir noch eine Idee.

**Comment by speedy-10** [comment]
Hi FredKruse, wenn ich eine Datei aus LO mit Languatool 5.3. öffnete, dann kam direkt eine doppelte Zeile. Wenn ich hingegen eine datei im Nautilus-Dateimanager doppelklicke (unda damit erst LO öffne) passiert das nicht.
Nähere Infos sind u.g. link zu finden.

**Comment by FredKruse** [comment]
Wenn die doppelte Menüleiste auftritt, verschwindet sie dann wieder, z.B. wenn du in das Dokument klickst oder die Größer veränderst?
Bei mir tritt sie nur manchmal auf und verschwindet wieder nach wenigen Augenblicken.

**Comment by speedy-10** [comment]
Bei mir bleibt sie, bis ich LO schließe; ich konnte auch eine 3. Zeile erzeugen.

**Comment by FredKruse** [comment]
Was für ein System nutzt du, Ubuntu, Linux Mint oder ein anderes Linux? Bitte schreib auch die Version auf. Ich versuche das mal in den nächsten Tagen nachzustellen.

**Comment by Dallun511** [comment]
Ich habe xubuntu-20.04.1-desktop-amd64 für das Nachstellen des Bugs genutzt. Das funktioniert auch unter einer VM. Ich habe das Xubuntu nicht nativ installiert.

**Comment by speedy-10** [comment]
Wie auf ubuntuusers geschrieben:

> Problem taucht bei mir wieder mit neuerem Languagetool auf:

    Ubuntu 20.04 5.4.0-53-generic

    Languagetool-5.1.3

**Comment by FredKruse** [comment]
@Dallun511 , @speedy-10 :
Jetzt habe ich sowohl die aktuellen Versionen von Ubuntu als auch Xubuntu installiert. Beide Systeme haben die Version 20.04.01 mit den aktuellen Updates. Die LibreOffice Version ist 6.4.6.2 in beiden Systemen. Installiert ist libreoffice-gtk3 (ich glaube das ist wichtig, weil es die Oberfläche bestimmt). Installiert habe ich LT-5.2-snapshot (das sollte für diese Problematik aber keinen Unterschied zur 5.1.3 machen).
Ich habe etwa 50 Dokumente geöffnet (auch immer wieder von einem leeren ausgehend). Einmal ist eine zweite Menüzeile aufgetaucht, die aber nach Bruchteilen von Sekunden wieder verschwunden ist.
Das ist die gleiche Erfahrung, die ich auch mit dem von mir bevorzugt verwendeten Linux Mint mache (das beruht auch auf der Ubuntu Version 20.04.01).
Insgesamt denke ich, dass es ein LibreOffice Problem ist, dass scheinbar mit den neusten Updates gelöst sein sollte. Versucht bitte eine Aktualisierung eurer Systeme und überprüft, ob libreoffice-gtk3 installiert ist (nicht libreoffice-gtk oder libreoffice-gtk2).

**Comment by speedy-10** [comment]
Hi, ich habe am WE LO über das offizielle PPA [https://launchpad.net/~libreoffice/+archive/ubuntu/libreoffice-6-4] aktualisiert auf:

Version: 6.4.7.2
Build-ID: 1:6.4.7-0ubuntu0.20.04.1~lo1

Sowohl mit languagetool 5.1.1 und 5.1.3 konnte ich keine doppelten Menu-Einträge provozieren.

Werde in den nächsten Tagen das Standard-LO mit einem neu augesetzten Ubuntu 20.04 nochmal testen und ggf. hier posten.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/101547998-73cdf380-39ab-11eb-88b6-786ee8e2b946.png)
Nachdem ich mehrmals "apt-get update" und "apt-get upgrade" in der Shell durchgeführt habe, ist mir auch das Update gelungen.

Die doppelten Menüleiste verschwindet sofort nach dem Start oder erscheint erst gar nicht. Ich muss nur sagen, dass mir auf gefallen ist, dass die Symbolleiste von LT zuerst gestartet wird, als die Symbolleisten von LibreOffice selbst.

Grüße Dallun511

**Comment by speedy-10** [comment]
Hi, frisch installiertes Ubuntu:
LO Version: 6.4.6.2
Die doppelte Menuzeile erscheint nur kurz beim Öffnen der 1. Datei, danach nicht mehr, daher ist das ok. Ansonsten den o.g. link für das PPA benutzen, falls es doch stört.

**Comment by Dallun511** [comment]
Ich warte noch eine Woche. Falls noch was kommt. Nach der Woche schließe ich das Issue
Grüße Dallun

**Comment by Dallun511** [comment]
Issue schließe ich jetzt.
@speedy-10 melde den Forum, dass das Problem gelöst ist, und zwar bitte mit einem neuen Kommentor, damit die anderen informiert werden. Mit einer Bearbeitung des letzten Kommentars werden sie nämlich nicht informiert.

Grüße Dallun511

**Comment by speedy-10** [comment]
Issue kann nun geschlossen werden aus meiner Sicht.

**Comment by Dallun511** [comment]
@speedy-10 Ich meinte das Ubuntu-Forum, denn dieses Issue ist bereits geschlossen.

**Comment by speedy-10** [comment]
Dort habe ich es bereits am 7.12. als gelöst markiert.
