### ISSUE TITLE
[uk] feedback on twitter

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3939]
Feedback - as I don't speak Russian, I cannot tell if it's useful:

https://twitter.com/arunninghacker/status/1333031105830801410

**Comment by yakovru** [comment]
Hello, Daniel
A tweet with an error in the Ukrainian language.
Other tweets on the page are in Russian.

  
>Воскресенье, 29 ноября 2020, 15:55 +03:00 от Daniel Naber <notifications@github.com>:
> 
> 
>Feedback - as I don't speak Russian, I cannot tell if it's useful:
>https://twitter.com/arunninghacker/status/1333031105830801410
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--

Yakov Reztsov

**Comment by arysin** [comment]
Thanks, this will be added in the next version of the dictionary.
