### ISSUE TITLE
[DE]Fehlalarm mit war

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#3940]
Moin liebes LanguageTool-Team

Das andere Ende **war** am rechten vorderen Bettpfosten.
LT: "Bitte prüfen, ob hier „waren“ stehen sollte."
Das Ende ist Singual, weswegen war richtig ist. Wieso das LanguageTool hier Plural sieht, ist mir ein Rätsel.

Grüße Dallun511

**Comment by udomai** [comment]
Ich musste die Commits leider wieder zunichtemachen, weil dadurch [hier viele FPs](https://internal1.languagetool.org/regression-tests/via-http/2020-12-10/de-DE/result_java_DE_AGREEMENT.html) entstanden sind.

**Comment by f-knorr** [comment]
@udomai Jetzt sollte es keine FP mehr geben.
