### ISSUE TITLE
[es] suggest "LanguageTool"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3942]
![Bildschirmfoto 2020-11-30 um 07 23 30](https://user-images.githubusercontent.com/37363/100575727-0223e480-32dd-11eb-8f53-33444de13ea6.png)

I think we should have a very simple rule that suggests "LanguageTool". We have the same for English, Portuguese and German, and they work very well.

**Comment by jaumeortola** [comment]
Added for Spanish, Catalan and French.
