### ISSUE TITLE
[fr] user feedback "Belges"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3943]
Not sure if I understand this user's feedback.

> Vous allez écrire quoi ? Beau article ?
Dans un autre article ; Ce ne sont pas des belges, vous mettez une majuscule, absolument pas . Il s'agit de la nationalité donc un nom commun ne prend pas de majuscule.

![Bildschirmfoto 2020-11-30 um 07 27 21](https://user-images.githubusercontent.com/37363/100576045-94c48380-32dd-11eb-825d-71275c22dd07.png)

**Comment by udomai** [comment]
The text doesn't seem too coherent... but, assuming the user is, here's what I see:

- The text seems to say that the nationality "Belge" should be written in lowercase, which is wrong. The `message` is correct.
- One thing we don't correct: _beau_ before masculine nouns starting with vowel or "silent h" must be corrected to "bel".

FN:

_Un **beau** homme._ --> bel
_**Beau** article_ --> bel
