### ISSUE TITLE
[de] False-positive with "lang" and "verklang"

### ISSUE THREAD

**Issue by ChristianPervoelz** [languagetool-org/languagetool#3947]
Sentence:
> Endlos lang zog sich der Ton dahin, aber schließlich verklang er doch.

"verklang" will be marked as already used in the same sentence. Removing "lang" will clear that hint.

**Info:**
Windows 10; Java 13; LibreOffice 7.0.3.1; LT: 5.2-SNAPSHOT (2020-11-28 19:45, 080edd0)

**Comment by FredKruse** [comment]
@ChristianPervoelz The issue is solved. Please test with the tomorrow snapshot and close the issue.

**Comment by ChristianPervoelz** [comment]
Checked with snapshot of 6th Dec. 2020 in LO - issue is gone: Closing.
