### ISSUE TITLE
LanguageTool sometimes does not work well with LibreOffice

### ISSUE THREAD

**Issue by gskoczylas** [languagetool-org/languagetool#3962]
I use _LibreOffice_ to write instructions for programmes. In these texts I use, among other things, various specific terms that should not be checked, such as product names or device names, etc. I do not want the _LibreOffice_ to mean such words as wrong. Therefore, I am used to marking these words and setting the language for them to _none_ (_do not spellcheck_).

_LanguageTool_ still marks such words as incorrect (underlines them with a green wavy line).

I use the Polish edition of _LibreOffice_, if that matters.

**Comment by FredKruse** [comment]
This is not a bug of the office integration. If you set the language of a single word to none, it has no effect to the grammar check. The language is detected by LO/OO per sentence. LT checks the sentence assuming the given language.
@gskoczylas: A green wavy line indicates a style error. Maybe you should detect the specific errors and report them to the developer of polish rules.
@danielnaber: Should this issue be closed or the label changed to Polish?
