### ISSUE TITLE
improve suggestions for rule COMMA_PARENTHESIS_WHITESPACE

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#3966]
When the error is `word1 ,word2`, a better suggestion would be "comma + white space", not just "comma", as it is now, which gives as a result `word1,word2` and triggers another error.

Is this solution okay for all languages?

**Comment by udomai** [comment]
Yes, for the comma, it's the same for ES, EN, FR, NL, and DE. Sounds like an excellent improvement to me!
