### ISSUE TITLE
[en] false alarm ADVERB_WORD_ORDER?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#3969]
A user says that this sentence is perfectly fine and our suggestion doesn't really improve the sentence.

> It has been removed from the server and should never be run there.

![Bildschirmfoto 2020-12-04 um 08 37 07](https://user-images.githubusercontent.com/37363/101135338-f7828b80-360b-11eb-9dd7-bd199493f061.png)

**Comment by udomai** [comment]
Thanks for the Feedback, @hftf! Could you look into this and improve on this rule? I think it comes down to excepting those adverbs for which the rule is not applicable, such as _never_.

**Comment by tiff** [comment]
@hftf I already fixed this specific issue. There was an antipattern missing for "MD" + "RB" + "be" + VBN ("run")

**Comment by hftf** [comment]
Ah, I didn't realize it. Well, I was working on some further improvements to it anyway – perhaps it may still be useful: #3982.

**Comment by tiff** [comment]
Great. Thanks
