### ISSUE TITLE
[pt] comma issue not found

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#3976]
User feedback about a wrong comma not being detected:

> Você pode tentar e é provável que funcione, mas não deixe ninguém, usá-la com você e levar você a dividir a diferença.

User says (I think) comma after "ninguém" should not be there.

**Comment by marcoagpinto** [comment]
@danielnaber 

He is right.

I will fix it tomorrow morning or this afternoon.

**Comment by marcoagpinto** [comment]
It is done:

https://github.com/languagetool-org/languagetool/commit/37ca246b708e4f22749fbedb1acadc6eebfcf310
