### ISSUE TITLE
[pt] FPs found on LT website

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#3978]
The following FPs have been found on the texts of the LT website. These are FPs as far as I know, this needs double-checking. If they are FPs, we need to fix the rules.

- [x] escrita clara, precisa e **estilisticamente** correta. (not in pt-PT dictionary)
- [x] Obrigado por escolher a **subscrição LanguageTool** Premium. (GENERAL_GENDER_AGREEMENT_ERRORS[5])
- [x] A sua **conta LanguageTool** gratuita foi criada com sucesso. (GENERAL_GENDER_AGREEMENT_ERRORS[5])
- [x] Já tem sessão iniciada como :logged_in, mas **está a tentar** ver um convite destinado a :invited. (VERBO_ESTAR_A_VERBO_INF[3])
- [x] Mais de **5.000** verificações adicionais para Inglês, Alemão, Francês, ... BUT NO ERROR FOUND IN: "Até 40.000 caracteres por campo de texto" (DECIMAL_COMMA[3])
- [x] 3.000+ avaliações Chrome **Store** (not in dictionary)
- [x] Verifique os seus **documentos Word** (GENERAL_NUMBER_AGREEMENT_ERRORS[1])
- [x] (até **40.000** caracteres). (DECIMAL_COMMA[2])
- [x] Quero receber atualizações ocasionais e promoções **da LanguageTool** (GENERAL_GENDER_AGREEMENT_ERRORS[6])
- [x] Basta colar uma lista de e-mails abaixo para enviar convites **a todos** eles. (GENERAL_NUMBER_AGREEMENT_ERRORS[9])

**Comment by marcoagpinto** [comment]
@udomai 

That is very strange... I translated those sentences to Portuguese and saw no errors in them using the browser add-on.

I will have a look tomorrow morning.

Thanks!

**Comment by marcoagpinto** [comment]
Ahhh... it is very strange... I was just checking with the browser add-on and some errors are reported.

I will have a closer look tomorrow morning.

**Comment by udomai** [comment]
@marcoagpinto, thank you in advance for looking into this! I appreciate your taking the time :)

**Comment by marcoagpinto** [comment]
- [1] escrita clara, precisa e **estilisticamente** correta. (not in pt-PT dictionary)

This one is fixed:
https://github.com/languagetool-org/languagetool/commit/09e00c75f2bd04a565754e12dff10a519afe19a5

https://github.com/languagetool-org/languagetool/commit/17673883a44722aad8835b4ed3baed07e577ef9a

**Comment by marcoagpinto** [comment]
- [2] Obrigado por escolher a **subscrição LanguageTool** Premium. (GENERAL_GENDER_AGREEMENT_ERRORS[5])

No error is triggered in my stand-alone tool.

Maybe I fixed it a few days ago?

![subscrição_lt_premium_20201208](https://user-images.githubusercontent.com/5192600/101425866-bf24cb00-38f3-11eb-9f03-a8610652d323.png)

**Comment by marcoagpinto** [comment]
- [3] A sua **conta LanguageTool** gratuita foi criada com sucesso. (GENERAL_GENDER_AGREEMENT_ERRORS[5])

Done!

https://github.com/languagetool-org/languagetool/commit/8e7ab88e804721a4919656c44b1fe2b51032c99f

**Comment by marcoagpinto** [comment]
- [4] Já tem sessão iniciada como :logged_in, mas **está a tentar** ver um convite destinado a :invited. (VERBO_ESTAR_A_VERBO_INF[3])

What is wrong with the suggestions?

It suggests "tenta" and "tente" which is a way of simplifying complex expressions in some situations.

**Comment by udomai** [comment]
> No error is triggered in my stand-alone tool.

Mysterious indeed! Languagetool.org definitely lights up:
![image](https://user-images.githubusercontent.com/67792088/101454746-c1a61580-3931-11eb-9c76-cbf7726080eb.png)

**Comment by udomai** [comment]
> * [4] Já tem sessão iniciada como :logged_in, mas **está a tentar** ver um convite destinado a :invited. (VERBO_ESTAR_A_VERBO_INF[3])
> 
> What is wrong with the suggestions?

The suggestions are perfectly fine! The entire rule is the problem. Any usage of the _estar + a + infinitivo_ construction is found by this rule. What's worse, it's not a style suggestion, either, but a grammar error saying "substitua por XYZ", implying that verb form is entirely grammatically wrong.

Here's what I think we should do:

- Make the entire rule a style rule.
- Write the `message` accordingly, i.e. in a softer way, something along the lines of "Em certos contextos, esta perífrasis pode ser simplificada."

- I would also strongly recommend making it more specific or excluding certain contexts. For example:

_Estás a brincar comigo?_ does not carry the same meaning as
_Brincas comigo?_

This rule is also a candidate for `tags="picky"`, as I suspect the construction is okay even in medium-formal contexts.

**Comment by marcoagpinto** [comment]
> 
> 
> > No error is triggered in my stand-alone tool.
> 
> Mysterious indeed! Languagetool.org definitely lights up: (the parentheses are the synthesizer trying to produce a masculine form of _subscrição_ or a feminine form of _LanguageTool_ and failing)
> 
> ![image](https://user-images.githubusercontent.com/67792088/101454746-c1a61580-3931-11eb-9c76-cbf7726080eb.png)

Maybe you are using Premium which I believe it is only updated every one or two weeks or so, and I fixed it shortly?

**Comment by marcoagpinto** [comment]
> > * [4] Já tem sessão iniciada como :logged_in, mas **está a tentar** ver um convite destinado a :invited. (VERBO_ESTAR_A_VERBO_INF[3])
> > 
> > What is wrong with the suggestions?
> 
> The suggestions are perfectly fine. The entire rule is the problem. Any usage of the _estar + a + infinitivo_ construction is found by this rule. What's worse, it's not a style suggestion, either, but a grammar error saying "substitua por XYZ", implying that verb form is entirely grammatically wrong.
> 
> Here's what I think we should do:
> 
>     * Make the entire rule a style rule.
> 
>     * Write the `message` accordingly, i.e. in a softer way, something along the lines of "Em certos contextos, esta perífrasis pode ser simplificada."
> 
>     * I would also strongly recommend making it more specific or excluding certain contexts. For example:
> 
> 
> _Estás a brincar comigo?_ does not carry the same meaning as
> _Brincas comigo?_
> 
> This rule is also a candidate for `tags="picky"`, as I suspect the construction is okay even in medium-formal contexts.

Good idea!

The problem is I have been adding several rules of this kind which then I apply to my thesis to improve its grammar (I am testing it on the field).

I will try to have them all pointing out: "Em certos contextos, esta perífrasis pode ser simplificada."

This will be my task to finish until Friday.

**Comment by udomai** [comment]
Cool, thank you for your help :)

**Comment by udomai** [comment]
> Maybe you are using Premium which I believe it is only updated every one or two weeks or so, and I fixed it shortly?

About this: It's definitely GENERAL_GENDER_AGREEMENT_ERRORS[5] in the Open-Source grammar.xml, which is updated every night. Are you sure that pull request was merged? The latest changes I see in the rule are from late October...

**Comment by marcoagpinto** [comment]
> > Maybe you are using Premium which I believe it is only updated every one or two weeks or so, and I fixed it shortly?
> 
> About this: It's definitely GENERAL_GENDER_AGREEMENT_ERRORS[5] in the Open-Source grammar.xml, which is updated every night. Are you sure that pull request was merged? The latest changes I see in the rule are from late October...

Maybe there is something wrong with the night updates.

I have just logged out of my Premium Account in the site to check the sentence.

Notice that "premium" is not triggered as a foreign word, but I have added it as so days ago or so.
![subscrição premium 20201208](https://user-images.githubusercontent.com/5192600/101462717-67f31a80-3934-11eb-9128-619c26371043.png)

**Comment by marcoagpinto** [comment]
@jaumeortola 

Hello!

Sorry to bother you.

I have been looking at the rules regarding the decimal houses DECIMAL_COMMA but I don't understand anything in them.

Is it possible for you to fix:
```
Mais de 5.000 verificações adicionais para Inglês, Alemão, Francês.
Até 40.000 caracteres por campo de texto.
(até 40.000 caracteres).
```

Thanks!

**Comment by marcoagpinto** [comment]
@udomai 

Here is a fix for:
- [2] Obrigado por escolher a **subscrição LanguageTool** Premium. (GENERAL_GENDER_AGREEMENT_ERRORS[5])

https://github.com/languagetool-org/languagetool/commit/26995f1999f90c2fbdfed2661f5500a954a4f52d

This is very strange, since I downloaded the nightly stand-alone tool and compared both grammar.xml (the one in my hard disk and the stand-alone) and the differences were just the rules I added last night/morning.

But now it should be fixed for good.

**Comment by udomai** [comment]
> Here is a fix for:
> 
> * [2] Obrigado por escolher a **subscrição LanguageTool** Premium. (GENERAL_GENDER_AGREEMENT_ERRORS[5])

Oh, splendid! Thank you for sorting this one out, I hadn't even managed to look into it yet. Do you work with IntelliJ? My IntelliJ sometimes misbehaves and causes mysterious things to happen. Anyway, many thanks :)

**Comment by jaumeortola** [comment]
> I have been looking at the rules regarding the decimal houses DECIMAL_COMMA but I don't understand anything in them.

In this kind of rule it is impossible to know if it is a thousands separator or a decimal comma with 3 decimals. So, I think we should allow both (3,141 and 3.141).
 
The rule recommends a white space as thousands separator, which is used in books with accurate typography (following https://ciberduvidas.iscte-iul.pt/consultorio/perguntas/2500-2-500-ou-2500/12873). But I guess we should accept a point as thousands separator in Portuguese. Is that right, @marcoagpinto?

**Comment by marcoagpinto** [comment]
> 
> 
> > I have been looking at the rules regarding the decimal houses DECIMAL_COMMA but I don't understand anything in them.
> 
> In this kind of rule it is impossible to know if it is a thousands separator or a decimal comma with 3 decimals. So, I think we should allow both (3,141 and 3.141).
> 
> The rule recommends a white space as thousands separator, which is used in books with accurate typography (following https://ciberduvidas.iscte-iul.pt/consultorio/perguntas/2500-2-500-ou-2500/12873). But I guess we should accept a point as thousands separator in Portuguese. Is that right, @marcoagpinto?

@jaumeortola 

I wish I knew the answer, but some years ago someone confused me on how numbers should be written, so, right now I am not sure any more. :(

**Comment by marcoagpinto** [comment]
> 
> 
> > Here is a fix for:
> > 
> > * [2] Obrigado por escolher a **subscrição LanguageTool** Premium. (GENERAL_GENDER_AGREEMENT_ERRORS[5])
> 
> Oh, splendid! Thank you for sorting this one out, I hadn't even managed to look into it yet. Do you work with IntelliJ? My IntelliJ sometimes misbehaves and causes mysterious things to happen. Anyway, many thanks :)

I use Notepad++ to edit the files, it is the best editor around.

And I commit them using TortoiseSVN.

**Comment by udomai** [comment]
> I wish I knew the answer, but some years ago someone confused me on how numbers should be written, so, right now I am not sure any more. :(

After some quick and sloppy online research, I feel confident enough to say that, in Portuguese-speaking countries, both a NBSP and a period are acceptable for separating the thousands.

**Comment by danielnaber** [comment]
> In this kind of rule it is impossible to know if it is a thousands separator or a decimal comma with 3 decimals.

@jaumeortola That's right, but it's still very uncommon to have "000" as the only digits after the comma/point, so in these cases the user probably wants to use the thousands separator.

**Comment by marcoagpinto** [comment]
- [5] Mais de **5.000** verificações adicionais para Inglês, Alemão, Francês, ... BUT NO ERROR FOUND IN: "Até 40.000 caracteres por campo de texto" (DECIMAL_COMMA[3])
- [6] (até **40.000** caracteres). (DECIMAL_COMMA[2])
- [7] 3.000+ avaliações Chrome **Store** (not in dictionary)

Fixed by Jaume

**Comment by marcoagpinto** [comment]
- [8] Verifique os seus **documentos Word** (GENERAL_NUMBER_AGREEMENT_ERRORS[1])

Fixed.

https://github.com/languagetool-org/languagetool/commit/a2d67c4545e54b5676174f85b8d3eba35be78efa

**Comment by marcoagpinto** [comment]
- [9] Quero receber atualizações ocasionais e promoções **da LanguageTool** (GENERAL_GENDER_AGREEMENT_ERRORS[6])

It is a mistake in the "DA LanguageTool".

It should be "DO LanguageTool".

How can it be fixed? @danielnaber Could you edit directly the string in the pt-PT translation or tell me how to do it?

**Comment by udomai** [comment]
I will fix it, thanks for spotting this :)

**Comment by marcoagpinto** [comment]
> 
> 
> @marcoagpinto, Thanks for spotting this :)
> 
> There are over twenty occurrences of "a/na/da/pela LanguageTool" in the translations. I can change them to "o/do/no/pelo LanguageTool". Just to make sure: LanguageTool should be masculine?
> 
> Specific question:
> 
> _Aplicar todas as sugestões **da** LanguageTool para atingir 100:_ --> should this be "do" or simply "de"?

"de" also works in this case.

I am about to fix the last false positive!!!!!

I am testing it against a 200 000 corpus.

**Comment by udomai** [comment]
@marcoagpinto, thank you for your help! Since you have already taken so much time, I'd feel really guilty handing you over the correction of the Portuguese Website. I think I've figured it out, I'd just need your input on a very general question: The definite article is used more frequently in Portuguese. Should "LanguageTool" generally be used with or without article? Example:

_Parece que o idioma deste texto não é suportado **pelo** LanguageTool_ --> por?

**Comment by marcoagpinto** [comment]
> _Parece que o idioma deste texto não é suportado **pelo** LanguageTool_ --> por?

"pelo" sounds better.

**Comment by marcoagpinto** [comment]
- [10] Basta colar uma lista de e-mails abaixo para enviar convites **a todos** eles. (GENERAL_NUMBER_AGREEMENT_ERRORS[9])

Fixed!

https://github.com/languagetool-org/languagetool/commit/555b613b36ccb2947499df10a05fecab2cd9ed4e

**Comment by marcoagpinto** [comment]
@udomai @danielnaber @jaumeortola 

I have started changing the rules for style + picky:
`<rulegroup id='VERBO_ESTAR_A_VERBO_INF' name="Verbo estar + a + Verbo_inf > Verbo" type='style' tags="picky">`

```
<message>Em certos contextos, esta perífrase pode ser simplificada.</message>
<suggestion><match no='3' postag='VMN0000' postag_regexp="yes" postag_replace='VMIP1S0'/></suggestion>
```

However, they aren't triggered in the stand-alone tool.

How do I make them work in it?

Thanks!

**Comment by udomai** [comment]
Good morning @marcoagpinto!

The standalone won't show you picky rules – they are basically unavailable in any context that doesn't have a "picky switch" to switch the picky mode on and off.

You said you were using this rule for your thesis – the best solution would be for you to run the old version of the rule locally...

**Comment by marcoagpinto** [comment]
Good morning, @udomai 

I guess I will remove the "picky" and in January, I will create a new kind of rules "paraphrases" that will appear in the options.

Right now I will only add:
`type='style'`

and

`<message>Em certos contextos, esta perífrase pode ser simplificada.</message>`

Does it sound good?

**Comment by udomai** [comment]
Yes, those three steps are all okay :)

**Comment by marcoagpinto** [comment]
I hope by January to have part of this in my tool working:
![ptg_build_187_20201209](https://user-images.githubusercontent.com/5192600/101602287-c3391180-39f5-11eb-8da4-e1129997e3c4.png)

It will help me organise the rules since they are kind of a mess.

**Comment by marcoagpinto** [comment]
@udomai 

`- [4] Já tem sessão iniciada como :logged_in, mas **está a tentar** ver um convite destinado a :invited. (VERBO_ESTAR_A_VERBO_INF[3])`

I have improved it so that it doesn't flag the start of sentences:
`Estás a brincar comigo?`

https://github.com/languagetool-org/languagetool/commit/6aae8489d189ace4e258c3625a13c6fa3564321e

Can we close this issue?

Thanks!

**Comment by udomai** [comment]
@marcoagpinto, thank you for your help! The issue can be closed.
