### ISSUE TITLE
[en] wrong disambiguation "number"

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#3991]
The word _number_ is disambiguated (by `JJ_NN_JJ[1]`) as a verb or adjective in a sentence like this, causing an FP by the rule `SENT_START_PRPS_JJ_NN_VBP[1]`:

_Your screenshot **number** 2 is taken directly in MS Word?_ (numbers, numbs [both intended as VBZ])

**Comment by MikeUnwalla** [comment]
Wrong disambiguation does not occur now. I added an example and closed.
