### ISSUE TITLE
LibreOffice Add-on - unidentified word after each period

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#4020]
Hello!

This has been happening for a long time.

I have the setting in the add-on to show unidentified words underlined in black (Portuguese).

What happens is that it detects spaces after periods, which affected a rule I created days ago "Por favor" → "Por favor," (adding of comma).

See the screenshot:
![LO_non_identified_word_20201215](https://user-images.githubusercontent.com/5192600/102187495-f410bf00-3eab-11eb-936b-78bd845efae4.png)

**Comment by danielnaber** [comment]
This is specific to LibreOffice and doesn't happen on languagetool.org, does it?

**Comment by marcoagpinto** [comment]
@danielnaber 

Yes, I have just tested it in languagetool.org and there are no issues with "Por favor,".

**Comment by FredKruse** [comment]
@marcoagpinto could you please send me a short text, in which the bug happened.

**Comment by marcoagpinto** [comment]
@FredKruse 

The text is always the same document most of the time :-)

Go to page 9/13 in the attached document.

[MCAT_Translation_60PT_unsent.zip](https://github.com/languagetool-org/languagetool/files/5729470/MCAT_Translation_60PT_unsent.zip)

Thanks!

**Comment by FredKruse** [comment]
@marcoagpinto: I tested the text with the latest snapshot and LibreOffice 7.0.4.2 (Linux) and 7.0.3.1 (Windows 10). In both cases there was exact the same results as in the standalone version. I used the default settings of LT. Could you give me a hint, what I have to do, to reproduce the error? (HINT: deactivate "Save cache to file" in the options, if you test new or changed rules. Otherwise, the old cache is used).

**Comment by marcoagpinto** [comment]
I have the latest LibreOffice in Windows 10.

Removing the caches doesn't fix it.

This is the settings I am using as a LT developer (to show unknown words in a different colour and flag them):
![unknown_words_20201222](https://user-images.githubusercontent.com/5192600/102904914-5187ab80-446a-11eb-87d4-3bd19afc80ed.png)

Does it help?

Thanks!

**Comment by marcoagpinto** [comment]
@FredKruse 

Here is just page 9 of the document mentioned above.
[MCAT_Translation_60PT_page9.zip](https://github.com/languagetool-org/languagetool/files/5741421/MCAT_Translation_60PT_page9.zip)

**Comment by FredKruse** [comment]
I was able to reproduce the problem. But it regards an old part of code which is very central. I got an idea to solve it, but it will be a change of code, that is too big to put it in version 5.2 in the short time before the release. I will work on it after LT 5.2 is released (after 29.12.).

**Comment by FredKruse** [comment]
The problem should be solved. Please test carefully, if there are no unwanted site effects.

**Comment by marcoagpinto** [comment]
Thanks, I will test tomorrow.

**Comment by marcoagpinto** [comment]
@FredKruse 

I tested it in the affected document and the issue seems to be fixed!

Great work!

Thanks!
