### ISSUE TITLE
[fr] user feedback "Je m'appel"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4028]
> I would have used the extension, but it didn't suggest a simple correction in French, although it recognizes the error:
<img width="320" alt="Screenshot 2020-12-16 at 10 21 51" src="https://user-images.githubusercontent.com/37363/102340396-c81e3800-3f96-11eb-816a-0d646beadd72.png">

Maybe we can have a simple rule that detects this and offers a replacement?

Also:
> Je m'apele
> Je m'appele

**Comment by udomai** [comment]
That's a quick win, if there ever was one :)

**Comment by tiff** [comment]
@udomai don't forget to set the correct priority, so it overlays the match that is currently produced

**Comment by udomai** [comment]
Thanks for reminding me!
