### ISSUE TITLE
Install English only

### ISSUE THREAD

**Issue by kracwarlock** [languagetool-org/languagetool#403]
I want to automatically check several files for grammar errors.  And I need to setup  the server. The `mvn` install crashes on some french tests. Is it possible to build the project for English only?

**Comment by danielnaber** [comment]
Well, you could remove all non-English languages from the top-level `pom.xml`. But which tests are failing and how? We should fix that instead.

**Comment by kracwarlock** [comment]
I found out the problem. I was using OpenJDK. As soon as I switched to Oracle Java 8 it started working. Thanks. I'll close this.

**Comment by kracwarlock** [comment]
I tried running it using
```
java -cp languagetool-server/target/languagetool-server-3.4-SNAPSHOT.jar org.languagetool.server.HTTPServer --port 20000
```
```
WARNING: running in HTTP mode, consider using org.languagetool.server.HTTPSServer for encrypted connections
Exception in thread "main" java.lang.NoClassDefFoundError: org/languagetool/language/LanguageIdentifier
        at org.languagetool.server.LanguageToolHttpHandler.<init>(LanguageToolHttpHandler.java:87)
        at org.languagetool.server.HTTPServer.<init>(HTTPServer.java:99)
        at org.languagetool.server.HTTPServer.main(HTTPServer.java:144)
Caused by: java.lang.ClassNotFoundException: org.languagetool.language.LanguageIdentifier
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
```
but the code crashes. What is the problem here and how can I solve this?

**Comment by danielnaber** [comment]
You need to `cd` first into `languagetool-server/target` so the paths are correct.

**Comment by kracwarlock** [comment]
I did that and I still get the same error.

**Comment by danielnaber** [comment]
Sorry, cannot reproduce. Here are my commands that work for me:

```
mvn package -DskipTests
cd target/LanguageTool-3.4-SNAPSHOT/LanguageTool-3.4-SNAPSHOT/
java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 20000
```

**Comment by kracwarlock** [comment]
Oh, that works. I was using the snapshot jar inside the languagetool-server folder and not this one.

**Comment by lizixroy** [comment]
It's very confusing how to launch the server. The documentation needs some work.
If the snapshot jar is not needed why do we have it?

**Comment by lizixroy** [comment]
@kracwarlock where did you find the languagetool-server.jar? I only have languagetool-server-3.5-SNAPSHOT.jar in the /languagetool-server/target folder

**Comment by lizixroy** [comment]
For what it's worth, the correct path where you will find languagetool-server.java is /languagetool-master/languagetool-standalone/target/LanguageTool-3.5-SNAPSHOT/LanguageTool-3.5-SNAPSHOT

**Comment by kracwarlock** [comment]
@lizixroy I used the one at 
```languagetool-standalone/target/LanguageTool-3.4-SNAPSHOT/LanguageTool-3.4-SNAPSHOT/languagetool-server.jar```

**Comment by kracwarlock** [comment]
that's the same as the path you used

**Comment by shackra** [comment]
The solution presented here doesn't work for me :(


```
# jorge at abril.charola in /usr/share/java/languagetool [20:09:18]
→ pwd                                                                                     
/usr/share/java/languagetool

# jorge at abril.charola in /usr/share/java/languagetool [20:09:23]
→ /usr/bin/java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
WARNING: running in HTTP mode, consider using org.languagetool.server.HTTPSServer for encrypted connections
Exception in thread "main" java.lang.NoClassDefFoundError: org/languagetool/language/LanguageIdentifier
        at org.languagetool.server.TextChecker.<init>(TextChecker.java:69)
        at org.languagetool.server.V1TextChecker.<init>(V1TextChecker.java:47)
        at org.languagetool.server.LanguageToolHttpHandler.<init>(LanguageToolHttpHandler.java:65)
        at org.languagetool.server.HTTPServer.<init>(HTTPServer.java:99)
        at org.languagetool.server.HTTPServer.main(HTTPServer.java:134)
Caused by: java.lang.ClassNotFoundException: org.languagetool.language.LanguageIdentifier
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more

# jorge at abril.charola in /usr/share/java/languagetool [20:09:27]
→ sudo parabola-java get                                                                  
java-8-openjdk

# jorge at abril.charola in /usr/share/java/languagetool [20:09:31]
→ 
```

**Comment by arysin** [comment]
It looks that we need to override main class (http instead of https) so we use -cp instead of -jar but then the classpath inside manifest is not picked up. If you have libs/ dir with all the jars try this:
`java -cp ./*:libs/* org.languagetool.server.HTTPServer --port 8081`

**Comment by shackra** [comment]
Sadly, I don't have that dir (languagetool was installed through the package manager of my GNU/Linux
distribution), all I have is this https://www.archlinux.org/packages/community/any/languagetool/

El miércoles 19 de octubre del 2016 a las 0310 horas, arysin escribió:

> It looks that we need to override main class (http instead of https) so we use -cp instead of -jar but
> then the classpath inside manifest is not picked up. If you have libs/ dir with all the jars try this:
> java -cp ./*:libs/* org.languagetool.server.HTTPServer --port 8081
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.


--
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by arysin** [comment]
Then your try something like this:
`java -cp /usr/share/java/languagetool:/usr/share/java/languagetool/* org.languagetool.server.HTTPServer --port 8081`
but I would run it from the directory you can write into, e.g. your home

**Comment by shackra** [comment]
Well, this is weird:

--8<---------------cut here---------------start------------->8---
# jorge at abril.charola in /tmp [22:28:32]
→ java -cp /usr/share/java/languagetool:/usr/share/java/languagetool/* org.languagetool.server.HTTPServer --port 8081
zsh: no matches found: /usr/share/java/languagetool:/usr/share/java/languagetool/*
--8<---------------cut here---------------end--------------->8---

El jueves 20 de octubre del 2016 a las 0228 horas, arysin escribió:

> Then your try something like this:
> java -cp /usr/share/java/languagetool:/usr/share/java/languagetool/* org.languagetool.server.HTTPServer --port 8081
> but I would run it from the directory you can write into, e.g. your home
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.


--
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by arysin** [comment]
Try enclosing in parenthesis (seems like zsh is trying to expand the wildcard):
`java -cp "/usr/share/java/languagetool:/usr/share/java/languagetool/*" org.languagetool.server.HTTPServer --port 8081`

**Comment by shackra** [comment]
Okay, now it runs but the application fails. I tried a lot of random ports but the error message is
still the same:

--8<---------------cut here---------------start------------->8---
# jorge at abril.charola in /tmp [22:27:07]
→ java -cp "/usr/share/java/languagetool:/usr/share/java/languagetool/*" org.languagetool.server.HTTPServer --port 6660
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
WARNING: running in HTTP mode, consider using org.languagetool.server.HTTPSServer for encrypted connections
Exception in thread "main" java.lang.RuntimeException: Could not start LanguageTool HTTP server on localhost, port 6660
        at org.languagetool.server.HTTPServer.main(HTTPServer.java:138)
Caused by: org.languagetool.server.PortBindingException: LanguageTool HTTP server could not be started on host "localhost", port 6660.
Maybe something else is running on that port already?
        at org.languagetool.server.HTTPServer.<init>(HTTPServer.java:106)
        at org.languagetool.server.HTTPServer.main(HTTPServer.java:134)
Caused by: java.lang.IllegalStateException
        at com.optimaize.langdetect.LanguageDetectorBuilder.build(LanguageDetectorBuilder.java:172)
        at org.languagetool.language.LanguageIdentifier.<init>(LanguageIdentifier.java:68)
        at org.languagetool.server.TextChecker.<init>(TextChecker.java:69)
        at org.languagetool.server.V1TextChecker.<init>(V1TextChecker.java:47)
        at org.languagetool.server.LanguageToolHttpHandler.<init>(LanguageToolHttpHandler.java:65)
        at org.languagetool.server.HTTPServer.<init>(HTTPServer.java:99)
        ... 1 more
--8<---------------cut here---------------end--------------->8---


El jueves 20 de octubre del 2016 a las 1205 horas, arysin escribió:

> Try enclosing in parenthesis (seems like zsh is trying to expand the wildcard):
> java -cp "/usr/share/java/languagetool:/usr/share/java/languagetool/*" org.languagetool.server.HTTPServer --port 8081
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.


--
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by arysin** [comment]
Try different port, also you can check if something is already running on that port by running `netstat -lpn | grep 6660`

**Comment by shackra** [comment]
But, that's the thing, I tried several ports on random and the same error was thrown by languagetool :(

El martes 25 de octubre del 2016 a las 1821 horas, arysin escribió:

> Try different port, also you can check if something is already running on that port by running netstat -lpn | grep 6660
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.


--
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by arysin** [comment]
Hmm, looking closer into the stack trace it looks like language-detector can't load language profiles. Unfortunately I am not very familiar with that part, possibly some files are missing in the jar/classpath. You may want to download package from LT site and try that way.
