### ISSUE TITLE
[nl] feedback about "zometeen"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#4041]
User feedback:

>  Please see https://onzetaal.nl/taaladvies/zometeen/, zometeen has been generally accepted for decades, even though it was originally "zo meteen"

**Comment by baarsrj** [comment]
The advice states: De officiële spelling is zo meteen, in twee woorden. 
And so far, only the official spelling is allowed, as prescribed for education and government. 
Allowing the larger variation 'Onze Taal' is proposing, would require multiple changes in the core of LT. Like having two types of spell checking, profiles etc.
