### ISSUE TITLE
[de] Nicht gefunden: "weis" vs "weiß"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4059]
> jetzt hat es geklappt, **weis** zwar nicht warum, aber Hauptsache es funktioniert.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/102903630-e42b4900-4470-11eb-8b36-4c64a697b1fc.png)
Wenn es als Verb eingetragen ist, wundert es mich nicht, dass das LanguageTool hier nichts sagt.

Eine Ausbauung der Regel für Wortverwechselung wäre sicherlich keine schlechte Idee.

**Comment by tiff** [comment]
Fixed as part of https://github.com/languagetool-org/languagetool/commit/8a7586ebfe10be5507d70a890e879dbe30c3a6ca
