### ISSUE TITLE
[DE] Imperativ wird ignoriert

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#4060]
Moin liebes LanguageTool-Team,

vorweg, ja dieser Fehler ist bekannt und ich weiß, dass der doppelt vertreten. Ich möchte euch nur darauf aufmerksam machen, weil dieser Fehler bald ein Jahr alt ist und ich irgendwie das Gefühl habe, dass dieser Fehler sogar die Rente erreicht.

**Fehler 35** aus #1431 entnommen.
B-Black Dallun sagte: „**Lies** es dir durch.“ 
**LanguageTool-Fehlermeldung:** "Meinten Sie "ließ" (Vergangenheitsform von 'lassen')?"
**Bemerkung:** Hier handelt sich um eine Auffordung sich etwas durchzulesen.
![grafik](https://user-images.githubusercontent.com/40240507/102905704-d4613400-4473-11eb-9238-141c13fd38b9.png)

Lies hat die richtigen Token bekommen und wird als Imperativ erkannt, aber es kommt trotzdem zum Fehlalarm. In der wörtlichen Rede ist es keine Seltenheit, dass ein Imperativ genutzt wird, weswegen ich euch danken werde, wenn ich diesen alten Fehler beheben werdet.

Grüße Dallun511

**Comment by udomai** [comment]
Hi @Dallun511! Danke fürs Nachhaken! In welchem Kontext tritt der Fehler denn noch auf? Die Regel, die seinerzeit den Fehlalarm ausgelöst hat, hat ein Antipattern für "Lies" nach dem Satzanfang erhalten und folgender Satz wird weder in Open Source noch in Premium bemängelt:

_Lies es dir durch._

Passiert es bei Dir, wenn Anführungszeichen verwendet werden? Dafür habe ich gerade noch ein Antipattern gesetzt.

**Comment by Dallun511** [comment]
B-Black Dallun sagte: „**Lies** es dir durch.“
B-Black Dallun sagte: **Lies** es dir durch
Er sagte: „**Lies** es dir durch.“
Er sagte: **Lies** es dir durch
LanguageTool-Fehlermeldung: "Meinten Sie "ließ" (Vergangenheitsform von 'lassen')?"
Bei diesen Beispielen schlägt der Fehlalarm an.

„**Lies** es dir durch“, sagte B-black Dallun.
**Lies** es dir durch, sagte B-black Dallun.
„Lies es dir durch“, sagte er.
Lies es dir durch, sagte er.
LT: "Keine Fehler gefunden"
In diesen Beispielen schlägt der Fehlalarm nicht zu.

Wenn erst "Name + sagen" und danach dirkte oder wörtliche Rede folgt, erscheint der Fehlalarm.
Umgekehrt nicht.

Grüße Dallun511

**Comment by udomai** [comment]
Hi @Dallun511, danke für die Beispiele! Jetzt ist der Groschen gefallen. Ab morgen sollten diese Fehlalarme wegfallen.

**Comment by Dallun511** [comment]
@udomai Jetzt muss ich nur noch beten, dass die sehr alten Fehlalarm behoben werden. Ich freue mich schon, wenn ein Fehlalarm weniger ist.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/103086252-70aa4880-45e4-11eb-9bf2-f85eef5d0336.png)
Mission erfüllt!
