### ISSUE TITLE
org.languagetool.openoffice.MainTest has start failing locally

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#4064]
`org.languagetool.openoffice.MainTest` fails for me locally (with IntelliJ and mvn):

```
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1.311 s <<< FAILURE! - in org.languagetool.openoffice.MainTest
[ERROR] testDoProofreading(org.languagetool.openoffice.MainTest)  Time elapsed: 1.227 s  <<< FAILURE!
java.lang.AssertionError: expected:<23> but was:<81>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.languagetool.openoffice.MainTest.testDoProofreading(MainTest.java:45)
```

The failure starts with this commit: https://github.com/languagetool-org/languagetool/commit/d3142300d12bab3e5c51dddcec01c8a3b2b31bc3. I have no idea why it doesn't fail in the CI. @FredKruse do you have any idea? I'm not even sure what exactly that test is supposed to test...

**Comment by FredKruse** [comment]
@danielnaber: I am not sure it this solves really the problem. Is there a possibility to run only a test of the office-extension. To run all tests takes a long time, especially if you want to check the test routines.

**Comment by danielnaber** [comment]
@FredKruse You can just run the tests in that module:
```
cd languagetool-office-extension
mvn test
```
I still have the problem with your change applied.

**Comment by FredKruse** [comment]
@danielnaber: Did you choose the remote server option in the local configuration? That is the only idea that is left for me.

"mvn test" doesn't run:
 [ERROR] Failed to execute goal on project languagetool-office-extension: Could not resolve dependencies for project org.languagetool:languagetool-office-extension:jar:5.2-SNAPSHOT: The following artifacts could not be resolved: org.languagetool:languagetool-core:jar:5.2-SNAPSHOT, org.languagetool:languagetool-gui-commons:jar:5.2-SNAPSHOT, org.languagetool:languagetool-http-client:jar:5.2-SNAPSHOT, org.languagetool:language-all:jar:5.2-SNAPSHOT: Failure to find org.languagetool:languagetool-core:jar:5.2-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced

**Comment by danielnaber** [comment]
> Did you choose the remote server option in the local configuration?

What do you mean by "local configuration", `.languagetool.cfg`? I've removed that as a test, but the problem remains (also, I think the unit test should not depend on configuration files).

To make `mvn test` work in `languagetool-office-extension`, first run `mvn clean install -DskipTests` in the LT directory (one level above `languagetool-office-extension`).

**Comment by FredKruse** [comment]
@danielnaber : Yes, you are right, the unit test should not depend on the configuration file. I did some test and choose different configurations (saved to file). I am sorry, but I can't reproduce the failure above.
The error message indicates, that the splitting into sentences does not work. <23> is the assumed beginning of the next sentence. <81> is the length of the string, which contains 3 sentences.
In all my local tests the splitting works as it should.

**Comment by FredKruse** [comment]
@danielnaber : the change in extension code should solve the problem. The configuration file is completely ignored in test mode now. I have commented out your ignore statements in testMain.java. Hope your local tests are running now.
If not: there must be a problem in the JLangTool.sentenceTokenize method, which is used to split the paragraph into sentences.

Another question: 
I like to implement a new test class, to test the correct handling of different kind of rules. In this context I would like to test :
- a sentence level rule 
- a rule, which works on the level of one paragraph (e.g. MultipleWhitespaceRule)
- a rule, which works on the level of more than one paragraph (e.g. WordRepeatBeginningRule)
- a rule, which works on the level of full text (e.g. GenericUnpairedBracketsRule)

The rules should be very stable. They should not be changed as possible.
Could you recommend for every category one rule?

**Comment by danielnaber** [comment]
Thanks, the test is working for me now locally.

By "stable" you mean the Java code doesn't change often? You could have a look at the git history of the rules you mentioned. In general most Java rules are quite stable I think.
