### ISSUE TITLE
red warning in options dialog

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#407]
The warning `Restart application for the language change to take effect.` should only appear when needed, i.e. when the setting has actually been changed. Otherwise it's just confusing.

**Comment by pminos** [comment]
The message is more like a note than a warning. But I agree that the imperative mood gives the wrong impression. We can change the message to something like  **Takes effect after you restart the application**.  Maybe change a little the layout like below

![screenshot](https://cloud.githubusercontent.com/assets/5192544/15323861/91c5abc0-1c4c-11e6-83d5-4d7097901b46.png)

But I can also make the message appear after setting the option.

What is your opinion?

**Comment by danielnaber** [comment]
I think your screenshot looks nice, but if it's not too difficult I'd prefer to additionally only show that text when the setting is changed.

**Comment by pminos** [comment]
Ok for the message. Do you mean you want me to keep the border around the option?

**Comment by danielnaber** [comment]
You mean the border will look strange if the red text is not there? Maybe always show the text, but not in red?

**Comment by pminos** [comment]
I don't think the border will look strange. I just wanted to be sure I understood well. So, I will keep the border and show the message only when the user change the option.
