### ISSUE TITLE
Wrong suggestions when there are multiple synthesized forms 

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#4073]
In suggestions like this (in French and also in other languages):
```
<suggestion><match no="1" postag="D m s"/> \2</suggestion>
<suggestion><match no="1" postag="D (m|e) p" postag_regexp="yes"/> <match no="2" postag="N m p"/></suggestion>
```

The first match of the first suggestion has multiple results: `ce, cet, ct'`, and the suggestions are incorrect: `Suggestion: Ce homme; Cet (homme); Ct' hommes; Ce hommes; Cet hommes`. 
The desired result is: `Suggestion: Ce homme; Cet homme; Ct'homme; Ces hommes`

**Comment by jaumeortola** [comment]
Solved in French with a filter (WordWithDeterminerFilter) that checks the suggestions with several pattern rules and discards the incorrect ones.

**Comment by udomai** [comment]
And you also removed the undesirables like `ct'`!
