### ISSUE TITLE
French: User feedback via Facebook

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#408]
Hi, little quuestion in french grammar with LT.
I wrote "On se créé des problèmes." and LT suggested créé -> créér.
But with "créér" it's also wrong (I think).

With "il se créé des problèmes." it also give a bad suggestion: with "se" before the "créé".
I think the right is "Il se crée des problèmes."

**Comment by f-knorr** [comment]
Hi! I'm no native speaker either. 
I  think it should either be "On s'est créé des problèmes." or "On se crée des problèmes." 
Both options are accepted by LT.

**Comment by dpelle** [comment]
janscheiber wrote:

> With "il se créé des problèmes." it also give a bad suggestion: with "se" before the "créé".
> I think the right is "Il se crée des problèmes."

Right.  LanguageTool correctly detects the grammar error, but the suggestion in this case is incorrect indeed.

*Il se créé des problèmes* should be "Il se crée des problèmes".  In some other contexts, "se créer des problèmes can also be correct" but not before "il" or "on" at least.  I'll fix that soon when I have time, and I'll update this ticket accordingly when done.

Thanks.
