### ISSUE TITLE
[uk] add "Кайсері" to dictionary

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4081]
user feedback:
> Кайсері - місто в Туреччині, адміністративний центр ілу Кайсері, біля північного підніжжя вулкана Ерджіяс. Це не помилка

**Comment by zverok** [comment]
@tiff That's Ukrainian :( Different language, I swear.

**Comment by arysin** [comment]
Буде в наступній версії [словника](https://vesum.nlp.net.ua/)

**Comment by arysin** [comment]
Додано
