### ISSUE TITLE
[ja] Issues of the sample text on the website

### ISSUE THREAD

**Issue by blueset** [languagetool-org/languagetool#4085]
> Sample text on https://languagetool.org/
> これわ文章を入力して'Check Text'をクリックすると、誤記を探すことができる。着色した文字をクリックすると、間違いの詳細の表示する。

## Incorrect autocorrection

The above text, after applying all the suggested correction, becomes:

> これは文章を入力して'Check Text'をクリックすると、誤記らせるる。着色した文字をクリックすると、間違いの詳細を軽蔑する。

* これわ → これは, no problem with this
* を探すことができ → らせる, this is confusing. The verb 探す (to find) is totally lost in the correction. Expected result should be 探すことができる → 探せる.
* の詳細の表示する → を軽蔑する, this is also confusing. The correction dropped 詳細 (detail) and 表示する (to display) and replaced with 軽蔑する (to despise, to look down). Expected result should be の詳細の表示する → の詳細を表示する.

It seems like some rules involving variables in the pattern are not properly reflected in the suggestion. But I wasn’t able to write out a correct rule for that because I didn’t manage to find a way to properly convert the part of speech of the verb in the rule set. 

For example ([] represents tokenization result):
* [暮らす][こと][が][できる] → 暮ら + せる
* [会う][こと][が][できる] → 会え + る (au → ae-ru)
* [書く][こと][が][できる] → 書け + る (kaku → kake-ru)
* [食べる][こと][が][できる] → 食べ + られる
* [見る][こと][が][できる] → 見 + られる
* [くる][こと][が][できる] → こられる
* [表示する][こと][が][できる] → 表示 + できる

## Mistake not found by LanguageTool

After the corrections mentioned above, there is still a grammar mistake in the sentence. 

> これは文章を入力して'Check Text'をクリックすると、誤記を探せる。

... which translates to: “This is `__` which looks for typos when you enter your text and click ‘Check Text’.” The object is missing from the sentence. 

To correct it, we can add an object like “a tool” in the sentence:

> これは文章を入力して'Check Text'をクリックすると、誤記を探せる[ツールです]。

**Comment by danielnaber** [comment]
Thanks for the detailed report. Unfortunately, support for Japanese isn't currently maintained in LT, so we'll just hide the demo text for now...
