### ISSUE TITLE
error when starting LT on libreoffice

### ISSUE THREAD

**Issue by icf20** [languagetool-org/languagetool#4089]
![image](https://user-images.githubusercontent.com/17784575/103527712-0d8da100-4e83-11eb-9876-57bf072d3d1b.png)

sadly i cant copy paste the error from the image

**Comment by danielnaber** [comment]
Does this also happen with LT 5.2? https://languagetool.org/download/LanguageTool-5.2.oxt

**Comment by FredKruse** [comment]
@icf20 This should be solved with 5.3. Please test and close the issue.

**Comment by FredKruse** [comment]
The issue is solved. I close it.
