### ISSUE TITLE
French replacements not there

### ISSUE THREAD

**Issue by jeffrobdun** [languagetool-org/languagetool#409]
Is it possible to add French replacements into languagetool? Looking at the following forum it doesn't seem like it's a big challenge according to Ruud_Baars. Seems like there are people who have been looking for this since 2013.

http://forum.languagetool.org/t/french-has-no-suggestions-of-wrong-written-words-at-all/225

Thanks for your help :)

**Comment by danielnaber** [comment]
This has just been implemented, see #850
