### ISSUE TITLE
[fr] Add Word2VecModel options for french language

### ISSUE THREAD

**Issue by thelittlefireman** [languagetool-org/languagetool#4090]
Hi,
Since word2vec models are available for a huge number of languages [https://fasttext.cc/docs/en/crawl-vectors.html](https://fasttext.cc/docs/en/crawl-vectors.html), could it be possible to enable this options for other languages than english, german and Portuguese ?

Thanks

**Comment by danielnaber** [comment]
Closing, the word2vec feature has never been fully maintained even for English...
