### ISSUE TITLE
[DE] Fehlalarm "Mögliche Wortverwechslung:"

### ISSUE THREAD

**Issue by Black56651** [languagetool-org/languagetool#4091]
Moin liebes LangaugeTool-Team

Serena sagte: „Du befindest dich hier in Gefangenschaft, also hast du keinen Schutz von deinem **ach so tollen** Clan.“
LT: "Mögliche Wortverwechslung: Meinten Sie „nach“?"
In diesem Fall "ach so tollen" richtig.

Grüße Dallun511

**Comment by danielnaber** [comment]
Closing, cannot reproduce anymore.
