### ISSUE TITLE
[nl] wrong suggestion Dutch for "uw"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#4092]
User report:

> LanguageTool is in Dutch suggesting 'jijw' which is not a word in Dutch. It should suggest 'jouw'.

Seems to be from coherency.txt, matching substring?

![CleanShot 2021-01-04 at 08 35 37](https://user-images.githubusercontent.com/857004/103530176-4596e300-4e87-11eb-9b65-15743c90bf4a.png)

**Comment by baarsrj** [comment]
Yes, ir probably is. But coherency should not match substrings. If it does, these two items are too risky:
u;je
u;jij
I cannot update this myself now, still having issues getting the machine up and running.

**Comment by danielnaber** [comment]
I see now that it's not substring matches, but the logic tries to match all forms of a word and "uw" has "u" as its base form. However, I cannot reproduce getting "jijw" as a suggestion.

**Comment by dpelle** [comment]
Unfortunately, the bug description does not give the full sentence. 
But I can anyway reproduce another incorrect word in the suggestion using this incorrect sentence:

*Dank je voor uw reactie.*

Here LT proposes the nonsensical replacement uw → *jew*  (*jew* is not a valid Dutch word).

Correct would be either:
-  "Dank je voor je reactie."
- or "Dank u for uw reactie."  (formal)

**Comment by baarsrj** [comment]
I removed those entries from the file. But I think the logic of the routine is too risky for short alternatives like this. I always thought it was just plain words, not parts of it.
It could be a good feature, but it clearly has to be controllable.

**Comment by danielnaber** [comment]
> I always thought it was just plain words, not parts of it.

As described above, it's **not** parts of words, but it tries to match all forms of a word (and "uw" seems to be a form of "u" according to our tagger).
