### ISSUE TITLE
Implement new HTTP API with JSON output

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#410]
I suggest a new HTTP API (see [the old one](http://wiki.languagetool.org/public-http-api)), to be available under `http://.../v2/`, with probably the same input parameters as now but with JSON output. The current output has several issues:

* Attribute name are a mess with CamelCase for only some attributes: `contextoffset` vs `ruleId`
* We don't really use the power of XML, what we return is always in attributes. Thus JSON is more appropriate.
* Attributes like `fromx`, `tox`, `fromy`, `toy` (i.e. line numbers, column numbers) shouldn't even be returned, as we shouldn't care about the concept of columns and lines.

The old API will still be available (under everything not prefixed `/v2/`) but it will be deprecated. A warning will be shown in its output as an XML comment, but only once we are happy with the new API.

Suggested output for a single match:

```json
{
  "software": {
    "name": "LanguageTool",
    "version": "3.4-SNAPSHOT",
    "buildDate": "2016-05-20",
    "apiVersion": 1
  },
  "language": {
    "name": "English (US)",
    "code": "en-US"
  },
  "matches": [
    {
      "message": "This sentence does not start with an uppercase letter",
      "replacements": ["My"],
      "offset": 0,
      "length": 2,
      "context": {
        "text": "my text.",
        "offset": 0,
        "length": 2
      },
      "rule": {
        "id": "UPPERCASE_SENTENCE_START",
        "description": "Checks that a sentence starts with an uppercase letter",
        "category": {
          "id": "CASING",
          "name": "Capitalization"
        }
      }
    }
  ]
}
```

**Comment by danielnaber** [comment]
Maybe we cold use http://editor.swagger.io/

**Comment by danielnaber** [comment]
A prototype of a new API is now online and can be tested here: https://languagetool.org/http-api/swagger-ui/#/default

**Comment by oriain** [comment]
Just wondering, is language autodetect not a feature of the HTTP API?

Ryan

**Comment by danielnaber** [comment]
Just use `language=auto`.

**Comment by oriain** [comment]
Duh, I should have just read the description.  :)

Seems like auto could be the default value?  Other than that, it doesn't
actually accept auto.

"Error: 'auto' is not a language code known to LanguageTool. Supported
language codes are: ast-ES, be-BY, ..., uk-UA, zh-CN. The list of languages
is read from META-INF/org/languagetool/language-module.properties in the
Java classpath. See http://wiki.languagetool.org/java-api for details."

**Comment by baarsrj** [comment]
I testes one rule. I wonder if replacement response is correct. It looks 
like me that this states the error i sstarting at offset 7, and is 5 
chars long. (Hope it is utf8 counted!)
But also the (empty) replacement is starting at 7, 5 long. Which would 
mean 'de de' will be replaced to nothing, not just one 'de'.
It could also be an error in the rule itself by the way ... Not 
perfectly sure.

Ruud

       "message": "Een dubbel woord kan juist zijn, maar vaak is het een 
vergissing.",
       "replacements": [],
       "offset": 7,
       "length": 5,
       "context": {
         "text": "Dat is de de gek.",
         "offset": 7,
         "length": 5
       },

**Comment by danielnaber** [comment]
@oriain Thanks, `auto` should be fixed now. This issue occurred only with very short texts where the auto-detection doesn't work. It falls back to English now in these cases.

**Comment by danielnaber** [comment]
@baarsrj The values are the same as they are now in the XML response. An empty list of replacements doesn't mean "replace with empty string" (that would be `[""]`) but it means there are no replacements, because the rule doesn't offer them.

**Comment by MikeUnwalla** [comment]
Some suggestions:
- Set enabledOnly to false by default, rather than to null.
- If a user specifies a rule ID or a category ID, and if that ID does not exist, give a message.
- Where a user must enter a language code, let the user enter only permitted values.

**Comment by danielnaber** [comment]
Mike, `enabledOnly` is now false by default. I like the other ideas, but they are not that easy to implement.

**Comment by creaticious** [comment]
..just tried the new api but i cant get it to work. maybe my request syntax is wrong..is there any reference...? I'm working in nodejs with 'request-json'-package...i'm always getting a 500 and the "Missing param 'Text'..."-Exception in console...

`var data = { text : 'This is ym Test!', language : 'de-DE', motherTongue : 'de'};

            spellServer.post('v2/check', data, function(err, res, body) {
              return console.log(res.statusCode);
            });`
