### ISSUE TITLE
[de] "Burgermeister" suggests "Burger Meister"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4102]
> Der Burgermeister

![Bildschirmfoto 2021-01-06 um 08 21 15](https://user-images.githubusercontent.com/37363/103740897-65014d80-4ff8-11eb-8846-542dd67f5f77.png)

Ich denke, wir sollten nie zwei Substantive getrennt mit Leerzeichen vorschlagen

**Comment by Dallun511** [comment]
In LibreOffice sind sogar die Treffer schlechter.
![grafik](https://user-images.githubusercontent.com/40240507/103746296-2ae87980-5001-11eb-8195-98bb6f1c68c7.png)
Da kommt das richtige Wort gar nicht vor.

**Comment by danielnaber** [comment]
> Ich denke, wir sollten nie zwei Substantive getrennt mit Leerzeichen vorschlagen

Die Logik haben wir schon, es war nur "Burger" nicht getaggt.
