### ISSUE TITLE
Coherency implementation (java code) wrong

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#4104]
Apparently, the code also replaces parts of words, not just full words. This leads to bad suggestions in some cases.
Trying to do all forms of a word is okay, but only full words.
Or, replacing part is allowed, but then it should be controllable.
Both have advantages and disadvantages. 
But current implementation fails for short words like u/uw je/jij etc.

**Comment by danielnaber** [comment]
Could you send an example so I can reproduce this? I don't get any substring matches.

**Comment by danielnaber** [comment]
> I will add je and u again, we will see what the nightly brings in.

Is there a risk of many false alarms? We shouldn't use the nightly then, as users would be affected.

**Comment by danielnaber** [comment]
I think this was fixed very recently.
