### ISSUE TITLE
[de] Verb "pulen" causes false positive

### ISSUE THREAD

**Issue by f-knorr** [languagetool-org/languagetool#411]
In the sentence "Er pulte das Etikett von der Flasche." the word "pulte" is incorrectly marked as an error. However, the list of recommendations contains "pulte" and its base form "pulen" is correctly recognized.

Is there a "generic" fix?

**Comment by danielnaber** [comment]
Mhh, strange. I have no idea. Could you debug this?

**Comment by f-knorr** [comment]
I will give it another try. I have already spent a few minutes looking into the bug...

**Comment by f-knorr** [comment]
Ok. It's the `Hunspell_spell` function from `HunspellLibrary` that returns the wrong result (0). Hence, I guess the problem cannot be solved from JAVA.

**Comment by danielnaber** [comment]
In LibreOffice, `pulte` is also detected as incorrect. Are you sure it's in the dictionary as a verb, not just as plural of the noun `Pult`?

**Comment by f-knorr** [comment]
Here is the Part-of-speech analysis of "pulte":
```
VER:1:SIN:KJ2:SFT
VER:1:SIN:PRT:SFT
VER:3:SIN:KJ2:SFT
VER:3:SIN:PRT:SFT 
```
Therefore, it is correctly recognized as a verb in this context.

The capitalized version (Pulte) gives:
```
SUB:AKK:PLU:NEU
SUB:DAT:SIN:NEU
SUB:GEN:PLU:NEU
SUB:NOM:PLU:NEU 
```

**Comment by danielnaber** [comment]
The spell checker is independent of the morphological analysis. It might not recognize words that the morphological analysis understands.

**Comment by f-knorr** [comment]
Oh, I did not know this. Then, I guess "pulen" is not in the dictionary.

**Comment by danielnaber** [comment]
You can report this to the maintainer (or add it and its forms to our `spelling.txt`, but for verbs, that's quite some forms).

**Comment by f-knorr** [comment]
Issue reported to the dictionary's maintainer
