### ISSUE TITLE
Server should report it's version on startup

### ISSUE THREAD

**Issue by msstice** [languagetool-org/languagetool#4111]
This helps with error reporting, e.g. from VS Code, when we can look at the log output in VS Code when making bug reports. e.g. #4109  Thanks!

**Comment by danielnaber** [comment]
Using `java -cp languagetool-server.jar org.languagetool.server.HTTPServer`, this is what I get:

> 2021-01-08 08:05:04 +0000 Starting LanguageTool 5.2 (build date: 2020-12-29 15:54, eb572bf) server on http://localhost:8081...

**Comment by msstice** [comment]
Thanks for looking into this. I will open this in https://github.com/davidlday/vscode-languagetool-linter
