### ISSUE TITLE
[en] FPs EN_COMPOUNDS

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#4122]
The java rule EN_COMPOUNDS gives false positives in passive sentences ([see Diff](https://internal1.languagetool.org/regression-tests/via-http/2021-01-11/en-US/result_java_EN_COMPOUNDS.html)):

_But Page at the FSA appears to offer some hope that the disclosure requirements will be **watered down**._ → in this context, it is a verb form and should not be hyphenated.

**Comment by tiff** [comment]
I have already removed it from compounds.txt and moved it to the COMPOUND_ADJECTIVE rule which only matches when there's a noun after it.
