### ISSUE TITLE
[fr] "droit(s) humain(s)" is not an "anglicism"

### ISSUE THREAD

**Issue by Thibaut120094** [languagetool-org/languagetool#4125]
<img src="https://user-images.githubusercontent.com/11076286/104272437-679eef80-549d-11eb-97ff-7299bd441624.png" width=350>

"droit(s) humain(s)" is not an "anglicism" and should not be corrected, it is widely used and accepted in Belgium and Switzerland, some examples:

**Belgium:**
- https://www.liguedh.be/
- https://diplomatie.belgium.be/fr/politique/themes_politiques/droits_humains (government)
- https://www.rtl.be/info/monde/international/huit-pays-dont-la-belgique-denoncent-les-violations-des-droits-humains-en-coree-du-nord-1265205.aspx
- https://www.lalibre.be/international/asie/huit-pays-dont-la-belgique-denoncent-les-violations-des-droits-humains-en-coree-du-nord-5fd46a6d9978e227df07558b
- [And many more](https://duckduckgo.com/?q="droits+humains"+belgique)

**Switzerland:**
- https://www.humanrights.ch/fr/
- https://www.amnesty.ch/fr/themes/droits-humains
- https://skmr.ch/frz/home.html
- https://www.rts.ch/decouverte/monde-et-societe/economie-et-politique/les-droits-de-l-homme/
- https://www.sp-ps.ch/fr/thema/menschenrechte
- https://www.admin.ch/gov/fr/accueil/documentation/communiques.msg-id-3805.html (government)
- https://www.admin.ch/gov/fr/accueil/documentation/communiques.msg-id-76050.html (government)
- https://www.ebg.admin.ch/dam/ebg/fr/dokumente/haeusliche_gewalt/infoblaetter/c4.pdf.download.pdf/c4_conventions-internationales-des-droits-humains-et-violence-domestique.pdf (government)
- https://www.wwf.ch/fr/droitshumains
- https://lecourrier.ch/dossier/chronique-des-droits-humains/
- [And many more](https://duckduckgo.com/?q="droits+humains"+suisse)

In France, the term is used by [Amnesty International](https://www.amnesty.fr/pays/france) and the [International Federation for Human Rights](https://www.fidh.org/fr/) based in Paris, "droits humains" is also [recommended](https://haut-conseil-egalite.gouv.fr/parite/actualites/article/droits-humains-une-expression-qu-il-est-temps-de-generaliser) by the [_Haut Conseil à l'égalité entre les femmes et les hommes_](https://fr.wikipedia.org/wiki/Haut_Conseil_%C3%A0_l%27%C3%A9galit%C3%A9_entre_les_femmes_et_les_hommes). In French Canada, the term is accepted by the very purist _[Office québécois de la langue française](https://en.wikipedia.org/wiki/Office_qu%C3%A9b%C3%A9cois_de_la_langue_fran%C3%A7aise)_ (OQLF): http://www.gdt.oqlf.gouv.qc.ca/ficheOqlf.aspx?Id_Fiche=26544191

**Comment by udomai** [comment]
Bonjour, @Thibaut120094 ! Merci de ton retour si bien documenté. Je suis parfaitement d'accord avec toi.

Ces derniers temps, j'ai vu et déactivé quelques règles concernant des soi-disant "anglicismes" (calques, emprunts, etc.) qui n'en étaient pas vraiment. Si tu en vois d'autres qui te paraissent étranges, merci de nous les signaler.
