### ISSUE TITLE
error in the check method of LanguageTool class for DictionaryMetadata of Brazil

### ISSUE THREAD

**Issue by FranckAJ** [languagetool-org/languagetool#414]
error in the check method of LanguageTool class
"Exception in thread "main" java.lang.NoSuchMethodError: morfologik.stemming.DictionaryMetadata.isFrequencyIncluded()Z"

**Comment by danielnaber** [comment]
Thanks for the bug report. What exactly have you done to get this error or, in other words, how can I reproduce it?

**Comment by FranckAJ** [comment]
I am studying the API to apply for research project that we are developing, by that I test the following code snippet:

`Language language = Languages.getLanguageForLocale(new Locale("pt","BR"));
	    JLanguageTool jlanguage = new JLanguageTool(language);
	    
	    List<RuleMatch> result = jlanguage.check("espero que q encontre mais de um erro erro");
	    
	      for (RuleMatch ruleMatch : result) {
		        System.out.println("    " + ruleMatch);
		        List<String> str = ruleMatch.getSuggestedReplacements();
		        for (String string : str) {
					System.out.println(string);
				}
		      }`

And I came across with the exception that I mentioned earlier, this code snippet works in languages such as English

**Comment by danielnaber** [comment]
I cannot reproduce that. `NoSuchMethodError` indicates that there's a problem with your classpath, i.e. you probably have the wrong version of morfologik in your classpath.

**Comment by FranckAJ** [comment]
I followed the steps in the example provided in the documentation.
the version is 3.3, available in the documentation

**Comment by danielnaber** [comment]
I'm sure this is a local problem with your setup. I cannot reproduce it and nobody else has reported this problem before. Please check your classpath and make sure it contains the same morfologik JARs that are included in the LanguageTool ZIP you can download from languagetool.org (and only those, not additional versions).
