### ISSUE TITLE
[Browser add-on] Developer Mode

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#4142]
Hello!

This is an enhancement request for developers.

Is it possible to have a "Developer Mode On/Off" so that the Premium version uses the nightly changes instead of waiting a week or two?

I am using the browser add-on to find missing words/rules and this feature would be very useful.

Thanks!

**Comment by danielnaber** [comment]
You can configure your own server with the latest rule, I don't think a special mode makes sense.
