### ISSUE TITLE
Easy: participe passé (French : AUX_AVOIR_VCONJ)

### ISSUE THREAD

**Issue by dwoops** [languagetool-org/languagetool#416]
Pour une phrase comme :
Il a regarder la télévision.
Il s'agit de modifier AUX_AVOIR_VCONJ pour ajouter en proposition le remplacement du verbe à l'infinitif en -er par son équivalent en participe passé en -é.
En se limitant aux verbes du premier groupe (simple : -é devient -er) on propose une correction pour une erreur très fréquemment commise.

**Comment by jaumeortola** [comment]
Found by A_INFINITIF and AUX_AVOIR_VCONJ with good suggestions.
