### ISSUE TITLE
[ES] Anúnciate with accent is marked wrong.

### ISSUE THREAD

**Issue by dmarman** [languagetool-org/languagetool#4163]
The imperative of the second person of the singular for "anunciarse" has accent on the vowel "u", but it is marked wrong with the following replacement.

*anúnciate* returns:
![image](https://user-images.githubusercontent.com/19510612/104771070-ec299080-5771-11eb-9ed0-b691fb435af4.png)

**Comment by jaumeortola** [comment]
Thank you. It has been fixed, with a few other similar imperative forms.
