### ISSUE TITLE
No errors detected with "After getting everything working it was still too slow."

### ISSUE THREAD

**Issue by jrmuizel** [languagetool-org/languagetool#4164]
grammarchecker.io suggests: "“After” at the beginning of a sentence usually requires a 2nd clause. Maybe a comma, question or exclamation mark is missing, or the sentence is incomplete and should be joined with the following sentence."

**Comment by tiff** [comment]
Grammarchecker.io is actually using LanguageTool. The rule you are talking about is available in our "picky mode"

**Comment by jrmuizel** [comment]
This is now suggested correctly on https://languagetool.org/
