### ISSUE TITLE
LibreOffice - double spaces in automatic line break aren't highlighted

### ISSUE THREAD

**Issue by kolAflash** [languagetool-org/languagetool#417]
Usually LanguageTool highlights double spaces. But if there's an automatic line break in LibreOffice, right at the double spaces, no blue underline is visible.

You can tell that LanguageTool is recognizing an double space error on that position by navigating to it with the text cursor and pressing the context menu button (or shift F10) on your keyboard. It'll give you the usual LanguageTool context menu, telling you that there are are multiple spaces.

I'm not sure if this is an error by LibreOffice or LanguageTool. Probably the LibreOffice underline feature just isn't made for marking something in a line break. Because errors which exist just over a line break (without the word before/after) don't exist for normal spellchecking.
So could you do a workaround like additionally highlighting the first letter before and after multiple spaces!?

**Comment by kolAflash** [comment]
P.S.

OS: openSUSE 13.2 Linux x86_64, system language is german
(KDE, but running LibreOffice with OOO_FORCE_DESKTOP=gnome environment variable set)

LibreOffice 5.1.3.2 (64 bit)
http://download.opensuse.org/repositories/LibreOffice:/5.1/openSUSE_13.2/

LanguageTool 3.3

**Comment by danielnaber** [comment]
This is an issue in LibreOffice, and I'm not a fan of the idea of adding a workaround just for LO.

**Comment by kolAflash** [comment]
Created a LibreOffice bug:
https://bugs.documentfoundation.org/show_bug.cgi?id=101687

Please find a way together :-)
