### ISSUE TITLE
Missing artifact 

### ISSUE THREAD

**Issue by Ohyeahmanolito** [languagetool-org/languagetool#419]
Always getting this error whenever I import the languagetool-standalone after I build the languagetool-parent.

Missing artifact:
org.languagetool:languagetool-tools:jar:3.4-SNAPSHOT
org.languagetool:languagetool-server:jar:3.4-SNAPSHOT

**Comment by danielnaber** [comment]
`languagetool-standalone` is a top-level project, it's not supposed to be included as a dependency.
