### ISSUE TITLE
Cannot use Languagetool in TeXstudio

### ISSUE THREAD

**Issue by EugeniaWEI** [languagetool-org/languagetool#4190]
When running the Check LanguageTool it returns Tries to start automatically. LT current status: error. 
Following is my seeting. And when I open http://localhost:8081, it shows that Error: Missing arguments for LanguageTool API. Please see https://languagetool.org/http-api/swagger-ui/#/default
![image](https://user-images.githubusercontent.com/62751541/105146880-6a53b180-5b3b-11eb-9e4f-2e82b9d27a9b.png)

**Comment by danielnaber** [comment]
This seems to be a TeXstudio-specific issue, I suggest you report the problem there.
