### ISSUE TITLE
[Feature request] Add link possibility to extra rule files, like barbarisms.txt, wordiness.txt, etc

### ISSUE THREAD

**Issue by neoscopio** [languagetool-org/languagetool#4193]
It would be nice in some cases to present further explanations to the user. My suggestion is to add a link as a normal "replacement", i.e. after a pipe "`|`" and, if the last item of the replacements array starts with `http:// `or `https://`, then add the link to some property, so that get `getUrl()` function can use it.

**Comment by danielnaber** [comment]
This has been implemented for rules based on `AbstractSimpleReplaceRule2`. Add a URL to the second (tab-separated) column and it will be interpreted as a link.
