### ISSUE TITLE
Clean build of "LanguageTool embedded HTTP server" fails with PortBindingExceptions in tests

### ISSUE THREAD

**Issue by fragmer** [languagetool-org/languagetool#420]
Performing a clean build of "LanguageTool embedded HTTP server" version 3.3 or latest/master fails, with several unit tests throwing the following exceptions from HTTPServer constructor:

```
org.languagetool.server.PortBindingException: 
LanguageTool HTTP server could not be started on host "localhost", port 8081.
Maybe something else is running on that port already?
	at org.languagetool.server.HTTPServer.<init>(HTTPServer.java:116)
...
Caused by: java.net.BindException: Address already in use: bind
...
```

This exception is thrown in the following places in **v3.3 source**:
- `HTTPSServerTest.runRequestLimitationTest:44`
- `HTTPSServerTest.testHTTPSServer:64`
- `HTTPServerLoadTest>HTTPServerTest.testEnabledOnlyParameter:208`
- `HTTPServerLoadTest.testHTTPServer:49`
- `HTTPServerLoadTest>HTTPServerTest.testMissingLanguageParameter:228`
- `HTTPServerLoadTest>HTTPServerTest.testTimeout:170`
- `HTTPServerTest.testAccessDenied:189`
- `HTTPServerTest.testEnabledOnlyParameter:208`
- `HTTPServerTest.testMissingLanguageParameter:228`
- `HTTPServerTest.testTimeout:170`

Complete log file for v3.3: https://gist.github.com/fragmer/914bba23c88bf6074cac1c9b55a365e8

The exception is thrown in the following places in the **latest source** (some line numbers differ from v3.3):
- `HTTPSServerTest.runRequestLimitationTest:44`
- `HTTPSServerTest.testHTTPSServer:64`
- `HTTPServerLoadTest>HTTPServerTest.testEnabledOnlyParameter:318`
- `HTTPServerLoadTest.testHTTPServer:50`
- `HTTPServerLoadTest>HTTPServerTest.testMissingLanguageParameter:338`
- `HTTPServerLoadTest>HTTPServerTest.testTimeout:271`
- `HTTPServerTest.testAccessDenied:290`
- `HTTPServerTest.testEnabledOnlyParameter:318`
- `HTTPServerTest.testMissingLanguageParameter:338`
- `HTTPServerTest.testTimeout:271`

Complete log file for master: https://gist.github.com/fragmer/864a9e97ec492dcdca7d028e3824297f

### Steps to reproduce:
1) Get a copy of languagetool v3.3 or master source 
2) run `mvn clean install` on languagetool-server

### System info:
OS: Windows 10 running on amd64; Cp1252; en_US (nb)
JRE: Java SE 1.8.0_92-b14; HotSpot 64-Bit Server VM 25.92-b14
Maven: 3.3.9

**Comment by danielnaber** [comment]
If something is running on port 8080 already (e.g. tomcat), the tests will fail indeed.

**Comment by fragmer** [comment]
Upon further investigation, looks like McAfee Service Agent Common Services process (macmnsvc.exe), part of McAfee Agent software, uses ports 8081 and 8082 by default. So this was not a bug but rather a compatibility issue.  Changing HTTPServerConfig.DEFAULT_PORT and adjusting HTTPSServerConfigTest to another port number allowed me to run all tests successfully and complete the build.
