### ISSUE TITLE
[fr] false alarm ACCORD_NOMBRE[4]

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4202]
User says this is a false alarm:

> En 2012, dans le cadre du 30e anniversaire de Juste pour rire, Stéphan Bureau est responsable de l’animation des grands plateaux télé : l’émission spéciale 30e anniversaire et le Gala du 30e.

![Bildschirmfoto 2021-01-20 um 16 08 32](https://user-images.githubusercontent.com/37363/105194420-d9300b00-5b39-11eb-910a-d4e6f19a9c41.png)

**Comment by jaumeortola** [comment]
Fixed with new rules.
