### ISSUE TITLE
[fr] FRENCH_WHITESPACE only handles space before not after quote

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4204]
> «Le Crime» 

A space before "»" is suggested but not after "«"

![Bildschirmfoto 2021-01-20 um 16 24 30](https://user-images.githubusercontent.com/37363/105196656-257c4a80-5b3c-11eb-8ffd-92532c5ab052.png)

**Comment by udomai** [comment]
@jaumeortola, can you fix this in QuestionWhitespaceRule.java? I see it from line 160 downwards, but I don't know how to go about it...

**Comment by jaumeortola** [comment]
QuestionWhitespaceRule.java and QuestionWhitespaceStrictRule.java should be unified. 

A previous question. What do you prefer? To underline only the quotation marks or to underline also the previous/next word (like in the screenshot)?

**Comment by udomai** [comment]
Thank you for looking into this!

I'd absolutely prefer underlining the previous/next word as well. It is much easier to see and to click on like that.

**Comment by dpelle** [comment]
@udomai 
> I'd absolutely prefer underlining the previous/next word as well. It is much easier to see and to click on like that.

I have the opposite opinion: I prefer to underline as little as possible in general, because underlining too much can cause multiple errors to overlap.  I would therefore prefer to underline the French quotes only.

**Comment by udomai** [comment]
I see what you mean, @dpelle. However, overlapping errors are not a problem. We can change a rule's priority if we want a specific error to take precedence.
Most importantly: An underline under just one punctuation character is just too tiny. As is already the case for "!", ";", ":" etc., we need to underline the word next to it as well.

**Comment by dpelle** [comment]
@udomai wrote:

> However, overlapping errors are not a problem. We can change a rule's priority

That's only mitigating the overlap issue.
Anyway, in this particular case it's not too bad to highlight the word + » as it's not so long.

But the general remark remains.
I've seen in some languages that long portions of sentences are sometimes highlighted which is not nice.
For example, typing "Estos cuatro actos, se van haciendo uno tras otro, y a veces continuamente." and checking in Spanish gives one error with a long section highlighted (first 5 words). I'm sure there are worse offenders.

**Comment by jaumeortola** [comment]
> For example, typing "Estos cuatro actos, se van haciendo uno tras otro, y a veces continuamente." and checking in Spanish gives one error with a long section highlighted (first 5 words).

Thanks for pointing out this issue. It is particularly difficult because there are tokens with max/min attributes before and after the comma. The obvious fix is to write several rules, instead of using max/min.
