### ISSUE TITLE
[DE] Maschengleichung, Maschengleichungen

### ISSUE THREAD

**Issue by mfbehrens99** [languagetool-org/languagetool#4205]
LanguageTool will Maschengleichung zu Maschinengleichung korrigieren, was natürlich Quatsch ist.

![image](https://user-images.githubusercontent.com/58851724/105231120-a9e3c300-5b66-11eb-9f7f-bd865c60505e.png)

Könnte jemand das Wort Maschengleichung zum Wörterbuch hinzufügen?

**Comment by danielnaber** [comment]
Danke, ist hinzugefügt.
