### ISSUE TITLE
[Support request] Support Overleaf V2 website

### ISSUE THREAD

**Issue by RoiArthurB** [languagetool-org/languagetool#4207]
Hello,

Firstly, I'd like to thank you all for this awesome open-source software! It changed my mind and I love it 🤗🤗

Secondly, I'm using a lot Overleaf and I'd love to be able to use LT on it. I saw that [it was possible](https://es.overleaf.com/blog/635-tip-of-the-week-languagetool-a-free-browser-add-on-to-check-your-grammar-and-spelling) with the V1 of the website, and that it's [been asked mid 2020](https://forum.languagetool.org/t/lt-not-working-on-overleaf/6034). 

I wanted to know if it was still on track or if I should drop the hope to use LT on Overleaf 😕😕

**Comment by danielnaber** [comment]
Overleaf.com is now supported starting with version 4.0 or our add-on
