### ISSUE TITLE
[en] False warning WHOS

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#4208]
False warning:

> Tom is the one **who's** rich.

![image](https://user-images.githubusercontent.com/5816160/105340279-94f24880-5bd5-11eb-866b-ae87001fe364.png)

**Comment by tiff** [comment]
This rule caused many more false alarms. I have fixed most of them (including this one):
https://github.com/languagetool-org/languagetool/commit/916ee4913cc046de4aa91abe16123e0bc434eb9d
