### ISSUE TITLE
[de] "neustarten" suggests "Neustarten"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4211]
> Der Computer lässt sich nicht mehr neustarten!

![Bildschirmfoto 2021-01-21 um 19 51 21](https://user-images.githubusercontent.com/37363/105398038-1ec80300-5c22-11eb-8425-9a1e23e2f662.png)

Warum wird hier "Neustarten" vorgeschlagen?

**Comment by danielnaber** [comment]
> Warum wird hier "Neustarten" vorgeschlagen?

Vermutlich: "neustarten" ist nicht im Wörterbuch, aber "(der) Neustart" und davon der Plural Dativ ist "Neustarten".

**Comment by tiff** [comment]
Heißt es denn "neustarten" oder "neu starten"?

**Comment by tiff** [comment]
Hab es schon:
![Bildschirmfoto 2021-01-22 um 12 49 01](https://user-images.githubusercontent.com/37363/105487359-3c43ae00-5cb0-11eb-9776-22b9a14e2b4c.png)

**Comment by tiff** [comment]
Dieser Fehler scheint häufig vorzukommen. ~50 Matches im Rule Editor. Hab eine Regel dafür geschrieben:
https://github.com/languagetool-org/languagetool/commit/77dbb06c976ca493d82b78eeffddab1c76274e3e
