### ISSUE TITLE
Howto reload spelling.txt when HTTP Server is running...

### ISSUE THREAD

**Issue by creaticious** [languagetool-org/languagetool#422]
Hey guys,

i'm using LT in server mode and would like to add new words to ignore to spelling.txt on the fly...so that the new words are ignored on the next spell check...withour restarting the server (!)

I'm sure the dictionary is cached so what can i do to reload it? Is there any function i could use and implement it to the JSON-API...?

Thx!

**Comment by danielnaber** [comment]
The caching is hard-coded to 10 minutes at https://github.com/languagetool-org/languagetool/blob/master/languagetool-core/src/main/java/org/languagetool/rules/spelling/CachingWordListLoader.java#L42, there's currently no way to configure that.
