### ISSUE TITLE
Description for A_A_ACCENT in uppercase (fr)

### ISSUE THREAD

**Issue by roipoussiere** [languagetool-org/languagetool#427]
The description for the french text _Bonjour à vous_ is _A au lieu de À_.

It should be _a au lieu de à_.

test: `curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'text=Bonjour%20a%20vous&language=fr&enabledOnly=false' 'https://languagetool.org/api/v2/check'`

**Comment by dpelle** [comment]
"A au lieu de À" is just the name of the rule.
I don't see why it should be "a au lieu de à"

**Comment by PoorPocketsMcNewHold** [comment]
Especially since this rule correct those precise characters too aswell. I’m against the modification of this rule description.
