### ISSUE TITLE
[en] Incorrect capitalization of suggestion PREPOSITION_VERB 

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#4271]
PREPOSITION_VERB suggests 'CONFIrmation':

> COULD YOU PLEASE ORDER THE FOLLOWING STAMPS FOR THE **CONFIRM** TO EXECUTE?

![image](https://user-images.githubusercontent.com/5816160/106587367-6ebb9980-6541-11eb-8977-7df307b10a6d.png)

**Comment by jaumeortola** [comment]
It can be fixed adding `case_conversion="preserve"` to the `match`:
`<suggestion><match no="3" regexp_match="(?i)rm" regexp_replace="rmation" case_conversion="preserve" /></suggestion>`

Perhaps the "preserve" case conversion should be the default setting. @udomai @danielnaber

**Comment by MikeUnwalla** [comment]
Whoever fixed this, thank you.
