### ISSUE TITLE
[es] HABER_GERUNDIO false positives

### ISSUE THREAD

**Issue by jmartorell** [languagetool-org/languagetool#428]
Introduction of this rule brought many positives and no actual detections in wikipedia/tatoeba runs:

https://languagetool.org/regression-tests/20160625/result_es_20160625.html

However the rule is OK, some cases need to be excluded.

**Comment by jaumeortola** [comment]
This is already fixed here: https://github.com/languagetool-org/languagetool/commit/739acbe2eec20e38539b3fb1188f2b10dbc16b7d
