### ISSUE TITLE
cannot access the server outside localhost

### ISSUE THREAD

**Issue by 1Euro7Cent** [languagetool-org/languagetool#4289]
Even when I try the --public flag the server is still only available in localhost

I use this command to start the server.

java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 25505 --public

The port 8081 is used for something else

**Comment by danielnaber** [comment]
Maybe this is a problem with a local Firewall blocking access?

**Comment by 1Euro7Cent** [comment]
Thanks. That helped
