### ISSUE TITLE
[de] Primärfrequenz

### ISSUE THREAD

**Issue by mfbehrens99** [languagetool-org/languagetool#4306]
![image](https://user-images.githubusercontent.com/58851724/107113795-89ec1900-6861-11eb-9d02-95b61794e661.png)
Scheint mir ein komisches Verhalten. Normalerweise hätte ich es einfach zu `spelling.txt` hinzugefügt, aber das wird ja das eigentliche Problem nicht lösen.

Ist ansonsten irgendwo dokumentiert, wie zusammengesetzte Nomen in das Wörterbuch eingepflegt werden können? 
Danke!

**Comment by danielnaber** [comment]
Dazu müssen sowohl "Primär" als auch "frequenz" mit den richtigen Flags in der `de_DE.dic` stehen. Das ist etwas kompliziert, weil die Datei nicht von uns stammt und die Flags auch rekursiv ausgewertet werden. Wenn du dich damit auseinandersetzen willst, hilft die hunspell-Doku. Ansonsten gerne zur `spelling.txt` hinzufügen.
