### ISSUE TITLE
[DE][LibreOffice] Fehlalarm "Schön zu hören, ..."

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#4314]
Moin liebes LanguageTool-Team

Reiner sagte: „**Schön zu hören**, dass du wieder arbeiten kannst.“
![grafik](https://user-images.githubusercontent.com/78316155/107338859-535e0a80-6abc-11eb-863b-86a64f2a5dc1.png)

@FredKruse  ich glaube, die Regel muss wieder nachgearbeitet werden. Dieser Fehler kommt ausschließlich in LO vor, auch mit aktuellster LT-Version. Ich habe für diesen Fehlalarm heute diese Version installiert.

Schönreden gibt es laut [Duden](https://www.duden.de/rechtschreibung/schoenreden), aber Schönhören gibt es laut Duden nicht. Natürlich hat das nichts zu sagen, weil der Duden nicht jedes Wort auflistet. Nur ist hier der Kontext entscheiden. "Schön zu hören", kann auch bedeuten "Schön dich zu hören". Bei z. B. schönreden würde es so lauten: "Katharina liebt es, ihre Welt **schönzureden**."

Grüße Dallun511

**Comment by FredKruse** [comment]
Man lernt immer dazu. Dass es das Substantiv "Schönhören" gibt, wusste ich auch noch nicht. Der Fehler ist beseitigt. Sollte im morgigen Snapshot behoben sein.

**Comment by MasterDallun511** [comment]
Wat? Als Substantiv existiert das Wort. Damit hätte ich nie gerechnet. Danke dir Fred
