### ISSUE TITLE
[en] False warning TOO_TO

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#4322]
TOO_TO suggests 'to':

> When I tried to speak to her, I always found myself **too** shy to do more than stammer or say something stupid.

![image](https://user-images.githubusercontent.com/5816160/107516467-5df3cf00-6ba4-11eb-93f7-04b37835406c.png)

**Comment by tiff** [comment]
I fixed this one last week. Sorry forgot to close it.
