### ISSUE TITLE
[ru] user feedback "Пре вет"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4329]
> Не смог найти ошибку в слове "Превет", исправляя её просто писав через пробел "Пре вет", а не "Привет".

**Comment by sergus2008** [comment]
В последнее время такое исправление предлагается для большей части неизвестных слов. Просто откалывается начало типа "пре", "при", "не" и т.д. и все нормально, даже если слово без этой части также не существует.

**Comment by yakovru** [comment]
Обновлены настройки генерации предпочтительных вариантов для исправления опечаток.
