### ISSUE TITLE
E-mail addresses

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#433]
LT gives warnings for e-mail addresses. For example, for AmE, the applicable rule is http://community.languagetool.org/rule/show/MORFOLOGIK_RULE_EN_US?lang=en-US.

For English, I could write a disambiguation rule that uses 'ignore_spelling' (http://wiki.languagetool.org/developing-a-disambiguator). But, because the problem is applicable to all languages, I guess that a better option is to correct the problem in the Java, as we do with website addresses (https://github.com/languagetool-org/languagetool/issues/212).

**Comment by f-knorr** [comment]
Should be fixed now

**Comment by jaumeortola** [comment]
There is a regression in the Catalan tokenizer. When a sentence contains an e-mail adress, the tokens are wrong. For example: L'origen de name@example.com. It should be: L' / origen, but it is L / ' / origen.
