### ISSUE TITLE
[DE]Performanceeinbrüche, Abstürze und Aufhänger

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#4332]
Moin liebes LanguageTool-Team

![grafik](https://user-images.githubusercontent.com/78316155/107817831-f3df5380-6d76-11eb-856d-34eb37dd9757.png)
Ich habe vermehrt über Abstürze, Aufhänger und Performanceeinbrüche gesprochen und bisher hat sich nichts geändert. Diese Probleme werden von Snapshot zu Snapshot nicht besser. Früher konnte man diese Probleme umgehen, in dem man das Dokument klein hält, doch dies nicht mehr der Fall.

Durch das HomeOffice/Schooling erstelle ich pro Tag kleine Dokumente und das LangaugeTool hängt sich trotzdem auf und stürzte direkt mit LO ab. Das macht kein Spaß, weil dadurch Datenverlust entsteht.

Hier muss eine Lösung her.

Grüße Dallun511

**Comment by FredKruse** [comment]
Die Abstürze wundern mich. Normalerweise sollte LT LO nicht zum Absturz bringen. Mir ist das noch nicht passiert und ich habe auch keine Idee, wie das passieren kann. Mir fällt auf, dass du offenbar mit dem LO-Rechtschreib-Dialog arbeitest. Dass dadurch ein Absturz, ausgelöst durch LT, zustande kommt, kann ich mir nicht erklären. 
Es gibt mittlerweile einen eigenen LT-Dialog. Vielleicht solltest du den mal probieren.

**Comment by FredKruse** [comment]
Heißt Aufhänger, dass sich die Eingabe verzögert oder dass die Anwendung ganz einfriert?

**Comment by MasterDallun511** [comment]
Von Eingabe wird leicht bis stark verzögert bis zum Abstürzt, letzteres kommt selten vor.

**Comment by MasterDallun511** [comment]
![grafik](https://user-images.githubusercontent.com/78316155/111352810-e58d9b80-8684-11eb-9457-6512eb791d1a.png)
Wenn du diesen Dialog meinst, dann lasse ich es lieber, der funktioniert bei mir gar nicht. Der hängt sich nur auf und lässt sich nicht bedienen.

**Comment by FredKruse** [comment]
Das Problem mit dem LO-Rechtschreibungsdialog muss ein Problem von LO sein. LT liefert in diesem Fall nur Ergebnisse für die Anfragen von LO. An dieser Stelle kann ich nichts machen.
Für den LT-Dialog zu Rechtschreibung und Grammatik habe ich Anpassungen gemacht, die das Handling mehrerer LO-Fenster gleichzeitig betreffen. Damit habe ich alle Probleme, die ich nachvollziehen konnte, behoben.
Bitte teste das mal ab morgen.
Sollten noch weiter solche Probleme auftreten, brauche ich ganz genau die Beschreibung welche Version LO und welches Java benutzt wurde und möglichst die Dokumente, die geöffnet waren.

**Comment by MasterDallun511** [comment]
Ich werde die neue Version testen, sobald meine neue Grafikkarte angekommen ist. Sie stürzt zurzeit regelmäßig ab. Der Grund ist mir unklar, aber ich vermute, dass sie mit der neuen Windows-Version nicht mehr kompatibel ist.

Meine LO-Version ist aktuell 7.0.5.2 (64x)
Meine Java Version ist 15.0.2

**Comment by FredKruse** [comment]
Hast du den LT-Dialog noch mal getestet?

**Comment by MasterDallun511** [comment]
Habe ich, aber nicht viel, da es im Gegensatz zum normalen Diaglog nicht funktioniert. Es bricht gerne die Überprüfung ab oder hängt sich auf. Gelegentlich schließt sich das Fenster und fängt von vorne an.

Ich sehe Potenzial, aber zurzeit nutze ich lieber das alte Dialog. Mit neuen Dialog hatte ich zumindest keinen Abstürz mehr und die Performace ist ein wenig besser gefunden, zumindest empfinde ich das.

LanguageTool 5.3 Release Version vom Forum.

**Comment by FredKruse** [comment]
In den letzten Versionen sind große Anstrengungen unternommen worden, die Stabilität zu verbessern. Ich schließe das Issue. Bitte öffne ein neues für die aktuelle Version, sollten weitere Probleme auftreten.
