### ISSUE TITLE
(Feature Request) Desktop and iOS App for Languagetool

### ISSUE THREAD

**Issue by dtantono** [languagetool-org/languagetool#4334]
Hi
I know Languagetools competitors like Grammarly and ginger have a desktop and iOS app for proofreading any misspelling on different texts in different apps. Is it possible for Languagetool to have a desktop and mobile app in Windows, macOS, iOS and Linux?

**Comment by lucknaumann** [comment]
They used to have a desktop app that was a jar file, and I believe it was cross-platform. It disappeared some time ago. Version 5.1.3 is the only version I can find, and the Releases section has a v5.3 source code as of Mar. 29th. I don't know the reason for ceasing the release of the jar binary, but I second the motion of a re-release. I'm on Windows, but a mobile app for Android as well would be cool.

**Comment by danielnaber** [comment]
> They used to have a desktop app that was a jar file

That is still available at https://languagetool.org/download/

**Comment by lucknaumann** [comment]
@danielnaber Thanks! I didn't see a link indicating that on the website, so thought it was removed. Maybe I missed it? Anyway, thanks for the super quick reply! 😄

**Comment by MikeUnwalla** [comment]
Nice one.

1) On https://languagetool.org/windows, the button 'Get for Windows' links to the file `LanguageTool-1.0.2.exe`. The standalone jar file is in `LanguageTool-5.5.zip`.

To make clear that checker for Windows and the standalone jars are different, change the file name of the exe to something like `LanguageTool-for-Windows-l-1.0.2.exe`.

Explain the differences between the 2 files on the https://languagetool.org/windows page.

2) The first screen shot shows the online LT Editor. Shouldn't it show a Windows program such as Excel, Word, or Outlook?

3) After the installation of `LanguageTool-1.0.2.exe`, I guess that LT uses the open-source rules that are on languagetool.org.
a) Is my guess correct?
b) Can the user change the set of rules that are used?

Suggestion: put this information on the page.

**Comment by danielnaber** [comment]
> After the installation of LanguageTool-1.0.2.exe, I guess that LT uses the open-source rules that are on languagetool.org.
> a) Is my guess correct?

For non-premium users, it uses the API documented at https://dev.languagetool.org/public-http-api. This is mostly the Open Source rules, often with some additional rules added for our testing.

> b) Can the user change the set of rules that are used?

No.

**Comment by MikeUnwalla** [comment]
@danielnaber, thanks.

If I install `LanguageTool-1.0.2.exe`, are the browser add-ons and the Windows plugin for Microsoft Word redundant?

I don't understand what `LanguageTool-1.0.2.exe` does. "LanguageTool adds advanced spelling, grammar and style correction to Windows". But, Windows is an operating system. Does the exe add spelling/grammar correction to all programs that use Windows? Only to some? And if only some, which ones?

**Comment by danielnaber** [comment]
LanguageTool-1.0.2.exe is just a Windows application. It replaces neither the browser add-on nor the Word add-on. It covers the many cases where people want to check texts in a software we don't have an add-on for. It's impossible to closely integrate everywhere, but you can check your text using a shortcut which open the LT application.

**Comment by MikeUnwalla** [comment]
Thanks for the clarification. Might be worth putting on the web page (I struggled to understand, and I'm on the team.)

**Comment by ShredderWalnut** [comment]
Hello,

> It’s impossible to closely integrate everywhere

I’ve always thought it was impossible as well, but I just saw that the recently released [Grammarly Desktop](https://www.grammarly.com/desktop) app can check nearly everywhere. How is this technically feasible, and can LanguageTool implement a similar feature? Thanks :)

**Comment by Gatherix** [comment]
Is there any way to use the Windows application with a custom LanguageTool API server? I can't find a setting anywhere

**Comment by danielnaber** [comment]
> Is there any way to use the Windows application with a custom LanguageTool API server? I can't find a setting anywhere

Sorry, that's not possible.

**Comment by dtantono** [comment]
I know iOS and Linux version still not yet release and this issue have been closed. why?

**Comment by tiff** [comment]
@dtantono iOS https://languagetool.org/ios
