### ISSUE TITLE
Check URLs in grammar.xml

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#434]
Refer to 'Broken URL in Catalan and Polish grammar files' (https://sourceforge.net/p/languagetool/mailman/message/35212313/).

Is it possible for testrules to include a check for broken URLs?

**Comment by dpelle** [comment]
> Is it possible for testrules to include a check for broken URLs?

I would rather not do that.  Checking for URL accesses many web sites, and several links on the same web sites, which is not a nice thing to do: it hogs resources on those web sites if we do it too often.  I think it's OK to check for broken URL every few months (before a release for example).

**Comment by danielnaber** [comment]
I agree with Dominique, accessing the web during tests is asking for trouble. But we already have a script `checkurl.bash` for occasional use.
