### ISSUE TITLE
[pt-br] user feedback "te amo"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4344]
> A frase "te amo" começa com pronome oblíquo o que é incorreto na língua portuguesa, porem aparece sem nenhum erro. Apesar de nativos da língua portuguesa falarem te amo, esta frase está errada.

**Comment by marcoagpinto** [comment]
@tiff 

https://github.com/languagetool-org/languagetool/commit/010b4cacc2f96ec2e3a3366122689f3583e43f71

How do I make \2 suggest in lowercase?

```
Title: Tatoeba-768550
1.) Line 1, column 1, Rule ID: LHE_S_TE_VOS_VERB[1]
Message: Substitua por 'dou-Te'.
Suggestion: Dou-Te
Rule source: /org/languagetool/rules/pt/grammar.xml
Te dou cinco dólares.
^^^^^^               
Article: 100
```

It suggests "Dou-Te" instead of "dou-te" ("te" lowercase).

Thanks!

@jaumeortola Can you help? Thanks!

**Comment by jaumeortola** [comment]
> How do I make \2 suggest in lowercase?

`<match no="2" case_conversion="lowercase"/>`

**Comment by tiff** [comment]
I think it's 

```
<match no="2" case_conversion="alllower"/>
```

**Comment by jaumeortola** [comment]
> <match no="2" case_conversion="alllower"/>

Yes. Right!

**Comment by marcoagpinto** [comment]
Thanks, about to buy some Coca-Cola, will fix it when I return.

**Comment by marcoagpinto** [comment]
Done!

https://github.com/languagetool-org/languagetool/commit/2215966bdf2f8695de210f9d70dacef0bd9fc118

Thanks @Tiff and @jaumeortola
