### ISSUE TITLE
[pt] not found: "Queria comprar una rosa"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#4348]
User feedback:

> "Queria comprar una rosa" should not pass the Portuguese checker

**Comment by udomai** [comment]
The only mistake in the above sentence is the (quite probable) typo una/uma.
Since "una" is a valid form of the verb "unir", this requires an xml rule that looks for contexts like this and proposes the correct indefinite article "uma".

**Comment by marcoagpinto** [comment]
Ahhhh... I will fix tomorrow at 5am.

**Comment by marcoagpinto** [comment]
A confusion rule "una/uma"

**Comment by marcoagpinto** [comment]
Rule created: https://github.com/languagetool-org/languagetool/commit/20087bc0d4d0a7b7762f03c0a759eeb4c7ac462f
