### ISSUE TITLE
[fr] typo in message?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4349]
User says:
> Bonjour,
> Dans le mode méticuleux, il est écrit "Insérer un espace insécable" à chaque fois, au lieu de "Insérer une espace insécable", l'espace étant féminin en typographie !
> Petit bug à corriger !

**Comment by dpelle** [comment]
Indeed, some message say "une espace" and some say "un espace".
We should consistently say "une espace" when it's about the typographical space.

**Comment by udomai** [comment]
Fixed in Premium as well.
