### ISSUE TITLE
[en] Proper Noun false capitalizations

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#4359]
These two examples recommend capital letters, but it seems like the normal terms would be _much_ more common than the movie or band:

> The themes most widely promulgated in our general culture—via books, magazines, humor, **pulp fiction**, or high drama—seem to confirm this.

"Pulp Fiction" is recommended.

> And his weapons are infinitely more refined than such clumsy contrivances as the rack and the **iron maiden**.

"Iron Maiden" is recommended.

**Comment by tiff** [comment]
Thank you. I will remove them from the list

**Comment by tiff** [comment]
Fixed as part of https://github.com/languagetool-org/languagetool/commit/61880b0b3ab7bd02857fe1d62ef21ac9ad47a7a6
