### ISSUE TITLE
Error Rules in LanguageTool Community shows the token number, not the correction

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#436]
![languagetool-community-error-message-shows-token-number](https://cloud.githubusercontent.com/assets/5816160/16800979/ff66a2ae-48ef-11e6-91fc-f292cee15043.png)

**Comment by danielnaber** [comment]
The correction depends on the input sentence, but there can be many input example sentences, so we'd have to show many messages. As this is mostly an internal tool for rule developers, I think it's okay to show the number here.
