### ISSUE TITLE
[en] "will of" -> "will have" false positives

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#4362]
**"will have" Recommended (False Positives)**

> You failed to defend the free **will of** young women such as herself.
> The representative **will of** actual people is not being recorded properly.
> The authority of the law had given way “to the arbitrary **will of** particular groups.”
> They were given the free **will of** young women such as herself.

I'm assuming "free will" is also a very common term.

**Comment by tiff** [comment]
Thank you for your great input!
