### ISSUE TITLE
[en] so/yet comma wrong within common phrases

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#4364]
**", so" Recommended (Wrong)**

> However, the point here is not that sometimes the facts are hard to gather and that the adjudicator makes a judgment and in** so** doing creates some ethical fact about who ought to bear what burdens.

"in so doing" + "in doing so" is a common English phrase:

https://english.stackexchange.com/questions/361803/in-doing-so-vs-in-so-doing

**", yet" Recommended (Wrong)**

> We can now consider** yet** another interesting argument proposed by Socrates.

Unsure what a rule could be—maybe "consider yet another"?—but the comma does not belong before "yet" in this case.

**Comment by tiff** [comment]
Fixed via https://github.com/languagetool-org/languagetool/commit/b157f888f3546f44ae2e0b0b0fa143beb2a630c1
