### ISSUE TITLE
[en] Smith's -> Smiths (first + last name + 's) false positive

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#4367]
Here's a real headscratcher...

**Smith's -> Smiths Recommended**

> If Professor Spengler has in mind a risk theory of profit such as Adam **Smith’s** where part of the undertaker’s profits were for risk bearing and the other for interest return on capital, then he is certainly correct.

This hits the rule:

"Possible typo: Consider using the plural form here"

Unsure how broad this false positive is. It looks like this error occurs with "last names", because it doesn't hit if you only have 1 name:

> If Professor Spengler has in mind a risk theory of profit such as Smith’s where part of the undertaker’s profits were for risk bearing and the other for interest return on capital, then he is certainly correct.

It also doesn't hit if you add an (undetected-by-LT) comma after "Smith's":

> If Professor Spengler has in mind a risk theory of profit such as Adam **Smith’s, where** part of the undertaker’s profits were for risk bearing and the other for interest return on capital, then he is certainly correct.

This simpler sentence also doesn't cause a hit:

> Examples such as Adam Smith’s are certainly correct.

**Comment by tiff** [comment]
Fixed via https://github.com/languagetool-org/languagetool/commit/fdd9c892789bc811dff01be0246fb24623052405
