### ISSUE TITLE
[en] "are loathe to" -> "are loath to": M-W.com article

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#4372]
Maybe this article could be added in the clarification bubble:

[M-W.com: "Is It 'Loath' or 'Loathe'?"](https://www.merriam-webster.com/words-at-play/is-it-loath-or-loathe)

That might help others who get stuck on this. :)

Here's another example sentence:

> Common sense also reflects many things people **are loathe to** acknowledge, at least in public.

LT recommends "are loath to".

**Comment by tiff** [comment]
Implemented as part of https://github.com/languagetool-org/languagetool/commit/fdd9c892789bc811dff01be0246fb24623052405
Thanks!
