### ISSUE TITLE
[en] "WW I"->"WW, I" (World War I) false positive

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#4373]
"WW I" is short for "World War I":

> During **WW I**, as during earlier wars, belligerent governments went off the gold standard.

Should be treated the same as:

- WWI
- WW1
- WWII
- WW2
- WW II

**Comment by tiff** [comment]
Fixed as part of https://github.com/languagetool-org/languagetool/commit/fdd9c892789bc811dff01be0246fb24623052405
