### ISSUE TITLE
[en] there's->"there are" false positive

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#4379]
These recommend "there are a X":

> Now **there’s a munitions** factory in the town.
> Now **there’s a weapons** factory in the town.

I think the underlying issue is "munitions" and "weapons" could also be singular.

These sentences are fine:

> Now there’s a clothing factory in the town.
> Now there’s a factory in the town.

After fix, may also want to test the "fixed" sentences:

> Now **there are a munitions** factory in the town.
> Now **there are a weapons** factory in the town.

**Comment by tiff** [comment]
Fixed as part of https://github.com/languagetool-org/languagetool/commit/fdd9c892789bc811dff01be0246fb24623052405
