### ISSUE TITLE
[en] does->doe

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#4383]
This sentence is already correct:

does->doe
> There is chaos, as each **does** whatever he wants, regardless of what others may or may not want.

**Comment by MikeUnwalla** [comment]
Caused by incorrect disambiguation in EACH_VB_NN

**Comment by tiff** [comment]
Fixed as part of https://github.com/languagetool-org/languagetool/commit/fdd9c892789bc811dff01be0246fb24623052405
