### ISSUE TITLE
[en] "could arguable"->"could be/have arguable" (Wrong recommendation)

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#4385]
> They **could arguable** endanger and thus violate the rights of innocent third parties.

LT currently recommends:

- "could arguable"->"could be arguable"
- "could arguable"->"could have arguable"

The correct recommendation would be:

- arguable->arguably

If you make LT's recommended change, we also get this example sentence:

> They could have arguable endanger and thus violate the rights of innocent third parties.

LT says no issues.

("have arguable endanger"->"have arguably endangered" might be the reasonable recommendation).

**Comment by tiff** [comment]
Fixed as part of https://github.com/languagetool-org/languagetool/commit/fdd9c892789bc811dff01be0246fb24623052405
