### ISSUE TITLE
[en] Undetected lowercase->uppercase sentence start

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#4393]
This is a headscratcher.

LT doesn't recommend a capital letter at beginning of 2nd sentence:

if->If
> The politicized civil service had built up. **if** Jefferson had followed circulation-of-elites, rotation in office principles, he would have booted out the Federalists and installed good Republicans.

But if you remove the "up" from the previous sentence, LT detects correctly:

> The politicized civil service had built. **if** Jefferson had followed circulation-of-elites, rotation in office principles, he would have booted out the Federalists and installed good Republicans.

**Comment by MikeUnwalla** [comment]
LT does not split the sentences correctly.
![image](https://user-images.githubusercontent.com/5816160/108356153-ada94a80-71e3-11eb-985a-30c429082e60.png)

**Comment by danielnaber** [comment]
This was fixed with https://github.com/languagetool-org/languagetool/commit/81452e8e53d42ff2a1f9a14185a5ec855a845cae
