### ISSUE TITLE
[en] hears->years

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#4395]
Currently undetected:

hears->years
> Mill knew little in detail about the history of British society in the two hundred and fifty **hears** before he was born.

Maybe rule looking for # + "hears" should recommend "years".

**Comment by udomai** [comment]
Hi @Tex2002ans! Thank you so much for all your valuable and well-documented feedback!

All of it will be integrated into LanguageTool and help improve the software, so: many thanks :) some of your issues might get fixed right away, others might take longer, I just thought I'd mention that.

If you'd like to do us a solid, you could "collect" several similar problems in one issue. I thought of that when I saw your 38 issues posted in the last 24 hours. Systematic weaknesses are easier to track in "collection issues"; fragmented micro-issues risk drowning among all the other issues.
For example: #4394 and this issue are both what we call "confusion pairs". Your input would be easiest to process if you could collect confusion pairs like this in one issue, grammatical problems in another one, etc. etc. — that way, if you spot a similar problem, you can add it to an already existing issue.

And, by the way: Would you like to talk about taking an even more active part in the LT team? If so, please let me know how I can best reach you.

**Comment by Tex2002ans** [comment]
> And, by the way: Would you like to talk about taking an even more active part in the LT team? If so, please let me know how I can best reach you.

Sounds great. Reach me in this email.

(I just joined up Github, so not sure if it's public.)

You can contact me at:

[insert my username] + @gmail.com

> Hi @Tex2002ans! Thank you so much for all your valuable and well-documented feedback!

No problem. :)

> I thought of that when I saw your 38 issues posted in the last 24 hours. Systematic weaknesses are easier to track in "collection issues"; fragmented micro-issues risk drowning among all the other issues.

Okay, I'll keep that in mind in the future.

> If you'd like to do us a solid, you could "collect" several similar problems in one issue.

Thanks for the info.

I wasn't sure what would be easier:

- mammoth dumps of hundreds?
- or trying to split smaller bugs.

I have thousands of errors I've collected over the years—using Word, LT, Antidote, manually, [...]—and I decided it was finally time to get this all integrated into LT!

> For example: #4394 and this issue are both what we call "confusion pairs". Your input would be easiest to process if you could collect confusion pairs like this in one issue, grammatical problems in another one, etc. etc. — that way, if you spot a similar problem, you can add it to an already existing issue.

Ahh, that's what I was trying to do... I guess I failed. :P

I was thinking "similar by solution":

- missing words/terms
- comma issues
- that->than
- a->an
- [...]

not necessarily by type.

- - -

Speaking of...

It would be nice if there was a way to visualize all "Confusion Pairs" or hits by category:

(I discussed this concept in detail back in [my 2018 MobileRead thread, "Does Tool Exist to Spellcheck/Grammarcheck by Category?"](https://www.mobileread.com/forums/showthread.php?t=310766).)

When working on book-level scales, that process becomes so much more efficient. :)

The closest grammarchecker I've seen to this is Antidote. So you're able to drill down and focus ONLY on:

- hyphen issues
- misspellings
- commas
- [...]

Having a tree-like structure would allow me to plop in tons of sentences, then report what fix belongs where! :)

**Comment by tiff** [comment]
I created a rule for years/hears confusion: https://github.com/languagetool-org/languagetool/commit/fdd9c892789bc811dff01be0246fb24623052405#diff-54b065c892e9aa885ae95cc110a0fc4cc77abba8c81e0eb1c417a27261f966afR74568-R74580
