### ISSUE TITLE
[en] "United State"->"United States" (Typo)

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#4397]
LT doesn't detect these.

Should probably recommend

United State->United States
> The largest private provider of ADR services in the **United State**, the American Arbitration Association, administered 62,423 cases in 1995.

Here's a few more example typos I created:

> In the **United State** of America.
> In the **united state** of America.
> In the **Unite States** of America.

I'm assuming the "United States of America" regex just needs an 's' or 'd' optional:

- united*
- states*

**Comment by tiff** [comment]
Fixed as part of https://github.com/languagetool-org/languagetool/commit/fdd9c892789bc811dff01be0246fb24623052405
