### ISSUE TITLE
[ru] False positive

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#440]
"Разработка ПО за деньги" gives a false positive at current version. 
"Можешь взять пиво какое либо водочки налей." current LT suggest to use "какое-либо", the correct case is to put a comma. 

The first false positive was completely resolved with my PR #439 , the second pattern was moved from compounds to rules in the same PR, so it should be possible to provide some exception  this way.
However, RU maintainer @yakovru claimed that this PR "slows down the loading of the program"
https://github.com/languagetool-org/languagetool/pull/439#issuecomment-236390558

This way the current issue will probably never be resolved. @danielnaber Daniel, could you please resolve this conflict? I believe that the correctens is the fist objective for LT, speed is the second one. The correctness should not suffer for speed. The next point is that I am not sure that two token rule is more expensive than a 60 words search

**Comment by danielnaber** [comment]
Moving some detection rules to `grammar.xml` to get a more detailed error message than by the generic Java rule seems to make sense to me, but I cannot comment on specific cases in a language I don't speak...

**Comment by kostyfisik** [comment]
@yakovru I agree, it was a bit Yoda style :) However, I can construct a valid example for a modern dialog "Мороженное будешь? Выбирай какое либо сливочное, либо шоколадное."  LT gives a wrong suggestion to put "-", while I would expect a comma or ":". Anyway, it should be easy to detect a double "либо" in the sentence , which will provide a large family of possible exceptions.  Another exception, I can not construct a valid exception is (again, a bit Yoda style, still rather valid for everyday dialog) "Если постучится кто то дверь не открывай, а зови на помощь." - most natural correction is again to put a comma before "то".  @yakovru  If you reopen PR than I will continue on moving "-то -либо -нибудь" into a grammar.xml

**Comment by kostyfisik** [comment]
It seems that the correct way of usage for "-то -либо -нибудь" is a hyphen or a comma beforehand without any exceptions. Is it possible to show both variants to the user so he can select the case that fits his needs? 

In my previous example "Если постучится кто то дверь не открывай, а зови на помощь." (it is for sure incorrect) from grammatical point of view both cases are correct 1) "Если постучится кто-то, дверь не открывай, а зови на помощь." 2) "Если постучится кто, то дверь не открывай, а зови на помощь."

**Comment by yakovru** [comment]
Fixed. Rules for  "-то" "-либо" placed in grammar.xml, rule for "-нибудь" is in java code with wordlist compounds.txt. I make exception if  sentence contain  two or more  "то" оr "либо".

**Comment by kostyfisik** [comment]
wrong spaces around '-' see the screenshot
![screenshot from 2016-11-11 19-30-26](https://cloud.githubusercontent.com/assets/5239997/20222188/5c63fc5e-a845-11e6-9e58-f6bf1a797bdb.png)

**Comment by yakovru** [comment]
It's a conflict between two rules: ESLI_TO and Defis_to. I'll try resolve it.

**Comment by yakovru** [comment]
Fixed.
