### ISSUE TITLE
[ru] Pronouns gender is not provided

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#441]
он	PNN:Sin:Nom:P3  should be Masc
она	PNN:Sin:Nom:P3  should be Fem
оно	PNN:Sin:Nom:P3  should be Neut

It is needed to provide a rule for consistent gender usage in the sentence e.g.
CORRECT он  сидел	PNN:Sin:Nom:P3  VB:Past:Masc 
CORRECT она сидела PNN:Sin:Nom:P3  VB:Past:Fem 
CORRECT оно сидело PNN:Sin:Nom:P3 VB:Past:Neut 
CORRECT они сидели PNN:PL:Nom:P3 VB:Past:PL 
WRONG она	сидел PNN:Sin:Nom:P3 VB:Past:Masc

**Comment by yakovru** [comment]
Agree. I add this POS tag today.

>
>он    PNN:Sin:Nom:P3  should be Masc
>она  PNN:Sin:Nom:P3  should be Fem
>оно  PNN:Sin:Nom:P3  should be Neut
>It is needed to provide a rule for consistent gender usage in the sentence e.g.
>CORRECT он  сидел    PNN:Sin:Nom:P3  VB:Past:Masc 
>CORRECT она сидела PNN:Sin:Nom:P3  VB:Past:Fem 
>CORRECT оно сидело PNN:Sin:Nom:P3 VB:Past:Neut 
>CORRECT они сидели PNN:PL:Nom:P3 VB:Past:PL 
>WRONG она    сидел PNN:Sin:Nom:P3 VB:Past:Masc 
>


-- 

Yakov Reztsov

**Comment by kostyfisik** [comment]
Fixed.
