### ISSUE TITLE
quotes in message get incorrectly modified

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#4412]
We have this message:

```
unpaired_brackets = Zeichen ohne sein Gegenst\u00fcck: ''{0}'' scheint zu fehlen
```

... which gets somehow transformed to this, i.e. the quotes become two starting quotes, because `"` is probably a special case:

```
Message: Zeichen ohne sein Gegenstück: ‚"‚ scheint zu fehlen
```

If there's no easy fix in the code, I'd just change the message to not contain the quotes. @jaumeortola, what do you think? I guess this is caused by our automatic improvements of the quote characters.

**Comment by jaumeortola** [comment]
There is a similar problem in some English rules like `<message> ...<suggestion>'s</suggestion> ...</message>`. I will try to fix these issues more generally.

**Comment by jaumeortola** [comment]
Related problem in message: `Please use either “didn’t” or “didn’t”.`

**Comment by danielnaber** [comment]
Maybe also related?

![image](https://user-images.githubusercontent.com/857004/111385246-c86bc380-86aa-11eb-9b52-e06b66592b14.png)

This is `HERAB_SINKEN` from `grammar-premium3.xml`.

**Comment by udomai** [comment]
This is so strange! I have been able to reproduce this only with such verbs where the PA2 coincides with some other form of the verb.

herab geschrieben → works fine
herab behandelt → bugs (behandelt = PA2 and VER:3:SIN:PRÄ:SFT etc.)
herab verlaufen → bugs (verlaufen = PA2 and VER:3:PLU:PRÄ:NON etc.)

Provisional fix: exception for `VER:[123].*`

**Comment by jaumeortola** [comment]
The same in the command line: 
```
2.) Line 1, column 51, Rule ID: HERAB_SINKEN[1]
Message: Wenn hiermit eine Form des Verbs ‚herabbehandeln‘ gemeint ist, wird „herabbehandelnbehandeln‘ gemeint ist, wird „herabbehandeln“ zusammengeschrieben.
Suggestion: herabbehandelnbehandeln' gemeint ist, wird <suggestion>herabbehandeln
...ollte das europäische Volk nicht so von oben herab behandeln. 
                                                ^^^^^^^^^^^^^^^
```
The quotation marks are wrong. I will debug this.

**Comment by jaumeortola** [comment]
The problem with HERAB_SINKEN is not related to advanced typography. It is a bug in the synthesizer (several matches in the message). It can be avoided just changing a bit the message.

**Comment by jaumeortola** [comment]
The cause of the problem is that the synthesizer generates two suggestions: `behandeln` and `Behandeln` (capitalized). I don't know if that is right. Shouldn't verbs be all lower case? 
Solutions: fix the dictionary or simplify the message.
