### ISSUE TITLE
[uk] user feedback

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4417]
> інколи неправельно підбирає слова наприклад на "витікаюча речовина" він підбирав "що проходить речона "хоча вона там зовсім не підходить

I'm not sure what he means. Feel free to close this issue if not helpful.

**Comment by arysin** [comment]
In general present time active participle (активні дієприкметники теперішнього часу) not recommended in Ukrainian.
We have specific rules with replacements for hundreds of them but for the rest it's just a generic suggestion, then user would have to think what's the best way to replace it.
