### ISSUE TITLE
[ru] rule "По-прежнему"

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#442]
If there is no NN:Masc:Sin:D after "по прежнему" before comma, then it should be written with hyphen.
If there is a  NN:Masc:Sin:D after "по-прежнему" before comma, it should be written without hyphen. 

http://russkiiyazyk.ru/orfografiya/pravopisanie/kak-pisat-pravilno-po-prezhnemu-ili-po-prezhnemu.html
СORRECT Я спускаюсь к речке по прежнему пути, знакомому с самого детства.
CORRECT Я поступлю по-прежнему, как бы вы меня ни уговаривали

similar rules can be provided for по–моему, по- другому, по- весеннему, по–зимнему и т.д.
 
WRONG Он был одет по зимнему
CORRECT Он шёл по весеннему снегу

**Comment by kostyfisik** [comment]
I am trying to develop a more general rule for this issue, however, it gives me few false positive. I check it in http://community.languagetool.org/ruleEditor/expert and the first match is "Ко́торосль  — река"
with word "районам" NN:Masc:PL:D after the comma token. I expect that is should not match due to presence of expetion for NN:Masc:.*:D in my rule, however, it is not. Any help?  How to avoid rule matching if there is the pos tag in the end of the sentence?

```xml
<rule>
    <pattern>
        <marker>
            <token regexp="yes" >по|По</token>
            <token  postag="ADJ:Masc:D"> </token>
        </marker>
        <token>,</token>
        <token skip="-1">
            <exception postag_regexp="yes" postag="ADJ:Masc:D|NN:Masc:.*:D|ADJ:Neut:D|NN:Neut:.*:D"></exception>
        </token>
        <token postag="SENT_END"></token>
    </pattern>
    <message>Слово пишется через дефис: <suggestion>\1-\2</suggestion>.</message>
    <short>Пишется слитно.</short>
    <example correction="по-зимнему">Я оделся <marker>по зимнему</marker>, так как было холодно.</example>
    <example correction="по-хорошему">Давай <marker>по хорошему</marker>, иначе будет грустно.</example>
    <!--<example correction="по-зимнему">Я оделся <marker>по зимнему</marker> тепло, так как было холодно.</example>-->
    <example correction="по-прежнему">Я поступлю <marker>по прежнему</marker>, как меня не уговаривай и чем меня не заманивай в эту ловушку.</example>
</rule>
```

**Comment by yakovru** [comment]
You can add    scope="next"   to exception:

<token skip="-1"><exception postag_regexp="yes" scope="next" postag="ADJ:Masc:D|NN:Masc:.*:D|ADJ:Neut:D|NN:Neut:.*:D"></exception>

**Comment by kostyfisik** [comment]
PR #464  with rules to cover cases.
1)  По ADJ smth.
2)  По ADJ smth, smth.

**Comment by kostyfisik** [comment]
I have a rule for "по-" error, that looks to be an extension of the existing rule. However, for some reason it does not match the first (commented out) example. Any ideas?
```xml
<rule>
    <pattern>
        <marker>
            <token postag="ADV" regexp="yes">по-.*</token>
        </marker>
        <token skip="-1"  postag_regexp="yes" postag="NN:Masc:Sin:D|NN:Neut:Sin:D">
           <!--<exception>IP-адресу</exception>-->
        </token>
        <token postag="SENT_END" />                
    </pattern>
    <message>Слова пишутся раздельно: <suggestion>по <match no="1" regexp_match="(по-)(.*)" regexp_replace="$2"></match></suggestion>.</message>
    <short>Пишется слитно.</short>
    <!--<example correction="по прежнему">Я спускаюсь к речке <marker>по-прежнему</marker>, знакомому с самого детства, пути.</example>-->
    <example correction="по прежнему">Я спускаюсь к речке <marker>по-прежнему</marker> пути, знакомому с самого детства.</example>
    <example correction="по весеннему">Лисица проваливалась <marker>по-весеннему</marker> снегу.</example>
</rule>
```

**Comment by yakovru** [comment]
You can add skip="1" to

<marker>
            <token postag="ADV" regexp="yes"  skip="1">по-.*</token>
</marker> 



>Понедельник,  8 августа 2016, 13:57 +03:00 от Konstantin Ladutenko :
>
>I have a rule for "по-" error, that looks to be an extension of the existing rule. However, for some reason it does not match the first (commented out) example. Any ideas?
><rule>
    <pattern>
        <marker>
            <token postag="ADV" regexp="yes">по-.*</token>
        </marker>
        <token skip="-1"  postag_regexp="yes" postag="NN:Masc:Sin:D|NN:Neut:Sin:D">
           
        </token>
        <token postag="SENT_END" />                
    </pattern>
    <message>Слова пишутся раздельно: <suggestion>по <match no="1" regexp_match="(по-)(.*)" regexp_replace="$2"></match></suggestion>.</message>
    <short>Пишется слитно.</short>
    
    <example correction="по прежнему">Я спускаюсь к речке <marker>по-прежнему</marker> пути, знакомому с самого детства.</example>
    <example correction="по весеннему">Лисица проваливалась <marker>по-весеннему</marker> снегу.</example>
</rule>
>


-- 

Yakov Reztsov

**Comment by kostyfisik** [comment]
Thanks, it helped. I`ve added more examples and exceptions. Now the rule does not match the last example (it is new and commented).

```xml
<rule>
    <pattern>
        <marker>
            <token postag="ADV" regexp="yes" skip="1">по-.*<exception regexp="yes">по-моему|по-твоему|по-нашему|по-вашему|по-разному</exception></token>
        </marker>
        <token skip="-1"  postag_regexp="yes" postag="NN:Masc:Sin:D|NN:Neut:Sin:D">
           <!--<exception>IP-адресу</exception>-->
        </token>
        <token postag="SENT_END" />                
    </pattern>
    <message>Слова пишутся раздельно: <suggestion>по <match no="1" regexp_match="([пП]о-)(.*)" regexp_replace="$2"></match></suggestion>.</message>
    <short>Пишется слитно.</short>
    <example correction="по прежнему">Я спускаюсь к речке <marker>по-прежнему</marker>, знакомому с самого детства, пути.</example>
    <example correction="по прежнему">Я спускаюсь к речке <marker>по-прежнему</marker> пути, знакомому с самого детства.</example>
    <example> По-моему, снегу осталось лежать совсем не долго.</example>
    <example> Как, по-вашему, снегу лежать еще долго?</example>
    <example correction="по весеннему">Лисица проваливалась <marker>по-весеннему</marker> снегу.</example>
    <!--<example correction="по весеннему">Лисица проваливалась <marker>по-весеннему</marker>, совсем талому снегу.</example>-->
</rule>
```

**Comment by kostyfisik** [comment]
For new regressions https://languagetool.org/regression-tests/20160808/result_ru_20160808.html  госдолг has no POS tag

**Comment by kostyfisik** [comment]
@yakovru  Other exceptions are in PR #465

**Comment by yakovru** [comment]
You can replace skip="1" to skip="-1", but you get a lot of false positives.

<marker>
            <token postag="ADV" regexp="yes" skip="-1">по-.*<exception regexp="yes">по-моему|по-твоему|по-нашему|по-вашему|по-разному</exception></token>
        </marker>

**Comment by kostyfisik** [comment]
Ok, it seems that this rule in not that general. PR #467

**Comment by yakovru** [comment]
Fixed.
