### ISSUE TITLE
[ru] Two verbs rule

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#443]
Two (or more) verbs of the same form in the same sentence should have a comma or "и" in between.

WRONG Он шёл по улице  говорил по телефону.

relateded false positive: Он смеялся радовался..  (verb+indefinite form verb rule)
![screenshot from 2016-08-01 12-36-44](https://cloud.githubusercontent.com/assets/5239997/17289966/b2e919c6-57e4-11e6-8b12-bce8b7b3722b.png)

**Comment by kostyfisik** [comment]
exception: if there are two nouns in the same form - it is a different rule,  it should be a comma with or without "и"
Наступил вечер закрылся муравейник.

**Comment by kostyfisik** [comment]
@danielnaber Is is possible with LT?
Is it possible to check postag matches for two verbs <token postag="VB:.*" postag_regexp="yes"> one after another ?  E.g., let both verbs have a VB:Past:Masc in their  postag lists, then trigger the rule.

This can easily be done as a set of 23 rules (one rule for each of VB:.*), however, it smells wrong to be a good practice.

**Comment by danielnaber** [comment]
Maybe it's possible with http://wiki.languagetool.org/using-unification, but it would be possible as a Java rule.

**Comment by kostyfisik** [comment]
@yakovru OMG!!! It is not used in Russian! Unification is a major feature for word agreement in Russian!

e.g.  many rules in rulegroups  id="SoglasovanieG", id="SoglasovanieNN_Verb" etc. are just Copy-Paste of each other with only change in gender or number.

**Comment by kostyfisik** [comment]
@danielnaber Wiki seems to be read-only. This way, could you please make Polish grammar rule set metioning at using-unification wiki page to be a link to Polish grammar rule set file https://raw.githubusercontent.com/languagetool-org/languagetool/master/languagetool-language-modules/pl/src/main/resources/org/languagetool/rules/pl/grammar.xml ?

**Comment by danielnaber** [comment]
@kostyfisik Please create an account at wikidot, I'll then give you write permission to the wiki.

**Comment by kostyfisik** [comment]
@danielnaber I suppose it can be usefull to add link to using-unification at tips-and-tricks page (add subsection "word agreement" to writing tools)
My account at wikidots is kostyfisik too.

**Comment by kostyfisik** [comment]
example
WRONG "Когда человек хочет что-то получить ему надо чем-то пожертвовать."

**Comment by yakovru** [comment]
WRONG "Когда человек хочет что-то получить ему надо чем-то пожертвовать."
CORRECT "Когда человек хочет что-то получить, ему надо чем-то пожертвовать."
BEST "Когда человек хочет что-то получить – ему надо чем-то пожертвовать."
It is 2 sentences.

**Comment by kostyfisik** [comment]
Yep. A good correction can also be "Когда человек хочет что-то получить, то ему надо чем-то пожертвовать."
However, for ease of the maintenance I would propose to have a split  rules to detect grammar error from rules for style improvement.  So style recommendation should be another issue. I will open it in few minutes.

**Comment by yakovru** [comment]
Mostly fixed, but need extend rule using unification.

**Comment by yakovru** [comment]
Fixed.
