### ISSUE TITLE
[ru] "C одной" rule

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#444]
If there is no noun  in form  NN:Fem:Sin:T or NN:Fem:Sin:R after "с одной" before the comma, the noun is missing (warning, as it is optional in dialog and was mentioned in some previous sentence) or not in the correct form.  

WRONG  С одной оптимизатору было проще найти минимум.
CORRECT С одной стороны оптимизатору было проще найти минимум.

WARNING С одной человеку проще сладить
CORRECT  С одной заготовкой человеку проще сладить

exception: there is a comma after "c одной"
example Он перепутал шапки: пришёл с одной, а ушёл с другой.

Similar rules can be given for  с одним, с другой, с другим, с другими, с одними

**Comment by yakovru** [comment]
Fixed.

**Comment by kostyfisik** [comment]
False positive "Изготовленные вручную , микроскопы Ван Левенгука представляли собой относительно небольшие изделия с одной очень сильной линзой"

**Comment by yakovru** [comment]
Fixed typo.
