### ISSUE TITLE
[de] loop "hochgeheim"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4440]
> Das ist hochgeheim.

-> hoch geheim

dann 

-> hochgeheim

usw.

Da gibt es bestimmt noch viel mehr solcher Fälle.

**Comment by danielnaber** [comment]
Fixed? Kann es nicht mehr nachvollziehen.

**Comment by udomai** [comment]
Ja, das ist behoben. Getestet mit:

> Das ist hochgeheim. Das ist hochinteressant. Er ist hoch motiviert. Sie ist hochschwanger.

"hoch motiviert" war ein hartnäckiger Loop, aber sogar der ist jetzt weg.
