### ISSUE TITLE
[DE] Bug-Fehlermeldung Februar

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#4443]
Moin liebes Language-Team

![grafik](https://user-images.githubusercontent.com/78316155/108946576-0010be00-765f-11eb-83fb-904a09b99d1d.png)
Der Fehler trat beim Bearbeiten zweier Dokemte statt. Es waren dabei zwei Textdokumente und eine Tabellenkalkulation offen.

Sollte der Fehler behoben sein, Issue schließen und Bescheid geben.

Grüße Dallun511

**Comment by MasterDallun511** [comment]
![grafik](https://user-images.githubusercontent.com/78316155/109535743-32864500-7abd-11eb-89bf-2d9efbba1cc8.png)
Update 01.03.2021. Problem besteht weiterhin.

**Comment by FredKruse** [comment]
Der Fehler ist behoben. Er kann ab morgen mit dem nächsten snapshot getestet werden.

**Comment by MasterDallun511** [comment]
Das kann ich bestätigen, dass dies nicht mehr aufgetreten ist.
