### ISSUE TITLE
[en] "Me and my dad"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4446]
@udomai @MikeUnwalla @Tex2002ans 
I see many users that are disabling the rule `CONFUSION_OF_ME_I` for contexts like this:

> Me and my dad have ....
> Me and my family are ... 

![Bildschirmfoto 2021-02-24 um 15 30 12](https://user-images.githubusercontent.com/37363/109015241-36792800-76b5-11eb-9093-9d0c44224067.png)

To me, as a non-native speaker, it feels like a false alarm.
Do we need an antipattern for "Me and my/your/his/her/their/your/our"?

**Comment by MikeUnwalla** [comment]
The rule is correct. You would not  write, "Me have..." or "Me has..."

**Comment by udomai** [comment]
I would definitely do something about this. It's very common to write "Me and my family have…", and "I and my family have…" doesn't sound natural at all. What does sound good, in my opinion, is "My family and I have…".

How about we put an AP for this case into CONFUSION_OF_ME_I[6] (and other subrules, if relevant) and make a separate rule that replaces "me" with "I" and puts "I" in second place? This can probably only be done for select cases:

`Me and my family|dad|m[ou]m(my)?|daughter|son|aunt|uncle|friend|buddy|chum|pal|(wo)?man` and `Me and NNP`

**Comment by tiff** [comment]
@udomai I'm working on a rule that turns this sentence:

> Me and my family are ...

to:

> My family and I are ...

Would that solve it?

**Comment by tiff** [comment]
Implemented as part of https://github.com/languagetool-org/languagetool/commit/a1de0432a382fa68d1c07f98af512719fbb3eb10#diff-54b065c892e9aa885ae95cc110a0fc4cc77abba8c81e0eb1c417a27261f966afR2797-R2868

**Comment by Tex2002ans** [comment]
I think the "I" is technically correct, but it's all stuffy/super formal.

These examples:

- Me and my dad drank beers together.
- Me and my family went on vacation.

sound perfect to my ear.

So yes, ultimately, it's probably good to refine the rules further... but I can see why me/I rules would have a lot of disables (way too formal for most people).

- - -

It kind of reminds me of the:

- Student: "Can I go to the bathroom?"
- English Teacher: "MAY you go to the bathroom?"

https://english.stackexchange.com/questions/18371/do-serious-grammarians-endorse-the-can-i-may-i-distinction
https://english.stackexchange.com/questions/22258/has-may-become-a-formal-version-of-can/22343

- - -

Another example is the "dad and me" -> "dad and I".

When I'm speaking/writing—even in business writing—I'd NEVER say/use:

- "My dad and I went to the store."

In Fiction, I'd definitely see that rule being disabled often too.

Some people may write/speak that way, but normal humans? No way. :P

I'll have to dig up a Lexicon Valley episode on this too, and a few more articles. I think this may have been an episode he covered this in:

[Lexicon Valley: "When Talking to Your Mother-in-Law Is a Minefield"](https://slate.com/podcasts/lexicon-valley/2020/09/baby-talk-register-linguistics)
- "From baby talk to formal varieties, languages around the world offer—or even require—different ways of speaking for different situations."

- - -

**Side Note:** As an example, I was editing a Fiction book, and the author used "him and I" all over the place, even within all the dialogue. NO realistic human speaks that way, especially not every single character in the book. MAYBE you'd have one character speaking like that if you wanted them to sound posh/formal/sophisticated—no way, José!

**Comment by udomai** [comment]
> @udomai I'm working on a rule that turns this sentence:
> 
> > Me and my family are ...
> 
> to:
> 
> > My family and I are ...
> 
> Would that solve it?

That would be perfect!

**Comment by Tex2002ans** [comment]
I tested these 3 sentences in **Antidote 10v3**:

- **Me and my dad** are happy.
- **Me and my dad** drank six beers together.
- **Me and my family** went on vacation.

Recommendation = just like udomai said, flip both and change me->I.

This is Antidote's explanation:

> **Pronoun Case** – The first person singular pronoun is **I** when it's a subject. When **I** is coordinated, it must be placed in the second position.

- - -

Similar with this sentence (already caught by LT):

- My dad and **me** went to the store.

Antidote says:

> **Pronoun Case** – The first person singular pronoun is **I** when it's a subject.

(It also categorizes all 4 under **Errors > Syntax > Pronoun**.)

**Comment by Tex2002ans** [comment]
Just finished listening to the older Lexicon Valley podcast, pretty interesting.

It specifically covered the case:

- "between X and Y" (me/you/I).

My emphasis added:

> [I]n 2003 a couple of sociolinguists, Phillipp Angermeyer and John Singler, looked at what people actually use. If we think of it again in terms of variables—"between X and Y"—they identified three competing permutations here: "between you and I" and "between you and me," and also "between me and you," putting the "me" first.
>
> [...] **"between you and me" they call the "standard" usage, "between you and I" the "polite" usage and "between me and you" the "vernacular."** And they found that each of these three constructions is favored by a particular demographic. Generally speaking, children and adults with limited formal education, no more than high school say, disproportionately use the vernacular "me and you." The oldest people they studied and those with the most education, Ph.D.s, tended to use the standard "you and me" and those, as they put it, "intermediate in age and level of education favor the polite,"—"between you and I."
> 
> [...]
>
> So, [...] which form is winning? They say in the paper that among the youth and the less educated, "between me and you" is consistent over time and that doesn't appear to be changing. For the rest of us, there's much more of a push-and-pull between the "standard" and the "polite" forms, each with its own advantage. What "between you and me" has in its favor is this sort of ongoing backlash against "between you and I."
>
> Now, I did my own very unscientific Googling of "between you and me" and "between you and I." "Between you and me" gets about four-and-a-half million hits and "between you and I," [...] 80 million hits.
>
>  [...] it's a pretty big disparity. By the way, "between me and you," the "vernacular," gets about a million-and-a-half hits and, you know, there's nothing grammatically incorrect about the "vernacular." It's only a custom of politeness really that says we place ourselves last in a list. In fact, Patricia O'Connor told me that she would rather be technically grammatically correct and say "between me and you" than polite and say "between you and I."

I just did the same informal test in Bing now, and got:

- 436,000,000 = "between you and I"
- 243,000,000 = "between you and me"
- 4,460,000 = "between me and you"

So there you go, it's settled... lol.

Also see:

- [M-W: "Between You and I"](https://www.merriam-webster.com/words-at-play/is-it-wrong-to-say-between-you-and-i)
- [Grammar Girl: "Between Me and You?: Problems Beyond 'I' Versus 'Me.'"](https://www.quickanddirtytips.com/education/grammar/between-me-and-you)
- [Lexico: "Is It 'Between You And Me' Or 'Between You And I'"](https://www.lexico.com/grammar/between-you-and-me)
- [Grammar Monster: "Between You and I or Me?"](https://www.grammar-monster.com/lessons/between_you_and_I_or_me.htm)
- [English Stack Exchange: "Which is correct, “you and I” or “you and me”?"](https://english.stackexchange.com/questions/1047/which-is-correct-you-and-i-or-you-and-me)

(Maybe one of these URLs could be added to the "between you and me" rule?)

**Comment by tiff** [comment]
Thank you all for your input. The rules are now implemented, and I even added some more cases for when "Me and my xxx" is not at the start of the sentence but right after a conjunction. I'm closing this. Feel free to open new issues for specific cases that are not found yet.
