### ISSUE TITLE
[ru] Mistakes in rules

### ISSUE THREAD

**Issue by sergus2008** [languagetool-org/languagetool#4454]
В продолжение [#2443.](https://github.com/languagetool-org/languagetool/issues/2443) Немного поиспользовал аддон для firefox и собрал еще несколько ошибок и предложений. 
 
- [x] 1.  Добавить слова и словосочетания «навроде, анх (пишет, что это имя или фамилия и должно быть с большой буквы, аналогично междометие «бам», слова «толстой», «толстых», «боковых», «миледи»), ищи-свищи, какую-никакую, по-тихому, в конце концов (могут написать через дефис и не определяет как ошибку), приключенец, стажёр,  свежевыжатого,  не очень-то (дефис нужен), отринувшийся
- [x] 2. Добавить словосочетание «что-что, а» (возможность писать «что-что», если после этого есть запятая и «а» или перед этим есть «уж» (https://classes.ru/all-russian/russian-dictionary-Efremova-term-119502.htm)
- [x] 3. Показывает ошибку почти во всех составных словах, написанных через дефис типа серо-зелёный, диван-кровать, либо словах с –то (поговорить-то) и т.д. см. параграф 79 ссылки https://therules.ru/?q=%D0%B4%D0%B5%D1%84%D0%B8%D1%81
- [x] 4. Правило «Нужна запятая или тире (перед «то»)» срабатывает на предложении «Если передумаешь - не тяни, а то я могу всё распродать»
- [x] 5. Правило «Однородные члены предложения» предлагает неправильно исправить предложения «Надеюсь однажды я перестану торчать здесь и смогу увидеть их вновь», «Может что-нибудь поможет в моих странствиях» (предлагает «надеюсь однажды я, перестану» и «Может что-нибудь, поможет».), фразе «выживаю как могу» (предлагает «выживаю как, могу»).
- [x] 6. Правило «Запятая не нужна» предлагает убрать запятую в предложении «Мэр сказал, что нужно ваше разрешение»
- [x] 7. Правило «Запятые при обстоятельственном обороте» предлагает добавить запятую после «и» в предложении «Я здесь, в том числе и чтобы помочь вам».
- [x] 8. Правило «Обычно слитно с «не»» предлагает писать «неопасно» в предложении «Разве не опасно бродить по улицам? Нужно добавить правило Разве не… (чуть ли не…, едва ли не... и т. д.) http://orthographia.ru/orfograf_uk.php?oid=5665 (параграф 147, п. 3)
- [x] 9. Правило «Глагол должен быть в личной форме» срабатывает на предложении «Он в состоянии помочь вам»
- [x]  10. Правило «Запятые не нужны» срабатывает на предложении «Она похожа на крепкую, защищаемую позицию, поэтому, должно быть, открывающиеся вокруг пещеры стали неприятным сюрпризом.»
- [x] 11. Правило «Пропущена запятая» срабатывает на предложении «Это может быть оружие ближнего боя (меч или копьё) или оружие дальнего боя (дротик или лук)». Предлагает поставить запятую после первой закрывающей скобки.
- [x] 12. Правило «Пишется через дефис» срабатывает на предложении  «Судя по мясному рагу и буханке сухого хлеба на столе, вы застигли его за обедом». Предлагает писать по-мясному.
- [x] 13. Правило «Требуется родительный падеж» срабатывает на предложении «Вы ещё на какое-то время избежите той же участи». Предлагает писать «избежите тоя».
- [x] 14. Правило «Ошибка» срабатывает на предложении «Вы видите невысокого роста женщину средних лет». Не считает женщину одушевленным.
- [x] 15. Правило «Запятая» срабатывает на предложении  «Ну, пройдёт скорее даже три года, прежде чем нам разрешат читать». Предлагает поставить запятую после «прежде», я сомневаюсь в ее необходимости.
- [x] 16. Правило «Слитно с «не» срабатывает на фразе  «Совсем не такой».
- [x] 17. Правило «Нужна запятая или тире» срабатывает на фразе  «Если уж на то пошло…»
- [x] 18. Правило «интересовать кого?» срабатывает на предложении  «Мы владеем сокровищами, которые интересуют не только нас.»
- [x] 19. Правило «Пишется слитно» срабатывает на предложении  «Что это за место?»
- [x] 20. Правило «Ошибка в согласовании» срабатывает на фразе  «Виски, которое…». Предлагает «Виски, которые…»
- [x] 21. Правило «Пропущен предлог» срабатывает на фразе  «Не её щеках…». Предлагает «о щеках; в щеках и т.д…»
- [x] 22. Правило «Пропущена запятая в сложном предложении» срабатывает на предложении  «На пристани стоит человек и продаёт билеты». Предлагает «…стоит человек, и продаёт…»
- [x] 23. Правило «Неверное спряжение глагола» срабатывает на предложении  «Вы целую минуту пялитесь друг на друга». Определяет «целую» как глагол
- [x] 24 Правило «Устойчивое выражение» срабатывает на фразе  «Если это так опасно, то…». Предлагает выражение «так как опасно»
- [x] 25 Правило «Стиль: обычно требуется единственное число» срабатывает на предложении  « Торговля приносит немало прибыли». 
- [x] 26 Правило «Требуется множественное число» срабатывает на предложении  «Аня с головой погрузилась под воду». Предлагает написать «погрузились»
- [x] 27 Правило «Грамматическая и прочее» срабатывает на фразе  «в неоплатном долгу»	
- [x] 28. Правило «Разговорная форма» срабатывает на фразе  «Вы уже бежите в укрытие». Предлагает «бегите».
- [x] 29. Правило «Запятая не нужна» срабатывает на фразе  «Они понимают, что нужно …». Предлагает убрать запятую.
- [x] 30. Правило «Пропущена запятая в сложном предложении» не реагирует на наличие скобки Пример: «Вы можете нажать эту кнопку (когда она выглядит…)». А также на наличие многоточия, например «Но я хочу оставить его на память о временах... когда я мог его создавать.»
- [x] 31. Правило «Ошибка в согласовании по числу» срабатывает на фразе  «Империи удалось многое узнать …». Видимо, считает слово «Империи» множественным.
- [x] 32. Правило «Запятая не нужна» срабатывает на предложении  «Совершенно непонятно, кто и зачем создал это». Предлагает «непонятно кто»
- [x] 33. Правило «Пишется слитно» срабатывает на фразе  «Имея это в виду…». Предлагает «ввиду»
- [x] 34. Добавить вводные словосочетания, которые должны выделяться запятыми (важен п. 8 честно говоря, но, может быть, и другие пригодятся),https://www.yaklass.ru/p/russky-yazik/11-klass/sposoby-oslozhneniia-predlozheniia-10915/konstruktcii-grammaticheski-ne-sviazannye-s-predlozheniem-10941/re-68ca8c95-f3f3-4264-a249-f4b6062e21df
- [ ] 35 Не знаю, должно быть так или нет, но ё-фикация не работает.

**Comment by yakovru** [comment]
p.35 Правило для ё-фикации отключено в дефолтных настройках, поэтому в расширении  для Firefox оно может заработать, только если при запуске LT-сервера его активировать через параметры запуска LT-сервера. Работа правила проверялась в приложении для рабочего стола и в расширении для LibreOffice.
p.3 Слово «поговорить-то» программа распознаёт как корректное. В старых версиях LT (старше 1 года), действительно, слова с «-то» не определялись как корректные.

**Comment by sergus2008** [comment]
> p.35 Правило для ё-фикации отключено в дефолтных настройках, поэтому в расширении для Firefox оно может заработать, только если при запуске LT-сервера его активировать через параметры запуска LT-сервера. Работа правила проверялась в приложении для рабочего стола и в расширении для LibreOffice.
Ну, то есть в плагине его без танцев с бубном сейчас не запустить, я понял.
> p.3 Слово «поговорить-то» программа распознаёт как корректное. В старых версиях LT (старше 1 года), действительно, слова с «-то» не определялись как корректные.
Странно, еще недели две-три назад, когда я использовал аддон на актуальной версии, мне показывало ошибку, а сейчас не показывает. Но все равно еще остаются "не очень-то", а также для примера "немного-то"

**Comment by sergus2008** [comment]
p.3. Я все-таки считаю, что необходимо создавать какое-то правило (а не просто вносить слова в словарь), позволяющее писать два любых существительных через дефис. В примере я привёл первые пришедшие в голову словосочетания. Их будет очень много и зачастую они могут быть выдуманы автором. Сочетания цветов и оттенков так вообще - отдельная песня. 
Ну и по поводу "-то" аналогичная ситуация.

**Comment by yakovru** [comment]
>Ну и по поводу "-то" аналогичная ситуация.
Для таких случаев есть универсальное правило. Но его надо еще донастроить (для слов с предыдущего комментария очень-то, немного-то).

**Comment by yakovru** [comment]
П.п. 1-34 исправлены.
Для более удобного управления правилом "пропущена буква Ё" в расширениях для браузера создано issue #5888
По п.3 еще есть issue #3561, в т.ч. по которому реализована проверка правописания слов, оканчивающихся на -то, или с приставками (префиксами):  пол-, обер-, унтер-, лейб-, штаб-, вице-, экс-.
