### ISSUE TITLE
[ru] "В" + noun

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#446]
After single "в" the noun should always be `NN:.*:.*:P`   
CORRECT в случае, в порядке, в домах, в жизни
WRONG  в пределам, в окну, в лампа"

**Comment by danielnaber** [comment]
Although I'm not working on Russian, I guess pull requests would be welcome.

**Comment by kostyfisik** [comment]
My first PR #439 was closed with unmerged commits with RU maintainer @yakovru  . It still has a 100% correct "ПО-за" rule exception and a number of examples for an exception of "-то -либо -нибудь".  All new issues (as proposals for rules) are present in current version of LT, I have checked them locally and on website.  I hope they can be helpfull for someone who has a chance of his PR to be accepted, or I will use tham as a reminder for my future PRs if we can deal with @yakovru about PR #439

**Comment by yakovru** [comment]
It is incorrect.  Preposition "в" use with noun in prepositional case (NN:.*:.*:P)  AND with noun in accusative case (NN:.*:.*:V).
Example: Он смотрел в окно.  (NN:.*:.*:V)
Я увидел её в окне.   (NN:.*:.*:P)

**Comment by kostyfisik** [comment]
Sure,  thank you! So the rule should check if noun is NN:.:.:V or NN:.:.P, otherwise it is an error... I think there can be few exceptions,  they can be figured out after composing the rule and checking against Wikipedia.

**Comment by kostyfisik** [comment]
part of the rule "or NN:.*:PL:Nom"
в мэры
в депутаты
в инструкторы
в инспекторы

**Comment by kostyfisik** [comment]
exception "в долгу" (other words in locative case has a similar :P case)
exception в (up to six words) году ( в 2136 году)

Аттику	аттик  NN:Masc:Sin:D  is probably missing :V (вижу Аттику)
колеса	колесо  NN:Neut:Sin:R  - the same

**Comment by yakovru** [comment]
another exception
https://github.com/languagetool-org/languagetool/commit/e5278eecac46e86b814e99ce7f5080f23c00e22e

**Comment by kostyfisik** [comment]
Mostly fixed
