### ISSUE TITLE
The IBAN bank check doesn't work

### ISSUE THREAD

**Issue by guidoevers** [languagetool-org/languagetool#4461]
Whenever I input a IBAN, it just gets red lined for being wrong.

![image](https://user-images.githubusercontent.com/12197079/109472894-fded9b80-7a72-11eb-8fb3-87687ebe4444.png)

I've tried, different formatting options, using spaces or separators, but it just won't do anything

**Comment by danielnaber** [comment]
Thanks for the report, this should be fixed with the next update.
