### ISSUE TITLE
[en] "dare" is tagged as "MD"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4465]
Is "dare" really a modal verb, or should we remove the tagging?

**Comment by MikeUnwalla** [comment]
It's a modal according to these dictionaries:
https://www.ldoceonline.com/dictionary/dare
https://www.lexico.com/definition/dare

Webster says it's an auxiliary: https://www.merriam-webster.com/dictionary/dare

**Comment by udomai** [comment]
Grammatically speaking, it can be used as a normal verb and as a quasi-modal.

Normal verb: "He dares me to jump head-on."
Quasi-modal: "He dare not speak while she is working."

I think the quasi-modal usage is limited to "dare not". In that case, the VBZ doesn't have the -s and the infinitive afterwards is "bare" (no "to").

**Comment by udomai** [comment]
Update: [it looks like](
https://english.stackexchange.com/questions/43315/dare-with-and-without-to) "Dare you to jump into the water?" is just as okay as "Dare you jump into the water?".

The modal verb construction is the one language purists prefer.

**Comment by marshinkar** [comment]
Discussion outdated. I am closing the ticket.
