### ISSUE TITLE
[ru] Rule "cо и во"

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#447]
There is a rule:

Розенталь: о пишется после предлогов в и с, если с этих же согласных начинается последующее стечение согласных, например: во власти, во внушении, со слезами, со словами, со страху;

Any other connection is an error.

**Comment by yakovru** [comment]
LT already have rules for prepositions "в", "во", "c", "со". But current LT rules are incomlete. I'll try fix it.

**Comment by yakovru** [comment]
I activated an existing rule for "СО", but it gives a lot of false positives.

**Comment by danielnaber** [comment]
@kostyfisik automatically generated reports for Russian for the changes from yesterday can be found at https://languagetool.org/regression-tests/20160804/result_ru_20160804.html

**Comment by kostyfisik** [comment]
@yakovru @danielnaber  There is an obvious exception - this rule doesn`t apply for acronyms. So if there are two or more capital letters in the next word than it is an exception. All captial letters do not cover all possible acronyms, e.g. "в ВКП(б)" and " коалицию с СвДП" There are two special single letter acronyms - "В" and "C", e.g. "в В направлении" и "с С азимута". For only fist captical letter the rule does apply, e.g. "со Станкивичем" It looks like this should cover all valid examples in regression file.

@@ -11127,6 +11398,11 @@
 Suggestion: новорождённый
 «единоутробный», и дельфин — «новорожденный младенец», «утробный» (возможно из-за внешнего сх...
                               ^^^^^^^^^^^^^
+Line 1, column 101, Rule ID: S_SO[1]
+Message: Неправильная форма предлога. Исправление: 'со младенцем'.

This and several others like "с многими" "с шляпой"  are some other rule false positive, as soon as "младенец" does not start from "с"

@@ -5039,6 +5130,13 @@
                                                      ^^

 Title: Столыпинская аграрная реформа
+Line 1, column 6, Rule ID: S_SO[1]
+Message: Неправильная форма предлога. Исправление: 'со слишком'.
+Suggestion: со слишком
+Но я с слишком большим уважением отношусь к народному разуму, чт...
+     ^^^^^^^^^                                                  
+
+Title: Столыпинская аграрная реформа

@@ -5347,6 +5478,13 @@
 ^^^^^

 Title: Союз Советских Социалистических Республик
+Line 1, column 9, Rule ID: S_SO[1]
+Message: Неправильная форма предлога. Исправление: 'со сравнительно'.
+Suggestion: со сравнительно
+В связи с сравнительно большими потерями и неподготовленностью Красной А...
+        ^^^^^^^^^^^^^^                                                  
+
+Title: Союз Советских Социалистических Республик

@@ -6784,6 +6964,13 @@
 ...рят, что сначала нужно исправить общество, но это всё равно, что ставить телегу впереди лошади.
                                                      ^^^^^^^^^^^^^^

+Title: Вторая мировая война
+Line 1, column 153, Rule ID: V_K_S[3]
+Message: Неправильная форма предлога: 'во Вторую'.
+Suggestion: во Вторую
+...ич А. М.) считают этот день датой вступления СССР в Вторую мировую войну.
+                                                     ^^^^^^^^               
+

There are  errors in the text. The LT corrections are valid.

**Comment by kostyfisik** [comment]
@danielnaber does test results on larger corpus are available online (like in the regression test, however, all current issues with LT?)

**Comment by yakovru** [comment]
Online tests are running every day at 22:00 MSK. https://www.languagetool.org/regression-tests/?C=M%3bO=D

**Comment by danielnaber** [comment]
@kostyfisik No, you'd need to check that yourself, e.g. with `	LanguageTool-wikipedia-...-snapshot.zip` available from https://languagetool.org/download/snapshots/?C=M;O=D. It can run on Wikipedia XML dumps. This is actually what the regression test does, but the regression test is limited to a few thousand articles because of limited computer power.

**Comment by yakovru** [comment]
I fixed false positives for acronyms now:
https://www.languagetool.org/regression-tests/20160807/result_ru_20160807.html

**Comment by kostyfisik** [comment]
@yakovru Please, review my PR #461  which cover "cо и во" with pronouns (it was missed in the current rule set).

**Comment by kostyfisik** [comment]
Same group rule exception "На ИЗО одному мальчику не хватило красок"

'''xml
  <rule>
                <pattern>
                    <token>изо</token>
                    <token regexp="yes">[аеёиоуыэюяьън].*</token>
                </pattern>
                <message>Неправильная форма предлога. Буква &quot;о&quot; не нужна: <suggestion>из \2</suggestion>.</message>
                <short>Буква &quot;о&quot; не нужна.</short>
                <example>Из окна выпал пакет.</example>
                <example correction="Из окна"><marker>Изо окна</marker> выпал пакет.</example>
            </rule>
'''

**Comment by yakovru** [comment]
Fixed.
