### ISSUE TITLE
[ru] repeated words

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#448]
Some words are valid to be repeated several times in the same sentence. At the moment (LT 3.4) this gives a false positive.

и... и... и, да.. да... да, ни... ни... ни, или... или... или, ли... ли... ли, ли... или... или, либо... либо... либо, то... то... то, не то... не то... не то, то ли... то ли... то ли

CORRECT  Было грустно и в весеннем воздухе, и на темневшем небе, и в вагоне (Ч.); 
CORRECT Не было ни бурных слов, ни пылких признаний, ни клятв (Пауст.); 
CORRECT После разлуки с Лермонтовым она [Щербатова] не могла смотреть ни на степь, ни на людей, ни на попутные села и города (Пауст.); 
CORRECT  Видеть ее можно было ежедневно то с бидоном, то с сумкой, а то и с сумкой и бидоном вместе — или в нефтелавке, или на рынке, или перед воротами дома, или на лестнице (Булг.).

**Comment by kostyfisik** [comment]
False positives in master (3.5 snapshot):

Время работы выросло с 56 минут до 2 часов 32 минут.
Они любили друг друга.

**Comment by yakovru** [comment]
Fixed.
