### ISSUE TITLE
[en] many sentences not found anymore by COMMA_COMPOUND_SENTENCE

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4484]
https://internal1.languagetool.org/regression-tests/via-http/2021-03-02/en-US/result_grammar_COMMA_COMPOUND_SENTENCE[1].html

**Comment by udomai** [comment]
This is due to the fact that the rule is not meant to trigger for sentences below 10 tokens (see AP line 72913). The tokenizer changes affect the token count (don't = 2 tokens now instead of 3).

**Comment by tiff** [comment]
@udomai there are many sentences that have more than 10 tokens

**Comment by jaumeortola** [comment]
There are several antipatterns for sentences like `XXXX and I'll` or `XXXX and you'd`. There is no easy fix, I'm afraid. Some are not properly written for the new tokenizer. So, we can expect even more false negatives like these.

**Comment by tiff** [comment]
I'll have a look myself. Thanks
