### ISSUE TITLE
[en] AGREEMENT_SENT_START_2: FP + message

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#4488]
[AGREEMENT_SENT_START_2[2]](https://internal1.languagetool.org/regression-tests/via-http/2021-03-02/en-US/result_grammar_AGREEMENT_SENT_START_2[2].html) gives a FP for "bell hooks" (proper name never to be capitalized).

The message should include the negation: It seems that the correct verb form here is “do”. → It seems that the correct verb form here is “don't”.

**Comment by MikeUnwalla** [comment]
To prevent incorrect suggestions, a separate rule is necessary for doesn't/don't. Refer to #4787.
