### ISSUE TITLE
[en] ALL_MOST_SOME_OF_NOUN: FP for plural POS -s'

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#4489]
[ALL_MOST_SOME_OF_NOUN[1]](https://internal1.languagetool.org/regression-tests/via-http/2021-03-02/en-US/result_grammar_ALL_MOST_SOME_OF_NOUN[1].html)

"All of analysts' doubts"

**Comment by MikeUnwalla** [comment]
> "All of analysts' doubts"

This text is not correct. 

The only FP is the first sentence, probably because of the unknown proper noun _Fortis_.
