### ISSUE TITLE
[ru] Comma for repeated linking words

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#449]
3 or more repetitons always use commas in between
2 repetitons always use commas in between for all, excpet "и" and "ни"

и... и... и, да.. да... да, ни... ни... ни, или... или... или, ли... ли... ли, ли... или... или, либо... либо... либо, то... то... то, не то... не то... не то, то ли... то ли... то ли

CORRECT Было грустно и в весеннем воздухе, и на темневшем небе, и в вагоне (Ч.); 
CORRECT Не было ни бурных слов, ни пылких признаний, ни клятв (Пауст.); 
CORRECT После разлуки с Лермонтовым она [Щербатова] не могла смотреть ни на степь, ни на людей, ни на попутные села и города (Пауст.); 
CORRECT Видеть ее можно было ежедневно то с бидоном, то с сумкой, а то и с сумкой и бидоном вместе — или в нефтелавке, или на рынке, или перед воротами дома, или на лестнице (Булг.).

CORRECT Колоть беспрестанно мне глаза цыганской жизнью или глупо, или безжалостно (А. Остр.); 
CORRECT Он готов был поверить, что приехал сюда не вовремя — или слишком поздно, или рано (Расп.);
CORRECT  Дамочка не то босая, не то в каких-то прозрачных... туфлях (Булг.); 
CORRECT Весь день идет либо снег, либо дождь со снегом. Они [лампы] лишь подсвечивали то стены пещерного зала, то наиболее красивый сталагмит (Сол.); 
CORRECT Рано ли, поздно ли, но приду.

**Comment by yakovru** [comment]
Try fix some example: https://github.com/languagetool-org/languagetool/commit/f15e84be89b6ed6e1c9b0a8e131925d5f0114cf3

**Comment by yakovru** [comment]
Mostly fixed, but need special exception for  и... и... и, или... или... или now.

**Comment by kostyfisik** [comment]
@yakovru Sorry, I am quite overloaded these days. I hope I will be able to join development in the winter.

**Comment by yakovru** [comment]
Fixed.
