### ISSUE TITLE
[ru] Preposition sequence rule

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#450]
Usually, preposition sequence is an error (not sure for exceptions)
(Can be found in freshly written texts  with many internal rewriting before proof-reading)

ERROR для к слову
ERROR от на заборе

**Comment by yakovru** [comment]
Fixed.

**Comment by kostyfisik** [comment]
The exception: if the one of the word starts with a capital letter and is not in the beginning of the sentence than it is probably not an preposition "в В направлении" "по С азимуту" "ИЗО в школе"

The exception: cases "изо"+preposition and preposition+"изо"  should propose to write ИЗО  in all capitals if it is a school class name.

**Comment by kostyfisik** [comment]
@yakovru  BTW, the example correction is wrong at line https://github.com/languagetool-org/languagetool/blob/5e65655ed49a88ff8558cd534499dc71fe20546d/languagetool-language-modules/ru/src/main/resources/org/languagetool/rules/ru/grammar.xml#L5217 
The only valid case is "Koшка выпрыгнула в окно", case "на окно" sounds rather strange.
Probably "Кошка прыгнула на|в окно" can be a good correction.

**Comment by yakovru** [comment]
Yes. Your example sounds better.
