### ISSUE TITLE
[en] DOES_XX_CAN: wrong usage of "dare" no longer found

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#4505]
[DOES_XX_CAN[1]](https://internal1.languagetool.org/regression-tests/via-http/2021-03-02/en-US/result_grammar_DOES_XX_CAN[1].html):

> **Do I dare** disturb the universe? → Dare I

**Comment by tiff** [comment]
This is unrelated to the tokenizer change. I added an antipattern that was a bit too aggressive.

**Comment by hftf** [comment]
> [DOES_XX_CAN[1]](https://internal1.languagetool.org/regression-tests/via-http/2021-03-02/en-US/result_grammar_DOES_XX_CAN%5B1%5D.html)

I judge all 5 of these sentences acceptable, although I judge "dare" slightly more acceptable than "dare to". "Dare you" sounds archaic.
