### ISSUE TITLE
[ru] incomplete check of adj and noun form

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#451]
The plural or single form is treated only in half of cases, the word case is never treated.

приблизительное решениям - the error is mark
Приблизительное решения - the error was missed with LT
Приблизительные решение - the error was missed with LT

ALL examples are WRONG

**Comment by yakovru** [comment]
Current algorithm can not resolve the ambiguity in determining the grammatical form: Приблизительное[приблизительный/ADJ:Neut:Nom,приблизительный/ADJ:Neut:V] решения[решение/NN:Neut:PL:Nom,решение/NN:Neut:PL:V,решение/NN:Neut:Sin:R] .

Приблизительные[приблизительный/ADJ:PL:Nom,приблизительный/ADJ:PL:V] решение[решение/NN:Neut:Sin:Nom,решение/NN:Neut:Sin:V]

**Comment by kostyfisik** [comment]
For sure it can!
 ADJ:Neut:V agrees with NN:Neut:Sin:V (same for any other case or gender)
 ADJ:PL:V agrees with any gender NN:.*:PL:V (same for other case).

The major fix to Russian grammar.xml before this one  should be introducing unification http://wiki.languagetool.org/using-unification like in Polish grammar set.  With unification agreement of all cases for prep and adj looks like (example from Polish grammar):
```xml
<unify>
    <feature id="case"/>
        <token postag="prep.*" postag_regexp="yes"/>
        <marker>
            <token postag="adj.*" postag_regexp="yes" inflected="yes" regexp="yes">jaki|który</token>
        </marker>
</unify>
```

**Comment by kostyfisik** [comment]
The case unification should also be checked
WRONG Был выбран этот алгоритм, как обладающий наибольшей производительность.

**Comment by kostyfisik** [comment]
All examples in the issue are now detected with LT.

**Comment by kostyfisik** [comment]
A number of cases that also should be treated:

Я терпеть не могу эту глупою женщину


При императрице Екатерине Великой Россия успешно воевала с Турцией за выход к Чёрному морю...
а при Ярославе Мудром митрополит впервые 
но
а в Балтийское моря поступают с глубинным течением

Централизация государственной власти свойственная России вела к унификации архитектурного стиля,

в бассейне Нижней Таймыры есть такие объекты 

 победа над французскими агрессорами, сделавшая возможной крах могущественной империи Наполеона в Европе

в состав Российской империи также вошло вассальное Речи Посполитой герцогство Курляндия и

 1 пуд крупы и т. д. — аналогичные нормам введенным Временным правительством 

Он посмотрел на ночной небо.

делала политически невозможной отмену единожды данных им законом прав

запущена первая промышленная АЭС в мире
плотина Саратовской ГЭС.

Среди них наибольшей известностью пользовались

и оттого враждебного чувствам и счастью

в которой находился портрет неизвестного работы Жана Фуке.

её сторонники считали необходимым объединение всех польских земель

вычислительный центр Афинской политехники в Зографу

и менее известные Крис Сфирис 

стоящее между оливковой ветвью слева и дубовой справа

В грузообороте портов преобладает нефть и другое минеральное сырье.

обеспечивающих необходимую городу информационную, административную и визовую подде

Ставшие хрестоматийными слова «Природой здесь

Официальный сайт Кировской городской думы

место пребывания короля, а позднее парламента.

Ранее здесь располагался англиканский приходской храм всех святых.

**Comment by kostyfisik** [comment]
https://languagetool.org/regression-tests/20160817/result_ru_20160817.html

**Comment by kostyfisik** [comment]
Mostly fixed. Addititonal cases 
добрых полчаса – добрые полчаса  (В сочетаниях с пол- и полтора (полторы) возможны обе формы согласования: добрых полчаса – добрые полчаса (см. также §168, п. 2))

I have checked against examples at http://www.evartist.narod.ru/text1/65.htm#з_03  - no more false positives.  Probably there can be more dual,  and cases like два дружного брата are not marked. This needs additional rules....

@yakovru  Could you review all the new rules with unification? I believe I will not edit them next few days.

**Comment by yakovru** [comment]
Fixed.
