### ISSUE TITLE
[en] NNS_IN_NNP_VBZ[1]: FP for acronym

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#4518]
[NNS_IN_NNP_VBZ[1]](https://internal1.languagetool.org/regression-tests/via-http/2021-03-02/en-US/result_grammar_NNS_IN_NNP_VBZ[1].html):

> they are responsible for making the payments on these contracts since ENA **has** defaulted. → have, had

Exclude all-caps acronyms

**Comment by MikeUnwalla** [comment]
Excluding acronyms doesn't help; refer to the counter-example.
I used a different solution.
