### ISSUE TITLE
[ru] False positive "Как правило"

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#452]
"Как парвило" is not always combined with commas. 

CORRECT Этот метод в литературе известен как правило буравчика.
False positive: 
![screenshot from 2016-08-03 15-53-01](https://cloud.githubusercontent.com/assets/5239997/17366156/6cdcac7c-5992-11e6-8290-ac624d871d71.png)

**Comment by yakovru** [comment]
Fixed.

**Comment by kostyfisik** [comment]
Rule still has a false positive 
<example>Рекомендация количества строк при реализации функции или цикла в программировании известно как правило одного экрана.</example>
