### ISSUE TITLE
[en]POSSESSIVE_APOSTROPHE[2]: FP for services provider

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#4525]
[POSSESSIVE_APOSTROPHE[2]](https://internal1.languagetool.org/regression-tests/via-http/2021-03-02/en-US/result_grammar_POSSESSIVE_APOSTROPHE[2].html)

**Comment by Tex2002ans** [comment]
@MikeUnwalla

Might work better with an optional 's' in the antipattern token:

`<token>services?</token>`

- - -

Doing a search in Google, I see:

- 840,000 "wireless service provider"
- 173,000 "wireless services provider"

I see some legitimate news sources + laws using the 's':

https://www.cnbc.com/2020/09/14/verizon-to-buy-wireless-services-provider-tracfone-in-6point25-billion-deal.html
https://law.lis.virginia.gov/vacode/56-484.26/

but can't say I've ever seen it with the 's' before... and I read A LOT of tech news...

The no 's' version also sounds so much more natural to my ear:

services->service
> DoCoMo is the world's leading wireless **services** provider.

**Comment by MikeUnwalla** [comment]
@Tex2002ans , there is no false warning with "wireless service provider". Thus, an optional s in the antipattern is not necessary.

The function of the rule is to find missing possessive apostrophes. The suggestion "wireless service's provider" is not correct in the context of the example sentence.

But, here is a sentence in which "wireless services's provider" is correct:
_The wireless service's provider of news was found to be unreliable._
(= The provider of news to the wireless service was found to be unreliable.) @udomai , the rule does not find "wireless services provider" in this context. Should I revert the change? Try to make the antipattern more specific? Forget it?

If we want to find "wireless services provider" and suggest "wireless service provider", then we must make a separate style rule to say "'wireless service provider' is the usual term."

**Comment by Tex2002ans** [comment]
Correct. I believe your fix is perfectly fine.

My mistake.

1. I wasn't looking at the broader rule (detecting apostrophe s).

2. I also was personally thrown off by the example sentence's "services". But from the Google search, it looks like that's valid too.
