### ISSUE TITLE
[en] PRP_COMMA[1]: lost matches "it seems to me"

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#4526]
[PRP_COMMA[1]](https://internal1.languagetool.org/regression-tests/via-http/2021-03-02/en-US/result_grammar_PRP_COMMA[1].html)

Why are those matches gone?

**Comment by jaumeortola** [comment]
There is an AP and this example: 
> <example>It seems to me we're making a lot of assumptions here.</example>

Probably introduced by me. Is the comma right in these sentences?

**Comment by udomai** [comment]
Come to think about it, "it seems to me" doesn't need a comma. But the sentences with "to me" (after SENT_START or "and") do need one.
