### ISSUE TITLE
[ru] Rule "при" and several nouns

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#453]
The correct case of the noun after "при" is checked only for the nearest one. However, if there is several coma or "и" separated nouns (probably with adjective) they also should be checked.

WRONG Часть которых удалось исправить при отладке, запуска и тщательное тестирования.
CORRECT Часть которых удалось исправить при отладке, запуске и тщательном тестировании.

**Comment by kostyfisik** [comment]
Still detects only first part of the example.

**Comment by yakovru** [comment]
Fixed.
