### ISSUE TITLE
[en] THANKS_SENT_END_COMMA[1]: old match was better

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#4533]
[THANKS_SENT_END_COMMA[1]](https://internal1.languagetool.org/regression-tests/via-http/2021-03-02/en-US/result_grammar_THANKS_SENT_END_COMMA[1].html):

> (in Carol's Thank you.

→ suggestion now: `, Thank`

Before, A_THANK_YOU[1] suggested `Thank-you, “Thank You”`. → prio up?

**Comment by tiff** [comment]
@udomai I already fixed it. You basically re-created an issue for it :)

**Comment by udomai** [comment]
Oops, my bad :)
