### ISSUE TITLE
[en] False warning: ain't

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#4537]
> This **ai**n't a spelling error.

![image](https://user-images.githubusercontent.com/5816160/109807975-7ba1da80-7c1e-11eb-84dd-87826ed97c4d.png)

The noun 'ai' and plural 'ais' have postags, but they cause spelling warnings.
https://www.lexico.com/definition/ai
https://www.merriam-webster.com/dictionary/ai

The quick win (and my preferred option) is to add 'ai' and 'ais' to spelling.txt. But, that could cause some typographic errors not to be found. (Hobby horse again: we should have rules that find errors, not rules that complain about correct text.)

@udomai , what do you think is the best option?

**Comment by Tex2002ans** [comment]
@MikeUnwalla 

> The quick win (and my preferred option) is to add 'ai' and 'ais' to spelling.txt.

Ehhhh... I don't think the lowercase word "ai" or "ais" (a three-toed sloth!) is actually used often (ever?).

Infinitely more likely (especially modern times) is "Artificial Intelligence":

- AI
- AI's
- AIs

or as an acronym:

- AIS
  - https://en.wikipedia.org/wiki/AIS

> But, that could cause some typographic errors not to be found. (Hobby horse again: we should have rules that find errors, not rules that complain about correct text.)

Would any modern human be talking about the sloths or their noises? lol. :D

If anything, I think 99.9% of the "ai" or "ais" would need to be capitalized to AI + AIs + AIS!

It looks like LT already does an *okay* job at that:

> The three-toed sloth is called an **ai**, and multiple are called **ais**.

Clicking on "ai" recommends:

- AI
- an
- a
- am
- I

Clicking on "ais" recommends:

- AIs
- AIS
- is
- as
- aid

**Note:** [SCOWL](http://wordlist.aspell.net/12dicts-readme/) lists these 2:

- AI
- AI's

starting at "size 50", which means very very common.

"size 60" = their default/recommended dictionaries.

Beginning in the "size 70" dictionary, these 3 appear:

- ai
- ai's
- ais

But even that has me scratching my head...

**Comment by jaumeortola** [comment]
This rule was missing in disambiguation.xml: https://github.com/languagetool-org/languagetool/commit/7895ee96ca0ccaccd3f46e39afeeda53f19cdf03
It is similar to other contractions: won't, can't, shan't. 

Now, you can remove "ai" from spelling.txt if you want. @MikeUnwalla

**Comment by MikeUnwalla** [comment]
@jaumeortola, @Tex2002ans , my preference is to keep the spellings. The words are valid English words and they have postags in LT. That a word is rare is not a good reason to say that it is a spelling error. The function of a spelling checker is to find spelling errors. The nouns 'ai' and 'ais' are not spelling errors.  As I have said to @udomai before, we need 'intelligence' and context-sensitive spelling rules.

@udomai , your call. Do you want me to revert my change for spelling?

**Comment by udomai** [comment]
@MikeUnwalla, I'd say we can leave it in the dictionary under one condition: We need a really simple rule that spots any lower-case occurrence of "ai" (except in ain't) and says something like "If you're referring to artificial intelligence, this acronym has to be capitalized. The lower-case spelling is okay if you're referring to a Brazilian three-toed sloth."

**Comment by MikeUnwalla** [comment]
@udomai , OK, will do.

**Comment by MikeUnwalla** [comment]
I added a basic rule (https://github.com/languagetool-org/languagetool/commit/bdc8f1c2f1cbdc78473cc68fbf7858f6b0c12ff8).

@udomai, I tried to make a rule to find 'ais', but I could not do it. I looked at https://dev.languagetool.org/tips-and-tricks#changing-the-case-of-matched-word, but I could not figure out how to make the suggestion give the correct capitalization.

**Comment by udomai** [comment]
Thank you, @MikeUnwalla! I've written a regex workaround. I also set it to temp_off so we can check the diff.

**Comment by MikeUnwalla** [comment]
@udomai , thanks.

**Comment by MikeUnwalla** [comment]
I improved the rule (https://github.com/languagetool-org/languagetool/commit/7778baa30c56c33892fbd6ee22e55860f91b27b7). It's not perfect, but it's much less bad than getting FN for each instance of the term.

Will wait until after tomorrow's diff for a final check before activating.

**Comment by Tex2002ans** [comment]
@MikeUnwalla 

I also ran across this Wikipedia page:

https://en.wikipedia.org/wiki/Ai

These 2 stood out:

- King Ai
- Emperor Ai

101,000 hits + 434,000 hits on Google.

> **King Ai** of Zhou was the twenty-ninth king of the Chinese Zhou Dynasty and the seventeenth of Eastern Zhou.
> **Emperor Ai** of Tang was the last emperor of the Tang dynasty of China.

**Comment by MikeUnwalla** [comment]
@Tex2002ans , thanks.

@udomai fixed the rule, so the examples you give do not cause false warnings now. The rule finds only all lowercase text.
