### ISSUE TITLE
[ru] Complex conjunction "так же как" and similar

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#455]
It looks like complex conjunctions are not treated with LT 3.4

WRONG Людей таких, как он ещё поискать

Есть составные союзы ТАК ЖЕ КАК, ТАК ЖЕ КАК И, а также союзные выражения ТАКОЙ ЖЕ КАК, ТАКОЙ КАК, ТАКОЙ ЖЕ КАК И

http://new.gramota.ru/spravka/punctum?layout=item&id=58_710

ТАК ЖЕ(,) КАК (И), союз; наречие + частица + союз

1. Союз. То же, что «равно как (и)». Синтаксические конструкции с союзом «так же как (и)» выделяются знаками препинания (запятыми). Между частями союза знаки препинания не требуются.

Так же как в средневековой харчевне, нас встречали дома бревенчатые темные стены, законопаченные желтым мхом, пылающие поленья в печке и запах тмина. К. Паустовский, Бакенщик. Я знала, так же как и она, что рано или поздно наступит день, когда мы поневоле заговорим и простим друг другу долгое молчание. Ч. Айтматов, Материнское поле.

2. Наречие + частица + союз. Запятая ставится перед словом «как».

От тяжелой росистой травы кругом и от цветов, ночных цветов, только теперь раскрывших свои головки, пахло так же, как от волос Анны. С. Сергеев-Ценский, Печаль полей. Совершенно так же, как в жмурках, бывало мы, ребята, шли с завязанными глазами, так и она переступала с лапки на лапку в направлении леса. М. Пришвин, Охотничьи собаки.

**Comment by yakovru** [comment]
part1
https://github.com/languagetool-org/languagetool/commit/e59ebdac24779a3a278eb565daf09263c05d70b9

**Comment by yakovru** [comment]
http://new.gramota.ru/spravka/punctum?layout=item&id=58_722

**Comment by yakovru** [comment]
URL http://new.gramota.ru/spravka/punctum?layout=item&id=58_710  is not found...
but URL  http://new.gramota.ru/spravka/punctum?layout=item&id=58_738 is exist
 (ТОЧНО) ТАК ЖЕ КАК (И), союз

**Comment by yakovru** [comment]
Fixed.

**Comment by kostyfisik** [comment]
Nice! Thank you!
