### ISSUE TITLE
[DE] Tippfehler wird nicht erkannt.

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#4555]
Moin liebes LanguageTool-Team

Er fragte: „Was **machen wird** jetzt?“
Das LanguageTool erkannt leider diesen Fehler nicht.

Bitte beheben.

Grüße Dallun511

**Comment by f-knorr** [comment]
now found:
„wird“ nicht wahrscheinlich
„wird“ erscheint hier weniger wahrscheinlich als „wir“.
wir
