### ISSUE TITLE
[DE] Fehlalarm -chen Endung

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#4557]
Moin liebes LanguageTool-Team

Die Gefängniswärterin fand ein kleines **Tütchen** in ihrer Hosentasche.
![grafik](https://user-images.githubusercontent.com/78316155/110254802-fd806380-7f90-11eb-830c-6a4652399fef.png)
Der Vorschlag ergibt kein Sinn. Bitte schnell fixen.

Grüße Dallun511

**Comment by danielnaber** [comment]
"Tütchen" = "kleine Tüte". Der Vorschlag ist schon richtig.
