### ISSUE TITLE
[nl] user feedback "ir"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4559]
> De titel ir (voor ingenieur) is geen afkorting maar een inkorting en moet zonder (afkortings)punt geschreven worden.

**Comment by tiff** [comment]
More from the same user:
> Dit geldt o.a. ook voor dr (dokter,Doctor) en drs (doctorandus)

**Comment by baarsrj** [comment]
No, it does not. Officially, the . is required.
https://woordenlijst.org/#/?q=ir
https://woordenlijst.org/#/?q=dr
