### ISSUE TITLE
[all][ru] some words in the dictionary miss of the part-of-speech tag

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#456]
There is a word "исследовались" in Russian dictionary (so it is not marked as misspelled and it is actually correct), however, it has no part-of-speech tag. I would expect many other missing too, probably not only in Russian dictionary but in other languages too. This is critical, as soon POS based rules do not trigger in this case.

Is it possible to add some self-integrity check, so in Russian (and probably any language with part-of-speech feature) all words in the dictionary should have at least one part-of-speech? It can be useful to run this check periodically, e.g. before every new release of LT.

исследовались  - - 
знакомились  знакомиться VB:Past:PL

**Comment by danielnaber** [comment]
`исследовались` is in the spelling dictionary, but not in the POS dictionary. These are independent, so there might be many words in the spell dictionary that have no POS tag. If something is in the POS dictionary, we already test that the tag list for that word isn't empty (`TestTools.testDictionary`).

**Comment by kostyfisik** [comment]
For Russian language there is a state-of-art POS detector https://tech.yandex.ru/mystem/ It has a rather permissive licence (both for commercial and non-commercial usage). INAL, it looks like in can be used for free to generate POS dictionary in any project (at least until Yandex will provide a grammar checker as service).

Moreover, mystem is capable of context dependent POS tagging, which looks to be very good even with synthetic Russian-like texts with non-existing words (with a valid morphological structure) . I believe that such kind of technic will dramatically increase the accuracy of any grammar and style checker.  I hope that some day they will open the code unser LGPL compatible licence and it will be possible to use it with LT directly.

**Comment by kostyfisik** [comment]
BTW, there is a java wrapper for mystem https://github.com/evg299/MystemWrapper

**Comment by yakovru** [comment]
The existing Russian dictionary (included in LT) is the most optimal.
This dictionary based on dictionary from www.aot.ru.

**Comment by kostyfisik** [comment]
AOT looks to be stagnating, news feed has only two entries for last five years.  Mystem provides facilities for tagging of non-dictionary words with the accuracy of more than 95%. For case of valid context available the non-dictionary word accuracy grows up to 98%.  The dictionary part of  Mystem I believe is more modern and more complete too.

**Comment by yakovru** [comment]
I can commit to AOT repositary,  but there are some difficulties with the preparation of a massive update of the dictionary.

**Comment by kostyfisik** [comment]
I hope that closer to NY I will have enough time to integrate mystem with LT tag notation and dictionary format to autotag missing words. Or, probably, someone else can introduce auto tagging system for Russian part of LT.

@danielnaber Does LT license allow to include proprietary binaries , e.g. to provide POS tagging? Yandex license allow free use for non-related to web search cases. If I will try to provide a wrapper around this binary to use with LT it will be GPL, however, without exact version of the binary it can be useless...

**Comment by danielnaber** [comment]
@kostyfisik For research and testing you can of course integrate whatever you like. But for the official version of LT that gets distributed, I suggest we stick to the well-known licenses (MIT, GPL, LGPL, Apache etc) that don't come with any restriction. We cannot use proprietary binaries in LT.

**Comment by kostyfisik** [comment]
Ok, probably this can be a satellite GitHub project.

**Comment by yakovru** [comment]
Autotag missing words on runtime is bad idea. It is very slowly. And it may be wrong.
AOT C++ binary can autotag unknown words, and after manual checking we can commit this words to dictionary.

**Comment by kostyfisik** [comment]
As far as I understand Yandex uses mystem for their search engine. It rather precise and very fast - it is capable of parsing a huge amount of news feeds in real-time. 

Anyway, with two independent auto-taggers it is a good idea to do cross-correlation. If there is only one you can just blindly trust it (it is impossible for a human or a small team to check tagging for large dictionary). With two taggers you can just check the difference.

**Comment by kostyfisik** [comment]
@yakovru  I have just created the scipt that generates tags using Yandex Mystem program. The script is in python and  assumes to have mystem and LT standalone to be located at certain paths... 
The script generates a list of unique words from the input file, check which of them are not tagged with LT and and outputs two files: a word list and the same list with tags. See the example attached with 3700+ new words (most of them has .
[final-tags.txt](https://github.com/languagetool-org/languagetool/files/453335/final-tags.txt)
[final.txt](https://github.com/languagetool-org/languagetool/files/453336/final.txt)

However,  mystem tagging system is quite different and is not compatible with LT. Could you please add missing tags to LT and provide a compatibility table? I will develop the script, so that it should provide tag output in ready to use format for LT.

**Comment by kostyfisik** [comment]
@yakovru  I have connected some tags I was able to recognize. The final script is in the repo. The possible output file with 8k+ new tags...
[final-tags.txt](https://github.com/languagetool-org/languagetool/files/453599/final-tags.txt)

many more words recieved tags not found in tags_russian.txt 
e.g.
горбачёв	горбачев	NNF:Masc:Sin:Nom <== S,famn,m,anim=nom,sg
горбачёва	горбачев	NNF:Masc:Sin:V <== S,famn,m,anim=acc,sg
горбачёва	горбачев	NNF:Masc:Sin:R <== S,famn,m,anim=gen,sg
горбачёва	горбачева	NNF:Fem:Sin:Nom <== S,famn,f,anim=nom,sg

I believe we should get the best from mystem grammar tagging system...

**Comment by yakovru** [comment]
I think we can not use result this script in release of LT!

**Comment by yakovru** [comment]
But we can  use it from other license-compatible systems...

**Comment by yakovru** [comment]
But it is cool script. I'll try find other licence-compatible systems for use with it.

**Comment by kostyfisik** [comment]
I wrote a letter to Yandex with hope to get a permission. According to https://yandex.ru/legal/mystem/  licence terms it is legal to use MyStem this way (without a distribution) as soon as LT is not inteded to send spam e-mails, do the internet serch and does not copy any service of Yandex (the closest is Yandex speller which does not provide any grammar or style check).

**Comment by yakovru** [comment]
But the license conditions may be modified at any time by Yandex. Or Yandex can release some functionaly of LT.  And in this case immediately the license is violated . It's bad.

**Comment by danielnaber** [comment]
> as soon as LT is not inteded to send spam e-mails, do the internet serch and does not copy any service of Yandex

While this may sound harmless at first, it's a restriction of freedom and we cannot accept any license that has restrictions that go beyond our main license (LGPL). Basically, we can only use software and data under a well-known Open Source license.

**Comment by kostyfisik** [comment]
Let`s wait for the answer from Yandex first :)  Anyway, if someone writes code in Windows using Visual Studio it does not put any additional restrictions to this code. When I do development in Linux with Emacs it does not give any additional freedom for my code.  The same way if we use MyStem to generate tag in full accordance with the existing license - it should be not a problem to license a result (a text file with token-lemma-gramma sequence) under any convenient license and it will not depend on any future changes in MyStem licensing.

**Comment by kostyfisik** [comment]
@danielnaber  @yakovru Yandex provided a draft for their official letter to allow the distribution of MyStem (in a binary form) along with LT under MyStem license as of 27.10.2011 . As far as I understand it explicitly grants that  LT will  continue to  be distributed under it own licence, however, the direct usage of  MyStem binary is still limited with it`s own license. 

I need to provide the name of the software (the full name is simply LanguageTool ?), the used license of LT (I believe it is  LGPL 2.1 or later, text is here: https://www.gnu.org/licenses/old-licenses/lgpl-2.1 ) and a LT  copyright holder ( ???) . It is still forbidden to do any reverse-engineering of MyStem binary.

[Письмо (MyStem) 2016-09-15.docx](https://github.com/languagetool-org/languagetool/files/477192/MyStem.2016-09-15.docx)

**Comment by kostyfisik** [comment]
Partly filled draft. I added the paragraph, that the Mystem output can be included into LT under LGPL 2.1 or later. 
[Письмо (MyStem)-revised.docx](https://github.com/languagetool-org/languagetool/files/477284/MyStem.-revised.docx)

**Comment by danielnaber** [comment]
My understanding is that the binary is only for developers and will not be distributed and not be check into git, is that correct?

There's no single copyright holder, contributors have the copyright for the parts they contributed. If you need something, you can say "Daniel Naber and the LanguageTool team".

**Comment by kostyfisik** [comment]
Yes, it is mostly for ru-devs, at least for the initial stage. This binary is capable of generating new POS tags in Russian. I found a huge amount of words that are not listed in the current POS dictionary. Yakov seems to add new tags manually, which is not feasible for first 8k+ tags I already prepared with this binary. It can actually do much more, e.g. to generate POS tags  for non-dictionary words, and, which is more important, it can resolve POS disambiguation for complete sentences. 

I think that the most convenient way for devs is to put this binary into git tree, I will correct paths in my script so that any developer can extend the dictionary.  It looks like that Yandex is ready to provide an explicit right for this without putting any restrictions for LT license. As soon as this is a separate binary which in not going to be linked with LT this should not be an issue for the LGPL license too. 

There is no need to put it into the release, at least while it is not used for resolving POS disambiguation. Howevever, this is not planed into nearest future anyway.

**Comment by kostyfisik** [comment]
BTW, what is the best licence for POS dictionary? LGPL, some flavor of CC BY, or something else?

**Comment by yakovru** [comment]
The best license for Russian POS dictionary in LT is LGPL 2.1 or later.

**Comment by danielnaber** [comment]
If the binary needs to be check in into git, it should be in a separate repo, to keep the Open Source code separated from the non Open Source code.

**Comment by kostyfisik** [comment]
@danielnaber Could you create in github/languagetool-org a  languagetool-non-free or languagetool-3dparty for this purpose?  I believe that we can include Mystem generated tags into a separate file for ease of detection if there is any need for this in future...

**Comment by danielnaber** [comment]
Is the legal situation cleared up already? I mean are we allowed to put it anywhere? If there a need at all, as users (actually developers) can always download the original I guess?

**Comment by kostyfisik** [comment]
No, Yandex only provided a draft of the letter. I would like to put Mystem binary, copy of current Mystem license and a letter from Yandex to the same location, with all additional scripts to generate Russian POS tags. I am not going to put anything from Yandex to LT until I have a signed letter from them. 

At the moment anyone can download the Mystem binary, however (as always with non-free soft) no one can guarantee that this will last forever.

**Comment by danielnaber** [comment]
There's now https://github.com/languagetool-org/languagetool-non-free

**Comment by yakovru** [comment]
I want integrate this script with aot lematizer.dll library. 
And in this case, we do not need to use mystem binary.

**Comment by kostyfisik** [comment]
@yakovru There is no need to lock-in with a single vendor AOT. I believe that at least Stemka (non-free?) and Snowball (BSD) are worth including alongside with MyStem. Other possibilities https://nlpub.ru/%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0_%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%B0#.D0.9C.D0.BE.D1.80.D1.84.D0.BE.D0.BB.D0.BE.D0.B3.D0.B8.D1.87.D0.B5.D1.81.D0.BA.D0.B8.D0.B9_.D0.B0.D0.BD.D0.B0.D0.BB.D0.B8.D0.B7

**Comment by yakovru** [comment]
I think that good alternative is pymorphy2
https://github.com/kmike/pymorphy2

**Comment by kostyfisik** [comment]
Yes, it looks  great!  http://nlp.lsi.upc.edu/freeling/ is another option that looks to be very promising, however,  pymorphy2 is python ready and should be easy to use.

**Comment by kostyfisik** [comment]
I have just comitted pymorph tag generator script
https://github.com/languagetool-org/languagetool/commit/7f0193cc84cc183c0e5f96ecc1dde7773794935b 
the result is attached,  the comparison with MyStem is 
tig@tig-laptop3:~/symlink/LT$ cat final-tags.txt |wc -l
18897
tig@tig-laptop3:~/symlink/LT$ cat final-mystem.txt |wc -l
8797

However, many POS tags from MyStem are absent in pymorth file (in both cases I only output only words, that are marked to be as dictionary). 

[final-tags.txt](https://github.com/languagetool-org/languagetool/files/478700/final-tags.txt)

**Comment by kostyfisik** [comment]
Sorry, pymorph turned to be a bit more complicated , it has separate dictionary for prefixes. So, after removing on dictionary prefixes, the result is 
tig@tig-laptop3:~/symlink/LT$ cat final-tags.txt |wc -l
4402
[final-tags.txt](https://github.com/languagetool-org/languagetool/files/478723/final-tags.txt)

**Comment by kostyfisik** [comment]
A letter from Yandex is attached. @yakovru I believe this solves any legal issues on usage of Mystem generated tags in the LT. Any objections?
[1371-Mystem-for-LT.pdf](https://github.com/languagetool-org/languagetool/files/488058/1371-Mystem-for-LT.pdf)

**Comment by kostyfisik** [comment]
@yakovru Please, review the letter from Yandex and write you opinion. I believe, that it should cover all legal issues needed for use in LT, however, I am not a lawyer, so I would prefer someone else to check it once more.

**Comment by yakovru** [comment]
I checked the script for pymorpy2, and it gave good results!
But I need some time to review the letter from Yandex.
And I want try third way (AOT prediction).

**Comment by kostyfisik** [comment]
I also have an idea to generate all inflected forms with pymorphy for get the best (I believe we should review tagging system in LT first).

It seems to be possible to generate tags simultaneously with Mystem, PyMorph2 and AOT and to provide a trusted list (all three match), and semi-trust (two match) and individual lists (tags from only one of them). This all can be done in an automated way against all dictionary words (with inflection).
