### ISSUE TITLE
[en] false alarm EN_UNPAIRED_BRACKETS

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4565]
> More research and find out if the "60098" error might be indicative of an issue
> And LT is telling me that the first is unpaired, though clearly it is not. Even in this feedback it throws the error.

![Bildschirmfoto 2021-03-09 um 09 45 11](https://user-images.githubusercontent.com/37363/110443558-56004f80-80bc-11eb-809c-f67b303f605e.png)

@danielnaber I think we should check this. I have no idea why it doesn't see the second quote.

**Comment by jaumeortola** [comment]
It is really strange. I can reproduce the issue (in the browser add-on and in the command line) only when there is a line break at the sentence end and some content in the next line.
