### ISSUE TITLE
[ru]new words for the dictionary

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#457]
There is a number of technical words, that are missing in LT 3.4

фотоника
нанофотоника
плазмоника
наноплазмоника
нановихрь
субволновой
суперпоглощение
суперрассеяние
самосогласованность
обезразмеренный
полноволновой
Пойнтинг (вектор Пойнтинга)
высокодобротный
параллелизация
полувысота (в выражении: ширина пика (резонанса, полосы и т.д.) на полувысоте)

**Comment by yakovru** [comment]
Fixed.
