### ISSUE TITLE
[en] Wrong tagging CONTRACTIONS

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#4585]
CONTRACTIONS tags Sha and Ca as NNP:

- [ ] Shan't is almost never used in AmE; rather, it is almost invariably replaced by won't or am/are/is not going to.
- [ ] Can't "ditto" Credit on that one.
- [ ] Can't, I'm going to a recruiting dinner.

**Comment by jaumeortola** [comment]
It is easy to do it with a simple disambiguation rule. I will do it.
