### ISSUE TITLE
[de] "benötig" is tagged

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4586]
Das Wort "benötig" hat `VER:IMP:SIN:SFT`. Denke, das können wir entfernen, um zu verhindern, dass falsche Vorschläge generiert werden, oder?

**Comment by MasterDallun511** [comment]
![grafik](https://user-images.githubusercontent.com/78316155/110696434-619e6400-81eb-11eb-8092-79f79b741e69.png)
https://www.duden.de/rechtschreibung/benoetigen

Das Entfernen könnte Fehlalarme versuchen, da "benötig" eine legtime Form ist.

**Comment by tiff** [comment]
Tatsächlich. Danke
