### ISSUE TITLE
[fr] false alarm ACCORD_GENRE[4]

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4597]
> Introduire le mot de passe chiffré de la réunion suivi de dièse ("PassCode")

![Screenshot_2](https://user-images.githubusercontent.com/37363/110815217-8b5a9800-828a-11eb-99f2-b05c3fcc35b0.png)

**Comment by jaumeortola** [comment]
We plan to create new French agreement rules for adjectives after nouns, to handle sentences like this one. "Suivi" agrees with "le mot de passe...", not with "la réunion".

**Comment by jaumeortola** [comment]
Solved with the new rules.
