### ISSUE TITLE
[es] spelling error not underlined: preveer

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#4605]
> La conclusión que me gustaría que el lector tuviera de la descripción de este sesgo es que las reglas las generamos porque nos ayudan a tomar decisiones, aceptamos que las reglas puedan ser erróneas porque la alternativa es no poder preveer absolutamente nada.

> Aceptamos que las reglas puedan ser erróneas porque la alternativa es no poder preveer absolutamente nada.

"**preveer**" is a spelling error. In the first sentence, it is not underlined (on the web checker, the editor and the browser add-on). But the error is shown by the API and in the command-line.  

Other spelling errors in the same position are not underlined: 
> La conclusión que me gustaría que el lector tuviera de la descripción de este sesgo es que las reglas las generamos porque nos ayudan a tomar decisiones, aceptamos que las reglas puedan ser erróneas porque la alternativa es no poder prebision absolutamente nada.

Changing a bit the sentence makes the error to be underlined: 
> Me gustaría que el lector tuviera de la descripción de este sesgo es que las reglas las generamos porque nos ayudan a tomar decisiones, aceptamos que las reglas puedan ser erróneas porque la alternativa es no poder preveer absolutamente nada.

**Comment by tiff** [comment]
@jaumeortola I know why: The editor and add-on both set picky mode for all requests so that they can calculate a score for the text. The score takes into account of all suggestions that LT makes. With picky mode enabled, `TOO_LONG_SENTENCE` is triggered and highlights exactly the part of "preveer". It seems that the style rule has a higher priority than the spelling rule. This should not be the case. So just decreasing the priority of TOO_LONG_SENTENCE should solve it. We should ensure that this is the case for all languages.

**Comment by tiff** [comment]
cc @danielnaber who build the rule.

**Comment by danielnaber** [comment]
Should be fixed with the next deployment.

**Comment by jaumeortola** [comment]
There are some rules in some languages with priorities lower than -100. Perhaps TOO_LONG_SENTENCE should be even lower (-1000)?
We need some general guidelines for setting priorities for all languages, so that some priorities can be shared without problems.

**Comment by jaumeortola** [comment]
I found more problems like this. We need a definitive solution. 

If picky rules should always have lower priority than regular rules, then let's force it someway. For example, add -10000 automatically to every picky rule priority. It can be added in CleanOverlappingFilter when deciding which matches have to be shown. 

I can implement it, but it has to be tested on the website.
