### ISSUE TITLE
[DE] Kommamangel wird nicht beachet

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#4612]
Moin liebes LanguageTool-Team

Er ging auf sein Zimmer und **sah das** Lucia auf dem Bett von ihm im Schneidersitz **saß**.
LT: "Keine Fehler gefunden."
Hier wird nicht darauf hingwiesen, dass ein Komma fehlt.

Grüße Dallun511

**Comment by NicoWeio** [comment]
Da heben sich wohl zwei Fehler (das/dass und fehlendes Komma) auf. Ich bin mir nicht sicher, ob LT mehrere Fehler gleichzeitig korrigieren kann/sollte.

> Er ging auf sein Zimmer und sah **dass** Lucia auf dem Bett von ihm im Schneidersitz saß.

funktioniert wie erwartet.

**Comment by MasterDallun511** [comment]
Es reicht, wenn das Komma erstmal bemängelt wird, denn hier treffen zwei Vollverben aufeinander. "dass" kann man zuerst ignorieren und wenn das Komma gesetzt ist, kann die nächste Regel anschlagen. Das ist beim LanguageTool keine Seltenheit.

**Comment by MasterDallun511** [comment]
Fehler wird erkannt und damit ist das Problem gelöst. Wurde wohl durch einen Patch beworden, ohne hier vorbeizuschauen.
