### ISSUE TITLE
[en] Wrong tagging: musn't

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#4615]
Snapshot 2021-03-14, Wrong tagging of incorrect word musn't:
![image](https://user-images.githubusercontent.com/5816160/111129892-83427700-856e-11eb-9236-4d63a7323064.png)

The word musn't should not have POS information because it is not an English word.

**Comment by jaumeortola** [comment]
The tag comes from the tagger dictionary: 
```
musn	must	MD
must	must	JJ
must	must	MD
must	must	NN:UN
muster	must	JJR
musts	must	NNS
```
I will add `musn	must	MD` to removed.txt.
