### ISSUE TITLE
[DE] Fehlalarm: "zu sehende"

### ISSUE THREAD

**Issue by NicoWeio** [languagetool-org/languagetool#4618]
> Dazu kam die oben <ins>zu sehende</ins> ausstehende Zahlungsanforderung.

resultiert in dem Hinweis

> Das Partizip scheint hier als Nomen benutzt zu werden und muss, falls es sich nicht auf ein vorheriges/nachstehendes Nomen bezieht, großgeschrieben werden.

**Comment by tiff** [comment]
Den hier hab ich gestern behoben
