### ISSUE TITLE
Support past participle?

### ISSUE THREAD

**Issue by buckle2000** [languagetool-org/languagetool#462]
>Engineers must have *learnt* from this accident
"possible spelling mistake found"

>Engineers must have *learn* from this accident
"use past participle"

**Comment by danielnaber** [comment]
`learnt` is accepted when setting the language to British English and according to https://technosiastic.wordpress.com/2009/11/30/learnt-vs-learned-whats-the-difference/ that's correct.

**Comment by buckle2000** [comment]
I understand.
