### ISSUE TITLE
[en] False warning WHOS 

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#4622]
The one **who's** rich is my friend:

![image](https://user-images.githubusercontent.com/5816160/111280177-6fad1400-8633-11eb-80ad-d23c72d47749.png)

**Comment by tiff** [comment]
Closed via https://github.com/languagetool-org/languagetool/commit/feb2f9cc0aeaed4992f7c4109009a3927edfca01
