### ISSUE TITLE
[es] "solo" vs "sólo"?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4632]
> Se cambia el idioma solo y hay muchas palabras que no reconoce.

Google Translate thinks that it should be "sólo". Do we agree? And if so, can we find this mistake?
![Bildschirmfoto 2021-03-17 um 12 50 28](https://user-images.githubusercontent.com/37363/111463020-69946180-871f-11eb-89f0-f080b88ef40c.png)

**Comment by jaumeortola** [comment]
Already discussed previously (in Slack). With the current RAE rules, only "solo" is correct. But, certainly, there is a lot of resistance to this rule.

**Comment by tiff** [comment]
Ok, I'm closing this then
