### ISSUE TITLE
[pt-pt] Why is "Covid-19" a spelling mistake?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4634]
![Bildschirmfoto 2021-03-17 um 17 43 00](https://user-images.githubusercontent.com/37363/111504803-4af69080-8748-11eb-9fc1-37882594b779.png)

It's in the global spelling but this doesn't seem to be working

**Comment by jaumeortola** [comment]
It is fixed now. A more permanent solution would be to use Morfologik dictionaries.
