### ISSUE TITLE
Libreoffice Addon does not work with remote servers (v. 5.2.3)

### ISSUE THREAD

**Issue by Tobias333** [languagetool-org/languagetool#4636]
In Libreoffice, the addon works fine with the inbuilt resource, but when I attempt to use either the Languagetool server or a self-hosted instance, I get a Java NullPointerException. This is on Fedora 33, LibreOffice 7.0, and I have tried with v. 5.2.3 and the nightly. This is a screenshot of the Java error:

![screenshot](https://user-images.githubusercontent.com/48659123/111517720-a9763b80-8755-11eb-94b3-f9f8841b549d.jpg)

**Comment by Jules-Bertholet** [comment]
I am also getting these errors, same OS, LibreOffice installed via Flatpak, LanguageTool extension 5.3.0. Strangely enough the add-on does work if one clicks through the errors.

**Comment by FredKruse** [comment]
The issue is solved. I close it.
