### ISSUE TITLE
[de][LibreOffice] false positive mit Au und Aufregung

### ISSUE THREAD

**Issue by ChristianPervoelz** [languagetool-org/languagetool#4641]
**Beispielsatz**
Die Au leuchtete im Blitz, die Glühwürmchen flimmerten vor Aufregung.

**Problem**
Sowohl das Wort "Au" als auch "Aufregung" werden als "im gleichen Satz verwendet" markiert.

**Anmerkung**
Problem tritt auch auf, wenn hinter "Au" ein falsches Apostroph gesetzt wird.

**Info**
LibreOffice 7.0.4.2
LT Plugin: 5.2.1

**Comment by FredKruse** [comment]
Der Fehler ist behoben. Bitte morgen mit dem neusten Snapshot testen und das Issue schließen.

**Comment by ChristianPervoelz** [comment]
Getestet mit _LanguageTool 5.3-SNAPSHOT (2021-03-22 19:45:43 +0000, 4993933)_
