### ISSUE TITLE
[de][LibreOffice] false positive bei "Art" und "Artefakt"

### ISSUE THREAD

**Issue by ChristianPervoelz** [languagetool-org/languagetool#4647]
**Beispielsatz**
Sie sind alle in der gleichen Art hergestellt. Nur bei einem Artefakt wurde eine andere Vorgehensweise angewandt.

**Problem**
Das Wort _Art_ wird als "im nachfolgenden Satz verwendet" markiert, das Wort _Artefakt_ als "im vorhergehenden Satz".

Das Problem tritt auch auf, wenn die beiden Sätze mit einer Konjunktion verbindet.

**Info**
LibreOffice 7.0.4.2
LT Plugin: 5.2.3

**Comment by FredKruse** [comment]
Der Fehler ist behoben. Bitte morgen mit dem neusten Snapshot testen und das Issue schließen.

**Comment by ChristianPervoelz** [comment]
Getested in _LanguageTool 5.3-SNAPSHOT (2021-03-22 19:45:43 +0000, 4993933)_.
