### ISSUE TITLE
Runtime error when using with Flatpak version of LibreOffice

### ISSUE THREAD

**Issue by kolgza** [languagetool-org/languagetool#4649]
![Screenshot from 2021-03-20 14-30-15](https://user-images.githubusercontent.com/46303203/111881893-0efe3e00-8989-11eb-8a7a-f20af87b882d.png)

**Comment by FredKruse** [comment]
This problem should be solved with 5.3. Please test with the latest snapshot at: https://internal1.languagetool.org/snapshots/

**Comment by kolgza** [comment]
I don't know how to compile an extension for LibreOffice.

**Comment by FredKruse** [comment]
You can use this link to download the extension: https://internal1.languagetool.org/snapshots/LanguageTool-20210322-snapshot.oxt.

**Comment by kolgza** [comment]
This issue seems to have been resolved with the latest snapshot.
