### ISSUE TITLE
[es] some commonly ignored words

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4663]
Not sure if this list is helpful, I took it from Matomo
* Aeroméxico
* INEGI
* Karla
* Oscar
* Joan
* Angie
* Center
* Marc
* Meet (Probably "Google Meet")
* DiDi
* Marie
* CS
* co
* Wow
* Martin
* KB
* AC
* Resolution
* CR
* Restrepo
* min
* quiz
* Victor
* Miriam
* Angela
* engagement
* Express
* Teams (Probably when referring to "Microsoft Teams")
* IMSS
* Community
* Samantha
* CO (short for "Colombia"?)
* SN
* Maritza
* Ashley
* Nicolas
* Ibagué
* FC (Probably abbreviation for "Football club")
* IGV
* Lopez
* TP
* Quijano
* relacionamiento
* 3x
* RR
* CDC
* Ivonne
* 8M
* Nelly
* BTS
* Ethan
* ARL
* CAS
* Sofia
* Solís
* Adrian
* Network
* shampoo
* Lilly
* DRV
* Jaume
* IPS
* PET
* CUIT
* Research
* Champions
* tambien
* Catalunya
* Galdós
* Arredondo
* Drv indica
* CTA
* DSL
* CAT

**Comment by jaumeortola** [comment]
Thanks. The list was more useful than it seemed at first sight. 

"tambien" is doubtlessly a misspelling. Users shouldn't add it to their personal dictionary. I put it in a rule, so the match cannot be avoided.

**Comment by tiff** [comment]
Great, thanks!
