### ISSUE TITLE
[fr] *son cachés / sont cachés

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#4669]
- [x] Dans sa tour **son** cachés les plus beaux trésors.
- [x] contre de vastes rocs trois vaisseaux **son** lancés.
- [x] les "dream box" son disponibles partout
- [x] Tout à côté son posés
- [x] Éric Haley et son adjoint Richard Vachon son congédiés et remplacés

Undetected errors.

**Comment by jaumeortola** [comment]
> Tout à côté son posés
> Éric Haley et son adjoint Richard Vachon son congédiés et remplacés

**Comment by jaumeortola** [comment]
> Les liens que je tes donné 
t'ai donné

**Comment by jaumeortola** [comment]
je tes/je t'ai https://github.com/languagetool-org/languagetool/commit/49d266bfb6799574533efb82d5a7727fb69e1d2a

**Comment by dpelle** [comment]
> Les liens que je tes donné

Also not detected:

Il s'ait trompé → Il s'est trompé.

**Comment by udomai** [comment]
Interesting rule lead! Phonetic confusion pairs (est, es, ai, ais, ait (aie, et) / combinable with m', s', t' (including mes, tes, ses, ces)
