### ISSUE TITLE
[DE]LibreOffice LT-Installer Loop

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#4670]
Moin liebes LanguageTool-Team

Ich wollte euch informieren, dass das Updaten auf einem neuen Snapshot immer in einer Dauerschleife landet. Erst wird installiert, dann neuzustarten, um neu installiert zu werden. Das ist mir in letzten Version dauernd passiert. Ist das ein Fehler von euer Seite oder von LO? 
![grafik](https://user-images.githubusercontent.com/78316155/112336962-cd89cd80-8cbd-11eb-87c8-a0c494d8192a.png)

Grüße Dallun511

**Comment by FredKruse** [comment]
Das ist ein Fehler von LO, der auftritt, wenn LO erst durch die Installation geöffnet wird. Ich umgehe ihn, indem ich ein leeres Dokument öffne und erst dann die oxt-Datei mit einem Doppelklick aufrufe.

**Comment by MasterDallun511** [comment]
Gilt das auch, wenn LO durch das System bereits gestartet wird? Ich habe diesen Fehler immer, weswegen ich frage.

**Comment by FredKruse** [comment]
Leider weiß ich das auch nicht. Das müsstest du ausprobieren.

**Comment by FredKruse** [comment]
Leider nicht vonseiten LT zu beheben. Ich schließe das Issue.
