### ISSUE TITLE
[en] common VB/VBN confusions not found

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#4674]
Were they **send** via WhatsApp? → sent
It looks fine but was it **build** on concrete? → built
Weren't those houses **build** with the help of a construction company? → built
~~Will it **sent** the message? → send~~

**These are already found:**

What was it build on? (HOW_DO_I_VB[2])
Did they sent the message? (DID_PAST[2])

**Comment by tiff** [comment]
> Will it sent the message?  

I committed a rule for this, this morning (MD + PRP + VB.*).

**Comment by AzadehSafakish** [comment]
Committed a rulegroup for the phrases above + present (progressive) perfect tense.
