### ISSUE TITLE
[DE]Der Vorgesetzter = Fehlalarm

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#4678]
Moin liebes LanguageTool-Team

Der **Vorgesetzter** schrie durch das Smartphone.
LT: "Artikel und Nomen stimmen grammatikalisch nicht überein. Meinten Sie „Vorgesetzte“?"
![grafik](https://user-images.githubusercontent.com/78316155/112561809-37959600-8dd6-11eb-9d52-5e939590739d.png)
https://www.duden.de/rechtschreibung/Vorgesetzter

Bitte beheben.

Grüße Dallun511

**Comment by danielnaber** [comment]
Auch wenn die Analyse seltsam aussieht, LT hat hier recht ("Ein Vorgesetzter", "Der Vorgesetzte").

**Comment by MasterDallun511** [comment]
Mein Fehler, ich habe völlig vergessen, dass ein Vorgesetzter heißt.
