### ISSUE TITLE
[fr] 2e -> 2d, 2de

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#4679]
> 2e[2e/J e s] 2d[2d/J m s] 2de[2d/J f s]

Create a rule that suggests 2e -> 2d (masculine), 2de (feminine), with superscripts.

**Comment by jaumeortola** [comment]
More generally, check all abbreviated forms for ordinals: 

http://www.academie-francaise.fr/abreviations-des-adjectifs-numeraux

**Comment by dpelle** [comment]
@jaumeortola wrote:

> Create a rule that suggests 2e -> 2d (masculine), 2de (feminine), with superscripts.

That's not correct:

* 2e = deuxième (épicène)
* 2d = second (masculin)
* 2de = seconde (féminin)

Both are fine, they abbreviate different words.
The link at http://www.academie-francaise.fr/abreviations-des-adjectifs-numeraux could clearer.

**Comment by jaumeortola** [comment]
Thank you. It is here documented: https://fr.wiktionary.org/wiki/2e
