### ISSUE TITLE
[ru] logical error  "интересую книгу"

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#468]
messed интересную и интересую

Example
WRONG Я заглянул в книжный и купил интересую книгу.

if there is an NN:.*:Sin:V after интересую it is probably интересную

**Comment by kostyfisik** [comment]
The rule should check for a verb in advance. Otherwise, there will be a lot of exception like
Я не интересую службу охраны как личность

**Comment by yakovru** [comment]
Yes, this is typo in wikipedia. But for this need another rule.

**Comment by kostyfisik** [comment]
The rule is incomplete. There is a bunch of similar examples:
WRONG Тогда поймёшь интересую вещь, таракан без ног не слышит.
WRONG Подметили интересую деталь, все корешки книг перевёрнуты.
WRONG Встретил интересую женщину.
and so on...

**Comment by kostyfisik** [comment]
Seems to be fixed.
