### ISSUE TITLE
[ru] Style correction "Когда\если" and two verbs

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#469]
For sentence starting with когда\если with two verbs without a conjugation in between suppose using -- or a conjugation in between. 

CORRECT "Когда человек хочет что-то получить, ему надо чем-то пожертвовать."
BETTER "Когда человек хочет что-то получить – ему надо чем-то пожертвовать."
BETTER "Когда человек хочет что-то получить, то ему надо чем-то пожертвовать."

СORRECT "Если ты позвонил, говори."
BETTER "Если ты позвонил, то говори."

**Comment by yakovru** [comment]
Fixed.
