### ISSUE TITLE
LibreOffice: Some strings are untranslated

### ISSUE THREAD

**Issue by Elaborendum** [languagetool-org/languagetool#4699]
![image](https://user-images.githubusercontent.com/71190696/112744153-1f9f4d00-8f63-11eb-84eb-6ac7302bc35d.png)

Just from this image: "No check of text in the background", "Sentence exceeding rules", "All", "Only spelling", "Use only one core", etc

I can't exactly pinpoint all instances at the moment, but certainly there are a lot of them scattered around.

Present in 5.3-snapshot and previous versions.

**Comment by FredKruse** [comment]
@danielnaber All these strings are in the MessageBundle.properties. Is this a problem with the translation or made I a mistake? (I am not sure if all the strings are in MessageBundle_en.properties. Could this be a problem?)

**Comment by danielnaber** [comment]
@FredKruse Please also add new keys to `MessageBundle_en.properties`, maybe that will help.

**Comment by FredKruse** [comment]
I am not sure, if all strings in the option panel translated for all languages. Could you test this for 5.5.1? Please close the issue, If the translations are done.

**Comment by FredKruse** [comment]
The issue should be solved for the latest version, so I close it.
Please reopen the issue with an actual screenshot, in case the problem still exist.
