### ISSUE TITLE
[en] wrong spelling suggestion suggested first

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4704]
> I want to handel it.
> I want to oder it.

<img width="461" alt="Bildschirmfoto 2021-03-29 um 12 33 25" src="https://user-images.githubusercontent.com/37363/112824569-faa5f980-908a-11eb-9649-cee9a6ea7021.png">

@danielnaber again, it really seems that any word that matches case-sensitive is suggested first. I think it's caused by the fixes done for: https://github.com/languagetool-org/languagetool/issues/2738 ("gif" should suggest "GIF")

**Comment by ChristinaLJC** [comment]
Hi! I'd like to work on this issue!

**Comment by ChristinaLJC** [comment]
The weight for each suggested word is totally determined by the distance in the dictionary. We may modify the weight calculation method of replacement candidates. We will both consider the distance in the dictionary and frequency of using.
![QQ图片20220523232943](https://user-images.githubusercontent.com/44918766/169855896-ca324617-fc70-4333-a6e2-d22b5ee159d9.png)

**Comment by ChristinaLJC** [comment]
I actually find that the "distance" is calculated according to the frequency. I may check the frequency of the suggested word and then change its weight by adding a constant number.

**Comment by tiff** [comment]
This got worse:

<img width="606" alt="Bildschirm­foto 2023-05-25 um 13 22 25" src="https://github.com/languagetool-org/languagetool/assets/37363/eb7270e6-640c-450e-95df-ccbcf2cf120b">

**Comment by danielnaber** [comment]
Closing outdated issue (feature turned off).
