### ISSUE TITLE
[de] großgeschriebene Verben im POS Dict

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4712]
Warum ist "Gehe" (großgeschrieben) hier als Verb getaggt aber "Laufe" nicht?

![Bildschirmfoto 2021-03-30 um 08 08 08](https://user-images.githubusercontent.com/37363/112941641-3db9a880-912f-11eb-9c24-6176062ff036.png)

Dasselbe Problem existiert mit "Besuche":
> Ich Besuche dich.

Wahrscheinlich gibt es viele mehr solcher Fälle.

Das führt dann u.a. zu solchen merkwürdigen Vorschlägen:
![Bildschirmfoto 2021-03-30 um 07 28 24](https://user-images.githubusercontent.com/37363/112941773-6d68b080-912f-11eb-92ed-48eef23cdbe0.png)

Wenn man Verb-POS für "Besuchen" entfernt schlägt die Regel `SUB_VER_KLEIN` fehl.

**Comment by danielnaber** [comment]
This should be fixed now (but the original error "Bitte besuche Sie mich...") doesn't match anymore due to other changes.
