### ISSUE TITLE
[es] user feedback regarding agreement rules

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4716]
> No reconoce error de concordancia sujeto-verbo ni de sentido; pero sobre todo me interesa el de concordancia. En español > es  indispensable.
> El texto fue: 
> la niñas compró de aquí.

**Comment by tiff** [comment]
Is it just me or do we actually find the mistake?

**Comment by jaumeortola** [comment]
We find an agreement mistake (determiner + noun): "la niñas" > "las niñas".

We don't find the mistake in: "las niñas compró" (subject-verb agreement).

The subject-verb agreement rules can be extended. But the risk of getting many false positives is high.

**Comment by udomai** [comment]
> la niñas compró de aquí.

This does not look like a natural mistake. If we catch the N_V_AGR, that's cool. But we cannot re-write a nonsense sentence.
