### ISSUE TITLE
Develop Google Docs add-on

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#473]
From the feedback I get about the [Chrome add-on](https://chrome.google.com/webstore/detail/languagetool/oldceeleldhonbafppcapldpdifcinji), I see an add-on for Google Docs should be high on our list of priorities. I got confirmation from someone who has developed something similar that a basic version can be done in about 2 days (Javascript knowledge required). Anybody from the community who'd like to work on this?

See https://developers.google.com/apps-script/add-ons/

See https://github.com/jordimas/google-docs-language-tool for a prototype

**Comment by jaumeortola** [comment]
I have taken a look at this. So far I have implemented the new JSON API and have re-used some CSS styles from the LT web browser add-on. 
Next steps:
- [ ] Replace errors with suggestions in the document with a click. 
- [ ] Multilingual messages (probably re-using the translations in the web browser add-on)
- [ ] Add some setup options (similar to the web browser add-on). 
- [ ] Deal with long text documents (more difficult).

**Comment by jaumeortola** [comment]
@danielnaber 
I got something that works. Now I'm figuring out how to make it available to other people (for testing a little before publishing). Do you have any suggestion or preference?
And what about publishing? From what account do we do it?

**Comment by danielnaber** [comment]
Great! I'm not sure how to test it without publishing. But maybe we could just publish it without linking it from anywhere (and with a big "ALPHA" marker). If you want, you can publish it from your own account, but we can also publish it from mine so it's published from the same account as the Chrome add-on.

**Comment by jaumeortola** [comment]
I have put the code [here](https://github.com/jaumeortola/languagetool-google-docs). One way of testing is to copy and paste the four files manually in "Tools > Script Editor" in a Google Document. There are other ways to do it, but I am not familiar with the development environment described [here](https://developers.google.com/apps-script/managing_projects). Is this the same environment that you use for the Chrome extension?

I didn't want the add-on to re-check constantly the text after each replacement is made. So when an error is selected in the sidebar, the error text is searched inside the document with the help of the context. This could sometimes fail, specially after the original text is edited, but I think it's the least bad solution.

**Comment by danielnaber** [comment]
I don't use any environment for the Chrome add-on other than IntelliJ for working on the JS. For the add-on, the packaging is just zipping the files and uploading them to the store manually. So I don't think I can be of much help with this.

**Comment by milekpl** [comment]
@jaumeortola The code is already there, shouldn't we close this? Of course, there will be outstanding issues, but they belong to the Google Docs extension, right?
