### ISSUE TITLE
[fr] "á" should only suggest "à"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4735]
I think it would help if "á" only suggests "à", or is there a prominent case where the user wanted to use one of the other options?

![Bildschirmfoto 2021-04-01 um 16 12 58](https://user-images.githubusercontent.com/37363/113307270-406df680-9305-11eb-8f85-a5f2ee9cccd6.png)

**Comment by jaumeortola** [comment]
The only exception would be when we suggest à → a. 
`<example correction="a">Il <marker>à</marker> été aux États-Unis.</example>`

We can add "á" to the rules for à → a and a → à. We will have:
à|á → a and a|á → à.

**Comment by tiff** [comment]
Sounds good
