### ISSUE TITLE
[BUG][Webseite] Copy und Paste Bug auf der Webseite

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#4736]
Moin liebes LanguageTool-Team

Das wird korpiert.
> Werkstaat

Hier soll es eingefügt werden
![grafik](https://user-images.githubusercontent.com/78316155/113359681-90ba7800-9348-11eb-92db-be6d64fbe98d.png)

und das ist das Ergebnis
![grafik](https://user-images.githubusercontent.com/78316155/113359717-a29c1b00-9348-11eb-94b2-47f45097e25d.png)

Wo kommen die Absätze her? Vor allem wird es schlimmer, wenn man einen ganzen Satz hinzufügt.

> Die Gruppenführerin sagte, dass sie zu ihrem Boss gehen müssen, der sich in der Werkstatt ihres Berufes auf sie wartet und dass sie sich nicht wundern sollten, wenn er oder sie die Namen der Rolle sagen und nicht ihren echten Namen.

Das Ergebnis
![grafik](https://user-images.githubusercontent.com/78316155/113359900-058db200-9349-11eb-87c3-e259e81a4579.png)

Ist das von euch so gewollt? Für mich sieht das im ersten Moment für ein Bug aus.

Grüße Dallun511

**Comment by tiff** [comment]
@MasterDallun511 Danke für den Hinweis. Wo hast du den Text herkopiert und welchen Browser verwendest du? Ich kann es gerade nicht nachvollziehen

**Comment by MasterDallun511** [comment]
Webbrowser Mozilla Firefox 87.0 (64-Bit)
Der Text und das Wort kommen ürsprünglich aus LibreOffice.
Dabei ist es egal, welchen Text ich nehme.

Als weiteres Beispiel:
![grafik](https://user-images.githubusercontent.com/78316155/113576060-2858e880-961f-11eb-8464-5970d23a368a.png)
![grafik](https://user-images.githubusercontent.com/78316155/113576081-2f7ff680-961f-11eb-8021-fdafe75ba1ed.png)

**Comment by tiff** [comment]
Danke, sollte nun behoben sein.
