### ISSUE TITLE
[en] Oxford spelling "raise"

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#4744]
Hello!

I get a false positive with:
`Raise and shine!`

**Comment by MikeUnwalla** [comment]
@marcoagpinto , not sure why the rule gave a false warning. The lower-case word 'raise' was in the example that starts "These verbs are always ~ise: ". The postags for 'Raise' and 'raise' are the same. Anyway, I changed an exception to fix the FP.
