### ISSUE TITLE
[pt-br] The adverb "daqui" not always requires preposition 2

### ISSUE THREAD

**Issue by hmslima** [languagetool-org/languagetool#4747]
One year ago I reported ([link](https://github.com/languagetool-org/languagetool/issues/2950)) that LT (LanguageTool) wrongly was considering all occurrences of "daqui" without the preposition "a" as wrong.

But still there are situations where "daqui" is considered as incorrect

    Vou-me embora daqui!

That sentence is correct.

**Comment by marcoagpinto** [comment]
ahhhh...

I will take a look at it on Tuesday.

I didn't go to my job on Saturday and the boss let me do the day tomorrow.

On Tuesday I will be at home and will work on it.

Sorry for taking a year.

**Comment by marcoagpinto** [comment]
Fixed!
