### ISSUE TITLE
[pt-br] Verb agreement of the verb "assistir"

### ISSUE THREAD

**Issue by hmslima** [languagetool-org/languagetool#4749]
The use of the verb _"assistir"_ is a bit complex, but I will only talk about only one aspect of the word. However, let's see its possible meanings:

<hr>

**TO ASSIST:**

    A enfermeira foi contratada para assistir o paciente.
    A prefeitura assistirá as famílias que perderam as casas na enchente.
    A mãe assistia o filho no hospital.
    A mãe assistia ao filho no hospital.

**TO WATCH:**

    Todos assistiram ao filme de Elizabeth Taylor.
    Assisti a um jogo de vôlei.
    Assistiremos a um show de rock 

**TO BELONG TO:**

    É um direito que assiste ao trabalhador.
    O direito à moradia assiste aos cidadãos.

All cases admit the use of the preposition _"a"_, although it's preferable to not use this preposition when _"assistir"_ means "to assist".

<hr>

OK, my point is, when the verb _"assistir"_ is succeeded by words like _"televisão", "TV", "filme", "show", "jogo", "teatro", "espetáculo", "cinema"_, etc, it's most likely that the verb _"assistir"_ means "to watch".

So, if you see the sentence...

    Todos assistiram o filme de Elizabeth Taylor.

..., it most likely means _"Everybody watched the movie of Elizabeth Taylor"_ than _"Everybody assisted the movie of Elizabeth Taylor"_, so the verb of this sentence should have a preposition if _"assistir"_ here really means "to watch".

My suggestion is, if LanguageTool sees the verb _"assistir"_ **without preposition** and this verb is succeeded by words from the list below, LanguageTool could show a mere warning that when the word _"assistir"_ has the meaning of "seeing" (_ver_), "witnessing" (_presenciar_) or "watching", it must have the preposition _"a"_.

* televisão
* TV
* filme
* show
* jogo
* futebol
* partida
* teatro
* peça
* espetáculo
* cinema
* _You can add more key-words to this list_

**Comment by marcoagpinto** [comment]
This one I will fix tomorrow 🙂 

I have already spent a few hours today improving a rule and testing it against a 600 000 corpora.

**Comment by marcoagpinto** [comment]
@tiff @udomai @jaumeortola 

I have created the rule:
https://github.com/languagetool-org/languagetool/commit/f3929d4174b9a00d8f94bb6b204c41a7712d9f15

However, there must be a simpler/cleaner way of making its suggestions (one or two lines, instead of one line for each possibility).

Could one of you improve the suggestions code and close the ticket?

Thanks!

**Comment by marcoagpinto** [comment]
Well, the rule suggests too many words, but it does the job.

Closing the ticket.
