### ISSUE TITLE
[ru] new words for tagging dictionary

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#475]
@yakovru Could you please add to tagging dictionary superb forms of adjectives?

Наибольший наименьший наилучший наихудший наикрасивейшая наимудрейший наисильнейший наибыстрейший наибеднейший

The first four seems to be used quite often in modern texts.

In scientific papers word "исследовались" is also used quite often, still it is missing in tagging dictionary.

**Comment by yakovru** [comment]
Fixed.
