### ISSUE TITLE
[ru] False positive "однако"

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#476]
"однако" separating two verbs  or parts of a complex sentence (so in the meaning of "но") should be decorated with only one comma (at the moment LT suggest to put the second).

FALSE POSITIVE
Перестрелка затихла, однако ядра и бомбы продолжали летать сюда, как и отсюда
Они умолкли, однако не успокоились.

**Comment by yakovru** [comment]
Fixed.

**Comment by kostyfisik** [comment]
False positive on the text in Rosental`s book
Однако вместо нужной в подобных случаях конструкции

**Comment by yakovru** [comment]
This example is related to word "вместо".  Thanks.
"Но вместо нужной в подобных случаях конструкции."

**Comment by yakovru** [comment]
Fixed.
