### ISSUE TITLE
[en] POS for ct and cts (abbreviations of cent/s)

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#4761]
LT has these tags:
```
ct/null
cts/NN
```

Merriam-Webster and American Heritage dictionaries show only ct, not cts. Collins (British English) shows cts as a plural.
https://www.merriam-webster.com/dictionary/ct
https://ahdictionary.com/word/search.html?q=ct
https://www.collinsdictionary.com/dictionary/english/cts

ct must be NN, but is it also NNS? ("I lost 3 ct yesterday" or "I lost 3 cts yesterday"?)

@AzadehSafakish, in American English, do you use ct or cts or both as an abbreviation for cents?

**Comment by AzadehSafakish** [comment]
Both are acceptable, but I'm definitely leaning more towards "3 ct." I would say "ct" is both NN and NNS in American English.

**Comment by MikeUnwalla** [comment]
@AzadehSafakish , thanks.
