### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by giorgossideris** [languagetool-org/languagetool#4764]
Hello, I am new to languagetool and I am trying to build it. I cloned it successfully but after the command "mvn clean test" the LanguageTool command-line version test fails. Is there a way to fix this?

**Comment by danielnaber** [comment]
What error do you get?

**Comment by giorgossideris** [comment]
![languagetool_error](https://user-images.githubusercontent.com/56915448/113745730-376a9400-970e-11eb-9842-30eebd5cdb7b.png)
This is what I get, I am not sure if it is local or general.

**Comment by danielnaber** [comment]
You need to scroll up to see the actual error.

**Comment by giorgossideris** [comment]
Oh I am sorry. Here it is.
![image](https://user-images.githubusercontent.com/56915448/113752340-84059d80-9715-11eb-8c86-3347f5de464c.png)
![image](https://user-images.githubusercontent.com/56915448/113752401-98499a80-9715-11eb-9672-a9e81315c582.png)
![image](https://user-images.githubusercontent.com/56915448/113752433-a3042f80-9715-11eb-870b-0e63b2209bb8.png)
![image](https://user-images.githubusercontent.com/56915448/113752448-aa2b3d80-9715-11eb-946a-3b8af39088f4.png)

**Comment by danielnaber** [comment]
This is under Windows, isn't it? The CI and the developers don't use Windows, so any help to get the tests more stable under Windows is welcome.

**Comment by giorgossideris** [comment]
Yes, correct. Ok I will give it a look, thank you! I am closing the issue.
