### ISSUE TITLE
[ru] "То же время"

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#477]
Usually "то же" should be split if there is a "NN:Neut" after it.
WRONG Буду в тоже время
WRONG Cпрячу в тоже место
Antipattern - there is an noun before "тоже"
CORRECT Сосна тоже дерево, только хвойное.

**Comment by yakovru** [comment]
http://lik-bez.com/board/orfografija/slitno_razdelno_cherez_defis/to_zhe_tak_zhe/64-1-0-303

**Comment by yakovru** [comment]
Fixed.
