### ISSUE TITLE
[DE]Fehlalarm/Überreaktion einer Regel

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#4770]
Moin liebes LanguageTool-Team

Er begann dann, die fünfte **Sinfonie** von Beethoven zu spielen.
![grafik](https://user-images.githubusercontent.com/78316155/113841615-2d8a7480-9792-11eb-8139-9df970fe5c24.png)

Hier ist nur ein Satz und bereits hier schlägt die Regel an. Das sollte sie aber nicht.

Grüße Dallun511

**Comment by danielnaber** [comment]
Liegt daran, dass "Symphonie" als Grundform von "Sinfonie" betrachtet wird. Ich nehme das Paar mal raus bis zu einem richtigen Fix.

**Comment by MasterDallun511** [comment]
Die Überreaktion wurde behoben. Es wurde vermutlich vergessen, den Thread zu schließen.
