### ISSUE TITLE
[pt] false alarm "mail.google.com"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4773]
![Bildschirmfoto 2021-04-07 um 16 47 16](https://user-images.githubusercontent.com/37363/113886402-ef587980-97c0-11eb-9a04-8163911db832.png)

**Comment by marcoagpinto** [comment]
@tiff 

It happens with all mail servers:
mail.sapo.pt
mail.google.com

not sure how it can be fixed because the word "mail" is the one which gets the hit.

**Comment by marcoagpinto** [comment]
unless I can create an antipattern for
mail + DOT + noun + DOT?

Is it a good plan?

**Comment by marcoagpinto** [comment]
Ops... the dots should be inside brackets:


```
<!-- MARCOAGPINTO 2021-04-07 (17-MAR-2021+) *START* -->
<!--
mail.google.com
mail.sapo.pt
-->
      <antipattern>
		<token>mail</token>
		<token regexp='yes' spacebefore='no'>[.]</token>
		<token spacebefore='no' postag='NC.+|AQ0.+' postag_regexp='yes'/>
		<token regexp='yes' spacebefore='no'>[.]</token>
      </antipattern> 
<!-- MARCOAGPINTO 2021-04-07 (17-MAR-2021+) *END* -->	  
```
