### ISSUE TITLE
[fr] Sur ce bonne fin de journée. -> Sur ce, bonne fin de journée.

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#4777]
Missing comma: 
> Sur ce bonne fin de journée. -> Sur ce, bonne fin de journée.

New rule needed. Otherwise, there is an agreement rule match.

**Comment by Rebecca-auque** [comment]
The rule is done.

**Comment by jaumeortola** [comment]
Now, we need to adjust the priorities. Is this a good idea? → All comma rules should have higher priority than agreement rules. @Rebecca-auque @udomai

**Comment by udomai** [comment]
In theory, that's the way to go. A comma can prevent an agreement FP!

**Comment by jaumeortola** [comment]
Then, collect all IDs for comma rules and add them here: https://github.com/languagetool-org/languagetool/commit/51f50010a6617f160b4cb966099a2cae685d2cfa @Rebecca-auque
