### ISSUE TITLE
[ru] word repetitions are not detected

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#478]
WRONG \ CORRECT
исключить исключение \ убрать исключение
потребовать требование \заявить тербование
пожелать желание \ загадать желание
заказать заказ \ сделать заказ 

Sometimes they can be rather separated in the sentence.
WRONG Я хочу заказать небольшой, но очень важный для нашего коллектива заказ.
WRONG Мы исключили Иванова и Петрова из списка допущенных до работ и оставили в нём, в виде исключения, только Сидорова.

**Comment by yakovru** [comment]
Fixed for collocations.

**Comment by yakovru** [comment]
For single-root words, we already have the Java rule, which  find repetitions of this words in a sentence.
But this rule is disabled by default.

**Comment by yakovru** [comment]
Fixed.
