### ISSUE TITLE
[ru] Missing tags

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#479]
курса  курс  NN:Masc:Sin:R
сапога    сапог NN:Masc:Sin:R  

missing tag NN:Masc:PL:V 

Два сапога пара.
Он рассматривал два альтернативных курса.

can be related to false positives of #470

**Comment by kostyfisik** [comment]
There are may of them. This is a current walkaround (check them to be plural with два\две\пара)
```xml
<exception regexp="yes">брата|сына|cапога|курса|помощника|фактора|языка|парня|закона|сестры|жены|угла|дня|вопроса|звезды|телефона|любовника|зуба|переводчика|господина|типа|участка|фильма|яблока|вида|прогноза|вектора|села|представителя|вдоха|человека|корабля|спутника|пчелы|шара|билета|ответа|брака|канала|лицея|соседа|ресторана|скворечника|часа|вкуса|кабеля|вулкана|хребта|гиганта|варианта|пресса|обеда|рода|стула|взноса|слезы|приступа|отца|экзамена|стекла|игрока|писаки|военных|этапа|причины|коллеги|вагин|героя|друга|вождя</exception>
```

**Comment by yakovru** [comment]
No. Right form are:
курсы  курс NN:Masc:PL:V 
сапоги сапог NN:Masc:PL:V

**Comment by kostyfisik** [comment]
Это пережиток двойственного числа, вроде спокойно в современном языке используется как множественное. https://ru.wikipedia.org/wiki/%D0%94%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE#.D0.9F.D0.B5.D1.80.D0.B5.D0.B6.D0.B8.D1.82.D0.BA.D0.B8_.D0.B4.D0.B2.D0.BE.D0.B9.D1.81.D1.82.D0.B2.D0.B5.D0.BD.D0.BD.D0.BE.D0.B3.D0.BE_.D1.87.D0.B8.D1.81.D0.BB.D0.B0_.D0.B2_.D1.81.D0.BE.D0.B2.D1.80.D0.B5.D0.BC.D0.B5.D0.BD.D0.BD.D0.BE.D0.BC_.D1.80.D1.83.D1.81.D1.81.D0.BA.D0.BE.D0.BC_.D1.8F.D0.B7.D1.8B.D0.BA.D0.B5 
один - курс 
два/три/четыре - курса (Учился четыре курса в бакалавриате.)
пять и более - курсов
Остальные слова - аналогично.

**Comment by kostyfisik** [comment]
порядка has ADV tag with same meaning as около приблизительно
Собралось порядка 100 человек

**Comment by kostyfisik** [comment]
саке should share сакэ tag
карате should share каратэ tag  (according to wiki both spellings are correct)

**Comment by kostyfisik** [comment]
missing word дисбактериоз  
понимают дисбактериоз кишечника как

missing tag  NN:Neut for боке
Хорошее боке особенно важно для объективов с большой максимальной диафрагмой
https://ru.wikipedia.org/wiki/%D0%91%D0%BE%D0%BA%D0%B5

**Comment by kostyfisik** [comment]
мате NN:Masc
Крепкий мате
https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%82%D0%B5

**Comment by kostyfisik** [comment]
A huge list of personal names (and some other rare words) from Wikipedia with missing tags can be found in the attached file - most of the errors are due to missing tags or are real errors...
[wiki-result-ru-missing-Names.txt](https://github.com/languagetool-org/languagetool/files/447242/wiki-result-ru-missing-Names.txt)

**Comment by kostyfisik** [comment]
I believe that most of that names are not flexible (with no cases).

**Comment by kostyfisik** [comment]
cебя is missing
я был вне себя от зависти
себе marked as a particle while it is a PNN (возвратное местоимение)

**Comment by kostyfisik** [comment]
https://ru.wiktionary.org/wiki/%D1%81%D0%B5%D0%B1%D1%8F

**Comment by yakovru** [comment]
кратчайший  in dictionary is ADJ_Com:Masc:Nom, but it  ADJ_Com:Masc:Nom +  ADJ_Com:Masc:V

**Comment by kostyfisik** [comment]
has no tag воспроизводимость, воспроизводимости и т.д.

**Comment by kostyfisik** [comment]
has no tag антикорреляция, антикорреляции etc.

**Comment by kostyfisik** [comment]
has no tag невозмущённой etc.

**Comment by kostyfisik** [comment]
has no tag расфазировка, расфазировке etc

**Comment by kostyfisik** [comment]
has no tag метаматериалы, метаматериал, метаматериалов etc

**Comment by kostyfisik** [comment]
missing tags for  однодолинных двухдолинный многодолинных for all cases/number/gender

**Comment by kostyfisik** [comment]
has no tag издёрганое etc.

**Comment by kostyfisik** [comment]
missing tags двукратное  and all cases etc.

**Comment by kostyfisik** [comment]
собой is missing (договорились между собой)
трёхуровневый четырёхуровневый all forms are missing (четырёхуровневая схема накачки лазера)

**Comment by yakovru** [comment]
Fixed via https://github.com/languagetool-org/languagetool/commit/2260695f5922be9ae6d150364e2694a4a742be14
