### ISSUE TITLE
Enable GitHub sponsorship

### ISSUE THREAD

**Issue by instagendleg** [languagetool-org/languagetool#4793]
Hi,

I'm really thinking that LanguageTool makes my life better. I want to support it financially.

It could be useful to add a "Sponsorship" button, this feature is free and included within GitHub.

What are you thinking about?

**Comment by danielnaber** [comment]
You could subscribe to the Premium version to support us :-) https://languagetool.org/premium

**Comment by instagendleg** [comment]
Done :)
