### ISSUE TITLE
[de] bullet points at sentence start cause spelling error

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4808]
> ● Ablenkungsfreie Umgebung
> \- Ablenkungsfreie Umgebung
> \* Ablenkungsfreie Umgebung
> \+ Ablenkungsfreie Umgebung

![Bildschirmfoto 2021-04-12 um 16 52 52](https://user-images.githubusercontent.com/37363/114414937-8b162b00-9baf-11eb-8050-1c53066d8db3.png)

@danielnaber war das schon immer so?

**Comment by tiff** [comment]
Verwirrend ist auch der Vorschlag "Ablenkungsfreiem" und "Ablenkungsfreien"? Die scheint er großgeschrieben zu kennen.

**Comment by danielnaber** [comment]
> war das schon immer so?

Ich denke ja. Ist nicht aufgefallen, weil es nur Wörter aus der `spelling.txt` betrifft. Für die haben wir wohl nicht die hunspell-Logik für Deutsch, die besagt, jedes Wort in großgeschrieben zu akzeptieren. Ist einfach zu fixen, aber erstmal die Nebenwirkungen testen...
