### ISSUE TITLE
[fr] suggestion loop

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4810]
> quelques questions quant a la carte

See https://twitter.com/softyoda/status/1381631960544595973

**Comment by tiff** [comment]
@udomai thanks for fixing the loop. I guess the "a" is wrong and needs an accent? If so, we should have a suggestion for this (not urgent).

**Comment by udomai** [comment]
@Rebecca-auque, I think "quant + à + `D`" is a quick win for a "a → à" rule 🤓 this is not urgent, but when you can spare a moment, could you write it?
