### ISSUE TITLE
[de] suggestion in parenthesis ART_ADJ_SOL

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4813]
> Und es wird durch die superweiche Innenseiten ...

![Bildschirmfoto 2021-04-12 um 18 58 37](https://user-images.githubusercontent.com/37363/114432607-2c59ad00-9bc1-11eb-9b32-07356d6884a6.png)

**Comment by tiff** [comment]
Noch einer:

> Falls die Corona-freie Züge ein Erfolg sind ...

![Bildschirmfoto 2021-04-12 um 19 00 00](https://user-images.githubusercontent.com/37363/114432745-4e532f80-9bc1-11eb-8f9a-9e4f4ec9b68b.png)

**Comment by udomai** [comment]
Also am besten wäre ja, wenn wir "super-" und "corona-" vor Adjektiven erkennen und ignorieren könnten. Damit wir auch den Fehler in "Die coronageplagte Kölner haben eine neue Lösung gefunden" finden… kann man das mit dem Chunker irgendwie nachhaltig bauen?
Ansonsten wäre eine einfachere Lösung: die häufigsten Wörter mit super- und corona- suchen und hinzufügen…

**Comment by udomai** [comment]
Dieses spezielle Problem hat sich mit `suppress_misspelled` lösen lassen. Ich halte aber die Augen offen, ob das zukünftig buggt.
