### ISSUE TITLE
[en] possible disambiguation error: 'have' as VB only

### ISSUE THREAD

**Issue by AzadehSafakish** [languagetool-org/languagetool#4814]
'Have' is not tagged as VBP in perfect tense contexts, is this the usual behavior?
'The United States/US have never had a female president.'

![image](https://user-images.githubusercontent.com/81176099/114485792-64f98680-9bc1-11eb-978a-e38f2aa0b701.png)

Additionally, some sentences in present tense seem not to have the tag either.
'They have a younger leader.'
'I have two terriers.'

![image](https://user-images.githubusercontent.com/81176099/114485690-38de0580-9bc1-11eb-9fd4-a246664f7355.png)
![image](https://user-images.githubusercontent.com/81176099/114485718-45625e00-9bc1-11eb-9336-b2d35394128a.png)

**Comment by tiff** [comment]
I noticed this as well. This should not be the case.

**Comment by MikeUnwalla** [comment]
References:
VB vs. VBP: https://sites.google.com/site/partofspeechhelp/home/vb_vbp
VBP: https://sites.google.com/site/partofspeechhelp/#TOC-VBP
https://www.lexico.com/definition/have

@udomai, @AzadehSafakish, @tiff, I am struggling a lot with this disambiguation. The AP are correct for the disambiguation, but, they cause many failures in grammar rules.

I added examples to show what the rule does and does not do. I *think* that all the examples in comments should be VBP:
1) Is my analysis correct?
2) If my analysis is correct, then I will start to look at how to add AP and at the same time prevent failures in the grammar rules.

**Comment by udomai** [comment]
I agree that all the verbs in your examples are VBPs, none of them meet the infinitive/imperative/subjunctive criteria.

<details>
    <summary>examples in question</summary>

        <example type="untouched">The United States have never had a female president.</example>
        <example type="untouched">The United States/US have never had a female president.</example>
        <example type="untouched">They have a younger leader.</example>
        <example type="untouched">I have two terriers.</example>
        <example type="untouched">We actually have 3 children.</example>
        <example type="untouched">Nevertheless, you have the time to help, don't you?</example>
        <example type="untouched">These uninstalls have worked.</example>
        <example type="untouched">What have you done?</example>
        <example type="untouched">Many others have been hiding from the police.</example>
        <example type="untouched">We already have purchased it.</example>
        <example type="untouched">I know several others that have also had problems.</example>
        <example type="untouched">If you have 10 stores, would they not have 10 different URLs?</example>
        <example type="untouched">The 3 SMEs that have already committed to being on film need to be prepared.</example>
        <example type="untouched">These words have errors.</example>
</details>

**Comment by MikeUnwalla** [comment]
@udomai, 

> If **you have** 10 stores, **would they not have** 10 different URLs?

The first 'have' is VBP, but what about the second one? In the affirmative, "They would have 10...", have is VB (infinitive after a modal). So, I am tending towards saying that the interrogative is also VB. That 'they' comes between the modal and the lexical verb is not important.

What do you think?

**Comment by udomai** [comment]
I agree!

**Comment by MikeUnwalla** [comment]
@udomai, @AzadehSafakish, I have done as much as I can to fix the incorrect disambiguation. Some incorrect disambiguations remain. I do not know the best way to deal with them.

Possibly, NODT_HAVE should be rewritten, possibly as a rulegroup, to apply the POS only where we are sure that it is VB. Currently, the APs prevent the rule assigning the POS, but as you can see from the commented examples, I have reached the limit with this method.

What do you think we should do?

**Comment by AzadehSafakish** [comment]
I can take a whack at rewriting it as a rulegroup today.

**Comment by MikeUnwalla** [comment]
@AzadehSafakish , that's great. Thank you.

**Comment by MikeUnwalla** [comment]
Some edge cases remain. If we find them, we can make an issue.
