### ISSUE TITLE
[pt-br] user feedback "porquês"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4815]
> Estou utilizando o LanguageTool há uns dias e aprecio demais o corretor. É sensacional!
Entretanto, reparei um erro quanto ao uso dos “porquês”. O corretor não reconhece quando é uma pergunta sendo feita e acaba informando erroneamente qual o “porque” deve ser usado.
Acredito que essa é uma questão importante e deva ser revisada no LanguageTool.
> Ademas, estou encantada com o LanguageTool.

**Comment by udomai** [comment]
@marcoagpinto – é verdade que as quatro formas existem??

https://brasilescola.uol.com.br/gramatica/por-que.htm

**Comment by jaumeortola** [comment]
Four forms and diverging uses in Portugal and Brazil... https://github.com/languagetool-org/languagetool/issues/2963

**Comment by marcoagpinto** [comment]
@udomai 

Yes, the four terms exist.

I found a Portuguese PDF that explains when to use "por que", but I believe that in Brazil it is used differently?

**Comment by marcoagpinto** [comment]
The Portuguese PDF is from a news channel/newspaper with reporter rules (for their workers).

**Comment by ricardojosehlima** [comment]
@susanaboatto maybe it's time for Brazilians to take over it?
"Porque ele veio?" in complete disagreement with our rules for "porque" and its variants is not flagged by LT as wrong.
The first step may be to know the current rule for "porque" and @marcoagpinto may know it better and also talk to him on how to separate both situations, pt-br and pt-pt.

**Comment by marcoagpinto** [comment]
@ricardojosehlima @susanaboatto 

I, too, don't know the usage of “porque” and “por que”, for decades that I have this doubt.

**Comment by marcoagpinto** [comment]
Ricardo and Susana, maybe you both can find a solution for the rule.

**Comment by marcoagpinto** [comment]
I can do very complex things, but sometimes I fail in very basic stuff. 😄

**Comment by susanaboatto** [comment]
Hi @ricardojosehlima 

About a month ago, I made some improvements to the `POR_QUE_PORQUE` rule and thought of adding one that would detect this mistake. However, we have a problem of ambiguity with it. For example, you could say:

`Você disse que ele ficou bravo comigo. Porque eu não fui?`

In this sentence, "porque" could have the same meaning as "só porque", so it is correct. However, "por que" could also be correct depending on the writer's intention:

`Você disse que ele ficou bravo comigo. Por que eu não fui?`

So I think we need to find a solution for this ambiguity before we detect this error. I would need to analyze more sentences that could be ambiguous and se if "só porque" would be suitable for all of them as a suggetsion.

**Comment by ricardojosehlima** [comment]
We can do the Brazilian part of it. Maybe a separate rule for pt-br and for pt-pt it can remain as is now

**Comment by marcoagpinto** [comment]
“Great Minds Think Alike”

❤️ ❤️ ❤️ ❤️ ❤️

**Comment by ricardojosehlima** [comment]
> Hi @ricardojosehlima 
> 
> About a month ago, I made some improvements to the `POR_QUE_PORQUE` rule and thought of adding one that would detect this mistake. However, we have a problem of ambiguity with it. For example, you could say:
> 
> `Você disse que ele ficou bravo comigo. Porque eu não fui?`
> 
> In this sentence, "porque" could have the same meaning as "só porque", so it is correct. However, "por que" could also be correct depending on the writer's intention:
> 
> `Você disse que ele ficou bravo comigo. Por que eu não fui?`
> 
> So I think we need to find a solution for this ambiguity before we detect this error. I would need to analyze more sentences that could be ambiguous and se if "só porque" would be suitable for all of them as a suggetsion.

Hi yes the case you showed will lead to the ambiguity but I think it is rare to have porque instead of por que. So maybe in the beginning of a sentence always correct to por que.
Maybe it is worth looking at a corpus to find a legitimate use of porque in the beginning to see if we really need to accommodate it

**Comment by susanaboatto** [comment]
Yes, I think looking at the corpus first is a good idea. I will add that to my list :)
