### ISSUE TITLE
[de] inkorrekter Komposita-Split "Onlinestore"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4825]
<img width="524" alt="Bildschirmfoto 2021-04-14 um 15 50 03" src="https://user-images.githubusercontent.com/37363/114721440-37374d80-9d39-11eb-9547-38918c113c81.png">

Das führt zu Fehlalarmen, wie:
> Der Onlinestore ist geschlossen

<img width="355" alt="Bildschirmfoto 2021-04-14 um 15 51 49" src="https://user-images.githubusercontent.com/37363/114721583-5a61fd00-9d39-11eb-8bb6-377e78bb3bdc.png">

**Comment by danielnaber** [comment]
Fixed by https://github.com/languagetool-org/languagetool/commit/ebb77a951988fbd562e42dacb61141fe747e9830
