### ISSUE TITLE
[ru]Typo "в прошлом"

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#483]
If after "в пошлом" there is a past VB it probably should be "в прошлом"

WRONG Хотя в пошлом были предложены решения, мы только сегодня имеем
WRONG В пошлом действии вы видели начало этой истроии.

**Comment by yakovru** [comment]
Fixed.

**Comment by kostyfisik** [comment]
All inflected forms пошлый and inflected (опыт|время|год|месяц|неделя|раз|попытка|серия|сезон|муж|жена|любовник|любовница|отпуск|каникулы|зима|лето|весна|очень|коллекция|квартира|дом) probably should also be used for a new rule. May be it is even easier to find all nouns that can actull be пошлый - рассказ, повесть, фильм, действие... 

WRONG Мой пошлый опыт
WRONG Глагол используется в пошлом времени
WRONG Пошлая попытка не очень удалась
WRONG На пошлой неделе
WRONG В пошлой сери
WRONG Её пошлый любовник 

May be it is even easier to find all nouns that can actully be пошлый - рассказ, повесть, фильм, жест, комментарий, шутка, анекдот,байка, мысли, воспоминания - it looks to be  a full list found in tatoeba base.. 
Пошлый человек should be replaced with пошляк/пошлячка.

a

**Comment by kostyfisik** [comment]
Пошлая фраза, стихотворение, фельетон, куплеты, частушка, предложение

**Comment by yakovru** [comment]
Certain variants are possible:
Possible Мой пошлый опыт
WRONG Глагол используется в пошлом времени
Possible Пошлая попытка не очень удалась
WRONG На пошлой неделе
WRONG В пошлой серии
Possible Её пошлый любовник 

http://dic.academic.ru/dic.nsf/wordhistory/158/%D0%9F%D0%9E%D0%A8%D0%9B%D0%AB%D0%99

**Comment by kostyfisik** [comment]
Wow! Such a great story for a such a  simple word...  Anyway, I believe that it worth warning.
Simple frequency analysis gives us:
tig@tig-laptop3:~/symlink/LT$ cat tatoeba-sentences-rus.csv |grep прошлый |wc -l
55
tig@tig-laptop3:~/symlink/LT$ cat tatoeba-sentences-rus.csv |grep пошлый |wc -l
0
So прошлый из used quite often, and for пошлый -  tatoeba base is not so word rich.

СORRECT Пошлый дурак
Possible Пошлый быт, but something like "Их прошлый быт был прост" looks to have more chances to be correct.

**Comment by yakovru** [comment]
Fixed for exactly wrong variants.
