### ISSUE TITLE
[en] American-British confused words feature not working correctly

### ISSUE THREAD

**Issue by giorgossideris** [languagetool-org/languagetool#4846]
The expressions that contain more than one word in the replace.txt file with the American words confused with British ones (and the British words confused with American ones) are not detected by LanguageTool.

**Example:**

* correctly detected:

![image](https://user-images.githubusercontent.com/56915448/115111524-78be3780-9f89-11eb-95a1-931bd602676d.png)

* not detected:

![image](https://user-images.githubusercontent.com/56915448/115111576-a905d600-9f89-11eb-8540-e25db4048459.png)

**Comment by giorgossideris** [comment]
I will fix it

**Comment by jaumeortola** [comment]
Thank you.
