### ISSUE TITLE
server log: matches count always 1

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#4864]
In the server log, we now get always "1 matches". See: https://github.com/languagetool-org/languagetool/blob/32b8cf788004c55eba6f6eafb668ea59d927bbf0/languagetool-server/src/main/java/org/languagetool/server/TextChecker.java#L503

Is that the desired result for machCount? https://github.com/languagetool-org/languagetool/blob/32b8cf788004c55eba6f6eafb668ea59d927bbf0/languagetool-server/src/main/java/org/languagetool/server/TextChecker.java#L509

**Comment by danielnaber** [comment]
That looks like a bug indeed. Not sure when it broke, we rarely use that number in the logs.

**Comment by jaumeortola** [comment]
I can fix it. Just to be sure: matchCount should be the total count of matches in all CheckResults?

**Comment by danielnaber** [comment]
> matchCount should be the total count of matches in all CheckResults?

I guess so, thanks for the fix.
