### ISSUE TITLE
[pt-br] user feedback "porteiro"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4867]
> O LanguageTool afirmou que a palavra Porteiro é uma expressão de Portugal, em Português do Brasil utiliza-se: zelador.
Tudo bem, existe a palavra zelador no Brasil, mas porteiro é muito utilizada! Porteiro não é só de Portugal!

**Comment by tiff** [comment]
Wow, that was fast. Thanks.

**Comment by marcoagpinto** [comment]
Well, very simple to do.

Only delete one line of text 🙂

**Comment by marcoagpinto** [comment]
The other ticket I will try to fix tomorrow will give a lot more effort.
