### ISSUE TITLE
[de] false-positive bei doppeltem Wort

### ISSUE THREAD

**Issue by ChristianPervoelz** [languagetool-org/languagetool#4879]
**Beispielsatz**
Ich erkannte keinen Lidschlag zu spät, dass es nicht in ihrer Absicht lag

**Problem**
LT markiert _Lidschlag_ und _lag_ als bereits im selben Satz verwendet.

Die Webprüfung bemängelt dies nicht.

**Versionen**
LibreOffice 7.0.5.2
LT 5.3

**Comment by FredKruse** [comment]
Streng genommen war das kein Fehler der Office-Integration, sondern ein Fehler in einer deutschen Regel. Er taucht nur deswegen ausschließlich in der Office-Integration auf, weil es sich um eine optionale Regel handelt, die in der Web-Prüfung nicht berücksichtigt wird (Unter Stil: Wiederholte Worte in aufeinanderfolgenden Sätzen).
Sie ist hier trotzdem richtig gelandet, weil ich sie auch betreue. Es ist schön das jemand anderes, außer mir selbst, die Regel auch nutzt und testet.
Der Fehler sollte behoben sein. Bitte ab dem nächsten Snapshot morgen testen und wenn behoben bitte das Issue schließen.

**Comment by ChristianPervoelz** [comment]
**Behoben**
Getestet mit LanguageTool 5.4-SNAPSHOT (2021-04-26 21:03:51)

Ich finde diese Regel enorm wichtig, nicht nur für das kreative Schreiben, sondern auch für technische Dokumente, Bewerbungen etc. Sich ständig wiederholende Wörter stören enorm den Lesefluß.
