### ISSUE TITLE
[ru]disambiguation problem

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#488]
I have disabled problem cases and marked them with TODO sign. There is also an example that should help to develop an exception in future.  See the file:

https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/ru/src/main/resources/org/languagetool/resource/ru/disambiguation.xml

**Comment by yakovru** [comment]
Remove "за" preposition from disambiguation?

**Comment by kostyfisik** [comment]
No, there is a need for an exception for "Что за"+noun
Disabiguations are very helpful and they should be developed even more. However, I am not a linguist, so this is out of my qualification.

**Comment by yakovru** [comment]
Excepdtion: Однако дворец был возрождён за два (три, четыре) года.
 за + два + "NN:.*:.*:R"
https://github.com/languagetool-org/languagetool/commit/8a01799bf6a3b147a804b5abd40a7fb08d1e545b

**Comment by kostyfisik** [comment]
Михаила Тухачевского, которому предписывалось «в кратчайший срок подавить восстание в Кронштадте».

срок should keep Nom case

Disambiguator log: 
NOUN_V[1]: срок[срок/NN:Masc:Sin:Nom,срок/NN:Masc:Sin:V] -> срок[срок/NN:Masc:Sin:V]
Token	Lemma	Part-of-speech	Chunk
- 
SENT_START 
в	в 
PREP 
кратчайший	краткий 

короткий 
ADJ_Com:Masc:V 
ADJ_Com:Masc:Nom 
ADJ_Com:Masc:Nom 
срок	срок 
NN:Masc:Sin:V 
подавить	подавить 

VB:INF 
SENT_END

**Comment by yakovru** [comment]
In context "в кратчайший срок подавить восстание" noun "срок" is only NN:Masc:Sin:V
The nominative case of noun or adjective is never uses with any preposition.  If we use preposition - then noun or adjective is in accusative case.

**Comment by kostyfisik** [comment]
Ok, then we should not forget to check case unification rule, which marked this sentence as an error... Previously, some similar errors due to wrong disambuation happened, so I put this without any actual check, sorry...

**Comment by kostyfisik** [comment]
This is strange. This sentense was marked as an error in https://languagetool.org/regression-tests/20160919/result_ru_20160919.html  (and I was not able to found its dismission later on) however, in my local hope LT does not show such an error.

**Comment by yakovru** [comment]
I fixed this error on the next day
https://languagetool.org/regression-tests/20160920/result_ru_20160920.html

**Comment by yakovru** [comment]
Fixed.
