### ISSUE TITLE
apostrophe modfied to the wrong type of character

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#4880]
> Angela idea is good.

LT says `The genitive (‘s) may be missing.` but the apostrophe in the message is modified from what's in XML. The rule is `MISSING_GENITIVE[1]`.

**Comment by jaumeortola** [comment]
There are exceptions to solve: 
* Spanish: Asegúrese de que el carácter 's' es correcto y no es un error de escritura.
* English: The word 'Language‘s' is not standard English. Did you mean "Language’s" (curly apostrophe) or "Language's" (straight apostrophe)?

We could change slightly the messages to avoid the problems, but that is not a general solution. The more general solution would be to preserve any character inside quotation marks.

**Comment by jaumeortola** [comment]
If the replacement of the tags `<suggestion></suggestion>` is done in `toAdvancedTypography()`, the suggestions can be preserved. Fixed here: https://github.com/languagetool-org/languagetool/commit/9378ad2b4066a5d9e806fd3e741eaef757a35cd9
