### ISSUE TITLE
[en] first suggestion for "moore" is "Moore"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4884]
In this sentence I would have expected "more" to be the first suggestion:

![Bildschirmfoto 2021-04-21 um 17 19 21](https://user-images.githubusercontent.com/37363/115578749-d625f180-a2c5-11eb-9061-1ceefbaf7fc9.png)

I'm certain that this happens because of the fix we did for https://github.com/languagetool-org/languagetool/issues/2738

Also, see: https://github.com/languagetool-org/languagetool/issues/4704

**Comment by ChristinaLJC** [comment]
The weight for each suggested word is totally determined by the distance in the dictionary. We may modify the weight calculation method of replacement candidates. We will both consider the distance in the dictionary and frequency of using.

![QQ图片20220523232943](https://user-images.githubusercontent.com/44918766/169854959-9572b863-a8be-41fb-8886-c74c3a550186.png)

**Comment by danielnaber** [comment]
Closing outdated issue (feature turned off).
