### ISSUE TITLE
[DE] Fehlalarm "wo von kein Mensch dabei war"

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#4888]
Moin liebes LanguageTool-Team

Weil bisher nur die Hälfte wieder bei ihren Familien sind, wo von **kein Mensch** dabei war.
LT: "Möglicherweise fehlende grammatische Übereinstimmung des Genus (männlich, weiblich, sächlich - Beispiel: ‚der Fahrrad‘ statt ‚das Fahrrad‘)."

Weil bisher nur die Hälfte wieder bei ihren Familien sind, wo von **keine Menschen** dabei war. 
LT: "Keine Fehler gefunden"

Grüße Dallun511

**Comment by RomanVolak** [comment]
1. Satzsyntax? Ich zähle 3 Varianten (mehr möglich) mit verschiedenem Sinn.
2. wovon oder wo von => aber auch ...wo  kein(e) Mensch(en)... und ...wo davon kein(e) Mensch(en)...
3. Satzanfang mit Konjugation ... kein guter Stil? => Künstlerischer Text? z.B. Spannung mit Stilmittel.
... wenn die Satzglieder nicht definiert sind, folgt Fehler im Detaille. 

Gruß Roman

P.S.: Ich hoffe auf Erkenntnis.

**Comment by janschreiber** [comment]
Wahrscheinlich ist es die beste und praktikabelste Lösung, die Zusammenschreibung von "wovon" zu verlangen.

**Comment by MasterDallun511** [comment]
Der Fehler wurde behoben. 

Weil bisher nur die Hälfte wieder bei ihren Familien **sind**, wo von kein Mensch dabei war.

Dabei wurde sogar an das "sind" im Satz gedacht.
