### ISSUE TITLE
[en] "bussines" only suggests "bus sines"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4891]
![Bildschirmfoto 2021-04-22 um 15 30 51](https://user-images.githubusercontent.com/37363/115723006-d5519600-a37f-11eb-8959-23d15372ed3a.png)

**Comment by udomai** [comment]
Can we solve this by using `en/replace.txt` (i.e. the SimpleReplaceRule.java)? There's only one entry in there for now. Does it work?

Idea by @jaumeortola

**Comment by jaumeortola** [comment]
I see no problem with the simple replace rule. It can be difficult to improve the speller for these words.
