### ISSUE TITLE
[DE] Rule "In Kraft getreten" is wrongly named "ungefähr genau"

### ISSUE THREAD

**Issue by SantosSi** [languagetool-org/languagetool#4903]
In "Semantische Unstimmigkeiten", the rule "ungefähr genau" exists twice. One of them is in reality: "In Kraft getreten" https://community.languagetool.org/rule/show/SEIT_IN_KRAFT_TRETEN?lang=de-DE&ref=standalone-gui

**Comment by danielnaber** [comment]
Thanks, it's fixed now in the code.
