### ISSUE TITLE
On LibreOffice, the options can only be accessed after opening Writer

### ISSUE THREAD

**Issue by SantosSi** [languagetool-org/languagetool#4904]
LibreOffice's extension manager offers options, but the button is greyed out. Instead, one has to open Writer before being able to access LT's options.

**Comment by FredKruse** [comment]
That's a feature not a bug ;)
As far as I know, the option-button inside the extension manager is just for options regarding the installation process. I don't know an any other extensions, for which the option button is not greyed out. 
The options to manage LanguageTool can only be reaches by menu, context menu, LT toolbar or LT ribbon bar.
LT is only available for writer. Other LO products (like impress, etc.) don't support grammar checking. So, the LT menu, etc. appears only for writer.
