### ISSUE TITLE
[de] false-positive näher <> nächste

### ISSUE THREAD

**Issue by ChristianPervoelz** [languagetool-org/languagetool#4917]
**Beispielsatz**
Dieser Schritt brachte uns näher an die Lösung. Der nächste würde das Problem für immer aus der Welt schaffen.

**Problem**
LT markiert _näher_ und _nächste_ als bereits im nächsten, bzw. vorhergehenden Satz verwendet.

**Auftreten**
LibreOffice 7.0.5.2
LT 5.3

Die Webanalyse auf languagetool.org markiert es nicht als Fehler.

**Comment by MasterDallun511** [comment]
Ich kann diesen Fehler nicht nachstellen. Vermutlich, weil meine LT-Version aktueller ist, als deine.

LO: 7.0.5.2
LT: LanguageTool-20210425-snapshot

**Comment by FredKruse** [comment]
Dieser Fehler hat nichts mit der Version der Office-Integration zu tun, sondern es handelt sich um eine optionale Regel (Unter Stil: Wiederholte Worte in aufeinanderfolgenden Sätzen, siehe auch #4879).
Ich empfehle sie gern für kreatives Schreiben, da sie auf Wiederholungen aufmerksam macht und damit den Stil verbessert.
Der Fehler sollte behoben sein. Bitte ab dem nächsten Snapshot morgen testen und wenn behoben bitte das Issue schließen.

**Comment by ChristianPervoelz** [comment]
**Behoben**

Getestet mit LanguageTool 5.4-SNAPSHOT (2021-04-26 21:03:51)

Ich finde diese Regel enorm wichtig, nicht nur für das kreative Schreiben, sondern auch für technische Dokumente, Bewerbungen etc. Sich ständig wiederholende Wörter stören enorm den Lesefluß, egal um welches Textform es sich handelt.
