### ISSUE TITLE
How to integrate language tool in html page.

### ISSUE THREAD

**Issue by sumanrajpura** [languagetool-org/languagetool#4923]
Hi there,
I want to implement language tool in my website html page.
I tried to search on implementation document but was not able to get any.
I want to implement it in same way as shown on your website homepage.
Please share sample code for the same.
Thanks.

**Comment by danielnaber** [comment]
This should still work: http://wiki.languagetool.org/integration-on-websites

**Comment by sumanrajpura** [comment]
Yes that still works but it uses tinyMCe and I don't want to use it. And as shown on your website it's not using tinymce.
If you can share the sample code for the way in which its implemented on your website that would really help.
Thanks.

**Comment by danielnaber** [comment]
The code available on our homepage is only available as part of your Premium product. Please email us at the address given at https://languagetool.org/legal/ if you're interested in that.
