### ISSUE TITLE
[fr] false alarm "Je google"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4927]
According to Wiktionary, "google" is a verb:
https://fr.wiktionary.org/wiki/google

But this happens:
![Bildschirmfoto 2021-04-28 um 15 37 00](https://user-images.githubusercontent.com/37363/116413246-ba779980-a837-11eb-94f6-0eedf0f001dc.png)

**Comment by udomai** [comment]
In principle, we'd have to add the whole paradigm of the verb "googler": 

[https://leconjugueur.lefigaro.fr/conjugaison/verbe/googler.html](https://leconjugueur.lefigaro.fr/conjugaison/verbe/googler.html)

"Toujours faillait-il que je le googlasse…"

**Comment by jaumeortola** [comment]
Tell me some existing verb that can be used as a model (aimer?), and I will add all forms.

**Comment by jaumeortola** [comment]
I have added the verb "googler" with the paradigm of "aimer". Perhaps now we need some rules to suggest `google->Google` when it is a noun.

**Comment by udomai** [comment]
Thank you! "googler" is a first-group verb like "aimer", that's perfect!

Yes, a capitalizing rule for [Gg]oogle is in order now!
