### ISSUE TITLE
[en] False warning ARROWS

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#4934]
ARROWS suggests an arrow at the end of the HTML comment:

`<!-- An arrow in this context is not correct. -->`

![image](https://user-images.githubusercontent.com/5816160/116550538-d0946100-a8ee-11eb-848a-d3ea0341d2e8.png)

**Comment by tiff** [comment]
Closed via https://github.com/languagetool-org/languagetool/commit/7618c058c403cb8c4dd49e618c92615cb100c176
