### ISSUE TITLE
[fr] specific rule needed: à + inf → a + ppa

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#4952]
We'd need a rule for a very specific error (this is to address imprecise suggestions by NON_V):

- Il **à corriger** les erreurs. → a corrigé
- Elle **à trouver** les fautes. → a trouvé
- On **à regarder** un film ensemble. → a regardé

→ in `French.java`, this rule must have higher priority than NON_V.

**Comment by jaumeortola** [comment]
Done by @Rebecca-auque: A_VERBE_INFINITIF
