### ISSUE TITLE
Some weird behavior of ruleEditor

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#496]
Using rule editor at http://community.languagetool.org/ruleEditor/expert 
with a rule 
```xml
<rule id="Unify_Adj_NN_case">
<antipattern> <!-- begin problematic antipattern -->
    <token postag="ADJ:.*:T" postag_regexp='yes'>
        <exception postag="ADJ:.*:T"
                    postag_regexp='yes' negate_pos='yes'/>
    </token>
    <marker>
        <token postag="NN.*:Nom" postag_regexp='yes' />
    </marker>
</antipattern> <!-- end problematic antipattern -->
	<pattern>
		<marker>
	 	<token postag="ADJ:.*"	postag_regexp="yes"/>
		<token postag="NN:.*" postag_regexp="yes"/>
		</marker>
	</pattern>
	<message>test:
	</message>
	 <example> <marker>хрестоматийными слова</marker> о природе </example> 
	<example correction=""> <marker>хрестоматийное слово</marker></example>
</rule>
```
shows an "Unexpected error in the example"
![screenshot from 2016-08-20 12-13-13](https://cloud.githubusercontent.com/assets/5239997/17830254/7ee1b03a-66cf-11e6-9a3e-b036d17e1018.png)

Changing any symbol in rule id fix this. (The present rule id seem to be the only one with antipattern, which is present in Russian grammar.xml at the moment.

**Comment by yakovru** [comment]
name attribute is missing:
<rule id="Unify_test" name="Пробное правило">

**Comment by kostyfisik** [comment]
it does not help for `<rule id="Unify_Adj_NN_case" name="Пробное правило">`
![screenshot from 2016-08-20 14-43-54](https://cloud.githubusercontent.com/assets/5239997/17830940/b052f948-66e4-11e6-83c8-71c6dd488dcd.png)

**Comment by yakovru** [comment]
I try fix this issue.
The id  "Unify_Adj_NN_case" incorrectly used in grammar.xml.
If rule is in rulegroup, that it did not need to assign a name and id.

**Comment by kostyfisik** [comment]
This will break my testing script. I use
`
LT_RULE="Unify_Adj_NN_number,Unify_Adj_NN_gender,Unify_Adj_NN_case"
err_num=100

time java -jar languagetool-wikipedia/target/LanguageTool-wikipedia-*-SNAPSHOT/LanguageTool-wikipedia-*-SNAPSHOT/languagetool-wikipedia.jar check-data -l ru --max-errors $err_num -r $LT_RULE -f ../tatoeba-sentences-rus.csv  > tatoeba-result-ru.csv
`
if I set `LT_RULE` with a rulegroup`s ID this does not work. Anyway, for concurrent testing of several related rules from different rulegroups ID is needed for each rule.

**Comment by yakovru** [comment]
For this example in grammar.xml  we can simply remove rulegroup, and make independed rules.

**Comment by yakovru** [comment]
Depended of GitHub issue #498

**Comment by kostyfisik** [comment]
Yakov, please, do not touch unification part of xml for a wile, let me finish to struggle with exception. I put the ID back as it had broken my workflow. I hope I will finish it soon, so you can review the changes and improve it a bit later.

**Comment by kostyfisik** [comment]
Unification ADJ and NN has a number of common antipatterns, so it is not rational to split them out...

**Comment by kostyfisik** [comment]
I hit this issue again for a rule I have copied from grammar.xml  (improving rule with ruleEditor seems to be more productive). Probably a simple solution can be just to replace the rule id internally with some random long enough string before a real check.

**Comment by danielnaber** [comment]
Should be fixed now in the code, but will take 24 hours to go online.
