### ISSUE TITLE
Premium version tool?

### ISSUE THREAD

**Issue by grantmk** [languagetool-org/languagetool#4960]
Thanks for the open source version of Language Tool.

I have just setup my own server and it's running great. However, I noticed the JSON results come back as "not premium" and basic grammar errors aren't picked up (eg, there vs their).

Do I need to build the tool from source or is that functionality not open sourced?

Thanks in advance!

**Comment by danielnaber** [comment]
That refers to the premium version (languagetool.org/premium) which is not open source.
