### ISSUE TITLE
Another problem with ruleEditor

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#497]
I can put
```xml
<rule id="testlj">
	<pattern>
		<marker>
	 	<token postag="ADJ:.*"	postag_regexp="yes"/>
		<token postag="NN:.*" postag_regexp="yes"/>
		</marker>
		<or>
			<token postag="NN:.*" postag_regexp="yes"/>
			<token postag="SENT_END" />
		</or>

	</pattern>
	<message>test:
	</message>
	 <!-- <example>Смелого пуля.</example> -->
	<example correction=""> <marker>хрестоматийное слово</marker>.</example>
</rule>
```
into ruleEditor and

![screenshot from 2016-08-20 13-26-53](https://cloud.githubusercontent.com/assets/5239997/17830635/d28d8fba-66d9-11e6-9f66-a502c6792a9e.png)

while there is only one `<rule>` block here...

**Comment by jaumeortola** [comment]
When `<or>` is used, several rules are generated internally. It is not easy to do it otherwise. To fix the problem in the rule editor would require some time and work. I am not sure if it is worthwhile, because  `<or>` is not used very often.

**Comment by kostyfisik** [comment]
Probably it should provide a hint which part of `<or>` it is using and show output for both rules on a web page...  I am struggling with a problem on antipattern, however, it appears only with <or> block. See http://forum.languagetool.org/t/antipattern-is-not-working/991/32 for details.

**Comment by danielnaber** [comment]
I've improved the error message to mention the issue with `<or>`.
