### ISSUE TITLE
[en] should "several" be DT?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#4975]
"many" and "some" are tagged as "DT", but "several" is not. Should we add "DT" to "several"?

@udomai @MikeUnwalla

**Comment by MikeUnwalla** [comment]
From a BrE perspective, yes:
https://www.lexico.com/definition/several
https://www.ldoceonline.com/dictionary/several

AmE does not treat 'several' as a determiner:
https://www.merriam-webster.com/dictionary/several
https://ahdictionary.com/word/search.html?q=several

Maybe @AzadehSafakish can confirm/clarify.

But, MW does not show 'many' or 'some' as DT. So, I don't see a problem with adding the POS.

**Comment by AzadehSafakish** [comment]
I don't believe adding the POS would be a problem for AmE, it is used as a determiner and should have the tag.

**Comment by tiff** [comment]
Thanks for your feedback. Closed via 7432aebc51f31fbbb311c8b3bb71efee8c8a9cc0
