### ISSUE TITLE
Add compatibility with Overleaf (Ajax.org Cloud9 Editor)

### ISSUE THREAD

**Issue by instagendleg** [languagetool-org/languagetool#4987]
Hi,

Overleaf the most used online LaTeX editor. It is allowing user to write text, thesis, university documents for the most part.

As of today, LanguageTool is incompatible with this platform. It is using Ajax.org Cloud9 Editor (https://github.com/ajaxorg/ace).

I see two solutions to implement it:

1. Integrate it only with Overleaf.
2. Integrate is with Ace itself as the code editor is widely used on the web.

**Comment by tiff** [comment]
Don't want to spoiler, but just wait 2-3 weeks :)

**Comment by instagendleg** [comment]
I'm looking forward to see that :)

**Comment by danielnaber** [comment]
Overleaf.com is now supported starting with version 4.0 or our add-on.

**Comment by MisterX2000** [comment]
Is there any way to use this on self-hosted instances?

**Comment by danielnaber** [comment]
> Is there any way to use this on self-hosted instances?

The next update (maybe 1-4 weeks away) should detect Overleaf properly, even when running on a different domain than overleaf.com.
