### ISSUE TITLE
[nl] UNPAIRED_BRACKETS has no suggestion

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#5020]
How can we make UNPAIRED_BRACKETS give a suggestion in Dutch?

> Als jij je afvraagt ”Wat te doen met spaargeld in 2020?” dan heb ik vandaag 30 verrassende suggesties.

![image](https://user-images.githubusercontent.com/67792088/118518028-0a12fc00-b738-11eb-8121-13b1d9959a84.png)

**Comment by jaumeortola** [comment]
See: https://github.com/languagetool-org/languagetool/issues/4630
