### ISSUE TITLE
[DE] Fehlerbeschreibung ergibt keinen Sinn

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#5022]
Moin liebes LanguageTool-Team

Sie trägt einen rosa **Push-Up-BH**.
LT: "Das Wort „Push-up-BH“ wird mit Bindestrichen getrennt."
Laut Duden heißt "Push-up-BH, aber ich werde auf Bindesstriche aufmerksam gemacht, die vorhanden sind.
Für mich ergibt die Regel keinen Sinn.

Bitte beheben.

Grüße Dallun511

**Comment by danielnaber** [comment]
Sie trägt einen rosa Push-Up-BH.

**Comment by tiff** [comment]
Hier ist die eigentlich nur die verwirrende Message das Problem. "Push-up" wird nämlich mit einem kleinen "up" geschrieben:
https://www.duden.de/rechtschreibung/Push_up_BH
