### ISSUE TITLE
[fr] plural subject followed by wrong tense (v 3ps instead of 3pp)

### ISSUE THREAD

**Issue by philippehenri** [languagetool-org/languagetool#5023]
En outre, les flux financiers actuels crée et exacerbent les inefficacités et les inégalités.
crée -> créent (les flux financiers = plural)

same but more complex:

En outre, les flux financiers actuels au sein des systèmes de santé crée et exacerbent les inefficacités et les inégalités.
crée -> créent (les flux financiers = plural)

**Comment by jaumeortola** [comment]
The rules for this kind of errors will be improved soon. There are known problems (too many false positives), that have to be resolved. See https://github.com/languagetool-org/languagetool/issues/3306
