### ISSUE TITLE
[DE] Umstimmigkeit bei einer Regel (COMMA_IN_FRONT_RELATIVE_CLAUSE)

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#5059]
Moin liebes LanguageTool-Team

Die Ärztin sagte, dass Sandra immer **noch in der** geschlossenen befindet, weswegen es ihm nicht gestattet ist, sie zu besuchen.
LT: "Sollten Sie hier ein Komma einfügen?"

Die Ärztin sagte, dass sie immer **noch in der** geschlossenen befindet, weswegen es ihm nicht gestattet ist, sie zu besuchen.
LT: "Keine Fehler gefunden."

Grüße Dallun511

**Comment by danielnaber** [comment]
Da fehlt ein "sich" und "Geschlossenen" wird großgeschrieben, dann kommt kein Fehler mehr.

**Comment by MasterDallun511** [comment]
Danke dir für die schnelle Information.
