### ISSUE TITLE
[de] False Alarms DE_AGREEMENT

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#5074]
Unseren neuesten Änderungen in DE_AGREEMENT haben ein paar systematische Fehler aufgedeckt.

@AgnesKleinhans, bitte klassifiziere die im Spreadsheet gelisteten Sätze wie besprochen. Kannst du die FAs, die per `added.txt` und `compounds.txt` zu lösen sind, gleich selbst reparieren?

Danach werden die notwendigen APs und Änderungen in den Suggestions in Angriff genommen.

**Comment by tiff** [comment]
@udomai ich glaube, es gibt für deutsch keine multiwords.txt

**Comment by udomai** [comment]
Stimmt! Ich dachte eigentlich auch an compounds.txt. Ich hab's oben mal korrigiert.
