### ISSUE TITLE
[de] False Positive: Wanderstab/Wand

### ISSUE THREAD

**Issue by ChristianPervoelz** [languagetool-org/languagetool#5076]
**Beispiel**
Er lehnte seinen Wanderstab gegen die Wand.

**Problem**
LT meldet doppelte Verwendung des Wortes im Satz.

**Hinweis**
- Fehler tritt in LibreOffice auf, aber nicht in der Webprüfung
- Die meisten der optionalen Stilregeln sind eingeschaltet

**Comment by FredKruse** [comment]
Der Fehler ist beseitigt. Bitte ab morgen mit dem neusten Snapshot testen und das Issue schließen.

**Comment by ChristianPervoelz** [comment]
Geprüft mit 5.4-SNAPSHOT (2021-05-30 18:46:38.
