### ISSUE TITLE
Feature request: Show grade level of text

### ISSUE THREAD

**Issue by tjohnson314** [languagetool-org/languagetool#508]
I would appreciate it if the analyzer would show the grade level of my text.

Since the text is already parsed into sentences and individual words, this score should be easy to calculate: https://en.wikipedia.org/wiki/Automated_readability_index.

**Comment by danielnaber** [comment]
LT is focused on finding specific errors and providing specific messages. I don't think the user benefits from a general score that doesn't help them to improve their text. None of our clients has space in their UI to show such a value, either.
