### ISSUE TITLE
"spellcheck" not recognised as a verb

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#5085]
"Firefox tries to spellcheck non-English words, e.g. Chinese, when using en-GB"

It gives an error in "to spellcheck" saying it is not a verb, when it is.

**Comment by tiff** [comment]
Thanks. I'm taking care.

**Comment by tiff** [comment]
Fixed as part of https://github.com/languagetool-org/languagetool/commit/ea2d4d67ed6e085667dddeec04ade78cb9ea459f
