### ISSUE TITLE
Official Extensions for VSCode

### ISSUE THREAD

**Issue by phil-lgr** [languagetool-org/languagetool#5123]
I think since Adam Voss's extensions are not maintained anymore, it would make a lot of sense if you could make #1312 happens

The LanguageTool extensions almost looks like they are official https://marketplace.visualstudio.com/items?itemName=adamvoss.vscode-languagetool

As a potential customer, I would want to use my subscription in vscode

Thank you

**Comment by danielnaber** [comment]
Sorry, there are no plans for an official VS Code extension. But there are at least two extensions which seem to be maintained:

* https://github.com/davidlday/vscode-languagetool-linter
* https://github.com/valentjn/vscode-ltex
