### ISSUE TITLE
[de] "gerannt" vs. "geronnen", "<suggestion>" im Grammatikvorschlag

### ISSUE THREAD

**Issue by LauraWartschinski** [languagetool-org/languagetool#5128]
In diesem (leicht umgangsspachlich gedachten) Nebensatz, in dem das "ist" am Ende steht, wird die Grundform des Verbs falsch zugeordnet, und "\<suggestion\>" erscheint, ohne durch einen tatsächlich Vorschlag ersetzt zu werden.

![image](https://user-images.githubusercontent.com/38694039/120443303-ca2e5480-c386-11eb-9826-02c051c393a7.png)

(can someone add the Label "German", please?)

**Comment by udomai** [comment]
Hi @LauraWartschinski, danke fürs Reporten! Ich konnte inzwischen orten, wo dieser Bug entsteht, er wird zeitnah gefixt sein.

Für Bug-Reports sind wir jederzeit dankbar 🙂
