### ISSUE TITLE
[ru]PNN on end has huge amount of false positives

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#513]
They are rather simialr, like
как и он/она
как он/она
чем он/она
кто он/она
кто же он/она
or
`VB:.*:Masc:.* он`
`VB:.*:Fem:.* она`

[tatoeba-result-ru-PNN_ON_END.txt](https://github.com/languagetool-org/languagetool/files/438173/tatoeba-result-ru-PNN_ON_END.txt)

**Comment by yakovru** [comment]
https://www.languagetool.org/regression-tests/20160825/result_ru_20160825.html

**Comment by yakovru** [comment]
http://zorych.livejournal.com/690556.html

**Comment by kostyfisik** [comment]
For prep_on_end a good antipattern can be 
token regexp  [IVXLCM]*|[0-9]*
token в
token . 
as soon as it if valid to put XX в. to the end of the sentence.

another antipattern is
token case_sensitive С|В|К|У
token .
(e.g. В. Г. Белинский)

**Comment by kostyfisik** [comment]
For PNN_on_end -  I believe that LT should not recommend aginst widely used patterns found in tatoeba base. I think that is can possibly be found few examples in tatoeba, then PNN on end is really a style error, however, this should be  few cases, not hundreds.

**Comment by kostyfisik** [comment]
Few PPN on end left

Only these rules are enabled: [PNN_ON_END]
All spelling rules are disabled
Working on: ../tatoeba-sentences-rus.csv
Sentence limit: no limit
Error limit: 100

Title: <Tatoeba>
1.) Line 1, column 32, Rule ID: PNN_ON_END[1]
Message: Местоимение в конце предложения.
"Ты ужасный человек, - сказала она. - Ты никогда не помнишь моих слов".
                               ^^^^                                    

Title: <Tatoeba>
1.) Line 1, column 51, Rule ID: PNN_ON_END[1]
Message: Местоимение в конце предложения.
..."Домашнее задание я не выполнил! — весело крикнул он. — Некогда было".
                                                     ^^^                 

Title: <Tatoeba>
1.) Line 1, column 29, Rule ID: PNN_ON_END[1]
Message: Местоимение в конце предложения.
«Тьфу, пропасть!» — говорит она. — «И тот дурак, кто слушает людских всех врак: вс...
                            ^^^^                                                  

Title: <Tatoeba>
1.) Line 1, column 126, Rule ID: PNN_ON_END[1]
Message: Местоимение в конце предложения.
.....» — «А, так ты её знал... Хмм..» — пробормотала она. «И пока мы болтали с ней о всём на свете, о глупц...
                                                     ^^^^                                                  

Title: <Tatoeba>
1.) Line 1, column 26, Rule ID: PNN_ON_END[1]
Message: Местоимение в конце предложения.
"Бедняжка! — воскликнула она. — Что я могу сделать для вас?"
                         ^^^^                               

Title: <Tatoeba>
1.) Line 1, column 35, Rule ID: PNN_ON_END[1]
Message: Местоимение в конце предложения.
«Милая моя куколка! — воскликнула она. — Спасла ты меня от моей беды. Осталось мне тепер...
                                  ^^^^                                                  

Title: <Tatoeba>
1.) Line 1, column 88, Rule ID: PNN_ON_END[1]
Message: Местоимение в конце предложения.
...ой билет. "Но это же детский билет"! - настаивает он. "Теперь вы видите, сколько мне пришлось ждать пое...
                                                     ^^^                                                  
Russian: 7 total matches
Russian: ø0.00 rule matches per sentence

**Comment by yakovru** [comment]
I think the best solution is set default off this rule.

**Comment by kostyfisik** [comment]
Switching off the rule by default is not a solution.  It should be improved with an antipattern (or several antipatterns), the most obvious is to check the sentence for direct speech. I believe this can dramatically reduce the number of false positives and it can be again switch on by default.

**Comment by yakovru** [comment]
Fixed.
