### ISSUE TITLE
[ru] unexpected regression

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#514]
https://languagetool.org/regression-tests/20160826/result_ru_20160826.html

The error was correctly detected, however, it stopped.

Line 1, column 1, Rule ID: RU_COMPOUNDS
-Message: Эти слова должны быть написаны через дефис.
-Suggestion: Мало-помалу
-Мало помалу, бутоны на розовом кусте в моём саду начали раскр...

**Comment by kostyfisik** [comment]
Title: Союз Советских Социалистических Республик
-Line 1, column 26, Rule ID: RU_COMPOUNDS
-Message: Эти слова должны быть написаны через дефис.
-Suggestion: Вице-президент
-В состав комитета вошли: Вице президент СССР, Министр Обороны СССР, Министр МВД СССР, Пре...
-                         ^^^^^^^^^^^^^^                                                  
--Line 1, column 8, Rule ID: RU_COMPOUNDS
-Message: Эти слова должны быть написаны через дефис.
-Suggestion: Нью-Йорке
-Зима в Нью Йорке - хуйня по сравнению с ХМАО.
-       ^^^^^^^^^                             
-Title: <Tatoeba>
-Line 1, column 1, Rule ID: RU_COMPOUNDS
-Message: Эти слова должны быть написаны через дефис.
-Suggestion: Премьер-министр
-Премьер министр сегодня сделает заявление.
-^^^^^^^^^^^^^^^                           
-
 Title: Греция

Title: <Tatoeba>
-Line 1, column 1, Rule ID: RU_COMPOUNDS
-Message: Эти слова должны быть написаны через дефис.
-Suggestion: Когда-то
-Когда то в этом здании была больница.
-^^^^^^^^

**Comment by yakovru** [comment]
Partially fixed, regression:

>  Title: <Tatoeba>
-Line 1, column 8, Rule ID: RU_COMPOUNDS
-Message: Эти слова должны быть написаны через дефис.
-Suggestion: Нью-Йорке
-Зима в Нью Йорке - 
-       ^^^^^^^^^

**Comment by yakovru** [comment]
Fixed with GitHub issue #969
