### ISSUE TITLE
[de] DE_AGREEMENT: FPs caused by missing tags

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#5142]
DE_AGREEMENT schlägt manchmal wegen fehlender Tags an:

_Die Kosten werden durch **die höheren Erträge** kompensiert._

Dieser FA wird ausgelöst durch die Tatsache, dass für "höheren" im dictionary nur
```
höheren	hoch	ADJ:AKK:PLU:FEM:KOM:DEF
höheren	hoch	ADJ:AKK:PLU:NEU:KOM:DEF
```
aber nicht ADJ:AKK:PLU **:MAS:** KOM:DEF eingetragen ist.

Wir sollten das dictionary gezielt absuchen nach Adjektiven, für die im Plural nur für zwei Genera eine `DEF`-Form existiert.
```
\b(.*?)\t(.*?)\t(ADJ.*?PLU:)MAS(:.*?:DEF)
\b$1\t$2\t$3FEM$4
\b$1\t$2\t$3NEU$4
```
Alle Adjektive, für die es nicht alle 3 Einträge gibt, sind theoretisch verdächtig.

**Comment by danielnaber** [comment]
Quick hack: https://gist.github.com/danielnaber/737ecf678125eab5fd49fa9f8186983e -- result is that "groß", "gut", and "moldawisch" might also be affected (haven't checked). I have checked `GRU`, `KOM`, and `SUP`.

**Comment by udomai** [comment]
Missing `ADJ:AKK:PLU:MAS:KOM:DEF` confirmed for:

besseren
größeren

Missing `ADJ:AKK:PLU:MAS:GRU:DEF` and `ADJ:AKK:PLU:FEM:GRU:DEF` confirmed for:

moldawischen

**Comment by udomai** [comment]
This fixes the immediate problem. We might want to make sure no such things are lurking in the DAT or NOM…

**Comment by danielnaber** [comment]
> We might want to make sure no such things are lurking in the GEN, DAT, or NOM…

I've done that with my script now but it didn't find any cases.

**Comment by udomai** [comment]
Thank you 😃 then there doesn't seem to be a massive tagging problem.
