### ISSUE TITLE
[de] Punkt vor oder nach einem Wort

### ISSUE THREAD

**Issue by Mernissi** [languagetool-org/languagetool#5144]
**Beschreibung**:

Momentan gibt es für die deutsche Sprache ein Problem mit den Wörtern, die mit Punkt anfangen oder enden. z.B. ".bubu" oder "bubu." 

Gibt man z.B. ".bubu" an, dann wird nach der Rechtschreibprüfung das ganze Wort mit dem Punkt als falsch markiert. 

Das Problem betrifft auch die Wörter, die man selbst zum Wörterbuch hinzugefügt hat.

**Erwartet**:
Bei der Rechtschreibprüfung muss der Punkt ignoriert werden, sodass am Schluss nur das Wort "bubu" als falsch markiert wird.

**Hinweis**:
Nach Codeanalyse sieht das so aus als das Problem an dem Pattern liegt, die in GermanSpellerRule::init() verwendet wird, dort wird der Punkt ignoriert:
nonWordPattern = **((?![ß\-**.**])[^\p{L}]|(?<=[\d°])-|-(?=\d+))**

Könnten Sie bitte den Bug fixen ?

**Comment by danielnaber** [comment]
Scheint behoben zu sein (außer mit dem Punkt an Anfang, da scheint das aber eher ein Feature, den Punkt auch zu markieren).
