### ISSUE TITLE
[de] false alarm DE_DU_UPPER_LOWER

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#5149]
Wenn man "Du" (großgeschrieben) und "ihr" (kleingeschrieben) in einem Text verwendet, passiert das:

![Bildschirmfoto 2021-06-04 um 16 21 18](https://user-images.githubusercontent.com/37363/120816458-0a413300-c551-11eb-8bda-5ebc6cffb26b.png)

Ich glaube, dass man in einem Text duzt und siezt ist recht ungewöhnlich. Macht es Sinn ein Antipattern dafür anzulegen?

**Comment by danielnaber** [comment]
Es gibt "Ihr" ja auch in der "Du"-Form, als Plural: "Könnt Ihr Euch das vorstellen?". Aber trotzdem, das "ihr" macht wegen seiner Mehrdeutigkeit gerne Ärger. Ich nehme es mal raus und schau dann in die Statistiken.

**Comment by danielnaber** [comment]
`IHR_EUCH` kümmert sich jetzt um einen Spezialfall, den wir weiter finden (https://github.com/languagetool-org/languagetool/commit/13c228101a9fe88d96b7c4999e65e9d852ffe20b), die anderen Fälle mit "Ihr" sind jetzt aus.
