### ISSUE TITLE
[de] False positive: „War das Absicht?“

### ISSUE THREAD

**Issue by NicoWeio** [languagetool-org/languagetool#5154]
> War das Absicht?

resultiert in
_Evtl. keine Übereinstimmung von Kasus, Genus oder Numerus_.

Es gäbe aber durchaus sinnvolle Konstruktionen, in denen es sich sicher nicht um einen Fehler handelt, z.B.:

> Er versperrte mir den Weg. War das böse Absicht?

**Comment by danielnaber** [comment]
Danke, das wird mit dem nächsten Update behoben sein.
