### ISSUE TITLE
[en] should we accept "Sou"

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#5157]
> **Sou** might also help me with this kind of question.

We find no error here. Is there a good reason to accept "Sou" and "sou" at all? @MikeUnwalla

**Comment by MikeUnwalla** [comment]
@Daniel, we should accept 'sou': 
https://www.lexico.com/definition/sou
https://www.merriam-webster.com/dictionary/sou

**Comment by udomai** [comment]
This looks like an "ai" to me 🦥 – if the word is not preceded by a determiner (or similar), we could use an XML rule asking whether "you" was the intended word.
