### ISSUE TITLE
Correcting Emoji?

### ISSUE THREAD

**Issue by jcolag** [languagetool-org/languagetool#5159]
I recently wrote a blog post mentioning in passing that June is LGBT+ Pride Month, and figured that I'd throw in the rainbow flag emoji 🏳️‍🌈 for emphasis.  LanguageTool's CLI tool (running through a script, so *nothing* gets posted without it, anymore!) had *feelings* about this choice, apparently.  To make sure that the issue isn't more complicated than the emoji, I created a file that *only* has the emoji in it.  In both cases, the result is this.  And it looks like I'm on version 5.2.

```JSON
{
  "message": "Possible spelling mistake found.",
  "shortMessage": "Spelling mistake",
  "replacements": [
    {
      "value": "☀️"
    },
    {
      "value": "♂️"
    },
    {
      "value": "♻️"
    },
    {
      "value": "⚠️"
    },
    {
      "value": "✏️"
    },
    {
      "value": "✔️"
    },
    {
      "value": "❤️"
    },
    {
      "value": "➡️"
    }
  ],
  "offset": 0,
  "length": 3,
  "context": {
    "text": "🏳️‍🌈 ",
    "offset": 0,
    "length": 3
  },
  "sentence": "🏳️‍🌈",
  "type": {
    "typeName": "Other"
  },
  "rule": {
    "id": "MORFOLOGIK_RULE_EN_US",
    "description": "Possible spelling mistake",
    "issueType": "misspelling",
    "category": {
      "id": "TYPOS",
      "name": "Possible Typo"
    }
  },
  "ignoreForIncompleteSentence": false,
  "contextForSureMatch": 0
}
```

I'm not sure that a grammar checker should be in the business of checking emoji to begin with or that it's possible for an emoji to have a "Possible spelling mistake."  But even if we take all that as given, and even accepting that grammar checkers often produce "did you mean this clearly-wrong thing?" false positives, they seem like incoherent alternatives at best, and at worst reads like "instead of the LGBT community, perhaps you meant to refer to garbage?  Or to warn people?"  And not being able to remember another case where it objected to emoji, it *feels* like a deliberate choice, even though that's probably not really the case.

I assumed that it might have something to do with ZWJ sequences, but I can't reproduce behavior like this with any other emoji.

**Comment by jaumeortola** [comment]
I cannot reproduce this in the current version (5.4-SNAPSHOT). All emojis are ignored in the spelling rules for most languages.

**Comment by jcolag** [comment]
Good to hear.  That's what I'd expect, too.  Thanks!
