### ISSUE TITLE
Compile error on JDK 15

### ISSUE THREAD

**Issue by arysin** [languagetool-org/languagetool#5161]
Description	Path	Resource	Location	Type
Type mismatch: cannot convert from List<Object> to List<RuleMatch>	/languagetool-core/src/main/java/org/languagetool/rules	GRPCRule.java	line 268	Java Problem

**Comment by arysin** [comment]
Note: I see this in Eclipse 2021-06 compiler, the code seems to compile ok with maven on JDK 16. I wonder if it's an Eclipse's hotspot JRE problem.

**Comment by jaumeortola** [comment]
This change (thanks to @fabrichter) should fix the compiling error, https://github.com/languagetool-org/languagetool/commit/12048df38d4e55ba0f318f1e0cbe931de038979e
