### ISSUE TITLE
Incorrect Correction: "I and John work together" doesn't seem right

### ISSUE THREAD

**Issue by kerryland** [languagetool-org/languagetool#5168]
I'm using LanguageTool via Intellij Community Edition version 2021.1.2 and have just received this message:

When referring to yourself and somebody else, put their name first. Also check whether the nominative form I is required here. Incorrect: Me and John work together. Correct: I and John work together. Powered by LanguageTool

"I and John work together" doesn't seem right.

Hope this helps.

**Comment by udomai** [comment]
Hi @kerryland! Thanks for your feedback! Where is it the correction "I and John work together" is suggested? This would be a bug – as the message states, the other person's name has to be put first.

I went ahead and tested that sentence in the editor. "**Me and John** work together." is being corrected to "**John and I** work together.", which is the intended correction by the rule `CONFUSION_OF_ME_I`.

If you can reproduce this, could you send me a screenshot, maybe?

Also, feedback on LT is most welcome anytime! 🙂

**Comment by kerryland** [comment]
I can reproduce it in Intellij Community Edition version 2021.1.2 with the text "Me and the guys had done a pretty good job of spreading the word", 

![image](https://user-images.githubusercontent.com/398113/121281014-57dfe600-c92b-11eb-861f-5df3f2a97734.png)

but I get the same result with "Me and John work together."

![image](https://user-images.githubusercontent.com/398113/121281332-d9377880-c92b-11eb-8452-bb4e79ba2bdb.png)

I didn't look too closely at LanguageTool when I first raised this bug, and assumed it was a plugin you provided to them, but maybe they have mangled it themselves?

![image](https://user-images.githubusercontent.com/398113/121281451-0421cc80-c92c-11eb-981e-5592ba550d0e.png)

**Comment by udomai** [comment]
@kerryland, thank you for bringing that to our attention, and for clarifying!

This appears to be the Grazie plugin. I can reproduce it with an .md file in IntelliJ. Sure isn't ideal that worse suggestions than what LT currently does appear as "powered by LanguageTool"…

![image](https://user-images.githubusercontent.com/67792088/121308250-1df9ea00-c901-11eb-960d-ea7bf76c43cc.png)

**Comment by danielnaber** [comment]
The Grazie add-on works offline, i.e. they don't always use the very latest version. The add-on gets updated regularly, and I'll make sure they use the latest version. They do offer regular updates (https://plugins.jetbrains.com/plugin/12175-grazie/versions/stable).

**Comment by danielnaber** [comment]
Feedback form IntelliJ:

> The last released version of Grazie uses LT 5.2. We've switched to 5.3 in the current 2021.2 EAP, and I hope we will also switch to 5.4 before the release.
