### ISSUE TITLE
[DE] LT-Fehlermeldung Juni 2021

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#5172]
Moin liebes LanguageTool-Team

![grafik](https://user-images.githubusercontent.com/78316155/121148657-41119480-c842-11eb-9325-5b25ae0e1f05.png)

Ich kann leider nicht sagen, wie es zu dieser Fehlermeldung kam, weil ich diese erst bemerkt habe, nachdem ich alle Dokumente geschlossen hatte.

Grüße Dallun511

**Comment by MasterDallun511** [comment]
![grafik](https://user-images.githubusercontent.com/78316155/121673419-255ff580-cab1-11eb-97e6-faf8d022c5a7.png)

**Comment by FredKruse** [comment]
Der Fehler ist gelöst. Bitte mit dem morgigen snapshot testen und den issue schließen.
