### ISSUE TITLE
Nightly crashed on LibreOffice - 2021-06-08

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#5174]
Hello!

![LT_crash_nightly_202010608](https://user-images.githubusercontent.com/5192600/121279805-13bdf880-c8cd-11eb-8c68-613b6aebb30a.png)

Thanks!

**Comment by dpelle** [comment]
The ticket description is too short.
How is it reproducible? 
What was the language?
If you have a document that triggers the crash, maybe you can narrow it down to find a sentence that triggers it?

**Comment by marcoagpinto** [comment]
Ahhhh... sorry...

The document was my thesis in Portuguese (Language → All text → Portuguese).

I was just scrolling it down using the mouse wheel from bottom to end.

And it was LibreOffice:
Version: 7.1.3.2 (x64) / LibreOffice Community
Build ID: 47f78053abe362b9384784d31a6e56f8511eb1c1
CPU threads: 12; OS: Windows 10.0 Build 19043; UI render: Skia/Vulkan; VCL: win
Locale: en-GB (en_GB); UI: en-GB
Calc: CL

Thanks!

**Comment by dpelle** [comment]
@marcoagpinto wrote:

> The document was my thesis in Portuguese (Language → All text → Portuguese).
> I was just scrolling it down using the mouse wheel from bottom to end.

Can you reproduce it all the time?
If yes, you may be able to trim the document to a minimalistic part that trigger the crash, ideally a single sentence.
Otherwise it may be difficult to look at.

In the stack, I also see the function name `getSentenceErrosAsList` in SingleCheck.java which appears to be misspelled but that's unrelated to the crash, i.e.:

getSentenceErrosAsList → getSentenceErrorsAsList

**Comment by marcoagpinto** [comment]
@dpelle 

The thesis is ~440 pages long.

I was scrolling it down and can't remember where the crash happened.

I will try to revise it again with a nightly on Friday.

**Comment by FredKruse** [comment]
The bug is solved. Please test it with the nightly tomorrow and close the issue

**Comment by marcoagpinto** [comment]
@FredKruse 

I have installed the nightly minutes ago.

I got another crash while scrolling down my thesis:
![lt_crash_20210617](https://user-images.githubusercontent.com/5192600/122328051-d689e400-cf26-11eb-999b-c9aea04fcccc.png)

**Comment by marcoagpinto** [comment]
Several pop-ups:
![lt_crash_20210617b](https://user-images.githubusercontent.com/5192600/122328638-ee159c80-cf27-11eb-8ef4-019c63e4cfd9.png)

**Comment by FredKruse** [comment]
The issue should be solved. Please test it tomorrow with nightly.

**Comment by marcoagpinto** [comment]
It seems to be fixed.

Thanks!
