### ISSUE TITLE
[en] dublicate duplicate

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#518]
This should be corrected with LT. The first one is for sure wrong (and marked with spellchecker). However, is can be a bit hard for a non-native speaker to locate the error, as soon as "double" has "b", not "p".

**Comment by kostyfisik** [comment]
Hmm... Or it is a dictionary word? http://www.eudict.com/?lang=engger&word=dublicate,%20duplicate

**Comment by MikeUnwalla** [comment]
I searched COCA and BNC using corpus.byu.edu. The word 'dublicate' was not in the results. I looked in my paper copy of Shorter Oxford English Dictionary, and I did not find the word.

"... can be a bit hard for a non-native speaker to locate the error, as soon as "double" has "b", not "p"."
Yes, but what can a new rule do to help someone to locate the error?

LT finds the spelling error. Thus, I think that there is nothing more for LT to correct. (I am closing this issue, but feel free to re-open.)
