### ISSUE TITLE
[en] Invalid POS (with regexp inside: NN.*|JJ.*) in an English sentence

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#5193]
The sentence is "there was slightly decrease for 20 years"

![image](https://user-images.githubusercontent.com/122009/121856747-241f0a80-ccf5-11eb-8a6b-ac92f2ee20d9.png)

**Comment by jaumeortola** [comment]
This is related to the disambiguation rule EX_ARE_NN[2]
```
 <rule>
            <pattern>
                <token postag="EX"/>
                <token regexp="yes">is|was|are|were</token>
                <marker>
                    <token postag="RB"><exception postag="CC"/></token>
                </marker>
                <and>
                    <token postag="VB"/>
                    <token postag_regexp="yes" postag="NN.*|JJ.*"/>
                </and>
            </pattern>
            <disambig><match no="3" postag_regexp="yes" postag="NN.*|JJ.*"/></disambig>
        </rule>
```
Probably we need to change the disambiguation action: 
`<disambig action="filter" postag="RB"/>`

Can you confirm it? @udomai @MikeUnwalla

**Comment by udomai** [comment]
I'd say so: The sentence is wrong, and correcting it is easier if the error is tagged accurately. The question is: Would there be any adverse effects on the tagging of correct sentences?

**Comment by MikeUnwalla** [comment]
Counter example that shows we cannot assume that RB is always correct ('hot' is an adjective, not an adverb):

There are **hot** samples on the table.

**Comment by udomai** [comment]
"Hot" bears the `RB` tag unduly, methinks. If this happens only with `JJ` that are incorrectly (?) tagged as `RB`, the problem is the tag, not the disambiguation rule. But it feels like I'm on thin ice with that hypothesis 🙂

**Comment by MikeUnwalla** [comment]
Hot as an adverb is rare, but possible: 
https://www.merriam-webster.com/dictionary/hot
https://www.collinsdictionary.com/dictionary/english/hot (item 12)

Better counter example with 'back', which is a common adverb, but here, incorrectly tagged as an adverb:

There are **back** issues of the magazine on the shelf.

**Comment by udomai** [comment]
I like the "back" example, thank you! What is the best solution then? Adding exceptions? Remove the `VB` tag?

_Linguistic comment about what MW has to say: "hot" is not a real adverb in "The sun is shining hot". The word "hot" specifies the "sun", and the tie with the predicate "is shining" is ontological (the sun was hot and shone). Similar cases with "dead" and "drunk": "He dropped dead.", "He went to bed drunk."_

**Comment by MikeUnwalla** [comment]
I think that the safe option is to remove the VB tag.

**Comment by jaumeortola** [comment]
I don't fully understand the aim of the rule. Is it to remove the RB tag?
Anyway, it is not a good practice to add/filter with postags (here `NN.*|JJ.*`) that are not in the original word (slightly/RB). This has to be fixed.

**Comment by MikeUnwalla** [comment]
@jaumeortola , @udomai, ignore my comment about removing the VP tag. It was a stupid thing to write (I was thinking about the terms in the `and`, not the marked term.

I haven't got a clue about the purpose of the rule.

**Comment by donnerpeter** [comment]
I'd expect there to be `RB` tag, maybe others. But definitely not regexps as tags.

**Comment by MikeUnwalla** [comment]
The rulegroup name shows that NN/VB is disambiguated as NN. Thus, I wonder whether the marker is in the wrong position. Refer to the marker position for rule 1, which is around the `and`.

With many rules, we have the problem that there are no or very few examples that show what is touched and what is not touched.

**Comment by jaumeortola** [comment]
The `<marker>` around the `<and>` makes perfect sense. I would do that.

**Comment by MikeUnwalla** [comment]
Interesting observation number 1 (oh, yes, more coming). 
a) When there is a mismatch between the marker and the match number, the marker takes precedence.
b) There are no checks to find the marker/match number mismatch.

![image](https://user-images.githubusercontent.com/5816160/121906319-e89b3500-cd22-11eb-8e28-8552183f2e75.png)

**Comment by MikeUnwalla** [comment]
Interesting observation number 2:
Remove the marker. The first token is touched. @udomai, can you confirm that this happens for you too? (It's not just me, is it?)

![image](https://user-images.githubusercontent.com/5816160/121907667-2d739b80-cd24-11eb-8fdd-2660ea898e67.png)

**Comment by MikeUnwalla** [comment]
Other disambiguation rules use marker only, and they seem to work fine. What is going on here?

**Comment by jaumeortola** [comment]
I always use `<marker>` and `<disam action="filter/add/remove..." pos="...">`, never `<match no="">`. In fact, I didn't remember the `<match>` option existed. It should be considered "obsolete".  There are 24 English disambiguation rules that still use `<disambig><match no="">`. 

The solution for EX_ARE_NN[2] seems to be: 
```
        <rule>
            <pattern>
                <token postag="EX"/>
                <token regexp="yes">is|was|are|were</token>
                <token postag="RB"><exception postag="CC"/></token>
                <marker>
                    <and>
                        <token postag="VB"/>
                        <token postag_regexp="yes" postag="NN.*|JJ.*"/>
                    </and>
                </marker>
            </pattern>
            <disambig action="filter" pos="NN.*|JJ.*"/>
        </rule>
```

**Comment by MikeUnwalla** [comment]
Thanks @jaumeortola, I will have another go.

@udomai, @jaumeortola, the examples in https://dev.languagetool.org/developing-a-disambiguator#filtering-tags use`<disambig><match no="1"...` Can you please correct the documentation?
