### ISSUE TITLE
[en] False positive its->it's suggestion

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#5207]
`An inner class and its containing class are compiled.`

**Comment by rillig** [comment]
Related example, [also from a software documentation](https://github.com/rillig/gobco/blob/190a60687ffbea2442e50de263e72b107b036bf0/main.go#L521):

> If it is inside GOPATH, it or its containing directory is copied, otherwise the whole Go module will be copied.

LanguageTool should know that the word `containing` is an adjective in these sentences. If it were a verb, the following noun should be either in plural form or have an article, as in:

> An inner class, and it's containing lots of methods.
>
> An inner class, and it's containing another inner class itself.

**Comment by tiff** [comment]
Thanks. Fixed by yesterday's changes

**Comment by rillig** [comment]
The relevant commit is 36a9db9ae061f7f8d33493b6f331e1432bf9f6d0.
