### ISSUE TITLE
[el] Specific-case-rule

### ISSUE THREAD

**Issue by Nikos-Antonopoulos** [languagetool-org/languagetool#5227]
A Specific case rule for Greek could be quite useful.

**Comment by Nikos-Antonopoulos** [comment]
@Giorgossideris and I will create this!!

**Comment by danielnaber** [comment]
I forgot about this: could you make sure the rule doesn't load the list each time? Depending on the LT configuration, a rule constructor might be called once per check. The constructor should thus be lightweight and not take a long time to initialize.

**Comment by giorgossideris** [comment]
@danielnaber I'll open a new pull request soon to fix that, I didn't think of that and thank you for mentioning it.
