### ISSUE TITLE
[ru] wrong disambig

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#523]
Глухой  is still an ADJ

Издает при постукиваниии глухой звук

Disambiguator log: 
NOUN_P[1]: глухой[глухой/ADJ:Fem:D,глухой/ADJ:Fem:P,глухой/ADJ:Fem:R,глухой/ADJ:Fem:T,глухой/ADJ:Masc:Nom,глухой/ADJ:Masc:V,глухой/NN:Masc:Sin:Nom,глухая/NN:Fem:Sin:D,глухая/NN:Fem:Sin:P,глухая/NN:Fem:Sin:R,глухая/NN:Fem:Sin:T] -> глухой[глухая/NN:Fem:Sin:P]

глухой	глухая  NN:Fem:Sin:P

**Comment by yakovru** [comment]
It may be family (Глухой Иван Иванович, Глухая Светлана Владимировна), but f
глухая глухой  NN:Fem:Sin:P  or  глухая глухой  NNF:Fem:Sin:P (mistake in dictionary).
But for this expression  "Издает при постукивании глухой звук" need improve disambig.

**Comment by yakovru** [comment]
Fixed.
