### ISSUE TITLE
[pt-br] user feedback "Esfolamento"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#5238]
> ''Esfolamento'' o corretor aponta um erro, quando obviamente está escrito de forma correta. O errado ele aponta como certo: ''esfrolamento''.

**Comment by marcoagpinto** [comment]
I have just added "esfolamento":
https://github.com/languagetool-org/languagetool/commit/e32ae6d8e34d27a17eeb0e5dd04b018ce6a6169a

https://github.com/languagetool-org/languagetool/commit/261bb37428d57dd0c1b3afb680adc2c59305b865

The word "esfrolamento" is in the pt-BR dictionary, which isn't maintained by me.
