### ISSUE TITLE
[fr] improve spelling suggestions for split words with apostrophe or space

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#5241]
By @udomai 

> Note to self: evaluate different cases – do we get all of them?
> 
> Example with no good correction: Je crois que personne ne pouvait sattendre à ça. (ideal correction: s'attendre; actual suggestion: attendre, s attendre)
> 
> → we should not suggest splitting off a single letter, except a, y

**Comment by udomai** [comment]
Cool! Thanks :)

**Comment by jaumeortola** [comment]
There are some changes in spelling suggestions. Check if they are improvement or regressions: https://internal1.languagetool.org/regression-tests/via-http/2021-06-23/fr/result_java_FR_SPELLING_RULE.html

**Comment by udomai** [comment]
At first glance, I see a few suggestions that are worse now: `àdomicile` now only gets `domicile`. Before, it also got `à domicile`. Same goes for `àmaintenir`, `àseulement` (cases of missing space)

**Comment by jaumeortola** [comment]
Those are fixed here: https://github.com/languagetool-org/languagetool/commit/ef3f3db0b5d8980887ed1ba1fda2d4a669e624dd

Check if we miss some combination pronoun+verb. They are defined here: https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/MorfologikFrenchSpellerRule.java
