### ISSUE TITLE
Crash LanguageTool standalone ("pt-PO"?)

### ISSUE THREAD

**Issue by Sukups** [languagetool-org/languagetool#5244]
![Captura](https://user-images.githubusercontent.com/81076421/123147045-de81e080-d45e-11eb-87c3-e64b23dc339c.PNG)
Hi ! Recently, LanguageTool crashed for some reason, I didn't mess with the software files, and I tried to re-download the software from the Internet, but the result is still the same.

**Comment by danielnaber** [comment]
Deleting the configuration file `.languagetool.cfg` might help (its location differs, so you'll need to search for it).

**Comment by Sukups** [comment]
I don't have that file, maybe I'm using the Java version because I usually open LanguageTool with languagetool-server.jar.

**Comment by Sukups** [comment]
Wait, I found it :) Thank you so much again @danielnaber for your help !
