### ISSUE TITLE
[fr] media/média

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#5247]
We have "media" in the dictionary as a plural of "medium" (`media[medium/N m p]`), but it seems wrong, or it could be confused with `média N m s / médias N m p`. 

@Rebecca-auque Please, adjust the dictionary or create some rule if necessary.

**Comment by Rebecca-auque** [comment]
Indeed, it is weird. It seems to be from latin but it is not commonly used in French so I just removed it from the dictionary.

**Comment by jaumeortola** [comment]
Thanks. It seems that removing the POS tag is not enough to trigger the spelling rule, so I have created a specific rule. The rule will allow introducing exceptions.

**Comment by Rebecca-auque** [comment]
How did you know that removing the postag was not enough for the spelling rule and why was it not enough? If the exceptions are already tagged there is no need to put exceptions in the new rule, is there?

**Comment by jaumeortola** [comment]
I tested it. With the current configuration, we would need to 1) remove the tag in remove.txt, and 2) add the word to a file named `fr/hunspell/prohibit.txt` (which doesn't exist now).
