### ISSUE TITLE
[fr] subject ET subject verb -> wrong number

### ISSUE THREAD

**Issue by philippehenri** [languagetool-org/languagetool#5248]
Example:

Le vélo et la voiture est des bons moyens de transport. --> est -> SONT des... (vélo ET voiture = plural)

Les carottes et les fruits est bon pour la santé --> SONT bonS pour... (3ps -> 3pp)

La poule et le poulet fait trop de bruit. -> FONT trop...

same problem with adj or adv of course: La vilaine poule et le très méchant poulet fait trop de bruit. -> FONT trop...

I also note that "Les carottes est bon pour la santé" get a suggestion "bonne" and not "bonnes" (carrotteS is plural)

**Comment by jaumeortola** [comment]
Thank you. The wrong number issue is resolved. The issue about the adjectives is here: improve rule ETRE_VPPA_OU_ADJ
