### ISSUE TITLE
[en] A/An false positive before "hours"

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#5260]
`We have an "hours" value of 42, when...`, `We have an hours value of 42, when...`

LanguageTool is suggesting "a" here, which seems quite irrelevant. I'd understand it suggesting `the` or no article in the second case, and the first one seems OK to me (in programming-related texts).

**Comment by donnerpeter** [comment]
From https://youtrack.jetbrains.com/issue/IDEA-272375

**Comment by udomai** [comment]
Thanks for spotting this, @donnerpeter!

**Comment by donnerpeter** [comment]
Ready to close?

**Comment by udomai** [comment]
Yes, it works fine now 🙂
