### ISSUE TITLE
rule type for 'hints'

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#5262]
In Dutch, neither 'rechtelijk', nor 'rechtelijk' are wrong. Since the first refers to a judge, the second to the law itself, there is no context difference.
So I want to make a rule that just hints by making a remark on the words, and suggesting the alternatives in frequency order.

There are many cases like these. 
Rules that suggest alternatives for both are 'circular rules', thus rejected.

How does one make a good rule for cases like this?

**Comment by danielnaber** [comment]
> Rules that suggest alternatives for both are 'circular rules', thus rejected.

Do you mean the tests fail? Could you post an example rule?

**Comment by baarsrj** [comment]
`		<rulegroup id="RECHTERLIJK" name="Rechte(r)lijk">
			<rule>
				<antipattern><token>rechterlijke</token><token regexp="yes">macht|orde</token></antipattern>
				<pattern>
					<token regexp="yes">.*rechterlijke?</token>
				</pattern>
				<message>Let op: gebruik rechterlijk als het op de rechter slaat, rechtelijk als het op de wet slaat.</message>
				<suggestion><match no="1" regexp_match="rechterlijk" regexp_replace="rechtelijk"/></suggestion>
				<example correction="strafrechtelijke">Het is een <marker>strafrechterlijke</marker> kwestie.</example>
			</rule>
			<rule>
				<pattern>
					<token regexp="yes">.*rechtelijke?</token>
				</pattern>
				<message>Let op: gebruik rechterlijk als het op de rechter slaat, rechtelijk als het op de wet slaat.</message>
				<suggestion><match no="1" regexp_match="rechtelijk" regexp_replace="rechterlijk"/></suggestion>
				<example correction="strafrechterlijke">Het is een <marker>strafrechtelijke</marker> kwestie.</example>
			</rule>
		</rulegroup>
`

**Comment by danielnaber** [comment]
> Rules that suggest alternatives for both are 'circular rules', thus rejected

What message do you get? I don't get a test failure with the rule you posted.

**Comment by baarsrj** [comment]
There is no hard error. But there is no 'incorrect' either. What I mean there can be text hints, that are no correction either way, just a risk something could be wrong. Which is something different from a correction. But I will forget about it. If I am the only one seeing the difference...
