### ISSUE TITLE
[en] Oxford spelling "raising" suggests itself?

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#5266]
![Screenshot 2021-06-28 at 19-28-11 (10) Home Twitter](https://user-images.githubusercontent.com/857004/123748745-e73a4280-d8b4-11eb-989e-c8c902409469.png)

**Comment by MikeUnwalla** [comment]
@danielnaber, there is something strange with 'raised' and 'raising'. This is before I added the exception for 'raising':
![image](https://user-images.githubusercontent.com/5816160/123761254-8b25ed00-d8b9-11eb-9f97-9d69b86b9e2a.png)
