### ISSUE TITLE
[en] ignore footnotes in spell checker

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#5267]
user feedback:
> 'statements¹' and 'statements¹.' is corrected to 'statements'

Maybe related to:
https://github.com/languagetool-org/languagetool/issues/2590

@jaumeortola any idea how to solve this?

**Comment by jaumeortola** [comment]
What is the character that LanguageTool sees? If it is `\u00B9`, we can add these characters to the word tokenizer.

**Comment by jaumeortola** [comment]
Fixed here for the superscript characters (not for superscript formatting): https://github.com/languagetool-org/languagetool/commit/b196b7ef3ce7012bffa5615c91ff5d2da0c546de

**Comment by jaumeortola** [comment]
This is fixed now. The only relevant change is that now units like `km²` have two tokens instead of one. We can live with it, or we can change the tokenizers to keep them in one token.

**Comment by tiff** [comment]
I think it's fine. Thanks!
