### ISSUE TITLE
Issues with "picky"

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#5275]
Hello!

There seems to be an issue with "picky" mode.

The nightlies diffs don't show results for them:

`    <rulegroup id='FAZER_EFETUAR_REALIZAR_CONDUZIR_CONCRETIZAR_ELABORAR' name="Fazer → efetuar/realizar/conduzir/concretizar/elaborar" type="style" tags="picky" default="temp_off">`

The same happens with the Wikipedia tool... it shows zero hits.

**Comment by danielnaber** [comment]
Please let me know how exactly you tested with the online editor and whether it works with the `default="temp_off"` removed.

**Comment by marcoagpinto** [comment]
Ahhhh... sorry...

I had a picky rule and used the Wikipedia tool with the command:
`java -Dfile.encoding=UTF-8 -Xmx4500M -jar languagetool-wikipedia.jar check-data -l pt-PT -r RULE_HERE -f ptwiki-20121230-pages-articles.xml -f tatoeba-pt.txt --max-sentences 200000 --context-size 100 >before.txt`

It showed no results.

Also with "temp_off" the Wikipedia tool display the rule twice.

Also, the Stand-alone tool doesn't give hits for picky rules.

And the nightly has the same issue, not hits for picky rules.

**Comment by maphjo** [comment]
closing as this seems to be resolved.
