### ISSUE TITLE
[DE] Fehlende Funktionen

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#5278]
Moin liebes LanguageTool-Team,

mir ist aufgefallen, dass in den neueren Versionen Funktionen fehlen, die in den älteren vorhanden sind.
Gibt es dafür einen Grund oder ist das ein Bug?

Als Beispiel ein paar Sreenshots.
LT: LanguageTool-20210627-snapshot

![LanguageTool-20210627-snapshot](https://user-images.githubusercontent.com/78316155/123997143-5b1d3d80-d9d0-11eb-9825-238aa62fc97e.JPG)

Hier fehlen die weiteren Optionen für die Stillregeln, um anzupassen ab viele Wörter hingewiesen wird, dass ein Absatz zu lang ist oder überhaupt die Funktion, die Regeln komplett abzuschalten. Zudem fehlt eine ganze Kategorie, was wirklich schade ist.

LT: 5.2.3
![grafik](https://user-images.githubusercontent.com/78316155/123997226-74be8500-d9d0-11eb-9bbc-eab463a5ff7b.png)
![grafik(1)](https://user-images.githubusercontent.com/78316155/123997231-75efb200-d9d0-11eb-885d-bfd8b512f961.png)
In der Version 5.2.3 ist alles enthalten und lässt sich ohne Probleme auf LT 7,1 installieren.

Ich würde mich diesbezüglich auf eine Antwort freuen.

Grüße Dallun511

**Comment by FredKruse** [comment]
Moin Dallun,
die Möglichkeit der Einstellungen ist weiterhin vorhanden. Sie sind jetzt in dem Sinn erweitert, dass für jede Regel eine eigene Farbe und ein eigener Stil für die Unterstreichung vergeben werden kann. Wenn du eine Regel auswählst (also auf sie klickst), werden in einem Bereich unten im Fenster die möglichen Einstellungen angezeigt. Das sind bei allen Regeln die Möglichkeiten der Einstellungen zu Farbe und Stil, sowie zu speziellen Regeln die weiteren Einstellungen.
Beispiel:
![LT_Optionen](https://user-images.githubusercontent.com/23344265/127769389-a221fa64-6fc7-475f-a68c-8c8bb368f4c8.png)
