### ISSUE TITLE
Spelling issue for Dutch

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#5287]
I never noticed this behaviour before:
![afbeelding](https://user-images.githubusercontent.com/8479998/124345182-b66d4c80-dbd7-11eb-89b6-cc6e7cc20110.png)

Apparently, the word is seen as 1 token, so it cannot be Morfologik. It could be one of the 'ignore spelling' rules in disambiguation. 
I assume this bug is caused by the well-intended custom code dealing with the optional hyphen in a word, but marking a word as 'ignore spelling' when the word without - is not in dictionary.

**Comment by jaumeortola** [comment]
Please, specify what is wrong in the current behavior, and what is the desired result. I don't understand now

**Comment by baarsrj** [comment]
I managed to solve it myself. I am not much of a programmer, but sometime, I manage to shuffle existing code around.
