### ISSUE TITLE
[fr] adj/number before noun -> wrong number

### ISSUE THREAD

**Issue by philippehenri** [languagetool-org/languagetool#5294]
Les dix première maison sont jolies -> Les dix premièreS maisonS sont jolies.
Les dix maison est jolies. -> Les dix maisonS SONT jolies.
Les premières maison est jolies. -> Les premières maisonS SONT jolies.
Les premières maison est jolie. -> Les premières maisonS SONT jolieS.
Les 10 maisons est jolies.  -> Les 10 maisons SONT jolies.
Les 10 maisons est jolie.  -> Les 10 maisons SONT jolieS.

Les deux enfant jouent dans le jardin.->Les deux enfantS jouent dans le jardin.
Les deux enfant joue dans le jardin.-> Les deux enfantS joueNT dans le jardin.

**Comment by jaumeortola** [comment]
Remaining FN for nominal groups: 
- [ ] Les dix premières maison
- [ ] Les premières maison 

Remaining FN for subject-verb agreement: 
- [ ] Les 10 maisons est jolies.
- [ ] Les premières maisons est jolie. [We prefer not to detect this because it will create many other FPs]
- [ ] Les 10 maisons est jolie. [We prefer not to detect this because it will create many other FPs]

**Comment by philippehenri** [comment]
Hi Jaume

Can you give an example of why this would cause false positive please? I am not sure to understand. 

ps: and strange, it detects correctly the error for  "Les jolies maison est bleue." (-> Les jolies maisons SONT bleueS), or "Les grandes maison est bleue."

but think everything is ok for "Les premières maison est bleue." (same for: secondes, troisièmes,... anything related to a number in fact...)

**Comment by philippehenri** [comment]
yep, seems LT does not like dernières, premières , ... ex:
 "Il a tiré ses dernières cartouche." (not detected: -> cartoucheS )
"Les secondes année d'école." -> "annéeS"
...

**Comment by jaumeortola** [comment]
> Can you give an example of why this would cause false positive please? I am not sure to understand.

With the verbs être, sembler..., there are different agreement patterns. The subject can be before or after the verb (See examples here: https://forum.wordreference.com/threads/fr-singulier-est-sont-pluriel-accord-du-verbe.2592246/). Thinking again about these examples, it seems that when the next word is an adjective (`Les maisons est jolie`), we can detect the subject-verb error safely. I will do it. 
 
> but think everything is ok for "Les premières maison est bleue." (same for: secondes, troisièmes,... anything related to a number in fact...)
There was a problem disambiguating some words as nouns or adjectives (premier, dernier, troisième...). 

I think all your examples are fixed now.
