### ISSUE TITLE
[el] Grammatical error in GreekWordRepeatBeginningRule message

### ISSUE THREAD

**Issue by giorgossideris** [languagetool-org/languagetool#5295]
In the message that pops up when the GreekWordRepeatBeginningRule is applied,"ξεκινάμε" (first plural) should be "ξεκινάνε" (third plural).

![image](https://user-images.githubusercontent.com/56915448/124397525-ecfeb080-dd18-11eb-8659-b58f2e06a00d.png)

Where can I find and change this message?

**Comment by danielnaber** [comment]
It's at https://webtranslateit.com/en/projects/21275-LT-Core/locales/en..el/strings?current_id=19578696&utf8=%E2%9C%93&object=&s=%CE%BE%CE%B5%CE%BA%CE%B9%CE%BD%CE%AC%CE%BC%CE%B5&ignore_case=on - I have made that change now, thanks.

**Comment by giorgossideris** [comment]
Thanks, the case when there are successive sentences that start with the same adverb is fixed, but the case of three sentences that start with the same word (non adverb) still has the problem.

**Comment by danielnaber** [comment]
Is it okay now? "Συνεχόμενες προτάσεις που ξεκινάμε με την ίδια λέξη" is also okay or does it need to be changed, too?

**Comment by giorgossideris** [comment]
No, it should be "Συνεχόμενες προτάσεις που ξεκινάνε με την ίδια λέξη".

Also, in this case:

![image](https://user-images.githubusercontent.com/56915448/124459876-532a1880-dd97-11eb-8c7a-0449bd2ddf7f.png)

It should be "Τρεις συνεχόμενες προτάσεις ξεκινάνε με την ίδια λέξη"

**Comment by giorgossideris** [comment]
Generally, in all the cases at the particular rule "ξεκινάμε" should be "ξεκινάνε".

**Comment by danielnaber** [comment]
Could you send me your email, I'd like to invite you to webstranslateit, so you can do those changes yourself.

**Comment by giorgossideris** [comment]
Of course, it is: sideris.geo.s@gmail.com

**Comment by danielnaber** [comment]
You should have received an invitation now. Making changes on that website doesn't mean they end up in LT's github immediately. There's a process that runs about once a week that fetches the latest translations.

**Comment by giorgossideris** [comment]
Great, I made the change and I couldn't fine "ξεκινάμε" used anywhere else. So now it's good.
