### ISSUE TITLE
 Elapsed time for results in the GUI is much longer than the processing time

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#530]
In the GUI, when there are many errors in the text, the elapsed time to see the results can be many minutes, although the processing time is only a few seconds.

![elapsed-time-is-non-linear](https://cloud.githubusercontent.com/assets/5816160/18225681/2ad0108c-71f0-11e6-9d42-6ebc7e564188.png)

Daniel wrote, "so it's indeed just the JTextPane being slow" ([http://www.mail-archive.com/languagetool-devel@lists.sourceforge.net/msg05833.html]).

@pminos, if possible, please could you correct this problem? Thanks.

**Comment by pminos** [comment]
@MikeUnwalla the latest commit should help speed things up a bit. Can you verify it?

**Comment by MikeUnwalla** [comment]
@pminos, wonderful, thank you. The elapsed time for the set of test sentences was a little less than 16 seconds (previously was 320 seconds). Potential problems found = 3760, total words = 23,360.
