### ISSUE TITLE
[fr] improve spelling suggestions: Il *saperçu de son erreur

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#5307]
(Spotted by @Rebecca-auque) 
The speller gives suggestions for wrong split words that are not relevant. 
![imatge](https://user-images.githubusercontent.com/4289501/124585510-a5ca0a00-de55-11eb-83d9-1aa6b45be02c.png)

Expected suggestions: `Il s'aperçoit`, `Il s'est aperçu`. 

We would need a rule similar to JE_VEBE but for other personal pronouns (and it should consider the missing apostrophe in `s'`).

**Comment by jaumeortola** [comment]
The rules  IL_VERBE and ILS_VERBE provide, generally, better suggestions. But sometimes the speller suggestions are better. A full solution would be to include the logic of IL_VERBE, ILS_VERBE, JE_VERBE... inside the Morfologik speller rule.

**Comment by Rebecca-auque** [comment]
Separate two words: 
Il vousvoit d'un mauvais œil.
Il s'agitdonc de savoir utiliser au mieux les tableaux 

Weird prefixes
... remarqué qu'elle désaturait jusqu'à 40 
... il ressonda l'environ et apperçu la petite plainte. 

Rules to improve:
... comment il ny comprend pas à angers -> improve rule for n'y
l n'ya qu'une partie du cosmos -> improve rule YA

**Comment by Rebecca-auque** [comment]
Comment on peut les decodés puis qu'ils sont déjà aléatoires ? ->décoder
Ils sont decodés.->décodés.

**Comment by Rebecca-auque** [comment]
As well as the  missing space for inflected pronouns (me, te, se), could it integrate the negation adverb as well in order to correct sentences like 'Ils nont pas fait leurs devoirs.' or 'Il nappela pas son frère hier.' into Ils n'ont pas fait leurs devoirs.' or 'Il n'appela pas son frère hier.'

**Comment by jaumeortola** [comment]
> sentences like 'Ils nont pas fait leurs devoirs.

It is already done, but it is not yet on Premium. Check it on open source.

**Comment by jaumeortola** [comment]
- [ ] Some split suggestions in rules JE_VERBE, TU_VERBE...: `Ils fontun travail`
