### ISSUE TITLE
[en] False warning in MD_BASEFORM

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#5311]
MD_BASEFORM suggests the verb 'happen' after the modal 'can'. But, in this context, 'metal can' is a noun cluster (semantically, "can happen to be" does not make sense):

> A defect in this metal can **happened** to be the cause of the accident.

**Comment by tiff** [comment]
Fixed as part of https://github.com/languagetool-org/languagetool/commit/1b40b8862d7d03d2b443aaad6bf064b46f802a38#diff-54b065c892e9aa885ae95cc110a0fc4cc77abba8c81e0eb1c417a27261f966afR59248
