### ISSUE TITLE
[pt-br] user feedback "à toa"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#5317]
> Olá,  gostaria de informar que uma das formas sugeridas pelo LanguageTool está em desuso.
> "À-toa", com hífen, não se usa mais. 
> Exemplo: 
> "Ele precisava ser inteligente em seus ataques para não enfraquecer à toa."
> O corretor indica o hífen, sendo que esse não existe.
> Obrigada.

**Comment by marcoagpinto** [comment]
Hello!

In pt-PT it is correct:
https://dicionario.priberam.org/%C3%A0-toa

However, I have removed it from the hyphens file:
https://github.com/languagetool-org/languagetool/commit/b40656b8c160d5bd67cb5359c96efd0ceb560e72

If you have any idea of how to make it suggest the hyphen in pt-PT it would be great.

🙂

**Comment by marcoagpinto** [comment]
This was the best I could come up with:
https://github.com/languagetool-org/languagetool/commit/46be3470ce481cd0d9345478514a8a209b12ae2d

https://github.com/languagetool-org/languagetool/commit/133a695f4050ac7a47a89cf530843c42438e6880

Do you think it will solve the issue?

Thanks!

**Comment by udomai** [comment]
I think putting it in the pt-PT and pt-BR replace.txt is a good solution, right @danielnaber?
