### ISSUE TITLE
[nl] Bug (?) detecting sentence

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#5319]
The sentence
139 Hoesten; Tintelingen ; Gevoelloosheid ; Dubbel zien ; Verzwakte armen of benen.
is one of the sentences havin a semicolon that is detected by a rule trying to catch only sentences of 2 words:

`<pattern><token postag="SENT_START"/><token/><token/><token postag="SENT_END"/></pattern>`

In the Dutch segmentation, I could not find detection of a ; (In Dutch a ; is like a sentence end without a capital following).

**Comment by jaumeortola** [comment]
The disambiguation rule PUNTKOMMA_END adds a SENT_END tag to every semicolon.
```
PUNTKOMMA[1]: ;[;/null] -> ;[;/PUNTKOMMA]
SEMICOLON[1]: ;[;/PUNTKOMMA] -> ;[;/PUNTKOMMA,;/START]
PUNTKOMMA_END[1]: ;[;/PUNTKOMMA,;/START] -> ;[;/PUNTKOMMA,;/START,;/SENT_END]
```
This is the rule:
```
        <rule id="PUNTKOMMA_END" name="">
		<pattern>
			<marker><token>;</token></marker>
		</pattern>
		<disambig action="add"><wd pos="SENT_END"/></disambig>
	</rule>
```

**Comment by baarsrj** [comment]
Thanks. Just found and removed it.
