### ISSUE TITLE
[DE][Stillregel] Fehlalarm mit "nach was"

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#5323]
Moin liebes LanguageTool-Team

Wieso riecht es **nach was** verbrannten?
LT: "Möchten Sie das standardsprachliche „wonach“ verwenden?"

Wieso riecht es **nach etwas** verbrannten?
LT: "Keine Fehler gefunden."

Grüße Dallun511

**Comment by janschreiber** [comment]
Das Problem tritt nicht auf bei dem Satz "Wieso riecht es nach was Verbranntem?"
