### ISSUE TITLE
[fr] wrong sentence splitting with etc. and cf. and guillemets

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#5333]
As seen in today's [Open Source spellcheck](https://internal1.languagetool.org/regression-tests/message-spelling/result/2021-07-08/fr_diff.html):

Si « cf. **» désigne** l’abréviation de « confer », il convient… → Cette phrase ne commence pas par une majuscule

_Side note: That message should end in a period._

![image](https://user-images.githubusercontent.com/67792088/125059866-136f7380-e0ac-11eb-856c-d54e94b4db76.png)

**Comment by jaumeortola** [comment]
Fixed here: https://github.com/languagetool-org/languagetool/commit/8c1fb2146da7e18188736f01689d52ff06768f0b
