### ISSUE TITLE
[fr] user feedback "boite"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#5336]
> Some accentuations in French are ignored by your application, like the word "boite" which carries an accent.

**Comment by udomai** [comment]
It doesn't after the spelling reform: https://www.larousse.fr/dictionnaires/francais/bo%C3%AEte/10034 🤓

We might want to have a coherency rule for old/new spelling at some point.

**Comment by jaumeortola** [comment]
See Premium issue: https://github.com/languagetooler-gmbh/languagetool-premium/issues/2994
