### ISSUE TITLE
[pt] user feedback "A rais da árvore esta podre""

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#5343]
User feedback:

> não percebe qualquer erro nesta frase: "A rais da árvore esta podre"

**Comment by marcoagpinto** [comment]
Ahhh... I will work on it during the week or probably next week, as I have some other rules on mind.

**Comment by marcoagpinto** [comment]
@danielnaber 

Done!

https://github.com/languagetool-org/languagetool/commit/21c763d456c60d169d758bcd7df97ee3b70d928d

https://github.com/languagetool-org/languagetool/commit/6511d24bc9d98496d66a2692cd2a10fb22c68854
