### ISSUE TITLE
wrong warning

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#5352]
The rule
```
		<rule id='START-IPTKOM-ZNWMRVVRKDE_-ITPPNT-END' name='z'>
			<pattern><token postag="SENT_START"/><marker><token>,</token><token postag="ZNW:MRV:VRK:DE_"/><token postag='SENT_END' regexp='yes'>[!.]</token></marker></pattern>
			<message>x</message>
			<example type = 'incorrect'><marker>, aaitjes.</marker></example>
		</rule>
```
gets the compile warning
removes ', ' but doesn't have a space, comma or dot at the start of the suggestion: <marker>, aaibaarheid.</marker> => []

Quite logical, since there is no suggestion!

**Comment by danielnaber** [comment]
I've commented out the test for now, as it would require more work to distinguish between empty string suggestion and no suggestion.

**Comment by udomai** [comment]
To save the test's honour, I have to mention that it actually prevented space-less suggestions in German just this week.
