### ISSUE TITLE
[ru] Возможно могу

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#536]
Предлагать синонимы для "возможно" (вероятно?) и для "могу\может" (способен? или совсем убрать его)
WRONG Я, возможно ошибаясь, могу предложить способ решения.
WRONG Он возможно не спешил и может опоздать.
Он возможно не спешил и опоздает.

**Comment by yakovru** [comment]
This is not mistake.
But "Я, возможно ошибаясь, могу предложить способ решения." sounds bad, and need correct.

**Comment by kostyfisik** [comment]
Yes, this is the point. As soon as LT is also a style corrector, it should notify the user for the bad style like this. It looks to be quite a certain pattern, but at the moment I do not have a possibility to check for possible exceptions and antipatterns.

**Comment by yakovru** [comment]
Fixed.
