### ISSUE TITLE
Premium API works with Postman but can't get AWS Lambda running

### ISSUE THREAD

**Issue by weisisheng** [languagetool-org/languagetool#5368]
Would appreciate any tips, tricks.  Only returns a #400 and a cryptic error.

{
  "errorType": "Error",
  "errorMessage": "Request failed with status code 400",
  "trace": [
    "Error: Request failed with status code 400",
    "    at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)",
    "    at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)",
    "    at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:260:11)",
    "    at IncomingMessage.emit (events.js:388:22)",
    "    at IncomingMessage.emit (domain.js:470:12)",
    "    at endReadableNT (internal/streams/readable.js:1336:12)",
    "    at processTicksAndRejections (internal/process/task_queues.js:82:21)"
  ]
}

#

const aws = require("aws-sdk");
const axios = require("axios");

exports.handler = async (event) => {

  //console.log(event.text)

  const res;

  try {
    const res = await axios.post("https://api.languagetoolplus.com/v2/check", {
        apiKey: 'fooAPIkey',
        language: 'en-US',
        username: 'foo@foo.io',
        text: event.text
    });

  console.log(JSON.stringify(res.data));

  return {
    statusCode: 200,
    body: res.data,
    };
  } catch (error) {
    console.log(error);
    return {
        statusCode: 400,
        body: error,
      };
    }
};

**Comment by danielnaber** [comment]
You will need to print the body of the 400 response to see the actual error message.

**Comment by danielnaber** [comment]
Closing, as there was no further reply.
