### ISSUE TITLE
[en] Can be field\filled

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#537]
I believe that this two are for sure wrong:
Can be field to complete a task.
Can be field with letters.
And this one is correct:
Can be filled with letters.

(I think that it can be some more general rule, that will see that field is a noun, so it should be "a field", "the field", "some filed", and probably some more connections, however, without it is for sure wrong usage of noun ).

**Comment by danielnaber** [comment]
I've added field/filled as a pair to `confusion_sets.txt` and it detects both your examples. It will be online at languagetool.org tomorrow night.
