### ISSUE TITLE
[en] FP for ADVERB_WORD_ORDER[9]

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#5389]
It doesn't **happen often**, but when it happens, it's bad. → often happen

I think this is a false alarm, isn't it?

**Comment by MikeUnwalla** [comment]
I think it's a false alarm.

**Comment by udomai** [comment]
This rule has > 5k opens per week, **we should fix this** (41% apply, 3.7% disable). Most deactivations come from subrules 1, 3, 9, 4, 5 (in descending order).

Here are the deactivation contexts for July, sorted by rule ID:

[ADVERB_WORD_ORDER deactivations.xlsx](https://github.com/languagetool-org/languagetool/files/6854828/ADVERB_WORD_ORDER.deactivations.xlsx)

**Comment by MikeUnwalla** [comment]
Grafana stats, last 7 days on 2021-07-28:
![image](https://user-images.githubusercontent.com/5816160/127299500-2285c2b6-0b31-4326-aebe-f294026123d0.png)

**Comment by MikeUnwalla** [comment]
Incorrect adverb word order not found after changes:

- [ ] Rarely casinos offer the place bet to lose. [Rarely do casinos; Casinos rarely; Rarely, casinos]

**Comment by MikeUnwalla** [comment]
Grafana results 2021-08-04, past 7 days:
![image](https://user-images.githubusercontent.com/5816160/128174169-7fec2917-07dc-441a-b9b0-1f415c416520.png)

**Comment by MikeUnwalla** [comment]
Grafana results 2021-08-16, past 7 days:
![image](https://user-images.githubusercontent.com/5816160/129528509-a6c449b7-32bd-40b8-a2b8-d013c58c83cc.png)
