### ISSUE TITLE
[en] inspired with or inspired by

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#539]
"inspired with" should always be replaced with "inspired by"

**Comment by MikeUnwalla** [comment]
Done [https://github.com/languagetool-org/languagetool/commit/738ab6ffa294899d2dcbcc6a24ba71953a445f06](https://github.com/languagetool-org/languagetool/commit/738ab6ffa294899d2dcbcc6a24ba71953a445f06)
