### ISSUE TITLE
[en] Wrong suggestion: HELL 

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#5391]
HELL suggests 'She'll':

> Enron and **Shell** will each write a guaranty in favor of TBS for their ...

![image](https://user-images.githubusercontent.com/5816160/126452527-a310545a-0b52-46bd-9fd9-338f39c0491c.png)

**Comment by tiff** [comment]
This has been fixed recently (sorry, forgot to close and mention the issue)
