### ISSUE TITLE
[en] A possible possibility

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#540]
I do not have a possibility to check for possible exceptions.

I think it should be detected as a bad style. The second "possible" can simply be omitted of may there are some similar words to keep the exact meaning of the original sentence.

**Comment by MikeUnwalla** [comment]
Done (https://github.com/languagetool-org/languagetool/commit/622f125dcaa2dc49029bb1ad47bedae0869e6683).
