### ISSUE TITLE
[all] check-data does not filter rules

### ISSUE THREAD

**Issue by f-knorr** [languagetool-org/languagetool#541]
When I run `org.languagetool.dev.wikipedia.Main` with arguments `check-data -l en -f /home/test.csv -r RATHER_THEN` the restriction to rule RATHER_THEN does not work anymore.
Here is the output of first few lines of my command line:
```
Only these rules are enabled: [RATHER_THEN]
All spelling rules are disabled
Working on: /home/test.csv
Sentence limit: no limit
Error limit: no limit

Title: <Tatoeba>
1.) Line 1, column 14, Rule ID: USELESS_THAT[1]
Message: "that" may be unnecessary here.
I can't live that kind of life.
             ^^^^              
```

**Comment by danielnaber** [comment]
@pminos Could this be caused by your recent changes?

**Comment by pminos** [comment]
Probably yes, this is caused by the resent changes.

But the option  **-r,--rule-ids <id>** has the function _comma-separated list of rule-ids to activate_

The other rules that are enabled by default should be active, or not?

**Comment by pminos** [comment]
I see at the code that when we disable every rule when we specify the -r option. Maybe we should update the description of the option.

**Comment by pminos** [comment]
@f-knorr I think it works now.

**Comment by f-knorr** [comment]
@pminos Thanks!
