### ISSUE TITLE
[ru] improve style without же

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#542]
In many cases "же" polutes the sentence adn  can be removed without any  change of the meaning to improve the style
BAD STYLE Это сразу же приводит к необходимости выбора
BETTER  Это сразу приводит к необходимости выбора
BAD STYLE Здесь же очень хорошо
BETTER Здесь очень хорошо

correct usage
 Для достижения того же результата.
В той же таблице большинство значений оказалось на 9 порядков меньше.
Удалось подобрать ту же цветовую гамму 

Antipattern: Direct speach
Он же меня уволит за это!

**Comment by yakovru** [comment]
I set new rule off by default because "же" is а very common particle.

**Comment by kostyfisik** [comment]
@yakovru  Rules off by default are something a bit strange. Some effort was done to provide a check, however, most of the users do not know about it (as soon as, I believe, most of them use the default settings of LT). Did I get it right, that is simply means that this rule does not have enough antipatterns and exceptions and is not ready for wide use?

**Comment by yakovru** [comment]
Particle "же" is а very common:
http://gramota.ru/slovari/dic/?word=%D0%B6%D0%B5&all=x
Use "же" in business correspondence is bad style. 
But in literature and everyday speech this is the standard.
We can improve this rule, but еhe best solution was to create a set of rules
for business correspondence, literature and everyday speech.
