### ISSUE TITLE
Duplicate rules not detected

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#5421]
Hello!

If the case changes in rules names, they aren't detected as duplicates:
```
<rule id='ESTA_está' name="Confusão: esta/está">
<rulegroup id='ESTA_ESTÁ' name="Confusão: esta/está">

```
Is it a bug or a feature?

Thanks!

**Comment by danielnaber** [comment]
Please use uppercase-only IDs to avoid this issue.
