### ISSUE TITLE
[LibreOffice] Add-on crashes

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#5430]
Hello!

![languagetool_error_20210729](https://user-images.githubusercontent.com/5192600/127439297-583beea5-3cc3-4bd9-9a7e-66ada528e9ea.png)

**Comment by marcoagpinto** [comment]
It has been happening for weeks or so.

**Comment by danielnaber** [comment]
Does this still happen? A lot of issues have been fixed in the add-on recently.

**Comment by marcoagpinto** [comment]
For what I have seen, I haven't experienced any crashes lately.

🙂
