### ISSUE TITLE
[ru] POS tagset should be extended

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#546]
At the moment is looks to be too limited compared to many notations in use by other porjects (Pymorph2, mystem, FreeLing, etc..).  However, current notation looks to be quite easy to remember and to use, so it just need to be extended... E.g. http://opencorpora.org/dict.php?act=gram  (an addtions from pymorph2 https://pymorphy2.readthedocs.io/en/latest/user/grammemes.html )
More cases, genders, etc...

**Comment by yakovru** [comment]
This complicates the rules, but  the extension for the tags will help us improve the suggestions 
like (чая/чайку). This is done only in the next version of LT.

**Comment by yakovru** [comment]
In the AOT system uses more tags than moved to LT.
http://aot.ru/docs/rusmorph.html
We can use in next LT release.

**Comment by kostyfisik** [comment]
Probably we can rethink tags for Russian to make it more flexible for any future updates, so it can use grammar tags from any available tagging system (AOT, pymorph2, mystem, freeling, etc.)  In general, rules should not rely on the order of grammar characteristics. Keeping all names for all characteristics to be unique,  we should alway use ":" around them (including the end).  This will give the possibility to generalize the regexp, e.g. at the moment we have the following tags:
NN:Masc:PL:D
NN:Masc:PL:D:Talk
The rule (a real example from grammar.xml)
```xml
<token postag="NN:.*:.*:D" postag_regexp="yes">
```
 will be applied only to the first one, in spite of there is a need for word agreement for the talk form too.
Using the closing ":"  for any tag will give:
NN:Masc:PL:D:
NN:Masc:PL:D:Talk:
and the rule can be written as
```xml
<token postag="NN:.*:D:.*" postag_regexp="yes">
```
and it will continue working when we add
NN:Masc:PL:D:Obsc:
NN:Masc:PL:D:Old:
This way rules like 
```xml
<token postag="NN:.*:.*:.*"
```
should be explicitly avoided, if there is a need in Noun just use postag="NN:.*"

NNN, NNF, NNP are cryptic - we should simply use NN: (as soon as most of the rules applied to NN in general should be applied to NNN, NNF, and NNP)  with  :Name:  :Family: :Patrionic:  . This will also give a possibility to extend names with :Geo:  and :TM: 

Adding :Fixed: will simplify unification definition.

ADJ_Sup and ADJ_Com are messed in the current system (and it should be ADJ_Comp according to general rules for abbreviations, that the word is truncated before vowel)

**Comment by yakovru** [comment]
Done. See https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/ru/src/main/resources/org/languagetool/resource/ru/tags_russian.txt
and
https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/ru/src/main/resources/org/languagetool/resource/ru/tagset.txt

**Comment by kostyfisik** [comment]
It seems the same misprint is still here

```
ADJ:Sup -  прилагательное в сравнительной степени сравнения - ADJECTIVE comparative  construction
ADJ:Comp - прилагательное в превосходной степени сравнения - ADJECTIVE  superlative constructio?
```

Why `Sup` stands for `comparative` and `Comp` for `superlative`? This is very contrintuitive. I will need more time to review this change, I hope I fill find some time during NY holidays.

**Comment by yakovru** [comment]
Thanks. It is typo.
I'll update it today.
Everything is ready for release, I will update the documentation.

**Comment by kostyfisik** [comment]
@yakovru Why don`t you accept adding closing semicolumn to all tags? This will add flexibility and simplify a number of rules, this way any grammatical characteristic will start and finish with a `:`, writing regexp to select one is very easy. I do not see any major drawbacks, could you clarify this?  

One more benefit - this will easily allow extending rules with various other grammatical charachteristics if needed, see possible list here http://opencorpora.org/dict.php?act=gram 

ADJECTIVE comparative  construction should be ADJ_Comp, not ADJ:Comp. This is due to the fact that it has no gender, number, or case, this way it will always be an exception, this is an easy way to avoid adding it manually to every generic rule with ADJ.

:2V  case (второй винительный) `записаться в солдаты` (а не `записаться в солдат`, но `играть в солдат`, оба отвечают на вопрос "в кого? во что?" ), `годится в отцы` (а не `годится в отцов`) and huge number of similar combinations (that should be treated as exceptions otherwise).

NN:Geo Африка
NN:Corp Яндекс   

A simple (but usefull rule) is ready to be  added - if tag is only NN:Geo or only NN:Corp the token should start from a capital letter.

**Comment by kostyfisik** [comment]
@yakovru Переходность глагола is detected with Yandex Mystem and can be used in a number of rules https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4%D0%BD%D1%8B%D0%B9_%D0%B3%D0%BB%D0%B0%D0%B3%D0%BE%D0%BB 

using the same notation will ease things a bit 

tran	переходный глагол
intr	непереходный глагол

**Comment by yakovru** [comment]
@kostyfisik Now I fixed ADJ:Sup and ADJ:Comp. This typo is come from LT.2.6

Now I can not change any POS tags, because the release LT 3.6 is planning to 28.12.2016!

**Comment by yakovru** [comment]
@kostyfisik AOT also provide additional grammar characteristics like transitive (переходность) . I am planning extended dictionary for next release.
I did not include this information in this version because the resulting POStag is too long.

**Comment by kostyfisik** [comment]
@yakovru OK, let`s keep changes till the end of freeze. Please, consider closing : and other improvements, it would be great if we can stabilize POS system till the NY. I hope to rework on POS-ing scripts and to provide many more POS-tags for Russian during NY holidays. To succeed with it and to get most from tagging possibilities of AOT, Mystem, and Pymorph we need a rather generic POS tags. The final profit from this activity should be a reduced number of exceptions, which is a real hell now for generic rules, like unification......

**Comment by kostyfisik** [comment]
One more source of ideas for tagging https://talp-upc.gitbooks.io/freeling-user-manual/content/tagsets/tagset-ru.html

**Comment by kostyfisik** [comment]
@yakovru Can you please share you vision how POS tag system for Russian should look like in next release?

**Comment by yakovru** [comment]
1. Fix bug for abbreviation. Some words like "ГДР" have wrong POS tag like NN:Name:Fem:Sin.
It must be ABR:Fem, etc but another group of abbreviation has correct POS tag like  ABR:Fem,  ABR:Masc,  ABR:Neut
2. Fix other possible bugs in POS tags.
I am planning to create rules using new grammatical characteristics of LT 3.6,  and as a result of the creation of these rules to make changes to the POS tag system.

**Comment by yakovru** [comment]
POS tags for nouns and adjectives do not require major changes.
POS tags for verbs and numerals require some changes.

**Comment by yakovru** [comment]
Done. For Release 4.2 See https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/ru/src/main/resources/org/languagetool/resource/ru/tags_russian.txt
and
https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/ru/src/main/resources/org/languagetool/resource/ru/tagset.txt

**Comment by kostyfisik** [comment]
@yakovru Great! Do you need help with the script to generate LT tags from Yandex mystem? I think that there is still a huge amount of word that miss a tag in LT and do have it in mystem dictionary.

**Comment by yakovru** [comment]
@kostyfisik  Now I'm working on adding new words to the AOT project.
I found an more easier way to add words to the AOT vocabulary,
and on the basis of the user's  spellcheck LT dictionary I plan to significantly expand the AOT dictionary.
