### ISSUE TITLE
[de][LibreOffice] false positive bei "lagen" und "einschlagen"

### ISSUE THREAD

**Issue by ChristianPervoelz** [languagetool-org/languagetool#5500]
**Beispielsatz**
Zweifel lagen in der Luft, ob es richtig war, diesen Weg einzuschlagen.

**Problem**
Die Wörter _lagen_ und _einzuschlagen_ werden als "im gleichen Satz verwendet" markiert.

**Info**
LibreOffice 7.0.4.2
LT Plugin: 5.4
Alle Stilregeln aktiviert

**Comment by danielnaber** [comment]
@FredKruse Ähnlicher Fix wie #5530?

**Comment by FredKruse** [comment]
@ChristianPervoelz Der Fehler ist beseitigt und kann morgen mit dem Snapshot getestet werden.
@danielnaber Ich habe wieder eine Ausnahme hinzugefügt, werde mir aber Gedanken machen, ob es nicht eine allgemeingültige Lösung gibt.

**Comment by ChristianPervoelz** [comment]
Geprüft mit 5.5-SNAPSHOT (2021-08-22) - **Behoben**
