### ISSUE TITLE
Captcha Broken for Support Ticket

### ISSUE THREAD

**Issue by phil-lgr** [languagetool-org/languagetool#5502]
![image](https://user-images.githubusercontent.com/9644867/128949739-018d6f05-2fa1-4d64-ab8c-7338140efc5a.png)

As the title says... I found no way to submit a ticket

**Comment by phil-lgr** [comment]
While where at it, here is my question:

---

Hi LanguageTool, 

I'm very happy with my premium subscription.

I read here https://languagetool.org/http-api/swagger-ui/#/default that Premium has a limit of 80 calls per minute... but I don't see how to get an API key

Is it possible to have access to the API with a premium subscription?

Thank you,

Philippe

**Comment by danielnaber** [comment]
I cannot reproduce the captcha issue - did it happen after you had to solve a captcha, or did the green check mark appear when you click on "I'm not a robot"? Also, which browser did you use, and can you reproduce the problem?

**Comment by phil-lgr** [comment]
> did the green check mark appear when you click on "I'm not a robot"? 

Yes. It did, I use Chrome stable.

I tried again this morning

![image](https://user-images.githubusercontent.com/9644867/129044767-a115ed1f-f9e9-44ea-943e-647001ac3ab5.png)

Only a weird error in the console

**Comment by phil-lgr** [comment]
The achor:1 url points to https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LdvejUUAAAAAEn6wjOFcPVRyQr4KtAJ03ltA1SQ&co=aHR0cHM6Ly9sYW5ndWFnZXRvb2xlci5mcmVzaGRlc2suY29tOjQ0Mw..&hl=en&v=tFhBvPrftr7Y91fo1S1ASkA6&theme=light&size=normal&cb=bdqhn4eioxil

**Comment by phil-lgr** [comment]
When I click on the Captcha the error appears

![image](https://user-images.githubusercontent.com/9644867/129045216-3fc9835a-2812-4fdb-beb7-51e78ddaaa4a.png)

**Comment by danielnaber** [comment]
Closing, as this is an old issue and we haven't received recent reports like this
