### ISSUE TITLE
Conflict between Duden Mentor Premium and free Languagetool: ,,Oder/Oder, weil wir nach mehr Akzeptanz suchen? Nach mehr Anerkennung. Nach Geborgenheit Auf der Suche´´

### ISSUE THREAD

**Issue by re33333** [languagetool-org/languagetool#5505]
Happening in Word (German language) as
Conflict between Duden Mentor Premium and free Languagetool: 

> _,,Oder weil wir nach mehr Akzeptanz suchen? 
> Nach mehr Anerkennung. Nach Geborgenheit
> 
> 
> Auf der Suche´´_ 

Languagetool suggests: _

> ,,Oder, weil...´´

_ meanwhile Mentor let it be. The Duden Korrektor react both fine. Both ignores the lost point by the end of 

> _,,heit´´_<.

---

> _,,Oder, weil wir nach mehr Akzeptanz suchen? 
> Nach mehr Anerkennung. Nach Geborgenheit
> 
> 
> Auf der Suche´´_

 0 $ Languagetool responds:

> ,,1 weiterer Hinweis gefunden...´´.

 Duden Mentor wants to remove comma. Maybe accepting no dot can be right.

---

In Languagetool of 

>  ,,Oder, weil wir nach mehr Akzeptanz suchen?´´

It alerts as one mistake founded (unknown). Duden Mentor recommend no _,, , ´´_.

---

However when I mark only

>  _,,Oder weil wir nach mehr Akzeptanz suchen?´´_ 

gets zero errors in both Dude. M. and Language. This makes the open-source program less consistent.

---

By 

> _,,Und, wenn diese Zugehörigkeit nicht gegeben ist ... ´´_

 Languagetool says 

> _,,1 weiterer ...´´_

 mentor.duden.de removes comma.

---

_,,Und wenn diese Zugehörigkeit nicht gegeben ist ... ´´_ Dud. Ment. finds it right. Languagetool adds it (the comma).

---

Duden Korrektor scanned both variants in all sentences here (which one has two versions on it) all called no mistakes.

---

I am glueless if there´s even in this situation a/two correct answer/s since Duden is considered as standard (which in positioning kinda says differently with two of their own represented programs) yet in the same time languages like german are fluid and population-dependent.

I found out by adding those weird gaps:
_,,

´´_ in Languageto., it differs by his results. Those examples I picked from [https://www.germanskills.com/post/perfektes-deutsch](https://www.germanskills.com/post/perfektes-deutsch), in chapter 

> _,,Warum eigentlich?´´_<.

**Comment by Discostu36** [comment]
LanguageTool Pro can't decide. Without comma, it wants to add it (the rule from the free version). With comma, it wants to remove it (pro rule).

**Comment by udomai** [comment]
Thanks @Discostu36! LT should not force the comma between _und/oder_ and the subordinating conjunction. It can be right sometimes, but most of the time, it's not.

**Comment by udomai** [comment]
By the way, https://www.germanskills.com/post/perfektes-deutsch has errors in the text.

> Perfektes Deutsch **zu** sprechen wollen aber nicht nur Perfektionisten. (superfluous "zu")
> Perfekt oder wie ein Muttersprachler, Deutsch sprechen zu wollen, hat mit dem eigenen Ego zu tun. (First comma is wrong)

The text has been written by a non-native speaker. One with an exceptional mastery of written German, but the text still sounds somewhat "off" here and there.
