### ISSUE TITLE
[en] False positive for 'The article is probably missing before the noun'

### ISSUE THREAD

**Issue by rillig** [languagetool-org/languagetool#5506]
> The included file defines a default value, and the including file later overrides that value.

LanguageTool wants to correct this into "including a file", even though there already _is_ an article.

![image](https://user-images.githubusercontent.com/3233724/129141133-a607e716-103c-4eda-aad9-24a38973134e.png)

JetBrains CLion 2021.2, using LanguageTool 5.4.

**Comment by danielnaber** [comment]
I cannot reproduce on languagetool.org, so this has probably been fixed already.
