### ISSUE TITLE
[de] misspelling not found when similar word in spelling.txt

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#551]
Add `Amigaatest` to `de/spelling.txt` (yes, it's a fantasy word). Then check a text which contains `Amigaatestx`. No error will be detected. I think this is caused by the recent changes to better detect compounds from `spelling.txt`. @f-knorr could you have a look?

**Comment by f-knorr** [comment]
@danielnaber That was my fault! My modifications check whether everything that comes after "Amigaatest" (the 2nd part) is correct. However, single characters are always  correct...
Now, the length of the 2nd part must be at least two characters long.
