### ISSUE TITLE
[pt-pt] user feedback "Fiquei surpreendido"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#5512]
> Wrong feedback on an expression in Portuguese
> "Fiquei surpreendido" 
> It says the most correct form is "Fiquei surpreso". That is not the case in Portuguese from Portugal.
> Source: https://ciberduvidas.iscte-iul.pt/consultorio/perguntas/ficar-surpreendido/25441
> The info icon of that correction also redirects to a Brazilian page:
> https://radames.manosso.nom.br/linguagem/gramatica/morfologia/verbos-abundantes/

**Comment by marcoagpinto** [comment]
I will look at it tomorrow 🙂

**Comment by marcoagpinto** [comment]
Fixed!

**Comment by tiff** [comment]
Thanks
