### ISSUE TITLE
repeated lemmas in patterns

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#5515]
It would be useful to detect repeated lemmas in patterns. The syntax could be something like this:
```
<pattern>
    <token regexp="yes">.+</token>
    <token inflected="yes" regexp="yes"><match no="0" inflected="yes"/></token>
</pattern>
```
The `<match>` element should be replaced by all the lemmas in the referenced token: `lemma1|lemma2|lemma3`.

**Comment by ricardojosehlima** [comment]
Hi,
   Would this mean that in the sentence "Eu comprei um caderno, é um caderno caro, gosto de cadernos.", the repetition of "caderno" would be detected?

**Comment by jaumeortola** [comment]
Yes. You can detect a repeated token (caderno/caderno)  with:

```
<pattern>
    <token skip="-1"></token>
    <token><match no="0"></token>
</pattern>

```
But if you want to detect also different forms of the same lemma (caderno/cadernos), you need:

```
<pattern>
    <token skip="-1" regexp="yes">.+</token>
    <token inflected="yes" regexp="yes"><match no="0" inflected="yes"/></token>
</pattern>
```

**Comment by ricardojosehlima** [comment]
Thanks, on that, I may have misread what base form is on the rule editor: 

"Check this and specify the base form to make all forms match (e.g. plural)." 

I interpreted that the base form would be the lemma.

My view is that it would be worth a try a rule for detecting repeated lemmas even if there is the need to create a rule for each tag - however, for Portuguese, first it would be necessary to fix the lemmatization process, a problem that is not of languagetool alone, but of other libraries like Spacy.

**Comment by jaumeortola** [comment]
Base form and lemma are the same thing. This token (`<token inflected="yes">caderno</token>`) will match "caderno" and "cadernos".
In this issue, we are dealing with something more complex: duplications of any form of a lemma/base form inside a sentence. It has never been used in rules, but it could be handy for some style rules. 

As for what you call "lemmatization", what we do generally is rule-based disambiguation (in the "disambiguation.xml" file), e.g. decide if a word is a noun or a verb in certain contexts. For Spanish, French and Catalan, it is partially developed. We don't do a full disambiguation, but only disambiguation for our specific needs. Similar strategies can be applied in Portuguese. Please open a new issue and collect errors in Portuguese disambiguation so that it can be improved.

**Comment by ricardojosehlima** [comment]
Hi,
  Thanks for the clarifications! This issue you are dealing is very interesting and important and if you can be successful it will be great for languagetool.
  As for the issue with the lemmas, I will take a look at the file you mentioned (have already found it) and will compile a list of errors in Portuguese - this may take some days, maybe Wednesday - and I will open the issue as you pointed.
