### ISSUE TITLE
What is the source of uk_UA dictionary exactly?

### ISSUE THREAD

**Issue by k-bx** [languagetool-org/languagetool#553]
Hi. I can't figure out where do you take the `uk_UA.dict` file from, exactly. Its size is 1534568 bytes. Hunspell's README points to http://extensions.libreoffice.org page, where I was able to find [Ukrainian spelling dictionary](http://extensions.libreoffice.org/extension-center/ukrainian-spelling-dictionary-and-thesaurus) page, but couldn't get any link to its source from there. Second link in http://cgit.freedesktop.org/libreoffice/dictionaries , where I could find uk_UA.dic which is 2584267 i size.

So, the question is, what's the source for `uk_UA.dict` in this repo and where is the "canonical" dictionary which is being supported and updated? Thank you.

**Comment by arysin** [comment]
The source is here:
https://github.com/brown-uk/dict_uk

**Comment by kostyfisik** [comment]
Probably answered.
