### ISSUE TITLE
[LibreOffice] false-positive zu "Zeichen ohne sein Gegenstück" bei Zitaten über mehrere Absätze

### ISSUE THREAD

**Issue by ChristianPervoelz** [languagetool-org/languagetool#5539]
**Reproduktion des Problems**
- Drei Sätze in LO/OO schreiben
- jeder Satz in eigenem Absatz
- vor den ersten Satz ein öffnendes Anführungszeichen
- hinter dem letzten Satz ein schließendes Anführungszeichen

**Ergebnis**
Sowohl das öffnende, als auch für das schließende Anführungszeichen werden markiert mit "Zeichen ohne sein Gegenstück"

**Anmerkung**
Verhalten ist auf languagetool.org nicht nachvollziehbar, weil man dort keine echten Absätze einbauen kann.

**Version**
LO v7.0.6.2
LT v5.4

**Comment by FredKruse** [comment]
Wie sind die Einstellungen in den LT-Optionen?
Unter "Allgemein" darf nicht "Nur den Absatz prüfen" eingestellt sein. Diese Option arbeitet zwar etwas schneller als der Standard, liefert aber keine korrekten Ergebnisse, wenn eine Prüfung über den Absatz hinaus notwendig ist (Sie ist nur für OO, alte Versionen von LO und als Rückfalloption notwendig).

**Comment by FredKruse** [comment]
Ich denke, das Problem ist gelöst und schließe das Issue.
