### ISSUE TITLE
[ru] no comma for "как" and a regular sequence.

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#554]
It should track inflected forms too
WRONG бледный, как полотно
WRONG побледнел, как полотно

http://orthographia.ru/punctum_uk.php?rid=263

е) если оборот с союзом как является устойчивым сочетанием: бледный как смерть (как полотно), блестеть как зеркало, седой как лунь, вертеться как белка в колесе, кататься как сыр в масле, голодный как волк (как собака), идти как на казнь, лететь как стрела, красный как рак, знать как свои пять пальцев, сидеть как на иголках, гол как сокол, чувствовать себя как дома, пристать как с ножом к горлу, остановиться как вкопанный, дрожать как осиновый лист, нужен как воздух, упасть как подкошенный, упрям как осел, развеяться как дым, ударить как обухом по голове, ходить как в воду опущенный и др.: Вот увидишь — возьмет да вернется, упадет как снег на голову (Айт.); Как дым рассеялись мечты (Л.); Вдруг он опустил дуло пистолета и, побледнев как полотно, повернулся к своему секунданту (Л.); Дождь, начавшийся еще в среду, ливший с утра и до вечера, лил как из ведра (Бун.).

**Comment by yakovru** [comment]
Fixed:
https://github.com/languagetool-org/languagetool/commit/f7851d9de46cc54502fc4fe29625e9e2a2398384
