### ISSUE TITLE
[en] probable misspelling: wold

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#5541]
Just like the dictionary word "anther" occurs most probably as a misspelling of "another", the word "wold" will most likely be a typo ("world").

@MikeUnwalla, may I entrust you with yet another one of these? :)

**Comment by marcoagpinto** [comment]
It is Latin:
https://en.wiktionary.org/wiki/anthe

**Comment by marcoagpinto** [comment]
I also believe it is a proper name, since in the British Dictionary it starts uppercase and has a possessive.

**Comment by marcoagpinto** [comment]
Sorry for the deletion of my two previous posts.

It is a valid word (botany):
https://www.lexico.com/definition/anther

**Comment by udomai** [comment]
Hi @marcoagpinto, that is true: Words like 'anther' or 'wold' are 'valid', but 99.9% of the time they are typed, they're just misspellings. Those are typos our dictionary won't correct, so we write rules for those typos. See the anther rule message and antipatterns for how we go about that :)

**Comment by MikeUnwalla** [comment]
@udomai, we already have rulegroup WOLD_WOULD, which finds these typos:

> **Wold** you like a nice cup of tea?
> If I were you, **I wold** not do that.

What are the typos that are **not** found?

**Comment by danielnaber** [comment]
@MikeUnwalla One example (I just made it up): "This is the largest cake in the wold."

**Comment by MikeUnwalla** [comment]
@danielnaber, your example is a semantic problem. I made an issue: https://github.com/languagetool-org/languagetool/issues/5545 for the noun/noun confusion.

**Comment by danielnaber** [comment]
Seems to be fixed for a long time, so closing the issue.
