### ISSUE TITLE
[LibreOffice] Right-click not working in tables

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#5543]
Hello!

Tested with pt-PT.

Download the .odt.

Press CTR+G and select page 6.

Then, scroll up and right-click in the table text where there are grammar issue.

It doesn't show LanguageTool suggestions.

Tested with the latest nightly and LibreOffice 7.2.0.4.

I tried to keep only this page of my document, but if I do that it works, so I have attached the full document.

See also the video attached.

[MCAT_Translation_60PT_unsent.odt](https://github.com/languagetool-org/languagetool/files/7019243/MCAT_Translation_60PT_unsent.odt)

https://user-images.githubusercontent.com/5192600/130182718-3e6b0cd2-196d-4440-800b-7cc987a26122.mp4

**Comment by FredKruse** [comment]
I just committed a fix of the bug. Please test it after tomorrow with the latest snapshot and close the issue, if it works.

**Comment by FredKruse** [comment]
I think we can close the issue.
