### ISSUE TITLE
From „Blütenstand mit unverzweigter Hauptachse, an der die ungestielten Blüten sitzen.“ LT corrects as „gestielten“ without the prefix „un“, which changes his meaning.

### ISSUE THREAD

**Issue by re33333** [languagetool-org/languagetool#5551]
It corrects „ungestielten“ as „gestielten“ wrong in only copy and pasting, which the prefix changes his meaning:

> „Blütenstand mit unverzweigter Hauptachse, an der die ungestielten Blüten sitzen.“

> „Ungestillten, ungezielten, gestielten, ungeteilten, ungezügelten“.

**Comment by danielnaber** [comment]
Already fixed (#5549), will be online later today.
