### ISSUE TITLE
Selecting fix then moving cursor inserts fix in wrong location

### ISSUE THREAD

**Issue by SethFalco** [languagetool-org/languagetool#5552]
When the LanguageTool browser extension suggests a fix, there is a short period between clicking it and the fix being applied. In this time, the user can move their text cursor to another location, which makes the fix appear in the wrong location.

I've only managed to reproduce the issue on Discord, on other websites the fix is applied quick enough that there's no time to move the cursor.

### Steps to Reproduce
1. Go to a website such as discord.com (In the web app.)
2. Type a message like "Thanks for the heads up!"
3. Apply the fix to change "heads up" to "heads-up".
4. Spam the down-arrow key or click to move the text cursor location.

### Example
https://user-images.githubusercontent.com/22801583/130360193-4d374444-9d8d-4401-b223-b61bd6e2d677.mp4

### Notes
This issue was discovered through regular use, however only that one time was the issue ever accidentally triggered.

**Comment by tiff** [comment]
This should be fixed already.
