### ISSUE TITLE
[ru]False positives

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#556]
CORRECT Такой подход дополняет теорию компенсации
рассеяния, только вместо отрицательной электрической
восприимчивости из квазистатического приближения
(LT assumes to put a comma before вместо. If I use но вместо false possitive does not occures)

CORRECT нам пришлось уменьшить
шаг сканирования для толщины покрытия и увеличить размер популяции в
настройках 
(LT assumes comma before и, however this two has a common пришлось)

СORRECT  Тем не менее, несмотря на указанные сложности,
адаптивный метод дифференциальной эволюции 
(LT assumes to remove a comma after тем не менее)

**Comment by yakovru** [comment]
СORRECT Тем не менее несмотря на указанные сложности, адаптивный метод дифференциальной эволюции.
(LT right assumes to remove a comma after тем не менее)
http://new.gramota.ru/spravka/punctum?layout=item&id=58_731
http://aprikablog.com/2013/10/tem-ne-menee/

**Comment by kostyfisik** [comment]
This is some missing antipattern.  The comma is needed because  "несмотря на указанные сложности" should be in commas around  http://new.gramota.ru/spravka/punctum?layout=item&id=58_482 
СORRECT Тем не менее адаптивный метод дифференциальной эволюции.
or
СORRECT Тем не менее адаптивный метод дифференциальной эволюции,  несмотря на указанные сложности,  ....
Usage without a comma before "несмотря на" is WRONG

**Comment by yakovru** [comment]
Possible both variants (with and without comma)
http://new.gramota.ru/spravka/punctum/punctum-attach2 (part 3. Вводное слово и союз)

**Comment by kostyfisik** [comment]
One more example, where NNN, NNF, or NNP should have two commas around for sure
CORRECT Тем не менее, Иван, ты поступил не правильно!
@danielnaber @yakovru  Actually, it seems to be a bad practice, as soon as it is not an antipattern for this rule, but it is more like a relation between rules. Is it possible to set this in LT in some explicit way? So  we have:
rule 1: it is an error to have a comma after "Тем не менее" at the sentence beginning.
rule 2: if we have a NNN|NNF token followed with "ты|тебе" it should be two commas around (or one comma for sentence begin\end). 
If we have a sentence 
```xml
CORRECT Тем не менее <marker>,</marker>  Иван, ты поступил не правильно!
```
The marked comma violates rule 1, however, is we remove it will violate rule 2.  Is it possible to solve this in LT?  E.g. have rule 1  priority 3 (Low), rule 2 priority 5 (Normal) and treat this in accordance with the priority.

**Comment by kostyfisik** [comment]
@yakovru  Probably you are right, both cases are valid, if  I  change as 
Однако, несмотря на указанные сложности, адаптивный метод работает быстрее неадаптивного.
Однако несмотря на указанные сложности, адаптивный метод работает быстрее неадаптивного.
(and comma seems to be mostly not needed). Similar  (however, with a bit different meaning) is
Но несмотря на указанные сложности, адаптивный метод работает быстрее неадаптивного.
and here comma seems to be wrong.

**Comment by yakovru** [comment]
I disabled this rule due to feature freeze. And it need improve.
https://github.com/languagetool-org/languagetool/commit/dbc8b78f3d3c06abd804cef7803b58f595cba3d6

**Comment by yakovru** [comment]
Fixed.
P.S. I use workaround - add parenthesis to exception in this rulegroup (&start_vvodnoe;).
