### ISSUE TITLE
Selecting a synonym inserts synonym next to and concated with the word

### ISSUE THREAD

**Issue by ghost** [languagetool-org/languagetool#5564]
When double-click a word to show synonyms and select it, it was perceived a strange behavior where the synonym appears right next to the originate word, even if you move yours text cursor or no.  

This issue is occurring with frequency on Google Docs, on the other websites, everything works as supposedly it has to do.

### How to reproduce it?

1. Go to Google Docs
2. Type any message/phrase (e.g., `Mama, just killed a man. `)
3. Try changing “killed” to any synonym using the extension.
4. The bug should occur (`Mama, just killedkill off a man.`)

### Example
https://user-images.githubusercontent.com/63242633/130649864-f3c544c8-4e37-4daf-a83e-1a15b439993b.mp4

**Comment by danielnaber** [comment]
Can you still reproduce this? It's working okay now for me.
