### ISSUE TITLE
RU: запретить "заместо"

### ISSUE THREAD

**Issue by socketpair** [languagetool-org/languagetool#557]
`Использовать болт заместо шпильки` -- не грамотно. Правильно -- `Использовать болт вместо шпильки`

**Comment by yakovru** [comment]
Слово  «заместо» присутствует в словаре с пометкой  «разг.»:
http://www.gramota.ru/slovari/dic/?word=%D0%B7%D0%B0%D0%BC%D0%B5%D1%81%D1%82%D0%BE&all=x

**Comment by yakovru** [comment]
Fixed.

**Comment by socketpair** [comment]
https://ru.m.wiktionary.org/wiki/Категория:Просторечные_выражения/ru

Нашел тут…
