### ISSUE TITLE
[en] Too vs To with a Cardinal Number

### ISSUE THREAD

**Issue by TediouslyBored** [languagetool-org/languagetool#558]
I cannot think of any instances where "too" would be used before a cardinal number. This is my first attempt at making a rule using the Language Tool Rule Editor. Sorry if I made any mistakes.
```
<!-- English rule, 2016-09-29 -->
<rule id="TOO_CARDINAL_NUMBER" name="too CARDINAL NUMBER">
 <pattern>
  <token>too</token>
  <token postag='CD'></token>
 </pattern>
 <message>Did you mean <suggestion>to <match no="2"/></suggestion>?</message>
 <example correction=''>We are expanding <marker>too ten</marker> new locations</example>
 <example>We are expanding to ten new locations</example>
</rule>
```

**Comment by MikeUnwalla** [comment]
@TediouslyBored,

Thanks for your rule. It will be in the LT snapshot (daily build) tomorrow. Refer to https://github.com/languagetool-org/languagetool/commit/a8a0ef1ba6554ef30d1128a4bd77a9cf6ad8ff6a. I made some changes, and I explain why:

- A marker in an example causes the text in the marker to have a green highlight in the GUI (when the user right-clicks an error and selects More).
- If a rule has a suggestion, each incorrect example must have a 'correction' attribute. Use 'testrules' (http://wiki.languagetool.org/development-overview#toc7) to find syntactic problems like that.
- A short message gives the user a little information about the type of the problem.
- Use an antipattern to prevent the rule from finding correct text.
- Put the postag in double quotes. That's just my personal preference, but I think that most rules use double quotes.

Thanks for your contribution. More are welcome.
