### ISSUE TITLE
LibreOffice dialog has tiny size and fonts

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#5584]
User screenshot, dialog is tiny compared to document font size:

![Bildschirmfoto von 2021-08-27 13-37-40](https://user-images.githubusercontent.com/857004/131122557-147b3a9f-31cd-4b7a-ae56-05f49230f14e.png)

* LibreOffice 7.0.6.2 with the latest version of Java
* Windows 10 64-bit and have a resolution of 2736x1824 (running on a Microsoft Surface Pro)

At start, the user gets this error:
![Java error](https://user-images.githubusercontent.com/857004/131122745-4a693890-7ee8-499c-bab2-70d33a5e2e2b.jpg)

@FredKruse, any idea what the problem might be?

**Comment by FredKruse** [comment]
The problem should be solved. Please test it with the new snapshot tomorrow

**Comment by danielnaber** [comment]
The customer reports that the font/dialog is still tiny, but the error has disappeared with the latest snapshot.

**Comment by FredKruse** [comment]
The issue should be solved. Can we close it?
