### ISSUE TITLE
Access to premium features over API

### ISSUE THREAD

**Issue by mhalano** [languagetool-org/languagetool#5587]
I subscribed to the premium plan and I would like to use this tool here: https://github.com/valentjn/vscode-ltex
The idea is to check the language using the premium features, but it needs some way to the program could be able to log in and do the queries using the premium features.

I added this issue [here](https://github.com/valentjn/vscode-ltex/issues/398) about this case.

**Comment by danielnaber** [comment]
Does vscode-ltex have fields for email and API key? If it doesn't, it would need to be added there.

**Comment by mhalano** [comment]
Yes, it has. But I just have the premium plan, not the plan with API access (which is expansive and cumbersome to me). The idea would be to have a way to authenticate with the public API and get the premium checks, the same way if I use the Firefox or Thunderbird extensions.

**Comment by mhalano** [comment]
May be offer API access to premium plan with more limitations as accessed over regular public API?

**Comment by danielnaber** [comment]
Please contact us at  support ..at.. languagetoolplus.com and we'll see what we can do.

**Comment by mhalano** [comment]
@danielnaber I just sent the email. Thank you for your help.

**Comment by T2brozz** [comment]
Is there a solution for this for everyone?
