### ISSUE TITLE
Premium with self hosted docker

### ISSUE THREAD

**Issue by DominikGeimer** [languagetool-org/languagetool#5591]
Hello,

is it possible to use a premium account, but with a self hosted Version (dicker).

Thanks
Dominik

**Comment by danielnaber** [comment]
Sorry, the Premium version is only available in the cloud and - for larger customers with 250+ users - as an on-premise version.

**Comment by DennisYildirim** [comment]
does it have the premium features? 

Enhanced grammar, punctuation and style checking
Up to 100,000 characters per text field
Suggestions to improve style and tone
Detection of incorrect names and titles in e-mails
Detection of incorrect numbers (e.g. IBAN, ISBN, ...)
Add-in for Microsoft Word
Add-on for Google Docs

Or does it simply do the simple basic grammar checks like in the free edition? 

Basic grammar, punctuation and style checking
Only up to 10,000 characters per text

**Comment by danielnaber** [comment]
For details about the premium version, please contact our support. You can find our email address at https://languagetool.org/legal.

**Comment by wokawoka** [comment]
I'm also wondering how it works with the self-hosted version, I'd much prefer to use the self-hosted version for privacy reasons but I would gladly pay for premium.

Just to be clear: could you confirm that the self-hosted version is limited in the number of characters per text field?
Thank you!

**Comment by danielnaber** [comment]
> could you confirm that the self-hosted version is limited in the number of characters per text field?

The self-hosted version has no limits, unless you configure them.

**Comment by wokawoka** [comment]
That's nice to hear. 
Then is the self-hosted version basically missing the enhanced grammar rules?
Thank you

**Comment by danielnaber** [comment]
> Then is the self-hosted version basically missing the enhanced grammar rules?

It is missing some rules. If your question is about the premium version, please contact our support (you can find the email at https://languagetool.org/legal).

**Comment by wokawoka** [comment]
My question was about the limitations of the self-hosted version. I guess that in this case the best thing to do is to install it again and test it myself.
Thank you!

**Comment by elandorr** [comment]
@wokawoka Did you figure it out after all? I'm wondering if the self-hosted is 100% identical to the one embedded in the main site. Like you, 'cloud' is an instant all caps 'no!' for us.

**Comment by wokawoka** [comment]
@elandorr Unfortunately I didn't have the time to install it yet, but I'm planning to do it as soon as I'll have some spare time during a weekend. I will try to post the results here.

**Comment by mishushakov** [comment]
@elandorr @wokawoka the results are identical indeed

**Comment by wokawoka** [comment]
@mishushakov thank you for the information. 
But did you mean that the self-hosted version outputs the same results of the "cloud" free version with the same limits in the amount of characters per text field?

In a reply above danielnaber did write:
>> The self-hosted version has no limits, unless you configure them.

I admit I'm still very confused.

**Comment by mishushakov** [comment]
@wokawoka there are no limits in the self-hosted version
the only difference is that their cloud version has premium spelling rules

you can configure your self-hosted installation to enable character limiting (which is disabled by default)

**Comment by wokawoka** [comment]
@mishushakov Thank you very much for the clarification!

**Comment by elandorr** [comment]
Thanks from me as well @mishushakov! I wonder what secret style rules the proprietary one holds.
