### ISSUE TITLE
[ru] баги по проверке текста с главной.

### ISSUE THREAD

**Issue by socketpair** [languagetool-org/languagetool#561]
Взял текст с главной - поместил на проверку. результат:

1. Не знает слова "типографика"

2. "Доступны ежедневные нетестированные сборки (cписок изменений)."
"нетестированные" написано не верно, "список"  написан не верно (первая буква английская)
но это к сайту, не к проверялке.

**Comment by yakovru** [comment]
В данном контексте слово «нетестированные» написано верно. Хотя возможно и раздельное написание в другом контексте (не тестированные разработчиками сборки).

**Comment by socketpair** [comment]
Если «нетестированные» написано здесь верно, то нужно чтобы LanguageTool не ругался на это.

**Comment by yakovru** [comment]
Исправлено.
Fixed.
