### ISSUE TITLE
[ru] Не может проверить диктант Бунина

### ISSUE THREAD

**Issue by socketpair** [languagetool-org/languagetool#562]
"А между клёнами синеют то там, то здесь в листве сквозной просветы в небо, что оконца." - вобще невнятную ошибку пишет.

"Почва под ногами, заросшая болотными травами, глубоко зыбится" -- туда же (про последнее слово).

"Словно вырубленных в отвесных скалах богатырским мечом Одина — бога войны" -- не знает бога Одина.

"Она пела много арий и романсов, по указанию Штольца" -- не знает известную фамилию.

"Старик подумал-подумал и говорит: «Мне ничего от тебя не надобно." -- "подумал-подумал".

Не знает слово "тестировщиков"

"Мы ищем IT-специалистов" -- тоже пишет ошибку

"В сетях с пропускной способностью до 10 Гбит/с" -- не знает про гигабиты.

"Отсутствие ограничений по минимальному объему закупок." -- бредовую ошибку про "по-минимальному" пишет...

"Войдите в веб-интерфейс" -- тоже ошибка.

"IP-адрес" -- тоже не понимает.

Ну ё-моё! Уж диктанты-то должно проходить.

**Comment by yakovru** [comment]
Много устаревших слов или неологизмов. 
Я сомневаюсь, что Бунин писал: «Мы ищем IT-специалистов».
Исправлено.
Fixed.

**Comment by socketpair** [comment]
Про айти-специалистов -- это, конечно, не  Бунин. Но началось с него.
