### ISSUE TITLE
Capitalization error not found: "effizientes arbeiten"

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#5621]
LanguageTool does not detect the capitalization error in this sentence:

> Effizientes arbeiten ist essenziell.

**Comment by Discostu36** [comment]
LT seems to have general problems with substantiations, see #5548 for an example with an adjective.

**Comment by udomai** [comment]
@Discostu36, thanks for spotting this!

We are working on two different ways of tackling this very broadly.

This context, though, seems nice and clear-cut. I wonder what if a pattern like this could work:

```xml
    <token postag="ADJ.*NEU.*" postag_regexp="yes"/>
    <marker>
    <token postag="VER:INF.*" postag_regexp="yes">\p{Ll}.*</token>
    </marker>
    <token postag="VER.*[123].*" postag_regexp="yes"/>
```

… looking into it :)

**Comment by Discostu36** [comment]
Your rule is very specific for sentence start. It will not help in a case like

> Unsere Software ist perfekt für effizientes arbeiten.

Should I open a separate issue for it?

**Comment by udomai** [comment]
I'll take care of that, thank you! I'll divide it into different nominalized parts of speech.

A little thought:

> Wir möchten Gutes tun.
> Nicht immer wird gutes Tun belohnt.

**Comment by udomai** [comment]
https://github.com/languagetool-org/languagetool/issues/5626
