### ISSUE TITLE
[ru] Он хотел избежать службу в армии.

### ISSUE THREAD

**Issue by socketpair** [languagetool-org/languagetool#563]
Ворд исправляет на:

"Он хотел избежать службЫ в армии."

Описание правила не вспомню. но это лишь пример,  это не особая фраза.

**Comment by yakovru** [comment]
Ну так это ошибка MS Word.
Incorrect.

**Comment by socketpair** [comment]
А я так не считаю, и считаю, что MS Word прав. что делать?

**Comment by yakovru** [comment]
Пример неудачный. Я решил, что вопрос о типовой ошибке Word: 
https://ru.wikipedia.org/wiki/Microsoft_Word
когда предлагаемый вариант исправления меняет смысл фразы.

**Comment by yakovru** [comment]
Должно быть такое правило:
Избежать встречи – correct (родительный падеж)
Избежать встречу – incorrect (винительный падеж)

**Comment by socketpair** [comment]
Совершенно точно! можно переоткрыть ишью ?

**Comment by yakovru** [comment]
Правило создано!

**Comment by socketpair** [comment]
Супер!
