### ISSUE TITLE
[en] Oxford comma

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#564]
It is a very common error not to use Oxford comma for non-native speakers (e.g. in Russian similar comma is a grammar error, so I was not using it for many years in English too). 

WRONG For review, test and improve rules...
CORRECT For review, test, and improve rules, 

Cases, where you should not use Oxford comma, looks to be quite rare, still they can be found. So it should be more kind of warning, not an error message, e.g.: "You have probably missed an Oxford comma" I believe that native speaker can probably find some antipatterns.

**Comment by Hrxn** [comment]
I don't think that there really is a consensus on the proper usage of the oxford comma.. ;-)

**Comment by MikeUnwalla** [comment]
Oxford comma is a style preference (https://en.wikipedia.org/wiki/Serial_comma). 

I can probably make a simple rule, but refer to the Wikipedia article to see some of the complexities of the problem.

**Comment by kostyfisik** [comment]
Many non-native speakers do not even understand, that it can be a problem here. As soon as it is a style preference it should be a warning, not an obligation from  LT.

Actually, as soon as in the provided example all 3 actions are related to the same object I believe that coma should be present.

**Comment by f-knorr** [comment]
I support the idea of having a rule for the serial comma. Here is a first **simple** attempt:
<rule id="SERIAL_COMMA" name="serial comma (a, b>>,<< and c)">
    <antipattern>
        <token skip="-1">and</token>
        <token regexp="yes">,|and</token>
    </antipattern>
    <pattern>
        <token postag="NN.*" postag_regexp="yes"><exception scope="previous">and</exception></token>
        <token>,</token>
        <token regexp="yes" min="0">my|your|his|her|our|their|a|an|the|these|those|some|many|most|in|at|with</token>
        <marker><token postag="NN.*" postag_regexp="yes"/></marker>
        <token>and</token>
        <token regexp="yes" min="0">my|your|his|her|our|their|a|an|the|these|those|some|many|most|in|at|with</token>
        <token postag="NN.*" postag_regexp="yes"></token>
    </pattern>
    <message>In American English, a majority of style guides mandate use of the serial comma here: <suggestion>\4,</suggestion></message>
    <url>https://en.wikipedia.org/wiki/Serial_comma</url>
    <example correction="president,">She took a photograph of her parents, the <marker>president</marker> and the vice president.</example>
    <example correction="German,">She speaks Spanish, <marker>German</marker> and French.</example>
    <example>She lived in France, Italy, and Spain.</example>
    <example>Irina, a singer and actress, was born in Poland.</example>
</rule>

@MikeUnwalla Would be great if you could check the rule and commit it, if you consider it sufficient.

**Comment by MikeUnwalla** [comment]
Thanks @f-knorr. I used your rule in the rulegroup SERIAL_COMMA_ON. Refer to https://github.com/languagetool-org/languagetool/commit/81bc2dd48b9a1447b752a6692047739989d729bc.

**Comment by danielnaber** [comment]
This causes a lot of matches, see https://languagetool.org/regression-tests/20161004/result_en_20161004.html. Are we sure this should be active by default? If so, can we rephrase the error to be more helpful, i.e. letting the user know this is more of a style choice?

**Comment by janschreiber** [comment]
Also, these two matches in the regression test look like false positives:

- ...ternational became polarised into two camps, with Marx and Bakunin as their respective figureheads.
- Generally who visits their parents the most, sons or daughters?

**Comment by MikeUnwalla** [comment]
I had forgotten that style rules are usually off. Later today, I'll look at the false positives and the message.

As a minimum, I'll make the rule inactive by default.

**Comment by kostyfisik** [comment]
This again leads to #545  - as soon as there is no way to switch on rules at the web-site and for browser plugin many users will never get aware about its presence in LT.

**Comment by f-knorr** [comment]
I think we should move the rule to the American English grammar.xml.  
There, however, I recommend to activate it by default. (According to Wikipedia "in American English, a majority of style guides mandate use of the serial comma, including APA style, The Chicago Manual of Style, The MLA Style Manual, Strunk and White's Elements of Style, and the **U.S. Government Printing Office Style Manual**."). I think this would be most appropriate for users running LT with American English.

Here is a modified rule which - hopefully - does no longer trigger false positives (I have also modified the suggestion):

```
            <rule>
                <antipattern>
                    <token skip="-1" regexp="yes">and|or</token>
                    <token regexp="yes">,|and|or</token>
                </antipattern>
                <antipattern>
                    <token postag="RBR|RBS" postag_regexp="yes"/>
                    <token>,</token>
                    <token regexp="yes" min="0">my|your|his|her|our|their|a|an|the|these|those|some|many|most</token>
                    <token postag="NN.*" postag_regexp="yes"/>
                    <token regexp="yes">and|or</token>
                </antipattern>
                <antipattern>
                    <token postag="NNP"/>
                    <token regexp="yes">,</token>
                    <token regexp="yes" min="0">my|your|his|her|our|their|a|an|the|these|those|some|many|most</token>
                    <token postag="NN.*" postag_regexp="yes"><exception postag="NNP"></exception></token>
                    <token regexp="yes">and|or</token>
                </antipattern>
                <antipattern>
                    <token>on</token>
                    <token>the</token>
                    <token>other</token>
                    <token>hand</token>
                    <token>,</token>
                    <token regexp="yes" min="0">my|your|his|her|our|their|a|an|the|these|those|some|many|most</token>
                    <token postag="NN.*" postag_regexp="yes"/>
                    <token regexp="yes">and|or</token>
                </antipattern>
                <antipattern>
                    <token postag="SENT_START"/>
                    <token regexp="yes" skip="-1">While|Since|After|With|In|Here|</token>
                    <token>,</token>
                    <token regexp="yes" min="0">my|your|his|her|our|their|a|an|the|these|those|some|many|most</token>
                    <token postag="NN.*" postag_regexp="yes"/>
                    <token regexp="yes">and|or</token>
                </antipattern>
                <pattern>
                      <token postag="NN.*" postag_regexp="yes"><exception scope="previous">and</exception></token>
                      <token>,</token>
                      <token regexp="yes" min="0">my|your|his|her|our|their|a|an|the|these|those|some|many|most</token>
                      <marker>
                          <token postag="NN.*" postag_regexp="yes"/>
                          <token regexp="yes">and|or</token>
                      </marker>
                      <token regexp="yes" min="0">my|your|his|her|our|their|a|an|the|these|those|some|many|most</token>
                      <token postag="NN.*" postag_regexp="yes"></token>
                </pattern>
                <message>In American English, a majority of style guides mandate use of the serial comma (Oxford comma, Harvard comma). Please check, whether the serial comma is missing: <suggestion>\4, \5</suggestion></message>
                <url>https://en.wikipedia.org/wiki/Serial_comma</url>
                <short>Serial comma: missing</short>
                <example correction="German, and">She speaks Spanish, <marker>German and</marker> French.</example>
                <example correction="president, and">She took a photograph of her parents, the <marker>president and</marker> the vice president.</example>
                <example correction="water, or">Would you like tea, coffee, <marker>water or</marker> wine?</example>
                <example correction="car, or">How will you go to the city? Will you use my car, your <marker>car or</marker> the train?</example>
                <example>She speaks Spanish, <marker>German, and</marker> French.</example>
                <example>Irina, a singer and actress, was born in Poland.</example>
                <example>They became polarised into two camps, with Marx and Bakunin as their respective figureheads.</example>
                <example>The International Time Bureau began a time scale, Tm or AM, in July 1955, using both local caesium clocks and ...</example>
                <example>Generally who visits their parents the most, <marker>sons or</marker> daughters?</example>
                <example>While he was growing up, his <marker>father and</marker> Nick Bollettieri trained him in this way.</example>
                <example>Since being introduced by Portuguese in the 16th century, <marker>maize and</marker> manioc have replaced traditional African...</example>
                <example>Which do you like better, <marker>summer or</marker> winter?</example>
                <example>With the rise of space tourism, NASA and the Russian Federal Space Agency agreed to use...</example>
                <example>On the other hand, consonants and vowels are written as independent letters.</example>
                <example>In spite of their various differences, Joan and Ann are friends.</example>
                <example>In addition to buses, Calgary and Edmonton operate light rail transit systems.</example>
                <example>It was Branchus, son or lover of Apollo.</example>
                <example>His father was Hermann Einstein, a salesman and engineer.</example>
                <example>Recorded by Ptolemy, the geographer and astronomer from Alexandria</example>
                <example>I like both chips and <marker>eggs and pie</marker> and peas.</example><!-- TODO -->
            </rule>
```

Since I have no access to my Linux machine, it would be great if someone could commit the rule...

**Comment by MikeUnwalla** [comment]
@f-knorr, thanks.

I disagree strongly about putting the rule into the American English grammar.xml, because the rule is applicable to British English and possibly to other variants. The Oxford Manual of Style is a credible style guide for British English. The serial comma (Oxford comma) is a style preference that is applicable to BrE and AmE.

@danielnaber, the new rule decreases the number of false positives. If I put the rule into the default grammar.xml, we still have the problem that @kostyfisik mentions.

- What is a sufficiently low percentage of false positives such that I can set the rule on by default?
- Is there a way to run the rule against Wikipedia before I commit the rule, so that I can find the percentage of false positives?

**Comment by danielnaber** [comment]
You could use `java -jar languagetool-wikipedia.jar check-data` (from https://languagetool.org/download/snapshots/LanguageTool-wikipedia-20161004-snapshot.zip) to run on a local XML dump of Wikipedia which you can download from e.g. https://dumps.wikimedia.org/enwiki/20161001/ (`enwiki-20161001-pages-meta-current...`)

I don't feel I can give a percentage, though.

**Comment by kostyfisik** [comment]
I believe that rule should be switch on by default if you see the ratio "false positive"/"real errors"<1 :)

**Comment by f-knorr** [comment]
I agree with kostyfisik (provided that the number of false positives is sufficiently low).

**Comment by MikeUnwalla** [comment]
@f-knorr , I put one antipattern into comments, because it causes too many false negatives. Refer to the examples in https://github.com/languagetool-org/languagetool/commit/90b9391b7f0c38d3167e210fb5a215ccf578fe44.

For the reasons I gave previously, I did not move the rule to American English grammar.xml.

The rule still gives many false positives, so I set it to inactive by default (sorry @kostyfisik).

**Comment by f-knorr** [comment]
@MikeUnwalla : Hi Mike, I have put some effort into improving the rule (SERIAL_COMMA_ON). I hope the number of false positives is now acceptable. (However, this comes at the price of more false negatives). I would really appreciate your opinion on my changes.
BTW, I have added another rule COMMA_BEFORE_AND which is off by default.

**Comment by MikeUnwalla** [comment]
@f-knorr , thanks. The rule is good.

I found a few false positives, but there are not many compared to the errors that the rule finds.
