### ISSUE TITLE
dialog box often covers the mistake when using an iframe

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#5656]
The dialog box most of the time covers the mistake detected. That is not convenient.
![image](https://user-images.githubusercontent.com/8479998/132865192-5240b35b-9d5f-4490-8965-4177d52e17cd.png)

**Comment by danielnaber** [comment]
Which website does this happen on? Which text can be used to reproduce it?

**Comment by baarsrj** [comment]
It is in a local page, in an iframe. It looks like the message box aligns with the top of the iframe. After some testing resizing the text area, I think it does that when there is not enough vertical space to show it in full.

**Comment by danielnaber** [comment]
Which version of the add-on do you use? A new one (4.2.2) is being released right now, and you might already have it or not.

**Comment by baarsrj** [comment]
4.1.0. Iĺl check again when the update is available.

**Comment by danielnaber** [comment]
Is this still valid or can it be closed?
