### ISSUE TITLE
[ru] неоправдано находит ошибку.

### ISSUE THREAD

**Issue by socketpair** [languagetool-org/languagetool#566]
"Сторожевые посты из крестьян стояли метрах в пятидесяти друг от друга вдоль полотна."

http://russkiy-na-5.ru/articles/644

Также, если взять ошибочный текст с сайта, то LanguageTool не нашёл ни одной пунктуационной ошибки, а должен.

Вообще, не плохо бы чтобы LanguageTool находил все ошибки, которые нашли люди. Не плохой сайт для того чтобы оценить возможности LanguageTool. Правда там не говорится где именно ошибки...

**Comment by socketpair** [comment]
Также, если взять ошибочный текст с сайта, то LanguageTool не нашёл ни одной пунктуационной ошибки, а должен.

**Comment by yakovru** [comment]
Если в тексте есть орфографические ошибки, то вероятность обнаружения пунктуационных ошибок уменьшается...

**Comment by socketpair** [comment]
Согласен, понимаю почему, однако не обнаруживаются ошибки, а так же неправильно обнаруживаются ошибки в предложениях, где с орфографией всё в порядке.

**Comment by kostyfisik** [comment]
@socketpair  Созданием для русского языка правил, которые ищут ошибки, занимается всего несколько человек на добровольных началах. Если вы сможете придумать правило, которое ищет ваши ошибки  (и не находит их в правильных текстах) - с удовольствие его добавим. Проблема ложных срабатываний одна из самых серьёзных, пока не попробуешь - не понимашь насколько наш язык на самом деле разнообразен). Для начала создать правило можно попробовать тут http://community.languagetool.org/ruleEditor/expert 
о том как задаются правила можно почитать тут http://wiki.languagetool.org/development-overview и тут http://wiki.languagetool.org/tips-and-tricks 

Если это выглядит слишком сложно - можно помочь создавая описания ошибок (как тех, которые LT еще не находит, так и о тех, которые LT находит там, где их нет) Например, вот #470 или вот #564

**Comment by socketpair** [comment]
Прекрасно понимаю. Иначе бы не контрибутил в этот проект. Помогаю как могу -- если найду время чтобы разобраться как пишутся правила -- сделаю пулл-регвест.

**Comment by yakovru** [comment]
Most error fixed, but for commas in the participle phrases I make new issue:
https://github.com/languagetool-org/languagetool/issues/584
