### ISSUE TITLE
[en] False positive "these" suggestion in "this fixes issue with ..."

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#5671]
`This fixes issue with empty selection in the tree.`

![image](https://user-images.githubusercontent.com/122009/133251816-410dd6e0-60f6-4e59-9756-aed47c483d07.png)

The actual problem is a missing article (which LT also detects, but for some reason suggests only `the`, while `an` could also be appropriate). But I think `this->these` shouldn't be suggested here at all, as it doesn't result in a meaningful sentence.

**Comment by tiff** [comment]
this is fixed as of yesterday
