### ISSUE TITLE
User interface 

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#5677]
![afbeelding](https://user-images.githubusercontent.com/8479998/133412923-1f0cd19f-a4a6-404a-9a29-5de46f41ec50.png)
A rule is falsely triggered, but that is not the issue; the issues are:
- the rule is listed as prem:ZAL_ZUL[1], while it is not in the premium set, but in OS
- there is a dialog item (i), that shows 'details...' when hovered over, but there is no info, nor can it be clicked.

**Comment by tiff** [comment]
@baarsrj second one is actually a bug. Thanks for reporting. Should be fixed soon

**Comment by baarsrj** [comment]
Why is the rule mentioned as prem: ? Is that because currently Premium is activated?

**Comment by tiff** [comment]
On the website, we still have some open-source rules marked as Premium. This is from a time when we didn't have a Premium version for Dutch.

**Comment by baarsrj** [comment]
Ah, I never knew this.
