### ISSUE TITLE
[pt-br] user feedback "de certo composto"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#5678]
### User says:

O language tool pede para que eu mude "de certo composto" para "decerto composto", sendo que na frase, "de certo" significa "de terminado", assim a sugestão estaria incorreta.

As duas formas – de certo e decerto – existem na Língua Portuguesa.

Ou seja, ambas as expressões estão corretas, devendo, no entanto, serem usadas em diferentes situações.

De certo é uma expressão significa de correto; de determinado; de verdadeiro.

"Conversar de certo assunto implica conhecimento. O que sei de certo sobre isso é pouco."

Decerto significa com certeza; certamente. Pode ter um sentido irônico e ser uma interjeição que exprime dúvida ou o contrário daquilo que se afirma.

"Decerto está senil."

**Comment by marcoagpinto** [comment]
@tiff 

I will have a look at it tomorrow at 5am.

**Comment by marcoagpinto** [comment]
Fixed!
