### ISSUE TITLE
[en] Do not show mid-sentence or end-sentence proper nouns as spelling mistakes

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#568]
The spelling rule ignores some proper nouns, but not all. LT identifies 'Hoopes' as an NNP. Can the rule be made to ignore uppercase NNP that occurs in the middle or at the end of a sentence? (Uppercase only, because the rule usually correctly shows lowercase NNP as a possible spelling error.)

![mid-sentence-nnp](https://cloud.githubusercontent.com/assets/5816160/19107973/9bf7b9d6-8ae6-11e6-9533-e3ccd7312c5f.png)

**Comment by f-knorr** [comment]
You can write a disambiguation-rule for this purpose:
```
    <rule name="Ignore spelling of NNP" id="IGNORE_SPELLING_OF_NNP">
      <pattern case_sensitive="yes">
        <token><exception postag="SENT_START"/></token>
        <marker>
          <token postag="NNP" regexp="yes">[A-Z][a-z]+</token>
        </marker>
      </pattern>
      <disambig action="ignore_spelling"/>
    </rule>
```
I do not understand why you want to limit the rule to mid-sentence NNPs. Wouldn't it make sense to exclude all NNP from spell-checking? (In this case, just delete `<token><exception postag="SENT_START"/></token>`)


![scr](https://cloud.githubusercontent.com/assets/16450958/19418372/dce61d90-93c2-11e6-8aed-67fff133b77a.png)

**Comment by MikeUnwalla** [comment]
@f-knorr , thanks for your rule. I had forgotten about ignore_spelling.

If the rule excludes NNPs that start a sentence, then LT will not find incorrect text such as 'Hoopes, coils, and other types of loop...' I think that we will have to accept the incorrect warnings for this type of problem.

If we exclude only mid-sentence and end-sentence NNPs, then LT does not find incorrect text such as 'These coils, Hoopes, and other types of loops are ...' This type of error is probably very rare (compared to the false warnings for NNPs).

I will do tests with the Wikipedia corpus, and if there are not many false negatives, I will add the rule.
