### ISSUE TITLE
Nightly test and html codes

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#5697]
There are quite some falses caused by the nightly test text because these contain HTML code. Why are those (valid ones) not removed before testing?

**Comment by danielnaber** [comment]
Could you send some examples?

**Comment by baarsrj** [comment]
De  ahadieth die geselecteerd zijn om dit boek samen te stellen zijn  gehaald uit de meest betrouwbare verzamelwerken zoals de Sahieh van  al-Boekharie &amp; de Sahieh

(Here it does not show the error, but look: )

![afbeelding](https://user-images.githubusercontent.com/8479998/133888472-c130391e-e852-460f-9012-8743bfa143dc.png)

**Comment by danielnaber** [comment]
There were only 3 such cases in more than 200,000 sentences, but I have removed them now.

**Comment by baarsrj** [comment]
That is not much. I just accidentally ran into them trying to check the 'full' for falses.
