### ISSUE TITLE
[nl] morfologik mistake (bug?)

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#5698]
Watergate en

This triggers a spelling error in Dutch. I do not understand why.

**Comment by danielnaber** [comment]
That's because `Watergate` is not in the NL dictionary.

**Comment by baarsrj** [comment]
Fine, but why is the 'en' also underlined?

**Comment by danielnaber** [comment]
Because there's logic in the speller that tries to find out if there are better suggestions if both words are considered. That mostly helps, but not always.

**Comment by baarsrj** [comment]
Ah.
