### ISSUE TITLE
[ru] Заменить компьютер на калькулятор.

### ISSUE THREAD

**Issue by socketpair** [languagetool-org/languagetool#570]
`Заменить компьютер на калькулятор.`

Я не согласен, но вроде по правилам, следует писать:

`Заменить компьютер калькулятором.`

Ворд такое находил. Насколько это соответствует нормам и т.п. я не знаю, не эксперт.

**Comment by yakovru** [comment]
Не нашёл такого правила. 
А поиск по библиотеке (http://aot.ru/cgi-bin/search.cgi) нашёл 2311 примеров с похожими фразами «заменить Х на У».
Word на похожих примерах даёт ошибку «Предлог 'на' не связан с существительным или местоимением». То есть это недоработка Word.
Скорей всего вариант 
> Заменить компьютер калькулятором.

предпочтительный, но и 
> Заменить компьютер на калькулятор.

допускается.
