### ISSUE TITLE
false reports from nightly test

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#5700]
It looks like sentences that are fed from the test, sometimes come in a combination that has no space after the first sentence. This causes false reports:

ADD#2 | java | SENTENCE_WHITESPACE[] | Tussen zinnen hoort witruimte  Accepteer  cookies Zo organiseer en leid ik intervisiesessies waar de onderzoekers de  voortgang van hun projecten presenteren en lees ik mee met  conceptrapporten om zodoende de kwaliteit van onderzoek te waarborgen.    FA? | Accepteer | Accepteer
-- | -- | -- | -- | -- | --
ADD#3 | java | SENTENCE_WHITESPACE[] | Tussen zinnen hoort witruimte  Advies, christian wanneer de criticus en dit heet een meer dan een bruid!    FA? | Advies | Advies
ADD#4 | java | SENTENCE_WHITESPACE[] | Tussen zinnen hoort witruimte  Advies en (re)organisatie op maat.    FA? | Advies | Advies
ADD#5 | java | SENTENCE_WHITESPACE[] | Tussen zinnen hoort witruimte  Akkoord Vragen over op o.a. Marktplaats aangeboden boten, waarbij een link naar deze site staat, ga ik niet beantwoorden.    FA? | Akkoord | Akkoord
ADD#6 | java | SENTENCE_WHITESPACE[] | Tussen zinnen hoort witruimte  Akkoord Elk van onze arbeiders zijn gewerkt op dit gebied 4-5 minstens jaar.    FA? | Akkoord | Akkoord
ADD#7 | java | SENTENCE_WHITESPACE[] | Tussen zinnen hoort witruimte  Al een twintigtal ziekenhuizen - algemene en universitaire - doen mee.    FA? | Al | Al
ADD#8 | java | SENTENCE_WHITESPACE[] | Tussen zinnen hoort witruimte  Alle knoppen en aansluit punten van je toestel blijven volledig bruikbaar met dit hoesje.    FA? | Alle | Alle
ADD#9 | java | SENTENCE_WHITESPACE[] | Tussen zinnen hoort witruimte  Alle genoemde prijzen waren dan gewonnen.    FA?

**Comment by danielnaber** [comment]
I don't think these are false reports, it's just difficult to interpret them without the previous sentence. Input looks like this:

`lastenboeken, enzovoort.Al een twintigtal`

So, the message that suggests adding a space seems okay.
