### ISSUE TITLE
[nl] better translation

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#5701]
ADD#1 | java | DOUBLE_PUNCTUATION[] | Twee opeenvolgende punten  Of bakker, loodgieter, leraar..noem maar op.    FA?
-- | -- | -- | --

The message could better be: 
Twee of meer opeenvolgende punten. Het beletselteken (…) heeft er altijd drie.

**Comment by danielnaber** [comment]
You can change that yourself at https://webtranslateit.com/en/projects/21275-LT-Core/locales/en..nl/strings?utf8=%E2%9C%93&object=&s=Twee+opeenvolgende+punten&ignore_case=on

**Comment by baarsrj** [comment]
done
