### ISSUE TITLE
[DE]Fehlalarm Satzanfang "wörtliche Rede"

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#5702]
Moin liebes LanguageTool-Team

Er sagte: „**Essen** gehen.“
LT: "In der Wendung ‚essen gehen‘ wird „essen“ kleingeschrieben."

Grüße Dallun511

**Comment by udomai** [comment]
Danke @MasterDallun511 für den Hinweis! Sollte morgen nicht mehr passieren.
