### ISSUE TITLE
[fr] lemma of some adjectives

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#5710]
Many adjectives in French have an infinitive as a lemma:
```
grisé	griser	J m s
grisés	griser	J m p
grisée	griser	J f s
grisées	griser	J f p
```
In many cases, this is annoying. For example, to get the right suggestions in some rules. The expected lemma is:
```
grisé	grisé	J m s
grisés	grisé	J m p
grisée	grisé	J f s
grisées	grisé	J f p
```
The infinitive is correct when the form is a past participle:
```
grisé	griser	V ppa m s
grisés	griser	V ppa m p
grisée	griser	V ppa f s
grisées	griser	V ppa f p
```
Probably, we should check and change all these lemmas systematically.

**Comment by jaumeortola** [comment]
There are ~26.000 forms of adjectives with this problem. I favor doing the change: the lemma should be the masculine singular form, not an infinitive.

**Comment by udomai** [comment]
Sounds perfectly reasonable! The base form of a `J` should be a `J`, even when it's deverbal. Is this a huge endeavor in terms of time? We should weigh costs against benefits, since we'll probably have other things on our wishlist for the coming Q4.

**Comment by jaumeortola** [comment]
I am going to do it now because I have all the details in my head.
