### ISSUE TITLE
[nl] another Morfologik speller issue

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#5718]
The word trans-Atlantische is in the dictionary.
Trans-Atlantische is not recognized, however.

**Comment by jaumeortola** [comment]
I guess this has to be solved in the tagger. What would be the specification, the rule? Something like capitalized words that are camel case with hyphen?
In general, camel case words cannot be capitalized (we accept `iPhone`, but not `IPhone`). 
If they are few words, they could be added one by one to the dictionary. If they are many, then we need to do it in the tagger.

**Comment by baarsrj** [comment]
This is not camel case (for Dutch). The hyphen is special. There are not a lot of words like this. Adding to the speller file is most convenient, I guess.
