### ISSUE TITLE
[ru] many users complaining about spelling mistakes

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#5742]
@yakovru we have plenty of users that complain that the speller is now marking words as wrong that are actually correct.
This can also be seen in the regressions for Russian:
https://internal1.languagetool.org/regression-tests/via-http/2021-09-26/ru/ 

Scroll down to MORFOLOGIK_RULE_RU_RU

**Comment by yakovru** [comment]
I see.
I'll rebuild the dictionary.
