### ISSUE TITLE
[DE] Fehlalarm Zeichsetzung

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#5749]
Moin liebes LanguageTool-Team

So was gibt es nicht**.**
LT: "Eine Frage bitte mit einem ‚?‘ abschließen, eine Aufforderung mit einem ‚!‘ oder ‚.‘"

Dies ist keine Frage oder Aufforderung.

Grüße Dallun511

**Comment by udomai** [comment]
Danke für den Hinweis, @MasterDallun511!
