### ISSUE TITLE
[LibreOffice] Spaces around cross references are considered redundant

### ISSUE THREAD

**Issue by kewisch** [languagetool-org/languagetool#575]
I've reported this in the [forum](http://forum.languagetool.org/t/redudent-spaces-rule-triggered-when-adding-cross-reference-and-a-false-positive) already, but I thought I'd file an issue so that others searching for it have something to follow in case there is progress.

I am using cross references to reference another chapter. This prompts Language Tool to complain because of the spaces around the reference. I assume this is because the chapter reference does not count as a word.

Example:

```
In Chapter [3.5.2] you can read more about this bug
          ~~~~~~~~~
```

**Comment by FredKruse** [comment]
The MultipleWhitespaceRule handles now LO/OO functions like cross references.
The issue can be closed.

**Comment by FredKruse** [comment]
The issue is solved (I tested it)
