### ISSUE TITLE
[DE] Fehlalarm: „dass sog.“

### ISSUE THREAD

**Issue by NicoWeio** [languagetool-org/languagetool#5754]
> Es ist ausgeschlossen, **dass** sog. Dateikonflikte entstehen.

liefert 

> Meinten Sie „das“? Die Subjunktion ‚dass‘ scheint an dieser Stelle nicht zu passen.

Wohingegen „z. B.“ keinen Hinweis hervorbringt:

> Es ist ausgeschlossen, dass z. B. Dateikonflikte entstehen.

**Comment by udomai** [comment]
Danke für den Hinweis, @NicoWeio! Da kam das System durcheinander, weil "sog" eine Form von "saugen" ist. Ist ab morgen gefixt!

**Comment by NicoWeio** [comment]
So ähnlich hatte ich es mir auch überlegt – danke! 😁

**Comment by NicoWeio** [comment]
So ähnlich hatte ich es mir auch überlegt – danke! 😁
