### ISSUE TITLE
[DE] Fehlalarm "mit gewaltiger Kraft den Einkaufswagen"

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#5770]
Moin liebes LanguageTool-Team

Er zog mit gewaltiger Kraft den Einkaufswagen.
LT: "Die Präposition ‚den‘ erfordert standardsprachlich den Genitiv."

Ich verstehe die Regel nicht, aber das muss ich auch nicht. Sie ist hier nicht gültig, weil "mit gewaltiger Kraft" Dativ und "den Einkaufswagen" Akkusativ ist.

Grüße Dallun511

**Comment by udomai** [comment]
Danke für den Hinweis, @MasterDallun511! Du hast voll und ganz recht. Ich habe mal ein Antipattern gebaut, damit die Regel nicht mehr matcht, wenn davor ein Adjektiv, Possessivpronomen o.ä. steht, dass zu "Kraft" passt. Und ich habe dein Beispiel zum Testen geklaut.

**Comment by MasterDallun511** [comment]
> 
> 
> Danke für den Hinweis, @MasterDallun511! Du hast voll und ganz recht. Ich habe mal ein Antipattern gebaut, damit die Regel nicht mehr matcht, wenn davor ein Adjektiv, Possessivpronomen o.ä. steht, dass zu "Kraft" passt. Und ich habe dein Beispiel zum Testen geklaut.

Ich habe mich schon im LanguageTool verewigt und es gibt meines Wissens dutzende Beispiele von mir, die ruhig im LanguageTool verbleiben können. Deswegen ändere ich die Beispiele immer etwas ab, damit sie neutral bleiben.

**Comment by udomai** [comment]
Notiz: Das AP behebt auch bestimmte Fehlalarme, wenn das Problem ein fehlendes Komma ist:

> Mir fehlt die **Kraft den Einkaufswagen** den Berg hochzuschieben.
