### ISSUE TITLE
[LibreOffice add-on] Hangs on exit

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#5773]
Hello!

For weeks that this has happening.

When I am closing my thesis ~445 pages on LibreOffice:
**Version: 7.2.1.2 (x64) / LibreOffice Community
Build ID: 87b77fad49947c1441b67c559c339af8f3517e22
CPU threads: 12; OS: Windows 10.0 Build 19043; UI render: Skia/Vulkan; VCL: win
Locale: en-GB (en_GB); UI: en-GB
Calc: CL**

It hangs. The cursor becomes circling, and I have to close LibreOffice in the close gadget of the window.

**Comment by FredKruse** [comment]
A lot of work is done in 5.5.1 and 5.6 to increase stability of the extension. Please test, if the bug occur in the latest version.

**Comment by marcoagpinto** [comment]
@FredKruse 

It still hangs with the ~445-page thesis.

Tested with LibreOffice 7.3.0.1 and Windows 10.

Tested with the latest nightly.

**Comment by FredKruse** [comment]
The bug is (hopefully) solved. Please test it with the tomorrow snapshot.

**Comment by marcoagpinto** [comment]
It seems to be fixed.

Thanks!
