### ISSUE TITLE
[en] "Evident" has an NN reading

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#5776]
According to https://www.oxfordlearnersdictionaries.com/definition/english/evident?q=evident, it can only be an adjective

`As widely evident, it is not just the regime's claim`

![image](https://user-images.githubusercontent.com/122009/135823117-ba119297-fa83-4a20-8b45-341c0d531105.png)

**Comment by udomai** [comment]
Agreed. Some of these tags are in there because of edge-case reasoning:

> The plausible must never supplant the evident.

By that logic, all `JJ`s would need an extra `NN` tag – which makes no sense.

**Comment by tiff** [comment]
I have removed "NN" from "evident" and "NNS" from "evidents". We usually do not have noun tags on pure adjectives
