### ISSUE TITLE
Add JSON output to command-line LT

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#578]
Provide a JSON output for LT (--json) in the command-line because the XML output (--api) has been deprecated.

**Comment by jaumeortola** [comment]
@danielnaber @milekpl @arysin @dpelle 
Do we need to keep the --line-by-line option in the JSON output? If we keep it, the code gets a little more complicated, and I don't know if it makes sense.
I use the XML/JSON output for files up to ~100.000 words. For larger documents I use the plain text output with the --line-by-line option.

**Comment by dpelle** [comment]
@jaume:
> Do we need to keep the --line-by-line option in the JSON output? 

I must admit that I don't know for sure what this option does. Usage with --help says:

 --line-by-line           work on file line by line (for development, e.g. inside an IDE)

That's not very clear to me. Ah, I suppose that it's for interactive use to show the errors
as soon and the line is entered before the end of the input.  I don't never use that.
I would say that when using --api (or its equivalent option of json) it does not really
make sense anymore.

I just tried with the --api and with/without --line-by-line and I see that --line-by-line
changes the  line number in the reported errors?!  Isn't that a bug?

Example:

```
$ cat test.txt
This is an error error.
This is is another error.
```

`$ java -jar languagetool-standalone/target/LanguageTool-3.6-SNAPSHOT/LanguageTool-3.6-SNAPSHOT/languagetool-commandline.jar -c utf-8 -l en-US --api  test.txt`

shows errors at lines 0 and 1.
If I add the --line-by-line option, it shows errors at line 1 and 2.  Is that expected?

In any case, I never used that option and did not know about it until now.

**Comment by jaumeortola** [comment]
With "--line-by-line" the input text is read and analyzed by chunks (paragraphs). If I am right, this is needed for analyzing very large text corpus in order to avoid performance issues. (I don't understand why the help says "e.g. inside an IDE").

At the moment, I am not going to implement "--json" + "--line-by-line", unless someone says it is necessary.

**Comment by jaumeortola** [comment]
Done here: https://github.com/languagetool-org/languagetool/commit/aa8c40a735d5e8ad3e748666c5400967df55e3bb
