### ISSUE TITLE
Attempt for a verb agreement rule in portuguese

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#5795]
The sentence "A realidade das pessoas mostram" is not corrected to "A realidade das pessoas mostra" and my guess is that it is because it is hard not to capture false alarms as in "A vida e a realidade das pessoas mostram" where the verb in the plural is correct. But "A realidade das pessoas mostram" must be captured as wrong, as the verb agreement is not going to the head of the subject when it must go.

Thus I elaborated a rule that captures only when this situation occurs at the beginning of a sentence.
So I tried the rule editor at the languagetool site and came up with this:
```
<!-- Portuguese rule, 2021-10-08 -->
<rule id="CONCORDANCIA_COM_NUCLEO_DO_SUJEITO" name="Concordancia com nucleo do sujeito">
 <pattern case_sensitive='yes'>
  <marker>
  <token regexp='yes'>[AO]</token>
  <token postag='NCFS000'><exception>maioria</exception></token>
  <token postag='SPS00+*'></token>
  <token postag='NC[FM]P000' postag_regexp='yes'></token>
  <token postag='V...3P0'></token>
  </marker>
 </pattern>
 <message>O verbo concorda com o núcleo do sujeito ("A realidade das pessoas mostra")</message>
 <example correction=''><marker>A realidade das pessoas mostram</marker></example>
 <example>A realidade das pessoas mostra</example>
</rule>
```

As can be seen, the rule encompasses not only feminine but masculine prepositional phrases ("A realidade das pessoas" "A realidade dos homens"). The checking of evaluation of the rule brought two cases candidates for false alarm:
A generalidade dos investigadores entendem que houve uma evolução das instituições ao longo da história.
A soma desses fatores ocasionaram uma paralisação no desenvolvimento da nova comunidade.
  But at least in standard Brazilian Portuguese, none of them is correct in verb agreement.

  I would like to receive feedback for this attempt, if there is anyone interested in pursuing this verb agreement path, with other situations I am aware languagetool doesn't capture, and if it is worth to create more similar rules (or ones that encompass many).

  As a sidenote, when I used VMIP3P0 as the verb form to be captured, another case came up (it was not a false alarm), which is strange as this case doesn't appear in the V...3P0 broader expression. I would also appreciate some feedback on why it happened, and to check the complete set of rules for regular expressions that languagetool uses.

**Comment by marcoagpinto** [comment]
Hello!

I will take a look at in on Monday.

Thanks!

**Comment by marcoagpinto** [comment]
Hello @ricardojosehlima 

It is coded:
https://github.com/languagetool-org/languagetool/commit/c4108360fc51b7ec5c6f10b98a69f88a4192f816

Such a rule takes 3 or 4 hours to code and tests against a massive corpus, that it is why I need to code it when I am able to get up at 4 or 5am.

I am including here the results against a 600 000 sentences database so that you can see if it is working well.

If it is okay, please close the ticket.

Thanks
[rule_ricardo_lima_20211012.txt](https://github.com/languagetool-org/languagetool/files/7327422/rule_ricardo_lima_20211012.txt)
!

**Comment by ricardojosehlima** [comment]
Ok, sorry but I think it's safer, for the moment, not to have a broad rule, for it will result in many false alarms.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello!

I committed the new code:
https://github.com/languagetool-org/languagetool/commit/0ba432accac564e22d7ec8462d42937af10e6d88

Now it checks if the sentence is at the start of a line, but instead of only looking for "a/o" it just accepts any word to make in broader.

```
SentenceSourceChecker: org.languagetool.dev.dumpcheck.DocumentLimitReachedException: Maximum number of documents (900000) reached
Portuguese (Portugal): 64 total matches
Portuguese (Portugal): ø0.00 rule matches per sentence
Portuguese (Portugal): 0 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```

It produced 64 hits against 900 000 sentences which gives an average of  7 hits per each 100 000 sentences which is quite acceptable.

Notice that it is still possible to remove more false positives, but each test against a 900 000 corpora takes a long time, so I will only revise the rule at some other time if needed.

I have attached here the .txt that shows the hits for you to see.
[rule_ricardo_lima_20211013j.txt](https://github.com/languagetool-org/languagetool/files/7338275/rule_ricardo_lima_20211013j.txt)

What I would really like to know is if all the sentences I placed in the XML are valid:
```
	  <example>O direito de civis possuírem armas é objeto de um controverso debate político.</example>
	  <example>A actividade vulcânica, o impacto de cometas e a existência de vida sob a forma de microrganismos está entre as possíveis causas ainda não comprovadas.</example>
	  <example>A área destes túmulos varia de tamanho, chegando a dimensões tão grandes quanto as pirâmides do Egito.</example>
	  <example>Um bilhão de pessoas falam inglês.</example>
	  <example>Artigos só com links são muito mal vistos.</example>	  
	  <example>Um milhão de pessoas perderam as suas vidas na guerra.</example>
	  <example>Meia dúzia de ferramentas formam a coleção.</example>
	  <example>Cada uma destas denominações tem direito a um lugar no parlamento.</example>
	  <example>Cada um destes dialetos tem por sua vez suas variantes.</example>

	  <example>Cada uma das características podem ser definidas separadamente</example>
	  <example>Na forma de fios podem ser utilizados para usinagem por eletroerosão de corte a fio (fast-cut).</example>
	  <example>Uma série de obras foram bem sucedidas apenas no seio da comunidade mórmon.</example>	
	  <example>Uma variedade de categorias têm sido propostas para tentar distinguir as diferentes formas de ateísmo.</example>
	  <example>No extremo das interações estão as junções de galáxias.</example>
	  <example>Na constituição dos átomos predominam os espaços vazios.</example>
	  <example>Ao longo dos tempos foram vários os sistemas para classificar a artilharia segundo o calibre utilizado.</example>
	  <example>Ao longo dos séculos foram sendo registrados muitos problemas curiosos, cujas resoluções têm como base este famoso teorema.</example>
```

If they are, then the rule is ready to go and somewhere in the future I may enhance it.

Thanks!

**Comment by marcoagpinto** [comment]
> With exception to:
> Cada uma das características podem ser definidas
> Uma variedade de categorias têm sido propostas
> All others are correct, and again should not be captured by the rule.

That is all I need to know.

They are “captured” as VALID, that is why I placed them in the `<example>` tags (not sure what you mean with “captured”).

I will fix the two incorrect ones tomorrow or so, as I want to code important rules to apply to my thesis… I have been writing the ideas as I revise the thesis “manually”.

**Comment by marcoagpinto** [comment]
> Ok! By captured, I mean: the rule identifies the sentence as incorrect and flags it.

In my case, the sentences written in those tags are correct, so they are “not captured” by the rule.

They are supposed to know if I break (damage) the rule.

If I damage the rule, one or more of those sentences will break the testing of the grammar.xml and throw an error with the broken sentences.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello!

I have improved the rule:
https://github.com/languagetool-org/languagetool/commit/f1b323ff01e525e2301041b6691a5042db3b253a

Could you tell if these sentences are correct?:
```
Do lado dos cangaceiros morreram cinco bandidos.
No rescaldo dos confrontos morrem quatro pessoas.
A habilidade destes radares diferenciarem dois objetos próximos depende da largura do sinal emitido.
```

If they are, I will close the ticket.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

On LanguageTool standalone tool, LibreOffice, OpenOffice and also on the software supported by add-ons such as Firefox, Thunderbird, etc.

https://proofingtoolgui.org/getting_most_tb.html

https://proofingtoolgui.org/getting_most_lo.html

Notice that the LibreOffice/OpenOffice add-on is only released every three months, unless you download the nightly.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Done!

https://github.com/languagetool-org/languagetool/commit/2eb1a640b74e08c4bce6d28498063310c9db501d

It fixes:
```
Neste tipo de erupções predominaram as de estilo pliniano, conduzindo ao abatimento da caldeira do vulcão mencionado.
Na aldeia de Pedras existiam também umas pedras lavradas antigas, que terão dado nome ao lugar.
Na prestação de Serviços destacam-se cabeleireiros, oficinas mecânicas, eletrônicas.
```

Also, see attached here the latest text file of the 900 000 sentences check.
[rule_ricardo_lima_20211020.txt](https://github.com/languagetool-org/languagetool/files/7378357/rule_ricardo_lima_20211020.txt)

**Comment by marcoagpinto** [comment]
Closing it, then.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

During my afternoon nap, I was thinking:
What if we make the rule broader by not checking if it is at the start of a sentence?

Imagine that one uses “e” or “ou” or any other word before starting the sentence… I am almost sure the rule would still work and would become more powerful… should I test it tomorrow?

Thanks!

**Comment by ricardojosehlima** [comment]
That sounds a good idea. Are you thinking of a list of words that can come at the beginning of a sentence? I thought on some cases like "Aquele cujo nome não pode ser falado morreu." which is correct and "Aquele, cujo nome não pode..." which is also correct.

**Comment by ricardojosehlima** [comment]
Yes, that's a lot, but there is always some pattern to look at. See:
Todas as regras e restrições definidas no banco de dados devem ser obedecidas.
This was captured because of the structure of the rule that allows a preposition before the head of the subject, thus "no banco de dados" was seen by the rule and as the verb is plural, it was captured.
My suggestion is to remove the preposition, leaving the structure of the rule as determiner + singular noun + preposition + plural noun.
