### ISSUE TITLE
[es] user feedback: mama

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#5805]
I am not sure if this helps:
> No corrige errores gramaticales de acentuación cuando la palabra depende de la entonación para un contexto determinado. Ej.: La mama

**Comment by udomai** [comment]
This is the kind of candidate for a confusion pair. With XML rules, we can only take it so far. AI can teach itself the contexts to distinguish the person from the body part. This can be realized by the end of Q4.
