### ISSUE TITLE
[en] "woman" tagged as an adjective

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#5818]
`The woman that I met`
JJ seems inapplicable to `woman` in general and here in particular
![image](https://user-images.githubusercontent.com/122009/137135829-d3f51413-9840-43f9-ab46-ebcbfc4e3b0f.png)

**Comment by MikeUnwalla** [comment]
@donnerpeter, I agree with you.

But, some dictionaries say that 'woman' is an adjective:
https://www.merriam-webster.com/dictionary/woman 
https://www.collinsdictionary.com/dictionary/english/woman

I think that the dictionaries are incorrect. 'woman' is no more an adjective that 'computer' or 'disambiguation'.
