### ISSUE TITLE
[En] false positive 'Grammatical problem:use gerund'

### ISSUE THREAD

**Issue by SkyCharger001** [languagetool-org/languagetool#583]
"That is what it tries to teach to people like me."
it tries to 'correct' it into "That is what it tries to teach peopling like me."
when it is actually a slightly more formal form of "That is what it tries to teach people like me."

second: is it possible for the libre/openoffice version to provide a direct connection to the rule that is complaining? I can't find it in the options.

**Comment by danielnaber** [comment]
Thanks for the report. There's no way to find the matching rule in LO, you need to use languagetool.org for that (`Examples` -> `Rule implementation`).

**Comment by SkyCharger001** [comment]
As in, no way to implement it?
