### ISSUE TITLE
LT cause Crash of OpenOffice / No LT menu at OpenOffice 

### ISSUE THREAD

**Issue by FredKruse** [languagetool-org/languagetool#5835]
LT 5.5:

1. There is no working menu point for LT in OpenOffice.
2. OpenOffice crashes when it was started with en empty document, and a document is loaded after a few seconds.

The second bug may be related to issue #5799.

**Comment by FredKruse** [comment]
@danielnaber These are very heavy bugs. Should we publish a version 5.5.1 of the extension?

**Comment by FredKruse** [comment]
I did some tests. It is OK, as far as I can see. It can be published.

**Comment by danielnaber** [comment]
@FredKruse I guess this issue can now be closed?
