### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by aronbos** [languagetool-org/languagetool#5844]
![Screenshot of 2021-10-15 14-04-44](https://user-images.githubusercontent.com/48289775/137484151-63bbb6bb-cd49-4954-8b02-09efee4ad1c9.jpg)

Error occurs in Libreoffice 7.2.1 with languagetool snapshot.

**Comment by FredKruse** [comment]
@danielnaber: As far as I see, the null pointer exception is triggered in MorfologikSpellerRule. The Speller rules should be deactivated for LO/OO and the internal speller should be used. Have you an idea, why the speller rule is used in this case?

**Comment by FredKruse** [comment]
The Bug is fixed for V5.5.1 in an easy way: A test of null is integrated in MorfologicSpellerRule, as result ismisspelled returns allways false for LO/OO-Extension.
In 5.6 I introduced a more advanced solution, that uses the speller of LO/OO for the extension.
