### ISSUE TITLE
[ru] Some rules in Russian do not work as expected

### ISSUE THREAD

**Issue by khorov** [languagetool-org/languagetool#5845]
Go to https://languagetool.org/ru  and check the sentence
"Я терпеть не могу эту глупою женщину"

The mistake is not detected, see 
![image](https://user-images.githubusercontent.com/85366265/137489088-dd9af1a5-a018-4879-a184-4138f94bbd6a.png)

The system cannot find a mistake although it is given as an example of rule Unify_Adj_NN_gender here https://community.languagetool.org/rule/index

This bug is reproduced in the standalone tool, https://community.languagetool.org/rule/index, https://languagetool.org/ru 

Also, some other similar rules do not work: Unify_Adj_NN_gender [2], Unify_Mult_Adj [1]

**Comment by khorov** [comment]
@yakovru 
OK. A more complex example is 
Во введении обоснована актуальность диссертационного работы, сформулированы цель, и аргументирована научного новизна исследований.
There is a dot at the end.
The site says that everything is OK. However, two mistakes are here. Only the first one is found if the sentence is split into several simple sentences.

**Comment by yakovru** [comment]
We are currently working on setting up the rules.
