### ISSUE TITLE
Multi language text issue

### ISSUE THREAD

**Issue by SkyCharger001** [languagetool-org/languagetool#585]
while going through an old document I have discovered that sometimes Grammar sticks to the rules of one language instead of switching along.

Example from the document:
[VORSICHTIG! Diese Brücke ist für nicht mehr als zwei Erwachsene ausgelegt.] Hope I wrote it correctly… once again, machine-translation.

instead of using English grammar for the English text it stuck to German grammar.

**Comment by danielnaber** [comment]
There's no support for multi-language texts, the automatic language detection will simple use the language that prevails.

**Comment by SkyCharger001** [comment]
no offense, but could you please give an indication whether you are talking about a current or permanent fact?

**Comment by danielnaber** [comment]
There are no plans to implement this.
