### ISSUE TITLE
[DE]LT-Bugmeldung 5.4

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#5850]
Moin liebes LanguageTool-Team

![grafik](https://user-images.githubusercontent.com/78316155/137640430-46f0eaab-124e-4dce-becc-5da22b2a1812.png)
Diese Meldung kam, als ich das LanguageTool temporär deaktivieren wollte, wofür ihr eine Funktion eingebaut habt.
Danach kam diese Bugmeldung.

Ich weiß, dass dieses Version veraltet bin, nur weiß ich nicht, ob der Fehler bereits gefixt ist.

Grüße Dallun511

**Comment by FredKruse** [comment]
Der Fehler tritt in der 5.5 nicht auf. Das Issue kann geschlossen werden.
