### ISSUE TITLE
[pt] ruling out 'Cujo' and its variants

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#5879]
Hi,
   As my suggestion on agreement seemed to work fine (after some work by @marcoagpinto to whom I am grateful), here is another one, which I believe (hope!) is simpler:

   The goal of this proposed rule is to flag cases of the relative pronoun "cujo" and its variants (cujos, cuja, cujas) appearing at the beginning of a period.
This pronoun connects two nouns as in "Esse é o menino cujo pai chegou", thus cannot appear isolated as in "Esse é o menino. Cujo pai chegou."

   
<rule id="CUJO_EM_INICIO_DE_FRASE" name="cujo em início de frase">
 <pattern case_sensitive='yes'>
  <marker>
  <token regexp='yes'>Cuj[oa]s?</token>
  </marker>
 </pattern>
 <message>O pronome relativo <suggestion>cujo</suggestion> liga dois substantivos, portanto não pode estar em começo de frase.</message>
 <example correction=''><marker>Cujo</marker> pai chegou.</example>
 <example>, cujo pai chegou.</example>
</rule>

The check using the rule editor:

 We've checked your pattern against sentences 1 to 1.000 from the pt Wikipedia, Tatoeba, and several online forums and found the following matches. Please consider modifying your rule if these matches are false alarms. Hover over the words to display their part-of-speech tags.

    Cujo público lotava estádios e festivais relembrando os grandes shows de rock do passado. Analyse
    Cujo gentílico é paraense, ou parauara, do tupi para'wara "o que nasceu no rio-mar". Analyse
    Sources: Wikipedia, License: CC BY-SA 3.0 Unported & Tatoeba, License: CC-BY 2.0

  Both cases are wrong according to standard brazilian portuguese.

**Comment by marcoagpinto** [comment]
@jaumeortola @udomai @tiff 

```
	<!-- CUJO , cujo -->
    <rule id='CUJO_EM_INICIO_DE_FRASE' name="'cujo' em início de frase" type="style">
    <!--      Created by Ricardo Joseh Lima and improved by Marco A.G.Pinto, Portuguese 2021-10-20 (25-JUN-2021+)      -->
	<!--
Cujo pai chegou. → Foi a Ana, cujo pai chegou.
	-->
      <pattern>
		<token postag_regexp='no' postag='SENT_START'/>
		<marker>
			<token regexp='yes' case_sensitive="yes">Cuj[oa]s?</token>
		</marker>
		<token/>
      </pattern>
      <message>O pronome relativo 'cujo' liga dois substantivos, portanto não pode estar em começo de frase.</message>
	  <suggestion>, <match no='2' case_conversion="alllower"/></suggestion>
      <example type='incorrect'><marker>Cujo</marker> pai chegou.</example>
      <example type='correct'>Foi a Ana<marker>, cujo</marker> pai chegou.</example>	  
    </rule>
```

Why does the suggestions suggests `", Cujo"` (uppercase) when I have there a `<match no='2' case_conversion="alllower"/>`?

Thanks!

**Comment by ricardojosehlima** [comment]
My bad!  I put cujo between '' which languagetool reads as a suggestion but it wasn't intended to be so.
