### ISSUE TITLE
[ru] missing prepositional case in "на своем счету"

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#5923]
счету should have some prepositional case reading

![image](https://user-images.githubusercontent.com/122009/138716514-37dd3f39-e36b-4a91-85f9-c7a87b8997ef.png)

**Comment by yakovru** [comment]
Fixed via https://github.com/languagetool-org/languagetool/commit/475ed3931466e64b4bfe19e7e5c144aaa1002d91
