### ISSUE TITLE
[en] False positive on "the write buffer" (A_INFINITIVE[2])

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#5936]
Flush the write buffer for the event log file.

Googling for "write buffers" suggests that people use that often :)
"read buffer" might be acceptable as well.

![image](https://user-images.githubusercontent.com/122009/138848976-cd341966-1046-4c84-877f-6b487d36e5c0.png)

**Comment by tiff** [comment]
This has been fixed already
