### ISSUE TITLE
[ru] missing P/2P case on долгу

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#5938]
я в долгу

![image](https://user-images.githubusercontent.com/122009/138853926-88463019-c076-47c5-b305-57efdd131deb.png)

**Comment by yakovru** [comment]
Fixed via https://github.com/languagetool-org/languagetool/commit/475ed3931466e64b4bfe19e7e5c144aaa1002d91

**Comment by donnerpeter** [comment]
Still an issue in:
Быть в неоплатном долгу.
