### ISSUE TITLE
[pt] back to 'cujo' (a long story)

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#5959]
Took sometime to look more carefully to how languagetool deals with 'cujo' and I came up with this:

The cujo standard usage: as it is a relative pronoun, (a) it must connect two elements and (b) both are nouns, but the first element can be succeeded by an adjective (O menino bom cujo pai chegou) and the second can be preceded by an adjective or numeral (O menino cujo bom pai chegou; O pai cujos dois filhos chegaram).
Thus:
(i) cujo cannot appear at the beginning of a sentence (violates (a));
(ii) cujo cannot connect other elements than nouns (violates (b)).

(i) was solved by a rule that I proposed and @marcoagpinto improved.

(ii) is harder to approach due to limitations of languagetool.

There is already a specific rule preventing cujo to connect to a determiner:

<rule id="CUJO_O" name="Cujo">
  <pattern>
    <token>cujo</token>
    <token regexp="yes">[ao]s?</token>
  </pattern>
  <message>Substitua por <suggestion>cuj\2</suggestion>.</message>
  <example correction="cujo">O autor <marker>cujo o</marker> livro foi um best-seller.</example>
</rule>

But this rule appears to apply only to 'cujo' not to its inflected forms 'cuja, cujos, cujas'.
However, this is not a problem because "A menina cuja a mãe chegou" is captured by another rule,
responsible for errors concerning standard register ("Erro gramatical ou de normativa."). But I couldn't find this rule in grammar.xml or in the list of rules here (https://community.languagetool.org/rule/list?lang=pt).

Anyway both rules only prevent 'cujo' and its variants to appear before determiners. As this relative pronoun is categorically absent from everyday oral register in Brazil, people have no idea how to use it and thus use it in unexpected contexts from a standard register perspective as in "O menino cujo queria um sorvete chegou", where a simple "que" would be enough ("O menino que queria um sorvete chegou").

The logical step, given (b) above, would be to create a rule that bars 'cujo' and its variants before any postag that is not A nor N nor Z.
However, languagetool classifies 'primeiro' as A, Z and R (probably because sometimes it is an adverb: "Primeiro, ele veio"). So if the rule bars 'cujo' before R it will create false alarms as "O pai cujo primeiro filho chegou". Maybe it would be the case of barring R but allowing as exception 'primeiro' and its variants?
The second and more difficult problem to overcome is about verbs. languagetool classifies many very common words that are verbs as nouns ('veio' is a verb in 'Ele veio', but a noun in the rare case "Descobriu um veio de ouro").
By observing the false alarms that a rule barring 'cujo' before verbs generated, these problematic verb-noun cases appear to be only with verbs in the present tense, singular.

Thus, I created two rules to deal with (b). One bars 'cujo' and its variants before all postags except N, A, R or V.

<rule id="CUJO_SUBST_ADJ" name="cujo_subst_adj">
 <pattern>
  <token regexp='yes'>cuj[oa]s?</token>
  <token postag='[CDPSWI].*' postag_regexp='yes'></token>
 </pattern>
 <message>Só se usa cujo antes de substantivo ou substantivo precedido de adjetivo.</message>
 <example correction=''>O pai <marker>cujo ele</marker> queria ver.</example>
 <example>O pai que ele queria ver.</example>
</rule>

The second rule deals specifically with verbs that are not in the present tense:

<rule id="CUJO_ANTES_DE_VERBO" name="Cujo antes de verbo">
 <pattern case_sensitive='yes'>
  <token regexp='yes' negate='yes'>dit[oa]s?</token>
  <marker>
  <token regexp='yes'>cuj[oa]s?</token>
  <token postag='V..[IFSCM]...' postag_regexp='yes'></token>
  </marker>
 </pattern>
 <message>O pronome "cujo" não pode anteceder um verbo.</message>
 <example correction=''>O menino <marker>cujo veio</marker> está aqui.</example>
 <example>O menino que veio está aqui.</example>
</rule>

The tests with the editor were successful for there were few if any false alarms in both rules.

What my limited knowledge of the workings of languagetool prevents me from doing is:

- (probably) delete the 'cujo o' rule and the 'normativa' rule mentioned first;
- unify the two rules I proposed in one;
- (probably) unify the rule created to solve (a) (which is (i)) with the one to solve (b), although I, personally, prefer to leave them separated for they send different messages of different errors.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello!

I am terribly confused about the rule creation, which you mentioned in the first comments.

What is it supposed to suggest and warn to the users?

However, I have just finished coding the "cuj[ao]s?" gender rule:
https://github.com/languagetool-org/languagetool/commit/ea3f9ec08488be0b35914d8b3992a3d241be5b5a

Here is attached the .txt file with the results of a 600 000 sentences check.

Notice that it is a gender rule, not a plural/singular match rule.
[ricardojosehlima_cuja_s_cujo_s_ECG_20211101b.txt](https://github.com/languagetool-org/languagetool/files/7454001/ricardojosehlima_cuja_s_cujo_s_ECG_20211101b.txt)

**Comment by ricardojosehlima** [comment]
Hi,
  first, the good news: no false alarms on the rule you created.
  Now, my bad for presenting so many things at the same time. We can go step by step. My guess is that would be to create a rule on number mismatch. I was considering a unique rule for both gender and number mismatch, but maybe it is too hard or confusing, so separate rules under a group rule, as you made it, seems to be the better way.
   After, we can focus on the other part of the cujo rule, what do you think?

**Comment by marcoagpinto** [comment]
> 
> 
> Hi, first, the good news: no false alarms on the rule you created. Now, my bad for presenting so many things at the same time. We can go step by step. My guess is that would be to create a rule on number mismatch. I was considering a unique rule for both gender and number mismatch, but maybe it is too hard or confusing, so separate rules under a group rule, as you made it, seems to be the better way. After, we can focus on the other part of the cujo rule, what do you think?

Sure, I will code it tomorrow at 5am 🙂

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I had just finished creating the number rule and when I was testing it in the stand-alone tool, I typed:
```
A mãe cujo filhos fizeram anos. → A mãe cujos filhos fizeram anos.
A mãe cujos filho fez anos. → A mãe cujo filho fez anos.
```
and it was already supported by the existing rules.

**Comment by ricardojosehlima** [comment]
@marcoagpinto sorry for the delay in answering, yesterday was holiday in Brazil. 
That's good news! Now, will this rule be merged with the one you created or will remain separate rules?

Same question for the rule for 'cujo o' and another (which I couldn't find) that takes the other variants (cujos os, cujas as, cuja a). 

Now, for the part of my first message that was confusing: 'cujo' can only be connected to an adjective, numeral or noun - so a rule that has 'cujo' (and its variants) forcing it to be followed only by words with these postags would be interesting and attend to what is needed.
However, languagetool postagger sometimes classifies words both as noun and verbs, as in the case of 'veio' (Ele veio = O veio de ouro) and 'fala' (Ela fala = A fala foi boa), and so on.
These cases wouldn't be flagged by the rule as the postagger sees 'veio' in "Ele veio" both as verb and noun. What I tried was to create a complex rule, but now I think that the one expressed above, forcing 'cujo' and its variants only before adjectives, numerals and nouns may suffice.

**Comment by marcoagpinto** [comment]
> That's good news! Now, will this rule be merged with the one you created or will remain separate rules?

I didn't commit the number agreement rule, since it was already working with the current ones.

**Comment by marcoagpinto** [comment]
I will try to create/commit the rule tomorrow, as right now, I am working on some projects.

Thanks!

🙂

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello Ricardo,

I have just implemented the rule:
https://github.com/languagetool-org/languagetool/commit/0b07952227fb8b2b86e7660fd6501d69f69599e3

It will also flag unknown words (typos or without POS information), so I added some POSes to common pt-BR words:
https://github.com/languagetool-org/languagetool/commit/2fc71dfdcf4d8461f286593f30821a4f7a55f8bc

See the attached file for a test run against 900 000 sentences:
[ricardo_cujo_nc_adj_numeral_20211104.txt](https://github.com/languagetool-org/languagetool/files/7472918/ricardo_cujo_nc_adj_numeral_20211104.txt)

**Comment by ricardojosehlima** [comment]
Hi! Great! 
I compiled a list of the unknown words, some are proper nouns, other abbreviations, many are rare and a few are common:
cuja Bachiana
cuja Buch
cuja Luftwaffe
cuja Muqadimmah
cuja Vênus
cuja agrovila
cuja atemporalidade
cuja dijina
cuja ordem
cuja umidade
cuja wikipédia
cujas antiderivadas
cujo IDEB
cujo IDHM
cujo Rianga
cujo codinome
cujo esporte
cujo finale
cujo frame
cujo instamento
cujo mantra
cujo ordinário
cujo orixá
cujo tóhwyó
cujo zoneamento
cujo órago
cujos anfídeos
cujos axônios
cujos kanjis
cujos microporos
cujos íons
cujos órgãos

My guess is that:
órgão, ordinário, esporte, ordem, umidade, wikipédia should go to the Added words to added.txt 

Just one more question. In the rule created,
<exception postag_regexp='yes' postag='V.+|RG|NP.+|AO.+'/>
  Is this supposed to allow 'cujo' before these POS?

**Comment by marcoagpinto** [comment]
> Just one more question. In the rule created,
> exception postag_regexp='yes' postag='V.+|RG|NP.+|AO.+'/
> Is this supposed to allow 'cujo' before these POS?

It is to prevent certain words from flagging the rule, for example:
"poderes" is a noun and a verb, so by adding there "V.+" it is accepted as a valid noun.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Now I am confused, should the rule also accept proper names?

I placed there to ignore them.

**Comment by ricardojosehlima** [comment]
Hi, it shouldn't.

**Comment by marcoagpinto** [comment]
It should ignore them, or it should accept them? 🙂

**Comment by ricardojosehlima** [comment]
Sorry, ignore them.

**Comment by marcoagpinto** [comment]
ahhhhhh
then, it is well coded.

I will take a look at the added.txt words, but wikipédia is a proper name (should be capitalized).

**Comment by marcoagpinto** [comment]
@ricardojosehlima 
https://github.com/languagetool-org/languagetool/commit/b6be63d8bf07e84eaa9d13c56c2bef1f165d4870

It is very strange, I typed:
`órgão, ordinário, esporte, ordem, umidade, wikipédia`
and three of them were already nouns/adjectives, but I noticed the "I" in "ordinário" and "ordem" which means "interjection".
https://community.languagetool.org/analysis/analyzeText

So, tomorrow at 5am I will try to add "I" to the exclude POS to see what happens.

**Comment by ricardojosehlima** [comment]
Indeed, the postagger for Portuguese does some stranger things sometimes

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello!

I have improved it, and the POS additions yesterday removed several false positives:
https://github.com/languagetool-org/languagetool/commit/2a43b3c94e196da9914048f763c11a84cee49118

Here is the test against 900 000 sentences:

[ricardo_cujo_nc_adj_numeral_20211105bb.txt](https://github.com/languagetool-org/languagetool/files/7481271/ricardo_cujo_nc_adj_numeral_20211105bb.txt)

BEFORE:
```
SentenceSourceChecker: org.languagetool.dev.dumpcheck.DocumentLimitReachedException: Maximum number of documents (900000) reached
Portuguese (Portugal): 116 total matches
Portuguese (Portugal): ø0.00 rule matches per sentence
Portuguese (Portugal): 0 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```

AFTER:
```
SentenceSourceChecker: org.languagetool.dev.dumpcheck.DocumentLimitReachedException: Maximum number of documents (900000) reached
Portuguese (Portugal): 104 total matches
Portuguese (Portugal): ø0.00 rule matches per sentence
Portuguese (Portugal): 0 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```

**Comment by ricardojosehlima** [comment]
Great job!
