### ISSUE TITLE
[en] Caught in "any·more"-loop

### ISSUE THREAD

**Issue by herschel666** [languagetool-org/languagetool#5965]
The following sentence sends me into an "any·more"-loop:

```
When setting up a new machine, the first thing I have to do is installing Alfred because
I literally can't work decently anymore without clipboard history.
```

**Comment by udomai** [comment]
Oh no! I was hoping this wasn't happening any·more. I'm on it.

We might want to scan for 'anymore' loops again, maybe on a different corpus.
