### ISSUE TITLE
Extension for LibreOffice does not apply any ngram rules, if it calls HTTP server for checking

### ISSUE THREAD

**Issue by Christian-Schmidt-canau** [languagetool-org/languagetool#5969]
Hi there! Thanks for maintaining and developing this wonderful language tool! I really like using this tool a lot!

Unfortunately, I am experiencing the following trouble:
The extension for LibreOffice does not apply any ngram rules, if the extension calls the HTTP server for checking.
But if the extension for LibreOffice uses its own built-in logic instead, then the extension applies the ngram rules properly.
Furthermore, the HTTP server applies the ngram rules properly too, if it is called via browser and not out of LibreOffice.

**Steps to reproduce:**

1. Start LT HTTP server like this: java -cp /some/path/languagetool-server.jar org.languagetool.server.HTTPServer --port 8081 --allow-origin "*" --languageModel /some/path/ngrams/
                                                   
2. Check general application of ngram rules via server like this: open Firefox, type in URL http://localhost:8081/v2/check?language=en-US&text=put+on+the+breaks, result: the rule CONFUSION_RULE_BREAKS_BRAKES is present in the resulting JSON file.

3.  Check LibreOffice with **server call** like this: configure LibreOffice extension to call HTTP server on http://localhost:8081, open new document in libre writer, type in "Put on the breaks.", result: The word “breaks” is **not** marked as faulty. (If I type in words like "findd", then the server check does find the error. I conclude, that the server call is working properly in general, except for the ngram rules.)

4. Check LibreOffice with **built-in logic** like this: configure extension to use built-in logic, open new document in libre writer,  type in "Put on the breaks.", result: The word “breaks” is marked as possible confusion.

**Some information on my system and versions:**
- LanguageTool version 5.5 (2021-10-02 12:33:00 +0000, `5e782cc`)
- LibreOffice 6.1.5.2 10(Build:2)
- LibreOffice extension: LanguageTool 5.5.1
- System: Host: q4os-desktop Kernel: 4.19.0-17-amd64 x86_64 bits: 64 Desktop: Trinity R14.0.6 Distro: Q4OS 3.15.1-n1 

**Calls in console logging of HTTP server:**

- calling via Firefox:` 2021-11-02 19:53:35.691 +0100 INFO  org.languagetool.server.TextChecker Check done: 17 chars, en-US, requestId: null, #33, null, 0/1 matches, 630ms, agent:-, sent, q:0, h:1, dH:1, r:102, m:all, premium: false`
- calling via libre office extension: `2021-11-02 19:53:58.438 +0100 INFO  org.languagetool.server.TextChecker Check done: 105 chars, de-DE (mother tongue: en-US), requestId: null, #30, null, 0/1 matches, 475ms, agent:java-http-client, sent, q:0, h:1, dH:1, r:104, m:!tlo, premium: false`

Please help me to get the calls from LibreOffice's extension to the HTTP server properly working for ngram rules!

Thanks a lot in advance, and please let me know if you need any further information.

**Comment by danielnaber** [comment]
> calling via libre office extension: 2021-11-02 19:53:58.438 +0100 INFO org.languagetool.server.TextChecker Check done: 105 chars, **de-DE**

This might be the problem: are you sure your text in LO is set to English?

**Comment by Christian-Schmidt-canau** [comment]
First of all: You are damn quick! Thanks a lot.

Unfortunately, I am afraid, that the solution is not in this direction.

You are right, in my logging example I mixed up the languages.
But nevertheless I can reproduce the problem with “en-US” too. (And with German sentences with “de-DE” as well.)

`2021-11-02 21:07:18.002 +0100 INFO  org.languagetool.server.TextChecker Check done: 18 chars, en-US, requestId: null, #50, null, 0/1 matches, 715ms, agent:java-http-client, sent, q:0, h:1, dH:1, r:159, m:!tlo, premium: false`

Is there a way to get more logging details to see more differences for the calls from Firefox and LibreOffice?
(Or do you think this is not helping either?)

**Comment by danielnaber** [comment]
Maybe @FredKruse has an idea.

**Comment by FredKruse** [comment]
The issue should be solved. Please test the next 5.6-snapshot

**Comment by Christian-Schmidt-canau** [comment]
I have built the 5.6-snapshot this morning and installed the office-extension.

Result: Works like a charm!

Thanks a lot and keep your great work up!

You can close this issue. :-)
