### ISSUE TITLE
Runtime Error after installation

### ISSUE THREAD

**Issue by Dre-OS** [languagetool-org/languagetool#5970]
# Bug report:
## Versions:
 - **Extensions tested**: 

    > Language Tool for LibreOffice 5.5.1
    > Language Tool for LibreOffice 5.5
    > Language Tool for LibreOffice 5.4

 - **LibreOffice**: LibreOffice 7.1.6.2 for Ubuntu

    > Version: 7.1.6.2 / LibreOffice Community
    > Build ID: 10(Build:2)
    > CPU threads: 4; OS: Linux 5.13; UI render: default; VCL: gtk3
    > Ubuntu package version: 1:7.1.6-0ubuntu0.21.04.1
    > Calc: threaded

 - **Java:** OpenJDK 11.0.11

    > openjdk version "11.0.11" 2021-04-20
    > OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2)
    > OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2, mixed mode, sharing)

 - **OS**: Pop!_OS (based on Ubuntu) 21.04
 

    > Kernel: 5.13.0-7620-generic

## Issue:

- Runtime error after installation.
- Also displaying same error when extension is enabled after installation.
- Error persists after re-enabling and reinstallation.

## To replicate:
- most probable way to replicate this is installing the extension on Pop!_OS 21.04 with same Java JDK version, haven't tested running it in another system.

### - after installation
![image](https://user-images.githubusercontent.com/65882951/139922402-5be68cfb-5421-44a9-8df3-f69e7a0be6f5.png)
### - after enable
![image](https://user-images.githubusercontent.com/65882951/139974738-ae92ca01-ef16-4fa9-bb49-bdb7f495fd45.png)
![image](https://user-images.githubusercontent.com/65882951/139975723-cba30d5f-3bc7-43a6-badf-df57bfcf6c9b.png)
![image](https://user-images.githubusercontent.com/65882951/139977517-f10c4828-ee6a-443b-b9b3-5dd433802444.png)

**Comment by danielnaber** [comment]
Have you checked this article? https://languagetooler.freshdesk.com/en/support/solutions/articles/44002037688-linux-specific-issues

**Comment by Dre-OS** [comment]
I just did and it just solved the problem, thank you.
