### ISSUE TITLE
Add POS to quotes

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#5981]
Hello!

In Portuguese, there is no token for quotes in the morphological dictionary:
https://community.languagetool.org/analysis/analyzeText

If I write in it:
`Marco "ninja" is here!`

It reports the "!" as "_PUNCT".

But it doesn't report the " as a token, like "_QUOTE" or something like that.

It could avoid using in the XML:
`<token min="0" max="1" regexp="yes">[»«"”‘‹›']</token>`

Thanks!

**Comment by yakovru** [comment]
Hello, @marcoagpinto!
You can modify this rule in disambiguation.xml or make a new rule like this for that:

https://github.com/languagetool-org/languagetool/blob/91d62506eae146104579f4f4ca06a9362e3e915b/languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml#L1551-L1557

**Comment by marcoagpinto** [comment]
@yakovru 

Thank you for the tip.

Could someone check if I implemented it well?:
https://github.com/languagetool-org/languagetool/commit/67237305ac9eb3ee9b7d869c50a290b690ce2992

@jaumeortola @udomai @tiff 

Thanks!
