### ISSUE TITLE
LO Extension does not work correct with public LT remote server

### ISSUE THREAD

**Issue by FredKruse** [languagetool-org/languagetool#5984]
The maxtextlength request always deliver the max value of an integer.
The reason is that the handleMaxTextLengthRequest at ApiV2 gives back the maxTextHardLength. Needed is the text length limit for the user.
@danielnaber Could you tell me, which variable stores the user text length?
Another idea to advance the Extension could be, to use a premium account when doing the checks by the remote server. I didn't use the premium account till now. Could you please tell me, what I have to do, to use this possibility? Then I could think about a way to add such a support.

**Comment by danielnaber** [comment]
There's `UserLimits.getLimits...` to get the limits for the current user. But I don't think it's a good approach to have the client use a user-based limit. Can't requests be split in e.g. 5000-character chunks so that they will always work?

**Comment by FredKruse** [comment]
@danielnaber That's the use of maxtextlength, to split the text in chunks of maximal maxtextlength characters.

**Comment by danielnaber** [comment]
Then maybe `getMaxTextLengthAnonymous()` should be used instead?
