### ISSUE TITLE
[en] False warnings EN_A_VS_AN 

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#5985]
> Make sure that 3.a as well as 3.b are correct.
> Instruction 3.a is not correct.
> 3.a in this case will be the default.
> Use the example from 3.a if necessary.

![image](https://user-images.githubusercontent.com/5816160/140654253-93128c73-152c-4dd2-b105-4cabff5cd958.png)

**Comment by tiff** [comment]
Can be solved by disambiguation (remove 'DT' from `3.a`)
