### ISSUE TITLE
[en-ca] inconsistent "ize" "ise" support

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6000]
A user reported this:
![Bildschirmfoto 2021-11-09 um 14 53 53](https://user-images.githubusercontent.com/37363/140936524-a9c641ed-f07a-49e4-a007-dde78eb512cf.png)

When a word is ending with "~ize" and it is not in the Canadian dictionary, then we offer replacing it with "~ise".

**Comment by tiff** [comment]
@AzadehSafakish do we have to put all "~ize" words that you manually moved to spelling_en_us and spelling_en_gb also into spelling_en_ca? I noticed that in there the verb "essentialize" is listed

**Comment by AzadehSafakish** [comment]
@tiff Yeah, I think that would be a good move.

**Comment by AzadehSafakish** [comment]
@tiff 
I copied all of the -ize words from en-US and put them in en-CA, so this particular issue doesn't occur anymore.

However for Canadian English, the suggestions for 'organise' and 'essentialise' are related words, whereas in AmE there is an option to switch to BrE. How do I get that to work for Canadian English as well?
