### ISSUE TITLE
[de] DE_AGREEMENT no suggestion

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6003]
> Das ist ein sehr schönes Tisch.

Sobald zwischen Artikel und Adjektiv ein Adverb kommt, wird kein Vorschlag mehr generiert, dabei könnte man den Fall eigtl. so behandeln als wäre kein Adverb vorhanden und es einfach 1-zu-1 übernehmen.

![Bildschirmfoto 2021-11-09 um 18 40 53](https://user-images.githubusercontent.com/37363/140976278-1c74be5f-483e-4a7f-96bd-e13f1f0456b4.png)

**Comment by tiff** [comment]
@danielnaber ich sehe, dass du hier was gemacht hast, aber das funktioniert noch nicht, oder?

**Comment by danielnaber** [comment]
@tiff, ja, es fehlt noch ein zweiter Schritt. Ich bin dran, aber ist nicht so einfach...

**Comment by tiff** [comment]
Scheint jetzt zu gehen. Super!
