### ISSUE TITLE
[pt] Agreement with 'false' passive

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#6014]
In some sentences, the verb when followed by '-se' cannot be in the plural due to the preposition 'de':

Precisam-se de trabalhadores.
Tratam-se de pessoas estudiosas.

(Compare with true passives "Vendem-se casas", "Compram-se doces").

I found it hard to create a general rule for any verb in this situation, for many false alarms were generated ("Alimentam-se de algas" is correct).

So below, a rule only for 'precisar' and 'tratar'. It includes any postag that can be in the plural, following 'de'.

     
     <rule id="PLURAL_FALSA_PASSIVA" name="Plural_Falsa_Passiva">
     <pattern>
     <token regexp='yes'>(precisam|tratam)</token>
     <token>-</token>
     <token>se</token>
     <token>de</token>
     <token postag='(N..P...|A...P.+|D...P.|Z.+)' postag_regexp='yes'></token>
      /pattern>
      <message>O complemento da preposição "de" não é o sujeito do verbo, que deve ficar no singular. /message>
     <example correction=''><marker>Precisam-se de trabalhadores</marker>. Tratam-se de pessoas estudiosas.</example>
     <example>Precisa-se de trabalhadores.</example>
     <example correction=''>Tratam-se de pessoas estudiosas.</example>
     <example>Trata-se de pessoas estudiosas.</example>
     /rule>

If possible, the message should include the singular form of the verb used, 'precisa' or 'trata' depending on the situation.

**Comment by marcoagpinto** [comment]
I will look at it at 5am as usual 🙂

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Before 5am:
Do you mean that if the verb ending in "am-se"/"em-se" if it has a "de" after it, it is correct?

If so, it is easy to code.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I am confused, I can't focus 🙂 

Could you explain again?

Thanks!

**Comment by ricardojosehlima** [comment]
@marcoagpinto 
It is a rule only for the verbs 'precisam-se' e 'tratam-se' followed by 'de', other cases may generate false alarms.

**Comment by marcoagpinto** [comment]
ahhhhhhh... ok. 🙂

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Here it is:
https://github.com/languagetool-org/languagetool/commit/54a5a0c0395373b2a37582b5059e99802aed91a6

In a 900 000 sentences check it only gave one hit (see attached .txt).


[ricardo_joseh_20211111c.txt](https://github.com/languagetool-org/languagetool/files/7518522/ricardo_joseh_20211111c.txt)

**Comment by ricardojosehlima** [comment]
Great! The rule was so much improved and the only hit found is not a false alarm.
