### ISSUE TITLE
[es] user feedback: agreement "todo + NC"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6016]
## User feedback:
It can’t suggest a replacement when flagging a false friend in.
> “iré de todas formas”

Then when I realize myself that it should be
> iré de todas modos”

It can’t spot the gender mismatch with todas which should be todos.

**Comment by jaumeortola** [comment]
I don't know how to reproduce the problem about the false friend. Where are false friends shown?

> iré de todas modos

This is a clear FN. Not easy to solve because "todas" can be a determiner or a pronoun. We need some specific rules for "todo" (and inflected forms).

**Comment by jaumeortola** [comment]
Solved for the most common phrases: "todos modos", "todas formas", "todo tipo", "toda clase"...
But "todo" (determiner or pronoun) is ambiguous, and a more general rule would cause tons of false positives.
