### ISSUE TITLE
[es] user feedback verb tense

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6017]
> For a conditional/subjective verb tense mixup, all LT can do is point at a spelling mistake, but makes NO suggestion as to what the correct tense is:

![image001](https://user-images.githubusercontent.com/37363/141326238-bfc5c3d4-d260-43d9-acc8-f07de667dde5.png)

> And if I change it to the wrong verb tense, but spelt correctly, it thinks it’s fine:

![image002](https://user-images.githubusercontent.com/37363/141326302-09aa76a6-5f64-4e2a-bb84-8f6163587584.png)

**Comment by jaumeortola** [comment]
This error is unusual, at least for native speakers. It will be a Premium rule, and it can be further developed for other contexts. https://github.com/languagetooler-gmbh/languagetool-premium/commit/ef8dfa7e74a8053a1ca3f946ebe8fc2c96807120
