### ISSUE TITLE
stanford corenlp parser used?

### ISSUE THREAD

**Issue by aliabbasjp** [languagetool-org/languagetool#602]
How can I modify the code to use stanford corenlp parser, which parser is this repo using ?

**Comment by danielnaber** [comment]
We're not using a parser at all, just looking up part-of-speech tags, then disambiguate some of them. My understanding is that stanford is GPL, so this could only be a solution for yourself, not something that can be published, as LT is under LGPL.

**Comment by aliabbasjp** [comment]
@danielnaber  can I use spacy parser? or any other compatible parser ? if yes then how can I go about adding a wrapper which outputs POS tags and multiword named entities to the rule engine.

**Comment by danielnaber** [comment]
The tagger interface is called `Tagger`, so you can add your own implementation, you'll just need to activate it in the language class, e.g. `English` instead of `EnglishTagger`. But what are you trying to achieve?

**Comment by aliabbasjp** [comment]
@danielnaber to extend the tagsets to include more tags, dependencies and named entity tags and use them in rule making. Is this possible ?

**Comment by aliabbasjp** [comment]
@danielnaber also the parser itself will handle tokenizer. But how to handle multiword tags say a two word 
Person name which is assigned a NE PERSON tag.

**Comment by danielnaber** [comment]
http://wiki.languagetool.org/developing-a-tagger-dictionary describes how to extend the tagger. It doesn't support multi words, though.
