### ISSUE TITLE
[de] DE_AGREEMENT liefert keinen Vorschlag für Adjektiv

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6026]
Für diesen Fall liefert `DE_AGREEMENT` einen Vorschlag:
![Bildschirmfoto 2021-11-16 um 11 46 35](https://user-images.githubusercontent.com/37363/141971577-571c8281-04a0-497e-a170-a6a9a7e6a58e.png)

Aber nicht für diesen Fall:
![Bildschirmfoto 2021-11-16 um 11 46 39](https://user-images.githubusercontent.com/37363/141971603-407c05f0-698a-4105-b691-43c8b46b9832.png)

**Wahrscheinlich, weil "anstrengend" kein `ADJ:.*` ist, sondern ein `PA1:.*` bzw. `PA2:.*`. Da das Tagging recht ähnlich ist, könnte es eine Low-Hanging-Fruit sein :)**

**Comment by tiff** [comment]
Sieht so aus als würde es mit PA2 bereits funktionieren. In der `AgreementSuggestor2` Klasse gibt es ein `pa2Template` aber kein `pa1Template`

**Comment by danielnaber** [comment]
Bei der Überlegung, "anstregend" auch als ADJ zu taggen, sind viele weitere Fälle aufgefallen, die evtl. auch ein ADJ sein könnten, die aber Grenzfälle sind (siehe `FindMissingAdjectiveReadings`). Deshalb jetzt über ein `pa1Template` gelöst, wie in deinem Kommentar vorgeschlagen (https://github.com/languagetool-org/languagetool/commit/4942b0bce1cd44498fc18ce89d0d825be09e33ac).
