### ISSUE TITLE
java.lang.RuntimeException: Could not check sentence (language: German (Germany)):

### ISSUE THREAD

**Issue by Programmerier** [languagetool-org/languagetool#6028]
Hello, i want to correct my homework with a program. Im from Germany and every time i start it this error appears:   returned invalid JSON response... here my code: 

tool = language_tool_python.LanguageTool('de-DE')
text = 'Das ist keine Rechtscreibung'
try:
    print(tool.correct(text))
except:
    print('Error oder Kein Fehler')

**Comment by danielnaber** [comment]
You seem to be using a Python-based library not developed by the LT team. I'm sorry we can't help with that.
