### ISSUE TITLE
Strange EnglishUnpairedBracketsRule incorrect example

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#6034]
Here: https://community.languagetool.org/rule/show/EN_UNPAIRED_BRACKETS?lang=en

![image](https://user-images.githubusercontent.com/122009/142239265-4126a469-7f85-4bcd-a173-818c253f4ce3.png)

This looks as if the underlined quote is suggested to be replaced with a... quote. In the API, it's an `IncorrectExample` with the marker around the only quote and the quote as a suggestion. IntelliJ, having nothing else to deduce the fix, displays a tautology:
![image](https://user-images.githubusercontent.com/122009/142239703-d0696ee2-4d8b-484d-9a53-a284b68b26ea.png)

Should IntelliJ be adjusted in some way (which one?), or the LanguageTool?

**Comment by danielnaber** [comment]
I've made this change, does it work better like this? https://github.com/languagetool-org/languagetool/commit/317cb41ff33557a64d132253a2830440603c67c2

**Comment by danielnaber** [comment]
Indeed, the example pair is used to check the rule, but if it has no suggestion, then the fact that the incorrect example causes a rule match is enough.
