### ISSUE TITLE
[pt] Proper nouns with doubled consonants to be corrected?

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#6040]
What do Maria Callas, Camilla Cabello, Ladislau Netto, Antonio Gallo, José de Britto have in common?

All of them in Portuguese have a doubled consonant in the name, and all are marked as incorrect. And of course with only one consonant, all are correct (Cabelo, Neto, Galo, Brito, Calas).

So, could there be a way to check if there are doubled consonants, reduce them to one, check in the dictionary and accept these names? 
Or should they be added, one by one (in this case, any name not listed above won't be captured)?

**Comment by marcoagpinto** [comment]
They must be added as proper names, one by one, in spelling.txt and the POS in added.txt.

I will do it at 5am 🙂

**Comment by marcoagpinto** [comment]
Are they real names? I have never seen those words with double consonants.

**Comment by marcoagpinto** [comment]
Spelling mistakes are fixed/suggested by the Hunspell dictionary.

**Comment by ricardojosehlima** [comment]
Ok! They are all real names. Only the part of the name that has double consonants should be added. So, in Maria Callas, no need to add Maria, only Callas; and so on with the other names.

**Comment by marcoagpinto** [comment]
I will add them in the morning 🙂

**Comment by jaumeortola** [comment]
Normally, it is fine to add proper nouns to the dictionary. But when the noun can be confused with another usual and correct word, it could be advisable not to add it. 

Multiwords (expressions or nous with some white space) can be added here: https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/multiwords.txt

**Comment by marcoagpinto** [comment]
@jaumeortola 

Thanks, I will add them there at 5am.

🙂

**Comment by marcoagpinto** [comment]
Done!
