### ISSUE TITLE
[pt] Replacing paronym regex by more universal postags

### ISSUE THREAD

**Issue by Konfekt** [languagetool-org/languagetool#605]
Replacing the regex by more universal postags, such as A* for adjective, P* for propositions which would match many more cases in the paronyms rule, see for example https://github.com/languagetool-org/languagetool/commit/00738e93f40a69226ad45c2a6a002c32f8e90706

Using POSTAG (it would D.|P.) is a good idea but right now no time to test it. 

First try replacing that all article lines with <token postag='(P|D).*' regexp_postag='yes'></token> and see how it goes.

**Comment by Konfekt** [comment]
See also https://gist.github.com/Konfekt/ec7bb1360061ca130b51776bae586fc7 for a list of paronyms.

**Comment by TiagoSantos81** [comment]
See https://gist.github.com/TiagoSantos81/540eed4d497df22890aacda504959732#file-portugueseaccentuationrule

Closing this one.

**Comment by Konfekt** [comment]
👍
