### ISSUE TITLE
[de] Missing abbreviation „einschl.“

### ISSUE THREAD

**Issue by NicoWeio** [languagetool-org/languagetool#6051]
> Zu den Aufgaben gehört die Reinigung des Pachtobjektes einschl. der Glasflächen.

ist falsch-positiv wegen des falsch interpretierten Punktes.

Aus dem _Disambiguator log_:
```
UNKNOWN_PKT[1]: .[./SENT_END*] -> .[./SENT_END*,./PKT*]
```

**Comment by NicoWeio** [comment]
Übrigens ist auch „vmtl.“ betroffen.

**Comment by tiff** [comment]
Both fixed as part of https://github.com/languagetool-org/languagetool/commit/06d47d08d8f6a541231c6357ef2e1bc1edff5a2f
