### ISSUE TITLE
[de] suspended hyphen in german

### ISSUE THREAD

**Issue by mkarneim** [languagetool-org/languagetool#6059]
"Der Wirkstoff wird aus Oliven-, Borretsch-, Leinsamen- und Mandelöl gewonnen."

The words with the suspended hyphen (Ergänzungsstrich) appear as errors in version 5.5.

Is there a solution for this, or is the construct not supported?

**Comment by danielnaber** [comment]
Thanks, this should be fixed with the next version. It only affected a few words, the construct itself was supported already.
