### ISSUE TITLE
[pt] list of commonly confused paronyms

### ISSUE THREAD

**Issue by Konfekt** [languagetool-org/languagetool#606]
The script https://gist.github.com/Konfekt/2328e1ae5f8305199d46fbcbe9dec01b takes a word list and groups them into paronyms, words that differ by a single letter.

However, taking a spell file such as http://www.winedt.org/dict/portuguese.zip, there are far too many. For example by containing all the conjugated verb forms. 

Maybe there are separate list of portuguese substantives, adjectives, infinitives and such?

**Comment by TiagoSantos81** [comment]
That is a great help. Awesome job there. I would improve it in too ways. First we have to set a make a better criteria for disambiguation. 

Hunspell uses in the .aff file criteria to reduce the number of probable confutions. We could use the fonetic model to limit word difference. Search for 'REP' entries to have examples on how they behave. pt-BR.aff has a very complete list and it has a compatible open license, so, it can be reused.

I would first test this hypotesis to know how much can we reduce the number of possibilities with this alone. Improving the 'REP' database seams very easy. This dataset is complete enough to make good estimations.

After that, I can provide a short list with the triaged information for the pt-PT.dic. It is quite simple because, although very incomplete, it has basic morfological information for most common words. Considering that a grammar checker will (probably) never cover all situations, this seams a viable option.

**Comment by Konfekt** [comment]
What's needed is a lista of substantivos, verbos, adjetivos, prépositions and alike. Hardly a verb is confused with an adjective. That would make the job a lot simpler. 

There's à list of substantivos that language tool recognizes. That's à Start.

**Comment by TiagoSantos81** [comment]
https://raw.githubusercontent.com/languagetool-org/languagetool/master/languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/hunspell/pt_PT.dic

CAT=nc   nouns/substantivos
CAT=v     verbs
CAT=..so on

In which format you need the list?

**Comment by TiagoSantos81** [comment]
Follow the link in the string comparison line and tried to understand it. Found the snippet that gives origin to that comparator:
http://www.perlmonks.org/?node_id=500235
```
Example:
my $s1 = 'AAAAA';
my $s2 = 'ATCAA';
my $s3 = 'AAAAA';

hd($s1,s2) # will give value 2
hd($s1,s3) # will give value 0

sub hd
{
     #String length is assumed to be equal
     my ($k,$l) = @_;
     my $len = length ($k);
     my $num_mismatch = 0;

     for (my $i=0; $i<$len; $i++)
     {
      ++$num_mismatch if substr($k, $i, 1) ne substr($l, $i, 1);
     }

     return $num_mismatch;
}
```
In this line:
      ++$num_mismatch if substr($k, $i, 1) ne substr($l, $i, 1);
For each REP line in the pt_BR.aff, can you recursivelly lookup the dictionary and add to the list mismatches of one character?

**Comment by Konfekt** [comment]
Regarding the list, fastest would be one for each category, nouns, verbs, adjectives, prepositions. To simplify detection and the idea also being that people are unlikely to confuse verbs with prepositions, say.

These are the REP lines that make sense to me:
```
por pro
pre per
iz íz
cao ção
ç ss
ss ç
c ss
ss c
ch x
x ch
k qu
íti ití
ití íti
issí íssi
ilí íli
íli ilí
ífi ifí
ifí ífi
nume mune
coen quen
```
That would be a script that replaces all occurrences on the left-hand by the right-hand side, and checks if this modified word is again in the word list.

**Comment by Konfekt** [comment]
Here's what the current perl script spits out for all substantivos in https://raw.githubusercontent.com/languagetool-org/languagetool/master/languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/hunspell/pt_PT.dic:

https://gist.github.com/Konfekt/141b085ec247d8001058e4924954b402

**Comment by Konfekt** [comment]
At the end, there will be some manual labor to see among this list which words are indeed frequently confused. For example, `aflição` and `afeição` could be one of those. 

Maybe there is even a list of common confusions in portuguese?

**Comment by TiagoSantos81** [comment]
> Maybe there is even a list of common confusions in portuguese?

I found some fairly limited sites:
http://www.normaculta.com.br/palavras-homofonas/
http://www.recantodasletras.com.br/gramatica/2576928

Some are already handled by the existing rules, with varying degrees of efficiency.

As you may notice on the links above, many confusions are across group types.
You may also notice that common confusions are mostly phonetic.

'Real life' confusions and misspellings occur according to that REP table, that is design using similar phonemes. Trust me on this. 
'Real life' typos that produce grammar mistakes are near keys. They are represented by in pt_PT.aff by KEYS groups.

Your approach on this group also misses differences in length. Some letters act as accents. The 'r' in 'parto','prato' and 'pato' or the c in 'facto' and 'fato'. 
Exchanged or missing letters can produce huge amounts of useful pairs to be used in wrongWordInContext. 
They may also be easier to find adapting your script. You would need test a permute and a skip for each letter of a word with the next one. Then for each "word" created see if it fits the dictionary. If so, add to list. In this process you can also fill the 'match1' and 'match2 fields', saving the permute (+ surrounding characters) information.


Produce these paired lists in a form similar to the last output you showed but with all the combinations between forms. You can exclude inflected verbs. 
For the first list extend the difference search criteria to 2 characters. Both characters that diverge need to be together, so they represent at most a single difference in one sound.
Using the same example with the sequence AAAAA:

Sequence	Match	Reason
AAAAA		X	(Equal)
ATAAA		V	(1 base)
ATGAA		V	(2 bases)
ATAGA		X	(2 bases separated)
ATCGA		X	(3 bases)

I know how to take care of triaging the pairs from the first list, if you can adapt your output to this. That list will be far too long to be searched manually.

**Comment by Konfekt** [comment]
The script checking for the REP table and the found paronimos are in the repo

https://github.com/Konfekt/languagetool-paronimios

**Comment by Konfekt** [comment]
> Your approach on this group also misses differences in length. Some letters act as accents. The 'r' in 'parto','prato' and 'pato' or the c in 'facto' and 'fato'. 
Exchanged or missing letters can produce huge amounts of useful pairs to be used in wrongWordInContext. 

So how about  a list of those, seems like that by the REP table is incomplete. Your examples suggest adding
```
AR RA
RA AR
AR A
RA A
A AR
A RA
C CT
CT C
```
One all of them are known, they are added to the paronyms script and it is run again on the dictionary.

**Comment by Konfekt** [comment]
As another addition, http://www.recantodasletras.com.br/gramatica/2576928 suggests adding
```
S C
C S
```
too.

**Comment by TiagoSantos81** [comment]
> So how about a list of those, seems like that by the REP table is incomplete. Your examples suggest adding

That REP list is not mine.

> Search for 'REP' entries to have examples on how they behave. pt-BR.aff has a very complete list and it has a compatible open license, so, it can be reused.

I look into your code. I do not have the compiler nor know Perl, but the algoritm seams to be good and easy to adapt.

>  Your examples suggest adding

There are far too many examples of missing and exchanged letters. It needs to be done via scripting. 

Give a few days. I still have the no_replace keyword to test properly from another issue. 
Perl seams basic enough so I will adapt your script to what I have in mind. It is easier to explain that way.

**Comment by Konfekt** [comment]
Ok. Feel free to adapt. To test, there are also in the repo the lists of substantives, verbs and adjectives filtered from the hunspell dictionary https://raw.githubusercontent.com/languagetool-org/languagetool/master/languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/hunspell/pt_PT.dic.

**Comment by TiagoSantos81** [comment]
https://github.com/languagetool-org/languagetool/issues/609#issuecomment-261040349
https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance

Seams like the solution. Can you implement it?

**Comment by TiagoSantos81** [comment]
The version with transposition.

**Comment by Konfekt** [comment]
The module

http://search.cpan.org/~ugexe/Text-Levenshtein-Damerau-0.41/lib/Text/Levenshtein/Damerau.pm

implements the Levenshtein-Damerau distance. The repo 

https://github.com/Konfekt/languagetool-paronimios

has been updated accordingly.

There should be speed improvements.

**Comment by TiagoSantos81** [comment]
Good news. I look briefly at: https://github.com/Konfekt/languagetool-paronimios/blob/master/all.txt
If I understand the output correctly, it seams that this implementation is not perfect. Some pairs have a 'distance' bigger than to transitions.

Looking at the first examples:
```
abacateiro
abacate ->3 changes
abacaxi ->OK
ábaco ->4 changes
abade ->3 changes
abafante ->5 changes
abafar ->4 changes
abafo ->OK
``` 
Maximum distance of 2 is advisable for now.

I have no time right now to adapt the code, nor to develop these specific rules (for paronyms), though I have them in high regard. There is still a lot of adjustments and fixes that I still consider prioritary, as well as, a lot of easy additions with great impact to be added.

I will add PortugueseAccentuationCheckRule as disabled by default, and without java test, tomorrow or one day after, depending on the regression test results of today. This way, you can test and develop it. You will have to activate it on the options to use it.

**Comment by Konfekt** [comment]
Ok. `max_dist = 2` as default is set.

**Comment by TiagoSantos81** [comment]
In here you have a list with max_dist = 1
https://gist.github.com/Konfekt/141b085ec247d8001058e4924954b402
I have triaged and I would like to upload it as dummy version for ngram sets. What is the usage license for the list and the extractor?

**Comment by Konfekt** [comment]
It is the https://fr.wikipedia.org/wiki/WTFPL#Traduction_fran.C3.A7aise_officielle_de_la_version_2

**Comment by TiagoSantos81** [comment]
Great license choice. 
https://en.wikipedia.org/wiki/WTFPL
I would prefer to include the base license (in English) since more people understand it nowdays. Do you mind if I use it instead?

**Comment by Konfekt** [comment]
Of course not!

**Comment by TiagoSantos81** [comment]
A bit of old news, the list has added, with thanks, in 596f55d.

**Comment by TiagoSantos81** [comment]
Problem solved. Thread is dead.
