### ISSUE TITLE
[NL] changed behaviour of some quotes

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#6060]
Something happened to tokenisations earlier this or previous week. Suddenly, some quotes at the start of a word or at the end are considered to be part of the word, causing all kinds of mistakes.

What causes this for Dutch? Could this be rolled back, please?

**Comment by jaumeortola** [comment]
There were changes in the tokenizer 21 days ago, affecting several languages. They cannot be reverted as a whole. 
I can't spot any relevant change in the Dutch tokenizer: https://github.com/languagetool-org/languagetool/commit/b1d4cb284bea36bcc176fb8388651979f5c5eace#diff-9c7e7716d8cee3d4edaa152ec33a073ec9b0f81f37c38c72ee3ce8c7dae46959

Please provide some examples. I will fix them, and they will be added to the tests.

**Comment by jaumeortola** [comment]
You can see here the current tests: https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/nl/src/test/java/org/languagetool/tokenizers/nl/DutchWordTokenizerTest.java

**Comment by baarsrj** [comment]
These results were not in the nightly, but local. Since these results are only presented on screen (I might have to change that, I cannot replay it. There were several occurrences though, for starting single quote like characters, as well as trailing ones. In common rules, not quote related ones.

There is a loop in the code that deletes all quotes (single?) from tokenisation chars for Dutch. That might be an issue, since only characters used as an apostrophe in the middle of a word (and possible after sj-characters in a posessive name form) should be possible to have inside a word.

Anyway, I found one:
FOUTE_WOORDGROEPEN[5]~
Message: U bedoelt vast “anti-elite'”.
Suggestion: anti-elite'
...ht 181: De anti-elite-paradox over elitaire 'anti-elite' acties en bericht 182: 'De kloof' bestaat ni...
                                                ^^^^^^^^^^^                                             
This might be caused by something else. I will close this issue, re-open when there is a new one.
