### ISSUE TITLE
[en] Ignore comments

### ISSUE THREAD

**Issue by flaxel** [languagetool-org/languagetool#6062]
I'm using the [action-languagetool](https://github.com/reviewdog/action-languagetool) and I would like to ignore HTML comments in my documents. So that, for example, no error is thrown for the text due to GitHub being misspelled.

```
<!-- long comment with option --github and important information -->
```

However, I could not find a rule to ignore the comments and would like to see the rule created to use it.

**Comment by danielnaber** [comment]
Rules are used to detect errors. If you want to ignore parts of your text, you'd need to submit `data` instead of `text`(https://languagetool.org/http-api/#!/default/post_check), with the parts to be ignored defined as `markup`.
