### ISSUE TITLE
[all] Testrules does not work

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#6066]
Testrules does not work with snapshot LanguageTool-20211122-snapshot.zip:

```
D:\LanguageTool-5.6-SNAPSHOT>testrules
Error: Could not find or load main class org.languagetool.rules.patterns.PatternRuleTest
Error: Could not find or load main class org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest
Error: Could not find or load main class org.languagetool.rules.bitext.BitextPatternRuleTest
Error: Could not find or load main class org.languagetool.ValidateFalseFriendsXmlTest

D:\LanguageTool-5.6-SNAPSHOT>
```

Possibly, the problem occurred earlier (I have not checked). My last known good was LanguageTool-20211027-snapshot.

**Comment by danielnaber** [comment]
`libs/languagetool-core-tests.jar` is missing from the snapshot. @SteVio89 could this be because of your recent changes? If so, can it easily be fixed?

**Comment by SteVio89** [comment]
My changes are not merged jet. I will check it tomorrow.
