### ISSUE TITLE
Find a missing noun

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#607]
New rule idea: if there is an ADJ (full or sup) LT should look for the unified (or some none varying) noun. If there are no one - the noun was probably missed. Still this can be quite legal to skip this rule for informal style (e.g. Так он и запил горькую [cудьбу is missing] )

**Comment by yakovru** [comment]
Fixed, but in example "Так он и запил горькую" new rule can not detect warning because word
"горькую" can be noun or adj.
