### ISSUE TITLE
several + noun

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#608]
Here LT detects the error:
`Several project can be opened`
And here does not:
`Several CST project can be opened`
It should be `projects` in both cases.

**Comment by Hsankesara** [comment]
@MikeUnwalla are you currently working on this  issue. I want to work on this issue if you're not on it.

**Comment by MikeUnwalla** [comment]
@Hsankesara , thanks for taking over. I appreciate your help.

**Comment by Hsankesara** [comment]
Thanks @MikeUnwalla

**Comment by ella-emc** [comment]
Hello,

I wanted to let you know that this issue seems to be resolved. I tested it again, and it now correctly identifies the grammatical error. We can go ahead and close this issue.

Thanks!
