### ISSUE TITLE
[DE] Fehlalarm mit "mit den albernen Kinderspielen"

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#6081]
Moin liebes LanguagenTool-Team

Beamtin Tori sagt leicht keuchend: „Genug mit **den albernen Kinderspielen**.“
LT: "Möglicherweise fehlende grammatische Übereinstimmung von Kasus, Numerus oder Genus. Beispiel: ‚mein kleiner Haus‘ statt ‚mein kleines Haus‘"

Singular
das Kinderspiel
des Kinderspieles, Kinderspiels
dem Kinderspiel
das Kinderspiel

Plural
die Kinderspiele
der Kinderspiele 
**den Kinderspielen**
die Kinderspiele

Quelle: [Duden](https://www.duden.de/deklination/substantive/Kinderspiel)

mit **den albernen Kinderspielen** ist richtig und nicht falsch.

Grüße Dallun511

**Comment by danielnaber** [comment]
Danke, ist ab morgen behoben.
