### ISSUE TITLE
[Thunderbird add-on] Incompatible with QuickText Keywords

### ISSUE THREAD

**Issue by joreiff** [languagetool-org/languagetool#6085]
## Steps to reproduce
1. Install QuickText
2. Add a QuickText template and assign a keyword
3. Create a new message, type the keyword, and hit tab. The keyword expands to the replacement text.
4. Install the LanguageTool add-on
5. Create a new message, type the keyword, and hit tab. The keyword does NOT expand anymore.

## Workaround
The correct behavior is restored when LanguageTool is disabled via its menu. Inserting the template via QuickText's menu continues working when LanguageTool is enabled, so this seems to be a keyboard-related bug.

## Affected systems
* Thunderbird 78.14 on Debian 10
* Thunderbird 91.3 on Fedora 35

**Comment by danielnaber** [comment]
Note: QuickText is one of the most popular Thunderbird add-ons with ~128K users.

**Comment by joreiff** [comment]
Addendum: I just discovered by accident that QuickText's keyword expansion only seems to be broken in the first line. Simply inserting a newline before the keyword, even without any text, makes keyword expansion work again. Since I rarely use QuickText in the first line, this issue is less severe for me.

**Comment by tiff** [comment]
Thanks for this detailed bug report. We'll have a look very soon

**Comment by Wolf-SO** [comment]
This might be related even though I don't have QuickText installed:

When I press the [Home] key in Thunderbird while composing an email, it is also swallowed in the first line <sup>[1]</sup>, while in other lines it is converted into the expected navigation movement.  I observe this in plain text mode only, not in HTML mode. 

<sup>[1]</sup> I really mean line, not paragraph

**Comment by joreiff** [comment]
Interesting observation. I can confirm that QuickText keywords work correctly in HTML messages, even on the first line.

**Comment by tiff** [comment]
A new version (5.0.6) that fixes this behavior is currently being rolled out. Feel free to reopen if the issue is still occurring.

**Comment by joreiff** [comment]
I can confirm that the issue is fixed with the latest release, thanks!
