### ISSUE TITLE
Check for double spaces

### ISSUE THREAD

**Issue by claell** [languagetool-org/languagetool#6086]
Currently, I think that LT does not offer a check for double spaces in a sentence. Or do I need to manually turn on some "exact" mode or something like that?

Else, I suggest to also check for this.

**Comment by tiff** [comment]
This is very high on our list, and it is constantly worked on. Unfortunately, it isn't as easy as one might think, since we need to parse and understand HTML markup. We'll carefully make this feature available over the next months.

**Comment by danielnaber** [comment]
This should be implemented now for all maintained languages
