### ISSUE TITLE
shot/short, with/withe pair and other rare words

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#609]
WRONG: It is rather shot
CORRECT: It is rather short

May be it can be done with ngrams in general. Probably `rather shot` is always an error.

**Comment by kostyfisik** [comment]
One more pair:
withe /with
Example: A problem withe the manuscript.

**Comment by danielnaber** [comment]
I've added short/short. It detects `It is rather shot.` as an error. In general, it only finds ~ 27% of errors. For withe/with, I don't even find enough example sentences with `withe` to evaluate the pair.

**Comment by kostyfisik** [comment]
`withe` was a typo passed with LT spell-checker, it should be somehow corrected.
![screenshot from 2016-11-16 21-05-08](https://cloud.githubusercontent.com/assets/5239997/20359347/7dd70314-ac40-11e6-86de-873566b99c98.png)

**Comment by danielnaber** [comment]
Maybe we shouldn't accept it at all, considering how rare it is? Maybe @MikeUnwalla has an opinion on this.

**Comment by kostyfisik** [comment]
Does LT has a special warning for usage of extremely rare words? Probably 1-gram statistics?

**Comment by danielnaber** [comment]
No, although that could be developed of course. But would then every word need to be looked up? The lookup is fast, but that might still be too much.

**Comment by MikeUnwalla** [comment]
'Withe' is a rare word. I had to look in a dictionary to find its meaning. We should show the error, and live with the false positives when someone writes and means, "The withe is ..."

**Comment by kostyfisik** [comment]
I think it can be a one-time extraction into a small dictionary `rare-words` having a popular counterpart at Levenshtein distance equals one (and, if it is not too big, two). A warning with possible confusion should be raised for words from such a dictionary (wich should be rather fast).

**Comment by kostyfisik** [comment]
It is quite a universal principle that should fit any European language (any LT supported language?) with 1-gramm data.

**Comment by kostyfisik** [comment]
Or it should be Damerau–Levenshtein distance = 1 as it is used in ispell

**Comment by kostyfisik** [comment]
A smart option: if the replacement of a rare word leads to a detection of some other rule error - do not provide a warning about a rare word.

**Comment by TiagoSantos81** [comment]
> Or it should be Damerau–Levenshtein distance = 1 as it is used in ispell

That was what I was looking for in another thread.

**Comment by danielnaber** [comment]
I've committed `org.languagetool.dev.RareWordsFinder`. Turns out it's not immediately useful, as even a "rare" word like "withe" has 20,000 occurrences in the Google ngram corpus.

**Comment by danielnaber** [comment]
`A problem withe the manuscript.` is detected now, although by a different rule... but still, I'll close this issue, as I don't see a general solution.

**Comment by kostyfisik** [comment]
Probably it is worth to add tag "Unsolved" for this and other cases without any reasonable solution available right now.
