### ISSUE TITLE
Editor shortcut Shift+Del stops working properly in Thunderbird

### ISSUE THREAD

**Issue by Wolf-SO** [languagetool-org/languagetool#6091]
I'm observing this when composing plain-text emails in Thunderbird (Version 91.3.2 (32-Bit) under Windows 8.1).
At some time, the shortcut Shift+Del (which is an alias for Ctrl+X to cut text) stops to work: 

Shift+Del now is interpreted as plain Del (bypassing the clipboard) which is *the* showstopper for the Shift+Del Shift+Ins workflow.

The issue remains if I switch off LT, it's very hard to reproduce when exactly this happens, but this makes it even worse for users. I, somehow, finally found a way to show what I mean:

type in the following (or just paste it):
```
A
B
```

Now cut and paste alternating lines via
- navigate to line start
- select line (Shift+End)
- cut using Shift+Del
- paste by Shift+Ins

Normally this cycle would keep the text intact, but what you'll observe after a few cycles is either
```
A
A
```
or
```
B
B
```
As already mentioned, the issue can be observed even if LT is disabled by its built-in switch, and (as opposed to #6085) it can be confirmed on any two lines.

**Comment by tiff** [comment]
Hi, thanks for reporting this. We will have a look.

**Comment by Xenwolf** [comment]
Thanks for having a look. Maybe it will help to know that there is no comparable issue with Firefox.

Maybe there is a pitfall with the [Shift+Del combination for deleting mails](https://support.mozilla.org/en-US/questions/1207624) (circumventing the trash folder) in the management view of Thunderbird?

**Comment by Wolf-SO** [comment]
Thanks for having a look. Maybe it will help to know that there is no comparable issue with Firefox.

Maybe there is a pitfall with the [Shift+Del combination for deleting mails](https://support.mozilla.org/en-US/questions/1207624) (circumventing the trash folder) in the management view of Thunderbird?

**Comment by tiff** [comment]
A new version (5.0.6) that fixes this behavior is currently being rolled out. Feel free to reopen if the issue is still occurring.

**Comment by Wolf-SO** [comment]
I just wanted to let you know that I can confirm that the problem has been solved in version 5.0.6.

**Comment by tiff** [comment]
Thanks!
