### ISSUE TITLE
[French] [Grammar] agreement issue

### ISSUE THREAD

**Issue by ebanDev** [languagetool-org/languagetool#6106]
![Capture d’écran du 2021-12-01 14-49-32](https://user-images.githubusercontent.com/57091497/144246146-b489f185-8ed9-4570-a655-ec24db556f8f.png)
It should suggest "requis"

**Comment by jaumeortola** [comment]
Thank you, @ebanDev!

**Comment by ebanDev** [comment]
Pleasure :)
