### ISSUE TITLE
[en] Missing Comma false positive before "so"

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#6108]
The Communist Party also was outlawed, and the government defined membership so broadly it could arrest people indiscriminately, branding them Communists.
![image](https://user-images.githubusercontent.com/122009/144290826-3d5cc887-5ba7-4211-8faa-b8dad370ed23.png)

**Comment by MikeUnwalla** [comment]
I think this is a semantic problem. Change _broadly_ to _usually_, and a comma is correct in this position:

> The Communist Party also was outlawed, and the government defined membership, so usually it could arrest people indiscriminately, branding them Communists.

**Comment by donnerpeter** [comment]
True. Nevertheless, it's a false positive :)
