### ISSUE TITLE
[ru] Conjunction comma false positives

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#6119]
Причем, по его словам, сюжет иной раз рождает сама музыка
Причем, отметила она, сажали тогда чаще всего быстрорастущие деревья

Между тем, как сообщают журналисты, всё хорошо

Он торопится, опа а там другая вывеска.

ни один абитуриент не решил задачу по математике, потому что составители этой задачи упустили одно из условий и она была составлена с ошибкой.
(тут запятая между однородными придаточными, вроде не нужна)

**Comment by yakovru** [comment]
Исправлено:
> Причем, по его словам, сюжет иной раз рождает сама музыка Причем, отметила она, сажали тогда чаще всего быстрорастущие деревья
> 
> Между тем, как сообщают журналисты, всё хорошо


Однозначно нужна запятая, но может быть и тире:
> Он торопится, опа а там другая вывеска.

Нужна запятая, в придаточных всё-таки говорится о разных предметах:
>Ни один абитуриент не решил задачу по математике, потому что составители этой задачи упустили одно из условий и она была составлена с ошибкой.

**Comment by donnerpeter** [comment]
> Он торопится, опа а там другая вывеска.

Запятой перед "опа" вроде достаточно. Можно ещё одну поставить, но кажется, что "опа" вполне работает как ещё одно введение в клаузу.

> Нужна запятая, в придаточных всё-таки говорится о разных предметах:
> Ни один абитуриент не решил задачу по математике, потому что составители этой задачи упустили одно из условий и она была составлена с ошибкой.

А что это за правило про разные предметы? Я вот вижу, например, https://russkiiyazyk.ru/punktuatsiya/v-kakih-sluchayah-pered-soyuzom-i-stavitsya-zapyataya.html, и там:

> В сложноподчиненных предложениях с однородным подчинением также не ставится пунктуационный знак.
