### ISSUE TITLE
[pt] Two small (and easy?) fixes

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#6124]
Languagetool suggests for "O eu lírico da narrativa está oculto" that if the intention was to use the verb , it shouldn't receive a diacritic: 
Esta palavra não é um verbo
Se pretende utilizar o verbo, não deve acentuar a palavra.
eu lirico

However, I am unaware of the verb "liricar", and at the same time "eu lírico" is a correct expression (in Brazilian Portuguese).

In the same manner, "Drive" is being considered feminine, so the sentence "O Drive com os arquivos está disponível" is being corrected to "A Drive" and (at least) in Brazilian Portuguese Drive is masculine.

**Comment by marcoagpinto** [comment]
The "drive" is now fixed:
https://github.com/languagetool-org/languagetool/commit/aef82db5aee30c7f4c541c5c9057c13ccd1d7d64

https://github.com/languagetool-org/languagetool/commit/b450ea1b5b73c5ed1acf9d18fa1f86aacf85f161

I will look at the other issue soon.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Maybe:
[ao]s?
+
eu/tu/ele/nós/vós etc.
+
verb
?

an antipattern with this should do it?

**Comment by marcoagpinto** [comment]
Fixed:
https://github.com/languagetool-org/languagetool/commit/ef012aad88231fc4ed4ad1277225401d89cb84fa

Notice that there are rules for each vowel, and my quick fix is just for "i".

**Comment by ricardojosehlima** [comment]
Looks great to me! Thanks

**Comment by marcoagpinto** [comment]
Done!

https://github.com/languagetool-org/languagetool/commit/86dc41caccf9e7353fbbeddee042c6fa7007febd

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I have created an advanced linguistic tool that also support LanguageTool (experimental, very basic):
https://proofingtoolgui.org

It would be great if you downloaded it, opened the grammar.xml with it and suggest improvements for rules names and rules order.

It also allows exporting the structure of the grammar.xml as text for easier reading.

**Comment by ricardojosehlima** [comment]
Thanks a lot, will surely see it!
