### ISSUE TITLE
Regression tests are broken

### ISSUE THREAD

**Issue by yakovru** [languagetool-org/languagetool#6133]
Regression tests  from https://internal1.languagetool.org/regression-tests/ are broken from 2 December.
Tests for Russian are also broken.

**Comment by yakovru** [comment]
@danielnaber 
Regression tests from https://internal1.languagetool.org/regression-tests/ are broken 
Perhaps the data sampling from Wikipedia for tests is empty.
Therefore, the test result is empty.

**Comment by danielnaber** [comment]
Please use these results: https://internal1.languagetool.org/regression-tests/via-http/ - they don't rely on the command-line version of LT, they use the HTTP API instead, which is closer to what most users see.

**Comment by yakovru** [comment]
Ок.
