### ISSUE TITLE
spell checking suggestion improvement

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#6134]
I noticed for some word the order of suggestions is not as good, or the correct suggestion is occasionally missing.
I would like to add a plain list of words and alternatives to the speller, without any coding needed.
A plain list of tab separated words and alternatives would do.

**Comment by jaumeortola** [comment]
This is usually done with a simple replace Java rule. You can use the existing rules, or we can set up a new rule with a different configuration. We need to know what is the desired behavior: only single words or phrases, case-sensitive/case-insensitive, keep case (in the suggestions)...

**Comment by baarsrj** [comment]
That is an option. I will have to get all suggestions for words by MORFOLOGIK, however, to get the current suggestions and compare those. I guess I can do that using the server mode. I will put it on my list.
