### ISSUE TITLE
[nl] split words improvement

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#6136]
When word have been split, LT succesfully suggests the correction without the space:
![afbeelding](https://user-images.githubusercontent.com/8479998/145227496-35c56afc-0fab-43f9-99e7-04177722c9ab.png)
But it does not do this for splitups having hyphen and space, like in books. This happens a lot when working on scanned texts:
Example:
pia- nist

Would this be difficult to address?

**Comment by jaumeortola** [comment]
That is interesting. I have created a simple pattern rule to do it. I think it can work reasonably well, and it can be used in many languages:
 ```
        <rule id="ES_SPLIT_WORDS" name="palabras partidas con guión" default="temp_off">
            <pattern>
                <token regexp="yes">\p{L}+</token>
                <token spacebefore="no">-</token>
                <token regexp="yes" spacebefore="yes">\p{L}+</token>
            </pattern>
            <message suppress_misspelled="yes">Posible palabra mal partida.</message>
            <suggestion>\1\3</suggestion>
            <example correction="pianista">La <marker>pia- nista</marker> canceló el concierto.</example>
        </rule>
```

**Comment by jaumeortola** [comment]
I am going to create similar rules in French and English to test the results.

**Comment by jaumeortola** [comment]
In fact, it is not so easy because `suppress_misspelled` only works for words synthesized with `<match>`

Perhaps we could create a "suppress misspelled filter", which would do a different thing. It will remove misspelled suggestions, no matter how they were created. It will be useful for different purposes.

**Comment by udomai** [comment]
> Perhaps we could create a "suppress misspelled filter", which would do a different thing. It will remove misspelled suggestions, no matter how they were created. 

@jaumeortola, that would be super helpful! I know @affemitkaraffe would like that, too 🙂

**Comment by jaumeortola** [comment]
> > Perhaps we could create a "suppress misspelled filter", which would do a different thing. It will remove misspelled suggestions, no matter how they were created.
> 
> @jaumeortola, that would be super helpful! I know @affemitkaraffe would like that, too slightly_smiling_face

Done here https://github.com/languagetool-org/languagetool/commit/2e0282f812bbfccbe4ff9e5aa20cd87ebd2212f3

You can also create a rule similar to EN_SPLIT_WORDS_HYPHEN in German.
