### ISSUE TITLE
[DE] Das Comeback eines Bugs

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#6142]
Moin liebes LanguageTool-Team,

hiermit melde ich mich erneut zum Bug, wo das LanguageTool einfach alles eines Kapitels einscannt und dann sein Feedback gibt, mit einem Beispieldokument.

Bild 1
![grafik](https://user-images.githubusercontent.com/78316155/145458538-34fdf093-10ee-41a2-878b-ac169765250b.png)
Wir sehen hier ein Text mit **formatierem Titel und formatieren Überschriften**, was für den Bug wichtig ist. 

Bild 2
![grafik](https://user-images.githubusercontent.com/78316155/145458276-e760bb3b-e7b7-4bed-882e-ec8aba592c80.png)
Hier wird **ein Satz** und **nicht** das ganze Kapitel markiert.

Wenn man jetzt auf "Extras" und dann auf **Rechtschreibung** drückt
Bild 3
![grafik](https://user-images.githubusercontent.com/78316155/145458756-b6be76a3-6be6-479f-a7c8-dfb16e811057.png)
ist das, das Ergebnis.

Ich habe den ersten Satz nicht markiert und trotzdem wird dieser als Erstes in der Ausgabe angezeigt.

Dies ist seit längerem der Fall und ich habe auch euch in diesem [Thread](https://forum.languagetool.org/t/de-das-comeback-eines-fehlers/7237) auf die Rückkehr des Fehlers aufmerksam gemacht. Damals mit der Full-Version 5.4.

In diesem Beispiel wurde die Full-Version 5.5.1 verwendet, wo der Fehler weiterhin vorhanden ist.

Geht man zurück in die Vergangenheit zu Full-Version 4.8 und wiederholt die Sache.
Bild 5
![grafik](https://user-images.githubusercontent.com/78316155/145459700-0a7d2efa-3dc6-4a7f-bfda-55d7abce764a.png)

Bild 6
![grafik](https://user-images.githubusercontent.com/78316155/145459445-b65d1d21-1d7a-4497-940d-46906a8e9a5f.png)
Wird nur der markierte Text in der Ausgabe präsentiert und der Rest ignoriert.

Ich bitte darum, dass diese Funktion wieder ein Einzug findet, weil ich ohne diese gar nicht arbeiten kann. Meine Kapitel sind viel zu groß, um mich erst durchzuklicken, bis die Ausgabe bei der Textstelle angekommen ist, die zuvor markiert habe.

Das Bugdokument zum Testen
[Bugtext.zip](https://github.com/languagetool-org/languagetool/files/7687798/Bugtext.zip)

Grüße Dallun511

**Comment by FredKruse** [comment]
@MasterDallun511 Den Bug habe ich behoben. Du kannst ihn ab morgen mit dem aktuellen Snapshot testen.

**Comment by MasterDallun511** [comment]
Ich kann bestätigen, dass die Funktion wieder funktioniert.
