### ISSUE TITLE
BOM in repository files

### ISSUE THREAD

**Issue by jayvdb** [languagetool-org/languagetool#615]
The following files in `languagetool-language-modules/` include a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark):

- [ca/src/main/resources/org/languagetool/resource/ca/tag_verbs.pl](/languagetool-org/languagetool/blob/master/languagetool-language-modules/ca/src/main/resources/org/languagetool/resource/ca/tag_verbs.pl)
- [is/src/main/resources/org/languagetool/resource/is/hunspell/license.txt](/languagetool-org/languagetool/blob/master/languagetool-language-modules/is/src/main/resources/org/languagetool/resource/is/hunspell/license.txt)
- [km/src/main/resources/org/languagetool/rules/km/replace.txt](/languagetool-org/languagetool/blob/master/languagetool-language-modules/km/src/main/resources/org/languagetool/rules/km/replace.txt)
- [km/src/main/resources/org/languagetool/resource/km/tagset.txt](/languagetool-org/languagetool/blob/master/languagetool-language-modules/km/src/main/resources/org/languagetool/resource/km/tagset.txt) - no need for BOM in this file as far as I can see
- [pl/src/main/resources/org/languagetool/resource/pl/hunspell/README_en.txt](/languagetool-org/languagetool/blob/master/languagetool-language-modules/pl/src/main/resources/org/languagetool/resource/pl/hunspell/README_en.txt)
- [pl/src/main/resources/org/languagetool/resource/pl/tagset.txt](/languagetool-org/languagetool/blob/master/languagetool-language-modules/pl/src/main/resources/org/languagetool/resource/pl/tagset.txt)
- [pl/src/main/resources/org/languagetool/rules/pl/grammar.xml](/languagetool-org/languagetool/blob/master/languagetool-language-modules/pl/src/main/resources/org/languagetool/rules/pl/grammar.xml)
- [ru/src/main/resources/org/languagetool/resource/ru/tagset.txt](/languagetool-org/languagetool/blob/master/languagetool-language-modules/ru/src/main/resources/org/languagetool/resource/ru/tagset.txt)
- [sk/src/main/resources/org/languagetool/rules/sk/grammar-typography.xml](/languagetool-org/languagetool/blob/master/languagetool-language-modules/sk/src/main/resources/org/languagetool/rules/sk/grammar-typography.xml)
- [sl/src/main/resources/org/languagetool/resource/sl/hunspell/README_sl_SI.txt](/languagetool-org/languagetool/blob/master/languagetool-language-modules/sl/src/main/resources/org/languagetool/resource/sl/hunspell/README_sl_SI.txt)
- [sv/src/main/resources/org/languagetool/resource/sv/hunspell/LICENSE_en_US.txt](/languagetool-org/languagetool/blob/master/languagetool-language-modules/sv/src/main/resources/org/languagetool/resource/sv/hunspell/LICENSE_en_US.txt)
- [sv/src/main/resources/org/languagetool/resource/sv/hunspell/LICENSE_sv_SE.txt](/languagetool-org/languagetool/blob/master/languagetool-language-modules/sv/src/main/resources/org/languagetool/resource/sv/hunspell/LICENSE_sv_SE.txt)
- [zh/src/main/resources/org/languagetool/rules/zh/grammar.xml](/languagetool-org/languagetool/blob/master/languagetool-language-modules/zh/src/main/resources/org/languagetool/rules/zh/grammar.xml)

Note that the [tests pass](https://travis-ci.org/languagetool-org/languagetool/builds/178264163) without the BOM, but I dont know whether the tests are sufficient for this.
I do know that many other files with UTF encoding do not have a BOM.
Consistency would be good.

**Comment by danielnaber** [comment]
I'm closing this as I don't see a real problem here.
