### ISSUE TITLE
Support of Tables, Footnotes in LibreOffice Text-Documents

### ISSUE THREAD

**Issue by FredKruse** [languagetool-org/languagetool#6151]
Add support for tables footnote etc.
This includes the support of text level check inside table-cells, footnotes, etc. The cursor setting from LT grammar check dialog as well as the examination of the cursor position (also inside tables, etc.)

**Comment by FredKruse** [comment]
@danielnaber The development is done so far. Bugs are solved as far as I got them. I'm in the phase of testing the extension with real documents. On the other hand, the changes concern the core code of the extension and there is left few time till publishing version 5.6. I wonder if I should wait to commit until the development of 5.7 starts.

**Comment by danielnaber** [comment]
My suggestion is to wait, so we can have a stable 5.6 release.

**Comment by FredKruse** [comment]
Solved in 5.7
