### ISSUE TITLE
[Feature req]: vscode extension

### ISSUE THREAD

**Issue by maximilianMairinger** [languagetool-org/languagetool#6155]
I would personally appreciate a vscode extension. Specifically for comments. 

I assume this wouldn't take a lot of effort, departing from the already existing browser extensions. I would be happy to help "developing" the necessary UI (login etc.) + handling the I/O, if you consider this worth pursuing.

**Comment by danielnaber** [comment]
You can find extensions developed by the community (including ones for vscode) here: https://dev.languagetool.org/software-that-supports-languagetool-as-a-plug-in-or-add-on
