### ISSUE TITLE
[ru] false positive for "ненадолго" needs to be spelled separately

### ISSUE THREAD

**Issue by Katzen-Gott** [languagetool-org/languagetool#6165]
"Он замолкает ненадолго, а потом поет печальную песню" — Пишет, что "ненадолго" должно быть раздельно "Пишется раздельно с «не», имеется противопоставление с союзом «а»: «не надолго, а потом».", хотя противопоставление тут нет. "А" относится к "потом", а не к "ненадолго". Надеюсь это можно починить.

**Comment by yakovru** [comment]
Спасибо.
Исправлено.
