### ISSUE TITLE
[ru] полу missing R2 case

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#6168]
![image](https://user-images.githubusercontent.com/122009/146733806-ac120370-a1dc-425a-b4f2-53aadbece1bd.png)

Judging by https://ru.wikipedia.org/wiki/%D0%A0%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D0%BF%D0%B0%D0%B4%D0%B5%D0%B6#%D0%92%D1%82%D0%BE%D1%80%D0%BE%D0%B9_%D1%80%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9, it should be a second genitive (R2)

**Comment by yakovru** [comment]
Fixed via https://github.com/languagetool-org/languagetool/commit/475ed3931466e64b4bfe19e7e5c144aaa1002d91
