### ISSUE TITLE
[ru] Self inconsistent rules

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#617]
Check on web:
По количеству опубликованных работ в научных журналах.

The result:
![screenshot from 2016-11-24 11-34-34](https://cloud.githubusercontent.com/assets/5239997/20591562/2d930740-b23a-11e6-8696-28d138ab862d.png)

After correction:
![screenshot from 2016-11-24 11-34-18](https://cloud.githubusercontent.com/assets/5239997/20591578/3c94655e-b23a-11e6-86fe-943a40d5b54c.png)

**Comment by yakovru** [comment]
This rule is now being developed. The process is not completed.

**Comment by kostyfisik** [comment]
Ok. Probably you can add this example to both rules.

**Comment by yakovru** [comment]
[object Object] is result of parametr  suppress_misspelled="yes" in suggestion.
It would be nice if this result does not stop the trigger the rules, and do not show an empty result.

**Comment by yakovru** [comment]
Another option -  modify the filter in the rule.

**Comment by yakovru** [comment]
Fixed.
