### ISSUE TITLE
[office-integration] Error while checking text with pictures

### ISSUE THREAD

**Issue by yakovru** [languagetool-org/languagetool#6175]
Error while checking text with pictures.
How to reproduce.
1. Make or open LibreOffice document with picture.
2. Select  any picture in document with mouse (one click to picture).
3. Press F7.
4. Get Error message.
![LT_int_picture](https://user-images.githubusercontent.com/5228814/146924356-18f80a3c-ed67-43af-a5a4-9225f8b82200.png)

**Comment by yakovru** [comment]
Upd: If the text being checked contains pictures, then it is possible to loop when checking through the dialog called by F7

**Comment by yakovru** [comment]
@FredKruse

**Comment by FredKruse** [comment]
The problem can't be solved completely, because all objects like pictures, graphics or text objects are not supported by the LO/OO grammar check interface. But know the bug is captured, and the user will be requested to place the cursor into the text.

Please test it with the next snapshot.

**Comment by yakovru** [comment]
Now, when user selects a picture, a warning is displayed. Pictures are processed correctly.

**Comment by yakovru** [comment]
Thanks!
