### ISSUE TITLE
When a local server (localhost) is preferred, the browser extension must not allow the 'Enable synonyms' feature

### ISSUE THREAD

**Issue by grahamperrin** [languagetool-org/languagetool#6177]
Extension version 4.4.1 added to Firefox: 

![image](https://user-images.githubusercontent.com/192271/146993328-f62419c7-b365-46f2-ae8d-55d735a66eff.png)

I spent a few hours trying, failing to understand why the feature did not work. No mention of _synonym_ at <https://dev.languagetool.org/http-server>. 

[Eventually](https://forum.languagetool.org/t/synonyms-feature-not-working-with-sites-such-as-freebsd-forums-xenforo-dpaste-and-pastebin-com/7507/5?u=grahamperrin) I learnt, thanks to @danielnaber: 

> The synonym feature doesn’t work when an on-premise server is in use. …

### Suggestions

Fix the extension GUI to disallow feature combinations that are impossible. 

Update <https://dev.languagetool.org/http-server>. 

Thanks

**Comment by tiff** [comment]
This should not happen anymore with v.4.4.2

**Comment by grahamperrin** [comment]
https://addons.mozilla.org/en-GB/firefox/addon/languagetool/versions/4.4.2/updateinfo/ was empty. 

Fix confirmed with 4.4.3: 

![image](https://user-images.githubusercontent.com/192271/148010624-cb7fa3c5-4c1e-4101-bdde-2093d32141ad.png)

– the option typically appears, for a split-second, disabled, before disappearing: 

![image](https://user-images.githubusercontent.com/192271/148010201-65439c43-ae3b-4d88-b680-880f31b5428b.png)

Thank you!

**Comment by grahamperrin** [comment]
Also noted, with thanks, from <https://dev.languagetool.org/http-server#starting-from-command-line>: 

> … Note: The LanguageTool server doesn’t support synonyms, so the synonym feature in the add-on will not work. …
