### ISSUE TITLE
[de] DEF_ARTIKEL_INDEF_ADJ[1] needs work (FPs, faulty suggestion)

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#6179]
Die Regel [DEF_ARTIKEL_INDEF_ADJ[1]](https://internal1.languagetool.org/regression-tests/via-http/2021-12-22/de-DE/result_grammar_DEF_ARTIKEL_INDEF_ADJ[1].html) müsste nachgebessert werden. Heute sind neue FPs dazugekommen, aber auch in den [Full_Results](https://internal1.languagetool.org/regression-tests/via-http/2021-12-22/de-DE_full/result_grammar_DEF_ARTIKEL_INDEF_ADJ[1].html) sind vor allem FPs.

Die Regel wird gerne von einem fehlenden Komma vor Relativpronomen verwirrt. Außerdem ist die erste Suggestion meistens mit dem Ursprungswort identisch. Es gibt auch FPs in völlig richtigen Sätzen.

>  Sie ist die **jüngste** Düsseldorfer Rheinbrücke, sie wurde zwischen 1998 und 2002 gebaut.

In den letzten 30 Tagen:

\> 5k opens, 0.26 % disables, 57.5 % apply

**Comment by tiff** [comment]
Closing this. Most cases have been fixed and a few more are about to be fixed.

I changed the priority to be less than `DE_AGREEMENT` and now `DE_AGREEMENT` makes a much better suggestion.
https://internal1.languagetool.org/regression-tests/via-http/2021-12-24/de-DE/result_grammar_DEF_ARTIKEL_INDEF_ADJ[1].html

Some remaining false alarms are tackled piece by piece.
