### ISSUE TITLE
How to get token?

### ISSUE THREAD

**Issue by rezaffm** [languagetool-org/languagetool#6182]
Hi,

we started to develop an extension for tiptap editor.

However, we don't want to run our own api server and would like to continue using our premium accounts for LT.

I noticed when logging in through the Chrome extension, a token is sent when using this url: https://languagetool.org/client-login?callback_uri=chrome-extension%3A%2F%2Foldceeleldhonbafppcapldpdifcinji%2Fwelcome%2FloginRedirectUri.html

So, I guess it is an oauth2 server or something similar.

I am pretty sure there must be an api endpoint for exchanging user details vs. a token and would appreciate if you could tell us how this would work.

Once the extension is finalized, we will make it open source by the way.

**Comment by danielnaber** [comment]
Solved via support desk
