### ISSUE TITLE
The extension for Firefox uses phrases such as 'these instructions' and 'see our privacy policy' but lacks the required links

### ISSUE THREAD

**Issue by grahamperrin** [languagetool-org/languagetool#6185]
A [browser-add-on](https://github.com/languagetool-org/languagetool/labels/browser-add-on) bug: 

![image](https://user-images.githubusercontent.com/192271/147343355-1712c0ae-43b5-4931-adfa-d6f687ab6997.png)

### Suggestion

If Mozilla disallows linking in this context, then please make explicit (in plain text) the intended address. I assume: 

<https://dev.languagetool.org/http-server>

`https://dev.languagetool.org/http-server`

> LanguageTool embedded HTTP Server | dev.languagetool.org

Thank you

**Comment by grahamperrin** [comment]
Similarly, phrases such as: 

> See our privacy policy 

![image](https://user-images.githubusercontent.com/192271/147344506-4cec23ea-da53-4b63-9f82-c38e92396b9d.png)

A reader might think to browse to the home page, then (through the footer):  

* <https://languagetool.org/legal/privacy>

The link that's missing from the about:addons view of things is, effectively: 

* `https://addons.mozilla.org/addon/languagetool/privacy/`

– <https://addons.mozilla.org/addon/languagetool/privacy/>, redirecting to e.g. <https://addons.mozilla.org/en-GB/firefox/addon/languagetool/privacy/> where the policy is significantly different.

**Comment by danielnaber** [comment]
This should be fixed now (might take until the next update before it becomes visible).

**Comment by grahamperrin** [comment]
Thanks!
