### ISSUE TITLE
Privacy: inconsistent statements

### ISSUE THREAD

**Issue by grahamperrin** [languagetool-org/languagetool#6186]
From the screenshot at <https://github.com/languagetool-org/languagetool/issues/6185#issuecomment-1000773511>: 

> … don't store your IP address. …

From <https://addons.mozilla.org/en-GB/firefox/addon/languagetool/privacy/>: 

> … your IP address is stored …

From <https://languagetool.org/legal/privacy>: 

> … The processing of personal data on this website and in our add-ons is carried out in accordance with the European General Data Protection Regulation (GDPR) and the German Federal Data Protection Act, Bundesdatenschutzgesetz (BDSG 2018). …

No mention of GDPR etc. at <https://addons.mozilla.org/en-GB/firefox/addon/languagetool/privacy/>.

**Comment by danielnaber** [comment]
Please quote properly:

> In our web server log files, your IP address is stored in an abbreviated form (like 192.168.xxx.xxx) so it cannot be used to identify you.

I don't see why the GDPR needs to be mentioned here, too.

**Comment by grahamperrin** [comment]
> Please quote properly:

Sorry, here's the more significant inconsistency, with added emphasis: 

>> … We **don't** store your IP address. See our privacy policy for more details. …
