### ISSUE TITLE
Clarity re: bug reporting

### ISSUE THREAD

**Issue by grahamperrin** [languagetool-org/languagetool#6188]
From <https://addons.mozilla.org/en-GB/firefox/addon/languagetool/>: 

> Please report bugs at https://forum.languagetool.org or at github.

From more recent <https://forum.languagetool.org/t/about-the-browser-addon-privacy-and-open-source/7505/7?u=grahamperrin>: 

> … Please post bugs only to the bug tracker.

**Comment by danielnaber** [comment]
People are free to post bugs to the forum if they are not familiar with GitHub, but please don't post the same issue to both the forum and GitHub.
