### ISSUE TITLE
Local server fails to start with '--allow-origin "*"' parameter

### ISSUE THREAD

**Issue by romCHKDSK** [languagetool-org/languagetool#6190]
I am trying to run LanguageTool-5.5 embedded HTTP server on Windows 10 using java version "17.0.1" 2021-10-19 LTS.
Using the command line ```java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081 --allow-origin "*"```, as described in the documentation, the server refuses to start, instead showing usage help (Usage: HTTPServer --config...).
The server starts normally if I remove the --allow-origin argument or use any parameter other than "*". Using single quotes or no quotes at all doesn't seem to help.
I tried starting the server from both powershell and command line, as well as using different java runtime environments, but it seems to make no difference.
Any help would be appreciated.

**Comment by danielnaber** [comment]
Please try a recent snapshot from https://internal1.languagetool.org/snapshots/ using this command:

`java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081 --allow-origin`

**Comment by romCHKDSK** [comment]
That worked, thank you very much!
