### ISSUE TITLE
[fr] "du Danemark"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6193]
> Pour eux, cela demeurait un leurre pour quelque chose de pourri au royaume du Danemark (énoncé de Shakespeare, tirée de « Hamlet »).

User claims (but isn't sure) that it should be "de Danemark"

**Comment by udomai** [comment]
The user is incorrect. This country is used with the article, i.e. "le Danemark", which requires "du" and not "de". There are some fixed expressions where the "de" is mandatory, though. Opening a separate issue for article usage with country names :)
