### ISSUE TITLE
[en] unpaired quotation marks

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#6195]
See: https://forum.languagetool.org/t/check-on-quotes/2661/7

Now, there are no quotations marks in EnglishUnpairedBracketsRule, probably because of too many false positives (https://github.com/languagetool-org/languagetool/commit/9773e6142d45d930afe88ed9d30d1ed9bba574c0). If we add them again, we will need to take care of false alarms.

**Comment by jaumeortola** [comment]
I created a separate rule (EnglishUnpairedQuotesRule, temp_off) so we can test and fix FPs. https://github.com/languagetool-org/languagetool/commit/6eedfa7c6dd121bba460a95a0015535c2f3e31d9

**Comment by jaumeortola** [comment]
Test results: https://internal1.languagetool.org/regression-tests/via-http/2021-12-29/en-US/result_java_EN_UNPAIRED_QUOTES.html

With curly double quotes, there are no false positives. 

Single quotes (curly or straight) are more tricky. We need to add exceptions: 
```
You're only foolin' round.
Please find attached Fritz' revisions
I stayed awake 'till the morning.
```
Quotes and possessive can be confused sometimes:
```
naming the Cleveland Browns defense 'The Dawgs' in the mid-80's.
```

COMMENT: straight double quote is active in the rule EN_UNPAIRED_BRACKETS.

**Comment by AzadehSafakish** [comment]
To start, apostrophe exceptions from the diff:

'bout
'burbs
'cause
'cuz
'em
'er
'lil
'n
'ol
'ole
'spose
'sposed
'til
'till
'tis
'twas
'twere
'twixt

an'
gangsta'
.*in' (sittin', searchin', nothin', freakin', etc.)
Jack-o'-lantern
Jack o'lantern
jus'
o'
o'er
slo'
tho'
tol'
ya'
y'know

As you know, possessives:
.*s'
.*z'

**Comment by jaumeortola** [comment]
Thanks! Most exceptions added here: https://github.com/languagetool-org/languagetool/commit/e6a427d18bda93f853cf908be1045e58d8ad69de
I have also improved the tokenizer and the tagger for `sittin', searchin', nothin', freakin', etc.`. Now, the apostrophe goes inside the token, and the token gets the tags from the -ing word.
