### ISSUE TITLE
Extracting the version from the pom.xml file for version 5.6

### ISSUE THREAD

**Issue by Erikvl87** [languagetool-org/languagetool#6198]
I am using the version extracted from the `pom.xml` file in a pipeline for building the Docker container [erikvl87/languagetool](https://github.com/Erikvl87/docker-languagetool). The location of that version element got changed. 

https://github.com/languagetool-org/languagetool/issues/3659#issuecomment-703843554:
> The main location for the version is `//project/properties/languagetool.version` in the top-level `pom.xml`.

The version element seems to have been removed in the following commit: https://github.com/languagetool-org/languagetool/commit/db14956a454e7b6c845c6e31114a75e96baca05d

Is it safe to say that the new location to determine the appropriate LanguageTool standalone version is now at `//project/version`?

**Comment by danielnaber** [comment]
> Is it safe to say that the new location to determine the appropriate LanguageTool standalone version is now at //project/version?

Currently, it is, although it might change in the future.

**Comment by Erikvl87** [comment]
Thank you for the quick response, @danielnaber. For now I'll change it accordingly.

**Comment by Erikvl87** [comment]
For version `5.7`, the path `//project/version` now contains `${revision}` instead of an actual version. I expected `5.7`.

I am using the extracted version in CI to resolve the proper target zip file (`/languagetool/languagetool-standalone/target/LanguageTool-5.7.zip`) after executing `mvn package`.
See: https://github.com/Erikvl87/docker-languagetool/blob/v5.6/Dockerfile#L28

From where can I extract the exact same version that is also used in the zip filename?

**Comment by danielnaber** [comment]
Currently, it seems to be at `properties/revision`, isn't it?

**Comment by Erikvl87** [comment]
Right, Thanks @danielnaber. I thought I scanned through the file looking for the version but I've overseen this one. Thank you.
