### ISSUE TITLE
[en] "can't ran" (Wrong modal verb 'ca')

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#6204]
Looks like it's an error with words + n't.

- [ ] You can't **ran** away.

gives this error in the description:

> **Grammatical problem: use the base form:**
> The modal verb ‘ca’ requires the verb’s base form.

'ca' should be 'can'.

- - -

There's also:

- You won't **ran** away. ('wo' -> "will")
- You shan't **ran** away. ('sha' -> "shall")

Although this is correct:

- You couldn't **ran** away. ('could')

I didn't test any other n't words.

**Comment by danielnaber** [comment]
@jaumeortola Is this maybe a side effect of changing the tokenization some time ago?

**Comment by jaumeortola** [comment]
Yes. We need to rewrite someway the message of the rule MD_BASEFORM. It should be: `The modal verb ‘can’ requires the verb’s base form.` or `The modal verb ‘can't’ requires the verb’s base form.`

**Comment by jaumeortola** [comment]
@udomai With the current tagging for modal verbs, there is no easy fix. We would need a particular tag for the "base form" of the modal verb (can vs. cannot could canst...). It should be something like `can[can/MD, can/MD_BASEFORM]`, but it could interfere with disambiguation and grammar rules. 
Possible solutions: 
- Change the message. Something like `After a modal verb, the verb's base form is required`.
- Duplicate the rules (from 2 to 4): some for "can" and the other for "can't", and use the message `The modal verb ‘can't’ requires the verb’s base form.` for the second.

**Comment by udomai** [comment]
Thanks for looking into this! Let's go for a pragmatic solution (the first option seems fine). @plumaj, can I hand you over the raw task?

- find out which rules are concerned
- change the message (or split the rule)

**Comment by plumaj** [comment]
I've gone through all the rules that contain `MD` in the ID and made some changes where necessary.
