### ISSUE TITLE
[en] Broken Misspelling Detection ’ vs. ' (Smart vs. Dumb Apostrophe)

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#6217]
This curly apostrophe version is marked as misspelled:

- [x] coup d’***état***

but the dumb apostrophe version is correctly ignored:

- coup d'état

Same with these:

- ***maître*** d’***hôtel***
- ***maîtres*** d’***hôtel***
- O’***Hanlon***

vs. correctly ignored:

- maître d'hôtel
- maîtres d'hôtel
- O'Hanlon

- - -

**Note:** Tested on LanguageTool 5.6 standalone + the latest online version as of today (2022.01.07).

Also happened in LT 5.5. I did not test any further back.

I caught these while testing words in [/en/hunspell/spelling.txt](https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt).

**Comment by danielnaber** [comment]
Closing, as they all seem to be accepted now.
