### ISSUE TITLE
[es] "40dB" marked as misspelling

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6228]
![Bildschirmfoto 2022-01-10 um 08 16 09](https://user-images.githubusercontent.com/37363/148729771-661000be-d714-4034-8d48-96fbf0ac5be0.png)

I guess this happens with other units as well?

**Comment by tiff** [comment]
Also, the word after "40dB." is detected as the start of a new sentence:
> De forma prácticamente insólita —es difícil encontrar un dato así en las series demoscópicas—, los socialistas aparecen por delante del PP como el partido en el que los ciudadanos confían más para gestionar la economía y el empleo, según la encuesta de 40dB. para EL PAÍS y la Cadena SER, de la que hoy estarán disponibles, por vez primera en este tipo de encuestas, todos los datos detallados en Elpais.es.

Not sure if the period after "40dB" is correct.

**Comment by jaumeortola** [comment]
`40 dB` could mean  "40 decibels" without period. We should provide this suggestion. 

But here `40dB.` is a (very strange) company name. Never heard of it. It can be added to multiwords.txt.

**Comment by tiff** [comment]
Ah got it. I just checked a random news article on elpais.com to debug a different problem
