### ISSUE TITLE
[de] capitalized "Deine" not tagged

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6231]
> Das sind **Deine** Ideen.
> Das ist **Dein** Haus.

"Dein" is not tagged in both sentences, which causes false alarms and reduces Recall. Can we just add the tagging?

@udomai @danielnaber

**Comment by tiff** [comment]
Example for a false alarm:

![Bildschirmfoto 2022-01-10 um 11 09 53](https://user-images.githubusercontent.com/37363/148748867-8d907673-5a3c-4d1b-b526-438662f6c192.png)

**Comment by jaumeortola** [comment]
"Tag all capitalized words with tags for the lower case word, if the capitalized form has no specific tags" is something that can be done in the tagger. But perhaps it has downsides if used generally. I don't know. At least in French, Catalan and Spanish it is done.

**Comment by udomai** [comment]
I like your general approach. We could try it in a branch and see if it causes any failures. Then we could run it on the test server.

**Comment by tiff** [comment]
OK, I think this issue is a bit out of the original scope. Feel free to do try this approach if there's nothing holding you back.
I will add manual tagging for capital `Dein(e[rsnm]?)?` tonight, as it was already done for `Ihre`.

**Comment by tiff** [comment]
Done, regressions are looking good
