### ISSUE TITLE
[de] GERMAN_SPELLER_RULE gives strange suggestion

### ISSUE THREAD

**Issue by udomai** [languagetool-org/languagetool#6241]
> Gibt es **einen grund**, dass…

→ eineng rund

Die Logik macht total Sinn für Fehler wie diesen:

> Ich habe einen eue Garage.

Aber wenn das Wort nach "einen" großgeschrieben im dict ist, sollte es vielleicht einzeln gematcht werden.

![image](https://user-images.githubusercontent.com/67792088/149132140-45c60c17-1a97-4926-89e3-ecee9c1b60ab.png)

**Comment by tiff** [comment]
This specific case might be solved when you add "eineng" to "ignore.txt"

**Comment by tiff** [comment]
Another case:

![Bildschirmfoto 2022-01-13 um 14 43 14](https://user-images.githubusercontent.com/37363/149341198-b69268fd-0426-4ec5-a9b9-51d7a8ecc777.png)

I think the speller should never suggest single capitalized words.

**Comment by tiff** [comment]
Adding "eineng" to "ignore.txt" does not solve this

**Comment by Wolf-SO** [comment]
Wenn ich LT so Schritt für Schritt einenge (*eineng*, *eineng*), wird es mir dann auf Dauer zuverlässig helfen? Scherz beiseite, ich habe das Gefühl, dass Fehler in der Groß-/Kleinschreibung aktuell so manchen für Menschen naheliegenden Match vereitelt. Siehe dazu auch #6394.
