### ISSUE TITLE
Conflict between testrules message and LT behaviour with chunks

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#625]
Using LT 3.6 snapshot 2016/11/30

Sentence to test: Do not let the water drain quickly from the container.

Tagger result for the test sentence:
`<S> Do[do/VB,do/VBP,B-VP] not[not/RB,I-VP] let[let/VB,I-VP] the[the/DT,B-NP-singular] water[water/NN:U,I-NP-singular] drain[drain/NN,drain/VB,drain/VBP,E-NP-singular] quickly[quickly/RB,B-ADVP] from[from/IN,from/RP,B-PP] the[the/DT,B-NP-singular] container[container/NN,E-NP-singular] .[./.,</S>,O] `

This grammar rule uses a chunk B-ADVP to find adverbs:
```
<rule id="chunker_test" name="chunker test">
    <pattern>
        <token chunk="B-ADVP"/>
    </pattern>
    <message>'\1' is an adverb.</message>
    <example correction="">Do not let the water drain <marker>quickly</marker> from the container.</example>
    <example>This sentence is correct.</example>
</rule>
```

LT gives the expected result:
![chunker-test](https://cloud.githubusercontent.com/assets/5816160/20860299/ad76c04e-b96c-11e6-8958-e0a22e3ebca1.png)

Part of the output from 'testrules':
```
Running XML validation for en/grammar.xml...
cvc-enumeration-valid: Value 'B-ADVP' is not facet-valid with respect to enumeration '[B-NP-singular, B-NP-plural, I-NP-
singular, I-NP-plural, E-NP-singular, E-NP-plural, B-VP, I-VP, B-PP, I-PP, containsTypewriterApostrophe]'. It must be a
value from the enumeration. Problem found at line 49, column 32.
Exception in thread "main" java.io.IOException: Cannot load or parse '/org/languagetool/rules/en/grammar.xml'
        at org.languagetool.XMLValidator.validateWithXmlSchema(XMLValidator.java:123)
        at org.languagetool.rules.patterns.PatternRuleTest.validatePatternFile(PatternRuleTest.java:226)
        at org.languagetool.rules.patterns.PatternRuleTest.runTestForLanguage(PatternRuleTest.java:155)
        at org.languagetool.rules.patterns.PatternRuleTest.runGrammarRulesFromXmlTestIgnoringLanguages(PatternRuleTest.j
ava:150)
        at org.languagetool.rules.patterns.PatternRuleTest.main(PatternRuleTest.java:571)
Caused by: org.xml.sax.SAXParseException; lineNumber: 49; columnNumber: 32; cvc-enumeration-valid: Value 'B-ADVP' is not
 facet-valid with respect to enumeration '[B-NP-singular, B-NP-plural, I-NP-singular, I-NP-plural, E-NP-singular, E-NP-p
lural, B-VP, I-VP, B-PP, I-PP, containsTypewriterApostrophe]'. It must be a value from the enumeration.
```
If 'testrules' is correct and B-ADVP (and others) should not be used, could LT give an error message when it is started?

**Comment by danielnaber** [comment]
> If 'testrules' is correct and B-ADVP (and others) should not be used, could LT give an error message when it is started?

Technically yes, but that would mean to write the code that checks for valid chunks twice. I think it's better to have it in the XML validation (which is what testrules is doing) only. We *could* just accept tags like `B-ADVP`, but that would make it more difficult to replace the chunker later. Replacing the chunker should be an option, as the current one is slow and not always accurate.

**Comment by MikeUnwalla** [comment]
OK. I removed the 'bug' label.

**Comment by MikeUnwalla** [comment]
OK. I removed the 'bug' label.
