### ISSUE TITLE
[ca] baba, missatge d'avertiment

### ISSUE THREAD

**Issue by xalbons** [languagetool-org/languagetool#6254]
Com en altres casos semblants, caldria afegir una regla d'advertiment de possible confusió per a la forma _baba_ (Possible confusió. «baba» existeix com a forma de llenguatge infantil per 'àvia').

**Comment by jaumeortola** [comment]
Gràcies. Tenim algunes regles per a "mala *baba/bava", "caure la *baba/bava", "*babes/baves". Podríem ampliar els casos en què fem l'advertiment o simplement fer-lo sempre.

**Comment by xalbons** [comment]
Mirant una mica les col·locacions que dona el [TermGallery](https://term.gallery/catal%C3%A0/baba), gairebé ho faria a l'inrevés i deixaria el cas de "baba [A-Z][a-z]+" com a cas en què no aparegués l'avís i en la resta de casos que aparegués sempre.

**Comment by jaumeortola** [comment]
Hi he dedicat una mica de temps perquè totes dues paraules són prou comunes. Ara no passarem per alt gairebé cap cas de baba -> bava. En els casos dubtosos apareixerà l'advertiment, i hi haurà un 10% de falsos positius, que encara és alt, però no és greu.
