### ISSUE TITLE
Maven test summary shows success, but a rule contains errors

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#627]
Refer to https://github.com/languagetool-org/languagetool/commit/c69a5ee42be05c5950942c02672fce3375f6556e

I downloaded LanguageTool-20161206-snapshot.zip this morning. When I ran testrules, I got this error:
```
The English rule: DT_plural_VBNNN_VBN[1], token [1], contains "those" that is marked as regular expression but probably is not one.
The English rule: DT_plural_VBNNN_VBN[1] (POS tag), token [2], contains "VBD" that is marked as regular expression but probably is not one.
```

Then, I synced my GitHub clone. When I ran the Maven test, I got these lines at the end of the results:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] languagetool-parent ................................ SUCCESS [  1.370 s]
[INFO] LanguageTool Style and Grammar Checker Core ........ SUCCESS [ 53.507 s]
[INFO] English module for LanguageTool .................... SUCCESS [ 49.680 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:45 min
[INFO] Finished at: 2016-12-07T09:27:32+00:00
[INFO] Final Memory: 26M/299M
[INFO] ------------------------------------------------------------------------
```

The summary shows SUCCESS for the English module. But, in the middle of the results, there is a message about the error in DT_plural_VBNNN_VBN.

Is this summary correct? Could the summary be made to include a warning about the error?

**Comment by danielnaber** [comment]
This is just a warning, so it doesn't make the build fail. The final message comes from Maven, I don't think we can make it mention the warning. We could change the logic so the build fails, but I don't think I'd like that.
