### ISSUE TITLE
LanguageTool under LibreOffice in French: StackOverflowError and NoClassDefFoundError

### ISSUE THREAD

**Issue by alitokmen** [languagetool-org/languagetool#6274]
Steps to reproduce the issue:

1. Install LibreOffice 7.2.5
2. Install LanguageTool 5.5.1
3. In the LibreOffice Writer, write some text (in French)
4. Set the language to French

This results in a StackOverflowError:

<img width="1057" alt="Screen Shot 2022-01-23 at 23 11 20" src="https://user-images.githubusercontent.com/429213/150700028-c4227868-1916-4b29-bd4e-f7911229252b.png">

There are also other unexpected errors, such as a NoClassDefFoundError with org.languagetool.rules.fr.WordWithDeterminerFilter:

<img width="1216" alt="Screen Shot 2022-01-23 at 23 14 20" src="https://user-images.githubusercontent.com/429213/150700087-e9fadffd-c5e6-4c53-902c-2a7c381c3f01.png">

**Comment by danielnaber** [comment]
Could you try LT 5.6? https://languagetool.org/download/LanguageTool-5.6.oxt

**Comment by alitokmen** [comment]
That was easy - Yes, version 5.6 fixes it :)

Would it be possible to update https://extensions.libreoffice.org/en/extensions/show/languagetool by any chance, so it has this new and great version?

**Comment by danielnaber** [comment]
> Would it be possible to update https://extensions.libreoffice.org/en/extensions/show/languagetool by any chance, so it has this new and great version?

I've tried, but that site has bugs that make adding updates difficult. I've emailed the support address again, though.
