### ISSUE TITLE
:question: Conditions to use or modify the logo

### ISSUE THREAD

**Issue by PillFall** [languagetool-org/languagetool#6278]
I create a modified version of the logo for use in my Emacs package documentation, as the package is a wrapper to use LanguageTool inside Emacs. I haven't published the logo, but if you want to know: it is an E shaped like the Emacs logo (with the serif pointing outside), but using visual aspects of LT characters, with the same curly blue underline in a black rounded square background.

My question is, can I do this? Or there are restrictions about logo usage.

[Link to the package](https://github.com/PillFall/Emacs-LanguageTool.el)

**Comment by danielnaber** [comment]
Could you send us the logo, so we can have a look (you can find the support email at https://languagetool.org/legal)?

**Comment by PillFall** [comment]
Yeah, of course, there it is. Sorry, I was looking for a while and I didn't get to that page. :sweat:

![logo](https://user-images.githubusercontent.com/30298743/150877516-ede181a2-3f92-4d15-91c3-dd0d06a54545.svg)

**Comment by PillFall** [comment]
OK, I'll send it right on. I search for a while and never get to that page.
