### ISSUE TITLE
Laguage Tool crashes in KDE (Wayland)

### ISSUE THREAD

**Issue by dasarne** [languagetool-org/languagetool#6286]
Hi, 
a fresh installed LibreOffice (7.2.5-1) running with Manjaro Linux (250) under KDE (5.23.5-1) crashes after installing LT (5.5.1) If running with KDE (X11) everything is stable. Switching back to KDE (Wayland) LibreOffice with LT crashes again.
What can I do to get more logging? What other information can I give you? Can you reproduce the failure?

Yours 
 Arne

**Comment by danielnaber** [comment]
Does this also happen with the latest LT: https://languagetool.org/download/LanguageTool-5.6.oxt ?

**Comment by dasarne** [comment]
Yes it does. :.(
I changed the machine and was able to reproduce the error on a completely different computer. I deleted the .config and .local folders and got three different states with LT 5.5.1 **and** LT 5.6:
- Direct crash (99% of the time).
- 100% CPU load on one core and no response from the process (1%)
- Everything works fine (**1 single time**, but after a restart of the LibreOffice-process only crashes again)

**Comment by danielnaber** [comment]
@FredKruse any idea?

**Comment by dasarne** [comment]
I just noticed that the error really only occurs in KDE- Wayland. Under GNOME-Wayland there is no crash. 
Where can I have a build with check in cbf4fc8? I'd like help with testing...

**Comment by danielnaber** [comment]
Daily builds are available at https://internal1.languagetool.org/snapshots/

**Comment by dasarne** [comment]
Hi, I tried the LanguageTool-20220129-snapshot.oxt but it continues crashing.

**Comment by FredKruse** [comment]
In a virtual box, I installed  the Manjaro Linux 21.2 (KDE-Plasma-Version 5.23.5). After that, I installed:
libreoffice-fresh (LibreOffice Version 7.2.5-4)
jdk-openjdk (Version 17.0.1)
Next, I load down and installed LanguageTool-20220130-snapshot.oxt.
LibreOffice started correct, and LanguageTool worked well after that.
@dasarne: Please check your installation again. What java version did sou use? Could you describe the single steps you did till LO crashes?

**Comment by FredKruse** [comment]
@dasarne Could you solve your problem? I would like to close the issue.

**Comment by dasarne** [comment]
Hi Fred, 
yes order is half the battle. ![emotion-twinkle](https://user-images.githubusercontent.com/8106470/174853461-482fb1f9-a72d-46dc-b223-868664f3bd73.png)
I would be happy to check if the problem still exists. Unfortunately, I only have time at the end of the week.

**Comment by dasarne** [comment]
Unfortunately, the error is still there. I deleted +/.config/libreoffice and then reinstalled LT (5.7). On the following restart of Libreoffice it crashed with the error message.
```
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
soffice.bin: xcb_io.c:730: _XReply: Zusicherung »!xcb_xlib_threads_sequence_lost« nicht erfüllt.
```
![emotion-sad](https://user-images.githubusercontent.com/8106470/175777497-2db5a02f-f256-4384-8de2-d0ac6a6984f6.png)

**Comment by FredKruse** [comment]
I could reproduce the issue now.
So, I did some research on the net. It seems that your issue is a special Plasma Wayland problem. It is documented in many postings regarding different applications, and seems related to the graphic engine of Plasma.
I'm very sorry, but we can't solve the problem in LT (multithreading is needed). You have to use X11 and wait till the bug in Plasma Wayland is solved.

**Comment by FredKruse** [comment]
> Is this bug related to https://bugs.documentfoundation.org/show_bug.cgi?id=144994 ?

Yes, I think it is the same issue.

**Comment by Marzal** [comment]
It's now fixed for me.
