### ISSUE TITLE
The grammatical error in 'This is attempt to write.' can't be detected

### ISSUE THREAD

**Issue by junyixu** [languagetool-org/languagetool#6290]
![image](https://user-images.githubusercontent.com/40481594/151818424-24ad275c-d886-478c-be53-df85eaae1e41.png)

**Comment by udomai** [comment]
Thanks for the report, but this mistake is already found by LanguageTool. Where did you test this?

<img width="300" alt="image" src="https://user-images.githubusercontent.com/67792088/151820603-a64ab560-99eb-4ae6-8b66-44e34309ba1a.png">

**Comment by junyixu** [comment]
[Arch Linux community repository](https://archlinux.org/packages/community/any/languagetool). 
![image](https://user-images.githubusercontent.com/40481594/151826725-1069b330-08e0-4486-a1ee-316572602195.png)

Sorry, I'm new to languagetool. I should have tested it in <https://languagetool.org/>.
Thank you very much for your great work!

**Comment by udomai** [comment]
@junyixu, I have to thank you for contributing to LT 🙂 

The safest way of testing this is on https://languagetool.org/ or by using the browser add-on. That way, you make sure you have all the rules, including the AI rules.

**Comment by junyixu** [comment]
@udomai Maybe buying an API is a better way for me, since I just want to make languagetool work well with vim, my favorite editor.
I click <https://languagetool.org/proofreading-api>, only to find it's too expensive for personal use...
