### ISSUE TITLE
[DE]LT-Bugfehlermeldung 01.02.2022

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#6291]
Moin liebes LanguageTool-Team

![LT 2022](https://user-images.githubusercontent.com/78316155/151893916-83204857-fa08-44d1-b200-f931ab8b8c64.JPG)

Diese Meldung kam beim Schreiben einer E-Mail. Dabei wurde ein Entwurf von Outlook in ein LibreOffice-Dokument kopiert und bearbeitet. Nach Fertigstellung wurde das Dokument abgespeichert und geschlossen. Erst dann habe ich die Bugfehlermeldung gefunden.

Ich weiß nicht, ob das Problem in einer Beta-Version behoben ist, weswegen ich sie melde.
Sicher ist sicher.

Grüße Dallun511

**Comment by danielnaber** [comment]
@FredKruse

**Comment by FredKruse** [comment]
Vielen Dank für die Meldung. Der Fehler war auch noch in der 5.7 vorhanden und wird jetzt abgefangen (ab dem morgigen Snapshot). Er sollte aber auch in der 5.6 eher selten auftreten.
