### ISSUE TITLE
Can't deactivate LanguageTool in GoogleDocs

### ISSUE THREAD

**Issue by jpinksterboer** [languagetool-org/languagetool#6292]
Can't seem to turn off LanguageTool in GoogleDocs. Very annoying when working in documents with multiple languages.

**Comment by danielnaber** [comment]
You can always turn off LT here:

![turn_off](https://user-images.githubusercontent.com/857004/151989400-9be5f181-2976-42e6-93c1-fce004e9e9df.png)

**Comment by jpinksterboer** [comment]
Dear Daniel,

After years of using LanguageTool I know how it works and have never had
this problem before. I click the button you indicated and nothing happens.
I can only deactivate LanguageTool by turning it off completely in my
browser. I deleted LanguageTool, restarted my computer and reinstalled
LanguageTool but the same problem persists. I hope you can give me some
advice on what else I can try.

Kind regards,
Josefien Pinksterboer


Le mar. 1 févr. 2022 à 15:42, Daniel Naber ***@***.***> a
écrit :

**Comment by danielnaber** [comment]
Unfortunately, I don't really have an idea... which browser do you use? Is it a recent version of the browser? Does deactivation work if you click the "LT" icon in the browser's toolbar?
