### ISSUE TITLE
[ru] case mismatch false positive with a foreign name

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#6305]
`Знакомство с LanguageTool`
![image](https://user-images.githubusercontent.com/122009/152963589-1882a149-6df2-4b1b-80ae-c049e7680be6.png)

**Comment by yakovru** [comment]
For proper text processing, it is necessary to solve the problem described in  SENT_END and PARA_END - Development - LanguageTool Forum 
>Вторник, 8 февраля 2022, 12:58 +03:00 от Peter Gromov ***@***.***>:
> 
> 
>Знакомство с LanguageTool
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you are subscribed to this thread. Message ID:  <languagetool-org/languagetool/issues/6305 @ github . com> 
 
 
--

Yakov Reztsov
