### ISSUE TITLE
[pt] Two minor corrections

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#6308]
LT corrects 'esse cara' to 'esse caro'; in Brazil, if someone writes 'esse cara' it refers to 'this guy', and as 'cara' is masculine, 'esse cara' is correct.
Also, 'suspense' is flagged as 'Estrangeirismo', which, in Brazil, definitely is not.

**Comment by marcoagpinto** [comment]
Sure, I will fix it at 5am as usual.

Thanks!

🙂

**Comment by marcoagpinto** [comment]
Hello!

About "cara", I thought I had fixed it one or more weeks ago, so I tested, and it worked.

Where did you see it not working?

![esse_cara_20220209](https://user-images.githubusercontent.com/5192600/153129554-5c5a2923-e94c-4f74-bd31-4b5a4d5fccd8.png)

**Comment by marcoagpinto** [comment]
The "suspense" it is done:
https://github.com/languagetool-org/languagetool/commit/65e08106b38f080b5d468906d1ccb0b6d371abfc
https://github.com/languagetool-org/languagetool/commit/368ed60b371a884eed1006bb5998f6dd355d921d

**Comment by ricardojosehlima** [comment]
"Esse cara" was spotted wrong in LO where 5.6 of LT is installed

**Comment by marcoagpinto** [comment]
Yes, because I only fixed it one or two weeks ago or so.

You must use the nightly build:
https://internal1.languagetool.org/snapshots/

The official releases for LibreOffice only happen every three months.
