### ISSUE TITLE
Nightly diff “Picky” and “tempOff”

### ISSUE THREAD

**Issue by SteVio89** [languagetool-org/languagetool#6309]
The columns for “picky” and “tempOff” were just filled for new RuleMatches.

![image](https://user-images.githubusercontent.com/6919869/153162005-86d435fb-0af7-4396-a25a-c97d44a26965.png)

![image](https://user-images.githubusercontent.com/6919869/153162022-316b5942-06ab-49d0-aff2-7051aeab2e31.png)

**Comment by danielnaber** [comment]
Should be fixed now.
