### ISSUE TITLE
False negative "Der Editor hebt fehlerhafte Eingabe hervor."

### ISSUE THREAD

**Issue by martinvonwittich** [languagetool-org/languagetool#631]
Test case:

    Der Editor hebt fehlerhafte Eingabe rot hervor.

This should be "Der Editor hebt fehlerhafte Eingaben rot hervor.", but LanguageTool doesn't notice it:

```
www0.iserv.eu ~ # echo "Der Editor hebt fehlerhafte Eingabe rot hervor." | java -jar /root/LanguageTool-3.5/languagetool-commandline.jar -l de-DE
Expected text language: German (Germany)
Working on STDIN...
Time: 4069ms for 1 sentences (0.2 sentences/sec)
```

It seems to detect correctly that "Eingabe" is singular though:

```
www0.iserv.eu ~ # echo "Der Editor hebt fehlerhafte Eingabe hervor." | java -jar /root/LanguageTool-3.5/languagetool-commandline.jar -l de-DE -t
Expected text language: German (Germany)
Working on STDIN...
<S> Der[der/ART:DEF:DAT:SIN:FEM,der/ART:DEF:GEN:PLU:FEM,der/ART:DEF:GEN:PLU:MAS,der/ART:DEF:GEN:PLU:NEU,der/ART:DEF:GEN:SIN:FEM,der/ART:DEF:NOM:SIN:MAS,der/PRO:DEM:DAT:SIN:FEM,der/PRO:DEM:NOM:SIN:MAS,der/PRO:PER:NOM:SIN:MAS,B-NP] Editor[Editor/null,I-NP] hebt[heben/VER:2:PLU:PRÄ:NON,heben/VER:3:SIN:PRÄ:NON,heben/VER:IMP:PLU:NON,O] fehlerhafte[fehlerhaft/ADJ:AKK:SIN:FEM:GRU:DEF,fehlerhaft/ADJ:AKK:SIN:FEM:GRU:IND,fehlerhaft/ADJ:AKK:SIN:FEM:GRU:SOL,fehlerhaft/ADJ:NOM:SIN:FEM:GRU:DEF,fehlerhaft/ADJ:NOM:SIN:FEM:GRU:IND,fehlerhaft/ADJ:NOM:SIN:FEM:GRU:SOL,B-NP|NPS] Eingabe[Eingabe/SUB:AKK:SIN:FEM,Eingabe/SUB:NOM:SIN:FEM,I-NP|NPS] hervor[hervor/ADV:LOK,hervor/ZUS,O].[</S>./PKT,O] 
```

Unfortunately I'm too new to LanguageTool to figure out a rule that could detect this :(

**Comment by cnleo** [comment]
But it could also be called correctly:
Der Editor hebt **die** fehlerhafte Eingabe rot hervor. ← singular
Der Editor hebt **die** fehlerhafte**n** Eingabe**n** rot hervor. ← plural

Same with:
Ich möchte erneute Eingabe vermeiden.
Ich möchte **die** erneute Eingabe vermeiden.
Ich möchte **die** erneute**n** Eingabe**n** vermeiden.

**Comment by janschreiber** [comment]
As an aside: any rule that attempts to cover this case would have to be very carefully crafted to avoid false positives. It is quite common to skip the articles, for example in newspaper headlines: "Frau (32) durch fehlerhafte Eingabe getötet."

**Comment by danielnaber** [comment]
I think it's not a real bug, so I'm closing this.
