### ISSUE TITLE
Problem with the word pokemon in catalan

### ISSUE THREAD

**Issue by Aeluv123** [languagetool-org/languagetool#6310]
The problem is that in Catalan it says that the plural of Pokémon is Pokémons when it is Pokémon for both scenarios

**Comment by jaumeortola** [comment]
Some use the word as a common word, with a plural form. See: https://esadir.cat/nomspropis/fitxa/id/6796
Obviously, there are no strict rules for this kind of adaptations. We could allow Pokémon, capitalized and invariable.

**Comment by jaumeortola** [comment]
Thanks for the feedback, @Aeluv123.
