### ISSUE TITLE
[pt] LT captures repetitions of ==>

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#6311]
As can be seen in the files, when it is PT, LT flags repetitions of ==> and also other similar characters (--> , --) while in EN it doesn't. This is one case in which I can't just tell LT to not deactivate the rule, as it is very useful for flagging repeated words.

![repet_en](https://user-images.githubusercontent.com/36453534/153256581-e2a76189-08c1-4ed0-8493-be58184aca61.png)
![repet](https://user-images.githubusercontent.com/36453534/153256587-4de5c95c-01bf-4868-b123-dfec0af058eb.png)

**Comment by marcoagpinto** [comment]
@jaumeortola @tiff @udomai 

You are maintainers of the English rules, could one of you enhance this part with some code from English?

Thanks!

**Comment by jaumeortola** [comment]
I will take care. Please copy the examples also as plain text. That way, we can copy and paste, and it is easier to reproduce the issues.

**Comment by jaumeortola** [comment]
The rules are REPEATED_WORDS_3X REPEATED_WORDS. It is easy to add exceptions there.
