### ISSUE TITLE
[pt] More helpful disambiguator POSes

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6321]
Hello @jaumeortola @udomai @tiff 

For years that I have problems with words like "n[ao]s?", "d[ao]s?", etc.

The morphologic dictionary shows "SPS00+DA", "SPS00.+", etc.

Could we keep these for compatibility reasons and have more helpful information?

Information such as gender and plural/singular?

It is a lot of pain to have to add antipatterns with regular expressions, typing the words manually.

Thanks!

**Comment by jaumeortola** [comment]
Yes. That seems a good idea. Just make a proposal. 

Something like this? `nos em+os SPS00+DA0MP0`

The `+` character inside the POS tags causes some problems hard to solve in synthesis. I suggested replacing `+` with `:`.

**Comment by marcoagpinto** [comment]
@jaumeortola 

Excellent, I will start making a list as I develop more rules.

Thanks!
