### ISSUE TITLE
[ru] False positve

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#633]
Такой подход оказался достаточно универсальным.

![screenshot from 2016-12-13 16-48-08](https://cloud.githubusercontent.com/assets/5239997/21142585/f61db296-c153-11e6-8b72-7748553a0b89.png)

**Comment by kostyfisik** [comment]
Несколько неожиданной оказалась форма кривой для электрической дипольной моды: вершина резонансного колокола выглядит практически плоской.
![screenshot from 2016-12-13 19-51-18](https://cloud.githubusercontent.com/assets/5239997/21149718/8877c47e-c16d-11e6-907d-b5d58b6c79da.png)

**Comment by yakovru** [comment]
Fixed.
