### ISSUE TITLE
Basic auth support

### ISSUE THREAD

**Issue by someone-stole-my-name** [languagetool-org/languagetool#6349]
Hello,

Would it be possible to add support for basic authentication in the Firefox extension? Is the extension code open sourced somewhere?

The extension throws the following error when using `https://foo:bar@foo.bar/v2`:

```
Cannot connect to https://foo:bar@foo.bar/v2/check - please check your internet connection or try again in a minute (#1, code=undefined)
```

**Comment by michal7918** [comment]
This would be great addition for Firefox addon as well as Thunderbird, Chrome and Libre/Open Office plugins. Currently, I don't find any way how to limit access to publicly running LanguageTool server except for blocking IPs which is not practical.

**Comment by someone-stole-my-name** [comment]
> This would be great addition for Firefox addon as well as Thunderbird, Chrome and Libre/Open Office plugins. Currently, I don't find any way how to limit access to publicly running LanguageTool server except for blocking IPs which is not practical.

I ended up exposing LanguageTool under a “secret” URL and hoping for the best 🤷

**Comment by danielnaber** [comment]
Closing, duplicate of #4308
