### ISSUE TITLE
[de] Some German verbs on the beginning of a sentences are identified only as substantives

### ISSUE THREAD

**Issue by FredKruse** [languagetool-org/languagetool#635]
Some Words like 'Haben', 'Sehen' and 'Gehen' are only identified as substantives, when they are written with an upper case first letter.
Here are three sentences as example:
Haben wir ein Problem oder nicht?
Gehen wir oder nicht?
Reden Sie nicht um den heißen Brei herum!

**Comment by f-knorr** [comment]
Hi @FredKruse ,
kannst du bitte prüfen, ob meine Änderung o. g. Problem löst? Falls ja, mache dieses Issue einfach zu. Falls nein, gib Bescheid, wo's noch klemmt. CU

**Comment by janschreiber** [comment]
@FredKruse Nur zur Sicherheit, falls Du es nicht weißt, die aktuellen Snapshots gibt es immer hier: [https://languagetool.org/download/snapshots/?C=M;O=D](https://languagetool.org/download/snapshots/?C=M;O=D).

**Comment by f-knorr** [comment]
Wenigstens für die 3 Beispiele geht's => Closed

**Comment by FredKruse** [comment]
Hi,

tut mir leid, dass ich erst jetzt antworte, aber die Telekom hatte es 
geschafft, mich abzuhängen.

das Problem mit den drei Sätzen ist gelöst. Allerdings scheint es ein 
grundsätzlicheres Problem zu geben. In folgendem Satz wird das Wort am 
Anfang auch nur als Substantiv erkannt, obwohl es kleingeschrieben als 
Adverb zugeordnet wird:

"Gerade wer das Bewahrenswerte bewahren will, muss verändern, was der 
Erneuerung bedarf."


Noch ein weiterer Bug, der mich vollends verwirrt:

der folgende Satz, stammt aus dem Tatoeba:

"Wer immer lacht, ist töricht - wer nie lacht, ist unglücklich."

Wie sinnvoll der Gedankenstrich (Minuszeichen) an dieser Stelle auch 
sein mag, er wird vollkommen verrückt interpretiert, wenn man ihn über 
https://community.languagetool.org/analysis/analyzeText analysiert:

- 	Hehl



abendlich

	SUB:DAT:SIN:MAS
SUB:DAT:SIN:NEU
SUB:GEN:SIN:MAS
SUB:GEN:SIN:NEU
ADJ:PRD:KOM
ADJ:PRD:SUP
	I-NP
NPS

Die Regel, die ich gerade teste, interpretiert das Minuszeichen dann 
tatsächlich als SUB:*.

Gruß

Fred



Am 16.12.2016 um 17:30 schrieb f-knorr:

**Comment by f-knorr** [comment]
Jetzt sollte es für alle Wörter am Satzanfang klappen. Ich hatte noch eine Beschränkung auf Wörter, die mit "en" (Können, Sollen,...) enden drin.
