### ISSUE TITLE
user feedback pt-BR

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#6351]
> 1) "dezanove": in pt-BR it is "dezenove", always.

> 2) "abaixo assinado" is wrong because it should have hyphen (abaixo-assinado)? No: the two words exist and mean different things.

**Comment by marcoagpinto** [comment]
Fixed:
https://github.com/languagetool-org/languagetool/commit/488b3b407645e6139057c75e78dde0f2d39ed1ec

https://github.com/languagetool-org/languagetool/commit/0d5b54adacee55a0573c4a97e0034d8161fa4c9d
