### ISSUE TITLE
Pro features

### ISSUE THREAD

**Issue by iMonZ** [languagetool-org/languagetool#6357]
Hey,
I would like to buy 10 Licenses for our team.

- [ ] My Question is if the On-Premise Server also supports for the Premium features?

- [ ] And if it's possible that you could make suggestions for missing words in the LanguageTool Dictionary? (Currently it's only local possible)

**Comment by danielnaber** [comment]
Hi, could you contact our sales/support about this? You can use the email at https://languagetool.org/de/legal
