### ISSUE TITLE
[de] „(des) Grüns“ not accepted by GERMAN_SPELLER_RULE

### ISSUE THREAD

**Issue by NicoWeio** [languagetool-org/languagetool#6381]
Aus mir unverständlichen Gründen wird „Grüns“ zwar korrekt als `SUB:GEN:SIN:NEU` erkannt (laut der Textanalyse [hier](https://community.languagetool.org/analysis/analyzeText)), _GERMAN_SPELLER_RULE_ liefert aber _„Möglicher Tippfehler gefunden.“_

#### Beispiel
> Die Erhaltung des urbanen **Grüns** ist wichtig.

**Comment by danielnaber** [comment]
Die Textanalyse ist unabhängig von der Rechtschreibprüfung. Für die Rechtschreibung kann man fehlende Wörter in die Datei `spelling.txt` eintragen, damit sie erkannt werden.

**Comment by NicoWeio** [comment]
Verstehe, dann mache ich das gerne. :)
