### ISSUE TITLE
Nightly diffs are dead

### ISSUE THREAD

**Issue by milekpl** [languagetool-org/languagetool#6383]
For the last week or so, the nightly diff testing is dead:

Copying snapshot /home/languagetool/snapshots/open-source/LanguageTool-wikipedia-20220226-snapshot.zip failed (tried with both today's and yesterdays date)

Could you restore this? It would be useful for testing a fairly complex and ambitious rule I want to contribute.

**Comment by marcoagpinto** [comment]
Nightly diffs have been blank for weeks.

I have been seeing the results of my rules with:
https://internal1.languagetool.org/regression-tests/via-http/2022-02-28/pt-PT/index.html

**Comment by udomai** [comment]
Hi @marcoagpinto, the Open Source nightly diff results for Portuguese are here:

https://internal1.languagetool.org/regression-tests/via-http/2022-02-28/pt-PT/

@milekpl, what exactly have you been using for Polish? The above link is to a snapshot, how does that work?

**Comment by milekpl** [comment]
I simply subscribed to the commit list at sourceforge.net and it seemed to change for RU, for example

**Comment by milekpl** [comment]
https://lists.sourceforge.net/lists/listinfo/languagetool-commits

**Comment by milekpl** [comment]
See the change here:

https://sourceforge.net/p/languagetool/mailman/languagetool-commits/?viewmonth=202202

**Comment by yakovru** [comment]
Hi @milekpl,  I asked Daniel to restore this test for RU.
And I also use the new tests on this page:
https://internal1.languagetool.org/regression-tests/via-http/

**Comment by milekpl** [comment]
Hm, @udomai are you sure internal regression tests are on? I looked up what's inside the stderr files at https://internal1.languagetool.org/regression-tests/result_stderr_pl, and it says:

> Exception in thread "main" java.lang.RuntimeException: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[15328027,36]
> Message: XML document structures must start and end within the same entity.
> 	at org.languagetool.dev.dumpcheck.WikipediaSentenceSource.hasNext(WikipediaSentenceSource.java:85)
> 	at org.languagetool.dev.dumpcheck.MixingSentenceSource.hasNext(MixingSentenceSource.java:77)
> 	at org.languagetool.dev.dumpcheck.SentenceSourceChecker.run(SentenceSourceChecker.java:239)
> 	at org.languagetool.dev.dumpcheck.SentenceSourceChecker.main(SentenceSourceChecker.java:74)
> 	at org.languagetool.dev.wikipedia.Main.main(Main.java:45)
> Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[15328027,36]
> Message: XML document structures must start and end within the same entity.
> 	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
> 	at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
> 	at org.languagetool.dev.dumpcheck.WikipediaSentenceSource.handleTextElement(WikipediaSentenceSource.java:144)
> 	at org.languagetool.dev.dumpcheck.WikipediaSentenceSource.fillSentences(WikipediaSentenceSource.java:131)
> 	at org.languagetool.dev.dumpcheck.WikipediaSentenceSource.hasNext(WikipediaSentenceSource.java:83)
> 	... 4 more
> Command exited with non-zero status 1
> real 13.97
> user 19.94
> sys 1.32 
>

**Comment by danielnaber** [comment]
I've activated the new diffs now (they use our API). You can see the first result at https://internal1.languagetool.org/regression-tests/via-http/2022-03-02/pl/. The data is about 100,000 lines from Tatoeba. Let me know if you want more data to be added. It should now run every day, just replace the date in the URL. Getting the old diffs running again is more complicated, as the Wikipedia XML extraction is broken.

**Comment by milekpl** [comment]
@danielnaber Thanks. This is actually much better for me because I do have my own corpora but they are less conversational (a newspaper corpus, classical literature corpus and a blog corpus). Will this be announced on the old sourceforge mailing list?

**Comment by danielnaber** [comment]
> Will this be announced on the old sourceforge mailing list?

I've sent a message there, but I'm not sure whether it will get through.

**Comment by milekpl** [comment]
It did not. But I can manage without it.
