### ISSUE TITLE
[pl] user feedback "ukraincom"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6387]
A user says:
> Dlaczego napisanie "ukraincom" nie jest poprawne, a napisanie "polakom" już jest.
> Należy to poprawić, gdyż jest to  dyskryminacja.

@milekpl maybe you can have a quick look.

**Comment by milekpl** [comment]
This is a rare word 'polak' that means a class in Polish language.

https://sjp.pl/polakom

It makes sense to remove it from the speller, as this is almost never used
(and never in plural form). I'll update the appropriate files.



pon., 28.02.2022, 15:01 użytkownik Christopher Blum <
***@***.***> napisał:

**Comment by tiff** [comment]
Thank you @milekpl !
