### ISSUE TITLE
[LibreOffice] Quickly opening and closing documents causes extra menubars to be added until LibreOffice crashes when LanguageTool extension is installed

### ISSUE THREAD

**Issue by Nuromi-pm** [languagetool-org/languagetool#6390]
When the LanguageTool extension is installed and enabled, quickly opening and closing documents from the main LibreOffice program causes extra menubars to be added to the UI until LibreOffice crashes.

This only happen when the libreoffice-gtk3 package is installed.

https://user-images.githubusercontent.com/86095293/156090093-8bf54a36-fa6c-408d-8bfe-0a6cc9cbcf3a.mp4

LanguageTool 5.6
LibreOffice 7.3.0
Debian 11 Bullseye with XFCE Desktop

**Comment by Nuromi-pm** [comment]
I have also filled a bug in the LibreOffice bug tracker: https://bugs.documentfoundation.org/show_bug.cgi?id=147796

**Comment by FredKruse** [comment]
I could reproduce the bug. It is related to https://github.com/languagetool-org/languagetool/issues/6412. So, I like to discuss it there.

**Comment by Nuromi-pm** [comment]
Still happen in LanguageTool 5.7. There is a patch coming from the LibreOffice side that supposedly fix this bug: https://git.libreoffice.org/core/+/9f041e7678521074b09b20f4088996c86bea5cd0%5E%21

It will be available in 7.4.0. I hope this solves the issue.
