### ISSUE TITLE
en-GB recognizes some common composite words that other varieties of English (including en-US) don't 

### ISSUE THREAD

**Issue by Christian-Nieber** [languagetool-org/languagetool#640]
The following words are marked as missspelled by any variety of English other than en-GB (and en, but en does not mark any misspellings at all)

autosave
codec
gameplay
subfolder
timestamp

Same for some accented words. This is not necessarily a bug, but may give a hint:
fiancé
fiancée
née
rôle

**Comment by marcoagpinto** [comment]
Welcome to the state of the art!

:-)

en_GB! :-)

**Comment by marcoagpinto** [comment]
Last week it was merged into LibreOffice :-)

After weeks nagging the people there :-)

**Comment by MikeUnwalla** [comment]
@Christian-Nieber , thanks for the report. 

Mostly fixed. Refer to https://github.com/languagetool-org/languagetool/commit/7051f394e58fb2291699abadf645dc087f8bf411
