### ISSUE TITLE
[de] False positives for missing comma

### ISSUE THREAD

**Issue by f-knorr** [languagetool-org/languagetool#641]
The following sentences trigger *false positives*:
* Der Konzern konzentriert *sich seitdem* auf Ausrüstung für Mobilfunknetze.
* Wir haben das Rezept geändert, sodass er sich bereits im Mund auflöst und weniger davon in den Magen-Darm-Trakt *gelangen kann*.
* Schon über die Frage, ob der isolierte Zellkern einer unbefruchteten Eizelle noch _als_ Keimzelle zu werten sei, werde gestritten.
* Was genau die Glücklichen erwartet, die den Konzerten beiwohnen werden, *das wird* sich noch zeigen.
* Aus Sorge, dass die Reichskrone in französische Hände *gelangen könnte* und die österreichischen Länder unter napoleonische Herrschaft *gelangen könnten*, löste er das Reich als Ganzes auf.

Maybe @FredKruse can have a look at this.

**Comment by FredKruse** [comment]
OK, I'll take a look


Am 22.12.2016 um 11:27 schrieb f-knorr:

**Comment by f-knorr** [comment]
Great! Your recent pull request solved all examples reported here!

**Comment by f-knorr** [comment]
Found another two examples:
* Die _heile Fassade war_ die Voraussetzung dafür, dass sie ungestört trinken konnte.
* Eltern zerbrechen sich den Kopf, wie sie die Betreuung organisieren sollen, _vor allem wenn_ es mal länger als nur ein, zwei Tage dauert.

**Comment by f-knorr** [comment]
@FredKruse Thank you very much for your immediate pull request!! I will leave this call open because the sentences from the regression test (z. B. Über die Beantragung muss der Regisseur Stillschweigen halten, ebenso darf er den fertigen Film nicht öffentlich kritisieren) still cause false positives.
Merry X-Mas!

**Comment by FredKruse** [comment]
There was some difficulties on my side to solve the problems:
- The false positives at two Examples arose because of the interpretation of the words "heile" and "terrorverdächtige" only as verbs and not as adjectives. I added this words in the added.txt. In the first case (heile) this solves the problem. In the second case it doesn't. So I had to add an extra exception in the grammar.xml which is from my point of view a very ugly solution. Could someone look at this problem with the added.txt?
- I'm not sure if it is the right solution to exclude optional settings as in the second example (I did it anyway). As more exceptions we define as more real matches we exclude also. Maybe we should discuss what strategy we should pursue. Who many mismatches are acceptable? 
Merry X-Mas!

**Comment by danielnaber** [comment]
> I added this words in the added.txt. In the first case (heile) this solves the problem. In the second case it doesn't.

There's some strange characters in your change that will cause the word not to be detected:

![adj](https://cloud.githubusercontent.com/assets/857004/21452443/35549b68-c907-11e6-862d-9484e6dae277.png)

**Comment by FredKruse** [comment]
strange, I added the characters with gedit (ubuntu).

**Comment by FredKruse** [comment]
The problems in the added Text are solved. I deleted the additional exception.
The false match in "Über die Beantragung muss der Regisseur Stillschweigen halten, ebenso darf er den fertigen Film nicht öffentlich kritisieren" is also solved.

**Comment by danielnaber** [comment]
I can still see the wrong characters, both with IntelliJ and `joe`. Other editors might not show them. This can also happen if you copy and paste text from somewhere.

**Comment by f-knorr** [comment]
I have removed the wrong characters.

> I'm not sure if it is the right solution to exclude optional settings as in the second example (I did it anyway). As more exceptions we define as more real matches we exclude also. Maybe we should discuss what strategy we should pursue. Who many mismatches are acceptable?

@FredKruse You mention a good point here. There is no strict rule. False positives are acceptable if the ratio of false positives / true positives is considerably small. In the specific case, I think an exception is the better option because I do no expect an increase of false negatives. I personally even prefer missing some true positives when the number of false positives decreases...

**Comment by f-knorr** [comment]
* Ich muss einkaufen gehen, ich komme in einer Stunde zurück.
* Um die zusammengesetzten Formeln bewerten zu können, muss für jeden Junktor definiert werden, welchen Wahrheitswert die Bewertungsfunktion für die unterschiedlichen Wahrheitswertkombinationen liefert, den seine Argumente annehmen können.
* Zwar hielt sich Hitchcock darüber stets äußerst bedeckt, doch es gilt als gesichert, dass der Regisseur sich von diesen nicht beeindrucken ließ.
* Ihre Entdeckung konnte jedoch nicht bestätigt werden und wurde später als falsch erkannt.
* Der Einfluss des Aristoteles sollte wohl nicht zu hoch veranschlagt werden, doch sicher war Alexander sehr gebildet.
* Pope wollte schließlich 303 Verurteilte hinrichten lassen, doch Lincolns Regierung fürchtete den ungünstigen Eindruck einer solchen Massenexekution.
* Dort wollte er das Verfliegen der Kriegsbegeisterung von 1914 in Deutschland erstmals bemerkt haben; bei seinem Pflegeaufenthalt in München habe er die Stadt kaum wiedererkannt.
* Der Standard des Gesundheitswesens konnte in den letzten Jahren verbessert werden, ist aber immer noch unzureichend.

**Comment by FredKruse** [comment]
The false positives of the first eight sentence are corrected. The last one is related to another rule. I will do some changes on this in the next days.
