### ISSUE TITLE
[pt] Correcting tera for terá

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#6419]
When we write "Ele tera problemas com isso." LT doesn't flag the lack of diacritc in the 'tera', that should be 'terá'.
My guess is that this is because of the word tera as in terabytes. 
As LT already flags some similar cases ("Eu escrevi a pagina do livro" is captured to suggest 'página'), maybe something like that could apply to tera.
P.S.: Although it flags 'a pagina' it doesn't flag 'uma pagina'. So maybe there is some work to do, if it is within my reach, I can help.

**Comment by marcoagpinto** [comment]
cool!

I will have a look at 5am or after my date. 

😃

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

"uma página" caused tons of false positives. I have been attempting to fix all false positives, but not sure when it will be done.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

At 5am, I will revert the code and start coding the "uma página" again.

**Comment by ricardojosehlima** [comment]
I am curious about the false positives of 'uma pagina', if you could send me some, I can take a look.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Wait, I was just opening 10.txt, most results seem valid… so much stress… 🙂 

Can you spot the false positives?

Maybe there won't be the need to rewrite, just fix some false positives.

**Comment by ricardojosehlima** [comment]
Awesome! Pity there isn't a case of tera-terá but I assume it will work for this case.

Also, note that Ninguém and nada trigger false positives:

Parece que ninguém sabia a verdade is being corrected to sabiá
Sócrates dizia que ele sabia que nada sabia
Isso também indica que ninguém pronuncia essa palavra há várias décadas.
A vida me mostrou ao longo do caminho,que nada seria por acaso, e que tudo teria um porque.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

For "tera" I will duplicate this rule and just change the suggestion message.

What should the message say?

🙂

**Comment by marcoagpinto** [comment]
ahhhh... probably I will also have to slightly change the code.

**Comment by ricardojosehlima** [comment]
> @ricardojosehlima
> 
> For "tera" I will duplicate this rule and just change the suggestion message.
> 
> What should the message say?
> 
> slightly_smiling_face

I was going to mention the message. As tera is not a verb, the message we see doesn't fit:
Esta palavra é um verbo. Se pretende referir-se a um nome ou adjetivo, deve utilizar a forma acentuada.

Before going to the message of tera-terá I must say that for me and some colleagues the above message is ambiguous. When I write "Escrevi uma pagina" the word is a noun, what I intend is a noun. However, the message says it is a verb. Well, without the diacritics and in other context, it is indeed a verb. But the way it is phrased looks confusing and also I guess that almost all the verb forms are by far very rarely compared to the noun/adjective forms (who uses the verbs paginar, ultimar, veicular compared to página, última and veículo?)

So I would suggest for this case "Sem o acento, essa é a forma verbal da palavra. Se pretende referir-se a um nome ou adjetivo, deve utilizar a forma acentuada."

For tera-terá it would be "Sem o acento, essa palavra é o substantivo tera. Se pretende referir-se ao verbo ter no futuro, deve utilizar a forma acentuada."

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

The "um livro" is ready.

With 10.txt:
```
Portuguese (Portugal): 608 total matches
Portuguese (Portugal): ø0.00 rule matches per sentence
Portuguese (Portugal): 17323 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```

With 29.txt:
```
Portuguese (Portugal): 555 total matches
Portuguese (Portugal): ø0.00 rule matches per sentence
Portuguese (Portugal): 17323 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```

29.txt:
[29.txt](https://github.com/languagetool-org/languagetool/files/8222533/29.txt)

I also replaced the suggestion message with the one you suggested.

If you find any false positives that can be fixed with antipatterns, please tell.

Notice that there are some diacritics rules in the grammar.xml that interfere with this rule, created by an old developer who is no longer part of the team.

Later today I will work on the "tera".

Thanks!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

"tera/terá" created:
https://github.com/languagetool-org/languagetool/commit/7a307592dd50843cb5ad24ac963099ffb00786fb

In 600 000 sentences it produces no hits.

**Comment by ricardojosehlima** [comment]
Hi, great!

I spotted these two false positives with seria:

Pense diariamente em algo que ninguém mais pensa. Faça diariamente algo o qual nenhum outro seria suficientemente estúpido para fazê-lo. Prejudica o espírito sempre viver somente em concordância.
Mas pq diabos uma figura dessas seria agora plasmada à imagem de um (ex)juiz em manifestações de rua?

And looks like alguém also causes troubles:

É a primeira vez que alguém critica o meu trabalho.
Alguém duvida da capacidade de Aguinaldo Silva para criar vilões?

**Comment by marcoagpinto** [comment]
ahhhh... thanks for the false positives, I will fix them at 5am as usual.

🙂 🙂 🙂

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is done!:
https://github.com/languagetool-org/languagetool/commit/d22f7e00700b8200cff55d2b67189d5efc69d2c0

32.txt:
[32.txt](https://github.com/languagetool-org/languagetool/files/8229669/32.txt)

Closing the ticket!

Thanks!

**Comment by marcoagpinto** [comment]
Ricardo,

Just a small fix:
```
1.) Line 1, column 16, Rule ID: DIACRITICS[1]
Message: Sem o acento, essa é a forma verbal da palavra. Se pretende referir-se a um nome ou adjetivo, deve utilizar a forma acentuada.
Suggestion: cantã
Rule source: /org/languagetool/rules/pt/grammar.xml
O Estádio todo canta e vibra com o som da vitória que todos nós ajudámos a conseguir mas há que dar todo o mérito ás nos...

```

https://github.com/languagetool-org/languagetool/commit/c6b52f79ac9d1dea7c70113f267a13548cb96181

33.txt:
[33.txt](https://github.com/languagetool-org/languagetool/files/8229778/33.txt)
