### ISSUE TITLE
Thunderbird add-on local server synonyms incorrect toggle

### ISSUE THREAD

**Issue by Richardk2n** [languagetool-org/languagetool#6420]
Similar to #6177 there should be no synonym toggle if it is not possible due to local server. There is one in the add-on settings.

However, in thunderbird, in the writing window neither the picky nor the synonym toggle exist in the context menu (both are in the settings tho).
The context menu however flashes them very briefly when opening.
![grafik](https://user-images.githubusercontent.com/5147221/157316741-99985d1b-7074-4f90-a379-9702bb182e76.png)
![grafik](https://user-images.githubusercontent.com/5147221/157317347-202fa88c-fc03-4d30-9280-d18368559ac2.png)

**Comment by danielnaber** [comment]
I think this is not relevant anymore, as the setting has been removed from there.
