### ISSUE TITLE
Exception: Could not initialize class org.languagetool.rules.en.EnglishRepeatedWordsRule (LanguageTool v5.6.0)

### ISSUE THREAD

**Issue by AAbakumov** [languagetool-org/languagetool#6423]
Hi there, after upgrading LanguageTool to v5.6.0 stable, we started facing an exception with java class org.languagetool.rules.en.EnglishRepeatedWordsRule

callConstructor LangToolJNIProvider::callConstructor exception: Could not initialize class org.languagetool.rules.en.EnglishRepeatedWordsRule. 

Could you please suggest any workaround to prevent this issue?
We tried to increase JVM memory but it didn't help... Also, we thought about disabling this rule...but since it's part of Java code ... it's worthless.

**Comment by danielnaber** [comment]
Could you send the full stack trace?

**Comment by AAbakumov** [comment]
Hello @danielnaber, thank you for the speedy response! We will send this information as soon as we have it.

**Comment by AAbakumov** [comment]
@danielnaber Hello again, also we cached the same error with the German language, it reproduces from time to time (more often with the English language). Usually it reproduces during new instance initialization.

Stack trace:
java.lang.ExceptionInInitializerError
org.languagetool.language.German.getRelevantRules(German.java:131)
org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:492)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:324)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:293)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:353)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:259)
Caused by: java.lang.RuntimeException: java.io.IOException: Unknown line format when loading manual synthesizer dictionary: Pathologinnen        Pathologin        SUB:GEN:PLU:FEM
org.languagetool.synthesis.BaseSynthesizer.<init>(BaseSynthesizer.java:96)
org.languagetool.synthesis.BaseSynthesizer.<init>(BaseSynthesizer.java:101)
org.languagetool.synthesis.GermanSynthesizer.<init>(GermanSynthesizer.java:43)
org.languagetool.rules.de.GermanRepeatedWordsRule.<clinit>(GermanRepeatedWordsRule.java:33)
org.languagetool.language.German.getRelevantRules(German.java:131)
org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:492)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:324)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:293)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:353)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:259)
Caused by: java.io.IOException: Unknown line format when loading manual synthesizer dictionary: Pathologinnen        Pathologin        SUB:GEN:PLU:FEM
org.languagetool.synthesis.ManualSynthesizer.loadMapping(ManualSynthesizer.java:100)
org.languagetool.synthesis.ManualSynthesizer.<init>(ManualSynthesizer.java:57)
org.languagetool.synthesis.BaseSynthesizer.<init>(BaseSynthesizer.java:73)
org.languagetool.synthesis.BaseSynthesizer.<init>(BaseSynthesizer.java:101)
org.languagetool.synthesis.GermanSynthesizer.<init>(GermanSynthesizer.java:43)
org.languagetool.rules.de.GermanRepeatedWordsRule.<clinit>(GermanRepeatedWordsRule.java:33)
org.languagetool.language.German.getRelevantRules(German.java:131)
org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:492)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:324)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:293)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:353)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:259)

Stack trace 2:
java.lang.NoClassDefFoundError: Could not initialize class org.languagetool.rules.de.GermanRepeatedWordsRule
org.languagetool.language.German.getRelevantRules(German.java:131)
org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:492)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:324)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:293)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:353)
org.languagetool.JLanguageTool.<init>(JLanguageTool.java:259)

**Comment by danielnaber** [comment]
Thanks for the report, I think this should now be fixed with the commits referenced here.
