### ISSUE TITLE
[LibreOffice][pt] Words in spelling.txt appear as typos

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6426]
Hello @FredKruse 

I noticed that in the latest nightlies while working on my thesis, somehow, several words in spelling.txt started appearing underlined in red (spelling mistakes).

Maybe a recent change damaged the code?

**Comment by marcoagpinto** [comment]
See it happening:
![words_spelling_txt_appear_as_typos_20220310](https://user-images.githubusercontent.com/5192600/157673493-ff165a16-45b6-4b93-a726-1bfcf0a274ca.png)

[words_spelling_txt_appear_as_typos_20220310.odt](https://github.com/languagetool-org/languagetool/files/8223834/words_spelling_txt_appear_as_typos_20220310.odt)

**Comment by FredKruse** [comment]
This was a mistake. I deactivated the function while searching for the source of another bug, and forgot to activate it again after the last change.
Please test it tomorrow.

**Comment by marcoagpinto** [comment]
It is working! Thanks!
