### ISSUE TITLE
How to apply (apply option ) for languagetool-server 

### ISSUE THREAD

**Issue by bailobah** [languagetool-org/languagetool#643]
Hi, i use languagetool-server  how to appaly correction automatic ex( language-command use option --apply) but the option not found for  languagetool-server.

help please

**Comment by danielnaber** [comment]
The server doesn't support that option. I don't think it should be implemented, as it has a high risk of causing more harm (false alarms being "corrected") than good.

**Comment by bailobah** [comment]
Hi,
I use Language Tools for machine translation, can you help me to add this option please.
