### ISSUE TITLE
[LibreOffice add-on] No longer possible to deactivate rules

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6435]
@FredKruse 

Hello!

With the latest nightly, when we right-click in a flagged word, there is no longer an option to deactivate the rule.

**Comment by FredKruse** [comment]
@marcoagpinto 
thank you for testing. Another bug from the last changes. It is solved.
Please test it tomorrow.

**Comment by marcoagpinto** [comment]
Thanks, it is fixed.

However, I deactivate the 50 words or so rule in Portuguese, and it only deactivated it after I reopened the .ODT and after deactivating it several times it hung LibreOffice.

**Comment by FredKruse** [comment]
@marcoagpinto 
The issue should be fixed. Please test it tomorrow.

**Comment by marcoagpinto** [comment]
It is fixed, thanks!
