### ISSUE TITLE
[ca] false alarm for "Sumi" (VERBS_NOMSPROPIS[3])

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#6436]
> També van bombardejar estratègics i específics, com ara Járcov i **Sumi**.

VERBS_NOMSPROPIS[3] matches here

@jaumeortola

**Comment by jaumeortola** [comment]
Fixed https://github.com/languagetool-org/languagetool/commit/7ff31ea88edcf2285aa74f865a0f0a84e6950d51
