### ISSUE TITLE
[pt] strange behavior with 'para eu e ele'

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#6437]
![para_eu](https://user-images.githubusercontent.com/36453534/158289083-cd278a51-cb70-478e-b9d0-2d0405c9245c.png)
In the first sentence, LT correctly doesn't do anything.
In the second sentence, LT should... also not do anything. Instead, it does a strange correction...
I can't figure why change 'para eu' for 'de mim'.
My guess is that the rule should include the conjunction after 'para eu'.
Last: "Esse livro é para eu" also leads to the suggestion to change it to 'de mim' or even weirdly 'de eu'.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello!

I have fixed it.
First the antipattern, but it produces no hits in 600 000 sentences:
https://github.com/languagetool-org/languagetool/commit/5d74bc26040f33c4b75e202f8edfb666f0b0f9fc

Then a fix for the rule:
https://github.com/languagetool-org/languagetool/commit/e3a9f7ce9fc71d0ca00e1a1e6f86d11a3fbaf655

The fix only produces two hits:
BEFORE:
[1.txt](https://github.com/languagetool-org/languagetool/files/8251054/1.txt)

AFTER:
[2.txt](https://github.com/languagetool-org/languagetool/files/8251056/2.txt)

**Comment by ricardojosehlima** [comment]
Ok! Some things I have spotted:
- the suggestions 'te', 'me' don't make much sense in any case, so could only be 'mim, ti'
- when the pronoun is in capital letters, the rule should not apply (wrongly flags a EU-Bralat, and others)
- "Compra-a tu" is being wrongly flagged even though 'a' is not a preposition here

**Comment by marcoagpinto** [comment]
What about now?:
https://github.com/languagetool-org/languagetool/commit/0e331429521148bd779b14f0678cb9bb067d209b

[8.txt](https://github.com/languagetool-org/languagetool/files/8254707/8.txt)

**Comment by ricardojosehlima** [comment]
There are som false positives ("a ideia de eu", "tu a tu"), but my guess is tha these are rare, so for me the rule is fine.
