### ISSUE TITLE
[all] false alarm PUNCTUATION_PARAGRAPH_END

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6443]
![Bildschirmfoto 2022-03-16 um 08 16 56](https://user-images.githubusercontent.com/37363/158536618-a0af55aa-633a-4f62-9894-e2e565017630.png)

@jaumeortola would it be easily possible to exclude sentences that start with a number and a period or parenthesis?

> 1. Something

> 2) Something

Also. maybe:

> a.) Something

> a) Something

> • Something

> \* Something

> \- Something

> ✓ Something

**Comment by jaumeortola** [comment]
This rule is active for German, English, Galician, Portuguese and Russian. 
PunctuationMarkAtParagraphEnd2 is active for English and Russian. This rule is slightly different, but I don't know the differences. 

I can add exceptions easily. I guess the exception should be used only when there is one sentence in the paragraph. If there are more than one sentence, then we can keep the rule match. Does it sound right?
