### ISSUE TITLE
[DE]Fehlalarm mit dem Adjektiv "lieb" (SUBJECT_VERB_AGREEMENT[5])

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#6459]
Moin liebes LanguageTool-Team

Heute ist sie **lieb** und morgen böse.
LT: "Prüfen Sie, ob hier eine Form von ‚lieben‘ stehen sollte."
Der Fehlalarm ist mittlerweile aus meiner Sicht ein Klassiker, da das Problem schon über ein Jahr bekannt sein sollte.
In diesem Beispiel wird selbstverständlich das Adjektiv "lieb" eingesetzt und nicht das Verb "lieben".

Bitte schnell fixen.

Grüße Dallun511

**Comment by tiff** [comment]
Behoben mit https://github.com/languagetool-org/languagetool/commit/53dcb0e70fba14976485508ed42140fa7b1423d4

**Comment by MasterDallun511** [comment]
@tiff Der Fehler ist weiterhin vorhanden.
![grafik](https://user-images.githubusercontent.com/78316155/160256653-4513e292-08db-4aba-a78c-fe467ed73e00.png)
