### ISSUE TITLE
[pt] Reviewing foreign word use in pt-pt and pt-br

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#6463]
As a Brazilian user of LT, I was receiving some suggestions to change foreign words to Portuguese ones that didn't apply to our current register. LT has a system for capturing foreign words in Portuguese that goes like this:

one file containing foreign words for both varieties (Portuguese and Brazilian)
one for the Brazilian variety
one for the Portuguese variety

The files for the specific varieties are very small and the one that encompasses both is large (over 1,6k words). 

I then worked on the large file, creating a spreadsheet that in the first column repeats the original list of foreign words for both varieties, in the second column are the changes that I view as necessary: either changing the translation (abat-jour = quebra-luz for abat-jour = abajur) or deleting the situation, for the Brazilian variety accepts much more foreign words than the Portuguese one  (antidoping may have to be changed to antidopagem in Portuguese, but in Brazilian antidoping is the word of general use), and finally in the third column two << indicate that a change has occurred, as can be seen in the image attached).

![estr](https://user-images.githubusercontent.com/36453534/159246047-92d99dab-2724-4421-bc8f-440ac49ab802.png)

A final suggestion: the names of the files are barbarisms-pt, barbarisms-pt-pt, barbarisms-pt-br but to my knowledge these are not cases of what is barbarism in English; I don't know the word for 'use of foreign words' in English, in Portuguese it is surely 'estrangeirismo', not 'barbarismo'.
[estrangeirismos.xlsx](https://github.com/languagetool-org/languagetool/files/8314789/estrangeirismos.xlsx)

**Comment by marcoagpinto** [comment]
Hi Ricardo,

I have added all words and also fixed some words.

https://github.com/languagetool-org/languagetool/commit/e55af0365ec5528e99126a0f4f9d38a7f4cad418

https://github.com/languagetool-org/languagetool/commit/5118c365119b996e31734007cf862255781c44e8

https://github.com/languagetool-org/languagetool/commit/fcd10b4502da15844903e1a9f672400bf0fbdc51

If you find any mistake, please tell.

Thanks!

**Comment by ricardojosehlima** [comment]
Looks fine to me! What about adding
app = aplicativo
apps = aplicativos
(at least for pt-br)

**Comment by ricardojosehlima** [comment]
Hi @marcoagpinto I've noticed that the word 'slide' is still being flagged for pt-br as a foreign word, but we use it regularly
