### ISSUE TITLE
[pt] It suggests starting with an uppercase word when word is already uppercase

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#647]
Hello!

There is screenshot of the issue in:
http://forum.languagetool.org/t/pt-some-false-positives-in-my-thesis-2016-12-16/1279/17

and a sample file on:
http://forum.languagetool.org/t/pt-some-false-positives-in-my-thesis-2016-12-16/1279/20

**Comment by TiagoSantos81** [comment]
Closed as 'NOT OUR BUG'. 
See: http://forum.languagetool.org/t/pt-some-false-positives-in-my-thesis-2016-12-16/1279/21
