### ISSUE TITLE
Understanding the preAO portugese variations

### ISSUE THREAD

**Issue by Minenash** [languagetool-org/languagetool#6479]
I'm using the java tool, and saw the weird variant names for portuguese, after a bit of searching, I finally understood that preAO meant before the agreement, but I'm still confused by the variants, as according to the site I read the two countries with variants suffixed with preAO also accepted the agreement. Are Angola preAO and Moçambique preAO the same as their Brazil/Portugal counterparts preAO, or are there also some Angola/Moçambique specific things in these.

(Also, relatedly, if I were to show language options to a user, should I keep Spanish's voseo variant named that, or would `Spain` make more sense)

Thanks!

**Comment by marcoagpinto** [comment]
Basically, there are two accepted variants: Portuguese and Brazilian, both “after agreement”.

The Angola and Mozambique ones don't have specific rules, just specific dictionaries.

**Comment by Minenash** [comment]
So the dictionaries are preAO, but would it be more user friendly to count it as "Brazilian preAO" and "Portuguese preAO", to keep it with those two counties names, or just not to include them at all?

**Comment by marcoagpinto** [comment]
What is your opinion, @jaumeortola ?

Thanks!

**Comment by jaumeortola** [comment]
> (Also, relatedly, if I were to show language options to a user, should I keep Spanish's voseo variant named that, or would Spain make more sense)

"Voseo" is usual in some Latin American countries (Argentina, Chile, Paraguay, Uruguay…), not Spain. 

I have no clue about the Portuguese variants and dictionaries. At some point, we will rebuild those dictionaries (see: https://github.com/languagetool-org/languagetool/issues/6079), but I don't know when. Any information about the dictionaries content and use will be appreciated.
