### ISSUE TITLE
[pl] missing words?

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6486]
Here's an (unfiltered) list of words that Polish users often add to their dictionary:

* Zełenski
* Wołodymyr
* contentu
* mega
* OLX
* eko
* benfity
* 24h
* fake
* beauty
* aś
* influencerów
* loftowym
* email
* bio
* code
* benefitów
* dress
* BIO
* Bytnar
* Exupéry
* Alexem
* copywritingu
* procesowana
* ADHD
* Agricole
* research
* chia
* Czarnek
* QR
* e-sklepu	
* arganowy
* modowych
* Zzdzich
* casualowych
* Dmytro
* Emily
* Aspergera
* biznesowo
* Netflixa
* outfit
* fashion
* cyberataków
* sprawczości
* cardio
* uważności
* ekogroszek
* F1
* elastanu
* Felixa

**Comment by milekpl** [comment]
I am updating the spelling dictionary. The following words were not included:

* OLX - proper name of a company; it remained active in Russia, so I'm not going to include it right now
* benfity - typo
* beauty - English word
* aś - huh
* Bytnar - proper name
* Exupéry - included as Saint-Exupéry
* procesowana - not a word (jargon)
* Agricole - part of the bank name, maybe will add as a complex form
* Czarnek - proper name, probably will be added in a future update
* QR - acronym
* Zzdzich - typo
* Dmytro - not yet in sjp.pl
* Emily - foreign proper name
* cardio - jargon

**Comment by milekpl** [comment]
Sorry, totally forgot about compounds, and had no access to my computer for the most of my day
