### ISSUE TITLE
The 5.7 release was incorrectly published to Maven Central as $%7Brevision%7D

### ISSUE THREAD

**Issue by mattvalley** [languagetool-org/languagetool#6490]
I saw that the 5.7 release was recently tagged at https://github.com/languagetool-org/languagetool/releases/tag/v5.7 .  However, when I look at what is published in Maven Central at https://search.maven.org/artifact/org.languagetool/languagetool-core I see that the new release has the version specified as $%7Brevision%7D which looks corrupt.  See attached screenshot.
![corrupt_languagetool_release_version](https://user-images.githubusercontent.com/4983376/160694805-55d593b8-9346-49ab-9807-51b115e90ac3.png)

I see this issue with many of the jars that were released this week and not just with the languagetool-core jar.

Is this something you can fix by republishing the correct 5.7 version of the build artifacts to Maven Central?  Or is this actually a bug in Maven Central itself?

**Comment by danielnaber** [comment]
We're not sure where the bug comes from, but we'll try to publish a "real" 5.7 soon.

**Comment by danielnaber** [comment]
It's not (yet?) visible on https://search.maven.org/search?q=languagetool, but it's now available on Maven Central.

**Comment by mattvalley** [comment]
@danielnaber Thank you for republishing the 5.7 version.  I see it now on Maven Central with the correct version.
