### ISSUE TITLE
[pt] user feedback "matricula"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6492]
> Fiz o teste com uma só palavra e não constou erro ortográfico, a palavra "matricula" sem o assento.

**Comment by marcoagpinto** [comment]
"O Marco matricula o seu filho na escola."

**Comment by marcoagpinto** [comment]
(without accent, it is the verb "matricular")

**Comment by tiff** [comment]
But shouldn't we detect when you are using the wrong one?

**Comment by marcoagpinto** [comment]
yes, tell me the full sentence.

Writing just the word, it won't appear as a typo since it is a valid word.

**Comment by tiff** [comment]
Unfortunately the user did not provide the full sentence

**Comment by marcoagpinto** [comment]
@jaumeortola @tiff 

I have fixed the rule, and I am currently removing false positives.

Rule ID: DIACRITICS (by Jaume).

Maybe this rule will replace all the paronym ones created by Tiago Santos years ago?

**Comment by marcoagpinto** [comment]
I believe most false positives are gone.
