### ISSUE TITLE
[pt] Suggesting diacritic for 'ate'

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#6509]
Maybe because the verb 'atar' exists and can be conjugated as 'Quero que ate os nós do sapato', LT does nothing when we forget the diacritc on the preposition 'até':

E ate o menino conseguiu fazer isso.
Vou ate minha casa e volto.

A possible solution when the user writes 'ate':
Alert the user that if he intended to write 'até' the diacritic should be added ("Se pretende usar a preposição 'até', acrescente o acendo agudo' or "A preposição 'até' tem acento agudo" assuming that almost all uses of 'ate' will be of the preposition; I particularly prefer this latter message).

**Comment by marcoagpinto** [comment]
Ahhhhh… now that you mention it, I was supposed to improve the diacritics rule to try to make it work with "matricula", at 5am I will see if it can also work with "ate".

Thanks!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Done!

https://github.com/languagetool-org/languagetool/commit/75d7cefd12218b08af85ff6122c9f540f7cb83c1

In 600 000 sentences it only produces two hits:
[1.txt](https://github.com/languagetool-org/languagetool/files/8438848/1.txt)

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I made the rule more flexible:
https://github.com/languagetool-org/languagetool/commit/c7cc722132312c8a62717d9b2c5ecff02962e586

In 600 000 sentences it now produces 9 hits:
[2.txt](https://github.com/languagetool-org/languagetool/files/8438981/2.txt)

**Comment by ricardojosehlima** [comment]
Only 9 out of 600k? I keep forgetting this diacritic, but if it is not a usual issue, so better. At least, LT has incorporated one more rule that may help.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I may retire this year due to my illness, and then will have more time for open-source.

🙂 🙂 🙂

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I have improved the rule:
https://github.com/languagetool-org/languagetool/commit/7f67757e4266fa18784a5793557a5620c7522aa4

It now gave one more hit:
`O atacante Gabriel Jesus, titular da equipe, foi decisivo na ate então inédita conquista.`

**Comment by ricardojosehlima** [comment]
What if the rule had no context at all? I checked the rule and it seems that it only applies to 'ate' if tagged as preposition

**Comment by marcoagpinto** [comment]
Well, it would probably produce tons of false positives:
`"Quero que o Rui ate as cordas."`

**Comment by ricardojosehlima** [comment]
@marcoagpinto would it? Maybe it is worth a test, if it does, then your last version remains.

**Comment by ricardojosehlima** [comment]
@marcoagpinto a quick try at the LT editor and I have seen lots of 'ate' instead of 'até', but seen none like the example you mentioned - but a deeper look will be necessary.
And after all, I was right in considering the forgetting of the diacritic in 'até' as common issue: 992 issues.
One tip already: if 'ate' is 'Ate' and not in the beginning of the sentence, don't correct it.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

How should I code it then?

I will do it on Monday.

Weekend is workdays, unless I win the EuroMillions tonight 🙂 🙂 🙂

**Comment by ricardojosehlima** [comment]
just remove the postag information from your rule.
And add an exception: don't correct it if the first or all the letters are capitalized (Ate, ATE) and NOT in the start of a sentence.

</rule>
		<rule>
			<pattern>
				<marker>
					<token>ate</token>
				</marker>
			</pattern>
			<message>Se pretende usar a preposição 'até', acrescente o acento agudo.</message>
			<suggestion>até</suggestion>
			<example correction="até">O Rui foi decisivo na <marker>ate</marker> então inédita conquista.</example>
		</rule>

**Comment by marcoagpinto** [comment]
Hello @ricardojosehlima 

Today is work day, so I can't dedicate much time to it.

I created a rule to generate all the "ate" words in the 600 000 sentences wordlists:
```
pt-PT.txt
tatoeba-pt.txt
```

Rule:
```
	<!-- ATE ATÉ -->
    <rulegroup id='CONFUSÃO_ATE_ALL' name="Confusão: ate/até">
		<rule>
			<pattern>
				<marker>
					<token>ate</token>
				</marker>
			</pattern>
			<message>Se pretende usar a preposição 'até', acrescente o acento agudo.</message>
			<suggestion>até</suggestion>
			<example correction="até">O Rui foi decisivo na <marker>ate</marker> então inédita conquista.</example>
		</rule>
	</rulegroup>
```

[0_ate_all.txt](https://github.com/languagetool-org/languagetool/files/8458455/0_ate_all.txt)

In the 600 000 sentences it only produces:
```
Portuguese (Portugal): 55 total matches
Portuguese (Portugal): ø0.00 rule matches per sentence
Portuguese (Portugal): 17323 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```

How did you get hundreds of hits?

On Monday, I will improve the rule to match more.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I was just looking at the results, and you were right about matching only “ate” with lowercase will do the task.

I will rewrite the rule tomorrow.

Thanks!

**Comment by ricardojosehlima** [comment]
Yes, this was the pattern I used at https://community.languagetool.org/ruleEditor2/index?lang=en
We've checked your pattern against sentences 1 to 992 from the pt [Wikipedia](http://www.wikipedia.org/), [Tatoeba](http://tatoeba.org/), and several online forums and found the following matches. Please consider modifying your rule if these matches are false alarms. Hover over the words to display their part-of-speech tags.

**Comment by marcoagpinto** [comment]
Hello @ricardojosehlima 

I have improved and cleaned the rule:
https://github.com/languagetool-org/languagetool/commit/0954cf1e5936b8f820c6013a1c48b004d28307c0

[10.txt](https://github.com/languagetool-org/languagetool/files/8463397/10.txt)

```
Portuguese (Portugal): 38 total matches
Portuguese (Portugal): ø0.00 rule matches per sentence
Portuguese (Portugal): 17323 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I believe the rule is now working for most cases:
https://github.com/languagetool-org/languagetool/commit/b38f5241f4c1ef8ea600787c6847e582139bc780

I was working on a document from the thesis supervisor and noticed several missing hits.
[12.txt](https://github.com/languagetool-org/languagetool/files/8468509/12.txt)

```
Portuguese (Portugal): 46 total matches
Portuguese (Portugal): ø0.00 rule matches per sentence
Portuguese (Portugal): 17323 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

ahhhh… sorry… forgot a POS:
https://github.com/languagetool-org/languagetool/commit/d45dca4732c6410ea537b3321da75ecff6906f56

[13.txt](https://github.com/languagetool-org/languagetool/files/8468675/13.txt)

```
Portuguese (Portugal): 49 total matches
Portuguese (Portugal): ø0.00 rule matches per sentence
Portuguese (Portugal): 17323 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```

**Comment by ricardojosehlima** [comment]
Ok!
