### ISSUE TITLE
[en] brain wave(s) → brainwave(s)

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6514]
Hello!

`There are many kinds of brain waves, and a brain wave is all one needs.`

LT doesn't suggest joining the words “brain waves” into just one word.

**Comment by dpelle** [comment]
Both "brainwave" or "brain wave" are good, at least according to wiktionary: https://en.wiktionary.org/wiki/brainwave

Also, https://en.wikipedia.org/wiki/Neural_oscillation has both spellings.

So we should not suggest anything, it would be false error.

**Comment by marcoagpinto** [comment]
Ahhhh... okay.
