### ISSUE TITLE
[pt] sources (dictionaries) for Portuguese words

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#6517]
In this issue, I am going to collect the most important sources for Portuguese vocabulary. 
@marcoagpinto @ricardojosehlima Please, add other sources you may know, and comment strengths and weaknesses of them (e.g. good/poor coverage, good for BR/PT vocabulary or not, and so on). 

* Michaelis https://michaelis.uol.com.br/moderno-portugues/busca/portugues-brasileiro/
* Priberam https://dicionario.priberam.org/
* Porto Editora https://www.infopedia.pt/dicionarios/lingua-portuguesa/
* Léxico https://www.lexico.pt/
* Aulete https://www.aulete.com.br/
* Dicio https://www.aulete.com.br/
* Wikcionário https://pt.wiktionary.org/w/index.php?search=
* Educalingo https://educalingo.com/pt/dic-pt/
* Vocabulário ortográfico da Língua Portugesa https://volp-acl.pt/index.php
* Vocabulário Ortográfico do Português http://www.portaldalinguaportuguesa.org/

**Comment by marcoagpinto** [comment]
@jaumeortola 

The most recent pt-BR dictionary and thesaurus is here:
https://opengrok.libreoffice.org/xref/dictionaries/pt_BR/

**Comment by jaumeortola** [comment]
Thanks, @marcoagpinto 
I see some problems in this last version of pt-BR Hunspell dictionary. It generates 80 million forms, while previous dictionaries have 10 million forms. It creates many forms with prefixes: for example, a- + abafar = aabafar. This seems wrong. Have you tried this dictionary?

**Comment by marcoagpinto** [comment]
@jaumeortola 

It is the LibreOffice dictionary, Olivier Hallot told me about it since he was going to do some editing with my app Proofing Tool GUI.

**Comment by marcoagpinto** [comment]
@jaumeortola 

It has 10 million forms too:
![pt_BR_dic_statistics_20220408](https://user-images.githubusercontent.com/5192600/162454529-8be99da6-3dd6-4129-bcb1-c4052041a744.png)

See the wordlist here:

[pt_BR_dic_wordlist_20220408.zip](https://github.com/languagetool-org/languagetool/files/8452615/pt_BR_dic_wordlist_20220408.zip)

I used Proofing Tool GUI to extract it:
https://proofingtoolgui.org

Thanks!

**Comment by jaumeortola** [comment]
Yes, you are right. It has 10 million forms. The problem is that the unmunch command for Hunspell dictionaries doesn't work with UTF-8.

**Comment by marcoagpinto** [comment]
@jaumeortola 

Use Proofing Tool GUI, my linguistic tool.
