### ISSUE TITLE
PatternRules ignore postag in <match> when rule contains <or>

### ISSUE THREAD

**Issue by f-knorr** [languagetool-org/languagetool#652]
When writing some new rules for English, I wrote the following rule:
```
<rule>
    <pattern>
        <or>
            <token postag="SENT_START"/>
            <token regexp="yes">what|which|who|whose|where|when|whether|how</token>
        </or>
        <token postag="DT"/>
        <token postag="NNS"><exception postag="NN|NN:.*" postag_regexp="yes"/></token>
        <marker>
            <token postag="VBZ"><exception>is</exception></token>
        </marker>
    </pattern>
    <message>You should probably use <suggestion><match no="4" postag="VBP"/></suggestion>.</message>
    <example correction="bark">The dogs <marker>barks</marker> loudly.</example>
    <example correction="bark">He asked whether the dogs <marker>barks</marker> loudly.</example>
</rule>
```
The test for this rules fails because the insertion of an inflected matched token (`<match no="4" postag="VBP"/>`). The reason for this seems to be the `<or>` within the rule: The PatternRuleHandler seems to treat the iinflection correclty only for the first token in the or-group. (see `suggestionMatches.clear();` in PatternRuleHandler.java)

**Comment by bebras123** [comment]
Also see: https://forum.languagetool.org/t/wrong-match-suggestion-when-changing-postag-in-rules-with-or/2189

**Comment by oserikov** [comment]
Working on fix.

**Comment by oserikov** [comment]
Seems that I've fixed the problem with or patterns, it passes the case stated in https://forum.languagetool.org/t/wrong-match-suggestion-when-changing-postag-in-rules-with-or/2189.

But your case fails:
```
java.lang.AssertionError: English: Incorrect suggestions: [bark] != [Bark] for rule AGREEMENT_SENT_START[1] on input: The dogs barks loudly. 
Expected :[bark]
Actual   :[Bark]
```
The word is correctly corrected, but is also capitalized. May that be caused by `SENT_START`? Or here is another bug discovered?

**Comment by f-knorr** [comment]
Great job, @oserikov ! Closed this issue.

**Comment by danielnaber** [comment]
@f-knorr Would you also like to merge the PR? (#920)
