### ISSUE TITLE
[ru] missing hyphen false positive

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#6522]
кликните правой кнопкой по нужному пулреквесту.

**Comment by danielnaber** [comment]
Hi Peter, I have added you to this repo so you can set the labels for your issues yourself.

**Comment by donnerpeter** [comment]
@danielnaber Thanks! I'm not familiar with the workflow though. Is it enough to specify the language?

**Comment by danielnaber** [comment]
Usually yes. If you know the issue requires more than "just" XML changes, you can also specify `code/java`.

**Comment by yakovru** [comment]
Already fixed.
