### ISSUE TITLE
Grazie & LT Premium license

### ISSUE THREAD

**Issue by gour** [languagetool-org/languagetool#6537]
Hello,

I'm evaluating PhpStorm, but would like to use IDE for writing as well (AsciiDoc & Markdown), so wonder if the built-in Grazie plugin can take advantage of LT Premium license?

What about Grazie Pro version? Does it use LT at all?

Sincerely,
Gour

**Comment by danielnaber** [comment]
I think Grazie runs locally, while LT Premium is a cloud solution, so I'm afraid using LT Premium with Grazie isn't currently possible.

**Comment by danielnaber** [comment]
I don't know, the Grazie add-on isn't developed by us but by JetBrains, I think you'll need to contact them.
