### ISSUE TITLE
[pt] adverbs -mente

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#6542]
I am uncertain if these Portuguese adverbs all are correct. For example, "ampliamente, amplissimamente" are not in any dictionary. I know a few are old spelling (we can keep these because we have rules for them). Could you check them? @ricardojosehlima @marcoagpinto 

`acertadissimamente, aconselhavelmente, activissimamente, admissivelmente, afabilissimamente, agilissimamente, aguisadamente, alopaticamente, amabilissimamente, amadoristicamente, amarissimamente, ampliamente, amplissimamente, animadissimamente, apetecivelmente, arquitectonicamente, articulatoriamente, asseveradamente, assinalavelmente, assistematicamente, atrevidissimamente, atribuladissimamente, atrocissimamente, aversamente, bajulatoriamente, beatissimamente, belissimamente, biunivocamente, bravissimamente, brevissimamente, calculisticamente, calidamente, carissimamente, cautissimamente, censoriamente, censuravelmente, cepticamente, chiquerrimamente, cismaticamente, citologicamente, climatologicamente, comodissimamente, comovidissimamente, congenitamente, conotativamente, conseqüentemente, contabilisticamente, correctissimamente, cosmogonicamente, cosmologicamente, crespamente, cristalograficamente, cromaticamente, cronicamente, crudelissimamente, delicadissimamente, densissimamente, dermatologicamente, desaconselhavelmente, desaparadamente, desastradissimamente, descontinuamente, desejavelmente, desmilitarizavelmente, diacronicamente, diafanamente, dicotomicamente, didacticamente, dificilimamente, dignissimamente, distintissimamente, distribucionalmente, dulcissimamente, eclecticamente, ecograficamente, efemeramente, egoistamente, eloquentissimamente, entranhavelmente, epidemicamente, epidemiologicamente, epistemologicamente, equanimemente, ergologicamente, esotericamente, esperavelmente, espertissimamente, espiralmente, esponencialmente, estanquemente, estataticamente, estocasticamente, estultissimamente, exactamente, exibicionisticamente, expiatoriamente, facilimamente, farmacologicamente, feericamente, ferocissimamente, fetidamente, fidelissimamente, filatelicamente, flagilosamente, fluidicamente, fotoelectricamente, frutiferamente, galvanicamente, gastronomicamente, geneologicamente, geopoliticamente, hebdomadariamente, hegemonicamente, heliograficamente, hidroelectricamente, hipnoticamente, ilustravelmente, imaginavelmente, impagavelmente, imparavelmente, imprevisivelmente, improvavelmente, inacabavelmente, indemovivelmente, indisputavelmente, indomitamente, inelegivelmente, inescrutavelmente, inespecificamente, inesquecivelmente, inexaurivelmente, infimamente, inolvidavelmente, inqualificavelmente, insubornavelmente, insulvamente, integramente, irrepetivelmente, itenerantemente, lastimavelmente, lentissimamente, lestissimamente, lexicograficamente, liberrimamente, lividamente, louçãmente, mecanograficamente, meiguissimamente, mesmissimamente, milimetricamente, modestissimamente, monogamicamente, neurologicamente, notabilissimamente, oftalmologicamente, oniricamente, ousadissimamente, parcoviamente, paripateticamente, paritariamente, pauperrimamente, perduramente, perecivelmente, permissivelmente, persuadivelmente, planetariamente, plausivelmente, poligamicamente, predizivelmente, prestavelmente, prestissimamente, proteladamente, psicanaliticamente, psicofisiologicamente, racicamente, rapidissimamente, rarissimamente, reaccionariamente, reconhecivelmente, referencialmente, reprovavelmente, returbantemente, riquissimamente, sectariamente, sequencialmente, simolicissimamente, sintagmaticamente, sismologicamente, socioeconomicamente, subrepticiamente, sumarissamente, tautologicamente, taxinomicamente, taxionomicamente, taxonomicamente, tectonicamente, vastissimamente, velocissimamente, zoologicamente`

**Comment by ricardojosehlima** [comment]
Wow, looks like someone made a list wit -issima and -vel and the added -mente and didn't think if it was viable or not.
I selected 50 from the list. One criterion was if it made sense considering the original adjective.
See:
"O político está inelegível." How could -mente be added to this?
But now:
"Que isso está certo é indisputável." --> "Indisputavelmente, isso está certo."

the list
aconselhavelmente
admissivelmente
amadoristicamente
apetecivelmente
arquitectonicamente
articulatoriamente
asseveradamente
assistematicamente
calidamente
censuravelmente
citologicamente
conotativamente
conseqüentemente
contabilisticamente
crespamente
desaconselhavelmente
desejavelmente
diacronicamente
diafanamente
dicotomicamente
didacticamente
efemeramente
egoistamente
epidemiologicamente
epistemologicamente
esperavelmente
espiralmente
esponencialmente
estocasticamente
exactamente
feericamente
geopoliticamente
imaginavelmente
imprevisivelmente
improvavelmente
indisputavelmente
infimamente
integramente
lastimavelmente
lentissimamente
lexicograficamente
lividamente
milimetricamente
permissivelmente
planetariamente
plausivelmente
referencialmente
socioeconomicamente
subrepticiamente
tautologicamente

**Comment by jaumeortola** [comment]
Thank you!
