### ISSUE TITLE
[pt] LT is vegan... but not in Portuguese?

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#6552]
LT recognizes 'vegan' in en but not in pt: vegano, vegana, veganos, veganas are not in the dictionary. 
Curiously, veganismo is.

**Comment by marcoagpinto** [comment]
Another task for 5am 🙂

**Comment by marcoagpinto** [comment]
Hello Ricardo!

I have just added the words:
https://github.com/languagetool-org/languagetool/commit/0ccb3f033dd7088166ebd78496cc5d49e49d5c07

https://github.com/languagetool-org/languagetool/commit/87cee9f6660a31bc26d2c0befac731a01827cd4b

**Comment by ricardojosehlima** [comment]
Great and I see you added vegan and vegans, although foreign, both are used in pt-br.
