### ISSUE TITLE
Spelling: missing split word suggestions

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#6557]
We don't provide good suggestions for joined camel-case words like: BretagneItinéraire (French) or GreatElephant (English). It happens in most languages.

**Comment by milekpl** [comment]
@jaumeortola This is because most languages are set to ignore all camel case words altogether. I have just set this ignoring setting to off yesterday for Polish by adding this to the `.info` file:

 `fsa.dict.speller.ignore-camel-case=false`

**Comment by jaumeortola** [comment]
> This is because most languages are set to ignore all camel case words altogether. 

That is not the case in the languages I have looked into. `fsa.dict.speller.ignore-camel-case=false` is already there. 
"BretagneItinéraire" (camel case) is a spelling error in French, but there was no suggestion. For "Bretagneitinéraire" (not camel case) we get the expected suggestion ("Bretagne itinéraire"). So far, there is a solution for ES, FR, CA. I will try a more general solution for all languages using the Morfologik speller

**Comment by milekpl** [comment]
I cannot for the life of me find the `french.dict` file with its .info file, but I suspect that you might have the function for converting case off (see line 234 in `Speller.java` in morfologik-stemming).

**Comment by milekpl** [comment]
@jaumeortola Just tested on the Polish speller – get same results as you do. Apparently, `findReplacementCandidates` does not even try to break camel-case words in the obvious place because not all case conversions are properly covered (esp. lines 452 and following). I thinks this must be fixed in morfologik-stemming.

**Comment by jaumeortola** [comment]
This could be a more general solution: https://github.com/morfologik/morfologik-stemming/pull/114

**Comment by milekpl** [comment]
Nice, I added test two other cases to morfologik-stemming JUnit tests.

**Comment by milekpl** [comment]
@jaumeortola There's a new release of morfologik-speller, we should update it

**Comment by jaumeortola** [comment]
> There's a new release of morfologik-speller, we should update it

I will do it now.

**Comment by milekpl** [comment]
This is because most languages are set to ignore all camel case words
altogether. I have just set this ignoring setting to off yesterday for
Polish.

wt., 19.04.2022, 13:57 użytkownik Jaume Ortolà ***@***.***>
napisał:
