### ISSUE TITLE
[pt] User feedback: ás dos vs. às dos (LOOP)

### ISSUE THREAD

**Issue by MarvinErdner** [languagetool-org/languagetool#6559]
> Essas situações permitem deias e compará-las ás dos colegas.

HOMOPHONE_AS_CARD[4]

_Essas situações permitem deias e compará-las às dos colegas._

HOMOPHONE_AS_CARD[2]

_Essas situações permitem deias e compará-las ás dos colegas._

https://twitter.com/D1360_64RC14/status/1516553037652926471

**Comment by marcoagpinto** [comment]
Hello!

Nice finding.

I will work on it today or at 5am.

Thanks!

**Comment by marcoagpinto** [comment]
Fixed:
https://github.com/languagetool-org/languagetool/commit/d244cccb784657fccfbd64ff6d0dca7fa307aa15
