### ISSUE TITLE
Missing rule for accord du participe passé

### ISSUE THREAD

**Issue by cphyc** [languagetool-org/languagetool#656]
La phrase :
```
Ta voiture, je ne l’ai pas volé
```
est détectée comme étant correcte, malgré l’absence du « e » à « volé ».

**Comment by vkyfox** [comment]
J'ai essayé de créer une règle qui corrigerait ce manque, mais le problème d'une telle règle, c'est que je ne conçois pas de moyen faisable de déterminer si "l'" réfère bel et bien au nom qui le précède.
Par exemple, la phrase suivante est grammaticalement identique (ou presque) à la vôtre, mais cette fois-ci correcte :
> Pour ta voiture, je ne l'ai pas su avant plusieurs jours.

Malgré tous mes efforts, impossible de créer une règle qui ne regorgerait pas de faux positifs.
