### ISSUE TITLE
An error has occurred (NullPointerException with deactivateRule)

### ISSUE THREAD

**Issue by willismonroe** [languagetool-org/languagetool#6563]
I'm trying to deactivate the Passive Voice rule but every time I select this option from the right click menu I get the following error message:
![image](https://user-images.githubusercontent.com/715210/164330959-d741e56f-4d14-49e1-bbb1-857b0941d20e.png)

**Comment by danielnaber** [comment]
@FredKruse

**Comment by FredKruse** [comment]
The issue should be solved
@willismonroe Please test it with the nightly tomorrow.
