### ISSUE TITLE
[PT-BR] “Hacker” does not mean “Cyber-Pirate” in Brazilian Portuguese

### ISSUE THREAD

**Issue by kaiodcosta** [languagetool-org/languagetool#6579]
Recently, I used LanguageTool in the Brazilian Portuguese language, and I came across a warning, notifying the foreignness of the word “Hacker” and the recommendation to use the word “Cyber-Pirate”.

Putting such a synonym in the word, besides being incorrect, is an association of “Hackers” to “Cyber Thieves”, encouraging prejudice and suppression of the hacker and hackerativist community. 

I recommend a look at [RFC 2828]( https://www.ietf.org/rfc/rfc2828.txt)(Internet Security Glossary), and the [Portuguese language dictionary Michaelis]( https://michaelis.uol.com.br/moderno-portugues/busca/portugues-brasileiro/hacker/).

**Comment by marcoagpinto** [comment]
Fixed!

https://github.com/languagetool-org/languagetool/commit/4ef4d895c63889ae7f737e3125cffb859ddd80e1
