### ISSUE TITLE
[pt] Missing “pleiteada” 

### ISSUE THREAD

**Issue by MarvinErdner** [languagetool-org/languagetool#6590]
_Inicialmente, a limitar pleiteada pelo Ministério Público foi deferida…_  

— > leitada

![grafik](https://user-images.githubusercontent.com/88431679/165294939-f73c3b82-7757-429d-aef9-711cc985a224.png)

**Comment by marcoagpinto** [comment]
Fixed!

https://github.com/languagetool-org/languagetool/commit/9036065d41996473f8f9dc4560a29165c2532b82

https://github.com/languagetool-org/languagetool/commit/00cf1bae3460899f8e3fde1a8d1cd61f9646561e

**Comment by jaumeortola** [comment]
@marcoagpinto As you can see, the verb is already in the new tagger dictionary (coming soon): https://github.com/languagetool-org/portuguese-pos-dict/blob/ffbca71c064845dde8e47994e570c60e5b66867b/src-dict/verbs-fdic.txt#L11557
