### ISSUE TITLE
[jp] suggestion for DOUSI_KOTOGADEKIRU rule

### ISSUE THREAD

**Issue by mhorioka** [languagetool-org/languagetool#6592]
Hi

## Background

While looking at an issue reported to IntelliJ IDEA https://youtrack.jetbrains.com/issue/IDEA-291722 , 

I found that the Japanese DOUSI_KOTOGADEKIRU rule needs a bit of improvement.

As discussed in a couple of sites, I agree that the rule detects a kind of redundant expression.

- https://www.fumitei.jp/surukotogadekiru/
- https://lifelikewriter.com/verbose-sentences/

## Issue
However, the suggestion/correction provided in the rule was for a very special case (with specific a part of verb 暮).  As a result,  it's not useful for users or users would see the result as a false positive. 

		<rule id="DOUSI_KOTOGADEKIRU" name="動詞_ことができる">
			<pattern>
				<token postag="動詞.*" postag_regexp="yes"/>
				<token>こと</token>
				<token>が</token>
				<token>できる</token>
			</pattern>
			<message>省略が可能です。暮<suggestion>らせる</suggestion></message>
			<example correction="らせる"><marker>暮らすことができる</marker></example>
		</rule>

## Questions

Do you have any reference/rationale for the rule, which recommends specific suggestions? 

If no, I personally believe
- there is no general suggestion for this context "Verb + ことができる" 。
- Maybe we can change the message saying "this phrase can be redundant and worth considering rephrasing with a shorter expression"

Looking at https://dev.languagetool.org/languages , maybe nobody maintains Japanese rule. If you need a proposal for the change to the rule file, I can do.

**Comment by danielnaber** [comment]
> maybe nobody maintains Japanese rule

Indeed that's true, so any feedback or improvements, especially as pull requests, is welcome.

**Comment by KisaragiEffective** [comment]
Hi, I'm original reporter of IDEA-291722.

## Case
|Case|Expected|Actual|Comment|
|:---|:-------|:-----|:------|
|暮らすことができる|暮らせる|暮らせる|should be work|
|活かすことができる|活かせる|-|ftn, but should work|
|見つけることができる|見つけられる|らせるる|the original case|
|遊ぶことができる|遊べる|-|further test needed|
|行くことができる|行ける|-|further test needed|

Note: the below sentences is Japanese.
「暮らす」はサ行五段活用で、語幹は「くら」です。「活かす」もサ行五段活用であるため、現行の書き換え規則でも動作することでしょう。
しかし、サ行五段活用ではない語では動作しないことが想定されます。実際に動作させて確かめることが必要なので、現時点で断言はできません。参考までに記しておくと、「見つける」はカ行下一段活用、「遊ぶ」はバ行五段活用、「行く」はカ行五段活用です。

**Comment by mhorioka** [comment]
@KisaragiEffective thank you for your insight.

As I wrote above, at this moment my proposal is to change the message as "this phrase can be redundant and worth considering rephrasing with a shorter expression" or "表現が冗長です" without providing a specific suggestion based on a context because 

1) my primary goal here is, as a quick solution, to remove the (impression of) false positive with an irrelevant suggestion for the correction.

2) I'm not sure if it's possible to implement such a complex rule based on the table you provided.  For example, seeing the output of languagetool-commandline.jar command, it does not contain "verb form" or "動詞の活用" like:

echo "見つけることができる" | java -jar languagetool-commandline.jar -t -l ja-JP -c UTF-8
Expected text language: Japanese (no spell checking active, specify a language variant like 'en-GB' if available)
Working on STDIN...
<S> 見つける[見つける/動詞-自立]こと[こと/名詞-非自立-一般]が[が/助詞-格助詞-一般]できる[できる/動詞-自立,</S>]


This is what I think, based on my quick investigation of LanguageTool, at this moment. If you have a better solution, no problem for you to bring it.

**Comment by KisaragiEffective** [comment]
@mhorioka 
> my primary goal here is, as a quick solution, to remove the (impression of) false positive with an irrelevant suggestion for the correction.
sure, I think my previous comment should be separated into another issue.

**Comment by danielnaber** [comment]
> Do you want to keep it?

Yes, please keep whitespace so any diffs are minimal.

**Comment by mhorioka** [comment]
@danielnaber Hello, I created a PR some time ago. Please advise if anything else is needed from my side.

**Comment by danielnaber** [comment]
@mhorioka I've merged the PR now, thanks.

**Comment by mhorioka** [comment]
@danielnaber thank you! BTW I started to go through Japanese rules and found a couple (maybe more) issues. Will report them separately.
