### ISSUE TITLE
find a way to easily disable and enable whole categories on the command line

### ISSUE THREAD

**Issue by milekpl** [languagetool-org/languagetool#66]
Right now only individual rules or rule groups can be enabled and disabled on the commandline. Find a way to disable and enable whole categories: this is more difficult because categories have only names and types (which also could be used). But names may contain spaces, which means that they need to be escaped on the commandline, or we need to introduce IDs.

In verbose mode, the disabled/enabled categories and types should display also rule IDs that were enabled/disabled.

**Comment by fekete-robert** [comment]
+1, I'd also need this functionality

**Comment by danielnaber** [comment]
Also see #326
