### ISSUE TITLE
[ru] Missing rule for "Важно, что этого удалось показать для случая изотропных материалов."

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool#661]
WRONG Важно, что этого удалось показать для случая изотропных материалов.
CORRECT Важно, что это удалось показать для случая изотропных материалов.

**Comment by yakovru** [comment]
Fixed. Rule created.

**Comment by ZakShaker** [comment]
К сожалению, правило сложнее :-) 
WRONG Важно, что это удалось ДОБИТЬСЯ для случая изотропных материалов.
СORRECT Важно, что этого удалось ДОБИТЬСЯ для случая изотропных материалов.

удалось ДОБИТЬСЯ чего?
удалось ПОКАЗАТЬ что?
