### ISSUE TITLE
[pt] undetected errors: varias/várias

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#6616]
- [ ] Vi varias charges do jornal  >> várias

**Comment by marcoagpinto** [comment]
Very easy to do, also for "vários".

Will do it on Monday, weekend is workday, and I am already very stressed.

Unless I manage to wake up very early to dedicate some hours to it.

🙂

**Comment by marcoagpinto** [comment]
The rule is coded and tested:
https://github.com/languagetool-org/languagetool/commit/6c44e31411632171049a900ccc86accecac766ed

100% positives:

[0.txt](https://github.com/languagetool-org/languagetool/files/8596331/0.txt)
