### ISSUE TITLE
Normal installer with updater.

### ISSUE THREAD

**Issue by Piter432** [languagetool-org/languagetool#662]
Like in the title. Would be nice to install LanguageTool on Windows like a normal Windows program instead  of installing the portable-only version. The updater component for LT is optional, but could also be included.

**Comment by yakovru** [comment]
You can use Windows Repository Chocolaty to do it:
https://chocolatey.org/packages/languagetool

**Comment by Piter432** [comment]
@yakovru: Hmm, I've never used this, so I'm not sure I'm doing it right. I have LT .zip file on my Downloads folder and I downloaded .nupkg file from this site to the same location, where .zip file is downloaded. Now I need to install like it says on the page, right?

**Comment by danielnaber** [comment]
I also think this is something better done outside of LT. I'm doing the releases and I don't even have a Windows system that I could test this on. Also, making the release is already quite some work, I don't want to process to be more complicated.

**Comment by Piter432** [comment]
Okay, looks like I know how to install LT (and other programs) almost like a normal program if the program is only in portable version to PC.

Link to guide: https://mspoweruser.com/windows-10-tip-using-package-manager/
