### ISSUE TITLE
Allow automatically checking for updates in LibreOffice

### ISSUE THREAD

**Issue by Glitchy-Tozier** [languagetool-org/languagetool#6635]
In LibreOffice, new updates aren't found for the LanguageTool-extension. It would be great to automatically allow LibreOffice to find updates. Otherwise, users are forced to routinely check website/repository just to make sure they're using the latest version.

### LibreOffice info
```
Version: 7.3.2.2 / LibreOffice Community
Build ID: 49f2b1bff42cfccbd8f788c8dc32c1c309559be0
CPU threads: 8; OS: Linux 5.4; UI render: default; VCL: gtk3
Locale: de-AT (en_GB.UTF-8); UI: en-GB
Flatpak
Calc: threaded
```
### Screenshot
![image](https://user-images.githubusercontent.com/59611881/166525273-3b86abba-058f-4eb5-ae4a-bdd7816127ee.png)

One extension fails to load, but this doesn't seem to be related to LanguageTool.
![image](https://user-images.githubusercontent.com/59611881/166525843-a647eb74-54d8-4b34-9330-565a4faf6df6.png)
![image](https://user-images.githubusercontent.com/59611881/166525919-8df248a3-c5b6-427c-95f7-9059048abd1d.png)

**Comment by danielnaber** [comment]
I cannot reproduce this. We regularly update `https://languagetool.org/languagetool.update.xml` to point to the latest release (although not directly on the date of the release).
