### ISSUE TITLE
[pt] Fix "a pós"

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#6638]
The expression "a pós", commonly used in Brazil as an abbreviation for "a pós-graduação", is being flagged as wrong "Essa expressão é invariável: pó."
The case for this rule is Passou o dia a limpar os pós da casa. that sould be "o pó".
My suggestion is to delete this part of the rule, or to keep it just for the expression "os pós". Any other "pós" would be allowed.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I have fixed it:
https://github.com/languagetool-org/languagetool/commit/0e84b8e6cc12ef42ae765343b48a394eb5be8dda

But it triggers the hyphen rule if it catches a verb after the "pós"
"pós-é"

I have to create an antipattern having in account infinitive + past participle: pós graduação, pós graduado
(it will check for a verb after "pós".

**Comment by marcoagpinto** [comment]
ahhh... it only triggers in pt-PT, in pt-BR not.

**Comment by ricardojosehlima** [comment]
Strange, it triggers here, in the LO version is in grammar.xml
"pós" can also appear as regular word without verb following if: "Eu já fiz uma pós."

**Comment by marcoagpinto** [comment]
Ahhhhhh... 🙂 

Right, I hardcoded it as "as?" and didn't think about "uma" and such.

After I fix the hyphen issue, I will improve that rule.

**Comment by ricardojosehlima** [comment]
Couldn't "pós" just be added as a word, and no rule? 
And as for "pós" as plural of "pó", there could be a rule flagging "os pós".

**Comment by marcoagpinto** [comment]
No, it can't be added as a word because of the language agreement rules for hyphenated words.

pt-PT triggers the rule:
"pós-parto", "pós-morte"

**Comment by marcoagpinto** [comment]
Ahhh... the hyphenator rule is fixed:
https://github.com/languagetool-org/languagetool/commit/e21f4a6be0cf2405daa62ee29d5bed5813a127df

Now I will return to the original one reported by you.

**Comment by marcoagpinto** [comment]
Hello @ricardojosehlima 

I believe it is fixed:
https://github.com/languagetool-org/languagetool/commit/f21ee39a90bc458548ac649ea2db6a086958ac76

[0before.txt](https://github.com/languagetool-org/languagetool/files/8620639/0before.txt)

[2.txt](https://github.com/languagetool-org/languagetool/files/8620642/2.txt)

It only removed 3 false positives:

```
Outra pergunta: posso fazer uma pós que me autorize a demolir e construir auxiliando melhorar ambientes somente?
Na pós, você pode continuar a desenvolver o que aprendeu na graduação, focando em uma área específica do s...
Atualmente cursando Engenharia de Produção e já sonhando com a pós em Engenharia de Segurança do Trabalho.
```

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Are you referring to the text files above? If so, I guess the Wikipedia tests use the pt-PT dictionary, so all other words not in it are flagged.

**Comment by marcoagpinto** [comment]
and bróculo vs brócolis can be added to the .txt file that says "in pt-RB it is written blah blah".

It is easy to fix.

We just need to know the exact words and add them to the PT → BR and the opposite to the BR → PT

**Comment by marcoagpinto** [comment]
It is the file: replace.txt

It is inside the language variances in the grammar.xml folder.

**Comment by ricardojosehlima** [comment]
> @ricardojosehlima
> 
> Are you referring to the text files above? If so, I guess the Wikipedia tests use the pt-PT dictionary, so all other words not in it are flagged.

Yes to the 2.txt file above. But for me, the mystery remains as why these words are flagged for me. 
In the replace.txt, but which one? I haven't found calça in neither the pt-BR or pt-PT folder nor in the pt folder

**Comment by marcoagpinto** [comment]
pt-BR:
[replace.txt](https://github.com/languagetool-org/languagetool/files/8621175/replace.txt)

pr-PT:
[replace.txt](https://github.com/languagetool-org/languagetool/files/8621178/replace.txt)

both files are very incomplete.

**Comment by marcoagpinto** [comment]
\languagetool-language-modules\pt\src\main\resources\org\languagetool\rules\pt\pt-BR

\languagetool-language-modules\pt\src\main\resources\org\languagetool\rules\pt\pt-PT

**Comment by marcoagpinto** [comment]
ahhhhhhhhh...

@ricardojosehlima 

Do you mean they are in INVARIABLE_NOUNS?

What if I move that rule to inside the grammar.xml in the pt-PT?

Only pt-PT will use it.

**Comment by marcoagpinto** [comment]
Let me do it.

Give me two or three minutes.
