### ISSUE TITLE
[ru] N-gram for Russian language

### ISSUE THREAD

**Issue by ZakShaker** [languagetool-org/languagetool#664]
Do we have n-gram data and/or mechanism for Russian language ? How to make it possible?

**Comment by danielnaber** [comment]
It already exists, you just need to add pairs to https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/ru/src/main/resources/org/languagetool/resource/ru/confusion_sets.txt.

Of course, you need to download the ngram data from http://languagetool.org/download/ngram-data/untested/ to make it work. More details are at http://wiki.languagetool.org/finding-errors-using-n-gram-data

**Comment by ZakShaker** [comment]
Thanks! Then it should be added to the list of supported languages: 
"Here you can see the confusion pairs we support so far:

English
German
French
Spanish
"

**Comment by danielnaber** [comment]
The Russian confusion set file has only two pairs, so I wouldn't yet call that "supported" to avoid users getting the impression that it's actually useful. But I've improved the wording on the wiki a bit, thanks.

**Comment by yakovru** [comment]
https://github.com/languagetool-org/languagetool/issues/569
