### ISSUE TITLE
[de] "sehr" wird nicht erkannt im Kontext von "ein sher"

### ISSUE THREAD

**Issue by herschel666** [languagetool-org/languagetool#6644]
Im Satz `Das ist ein sher schöner Satz.` wird keine Korrektur für `sher` angeboten.

![Screenshot 2022-05-06 at 10 52 11](https://user-images.githubusercontent.com/520258/167099981-6c89ab1f-c8c8-4bf0-8fe0-b861a01e35ad.png)

**Comment by tiff** [comment]
Ähnlich zu: 
https://github.com/languagetool-org/languagetool/issues/6587
https://github.com/languagetool-org/languagetool/issues/6241

@danielnaber vielleicht können wir hier bald mal was machen

**Comment by tiff** [comment]
@jaumeortola I remember that you fixed something similar in French and/or Spanish? Basically, you added a list of short words that are frequently used? We should have such a list for German. If you add the code for it, I could add the words

**Comment by jaumeortola** [comment]
@tiff Yes. This happens in languages using Hunspell spelling. It was fixed for Portuguese.
For German: https://github.com/languagetool-org/languagetool/pull/6786/files

**Comment by jaumeortola** [comment]
@tiff Done here: https://github.com/languagetool-org/languagetool/commit/d2cf82bd1739cbd444a4948e455ab880816d3fa5
We only need to expand the list of words. We could just take the 200/300 most common words in German. The problems usually appear with short words.

**Comment by tiff** [comment]
Great I will add more words! Thanks!
