### ISSUE TITLE
[ru] russian.dict misses all PT:Past:DST:Neut:.* forms

### ISSUE THREAD

**Issue by ArtemBudnikov** [languagetool-org/languagetool#666]
Hi there,

The new russian.dict file (I downloaded it a couple of days ago) doesn't contain the PT:Past:DST:Neut:.* forms (действительные причастия прошедшего времени в форме среднего рода для любого подежа). There are masculine forms but no neutral ones. 

For example, for this one https://ru.wiktionary.org/wiki/%D1%81%D1%82%D0%B0%D0%B2%D1%88%D0%B8%D0%B9:
1) the file contains ставшим (PT:Past:DST:Masc:T), but no ставшим (PT:Past:DST:Neut:T);
2) similarly, it contains ставшем (PT:Past:DST:Masc:P), but no ставшем (PT:Past:DST:Neut:P). 

In fact, the file does not have a single instance of PT:Past:DST:Neut:.*, but it definitely should. This breaks many rules.

Thanks.

**Comment by danielnaber** [comment]
@yakovru can probably comment on this.

**Comment by yakovru** [comment]
Yes, tags for words with postags PT:Past:DST:Neut:.*  are missing, but it can not break any rules.
Current Russian ruleset is not uses postags like PT:Past:DST:Masc:.* or PT:Past:DST:Neut:.*
It is planned in future releases.
I also plan to rebuild the postag dictionary for LT-3.7

**Comment by yakovru** [comment]
Fixed in https://github.com/languagetool-org/languagetool/commit/d797e89c42fbdc0505365602c343d4d78634c5b2

**Comment by ArtemBudnikov** [comment]
Hi @yakovru 

Now, when you've expanded the tag set for participles, the neutral forms are missing again. russian.dict does not have the following forms: PT:Past:TRANS:PFV:STR:Neut:*

I have a couple of rules that rely on this tag, and, when it's missing, I've got an error. Could you please add them to the dictionary?
