### ISSUE TITLE
[pt] suggestions shows `{suggestion}`

### ISSUE THREAD

**Issue by 3cpt** [languagetool-org/languagetool#6670]
With the sentence: `“mas antes de submeter vou rever tudo novamente.”`, the `"vou rever"` shows the following warn: 

![Screenshot from 2022-05-13 13-03-44](https://user-images.githubusercontent.com/1552965/168332090-f19e8bd1-434e-4d2e-a983-567854d766ad.png)

**Comment by marcoagpinto** [comment]
@jaumeortola 

Another instance of the verbs issue RE + verb?

**Comment by jaumeortola** [comment]
> Another instance of the verbs issue RE + verb?

It seems so. The problem is solved with the new tagger dictionary. 
![imatge](https://user-images.githubusercontent.com/4289501/168379458-5a3f3cdb-3389-45a0-8179-bf2bf678eb0c.png)

The fix will be available online next week.
