### ISSUE TITLE
[Question] Is there an exhaustive doc. for the JSON API?

### ISSUE THREAD

**Issue by jeertmans** [languagetool-org/languagetool#6698]
Hello,
 
Recently, I've been developing [Rust bindings for the LanguageTool API](https://github.com/jeertmans/languagetool-rust), so that I can later use LT's grammar checker within Rust code.
To this end, I based my library on the [LT JSON API](https://languagetool.org/http-api/swagger-ui/#!/) page.

However, I cannot find documentation about output data types, which could become a problem, especially for `[POST] /check`.

My question is therefore the following: **is there some place where I can find the exact types of responses** (fields and data types) that can be returned by your API?
Also, **did this evolve a lot from version to version**? E.g., is the field `sentenceRanges` only present in version greater than X.Y?

Below, you can find some lines of my code where I try to mimic LT's API for the `[POST] /check` request:

https://github.com/jeertmans/languagetool-rust/blob/ecc15eaf4340f5144ace42ef569f043d0c772d05/src/lib/check.rs#L276-L304 

I hope my question is addressed at the right place.

Thanks in advance,

Jérome

**Comment by danielnaber** [comment]
The API is documented at https://languagetool.org/http-api/#!/default/post_check, search "Model" on that page. Anything not documented there shouldn't be relied on and is not stable, anything documented there has been stable for a long time and probably will be stable for quite some time.
