### ISSUE TITLE
detect UTF-8 text files on commandline and in GUI

### ISSUE THREAD

**Issue by milekpl** [languagetool-org/languagetool#67]
In GUI and our commandline interface, we assume the platform's encoding. In Windows, it may not be UTF-8, but UTF-8 files are easy to detect (with BOM or without BOM). Add a simple fix to detect them properly.

**Comment by pminos** [comment]
The committed code adds support for detecting Unicode files with BOM:
- UTF-8
- UTF16 (big and little endian)
- UTF32 (big and little endian)

There is not safe way to detect UTF-8 files without BOM.

**Comment by pminos** [comment]
Closing for now.
