### ISSUE TITLE
LibreOffice: toolbar buttons look very ugly

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6702]
Hello!

Can't the buttons be redesigned to look more professional?

They are terribly ugly.

Thanks!

**Comment by FredKruse** [comment]
I agree, the buttons don't look very professional. Is there anybody at the community who could redesign them? It would be no problem to change the files.

**Comment by FredKruse** [comment]
I had played around with gimp. The icons look like a bit more colibre style. Please take a look of the next nightly tomorrow.

**Comment by marcoagpinto** [comment]
It became very good!

Well done!
