### ISSUE TITLE
[LibreOffice] High RAM/CPU usage

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6704]
Hello!

I was testing the latest nightly.

With my thesis (tested only there), there is a very high RAM/CPU usage.

Look at the screenshot.

Word 365 only takes 200 MB.

The same document opened with LibreOffice was already in 16 GB of RAM and increasing.

I have the latest LibreOffice.
![LibreOffice_extension_CPU_RAM_usage_20220523](https://user-images.githubusercontent.com/5192600/169782309-cbda93f6-3cd3-43d8-94ed-48bc5c13d82b.png)

**Comment by marcoagpinto** [comment]
@FredKruse 

Do you have any idea on how to fix it?

Thanks!

**Comment by dpelle** [comment]
> With my thesis (tested only there), there is a very high RAM/CPU usage.

Is that document available? If not, can you reproduce with a publicly available document?

It should be possible to use a Java heap profiler to see where memory is allocated.

**Comment by marcoagpinto** [comment]
Thank you, @FredKruse

**Comment by FredKruse** [comment]
I think we can close the issue
