### ISSUE TITLE
[pt] Strange correction for 'voz'

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#6719]
In the sentence:

"Eu confio na voz que cada um tem."

LT says it is a confusion with 'vós' and suggests replacing 'voz' with 'vós' but it doesn't make sense.

@marcoagpinto changing it, one day at a time, for the better!

**Comment by marcoagpinto** [comment]
Ahhhh… it seems very easy to fix. Maybe today or at 5am it will be fixed.

Thank you!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I have been working on it.

It is harder than I thought, since some results are inconclusive (depending on what one wants to say, it can be both "voz" and "vós").

**Comment by ricardojosehlima** [comment]
If you wish, send me some examples

**Comment by marcoagpinto** [comment]
Ricardo, for example:
`Ficamos sem voz porque falamos muito.`

By reading it ourselves, we can see the difference, but the computer can't.

Here is the current status of the hits against 600 000 sentences:
[_5.txt](https://github.com/languagetool-org/languagetool/files/8789263/_5.txt)

I am still working on removing false positives.

**Comment by marcoagpinto** [comment]
Another false positive removed:
`Vós dizeis isso num tom de voz que me deixa assustado.`

[_6.txt](https://github.com/languagetool-org/languagetool/files/8789318/_6.txt)

**Comment by ricardojosehlima** [comment]
Ok!

**Comment by marcoagpinto** [comment]
I have just added webcam + webcams to added.txt and spelling.txt which will remove the false positive in the sentence that uses it.

**Comment by marcoagpinto** [comment]
Ricardo,

I have just improved the rule.

It removed:
```
Sou a voz que clama no deserto, pero no soy camelo.
Ficamos sem voz porque falamos muito.
Ficamos sem voz porque falamos muito.
```
(the last sentence appeared twice)

This is the best it can get.

[_7.txt](https://github.com/languagetool-org/languagetool/files/8789454/_7.txt)

```
Portuguese (Portugal): 4 total matches
Portuguese (Portugal): ø0.00 rule matches per sentence
Portuguese (Portugal): 17349 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```

With the webcam postags it will be "3 total matches".

I believe that 3 matches in 600 000 sentences is very good.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Here it is:
https://github.com/languagetool-org/languagetool/commit/ecfa148585578b82f0debd7fb760e84659cae35f

[_0_original_rule.txt](https://github.com/languagetool-org/languagetool/files/8789482/_0_original_rule.txt)

[_7.txt](https://github.com/languagetool-org/languagetool/files/8789484/_7.txt)

**Comment by marcoagpinto** [comment]
By the way, is "webcam" a foreign word in pt-BR?

I need to add it to the list.

**Comment by ricardojosehlima** [comment]
@marcoagpinto no it isn't; follow the rule: when in doubt, it is not a foreign word in pt-BR, we are very relaxed to foreign words, we accept them even in formal registers.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Ahhh… I will add "webcam" only to pt-PT foreign list.

Thank you, Ricardo.

Did you notice that in the "0_" file 100% (or so) are false positives? And in the "_7" file there is no 100% way of finding it they are false or real positives?

This seems to be the best it can get.

**Comment by ricardojosehlima** [comment]
> @ricardojosehlima
> 
> Here it is: [ecfa148](https://github.com/languagetool-org/languagetool/commit/ecfa148585578b82f0debd7fb760e84659cae35f)
> 
> [_0_original_rule.txt](https://github.com/languagetool-org/languagetool/files/8789482/_0_original_rule.txt)
> 
> [_7.txt](https://github.com/languagetool-org/languagetool/files/8789484/_7.txt)

maybe add 'controle/gravador/assistente de' that will probably be voz!?

**Comment by marcoagpinto** [comment]
Well thought!

I will add them at 5am 🙂 

I have closed the folders and editor.

lol 🙂 🙂 🙂

**Comment by marcoagpinto** [comment]
Ahhhhhh... it is fixed:
https://github.com/languagetool-org/languagetool/commit/3f12add291dd5511d7ab717734d714c5fdb134e1

[_8.txt](https://github.com/languagetool-org/languagetool/files/8790052/_8.txt)


```
Portuguese (Portugal): 1 total matches
Portuguese (Portugal): ø0.00 rule matches per sentence
Portuguese (Portugal): 17349 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```
