### ISSUE TITLE
languagetool.org API performance issues

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#672]
A few hundred 503 errors are sent to users every day because text checking takes more than 10 seconds. This bug tracks our work on improving the situation:

- [x] implement caching
- [x] speed up German checking (#670)
- [x] lower overhead for Catalan (#673)
- [x] make Android requests use lt.softcatala.org
- [x] as many texts are very short, write a test to make sure there's not a lot of overhead when checking a very short text (maybe the empty string?) - this test should work on all languages and their variants
- [x] collect the errors found until the timeout so user gets an incomplete result after 10 seconds, but still better than just an error message
- [x] fix the load balancer setup so it depends on the client's IP to make sure the (local) cache is used properly - not possible with Apache, requires nginx -- now solved with `loadfactor=100` and `loadfactor=1` in the Apache configuration, so that one JVM gets (almost) all the requests
- [x] add a warm up after server start for all languages, so performance is more predictable
- [x] switch to a more powerful virtual server
- [x] increase memory (`-Xmx`) from 1350M to 2000M per process

**Comment by jaumeortola** [comment]
Is this problem related just to server load or there is something else we did after the latest release?

In lt.softcatala.org there are some timeout errors now. We could install, for example, the latest released version (3.6) in lt.softcatala.org and see if there are errors or not.

**Comment by danielnaber** [comment]
It's not related to recent changes. Some error have always been there, I just didn't look closely enough at the statistics to notice them. Also, my impression is that it's getting worse, but I cannot point to a specific change that might cause this. On lt.softcatala, the requests with long text don't seem to come from Android, I guess you're using that server now, too?

**Comment by jaumeortola** [comment]
A few requests from Chrome and Google Docs add-ons are mine, yes. I got some timeout errors in Chrome, and this had never happened to me before with the default server. 

In softcatala.org/corrector we have never detected these timeout errors. We run the server with `-Dsun.net.httpserver.maxReqTime=10 -Dsun.net.httpserver.maxRspTime=10` and no server.properties file.

**Comment by danielnaber** [comment]
Catalan has a bit of an overhead per check that can probably be improved. I don't think that's the cause for this issue, but I'll open an issue for that.

**Comment by danielnaber** [comment]
See #673

**Comment by danielnaber** [comment]
This seems to be solved now. The main problem was actually the lack of memory for the JVM.

**Comment by danielnaber** [comment]
Changes after switching to a new server and giving more memory to the JVM:

![performance-api](https://cloud.githubusercontent.com/assets/857004/23744248/c4e448e0-04b3-11e7-9af1-0123b9339fd8.png)
