### ISSUE TITLE
Updates and cannot install

### ISSUE THREAD

**Issue by lagsh** [languagetool-org/languagetool#6727]
I have one version that works and which is 5.5 . 5.5.1 and newer does not work.

my version 
$ libreoffice7.3 --version
LibreOffice 7.3.3.2 d1d0ea68f081ee2800a922cac8f79445e4603348

I user Linux Mint

**Comment by FredKruse** [comment]
This issue seams to be related to issue #6525. 
@lagsh  please do the following tests and answer the questions:

1. Open an empty document. Click on the LanguageTool (LT) Option Button (blue wavy underlined gear wheel). Does the LT option panel appear? (this can take 1 to 3 seconds)
2. Type a short sentence in your default language. Type two blanks between two words. Appears a green wavy line under the two blanks? Which language do you use?
3. If the first two points work, every thing is fine, and we can stop here. When not: Look at ~/.config/LanguageTool/LibreOffice/. There should be a file LanguageTool.log and possibly a file LanguageTool.cfg. Please post them here.
4. In LibreOffice, open the menu point tools/options. In the option window, go to libreoffice/advanced. The checkbox "Use a Java runtime environment" should be enabled. Which version of JRE is selected?

**Comment by FredKruse** [comment]
I think I got the problem:
It seems the automatic grammar check is disabled. Please enable "Check grammar as you type" at "Tools"/"Options"/"Language Settings"/"Writing Aids" and restart LibreOffice/OpenOffice.
If this solves the Problem, close the issue, please.
I added a warning in version 5.8.

**Comment by lagsh** [comment]
I have now deinstalled and removed it by hand from .config/* then reinstalled version 5.7, then restarted and then I could get options open. The option buttons were always there but they did not work. Now they do work. I will close the issue now. I had much trouble deinstalling versions in LibreOffice in the past.
