### ISSUE TITLE
Catalan has overhead per check

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#673]
See `org.languagetool.server.HTTPServerOverheadTest` to reproduce. On my computer, checking the empty string takes about 30ms for Catalan. Reason seems to be the creation of `CatalanSynthesizer` in `SimpleReplaceVerbsRule` and `ReplaceOperationNamesRule`. As the rules get re-created for every check, this could probably be optimized. We already use `synchronized` in `BaseSynthesizer`, so making the synthesizer `static` *might* be enough.

**Comment by jaumeortola** [comment]
I managed to lower the time from 28 ms to 2 ms. Thanks.
