### ISSUE TITLE
[Feature Request] plugin for obsidian (a popular note-taking/PKM app)

### ISSUE THREAD

**Issue by afland** [languagetool-org/languagetool#6731]
Obsidian (obsidian.md for the website) is a growing (and already popular) app for really anything related to knowledge management or even producing content. It's loosely based around the zettelkasten ideology, and is IMO the best out of the growing # of note-taking apps. Bloggers, researchers, etc. use it.
Since there are already hundreds of thousands of users and no grammar checker plugins (only a built-in spell checker), I think LanguageTool would appeal to a lot of obsidian's userbase. 
Obsidian is very plugin based, so it should be realistic to adapt LanguageTool to an obsidian plugin (e.g. https://github.com/obsidianmd/obsidian-sample-plugin)

**Comment by danielnaber** [comment]
Hi, thanks for your feedback. There's already a community-contributed add-on available at https://github.com/Clemens-E/obsidian-languagetool-plugin.

**Comment by afland** [comment]
don't know how I didn't see that, sorry
