### ISSUE TITLE
[pt]: “aceite” instead of “aceito” 

### ISSUE THREAD

**Issue by MarvinErdner** [languagetool-org/languagetool#6739]
> foram aceitos

IRREGULAR_PAST_PARTICIPLES[3]

_foram aceites_

According to this source, “aceito” as particípio is also correct (next to “aceite”). 

https://ciberduvidas.iscte-iul.pt/consultorio/perguntas/os-participios-passados-de-aceitar-novamente/31576

**Comment by marcoagpinto** [comment]
It seems to work here:
![aceite_aceito_20220601](https://user-images.githubusercontent.com/5192600/171387506-dce063e9-9ec0-4c6e-ad0b-1fbbb6d98749.png)

What is the wrong sentence for me to see?

Thanks!

**Comment by jaumeortola** [comment]
This could be the undesired match:
![imatge](https://user-images.githubusercontent.com/4289501/171388689-b8bf88b8-c413-4907-bb15-e386de381d03.png)

Let's see if we need any change in the tagging of these forms.

**Comment by jaumeortola** [comment]
In my opinion, the rule IRREGULAR_PAST_PARTICIPLES[3] should be moved to pt-PT/grammar.xml.
Instead of saying "A forma correta deste particípio é", say "Em Portugal, a forma mais comum deste particípio é..."

**Comment by MarvinErdner** [comment]
The user who mentioned this uses the Brazilian version.

**Comment by marcoagpinto** [comment]
@jaumeortola 

Could you do the commit?

I am too stressed currently and can only do very basic things.

🙂 

Thanks!

**Comment by jaumeortola** [comment]
Done https://github.com/languagetool-org/languagetool/commit/856d90bb39fb44b345792d1b223922b00b0b9b35
