### ISSUE TITLE
[en] “Multi-purpose” suggests "Multipurpose”, which suggests the reverse

### ISSUE THREAD

**Issue by lennartb-** [languagetool-org/languagetool#6747]
Language is en-gb. Sample sentence: "Multipurpose text editors like Notepad++ are great"

![image](https://user-images.githubusercontent.com/5563601/171609218-413761a7-41cc-4c22-993c-f36afe0d685b.png)
![image](https://user-images.githubusercontent.com/5563601/171609284-47f24b65-06b9-401e-8ea1-79cef4e4340a.png)

**Comment by tiff** [comment]
This got recently fixed
