### ISSUE TITLE
Question: Differences between self-hosting and premium languagetool

### ISSUE THREAD

**Issue by AlessioGr** [languagetool-org/languagetool#6750]
Hi there,

I'm self-hosting languagetool with ngrams at the moment and I'm wondering how it differs to the premium languagetool version offered at languagetool.org.

Does latter offer more or better checks than the self-hosted version, or is there a way to tune the self-hosted version to be better?

Does the self-hosted version also offer the style checks? And what does the premium:false in the self-hosted version's log mean?

**Comment by danielnaber** [comment]
The free self-hosted version you can download from https://languagetool.org/download/ lacks all the premium rules (several thousand rules for English, German, French, Spanish and Dutch) and AI-based rules.

The free self-hosted version offers limited style checks. `premium:false` in the log simple means the request wasn't a request from a premium user (it can only be `false` with the free version).

**Comment by tophee** [comment]
Do I need the premium plan to get an api-key to access the api of the self-hosted version?

**Comment by danielnaber** [comment]
@tophee The premium version isn't available as an on-premise version (except for larger business customers). You can use the free version's API as documented at https://dev.languagetool.org/http-server

**Comment by 0xkr4t0s** [comment]
Im not sure why an opensource project would make thisclosed source even when people want to host it locally. It's very "Open"ai like :/

**Comment by working-name** [comment]
> Im not sure why an opensource project would make thisclosed source even when people want to host it locally. It's very "Open"ai like :/

It's the only way they can choke the $25/mo out of you, which is INSANELY expensive for this tool. It's not even attempting to compete with the big bois.

Why would I support languagetool which is actually anti-open source? At that price point I can take ANY, and I mean absolutely any other offering on the market and save big bucks: quillbot, grammarly, heck even Azure AI is cheaper per month.

Such a disappointment.

**Comment by sagittarius-codebase** [comment]
@working-name 
well, that's not completely true!

If you know you want to use it for a longer time than just a month, you can buy the app for cheaper!
The 2-year plan costs about $5 per month. If you are a student, even less: 
[https://languagetool.org/de/premium?coupon=EDUCATION](url)

Hope that helps :)

**Comment by ryanwinter** [comment]
Yeah, I dont think they want you to use the monthly sign-up. That's why the annual price drops to around $5 / month which is reasonable.
