### ISSUE TITLE
[pt-BR] user feedback "Senhor"

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6759]
> Para se referir a Deus como Senhor, deve estar em maiúsculo. O programa acusa que a palavra "Senhor" no meio do texto está errada!

**Comment by marcoagpinto** [comment]
Hello!

Could you please give me the sentence that causes the error?

The sentence written above gives no hits.

Thanks!

**Comment by tiff** [comment]
The user unfortunately didn't provide a sentence
