### ISSUE TITLE
[en] strange spelling suggestions

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6777]
> Peter Grauer is a manager.

What is "dull~ overcast"?

![Bildschirmfoto 2022-06-13 um 19 11 48](https://user-images.githubusercontent.com/37363/173408187-1a9f68f2-40b1-45d2-8f1b-eef8e7d348b8.png)

**Comment by marshinkar** [comment]
error does not occur any longer (OS nor premium). I am closing the ticket.
