### ISSUE TITLE
[de] Falsch positive Fehlermeldung "anfallartig" 

### ISSUE THREAD

**Issue by Wolf-SO** [languagetool-org/languagetool#6780]
Laut Duden ist [*anfallartig*](https://www.duden.de/rechtschreibung/anfallartig) in Ordnung, [anfallsartig](https://www.duden.de/suchen/dudenonline/anfallsartig) hingegen nicht. 
LT Basic 5.2.3 (Browser-Plugin f. Firefox) schlägt (im Kern) folgende Korrekturen vor:
- anfallsartig
- Anfallsartig
- anfallsartige
- anal-artig

Das Fugen-S ruft bei mir den Eindruck einer süddeutschen/österreichischen Färbung hervor.

**Comment by tiff** [comment]
Ich habe `anfallartige`  hinzugefügt. `anfallsartig` wird recht häufig verwendet und hat einen Eintrag bei DWDS, daher habe ich es drin gelassen: https://www.dwds.de/wb/anfallsartig

**Comment by Wolf-SO** [comment]
Ich möchte doch noch einmal den Blick auf das Konstrukt `anal-artig` lenken. Die Nachsilbe *`-artig`* dient dazu, Adjektive zu bilden, und zwar üblicherweise aus Substantiven <sup>[Duden](https://www.duden.de/rechtschreibung/_artig)</sup>. Das Wort *`anal`* ist aber bereits ein Adjektiv <sup>[Duden](https://www.duden.de/rechtschreibung/anal)</sup> (Stamm *`an`*, Adjektivendung *`al`* <sup>[1](https://de.wiktionary.org/wiki/-al), [2](https://www.wortbedeutung.info/-al/) [3](https://www.duden.de/rechtschreibung/_al)</sup>).

Mir ist völlig schleierhaft, wie LT auf dieses Konstrukt kommt. 

Soll ich dafür einen neuen Bug eröffnen?
