### ISSUE TITLE
Access user dictionary

### ISSUE THREAD

**Issue by Wolf-SO** [languagetool-org/languagetool#6781]
I tried to locate the dictionary used by the LT Firefox plugin (ver 5.2.3). Is it stored locally? Is it possible to share between devices?

**Comment by tiff** [comment]
@Wolf-SO it is when you create a free account at https://languagetool.org/register and log in with that account in the settings of the Firefox add-on

**Comment by Wolf-SO** [comment]
Thanks, @tiff, I'll have a look on it soon.
To be honest: this bug report was more of an accident. I actually just wanted to search for “user dictionary” in the open issues, but apparently hit the wrong input line. ;)

**Comment by Wolf-SO** [comment]
Okay, I have now looked at the dictionary. Setting up the account provides a surprisingly meager increase in functionality from my perspective. Unfortunately, you can't export the personal dictionary or import it, in the sense that the words are added to an existing core dictionary. This is a great pity, especially since you have to add all sorts of forms of words, including obvious forms like words on “-ung”. I was actually hoping for a rudimentary form of support for languages with rich morphology (keyword: hunspell).

Translated with www.DeepL.com/Translator (free version)
