### ISSUE TITLE
[pt] Improve disambiguator - 2022-06-16

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6793]
Hello @jaumeortola 

I'm sorry to disturb you:
```
O que o torna perigoso é haver civis inocentes.
O que o deixa perigoso é haver civis inocentes.
```
The verbs are being detected as nouns, “torna” and “deixa” in these examples, which causes false positives.

Could you improve the disambiguator?

Thank you!

**Comment by marcoagpinto** [comment]
```
O que o torna mais perigoso é haver civis inocentes.
O que o deixa mais perigoso é haver civis inocentes.
```

**Comment by jaumeortola** [comment]
Done here: https://github.com/languagetool-org/languagetool/commit/87f9a1bb770391cd3193652d45ae4552baa0570c
Please let me know if there are other similar problems, and I will try to create more general disambiguation rules.

**Comment by marcoagpinto** [comment]
@jaumeortola 

Thank you!

<3 <3 <3 <3

**Comment by jaumeortola** [comment]
More incorrect disambiguations:

Quem o ensina francês?
Vejo que isso o deixa aflito.
Você o acha parecido com o pai?

**Comment by jaumeortola** [comment]
More improvements: https://github.com/languagetool-org/languagetool/commit/6c7cddf3809afa8df7c41f668e8c4d00ff25e353
