### ISSUE TITLE
LT does not seem to work with the "new" Overleaf editor

### ISSUE THREAD

**Issue by lennartb-** [languagetool-org/languagetool#6808]
Overleaf recently enabled the use of a new source editor:
![image](https://user-images.githubusercontent.com/5563601/174429185-b76fc390-020c-46ac-9037-3b09be262777.png)

LT doesn't seem to work in this new editor at all, there is no indicator at the bottom right of the editor, and no issues are displayed in the text. When switching to the "legacy" editor (as in the picture), LT works again as usual.

I'm using Firefox 101.0.1 (64-bit), same issue in Chrome 102.0.5005.115.

If this isn't a problem with LT, I'll report it on Overleaf instead.

**Comment by danielnaber** [comment]
It's a known issue with our add-on, but I cannot tell when it will be fixed.

**Comment by lennartb-** [comment]
Was there a recent update to the browser add-on? It seems to work now.

**Comment by danielnaber** [comment]
> Was there a recent update to the browser add-on? It seems to work now.

Yes, it should (mostly) work with the latest update. I'll keep this issue open until we know support is stable.

**Comment by tiff** [comment]
Closing. Please create separate issues if you discover any problems.
