### ISSUE TITLE
Unticking/ticking a rule checkbox in the options makes always untick

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#682]
I was trying to disable a pt_PT rule, but the checkbox is always unticked, no matter what I do, and it is always used like it was ticked.

See the forum post relating it:
http://forum.languagetool.org/t/pt-portuguese-rule-contribution-discussion/1399/23

Windows 10, LibreOffice 5.3.0.3.

**Comment by MikeUnwalla** [comment]
@marcoagpinto , this is a similar problem to https://github.com/languagetool-org/languagetool/issues/421.

With LT snapshot 2017-02-10, for the category 'Plain English', when all rules are selected, the checkbox is unticked, as shown on https://cloud.githubusercontent.com/assets/5816160/17830345/d28dc9f8-66c0-11e6-9210-734503c1cb63.png.

**Comment by TiagoSantos81** [comment]
At least in Linux Mint 18.1 and  LibreOffice 5.3.0.3. the rules are activated and deactivated as expected. Plain English category in the English version also works as expected. 

@marcoagpinto 
Note that you have two sets of rules. The months and cardinal points capitalization rules for post-AO also need to be deactivated in the Capitalization category. 
I may improve usability by creating a new category and moving those rules. Added to the TODO list.

**Comment by TiagoSantos81** [comment]
Since the visual feedback problem is already reported on #421, but the misunderstanding is solved as discussed in the forum, I will close this issue. 
New categories separating AO45 and AO90 will be available on 3.7 and they will be pushed soon.
Please, reopen this if there is any extra issue not discussed in the previous bug report.
