### ISSUE TITLE
Installation problems in LibreOffice 5.2 and Oracle openjdk 8

### ISSUE THREAD

**Issue by cmencar** [languagetool-org/languagetool#683]
I am trying to install LanguageTools 3.6 as LibreOffice extension (LanguageTool-3.6.oxt, downloaded on 15th March 2017). Installed Libreoffice is 

Version: 5.2.2.2
Build ID: 1:5.2.2-0ubuntu2
OS Version: Linux 4.8;

The running JRE  (as seen on Tools/Options/Advanced) is: **Oracle Corporation 1.8.0_121** (java-8-openjdk-amd64)

Installation fails with the following exception:

`(com.sun.star.uno.RuntimeException) { { Message = "[jni_uno bridge error] UNO calling Java method writeRegistryInfo: non-UNO exception occurred: java.lang.NoClassDefFoundError: com/sun/star/task/XJobExecutor\X000ajava stack trace:\X000ajava.lang.NoClassDefFoundError: com/sun/star/task/XJobExecutor\X000a\X0009at java.lang.ClassLoader.defineClass1(Native Method)\X000a\X0009at java.lang.ClassLoader.defineClass(ClassLoader.java:763)\X000a\X0009at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)\X000a\X0009at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)\X000a\X0009at java.net.URLClassLoader.access$100(URLClassLoader.java:73)\X000a\X0009at java.net.URLClassLoader$1.run(URLClassLoader.java:368)\X000a\X0009at java.net.URLClassLoader$1.run(URLClassLoader.java:362)\X000a\X0009at java.security.AccessController.doPrivileged(Native Method)\X000a\X0009at java.net.URLClassLoader.findClass(URLClassLoader.java:361)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:424)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:411)\X000a\X0009at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:357)\X000a\X0009at com.sun.star.comp.loader.RegistrationClassFinder.find(RegistrationClassFinder.java:53)\X000a\X0009at com.sun.star.comp.loader.JavaLoader.writeRegistryInfo(JavaLoader.java:376)\X000aCaused by: java.lang.ClassNotFoundException: com.sun.star.task.XJobExecutor\X000a\X0009at java.net.URLClassLoader.findClass(URLClassLoader.java:381)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:424)\X000a\X0009at java.lang.ClassLoader.loadClass(ClassLoader.java:357)\X000a\X0009... 15 more\X000a", Context = (com.sun.star.uno.XInterface) @0 } }`

Any hints? Thanks in advance.

**Comment by arysin** [comment]
Looks like you need to install libreoffice-java-common or openoffice.org-java-common package, see 
https://www.languagetool.org/issues/
and 
http://askubuntu.com/questions/595286/installation-of-libreoffice-extention-of-language-tool-is-error

**Comment by cmencar** [comment]
It works now, thank you very much. Perhaps it is better to specify this passage in the installation guide.

**Comment by laspic** [comment]
If _libreoffice-java-common_ is already installed, and if it still doesn't work, try : 

> Go to LibreOffice Options menu, choose Advanced and be sure Use Java runtime environment is checked **and a Java version is selected**.

(source : https://askubuntu.com/questions/458240/unable-to-install-languagetool-2-5-extension-for-libreoffice-4-2-on-ubuntu-14-04)
