### ISSUE TITLE
Northrup Grumman -> Northrop Grumman (u -> o)

### ISSUE THREAD

**Issue by Tex2002ans** [languagetool-org/languagetool#6832]
This was a typo I found using Google Docs:

- [ ]  **Northrup** Grumman

According to a Google Search:

- 'o' has ~12 million hits
- 'u' has ~180k hits

(~1.5% are typos.)

See [Wikipedia.org: "Northrop Grumman"](https://en.wikipedia.org/wiki/Northrop_Grumman) for official spelling.

- - -

The company name already exists in:

- `spelling_global.txt`
- `specific_case.txt`

If someone could just lead me to which exact file is needed, I can create a Pull Request.

**Comment by tiff** [comment]
Some words that look like proper nouns are ignored by the spell checker. You can add such simple replacements to the `replace.txt`, see my change:
https://github.com/languagetool-org/languagetool/commit/280b8cc56d74d365618a0ec2f3c3f1e611f5874e#diff-0951835863179a90707bf737ac3262f8ffa568033162514a2577f38ccc964119R76

**Comment by Tex2002ans** [comment]
> Some words that look like proper nouns are ignored by the spell checker. You can add such simple replacements to the `replace.txt`

Yes! That's the file.

Before submitting, I stumbled upon `diacritics.txt`... and I knew that proper nouns file was lurking there somewhere!

I'll have to refresh my memory on the LT files again before submitting the next batch of corrections.

Thanks for the info + fix.
