### ISSUE TITLE
LT 5.7 in LO 7.3 runtime exception Java null ptr

### ISSUE THREAD

**Issue by BloomingAzaleas** [languagetool-org/languagetool#6861]
Cointext:
Version: 7.3.4.2 (x64) / LibreOffice Community
Build ID: 728fec16bd5f605073805c3c9e7c4212a0120dc5
CPU threads: 8; OS: Windows 10.0 Build 19044; UI render: Skia/Raster; VCL: win
Locale: en-US (en_US); UI: en-US
Calc: CL

LT error msg screenshot.
![2022-07-01-LT-null-ptr-msg](https://user-images.githubusercontent.com/31942133/176965529-684e9598-c4d4-45d8-92ea-d4b09e8e35d6.JPG)

**Comment by Tex2002ans** [comment]
Try to upgrade to the latest LanguageTool 5.7 and see if that solves your problem.

**Comment by BloomingAzaleas** [comment]
Updated to LT 5.7.
2 screenshots need for the stack trace this time.
![2022-07-02-LT-null-ptr-msg-1](https://user-images.githubusercontent.com/31942133/177005226-b1014284-bab1-40fa-b258-592008ec6446.JPG)
![2022-07-02-LT-null-ptr-msg-2](https://user-images.githubusercontent.com/31942133/177005231-de85af38-32ed-4b7a-93b5-e99529754909.JPG)

**Comment by BloomingAzaleas** [comment]
I now recall I previously updated LT 5.6 --> LT 5.7 then dropped back to LT 5.6. While LT 5.6 still throws exceptions, they were a lot less frequent than LT 5.7.

**Comment by FredKruse** [comment]
Could you please give me an example sentences where the bug happens?

**Comment by BloomingAzaleas** [comment]
The LT 5.7 stack-trace screenshot above was for sentence (part of which is seen in the trace output screenshot):
![2022-07-05-LT-bug-6861-example-sentence](https://user-images.githubusercontent.com/31942133/177359937-e96dec51-44d9-4d38-bf7c-de49c58a7d07.JPG)

I have to show the example as a screenshot since it contains typographical elements that do not translate to this GitHub text format. I have encountered multiple LT 5.7 error traces since the above report but have not collected them due to frequency. If memory serves in many cases I was constructng hypenated expressions or otherwise fiddling with punctuation or non-letter typographical elements at the time. I will attempt to report additional examples when they occur now.

Regards.

**Comment by Tex2002ans** [comment]
> I have to show the example as a screenshot since it contains typographical elements that do not translate to this GitHub text format.

Can you create/attach a basic ODT document with the problem in it?

> An ST capture problem here is, at least on Win 10, is that Java throws up a potentially huge window much larger than the display size. Makes it difficult and fiddly to capture the ST in multiple screenshots.

What about `Alt+Print Screen`?

That creates a screenshot of the active window.

(I never tested it on a longer-than-the-monitor window though.)

You should be able to then paste it into whatever image program of choice.

**Comment by BloomingAzaleas** [comment]
ODT example doc prepared for the proximate text showing in the long stacktrace already reported.
[LT-bug-6861-ODT-example.odt](https://github.com/languagetool-org/languagetool/files/9049431/LT-bug-6861-ODT-example.odt)

Regards screenshots, I have been using the old MS Win tool 'Snipping Tool' which has both a rectangular snip and a window cap function. I have 3 displays logically arranged as 2 across upper level and 1 lower level "in the middle" with the Win destop extended across all. All screencap functions (Windows, *nix, whatever) work the same -- an API to grab a copy of some or all of a kernel display buffer. Apps call for their full graphical objects to be rendered but the window manager will not bother processing those pixels outside the hardware display or logical window borders for obvious perf reasons. Thus a logical window cap does not behave as one could hope -- what parts of the ST window that are outside any display border are also not present in any kernel display buffer for capture, so those parts capture as blank black.  The Java ST window is larger than all 3 of my displays combined, so I have to move it around and capture slightly overlapping sub-rectangles. Many sub-rectangles over a large 2D canvas (checkerboard style caps) to be tracked to their relative 2-coordinate position in the entire ST window image for later crop and stitch together as images by you or me. I have GIMP so the tech of the image stitching is not the issue. Thus the request for any available text dump function for the ST.

A plan B for the ST window would be if its width could limited or dynamically adjusted, with the text wrapping. This would reduce the checkerboard win caps challenge to a series of vertically linear caps as the ST window is moved through a display in a simple vertical manner. The resulting image files no longer need an associated 2D coordinate for stitching work.

Regards.

**Comment by Tex2002ans** [comment]
> I was not aware of LT 5.8. In any case, the LO extension version of LT 5.8 has not made it to the LO Extensions site yet.

You can grab the OXT straight from:

https://languagetool.org/download/

> ODT example doc prepared for the proximate text showing in the long stacktrace already reported. [LT-bug-6861-ODT-example.odt](https://github.com/languagetool-org/languagetool/files/9049431/LT-bug-6861-ODT-example.odt)

Thanks. I tested on my end:

- LanguageTool 5.8 (2022-07-02 14:50:13 +0000, 82e790a)

and:

```
Version: 7.3.4.2 (x64) / LibreOffice Community
Build ID: 728fec16bd5f605073805c3c9e7c4212a0120dc5
CPU threads: 8; OS: Windows 10.0 Build 19044; UI render: Skia/Raster; VCL: win
Locale: en-US (en_US); UI: en-US
Calc: threaded
```

Mine does not crash like yours, but it does just hang if I:

1) Open your test document.
2) Press **Check Text (F7)**.
3) Press "Ignore" button (to skip the "stacktrace" spelling error).

Then LT's window just sits there.

There's no excessive CPU usage or anything.

LT is stuck on the screen at "Result 100%".

Only way to get out is to close out of LibreOffice.

- - -

> Regards screenshots, [...] Thus a logical window cap [...] parts capture as blank black.

Ahh, thanks for letting me know.

> A plan B for the ST window would be if its width could limited or dynamically adjusted, with the text wrapping.

I know the standalone LT leaves an error log file every time it crashes.

Maybe the LO extension does similar.

(A dev will probably pop in and explain.)

**Comment by BloomingAzaleas** [comment]
Well, that horizontal rule case was the most identifiable textual 'geographic' location is the large doc corpus I have been working. LT does fail elsewhere, again typically while I am fiddling with hyphenation or other typograhical objects that are not letters-digits text. See there? I just created non-dictionary, one-time, special purpose hyphenated terms. I will now attempt to identify the proximate text if not also capture the entire stacktrace when it happens again. 

Having said that, if the symptom is a stall rather than stackdump, then I do not have a good way to know exactly on which text LT is stalling and no stackdump for hints. I have background processing enabled. Should I disable that?

Will try the LT 5.8 LO extension.

Regards.

**Comment by FredKruse** [comment]
@BloomingAzaleas Are you really sure, that the 2 screenshots are from LT 5.7? It seems, they show a bug from LT 5.6, fixed in LT 5.7.
@Tex2002ans I have tried to reproduce your experience with the example LT-bug-6861-ODT-example.odt. It works fine for me. No hanging. The horizontal line is no text and is ignored from LT, as it should be.

By the way, the background processing should be enabled. It marks the grammar errors (note: spelling errors are detected by the internal LO spell checker).
The hanging is a more complicate problem, strongly related to issue #6866. It will take some work and time to analyze it.

Please work with LT 5.8 and add the trace stacks here, if bugs appears.

**Comment by BloomingAzaleas** [comment]
@FredKruse Of the 2 screenshots posted in the  prior comment [https://github.com/languagetool-org/languagetool/issues/6861#issuecomment-1172909596](url), one is T-shaped (the top of the stacktrace, lower corners blank black because not in a frame buffer for cap in my T-shaped display arrangement), the other is not (lowest part of the trace). Look closely at the T-shaped top-of-trace screenshot image, first line. For example, with Firefox I can left-click that image on the GitHub webpage, "Open image in new tab," then use FF to zoom in on the image via CNTRL-mouse_wheel. That first line seems standard and lists the LT version (5.7) and a timestamp. I presume the timestamp (in this case from 28 Mar, 2022) is related to the build time. So whatever 5.6 bug you are referring to, uhmmmm... maybe not fixed in 5.7.

I am now running 5.8. No dumps yet, but I do get anomolous behavior, at least different from 5.6. I occasionaly get a bogus "100% complete" claim, perhaps that mentioned by @Tex2002ans, but different from theirs in that I can Close out of the LT GUI pane in the expected way then re-start a Check Text. Don't get me started on how small font and small window that LT scanning GUI pane is. The LT 5.8 scanning pane Edit window looses sync with the text showing in the LO doc window because for any change not a selection from the LT suggestion list, I tend to type in the LO doc windows because it is difficult to see and correctly position the cursor in the small font of the LT Edit window, especially when fiddling punctuation such as quotes, commas, periods, etc. While the LT scanning pane can be corner-drag enlarged, the text windows remain a stubbornly fixed, small size. LT 5.6 was good about re-synching to LO when you told it to scan again, LT 5.8 not. The LT 5.8 work-around is to manually Refresh Check Results with every typed edit in the LO windows, which apparently forces a sync. However, consistent with 5.6, 5.8 does not assure that the particular complaint in the Complaint Window is actually in view in the Edit window (nor in the LT window), so the Edit window has to be manually scrolled.

Whanker, whanker.

Regards.

**Comment by FredKruse** [comment]
The "hanging problems" should be solved (see also issue #6866). You could test it with the tomorrow nightly snapshot (developer version) at https://internal1.languagetool.org/snapshots/
At next, I have to look after the synchronization problems between edit document and  check dialog.

**Comment by BloomingAzaleas** [comment]
@FredKruse "tomorrow," as in the 7 July snapshot? 8 July snapshot? Which? Also, it would be helpful if the LT version number showed somewhere in its GUI panes so that if I screencap the LT GUI in support of a bug report it self-docs right in the image. Got a null ptr exception with the official 5.8 LO extension version I have installed now but I will wait on the snapshot you want me to try. Maybe that exception will go away.

Regards.

**Comment by FredKruse** [comment]
@BloomingAzaleas Some code was changed for the check dialog, now. Please test the snapshot 20220710. You have to wait till 10. July.
Regards

**Comment by FredKruse** [comment]
The last problem should be solved. There were some changes at the check dialog. Please test it with the next nightly tomorrow (20220714).

**Comment by BloomingAzaleas** [comment]
Various Java null pointer and array indexing errors in the context of LO Writer seem to have been cleared in to the LT 5.9 snapshots of early Aug 2022 during the work on #6928.
