### ISSUE TITLE
[de] cycle of contradictory improvement suggestions

### ISSUE THREAD

**Issue by Wolf-SO** [languagetool-org/languagetool#6867]
In the following use case, LT “cycles” between suggesting `löschen,` and `löschen`:

> Folglich lassen sie sich weder löschen, noch aktualisieren.

vs

> Folglich lassen sie sich weder löschen noch aktualisieren.

I'm using the version-5.3.0 Firefox plugin under Windows.

**Comment by tiff** [comment]
Behoben, sollte in den nächsten Tagen deployt sein
