### ISSUE TITLE
LO extension enhancement - show LT ON/OFF state

### ISSUE THREAD

**Issue by BloomingAzaleas** [languagetool-org/languagetool#6889]
Version: 7.3.4.2 (x64) / LibreOffice Community
Build ID: 728fec16bd5f605073805c3c9e7c4212a0120dc5
CPU threads: 8; OS: Windows 10.0 Build 19044; UI render: Skia/Raster; VCL: win
Locale: en-US (en_US); UI: en-US
Calc: CL
LanguageTool 5.8 (2022-07-02 14:50:13 +0000, 82e790a)

The LO Tools->Language Tool brings up a menu listing 7 options, of which one is "Switch Off/On". In working with the LT dev team and attempting some testing for LT bug 6861 which included the possibility of hangs, I was mashing the LO Toolbar buttons for LT of Check Text and Recheck Document and got no response from LT. Whelp, LT is hanging again. Then I happened to select the Refresh Check Results and only then did I get a popup indicating that LT was switched OFF.

A) LT will get blamed for hanging when it is just switched OFF. So EVERY "do something with the text" action button should popup LT IS OFF if indeed it is OFF.

B) While the LO Tools->Language Tool menu provides an OFF/ON toggle selection, it DOES NOT INDICATE THE CURRENT STATE. The user has to guess by further poking at LT if it is ON or OFF, but then the user cannot distinguish between OFF (legit) and a HANG condition.

Please update the LO interface  such that a user does not have to guess the OFF/ON state of the LT extension and from that distinguish OFF from hung state.

Regards.

**Comment by FredKruse** [comment]
At first, a hint: It was a bug, that the check dialog doesn't run, when LT is switched off. This is fixed in version 5.9 (snapshot).
The LT menu is generated dynamically. But only a static menu can be used, if the application starts. The static menu is displayed, if you run an empty document. It can't be changed for an empty document because of a LO bug, which causes LO to crash under Linux, if you try to change the menu by LT (see #6412).
So, if you open an empty document, the menu item is called "switch on/off". If you add a word or open a not empty document, the item changes to "switch off" (This is mistakable, I changed it to "switched off"; see snapshot tomorrow). This item is a check item. If LT is switched off, the item is marked. I changed the code a bit. So, the information should be more reliable.
Please test it with tomorrow's snapshot 20220714

**Comment by BloomingAzaleas** [comment]
Will test. Took a look at #6412 then Doc Foundation [https://bugs.documentfoundation.org/show_bug.cgi?id=147668](url). GTK3 DESTROY methods not getting time to complete or something during rapid doc open/close sequences. Looks like the LO dynamic menu fix will not be public until LO 7.4.0.
Yes, the point of a GUI is visible response to *all* user input. The user psychology is then if a GUI object (i.e., all LT buttons) does not respond in some way, even if to say 'Please turn me on in the menu' then something (in this case LT) is broken/hung even when fundamentally operating as intended behind the curtains.

**Comment by FredKruse** [comment]
I think, there is a misunderstanding. Maybe the problem is the wording of the menu item.
"Switch off" means, the check in the background is switched off. No marks are set into the text. This feature was integrated because some user working on huge documents got problems with the high CPU load, while the process is running in the background. The idea is that users can work and do the check "manually" by starting the check dialog.
So, all functions you mentioned have to work even when the "Switch off" was enabled.
 We should find a better, less misunderstanding wording. What do think of "No background check"?

**Comment by BloomingAzaleas** [comment]
Yes, when I was testing on v5.8 and got that popup of LT IS OFF, I interpreted the compination scope of the popup text + the menu text to mean that except for Options all LT functions were disabled. Why? Because no doc of what that menu choice meant.

I am testing with LT 5.9 20220714 snap now.

Yes, choice of English word phrase very important. So, in my you-should-know-my-verbose-ways-by-now way, there are (at least) two user-facing pieces of information we can choose to display via the menu-choice item:

A) The current operating mode or state of LT regards background_processing enabled or disabled.

B) What happens next if I select this menu choice?

However, until there is adequate doc on the LT Website regards all elements of the GUI, what they mean, etc. then we have a third burden of indicating the concept of or scope of the feature(s) affected by this menu item. All in 1 -- 3 English words.

AND, this menu choice phrasing should be coordinated with the phrasing of the Options->General->background_processing (assuming that Options choice is kept in that tab) so that they all mean the same thing for the user. But we can also take advantage of the fact that Options->General has graphical room for more words compared to the menu.

First, the current phrase in Options->General is "No check of text in the background" which is awkward to understand because it conveys the concept of enabling or disabling a NEGATIVE, a "_No_ check." In linguistic analogy, on exiting a conference room, does one Disable Lights using the little thingy by the door? Or does one Enable No Lights?

A first candidate for Options->General is then "Enable background text checking." I think the average user should be able to understand that check the box next to "Enable background text checking." and you get... background check enabled. Un-check that box and background check is no longer enabled. In English, the adjectives "enabled" and "disabled" (verbs "enable," "disable") convey a binary-choice, toggle-pair meaning. Using the word "enabled" implies the only other choice is "disabled." Notice I used the words "text" and "check" as user-assist concept callbacks to those same words in the LT menu and toolbar action buttons tooltips.

So now the the menu item:

A dynamic menu approach uses alternating text values in the same menu slot based on the current enabled state of background_check:
"Enable background text check" via the toggle-pairing implies the current state of background_check is DISABLED. It tells me what happens next: selecting this menu item ENABLES background_check.
"Disable background text check" via the toggle-pairing implies the current state of background_check is ENABLED.  It tells me what happens next: selecting this menu item DISABLES background_check.
A wording alternative could be "background text check" --> "background check" (saves 5 chars) and hope that is a callback for the user to the longer phrasing in Options->General.

A static menu text approach:
"Background text check" with either a grayed-out checked box to indicate DISABLED or a normal-color checked-box to indicate ENABLED.

Important: Note the LT 5.9 20220714 snap implementation of menu item "Switched Off" does not follow the grayed-out icon to-the-left convention. It is the presence of that grayed-out icon which visually clues the user that this likely is a toggle item. Without that, I'm completely guessing when I poke at it. Worse, since for this feature there is no immediate GUI feedback (its background!) I have no idea if anything changed or if this LT menu item is just broken.

Regards.

**Comment by BloomingAzaleas** [comment]
Will do.

Side-note regards context-dependent removal or addition of menu slots -- that is counter to long industry practice and thus trained-user psychology. Industry practice is to gray-out menu slot text if that menu choice is not applicable in a given context, not remove it. Why? Because users operate mostly by muscle-memory when navigating menu trees. When you remove or add a slot, you have changed the pick-list slot count and thus vertical pixel length since the user memorized that menu and now the user makes mis-picks on next menu visit. The old muscle-memory fails and the user gets annoyed, especially at having to learn it again. Then the menu changes again. You can see an extensive example of hard-learned industry good practice in the LO menus -- many, many grayed-out menu entries when they are not applicable.

Regards.

**Comment by BloomingAzaleas** [comment]
Main menu issue addressed with updated English menu word-phrasing in LT 5.9 snapshots late July 2022. However, as of snapshot 20220728, the description phrase for the LT Options->General pane checkbox item of this same functionality ("No check of...") is not yet coordinated with the menu phrasing as suggested in comment [https://github.com/languagetool-org/languagetool/issues/6889#issuecomment-1186634219 ](url). This LT Options item has space for more words but should use similar phrasing so that this Option item and the menu item mean the same thing to a user and act as memonic callbacks to each other.

Base on the current phrasing of "No check of text in the background," I suggest a revised phrasing of 
"Disable background-processing check of text." This of course implies that background processing ENABLED is the default.

Regards.

**Comment by FredKruse** [comment]
@danielnaber Does the translation application recognize changes in text of a known MessageBundle.properties label?

**Comment by danielnaber** [comment]
If the English text changes, translators will see the item needs to be "verified"

**Comment by FredKruse** [comment]
The label of the checkbox item was changed, see tomorrow nightly 20220730

**Comment by BloomingAzaleas** [comment]
This enhancement has been accomplished by re-wording of the English phrase choice in the LO Writer Tools->Language Tool menu slot for the background text processing mode, coordinated with English wording of the same function choice in the LT Options->General tab.
