### ISSUE TITLE
LO extension enhancement - show LT version in LT GUI panes

### ISSUE THREAD

**Issue by BloomingAzaleas** [languagetool-org/languagetool#6891]
Screen caps of the LT Edit pane (and others) are a key, quick way for LT bug reports to show the complex data. Alas, the LT GUI panes are not self-documenting regards the LT version in use. Reporters have to go through separate path to get to the LT "About" info, increasing the work effort for initial bug reports, especially reports on language issues.

Regards.

**Comment by FredKruse** [comment]
I'm not really sure, if this is a good idea. Many users may be confused about this information at every GUI element. I just added all relevant information to the "About pane". I think, this is the right place. Furthermore, the information is documented in the log file now. It can easily be copied and pasted into a bug report.

**Comment by BloomingAzaleas** [comment]
Hmmm... just to be sure, I see I did not give enough detail in correct terms. No, not "every GUI element" which to me suggests every button or something. I meant exactly one place per _window_ -- the title bar, which already carries the LT logo on the left, then the LT function title (LanguageTool something), then the 'X' icon on the right to quit the window. This addresses your user psychology concern as the title bar _already_ carries some identifcation information. I'm just proposing to add a short version ID string meaningful for the dev team in the middle: "LanguageTool function_title" --> "LanguageTool v5.9 function_title".

And why window title? Because many screencap tools offer a window capture mode that makes for an easy copy-paste directly to GitHub for an issue report.

Here is an example from another desktop app I use:
![image](https://user-images.githubusercontent.com/31942133/179426108-e8c64970-e5e8-4a1c-bbbf-c4c2bdcef9d3.png)

I bet you can guess which version of the app I am using. 

Regards the LT "About" window. Take a look at the LO Help->About feature. Notice the Copy_to_Clipboard button to the right of 'Version Information' in the middle of the window. I click that button and easy-peasy paste directly here:

Version: 7.3.4.2 (x64) / LibreOffice Community
Build ID: 728fec16bd5f605073805c3c9e7c4212a0120dc5
CPU threads: 8; OS: Windows 10.0 Build 19044; UI render: Skia/Raster; VCL: win
Locale: en-US (en_US); UI: en-US
Calc: CL

Very basic info but covers details of the LO edtion and build version, the host hardware, the host OS, locale, some graphics sub-system details, other miscellaneous. Makes it easy for users to provide this context info.

Regards.

**Comment by FredKruse** [comment]
I added the LT version number to the LT check dialog and the option panel. If it is an official version, only the version number is displayed. If it is a snapshot, the whole version information (build date etc.) is displayed.

**Comment by BloomingAzaleas** [comment]
Accomplished as of LanguageTool-20220916-snapshot.oxt.
