### ISSUE TITLE
[pt] Improving disambiguator "_QUOT" - 2022-07-09

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6892]
Hello @jaumeortola 

I'm sorry to bother you.

Could you improve the disambiguator to accept all of these as _QUOT?:
`'‘'’`
It works with all characters except the last one.

Context:
```
          <token regexp='yes'>['‘]</token>
          <token regexp='yes' spacebefore='no'>(?:&barbarismos;|&barbarismos2;|&barbarismos3;)s?</token>
          <token regexp='yes' spacebefore='no'>['’]</token>

        <suggestion>‘\1’</suggestion>
        <suggestion>“\1”</suggestion>


```

I want to replace all rules to use "_QUOT" instead of having all possibilities in regexps.

Thank you!

**Comment by jaumeortola** [comment]
The only missing one is the single closing quotation mark (’). I have added it to the disambiguation rule.

**Comment by jaumeortola** [comment]
https://github.com/languagetool-org/languagetool/commit/0ea247ad3c0d8bb3691d5b8598fae1769ce7358c
