### ISSUE TITLE
[pt-PT] Lower priority of rule over other rules

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6894]
Hello @jaumeortola 

I have been analysing the nightly results.

The rule BARBARISMS_PT_PT_V2 in the pt-PT grammar.xml removes hits from other rules, such as checking if a sentence starts with uppercase, if a sentence ends with punctuation, etc.

Is it possible for you to lower the priority of this rule?

Thanks!

**Comment by jaumeortola** [comment]
I did this: https://github.com/languagetool-org/languagetool/commit/c2c2047066c888ffbb97eadf61f85eb77b1c1846
Check if the results are what you expected.
