### ISSUE TITLE
How to start the desktop version?

### ISSUE THREAD

**Issue by eemantsal** [languagetool-org/languagetool#690]
Sorry for the probably silly question, but how can I use Languagetool desktop?
I've installed it, but I see no changes in my desktop's orthography options. I try to run java -jar languagetool-commandline.jar in case it does something but I only get:
`Error: Unable to access jarfile languagetool-commandline.jar`

`languagetool-gui` is the only command that seems to work, although it takes a lot to start; after entering it, 30 seconds later a 1995-like graphic interfaced control panel appears and I set the options I want. But I on't really know if it serves for anything since LT seems not to be functioning. There's no menu entry or whatever is added to the usual spell checking menues or options., nor an entry in my applications menu.

I guess I'm missing something, right? I'm running all those CLI commands as normal user, perhaps should I do it as root?

I have app-text/languagetool-3.5-r1 on virtual/jre-1.8.0-r1 and all the dependencies have been correctly (I think) satisfied during installation, so I don't know where else to look at. :-/

Thx.

**Comment by danielnaber** [comment]
> There's no menu entry or whatever is added to the usual spell checking menues or options.

Well, the stand-alone version offers no integration. It's just a window where you can paste text and check it. For integrations, please see http://wiki.languagetool.org/software-that-supports-languagetool-as-a-plug-in-or-add-on
