### ISSUE TITLE
[LibreOffice add-on] Add Ricardo Joseh Lima to "About window"

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6904]
Hello @FredKruse @danielnaber 

Could “Ricardo Joseh Lima” ( @ricardojosehlima ) also be added to the credits list in the “about window” of the LibreOffice add-on?

For months that he has been helping with the rules.

He suggested tons of fixes, rules ideas, rules checking, etc.

Thank you!

**Comment by FredKruse** [comment]
@marcoagpinto 
While 'cleaning up' I came across this issue. Is this point still relevant?
@danielnaber 
This is not a LO extension problem, but must be generally registered in the supporters. The extension window only shows the general supporters.

**Comment by danielnaber** [comment]
The method is called `getMaintainers()`, so it's meant to list maintainers (not contributors). I will add Ricardo to https://languagetool.org/dev under "Contributors", though.
