### ISSUE TITLE
Sorry, LanguageTool extension could not find error context in text

### ISSUE THREAD

**Issue by promeneur** [languagetool-org/languagetool#691]
If I post at www.voyageforum.com
then
I use LT to check my post then when I click in “Bonne” to replace “bonne” for example
then
“bonne” is not replaced by “Bonne”
and
I get an error message:
Sorry, LanguageTool extension could not find error context in text

**Comment by danielnaber** [comment]
Thanks for the report, could you post it at https://github.com/languagetool-org/languagetool-browser-addon/issues?
