### ISSUE TITLE
[LibreOffice add-on] Adding official logo to about window or other places (settings)

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6912]
@FredKruse 

Hello!

The “i” image looks awful in the “about window”.

Is there anyway you could use the official LT logo?

I downloaded the logo in SVG from:
https://commons.wikimedia.org/wiki/File:LanguageTool_Logo_(2018).svg

![LanguageTool_Logo_(2018)](https://user-images.githubusercontent.com/5192600/178930296-c50a9a10-eb0b-46f7-8fb1-5dc06a27d030.svg)

Thanks!

**Comment by marcoagpinto** [comment]
@FredKruse 

Look at this possibility:

![LO_extension_idea_20220714](https://user-images.githubusercontent.com/5192600/178949572-a6434b4b-d6b0-4988-beae-144cc386448a.png)

**Comment by FredKruse** [comment]
The logo was added.

**Comment by marcoagpinto** [comment]
Thank you, Fred!

Sorry, if sometimes I look too aggressive when I write.

My mind is always bursting with ideas, I can't keep quiet.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
Tested!

Thanks!
