### ISSUE TITLE
Ability to sync personal dictionary with chosen location

### ISSUE THREAD

**Issue by olantrust** [languagetool-org/languagetool#692]
Having LanguageTool operate on numerous devices and apps is great.

However, it also requires a separate personal dictionary input for instance.

In preferences, User should be able to propose a location (whether a URL, or a shared local file), which 

LanguageTool would use to store/sync the personal dictionary.

This would enable multiple instances of LanguageTool to utilise the same tailored personal dictionary, by selecting the same location (or a synced version of the same location).

**Comment by danielnaber** [comment]
There are many challenges that make this complicated: an URL cannot be written, so we'd need to integrate into some service like DropBox to have a writable file. We'd have to select a service and many people wouldn't like our choice. Then we'd have to adapt every single LT add-on out there so it can use this. It would need to be optional, as some users will want to keep their dictionary locally.

Sorry, I'll have to close this issue, as it seems to be too far away for what a small community like ours can implement.
