### ISSUE TITLE
[all] filter duplicate comma suggestions

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#6926]
I increasingly stumble upon duplicate comma suggestions (both in English and German). I think it should be easy to filter out these suggestions on the server. I would vote for keeping the second suggestion that underlines the space (suggesting `, word`) because based on the underline, it's already possible to tell that this might be a punctuation suggestion.

https://user-images.githubusercontent.com/37363/179350416-ec4178e3-eccc-4b76-92ae-f227eb2ce372.mov

@danielnaber @fabrichter @jaumeortola can we do this easily for all languages?

**Comment by jaumeortola** [comment]
I have also seen this problem. We can take of it in CleanOverlappingFilter.

**Comment by jaumeortola** [comment]
Done here: https://github.com/languagetool-org/languagetool/commit/96bfc39bc097a07794f24b3c4b4be83b7e2bb30e
We respect the existing rule priorities (including picky, Premium, and so on). If the priority is the same, we keep the second suggestion.

**Comment by tiff** [comment]
Awesome! Thank you so much

**Comment by jaumeortola** [comment]
The fix is online for Premium and OS. 
![imatge](https://user-images.githubusercontent.com/4289501/181040513-3441528f-117b-4f77-b2b3-aa785128e19b.png)
