### ISSUE TITLE
Some LibreOffice 7.3 Writer automatic-objects not read-only respected

### ISSUE THREAD

**Issue by BloomingAzaleas** [languagetool-org/languagetool#6927]
LO Writer provides for serveral types of (my term) 'automatic' objects. These are objects having a text value that is maintained and updated by LO. A catagory list of thes object types can be found in the Tools->Update menu. LT 5.9 snap 20220714 ignores most of these. However, it will scan and report on:

- Tables of <things> and Indexes -- objects inserted then configured by the user but with contents maintained by LO, drawing from document textual contents.
- 'sections' -- objects inserted by the user that are content import links to external documents or URLs.

Scanning/reporting is useful to an extent. However, LT then will offer Changes, which are still useful to know reminders, and if a Change is selected by the user, directly modify the object content. LT modifying automatic object content is deceptively pointless since, with the next object update, LO will 100% over-write/re-create the content of the automatic object from its configured source data. If a Change is needed, that Change has to be in the configured source text for an object to be persistent. Tracking down that source text then changing it is probably beyond the ambitions of LT. LT should respond with "Changes to automatic objects such as Indexes and Tables of Contents must be applied in their source text." or similar.

Regards.

**Comment by FredKruse** [comment]
This is an enhancement because the default LO/OO interface doesn't support the distinction between e.g. Tables of context and written text.

**Comment by BloomingAzaleas** [comment]
Ewwwwwwwww... ugly on the part of LO/OO. OK, so LT is not creating any persistent goofs to a document unlike, say, sync errors that place changes away from where they should be. The main effect is reputational for LT. So, for grins, I have noticed that LT seems to succesfully ignore headings in LO Writer, headings typically being incomplete sentence word-phrases LT would otherwise complain about. Do LO headings not appear in the flat paragraph list visible to LT? (See, I know about the Flat Paragraph List from alllllllll those stacktraces.) If headings do appear, by what LO property or LT heuristic does LT identify them as something to be ignored?

Where I am going here is that LO has paragraph styles, and the heading style for Index automatic objects is "Index" or a child-style thereof. For Table of XXXX automatic-objects, its style "Table of Contents" or a child thereof.  See Styles->Manage Styles. If LT can see those style identifiers, then it can know it is at the header for the following single-paragraph object of that type.

Or, move to the TO HARD pile.

Regards.

**Comment by FredKruse** [comment]
The issue is solved. Please test it tomorrow with snapshot 20220727

**Comment by FredKruse** [comment]
The issue is solved for all protected objects now.
Please test it after tomorrow (2022-08-05) and close the issue.

**Comment by BloomingAzaleas** [comment]
This issue of read-only respect seems to have been solved. For LO Writer index objects, LT 5.9 early Aug 2022 snapshots still offer wavy underline complaints in this objects but neither the right-click context menu nor the Next nor Check Text button offer those complaint items for correction. This behavior is excellent in that the user is still notified there are issues in the RW source text from which the index object is generated.
