### ISSUE TITLE
[pt] Regression tests not updated?

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6929]
@danielnaber 

Hello Daniel,

For two or three days that I look at the regression tests for pt-PT, and they don't show anything new.

https://internal1.languagetool.org/regression-tests/via-http/2022-07-16/pt-PT/index.html

For example, I have done major improvements in the antipatterns of the NUMBER AGREEMENT rules and no hits are shown above.

Is there an issue with the tests?

Thanks!

**Comment by danielnaber** [comment]
The nightly regression tets doesn't work and will probably be fixed on Monday.
