### ISSUE TITLE
[ar] Add arabic support

### ISSUE THREAD

**Issue by sohaibafifi** [languagetool-org/languagetool#693]
We are working on the arabic support (see [the fork]( https://github.com/sohaibafifi/languagetool/tree/arabic-dev) ,  #689 )

@linuxscout is working with some students on the linguistic part, I take care of the technical one.

Here are some tasks we are working on : 
- [ ] build tagged dict from [arramooz](https://github.com/linuxscout/arramooz) and [qutrub](https://github.com/linuxscout/qutrub)
       - [x] nouns
       - [x] verbs
       - [ ] others
       - [ ] Include frequency data
- [ ] rules from the [csv file](https://github.com/sohaibafifi/languagetool/blob/arabic-dev/languagetool-language-modules/ar/src/main/resources/org/languagetool/resource/ar/rules.csv) (570) 
- [x] unit tests
- [x] disambuigator and tagger
- [x] confusion_set

**Comment by linuxscout** [comment]
to be closed

**Comment by linuxscout** [comment]
@danielnaber please close it.
