### ISSUE TITLE
[pt] Fix rule: DEVE_DE

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6931]
Hello @ricardojosehlima

This rule generates numerous false positives.

Could you suggest which kind of words it should accept after the “dever de” + word_to_accept ?

This is the results of the current state of it:

[_0.txt](https://github.com/languagetool-org/languagetool/files/9130228/_0.txt)

Thanks!

**Comment by marcoagpinto** [comment]
Ricardo, sorry for asking, but do you have a better suggestion message for the rule?
`<message>Substitua por <suggestion>\1</suggestion>.</message>`

**Comment by marcoagpinto** [comment]
Ahhhh… I opened a ticket here because the forum confuses the attachments if they have the same name in multiple posts.

I don't know if it has been fixed, so I won't risk it.

**Comment by ricardojosehlima** [comment]
Hi @marcoagpinto two sources for the false positives:
- 'deveras' is an adverb (estava deveras cansado) that the rule is wrongly capturing
- there are some cases with 'devias' and the use of 2nd person singular as 'tu' is more typical in pt-pt so maybe a stilistic rule allows it in pt-pt?
  The message could be "A preposição 'de' não é necessária nesse caso.'

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Good morning,

And the postag after the “de”?

Should it accept only verbs?

And the verbs need to be in the infinitive?

Thanks!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

The “tu” will be caught by the informality rules.

**Comment by ricardojosehlima** [comment]
> @ricardojosehlima
> 
> Good morning,
> 
> And the postag after the “de”?
> 
> Should it accept only verbs?
> 
> And the verbs need to be in the infinitive?
> 
> Thanks!

yes and yes

**Comment by marcoagpinto** [comment]
Thanks!

Very easy to fix.

Will do it in a few hours.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello!

It is done!:
https://github.com/languagetool-org/languagetool/commit/68b96cf05e78484be99a02386bb31524393cb5bb

There seem to be no false positives:
[_1.txt](https://github.com/languagetool-org/languagetool/files/9133851/_1.txt)

Thank you for the help!
