### ISSUE TITLE
[pt] NUMBER AGREEMENT doubt – 2022-07-19

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6933]
Hello @ricardojosehlima

Today I want to fix some more number agreement issues by rewriting some antipatterns.

My brain is toasted and I can't reason.

In the example below, are they right?

For example:
`“segure o ovo direito”` and `“segure os ovos direito”`

Shouldn't the plural be `“direitos”` and not `“direito”`?

I can't think right now.

Thanks!

```

        <!-- MARCOAGPINTO 2020-06-20 *START* -->
        <!-- "Segure o ovo direito ou vai quebrá-lo." -->
        <!-- "Segure os ovos direito ou vai quebrá-los." -->
        <!-- "Segure a caneta direito ou vai quebrá-la." -->
        <!-- "Segure as canetas direito ou vai quebrá-las." -->
        <!-- "Segure o agente direito ou vai quebrá-lo." -->
        <!-- "Segure os agentes direito ou vai quebrá-los." -->
        <antipattern>
          <token postag='VMSP3S0|VMP00SF|VMM0[23]S0|VMI[SP]3S0|VM[IS]P1S0|VMG0000' postag_regexp='yes'>
            <exception postag_regexp='yes' postag="SPS00|CS|I|PT0CN000|RG"/></token>
          <token postag='DA0[FM][SP]0' postag_regexp='yes'/>
          <token postag='NC[CFM][SP]000' postag_regexp='yes'/>
          <token postag='AQ0MS0'/>
        </antipattern>
```

**Comment by susanaboatto** [comment]
Hi @marcoagpinto 

Both "segure os ovos direito" and "segure os ovos direitos" are correct but have different meanings. In "segure os ovos direitos", `direitos` is an adjective and refers to the noun `ovos`. But in "segure os ovos direito", `direito` is an adverb referring to the verb `segure`. It is roughly translated as "Hold the eggs properly". You could easily replace `direito` with another adverb here, such as `adequadamente`, so maybe that would help you understand the difference 😄. Maybe we could tag `direito` as an adverb to solve the problem.

**Comment by marcoagpinto** [comment]
@susanaboatto 

Ahhh… I will fix this rule today.

I said I would work on the NUMBER rules at night, but I couldn't wait, and I am working on them.

Thanks!

**Comment by marcoagpinto** [comment]
Anyway, I tested the NUMBER AGREEMENT rules without this antipattern, and the antipattern only had two or three hits, all wrong.

@susanaboatto I have just implemented the postags you told me above, and it only removed one hit, so it is a useless antipattern, it is better deleted.

Thanks!
