### ISSUE TITLE
GERMAN_SPELLER_RULE Zusammengesetzte Adjektivierte Substantive

### ISSUE THREAD

**Issue by QMBernhard** [languagetool-org/languagetool#6939]
Bsp. "Die Inhalte sollen zugriffsfreundlich sein" wird "zugriffsfreundlich" fälschlicherweise als Warnung deklariert. Korrekturvorschlag ist "Zugriffs-freundlich". Das ist gemäß neuer deutscher Rechtschreibung aber falsch. "zugriffsfreundlich" ist die korrekte Schreibweise.

**Comment by danielnaber** [comment]
Thanks, we have added that word.
