### ISSUE TITLE
[kn] add Kannada Support

### ISSUE THREAD

**Issue by MayuraVerma** [languagetool-org/languagetool#694]
Please add support to Kannada language. I will translate the interface on transifex, please add me to translate the interface to Kannada. My login in transifex is mayura.verma

**Comment by danielnaber** [comment]
We cannot add support for any language without a community member to write rules for that language and maintain it in the long run. If you're willing to do that, please check out http://wiki.languagetool.org/development-overview and start writing rules. We have support for Tamil, maybe that can be built upon?

**Comment by MayuraVerma** [comment]
OK. thank you. 
Where do I upload the rules? and invite other users to collaborate?
How many rules would be considered to add language support?

Thanks.

**Comment by danielnaber** [comment]
You can fork LT at github and add the rules there (e.g. to Tamil - remove the existing rules first - until there's real support for Kannada). We'll consider adding a new language once there are 50 rules and constant work for at least 3 months.

**Comment by danielnaber** [comment]
Closing, feel free to re-open once support for Kannada is ready.
