### ISSUE TITLE
[pt] Wrong suggestion by LT

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#6942]
In the sentence "você faltou as 4 aulas" LT says that the verb is not 'impessoal'.
Indeed, it isn't.
So what's the problem?
My guess is that the LT rule indicates that the verb should be in the plural; however, this is not the case.

**Comment by marcoagpinto** [comment]
Ahhhhh… I will add an antipattern to it at 5am…

Thank you for the report!

❤️ ❤️ ❤️ ❤️ ❤️

**Comment by ricardojosehlima** [comment]
If the rule applies to other verbs, I would like to see the list... And also the details of the rule.

**Comment by marcoagpinto** [comment]
Yes, after I find out the rule ID, I will do a test against 600 000 sentences BEFORE and an AFTER for you to see the differences.

😄

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Here is the rule your sentence triggers:


```
    <rulegroup id='NON_IMPERSONAL_VERBS' name="Concordância Verbal: Verbos não-impessoais: existir, bastar, faltar, etc.">
      <!-- Created by Tiago F. Santos , Portuguese rule, 2017-02-27 -->
      <rule>
        <pattern>
          <token postag_regexp='yes' postag='V...3S.+' inflected='yes' regexp='yes'>existir|bastar|faltar|restar|sobrar
            <exception>sobre</exception></token>
          <token postag_regexp='yes' postag='(?:D...|P...|N..|A...)P.+'>
            <exception negate_pos='yes' postag_regexp='yes' postag='(?:D...|P...|N..|A...)P.+'/></token>
        </pattern>
        <message>Este não é um verbo impessoal.</message>
        <suggestion><match no='1' postag_regexp='yes' postag='(V...)3S(.+)' postag_replace='$13P$2'/> \2</suggestion>
        <suggestion>\1 <match no='2' postag_regexp='yes' postag='(D...|P...|N..|A...)P(.+)' postag_replace='$1S$2'/></suggestion>
        <example correction="existem muitas|existe muita">Na vida <marker>existe muitas</marker> coisas boas.</example>
      </rule>
      <rule>
        <pattern>
          <token postag_regexp='yes' postag='V...3P.+' inflected='yes' regexp='yes'>existir|bastar|faltar|restar|sobrar</token>
          <token postag_regexp='yes' postag='(?:D...|P...|N..|A...)S.+'>
            <exception negate_pos='yes' postag_regexp='yes' postag='(?:D...|P...|N..|A...)S.+'/></token>
        </pattern>
        <message>Este não é um verbo impessoal.</message>
        <suggestion><match no='1' postag_regexp='yes' postag='(V...)3P(.+)' postag_replace='$13S$2'/> \2</suggestion>
        <suggestion>\1 <match no='2' postag_regexp='yes' postag='(D...|P...|N..|A...)S(.+)' postag_replace='$1P$2'/></suggestion>
        <example correction="existe muita|existem muitas">Na vida <marker>existem muita</marker> coisas boas.</example>
      </rule>
    </rulegroup>
```

**Comment by marcoagpinto** [comment]
Ricardo,

Basically, I just need to create an antipattern to check if the word after the verb is a preposition (a, as, o, os)?

**Comment by marcoagpinto** [comment]
Ahhhhhhhh…

What I need to check is if the token before the verb is a pronoun (você, tu, eles, etc.)?

**Comment by ricardojosehlima** [comment]
Hmmm, I guess in "você faltou as 4 aulas" although I fell it is a determiner, it really is a preposition, see "você faltou aos 4 encontros". 
So the rule is not exactly wrong, it just wasn't prepared to this situation.
So I guess it can remain unchanged.
However there may be other verbs to add to this list. Some that come to my mind:
chegar, acabar, ficar, sair, entrar
Maybe adding these and test could be a good try,

**Comment by marcoagpinto** [comment]
Ricardo, if it is the pronoun check before the missing verb, I will directly change the rule by adding an "exception scope='before' blah blah blah PP.+".

This should fix it.

**Comment by ricardojosehlima** [comment]
> Ahhhhhhhh…
> 
> What I need to check is if the token before the verb is a pronoun (você, tu, eles, etc.)?

It may solve a specific case, but I don't think it would be effective to the other verbs and it wouldn't solve "O menino faltou as 4 aulas".

**Comment by ricardojosehlima** [comment]
> Ricardo, if it is the pronoun check before the missing verb, I will directly change the rule by adding an "exception scope='before' blah blah blah PP.+".
> 
> This should fix it.

No, that's not the problem. My writing was the problem...

**Comment by marcoagpinto** [comment]
antipattern:
```
PP.+
V.+
DA.+
```
?

This will do some fixing?

😄

**Comment by marcoagpinto** [comment]
or maybe the exception with the scope=before blah blah PP.+

😄 

A quick fix.

I will do it at 5am and post the before and the after.

In the before I will add your verbs.

**Comment by ricardojosehlima** [comment]
> antipattern:
> 
> ```
> PP.+
> V.+
> DA.+
> ```
> 
> ?
> 
> This will do some fixing?
> 
> smile

maybe, not sure

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I have added your verbs and the “você/ele/nós blah blah” exception.

However, adding the verb “entrar” caused tons of false positives with “entre” which I fixed with an antipattern SPS00.

So, here is what we have:

Commit URL:
https://github.com/languagetool-org/languagetool/commit/c56690c1a987942c508a685ac4c91a8027c263d1

BEFORE (with your verbs added):
Portuguese (Portugal): 2198 total matches
[_0before.txt](https://github.com/languagetool-org/languagetool/files/9156221/_0before.txt)

AFTER (with the pronouns removed)
Portuguese (Portugal): 2178 total matches
[_2after.txt](https://github.com/languagetool-org/languagetool/files/9156231/_2after.txt)

AFTER (with “entre” removed)
Portuguese (Portugal): 121 total matches
[_3after.txt](https://github.com/languagetool-org/languagetool/files/9156235/_3after.txt)

If there are more fixes we can do for some special cases, I will create an antipattern for them.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Did you say that:
`“O menino faltou as 4 aulas”`
is a false positive?
Then so is:
`“O Marco faltou as 4 aulas”.`
`“Marco faltou as 4 aulas”.`
?

I can create a little antipattern that will fix that specific cases:
```
DA.+
NC.+|AQ.+
V.+
```
and an exception scope=previous with
`NP.+`

**Comment by marcoagpinto** [comment]
Ricardo,

I have created an entity with non-impersonal verbs, making it easy to add and remove verbs all over the grammar.xml:

`<!ENTITY verbos_nao_impessoais "acabar|bastar|chegar|entrar|existir|faltar|ficar|restar|sair|sobrar">`

https://github.com/languagetool-org/languagetool/commit/ce8b6e32518b5f96d9a77d572bafbad23e7c9041

**Comment by ricardojosehlima** [comment]
Hi @marcoagpinto. After reading the _3after.txt some considerations:
1-) the rule must not apply to infinitives
Esperamos ficar milionários em breve.
Costumava existir muitos peixes em qualquer rio do Japão.
and others are correct.
2-) also not apply if after comes a "sujeito composto":
E logo ao lado da porta ficam o espelho, o cesto de roupas sujas e os ganchos para pendurar roupas (nesta primeira foto o pijaminha...
No primeiro treino da epoca, faltaram Camião, Ganhão, Resende e Bruno Aires
and others are correct.
3-) the verbs I suggested present some challenges, because context may allow some cases:
O caso de Sami acabou meses atrás.
Maria ficou alguns dias em Paris.
A ambulância chegou poucos instantes depois do acidente.
Thus, I rest my case and ask for you to remove the suggested verbs, until a better and more careful analysis can be done (at the moment, I can't do it).

**Comment by marcoagpinto** [comment]
It is okay.

I will add some exceptions/antipatterns to fix part of the false positives.

I will post the results here.

Look at the results only when you have the time, it is not urgent.

I have been working on NUMBER and GENDER agreements rewriting all antipatterns (it will take months to have it ready).

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I lay down in bed and closed my eyes, and fell asleep 😄 

Now that I am up again, I am back to LanguageTool.

I have fixed false positives in the rule.

I have removed infinitive forms and added code to two antipatterns to remove some false positives.

Take a look at the examples in the two antipatterns to see if they are all well:
https://github.com/languagetool-org/languagetool/commit/222c55aff3efb8db672c99ae16e11eae9292edd8

So, here is BEFORE (posted in your last comment):
Portuguese (Portugal): 121 total matches
[_3before.txt](https://github.com/languagetool-org/languagetool/files/9164825/_3before.txt)

and here is AFTER:
Portuguese (Portugal): 61 total matches
[_9after.txt](https://github.com/languagetool-org/languagetool/files/9164827/_9after.txt)

**Comment by ricardojosehlima** [comment]
Right!
Some problematic cases (yet):
Por favor, basta nos enviar o inquérito para mais detalhes sobre nossos liquidificadores de alimentos elétricos. ("nos" shouldn't count as a pronoun that triggers the rule)
SERA QUE E MENTIRA,QUE PESSOAS FICAM IGUAL A LIXO NOS CHAOS DOS HOSPITAIS???? (as pessoas is plural before the verb, maybe when it happens the rule shouldn't apply)
Sai de lá antes que saíssem comigo, pois até rebelde, de anti-cristo já me chamavam. (comigo same situation as nos)
Enquanto tudo isso acontecia, outras mães no quarto ficavam me olhando. (me same thing)
Faltam convicção, coragem e determinação para um salto de qualidade. (there are many cases like this: verb plural, then something singular that is part of a sujeito composto, this can be captured by something like noun E noun or noun, noun E noun (with optional adjectives in the middle))
Durante quarenta anos os israelitas tiveram maná para comer, até chegarem a uma terra habitada, isto é, até que chegaram à fronteira de (a in 'a uma terra' is a preposition and the rule shouldn't apply)

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Seems easy to fix… I thought it would be harder. 😄 😄 😄 😄 😄 😄 😄 

I will start within an hour to fix it.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ 

Thanks!

**Comment by marcoagpinto** [comment]
I am still working on it.

😛 😛 😛

**Comment by marcoagpinto** [comment]
It gave tons of false positives (well, not tons because the whole file was just 61 matches)… 😛

**Comment by marcoagpinto** [comment]
Just “Part of a compound subject” is missing… I am about to code an antipattern for it.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is coded:
BEFORE (last .txt upload)
Portuguese (Portugal): 61 total matches
[_9before.txt](https://github.com/languagetool-org/languagetool/files/9167667/_9before.txt)

AFTER
Portuguese (Portugal): 46 total matches
[_14after.txt](https://github.com/languagetool-org/languagetool/files/9167675/_14after.txt)


```
        <example>Faltam convicção, coragem e determinação para um salto de qualidade.</example>
        <example>No primeiro treino da epoca, faltaram Camião, Ganhão, Resende e Bruno Aires que se encontam de ferias ou por motivos profissionais.</example>
        <example>Não lhe faltam dignidade e elegância.</example>
```


```
        <example>Por favor, basta nos enviar o inquérito para mais detalhes sobre nossos liquidificadores de alimentos elétricos.</example>
        <example>...s, como eles próprios o são. Os rebanhos, os bens e todos os animais domésticos serão assim nossos. Basta lhes darmos o consentimento e eles habitarão conosco.</example>
```


```
        <example>Sai de lá antes que saíssem comigo, pois até rebelde, de anti-cristo já me chamavam.</example>
        <example>Enquanto tudo isso acontecia, outras mães no quarto ficavam me olhando.</example>
        <example>Além do mais passavam ao nosso lado quase todos os aviões e respectivos pilotos quando acabavam a sua exibição!</example>
        <example>Fiquei sismado por ficarem me encarando.</example>
        <example>Funcionários da Flórida dizem que ainda não chegaram a uma conclusão. Ainda estão procurando descobrir o método pelo qual o vírus é transmitido.</example>
        <example>Durante quarenta anos os israelitas tiveram maná para comer, até chegarem a uma terra habitada, isto é, até que chegaram à fronteira de Canaã.</example>
        <example>SERA QUE E MENTIRA,QUE PESSOAS FICAM IGUAL A LIXO NOS CHAOS DOS HOSPITAIS????</example>
        <example>Todas disponíveis no Netflix, mas as duas últimas sairão junho ou julho.</example>
```

**Comment by marcoagpinto** [comment]
Ops…

Forgot the commit link:
https://github.com/languagetool-org/languagetool/commit/9b03156a249ec2c8a63afa8b36ec5e69959e9fea

**Comment by ricardojosehlima** [comment]
Great!
But sujeitos compostos remain:
Dentro do peito, existem o coração e o pulmão.
This is correct.
I imagine that it may be hard to capture this kind of construction because LT doesn't provide syntactic information (otherwise, that and many many other rules would be so much easier to make, but I understand how difficult it is to insert syntactic information in the LT architecture).

**Comment by ricardojosehlima** [comment]
Sorry only now I saw your comment on compound subjects.

**Comment by marcoagpinto** [comment]
Well, "a(s)" and "o(s)" is easy to code 😄 

Let me give it a try.

**Comment by marcoagpinto** [comment]
One thing I noticed with the new disambiguator is that if you use NC it also seems to address NP, and perhaps NP will only accept NP and not NC.

Just something I have been noticing… I am not 100% sure it is true.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is done and working:
https://github.com/languagetool-org/languagetool/commit/e4ae1d6e6a16fde87565d03cb4890cc4c5618ba1

AFTER:
Portuguese (Portugal): 44 total matches
[_15after.txt](https://github.com/languagetool-org/languagetool/files/9168044/_15after.txt)


```
        <example>... nichos moduláveis que ficam ao pé da cama, então continuando na parede oposta à cabeceira da cama, ficam o armário e a poltrona.</example>
        <example>Dentro do peito, existem o coração e o pulmão.</example>
```

**Comment by ricardojosehlima** [comment]
This
Entram André Horta e Jonas, saem Chrien e Rafa53' - Golo do Leipzig!
and another example are with proper nouns, and the rule is still applying. Proper nouns should be added

**Comment by marcoagpinto** [comment]
Ohhhhh… you are right, I was looking at the POS information, and they are NP.+ .

**Comment by marcoagpinto** [comment]
Let me give it another try.

**Comment by marcoagpinto** [comment]
I will also increase MAX="2" to MAX="3" to see if we can catch any more sentences.

**Comment by marcoagpinto** [comment]
ahhhh… it takes more time to test against 600 000 sentences than improving the code…

😛 😛 😛 😛 😛 😛 😛 😛 😛

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is done!

https://github.com/languagetool-org/languagetool/commit/dd2a84cd8a8995baa4623d4c4048c7292566a845

AFTER:
Portuguese (Portugal): 43 total matches
[_16after.txt](https://github.com/languagetool-org/languagetool/files/9168190/_16after.txt)

It only removed your example sentence:

`        <example>Entram André Horta e Jonas, saem Chrien e Rafa53' - Golo do Leipzig!</example>`

**Comment by marcoagpinto** [comment]
ahhhh... maybe because Hummel has no POS?

It is as UKNOWN.

But even that way it should work, it is strange.

**Comment by marcoagpinto** [comment]
Let me check if Hummel is male or female on Wikipedia.

**Comment by marcoagpinto** [comment]
It is male, and I have updated added.txt and spelling.txt both in GitHub and in my standalone+wikipedia tools.

I am now testing against 600 000 sentences.

**Comment by marcoagpinto** [comment]
Ahhhh... I was right, it was the missing POS:

AFTER:
Portuguese (Portugal): 42 total matches
[_17after.txt](https://github.com/languagetool-org/languagetool/files/9168416/_17after.txt)
![tortoiseSVN_screenshot_20220722](https://user-images.githubusercontent.com/5192600/180458747-ed92b8f8-7a50-458e-99e6-14d326a58aa6.png)

https://github.com/languagetool-org/languagetool/commit/f8e2adff0637585ffd3db7e689e94746e1053dcb

https://github.com/languagetool-org/languagetool/commit/5ee3499a13a5e9975c9a4f0213bda21ea6b182cb
