### ISSUE TITLE
[LO-Add-on] Windows still get hidden if you click anywhere on LibreOffice

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6949]
Hello @FredKruse 

I have been testing the latest nightly and the windows still get hidden if you click anywhere on LibreOffice.

Here is a video capture of it happening (converted using HandBrake since Nero damages the resolution):
https://user-images.githubusercontent.com/5192600/180564662-2ab1b522-aa14-4145-ab08-d146538f5363.mp4

Isn't there a “StickyWindow” command in Java like there is in PureBasic that allows to keep a window in front of the whole windows on the desktop?
![PureBasic_StickyWindow_20220722](https://user-images.githubusercontent.com/5192600/180559363-dce4b857-9a13-4fc2-b02c-93a8c4ac8584.png)

Thanks!

EDIT:
Microsoft isn't supposed to own GitHub? It doesn't accept WMV format (Microsoft).
Also, I had to upload the video three times because GitHub doesn't support H265 nor H264 (with custom frame rate?)… I had to do software based video encoding with constant frame rate.

**Comment by FredKruse** [comment]
The about-window is always on top now. I'm uncertain if that is a good idea. It has to be closed before a user can work on LO again. Please test it and give me feed back.

**Comment by marcoagpinto** [comment]
@FredKruse 

I will test tonight with the nightly.

Did you do the same to the “Options” and to the “Check Grammar blah blah” windows?

Thank you!

**Comment by marcoagpinto** [comment]
Yes, having an “about window” to stop other actions is the correct behaviour of any app.

**Comment by marcoagpinto** [comment]
@FredKruse 

Ahhhh… it is much better now.

Can you do the same for the windows:
1) spell and grammar check dialog
2) options
?

Thanks!

**Comment by marcoagpinto** [comment]
Also, take a look at the “about window”, there is a period missing and a space character that could be removed:
![LT_about_window_20220724](https://user-images.githubusercontent.com/5192600/180635039-b204334f-7887-4153-8a96-98e0802f2674.png)

**Comment by marcoagpinto** [comment]
Ohhhhhh… I came up with a brilliant idea for the unmaintained languages list there.

Instead of writing there “(*)” place the languages in red and change the text to:
“Red means language is unmaintained in LanguageTool.”

Much better, don't you think?

Thanks!

**Comment by FredKruse** [comment]
The blank is removed, and the option panel always stays in front now.

The spell and grammar check dialog behaves in another way. The user can switch between the dialog and the document. This is because sometimes it is easier to do large changes direct in the document. If the dialog gains focus again, the new check starts at the cursor position and displays the next match.

It is not a good idea, to paint languages missing maintainers red, I think. Red is a signal color. We should paint it gray, if we like to play with colors, or leave it as it is, I think.
@danielnaber What do you think?

**Comment by danielnaber** [comment]
> or leave it as it is, I think.

I agree

**Comment by marcoagpinto** [comment]
Very well done, thanks!
