### ISSUE TITLE
[pt] Is "parabéns" an interjection?

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6958]
@ricardojosehlima

Hello!

I checked in three on-line dictionaries, and none says it is also an interjection.

By heart, I know it is:
```
“Parabéns, Marco!”
“Muitos parabéns, Marco!”
```

After an interjection, the rules suggest adding punctuation such as a comma or exclamation mark.

Should I add the POS of interjection to this word?

Thanks!

**Comment by ricardojosehlima** [comment]
Hi @marcoagpinto I also don't think it is an interjection. If 'parabéns' is turned into one and must receive the punctuation suggestion, then we will have problems, for in "Eu dei os parabéns para o Marco" there is no need for a punctuation here (unless of course you create some antipattern).

**Comment by marcoagpinto** [comment]
Ahhhh… thanks!
