### ISSUE TITLE
Provide a .desktop file on Linux?

### ISSUE THREAD

**Issue by orschiro** [languagetool-org/languagetool#696]
Dear all, 

First, I want to thank you for your excellent work on this great tool!

I use it quite frequently on Ubuntu Linux 17.04.

However, I find the way of opening inconvenient by executing the jar file. 

Could we ship a .desktop file with a proper icon so that it nicely integrates into the launcher menus of popular Linux distributions like Ubuntu?

Yours,

Robert

**Comment by janschreiber** [comment]
Thanks for the suggestion. For now, you can modify and use mine:
```
[Desktop Entry]
Name=LanguageTool
Exec=java -jar ./languagetool.jar
Type=Application
Terminal=false
GenericName=LanguageTool
Comment=LanguageTool
StartupNotify=false
Path=/usr/bin/LanguageTool-3.7
Icon=/home/jan/Bilder/Icons/lt-icon.png
Categories=Office;
```
Modify the paths as necessary, then save this as e. g. `LT.desktop` in `/usr/share/applications`.

**Comment by orschiro** [comment]
@janschreiber, thank you very much!

Can you please share your `lt-icon.png` with me?

Moreover, where do I get `/usr/bin/LanguageTool-3.7` from?

**Comment by janschreiber** [comment]
You can download the icon from [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:LanguageTool_Logo.svg). If possible, use the .svg file provided there. It probably looks best.
`/usr/bin/LanguageTool-3.7` is where I extracted the zip file downloaded from languagetool.org, that means in your case the path to the `languagetool.jar` file that you use.

**Comment by orschiro** [comment]
It is working perfectly. Thank you, @janschreiber! :-)

However, I still do not understand the exact difference between the line `Exec` and `Path` and why they are the same. 

```
[Desktop Entry]
Name=LanguageTool
Exec=java -jar /home/orschiro/Software/LanguageTool/languagetool.jar
Type=Application
Terminal=false
GenericName=LanguageTool
Comment=LanguageTool
StartupNotify=false
Path=java -jar /home/orschiro/Software/LanguageTool/languagetool.jar
Icon=/home/orschiro/Software/LanguageTool/LanguageTool_Logo.svg
Categories=Office;
```

**Comment by janschreiber** [comment]
> However, I still do not understand the exact difference between the line Exec and Path and why they are the same.

The correct path in your case would be `/home/orschiro/Software/LanguageTool/`. `Path` must always be a directory.

**Comment by orschiro** [comment]
Thanks for the explanation!

**Comment by danielnaber** [comment]
Can this issue be closed? I see the file provided contains a user-specific path, so it's nothing that could be part if the LT distribution.

**Comment by orschiro** [comment]
Yes, it can be closed. 

Thanks again for the provided help!
