### ISSUE TITLE
Vim integration with remove server

### ISSUE THREAD

**Issue by vitaly-zdanevich** [languagetool-org/languagetool#6960]
Hi, I found this script https://www.vim.org/scripts/script.php?script_id=3223

But in the description I see

>  To use this plugin, you need to install the Java LanguageTool program.

Can we have Vim plugin without local server, but using remote one, like in browser extension?

**Comment by danielnaber** [comment]
I'm closing this issue, as the report seems to belong to the add-on, not to LT.
