### ISSUE TITLE
[pt-BR] do not give suggestions like 'provámos' 

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#6962]
In the rule TESE_PHD_PROCURAR_PROVAR_PROVARA, or in any other rule. 

@susanaboatto I open a new issue because this is a specific problem. I will provide a solution for that.

**Comment by jaumeortola** [comment]
I wrote this new rule. Please check the message and the rule name. @susanaboatto 
https://github.com/languagetool-org/languagetool/commit/13048ad8638971d116ab6d374b1825af67e5dfef

It is not indispensable because the Brazilian speller already detects the error, but it can be useful.

**Comment by susanaboatto** [comment]
Thanks @jaumeortola, the "Portuguese" tag is not included in our tagset description, so I didn't know that. It looks like this rule would fix it in case the spelling does not 😄
