### ISSUE TITLE
[all languages] MORFOLOGIK_RULE should suggest a capital letter directly after a period,

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#6975]
via @MarvinErdner
> MORFOLOGIK_RULE should suggest a capital letter directly after a period. Of course it works fine as  MORFOLOGIK_RULE and then UPPERCASE_SENTENCE_START[]. 

![imatge](https://user-images.githubusercontent.com/4289501/182111676-41df54eb-f24f-45b1-9b66-ad2c02927996.png)

**Comment by tiff** [comment]
@jaumeortola please keep in mind cases like "mRNA" or "macOS"

**Comment by jaumeortola** [comment]
TODO: remove duplicates. For example, in Dutch: 
```
old: Thailand, thailand    new: Thailand, Thailand
```
