### ISSUE TITLE
Better message for 'Get corrections from an OpenNMT server (beta)'

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#698]
In the LT 3.8 snapshot GUI, when I select Misc > Get corrections from an OpenNMT server (beta), I get a Java error message.

Although the rule is a beta, I think that a clearer error message would be useful. Tell the users what they must do to set up LT such that the rule can work.

**Comment by danielnaber** [comment]
What error do you get? Probably that the server cannot be connected? It's not yet supported, that's why it's beta. I'll document it when it actually works properly.

**Comment by MikeUnwalla** [comment]
The error is in part: Could not connect OpenNMT server at http://127.0.0.1:7784/translator/translate

>  I'll document it when it actually works properly.

OK, thanks. I'll close the issue.
