### ISSUE TITLE
Given source and target sentences, find what rules apply

### ISSUE THREAD

**Issue by federicoBetti** [languagetool-org/languagetool#6983]
I have a question that could be seen as the reverse process of what LT does.
Is it possible to find which rules can be used to pass from a source to a target sentence?

E.g.
Input
source sent: `"My name are John"`
target sent: `"My name is John"`

Output
`rules: [RULE_OBJECT_3, RULE_OBJECT_10]`
Each rule object with rule_ids, descriptions etc.

**Comment by danielnaber** [comment]
Not quite, but if you use the command-line version of LT with "My name are John" as input, it will print something like this:

```
1.) Line 1, column 9, Rule ID: SINGULAR_AGREEMENT_SENT_START[1] premium: false
Message: You should probably use “is”.
Suggestion: is
My name are John
        ^^^  
```
