### ISSUE TITLE
[pt] Improve disambiguator - 2022-08-03

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6984]
@jaumeortola 

Hello Jaume,

I'm sorry to bother you, but could you improve the disambiguator?:
`Minha namorada dança bem.`

“dança” should be a V.+ and not a NC.+

Thanks!

**Comment by marcoagpinto** [comment]
Another one:
`Minha alma busca-te, sem ti tudo é deserto.`

“busca”=verb “buscar”

**Comment by marcoagpinto** [comment]
`Meu irmão nada bem.`

**Comment by jaumeortola** [comment]
The solution for `busca-te` is good and general. 

I also added a fix for `nada` and `dança` (https://github.com/languagetool-org/languagetool/commit/4eb8f2d1e7e25f6802609d385ebcb059496733f8), but they are more ambiguous words and probably the solution is not general.
