### ISSUE TITLE
New rule causes problem in JLanguageToolTest.java

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#699]
I changed two disambiguation rules to fix the false warning for "He spoke to the chosen people.", as noted in http://forum.languagetool.org/t/false-positives/1233.

When I run testrules, I get the results that I expect. But, the Maven tests give an error. The applicable part is:

```
Running org.languagetool.JLanguageToolTest
Tests run: 10, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 1.5 sec <<< FAILURE! - in org.languagetool.JLanguageToo
lTest
testAnalyzedSentence(org.languagetool.JLanguageToolTest)  Time elapsed: 0.17 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...] test¡ed[tested/JJ,[test/VBD,test/VBN,test¡ed/null,]I-NP-singular] sente...>
but was:<...] test¡ed[tested/JJ,[]I-NP-singular] sente...>
```

As best I can tell, the error occurs because my rules change the postags for the word 'tested' in the test sentence "This is a test\u00aded sentence" that is in the test that starts on line 157 in /en/src/test/java/org/languagetool/JLanguageToolTest.java

I don't want to mess with things that I don't really understand. Could one of the developers please change the test sentence in JLanguageToolTest.java to something like "The sentence you tested is satisfactory."?

**Comment by f-knorr** [comment]
Hi @MikeUnwalla !
Could you please let us know what you changed!
Thank you!

**Comment by MikeUnwalla** [comment]
Hi @f-knorr 

I have not yet changed the rules on GitHub. Sorry for my unclear message.

I meant that I changed the rules on my development version. These are the changed versions of the disambiguation rules that I would like to put on GitHub:

```
    <rule name="determiner + verb/NN -&gt; NN" id="DT_VB_NN">
        <pattern>
            <token postag="DT"><exception postag="PDT"/><exception regexp="yes">th[eo]se|each|that|much</exception></token>
            <marker>
                <and>
                    <token postag_regexp="yes" postag="VB[PZDN]?|MD"/>
                    <token postag_regexp="yes" postag="NN.*"><exception negate_pos="yes" postag="VB[ZPDN]?|NNS?|NN:UN|NN:U|MD" postag_regexp="yes"/></token>
                </and>
            </marker>
            <token><exception postag="JJ"/></token>
        </pattern>
        <disambig action="filter" postag="NN.*"/>
        <example type="untouched">These may be to bring about political change.</example>
        <example type="untouched">The <marker>known good</marker> solution is disambiguated in DT_VBN_JJ.</example>
        <example type="ambiguous" inputform="dogs[dog/NNS,dog/VBZ]" outputform="dogs[dog/NNS]">The <marker>dogs</marker> barks loudly.</example>
        <example type="untouched">Anarcho-pacifism is a tendency that rejects violence.</example>
    </rule>
```

```
    <rule name="DT + VBN + JJ -&gt; VBN=JJ" id="DT_VBN_JJ">
        <pattern>
            <token regexp="yes">a|an|the</token>
            <marker>
                <token postag="VBN"/>
            </marker>
            <token postag_regexp="yes" postag="JJ|NNS?"/>
        </pattern>
        <disambig postag="JJ"/>
        <example type="ambiguous" inputform="known[know/VBN,known/NN]" outputform="known[known/JJ]">This is the <marker>known</marker> good solution.</example>
        <example type="ambiguous" inputform="broken[break/VBN]" outputform="broken[break/JJ]">The <marker>broken</marker> window is dangerous.</example>
    </rule>
```
The changed rule DT_VBN_JJ removes the postags VBD and VBN from 'tested' in the sentence, "This is a tested sentence." Hence, the Maven error message.

**Comment by milekpl** [comment]
I added myself. I will investigate this in a minute.

**Comment by milekpl** [comment]
@MikeUnwalla The 'error' you get with JLanguageToolTest is just a hardcoded old result that needed to be updated. We have some hardcoded results of our tagging, some of which must be wrong, in our tests. In this case, it was simply enough to remove 'vbn' and 'vbd' readings.

There was also a problem with EUPUB_HOMOGENISE_HOMOGENEOUS_HOMOGENEOUSLY – your rule removes "VBN" from homogenised, so you cannot find just "standardised" but many more forms.  I went ahead and changed it to a regexp-replace suggestion. 

I will commit the fix in a minute.

**Comment by milekpl** [comment]
Oh my, I used the wrong issue number but it's fixed. ;)

**Comment by MikeUnwalla** [comment]
@milekpl , thank you.

Although I knew about the problem with EUPUB_HOMOGENISE_HOMOGENEOUS_HOMOGENEOUSLY, I am very happy that you changed the rule. Your regexp-replace suggestion is very elegant.
