### ISSUE TITLE
[LO add-on] Text score

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#6991]
Hello @FredKruse 

Could a feature similar to the LanguageTool on-line editor be created, showing the text score 0-100% of the text in a document?

Even Microsoft has it built-in in Office 365 if we select its editor to check the document.

Thanks!

**Comment by FredKruse** [comment]
Hello @marcoagpinto 
a score is integrated at the check dialog. Is it that, what you mean?

**Comment by marcoagpinto** [comment]
@FredKruse 

How can it be 100%?

There are tons of underlined words in the 499 pages.

![result_20220805](https://user-images.githubusercontent.com/5192600/183061689-5df5681b-cd76-4099-aff7-f08fef782bc0.png)

**Comment by marcoagpinto** [comment]
Also, could “Result” be changed to “Score Result” or similar?

Thanks!

**Comment by FredKruse** [comment]
This bug may also be related to issue #6992. Please test it with the tomorrow nightly.

**Comment by marcoagpinto** [comment]
@FredKruse 

My 499 page-thesis:
![LT_text_score_0percent_20220806](https://user-images.githubusercontent.com/5192600/183263359-9ded002c-9907-4db6-a0da-215ed4422f97.png)

0%.
