### ISSUE TITLE
Multi-word equivalent of spelling.txt

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#700]
The spell checker (for English) shows warnings for some multi-word terms that are spelled correctly. Examples: boric acid; ab initio.

I can add those terms to disambiguation.xml, but an elegant alternative would be to put the terms into a text file in the same way that we put one-word terms into spelling.txt.

(Most of the warnings are for Latin phrases that are used in English. Although they should not be flagged as spelling errors, they could have rules in the Plain English category.)

**Comment by f-knorr** [comment]
Hi @MikeUnwalla / @danielnaber !
Just a first idea:

- We could continue using spelling.txt
- spaces in multi-word entries could be marked by `&#32;` (i.e., the entry in spelling.txt would look like `ab&#32;inito`)
- when parsing spelling.txt, we could check for the occurrence of &#32; and dynamically create a DisambiguationRule which we add to the corresponding rule's `antipattern`s
```
      if(ignoreWord.contains("&#32;")) {
    	  String[] tokens = ignoreWord.split("&#32;");
    	  List<PatternToken> patternTokens = new ArrayList<PatternToken>(tokens.length);
    	  for(String token : tokens) {
    		  patternTokens.add(new PatternToken(token, true, false, false));
    	  }
          antiPatterns.add(new DisambiguationPatternRule("INTERNAL_ANTIPATTERN", "(no description)", language,
                  patternTokens, null, null, DisambiguationPatternRule.DisambiguatorAction.IMMUNIZE));
      } else
      addIgnoreWords(ignoreWord, wordsToBeIgnored);

What do you think?
```

**Comment by danielnaber** [comment]
Why mark the words with spaces at all and not just use a space?

**Comment by f-knorr** [comment]
Good point! We could also do this. This would be easier and more transparent, but would AFAIK require changing the current tests. We would have to modify them so that accidentally inserted blanks (e.g., "dog&emsp;&emsp;") are detected as incorrect entries.

**Comment by danielnaber** [comment]
Yes, leading or trailing spaces should either be silently removed or throw an exception (I'd prefer throwing an exception).

**Comment by f-knorr** [comment]
OK. I'll give it a try...

**Comment by f-knorr** [comment]
Hi @MikeUnwalla ,

I have committed a possible solution to your problem. If this is what you wanted (just enter the multi-word expression in spelling.txt), please close this issue.

**Comment by MikeUnwalla** [comment]
@f-knorr . Thank you. This is exactly what I wanted.

Two multi-word terms that I added (https://github.com/languagetool-org/languagetool/commit/a7385980d29c39a91f03b1a73d4ca2e6afd4e109) are not ignored by the spell checker:
* loc. cit.
* raison d'être. (But, the spell checker correctly ignores déjà vu.)

If you get time, please investigate why the terms are not ignored for spelling. Thanks.

**Comment by f-knorr** [comment]
@MikeUnwalla : [I have just updated](https://github.com/languagetool-org/languagetool/commit/0a689cc4f331c325d1bf556138dac0f3d3b14d55) `changes.md`.
The change I have made is just quick way of defining a disambiguation rule. The tokens of 'raison d'etre' are "raison", "d", "'", "etre". Hence, to make the spell checker ignore 'raison d'etre' enter 'raison d ' etre' in spelling.txt. I know this sounds a little weird, but I hope this work-around is acceptable. (I have already committed this change.) An automated tokenization would make things pretty complicated because we have different tokenizers for Catalan, English, Dutch, Polish,...
"loc. cit." is even more difficult as this expression contains "." which is also used to split sentences. To make the spell checker accept this expression (no matter whether you use spelling.txt or disambiguation.xml), you have to modify segment.srx

**Comment by f-knorr** [comment]
Update: It turns out that the build fails if you enter "raison d ' etre" in spelling.txt. I will investigate this.

**Comment by MikeUnwalla** [comment]
@f-knorr , thanks for your explanation.

It's no problem if I can't add some terms. I can always write a disambiguation rule for the few multi-word terms that I can't put into spelling.txt.

In the light of your explanation, I am more than happy with the first version of the rule that you made.

**Comment by f-knorr** [comment]
Ok. Now you should be able to enter 'raison d'etre' and similar expressions without the need of any modifications (Thanks to a helpful hint from @danielnaber I could easily add an automated tokenization)
(Remark: I have already  added 'raison d'etre'.)
But you still have to modify segment.srx for any expression that contain "." where "." must not be interpreted as the end of sentence.

**Comment by milekpl** [comment]
I don't want to sound very negative, but it's really very easy to add any phrase to a list of expressions immunized from spellcheck. Just use `<disambig action="ignore_spelling"/>`. I'm not sure why adding these expressions to spelling.txt, from where we can easily add words to our standard dictionaries, would help. This rather makes additional noise and mess in our files...

**Comment by f-knorr** [comment]
Well, I think MikeUnwalla does not always want to create a disambiguation rule for a simple expression. (I can understand this very well.) The spelling.txt approach is very intuitive: Just enter the word (now also expression) which you want to be ignored. (Creating an rule in disambiguation.xml causes much more overhead: unique id, name, manual tokenization etc.)

**Comment by MikeUnwalla** [comment]
@milekpl , my reasons are as @f-knorr wrote.

>  I'm not sure why adding these expressions to spelling.txt, from where we can easily add words to our standard dictionaries, would help. This rather makes additional noise and mess in our files...

If I understand correctly, you use spelling.txt for your special terms. But, each time that there is an LT update, don't you have to put your terms into spelling.text?

We have many one-word terms in spelling.txt. Are you suggesting that the one-word terms should be in disambiguation.xml? If no, then why should the multi-word terms be in disambiguation.xml? What difference do multi-word terms in spelling.txt make to your workflow?

**Comment by milekpl** [comment]
@MikeUnwalla My idea is to simply, over time, to gradually add terms from spelling.txt to the main dictionary so that they would be also used for suggestions, and keep multi-word units in the disambiguation.xml. The difference is small, as it's trivially easy to detect a space in the entry and thus ignore it when enlarging the dictionary. Again, I simply didn't see much of a problem here to be solved but maybe it's because I'm really used to using disambiguation.xml.

**Comment by MikeUnwalla** [comment]
@milekpl , In terms of 'clean' design, if spelling.txt is for words that will be added to the main dictionary, then the multi-word terms should indeed be in disambiguation.xml because they are not candidates for inclusion in the dictionary. Thus, I have no objection if you want to revert the rule from @f-knorr (perhaps, add a comment and URL reference to this discussion).

**Comment by danielnaber** [comment]
Not all words from `spelling.txt` will make it into the original dictionaries, at least not for all languages. The original dictionaries are derived from hunspell dictionaries, and their maintainers do not always accept all of our suggested additions. I think the way `spelling.txt` now works with multi-words is fine.

**Comment by milekpl** [comment]
@MikeUnwalla @danielnaber Sure, I don't want to revert this. All I'm saying is that it's not strictly necessary but if convenience is more important than parsimonious design, no problem for me.
