### ISSUE TITLE
[pt] Stop suggesting 'vosso' for 'de vocês' for pt-br

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#7007]
Hi,
   In the sentence "a casa de vocês é linda", LT suggests "a vossa casa". However, this is unusual in pt-br and I can't see a context where the suggestion should apply - it can remain for pt-pt and other varieties, if it is the case.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Sure!

@susanaboatto 

Could you move this rule to pt-PT, please?

Thank you!

**Comment by susanaboatto** [comment]
I'll loom into it, thanks for pointing it out 😃
