### ISSUE TITLE
[en] Update URLs for lexico.com before 26 August

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#7010]
Some URL elements and some comments refer to www.lexico.com.

A message on www.lexico.com tells me that on 26 August, lexico will redirect to dictionary.com.

Make sure that all URLs operate correctly (and better, change the URLs to dictionary.com).

**Comment by danielnaber** [comment]
I've updated the links. Not all pages seem to have survived the move, though, so some links are removed, and the remaining links haven't been systematically checked yet.

**Comment by danielnaber** [comment]
Should be fixed now, links have been updated, and the broken ones have been removed.
