### ISSUE TITLE
[LO add-on] Crash with today's nightly - 2022-08-17

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7024]
Hello @FredKruse 

I had been waiting for your fixes to test my thesis.

LibreOffice still hangs when I right-click in underlined words.

I tried to create a sample file, but it can't reproduce the hang, however, after a ton of tests I got a crash in LanguageTool:
![LO_ADDON_crash_LT_20220818](https://user-images.githubusercontent.com/5192600/185263763-68e20cda-8466-4db8-862f-e19270c5de91.png)

**Comment by FredKruse** [comment]
I generated an equal problem with one of my documents an analyzed and solve the bug.
@marcoagpinto Please test if the solution solves your problem with your thesis as well.

**Comment by marcoagpinto** [comment]
@FredKruse 

The thesis still hangs with today's nightly:
![lt_20220821](https://user-images.githubusercontent.com/5192600/185803398-ff2e0b59-00d1-4895-87a3-d8be8d26c02a.png)

Since you committed the fix three hours or so ago, maybe it is still not in the nightly, so I will test tomorrow.

**Comment by marcoagpinto** [comment]
Well, I have tested it, it still hangs LibreOffice.

See the video of it happening:

https://user-images.githubusercontent.com/5192600/185998346-92d3d1cb-dee7-47a6-9910-c4fef436be1a.mp4

I simply right-click over and over again, all I get is a LibreOffice hang.

**Comment by marcoagpinto** [comment]
@FredKruse 

😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢

**Comment by FredKruse** [comment]
I can reproduce the problem with a huge document of mine. 
The reason for the deadlock seems to be located deep in the structure of LO. LO blocks the reading of other interfaces, if a right mouse click is done and a request is sent to the grammar checker, to provide information about the underlined match. In some cases (more likely for huge documents) the internal functions of LT are blocked while they are reading data. But the request of the right mouse click needs the information, so the whole application hangs.
I solved the problem by a mechanism which detect, if an information request is running, then zero matches are returned. That means, as long, as your machine is busy reading information from LO, your right mouse click will not show the information about the underlined match, but (hopefully) LO doesn't hang anymore.
Currently, I have no other idea to solve the problem.
Please test it with next nightly tomorrow.

**Comment by marcoagpinto** [comment]
Thank you, @FredKruse 

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
Well,

Here is what I discovered:
If I open the thesis and scroll to the part of the video, and right-click in the blue underlined word the moment it gets underlined, LibreOffice hangs.

If I scroll to the word and wait with the task manager opened until CPU load becomes 3%-4% and then right-click in the word, it works.

I am using more than one core for grammar checking (LT option).

Does this help?

**Comment by FredKruse** [comment]
@marcoagpinto Does LO hang really? My experience is (with the last nightly) that LO doesn't react for a long time, when the CPU load is high, but there is no deadlock, means that the application react again, after a while.

**Comment by marcoagpinto** [comment]
@FredKruse 

Ahhhh… let me explain better: if I right-click in the underlined words while the CPU load is high, LibreOffice hangs, because it is still processing the grammar.

When the CPU load becomes 3-4% it means that LanguageTool has finished checking the grammar and if I right-click, LibreOffice doesn't hang.

Of course, that if it checks the grammar again it may happen.

**Comment by marcoagpinto** [comment]
"hang" means that the window gets grey and it says in the title bar that the app is not responding.

**Comment by marcoagpinto** [comment]
Was my explanation good?

😄

**Comment by marcoagpinto** [comment]
Haven't tested with today's build yet.

**Comment by FredKruse** [comment]
Yes, I understand it.
How many characters or words do your thesis contain? I think the problem is related to the size of the document.

**Comment by marcoagpinto** [comment]
@FredKruse 

It is in the video of the hang happening which I posted yesterday or two days ago.

Look at the bottom-left: "503 pages, 81869 words, 523865 characters" and I still must write at least 10-20 pages more.

The reason it has fewer words than normal is that I have hundreds of figures/graphics in it.

**Comment by FredKruse** [comment]
@marcoagpinto I'm a bit unhappy. I can't reproduce the bug. So, I Have once more some questions:

1. What happens, when you wait for one or two minutes, after the hanging appears like in the video? Get LO active again, or hangs it until the end of time?
2. If the window doesn't get active again: Could you please give me hints of special features inside your document? You wrote there are many figures and graphics in it. Are there also tables or other none flat text elements in it (technical, this makes significant differences)? Is it a multilingual document? Other special features?

**Comment by marcoagpinto** [comment]
@FredKruse 
1. I tried to wait some minutes, but this is a 6-core i7, and when it reached some time I closed LibreOffice in the window gadget, and it was sending the error to Microsoft (the usual Windows blah blah); 😄 
2. I changed the whole language to Portuguese before checking the grammar because I am uncertain if LanguageTool supports bilingual. It has tons of English text which appear as typos because of the language change;
2.1. Yes, it has tons of hand drawn figures, with text boxes and canvas in some, it has tons of tables, a few equations using the ink draw feature of Word 365, when you draw the equation it is converted automatically into the right format.

**Comment by marcoagpinto** [comment]
Also, some tables have inside hand drawn equations, not sure if this is useful to mention.

**Comment by FredKruse** [comment]
@marcoagpinto I found an internal mapping problem, but I'm not certain, if this solves your problem. Please test the new version.

**Comment by marcoagpinto** [comment]
@FredKruse 

Thank you, I will test it after the nightly is released today.

**Comment by marcoagpinto** [comment]
@FredKruse 

I was just testing it, and it seems to be fixed.

Thank you very much for all your efforts.
