### ISSUE TITLE
[pt] "sequer"

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#7026]
In the sentence
Ele sequer lembra meu nome.

LT says that a negation must precede "sequer". However, the sentence without the negation is fine in pt-br. Maybe the rule should apply to pt-pt only?

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Dear brother!

Sure, @susanaboatto could you take care of it?

Thanks!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by susanaboatto** [comment]
Done!
