### ISSUE TITLE
[pt] Idea for rule: “que vem” → “próxima” - 2022-08-18

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7027]
Hello @ricardojosehlima

Here is an easy to implement rule, I hope. 😄 

`"A licença acaba na sexta-feira da semana que vem."`

The idea is to replace “semana que vem” with “próxima semana” and it is supposed to work with any noun.

This will make redaction clearer.

Basically, it will search for NOUN/ADJ + “que” + “vem” and suggest “próxima” (or “próximo”, or plural) + NOUN/ADJ.

This is the basic concept, then it will have to be refined and have a fix here and there.

I was thinking about a rule ID, maybe
Rule ID: QUE_VEM_PROXIMA
Rule name: “Simplificar: Que vem → próxim(ao)(s)”
Rule message: “A perifrase poderá ser simplificada blah blah”

Ricardo, what is your opinion?

I still don't know how many hits it will give in 600 000 sentences, I just have a basic idea for the rule.

Thanks!

❤️ ❤️ ❤️ 

😄

**Comment by ricardojosehlima** [comment]
That looks great!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello dear brother!

It is coded!

https://github.com/languagetool-org/languagetool/commit/3b274d430eca0270ff20a35bfb2cb4890b0729f4

It gave tons of hits, a rule with a huge impact, I am too stressed to look carefully at the results… 😄 😄 😄 😄 😄 😄 

```
Portuguese (Portugal): 272 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[4.txt](https://github.com/languagetool-org/languagetool/files/9385510/4.txt)

**Comment by ricardojosehlima** [comment]
Yes, yes, yes! A great rule! Congratulations! I've scanned the file and found nothing wrong with it.

**Comment by marcoagpinto** [comment]
Thank you, dear brother!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
Reducing the number of words in a document makes the text more readable and there are universities that say that documents can only have up to N words, so we can write more with fewer words.
