### ISSUE TITLE
[pt] Rule: TAMBÉM_O_VERBO - 2022-08-21

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7035]
Hello @ricardojosehlima

This one is a bit more complex, but also more powerful as it will “clean” sentences with a higher complexity.

Look at this sentence:
`Eu fiz a formação do cartão Oney que é obrigatória.  Esta também é obrigatória?`

The rule would change it to:
`Eu fiz a formação do cartão Oney que é obrigatória.  Esta também o é?`

Well, maybe it is not very hard to code, I haven't tried yet.

So, basically, the rule will search for:
QUE + VERB1 + NC2 + PUNCTUATION and on the next following sentence ESTA + TAMBÉM + VERB1 + NC2 + PUNCTUATION
and replace the last VERB1 + NC2 with “o é”, “esta também O É.”

We can make it more complex by using both male+female+singular+plural

I am not sure about an ID, rule name and suggestion message for it, but it could be something like:
ID=TAMBÉM_O_VERBO (bad name chosen, I know)
ID NAME: `“Que + Verbo + NC → também o é”`
Suggestion message: `"Evite a redundância para melhorar a clareza das parafrases."`
… I know, I am terrible at choosing names 😢 
We could use some better names…

Thank you!

**Comment by ricardojosehlima** [comment]
Hi, nice rule! However, in pt-br, we leave the object out and the suggestion would be "Esta também é?" ("Esta também o é?" is possible, but will sound pedantic).

**Comment by marcoagpinto** [comment]
Ahhhhh… thanks!

I will work on it at 5am.

I will create both PT+BR, or better, I will create two suggestions for each sentence flagged.

If all results are valid, I will duplicate the rule and leave one suggestion for PT and in the duplicate the other suggestion for BR, then @susanaboatto can move it to pt-BR.

Ahhhh… better thinking, Susana could move the rule to PT and BR, and then delete the suggestion that isn't for the variant.

😄 

Meanwhile, I had one more idea for a rule, or two… I have written it down.

**Comment by marcoagpinto** [comment]
I have been completely insane, all little thing makes me think about new rules.

**Comment by marcoagpinto** [comment]
@jaumeortola @udomai @tiff 

Hello!

I couldn't wait for 5am to implement the rule, but it is giving errors.

This is just the initial concept of it:
```
    <!-- TAMBÉM VERBO NOME_COMUM também [o] é -->
    <rule id='TAMBÉM_O_VERBO' name="Simplificar (redundância): Também + Verbo + NC/ADJ → também [o] é">
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, fully revised by Susana Boatto, Portuguese rule 2022-08-22 (25-JUL-2022+) -->
      <!--
	  Eu fiz a formação MULTIBANCO que é obrigatória. Esta também é obrigatória? → Eu fiz a formação MULTIBANCO que é obrigatória. Esta também o é?  
      -->
      <pattern>
		<token postag='NC.+|AQ.+' postag_regexp='yes'/>
	    <token>que</token>
	    <token postag='V.+' postag_regexp='yes'/>
		<token postag='NC.+|AQ.+' postag_regexp='yes'/>
		<token postag='_PUNCT' postag_regexp='no'/>
        <marker>
          <token regexp="yes">ess[ae]s?|est[ae]s?</token>
		  <token>também</token>
		  <token><match no="2"/></token>
		  <token><match no="3"/></token>
        </marker>
      </pattern>
      <message>Evite a redundância para melhorar a clareza da perífrase.</message>
      <suggestion>\6 também o \8</suggestion>
      <example correction="Esta também o é">Eu fiz a formação MULTIBANCO que é obrigatória. <marker>Esta também é obrigatória</marker>?</example>
    </rule>
```

TESTRULES PT says:

```
Testing rule 2700...
Skipped 0 rules for variant language to avoid checking rules more than once
2759 rules tested.
Exception in thread "main" org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule TAMBÉM_O_VERBO[1] in file /org/languagetool/rules/pt/grammar.xml: "Eu fiz a formaç?o MULTIBANCO que é obrigatória. Esta também é obrigatória?"
Errors expected: 1
Errors found   : 0
Message: Evite a redundância para melhorar a clareza da perífrase.
Analyzed token readings: [/SENT_START*] Eu[eu/PP1CSN00*]  [ /null*] fiz[fazer/VMIS1S0]  [ /null*] a[a/SPS00]  [ /null*] formaç?o[formaç?o/NCFS000]  [ /null*] MULTIBANCO[multibanco/AQ0MS0,multibanco/NCMS000]  [ /null*] que[que/CS,que/PE0CN000,que/PR0CN000,que/PT0CN000]  [ /null*] é[ser/VMIP3S0]  [ /null*] obrigatória[obrigatório/AQ0FS0] .[./_PUNCT*]  [ /null*] Esta[este/DD0FS0,este/PD0FS000]  [ /null*] também[também/CC,também/I,também/RG]  [ /null*] é[ser/VMIP3S0]  [ /null*] obrigatória[obrigatório/AQ0FS0] ?[?/SENT_END*,?/_PUNCT*]
Matches: []
        at org.languagetool.rules.patterns.PatternRuleTest.addError(PatternRuleTest.java:382)
        at org.languagetool.rules.patterns.PatternRuleTest.testBadSentences(PatternRuleTest.java:518)
        at org.languagetool.rules.patterns.PatternRuleTest.lambda$testGrammarRulesFromXML$1(PatternRuleTest.java:417)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Running disambiguator rule tests...
Running disambiguation tests for Portuguese...
100...
200...
300...
334 rules tested (188ms)
```

The debugging text I am using in the standalone tool to help me out:
```
Eu fiz a formação MULTIBANCO que é obrigatória. Esta também é obrigatória? → Eu fiz a formação MULTIBANCO que é obrigatória. Esta também o é?

1. MULTIBANCO
2. que
3. é
4. obrigatória
5. .
6. Esta
7. também
8. é
9. obrigatória
10. ?
```

**Comment by marcoagpinto** [comment]
Could one of you help?

Thanks!

**Comment by marcoagpinto** [comment]
I am completely brain toasted and can't figure out what is wrong.

**Comment by susanaboatto** [comment]
Could it be that this is happening because there is a `.` in the example, so it reads as two separate sentences?

**Comment by marcoagpinto** [comment]
@susanaboatto I thought about that, but then the first thing that came to my mind was that the abbreviation rules deal with periods, so I thought it was possible.

**Comment by marcoagpinto** [comment]
There must be a way to make it work.

**Comment by marcoagpinto** [comment]
@susanaboatto 

Is it correct in this case to separate the sentences with a coma instead of period?```

"Eu fiz a formação MULTIBANCO que é obrigatória. Esta também é obrigatória?"
"Eu fiz a formação MULTIBANCO que é obrigatória, esta também é obrigatória?"
```

**Comment by susanaboatto** [comment]
@marcoagpinto I think it only works with abbreviations because they are described in segment.srx, no? So with that we can separate which of those can or cannot finish sentences. But in this example, there's no abbreviation, so I don't think it works.

Using a comma in the example would still detect the mistake you're trying to catch, so it should be fine. It's not the best way to write it, though. Ideally, a `;`, `...` or a dash would be better. Maybe we can make another rule to enhance that? 😅

**Comment by marcoagpinto** [comment]
@susanaboatto 
You are right, without a period, it doesn't sound so well, but I will try it out in a few hours to see the results… better than nothing.

**Comment by marcoagpinto** [comment]
@ricardojosehlima @susanaboatto 

Committed:
https://github.com/languagetool-org/languagetool/commit/ab13c33552d8754084c816c15379bdd63539944f

0 hits in 600 000 which was expectable since the original idea was to have two sentences separated with a period, not with other punctuation, but it is better than nothing.

@susanaboatto 
Could you revise the rule by making some changes in the rule name and then moving the _BR to pt-BR and the _PT to pt-PT?

Thank you very much!
