### ISSUE TITLE
[DE]Fehlalarm Kommasetzung

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#7036]
Moin liebes LanguageTool-Team

Sie sagte **zu** mir bedrückt, dass sie sich in sie verliebt hat.
LT: "Hier scheint ein Komma zu fehlen."

Sie sagte **zu** mir bedrückt: „Ich habe mich in dich verliebt.“
LT: "Hier scheint ein Komma zu fehlen."

Hier gehört kein Komma hin, aber warum das LanguageTool hier ein Komma vorschlägt, verstehe ich nicht.

Bitte beheben.

Grüße Dallun511

**Comment by St-ac-y** [comment]
behoben https://github.com/languagetool-org/languagetool/commit/760e757b3294ce4f0a0bf1c97996dd0517bcbe1e
