### ISSUE TITLE
suggestion: provide dockerimage for languagetool

### ISSUE THREAD

**Issue by silvio** [languagetool-org/languagetool#704]
Hi,

I'm the "maintainer" of [silvio/docker-languagetool](https://github.com/silvio/docker-languagetool). Maybe its a good idea to have the dockerfile in the languagetool repository?

Some pros:

* possible to have a docker image to every commit (autobuild via docker service (github service) on every push)
* with the previous point: build a integration test infrastructure.
* docker container for all releases (pull it via `docker pull languagetool-org/3.6`)

What do you think?

**Comment by danielnaber** [comment]
Hi Silvio, could you maintain the file and answer bug reports even when the file is in our repo? If so, we could host it as well I think. On the other hand, we could just link to your github project.

**Comment by silvio** [comment]
@danielnaber: All pro's are only possible if the dockerfile is in the languagetool repo. The mentioned points are importend for the project?

Currently I have the rss feed of [languagetool releases] in my feedreader. If I read the rss feed and if I have time and I don't forget it I upgrade the versionnumber.

[languagetool releases]: https://github.com/languagetool-org/languagetool/releases.atom

**Comment by danielnaber** [comment]
I don't think these points are important for LT as a project, but having an LT docker container is of course useful for some users.

**Comment by Jotschi** [comment]
We have also create a docker image for the language tool. It would be good to merge both repos. The Image we use is directly build on docker hub and uses the alpine image (much more lightweight compared to debian).

https://github.com/gentics/languagetool-docker

**Comment by Jotschi** [comment]
@silvio Interessting. Did those crashes only happen with french? I did not yet encounter any issue but I'll keep that in mind. Thanks for the hint.

**Comment by danielnaber** [comment]
I'm closing this issue as the docker images are now there and linked.
