### ISSUE TITLE
[pt] Idea for rule: “até NÚMERO” - 2022-08-23

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7040]
Hello @ricardojosehlima

This was other rule idea I came up with while revising my thesis.

Imagine you have a sentence similar to this:
`Tudo bate certo e quatro ou menos variáveis são suficientes na equação.`

It could suggest replacing “quatro ou menos” with “até quatro”:
`Tudo bate certo e ATÉ QUATRO variáveis são suficientes na equação.`

It is just a basic idea, not sure how many hits it will provide and the exceptions yet.

Rule ID: ATE_NUMERO_NUMERO_OU_MENOS
Rule name: “Simplificar: NÚMERO + ou menos → até NÚMERO”
Suggestion: “A perifrase poderá ser simplicada blah blah”

Does it sound good?

Thanks!

**Comment by ricardojosehlima** [comment]
Hi, in pt-br the target construction is rare, but iy may be worth a try.

**Comment by marcoagpinto** [comment]
Thanks!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Here it is:
https://github.com/languagetool-org/languagetool/commit/2c1db15dde9e90b052f8e57538864977b93263ce

It gives zero hits in 600 000 sentences.
