### ISSUE TITLE
[pt] Strange suggestion for pt-br

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#7041]
In
   Ainda que falando baixo, conseguiu ser ouvido.

   LT suggests "Ainda que (falando") and says that "Hipóteses introduzem o conjuntivo."
   This construction is fine in pt-br and should not be flagged, but if the explanation (and the suggestion) makes sense in pt-pt, then the rule can remain for it.

**Comment by marcoagpinto** [comment]
ahhhh…

Here it sounds well too, I will look at it at 5am…

❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
Maybe I need to create an antipattern.

**Comment by marcoagpinto** [comment]
This will require generating a wordlist against 600 000 sentences and look at the results and attempt to fix all cases.

**Comment by ricardojosehlima** [comment]
why not eliminate the rule?

**Comment by ricardojosehlima** [comment]
it's not onlt for 'falando' seems to be to any verb

**Comment by marcoagpinto** [comment]
ahhhhhhh… ok… @susanaboatto Can you help us with removing it, if you see no real use for it?

Thanks!

**Comment by marcoagpinto** [comment]
Susana will kill me, I always ask her to do the “dirty” work… lolololol 😄 😄 😄 😄 😄 😄 😄 😄 😄 😄 😄

**Comment by susanaboatto** [comment]
@marcoagpinto it's what I'm here for! I have set it as temp off, so I can take a look at it and see if it can be improved. If not, then I will disable it 😄
