### ISSUE TITLE
[en] Chunker improvement

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#7044]
Is it possible change the behaviour of the chunker?

With a plural noun in a singular noun phrase, the chunker incorrectly gives the last word the chunk `E-NP-plural`. Some examples:

The aircraft maintenance **manager** is in the hangar.
Does your box **converter** operate correctly?
The happy **sheep** is grazing in the field.
The shiny new **aircraft** was on the runway.
I’d like a fish **pie** and a kilo of sprouts.

(Only a very small proportion of plural noun phrases end with a singular noun. Example, ‘sergeants major’: https://www.merriam-webster.com/dictionary/sergeants%20major).

**Comment by danielnaber** [comment]
I have made a change locally. The change wasn't difficult, but at least 12 tests break now. These seem to be cases where the chunker is wrong and has always been, but now it causes an error. One example:

> **Adults average** in length; the largest recorded specimen weighed 2.65 kg.

"Adults average" is considered a noun phrase, and now it's considered a singular noun phrase, breaking `ADJECTIVE_IN_ATTRIBUTE`. I won't have time to fix these cases. @MikeUnwalla, if you're interested in working on those cases, I could commit my changes to a branch. Of course, more issues might show up after those 12 tests are fixed...

**Comment by danielnaber** [comment]
The work-in-progress branch (which tests that don't work) is now available here: https://github.com/languagetool-org/languagetool/tree/issue-7044-chunker

**Comment by MikeUnwalla** [comment]
@languagetool-org/developers, if @danielnaber is out of the office today, can one of you please look at https://github.com/languagetool-org/languagetool/pull/7050 ? Many thanks. I think that I have possibly not used GitHub correctly. I am not sure what to do.

**Comment by danielnaber** [comment]
PR is be merged now.

**Comment by MikeUnwalla** [comment]
@danielnaber, thank you.

I know about more chunker errors. Do you want them? If yes, I will make a new issue.

**Comment by danielnaber** [comment]
> I know about more chunker errors. Do you want them? If yes, I will make a new issue.

We cannot really fix them, but maybe we can add antipatterns, so please send them.
