### ISSUE TITLE
[pt] Change lemma for ordinal numbers

### ISSUE THREAD

**Issue by susanaboatto** [languagetool-org/languagetool#7048]
Hi there!

One of the problems with `GENERAL_GENDER_AGREEMENT_ERRORS` is that ordinal numbers don't all have the same lemma for their tags. For `1o` or `1º` to be changed into `1a` or `1ª` they need to have the same lemma. But I don't know how to do this for all the numbers. Ideally, `[number]a` or `[number]ª` would have `[number]º` as a lemma. [This ](https://github.com/languagetool-org/languagetool/commit/7af58dfb977f1a1744f2f040a2c7640707d97c02)was my attempt, but of course it didn't work, because the lemma needs to match the number (so I reverted it). Can anybody help? @marcoagpinto @danielnaber 

If this isn't possible, I will add another rule in `GENERAL_GENDER_AGREEMENT_ERRORS` to fix it. The `GENERAL_NUMBERS_AGREEMENT_ERRORS` rule might need one too, @marcoagpinto.

**Comment by danielnaber** [comment]
Do you even need POS tags for that? `(\d+)º` would match any number followed by `º` and can then be replaced by a suggestion `\1ª` I think. See for examples this German rule (doesn't use numbers, but that shouldn't matter):

```
            <rule>
                <regexp>\b(ungefähr) (genau(so)?)\b</regexp>
                <message>&unstimmig; Bitte wählen Sie zwischen <suggestion>\1</suggestion> und <suggestion>\2</suggestion>.</message>
                <example correction="ungefähr|genauso">Die sehen <marker>ungefähr genauso</marker> aus.</example>
                <example correction="ungefähr|genau">Diese Wörter haben <marker>ungefähr genau</marker> dieselbe Bedeutung.</example>
                <example>Diese Wörter haben dieselbe Bedeutung.</example>
            </rule>
```

**Comment by susanaboatto** [comment]
You are right—that was the solution I had in mind, but I was just wondering if maybe there was a shortcut so that the same mistake would also be quickly fixed in other rules like `NUMBERS_AGREEMENT`.

@marcoagpinto since you're taking care of `NUMBERS_AGREEMENT`, would you mind checking if there are problems with the suggestions for ordinals there too? 😅

**Comment by marcoagpinto** [comment]
@susanaboatto @danielnaber 

I agree with Susana, if we could have extra power and simplicity using the disambiguator, we should use it.

Unfortunately, I don't have a clue on how to code it, I usually ask for the help of  @jaumeortola 

A year or so ago I tried to implement something in it and I failed and it was a bad experience for me.

**Comment by marcoagpinto** [comment]
@danielnaber @jaumeortola @susanaboatto @ricardojosehlima

`O algoritmo é muito bom, precisão 100%.`

It triggers a gender error.

One more reason for ordinals in the disambiguator.

When does Jaume return from holidays?

**Comment by jaumeortola** [comment]
> Ideally, [number]a or [number]ª would have [number]º as a lemma.

@susanaboatto We can add the POS tags to added.txt for a limited range of usual numbers (1-20 or 1-100). 
If you really need this for all numbers, we would have to make special changes in the tagger and the synthesizer (in Java). I haven't done it in other languages because high ordinal numbers are unusual in practice. The ordinals are all tagged in disambiguation.xml, but there are no suggestions in case of agreement errors.

**Comment by susanaboatto** [comment]
@jaumeortola Thanks for your input, that makes sense. I will add ordinals to added.txt within a limited range, then.
