### ISSUE TITLE
[pt] Rule idea: “PENSAR EM” → “PONDERAR” - 2022-08-29

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7052]
Hello @ricardojosehlima

I have come up with an idea for a style rule (as usual).

Look at this sentence:
`Estou a pensar em comprar o PC da televisão.`

It would suggest replacing “a pensar em” with “a ponderar”:
`Estou a ponderar comprar o PC da televisão.`

This is the basic concept, it will require some refinement in the process, and it will accept “pensar” as inflected (all forms).

Rule ID: PENSAR_EM_PONDERAR
Rule name: “Simplificar: pensar em → ponderar”
Rule suggestion: not sure if it should say to remove redundancy or to simplify the grammar.

Is it a good idea?

Thank you, my dear brother!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by ricardojosehlima** [comment]
Hi, in pt-br "ponderar' is a very formal verb. The rule if built should apply only to academic texts. 
Also, you aim "pensar em" only or its variants also (pensei, pensamos, etc)?

**Comment by marcoagpinto** [comment]
"Inflected" means all variants.

😄 

Ahhh… so it is only for academic texts.

Thank you, I will code it at 5am as usual.

❤️ ❤️ ❤️ ❤️ 

And minutes ago I came up with one more idea for a rule, I will share it tomorrow after this one is finished.

**Comment by ricardojosehlima** [comment]
Sorry, my bad, am tired, read but didn't process it...

**Comment by marcoagpinto** [comment]
It's okay 😄

**Comment by marcoagpinto** [comment]
Hello @ricardojosehlima 

I couldn't wait for 5am.

I have coded the rule:
https://github.com/languagetool-org/languagetool/commit/1226cab117e816853637c055f45f8d44e62da31f

It gives tons of hits, but in my quick view of the results, it seems they are all valid.
```
Portuguese (Portugal): 290 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[1.txt](https://github.com/languagetool-org/languagetool/files/9456849/1.txt)

**Comment by ricardojosehlima** [comment]
Hi yes all looks fine. One question though. Will it apply to any text? Because the suggestion seems to indicate that it'll.
If so, for pt-br it's not a good idea.

**Comment by marcoagpinto** [comment]
Ahhhh… I will add the tag “picky”.

Then, it will only suggest if people turn on the picky mode.

Or should I move it to pt-PT?

**Comment by marcoagpinto** [comment]
Well, I guess I will move it to pt-PT.

**Comment by marcoagpinto** [comment]
Done!

https://github.com/languagetool-org/languagetool/commit/eb451e4cef729266a021a21d4636071ef2cb963a
https://github.com/languagetool-org/languagetool/commit/97a93547397fb7e88ebb27705665bfe28345cbdc

Moved to pt-PT.

**Comment by ricardojosehlima** [comment]
Ok, but for pt-br in the picky mode it would work too.

**Comment by marcoagpinto** [comment]
Moved:
https://github.com/languagetool-org/languagetool/commit/0d154f6255890ce74c05075002d278a3e4f7cf89

https://github.com/languagetool-org/languagetool/commit/a14a044a3820ca296652c9480886a24cc234b8f3

4:30am: I am now going to prepare the release of the British Dictionary.
