### ISSUE TITLE
[pt] Rule idea: “que está/estão em → em” - 2022-08-31

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7057]
Hello @ricardojosehlima

Another idea for a rule:
`As máscaras de host que estão em uso são as adequadas.`

que + está/estão + em + NC → em NC

For example, it would suggest changing the sentence above to:
`As máscaras de host em uso são as adequadas.`

Is it a good idea?

Maybe the suggestion message should be the simplify one.

**Comment by ricardojosehlima** [comment]
Hmm, let's see some sentences:
O pai dos filhos que estão em casa --> O pai dos filhos em casa (looks vague to me)
Vou falar com um amigo que está em casa --> Vou falar com um amigo em casa (ambiguous!?)

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I am working on it since midnight or so.

It generates false positives, which I am trying to fix.

I also found out that there was a rule already for this: QUE_ESTAR_CONTRACAO_PREPOSICAO

After I finish removing the false positives, I will make it work with contractions/prepositions and replace the old rule with this one.

Thanks!

**Comment by marcoagpinto** [comment]
It is harder than I thought 😄  😄  😄  😄  😄  😄  😄

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I have just (finally) finished it:
https://github.com/languagetool-org/languagetool/commit/cdd87b8b738d94a77ced0060b036d7f450544dad

I believe to have removed all false positives:
```
Portuguese (Portugal): 18 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[22stable.txt](https://github.com/languagetool-org/languagetool/files/9462397/22stable.txt)

**Comment by marcoagpinto** [comment]
I will now have a bottle of cola to celebrate.

😄 😄 😄 😄 😄 😄 😄 😄 😄 😄 😄 😄 😄

**Comment by ricardojosehlima** [comment]
Cheers! All sentences look fine for me

**Comment by marcoagpinto** [comment]
Thank you, Ricardo.

At night, I will move the pt-PT one from yesterday to the main PT using "picky=on", just like you suggested.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by ricardojosehlima** [comment]
Ok but my suggestion for the picky mode was for the pensar-ponderar rule. This one (que está) can remain in regular mode.
