### ISSUE TITLE
[pt] LT fails to correct some verbal agreement errors

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#7059]
While LT correctly flags 1 and 2 as wrong:
Com isso, eles vai amanhã (eles vão)
Com isso, vocês vai comigo. (vocês vão)

It fails in 3 and 4:
Com isso, eles vai sair amanhã. (nothing decteded).
Com isso, vocês vai saber isso. (nothing detected).

Maybe because vai is auxiliar?

**Comment by marcoagpinto** [comment]
Verbs is a hard one for me 😄 

@susanaboatto 
Can you give a little hand?

Thanks!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I have several verb agreement sentences flagged in my thesis, I have been leaving them for last to ask for your suggestions, however I have been fixing false positives in other rules like NUMBER and GENDER agreement.

**Comment by ricardojosehlima** [comment]
Yes, verb agreement is hard, much more because of the way LT lemmatizes and the lack of a parser.
But this one looks simpler: is the rule applying to auxiliaries? Or is the verb in the infinitive playing some role in the rule causing this confusion?

**Comment by marcoagpinto** [comment]
Ahhhh...

Ricardo, I will take a look at it at 5am.

Tomorrow is release day for the British dictionary, the monthly update, I will work on the dictionary release during the night.

**Comment by marcoagpinto** [comment]
And if I get delayed in the dictionary, Susana will help out when she starts working in the morning.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by susanaboatto** [comment]
Hi all,

I have added an exception to an antipattern in the `GENERAL_VERB_AGREEMENT` rule. Let's see if this fixes it.

https://github.com/languagetool-org/languagetool/commit/9909741e649c7894fe4e6ae77318b96f4eb3444d

**Comment by marcoagpinto** [comment]
@susanaboatto 

Good morning!

Thank you!

❤️ ❤️ ❤️ ❤️ ❤️
