### ISSUE TITLE
[de] Detect commas placed incorrectly

### ISSUE THREAD

**Issue by madblobfish** [languagetool-org/languagetool#706]
Hello,

I thought it would be nice to have languagetool detect incorrect commas.
The following sentence gives me no errors in version 3.7

Aus, diesen, Gründen, wurde, es, getan.

Thank you for your work :)

**Comment by orschiro** [comment]
Good point. 

I never noticed this. :-)

How does one actually go about this and add a new rule?

I am completely new to this.

That's why I am asking. :-)

**Comment by madblobfish** [comment]
Hi orschiro, this issue isn't the right place to discuss creating new rules...
Here is more information on that topic: http://wiki.languagetool.org/#toc5

**Comment by orschiro** [comment]
Thank you!

**Comment by danielnaber** [comment]
> Aus, diesen, Gründen, wurde, es, getan.

I'm not sure why this should give an error - we try to catch errors that people actually make, not artificial ones. If you have real-world examples of incorrect commas, feel free to report the here.

**Comment by JustGregory** [comment]
Well, Daniel. That example from @madblobfish may have been taken to extremes, but I think it is no less valid for depicting the "problem". I would agree with the need for this issue, for the simple fact that I have checked some texts in OpenOffice or LibreOffice for years, and have on occasion come across this same thing (always texts typed from other people, of course). I don't think that example always needs to be presented as an "error", but maybe as a "personal preference" or maybe "troubling usage" of punctuation.

I, for one, will intentionally, specifically, only use commas and other punctuation as I have been taught! (I have always been at the top of my class in this regard....)

**Comment by madblobfish** [comment]
I resorted to removing all my commas with a script, languagetool then helps me find the ones which should be keept.
