### ISSUE TITLE
[en] Update British Dictionary - V3.1.2 - 2022-09-01

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7060]
Hello @yakovru 

I have updated the dictionary in GitHub:
https://github.com/marcoagpinto/aoo-mozilla-en-dict

Could you please add it to LanguageTool for the official release at the end of the month?

Thanks!

**Comment by yakovru** [comment]
Hello @ marcoagpinto

I will update the dictionary tomorrow.

**Comment by marcoagpinto** [comment]
Thank you, @yakovru
