### ISSUE TITLE
[pt] Idea for rule: “como é o caso do nosso” → “como é o nosso” - 2022-09-01

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7061]
Hello @ricardojosehlima

I came up with an idea for a rule.

The basic idea is to simplify sentences.

Right now, I am stressed and can't reason properly to give a good example of the rule in action, but the idea is to check for:
como + é/são + o/os/a/as + caso/casos + do/dos/da/das +pronoun
and remove the “caso do”
resulting in:
“como é o nosso”
“como é o vosso”
“como é o seu”
etc. depending on the pronoun.

What is your opinion?

Do you have any clue about a Rule ID and Rule Name for it?

The rule name could start with: “Simplificar: blah blah”

Thanks!

**Comment by ricardojosehlima** [comment]
Hi,
  It's worth a try!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is done!!!!

https://github.com/languagetool-org/languagetool/commit/50c1c7c9f553304fb855b81e76aafb0309854eb4

```
Portuguese (Portugal): 17 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```
[_1.txt](https://github.com/languagetool-org/languagetool/files/9474014/_1.txt)

**Comment by ricardojosehlima** [comment]
All fine for me

**Comment by marcoagpinto** [comment]
Thank you @ricardojosehlima
