### ISSUE TITLE
Languagetool on chess notation: Portuguese (and others?)

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#7063]
It looks like LT is fine with chess notation in English: no correction for Nf3, Be6, Qd5.
But in Portuguese, all notations are flagged as orthographic errors.
As the notation is very regular, maybe its pattern could be added as exception (or some other solution).
What we have:
- the pieces: D, R, C, B, T (all in capital letters)
- the letters: abcdefgh
- the numbers: 12345678

A regular expression could then be:
[DRCBT]?[abcdefgh][12345678]

The ? is because there are moves like e6, d4, c5 that are legitimate (pawns don't have a symbol of their own).

And a chess player would be thankful not seeing LT flagging every move in a game!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

They will be flagged as typos.

Each word will have to be added to spelling.txt .

**Comment by marcoagpinto** [comment]
unless there is something I don't know 😄

**Comment by marcoagpinto** [comment]
Unless… @jaumeortola maybe it is a disambiguator thing which you can implement?

Or @susanaboatto can implement it there?

I don't touch the disambiguator because I broke the build the first time I tried to improve it.

Thanks!
