### ISSUE TITLE
[pt] A question on a simplification rule

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#7064]
For
Muitos fatores contribuíram para ter acontecido desse modo.
LT suggests
Muitos fatores contribuíram para acontecer desse modo.

However, 'ter acontecido' is about the past while 'acontecer' doesn't necessarily refer to a time.
For me, the suggested sentence is not synonymous with the first.

**Comment by marcoagpinto** [comment]
That is why the suggestion says, “In certain contexts, this sentence may be simplified.”.

What I really need to do is to rewrite rules like that, that say “in certain contexts blah blah blah”.

But, back then, I didn't have the knowledge I now do.

**Comment by marcoagpinto** [comment]
well, maybe a little antipattern will fix this example.

I will do it at 5am 😄 

Thank you for the feedback!

**Comment by marcoagpinto** [comment]
luckily we have antipatterns to bypass the obstacles.

**Comment by ricardojosehlima** [comment]
Ok, but I still can't see a context where it can be applied...

**Comment by marcoagpinto** [comment]
I will generate a wordlist against 600 000 sentences at night, one before and other after the antipattern, then we will be able to see better.

**Comment by ricardojosehlima** [comment]
I'm still betting that the rule won't apply to many verbs (if not all)...
Eu espero ter falado a verdade --> Eu espero falar a verdade (??)
and so on

**Comment by marcoagpinto** [comment]
😄 🤗 ❤️

**Comment by susanaboatto** [comment]
I think we could remove the word `para` from this rule and only keep `por`.

**Comment by ricardojosehlima** [comment]
@susanaboatto yes! The rule is fine for "por", not for "para"

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Dear brother,

😄 

I have rewritten the rule last night.

❤️ ❤️ ❤️ ❤️ ❤️
