### ISSUE TITLE
Updating rules at runtime, externally

### ISSUE THREAD

**Issue by louis030195** [languagetool-org/languagetool#7065]
Hello !

Is it possible to update the rules at runtime, "externally"?
If so, is it possible to just edit the XML and the process will reload the rules in memory, I guess?
Or add rules via the API? (I don't see an endpoint for that, though).
Is there any other way?

I guess the other option would be to edit the XML and restart the instance, but that's less interesting for speed issues.

Apologize if there were any other issues / docs about this topic that I couldn't find.

Thanks!

**Comment by danielnaber** [comment]
Adding rules at runtime is only possible via [the Java API](https://languagetool.org/development/api/), not via the HTTP API. Changing the XML file requires a reload of the LT process.
