### ISSUE TITLE
languagetool-wikipedia check-data command --also-enable-categories is buggy

### ISSUE THREAD

**Issue by sdeprez** [languagetool-org/languagetool#707]
The command `check-data` has an argument `also-enable-categories` which expect a CSV like argument of category IDs to activate, however because of [this line](https://github.com/languagetool-org/languagetool/blob/master/languagetool-wikipedia/src/main/java/org/languagetool/dev/dumpcheck/SentenceSourceChecker.java#L247):

```
 if (rule.getCategory().getName().equals(categoryId)) {
```

The check is actually made on the category names, which does not work. A simple fix is to change that line to:

```
 if (rule.getCategory().getId().equals(categoryId)) {
```

So we can use the command as expected: 
```
java -jar languagetool-wikipedia.jar check-data --file dump.xml --language en --also-enable-categories TYPOS
```

Thanks!

**Comment by danielnaber** [comment]
Thanks for your bug report, I've fixed this now. The fix will be part of tomorrow's daily build.
