### ISSUE TITLE
[pt] Idea for rule: "vai desde os anos" → "remonta aos anos" - 2022-09-05

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7070]
@ricardojosehlima

Hello dear brother,

I came up with an idea for a rule:
`“Isto acontece desde os anos 1990s.” `→ `”Isto remonta aos anos 1990s”`

This is the basic idea.

Verb + “desde” + “a(s)/o(s)” + expressions_of_time_entitity → “remonta aos” + expression_of_time_used

I'm not sure if it will work with all verbs, we could start with V.+ and then see if it creates too many false positives.

Is it a good idea for a rule?

Could you suggest a good rule ID, rule name and suggestion?

Thanks!

**Comment by ricardojosehlima** [comment]
Hi good idea, may be restricted to 'acontecer', but who knows?

**Comment by marcoagpinto** [comment]
Ricardo!

❤️ ❤️❤️❤️❤️❤️❤️

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

You were right, the only real positive happened with the verb “acontecer”:

```
Title: <plaintext>
1.) Line 1, column 30, Rule ID: DESDE_TEMPO_REMONTA_TEMPO[1]
Message: Esta perífrase poderá ser simplificada.
Suggestion: remonta ao ano
Rule source: /org/languagetool/rules/pt/grammar.xml
Nosso Principal projeto, que acontece desde o ano 2000, é realizado em comemoração ao dia Mundial do Meio Ambiente, instituido pela ONU no dia 5 de J...
```

```
Portuguese (Portugal): 16 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```


[0.txt](https://github.com/languagetool-org/languagetool/files/9492138/0.txt)

At least we can write there the possible verbs and there won't be any false positives.

Do you have any ideas for more verbs?
1. acontecer;
2. ocorrer;
3. ir;
4. ????

Thanks!

**Comment by marcoagpinto** [comment]
https://dicionario.priberam.org/acontecer

“ [Verbo unipessoal] = ADVIR, OCORRER, SOBREVIR, SUCEDER”

To me these verbs don't sound very good (except “ocorrer”), what is your opinion?

**Comment by marcoagpinto** [comment]
This is how the rule looks now:

```
    <!-- ACONTECE DESDE OS ANOS remonta aos anos -->
    <rule id='DESDE_TEMPO_REMONTA_TEMPO' name="Simplificar: Desde tempo → remontar tempo" type="style">
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2022-09-05 (25-JUL-2022+) -->
      <!--
      Isto acontece desde os anos 1990s. → Isto remonta aos anos 1990s.
      -->
      <pattern>
        <marker>
          <token regexp='yes' inflected='yes'>acontecer|ocorrer|ir</token>
          <token>desde</token>
          <token postag='DA.+' postag_regexp='yes'/>
          <token regexp='yes'>&expressoes_de_tempo_simples;</token>
        </marker>
      </pattern>
      <message>Esta perífrase poderá ser simplificada.</message>
      <suggestion><match no='1' postag='V.+' postag_regexp='yes'>remontar</match> <match no='3' postag='DA0(..)0' postag_replace='SPS00:DA0$10'>a:o</match> \4</suggestion>
      <example correction="remonta aos anos">Isto <marker>acontece desde os anos</marker> 1990s.</example>
    </rule>
```

**Comment by ricardojosehlima** [comment]
> @ricardojosehlima
> 
> You were right, the only real positive happened with the verb “acontecer”:
> 
> ```
> Title: <plaintext>
> 1.) Line 1, column 30, Rule ID: DESDE_TEMPO_REMONTA_TEMPO[1]
> Message: Esta perífrase poderá ser simplificada.
> Suggestion: remonta ao ano
> Rule source: /org/languagetool/rules/pt/grammar.xml
> Nosso Principal projeto, que acontece desde o ano 2000, é realizado em comemoração ao dia Mundial do Meio Ambiente, instituido pela ONU no dia 5 de J...
> ```
> 
> ```
> Portuguese (Portugal): 16 total matches
> Portuguese (Portugal): 582235 total sentences considered
> Portuguese (Portugal): ø0.00 rule matches per sentence
> ```
> 
> [0.txt](https://github.com/languagetool-org/languagetool/files/9492138/0.txt)
> 
> At least we can write there the possible verbs and there won't be any false positives.
> 
> Do you have any ideas for more verbs?
> 
>     1. acontecer;
> 
>     2. ocorrer;
> 
>     3. ir;
> 
>     4. ????
> 
> 
> Thanks!

Hi, no idea. Pity only for acontecer but that's already something!
