### ISSUE TITLE
[pt] Verb question - 2022-09-10

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7084]
Hello @ricardojosehlima

The following sentence:
`É impossível aos humanos discernirem o que está representado neles.`

LanguageTool complains that the verb must match the subject, to replace “discernirem” with “discernir”.

But the subject, or whatever it says, is “humanos”, right?

So, “humanos” is plural, and the verb is plural?

Thanks!

**Comment by ricardojosehlima** [comment]
It's a tricky issue. Everyone feels that humanos is the subject. However it is preceded by a preposition and then according to tradition cannot be the syntactic subject, thus no agreement.
The correction of LT is ok but the explanation could be in line with what I wrote.

**Comment by marcoagpinto** [comment]
Ahhhhh… Thank you!

I will fix it soon.

😄

**Comment by marcoagpinto** [comment]
As you can see, verbs aren't my strong thing.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Ahhhh… sorry… I slept like a rock with the Xanax…

Could you please tell me in Portuguese what I should change/add here?:
`<message>O verbo concorda com o núcleo do sujeito.</message>`

Thanks!

**Comment by ricardojosehlima** [comment]
"De acordo com a gramática tradicional, o verbo permanece no singular, visto que o "sujeito" está preposicionado."

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Done!

https://github.com/languagetool-org/languagetool/commit/db9133e2c590801198b75dea93d5c540f6274bff

Thanks!
