### ISSUE TITLE
[LibreOffice -Add-on] Severe crashes on document - 2022-09-10

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7086]
Hello @FredKruse 

Sorry for opening a new ticket, but this is too serious to continue adding comments to the other ticket.

I was working on the following document and I reached a point where the add-on was crashing.

The last crash was an infinite loop and I had to close LibreOffice.

Here are the screenshots of the crashes, logs and document.
![LT_crash1_20220910](https://user-images.githubusercontent.com/5192600/189499038-5e529333-a777-424b-9275-fceedf6fcd11.png)

![LT_crash2_20220910](https://user-images.githubusercontent.com/5192600/189499057-9fa39169-822a-4bef-b7d1-66c0e903dd95.png)

![LT_crash3_20220910](https://user-images.githubusercontent.com/5192600/189499074-26c2b50c-dbff-486a-baa6-901d383018d0.png)
(infinite loop)

[LanguageTool.log](https://github.com/languagetool-org/languagetool/files/9541298/LanguageTool.log)

[Index do dossier a levar_20220910.odt](https://github.com/languagetool-org/languagetool/files/9541301/Index.do.dossier.a.levar_20220910.odt)

**Comment by marcoagpinto** [comment]
@danielnaber 

This is too critical.

Three crashes with a one-page document, and the third crash was an infinite loop.

**Comment by FredKruse** [comment]
I'm back at home tonight. Tomorrow I'll will have a look. But there is a test document this time, makes the debugging very much easier.

**Comment by FredKruse** [comment]
These changes should solve your problem. Please test it also with your PhD thesis. If LT extension runs into problems, not more than 3 paragraphs should be written to the log file.

**Comment by marcoagpinto** [comment]
@FredKruse 

Thank you!

❤️

**Comment by marcoagpinto** [comment]
@FredKruse 

The thesis seems too hard for LanguageTool. 😄 

In my first try, the add-on crashed:
1. Opened the .docx;
2. set all language to Portuguese;
3. Save as .ODT
4. Close LibreOffice.

When I clicked on the window gadget to close LibreOffice, it hang.

I got this:
![lt_crash_20220913](https://user-images.githubusercontent.com/5192600/189847229-93250129-6d44-475e-bcf1-35d506cd5f8c.png)

Can you please give me your private e-mail address to e-mail you the log?

The log shows confidential information from the thesis.

Thank you!

**Comment by marcoagpinto** [comment]
@FredKruse 

I have sent you the log via e-mail.

Notice that the log also has warnings about tables.

Thanks!

**Comment by FredKruse** [comment]
@marcoagpinto 
The problem with the loop is solved.
But the test document (problematic page) works for me (no crash).
Could you test both, the test document and your thesis, with the next nightly?

**Comment by marcoagpinto** [comment]
@FredKruse 

Sure!

Thanks!

**Comment by marcoagpinto** [comment]
@FredKruse 

It seems to be fixed!

Thank you for all your hard work!
