### ISSUE TITLE
[eo] False negative with transitive verb.

### ISSUE THREAD

**Issue by capiscuas** [languagetool-org/languagetool#709]
Hi, I love your language tool.
I was checking some esperanto text 
![image](https://cloud.githubusercontent.com/assets/515154/26033072/5662eb3c-38a3-11e7-9a53-4bf20c49ee51.png)

and it showed that the verb elŝviti is not transtivie, which is not true.
Here is the correct definition of elŝviti, it is transtive and therefore allows acussative case(with the -n suffix for the objects in Esperanto)

![image](https://cloud.githubusercontent.com/assets/515154/26033076/734cd83e-38a3-11e7-9863-b0cc5f365c9d.png)

Thanks a lot.

**Comment by danielnaber** [comment]
@dpelle Maybe you can have a look?

**Comment by dpelle** [comment]
Thanks. You're right, the verb "elŝviti" should be marked as transitive.
I just fixed it.

**Comment by capiscuas** [comment]
So fast, you guys are the best. I will send patches next time to make your work easier whenever I found more of these small bugs. Thank you!
