### ISSUE TITLE
add support for markup language

### ISSUE THREAD

**Issue by n3f4s** [languagetool-org/languagetool#710]
It would be nice to have support for mark-up language like ``latex`` or ``markdown``.
Using _LanguageTool_ with those languages raise a lot of error due to the tag and automatic styling (for ``latex`` mostly).

Furthermore, having things like piece of code in the text can make the usage of _LanguageTool_ less pleasant due to number of error raised. Supporting those mark-up languages would mean being able to disable spell checking for things like the ``verbatim`` environment in ``latex`` or  code quote (``) in markdown

**Comment by danielnaber** [comment]
I consider this out of scope for LT. Instead, editors should integrate LT and they should do the parsing of the text (markup vs. text, hand only the text to LT).
