### ISSUE TITLE
[pt] Colete à Prova de Bala - 2022-09-16

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7100]
@ricardojosehlima

Hello!

Is “bala” written in plural or singular?

When I created the rule years ago, I thought to be sure, but I have been facing philosophical questions.

Thanks!

**Comment by ricardojosehlima** [comment]
Hi, in pt-br it is plural the recommended form by the standard norm.

**Comment by marcoagpinto** [comment]
Thanks!

**Comment by marcoagpinto** [comment]
Ricardo!

I have enhanced the rule:
https://github.com/languagetool-org/languagetool/commit/a4542c56d4d02ad05b61d9e895d2e5aace2545c5

Thank you!
