### ISSUE TITLE
Regression tests empty

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7104]
Hello!

For over a week that I haven't looked at it, but I went there moments ago, and it appears to be empty:
https://internal1.languagetool.org/regression-tests/via-http/2022-09-19/pt-PT/index.html

Thanks!

**Comment by danielnaber** [comment]
https://internal1.languagetool.org/regression-tests/via-http/2022-09-18/pt-PT/index.html isn't empty?

**Comment by marcoagpinto** [comment]
@danielnaber 

It only shows two lines of results, in the past it would show dozens of lines.

Something must have changed.

**Comment by marcoagpinto** [comment]
It is working again!

https://internal1.languagetool.org/regression-tests/via-http/2022-09-20/pt-PT/
