### ISSUE TITLE
Repetition settings: distance_tokens

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool#7107]
(From the forum: https://forum.languagetool.org/t/en-many-nagging-error-from-rule-rep-passive-voice/8278/4)

REP_PASSIVE_VOICE is triggered with these repetition settings: min_prev_matches="4" distance_tokens="20": when there are 4 previous matches of the same rule, and they are close enough (less than 20 tokens).
The problem (or bug) is that the condition of <20 tokens is required only from the penultimate to the last repetition. (Most repetition rules use min_prev_matches="1")

Should we apply the condition "<20 tokens" to all repetitions? Anyway, some maximum length should be required.  
What would be the best solution for this rule? @AzadehSafakish

**Comment by jaumeortola** [comment]
> rule is only triggered if pattern is matched X times within X tokens

That is, `distance_tokens` would refer to the distance between the first and the last repetition. Is that what you mean? I think it makes sense, and it should be easy to implement.

**Comment by AzadehSafakish** [comment]
Yes, that would be ideal.

**Comment by jaumeortola** [comment]
Suggested changes: https://github.com/languagetool-org/languagetool/pull/7120

`distance_tokens` will refer to total distance between the first and the last repetition.

The results will be slightly different. Each language developer can adjust his/her rules.

**Comment by jaumeortola** [comment]
The documentation for the repetition rules: https://github.com/languagetool-org/languagetool-org.github.io/pull/9/files

**Comment by AzadehSafakish** [comment]
Thank you so much, @jaumeortola
