### ISSUE TITLE
[pt] Rule idea to remove "ser" from sentences - 2022-09-21

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7109]
Hello @ricardojosehlima

I came up with an idea for a rule based on:
`E de repente, num dia qualquer, acordamos e percebemos que já podemos lidar com aquilo que julgávamos SER maior que nós mesmos.`

The idea is to remove “ser” from the sentence.

The basic idea is to search for:
`V.+ + "ser" + ADJECTIVE/NOUN +QUE`
or
`V.+ + "ser" + ADJECTIVE/NOUN` (without “que”?)

Suggestion message:
`“O verbo 'ser' pode ser omitido nesta perífrase.”`

Is it a good idea?

Thanks!

**Comment by marcoagpinto** [comment]
or maybe:
`QUE + V.+ + "ser” + ADJECTIVE/NOUN`
(“que” at start)

**Comment by ricardojosehlima** [comment]
Hmmm what about "eu queria ser maior que ele"? 
Maybe julgar an realated verbs only (pensar, achar, acreditar).

**Comment by marcoagpinto** [comment]
Ahhhhhh… I will do some tests tonight, thanks. 😄

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Dear brother,

I have finished the rule:
https://github.com/languagetool-org/languagetool/commit/bcbb09fd20da545bafeb8ca84e2ba1f574d5b13a

```
Portuguese (Portugal): 5 total matches
Portuguese (Portugal): 582235 total sentences considered
```
[10.txt](https://github.com/languagetool-org/languagetool/files/9623097/10.txt)

This did the trick:

```
          <or>
            <token postag='VMII.+' postag_regexp='yes'/>
            <token regexp='no' inflected='yes'>parecer</token> <!-- Add more verbs here when found -->
          </or>
```

With the other verbs you suggested, it gave false positives.
