### ISSUE TITLE
Use “an” instead of ‘a’ before an Uppercase word that start with R,

### ISSUE THREAD

**Issue by AhmedElTabarani** [languagetool-org/languagetool#7112]
Image:
![image](https://user-images.githubusercontent.com/69223584/191687044-ffb48e53-ab7e-4999-a115-214ffa7f4715.png)

Text to test:
```
But note that the symbol `#` renders as a RTL word, so it will reorder to the other side.
```

**Comment by tiff** [comment]
I think the suggestion is correct. See https://editorsmanual.com/articles/indefinite-article-a-an-with-abbreviations/
