### ISSUE TITLE
Incorrect type of software.apiVersion

### ISSUE THREAD

**Issue by jtojnar** [languagetool-org/languagetool#712]
According to the [JSON API description](https://languagetool.org/http-api/swagger-ui/#!/default/post_check) `software.apiVersion` key should be a number. LanguageTool 3.7 returns a string.

**Comment by danielnaber** [comment]
Thanks, this has been fixed, i.e. the next version will return a number. It will be online later tonight for the public HTTP API.

**Comment by jtojnar** [comment]
Note that this is actually a breaking change for software that uses strong typing.

**Comment by danielnaber** [comment]
Yes, and it has been documented in the CHANGES file. For the public API server we don't provide any guarantees about compatibility.
