### ISSUE TITLE
[DE] Bugmeldung September

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#7122]
Moin liebes LanguageTool-Team

Seit langem wieder eine Bugmeldung.
![grafik](https://user-images.githubusercontent.com/78316155/192120813-df574d9c-c110-47d2-b55a-9476740e6dda.png)

Vielleicht wurde dieser bereits behoben, denn ich nutze zurzeit die Version 5.8 und bald kommt die Version 5.9. Wenn nicht, solltet ihr diesen beheben.

Diese Meldung habe ich erst bemerkt, als ich die Dokumente nach und nach schloss. Beim normalen Arbeiten ist mir nicht aufgefallen.

Grüße Dallun511

**Comment by FredKruse** [comment]
An dieser Stelle hat sich einiges geändert. Der Fehler müsste in 5.9 behoben sein.
