### ISSUE TITLE
[pt] Unicode encoding problem with accent marks

### ISSUE THREAD

**Issue by susanaboatto** [languagetool-org/languagetool#7123]
Hi everyone,

As some of you already know, we've been having problems with certain word encodings containing accent marks in Portuguese, and this has been causing some antipatterns not to work. Here is what I know:

- When I paste examples containing words with accent marks from the diff on Intellij, the build fails;
- When I retype the accent mark manually on Intellij, the build stops failing;
- When erasing the word pasted from the diff, I have to press backspace twice when I reach the letter with the accent mark. The example below describes the process:

satélite
saté
sate
sat

When typing the word manually, pressing backspace only once is enough.

Now, most importantly:

Typing the words manually on Intellij prevents the build from failing and fixes manually typed sentences, **but sentences with other encodings keep showing up in the diff and are not fixed.**

For some examples, please check MODS 105 to 122 from [this rule](https://internal1.languagetool.org/regression-tests/via-http/2022-09-24/pt-BR/result_grammar_GENERAL_NUMBER_AGREEMENT_ERRORS[5].html), which all include a word containing an accent mark right before the detected error.

@jaumeortola

**Comment by jaumeortola** [comment]
Some of these sentences have [combining characters](https://en.wikipedia.org/wiki/Combining_character). 
See # 105: afiliação  -> afiliacU+0327aU+0303o

Non-combining characters:
See # 103 participações -> participaU+00E7U+00F5es

So, is it a problem of IntelliJ with combining characters?

(BTW, I also experienced freezing of Eclipse IDE just copying some unusual characters. I think they were emojis...)

**Comment by danielnaber** [comment]
> It might make sense to normalize the corpora used in the nightly tests.

Do you have a command to do that?

**Comment by jaumeortola** [comment]
We need NFC normalization: 

In LanguageTool: `StringTools.normalizeNFC("afiliação")`
Linux bash: `echo "afiliação" | uconv -x any-nfc`

**Comment by danielnaber** [comment]
`uconv -x any-nfc` - I have used that on the `pt-BR` data now for the nightly diff, so the next result might contains "changes" because of this (@susanaboatto).

**Comment by danielnaber** [comment]
I have now also converted `pt-PT.txt`, so tomorrow's diff will probably be large.

**Comment by danielnaber** [comment]
@jaumeortola Should we do this for other languages, too?

**Comment by jaumeortola** [comment]
> Should we do this for other languages, too?

It's not essential, but it won't hurt. Any language with diacritics: fr, es, ca, pl...

**Comment by danielnaber** [comment]
Done for fr and es. pl, too, but the result was identical. Okay to do it now for ca or do you want me to wait for a day when there are no rules changes?

**Comment by jaumeortola** [comment]
> Okay to do it now for ca or do you want me to wait for a day when there are no rules changes?

Go ahead whenever you want.

**Comment by danielnaber** [comment]
Also done for ca now.
