### ISSUE TITLE
[en] Case conversion does not give the correct result for UPPER CASE text

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#7125]
"Note: LT automatically adjusts the case of suggestions if they are added as plain text." (https://dev.languagetool.org/tips-and-tricks#changing-the-case-of-matched-word)

```
        <rule id="CASE_CONVERSION_TEST" name="Case conversion test">
            <pattern>
                <token>cat</token>
            </pattern>
            <message>Use '<suggestion>dog</suggestion>'.</message>
            <example correction="dog">My <marker>cat</marker> is happy.</example>
            <example correction="Dog">My <marker>Cat</marker> is fat.</example>
            <example correction="DOG">MY <marker>CAT</marker> SAT ON THE MAT.</example>
        </rule>
```

Testrules gives this message (LanguageTool-20220919-snapshot.zip):

`Exception in thread "main" org.languagetool.rules.patterns.PatternRuleTest$PatternRuleTestFailure: Test failure for rule CASE_CONVERSION_TEST[1] in file /org/languagetool/rules/en/grammar.xml: Incorrect suggestions: Expected 'DOG', got: 'Dog' on input: 'MY CAT SAT ON THE MAT.'`

**Comment by jaumeortola** [comment]
You are right. The default behaviour of the suggestions should be similar to `case_converson="preserve"` for all languages. I will take a look. Probably, we will need to adjust some tests in many languages.

**Comment by jaumeortola** [comment]
All-uppercase suggestions have been implemented. 

Once we preserve the case for all-uppercase words in the original sentence automatically, rule creators will need a way to make exceptions to all-uppercase suggestions. The way to do that, is to use a `<match>` with a `case_conversion` attribute:
```
<suggestion><match no="2" regexp_match="^.*$" regexp_replace="Liebe Grüße" case_conversion="startupper"/></suggestion>
```
The `<match>` has to be at the start of the suggestion and in the first suggestion. This won't work:
```
<suggestion>L<match no="2" regexp_match="^.*$" regexp_replace="iebe" case_conversion="alllower/></suggestion>
```

**Comment by MikeUnwalla** [comment]
@jaumeortola , thank you.
