### ISSUE TITLE
Can't log in using Google account on Microsoft Word add-on

### ISSUE THREAD

**Issue by JiaChen-Zeng** [languagetool-org/languagetool#7128]
It says the following.

```
This browser or app may not be secure.
Use a different browser. If you're already using a supported browser, you can try signing in again.
```

**Comment by danielnaber** [comment]
Please see https://languagetooler.freshdesk.com/en/support/solutions/articles/44002257101

**Comment by JiaChen-Zeng** [comment]
Alright, I can use this workaround. Though it's not that secure compared to just using Google login.
