### ISSUE TITLE
Swagger : this is not a POST

### ISSUE THREAD

**Issue by stefdelec** [languagetool-org/languagetool#713]
In swagger it is written that it needs a POST to check, put it never works as POST but do work as GET.

https://languagetool.org/http-api/swagger-ui/#!/default/post_check

**Comment by danielnaber** [comment]
How exactly do you try it? It works from me as POST, e.g.:

`curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'text=der%20haus&language=de-DE&enabledOnly=false' 'https://languagetool.org/api/v2/check'`

**Comment by stefdelec** [comment]
like this

`fetch("https://languagetool.org/api/v2/check", {
  method: 'POST',
  body: JSON.stringify(
    {
      text: "Paste your own text here and click the 'Check Text' button. Click the colored phrases for details on potential errors. or use this text too see an few of of the problems that LanguageTool can detecd. What do you thinks of grammar checkers? Please not that they are not perfect. Style issues get a blue marker: It's 5 P.M. in the afternoon. LanguageTool 3.6 was released on Tuesday, 28 December 2016.",
      language: 'en',
    }
  ),
  headers: { 'Content-Type': 'application/json' },
})`

**Comment by danielnaber** [comment]
The API returns JSON, it doesn't accept JSON. Its input is just parameters like in a GET URL (but POSTed).

**Comment by stefdelec** [comment]
Hum. I think there is something wrong here. If my method is POST, it doesn't work. If my method is a "GET" it is a "get". Also, if you don't pass any parameters in the paylod (body), then it should be a get.
I think it is misleading.
