### ISSUE TITLE
High CPU and RAM usage

### ISSUE THREAD

**Issue by medmedin2014** [languagetool-org/languagetool#7139]
```
**LanguageTool**
libreoffice-extension-languagetool 5.8-1
```

```
**LibreOffice**
Version: 7.4.0.3 / LibreOffice Community
Build ID: 40(Build:3)
CPU threads: 2; OS: Linux 5.19; UI render: default; VCL: kf5 (cairo+xcb)
Locale: en-US (en_US.UTF-8); UI: en-US
7.4.0-3
Calc: threaded
```
```
**Operating System**
Operating System: Manjaro Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.97.0
Qt Version: 5.15.5
Kernel Version: 5.19.7-1-MANJARO (64-bit)
Graphics Platform: X11
```

```
**OpenJDK**
openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+0)
OpenJDK 64-Bit Server VM (build 18.0.2+0, mixed mode)
```

![Screenshot_20220929_161313-2](https://user-images.githubusercontent.com/7027319/193071408-9cec2693-9f9a-4487-b975-b04de5538053.png)

**Comment by FredKruse** [comment]
What machine do you use?
How many words got your document?
There are some changes in version 5.9, also regarding performance. Please try LT 5.9.
On the other side, LT is growing. This costs CPU-Time. During the initialization phase, the CPU usage could rise. But this should decrease after a few seconds.

**Comment by medmedin2014** [comment]
I'm using Manjaro KDE on Intel i5 (2.3Ghz)/6GB RAM, I upgraded yesterday to LO 7.4.1 and still has the same problem with LT 5.8 extension, the problem is that for even small document with 10 pages the RAM is consumed without stopping until it eats all my 6GB of RAM and freezes my whole machine, then I'm forced to kill LO, I'm sure there is definitely a memory leak with LT extension because without LT extension LO works fine and doesn't even surpass 1GB of RAM.

**Comment by FredKruse** [comment]
That sounds not good. Could you please Test that document with 5.9. There was a lot of changes. If the bug appears also at 5.9, I need the document for tests.

**Comment by BloomingAzaleas** [comment]
See also #7222 for similar on Windows 10.

**Comment by marcelolaia** [comment]
Some problem here. I'm using Debian (Linux 6.0.0-6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1 (2022-12-09) x86_64 GNU/Linux), LibreOffice 7.4.3.2 40(Build:2) and LanguageTool 5.9. With LT activated, LO raise 130 - 200 % CPU usage!

**Comment by FredKruse** [comment]
I will close this issue as solved. Open a new issue with current versions if necessary.

**Comment by kibertoad** [comment]
@FredKruse Are there plans to cut a new stable version with all the perf fixes/improvements?

**Comment by FredKruse** [comment]
@kibertoad Most of the perf fixes/improvements are already included in LT 6.3.1. The release of LT 6.4 is planned for the end of March 2024.

**Comment by kibertoad** [comment]
@FredKruse Could you add 6.3.1 to https://github.com/languagetool-org/languagetool/tags?

**Comment by FredKruse** [comment]
@kibertoad You can download the extension here: https://extensions.libreoffice.org/en/extensions/show/languagetool

**Comment by kibertoad** [comment]
@FredKruse We are using it programmatically, server-side.
