### ISSUE TITLE
[pt] Disambiguator improvement - it doesn't recognise verb - 2022-09-30

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7149]
Hello @jaumeortola 

Look at the sentence:
`Eu mal consigo aguentar.`

“consigo” is decoded as PP3CSO00 when it is also a verb, verb “conseguir”.

Could you enhance the disambiguator?

Thanks!

**Comment by jaumeortola** [comment]
https://github.com/languagetool-org/languagetool/commit/f9eb73a9396c78abccc4c38e2fc069eadf9139ce
