### ISSUE TITLE
[de] Add compounds with "-mitarbeitende" to spellchecker and POS

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#7159]
Compounds with "-mitarbeitende" are currently neither recognized by the spellchecker nor by the POS dictionary. For example:

>  Kanzleimitarbeitende
>  Firmenmitarbeitende
>  Polizeimitarbeitende
>  Universitätsmitarbeitende

As this is nowadays quite common as a gender-neutral alternative to "-mitarbeiter", LanguageTool should support it.

**Comment by danielnaber** [comment]
For the speller part, this can be done using a special case in `GermanSpellerRule.isMisspelled()`. Actually, I've just done that. Sorry, didn't see you've assigned yourself already, @tiff.

**Comment by danielnaber** [comment]
@tiff I can also take care of the tagging (in a generic way that supports all "...mitarbeitende" compounds) if you want.

**Comment by tiff** [comment]
Sure, go ahead!

**Comment by danielnaber** [comment]
Fixed with https://github.com/languagetool-org/languagetool/commit/c96900377a2c74d6d79dba8fc162397ce3d4fe12
