### ISSUE TITLE
[pt-br] "Historia" 

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#7211]
User feedback:

> Historia é com acento no ó.

**Comment by marcoagpinto** [comment]
Yes, but it depends on the sentence, as it can also be a verb, verb “historiar”.

So, without knowing the sentence, I created a quick fix if the word before is a “que”, but I am not sure which word the user used before “historia”.

**Comment by p-goulart** [comment]
gGEC handles this pretty well, closing.
