### ISSUE TITLE
Warn if languages library is not included

### ISSUE THREAD

**Issue by Madusudanan** [languagetool-org/languagetool#722]
When I include just the [core library](https://mvnrepository.com/artifact/org.languagetool/languagetool-core/3.7) and try to access the language tool. It throws an NPE.

```
List<Language> languages = Languages.get();

//Throws NPE below since the language jar is not included
Language englishLanguage = languages.get(0);
```

By adding the [language jar](https://mvnrepository.com/artifact/org.languagetool/language-all) this error goes away, but instead of throwing an NPE just a logger warning such as "No language libraries detected" would be helpful.

**Comment by danielnaber** [comment]
This makes sense, but it's not totally trivial as throwing an exception in this case breaks several tests. Pull requests are welcome, though.
