### ISSUE TITLE
[LO-Add-on] Crashed - 2022-10-07

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7221]
@FredKruse 

Hello!

![lt_addon_crash_20221007](https://user-images.githubusercontent.com/5192600/194670365-544bb08c-fef6-4326-99ab-0b13993de1b1.png)

```
LanguageTool 6.0-SNAPSHOT (2022-10-04 16:43:02 +0000, 4860d0d)
OS: Windows 10 10.0 (amd64)
LibreOffice 7.4.1.2 (The Document Foundation), en-GB
Java version: 1.8.0_341 (Oracle Corporation)
Java max/total/free memory: 7262MB, 2943MB, 2566MB
```

[LanguageTool_20221007.log](https://github.com/languagetool-org/languagetool/files/9737716/LanguageTool_20221007.log)

[Rules Structure 202207XX.odt](https://github.com/languagetool-org/languagetool/files/9737717/Rules.Structure.202207XX.odt)

**Comment by FredKruse** [comment]
Thank you, for the documents. I will look at it, at the beginning of next week.

**Comment by FredKruse** [comment]
@marcoagpinto I can't reproduce the bug with your document. Does it occur just by open the document, or did you do something else?

**Comment by marcoagpinto** [comment]
@FredKruse 

While I was editing it.

But it only happened once.

Nevertheless, I only opened the ticket so that you can see if something needs fixing.
