### ISSUE TITLE
Win 10 mem leaks + cpu spin bisect to LT snap 20220930 for LO

### ISSUE THREAD

**Issue by BloomingAzaleas** [languagetool-org/languagetool#7222]
Edition	Windows 10 Pro for Workstations
Version	21H2
Installed on	‎11/‎4/‎2020
OS build	19044.2075
Experience	Windows Feature Experience Pack 120.2212.4180.0

Version: 7.4.1.2 (x64) / LibreOffice Community
Build ID: 3c58a8f3a960df8bc8fd77b461821e42c061c5f0
CPU threads: 8; OS: Windows 10.0 Build 19044; UI render: Skia/Vulkan; VCL: win
Locale: en-US (en_US); UI: en-US
Calc: CL

JRE 1.8.0_351

Balloon in LT CPU load and memory consumption noticed when testing snap 20221007. Bisecting starting with snap 20220711 as the earliest I happen to have on hand, there seems to be two memory leaks then a catastrophe in snap 20220930. The setup is:

1. Launch Win Task Manager to observe the LO application CPU and Memory consumption
2. (Repeating test follows)
3. Launch LO to its Start window (no doc open)
4. Observe Task Man LO resource use after settle time
5. Launch test file. I use the AAiW-v3 file previously uploaded in #7089, however the observed results seem independent of file.
6. Observe Task Man LO resource use after settle time
7. First LT Recheck Document
8. Observe Task Man LO resource use after settle time of S&G pane on whatever first complaint
9. Without processing the S&G complaint, cycle Win focus from-to S&G pane such as by repeatedly clicking on the wallpaper (desktop) and back to S&G while ALSO observing the Task Man LO resource use, in particular the memory consumption
10. Conditional: If the prior step memory consumption is otherwise relatively well-behaved between S&G pane focus event, then repeatedly click LT Recheck Document, which should close then re-open the S&G pane while ALSO observing the Task Man LO resource use, in particular the memory consumption
11. Records CPU % and Memory consumption. Close test doc.
12. Using LO Tools->Extension manager, change the installed LT snap version as indicated in the table below.

Summary results:

A) Observable in 20220711, there is a small, accumulating memory consumption increment every time the S&G pane looses then re-gains focus.
B) Observable in 20220711, there is a somewhat larger, accumulating memory consumption increment every time LT Recheck Doc is re-launched.
C) Observable in 20220925, the loose-re-gain focus, accumulating mem consumption increment gets a bit larger.
D) Observable in 20220930 up through 20221007, LT is off the rails. On first Recheck Doc, initial mem consumption is twice that of 20220929 and prior, then the CPU spins at > 16% (relative of course to my laptop) and memory consumption steadily ticks up in Task Man while the S&G pane sits idle on its first complaint.

I had not noticed A, B, C in prior testing because the increments were relatively small and there was no idle-state CPU impact.

8 Oct: Notes and table updated to account for snap 20220929, showing 20220930 is the actual breakage snap.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ReidB/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ReidB/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0000EE" vlink="#954F72">

LT   Snapshot | LO Launch CPU | LO Launch Mem GB | Load AAiW-v3 Test   File CPU | Load AAiW-v3 Test   File Mem GB | First LT Recheck Doc CPU | First LT Recheck Doc Mem GB | First LT Recheck Doc Note | Repeated Recheck Doc CPU | Repeated Recheck   Doc Mem GB | Memory Behavior   During Repeated S&G Lose-Gain Focus
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
20220711 |   |   |   |   |   |   |   |   |   | Mem increases slightly
20220925 | < 1% | < 0.2 | < 1% | 0.7 | < 1% | 1.4 |   | < 1% | 1.5 | Mem increases slightly but with   a much greater increment than 20220711
  |   |   |   |   |   |   |   | < 1% | 1.6 |  
  |   |   |   |   |   |   |   | < 1% | 1.7 |  
  |   |   |   |   |   |   |   | < 1% | 1.8 |  
  |   |   |   |   |   |   |   |   | 1.9 |  
20220927 | < 1% | < 0.2 | < 1% | 0.7 | < 1% | 1.4 |   | < 1% | 1.5 | Mem increases slightly on same   order as 20220925
  |   |   |   |   |   |   |   | < 1% | 1.6 |  
  |   |   |   |   |   |   |   | < 1% | 1.7 |  
  |   |   |   |   |   |   |   | < 1% | 1.8 |  
20220928 | < 1% | < 0.2 | < 1% | 0.7 | < 1% | 1.4 |   | < 1% | 1.5 | Mem increases slightly on same   order as 20220925
  |   |   |   |   |   |   |   | < 1% | 1.6 |  
  |   |   |   |   |   |   |   | < 1% | 1.7 |  
  |   |   |   |   |   |   |   | < 1% | 1.8 |  
20220929 | < 1% | < 0.2 | < 1% | 0.7 | < 1% | 1.4 |   | < 1% | 1.5 | Mem increases slightly on same   order as 20220925
  |   |   |   |   |   |   |   | < 1% | 1.6 |  
  |   |   |   |   |   |   |   | < 1% | 1.7 |  
  |   |   |   |   |   |   |   | < 1% | 1.8 |  
20220930 | < 1% | < 0.2 | < 1% | 0.7 | > 16% | 2.8 | Steady mem increase during S&G   UI idle |   |   |  
20221007 | < 1% | < 0.2 | < 1% | 0.6 | > 16% | 2.8 | Steady mem increase during S&G   UI idle |   |   |  

</body>

</html>

**Comment by BloomingAzaleas** [comment]
Re-test with 20221023 .oxt snap. Same runaway CPU and memory behavior as snap 20221007.

Regards.

**Comment by BloomingAzaleas** [comment]
Confirmed again with
Version: 7.4.2.3 (x64) / LibreOffice Community
Build ID: 382eef1f22670f7f4118c8c2dd222ec7ad009daf
CPU threads: 8; OS: Windows 10.0 Build 19045; UI render: Skia/Vulkan; VCL: win
Locale: en-US (en_US); UI: en-US
Calc: CL

JRE 1.8.0_351

**Comment by FredKruse** [comment]
I will close this issue as solved. Open a new issue with current versions if necessary.
