### ISSUE TITLE
[pt] “ao a” - 2022-10-11

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7246]
Hello @ricardojosehlima

I hope you had nice holidays.

This sentence:
`Isto foi provado ao a máquina ler o seu próprio código.`

It triggers the rule saying I am using two prepositions “ao a”.

But the sentence is correct, isn't it?

Thanks!

**Comment by ricardojosehlima** [comment]
Hi, this construction seems very rare, maybe more usual in pt-pt. It is correct anyway. Perhaps an antipattern like ao + a + substantivo + verbo infinitivo?

**Comment by marcoagpinto** [comment]
> Hi, this construction seems very rare, maybe more usual in pt-pt. It is correct anyway. Perhaps an antipattern like ao + a + substantivo + verbo infinitivo?

That is exactly what I had in mind: ao(s) + (a/o)(s) + substantivo + verbo infinitivo.

😄 

But nothing like asking an expert first before attempting it.

Thanks!
