### ISSUE TITLE
[pt] Idea for rule: “e esta(s)/este(s) → que” - 2022-10-11

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7255]
@ricardojosehlima

Hello!

Look at this sentence:
`"A equação é fulcral no nosso estudo E ESTE suporta diversas variáveis."`

Would it be a good idea (rule) to replace “E ESTE” with “QUE”?

I guess “este” must match the gender of “estudo”, I will have to create a rulegroup with a rule for male and other for female.

Thanks!

**Comment by ricardojosehlima** [comment]
Hi,
  I thought on "Eu procurei o menino e este me respondeu que não queria ir". Now "Eu procurei o menino que me respondeu que não queria ir", looks like there are two (or more) meninos and I searched for the one that answered... and not for some other.
 Also, "Eu comprei uma laranja e esta não estava boa": only later I found out that it was not good; now "Eu comprei uma laranja que não estava boa" may indicate that previously I knew it was not good.
  Even then, it could be useful for formal texts, like dissertations, and so on. Give it a try!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

!!!!

We have a plan!

At 5am, I will do it!

I am so eager to see the results.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
I am still working on it.

Fixing false positives and attempting to make it broader.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is coded and tested:
https://github.com/languagetool-org/languagetool/commit/ce265b46eed95861e8268de266216bf5315309f8

```
Portuguese (Portugal): 7 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
Portuguese (Portugal): 17356 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```

[12.txt](https://github.com/languagetool-org/languagetool/files/9764463/12.txt)

Does it look good?

Thanks!

**Comment by ricardojosehlima** [comment]
Hi 
Look at these sentences
Dê-se responsabilidade a uma mulher e esta saberá como assumi-la.
Da flor nasce a semente e esta produz a planta...

IMO, in both cases, "e esta"! indicates a continuity, something that happened after the event, and replacing it with "que" makes this meaning get lost. And I think it applies to all the hits of the file.

**Comment by marcoagpinto** [comment]
They sound well here in the Portuguese used (European).

So, the best is for me to move the rule to pt-PT grammar.xml?

Thanks!

**Comment by ricardojosehlima** [comment]
Yes, maybe for pt-pt only

**Comment by marcoagpinto** [comment]
Done!

https://github.com/languagetool-org/languagetool/commit/f74cd576b308d52c4232f196b30354f39e927556

https://github.com/languagetool-org/languagetool/commit/61d72b4657f9ef8b5eec4b38449dd87d85d1949f

Thanks!
