### ISSUE TITLE
[pt] Idea for rule - 2022-10-13

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7268]
Hello @ricardojosehlima

I came up with an idea for a rule.

See the sentence:
`Após eu insistir muito, o que me foi dito foi para aguardar um pouco.`

After the suggestion:
`Após eu insistir muito, foi-me dito para aguardar um pouco.`

Basically, it should be triggered with:
o + que + me/lhe/te/etc. + verb1 + verb_part_passado + verb1 (verb1 appears the same twice)

Is it a good idea?

Also, do you have an idea for the rule ID name and rule name?

Thanks!

**Comment by ricardojosehlima** [comment]
Seems good!
repeticao_auxiliar_foi
"Eliminação da redundância de auxiliar" !!??
oh, also try without the pronouns (me/lhe/te etc.)

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is done:
https://github.com/languagetool-org/languagetool/commit/90eee5d145772e7b0b00d14f8b92a26f692043a8

```
Portuguese (Portugal): 2 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

Only 2 hits in 600 000 sentences:
[5.txt](https://github.com/languagetool-org/languagetool/files/9781313/5.txt)


Thanks for the tips on also creating a subrule for no pronouns!

❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
This is a medium complexity rule, it deals with more complex sentences.

Not all people have the knowledge to write this way.

**Comment by ricardojosehlima** [comment]
Na verdade o que é regulamentado é que só dentro da freguesia de Souselas é que os Materiais e Matérias são perigosos.
Mente quem faz mau uso dela” afinal ela é a descrição da própria natureza, então tudo o que é provado é verdadeiro!

Hi, in the sentences above, what is the simplified version? It seems that something is lost, affecting the meaning. They are not the same as in your example above.

**Comment by marcoagpinto** [comment]
```
Na verdade o que é regulamentado é que só dentro da freguesia de Souselas é que os Materiais e Matérias são perigosos.
Na verdade é regulamentado que só dentro da freguesia de Souselas é que os Materiais e Matérias são perigosos.

Mente quem faz mau uso dela” afinal ela é a descrição da própria natureza, então tudo o que é provado é verdadeiro!
Mente quem faz mau uso dela” afinal ela é a descrição da própria natureza, então tudo é provado verdadeiro!
```

It sounds well here in pt-PT, maybe it should be another pt-PT rule?

At least, we have been creating some pt-PT only rules.

😄 😄 😄 😄 😄 😄 😄 😄 😄

**Comment by marcoagpinto** [comment]
And I came up with some more ideas for rules.

But I don't want to write them all at the same time, or it will be a chaos of posts simultaneously.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I have moved it to pt-PT:
https://github.com/languagetool-org/languagetool/commit/b5fa938a17bbf76d48933da75e30844ecfde06a3

https://github.com/languagetool-org/languagetool/commit/522be788344ec14bfca27ecb2f789d8820334f8b
