### ISSUE TITLE
[pt] Fix incorrect suggestion

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#7273]
When writing "para travar as batalhas que nunca pudemos", LT suggests "Essa perífrase pode ser melhorada" and "que batalhas nunca pudemos".
The written sentence is ok and the suggestion looks weird.

**Comment by marcoagpinto** [comment]
ahhhhhhh

Nice finding.

I will work on the tasks in a few hours.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
It is fixed here:
https://github.com/languagetool-org/languagetool/commit/75646282b0609e43e8dc117c6f0e7a5b9eb5323c

**Comment by ricardojosehlima** [comment]
Great!
