### ISSUE TITLE
Spell check suggestions and punctuation

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#728]
If I take a valid German word form and add two random characters, LT (Web version) usually suggests the correct form, for example:

- aufgeregegt
- arkjbeiten
- Antorworten

Suggestions work as expected for all of these. Somewhat unexpectedly, if those incorrect forms happen to be followed by a hyphen or a period, I don't get any suggestions:

- aufgeregegt.
- arkjbeiten-
- Antorworten.
- Kundigungsfrist.

I'm not sure if this is doable, but my idea is: When looking for a match to suggest,

1. check if the last character is a hyphen or dot,
2. first search for a suggestion with that trailing character,
3. if that yields no result, save that character and remove it from the string,
4. search for a suggestion again,
5. re-add the dot/hyphen to the suggestion if found.

Related: We're getting a lot of suggestions that look like this:
weil....dann

Is it possible to remove dots inside a "word" before the spell check?

**Comment by janschreiber** [comment]
Another weird example: for "einzigstes." at the end of a sentence the only suggestion I get is "winzigstes.", but for "einzigstes" the most likely suggestion "einziges" is the second item in the menu and I get three more reasonable suggestions.

**Comment by danielnaber** [comment]
Should mostly be fixed now (`arkjbeiten-` not yet, but `arkbeiten-` should already work).

**Comment by janschreiber** [comment]
Now the problem appears to be almost reversed: The suggestions for 'gans.' are very good, but for 'gans' I only get uppercase suggestions, not including 'ganz'. I've added the pair s:z to [de_DE.info](https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/de_DE.info)

**Comment by marshinkar** [comment]
'gans' now receives the expected suggestion 'ganz' as first option.
