### ISSUE TITLE
[pt] Rule: “ser igual a → igualar” - 2022-10-15

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7285]
@ricardojosehlima

Hello!

Since yesterday that I have been creating this rule.

I believe I have been able to remove the false positives.

I added it in pt-PT, and I would like to ask your opinion if it should be moved to PT, or if I should keep it in pt-PT.

Thanks!

```
Portuguese (Portugal): 24 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[20.txt](https://github.com/languagetool-org/languagetool/files/9791532/20.txt)

**Comment by marcoagpinto** [comment]
Ahhhh… the commit URL:
https://github.com/languagetool-org/languagetool/commit/b40306124d2b1ee80de45222196c5229ff4c6cbe

**Comment by ricardojosehlima** [comment]
Hi when it comes to math it doesn't work for pt-br and almost all examples are with math so it's safer to keep it to pt-pt

**Comment by marcoagpinto** [comment]
Ahhhhhhhhh

Thank you!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ 

😄
