### ISSUE TITLE
[pt] Idea for rule: E NÃO SABEM → SEM SABER - 2022-10-16

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7290]
@ricardojosehlima

Hello!

Look at the sentences:
```
Quando se pergunta eles ficam perplexos E NÃO SABEM o que responder.
Quando se pergunta eles ficam perplexos SEM SABER o que responder.
```

Basically, it would search for `“e não + verb”`, and would suggest: “sem + verb_infinitive”.

Is it a good idea?

Thanks!

**Comment by marcoagpinto** [comment]
@ricardojosehlima

I have created the rule:
https://github.com/languagetool-org/languagetool/commit/21df5e52f4384f64043cd52bcce924582706c530

```
Portuguese (Portugal): 6 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```


[19.txt](https://github.com/languagetool-org/languagetool/files/9794606/19.txt)

**Comment by marcoagpinto** [comment]
@ricardojosehlima

I have added the code to deal with nouns:
https://github.com/languagetool-org/languagetool/commit/a1fd7c0654e762a3d80ed64eaf43709e7ad7121b

Now:
```
Portuguese (Portugal): 16 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[28stable.txt](https://github.com/languagetool-org/languagetool/files/9795679/28stable.txt)

The lines with “[1]” are from the subrule above.

The line with “[2]” are from the new subrule.

I believe all results are valid.

Thanks!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by ricardojosehlima** [comment]
This looks great! One or other sentence I think the original meaning is a little changed but not so sure. So all ok.

**Comment by marcoagpinto** [comment]
Cool.

Thanks!

I, too, am sometimes not 100% sure about some sentences, but usually, it only happens with two or three… because they are on the borderline or whatever it is called (I don't know the technical name).

Tonight I will revise my thesis with this rule as I believe it will have some hits since the idea came from there. 😄 

I have a few more ideas for rules, I will post them soon.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️
