### ISSUE TITLE
[LibreOffice add-on] Can't add words to internal dictionaries

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7298]
@FredKruse 

Hello!

I am not sure if this is a LanguageTool bug or a LibreOffice bug.

I have LibreOffice 7.4.2.3 and the latest LT nightly.

I have been noticing this behaviour for weeks, but I was waiting for a new version of LibreOffice to be released to confirm it.

If I have a word in my document that appears as a typo, it doesn't matter whether I add it to LT's dictionary or LO's dictionary with the right-mouse button, since it still appears as a typo.

It seems the word isn't being added to both dictionaries.

Fred, could you check if it is a LT or LO bug?

Thanks!

**Comment by FredKruse** [comment]
I could reproduce the bug. It is interesting, if you add it per LT check dialog to the dictionary, it works. If you do the same with the right mouse button, it doesn't work. The functionality of the right mouse button for spelling errors is provided by LO (not LT). It is a LO bug, I think.

**Comment by marcoagpinto** [comment]
@FredKruse 

I have deleted my LibreOffice 7.4.2.3 and inserted a typo.

I right-clicked and added to dictionary and it no longer appeared as a typo.

I installed the nightly, wrote a typo and adding typos with right-click no longer work.

Also, why are there two internal LT dictionaries?
![2internal_dics_for_LT_20221021](https://user-images.githubusercontent.com/5192600/197168871-652d710e-d19f-4aac-b3f7-410779e52beb.png)

**Comment by darkseji** [comment]
> It is a LO bug, I think.

I think that the problem started with 7.4.0 release. RMB context menus for synonyms and adding to a dictionary were missing. The menus are back but RMB add to dictionary does not work when there are 2+ dictionaries present and the LanguageTool is installed. I've reported an LO bug here: https://bugs.documentfoundation.org/show_bug.cgi?id=152110 so hopefully they will have a look on their end as well.

**Comment by FredKruse** [comment]
Yes, it's a LO bug. It occurs when more than one dictionary is used. 
The internal LT dictionaries are added to include the LT lists of correct spelled words, which are used additional to the official dictionaries. Meanwhile, the lists are very long (dependent on the language). The size of additional dictionaries is limited (by LO) to 30,000 words. So, the lists are split into several internal dictionaries (e.g. the additional German list includes more than 150,000 words and has to be split into 6 dictionaries).

**Comment by FredKruse** [comment]
By the way, I found no way to hide the internal LT dictionaries from the context menu or other lists.

**Comment by FredKruse** [comment]
I solved the issue by overriding the context menu. So, the LT internal dictionaries are not visible anymore (inside the context menu). The adding of words to the dictionaries works again, but only for users of the LT extension ;).

**Comment by marcoagpinto** [comment]
Good job!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by darkseji** [comment]
I've just checked and can confirm. It works in LO 7.4.2. Yeah! :)

As a side effect I now see a complete selection of active dictionaries (additional LT dic remains hidden and I can access it only via LO Options dialog) - those normally hidden are in the red rectangle. When working with Polish language I usually see only the first three (standard one and two additional dictionaries I need on a daily basis). I can live with that. :)
![image](https://user-images.githubusercontent.com/63911601/202864984-2086e0fa-8f3d-4805-82bb-23d22cc6d5b6.png)

**Comment by bstecklum** [comment]
I am on LO 7.4.2.3 with LT extension 5.9 and the bug is still there.
![screenshot](https://user-images.githubusercontent.com/24475571/208243130-cd052474-7092-4076-a50f-ff53035921b3.png)

**Comment by bstecklum** [comment]
I figured out that while adding a word to the dictionary does not work with a right mouse click, it can be done by invoking the Spell and Grammar Check Dialog (F7) and selecting the proper dictionary. This is a bit more cumbersome, but works.

**Comment by marcoagpinto** [comment]
@bstecklum 

Fred already replied two weeks ago or so that he fixed the bug.

You must wait for 6.0 (29-DEC) to be released or use a nightly.

Each official version is released every 3 months, so fixes will only come to already released versions if they are serious.

**Comment by bstecklum** [comment]
Installed today's nightly. Works. Thanks!

**Comment by stragu** [comment]
> I think that the problem started with 7.4.0 release where RMB context menus for synonyms and adding to a dictionary were missing. The menus are back now but RMB add to dictionary does not work [...]

Do you have any pointers for context menu items disappearing and reappearing in LO 7.4? I couldn't find relevant issues on our tracker. If you have a bug ID, or more precise version numbers, that would be great.

**Comment by stragu** [comment]
FYI, the LO issue was just fixed by Caolán: https://bugs.documentfoundation.org/show_bug.cgi?id=152110
The fix is already in trunk at 24.8, and will be in releases 24.2.3 and 7.6.7.
So maybe the workaround can be removed at a later date?
