### ISSUE TITLE
LanguageTool stand alone(http server) is ignoring my .info configuration 

### ISSUE THREAD

**Issue by neorganic** [languagetool-org/languagetool#730]
Hello,

 in /LanguageTool-3.8/org/languagetool/resource/sv/swedish.info  I added(currently have) these lines:

> #
> # Dictionary properties.
> #
> 
> # if set, all UPPERCASE words will be ignored during the spell-check;
> fsa.dict.speller.ignore-all-uppercase=true
> 
> # if set, the CamelCase words will be ignored during the spell-check;
> fsa.dict.speller.ignore-camel-case=true
> 
> # if true, words containing numbers are not checked;
> fsa.dict.speller.ignore-numbers=true
> 
> #if set, punctuation will be ignored during the spell-check;
> fsa.dict.speller.ignore-punctuation=true
> 
> # if true, the speller will treat upper and lower case as equivalent;
> fsa.dict.speller.convert-case=true
> 
> # if set to true, the frequency information is included in the dictionary (see below);
> fsa.dict.frequency-included=true
> 
> #
> #
> #
> fsa.dict.separator=+
> fsa.dict.encoding=iso-8859-1
> 
> fsa.dict.encoder=SUFFIX

But after closing, and starrting the http server again it seems that these configurations are being ignored for the language "sv"  . Am I doing something wrong here or it's the LT issue. Any help or guidance would be very welcome !

**Comment by danielnaber** [comment]
`swedish.info` belongs to `swedish.dict` and it's the part-of-speech tagger dictionary. It is not related to spell checking (which you seem to be looking for). For Swedish, hunspell is used for spell checking, see the `hunspell` dictionary.

**Comment by neorganic** [comment]
@danielnaber 
Thanks for the update,
 that explains a lot. Now how could I implement my settings to swedish spell check or let's say all the spellcheck ? Create an .info file in the /LanguageTool-3.8/org/languagetool/resource/sv/hunspell dir ?

**Comment by danielnaber** [comment]
I don't remember whether options like the ones you mention can be configured via hunspell's `*.aff` file, you'll need to research the hunspell documentation. In case it doesn't work, you'd need to modify LT's code I guess. Anyway, spell checking works differently for different languages on LT, so your approach from above is actually correct for some languages (those whose spell checker class does not extend `HunspellRule`).

**Comment by neorganic** [comment]
At first it looked like it would be an easy thing to do, but now it seems that I have hit a wall, because I don't have proficiency in JAVA - only PHP/JS... . In a matter a fact the .jar files appear encoded when looked via for e.g. sublime text .

P.S. Adding  the configuration in *.aff  had no effect , neither adding the *.info file to the hunspell dir. :/

**Comment by danielnaber** [comment]
What configuration did you add to the `.aff` file? `fsa.dict.speller.ignore-all-uppercase` etc. will not work. hunspell is its own software that just happens to be included in LT, it has its own settings. The JAR file is just a ZIP file, BTW.

**Comment by neorganic** [comment]
@danielnaber  yeah I added the ` fsa.dict.speller.ignore-all-uppercase`  etc configurations... Looking for hunspell configuration examples, but currently can't find anything useful . Thanks for the info.
