### ISSUE TITLE
spell check: split words

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#731]
Most spell checkers have the following feature: If a word that the user entered is not found in the dictionary, they try to split the user input into two valid words.

Two examples for which that works:
- immernoch
- desweiteren

Two examples for which it doesn't work:
- vorallem
- ausversehen

**Comment by danielnaber** [comment]
"vorallem" actually suggest "vor allem", but it's too far down in the list, so we need to find why it doesn't come first.

**Comment by danielnaber** [comment]
This should be fixed now.

**Comment by janschreiber** [comment]
I guess that's fixed now and can be closed. Can be reopened if tomorrow's tests yield unexpected results.

**Comment by janschreiber** [comment]
Maybe we should add a suggestion with a hyphen. This was suggested by a user today: russischamerikanischer

**Comment by janschreiber** [comment]
For 'Mafiosis' i get 'Mafiosi s' now. I think we'd better add a requirement that both chunks must be at least two characters long.

**Comment by danielnaber** [comment]
> I think we'd better add a requirement that both chunks must be at least two characters long.

Done.

**Comment by janschreiber** [comment]
Maybe we should add a special case for the dot: 'Mafiosis.' still yields 'Mafiosi s.' 'Mafiosis-' seems to work well. Also see #728.

**Comment by danielnaber** [comment]
Done.

**Comment by janschreiber** [comment]
Today we received 'einenzwillingsbruder' as user suggestion. I wonder if it's feasible to make the most obvious suggestion with a reasonable amount of work.

**Comment by danielnaber** [comment]
This should probably be fixed in morfologik here: https://github.com/morfologik/morfologik-stemming/blob/master/morfologik-speller/src/main/java/morfologik/speller/Speller.java#L339 - the second part after splitting needs to be uppercased and checked whether it's in the dict. Maybe I'll find time to create a pull request.
