### ISSUE TITLE
[Firefox Extension] Styles is leaking into devtool

### ISSUE THREAD

**Issue by imagoiq** [languagetool-org/languagetool#7312]
Hi,

When using devtool on a local website, styles from the extension are leaking.

This only appearing when I'm inspecting a website on localhost (127.0.0.1). So, it's quite annoying when developing a website to see your CSS custom properties, for example.

This is not a new issue and not linked to a particular browser version. I have it at least since one-two year.

As you are the only extension where I experience that, I guess this is something in your config.

**Comment by imagoiq** [comment]
Is the Firefox extension public? Can I contribute? It's very annoying, and I'm sure it could be fixed quickly.

**Comment by danielnaber** [comment]
Hi @imagoiq, I'm sorry, this isn't something that can easily be fixed (the extension isn't public, anyway).

**Comment by imagoiq** [comment]
Why closing the issue? I can understand that it's not easy to fix (even if it's hard to believe, as on the 15 extensions that I'm using currently your are the only one with this issue). Can't you think of a workaround? Like, I don't know, targetting only a specific port (I have no idea of what is the issue actually). Also perhaps it should be documented here?

**Comment by imagoiq** [comment]
Hi,
I looked at the `manifest.json` and I'm not entirely sure, but this part doesn't look right:

```
    {
      "all_frames": true,
      "match_about_blank": true,
      "js": [
        "common/browser-polyfill.min.js",
        "common/smoothscroll.js",
        "content.js"
      ],
      "matches": ["http://*/*", "https://*/*", "file:///*"],
      "run_at": "document_idle"
    },
    {
      "all_frames": true,
      "match_about_blank": true,
      "css": ["common/fonts.css", "content/styles/styles.css"],
      "matches": ["http://*/*", "https://*/*", "file:///*"],
      "run_at": "document_idle"
    },
 ```

Why do you need to expose those styles and scripts ont every webpage? I tried to remove `"content/styles/styles.css"` and the extension looks to work fine (at least at first sight).
