### ISSUE TITLE
[pt_BR] "oque" junto não aponta erros.

### ISSUE THREAD

**Issue by leoOze** [languagetool-org/languagetool#7330]
![image](https://user-images.githubusercontent.com/52644327/197407984-d2a10195-6b2c-4b3b-96f9-a0997aca411c.png)
![image](https://user-images.githubusercontent.com/52644327/197407994-ce6c0933-8d30-45da-8a09-dd44a6fc9a84.png)
![image](https://user-images.githubusercontent.com/52644327/197408006-a08e7b46-d146-4cf8-afb9-b2c3d6d64b88.png)

"oque" junto não existe, e é bem comum na escrita de textos, devemos corrigir isso.

**Comment by p-goulart** [comment]
Solved by gGEC, closing.
