### ISSUE TITLE
[pt] Idea for rule - “como é observável” → “observável” - 2022-10-25

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7334]
Hello @ricardojosehlima

I have just came up with an idea for a rule.

Look at this sentence:
`O total dos K a somar são 10, como é observável na tabela seguinte.`

I believe “como é” can be removed:
`O total dos K a somar são 10, observável na tabela seguinte.`
Maybe the whole verb “ser”?

Is it a good idea?

How to trigger it? Always look for a comma before “como + V. ser”? followed by a noun/adjective?

Thanks!

**Comment by marcoagpinto** [comment]
Ahhhhh… maybe it should also accept past participle of verbs:
`“visto na tabela seguinte”`

**Comment by ricardojosehlima** [comment]
Hmm, for me it feels like something is missing before "observável" and "visto". Maybe change "como é" to "conforme"?

**Comment by marcoagpinto** [comment]
ahhhhh…

“como é” is shorter than “conforme” in the number of characters.

But I know there are universities that require their essays to have a maximum of characters or letters, so it should be useful.

Should I attempt to create a “conforme” rule?

Thanks!

**Comment by ricardojosehlima** [comment]
It's shorter, but (for pt-br) it's less formal than "conforme".
It's a good idea to try this rule.

**Comment by marcoagpinto** [comment]
Cool!

I will code it tonight.

Thank you!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Brother Ricardo!!!

It is done!

https://github.com/languagetool-org/languagetool/commit/ec7e46c0866f46adf296fcf9dc1a4f39d4d1bf88

My first attempt with just: como + é/são + NC.+|AQ.+|VMP00.+ generated this:

```
Portuguese (Portugal): 223 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[Uploading 0_simple_all.txt…]()

Then, after making it as strict (valid) as possible, it became:

```
Portuguese (Portugal): 3 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[6.txt](https://github.com/languagetool-org/languagetool/files/9863909/6.txt)

Is there any sentence in the 0.txt that should be added to the rule?

Thanks!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by ricardojosehlima** [comment]
I think it's just fine!

**Comment by marcoagpinto** [comment]
Thank you, Ricardo.

😄 😄 😄 😄 😄 😄 😄 😄 😄 😄 😄 😄 😄
