### ISSUE TITLE
[pt] _spell_number_ postag

### ISSUE THREAD

**Issue by susanaboatto** [languagetool-org/languagetool#7336]
Hi @jaumeortola, I'm having a look at rule `SENT_START_NUM` and noticed the postag `_spell_number_`. I've never used it before, and it doesn't show up in the PT analyser. I figured you created it? I think it's very useful, but it doesn't provide gender alternatives (for example, `1 vaga` gets `um` as a suggestion, when it should be `uma`). Do you think we can change it so we get the right suggestion?

<img width="670" alt="image" src="https://user-images.githubusercontent.com/108675843/197769675-20e646a3-c625-49f4-af6a-116196529af1.png">

**Comment by jaumeortola** [comment]
Done here: https://github.com/languagetool-org/languagetool/commit/9cecb5b2391ebe3e404c849778617ca037acdb94
Check the results before enabling the rule, and check different numbers. There was a bug in the Portuguese number synthesizer for numbers 200, 300..., which I fixed. There could be other bugs.
