### ISSUE TITLE
[uk] No checks for pronouns with nouns

### ISSUE THREAD

**Issue by PerchunPak** [languagetool-org/languagetool#7346]
For example:

```
В кухні (must be на)
В пошті (must be на)
В росії (must be на)
На Україні (must be в)
```

**Comment by arysin** [comment]
«В кухні» - маловживана, але цілком допустима конструкція.
Теоретично «в пошті» теж - «сидів, розбирався в (своїй) пошті»
Загалом ми намагаємося створювати правила для помилок, що зустрічаються в реальних текстах. Бо створити правила на всі гіпотетичні неправильні вжитки неможливо.
За чинним правописом з країнами вживають «в».
Щодо «На Україні» є купа добрих вживань у старіших художніх текстах, але для сучасних, можливо варто створити правило, поміркуємо...
