### ISSUE TITLE
[pt] Idea for rule: “que passou” → “passada” - 2022-10-27

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7353]
Hello @ricardojosehlima

I have just come up with an idea for a rule:
`Isso aconteceu na semana que passou.`
Suggest replacing “que passou” with “passada”

Basically, it would check for: noun + que + verb past
and suggest past participle (male/female, singular/plural)

It will generate false positives, which I will fix.

Is it a good idea?

Thanks!

**Comment by ricardojosehlima** [comment]
Definitely!

**Comment by marcoagpinto** [comment]
Cool!

We have a plan!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
I will do it at 5am… I am very stressed right now 😄 😄 😄 😄 😄 😄 😄 

The things I can't say… 😄 😄 😄 😄 😄 😄 😄

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello!

I have just finished it:

https://github.com/languagetool-org/languagetool/commit/7668bbe5819884bc6b90279da4e12ed8c178eafa

```
Portuguese (Portugal): 32 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence

```

[16.txt](https://github.com/languagetool-org/languagetool/files/9887369/16.txt)


Thanks!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by ricardojosehlima** [comment]
Ok!
My guess is that it should be limited to situations involving time: a semana que passou and maybe only this verb.
Look

Para tal, deve aceder à caixa de e-mail do endereço que indicou e abrir o e-mail de confirmação enviado pelo PayPal.
"o e-mail indicado" feels like I didn't indicate it, whereas in the original sentence it's clear that I did.

...ido à falta de conexão durante esse período poderá acessar novamente e continuar a prova da questão que parou.
"a prova de questão parada" definitely isn't what was the original meaning.

...O sindicato poderia fazer uma visita a essa DRE na quarta-feira, fazer valer o direito do professor que estudou e agora quer ver seu direito respeitado.
"o professor estudado" changes the meaning of the sentence

And so on... :(

**Comment by marcoagpinto** [comment]
ohhhhhhhhhh 😢 😢 😢 😢 😢 😢 😢 😢 😢 

Let me fix it only for months, weekdays and times of day, and times.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I am just testing it.

I replaced the NC.+ line with:

`<token regexp='yes'>&meses_ano_abrev;&meses_ano;&dias_semana_abrev;&dias_semana;&partes_do_dia;&expressoes_de_tempo_simples;</token>`

Which triggers:

```
    <!ENTITY meses_ano_abrev "(?:[Aa]br|[Aa]go|[Dd]ez|[Ff]ev|[Jj]an|[Jj]ul|[Jj]un|mai|mar|[Nn]ov|[Oo]ut|[Ss]et)">
    <!ENTITY meses_ano "(?:[Aa]bril|[Aa]gosto|[Dd]ezembro|[Ff]evereiro|[Jj]aneiro|[Jj]ulho|[Jj]unho|[Mm]aio|[Mm]arço|[Nn]ovembro|[Oo]utubro|[Ss]etembro)">
    <!ENTITY dias_semana_abrev "(?:[Ss]ex|[Ss]eg|[Ss]áb|[Dd]om|[Qq]ui|[Tt]er)">
    <!ENTITY dias_semana "(?:[Dd]omingo|[Qq]uarta(-feira)?|[Qq]uinta(-feira)?|[Ss]ábado|[Ss]egunda(-feira)?|[Ss]exta(-feira)?|[Tt]erça(-feira)?|(seg|ter|qua|qui|sex)-feira)">
    <!ENTITY partes_do_dia "madrugada|manhã|matina|noite|tarde">
	<!ENTITY expressoes_de_tempo_simples "yoctossegundos?|zeptossegundos?|atossegundos?|fentossegundos?|picossegundos?|nanossegundos?|microssegundos?|milissegundos?|(?:segundo|minuto|hora|dia|semana|(?:bi|tri|quadri|se)mestre|ano|década|decénio|mil[éê]nio)s?|mês|meses">
```

**Comment by marcoagpinto** [comment]
Buaaaaaaaaaaaaaa...

Now the `<token regexp='yes'>n[ao]s?|d[ao]s?</token>` can accept more words such as "a(s)", "o(s)".

For now, I will make a quick fix.

At night, I will reattempt to rewrite and test that line.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

https://github.com/languagetool-org/languagetool/commit/12d59326344779b85f711a09429d95f94ede779f

At night, I will add more words, such as “a(s)” and “o(s)”.

I have spent the night working on it, and I can't think properly right now.

```
Portuguese (Portugal): 2 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[17_quickfix.txt](https://github.com/languagetool-org/languagetool/files/9888696/17_quickfix.txt)

**Comment by marcoagpinto** [comment]
Buaaaaaaaaaaa...

I forgot to use: `inflected="yes"` to get plurals of all entities.

I will do it tonight.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello Ricardo,

I believe the rule is ready:
https://github.com/languagetool-org/languagetool/commit/bd11d09c490567a34bb834d3fb1f51c07e68ae38

It only uses time related expressions.

```
Portuguese (Portugal): 14 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[24stable.txt](https://github.com/languagetool-org/languagetool/files/9893266/24stable.txt)

Notice it has 14 hits, but several are the same sentence that appeared repeated in the testing files.

Thanks!
