### ISSUE TITLE
[pt] Idea for rule: “com enorme realidade” → “com enorme realismo” - 2022-10-31

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7377]
Hello brother @ricardojosehlima

I have come up with an idea for a rule:
`“Isto é simulado com enorme realidade.”`

com POS + adjective + realidade

Should suggest replacing “realidade” with “realismo”.

I, too, have made this mistake in my thesis, thus the idea.

Is it a good plan?

Thanks!

**Comment by ricardojosehlima** [comment]
Sure!

**Comment by marcoagpinto** [comment]
Ricardo!

We have a plan!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello!

I have just finished the rule:
https://github.com/languagetool-org/languagetool/commit/889c6588aba03e8be35d343ef20db3f5df221ce9

It produces 0 hits in 600 000 sentences.

It works with:
`V.+|SPS00 + Adj/RG + realidade`

The RG allows the use of the word “mais”.

Here is in which I based the rule:
```
      <!--
      A equação dá mais realidade aos modelos. → A equação dá mais realismo aos modelos.
      Isto permite modelar com enorme realidade. → Isto permite modelar com enorme realismo.
      A equação para mais realidade é esta. → A equação para mais realismo é esta.
	  A equação para maior realidade é esta. → A equação para maior realismo é esta.
      -->
```

@jaumeortola @susanaboatto 
The rule produces 0 hits in 600 000 sentences, so it should be a very “safe” rule without the need to “temp_off”.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ 

Thanks!

**Comment by marcoagpinto** [comment]
ops, it has a tab in the last example instead of spaces, let me quick fix it.

**Comment by marcoagpinto** [comment]
tab replaced with spaces:
https://github.com/languagetool-org/languagetool/commit/101d997a1bc3c7aa752540c2e771ed4f2bb68747

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I came up with:
```
      As equações aumentam o grau de realidade dos modelos. → As equações aumentam o grau de realismo dos modelos.
      Há diferentes graus de realidade nos modelos. → Há diferentes graus de realismo nos modelos.
```

I have improved the rule, and it produces tons of false positives without the middle token.

I am testing a fix.

Give me a few minutes.

**Comment by marcoagpinto** [comment]
ahhhh... tons of false positives, I will still take some time to fix all of them.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is done!

https://github.com/languagetool-org/languagetool/commit/5675bcc80468d372b57a96d719463d51f3bed538

Now it has 3 hits:

```
Portuguese (Portugal): 3 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```
[14stable.txt](https://github.com/languagetool-org/languagetool/files/9905727/14stable.txt)

The hits are these:
```
Todos com muitas frases feitas na cabeça e nenhum senso de realidade.
...italismo FDP foi o maior feito do Lula não escreveria tanas críticas , precisa de um choquezinho de realidade das favelas!
Desejo lhe um choque de realidade.
```
“realidade” vs “realismo” are inconclusive in these three sentences, since if we observe the structure of the morphology, there is no way to tell which one is valid.

**Comment by ricardojosehlima** [comment]
In pt-br all these three sentences are valid only with realidade, not realismo.

**Comment by marcoagpinto** [comment]
ahhhhhh… I will fix it soon then.

Thanks for the feedback.

I am currently working on an antipattern for pt-PT.

Almost 2am, I will see if I can still fix it tonight.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Dear Brother Ricardo,

I gave up the antipattern I was working on for a pt-PT rule since it didn't work as planned.

I have fixed our rule:
https://github.com/languagetool-org/languagetool/commit/a01a8e8c8baae8c827c42160252502f5a7681e83

Now we are back to 0 hits in 600 000 sentences.

P```
ortuguese (Portugal): 0 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```
