### ISSUE TITLE
In German it is "jedes Mal" not "jedes mal"

### ISSUE THREAD

**Issue by Cherubin7th** [languagetool-org/languagetool#738]
LT things that in German "jedes mal" is OK, but it is wrong it must be "jedes Mal" with capital M.

**Comment by danielnaber** [comment]
Can you provide a complete sentence? I cannot reproduce this issue - "mal" is marked as an error for me, and "Mal" is correctly suggested.

**Comment by Cherubin7th** [comment]
Sorry, it was my mistake.
