### ISSUE TITLE
Message text in email window is vertically centred when using extension

### ISSUE THREAD

**Issue by BuzzKnightbeer** [languagetool-org/languagetool#7382]
Since a couple of days now whenever I write a new email the text is vertically centred in the composition window. When I disable the Language Tool extension it stops. I'm using Proton Mail and posted this originally in their Subreddit ([Link to post](https://www.reddit.com/r/ProtonMail/comments/yilgfb/message_text_is_vertically_centred/)) where someone had the same problem and pointed out it's actually the extension.

I'm using Brave browser 1.45.116 (latest).

![f7wggqwzv6x91](https://user-images.githubusercontent.com/45749699/199354245-3522a646-a0f7-4319-b027-3b427e57f346.png)

**Comment by tiff** [comment]
Thanks for reporting. Should be fixed with the next version.
