### ISSUE TITLE
[pt] Idea for rule: “para quando” → “quando” - 2022-11-02

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7385]
@ricardojosehlima

Hello Ricardo!

I came up with an idea for a rule.

Look at the sentence:
`A fiabilidade das equações é necessária PARA QUANDO se quer transmitir dados.`

It would suggest:
`A fiabilidade das equações é necessária QUANDO se quer transmitir dados.`

Maybe:
noun + “para” + “quando” + pronoun + verb
?

Is it a good plan?

Thanks!

**Comment by ricardojosehlima** [comment]
On your sentence it's ok

**Comment by marcoagpinto** [comment]
Cool!

We have a plan!

😄

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello, dear brother Ricardo.

I have just finished and tested the rule:
https://github.com/languagetool-org/languagetool/commit/f32236d6ffc24f0e61cb5f26c54aa7af65834487

It produces 0 hits in 600 000 sentences, so it must be a solid rule.

```
Portuguese (Portugal): 0 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

I made it strict:

```
    <!-- PARA QUANDO quando -->
    <rule id='PARA_QUANDO_QUANDO' name="Simplificar: Para quando → quando" type="style">
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2022-11-03 (25-JUL-2022+) -->
      <!--
      A fiabilidade das equações é necessária para quando se quer transmitir dados. → A fiabilidade das equações é necessária quando se quer transmitir dados.
      -->
      <pattern>
        <token postag='NC.+|AQ.+' postag_regexp='yes'/>
        <marker>
          <token>para</token>
          <token>quando</token>
        </marker>
        <token regexp='yes'>&pronomes_obliquos_sem_a_as_o_os;</token>
        <token postag='V.+' postag_regexp='yes'/>
      </pattern>
      <message>Esta perífrase poderá ser simplificada.</message>
      <suggestion>quando</suggestion>
      <example correction="quando">A fiabilidade das equações é necessária <marker>para quando</marker> se quer transmitir dados.</example>
    </rule>
```

`pronomes_obliquos_sem_a_as_o_os="l[ao]s?|lh[aeo]s?|n[ao]s?|me|se|te|vos"`

With just these pronouns, there should be no false positives.
