### ISSUE TITLE
[pt] Idea for rule “o que está” → “o” - 2022-11-03

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7387]
Hello @ricardojosehlima

I have just come up with an idea for a rule.

Look at the sentence:
`Agimos perante o que está estipulado no manual de utilizador.`

`“o que está estipulado”` → `“o estipulado”`

Basically, it would check for:
SPS00 + o(s)/a(s) + que + verb “estar” + verb_past_participle

Maybe it can also work with other verbs than just “estar”, it is just a matter of testing.

Do we have a plan?

Thanks!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
cool 😄

**Comment by marcoagpinto** [comment]
Ahhhhh… it only seems to work with “está/estão”.

However, I have extracted all hits with any token before the “o/a que” to see which ones would work.

It gave tons of false positives.

I am doing another extracting of the hits with just SPS00 (“perante”, etc. and the verb “ser”).

It seems that with SPS00/Verb “ser” it works fine.

I will post here the results after it finishes processing.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Some philosophy questions are going through my mind.

This is what we get with “<token/>” (any word before “o que”):

```
Portuguese (Portugal): 54 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[4_token_all.txt](https://github.com/languagetool-org/languagetool/files/9935530/4_token_all.txt)

This is what we get if we use the SPS00 (from “perante”, which produced 0 hits) and the verb “ser” (which produces 3 hits):
Portuguese (Portugal): 3 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence

[5_sps00_verbo_ser.txt](https://github.com/languagetool-org/languagetool/files/9935539/5_sps00_verbo_ser.txt)

From these 3 hits the one I like the most is:
`Nota: As teclas numpad são as que estão localizadas no teclado numérico.`

The other two hits, one seems acceptable and the other wrong: “Isso é o que está errado.”

Do you have any idea what we should do?

Limit the rule only to SPS00? Or focus in the token after the verb in past participle?

Thanks!

**Comment by marcoagpinto** [comment]
Here is how the rule looks like currently:

```
    <!-- O QUE ESTÁ ESTIPULADO o estipulado -->
    <rule id='O_QUE_ESTAR_PARTICIPIOPASSADO' name="Simplificar: O que está + V. Part. Passado → o + V. Part. Passado" type="style">
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2022-11-04 (25-JUL-2022+) -->
      <!--
      Agimos perante o que está estipulado no manual de utilizador. → Agimos perante o estipulado no manual de utilizador.
      -->
      <pattern>
		<or>
          <token postag='SPS00' postag_regexp='no'/>
		  <token inflected='yes'>ser</token>
        </or>
		<marker>
          <token postag='DA.+' postag_regexp='yes'/>
		  <token>que</token>
		  <token regexp='yes'>está|estão</token>
		  <token postag='VMP00.+' postag_regexp='yes'/>
        </marker>
      </pattern>
      <message>Esta perífrase poderá ser simplificada.</message>
      <suggestion>\2 \5</suggestion>
      <example correction="o estipulado">Agimos perante <marker>o que está estipulado</marker> no manual de utilizador.</example>
    </rule>
```

**Comment by ricardojosehlima** [comment]
Maybe keep it to SPS00 is better

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Thank you for the tips!

Here it is the commit with SPS00:
https://github.com/languagetool-org/languagetool/commit/85ec57f372f8a4c801aa8d5d410ac33f25da98d9
