### ISSUE TITLE
[nl] Please make simple replace case specific

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#7392]
In Dutch, common words are all lowercase. Only at the start of the sentence, or in proper names, capitals are used.
So simple replace had better be case specific, because many exceptions come from proper names. Many proper names are also commons words (like Word/word in English), but are used quite differently.

**Comment by danielnaber** [comment]
This should be working now. An entry like `kudde eigenschappen=kudde-eigenschappen` in `replace.txt` now means that `kudde eigenschappen` matches, but `Kudde eigenschappen` does not, except at the start of a sentence.

**Comment by baarsrj** [comment]
In most cases, it works like a charm. 
I noticed however that in the nightly, Amsterdam Zuidoost did no longer match at the start of the sentence. But it should, shouldn't it?
Example:
Amsterdam Zuidoost heeft 82 855 inwoners verdeeld over 42 160 huishoudens.

**Comment by danielnaber** [comment]
Mhh, it seems the current logic only works for the first character...

**Comment by baarsrj** [comment]
The first-char implementation is also not as desired:
PVC vloer=pvc-vloer leads to: Pvc-vloer (in the middle of the sentence); the first letter wrong.

**Comment by baarsrj** [comment]
The changecis being prepared. To keep LT working as usual, all replaces that happen at sent start havecto be added. Checking this takes time.

**Comment by baarsrj** [comment]
Done.
