### ISSUE TITLE
Fehlalarm mit "Ringende/Ring-Ende"

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#7397]
Moin liebes LanguageTool-Team

Sie ging zu **einem Ringende** und er zum gegenüberliegenden Ringende.
LT: "Evtl. keine Übereinstimmung von Kasus, Genus oder Numerus"

Vermutlich ein Problem mit dem Splitter oder der Tokens.

Grüße Dallun511

**Comment by tiff** [comment]
Behoben :)
