### ISSUE TITLE
[pt] Idea for rule “'a' seems to be missing before verb” - 2022-11-07

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7407]
Hello @ricardojosehlima

Yesterday or so, I wrote the following sentence on IRC:
`"Existem tantos sistemas estrelares. Já alguém os visitou todos? Eu serei a primeira pessoa fazê-lo"`
(quoting Star Wars).

Notice the last part, it says: “pessoa fazê-lo”, there is an “a” missing before the verb.

I believe it is a good idea for a rule?

It would search for:
Noun + Verb
and suggest:
Noun + “a” + Verb

The message would be:
`“Parece faltar o artigo 'a' antes do verbo.”`

I wonder if it will work with all verbs forms, I know it works with above's structure plus infinitive verbs.

Thanks!

❤️ ❤️ ❤️ ❤️ ❤️

**Comment by ricardojosehlima** [comment]
Hmm let's see "Eu vi a pessoa fazê-lo" seems fine and there is no "a". if possible, it will be hard to make the rule...

**Comment by marcoagpinto** [comment]
Ahhhhh… well spotted, thanks!

It will take a lot of work, but I believe we have nothing to lose.

I will use your example for the antipattern.

Brother Ricardo, we are in the good way!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

This is very hard to code.

First try (0.txt)
```
Portuguese (Portugal): 1508 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

Current results (15.txt)
```
Portuguese (Portugal): 563 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

**Comment by ricardojosehlima** [comment]
that's what I thought... (by the way, the file wasn't included).

**Comment by marcoagpinto** [comment]
ahhhh… sorry

This is 0.txt:
[0.txt](https://github.com/languagetool-org/languagetool/files/9956622/0.txt)
(a huge mess)

This is 16.txt (just finished processing)
[16stable.txt](https://github.com/languagetool-org/languagetool/files/9956625/16stable.txt)

And it is only with “VMN0000X”, after I insert the infinitive POS the number of false positives will increase again.

I guess tomorrow I will dedicate most of the day to fix the rule.

**Comment by marcoagpinto** [comment]
It is 2am, I am leaving to bed, during the day I will resume the task.

Here is the current state:
```
Portuguese (Portugal): 266 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```
[26stable.txt](https://github.com/languagetool-org/languagetool/files/9957035/26stable.txt)

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I am still working on it.

It is very hard.

😄 😄 😄 😄 😄 😄 😄 

I will make a break soon.

I believe it will take more than a day to have it ready.

**Comment by ricardojosehlima** [comment]
Dear friend, it seems extremely hard. Why not concentrate only in the verb fazer...? Even so it will be hard... Can't see how...

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

“Resistance is futile, we will win”

If by tomorrow night it is not working, I will give up.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is not working.

I have an idea.

What if I just make some basic checking for this rule, for example:
```
Eu serei a primeira pessoa fazê-lo. → Eu serei a primeira pessoa a fazê-lo.
Quem será o homem fazê-lo. → Quem será o homem a fazê-lo.
```

Basically, after the final verb, it will end with a _PUNCT.

I must also do it for infinitive.

This way it will reduce a lot the number of possible tokens.

Does it sound more doable?

Yes, “resistance is futile” but no victory this time. 😄 😄 😄 😄

**Comment by ricardojosehlima** [comment]
It still doesn't solve "Eu vi uma pessoa fazê-lo."...

**Comment by marcoagpinto** [comment]
Ricardo, is it wrong: "Eu vi uma pessoa A fazê-lo."?

**Comment by marcoagpinto** [comment]
Well, I give up then, it is too hard.

It sounded like a good idea, but it is almost impossible to make it work.

❤️ ❤️ ❤️ ❤️ 😄 😄 😄 😄 😄 😄 😄
