### ISSUE TITLE
[pt] Idea for rule: “meia-” → “meio-" - 2022-11-10

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7416]
Hello dear brother @ricardojosehlima

Look at the sentence:
`A garrafa está meia-cheia.`

It is always written “meio-” in pt-PT.

Is it the same in pt-BR?

If so, I was thinking about creating a rule for it, but I don't know what to write in the suggestion message.

Do you have an idea of what to write?

Thanks!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by ricardojosehlima** [comment]
Hi in pt-br it's without the hyphen
A garrafa está meio cheia.

So you would capture meia + adjective to change to meio + adjective, correct?

So
Meio nesse caso é um advérbio por modificar um adjetivo e por isso não varia.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello!!!

It is done:
https://github.com/languagetool-org/languagetool/commit/8b4d1dc0d9ac56e3a5378e1a63b5ac6b7b65e634

First try:
```
Portuguese (Portugal): 36 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[0.txt](https://github.com/languagetool-org/languagetool/files/9984341/0.txt)


With the fixes:
```
Portuguese (Portugal): 8 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[3.txt](https://github.com/languagetool-org/languagetool/files/9984343/3.txt)


To be honest, the results happen basically with similar words, so, either they are all right or all wrong.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello, dear brother Ricardo,

Since you told me that “meio” + adjective doesn't use hyphen in -BR, I had the idea of creating a pt-PT rule to suggest hyphen to all “meio” + adjective.

Commit:
https://github.com/languagetool-org/languagetool/commit/011f0b20205229ea0bad2b2c56a3163381653972

I have added an exception for situations such as:
```
“O Rui andou meio metro.”
“A Ana ganhou meio milhão de euros.”
```

(for distances and measures words, it doesn't suggest the hyphen) - is this the right way?

Thanks!

```
Portuguese (Portugal): 222 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[1_PT_PT_meio_hyphen.txt](https://github.com/languagetool-org/languagetool/files/9989410/1_PT_PT_meio_hyphen.txt)

**Comment by ricardojosehlima** [comment]
Sounds nice!
As for the examples, the ones about meia inglesa are rare, the others are correct.
However how is LT classifying meia in

Comprei uma meia bonita

? 
This case can't be captured by the rule

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It only accepts “V.+|NC.+|AQ.+” before “meia”.

This removed tons of false positives.

"uma” is “DI.+”, it is not accepted, too many false positives, I believe.

Better to have fewer results and they being correct, than having a ton of incorrect results.
