### ISSUE TITLE
CKEditor 5: One-click-correction stopped working with 35.3.0

### ISSUE THREAD

**Issue by TobiasHartlehnert** [languagetool-org/languagetool#7427]
Due to refactoring of some core aspects of **CKEditor 5**, the one-click-correction of LanguageTool stopped working starting with version [35.3.0](https://github.com/ckeditor/ckeditor5/blob/v35.3.0/CHANGELOG.md), released on 2022-11-02.

### Reproduction steps
1. Navigate to [Classic Editor example](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html)
2. Click inside the editing area; LanguageTool will underline "earth" in first paragraph as a possible error
3. Click anywhere inside "earth" to open the LanguageTool correction box
4. Click on the suggested correction "earth," (blue button)

### ✔️ Expected result

"earth" should change to "earth,"

### ❌ Actual result

Text is not changed. JS error is thrown, see Console (Chrome: "Uncaught TypeError: Cannot read properties of null (reading 'root') ...", Firefox: "Uncaught CKEditorError: i is null ...").

## 📃 Other details

* Browser: Chrome 107.0.5304.106, Firefox 106.0.5
* OS: Windows 10 Pro

I already opened an issue @ [ckeditor5 repo](https://github.com/ckeditor/ckeditor5/issues/12824), and the team acknowledged the issue as a result of the [beforeInput refactoring](https://github.com/ckeditor/ckeditor5/issues/11438) that came with 35.3.0:

> It looks like this browser extension is using beforeInput:insertText but it is not providing targetRanges this might be easy to fix by enabling fallback to the DOM document selection.

It would be nice if you can fix this on your end, instead of having CKEditor implement a workaround, as [Reinmar](https://github.com/ckeditor/ckeditor5/issues/12824#issuecomment-1309927630) suggested.

**Comment by tiff** [comment]
Thanks for bringing this to our attention. We will begin rolling out a fix for this, beginning of next week.
