### ISSUE TITLE
[pt] Idea for rule: “para o público” → “pública” - 2022-11-17

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7439]
@ricardojosehlima

Hello Dear Brother,

Sorry for my silence.

Here is a cool idea for a rule.

Look at the sentence:
`Esta é a primeira versão do software para o público.`

What about a rule:
NC/AQ + “para o público”
to suggest:
NC/AQ +  “pública”?

`Esta é a primeira versão do software pública.`

I can work on it in a few hours.

Is it a good idea?

Thank you!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by ricardojosehlima** [comment]
Hi it can work!

**Comment by marcoagpinto** [comment]
Cool!

We have a plan.

I was reflecting about the gender of “pública”/“público” and it is a bit tricky to get it, so I thought about suggesting both and the user chooses based on context.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello!

It is done:
https://github.com/languagetool-org/languagetool/commit/52a4e645c432c945fea828fdfe1d38d5f22beff2

The original idea didn't turn out very well:
```
Portuguese (Portugal): 14 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[0.txt](https://github.com/languagetool-org/languagetool/files/10036256/0.txt)

So, I have rewritten the logic of the rule, and now it only gives 1 hit in 600 000 sentences, but I believe it looks very good.

```
Portuguese (Portugal): 1 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[2.txt](https://github.com/languagetool-org/languagetool/files/10036263/2.txt)

**Comment by ricardojosehlima** [comment]
Sure!
