### ISSUE TITLE
Question regarding memory use - continuous increase

### ISSUE THREAD

**Issue by squalou** [languagetool-org/languagetool#7442]
Hi,

I've set up a languagetool server version `5.9` to be used with browser plugin.
It works great.
Issue is : it's memory use constantly increases until it runs out of memory. 
I've started it with option `Java_Xmx=2G` to have it run long enough between reboots, but still I wonder if I'm missing something.

It runs with `openjdk version "11.0.16.1"`

full startup comand is 

```
java -Xms256m -Xmx2G -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8080 --public --allow-origin * --config config.properties
```

Are there other options to prevent some sort of cache, or release it ?

thank you for any clue (even a pointer to the right RTFM will do ;) )

**Comment by danielnaber** [comment]
Hi, which languages do you check and how long does it take before the out of memory happens?

**Comment by squalou** [comment]
I check French mostly, more rarely english.

When using Xmx 1G, it took a few hours before OOM.

Interesting part is : when I set Xmx 2G, the "used" memory quickly (say, one hour) reach 85%, then slowly keeps increasing.

**Comment by danielnaber** [comment]
We don't experience this on our servers, but our use case is different and we use more memory. If you can reproduce this, e.g. by sending data to the server with a script, we might be able to debug this.

**Comment by squalou** [comment]
Ok, I'll try and let you know.

Anyhow, if simply inceasing memory a bit helps, it would be fine.
(and as the server starts very fast, there is no real "service interruption", even if it happens every now and then)

**Comment by squalou** [comment]
Hi again,
after a few tests, I managed ... to come to the obvious cause :)

Whenever a "new" language is loaded, it seems to bump the memory usage. Which makes sense.

What I did
- started a local serveur with Jmx 512M
- took en FR book on project gutenberg and looped over lines to stress the server with curl with language=fr
- *it works fine*, memory stable
- then one curl query with language="en" for instance, and boom, out of memory

(all this monitored with visualVM to be sure)

SO finally, I would have one last question : is it possible to restrict available languages ?

(once again I sincerely apologize  if it is already documented)

**Comment by danielnaber** [comment]
> is it possible to restrict available languages ?

I don't think there's an option for that.

**Comment by squalou** [comment]
I could remove the related resources from the running server, but that's ugly :)
logs would be full of exceptions (and probably side effects)

2022-11-22 08:52:24.484 +0000 ERROR org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'java.lang.NoClassDefFoundError: Could not initialize class org.languagetool.rules.en.EnglishRepeatedWordsRule, detected: fr', sending HTTP code 500. 


I wonder how/where in the code are inferred the supported languages

**Comment by danielnaber** [comment]
> I wonder how/where in the code are inferred the supported languages

They are references in `META-INF/org/languagetool/language-module.properties`.
