### ISSUE TITLE
[DE] LanguageTool hängt sich bei großen Dokumenten auf

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#7450]
Moin liebes LangaugeTool-Team

Ich kann euch für folgendes Problem möglicherweise kein Dummydokument für den Selbsttest geben, aber ich kann euch erklären, was zu tun ist, um das LanguageTool zum Aufhängen zu bringen, dafür muss das Dokument groß sein.

In meinen Fall:
200 Seiten
160.000 Wörter (aufgerundet)
1.000.000 Zeichen (aufgerundet)
Das Dokument ist in zehn Kapiteln aufgeteilt.

Das Dokument lässt sich normal bearbeiten. Also neue Wörter hinzufügen, alte entfernen. Das gängige Tippen.
Was wiederum das LanguageTool unwideruflich zum Aufhängen bringt, ist die Enter-Taste. Zweimal Enter und das LanguageTool hängt sich auf und nimmt LibreOffice mit.

Das Programm muss mit der Holzhammermethode abgeschossen werden, wodurch es zum Datenverlust kommt.

Dies passiert mir aktuell immer und lässt sich ohne Probleme nachstellen. 

Das ist sehr nervig und frustrierend, weil Daten verloren gehen und würde mir wünschen, wenn ihr das behoben bekommt.

Ich werde schauen, ob ich ein Dummy-Dokument hinbekomme, wo ich das Problemen emulieren kann. Bis dahin viel Glück.

**Comment by danielnaber** [comment]
@FredKruse

**Comment by FredKruse** [comment]
@MasterDallun511 Mit welcher Version von LT arbeitest du?

**Comment by MasterDallun511** [comment]
Version: 7.3.5.2 (x64) / LibreOffice Community
Build ID: 184fe81b8c8c30d8b5082578aee2fed2ea847c01
CPU threads: 20; OS: Windows 10.0 Build 22000; UI render: Skia/Vulkan; VCL: win
Locale: de-DE (de_DE); UI: de-DE
Calc: CL

LanguageTool 5.9 (2022-09-28 14:38:38 +0000, f8931be)
OS: Windows 10 10.0 (amd64)
LibreOffice 7.3.5.2 (The Document Foundation), de
Java version: 17.0.1 (Oracle Corporation)
Java max/total/free memory: 4042MB, 1122MB, 584MB

**Comment by MasterDallun511** [comment]
LanguageTool 6.0-SNAPSHOT (2022-11-20 17:44:16 +0000, cd38209)
OS: Windows 10 10.0 (amd64)
LibreOffice 7.3.5.2 (The Document Foundation), de
Java version: 17.0.1 (Oracle Corporation)
Java max/total/free memory: 4042MB, 974MB, 625MB

Ich habe mal diese Version ausprobiert und diese federt das ab. Hängt sehr kurz, aber fängt sich wieder. Ich beobachte dies mit dieser Version. Vielleicht triggert der Hänger an einer anderen Stelle.

**Comment by MasterDallun511** [comment]
Nach längerer Nutzung ist mir ein Grund aufgefallen, warum sich die alte Version aufgehangen hat. Wenn man in einem Kapitel doppeltes Enter betätigt, springt das Dokument völlig ramdom nach unten und nicht zu der Stelle, wo das doppelte Enter betätigt wurde.

Kurz statt von Zeile 1 zu 3, sondern zu Zeile 8. 

Das könnte dafür sorgen, dass das LanguageTool den Text neu einliest und deswegen ein Abstürz die Folge sein könnte.
