### ISSUE TITLE
SynthDictionaryBuilder: write xyz_tags.txt to better location

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#746]
Currently it's written to temp, which causes it to be ignored. See http://forum.languagetool.org/t/reverse-postag-lookup-please-help/1933/8. It should probably be written to the same directory as the `*.dict` file.

**Comment by gatitoneku** [comment]
Hello, i'm new to open-source. Can i try to do this one?

**Comment by danielnaber** [comment]
> Can i try to do this one?

Sure!

**Comment by gatitoneku** [comment]
Hmm weird, i also tested the master branch and it failed the English module. Is it because of the recent commits?

**Comment by danielnaber** [comment]
> Hmm weird, i also tested the master branch and it failed the English module. Is it because of the recent commits?

It's not because of your change I think, something else broke the build.
