### ISSUE TITLE
[pt] Idea for rule “não + ter + nc/aq” → “sem + nc/aq” - 2022-11-23

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7470]
@ricardojosehlima

Hello, dear brother,

Look at this sentence:
`(...) , ainda o concluirei, embora não terá utilidade a nível profissional.`

The “não” + verb “ter”, if used in present or future, could we replace with “sem”?:
`(...) embora SEM utilidade a nível profissional.`
?

Thanks!

**Comment by marcoagpinto** [comment]
The other powerful rule is lost, I didn't write it down, but as I write more e-mails some ideas will come to other complex rules.

**Comment by ricardojosehlima** [comment]
Hi!
As a rule that deals with verb and subject, it may be hard to code (I've already mentioned LT's limitation with syntactic rules):

O menino terá dinheiro, mas não terá felicidade ==> O menino terá dinheiro, mas sem felicidade (???) (does it make sense?)

**Comment by marcoagpinto** [comment]
Hello!

Thanks!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I was napping and the moment I woke up, I came up with an idea for the rule: what if I hardcode the words it will work with?

I can make it run against <token/> and write down as many valid words as possible.

Maybe this will do it?

If it is a good idea, should it be used with the verb in present + future?

Thanks!

**Comment by ricardojosehlima** [comment]
that's a way... but then the rule becomes too restricted, doesn't it?

**Comment by marcoagpinto** [comment]
Yes, the rule will become too strict. But better to have one than to have none.

😄 

Just my 2 cents, like Americans say.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

My brains keeps on bursting with ideas.

What if after the noun/adjective, it will require “[ao]s?”.

```
“O menino terá dinheiro, mas não terá felicidade a curto prazo.”
“O menino terá dinheiro, mas sem felicidade a curto prazo.”
```
?

Well, I guess I should give up on the rule.

**Comment by ricardojosehlima** [comment]
Maybe a good idea. I understand that one small rule is better than none, but sometimes some contexts are too specific...

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Dear brother!!!

Is that comment to the “[ao]s?” ?

**Comment by marcoagpinto** [comment]
ahhh... maybe a good idea to give up or maybe a good idea to use “[ao]s?”?

**Comment by ricardojosehlima** [comment]
A good idea to give up... :(

**Comment by marcoagpinto** [comment]
ahhhh… right… I give up then.

😄 😄 😄 😄 😄 😄 

More ideas will pop up.
