### ISSUE TITLE
NullPointerException on packaging language tool features as a JAR

### ISSUE THREAD

**Issue by Madusudanan** [languagetool-org/languagetool#748]
We are using language tool in a scala project and using sbt assembly to build. Below is a short code snippet just to demonstrate this issue.

```
import org.languagetool.{JLanguageTool, Languages}

object Test extends App{

  //The list is empty when packaged as a JAR using sbt assembly
  //Hence it results in an NPE
  //Working with Intellij IDE seems to be fine
  val language = Languages.get().get(1)
  val jLanguageTool: JLanguageTool = new JLanguageTool(language)
  

}
```

I am not sure what is happening because the same code works well when run inside in an IDE instead of a JAR. It seems that the language libraries are not included when packaging? Is this a known issue? Is someone else facing this? Is there anything else to include so that it works well as a packaged jar.

Below are the lines in my build.sbt

```
"org.languagetool" % "languagetool-core" % "3.8",
  "org.languagetool" % "language-en" % "3.8",
```

**Comment by danielnaber** [comment]
If the list is really empty, please check your JAR for [the required file and its content](https://languagetool.org/development/api/org/languagetool/Languages.html#get--). Or is it maybe not empty but has only one element? Then you'd need to use `get(0)` I guess.

**Comment by Madusudanan** [comment]
The issue was with the merge strategy. We added a below case to handle it. If anyone is facing the same problem then please include the below line as the first case in the assembly merge strategy.

```
case "META-INF/org/languagetool/language-module.properties" => MergeStrategy.first
```

Thanks for your help.
