### ISSUE TITLE
High severity vulnerabilities in the lucene-core.jar and json.jar libraries

### ISSUE THREAD

**Issue by AAbakumov** [languagetool-org/languagetool#7488]
Hi, 
Recently we scanned LanguageTool 5.9.0 package using Jfrog XRAY, there 2 more more vulnerabilites with severity marked as High, but there no CVEs for them yet. Could you please take a look on them?

| Vulnerable Component                | Decription                                                                                                  | Fixed version | Severity |
|-------------------------------------|-------------------------------------------------------------------------------------------------------------|---------------|----------|
| org.apache.lucene:lucene-core:5.5.5 | Apache Lucene Operations Class Improper Regular Expression Handling CPU Consumption   remote DoS            | 8.10.0, 9.0.0 | High     |
| org.json:json:20200518              | JSON-java JSONTokener::nextValue() Function Nested Object Handling Unlimited Recursion Stack Exhaustion DoS | 20220320      | High     |

**Comment by SteVio89** [comment]
Hi,

Thanks for bringing this to our attention. I updated the org.json dependency to the newest
Version.

For the org.apache.lucene dependency, I cannot update this, as our ngram file format version is not supported by these versions. This also should not be an issue as we only use this dependency for the ngram data we create.
