### ISSUE TITLE
Purchase Not working

### ISSUE THREAD

**Issue by bobaikato** [languagetool-org/languagetool#7493]
I want to buy a 2year sub, with the current 20% discount.
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/14136806/204504951-5cd05bba-4bfd-4140-b79e-a549e2b6a373.png">

**Comment by tiff** [comment]
Do you have any script blockers installed?

**Comment by bobaikato** [comment]
Turns out it was my VPN
