### ISSUE TITLE
[de] filter spell check suggestions

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#7499]
In German, when misspelling the base form of an adjective like "glücklich" all inflected forms are suggested which, from a user perspective, makes it harder to decide which to choose.

**Example:**
Here I misspelled "glücklich" as "glückklich" and only the first suggestion is the desired one. It's very unlikely that I meant "glückliche" or "glückliches":

<img width="374" alt="Bildschirmfoto 2022-11-30 um 17 57 04" src="https://user-images.githubusercontent.com/37363/204860160-c476b5d0-4adc-4e33-afce-1514cd00ebea.png">

Can we filter out suggestions where the lemma is the same as the first suggested word?

There's one exception: When the typo is at the end of the word. Here I misspell "glücklich" as "glücklichr" and I could actually mean "glückliche" or "glücklicher"

<img width="469" alt="Bildschirmfoto 2022-11-30 um 17 58 57" src="https://user-images.githubusercontent.com/37363/204860599-7a757ed9-878e-4d98-be5b-f7b52b188c26.png">

So the logic could be
* if the first suggested word is an adjective base form (`ADJ:PRD:GRU`) and the last letter is the same as the misspelled word, then filter out all suggestions for which: lemma == first suggested word

@danielnaber @jaumeortola what do you think?

**Comment by tiff** [comment]
Same actually for nouns:

<img width="458" alt="Bildschirmfoto 2022-11-30 um 18 14 31" src="https://user-images.githubusercontent.com/37363/204863996-90d6ddfd-473c-464f-ac32-4901174cd4bb.png">

Here "Fußballs" (genitive) and "Fußbälle" (plural) are very unlikely meant. The first suggested word "Fußball" would be correct.

**Comment by jaumeortola** [comment]
It makes sense. In the case of German, the best place to implement it is `GermanSpellerRule.getFilteredSuggestions()`?

**Comment by tiff** [comment]
Sounds good, but I think it's something that @danielnaber has to answer as I'm not familiar with the code.

**Comment by danielnaber** [comment]
> the best place to implement it is GermanSpellerRule.getFilteredSuggestions()

That, or `GermanSpellerRule.filterForLanguage()` which runs a bit later and *might* be the better place.

**Comment by tiff** [comment]
Thanks, I will check the diff tomorrow and let you know if it works as expected

**Comment by tiff** [comment]
I'm reopening:

* [ ] It seems that either it's not deployed or not working as it should (I tested against the current deployed Open Source version):
![Bildschirmfoto 2022-12-08 um 16 28 40](https://user-images.githubusercontent.com/37363/206486731-cc71b74b-b90f-4305-802d-702ca3cbf44d.png)

* [ ] We can use the exact same mechanism for `PA1:.*` and `PA2:.*` (which can be treated like adjectives):
> Er hat es erleddigt 

![Bildschirmfoto 2022-12-08 um 16 33 23](https://user-images.githubusercontent.com/37363/206487907-abe2c900-19eb-48c8-9ccb-680fc1c656b5.png)

"erledigte" should be filtered out


@jaumeortola could you have a look when you have time? Thanks!

**Comment by tiff** [comment]
Also,

* [ ] Using an inflected form like "glückliche" should not suggest all other inflected forms:

![Bildschirmfoto 2022-12-08 um 16 37 38](https://user-images.githubusercontent.com/37363/206489262-b7315794-22a5-4d5e-a1f0-e59690532fea.png)

Only the first suggestion "glückliche" would be correct here.

**Comment by jaumeortola** [comment]
The previous commit is not yet in the master branch.

**Comment by tiff** [comment]
Ah, thanks, I can confirm that it now works as expected. I guess it wasn't deployed yet.

For the case of "glücklichhe": As you suggested, If the first suggestion is an adjective which ends with the same two letters then filter out all suggestions which have the same lemma as the first suggestion. I think this could work.

**Comment by jaumeortola** [comment]
Done. Now we check the last two letters. 

As for "glücklichst", if we want to remove it from the suggestions, we need to tag it.

**Comment by tiff** [comment]
Thanks, looks all good. Closing
