### ISSUE TITLE
Russian false alarms / missing words

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#750]
Some feedback I got via email:

Words:
1. Фреймворка = framework (Borrowed word)
2. Лендинга = landing (Borrowed word)
3. Требушет = Trebuchet (not mistake)
4. Чат-бота = Chat-bot (Borrowed word)
5. Каспар = Kaspar(Jasper ...) one of Adjective\Name form
6. Редизайн = redesign (Borrowed word)

Decline:
1. Интернет-магазины = one of decline form of internet-shop. Utilite propose me to use 'Интернет-магазин \Интернет-магазине'
2. Интернет-коммерции - utilite porpose to use 'интернет-коммерция' it's wrong case
3. Агрегаторах - utilite porpose to use 'агрегатор ах' it's wrong case
4. Анимаций - propose - 'анимации  анимацию  анимацией  анимация'. It's just another case in plural.
5. Новорожденном = care about newborn. Propose to use 'новорождённый' it's wrong case
6. Веб-разработки - it's process case, not man like in porpose 'веб-разработчик'

@yakovru maybe you can have a look.

**Comment by yakovru** [comment]
Fixed in https://github.com/languagetool-org/languagetool/commit/8c459af9dcee933e6a94451d157669cdb8ce423d#diff-28f9bb24c2e2afb35faf7788e5dfeca6

But words 'новорождённый',  'новорождённом' are right form,  form  'новорожденном' is talk form.
