### ISSUE TITLE
[pt] Idea for rule: “que eu rapidamente usei” → remove “eu”/“nós” - 2022-12-01

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7504]
@ricardojosehlima

Hello!

Here is an easy to implement idea:
`[16:34:58] <Master_of_Chaos> que eu rapidamente usei`

“que” + “eu”/“nós” + RM + “usei/usamos/usámos”

Remove “eu”/“nós”

What is your opinion?

This should be very easy to code, and it might generate tons of hits.

Thanks!

**Comment by marcoagpinto** [comment]
Ahhhhh… it should also be done if no RM is found, I guess.

**Comment by marcoagpinto** [comment]
EDIT:
“usei/usamos/usámos”
This is just an example, it should be done with all verbs.

**Comment by ricardojosehlima** [comment]
Hi, although sometimes not using the pronoun might seem artificial in pt-br, it's well considered not to use in formal texts, so it's worth a try (also there may be cases where the pronoun is required, but we'll see in the hits).

**Comment by marcoagpinto** [comment]
Ricardo, dear brother,

I will work on it at 5am, or maybe tonight if I get to bed late.

Thank you for the feedback.

🤗 🤗 🤗 ❤️ ❤️ ❤️ 😛 😛😛

**Comment by marcoagpinto** [comment]
Ricardo,

Here are the first number results with just “vanilla”, or whatever it is called.

```
Portuguese (Portugal): 1114 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

I am creating antipatterns and in a few hours I will post the 0.txt and the latest .txt with all the fixes, for you to see what changed between 0.txt and the latest.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Dear Ricardo,

Here are the results:
PLAIN VANILLA:
```
Portuguese (Portugal): 1114 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```
[0.txt](https://github.com/languagetool-org/languagetool/files/10140401/0.txt)


CURRENT “eu”:
```
Portuguese (Portugal): 765 total matches
Portuguese (Portugal): 582235 total sentences considered
```
[12_eu.txt](https://github.com/languagetool-org/languagetool/files/10140404/12_eu.txt)

CURRENT “nós”:
```
Portuguese (Portugal): 127 total matches
Portuguese (Portugal): 582235 total sentences considered
```
[12_nós.txt](https://github.com/languagetool-org/languagetool/files/10140406/12_nos.txt)


CURRENT “eu” + “nós”:
```
Portuguese (Portugal): 892 total matches
Portuguese (Portugal): 582235 total sentences considered
```
[12_eu_and_nós.txt](https://github.com/languagetool-org/languagetool/files/10140408/12_eu_and_nos.txt)


Here is the rule, there was no need for antipatterns after all:
(the rule ignores sentences that after the verb have a “?” or “!” because these sentences need to emphasise the person pronoun)

```
    <!-- QUE EU RAPIDAMENTE USEI que rapidamente usei -->
    <rulegroup id='REMOVER_EU_NÓS' name="Simplificar: Eliminação do pronome pessoal eu/nós" type='style'>
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2022-12-02 (25-JUL-2022+) -->
      <!--
      Este foi o truque que eu usei. → Este foi o truque que usei.
      Este foi o truque que eu rapidamente usei. → Este foi o truque que rapidamente usei.

      Este foi o truque que nós usámos. → Este foi o truque que nós usámos.
      Este foi o truque que nós rapidamente usámos. → Este foi o truque que nós rapidamente usámos.

      Este foi o truque que nós usamos. → Este foi o truque que nós usamos.
      Este foi o truque que nós rapidamente usamos. → Este foi o truque que nós rapidamente usamos.
      -->

      <!-- WITHOUT ADVERB -->
      <rule>
        <pattern>
          <token><exception postag_regexp='yes' postag='_PUNCT|_QUOT'/></token>
          <marker>
            <token>que</token>
            <token regexp='yes'>eu|nós</token>
            <token postag='VMIS1.+' postag_regexp='yes'>
              <exception postag_regexp='yes' postag='VMI[CIS]3S0'/>
            </token>
          </marker>
          <token><exception postag_regexp='yes' postag='_PUNCT_INTERROGATION|_PUNCT_EXCLAMATION'/></token>
        </pattern>
        <message>Poderá omitir o pronome pessoal nesta perífrase.</message>
        <suggestion>\2 \4</suggestion>
        <example correction="que usei">Este foi o truque <marker>que eu usei</marker>.</example>
        <example correction="que usámos">Este foi o truque <marker>que nós usámos</marker>.</example>
        <example correction="que usamos">Este foi o truque <marker>que nós usamos</marker>.</example>
      </rule>

      <!-- WITH ADVERB -->
      <rule>
        <pattern>
          <token><exception postag_regexp='yes' postag='_PUNCT|_QUOT'/></token>
          <marker>
            <token>que</token>
            <token regexp='yes'>eu|nós</token>
            <token postag='RM' postag_regexp='no'/>
            <token postag='VMIS1.+' postag_regexp='yes'>
              <exception postag_regexp='yes' postag='VMI[CIS]3S0'/>
            </token>
          </marker>
          <token><exception postag_regexp='yes' postag='_PUNCT_INTERROGATION|_PUNCT_EXCLAMATION'/></token>
        </pattern>
        <message>Poderá omitir o pronome pessoal nesta perífrase.</message>
        <suggestion>\2 \4 \5</suggestion>
        <example correction="que rapidamente usei">Este foi o truque <marker>que eu rapidamente usei</marker>.</example>
        <example correction="que rapidamente usámos">Este foi o truque <marker>que nós rapidamente usámos</marker>.</example>
        <example correction="que rapidamente usamos">Este foi o truque <marker>que nós rapidamente usamos</marker>.</example>
      </rule>      

    </rulegroup>
```

**Comment by ricardojosehlima** [comment]
Hi!
  As I said, the rule wouldn't find many difficulties, and so it was. A nice work! No comments on the "nós", but for "eu" I'd like to draw your attention to this:

É um carro que eu comprei.

Imagine that the context before is someone saying that other person bought the car. Then I'd oppose to that and emphasize "eu" - sometimes we do this capitalizing the pronoun "É um carro que EU comprei.", but in most cases, the mere presence of the pronoun suffices to indicate that it's "eu" and not someone else.

Maybe the suggestion should point it out? I don't think so. If the rule suggests eliminating the pronoun and the user wants to maintain it, that will not be the most common case.

That said, for me, the rule is fine as is!

**Comment by ricardojosehlima** [comment]
A question: in pt-br we don't use "tu" or "vós" in their standard form "tu estás", "vós estareis" (maybe "tu" in some regions). So is already there a rule for "tu" and "vós" similar to this on "eu" and "nós"? @marcoagpinto what do you think?

**Comment by marcoagpinto** [comment]
Yes, I believe the pt-PT grammar.xml has a rule for “tu”/“vós”/“vocês”.

**Comment by marcoagpinto** [comment]
Yes, it is there:
`<rulegroup id='T-V_DISTINCTION' name='Tratamento formal: Tu,Você; Vós,Vocês' default='on' tags="picky">`

**Comment by ricardojosehlima** [comment]
Oh, no, I was thinking in

Aquilo que tu precisas
Aquilo que precisas

similar to eu-nós

**Comment by ricardojosehlima** [comment]
Oh, nice!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I have committed the rule:
https://github.com/languagetool-org/languagetool/commit/8857d44fb48e6a97b76d3eb8bb0a7c344d341488

If there is a need for enhancements, it can be done at any time.

**Comment by marcoagpinto** [comment]
Later today/tonight, I will post a suggestion for another rule that came up to my mind.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️
