### ISSUE TITLE
[BUG] Extremely high CPU load of LanguageTool for Desktop 1.0 on macOS building up

### ISSUE THREAD

**Issue by j-lakeman** [languagetool-org/languagetool#7505]
I recently updated LanguageTool for Desktop on macOS to version 1.0 via Homebrew. After some time, I realised that a tremendously high CPU load is being used by LanguageTool, as the fan of my MacBook became louder.
I think the issue is only arising after opening the menu of LanguageTool. From then on, I can monitor it in glances or the task manager and both show a building up CPU load of the app, which won't stop until you end the application.

![Bildschirmfoto 2022-11-29 um 00 09 36-obfuscated](https://user-images.githubusercontent.com/101660243/205015364-a0e0c29c-13da-46ca-9448-b483a155c59d.png)

**Comment by schurigeln** [comment]
@J-Lakeman thank you so much for your feedback. We're currently working on a couple of performance improvements and will take the issue you've mentioned into consideration as well. Keep looking out for updates.
