### ISSUE TITLE
Wrong conjugation in French when sentence is negative

### ISSUE THREAD

**Issue by briceparent** [languagetool-org/languagetool#751]
The following sentence is seen as right:

> Les personnes qui ne mange pas.

But `mange` should be corrected  to `mangent`.

But the rule is well applied if the sentence is not negative:

> Les personnes qui mange.

successfully corrected to 

> Les personnes qui mangent.

It seems to be the following rule which is successfully applied in one case but not in the other https://community.languagetool.org/rule/show/QUI_VCONJ?subId=3&lang=fr

But I don't know how to improve it to manage the cases of negative sentences (or if there need to be a new set of rules).

**Comment by danielnaber** [comment]
Maybe you can have a loo, @dpelle?

**Comment by dpelle** [comment]
> Maybe you can have a loo, @dpelle?

I'll improve the rule soon and I'll reply here when it's done.  Thanks for reporting this.
