### ISSUE TITLE
[pt] Idea for rule “tornando possível”=“permitindo” - 2022-12-03

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7518]
Hello @ricardojosehlima

Look at the sentence:
`É preciso um estudo estocástico, tornando possível validar as hipóteses científicas.`

What about suggesting replacing “tornando possível” with “permitindo” (maybe also “possibilitando”?) and using the “tornar” variants for its form?

Thanks!

**Comment by ricardojosehlima** [comment]
Nice idea!

**Comment by marcoagpinto** [comment]
Later today I will code it.

😄 

It is always good to be in the good path.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Sorry for taking so long.

Here it is:
https://github.com/languagetool-org/languagetool/commit/9625405f5b715b500eee03116ba4d56861b6d90a

Plain vanilla:
```
Portuguese (Portugal): 14 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[0.txt](https://github.com/languagetool-org/languagetool/files/10147472/0.txt)

After the `PP.+` exception:
```
Portuguese (Portugal): 9 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[1.txt](https://github.com/languagetool-org/languagetool/files/10147473/1.txt)

**Comment by ricardojosehlima** [comment]
Fine!

**Comment by marcoagpinto** [comment]
Thanks!

@ricardojosehlima 
I haven't told many people yet, but Friday I received the letter saying I am retired for good for disability.

In 2023+, my life will be open-source and PhD.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️
