### ISSUE TITLE
[pt] Add verb to correct number agreement

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#7536]
LT identifies the error in
Chegou as pessoas

but not in
Segue as datas.

I understand that the verb seguir has two transitivities so the above sentence can be an answer to the question "O que ele faz?" and then no correction should apply, as the verb agrees with "ele" not with "as datas".

But the above sentence is extremely common in pt-br with "as datas" being the subject and standard norm says it should be "Seguem as datas".

So the suggestion is a rule for:
verbo seguir
in the singular
at the beginning of a sentence
followed by
a noun or adjective or number in the plural

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I will try to code it tonight, within 30 minutes.

It seems easy with the steps you provided.

I will first code a “plain vanilla” and then try to fix false positives.

**Comment by marcoagpinto** [comment]
Ahhhh… the “key” question:
What name should I give to the rule + suggestion message?

😋 😋 😋 😋

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Silly question:
This is the rule for your first example:
```
      <rule>
        <pattern>
          <token postag_regexp='yes' postag='V...3S.+' inflected='yes' regexp='yes'>&verbos_nao_impessoais;
            <exception>sobre</exception>

            <!-- Fixes by MARCOAGPINTO/RICARDOJOSEHLIMA - 2022-07-21/22 *START*-->
            <exception scope='previous' regexp='yes'>&pronomes_retos;</exception>
            <exception postag_regexp='yes' postag='SPS00|VMN0000'/>
            <exception scope='next' regexp='yes'>a|n[ao]s|me|se|te|lh[aeo]s?|vos|comigo|contigo</exception>
            <exception scope='previous' postag_regexp='yes' postag='AQ..P.+|NC.P.+'/>
            <!-- Fixes by MARCOAGPINTO/RICARDOJOSEHLIMA - 2022-07-21/22 *END*-->

          </token>
          <token postag_regexp='yes' postag='(?:D...|P...|N..|A...)P.+'>
            <exception negate_pos='yes' postag_regexp='yes' postag='(?:D...|P...|N..|A...)P.+'/></token>
        </pattern>
        <message>Este não é um verbo impessoal.</message>
        <suggestion><match no='1' postag_regexp='yes' postag='(V...)3S(.+)' postag_replace='$13P$2'/> \2</suggestion>
        <suggestion>\1 <match no='2' postag_regexp='yes' postag='(D...|P...|N..|A...)P(.+)' postag_replace='$1S$2'/></suggestion>
        <example correction="existem muitas|existe muita">Na vida <marker>existe muitas</marker> coisas boas.</example>
        <example>Por favor, basta nos enviar o inquérito para mais detalhes sobre nossos liquidificadores de alimentos elétricos.</example>
        <example>...s, como eles próprios o são. Os rebanhos, os bens e todos os animais domésticos serão assim nossos. Basta lhes darmos o consentimento e eles habitarão conosco.</example>
      </rule>
```

`<!ENTITY verbos_nao_impessoais "acabar|bastar|chegar|entrar|existir|faltar|ficar|restar|sair|sobrar">`

Will adding the verb to the entity solve the issue?

**Comment by marcoagpinto** [comment]
Ahhhhh… I am giving it a try.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Original rule:
```
Portuguese (Portugal): 53 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```
[0.txt](https://github.com/languagetool-org/languagetool/files/10170699/0.txt)

Adding the verb “seguir” to the entity:
```
Portuguese (Portugal): 126 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

I guess I will need to add antipatterns to fix the whole false positives.

But, is this the way to do it? Add to the entity and then create antipatterns?

**Comment by ricardojosehlima** [comment]
The file with seguir didn't come

**Comment by marcoagpinto** [comment]
Yes, I forgot to add it, I edited the comment above with it.

**Comment by marcoagpinto** [comment]
Anyway, I was looking at the current antipatterns, and they need a rewrite too.

**Comment by ricardojosehlima** [comment]
Yes it must be only in the beginning of a sentence and in singular

**Comment by marcoagpinto** [comment]
ahhhhhhh...

I will do some rewriting of the antipatterns, some now and the others at 5am.

We will get there 😄

**Comment by marcoagpinto** [comment]
Better yet, I will do a quick antipattern fix.

**Comment by marcoagpinto** [comment]
ahhhh... bad idea, I really need to rewrite them all.

**Comment by ricardojosehlima** [comment]
Hi adding to the list doesn't solve the issue.

Just try as I said

Verbo seguir in the singular
Must be beginning of the sentence
Must be followed by an element in the plural

Just that, it's that simple

**Comment by marcoagpinto** [comment]
ahhhh

Right, let me create a rule for it.

What name description + suggestion should I add to the rule?

**Comment by ricardojosehlima** [comment]
Seguir_plural
Verifique se o sujeito do verbo seguir é o elemento que está no plural. Se for, coloque o verbo seguir no plural.

**Comment by marcoagpinto** [comment]
ahhhh... Thanks!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It only has 1 hit and it is a false positive:

```
    <rule id='SEGUIR_SINGULAR_PLURAL' name="Verbo 'seguir' singular + sujeito plural → Verbo plural">
      <!-- Created by Ricardo Joseh Lima and improved by Marco A.G.Pinto, Portuguese rule 2022-12-07 (25-JUL-2022+) -->
      <!--
      Segue as datas. → Seguem as datas.
      -->
      <pattern>
        <token postag='SENT_START' postag_regexp='no'/>
        <marker>
          <and>
            <token inflected='yes'>seguir</token>
            <token postag='VMIP3S0' postag_regexp='no'/>
          </and>
        </marker>
        <token postag='[DP][ADIPR]..P.+|SPS00:[DP][ADIPR]..P.+' postag_regexp='yes'/>
        <token postag='AQ..P.+|NC.P.+' postag_regexp='yes'/>
      </pattern>
      <message>Se não pretende realçar o tipo de imóvel, considere .</message>
      <suggestion><match no='2' postag='VMIP3S0' postag_replace='VMIP3P0'>seguir</match></suggestion>
      <example correction="Seguem"><marker>Segue</marker> as datas.</example>
    </rule>
```


```
Portuguese (Portugal): 1 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[0.txt](https://github.com/languagetool-org/languagetool/files/10171784/0.txt)

**Comment by marcoagpinto** [comment]
I am leaving to bed, I will return in a few hours.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
I have committed it:
https://github.com/languagetool-org/languagetool/commit/3f9b95af29e08431ba51ea0c003b72a95b2fcdaf

If any problems are found or if an enhancement is needed, it will be easy to make.

❤️ 🤗 😋

**Comment by ricardojosehlima** [comment]
Oh well, I expected so much more! But one question: is the rule being tested on pt-pt texts only?

**Comment by marcoagpinto** [comment]
The rule is in the main grammar.xml, it is for all PT variants and tested against 600 000 sentences from Tatoeba and the other file.

I, too, expected more results.

😢

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Let me try this:
```
Segue os sonhos perdidos.
Segue os vossos sonhos.
```
it doesn't detect the second sentences, it will need another line of code and min="0", "max=1"

Let me give it a try.

I will post again in a few minutes.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is incredible, not even detecting an extra token, it has hits.

But it works with:
```
Segue os sonhos perdidos.
Segue os vossos sonhos.
```

```
      <pattern>
        <token postag='SENT_START' postag_regexp='no'/>
        <marker>
          <and>
            <token inflected='yes'>seguir</token>
            <token postag='VMI.3S0' postag_regexp='yes'/>
          </and>
        </marker>
        <token min="1" max="2" postag='[DP][ADIPR]..P.+|SPS00:[DP][ADIPR]..P.+' postag_regexp='yes'/>
        <token postag='AQ..P.+|NC.P.+' postag_regexp='yes'/>
        <token><exception postag_regexp='yes' postag='SPS00|[DP][ADIPR]..S.+'/></token>
      </pattern>
```

https://github.com/languagetool-org/languagetool/commit/da02f097ba2e29eb1507199b90fcd6aab99b494e

```
Portuguese (Portugal): 0 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[2.txt](https://github.com/languagetool-org/languagetool/files/10175613/2.txt)

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Just an idea:
Should it only suggest “seguem” or “sigam” too?

I can make it broader if “sigam” is also a valid suggestion.

**Comment by marcoagpinto** [comment]
😢 😢 😢 😢 😢 

I didn't want to say this, but the two dreams sentences above look right for me.

Maybe we should add an “eles/elas/etc.” instead of start of sentence?

**Comment by marcoagpinto** [comment]
😢 😢 😢 😢 
I tried writing the sentences with "eles" and "os pássaros segue os seus sonhos" and it triggers other rule.

**Comment by ricardojosehlima** [comment]
On the sources, Tatoeba gives isolated sentences, so in real world, the rule may be worth.

**Comment by marcoagpinto** [comment]
ahhhhh... ok, and the "sigam"? Should it be suggested too? It would broaden the rule.

Thanks!

**Comment by marcoagpinto** [comment]
ahhhh... 😄 

❤️ ❤️ ❤️ ❤️ ❤️
