### ISSUE TITLE
[en] Wrong suggestion too/to

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7542]
Hello!

`I wish everyone a Merry Christmas and a Prosper New Year, and may you too accomplish long-time dreams.`

It suggests replacing “too” with “to”, which is wrong.

Thanks!

**Comment by tiff** [comment]
Fixed as part of https://github.com/languagetool-org/languagetool/commit/69dd606955602aee5ba6306f1d93d06143d12fa3
