### ISSUE TITLE
[DE] Fehlarlm mit "zu den Sturmgewehren"

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#7562]
Moin liebes LanguageTool-Team

Er sagte **zu** den Sturmgewehren beeindruckt:
LT: "Hier scheint ein Komma zu fehlen."
"zu" gehört zu "den Sturmgewehren", weswegen hier kein Komma hingehört.

Bitte beheben.

Grüße Dallun511

**Comment by tiff** [comment]
Das sollte nun behoben sein
