### ISSUE TITLE
[pt] Idea for rule “que é depois + V.Part.Passado” → “depois + V.Part.Passado”  - 2022-12-11

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7568]
Hello @ricardojosehlima

I still haven't coded the other rule.

I have been revising my thesis and I found a possible applicable rule.

Look at:
`(…) elas regressam ao formigueiro deixando um rasto de feromonas que é depois seguido pelas outras formigas.`

`“que é depois seguido”` → `“depois seguido”`

Basically, the rule would look for: que + é + depois + V. Part. Passado

Is it a good idea?

If so, are there any other words that can also be used along with “depois”?

Thanks!

**Comment by ricardojosehlima** [comment]
Hi, may be worth a try

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is coded:
https://github.com/languagetool-org/languagetool/commit/c26752c1c79ee2f1c6f9f4c0f528d4f752dd0638


```
    <!-- QUE É DEPOIS TRANSFORMADO depois transformado -->
    <rule id='QUE_É_ADVERBIO_VERPARTPASSADO' name="Simplificar: Que é + Adv + V.Part.Pass → Adv V.Part.Pass" type="style">
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2022-12-11 (25-JUL-2022+) -->
      <!--
      Elas regressam a casa deixando um rasto que é depois seguido por outras. → Elas regressam a casa deixando um rasto depois seguido por outras.
      -->
      <pattern>
        <token postag='NC.+|AQ.+' postag_regexp='yes'/>
        <marker>
          <token>que</token>
          <token regexp='yes'>é|são</token>
          <token postag='RG|RM' postag_regexp='yes'/>
          <token postag='VMP00.+' postag_regexp='yes'/>
        </marker>
      </pattern>
      <message>Esta perífrase poderá ser simplificada.</message>
      <suggestion>\4 \5</suggestion>
      <example correction="depois seguido">Elas regressam a casa deixando um rasto <marker>que é depois seguido</marker> por outras.</example>
    </rule>
```

A very simple rule with almost zero hits:

```
Portuguese (Portugal): 4 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```


[2.txt](https://github.com/languagetool-org/languagetool/files/10202294/2.txt)


A low-impact rule.

**Comment by ricardojosehlima** [comment]
Indeed! Seems good!

**Comment by marcoagpinto** [comment]
Thanks!

Ahhhh… I just woke up from my nap.

🤗 🤗 🤗 🤗 🤗 🤗
