### ISSUE TITLE
[LO-add-on] Huge RAM use and not returned to system

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7569]
Hello @FredKruse 

For at least two nightlies that I notice this:
I opened my 500+ page thesis on LibreOffice.

I looked at task manager, and it is consuming 13 GB (?!) of RAM (I have 32 GB).

Then, I close LibreOffice and task manager still has there 13 GB.

Only after I close the LibreOffice quickstarter in the tray icon area is when the RAM is returned to Windows:
![LO_RAM_issue_20221211](https://user-images.githubusercontent.com/5192600/206894262-1fe465f3-083d-4319-aea0-1e48443e7ee9.png)

When you have the time, could you take a look at it?

Thanks!

**Comment by marcoagpinto** [comment]
Look at the log:

```
LT office integration log from Sun Dec 11 06:54:59 GMT 2022

LanguageTool 6.0-SNAPSHOT (2022-12-10 17:39:43 +0000, 728361f)
OS: Windows 10 10.0 on amd64
LibreOffice 7.4.3.2 (The Document Foundation), en-GB
Java-Version: 1.8.0_351, max. Heap-Space: 7262 MB, LT Heap Space Limit: 6536 MB

getLTDictionaryFile: LT dictionary file doesn't exist: start to create
Time to generate LT spelling file: 36
setLtDictionary: Create LT spelling dictionary __LT_pt-PT_internal1.dic
Internal LT dicitionary for language pt-PT added: Number of words = 12923
Time to generate dictionary: 78
CacheIO: CacheCleanUp: Remove Path from CacheMap: /C:/Users/BLAH BLAH
CacheIO: CacheCleanUp: Remove Path from CacheMap: /C:/Users/BLAH BLAH 
CacheIO: CacheCleanUp: Delete cache file: C:\Users\BLAH BLAH\AppData\Roaming\languagetool.org\LanguageTool\LibreOffice\cache\LtCache2.lcz
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 1
SingleDocument: getCheckResults: SortedTextId and DocumentElementsCount are not supported by LO!
MultiDocumentsHandler: runShapeCheck: start
Time to generate cache(4): 14566
Caches saved to: C:\Users\BLAH BLAH\AppData\Roaming\languagetool.org\LanguageTool\LibreOffice\cache\LtCache1.lcz
Caches saved to: C:\Users\BLAH BLAH\AppData\Roaming\languagetool.org\LanguageTool\LibreOffice\cache\LtCache2.lcz
Time to generate cache(6): 11313
TextLevelCheckQueue: run: Interrupt ended
Time to generate cache(6): 15506
Caches saved to: C:\Users\BLAH BLAH\AppData\Roaming\languagetool.org\LanguageTool\LibreOffice\cache\LtCache2.lcz
```

**Comment by danielmarbach** [comment]
I am uncertain if it is related to this issue. I tried to run the LibreOffice Add-on on Linux with the latest version of the extension, but the tool is not even reacting. When I click the LanguageTool menu, nothing happens and no checking is done.

**Comment by FredKruse** [comment]
> I am uncertain if it is related to this issue. I tried to run the LibreOffice Add-on on Linux with the latest version of the extension, but the tool is not even reacting. When I click the LanguageTool menu, nothing happens and no checking is done.

No, this is not related. I got a similar problem as I created the OXT by myself with maven. Something went wrong and the OXT was not registered by LibreOffice. Please use 'clean', if you create it from the newest sources. Please download the newest OXT, otherwise. If it doesn't work, we have to contact @danielnaber.

**Comment by FredKruse** [comment]
@marcoagpinto I can't reproduce the behavior. Usually, I am working with a virtual machine running with less RAM. This works fine. The code is written in Java. Java does it own memory management. Maybe the newest version of Java or LibreOffice changes the default values for maximal heap space. I don't know.
Anyway, I did some research and did some optimization of the code regarding the freeing of memory.
Please test the new version.

**Comment by marcoagpinto** [comment]
@FredKruse 

Thank you so much, it has fixed the issue!

I scrolled through the 500+ pages of the thesis from start to end, and it only used 7 GB of RAM.

Thanks!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️
