### ISSUE TITLE
Extend JSON API to accept markup instead of plain text only

### ISSUE THREAD

**Issue by JBR69** [languagetool-org/languagetool#757]
Hi,

I use languageTool to check documents in asciidoc.
I would like to exclude from verification regular expressions; is it possible ? How?

For example, in my text I can have
`
Lorem ipsum dolor sit amet, a and sit, [red]#elementum# semper erat nibh magna donec adipiscing, masso como leo dui massa
`
And I don't want to control the content between `[` and `]` (red)

Jérôme

**Comment by danielnaber** [comment]
Do you use the LT Java API? Then you can use https://languagetool.org/development/api/org/languagetool/markup/AnnotatedTextBuilder.html to define markup and text.

**Comment by JBR69** [comment]
No I use LT with HTTP Server

**Comment by danielnaber** [comment]
This is not supported yet, sorry. Pull requests welcome, the place where this would need to be added is https://github.com/languagetool-org/languagetool/blob/master/languagetool-server/src/main/java/org/languagetool/server/ApiV2.java#L60

**Comment by johanneswilm** [comment]
How would you want for the api to receive the data? Instead of

    text: "text to be checked"

would you allow to alternatively receive a JSON structure like this?

    annotatedText: [
        {type: 'text', text: 'text to be '},
        {type: 'markup', text: '<b>'},
        {type: 'text', text: 'checked'},
        {type: 'markup', text: '</b>'}   
    ]

Or what other format would be in line with languagetool's philosophy?

**Comment by danielnaber** [comment]
I guess the alternative would be this?

```
annotatedText: [
   {text: 'text'},
   {markup: '<b>'}
]
```
It's a bit more compact, but I'm not sure. What do you think? Are there other approaches?

**Comment by johanneswilm** [comment]
I don't know about other approaches. I like your markup better than mine though.

**Comment by danielnaber** [comment]
This has now been implemented. Will probably be online at languagetool.org later today. Documented at https://languagetool.org/http-api/swagger-ui/#!/default/post_check
