### ISSUE TITLE
`cURL` is correctly capitalized

### ISSUE THREAD

**Issue by GideonBear** [languagetool-org/languagetool#7579]
LanguageTool suggests changing cURL to curl, but cURL is the correct name (source: [curl.se](https://curl.se/docs/faq.html#What_is_cURL)).
Maybe it should be added to [spelling_global.txt](https://github.com/languagetool-org/languagetool/blob/master/languagetool-core/src/main/resources/org/languagetool/resource/spelling_global.txt)?

**Comment by tiff** [comment]
Fixed
