### ISSUE TITLE
[en] Singular/plural false positive in verb (SINGULAR_VERB_AFTER_THESE_OR_THOSE[3])

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7591]
Hello!

Take a look at:
“But the last time he updated these three was in 2020, for what I remember.”

LanguageTool says that “was” is incorrect in this case, but it looks good to me.

Also, “for what I remember”, it suggests “to”, but “for” sounds better to me.

Could you take a look?

Thanks!

**Comment by tiff** [comment]
Thanks, fixed.
