### ISSUE TITLE
[pt] Idea for rule: sentences of the type: “que o nosso algoritmo suporta” → “suportados pelo nosso algoritmo” - 2022-12-17

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7592]
@ricardojosehlima

I promise this is the last rule I create before the official 6.0 (I will dedicate the week to fix false positives in the other rules).

Look at this sentence:
“Alguns cenários que o nosso algoritmo suporta:”

It would change:
“QUE O NOSSO ALGORITMO SUPPORTA”
to
“SUPORTADOS PELO NOSSO ALGORITMO”

Basically:
NC.+ + “que” + DA.+ + DP.+ + NC.+ + V.+

And it would change the verb to part. participle with the number+gender agreement based on the NC.+ before the “que”.

Well, my explication is a mess, but this is the core idea.

The rule would only be triggered if there is a noun (NC.+) before the “que”.

This rule would make the text more fluid and therefore easier to read (one less word).

Thanks!

**Comment by marcoagpinto** [comment]
Ricardo, what is your advice in the suggestion message?:
`“Torne o texto mais fluido e fácil de ler.”`
?

**Comment by ricardojosehlima** [comment]
Hi the suggestion should be only fluido, the word fácil could be eliminated, looks redundant.
As for the rule look at

As coisas que ele disse que vai fazer
As coisas ditas por ele vai fazer

As pessoas que eles foram visitar
As pessoas idas por eles visitar

The rule doesn't work for sentences like these. And may be more. You can try the rule but my guess is that too many of these are going to appear.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

In 10 minutes, I will start working on the rule… I napped in the afternoon and am not asleep.

I forgot to mention that the rule was only for verb forms “suporta” and “suportam” (VMIP3S0 and VMIP3P0) which will limit the false positives.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

After some “cleaning” the rule became this:

```
    <!-- QUE O NOSSO ALGORITMO SUPPORTA suportado pelo nosso algoritmo -->
    <rule id='QUE_ARTDEF_PRONPOSS_NOMECOMUM_VERBO' name="Simplificar: Que + Art.Def.+ Pron.Poss. + NomeC. + Verbo → Verbo.Part.Pass. + pel[ao](s) + Pron.Poss. + NomeC." type="style">
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2022-12-18 (25-JUL-2022+) -->
      <!--
      Alguns cenários que o nosso algoritmo suporta. → Alguns cenários suportados pelo nosso algoritmo.
      -->
      <pattern>
        <token postag='NC.+' postag_regexp='yes'>
          <exception postag='V.+' postag_regexp='yes'/>
        </token>
        <marker>
          <token>que</token>
          <token postag='DA.+' postag_regexp='yes'/>
          <token postag='DP...P' postag_regexp='yes'/>
          <token postag='NC.+|AQ.+' postag_regexp='yes'/>
          <token postag='VMIP3.+' postag_regexp='yes'>
            <exception regexp='yes' inflected='yes'>estar|ser</exception>
          </token>
        </marker>
      </pattern>
      <filter class="org.languagetool.rules.pt.AdvancedSynthesizerFilter" args="lemmaFrom:6 lemmaSelect:V.* postagFrom:1 postagSelect:NC(.)(.)000 postagReplace:VMP00\b2\b1" />
      <message>Poderá tornar o texto mais fluido.</message>
      <suggestion>{suggestion} <match no='3' postag='DA0(..)0' postag_replace='SPS00:DA0$10'>por:o</match> \4 \5</suggestion>
      <example correction="suportados pelo nosso algoritmo">Alguns cenários <marker>que o nosso algoritmo suporta</marker>.</example>
    </rule>
```
```
Portuguese (Portugal): 2 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[4.txt](https://github.com/languagetool-org/languagetool/files/10253102/4.txt)

Does it look good?

Thanks!

**Comment by ricardojosehlima** [comment]
The second sentence with tida looks weird, at least for pt-br

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It looks good in pt-PT:
`“A nossa expectativa de inscrição foi superada, o que prova a necessidade que a nossa população tem com relação ao aprendizado das artes”, comentou o Coordenador.`

“tida” sounds well in pt-PT:
```
“A nossa polícia é tida como sendo a melhor do mundo.”
“Estas são as resoluções tidas pelos nossos governos.”
```

Maybe it is a minor thing?

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

If you think it is better, I can add an exception if after the verb if it has an SPS00 (“com”, etc.)

You are the expert in Linguistics 😄 ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
Ohhhh… “para” is CC and SPS00.

I would have to create a list of valid POSes after the verb.

Or maybe I could hardcode “com” in an exception along with other SPS00s that produce results that sound strange in pt-BR.

I just don't know what to hardcode in the exception, do you have some ideas?

Thanks!

**Comment by marcoagpinto** [comment]
Ahhhhh… or maybe create an exception for the verb “ter” but it will be limited, very limited, and it is hard to find other verbs to analyse since it only had 2 hits.

**Comment by ricardojosehlima** [comment]
For pt-br it's better to leave the verb ter out

**Comment by marcoagpinto** [comment]
It is done!

This is the original commit 7 hours ago:
https://github.com/languagetool-org/languagetool/commit/b9930d2f44ab3a32bf4202b081a2f32b29426ffb

This is the “ter” fix:
https://github.com/languagetool-org/languagetool/commit/2231cb2e3f8b08e6734da9b36b15f224197ff3ca

Thank you for your help.

Now I guess I will spend the week before the official release fixing false positives all around.
