### ISSUE TITLE
[DE] newline not being recognised as separation character

### ISSUE THREAD

**Issue by J-Lakeman** [languagetool-org/languagetool#7594]
![Bildschirmfoto 2022-12-19 um 00 01 05](https://user-images.githubusercontent.com/101660243/208329702-fccb0f39-49d9-4c73-a98d-f05036408d18.png)

There's nothing wrong here, so the newline should be equal to a space.

**Comment by danielnaber** [comment]
Thanks for the report. Where did you take that screenshot? In the browser add-on? If so, which website was this?

**Comment by J-Lakeman** [comment]
No worries!
In the macOS mail client using the macOS desktop application

**Comment by schurigeln** [comment]
@J-Lakeman Just now we've released version 1.1 of LanguageTool for Desktop. As far as I'm concerned, the issue should now be resolved. Could you please update and verify whether it is working now? Thanks a lot!

**Comment by J-Lakeman** [comment]
Yep, seems resolved now. Cheers!
