### ISSUE TITLE
[LibreOffice add-on] Memory still not freed after closing document

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7597]
Hello @FredKruse 

The memory eating bug while verifying the grammar is fixed.

However, if you close the document, the memory used is not returned to the system.

The only way of this happening is closing the “Quickstarter” icon in the tray icon area of Windows 10.

**Comment by FredKruse** [comment]
I think it happens because LO keeps the java virtual machine running. The memory will be released if it is needed.

**Comment by FredKruse** [comment]
Hello @marcoagpinto,
the problem should be solved in the current snapshot. Could you please test it? If the problem persists, it must be a LO problem. All LT threads will be closed at the end.

**Comment by FredKruse** [comment]
I will close this issue as solved. Open a new issue with current versions if necessary.
