### ISSUE TITLE
Duplicate metric equivalent suggested

### ISSUE THREAD

**Issue by tami-x** [languagetool-org/languagetool#7612]
When I typed `18 °C (64.4 °F)`, LanguageTool suggested I add a metric equivalent.
![metric-equivalent](https://user-images.githubusercontent.com/121226648/209113027-f8a67d62-7705-45c0-9f5e-f677108d9154.png)

**Comment by danielnaber** [comment]
Thanks for the report, this should be fixed tomorrow.
