### ISSUE TITLE
Bug in multi part compounds

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#7619]
This was reported: 
...jk aan voor de |middelbare school tijd|ens de aanmeldw...
it is cause by multipartcompounds.txt having the line:
middelbare school tijd|tijd die men op de middelbare school doorbrengt

The line is correct, the error is not. It should not trigger unless on full tokens.

**Comment by danielnaber** [comment]
Should be fixed (online tomorrow)

**Comment by danielnaber** [comment]
It's fixed, but what about cases like "elektrische fiets gebruikers", which then won't match now only because of the "s" in "gebruikers"? Should it still match, maybe?

**Comment by baarsrj** [comment]
Maybe it should. There are all kinds of plurals and diminutives that would be correctly detected, but also falses. 
I can't guess what would be best. Intermediate solution is to keep of flexible, like having regexp on the last token. But even then, the description might be wrong.

**Comment by danielnaber** [comment]
Unfortunately, the implementation we use doesn't allow using regex here. So, I suggest keeping my fix. Should plurals etc. match, they will have to be listed as their own line then.
