### ISSUE TITLE
[nl] = not allowed in content

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#7621]
I was trying to add links to the official spelling site as text in a simple replace. But an = in the text (after the tab) is not accepted.

**Comment by danielnaber** [comment]
Add links there wouldn't work anyway, as they would not be interpreted as links. We could have a fourth column with a link, if you think that's useful.

**Comment by baarsrj** [comment]
For spelling issues where we can refer to woordenlijst.org, it would be a good addition. But the format would become a bit more complex, having 1 or 2 invisible tabs.
For now, I will simply remove the link.

**Comment by baarsrj** [comment]
Can't we interpret any absolute link as a link, and make it usable? Like anything starting with http: or https: ?

**Comment by danielnaber** [comment]
> Can't we interpret any absolute link as a link, and make it usable? Like anything starting with http: or https: ?

Yes, let's try that. I have made a commit for that (but `=` in the link still won't work)

**Comment by baarsrj** [comment]
For the dictionary items it is essential the = is allowed. Maybe the = as replace separator can be set.

**Comment by danielnaber** [comment]
`=` in links should work now.

**Comment by baarsrj** [comment]
Super. I will wait until the release has been announced and priority has changed. One step at a time.
