### ISSUE TITLE
macOS LanguageTool 1.1 not working without user logged in

### ISSUE THREAD

**Issue by J-Lakeman** [languagetool-org/languagetool#7626]
Happened on an up-to-date MacBook Pro running macOS Big Sur.
Below screenshot should be explanatory:

![Bildschirmfoto 2022-12-28 um 11 09 39](https://user-images.githubusercontent.com/101660243/209840540-3b484ee9-a59f-487b-93d2-d268d7b24b6d.png)

**Comment by J-Lakeman** [comment]
Seems resolved after a reboot

**Comment by schurigeln** [comment]
@J-Lakeman Thanks for reporting the bug. We'll take care of it. Could you please tell me if you also have the LanguageTool Safari Add-on/Editor App from the AppStore installed?

**Comment by schurigeln** [comment]
@J-Lakeman The problem should now be solved for good. Thanks again for reaching out.

**Comment by J-Lakeman** [comment]
Yep, cheers!
