### ISSUE TITLE
macOS desktop application should allow self-hosted LanguageTool server as destination

### ISSUE THREAD

**Issue by j-lakeman** [languagetool-org/languagetool#7628]
I really appreciate the possibility to self-host a LanguageTool server.
Unfortunately the macOS desktop application, contrary to the Firefox or Thunderbird extensions, doesn't offer an option to change the default LanguageTool server being used.
That would be very helpful though.

**Comment by Belphemur** [comment]
Any plan for this issue ?

**Comment by fr0st-beard** [comment]
I also would find this useful. I would, personally, pay for the ability to connect to a self-hosted server on macOS and iOS.

Regardless, phenomenal software, and thank you so much for making it open source.

**Comment by kris-anderson** [comment]
I would also love this feature, and would happily pay a subscription for this capability.

Sending all the text I type to a third party is a non-starter for me. But let me self host and point the macOS and hopefully iOS app at my self hosted instance... take my money!

**Comment by jhult** [comment]
Related to #[10533](https://github.com/languagetool-org/languagetool/issues/10533)

**Comment by j-lakeman** [comment]
Seems to be implemented now.
