### ISSUE TITLE
Chrome extension: Conflict with WordPress Plugin TablePress

### ISSUE THREAD

**Issue by fweigelt** [languagetool-org/languagetool#7632]
TablePress is a Plugin for WordPress to create and manage tables.
If the Chrome Extension "Grammatik- und Rechtschreibprüfung – LanguageTool" is active and you try to input Text into a table, it will always change the text to "undefined". 

This Problem occurs with the latest Versions of both programs (LanguageTool Extension: 1.6.4, TablePress: 2.0.1).

You can recreate the Bug in the Demo-Environment of TablePress: https://tablepress.org/demo/#try
Here is a Discussion of the Problem in the TablePress Forum: https://wordpress.org/support/topic/editing-content-renders-content-indefined/

**Comment by tiff** [comment]
A fix for this will be part of the next update (released in 2-4 weeks)

**Comment by tiff** [comment]
Version v6.1.6 (now in the Store, being rolled out to 100% over the next days) includes a fix.

**Comment by fweigelt** [comment]
I have forced the update and test it. Problem is solved. I will inform our writing staff and see if it works for them too.

Thank you very much!
