### ISSUE TITLE
[pt] Idea for rule: duplicate personal pronoun removal - 2022-12-29

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7634]
Hello @ricardojosehlima

Dear brother Ricardo!

Finally, V6.0 has been released, so we can get back to coding rules.

First, I would like to add to wordiness.txt:
```
para a próxima semana=para a semana
para o próximo mês=para o mês
para o próximo ano=para o ano
para a semana que vem=para a semana
para o mês que vem=para o mês
para o ano que vem=para o ano
```
Is there something I forgot above?

Now, I have written down tons of rules to create during my silent time.

The first one, look at this:
```
[19:40:26] <+Master_of_Chaos> pergunta a ela o que ela achou do texto
> remover o 2º "ela"
```

So, if the 2nd ELA matches the 1st, it removes the second.

Basically, for personal pronouns? Eu, tu, ele, ela, eles, elas, nós, vós, vocês?

Can it be expanded to fit more cases?

Is it a good idea?

Thanks!

❤️ ❤️ ❤️ ❤️ ❤️

**Comment by ricardojosehlima** [comment]
Hi!
The rule on "para a semana que vem - para a semana" I'm not sure if works for pt-br, I would have to see sentences.
The second idea looks promising!

**Comment by marcoagpinto** [comment]
Ahhhhh… we have a plan 😄 😄 😄 😄 😄

**Comment by marcoagpinto** [comment]
Ahhhh… to play safe, I only added to wordiness.txt:
```
para a próxima semana=para a semana
para o próximo mês=para o mês
para o próximo ano=para o ano
```
https://github.com/languagetool-org/languagetool/commit/5e009e65ad71e448f20a5d5d9d1aacf780acebef

Tonight or at 5am I will code the rule.

So much to do 😄 ❤️

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is coded:
https://github.com/languagetool-org/languagetool/commit/6ae81cc7b25bf5f3ff708abfaa31cc9262e06395

1 hit in 600 000 sentences, and an effortless to code rule:

```
Portuguese (Portugal): 1 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[0.txt](https://github.com/languagetool-org/languagetool/files/10322279/0.txt)

```
    <!-- ELA O QUE ELA ACHOU ela o que achou -->
    <rule id='PRONOME_PESS_O_QUE_MESMO_PRONOME_PESS' name="Simplificar: Pronome P. + o + que + Pronome P. → Omitir segundo Pronome P." type="style">
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2022-12-29 (25-JUL-2022+) -->
      <!--
      Pergunta a ela o que ela achou do texto. → Pergunta a ela o que achou do texto.
      -->
      <pattern>
        <token/>
        <marker>
          <token regexp='yes'>&pronomes_retos;</token>
          <token>o</token>
          <token>que</token>
          <token><match no="1"/></token>
        </marker>
        <token postag='V.+' postag_regexp='yes'/>
      </pattern>
      <message>Nesta perífrase poderá omitir o segundo pronome pessoal.</message>
      <suggestion>\2 o que</suggestion>
      <example correction="ela o que">Pergunta a <marker>ela o que ela</marker> achou do texto.</example>
    </rule>
```
