### ISSUE TITLE
[pt] Bug in comma

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7638]
Hello @susanaboatto 

It is you who knows well how the comma rules work and how they can be changed.

This sentence generates a false positive:
"Seja qual for o motivo pelo qual é celebrado, o Natal significa família, amor, gratidão, renascimento."

![comma_bug_lt_20221230](https://user-images.githubusercontent.com/5192600/210070683-15de557c-0927-4055-84f3-f6f9bfb45310.png)

Could you have a look at it when you have the chance?

Thanks!

**Comment by susanaboatto** [comment]
This was triggered by `ALTERNATIVE_CONJUNCTIONS_COMMA`, and a disambiguation rule was assigning the wrong tag to the word “pelo”. I have fixed this now, so let's see what we get tomorrow.

**Comment by marcoagpinto** [comment]
Thank you, dear Susana!

❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
It is fixed in the nightly released this end of afternoon for LibreOffice.

Thanks!
