### ISSUE TITLE
A caution while substituting “chamadas de” for “chamadas” in PT-BR

### ISSUE THREAD

**Issue by renanwp2** [languagetool-org/languagetool#7640]
In mathematical applications, it is pretty common to say something like:

> Em alguns casos, as sequências com termos positivos são chamadas de sequências positivas.

I see no problem with such a use of “chamadas de”. Besides that, there exist common applications where the term “chamadas de” is used, like: 

> Atualmente, são chamados de “gigantes” os indivíduos que apresentam o dobro do tamanho da média para aquele gênero. 

and

>  Depois da pandemia de COVID-19, as chamadas de video se tornaram fundamentais no espaço de trabalho.

It happens that the LanguageTool keeps warning me to substitute  “chamadas de”  for “chamadas” in all these sentences. Can somebody correct it?

**Comment by susanaboatto** [comment]
Hi @renanwp2,

This error is only triggered if you are using the PT-PT corrector. I suggest checking if PT-BR is active. 

<img width="832" alt="image" src="https://user-images.githubusercontent.com/108675843/210217091-1343fb65-4cb7-4608-8b4f-6acde2921bc9.png">
<img width="844" alt="image" src="https://user-images.githubusercontent.com/108675843/210217207-f5413034-5608-44f6-8fa2-fab1efa316bd.png">


@marcoagpinto, are all these examples correct in PT-PT or should we adapt this rule for this variant?

**Comment by marcoagpinto** [comment]
I have been translating for DALnet, I spent a couple of hours or so translating a document.

Of course, we could add some exceptions, for example: phone calls “Fiz uma chamada ao Pedro”, but not really sure currently any good example sentences for it.

**Comment by marcoagpinto** [comment]
ahhhh...
"Fiz uma chamada de atenção ao Pedro".

Here is a false positive.

**Comment by marcoagpinto** [comment]
ahhh...
"chamadas de vídeo", "chamadas de telefone" could be added to an antipattern.

@susanaboatto I will work on it tonight.

Allow me some time to analyse the results against 600 000 sentences tonight.

**Comment by renanwp2** [comment]
Ok, how do I run my server in pt-BR? I'm using the following command in the Linux terminal:

> java -cp /opt/languagetool/LanguageTool-5.8/languagetool-server.jar org.languagetool.server.HTTPServer --port 8081 --allow-origin "*"

Following this idea, how can I set the language to pt-BR? I may be losing some essential corrections in my PhD thesis.

**Comment by marcoagpinto** [comment]
Here it is the fix:
https://github.com/languagetool-org/languagetool/commit/ff6ed87a1aa8efeaa50760ccf42dd86122d373a5

Please tell me if you find any false positives in the resulting wordlist:
[13.txt](https://github.com/languagetool-org/languagetool/files/10333305/13.txt)

Notice that in the example given above "video" has a missing accent.

**Comment by renanwp2** [comment]
Ok, how do I run my server in pt-BR? I'm using the following command in the Linux terminal:

> java -cp /opt/languagetool/LanguageTool-5.8/languagetool-server.jar org.languagetool.server.HTTPServer --port 8081 --allow-origin "*"

Following this idea, how can I set the language to pt-BR? I may be losing some essential corrections in my PhD thesis.

**Comment by marcoagpinto** [comment]
@renanwp2 

I don't know how to run a server.

I only tried it once or twice, and it was ages ago.

**Comment by marcoagpinto** [comment]
https://proofingtoolgui.org/getting_involved.html

Better to use the nightly on LibreOffice, see the bottom of the page.

The page also explains the philosophy of open-source.

**Comment by renanwp2** [comment]
> https://proofingtoolgui.org/getting_involved.html
> 
> Better to use the nightly on LibreOffice, see the bottom of the page.
> 
> The page also explains the philosophy of open-source.

I use the server because I want LanguageTool to work with TeXstudio. My thesis is being written in LaTeX. Everything is open source, even the dictionaries I use.
