### ISSUE TITLE
[pt] Antipattern for 5+ periods

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7642]
@susanaboatto 

Hello Susana,

Sorry to bother you again, but it is you who knows about commas and periods.

Could you create an antipattern that would ignore 5 or more periods together in a line, as it could be a hand made index?

Thanks!

![periods_lt_20230101](https://user-images.githubusercontent.com/5192600/210167500-f640c721-41cb-4cf2-bb6b-9adb65b68793.png)

**Comment by marcoagpinto** [comment]
@jaumeortola @tiff @danielnaber 

Maybe the same for other languages as well?

**Comment by marcoagpinto** [comment]
The screenshot above is from LibreOffice.

**Comment by susanaboatto** [comment]
Hi @marcoagpinto, this error is not triggered for me 🤔

**Comment by marcoagpinto** [comment]
Sample doc here.

[Sample doc 20230102.odt](https://github.com/languagetool-org/languagetool/files/10331451/Sample.doc.20230102.odt)

**Comment by marcoagpinto** [comment]
Screenshot:

![Sample doc 20230102](https://user-images.githubusercontent.com/5192600/210229616-343184ab-3b95-483d-b280-22a820f8dcca.png)

**Comment by FredKruse** [comment]
@marcoagpinto I copied the text from the ODT and pasted it into languagetool.org. The same errors are displayed in the remote window. This is not a special problem with the LO extension.
@danielnaber There is another problem: The marks are displayed on wrong places (e.g. 30 dias). This also happens in the window at languagetool.org.
If you switch to German, there are some unnecessary marks, too.

**Comment by maphjo** [comment]
Hi @marcoagpinto 
after checking your files, I found out that the suggested corrections were triggered when there were . between the … 
LO is changing three consecutive periods . to suspension points … 
But if you end a line with two periods .. this will not happen; and with copy and paste you might end up with one or two periods in between …
I have added some antipatterns which should do the trick. Merge will probably happen after the weekend.

In case you do not know: you can add filler dots to your tab spaces in LO automatically.

**Comment by marcoagpinto** [comment]
Thanks!
