### ISSUE TITLE
[pt] Rule idea: “de agora” → “atual/atuais” - 2023-01-01

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7643]
@ricardojosehlima

Hello! Good Year!

Here is an idea for a rule:
```
Qual o preço de agora?
Aconteceu nos tempos de agora.
```

Replace “de agora” with “atual” and in the second sentence “atuais”, based on the noun number concordance.

It would check for:

NC + de + agora

Is it a good idea?

Thanks!

**Comment by ricardojosehlima** [comment]
Hi sure is.

**Comment by marcoagpinto** [comment]
Ricardo, thank you!

Tonight I will work on this and on antipatterns for the “chamada de” rule.

❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
Hello @ricardojosehlima 

It is coded:
https://github.com/languagetool-org/languagetool/commit/8c5206087f3184c2bcbd54ce7c4f8a1cc95501a2

First test:
```
Portuguese (Portugal): 11 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```
[0.txt](https://github.com/languagetool-org/languagetool/files/10335110/0.txt)


After applying antipatterns:
```
Portuguese (Portugal): 4 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```
[2.txt](https://github.com/languagetool-org/languagetool/files/10335117/2.txt)

It has a false positive, but the sentence is badly structured, so it is not the rule's fault:
`5 O requisito de Agora Forex Belford Roxo 1 significa que você só precisa realmente depositar 1 100th do que você está inv...`

**Comment by ricardojosehlima** [comment]
Fine!

**Comment by marcoagpinto** [comment]
Thanks!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️
