### ISSUE TITLE
[nl] rule priorities

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#7644]
The rule STAM_ZONDER_IK might need a little bit lower priority, since there are many other, more frequent mistakes, that cause this rule to trigger as well.
Same for KOMMA_ONTBR 

Could a member of the team please take care of this?
Or, alternative... could the priority be changed in XML? Say, in offset from average (-1, +3 etc)

**Comment by danielnaber** [comment]
Done, these rules now have a priority of `-1`.
