### ISSUE TITLE
[pt] Idea for rule: "acabar/terminar" → "concluir"

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7655]
@ricardojosehlima

Hello Ricardo,

The idea is to replace the verb “acabar”/“terminar” with the verb "concluir”, regarding courses:
`acabar/terminar o [meu/teu/seu/etc.] phd, curso, mestrado,doutoramento, doutorado, pós-graduação, licenciatura`

Is it a good idea?

Thanks!

**Comment by ricardojosehlima** [comment]
Sure!

**Comment by marcoagpinto** [comment]
cool!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is coded:
https://github.com/languagetool-org/languagetool/commit/a5f0ce5942c6d7facdc5db269499002b79a01726

```
Portuguese (Portugal): 10 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```
[0.txt](https://github.com/languagetool-org/languagetool/files/10337731/0.txt)


Thanks!

❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
yes, I missed them too 😛 

Let me add them.

**Comment by marcoagpinto** [comment]
I am generating a new wordlist. I have also added: `SPS00:DA.+|SPS00:DI.+` to see if we can match more cases, not sure about the results, it will take a minute or two to have it ready.

**Comment by marcoagpinto** [comment]
ohhhhhhh... I forgot "universidade" too... let me abort the wordlist generation and add it.

**Comment by marcoagpinto** [comment]
Ahhhhh… regenerating the wordlist… more like 5 minutes instead of 1 or 2 😋

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It produced the same hits as 0.txt:
[1.txt](https://github.com/languagetool-org/languagetool/files/10338072/1.txt)


I miss my old Wikipedia sentences file where we could check rules against tons of regular people sentences, but the Wikipedia tool stopped accepting it, giving an error.

```
    <rule id='CONCLUIR_UM_CURSO' name="Acabar/terminar um curso → Concluir">
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2023-01-03 (25-JUL-2022+) -->
      <!--
      Vou acabar o meu doutoramento. → Vou concluir o meu doutoramento.
      Ele terminou um mestrado em gestão. → Ele concluiu um mestrado em gestão.
      -->
      <pattern>
        <marker>
          <token regexp="yes" inflected='yes'>acabar|terminar</token>
        </marker>
        <token postag='DA.+|DI.+|SPS00:DA.+|SPS00:DI.+' postag_regexp='yes'/>
        <token min="0" max="1" postag='DP.+' postag_regexp='yes'/>
        <token regexp="yes">bacharelados?|bacharelatos?|cursos?|doutorados?|doutoramentos?|especialização|especializações|faculdades?|graduação|graduações|licenciaturas?|mestrados?|PhDs?|pós-graduação|pós-graduações|universidades?</token>
      </pattern>
      <message>Relativamente a cursos, é mais correto empregar o verbo 'concluir'.</message>
      <suggestion><match no='1' postag='V.+' postag_regexp='yes'>concluir</match></suggestion>
      <example correction="concluir">Vou <marker>acabar</marker> o meu doutoramento.</example>
      <example correction="concluiu">Ele <marker>terminou</marker> um mestrado em gestão.</example>
    </rule>
```

**Comment by susanaboatto** [comment]
Hi all,

I don't think this rule is very relevant for PT-BR. "Acabar/terminar" are frequently used and accepted, so I gather that Brazilians will disable this a lot. Maybe we should move it to PT-PT grammar?

**Comment by marcoagpinto** [comment]
@susanaboatto 

Yes, please move it to pt-PT if it is not relevant in BR.

Thanks!
