### ISSUE TITLE
CXXABI_1.3.9 dependency

### ISSUE THREAD

**Issue by lsmith77** [languagetool-org/languagetool#7657]
It appears that 6.0 requires `CXXABI_1.3.9` part of the `lib64stdc++` package, which is not yet supported in Debian stable, leading to the following error:

```
Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/jna5523480956296748116.tmp)
```

Would it be possible to revert (Hunspell?) to be able to work with `CXXABI_1.3.8` with LT 6.0?

**Comment by lsmith77** [comment]
created https://gitlab.com/dumonts/hunspell-java/-/issues/8

**Comment by cwd24** [comment]
> which is not yet supported in Debian stable

Are you sure? The package for Debian stable (bullseye) supports up to CXXABI_1.3.12:
$strings libstdc++.so.6 | grep CXXABI_1
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_1.3.9
CXXABI_1.3.10
CXXABI_1.3.11
CXXABI_1.3.12

**Comment by lsmith77** [comment]
indeed .. sorry for the noise. my server is on an older image than I realixed.
