### ISSUE TITLE
[pt] Incomplete suggestion

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#7658]
Hi,
   When I wrote "com direito a", LT underlined it and then what appears (see image attached) is an incomplete suggestion. 
![Captura de tela de 2023-01-03 12-21-42](https://user-images.githubusercontent.com/36453534/210387028-32db58e9-8598-430d-a0c3-ede11c00f6ad.png)

**Comment by marcoagpinto** [comment]
Fixed: https://github.com/languagetool-org/languagetool/commit/f139f82a483effc242d1cd25ff15ed1a47e62df9

**Comment by ricardojosehlima** [comment]
Hi, I've seen that you deleted the expression "com direito a", and just below it, there are two more with REFORMULAR as suggestion, should be deleted as well?

**Comment by marcoagpinto** [comment]
Ahhhhh…. the ones that say “REFORMULAR” means that the developer couldn't find a word to replace them; thus no suggestion is shown, the user must find it.

**Comment by ricardojosehlima** [comment]
But as is now "É preferível dizer REFORMULAR" it's confusing. If the user clicks on the button, the expression is replace by REFORMULAR. I'd suggest to remove the expressions as clichés.
