### ISSUE TITLE
Document chache failed and high CPU usage

### ISSUE THREAD

**Issue by marcelolaia** [languagetool-org/languagetool#7659]
After upgrade to 5.9, LibreOffice show a popup message with:

```
An error has occurred in LanguageTool 5.9 (2022-09-28 14:38:38 +0000):
Document chache failed:
Paragraphs:
Endnotes: 0/0
Footnotes: 0/0
Headers/Footers: 12/12
Shapes: 0/0
Tables: 1695/1695
Text: 594/596
Unknown: 16/14
```

This is popup very frequently. Annoying.

Plus, LO raise 130-200% of CPU usage. It is draining my CPU and memory until crash. It's needed to force close LO.

LO usage is only possible after deactivate LanguageTool extension.

**Comment by danielnaber** [comment]
Please re-open if this still happens with LT 6.0.
