### ISSUE TITLE
[pt] Add verb "viralizar"

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#7683]
LT doesn't recognize the verb "viralizar" and its inflections. Don't know if it's common in pt-pt, but in pt-br it is.

**Comment by marcoagpinto** [comment]
Sure, @susanaboatto could you implement it if you have the chance/time?

Thanks!

**Comment by ricardojosehlima** [comment]
Hi, I use it online. It appears that viralizando is not accepted, however viralizar and viralizou are. You can test it on the LT online editor for pt-br.![20230110_105616.jpg](https://user-images.githubusercontent.com/36453534/211570618-1b7c33fb-cd8a-4c4e-a29c-89c0b80e5609.jpg)

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Is it this?:
https://github.com/languagetool-org/languagetool/commit/47e5dfdbf048517c22a8d6aac0aad1dacbfbb9cb

https://github.com/languagetool-org/languagetool/commit/2ae1465edfd1a3dca6d9558c848579c890c712d5
