### ISSUE TITLE
[Global] Tool ribbon on Atlassian Jira is doubled or tripled when using LT extension.

### ISSUE THREAD

**Issue by Malinq94** [languagetool-org/languagetool#7723]
Hey, 

I'm active Jira user, and it seems that since last update there is a problem with Atlassian Jira comment section, 
It occurs on newest version of Edge (can't confirm others as I don't use them). 109.0.1518.55 (64bit, official)
![image](https://user-images.githubusercontent.com/100531093/212878815-7ae7c5e7-8640-43da-a8e2-becc6c3af83b.png)

This issue disappears when I disable the extension for Jira website.
I've tried Cache and Cookie clearing, still no improvement.

**Comment by danielnaber** [comment]
Thanks, we're aware of this issue. It should be solved with the next update in 1-2 weeks.

**Comment by Malinq94** [comment]
Hey @tiff it's fixed as you said, got fix yesterday. Thank you for the fast reaction. :)
