### ISSUE TITLE
[de] "nachfragerbezogen" wird zu "nachfragebezogen" korrigiert

### ISSUE THREAD

**Issue by sterafix** [languagetool-org/languagetool#7730]
"nachfragerbezogen" wird zu "nachfragebezogen" korrigiert. 

<img width="409" alt="grafik" src="https://user-images.githubusercontent.com/72454286/213299327-d29349ee-253f-4942-9692-4ade43d0b433.png">

Ersterer Begriff wird allerdings sogar teilweise in der Fachliteratur verwendet https://link.springer.com/chapter/10.1007/978-3-663-07968-2_2

**Comment by Discostu36** [comment]
"Nachfragebezogen" wird laut Google 10x häufiger verwendet. Ich frage mich, ob man diese Alternativschreibung einfach erlauben oder ob man die häufigere Variante zumindest in der Stilanalyse vorschlagen sollte.
