### ISSUE TITLE
[pt] Idea for rule: “e que” → “e” - 2023-01-21

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7735]
@ricardojosehlima

Hello!

Another idea to simplify text:
`É necessário saber que os terroristas são perigosos E QUE ninguém está seguro.`
becomes:
`É necessário saber que os terroristas são perigosos E ninguém está seguro.`

Is it a good plan?

Thanks!

**Comment by marcoagpinto** [comment]
Ricardo, do you have any idea of which keywords I should look after?

NC + “e” + “que” + pronoun/NC?

Do verbs have influence? Specific verbs?

Thanks!

**Comment by marcoagpinto** [comment]
Ricardo!

The rule already exists, but it doesn't detect the sentence above.

```
    <!-- E QUE que -->
    <rule id='SIMPLIFICAR_E_QUE_QUE' name="Simplificar: E que → que" type="style">
      <!--      Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2022-05-27 + 2022-06-01/02 (24-MAY-2022+)      -->
      <!--
      São regras muito simples e que permitem agir corretamente. → São regras muito simples que permitem agir corretamente.
      Recebemos um documento escrito em francês e que revelou uma lista de restaurantes. → Recebemos um documento escrito em francês que revelou uma lista de restaurantes.
      -->
      <antipattern>
        <token skip='-1'>que</token>
        <token postag='V.+' postag_regexp='yes' skip='-1'/>
        <token>que</token>
        <token postag='V.+' postag_regexp='yes'/>
        <example>Não há evidências de que seja melhor para o ambiente ou que contribua para o conceito.</example>
        <example>Afirmou que ainda não foi intimada sobre a decisão e que vai entrar com um recurso.</example>
      </antipattern>
      <pattern>
        <token postag='RG|SPS00' postag_regexp='yes'/>
        <token postag='AQ.+|NC.+' postag_regexp='yes'/>
        <marker>
          <token>e</token>
          <token>que</token>
        </marker>
        <token postag='V.+' postag_regexp='yes'>
          <exception postag_regexp='yes' postag='VMIS.+|VMSI.+'/>
        </token>
      </pattern>
      <message>Pode omitir a conjunção ‘e’ para tornar o texto mais fluido.</message>
      <suggestion>que</suggestion>
      <example correction="que">São regras muito simples <marker>e que</marker> permitem agir corretamente.</example>
      <example>Índio me disse que interpretou a pergunta como uma brecha aberta para uma negociação de propina e que tratou de fechá-la no mesmo instante.</example>
      <example>A vítima disse que apanhou bastante e que Beto agiu com violência e que escondeu a faca do crime quando os militares chegaram.</example>
      <example>Eron conta que já se envolveu com mulheres e que foi até noivo de uma delas.</example>
    </rule>
```

**Comment by marcoagpinto** [comment]
@ricardojosehlima

I am completely insane.

The rule I pasted above is “e que” → “que”.

What we need is “e que” → “e”.

I am terribly sorry for mixing it.

I will start coding the new rules in a few minutes.

**Comment by marcoagpinto** [comment]
@ricardojosehlima

I believe it is working:
https://github.com/languagetool-org/languagetool/commit/beb832e6c6052df168cec389e3902f8bec69aa82

```
Portuguese (Portugal): 62 total matches
Portuguese (Portugal): 582235 total sentences considered
```
[8.txt](https://github.com/languagetool-org/languagetool/files/10472221/8.txt)

This last .txt adds “a(s)” and “o(s)” after the “e que” and I was too stressed to check one by one entirely, but it appears to be okay.

I hope it is working as planned.

Thanks for your time, dear brother!

❤️ 😋 😛

**Comment by ricardojosehlima** [comment]
Hi

See
Deixe que o robot cuide do transporte e que os seus colaboradores se concentrem em tarefas mais importantes.

Deixe que o robot cuide do transporte que os seus colaboradores se concentrem em tarefas mais importantes.

Do you think the latter is ok? A first reading would connect the second que to transporte which is not the case in the original sentence.

**Comment by ricardojosehlima** [comment]
I've seen many cases like this...

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

So, I should remove the `DA.+|SPS00:DA.+` that flags "a,o, as, os"?

It will produce a ton less hits, but we prefer accuracy.

**Comment by ricardojosehlima** [comment]
Sorry I misread the rule, it's fine.

**Comment by marcoagpinto** [comment]
Meanwhile, my head has been bursting with ideas and I don't know which one to write first, so I will start with an easy to code one.

I will open a ticket in a few moments.
