### ISSUE TITLE
There is a typo in the premium page

### ISSUE THREAD

**Issue by Devoxer** [languagetool-org/languagetool#7736]
![84414C79-7009-4A7E-BDC0-BE7AA711292E](https://user-images.githubusercontent.com/23736496/213849445-fc4ee112-3cb1-4dcc-bf60-4f2f7cf2a57f.jpeg)

**Comment by jaumeortola** [comment]
"Add-in" is Microsoft's terminology, as you can see here: 
https://support.microsoft.com/en-us/office/view-manage-and-install-add-ins-for-microsoft-365-programs-16278816-1948-4028-91e5-76dca5380f8d
