### ISSUE TITLE
[pt] Idea for rule: "para ajudar a melhorar" → "para melhorar" - 2023-01-23

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7744]
@ricardojosehlima

Hello Dear Ricardo,

I am not sure if we should state that if it is a PhD thesis we must improve the writing style or what we should write if it is not intended for a PhD.

Look at sentences like:
`Estas regras servem PARA AJUDAR A melhorar a gramática.`
Would suggest:
`Estas regras servem PARA MELHORAR a gramática.`

It searches for “PARA AJUDAR A” + <verb_in_infinitive> and suggests “PARA” + the verb_in_infinitive.

Ricardo, you hold a PhD and know better than me if this rule is specific for thesis or to all the society (to know what to write in the suggestion text).

In my opinion, it applies at least to PhD thesis where one must use affirmative wording.

Thanks!

**Comment by marcoagpinto** [comment]
EDIT: The two sentences above were the “before” and the “after”, I separated them.

**Comment by ricardojosehlima** [comment]
Worth a try, we must see more sentences to check it

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello!

Good morning!

```
    <!-- PARA AJUDAR A MELHORAR para melhorar -->
    <rule id='TESE_PHD_PARA_AJUDAR_A_VINFINITIVO_PARA_VINFINITIVO' name="[PhD Tese]: Para Ajudar a + V.Inf. → Para V.Inf." type='style'>
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2023-01-24 (25-JUL-2022+) -->
      <!--
      Estas regras servem para ajudar a melhorar a gramática. → Estas regras servem para melhorar a gramática.
      -->
      <pattern>
        <marker>
          <token>para</token>
          <token inflected='yes'>ajudar</token>
          <token>a</token>
          <token postag='VMN0000' postag_regexp='no'/>
        </marker>
      </pattern>
      <filter class="org.languagetool.rules.pt.AdvancedSynthesizerFilter" args="lemmaFrom:4 lemmaSelect:V.* postagFrom:2 postagSelect:V(......)* postagReplace:V[\b1]*"/>
      <message>Se for uma tese de doutoramento, verifique se o 'tom' de redação é o apropriado.</message>
      <suggestion>\1 {suggestion}</suggestion>
      <example correction="para melhorar">Estas regras servem <marker>para ajudar a melhorar</marker> a gramática.</example>
    </rule>
```

Like my thesis supervisor complained in my first attempt to write a PhD thesis:
`"Esta tese procura provar blah blah blah"`
He shouted at me: `"Se procuras provar, o juri vai dizer para ires para casa para continuares a procurar"` (can't remember the exact words).

So, in a PhD we don't use wording that create doubts, we must use affirmative wording.

In a Master's dissertation you can use questions style, but not in a PhD.

There was going to be a tag for rules such as 'academic' or so, not sure when they will be implemented.

@danielnaber Do you have an idea when the new tags will be working so that I can change some rules to academic mode only?

@ricardojosehlima 
Here are the results:

```
Portuguese (Portugal): 33 total matches
Portuguese (Portugal): 582235 total sentences considered
```

[0.txt](https://github.com/languagetool-org/languagetool/files/10486770/0.txt)


Thanks!
