### ISSUE TITLE
[pt] Disambiguator bug: turns verb into noun – 2023-01-24

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7746]
Hello @jaumeortola 

Look at the sentences:
```
A sua deve comer.
A tua deve comer.
```
“deve” is parsed as a noun instead of a verb (verb “dever”).

Could you enhance the disambiguator?

Thanks!

**Comment by jaumeortola** [comment]
In this case, an adequate solution is to give priority to the disambiguation rule "dever+infinitive": https://github.com/languagetool-org/languagetool/commit/1649d3da639eeda1eb91ebabc9f1421dfdd65126

But the disambiguation of "a" (determiner/preposition) is more difficult and needs to be improved. Please keep reporting examples like this.

**Comment by marcoagpinto** [comment]
@jaumeortola 

What I have been noticing lately is that certain words have two POSes or more, but if you only use one in the antipattern it doesn't work, you either need to use both or the other. To solve my antipattern, I placed both postags in the code. I can't remember the sentence right now.

I also recall that certain words have several repetitions of POSes.

Yesterday or today I was seeing the morphologic information and certain words had three or four equal codes.
