### ISSUE TITLE
Compilation suddenly fails

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#7748]
[INFO] LanguageTool command-line version .................. FAILURE [  0.403 s]
[INFO] LanguageTool embedded HTTP server .................. SKIPPED
[INFO] LanguageTool tools for building dictionaries ....... SKIPPED
[INFO] LanguageTool stand-alone GUI ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.435 s
[INFO] Finished at: 2023-01-24T13:16:33+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project languagetool-commandline: Compilation failure: Compilation failure: 
[ERROR] error reading /media/ruud/data3/LT/languagetool/languagetool-language-modules/gl/target/language-gl-6.1-SNAPSHOT.jar; zip END header not found

Java version:
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)

**Comment by danielnaber** [comment]
Seems like a temporary error - what command did you use? Does `mvn clean package -U` work?

**Comment by baarsrj** [comment]
Yes, that worked. Thanks.
