### ISSUE TITLE
Feature Request: HTTP Server JSON expansion.

### ISSUE THREAD

**Issue by KnowZero** [languagetool-org/languagetool#775]
Right now a JSON request looks something like this:

`{ "text":"I am testming here", "language":"en-US" }`

It would be nice if it could be expanded to add some sort of multiple requests:

```
{ 
"session1":{"text":"I am testming here", "language":"en-US"},
"session2":{"text":"I am not testming here", "language":"en-US"}
}
```

Maybe even an option for setting global rules:

```
{
"_global":{ "language":"en-US" },
"session1":{"text":"I am testming here"},
"session2":{"text":"I am not testming here"}
}
```

or maybe to keep some backwards compatibility:

```
{
"language":"en-US",
   "multiple":{
     "session1":{"text":"I am testming here"},
     "session2":{"text":"I am not testming here"}
   }
}
```

Right now I am kind of hacking things in by use of tabs and new lines to achieve similar results (though all parameters are global. But it would be nice if it could be done without that and would probably leave less room for error.

**Comment by danielnaber** [comment]
What is your use case? I understand you have many small texts which are independent of each other?

**Comment by KnowZero** [comment]
Yes, what I do is give each container tag its own UUID, then when someone makes a change only that UUID is submitted. This makes sure that instead of the entire 5 pages being sent when evaluated, only a small text is sent.

And when you paste in 5 pages, it sends in multiple UUIDs.

This also lets me set a size limit on the text and create a queue of UUIDs (since in 10 seconds a user can make modifications in multiple places)

This also allows for handling of complex things like table cells and etc.

What I want though is to expand on it a bit further and create some user defined rules.

For example, you could add a regexp of:

"(.*?)" = ruleset1

And create a different ignore/include list for that regexp. (Since speech patterns tend to differ from more strict grammar rules)

At this point I just plan on dividing it up into multiple requests, but it would be better if they were part of one request.

**Comment by danielnaber** [comment]
I'm closing this, as I'm not sure the complexity is worth it.
