### ISSUE TITLE
[pt] New category for PhD thesis, academic and scientific texts - 2023-01-26

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7754]
Hello @jaumeortola @susanaboatto @ricardojosehlima

I have been reflecting, and maybe it would be a good idea to add a new category to grammar.xml:
`“PhD teses, textos científicos e académicos”`
with the tag: “academic”

See the tags here:
https://github.com/languagetool-org/languagetool/pull/6631/commits/c4b99d8602474eb4e9e6fa4d3bb1af7e49e9953a

Then we could start moving some rules into it.

Should we try it?

Thanks!

**Comment by marcoagpinto** [comment]
@jaumeortola 

May I create the category in the main grammar.xml?

“Teses, textos científicos e académicos”

But, how do we make “académicos” show as “acadêmicos” in pt-BR?

Thanks!

**Comment by jaumeortola** [comment]
> But, how do we make “académicos” show as “acadêmicos” in pt-BR?

This is a different topic. How to provide messages and rule names in pt-BR and pt-PT. It was discussed here: https://github.com/languagetool-org/languagetool/issues/6956
We can plan to implement a solution for this.

**Comment by marcoagpinto** [comment]
Hello!

I have created a new category:
`<category id='ACADEMIC_SCIENTIFIC' name="Regras académicas e científicas" type="other">`

https://github.com/languagetool-org/languagetool/commit/d2d777447b707c3057225d612c986f675ecd5b97

I have moved all the scientific and academic rules I could find, into it.

I also improved the rules' IDs, and names.

Some rules were created long ago and need to be improved.

At least they are now together and easier to spot in case they require changes.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by maphjo** [comment]
Hi @marcoagpinto,
Thank you very much for this. As Susana said, this might help us in the future. 
But please be careful with changing rule IDs. The IDs are connected to the disabling of rules. If you change it, a rule will work again for all users who disabled it before.

**Comment by marcoagpinto** [comment]
> Hi @marcoagpinto,
> Thank you very much for this. As Susana said, this might help us in the future.
> But please be careful with changing rule IDs. The IDs are connected to the disabling of rules. If you change it, a rule will work again for all users who disabled it before.

Ahhhh… right!

I also remembered later that Susana had rules with "Temp=off", I hope I haven't changed the names of some of them 😢
