### ISSUE TITLE
[nl] srx rule

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#7763]
pp. 
73–371
Should not be split.

I could not get a rule to work.

Help available?

**Comment by danielnaber** [comment]
SRX is only about sentence boundaries. When you say "should not split", it seems you mean `pp.` should be one token, not two?

**Comment by baarsrj** [comment]
No. I mean the sentence should not be ended after pp.Op 28 jan. 2023 20:53 schreef Daniel Naber ***@***.***>:
SRX is only about sentence boundaries. When you say "should not split", it seems you mean pp. should be one token, not two?

**Comment by danielnaber** [comment]
Can you provide a full example where that happens? I couldn't reproduce using an artificial example.

**Comment by baarsrj** [comment]
You are right. It only happens in cascading errors in srx. Thanks.
