### ISSUE TITLE
[de] Allow "60-Sekünder" etc.

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#7777]
In marketing, video production etc. it is common to refer to films of a certain length with a noun like "[30-Sekünder](https://www.google.com/search?q=%2230-Sek%C3%BCnder%22)" or "[30-Minüter](https://www.google.com/search?q=%2230-Min%C3%BCter%22)". 

I don't know how we can have LT allow these compounds, without also allowing a wrong isolated "Sekünder".

**Comment by danielnaber** [comment]
You can do this with `<disambig action="ignore_spelling"/>` in `de/disambiguation.xml`. If you search for `ignore_spelling` in that file, you'll see some examples.

**Comment by Discostu36** [comment]
Ok, but that means there will be no suggestion if someone writes "60-Sek*u*nder"?

**Comment by danielnaber** [comment]
If the pattern matches `\d-Sekünder`, only those will be ignored, not "xx-Sekunder".

**Comment by Discostu36** [comment]
Yes, but ignoring means there will be no spelling suggestion in case of a typo?

**Comment by danielnaber** [comment]
Maybe the suggestion won't be perfect, but if you mistype "xx-Sekünder", there will be a suggestion.
