### ISSUE TITLE
[en] FP in EN_COMPOUNDS  for 'sailing vessel'

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#7785]
> The sailing vessel has an unusual construction.

The text is correct BrE (https://www.collinsdictionary.com/dictionary/english/sailing-vessel). I do not know about AmE. LT gives an incorrect warning for BrE:

![image](https://user-images.githubusercontent.com/5816160/216120338-34fde16c-e7e3-457e-872b-9d75d7240ebc.png)

**Comment by tiff** [comment]
I couldn't find any reference for AmE either. Fixed it as part of https://github.com/languagetool-org/languagetool/commit/d9283f2dc67df513bacb6014c85b472399d90357
