### ISSUE TITLE
[pt] Idea for rule: “Fazer + [da.+|di.+] + verb → verb_infinitive” – 2023-02-03

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7788]
Hello @ricardojosehlima

I came up with an idea for a rule.

See the sentences:
```
Fazer conjeturas sobre algo é medir uma probabilidade.
Fazer uma conjetura sobre algo é medir uma probabilidade.
```
The core idea is to turn the verb after “fazer” into infinitive and simplify the sentence.

For example, the above sentences would become:
```
Conjeturar sobre algo é medir uma probabilidade.
Conjeturar sobre algo é medir uma probabilidade.
```

I believe it will only work with verbs in the same person as “conjetura” and “conjeturas” (`VMM02S0|VMIP2S0`).

Is it a good idea?

Thanks!

**Comment by ricardojosehlima** [comment]
Hi seems fine. In pt-br we use c still, conjectura(s)

**Comment by marcoagpinto** [comment]
Ahhhh… 😄 

At 5am, I will code it.

I will replace that word with other after I see the results and will take a verb from there.

❤️

**Comment by marcoagpinto** [comment]
ahhhhh... tons of false positives, I will rewrite the rule and the antipatterns.

**Comment by marcoagpinto** [comment]
I started from scratch, here is the tons of false positivives it gives.

I will remove the verb "comprar" and "contar" which will fix tons of hits.

```
Portuguese (Portugal): 563 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[21_ALL_AGAIN_HERE_HERE_HERE.txt](https://github.com/languagetool-org/languagetool/files/10608798/21_ALL_AGAIN_HERE_HERE_HERE.txt)

Yes, I give strange names to files 😋

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is done!
https://github.com/languagetool-org/languagetool/commit/bdceb07ceaf22b036eff5c8dee9dc1ba56046aa0

```
Portuguese (Portugal): 33 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```
[39.txt](https://github.com/languagetool-org/languagetool/files/10609402/39.txt)

```
    <!-- FAZER CONJECTURAS conjecturar -->
    <rule id='FAZER_VERBO_VERBO_INFINITIVO' name="Simplificar: V.Fazer + V. → V.Inf." type="style">
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2023-02-04 (25-JUL-2022+) -->
      <!--
      Fazer somas é o melhor que há. → Somar é o melhor que há.
      Mas fazer somas sobre algo é medir uma probabilidade. → Mas somar sobre algo é medir uma probabilidade.
      Assim fazer somas é o melhor. → Assim somar é o melhor.
      -->

      <antipattern>
        <token postag='NC.+|AQ.+' postag_regexp='yes'/>
        <token postag='SPS00' postag_regexp='no'/>
        <token>fazer</token>
        <token postag='VMIP2S0' postag_regexp='no'/>
        <token postag='VMIP3.+' postag_regexp='yes'/>
        <example>...is estratégicos para a retirada dos produtos pelos próprios clientes quanto a de uso de drones para fazer entregas estão sendo avaliadas pela Diálogo Logística para serem implantadas no país.</example>
      </antipattern>

      <pattern>
        <marker>
          <token>fazer</token>
          <token postag='VMIP2S0' postag_regexp='no'>
            <exception regexp='yes' inflected='yes'>amostrar|asneirar|bonecar|comprar|contar|curvar|dobrar|maravilhar|oferendar|provar|receitar|reformar|rimar|roupar|trançar|trilhar</exception> <!-- Add here exception verbs as they are found -->
            <exception postag_regexp='yes' postag='RG|RN|CC|CS|SPS00|DA.+|SPS00:DA.+|DI.+|SPS00:DI.+|PP.+|SPS00:PP.+|DP.+|SPS00:DP.+|AP.+|SPS00:AP.+'/>
          </token>
        </marker>
        <token>
          <exception postag_regexp='yes' postag='VMP00.+|NC.+|AQ.+|AP.+|DP.+'/>
          <exception regexp='yes'>aos?</exception>
        </token>
      </pattern>
      <message>Esta perífrase poderá ser simplificada.</message>
      <suggestion><match no='2' postag='V.+' postag_regexp="yes" postag_replace='VMN0000'/></suggestion>
      <example correction="Somar"><marker>Fazer somas</marker> é o melhor que há.</example>
      <example correction="somar">Mas <marker>fazer somas</marker> sobre algo é medir uma probabilidade.</example>
      <example correction="somar">Assim <marker>fazer somas</marker> é o melhor.</example>
      <example>Quero ir fazer compras.</example>
      <example>Eu preferiria não ir fazer compras sozinho.</example>
      <example>Já dizia o outro: é uma questão de fazer contas.</example>
      <example>Ele não é inteligente o bastante para fazer contas de cabeça.</example>
      <example>Aqui você pode fazer suas denuncias, reclamações, sugestões e elogios.</example>
      <example>..., baseadas no fato de que não vamos viver pra dieta (embora seja necessária certa dedicação), vamos fazer juntas nossa dietinha?</example>
      <example>Foi permitido fazer perguntas ao final da reunião.</example>
      <example>Xangô quis saber o que poderia fazer para ver sua filha só mais uma vez, e Orunmilá lhe disse para fazer oferendas ao orixá Iku (Oniborun), o guardião da entrada do mundo dos mortos.</example>
      <example>Fazer dobras em.</example>
    </rule>
```

In short:
The rule was hard to make because if you replaced the resulting verbs with “conjecturar” they would be valid, so, the best thing to do was to create a list of the non-valid verbs in the results instead of spending hours creating antipatterns and face the issue of losing valid sentences. I did create one antipattern after rewriting the whole rule to remove some false positives.

**Comment by ricardojosehlima** [comment]
Hi,
  For pt-br fazer perguntas means something different than perguntar. See:

Você pode fazer perguntas para esse professor.

Você pode perguntar para esse professor.

The first is used for a generic reading of pergunta, as the second is a more specific pergunta.

**Comment by marcoagpinto** [comment]
@ricardojosehlima @susanaboatto @jaumeortola 

My idea to make it slightly easier to create exceptions/antipatterns regarding verbs:
Tomorrow I will create an entity called "verbos_muito_incomuns" with verbs that no one uses, such as:
"asneirar|bonecar|maravilhar|oferendar|roupar|trançar" etc.

This entity will make it easier while developing.

**Comment by marcoagpinto** [comment]
> Hi, For pt-br fazer perguntas means something different than perguntar. See:
> 
> Você pode fazer perguntas para esse professor.
> 
> Você pode perguntar para esse professor.
> 
> The first is used for a generic reading of pergunta, as the second is a more specific pergunta.

Ahhhh... I had that doubt, thanks for telling me. I will fix it right away.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Done!

https://github.com/languagetool-org/languagetool/commit/ae252387c92ac516bedbc40d69a65767208bfde6

```
Portuguese (Portugal): 6 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[40.txt](https://github.com/languagetool-org/languagetool/files/10609438/40.txt)

😋 😛 ❤️

**Comment by marcoagpinto** [comment]
GMTA!

Great Minds Think Alike!
