### ISSUE TITLE
[pt] Suggestion for altering the explanation for "menas"

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#7789]
Hi,
  Currently, LT explains why menas is wrong in this way:

  O Advérbio “menos” não sofre alteração de gênero.

  However, when menas is employed it is almost always as an indefinite pronoun: quero menas água. água is a noun, so menas can't be, by definition, an adverb. So, an alternative could be:

   "Menas" é uma flexão de um pronome indefinido que não é aceita em registros formais.

**Comment by marcoagpinto** [comment]
Done!
