### ISSUE TITLE
[pt] ENTITY verbos_muito_incomuns

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7795]
Hello @susanaboatto @ricardojosehlima @jaumeortola 

I have added this entity to grammar.xml:
```
    <!-- The entity verbos_muito_incomuns are verbs almost 100% not used and cause false positives. It can be used in exceptions. Use: inflected='yes' -->
    <!ENTITY verbos_muito_incomuns "asneirar|bobear|bonecar|farar|maravilhar|oferendar|roupar|trançar">
```

The idea is to add here verbs that 99% of people won't use and cause false positives.

It will be useful to add to exceptions in rules that use verbs.

More verbs will be added as they are discovered while developing rules.

I wish I had this idea before.

**Comment by susanaboatto** [comment]
Good idea! 💡

**Comment by jaumeortola** [comment]
This list of verbs could be used in disambiguation. The rule would be something like this: 
If any word is a verb in this list and any other thing (noun, adjective...), then remove the verb tag. 
We will need to maintain a copy of the list in the two files: grammar.xml and disambiguation.xml.

**Comment by marcoagpinto** [comment]
> This list of verbs could be used in disambiguation. The rule would be something like this:
> If any word is a verb in this list and any other thing (noun, adjective...), then remove the verb tag.
> We will need to maintain a copy of the list in the two files: grammar.xml and disambiguation.xml.

Excellent idea, @jaumeortola 

❤️ ❤️ ❤️ ❤️
