### ISSUE TITLE
LanguageTool icon looks blurry 

### ISSUE THREAD

**Issue by quackerex** [languagetool-org/languagetool#7797]
In Firefox, both in the setting page and extension panel, LanguageTool icon looks blurry.

<img width="116" alt="image" src="https://user-images.githubusercontent.com/41659980/216901331-0e015249-b3f3-4ea5-9582-338e5a1de346.png">

<img width="412" alt="image" src="https://user-images.githubusercontent.com/41659980/216901380-8dfbddce-07c3-405a-8580-19ebf9a52291.png">

<img width="146" alt="image" src="https://user-images.githubusercontent.com/41659980/216901464-4489fa66-5f08-41cd-8b90-c269cacf8f8f.png">

**Comment by danielnaber** [comment]
I've also seen this, but it only happens sometimes. We have defined several resolutions in the `manifest.json`, so this looks like a bug in Firefox to me:

```
	"icons": {
		"16": "assets/images/icons/icon16.png",
		"32": "assets/images/icons/icon32.png",
		"48": "assets/images/icons/icon48.png",
		"64": "assets/images/icons/icon64.png",
		"128": "assets/images/icons/icon128.png"
	},
```

**Comment by danielnaber** [comment]
I have submitted an issue for Firefox at https://bugzilla.mozilla.org/show_bug.cgi?id=1815752

**Comment by danielnaber** [comment]
Potential solution is to use more than one icon for browser_action.default_icon: https://bugzilla.mozilla.org/show_bug.cgi?id=1815752#c10

**Comment by tiff** [comment]
Next release (~1 week) will contain a fix for this
