### ISSUE TITLE
FR "bien entendu" (indeed) is seen as if "entendu" was the verb

### ISSUE THREAD

**Issue by briceparent** [languagetool-org/languagetool#780]
In the sentence : "Elles sont bien entendu placées en hauteur.", the system sees 2 errors, one at entendu becauses it thinks it should be "entendues", and one ate "placées" because it thinks it should be "placer", while the sentence should be correct (to my knowledge).

But I'm not sure how to correct it, as "Elles sont bien entendu." is not correct, and should indeed be changed to "Elles sont bien entendues", so the rule is not obvious to write.

**Comment by dpelle** [comment]
I fixed it in 6894aca4fc8e958e7d0a94e36688118023a58162 by adding a disambiguator rule to classify "bien entendu" as adverb.

**Comment by briceparent** [comment]
I agree with the false negative not being common at all.
Congrats on the quick fix!
