### ISSUE TITLE
LanguageTool does not work in SnappyMail editor

### ISSUE THREAD

**Issue by gramakri** [languagetool-org/languagetool#7805]
The LanguageTool icon does not appear in the compose window of  https://github.com/the-djmaze/snappymail .

There are two problems:
* The LT icon does not appear in the bottom right
* The corrector works (see yellow underline in text). But selecting the yellow does not show the popup with corrections.

![image](https://user-images.githubusercontent.com/82041/217205118-370834d2-bf60-4306-b3b9-52deaebee481.png)

Are there any guidelines as to what is needed for the integration to work properly? I can take this up with SnappyMail upstream as well.

**Comment by gramakri** [comment]
I see that SnappyMail doesn't have a demo, so this might be a bit complicated for you to get it running. Let me know if you want me to give you access to a demo instance.

**Comment by afonsosantos** [comment]
Hi everyone,

SnappyMail does have a demo instance: [https://snappymail.eu/demo/](https://snappymail.eu/demo/)

Thanks.

**Comment by tiff** [comment]
This is now working in Chrome and Edge. We will roll out the fix for Firefox in the next weeks.
