### ISSUE TITLE
[de] das Zwischenspeichern is unknown

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#7819]
`zum Beispiel die Verwendung einer anderen API oder Überladung oder das Zwischenspeichern von Werten`

**Comment by Discostu36** [comment]
Spellchecker is ok, but the POS tagger thinks that “Zwischenspeichern” is the dative plural of “der Zwischenspeicher”.

**Comment by tiff** [comment]
Danke! Ist nun behoben
