### ISSUE TITLE
LibreOffice plugin - Sentences ending with a dot can't be overwritten in the dialog box

### ISSUE THREAD

**Issue by TiagoSantos81** [languagetool-org/languagetool#782]
Reported on issue #669 

 @FredKruse
     Member
«
Rules that replaces a dot at the end of a sentences for example by a question mark don't work in the dialog box (F7) (out of the text using the right mouse button they work fine). The question mark is inserted before the dot (this produces the next error). The behavior is strange. I don't know if LT handles the dialog box and the suggestions in the text different or if there is a bug inside of libre office.
I would like to work on both points but it will take time because I am not familiar with the interface and also not with the LT-code. So I have to do a lot of research.
 @TiagoSantos81
     Member
TiagoSantos81 commented 3 days ago
Rules that replaces a dot at the end of a sentences for example by a question mark don't work in the dialog box (F7)
I can confirm this. I tested it with the 'greeting and farewells' rules that I localized from German to Portuguese, since they have the exact same behaviour in both languages. For example, it replaces the dot in best regards. with best regards,. in an infinite cycle.
The rule works fine outside of the 'spelling and grammar' dialog (F7).
...
 @FredKruse
     Member
FredKruse commented 2 days ago
The problem with the dialog is not related with the TextLevelRules. I tested it with rules on sentences level.

**Comment by FredKruse** [comment]
As far as I see, the LibreOffice plugin uses the standard LO dialog for spelling errors. I found no way to change the reported error.
So there is only one idea left: Implement a filter which removes all suggestions for rules that try to replace the ending dot of sentences. I think its better to give no suggestion as to produce additional errors (like ?.).
@TiagoSantos81 and @danielnaber: What do you think, is this a good idea? I could implement such a filter in the plugin.

**Comment by TiagoSantos81** [comment]
This is indeed a serious bug in LO. 

In my opinion, 'hiding' the bug by disabling rules that have conflicts is a step back, because they will be overlooked for a longer period of time, and after some time, the workaround becomes the 'usual' behaviour.

Your filter idea is great, and it may be a reasonable compromise. 

On a related note, having a category/rule XML marker for rules that are disabled in LO would be ideal. It could work in tandem with the categorization idea presented on this post: http://forum.languagetool.org/t/severeness/1875/14

I did not finish that development because I got stuck with cross dependencies, and the support for said idea was not strong. If it is useful to you I can post the stashed diff that highlights config variables creation and XML metacode. What I have noticed is that those variables need to be read on each interface, so libreoffice\Main.java should have been the place to read those tags.

**Comment by FredKruse** [comment]
At the moment I'm testing a very simple Idea of a filter. Its look for suggestions that try to change the ending dot of a sentences. If it finds one such suggestion, no suggestions for the error are transfered to LO. So the user get the message in this cases but no suggestions.
I think I will commit the solution this very day.

**Comment by TiagoSantos81** [comment]
:+1:

**Comment by FredKruse** [comment]
Filter is implemented and works. I close this issue.
