### ISSUE TITLE
[en] der Graph is unknown

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#7820]
`Er berechnet den Graph.`
https://www.duden.de/rechtschreibung/Graph_Darstellung_Mathematik

**Comment by danielnaber** [comment]
Siehe https://de.wiktionary.org/wiki/Graph, Akkusativ ist "Graphen", LT hat hier schon recht, denke ich.

**Comment by donnerpeter** [comment]
Oh tatsächlich, Entschuldigung! Deutsche Deklination ist schwer :(
