### ISSUE TITLE
[DE] Kleiner Rechtschreib/Grammatikfehler wird nicht erkannt.

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#7821]
Moin liebes LanguageTool-Team

Sie holte dann einen **fischen** Salat aus dem Kühlschrank und wusch ihn danach in der Spüle aus.
LT: "Keine Fehler gefunden"

Ein kleiner Rechtschreibfehler, der aus einem Adjektiv ein Verb macht, ohne dass das LanguageTool irgendwas sagt.
Dieser Fehler sollte schnell behoben werden, weil solche Fehler in der Masse untergehen.

Grüße Dallun511

**Comment by danielnaber** [comment]
Fixed (https://github.com/languagetool-org/languagetool/commit/c0d2f5807674ccb8affc51b5e9900211530c0071)
