### ISSUE TITLE
[pt] Rule idea: “para que” →”para" - 2023-02-14

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7830]
Hello @ricardojosehlima

I have had this idea to simplify the text, another style rule:
`Os terroristas maximizam a respetiva exposição para que o mundo saiba que eles existem.`
>para o mundo saber(em)

It will involve removing the “que” and changing a verb to infinitive plural or singular.

Is it a good idea?

Thanks!

**Comment by ricardojosehlima** [comment]
Yeah let's see it in sentences, see if it'll change the original message or not

**Comment by marcoagpinto** [comment]
Yes, I will code it this afternoon. 😄

Then, we will check the results.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is already afternoon, so I coded the rule. 😋 

The good thing about the rule is that it has two static tokens, and the more of those you have, the fewer are the chances of false positives.

I gave a brief look at the results and the ones I saw seemed valid.

Here are the results:
https://github.com/languagetool-org/languagetool/commit/1ed7be2d78e316618da1cd0f5b30331849ad2f25

Portuguese (Portugal): 158 total matches
Portuguese (Portugal): 582235 total sentences considered

[4.txt](https://github.com/languagetool-org/languagetool/files/10733149/4.txt)


❤️ ❤️ ❤️ ❤️ 

Thanks!

Here is the rule (yes, a tiny number of lines, so easy to code):


```
    <!-- PARA QUE para -->
    <rule id='PARA_QUE_PARA' name="Simplificar: para que → para" type='style'>
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2023-02-14 (25-JUL-2022+) -->
      <!--
      Os criminosos causam estragos para que o mundo saiba que eles existem. → Os criminosos causam estragos para o mundo saber que eles existem.
      Os criminosos causam estragos para que os povos saibam que eles existem. → Os criminosos causam estragos para os povos saberem que eles existem.
      -->
      <pattern>
        <marker>
          <token>para</token>
          <token>que</token>
          <token postag='(SPS00:)?D[AI].+' postag_regexp='yes'/>
          <token postag='NC.+|AQ.+|NP.+' postag_regexp='yes'/>
          <token postag='VMM03.+' postag_regexp='yes'/>
        </marker>
      </pattern>
      <message>Esta perífrase poderá ser simplificada.</message>
      <suggestion>\1 \3 \4 <match no='5' postag='VMM03(.)0' postag_regexp="yes" postag_replace='VMN03$10'/></suggestion>
      <example correction="para o mundo saber">Os criminosos causam estragos <marker>para que o mundo saiba</marker> que eles existem.</example>
      <example correction="para os povos saberem">Os criminosos causam estragos <marker>para que os povos saibam</marker> que eles existem.</example>
    </rule>
```
