### ISSUE TITLE
[pt] Create a category for simplifying sentences?

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7837]
Hello!

@ricardojosehlima @susanaboatto @jaumeortola 

As you have noticed, I have been creating tons of style rules to simplify the sentences and make their writing clearer.

Should I start moving them to the “STYLE” category or should a new category, for example: “SIMPLIFY_SENTENCES” (also of the kind “style”), be created?

Thanks!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
Ahhhh…

Here is a screenshot with all categories existing in PT + PT-BR + PT-PT:


![languagetool_categories_20230215](https://user-images.githubusercontent.com/5192600/218982393-30621969-3f79-46ae-80a1-1ac85dd9b4e8.png)

**Comment by ricardojosehlima** [comment]
Maybe keep to style, after all short sentences are a stylistic feature

**Comment by marcoagpinto** [comment]
> Maybe keep to style, after all short sentences are a stylistic feature

Yes, but I needed advice 😄 

Thanks!
