### ISSUE TITLE
[pt] Number agreement question

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7843]
Hello @ricardojosehlima

I am asking just to be sure.

Look at:
```
Temos em conta terreno/obstáculos poderosos.
Temos em conta terreno/obstáculo poderosos.
```

I know the sentences don't make sense, but they are just examples.

What really concerns me is if the second sentence, where both nouns are singular, is treated as plural.

Thanks!

**Comment by ricardojosehlima** [comment]
Maybe the user wrote the plural influenced by the "s" in "Temos".
Are you considering a rule NOUN-SING ADJ-PLURAL? LT flags this situation for me.

**Comment by marcoagpinto** [comment]
ahhhh

The corrector complains about a number agreement error in my text.

But if I have "noun_singular/noun_plural" or "noun_singular/noun_singular", both should be referred to as plural?

**Comment by ricardojosehlima** [comment]
Hmm, I don't know, this construction with / seems rare in pt-br in formal texts. Anyway, for me, it should be plural.

**Comment by marcoagpinto** [comment]
Thanks!

**Comment by marcoagpinto** [comment]
Fixed (hours ago)! 0 hits in 600 000 sentences!
