### ISSUE TITLE
LanguageTool does not enable PASSIVE_VOICE even when explicitly enabled

### ISSUE THREAD

**Issue by Triagle** [languagetool-org/languagetool#7846]
I understand that in order to enable the `PASSIVE_VOICE` rule in languagetool through the command line, I must pass `-e PASSIVE_VOICE`. However, this does not enable the rule for me. I used the following command to run on a file with only `PASSIVE_VOICE` enabled:
```bash
java -jar ~/.local/langtool/languagetool-commandline.jar -l en-GB -eo -e PASSIVE_VOICE -v /tmp/test.org
```
I ran it on the following file containing an example of passive voice from the rules website:
```
By now, the work will have been completed by the engineers.
```
The verbose output clearly shows that no rules are enabled.
```
Working on /tmp/test.org...
<S> By[by/IN,by/JJ,by/NN,by/RP,B-PP] now[now/RB,B-ADVP],[,/,,,/PCT,O] the[the/DT,B-NP-singular] work[work/NN:UN,E-NP-singular] will[will/MD,B-VP] have[have/VB,I-VP] been[be/VBN,I-VP] completed[complete/VBN,I-VP] by[by/IN,by/JJ,by/NN,by/RP,B-PP] the[the/DT,B-NP-plural] engineers[engineer/NNS,E-NP-plural].[./.,</S>./PCT,O]<P/> 
Disambiguator log: 

BY_RB[1]: now[now/CC,now/JJ,now/NN:U,now/RB,B-ADVP] -> now[now/RB,B-ADVP]

UNKNOWN_PCT[1]: ,[,/,*,O] -> ,[,/,*,,/PCT*,O]

E_NP_NN_VBP[1]: work[work/JJ,work/NN:UN,work/VB,work/VBP,E-NP-singular] -> work[work/NN:UN,E-NP-singular]

CAN_WILL_MD[1]: will[will/VB,will/VBP,will/MD,will/NN:UN,B-VP] -> will[will/MD,B-VP]

MD_VB[1]: have[have/NN,have/VB,have/VBP,I-VP] -> have[have/VB,I-VP]

VBN_VBD[1]: completed[complete/VBD,complete/VBN,I-VP] -> completed[complete/VBN,I-VP]

DT_VB_NN[1]: engineers[engineer/NNS,engineer/VBZ,E-NP-plural] -> engineers[engineer/NNS,E-NP-plural]

UNKNOWN_PCT[1]: .[./.*,./SENT_END*,O] -> .[./.*,./SENT_END*,./PCT*,O]

0 rules activated for language English
Time: 1092ms for 1 sentences (0.9 sentences/sec)
```

# What I Tried
1. Enabling the `STYLE` category via `--enablecategories` in addition to `-e PASSIVE_VOICE`.
2. Removing the `default=off` property from the `PASSIVE_VOICE` rulegroup in the `grammar.xml` file.

**Comment by danielnaber** [comment]
Have you tried with this sentence? The rule doesn't detect all instances of passive.

> It is also thought that tests are satisfactory.

Also, you might need to enable picky mode (`--level PICKY`).

**Comment by Triagle** [comment]
Ah hah! Adding `--level PICKY` fixed it. If anyone else runs into this issue in the future here is exactly what I ran that worked:
```bash
java -jar ~/.local/langtool/languagetool-commandline.jar -l en-GB -e PASSIVE_VOICE --enablecategories STYLE --level PICKY /tmp/test.org
```
