### ISSUE TITLE
LT can't find "standard.dic" -wordbook

### ISSUE THREAD

**Issue by PalaceSoftware** [languagetool-org/languagetool#7849]
Sometimes (esspeccely at the first use of LT or after an reset of the standard.dic) can't LT the standard.dic in the LibreOffice wordbook-folder find. This problem is also there with other wordbooks in this folder (~/.config/libreoffice/4/user/wordbook).

I use Debian GNU/Linux with LibreOffice 7.4.5.1 and LanguageTool 6.0.

**Comment by FredKruse** [comment]
I'm uncertain if I understand you correctly. What do you mean by LT can't find the standard.dic file? Spell checking (red underlines) is performed by LO independently of LT. If there is a problem with this, it occurs at LO.

**Comment by PalaceSoftware** [comment]
I have just tested whether the problem also occurs in the English language environment, and it does not.

In the German locale, when I right-click on the red underlined word, and then press the "Add to dictionary" option, it displays the following:
- en-GB.dic
- en-US.dic
- technical.dic
- Liste ignorierter Wörter [= list of ignored words]

But not the "standard.dic" wordbook.

**Comment by FredKruse** [comment]
The problem should be solved. Please test it with the snapshot tomorrow.
Please close the issue if solved.

**Comment by PalaceSoftware** [comment]
Okay, thank you.
