### ISSUE TITLE
[DE] Fehlalarm mit Sensei (Kommaregel)

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#7852]
Moin liebes LanguageTool-Team

Er sagt: „Ihr wart es, die meinen **Sensei** entführt haben.“
LT: "Hier scheint ein Komma zu fehlen."

Selbstverständlich kommt hier kein komma.

Grüße Dallun511

**Comment by St-ac-y** [comment]
Hier schlägt keine Regel (mehr) an, deshalb schließe ich das Issue. LG
