### ISSUE TITLE
both + plural

### ISSUE THREAD

**Issue by jeanrjc** [languagetool-org/languagetool#786]
Hi

The following sentence is not reported as an error: `Both element are red.`, neither this one `Both of them says that.`, because both is not recognized as a plural.

I've created a rule for the first one, but I'm not a linguist, so I'm not really sure of its exactness. Also I don't know how to deal with invariable nouns like `ski` which raise an error with the following rule.
  
```xml
<!-- English rule, 2017-09-15 -->
<rule id="BOTH_PLURAL" name="Both + plural">
 <pattern>
  <token>Both</token>
  <token postag='NN'><exception postag='VBP|IN|JJ' postag_regexp='yes'></exception></token>
 </pattern>
 <message>Both is followed by a plural. <suggestion>Both <match no="2"/>s</suggestion></message>
 <example correction=''><marker>Both element</marker> are red.</example>
 <example>Both elements are red.</example>
</rule>
```

**Comment by f-knorr** [comment]
Thank you, @jeanrjc for your bug reported (That's how we can make LT better). The errors will now be detected on languagetool. I have optimized your rule suggestions (see linked commit and http://wiki.languagetool.org/development-overview) to avoid some false alarms.
The new rule will be online tomorrow and part of the next LT release. Thank you!
