### ISSUE TITLE
[DE] Fehlalarm bei Redewendung: "Hier und Jetzt"

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#7893]
Moin liebes LanguageTool-Team 

Dallun sagt: „Das werden wir **Hier und Jetzt** klären.“
LT: "Außer am Satzanfang werden nur Nomen und Eigennamen großgeschrieben."

Das stimmt nicht, sondern gilt, wie in der Regel. "In dieser Redewendung werden „Hier“ und „Jetzt“ großgeschrieben."

Bitte beheben.

Grüße Dallun511

**Comment by danielnaber** [comment]
Ich denke, die Großschreibung betrifft nur "**im** Hier und Jetzt".

**Comment by MasterDallun511** [comment]
@danielnaber dann sollte die Regel verfeinert werden.

Wir werden das **Hier und Jetzt** beenden, also mach dich bereit hier zu sterben.
LT: "In dieser Redewendung werden „Hier“ und „Jetzt“ großgeschrieben."
Das fungiert nicht als Begleiter und trotzdem besteht die Regel auf die Großschreibung.

Wir werden es Hier und **Jetzt** beenden, also mach dich bereit hier zu sterben.
LT: "Außer am Satzanfang werden nur Nomen und Eigennamen großgeschrieben."

Wird "das" gegen "es" ausgetauscht, wird nur "Jetzt" bemängelt und nicht "Hier".

Damit kann man sagen, dass das Problem nicht gelöst ist.

Bitte wieder öffnen.
