### ISSUE TITLE
[en-GB] Update the British dictionary

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7895]
Hello @yakovru 

Could you update the British dictionary for the official LanguageTool release at the end of March?
https://github.com/marcoagpinto/aoo-mozilla-en-dict

Thanks!

**Comment by yakovru** [comment]
Hello @marcoagpinto
I have updated the dictionary:
https://github.com/languagetool-org/languagetool/commit/c2462b769735d3c24347711e863bb34eb04f05c9

**Comment by marcoagpinto** [comment]
Thank you, Yakov!

🤗 ❤️ 😋 😛

**Comment by yakovru** [comment]
Closed as completed.
