### ISSUE TITLE
Add Google button to word submission page

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#791]
I think it would be helpful for both admins and users if we had a Google button on the page where users can submit words. Google's algorithm for guessing the intended word is often better than our spelling suggestions. Also, users might be encouraged to rephrase if they notice that there are zero hits.

![2017-09-19-131643_1024x768_scrot](https://user-images.githubusercontent.com/4381288/30590616-aae0950a-9d3f-11e7-8a6d-4f3d423e7a7f.png)

**Comment by janschreiber** [comment]
I might be able to do this myself if somebody could point me to the source file that has to be edited.

**Comment by danielnaber** [comment]
To test it, you'd need to set up Grails, which in general I cannot recommend unless you want to waste many hours of your life.

**Comment by danielnaber** [comment]
Should be online tomorrow at community.languagetool.org
