### ISSUE TITLE
[pt] Idea for rule: “perante o mesmo” → “perante idêntico” - 2023-03-05

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#7915]
@ricardojosehlima

Hello Dear Ricardo,

Please take a look at:
`Os cientistas respondem diferentemente perante o mesmo conjunto de dados.`

The idea is to:
`perante o mesmo` → `perante idêntico`

I am almost sure it is a good rule for formal, scientific or academic texts.

What is your opinion and the kind of rule it should be used for?

Thanks!

**Comment by ricardojosehlima** [comment]
In pt-br formal texts avoid the word mesmo, but the replacement by idêntico is strange for us. 
Maybe there's already a rule for mesmo?

**Comment by marcoagpinto** [comment]
I will add it to pt-PT.

I typed the sentence above, and it didn't suggest changes, so, if there is a rule already it isn't detecting the sentence.

Thanks!

But is it formal, academic or scientific?

🤗 ❤️ 😋

**Comment by ricardojosehlima** [comment]
I'd go for formal

**Comment by marcoagpinto** [comment]
Thank you!

I was napping and only now I got up.

😄

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Well, I coded the rule with the new disambiguator.xml (to fix the word “mesmo”) and it had 0 hits in 600 000 sentences.

I guess almost no one uses such an expensive expression.
https://github.com/languagetool-org/languagetool/commit/08c9a000152c4170617dae80a13b813d8de36c57


```
    <!-- PERANTE O MESMO perante idêntico -->
    <rule id='PERANTE_O_MESMO_IDENTICO' name="[pt-PT][Formal] Perante 'o mesmo' → idêntico">
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2023-03-07 (2-MAR-2023+) -->
      <!-- 
      A ciência responde diferentemente perante o mesmo conjunto de dados. → A ciência responde diferentemente perante idêntico conjunto de dados.
      Estamos perante a mesma categoria de dados. → Estamos perante idêntica categoria de dados.
      -->
      <pattern>
        <token regexp='yes'>perante|ante|diante</token>
        <marker>          
          <token regexp='yes'>d?[ao]s?</token>
          <token regexp='yes'>mesm[ao]s?</token>
        </marker>
        <token postag='NC.+|AQ.+' postag_regexp='yes'/>
      </pattern>
      <message>Num contexto formal, é preferível escrever:</message>
      <suggestion><match no='3' postag='DD0(..)0' postag_replace='AQ0$10'>idêntico</match></suggestion>
      <example correction="idêntico">A ciência responde diferentemente perante <marker>o mesmo</marker> conjunto de dados.</example>
      <example correction="idêntica">Estamos perante <marker>a mesma</marker> categoria de dados.</example>
    </rule>
```
