### ISSUE TITLE
Error in LanguageTool  version 6.0  on LibreOffice 7.5.1.2

### ISSUE THREAD

**Issue by hmidani-abdelilah** [languagetool-org/languagetool#7922]
This is the log of Extension:

LT office integration log from Sun Mar 05 18:26:09 WEST 2023

LanguageTool 6.0 (2022-12-29 12:13:11 +0000, e44dbb0)
OS: Linux 5.15.0-67-generic on amd64
LibreOffice 7.5.1.2 (The Document Foundation, Debian and Ubuntu), en-US
Java-Version: 11.0.18, max. Heap-Space: 2976 MB, LT Heap Space Limit: 2678 MB

setLtDictionary: Create LT spelling dictionary __LT_fr-FR_internal1.dic
Internal LT dicitionary for language fr-FR added: Number of words = 908
Time to generate dictionary: 22
CacheIO: getCachePath: cacheFileName == null!
MultiDocumentsHandler: getNumDoc: Document 0 created; docID = 1
SingleDocument: getCheckResults: SortedTextId and DocumentElementsCount are not supported by LO!
XDrawPageSupplier == null
java.lang.NullPointerException
	at org.languagetool.openoffice.DocumentCache.refreshWriterCache(DocumentCache.java:249)
	at org.languagetool.openoffice.DocumentCache.refresh(DocumentCache.java:173)
	at org.languagetool.openoffice.CheckRequestAnalysis.getParaPos(CheckRequestAnalysis.java:473)
	at org.languagetool.openoffice.CheckRequestAnalysis.getNumberOfParagraph(CheckRequestAnalysis.java:146)
	at org.languagetool.openoffice.SingleDocument.getCheckResults(SingleDocument.java:301)
	at org.languagetool.openoffice.SingleDocument.getCheckResults(SingleDocument.java:165)
	at org.languagetool.openoffice.MultiDocumentsHandler.getCheckResults(MultiDocumentsHandler.java:231)
	at org.languagetool.openoffice.MultiDocumentsHandler.doProofreading(MultiDocumentsHandler.java:174)
	at org.languagetool.openoffice.Main.doProofreading(Main.java:81)

LanguageToolMenus: ContextMenuInterceptor: xTextDocument == null
LanguageToolMenus: setActivateRuleMenu: event id: 1504

![Screenshot from 2023-03-05 18-36-02](https://user-images.githubusercontent.com/39446276/222976820-47b3ff78-79b5-48a0-b56a-e634907458f6.png)

**Comment by FredKruse** [comment]
This bug is solved in LT 6.1

**Comment by hmidani-abdelilah** [comment]
link to download it

**Comment by ichayapet** [comment]
It don't find an LT 6.1 is there a link to it somewhere?

**Comment by danielnaber** [comment]
> It don't find an LT 6.1 is there a link to it somewhere?

No, but you can use the latest snapshot at https://internal1.languagetool.org/snapshots/

**Comment by hmidani-abdelilah** [comment]
link to download : 
https://languagetool.org/download/

**Comment by FredKruse** [comment]
@danielnaber There is a stable LT 6.1.1 version at branch v6.1.1 now. How do we continue? Should I compile the extension and load it up to LO?

**Comment by danielnaber** [comment]
@FredKruse I've uploaded the build to https://languagetool.org/download/LanguageTool-6.1.1-beta.zip - could you check it? If it's okay, I will remove the "beta" from the name.

**Comment by FredKruse** [comment]
@danielnaber I did some tests. It's OK, I think. Should I load up it to the LO extension page?

**Comment by danielnaber** [comment]
@FredKruse 
> Should I load up it to the LO extension page?

Yes, please

**Comment by FredKruse** [comment]
@danielnaber It's done

**Comment by danielnaber** [comment]
@FredKruse Okay, the file will soon be renamed to `LanguageTool-6.1.1.oxt` at https://languagetool.org/download/

**Comment by FredKruse** [comment]
I will close this issue as solved. Open a new issue with current versions if necessary.
