### ISSUE TITLE
Use https in the links in emails from LanguageTool Forum

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#795]
The URLs in email messages from [LanguageTool Forum] use http, not https. Example:
Visit Topic <http://forum.languagetool.org/t/testing-new-browser-add-on/2128/7>  to respond.

Change the URLs to https.

Reason. If you are not logged in, when you click a link and start to log in, you get a message about an insecure connection.

**Comment by danielnaber** [comment]
Should be solved, although not by changing the links (cannot find how to so that) but by redirecting to https.

**Comment by MikeUnwalla** [comment]
Thanks Daniel.
