### ISSUE TITLE
[de] Quotation mark rule doesn't work properly with the add-on

### ISSUE THREAD

**Issue by nopepper** [languagetool-org/languagetool#798]
For example:
"Hallo Welt" returns two errors https://i.imgur.com/pzqW24d.png
„Hallo Welt” likewise returns two errors https://i.imgur.com/RmyYE5V.png
„Hallo Welt“ returns no errors

The list gets cluttered quickly by small details, especially for bigger texts. I think the rule should be disabled, or at least changed

**Comment by danielnaber** [comment]
This is fixed now (but not released yet) by having these rules turned off by default.
