### ISSUE TITLE
Output correct `RuleMatch.Type` in JSON API

### ISSUE THREAD

**Issue by torik42** [languagetool-org/languagetool#7995]
The official LanguageTool server as well as local servers seem to always add
```json
    "type": {
        "typeName": "Other"
    },
```
to each match in the JSON API output. I guess, this is the property to decide on how to highlight issues in the various LanguageTool applications (the property documented [here](https://languagetool.org/development//api/org/languagetool/rules/RuleMatch.Type.html)). However, it is not correctly set in the JSON output.

The property should be set correctly, so that other tools can use them, or be removed from the JSON output.

Additional question: How does LanguageTool decide on these types? Are they based on the `rule.issueType`, and if so, where can I find the mapping?

**Comment by danielnaber** [comment]
Thanks for the report, this is fixed now in git. The `typeName` doesn't map to `issueType`, it's independent of that.

**Comment by torik42** [comment]
Thanks a lot for fixing it so fast. It works perfectly.
