### ISSUE TITLE
[DE] LT-Bugfehlermeldung

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#8014]
Moin liebes LanguageTool-Team

![grafik](https://user-images.githubusercontent.com/78316155/224510523-189d598b-60a6-4715-8d62-5095d698b871.png)

Nach langer Zeit mal wieder eine Bugfehlermeldung. Diese Meldung kam nach einem Absturz, nach einem Grafikkartentreiberupdate, in der LibreOfice am Laufen war und aus diesem Grund auch abgestürzt war. Nach dem Neustart vom LibreOffice kam diese Fehler sofort.

Grüße Dallun511

**Comment by FredKruse** [comment]
Das ist eine Fehlermeldung von LT 6.0. In LT 6.1 wird sie bereits abgefangen.

**Comment by MasterDallun511** [comment]
Gut zu wissen.
Thread wird geschlossen.
