### ISSUE TITLE
[pt] Idea for rule: “determinadas” → “específicas” – 2023-03-13

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8018]
Hello @ricardojosehlima

I have come up with an idea for scientific/academic writing:
`Estes foram criados para desempenhar determinadas funções.`

The idea is to replace “determinadas” with “específicas”.

Basically, it would look for:
`para desempenhar determinadas funções`
(para + verb + determinada(s) + noun)

By having two static words, it will help remove false positives.

Is it a good idea?
Academic/Scientific?

Thanks!

**Comment by marcoagpinto** [comment]
Ahhhh…
`para|como|por`

**Comment by ricardojosehlima** [comment]
Worth a try

**Comment by marcoagpinto** [comment]
😛

**Comment by marcoagpinto** [comment]
Ahhhh… I will work on it tonight.

**Comment by marcoagpinto** [comment]
Ricardo, I never expected it to be this simple.

One of the easiest rules to code.

But it only works with plural nouns/adjectives, otherwise the meaning is lost.

https://github.com/languagetool-org/languagetool/commit/5178d7f72f6fee7216d10fd3746363bc7ba53889

BEFORE (IT HAD SINGULAR NOUNS):
```
Portuguese (Portugal): 6 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```
[0.txt](https://github.com/languagetool-org/languagetool/files/10960732/0.txt)

AFTER (ONLY PLURAL)
```
Portuguese (Portugal): 2 total matches
Portuguese (Portugal): 582235 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[1.txt](https://github.com/languagetool-org/languagetool/files/10960739/1.txt)

Here is the rule, in the tests I had:
`<message>Num contexto formal/científico, é preferível escrever 'específica'.</message>`

I changed the gender to “específico”.


```
    <!-- PARA DESEMPENHAR DETERMINADAS FUNÇÕES para desempenhar funções específicas -->
    <rule id='CIENTÍFICO_DETERMINADAS_ESPECÍFICAS' name="[Científico] Determinados → Específicos" type="style">
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2023-03-13 (2-MAR-2023+) -->
      <!--
      Estes foram criados para desempenhar determinadas funções. → Estes foram criados para desempenhar funções específicas.
      -->
      <pattern>
        <token regexp="yes">para|como|por</token>
        <token postag='V.+' postag_regexp='yes'/>
        <marker>
          <token regexp="yes">determinad[ao]s</token>
          <token postag='AQ..P.+|NC.P.+' postag_regexp='yes'/>
        </marker>
      </pattern>
      <message>Num contexto formal/científico, é preferível escrever 'específico'.</message>
      <suggestion>\4 <match no='3' postag='AQ0(..)0' postag_replace='AQ0$10'>específico</match></suggestion>  
      <example correction="funções específicas">Estes foram criados para desempenhar <marker>determinadas funções</marker>.</example>
    </rule>
```

**Comment by susanaboatto** [comment]
Hi all,

I don't think this rule is very relevant, at least not for PT-BR. It's very much a matter of preference and it's likely very context-specific. I would disable this rule if possible. If this definitely sounds better in academic texts for PT-PT, then we should move it to that specific grammar 🤔.

**Comment by marcoagpinto** [comment]
Sure, Susana.

😋 

I am currently working on:
CONFUSION_POR_PÔR_V2

The remaining POR_PÔR rule will be merged into this one (there were two rules for the same), I am just removing the false positives.

**Comment by marcoagpinto** [comment]
@susanaboatto 

Can you move it to pt-PT?

Thanks!
