### ISSUE TITLE
Error in GermanPatternRuleTest

### ISSUE THREAD

**Issue by nopepper** [languagetool-org/languagetool#802]
An example in the "NAMENS" German XML rule makes the Maven build fail:
`java.lang.AssertionError:` 
`German rule NAMENS[1]:`
`"Ein HTML-Backend Namens Broadway."`
`Errors expected: 1`
`Errors found   : 0`
`Message: Bitte prüfen Sie, ob <suggestion>\2</suggestion> hier als Adverb gebraucht wird und daher kleingeschrieben werden muss.`

**Comment by f-knorr** [comment]
Can we close this issue as it resulted from an invalid tagging?

**Comment by nopepper** [comment]
Yes, it has been fixed.
