### ISSUE TITLE
[en] Bad suggestions for "non-dismissable"

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#8038]
If I write “dismissable”, there is a helpful spelling-suggestion, but if I write “non-dismissable”, I get this instead:

![monadismisable](https://user-images.githubusercontent.com/30999326/225132749-7a19844c-5c14-45db-9910-e9a6e828d7e2.png)

**Comment by tiff** [comment]
Fixed as part of https://github.com/languagetool-org/languagetool/commit/b1d17162eb8e6ce0bf575cc4a4a4b2a95078efbd#diff-6df4346261484d6f99757d98e23bc28f0035a80c4545b098ad401250670d999fR34478-R34480
