### ISSUE TITLE
[de] capitalization false positives

### ISSUE THREAD

**Issue by kudkuda** [languagetool-org/languagetool#8040]
Die Eidgenössische Elektrizitätskommission (ElCom)
Bearbeitung des Grimmschen Märchens
die Grundidee vom Fairen Handel vermitteln
Sendung «RTL Aktuell»
das Eidgenössische Schützenfest 2020
die Zweiten Spanischen Republik
das Projekt „Quartier Weil“
das größte Mogelpaket der Zweiten Republik
Das Internationale Herbstlager
Verband Österreichischer Nachwuchsleistungssportmodelle (VÖN)
Das Blaue Sofa ist das bekannteste Möbel der deutschen Literaturszene
auf dem Kahlen Asten
die Untere Naturschutzbehörde sowie die Untere Jagdbehörde
vom Obersten Rat
die Untere Verkehrsbehörde
MotoGP-Weltmeister Joan Mir
Andreseck bringt Alltagsanekdoten zu Papier, gern auch Politisches, und präsentiert die Ergebnisse der Gruppe.
An der Landwirtschaftlichen Fachschule Norbertinum
Am Sonntagnachmittag mit 130 am Mittleren Graben
der stellvertretende Nationale Sicherheitsberater 
auf der Straße Am Beutlerpark.
von den Selber Wölfen nachverpflichtet
Daniel Craigs finaler Bond-Film Keine Zeit zu sterben
Wenn Sie Strg+Umschalt+I drücken
(zweimal Umschalt)

**Comment by tiff** [comment]
Behoben via https://github.com/languagetool-org/languagetool/commit/67fb8c86f08c5a09c87f6df2deb24d29fd6d7750
