### ISSUE TITLE
[En] proposed new rule

### ISSUE THREAD

**Issue by bhuvangu** [languagetool-org/languagetool#805]
Incorrect : I myself will do it
correct: I will do it

**Comment by f-knorr** [comment]
According to https://english.stackexchange.com/questions/124786/is-it-correct-to-say-i-myself and https://www.usingenglish.com/forum/threads/78427-When-to-use-I-myself both sentences are correct.

**Comment by bhuvangu** [comment]
Ok thanks.. i will consult 3-4 source on internet before bring it up

**Comment by MikeUnwalla** [comment]
@bhuvangu , this is a good rule for the 'plain English' category, so I added it (https://github.com/languagetool-org/languagetool/commit/715fe6b1572f96e7c1a23eeea84710aa32cfede4). Thanks for the suggestion.
