### ISSUE TITLE
[de] obliegt des dem Auftragnehmer nachzuweisen...

### ISSUE THREAD

**Issue by orschiro** [languagetool-org/languagetool#806]
Hey all, 

Just found this problem:

> Im Fall der Verweigerung der Abnahme, obliegt des dem Auftragnehmer nachzuweisen, dass kein Mangel vorlag.

It doesn't find an error but I think "obliegt des dem" should be "obliegt es dem":

![image](https://user-images.githubusercontent.com/170947/31020023-fe9f9ad4-a531-11e7-821e-9cccd7c4d92f.png)

**Comment by f-knorr** [comment]
I have written an error detection rule for the reported problem. Unfortunately, I did not find a more generic solution ("des dem" might be correct: "Die Rede des dem Königshaus angehörenden Vertreters wurde begeistert aufgenommen.")

**Comment by orschiro** [comment]
Thank you, @f-knorr!
