### ISSUE TITLE
[pt] Rule to be moved to pt-pt only - or removed at all?

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#8072]
![Captura de tela de 2023-03-17 12-15-49](https://user-images.githubusercontent.com/36453534/225946324-e41a05bb-f33b-41a9-855e-76ec87e8f8ef.png)
Hi,
   The rule in the attached file does not apply to pt-br. It's one of those urban legends that gained popularity but under scrutiny by linguists, it has been shown that there is not anywhere a ban on not making the contraction in this structure, where the subject of a verb in the infinitve is introduced by the contraction ("Eu gosto do menino ser como é", "A necessidade do país se desenvolver é urgente")

**Comment by marcoagpinto** [comment]
@susanaboatto 

Can you move it to pt-PT?

Thanks!

**Comment by marcoagpinto** [comment]
@susanaboatto 

If you are certain that it is also not usable in pt-PT, could you remove it?

Thanks!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

It is done!

I moved it to pt-PT and disabled it.

Thanks!

https://github.com/languagetool-org/languagetool/commit/d06a340415b4a589446af68f66342d6267f12900

https://github.com/languagetool-org/languagetool/commit/175a7372153f849ba72b8e8647980c6d6f8e4dea
