### ISSUE TITLE
wrong position in VerbAgreementRule

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#809]
Repoduce with `Ihr könnt das Training abbrechen, weil es nichts bringen wird. Er geht los und sagt dabei: Werde ich machen.` -> "Er geht lo" is underlined

Source: https://forum.languagetool.org/t/de-bug-oder-eigenartiger-fehler/2193

**Comment by danielnaber** [comment]
Maybe @f-knorr can have a look, I think this is related to your change from 2017-20-07. We probably need more multi-sentence test cases.

**Comment by f-knorr** [comment]
Yes, that was indeed my fault. Sorry! I have fixed it and added another test.
