### ISSUE TITLE
[LibreOffice] LanguageTool Server Settings - 2023-03-21

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8094]
Hello @danielnaber @tiff and core developers:

I was looking at:
https://languagetool.org/insights/post/product-libreoffice/#how-to-enable-languagetool-on-libreoffice

It is too hard to use.

I always come up with easier solutions for the tasks (UX - User Experience).

The regular user should always use the things “out of the box”, simple and clear.

What if instead of the current GUI, we could use my suggested one?:

![LibreOffice_LT_server_settings_20230321](https://user-images.githubusercontent.com/5192600/226579509-89907f14-e5fc-4c29-b6dd-4f1e1b6fe600.png)

**Comment by danielnaber** [comment]
This dialog has been developed by LibreOffice, not by us. Feel free to open an issue over there.

**Comment by marcoagpinto** [comment]
Ahhhhhh... thanks, Daniel!

**Comment by marcoagpinto** [comment]
https://bugs.documentfoundation.org/show_bug.cgi?id=154306

Done!
