### ISSUE TITLE
[en] LT does not support vertical tab

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#8106]
The vertical tab `\n` isn't treated like white space in LT:

In this screenshot, there's a vertical tab between "test" and "with".

<img width="519" alt="Bildschirm­foto 2023-03-22 um 11 09 41" src="https://user-images.githubusercontent.com/37363/226870935-fd9f7358-dd1d-46e7-a209-d0deb1cc3ffa.png">

```
I'm a cool testwith a line
```

@jaumeortola I guess this also affects other languages. I don't remember the file where such token delimiter are defined. Could you check if this can be easily solved?

**Comment by MikeUnwalla** [comment]
And if you have the time, please make it possible for a grammar rule to find any Unicode character (https://github.com/languagetool-org/languagetool/issues/1755).
