### ISSUE TITLE
Duplicate TokenPredicate and TokenExpressionFactory in german and russian module

### ISSUE THREAD

**Issue by I-Al-Istannen** [languagetool-org/languagetool#8127]
Hey, 

when running jacoco on this project it kept complaining about a duplicate class file for `org/languagetool/chunking/TokenPredicate.class`. It seems like this was copied over in [837a67e](https://github.com/languagetool-org/languagetool/commit/837a67e510451e3ef022773971172df86cdecd83). Later on the version in `de` was refactored by [#5945](https://github.com/languagetool-org/languagetool/pull/5945) so now the two representations have diverged, but still remain functionally identical. 

Depending on the order you load the two language modules (or shade them), different versions of `TokenPredicate` will be loaded by the JVM. Currently they behave essentially the same so that's fine, but in the future this might lead to differing behaviour in some circumstances.

The problem also applies to the TokenExpressionFactory, but this file is identical so the classes actually match.

Shouldn't one (or both) of them be renamed or moved to a different package? What am I missing here?

Enjoy your day!

**Comment by yakovru** [comment]
@danielnaber,
I think it is necessary to move TokenExpressionFactory and TokenPredicate to languagetool-core.
I will try to do this after the LT 6.1 release.
