### ISSUE TITLE
[pt] Remove a rule for pt-br?

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#8131]
![Captura de tela de 2023-03-24 18-41-01](https://user-images.githubusercontent.com/36453534/227646659-2224968a-167f-4cfe-8956-b8d43644324c.png)
The rule presented in the attached file works for pt-PT only, as it's indicated in the link where the rule is explained, and as usually we use in pt-BR 06 de abril.

**Comment by marcoagpinto** [comment]
Done!

https://github.com/languagetool-org/languagetool/commit/a2ced4fe0060c7d7f19582b697e3affd47f80b59

https://github.com/languagetool-org/languagetool/commit/6b6a8b0ac5ac8e0bd0d7cab3a9b3fe662b51ae18

Thanks!
