### ISSUE TITLE
[pt] Bug in adding word to dictionary?

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#8137]
![Captura de tela de 2023-03-27 16-34-57](https://user-images.githubusercontent.com/36453534/228047954-8424ce15-0179-4e71-bd33-244809116089.png)
Hi, contrary to all other words that I add to the dictionary, "recodificação" seems to be resistent: I add it, and then when I open the file again, LT flags it as non-existent.
I'm using the online premium version on Chrome, Ubuntu 22.04

**Comment by marcoagpinto** [comment]
Hello Ricardo,

This is the best I can do:
https://github.com/languagetool-org/languagetool/commit/faeab02ad0482f4cadbaefe844a747cab144030a

https://github.com/languagetool-org/languagetool/commit/235090cfe6ba43237c999d38bf32257fda554886

😛

**Comment by ricardojosehlima** [comment]
It works! Thanks

**Comment by marcoagpinto** [comment]
“Resistance is futile, the Universe shall bend!”

❤️ ❤️ ❤️ ❤️ ❤️ ❤️
