### ISSUE TITLE
TESTRULES PT doesn't work in snapshot 6.2

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8146]
Hello!

I have downloaded and unzipped the latest nightly, and when I type `TESTRULES PT` I get:

```
Error: Could not find or load main class org.languagetool.rules.patterns.PatternRuleTest
Error: Could not find or load main class org.languagetool.tagging.disambiguation.rules.DisambiguationRuleTest
Error: Could not find or load main class org.languagetool.rules.bitext.BitextPatternRuleTest
Error: Could not find or load main class org.languagetool.ValidateFalseFriendsXmlTest
```

Thanks!

**Comment by marcoagpinto** [comment]
Ahhh… I tried with a version from two days ago and the same happens, so I went back to the one I had from last month.

**Comment by SteVio89** [comment]
fixed by https://github.com/languagetool-org/languagetool/commit/ac0720eabde3dc15217e041c6f4fe17976fcf633
