### ISSUE TITLE
Misleading tense detection in German sentence

### ISSUE THREAD

**Issue by jo-so** [languagetool-org/languagetool#8148]
> Besorge Dir Stoff für heute, damit es nicht wieder so eine Hängepartie wie gestern **wird**.

In this sentence LanguageTool gets misled and suggests about »wird«:

> Falsche Zeitform? Meinten Sie „wurde“?

**Comment by tiff** [comment]
Hiermit behoben: https://github.com/languagetool-org/languagetool/commit/2a410d9dbf06e7d298b81ed0e303dc77f28ddca0#diff-33536d0dcaec8db0ad537c4177eaa7045006e4a0e25c4f54fc2daf70f3d00262R26694
