### ISSUE TITLE
[ru] При необходимости,

### ISSUE THREAD

**Issue by TristisOris** [languagetool-org/languagetool#8152]
ff, 6.2.5.
исходный: При необходимости, руководитель проекта может добавить в проект других участников
предлагает: При необходимости, **руководителе** проекта может добавить в проект других участников
после исправления предлагает еще: При необходимости, **руководителе проекте** может добавить в проект других участников

Если убрать запятую, то все ок. И еще тоже самое с этой структурой.

исходный: при необходимости, укажите количество исследованных образцов
предлагает: при необходимости, укажите **количестве** исследованных образцов

исходный: Что позволяет просмотреть только что созданную заявку, и при необходимости, внести исправления.
предлагает: _да вообще все подряд предлагает. тут он совсем сломался._
```
Требуется предложный падеж
Предлог «при» предполагает употребление существительного в предложном падеже: «при необходимости, внести исправлении», «при необходимости, внести исправлениях», «при необходимости, внести исправленье», «при необходимости, внести исправленьях»
```

И из той же оперы (кстати он не понял что делать с "тойже" - `тоже тойбе тойли тойни тойве`)

исходный: При условии, обнаружения несоответствия правилам подачи, укажите комментарий 
предлагает:
```
Требуется предложный падеж
Предлог «при» предполагает употребление существительного в предложном падеже: «При условии, обнаружении», «При условии, обнаружениях», «При условии, обнаруженье», «При условии, обнаруженьях»
```

**Comment by yakovru** [comment]
Исправлено.
