### ISSUE TITLE
Replacing contractions

### ISSUE THREAD

**Issue by smckenna7** [languagetool-org/languagetool#817]
When replacing a contraction word like "doesn't" with a suggestion like "do" we end up with "do't"

For example..
"What will I doesn't"
breaks the rule NON3PRS_VERB and suggests we replace with the word "do" which, when inserted becomes.
"What will I do't"

The root of this problem is probably down to the tokenizer splitting on apostrophes, which can be tested at https://community.languagetool.org/analysis/analyzeText

**Comment by MikeUnwalla** [comment]
Refer to my comment in https://forum.languagetool.org/t/replacing-contractions-bug/2234/1.
