### ISSUE TITLE
[pt] A rule to be deleted!?

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#8170]
![Captura de tela de 2023-03-31 13-52-57](https://user-images.githubusercontent.com/36453534/229182503-364affb0-b55b-4ab3-aab0-02ec2f75f075.png)
Considering that using the verb "passo" is much more frequent than using the word "paço" and that the rule doesn't even a situation where there is a "eu" before, which would clearly mean that what follows is the verb as in the attached file, I vote for deleting this rule from LT.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Heya,

I can't reproduce it.

What is the sentence?

“E assim eu passo.” doesn't trigger the rule.

Thanks!

**Comment by ricardojosehlima** [comment]
Sorry...
It was an excerpt, but now I see that it was truncated: "São essas unidades o nosso: eu passo".

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I can't find the rule in the grammar.xml:
PORTUGUESE_WRONG_WORD_IN_CONTEXT

Maybe it is a Java rule?

@susanaboatto can you find it? Thanks!

**Comment by yakovru** [comment]
https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/wrongWordInContext.txt   - rules for Java rule PORTUGUESE_WRONG_WORD_IN_CONTEXT

**Comment by marcoagpinto** [comment]
@yakovru 

Hi!

Thank you!

I will look at it tomorrow.

**Comment by marcoagpinto** [comment]
Heya,

I have just looked at the file and I don't know how it works.

@ricardojosehlima 
It is better to leave it for @susanaboatto on Monday.
