### ISSUE TITLE
[de] Abbreviated surnames

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#818]
At the moment abbreviated surnames are not recognized by the POS tagger. It would be great if this could be changed by somebody who does know how. The idea is something like that:

```
Token 1: EIG:.*:VOR
Token 2: Single uppercase letter
Token 3: PKT
```

In that case Token 2 should be tagged like a surname but with "ABK" as part of the tag. This could be helpful for some rules, e.g. for creating an antipattern in ZEICHENSETZUNG_DIREKTE_REDE [1].

**Comment by janschreiber** [comment]
I think this can be done in disambiguation.xml.

**Comment by f-knorr** [comment]
So "C" in the following example should be tagged as EIG:NOM:SIN:MAS:NOA:NAC:ABK ?
token1 = Franz (EIG:NOM:SIN:MAS:ART:VOR)
token2 = C
token3 = . (PKT)

**Comment by Discostu36** [comment]
Something like that, yes.

**Comment by janschreiber** [comment]
We need a way to make sure that the W in "George W. Bush" is not tagged as NAC, though. Looks tricky.

**Comment by Discostu36** [comment]
Good point.

**Comment by f-knorr** [comment]
If it's all about creating antipatterns for rules, why can't we do this with postag="UNKNOWN"?

**Comment by Discostu36** [comment]
Sure it's possible to write antipatterns without the tag. I just thought it might make some things easier. But as I see no good way to circumvent the problem of abbreviated middle names, this maybe wasn't a good idea.

**Comment by janschreiber** [comment]
> But as I see no good way to circumvent the problem of abbreviated middle names, this maybe wasn't a good idea.
Closing this because there is no clear fix for now and the issue seems a bit vague. Feel free to reopen this if you think it is important.
