### ISSUE TITLE
[pt] Repeated postags - 2023-04-03

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8187]
Hello @susanaboatto @jaumeortola 

I have been noticing tons of repeated postags, can't a script be created to automatically remove all repeated ones?

Thanks!

`Se acha que alguma função pode ser adicionada ou deseja reportar um erro, por favor visite o website phpBB Area51, onde você encontrar...`

![Screenshot 2023-04-03 at 19-18-54 Análise de Texto - LanguageTool](https://user-images.githubusercontent.com/5192600/229594435-90cc47ba-201a-4422-a090-cf2ae77761b3.png)

**Comment by jaumeortola** [comment]
There are many duplicates in added.txt (more than 10,000). I don't know why. We need to de-duplicate this file.

**Comment by marcoagpinto** [comment]
@jaumeortola @susanaboatto 

Is this it?:
[added_dupes_removed_20230404.txt](https://github.com/languagetool-org/languagetool/files/11148112/added_dupes_removed_20230404.txt)

![dupes_removed_20230404](https://user-images.githubusercontent.com/5192600/229782891-d2ce693f-528a-4136-b0f7-3106e07eb982.png)

**Comment by jaumeortola** [comment]
> Is this it?

Yes, that's it.

**Comment by marcoagpinto** [comment]
@jaumeortola 

May I commit it?

@susanaboatto  had assigned the task to herself.

**Comment by jaumeortola** [comment]
> May I commit it?

It seems safe. Just run the tests as usual.
