### ISSUE TITLE
Suggestion: auto-detect language for quotes

### ISSUE THREAD

**Issue by nopepper** [languagetool-org/languagetool#819]
It is often the case that some text will contain quotes written in another language. This raises lots of errors and clogs the error list so that looking for legitimate errors can become frustrating. I suggest that all text found between two quotation marks be either skipped or analyzed and checked in its original language.

**Comment by Discostu36** [comment]
I don't think it should be skipped, but I like the idea of a separate language detection for quotes.

**Comment by janschreiber** [comment]
"I suggest that all text found between two quotation marks be either skipped or analyzed and checked in its original language."
The problem I see here is that in scientific texts, long quotes usually are block quotes that don't have quote marks. For the LO plugin, what we really want IMO is a way to detect quotations that doesn't rely on quote marks.

**Comment by Discostu36** [comment]
Maybe LT should chose another language for a paragraph as soon as more than 50 % of the words a spelling mistakes (or something like that).

**Comment by Ablesius** [comment]
How would you find out which language is used in the quote?

**Comment by nopepper** [comment]
Languagetool already has a way to automatically detect languages, I think
that could come in handy.

**Comment by danielnaber** [comment]
Closing, mostly a duplicate #766
