### ISSUE TITLE
[pt] Idea for rule: “Quando temos de V_INF” → “Ao V_INF” - 2023-04-05

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8198]
Hello @ricardojosehlima

What about this idea:
`Quando temos de lidar com muitos elementos.`
to
`Ao lidar com muitos elementos.`
?

I am almost sure it is “lidarmos” and not “lidar” though 😄 

Thanks!

**Comment by maphjo** [comment]
@marcoagpinto: Dear Marco, when you create an issue, could you please also add the label "Portuguese" to it? 
Thank you! :heart:

**Comment by marcoagpinto** [comment]
@maphjo 

Ahhhhh… sorry… I will do it.

**Comment by ricardojosehlima** [comment]
Hi, sounds good. Will be on holiday from tomorrow on, will be back only on Monday.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Happy Easter!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

0 hits in 600 000 sentences:
https://github.com/languagetool-org/languagetool/commit/900d48859880cb8eb26710c70275c9e6caa25dc4


```
    <!-- QUANDO TEMOS DE LIDAR ao lidarmos -->
    <rule id='QUANDO_TER_DE_QUE_VINF_AO_VINF' name="[Simplificar] 'Quando V.Ter de/que V.Inf.' com → 'Ao V.Inf.'" type="style" default="temp_off">
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2023-04-10 (2-MAR-2023+) -->
      <!--
      Quando tenho de lidar com muitos elementos. → Ao lidar com muitos elementos.
      Quando temos de lidar com muitos elementos. → Ao lidarmos com muitos elementos.
      -->
      <pattern>
        <marker>
          <token>quando</token>
          <and>
            <token inflected='yes'>ter</token>
            <token postag='VMIP.+' postag_regexp='yes'/>
          </and>
          <token regexp="yes">de|que</token>
          <token postag='VMN0000' postag_regexp='no'/>
        </marker>
        <token>com</token>
      </pattern>
      <filter class="org.languagetool.rules.pt.AdvancedSynthesizerFilter" args="lemmaFrom:4 lemmaSelect:V.* postagFrom:2 postagSelect:VMIP(.)(.).* postagReplace:VMN0[\b1][\b2].*"/>
      <message>Esta perífrase poderá ser simplificada.</message>
      <suggestion>ao {suggestion}</suggestion>
      <example correction="Ao lidar"><marker>Quando tenho de lidar</marker> com muitos elementos.</example>
      <example correction="Ao lidarmos"><marker>Quando temos de lidar</marker> com muitos elementos.</example>
    </rule>
```

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

I wanted to create a subrule for uses without “com”, basically “DA.+” (a(s) and (o)(s)) and NC.+ (nouns), but I am not sure if replacing is valid.

I noticed that if “quando” appears at the start of a sentence, using DA.+ and NC.+ to replace “com” doesn't sound well.

Here is what I have:
[0.txt](https://github.com/languagetool-org/languagetool/files/11188753/0.txt)

If you believe that the meaning isn't lost, I will enhance the rule.

Thanks!

**Comment by ricardojosehlima** [comment]
Hi,
  in some sentences, "ter que" is very different from "ao....":
Rita fica insegura quando tem que falar alemão.
Rita fica insegura ao falar alemão.
  In the first, her insecurity comes from a forced situation; in the second, it looks that whenever she speaks German, she is insecure.
  And that happens with many other sentences in the list...

**Comment by marcoagpinto** [comment]
Ahhhh… so, it is better to stay only with “com” even if it has 0 hits in 600 000 sentences, right?

😋
