### ISSUE TITLE
[pt] Verbal nouns (disambiguator) - 2023-04-11

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8212]
Hello @jaumeortola @susanaboatto @maphjo 

Look at the sentence:
`Propomos o desenvolvimento de um software de gestão.`

“desenvolvimento” appears as: NCMS000

But it is a verbal noun:
https://dicionario.priberam.org/desenvolvimento

If the disambiguator could start accepting them, it would be possible to create more powerful rules.

In this example, “desenvolvimento” could appear as:
NCMS000
VNCMS000
(with a “V” before the “N”) to state it is a noun (NCMS000) and a verbal noun (VNCMS000).

Thanks!

**Comment by jaumeortola** [comment]
Changing the tag set is not viable. You would need to change hundreds of rules. 

You could create a file text with the correspondences: 
```
desenvolvimento=desenvolver
envolvimento=envolver
...
```
And then we could create a filter to use these correspondences. Anyway, before doing this work, we need some proof that the resulting rules will be useful.
