### ISSUE TITLE
[de] Gendergap is not supported

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#822]
Writing texts with [Gendergaps](https://de.wikipedia.org/wiki/Gendergap_(Linguistik)) is not supported by LanguageTool. A word like "Bürger_innen" doesn't lead to mistakes but is not correctly recognized by the tagger. The alternative form "Bürger*innen" is treated like two words and leads to errors. 

I think there are two possibilities: Either delete the gap and join the word. So it is just treated like "Bürgerinnen". Or, more in line with the idea behind the Gendergap, tag the words as a separate form of the lemma "Bürger" but tag it without a gender. 

Well, I guess a third possibility is to keep everything as it is because Gendergaps are not really following German orthography and grammar rules. But there are many contexts in which this is used frequently and LanguageTool should acknowledge that.

**Comment by janschreiber** [comment]
> But there are many contexts in which this is used frequently and LanguageTool should acknowledge that.

I agree.

**Comment by GiantCrocodile** [comment]
I think this is hard to support as there are more than 10 common styles.

**Comment by danielnaber** [comment]
Closing here in favor of #2417
