### ISSUE TITLE
[pt?] Issues between lower and upper case words in spelling.txt

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8221]
@jaumeortola @susanaboatto @maphjo 

Hello!

I am uncertain if this happens only with PT or also with other languages.

It has happened before that if I insert a word in lowercase in spelling.txt, it appears as a typo in the browser add-on if I write it capitalised:

![upper_lower_issue_20230411](https://user-images.githubusercontent.com/5192600/231265193-163771a7-877d-4944-8fa2-6556d18ac6d3.png)

**Comment by baarsrj** [comment]
Spelling.txt is case sensitive.
