### ISSUE TITLE
[pt] Idea for rule: “conforme ia revendo” → “ao rever” - 2023-04-13

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8232]
Heya, @ricardojosehlima

I came up with an idea to simplify the text.

Please take a look at:
`O Marco, CONFORME IA REVENDO o texto da tese, melhorava a gramática.`
TO:
`O Marco, AO REVER o texto da tese, melhorava a gramática.`

“conforme” + “ia(m)” + V.Gerund → "ao" + V.Infinitive.

Is it a good idea?

Thanks!

**Comment by marcoagpinto** [comment]
or maybe:
→ “conforme revia”
(remove the “ia(m)” and change verb)

**Comment by ricardojosehlima** [comment]
Hi, I prefer the second suggestion. It's worth a try.

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

My dear brother, I prefer the second suggestion too, but I had to ask to be certain.

We have a plan!

I will work on it in a few hours.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ 

Thanks!

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

While I was sleeping, I was thinking and came up with an idea:
```
Conforme LHE ia escrevendo.
Conforme SE ia escrevendo.
```
etc.

So, we can enhance the rule, right?

Thanks!

**Comment by marcoagpinto** [comment]
Ahhhh… sorry… I will work on it soon.

Meanwhile, I came up with more ideas for rules.

😋

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Very easy to make:
https://github.com/languagetool-org/languagetool/commit/95889b8e9c1b0573b356ec33097d03338f45e8da

It still only shows the hit of the previous version.

This improved rule looks like this:

```

    <!-- CONFORME IA REVENDO conforme revia -->
    <rule id='CONFORME_IA_IAM_GERUNDIO_CONFORME_PASSADO' name="[Simplificar] Conforme 'ia(m) + V.Gerúndio' → 'V.Passado.'" type="style" default='on'>
      <!-- Created by Marco A.G.Pinto with Ricardo Joseh Lima suggestions, Portuguese rule 2023-04-13/14 (2-MAR-2023+) -->
      <!--
      O Marco, conforme ia revendo o texto da tese, melhorava a gramática. → O Marco, conforme revia o texto da tese, melhorava a gramática.
      Os Marcos, conforme iam revendo o texto da tese, melhoravam a gramática. → Os Marcos, conforme reviam o texto da tese, melhoravam a gramática.
      -->
      <pattern>
        <token>conforme</token>
        <token min="0" max="1" regexp='yes'>&pronomes_obliquos;</token>
        <marker>
          <token inflected='yes'>ir
            <exception inflected='yes'>ser</exception>
          </token>
          <token postag='VMG0000' postag_regexp='no'/>
        </marker>
      </pattern>
      <filter class="org.languagetool.rules.pt.AdvancedSynthesizerFilter" args="lemmaFrom:marker1 lemmaSelect:V.* postagFrom:marker postagSelect:V.*"/>
      <message>Esta perífrase poderá ser simplificada.</message>
      <suggestion>{suggestion}</suggestion>
      <example correction="revia">O Marco, conforme <marker>ia revendo</marker> o texto da tese, melhorava a gramática.</example>
      <example correction="reviam">Os Marcos, conforme <marker>iam revendo</marker> o texto da tese, melhoravam a gramática.</example>
    </rule>

```

Basically, I added the `min="0" max="1"` line and changed the filter positions.

Thanks!
