### ISSUE TITLE
[de] Erkennung Eides Statt

### ISSUE THREAD

**Issue by GiantCrocodile** [languagetool-org/languagetool#825]
Die Versicherung an Eides Statt sollte erkannt werden. Momentan wird "Statt" blau markiert, weil es mitten im Satz groß geschrieben wird.

**Comment by janschreiber** [comment]
Eine oberflächliche Recherche (Google) deutet darauf hin, dass die Kleinschreibung korrekt ist.

**Comment by Discostu36** [comment]
Ja, wird laut Duden klein geschrieben.

https://www.duden.de/node/661917/revisions/1391586/view

**Comment by GiantCrocodile** [comment]
Stimmt, da bin ich selbst auf oberflächliche Ergebnisse meiner Recherche reingefallen. Danke für die Prüfung!
