### ISSUE TITLE
[pt] Idea for PhD thesis rule: Use periphrases in the affirmative - 2023-04-15

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8259]
Hello @ricardojosehlima

Basically, the idea for the rule is:
```
O que pretendemos saber é a equação da reta. → O objetivo é saber a equação da reta.
O que pretendemos saber são as equações da reta. → O objetivo é saber as equações da reta.

O problema que pretendemos resolver é a equação da reta. → O problema é resolver a equação da reta.
O problema que pretendemos resolver são as equações da reta. → O problema é resolver as equações da reta.
```

Is it a good plan?

I guess the rule will be very limited, but it is better to have it than not having it, I believe.

Do you have any ideas for special verbs and such?

Thanks!

**Comment by marcoagpinto** [comment]
@ricardojosehlima

I changed the examples:
```
SUBRULE 1:
O que pretendemos saber é a equação da reta. → O objetivo é saber a equação da reta.
O que pretendemos saber são as equações da reta. → Os objetivos são saber as equações da reta.

SUBRULE 2:
O problema que pretendemos resolver é a equação da reta. → O problema é resolver a equação da reta.
Os problemas que pretendemos resolver são as equações da reta. → Os problemas são resolver as equações da reta.
```

**Comment by ricardojosehlima** [comment]
Hi, for the first pair yes, but in the second I feel that something is lost in the meaning.

**Comment by marcoagpinto** [comment]
Thank you, I will work on it tonight.

LanguageTool now has a styles.xml, and I will download the stand-alone + Wikipedia tool tonight to have the new structure.

😋

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Dear brother,

I have committed the rule:
https://github.com/languagetool-org/languagetool/commit/5ad827f88491d984c81d6f1121140fa780c3978e
https://github.com/languagetool-org/languagetool/commit/32bffba23a4f5fef6fa9f87e0e557fba79e9936e (fix in rule name)

It had 0 hits in 600 000 sentences.

Thanks!

🤗 ❤️ 😋 😛
