### ISSUE TITLE
Github vulnerability warning

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#8260]
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
remote: 
remote: GitHub found 1 vulnerability on languagetool-org/languagetool's default branch (1 high). To find out more, visit:
remote:      https://github.com/languagetool-org/languagetool/security/dependabot/1
remote:

**Comment by danielnaber** [comment]
fixed with https://github.com/languagetool-org/languagetool/commit/c0f94d3e0a29971d33d2d0dab4714a2d8f4e9dfe
