### ISSUE TITLE
[en] “now-a-day” doesn't trigger LT - 2023-04-17

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8266]
It doesn't detect that it must end in plural:

`I have been doing this now-a-day.`

Thanks!

**Comment by BrianH824** [comment]
"Now-a-days" isn't proper usage. However, "nowaday" corrects to "nowadays" as expected. Perhaps there should be rules added to correct "now-a-day" and "now-a-days" to nowadays?

**Comment by BrianH824** [comment]
I created  #8413  to address this issue.
