### ISSUE TITLE
Menu in lower right corner on Firefox extension interfers with other tools

### ISSUE THREAD

**Issue by jeblad** [languagetool-org/languagetool#827]
This tool has an extension for Firefox, and that extension creates problems. It is the same developer, so I poste the issue here. 

The lower right corner in text fields are overpopulated and the extensions menu is one of them. The corner is also used for a lot of tools on various sites, and this extension makes them unavailable.

One example is the smileys on Twitter, but there are other sites with similar tool menus.

The input methods (IME) used by Wikimedia among others solves the problem by scrolling the menu in and out of view.

**Comment by danielnaber** [comment]
It's a known issue documented at https://github.com/languagetool-org/languagetool-browser-addon/issues/178, so I'm closing this report.

**Comment by danielnaber** [comment]
It's fixed for twitter and will be part of the next release. If you have more examples, please send them including screenshot, so they can be fixed, too.
