### ISSUE TITLE
Sampling methods

### ISSUE THREAD

**Issue by PavanLuca** [languagetool-org/languagetool#8273]
Undersampling, subsampling, downsampling and upsampling are all detected as wrong but I see them everywhere as a unique word. So then LanguageTool proposes them with a space between each of the 2 words that form them.

**Comment by marcoagpinto** [comment]
In the British dictionary, they are there:
https://proofingtoolgui.org/wordlist_marcoagpinto_20230401_270889w.txt

**Comment by tiff** [comment]
Fixed here https://github.com/languagetool-org/languagetool/commit/1b0acc213d147f70d299468da495a128f2274aa2#diff-6df4346261484d6f99757d98e23bc28f0035a80c4545b098ad401250670d999fR34588-R34603
