### ISSUE TITLE
[de] no (good) suggestions for misspellings of 'protokollieren'

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool#829]
The German spell checker does not make the expected suggestions for the following misspellings (and probably others):

- protokolieren
- protokullieren
- protokoliert
- protokollliert

Minor issue, but quite unexpected.

**Comment by InnovativeInventor** [comment]
I don't know German, but it seems like it is a word.

https://en.wiktionary.org/wiki/protokollieren

**Comment by janschreiber** [comment]
Thanks for the comment. Of course it is a word, but 'protokullieren' isn't. That's the whole point.

**Comment by plumaj** [comment]
It does also not make the expected suggestion for "Duzende" (i.e. "Dutzende") when it is placed at the beginning of a sentence.

**Comment by danielnaber** [comment]
Dupe of #993
