### ISSUE TITLE
[all] handle cases where space is missing in suggestion

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#8297]
From time to time, I stumble upon cases where the suggestion does not have a leading white space:

https://user-images.githubusercontent.com/37363/233324164-3cbc14a3-0693-47d2-a358-02a58a726df3.mov

I wonder if we can fix this generally for all by just having a post-processor that adds this space.

If the character before the match is a letter and the suggestion starts with a letter, then I think we can safely add a space (at least in English and German I don't see any issues).

What do you think @jaumeortola ?

Example sentence:
> We'll otherwise might miss a real dependency issue down the road.

**Comment by tiff** [comment]
Another case:
> Whatever their needs, we doesn't never disappoint they.

**Comment by jaumeortola** [comment]
These two cases in English are solved. 

Different languages may need slightly different solutions (e.g. contractions in fr, es, ca). I will add a new method per language when needed.

**Comment by jaumeortola** [comment]
In some cases, a white space is added for no reason at all. See: https://internal1.languagetool.org/regression-tests/via-http/2023-05-06/en-US/result_grammar_DASH_RULE%5B3%5D.html
I don't know if that happens in production. It seems that sometimes the values of getFromPos() and getToPos() are messed up. Sometimes they refer to the sentence, but sometimes to the whole text. Is there a completely safe way to get the underlined error string in a RuleMatch? @danielnaber 

The problem in EN_CONSISTENT_APOS (temp_off) will be fixed. https://internal1.languagetool.org/regression-tests/via-http/2023-05-06/en-US/result_java_EN_CONSISTENT_APOS.html

**Comment by tiff** [comment]
@jaumeortola thanks. I had a brief look. This seems incorrect: 
https://regression.languagetoolplus.com/via-http/2023-05-06/en-US/result_style-premium_RUN_ON%5B1%5D.html

**Comment by tiff** [comment]
I don't quite understand why it wants to add a space here:
https://regression.languagetoolplus.com/via-http/2023-05-06/en-US/result_style-premium_PRP_OWN%5B1%5D.html

Is it possible that there's an invisible Unicode character?

**Comment by jaumeortola** [comment]
All the problems are related to my previous comment. I am trying to recover the original error string when the positions have been already changed (instead of the position from the sentence start, we have the positions from the start of the text). 

I found a solution (for non-text-level rules). Anyway, the position fields are a bit confusing in RuleMatch.

**Comment by jaumeortola** [comment]
All problems seem to be fixed in today's diffs. For example: https://regression.languagetoolplus.com/via-http/2023-05-07/en-US/result_style-premium_PRP_OWN[1].html
