### ISSUE TITLE
[pt] Strange suggestion(s) on enumeration

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#8303]
The sentence, used in Google Docs, is "A apresentação pode ser tanto um como outro formato, ou ainda outro que possa ser sugerido." 

I guess that the comma followed by "ou" is triggering the rule.

Anyway, the suggestion seems strange to me. I've seen other cases of enumeration in which the suggestion also didn't make much sense.

![Captura de tela de 2023-04-20 15-11-09](https://user-images.githubusercontent.com/36453534/233452733-07f9d27a-104c-4c1d-ab09-a28f39ec7481.png)

**Comment by marcoagpinto** [comment]
@susanaboatto knows how to fix the comma issues 😄
