### ISSUE TITLE
Ignore Emojis

### ISSUE THREAD

**Issue by freddie-freeloader** [languagetool-org/languagetool#831]
Hey!

If I write text that includes emojis in other languages than English, they get rejected by LanguageTool.

Is there a way to configure a regex, for sequences that should be ignored by the spellchecker? :slightly_smiling_face:

**Comment by MikeUnwalla** [comment]
@freddie-freeloader , refer to http://wiki.languagetool.org/hunspell-support and http://wiki.languagetool.org/developing-a-disambiguator#toc11.

**Comment by f-knorr** [comment]
I do not understand the problem. Yesterday I fixed a problem regarding the offset of errors when the text contained emojis. (github issue #842). These emojis, however, are ignored by the spell checker. So what exactly is the problem?

**Comment by freddie-freeloader** [comment]
When you use Emojis for e.g. GitHub, you might add them by using `:slight_smile:`.

That's why I asked, whether one could define parts of text by using for example a regular expression (`:.*?:`).

This would also be awesome, when you are including code snippets in your posts. :smiley:
