### ISSUE TITLE
[FR] infinitif après "il faut"

### ISSUE THREAD

**Issue by setop** [languagetool-org/languagetool#832]
Test : "Il faut le fermé."
LanguageTool ne trouve aucune erreur.
Alors que la grammaire correcte est "Il faut le fermer", avec un infinitif.
Remarque, l'erreur "Il faut fermé", sans le pronom, est correctement détecte.

**Comment by dpelle** [comment]
Thanks.  The rule FAIRE_VPPA can be improved indeed to detect
more errors. Done in: 55ff898af6ea788384a0c8b4725186c46ab38647 and  5435fd8ff2247f3816b2334fe73424dd364406d8
