### ISSUE TITLE
[pt] Improve disambiguator “SPS00” → “DA.+” - 2023-04-26

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8331]
Hello @jaumeortola @susanaboatto 

Could the “a” here appear also as “DA0FS0”?:
`Quando se abre a definição em Modo Avançado.`

![Screenshot 2023-04-26 at 01-54-06 Análise de Texto - LanguageTool](https://user-images.githubusercontent.com/5192600/234438864-3cfa6541-3358-4594-825e-a9124cff7a61.png)

Thanks!

**Comment by jaumeortola** [comment]
I fixed it for the verb "abrir". But this is a more general problem with the disambiguation rule A_PREPOSITION[6].
