### ISSUE TITLE
"Archeologists" not in dictionary

### ISSUE THREAD

**Issue by InnovativeInventor** [languagetool-org/languagetool#834]
The word "archeologists" is interchangeable with the word "archaeologist", but language tool marks "archeologists" as incorrectly spelled.

**Comment by MikeUnwalla** [comment]
@InnovativeInventor , thanks for your report.

Team, I do not know how to correct this problem. 

'Archeologist' is the AmE spelling of BrE 'archaelogist'. If I add 'archeologist' to spelling.txt, then LT correctly gives no warning for the word when the text language is English (American). But, LT incorrectly gives no warning for the word if the text language is English (British).

To deal with this type of problem, we need a way to make locale-specific spelling suggestions.

**Comment by f-knorr** [comment]
Hi @MikeUnwalla !
I have just added support for locale-specific spelling suggestions. 
For each locale there is a file spelling_en-XY.txt.
Each file serves the same purpose as spelling.txt but is limited to the specific locale (e.g., US, CA,...).
Please close this issue if the changes solve the problem.

**Comment by MikeUnwalla** [comment]
I wrote, "'Archeologist' is the AmE spelling", but that is not correct. 'Archeologist' is **an** American spelling. Merriam Webster's Collegiate Dictionary gives both versions. On COCA, I got these results:
archaeology: 3040, example https://www.crt.state.la.us/cultural-development/archaeology/
archeology: 239

Plural arch[a]eologies is rare, but possible (and LT gives it the postag NNS)

The solution to #834 identifies another problem. We have no easy way to deal with alternative spellings. For example, in AmE, both spellings are correct: cancelation, cancellation. But, LT gives a warning for 'cancelation'. I can add 'cancelation' to spelling_en-US.txt. But, the user does not get a warning if a text contains both 'cancelation' and 'cancellation'. In AmE and BrE, the past participles 'dreamt' and 'dreamed' are possible. What do you think we should do about a word that has more than one possible spelling?

**Comment by Discostu36** [comment]
@f-knorr Great! Maybe this would also be a good idea for other languages?

**Comment by f-knorr** [comment]
This rule exists already for German. (I have just copied it from there.) I do not know whether there are other languages which might benefit from this rule, but if there are it would be very easy to add the rule.

**Comment by MikeUnwalla** [comment]
@f-knorr , Thank you.

Before I start to add words to the rule, I want to clarify the use of the rule:

1. The rule is for word variants that are possible in one locale, isn't it? For a word variant such as color/colour, where each locale has only one spelling, the word variants are not necessary in the rule. (The spelling rules find the misspelled words.)

2. For a word variant such as minimize/minimise, where both spelling are possible (in BrE), put the variants into the rule, although the AmE spelling rules also find 'minimise'.

3. The rule is for word variants of one lemma. Thus, do not include variants such as metre (measurement)/meter (device), or zeros (noun)/zeroes (verb). And by that reasoning, disc/disk should not be in the rule, because in BrE, they have different meanings: disc = a round flat object, disk = a round flat storage device for electronic information. Similarly, according to Merriam Webster's dictionary, 'disc' is correct AmE. For example, the word 'disc' is used with the meaning of 'a phonograph record', and with the meaning 'a concave circular steel tool...'. Also, it is part of the multi-word term 'compact disc'.

**Comment by f-knorr** [comment]
@MikeUnwalla . Let me answer your questions:

1. Adding words to coherency.txt will not add them to the dictionary. Hence, if one locale's dictionary does not contain a variant such as 'color', the word will be marked as a spelling error.
2. The WordCoherencyRule will work on all locales. Hence, if one locale contains does not contain both variants, a spelling error will be marked (see 1)
3. I have deleted dis[ck].

**Comment by MikeUnwalla** [comment]
@f-knorr , thanks. I will start to add word variants later today.

**Comment by MikeUnwalla** [comment]
@f-knorr , lines 1 to 8 in the screen shot are a copy of the text that is in coherency.txt. (For clarity, I de-selected the spelling rules):

![image](https://user-images.githubusercontent.com/5816160/33179440-58b5da06-d061-11e7-8570-1a013613e4cd.png)

All the words in the screen shot have a postag.

The rule does not give a message for these words: alkalis, busses, cancelled, cancelling. Is that the correct behaviour of the rule or is it a bug?

(Aside. Merriam Webster's dictionary shows that both 'l' and 'll' are correct in AmE for canceled and related words.)

**Comment by f-knorr** [comment]
Sorry, @MikeUnwalla ! That's my fault. I did not check the exact conditions which trigger this rule: 
The comparison between two variants is based on the word's base form. Hence, variants which have the same base form such as 'cancelled' and 'canceled' are currently not detected.

**Comment by MikeUnwalla** [comment]
@f-knorr , OK. Thanks for the clarification.

Until we have a way to deal with terms such as canceled/cancelled which are both correct in AmE, I won't change the spelling rules for such terms.

**Comment by MikeUnwalla** [comment]
Hello @f-knorr ,

![image](https://user-images.githubusercontent.com/5816160/47951349-67b71280-df57-11e8-85db-46bd6d2e0382.png)

As preparation for https://forum.languagetool.org/t/coherency-rules-for-words-such-as-christianize-and-balkanize/3505/2, I did some tests with words that are already in coherency.txt and which have postags.

Shouldn't LT show an error in lines 5 and 7 for 'Westernize'?

**Comment by MikeUnwalla** [comment]
@f-knorr , thank you.

**Comment by f-knorr** [comment]
@MikeUnwalla , you're welcome!
