### ISSUE TITLE
Tag as latest release

### ISSUE THREAD

**Issue by InnovativeInventor** [languagetool-org/languagetool#835]
I'm making a script that will install the latest release for everyone (pull request coming soon) to streamline the process of installing languagetool. Could the latest be release be marked as the latest release to make everything easier? Thanks.

**Comment by danielnaber** [comment]
The latest release is always available under this URL: https://languagetool.org/download/LanguageTool-stable.zip

**Comment by InnovativeInventor** [comment]
Thanks
