### ISSUE TITLE
[de] Partei/Partie

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#8362]
LanguageTool should have rule that detects typos with "Partie/Partei".

> Welche **Partie** hast du bei der letzten Bundestagswahl gewählt?

> Lass uns eine **Partei** Schach spielen.

Don't know if this is a case for statistical detection or a manual rule.

**Comment by Discostu36** [comment]
Is there a reason why this is still `temp_off`?

**Comment by danielnaber** [comment]
Maybe it was just forgotten, sorry. Luisa should be back in a few days to have a look. There's one false alarm, BTW: https://internal1.languagetool.org/regression-tests/via-http/2023-05-23/de-DE_full/result_grammar_PARTIE_VS_PARTEI%5B2%5D.html
