### ISSUE TITLE
Preformatted text isn't detected

### ISSUE THREAD

**Issue by PavanLuca** [languagetool-org/languagetool#8368]
No formatting 👇
![Schermata da 2023-04-28 17-45-43](https://user-images.githubusercontent.com/123581658/235235641-4805b1f6-2e6b-4f5b-bd98-3ae7236bb895.png)
**Bold** 👇
![Schermata da 2023-04-28 17-46-31](https://user-images.githubusercontent.com/123581658/235235654-5a73256c-fc7d-425b-8153-c846e812563a.png)
_Italic_ 👇
![Schermata da 2023-04-28 17-46-16](https://user-images.githubusercontent.com/123581658/235235653-9e026609-1bcb-40f6-b2e9-1bba56232043.png)
`Preformatted text` 👇
![Schermata da 2023-04-28 17-45-58](https://user-images.githubusercontent.com/123581658/235235649-c194d40f-c196-423d-a184-efc30cb3c58c.png)

**Comment by danielnaber** [comment]
Well, it's a feature to avoid false alarms, as preformatted text often isn't meant to be checked.
