### ISSUE TITLE
[pt] Disambiguator issue “de tal forma” (“tal”) - 2023-04-30

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8372]
@susanaboatto @jaumeortola 

Hello!

In “de tal forma”, “tal” appears as an unknown word:
`Isto acontece de tal forma sólida.`
![Screenshot 2023-04-30 at 22-39-43 Análise de Texto - LanguageTool](https://user-images.githubusercontent.com/5192600/235377530-c651ab37-df71-4505-8483-9e9afbe04b98.png)

Thanks!

**Comment by jaumeortola** [comment]
RG is not unknown, it is an adverb. "de tal forma" is tagged as an adverb, or rather an "adverbial phrase". 
If it is ambiguous in some contexts, then we need a disambiguation rule instead of an entry in multiwords.txt.

**Comment by jaumeortola** [comment]
fixed here: https://github.com/languagetool-org/languagetool/commit/b7206c0159223d8bb35cec01092e96c8ffd0a09d

**Comment by marcoagpinto** [comment]
Thank you, Jaume!
