### ISSUE TITLE
Identifying Text Areas

### ISSUE THREAD

**Issue by wfdigitalsupport** [languagetool-org/languagetool#8385]
Hi all, 

This is not an issue but a question. 

Can anyone technically explain how the extension is able to identify and please the button in nearly any text box?

I'm running a test and would appreciate some guidance.

**Comment by danielnaber** [comment]
> Can anyone technically explain how the extension is able to identify and please the button in nearly any text box?

You can find (old) code for that in the old version of the add-on at https://github.com/languagetool-org/languagetool-browser-addon. But the short answer is that there is no short answer - to make this work, you need a lot of special cases to cover all websites.
