### ISSUE TITLE
[uk] wrong case false positives

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#8390]
Казки про колобків.
Шпак з його: «Два магнітофони, куртка замшева»
Вибачились за гід по ресторанах.

**Comment by arysin** [comment]
Technically «колобок» is inanimate (piece of bread), so it should have been "про колобки". But in the story it becomes animate, not sure if it's worth to add another form just for this.
«гід» is animate, so rule is correct, I guess гід is here used as a book, but that would be substandard (dictionaries don't register that meaning)
«Шпак з його» - does not seem like a proper construction.
