### ISSUE TITLE
[DE] LT erkennt ein – ?" – nicht als Satzende an

### ISSUE THREAD

**Issue by CaitlinMkaKatie** [languagetool-org/languagetool#8401]
Langsam nervt das echt ;-)
ich schreibe in einem Kapitel ein Gespräch mit Rede – Gegenrede und – ?" – wird nicht als Satzende anerkannt. Erst wenn ich noch extra einen Punkt dazwischenquetsche, löst sich die 40-Wörter-Regel in Wohlgefallen auf. Hier das neuste Beispiel ...
![Screenshot 2023-05-05 113557](https://user-images.githubusercontent.com/129726921/236427347-25881f0d-c77f-479c-811b-921d012c36e2.jpg)

**Comment by Luisa-LT** [comment]
_Er fragte: Garak, kennst du wen, der als Führer bereit ist, die Strecke zu reiten?” Garak nickte und erklärte, dass sein Karawanenführer, der sie jetzt nach Shainsa bringt, der richtige für den Job ist, da er dann die Gelder für die Dörfer gleich mitnehmen könnte._

Erste Einschätzung: Liegt sehr wahrscheinlich an den fehlenden öffnenden Anführungsstrichen am Anfang der wörtlichen Rede. Sobald man diese setzt, schlägt die "zu-langer-Satz"-Regel nicht an ( => AP).

**Comment by CaitlinMkaKatie** [comment]
> _Er fragte: Garak, kennst du wen, der als Führer bereit ist, die Strecke zu reiten?” Garak nickte und erklärte, dass sein Karawanenführer, der sie jetzt nach Shainsa bringt, der richtige für den Job ist, da er dann die Gelder für die Dörfer gleich mitnehmen könnte._
> 
> Erste Einschätzung: Liegt wahrscheinlich an den fehlenden öffnenden Anführungsstrichen am Anfang der wörtlichen Rede. Sobald man diese setzt, schlägt die "zu-langer-Satz"-Regel nicht an ( => AP).

der erste Satz der wörtlichen Rede beginnt einige Zeilen darüber, besteht aus mehreren Sätzen und Beginn Anführungszeichen ist gesetzt. Er schließt den Satz von dir zitierten Satz, nur wenn ich hinter - ?" - einen extra Punkt setze. *hmm*

**Comment by tiff** [comment]
@danielnaber das Problem hier ist, dass alles als ein Satz erkannt wird. In der Regel könnten wir das recht einfach fixen, wir brauchen nur ein Antipattern, das schaut, ob der Satz `."`, `?"` oder `!"` enthält (natürlich auch mit typografischen Anführungszeichen).

**Comment by Luisa-LT** [comment]
Genau, wenn jedoch typografische Anführungszeichen verwendet werden [?“] schlägt die `TOO_LONG_SENTENCE` bei mir schon jetzt nicht an: 
![image](https://github.com/languagetool-org/languagetool/assets/115984740/8d548010-f9b3-4d89-839e-7c416ab0268a)

**Comment by danielnaber** [comment]
> In der Regel könnten wir das recht einfach fixen, wir brauchen nur ein Antipattern, das schaut, ob der Satz .", ?" oder !" enthält

Habe ich mal so gemacht, geht heute Abend online.
