### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Bachstelze** [languagetool-org/languagetool#841]
is there a Dockerfile out to build the language tool?

**Comment by InnovativeInventor** [comment]
No, but there is an install script at my fork (I've submitted a pull request, so you could just wait until they merge it). I might make a dockerfile sometime with my install script. 

[https://github.com/InnovativeInventor/languagetool](https://github.com/InnovativeInventor/languagetool)

**Comment by f-knorr** [comment]
Does this help: https://github.com/silvio/docker-languagetool

**Comment by f-knorr** [comment]
I close this issue as there has been now answer for more than ten days. If there are still open questions, reopen this issue.

**Comment by Bachstelze** [comment]
yeah thanks, the docker file looks great
