### ISSUE TITLE
[pt] Idea for scientific/academic rule: “pela ajuda dada/prestada” → “pelo auxílio prestado” - 2023-05-11

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8442]
Hello @ricardojosehlima

I was revising the thesis and found I could replace:
`Agradecemos a todos pela ajuda dada/prestada.`
For:
`Agradecemos a todos pelo auxílio prestado.`

Does it sound more scientific/academic this way?

Do you agree? Maybe a picky rule?

Thanks!

**Comment by ricardojosehlima** [comment]
Great, congratulations!

**Comment by ricardojosehlima** [comment]
I don't know
