### ISSUE TITLE
Is there any differences between online version and offline version?

### ISSUE THREAD

**Issue by thuxugang** [languagetool-org/languagetool#845]
Hello, i was wondering that is there any differences between online version and offline version?
I download LanguageTool-20171123-snapshot.zip and visit http://localhost:8081/v2/check?language=en&text=this+is+you+sister, the results are as follows:
{"software":{"name":"LanguageTool","version":"4.0-SNAPSHOT","buildDate":"2017-11-23 21:01","apiVersion":1,"status":""},"warnings":{"incompleteResults":false},"language":{"name":"English","code":"en"},"matches":[{"message":"This sentence does not start with an uppercase letter","shortMessage":"","replacements":[{"value":"This"}],"offset":0,"length":4,"context":{"text":"this is you sister","offset":0,"length":4},"rule":{"id":"UPPERCASE_SENTENCE_START","description":"Checks that a sentence starts with an uppercase letter","issueType":"typographical","category":{"id":"CASING","name":"Capitalization"}}}]}
But when i use online version, visit https://languagetool.org/api/v2/check?language=en&text=this+is+you+sister, the results are
{"software":{"name":"LanguageTool","version":"4.0-SNAPSHOT","buildDate":"2017-11-23 21:01","apiVersion":1,"status":""},"warnings":{"incompleteResults":false},"language":{"name":"English","code":"en"},"matches":[{"message":"This sentence does not start with an uppercase letter","shortMessage":"","replacements":[{"value":"This"}],"offset":0,"length":4,"context":{"text":"this is you sister","offset":0,"length":4},"rule":{"id":"UPPERCASE_SENTENCE_START","description":"Checks that a sentence starts with an uppercase letter","issueType":"typographical","category":{"id":"CASING","name":"Capitalization"}}},{"message":"Statistics suggests that 'your' (possessive pronoun) might be the correct word here, not 'you' (personal pronoun). Please check.","shortMessage":"","replacements":[{"value":"your"}],"offset":8,"length":3,"context":{"text":"this is you sister","offset":8,"length":3},"rule":{"id":"CONFUSION_RULE","description":"Statistically detect wrong use of words that are easily confused","issueType":"non-conformance","category":{"id":"TYPOS","name":"Possible Typo"}}}]}
Online version can replace "you" with "your".
Thanks a lot.....

**Comment by danielnaber** [comment]
Please see https://languagetool.org/compare/

**Comment by tv42** [comment]
The link you gave in 2017 now just redirects to the frontpage. Should I assume this project is hopelessly doomed into SaaS monetization and not interesting to free software zealots?
