### ISSUE TITLE
languagetool is in conflict with module "nlpsolver", generating an error "java.lang.reflect.InvocationTargetException"

### ISSUE THREAD

**Issue by bernardgisin** [languagetool-org/languagetool#846]
I work under linux KUbuntu 16.04, 64 bits, with KDE.
In libreoffice, I installed the extension "languagetool 3.9" and the extension "nlpsolver  0.9". 
nlpsolver can be installed from "Ubuntu software center" or from "Synaptic package manager"
When I try to activate "nlpsolver" I get the following error : 
 java.lang.reflect.InvocationTargetException
and nlpsolver doesn't work.  Languagetool work fine.
When I deactivate Languagetool, nlpsolver still doesn't work.
When I remove Languagetool, nlpsolver works fine.
I'm not the only one concerned, since I found why nlpsolver didn't work here :
https://code.google.com/archive/p/ooo2gd/issues/115

For the moment, I removed languagetool and use grammalecte instead.
Si there a way to make both modules work in Libreoffice ?

Thank you for your work,  Bernard Gisin.

**Comment by FredKruse** [comment]
I tested this with the LO 6.2.8. It works. Both extensions can be activated.
@bernardgisin: Please close the issue.

**Comment by bigi111** [comment]
I did some tests on KUbuntu 18.04 and both extensions worked on LibreOffice 6.0.7.3. I updated the non linear solver. It is still version 0.9
Language Tool has version 4.8 now.

**Comment by FredKruse** [comment]
@bigi111: I will close issue now.
