### ISSUE TITLE
[fr] "C'en est trop" unexpected error (premium)

### ISSUE THREAD

**Issue by Grimst** [languagetool-org/languagetool#8464]
![image](https://github.com/languagetool-org/languagetool/assets/16018842/18fcfbaa-ab37-4d2f-9ae2-0e622d1f48f5)

"C'en est" = "cela en est" (same)

Cheers,
Steve

**Comment by maphjo** [comment]
The indicated premium "error" is a style suggestion, currently indicated as an error. We are in the process of changing the approach for style suggestions.
