### ISSUE TITLE
[fr] "Manges ta soupe !" / WRONG no errors raised

### ISSUE THREAD

**Issue by Grimst** [languagetool-org/languagetool#8472]
![image](https://github.com/languagetool-org/languagetool/assets/16018842/c3bb0150-7444-402c-8c8e-4f9f9ce28bd0)

**Comment by maphjo** [comment]
The error is found in premium! But it is not marked as a hidden match.

**Comment by Grimst** [comment]
When I use LT online there is no error raised  ??

**Comment by maphjo** [comment]
I have checked it on the LT website, in the LT editor and in the add-on as a logged in premium user.
![image](https://github.com/languagetool-org/languagetool/assets/119609826/97440ad2-d70c-42bc-8b89-9917172edb29)

**Comment by Grimst** [comment]
OK I see : non-paid user does not ahve any marks (no error found) but paid user have this error raised ?

that is enough for me, I give up your tool.

**Comment by maphjo** [comment]
We generally do this, but unfortunately, we have a few rules for French which we still need to incorporate into the hidden matches feature.
I am sorry that you feel misled. We are constantly improving LanguageTool and your feedback is essential to get better.
