### ISSUE TITLE
[fr] "courir après quelqu'un" / error (premium)

### ISSUE THREAD

**Issue by Grimst** [languagetool-org/languagetool#8481]
"courir après quelqu'un" LT does not like this correct one :

![image](https://github.com/languagetool-org/languagetool/assets/16018842/994b7392-8fcb-402e-acec-0045035c35e2)

**Comment by maphjo** [comment]
The indicated premium "error" is a style suggestion, currently indicated as an error. We are in the process of changing the approach for style suggestions.
