### ISSUE TITLE
[fr] "J'offre des fleurs à son amie." / error (premium)

### ISSUE THREAD

**Issue by Grimst** [languagetool-org/languagetool#8492]
Correct sentence : 

![image](https://github.com/languagetool-org/languagetool/assets/16018842/b72f05da-81b3-4d1d-9bb4-25cf6ce03b52)

**Comment by maphjo** [comment]
The indicated premium "error" is a style suggestion, currently indicated as an error. We are in the process of changing the approach for style suggestions.
