### ISSUE TITLE
Could not initialize English chunker

### ISSUE THREAD

**Issue by zangetsou** [languagetool-org/languagetool#851]
Imported LanguageTool libraries into my project but I'm getting an error when trying to check a text in English.

IDE reports missing  file: "Could not load file from classpath: '/en-token.bin'", but i dont know where to find this file so I can add it to classpath.

**Comment by danielnaber** [comment]
Please don't copy resources manually to your classpath, instead use Maven or Gradle as documented at http://wiki.languagetool.org/java-api
