### ISSUE TITLE
[fr] "J'ai été voir ... " (and) "j'ai été faire ..." etc. no alternatives

### ISSUE THREAD

**Issue by Grimst** [languagetool-org/languagetool#8510]
![image](https://github.com/languagetool-org/languagetool/assets/16018842/5a7ab510-b35d-4f23-8c06-81ca57930145)

Better : 

"J'ai été voir la finale." => "Je suis allé voir la finale."
"J'ai été faire des achats." => "Je suis allé faire des achats."

**Comment by maphjo** [comment]
The error is found in premium! But it is not marked as a hidden match for basic users. This bug has been reported internally already.
