### ISSUE TITLE
[fr] sentence : "J'ai besoin de tout ce qui concerne cette affaire." / error (premium)

### ISSUE THREAD

**Issue by Grimst** [languagetool-org/languagetool#8511]
2 errors premium for a correct sentence : 

![image](https://github.com/languagetool-org/languagetool/assets/16018842/07c996d6-5401-4757-98b6-70c93cd82fbe)

**Comment by maphjo** [comment]
The indicated premium "error" is a style suggestion, currently indicated as an error. We are in the process of changing the approach for style suggestions.
