### ISSUE TITLE
[fr] "Votre décision est pleine de bon sens." / error (premium)

### ISSUE THREAD

**Issue by Grimst** [languagetool-org/languagetool#8515]
this sentence is correct.

![image](https://github.com/languagetool-org/languagetool/assets/16018842/3fb2e401-70d3-4ef1-82de-3aec88dcbae1)

**Comment by maphjo** [comment]
The indicated premium "error" is a style suggestion, currently indicated as an error. We are in the process of changing the approach for style suggestions.
