### ISSUE TITLE
Emojis are marked as misspelling in Spanish and Polish

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#853]
![bildschirmfoto 2017-12-03 um 16 54 27](https://user-images.githubusercontent.com/37363/33527094-fcf5e25a-d84a-11e7-82eb-56ed972d5631.png)

This only seems to happen with Spanish and Polish. I wasn't able to reproduce this in other languages.

**Comment by pabru** [comment]
Can we have some test strings for Polish? I'd like to try my hand at replicating this.

**Comment by f-knorr** [comment]
Just enter this as text string: 😀
For you r information: See #842
