### ISSUE TITLE
[fr] "par acquit de conscience." Uppercase missing after the point.

### ISSUE THREAD

**Issue by Grimst** [languagetool-org/languagetool#8533]
![image](https://github.com/languagetool-org/languagetool/assets/16018842/1c3f64c6-4b5f-4915-85f8-372659a06a7e)

No error 

expected : "Par acquis de conscience."

**Comment by maphjo** [comment]
The error is found in premium! But it is not marked as a hidden match for basic users. This bug has been reported internally already.
