### ISSUE TITLE
[fr] "Ces livres nous ont beaucoup servi." / error (premium)

### ISSUE THREAD

**Issue by Grimst** [languagetool-org/languagetool#8546]
This sentence is correct.

![image](https://github.com/languagetool-org/languagetool/assets/16018842/a6085d7e-e771-41c7-86dd-6c6ac29000fb)

**Comment by maphjo** [comment]
The indicated premium "error" is a style suggestion, currently indicated as an error. We are in the process of changing the approach for style suggestions.
