### ISSUE TITLE
List of Acronyms

### ISSUE THREAD

**Issue by Wanibzh29** [languagetool-org/languagetool#856]
[Acronym.zip](https://github.com/languagetool-org/languagetool/files/1541882/Acronym.zip)

**Comment by janschreiber** [comment]
What is that meant for?

**Comment by Wanibzh29** [comment]
Hello,
It has helped me to create another file for the Breton language that I will send in a few hours, if everything if everything will be fine.
I was thinking that it could maybe help for the list in English that need the article "an" instead of the "a" one.
regards
Pierre :)

**Comment by TiagoSantos81** [comment]
It seems very good. I looked through the other list and I hope it will be fully integrated. Many thanks, Pierre.

**Comment by Wanibzh29** [comment]
You're welcome ;)
