### ISSUE TITLE
[fr] pleonasm : bon succès

### ISSUE THREAD

**Issue by Grimst** [languagetool-org/languagetool#8571]
![image](https://github.com/languagetool-org/languagetool/assets/16018842/a9626d55-2dd8-49be-88ec-fa83e91461d3)

**Comment by danielnaber** [comment]
Thanks for your reports, but could you please summarize them in fewer issues, e.g. using Github's `- [ ] ...` syntax to create check marks for every single phrase?

**Comment by Grimst** [comment]
Ok sure, I will do that

**Comment by Grimst** [comment]
merged in #8593
