### ISSUE TITLE
[fr] "Pas de souci !" / error (premium)

### ISSUE THREAD

**Issue by Grimst** [languagetool-org/languagetool#8607]
Correct sentences but not for LT
![image](https://github.com/languagetool-org/languagetool/assets/16018842/578bb8ba-c751-4a3a-b8f0-c64be84268a6)

![image](https://github.com/languagetool-org/languagetool/assets/16018842/8dc032ba-2da6-4214-9bf1-85a273fb2a1b)

**Comment by maphjo** [comment]
The indicated premium "error" is a style suggestion, currently indicated as an error. We are in the process of changing the approach for style suggestions.
