### ISSUE TITLE
fsa.dict.speller.ignore-diacritics=false for Russian

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#861]
Generating spelling suggestions for Russian is very slow, it can take about 100ms per typo / unknown word. Setting `fsa.dict.speller.ignore-diacritics=false` in `ru/hunspell/ru_RU.info` speeds that by a factor of about 2. I'll do that change - @yakovru, can you check if that is okay or does it have bad side effects?

**Comment by yakovru** [comment]
I do not see any bad side effects now. I need a few days for full testing.

**Comment by yakovru** [comment]
Spell check for Russian with
`  fsa.dict.speller.ignore-diacritics=false`
 works correctly.
