### ISSUE TITLE
[fr] "Resonner"

### ISSUE THREAD

**Issue by Grimst** [languagetool-org/languagetool#8612]
![image](https://github.com/languagetool-org/languagetool/assets/16018842/631c1c89-625c-4c23-9d0e-aafc1d2593e0)

LT does not like "sonner à nouveau = resonner"

**Comment by danielnaber** [comment]
Could you please also put these types of bug reports into one single issue, just like with pleonasms?

**Comment by Grimst** [comment]
merged in #8595
