### ISSUE TITLE
Ammophila

### ISSUE THREAD

**Issue by PavanLuca** [languagetool-org/languagetool#8629]
Ammophila is detected as wrong both in English and Italian but exists in both.
https://it.wikipedia.org/wiki/Ammophila_arenaria

**Comment by jaumeortola** [comment]
Thank you. I will add "Ammophila arenaria" for all languages. Any way, this is a scientific name in Latin, and it is too vast a field for us to record all the cases.

**Comment by jaumeortola** [comment]
https://github.com/languagetool-org/languagetool/commit/bd7dd577a091ee11dfd205dd718d044d8b07abb3

**Comment by PavanLuca** [comment]
I understand. To make it clear, Ammophila is Latin and Ammofila is Italian. Usually Latin words with ph change the ph into an f. No changes in reading though, ph is pronounced as an f.
