### ISSUE TITLE
[de] G7 G8 G20 Komposita

### ISSUE THREAD

**Issue by Mynyx** [languagetool-org/languagetool#8660]
Bei Komposita wie G7-Gipfel oder G20-Staaten erscheint folgender fehlleitender Hinweis, der einen zusätzlichen Bindestrich vorschlägt:

> Nicht-empfohlene Schreibweise
> Wollen Sie die empfohlene Schreibweise verwenden, anstelle dieser (ebenfalls korrekten) Alternative?
> **G-7**-Gipfel

**Comment by Luisa-LT** [comment]
LanguageTool empfiehlt hier die Durchkopplung. Diese Empfehlung stimmt in diesem Fall auch mit dem Duden überein: https://www.duden.de/rechtschreibung/G_7_Gipfel
![image](https://github.com/languagetool-org/languagetool/assets/115984740/b01152e3-f8c5-472c-924c-e5277b23c24c)
