### ISSUE TITLE
[de] transident, nichtbinär, intergeschlechtlich

### ISSUE THREAD

**Issue by Mynyx** [languagetool-org/languagetool#8661]
Die Adjektive transident, nichtbinär und intergeschlechtlich werden nicht erkannt, es erscheint folgende Fehlermeldung:
> Rechtschreibung
> Möglicher Tippfehler gefunden.

**Comment by danielnaber** [comment]
Danke für den Hinweis, wird mit dem nächsten Update hinzugefügt.
