### ISSUE TITLE
[de] Geografische Angaben

### ISSUE THREAD

**Issue by Mynyx** [languagetool-org/languagetool#8676]
- Arzach
- Bolivarische Republik Venezuela
- Brunei Darussalam
- Cabo Verde
- Côte d’Ivoire
- Demokratische Arabische Republik
- Grenadinen
- Nevis
- Plurinationaler Staat Bolivien
- São Tomé und Príncipe
- Sint Maarten 
- Timor-Leste
- Vereinigte Mexikanische Staaten
- Vereinigtes Königreich Großbritannien und Nordirland

**Comment by tiff** [comment]
Danke, sollte ab Morgen unterstützt sein

**Comment by Mynyx** [comment]
Danke. Drei Fehler bestehen jedoch noch:

![image](https://github.com/languagetool-org/languagetool/assets/1632642/674d197f-27cb-4d64-bb58-0926a18de8cd)
