### ISSUE TITLE
Plural days with moment adverb

### ISSUE THREAD

**Issue by tandriamil** [languagetool-org/languagetool#868]
Hi,

Just to warn you about a little particularity when using plural days with a moment adverb in french. The problem is that `les vendredis soir` and `les mardis matin` are detected as mistakes and it suggests that we should add an `s` to `soir` and `matin` but in fact, we shouldn't.

See [« les lundi » ou « les lundis » ? « les lundis soir » ou « les lundis soirs » ? ](https://www.projet-voltaire.fr/regles-orthographe/les-lundi-ou-les-lundis-les-lundis-soir-ou-les-lundis-soirs)

Thank you   :)

**Comment by dpelle** [comment]
Thanks. I just corrected those false errors. See: a10b72ee7b752c9693410e9a956b3050bd105633

There are no false errors anymore. However, LT does not signal an error
in "Les lundis matins" despite https://www.projet-voltaire.fr/regles-orthographe/les-lundi-ou-les-lundis-les-lundis-soir-ou-les-lundis-soirs/
which says that it should be a mistake.  I see that this rule is controversial.
For example, according to this link http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=2685
both "Les lundis matin" and "Les lundis matins" are correct. It's also correct
according to "Le petit Rober". So I think it's fine if LT does not signal an error
in either of them, as it currently  does.   I prefer not to signal error when
something controversial.
