### ISSUE TITLE
[pt] Idea for rule: “logo que possível” → “prontamente” - 2023-05-23

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8680]
@ricardojosehlima

This is an idea for an academic/scientific rule, I guess:
`E para isso simulando logo que possível o modelo.`
To:
`E para isso simulando prontamente o modelo.`

I believe this is an important rule, during the testing against 600 000 sentences it will require testing with verbs before and verbs after and such to make sure it gets as many valid hits as possible.

Is it a good plan?

Thanks!

**Comment by marcoagpinto** [comment]
Better to have a small detection rule than having none.

**Comment by ricardojosehlima** [comment]
I can't think of having sentences where it makes sense...

**Comment by marcoagpinto** [comment]
Ahhhhh… thanks, let's give up on it then.
