### ISSUE TITLE
[sv] New words added to spelling.txt or spelling_custom.txt do not seem to be returned as replacements

### ISSUE THREAD

**Issue by f4irline** [languagetool-org/languagetool#8681]
Hey!

I've been testing the Swedish language module of the LanguageTool, and it seems that the possibility to add your own words to the `spelling_custom.txt` (or `spelling.txt`) do not seem to work as intended.

I've added the custom words to the `spelling_custom.txt` as such:
```
375f3b8f2575:/LanguageTool/org/languagetool/resource/sv/hunspell$ ls -la
total 2340
drwxr-xr-x    2 language language      4096 May 23 12:59 .
drwxr-xr-x    3 language language      4096 May 23 12:59 ..
-rw-r--r--    1 language language       494 Apr  4 07:36 LICENSE_en_US.txt
-rw-r--r--    1 language language       469 Apr  4 07:36 LICENSE_sv_SE.txt
-rw-r--r--    1 language language        77 Apr  4 07:36 ignore.txt
-rw-r--r--    1 language language       139 Apr  4 07:36 spelling.txt
-rw-r--r--    1 root     root            23 May 23 12:58 spelling_custom.txt
-rw-r--r--    1 language language     18662 Apr  4 07:36 sv_SE.aff
-rw-r--r--    1 language language   2344202 Apr  4 07:36 sv_SE.dic
375f3b8f2575:/LanguageTool/org/languagetool/resource/sv/hunspell$ cat spelling_custom.txt ; echo

testword
somethingelse
375f3b8f2575:/LanguageTool/org/languagetool/resource/sv/hunspell$ 
```

When sending the following kind of payload, which includes the word "somethingelse", everything seems to work as intended (left is the request, right is the response):
<img width="1465" alt="image" src="https://github.com/languagetool-org/languagetool/assets/31544493/5fa49336-10f5-4234-867f-6632a6aa71af">

But when sending the following kind of payload, which has a typo in the word "somethingelse" ("somehingelse"), LanguageTool seems to recognize the typo, but does not offer "somethingelse" in the `replacements`-list:
![image](https://github.com/languagetool-org/languagetool/assets/31544493/12679f80-346b-48d5-ac10-7307cdc7854e)

Is this a flaw in the Swedish module implementation, or a bug, or a known limitation? I've tried adding the words to `spelling.txt` and `spelling_custom.txt`, and neither seem to do the trick. For the English language module for example this seems to work

**Comment by danielnaber** [comment]
This is currently not supported for Swedish (neither for Danish, Galician, Esperanto, Portuguese). The Java code in `HunspellRule` would need to be adapted to support it.

**Comment by f4irline** [comment]
Alright, thanks!
