### ISSUE TITLE
[de] Following text fragments not being proofed correctly

### ISSUE THREAD

**Issue by lowersaxony** [languagetool-org/languagetool#87]
Mal sehen ob der Textverarbeitung richtig funktioniert.
Habe fertig.
~~Morgen schien die Sonne.~~
~~Gestern schneit es ein wenig.~~
Ich bin sicher das morgen die Welt untergeht.
Ich möchte ein morgen Uhr kaufen.
Ich möchte eine große neuer Uhr kaufen.
Ich habe der Mähdrescher gesehen.
Ich habe neue Arbeitsschuh gekauft.
Das ist der Köchin ihr letztes Haar.
~~Ich spreche ein feiner Deutsch.~~
~~Ich spiele der Tamburin.~~
Es darum, welche Kennzahlen in den bereits _erfassbare_ Daten existieren.
Dann läuft es Gefahr gar, keine Zeit für die restlichen _eingeplanten_ Zeit mehr zu haben.

**Comment by danielnaber** [comment]
Closing, copied the remaining errors to #228.
