### ISSUE TITLE
Google Docs Add-On: Correction Shortcut Key Not Working

### ISSUE THREAD

**Issue by Elendarin** [languagetool-org/languagetool#8707]
![image](https://github.com/languagetool-org/languagetool/assets/52305867/961d2eb8-9bdd-435d-bd13-5c7af36c2a68)

I use the shortcut key to bring up corrections in Google Docs. Before the update, enter and the up arrow keys worked fine. After the update, something went wonky. 

![image](https://github.com/languagetool-org/languagetool/assets/52305867/a9e49d03-8e4e-47d0-b1c8-57c59ddc3b88)

If I hit enter, it inserts a line break rather than making the correction. I've tried this elsewhere in Chrome (Discord, Reddit, etc) and had no issues.

**Comment by tiff** [comment]
Thanks! A fix for this is in the making :)

**Comment by tiff** [comment]
We have released a fix (v7.1.3) which is being rolled out over the next days.
