### ISSUE TITLE
[de] Falsche Regel durch Tippfehler "erst(e)" ausgelöst

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#8766]
![grafik](https://github.com/languagetool-org/languagetool/assets/30999326/ac850a0b-32d0-46c5-a038-652df1590486)

Die Regel NORMALISIERTE_ORDNUNGSZAHLEN wird ausgelöst und gibt eine falsche Empfehlung.

**Comment by Luisa-LT** [comment]
https://github.com/languagetooler-gmbh/languagetool-premium-modules/pull/604
