### ISSUE TITLE
[pt] False spelling error about "raios X" and "raios-X" (the X-ray wave; X-ray machine)

### ISSUE THREAD

**Issue by brunnopleffken** [languagetool-org/languagetool#8770]
As a physicist, I deal much about electromagnetic waves. In portuguese, there's a spelling difference between the X-ray used in radiography and tomography, and the X-ray electromagnetic wave.

<img width="453" alt="Screenshot 2023-06-03 at 15 03 57" src="https://github.com/languagetool-org/languagetool/assets/3427344/39b672eb-166d-43ea-bb59-b3f7052b6a0a">

_Above, is the electromagnetic wave, and I spelled it correctly._

To clarify:

- "Raios X": is the X-ray electromagnetic wave, and there's **NOT** a hyphen in it;
- "Raios-X": is the X-ray machine in hospitals and clinics, although is recommended to use the word "radiografia" (radiography).

**Comment by p-goulart** [comment]
@brunnopleffken , determining which one is meant by the user isn't super trivial, but we've removed `raio-x` from the automatic hyphenation rule and added a separate rule that tells users about the different possibilities. At least now you should be able to disable this one particular rule without losing support for the more general hyphenation rule. Hope it's an improvement!
