### ISSUE TITLE
[DE] Fehlalarm im Nebensatz mit "..., auf die Verlass ist"

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#8803]
Moin liebes LanguageTool-Team

"Sie sind sehr gute Kameraden, auf **die Verlass** ist."
LT: "Möglicherweise fehlende grammatische Übereinstimmung von Artikel und Nomen."

Das ist ein Fehlalarm, weil "auf die" in diesem Fall Bezug auf den Hauptsatz nimmt. Der Hauptsatz ist Mehrzahl, weswegen im Nebensatz die Mehrzahl fortgefürt werden muss.

Grüße Dallun511

**Comment by tiff** [comment]
Behoben mit https://github.com/languagetool-org/languagetool/commit/2bdbda3fe1a133e95fcb6263cd9f134a3fa374ae
