### ISSUE TITLE
running command line tool with the text from the official site takes 3 seconds

### ISSUE THREAD

**Issue by astoilkov** [languagetool-org/languagetool#881]
Running the following command `java -jar languagetool-commandline.jar -l en text.txt` takes 3 seconds `Time: 3095ms for 7 sentences (2.3 sentences/sec)` to return the result. The `text.txt` file includes the text from your official website:

> Paste your own text here and click the 'Check Text' button. Click the colored phrases for details on potential errors. or use this text too see an few of of the problems that LanguageTool can detecd. What do you thinks of grammar checkers? Please not that they are not perfect. Style issues get a blue marker: It's 5 P.M. in the afternoon. LanguageTool 3.8 was released on Thursday, 27 June 2017.

Why running the LanguageTool command line interface takes so long to return the result?

**Comment by danielnaber** [comment]
Because there's a lot of overhead in reading and initializing data structures. Starting the JVM also takes some time. If you need faster response times, try using [the server](http://wiki.languagetool.org/http-server), which returns JSON.
