### ISSUE TITLE
[pt-PT] Replacement rules suggest words not found in spelling dicts

### ISSUE THREAD

**Issue by p-goulart** [languagetool-org/languagetool#8814]
A new test has been introduced recently that checks whether all values introduced by replacement rules are actually found in the spelling dictionary. We've done `pt-BR` internally, but there are still some for `pt-PT`. This is a problem as it prompts the user to make a replacement that is then flagged as a hunspell error.

Many of these are simply words that **do** exist but have not been added to our hunspell dicts; some are split dialectally (we've handled those by splitting the replacement files); some others still are legitimate typos that must be fixed.

Attaching the current (as of 13 Jun '23) list of warnings issued for `Portuguese (Portugal)`.

[pt-PT-spelling-warnings.txt](https://github.com/languagetool-org/languagetool/files/11734020/pt-PT-spelling-warnings.txt)

**Comment by marcoagpinto** [comment]
@p-goulart 

Heya,

Nice to meet you and welcome to the team!

What shall I do with the list in the .txt?

Could you explain, please?

❤️ ❤️ ❤️ ❤️ ❤️ 

Thanks!

**Comment by p-goulart** [comment]
Well, depends on what's in the warning itself, but let's take this line for example:
```
*** WARNING: replacement 'crapô' for 'crapaud' from one of [/pt/barbarisms-pt.txt] isn't known to spell checker of Portuguese (Portugal): [HUNSPELL_RULE:0-5:Possível erro ortográfico]
```
This tells us that the file `/pt/barbarisms-pt.txt` tries to introduce a word (`crapô`) that doesn't exist in the `pt-PT` dictionaries, and therefore triggers `HUNSPELL_RULE`. If `crapô` is a valid `pt-PT` word, then it must be added to `spelling.txt` and (possibly) `added.txt`. If it's invalid, then you can just remove this replacement line or fix it (if it's a typo).

**Comment by marcoagpinto** [comment]
Ahhhhhh…

It seems easy to do, I will do it tonight.

Thanks!

😋 😛 ❤️

**Comment by p-goulart** [comment]
These are only _warnings_ for now, I don't think there's any need for anyone to do 400+ lines in one day, and definitely not at 5am 😌

**Comment by marcoagpinto** [comment]
Ahhhhh…

Another batch:
https://github.com/languagetool-org/languagetool/commits/master

I guess it will take days, not a few hours in a single day.

😄

**Comment by marcoagpinto** [comment]
Heya, @p-goulart and @susanaboatto 

It is done!

Sorry for taking two weeks to fix it, but I have also been working on other projects.

I haven't fixed the following because I couldn't find the words in dictionaries:
```
*** WARNING: replacement 'jérsias|camisas' for 'jerseys' from one of [/pt/barbarisms-pt-PT.txt] isn't known to spell checker of Portuguese (Portugal): [HUNSPELL_RULE:0-7:Possível erro ortográfico]
*** WARNING: replacement 'jérsia|camisa' for 'jersey' from one of [/pt/barbarisms-pt-PT.txt] isn't known to spell checker of Portuguese (Portugal): [HUNSPELL_RULE:0-6:Possível erro ortográfico]
*** WARNING: replacement 'spintrónica' for 'spintrônica' from one of [/pt/pt-PT/replace.txt] isn't known to spell checker of Portuguese (Portugal): [HUNSPELL_RULE:0-11:Possível erro ortográfico]
*** WARNING: replacement 'spintrónicas' for 'spintrônicas' from one of [/pt/pt-PT/replace.txt] isn't known to spell checker of Portuguese (Portugal): [HUNSPELL_RULE:0-12:Possível erro ortográfico]
*** WARNING: replacement 'videoconsola' for 'aparelho de videogame' from one of [/pt/pt-PT/replace.txt] isn't known to spell checker of Portuguese (Portugal): [HUNSPELL_RULE:0-12:Possível erro ortográfico]
```

😋 😛 ❤️ 🤗

**Comment by maphjo** [comment]
Thank you, @marcoagpinto, for taking care of this!

---
Regarding this:

> I haven't fixed the following because I couldn't find the words in dictionaries:
> 
> ```
> *** WARNING: replacement 'jérsias|camisas' for 'jerseys' from one of [/pt/barbarisms-pt-PT.txt] isn't known to spell checker of Portuguese (Portugal): [HUNSPELL_RULE:0-7:Possível erro ortográfico]
> *** WARNING: replacement 'jérsia|camisa' for 'jersey' from one of [/pt/barbarisms-pt-PT.txt] isn't known to spell checker of Portuguese (Portugal): [HUNSPELL_RULE:0-6:Possível erro ortográfico]
> *** WARNING: replacement 'spintrónica' for 'spintrônica' from one of [/pt/pt-PT/replace.txt] isn't known to spell checker of Portuguese (Portugal): [HUNSPELL_RULE:0-11:Possível erro ortográfico]
> *** WARNING: replacement 'spintrónicas' for 'spintrônicas' from one of [/pt/pt-PT/replace.txt] isn't known to spell checker of Portuguese (Portugal): [HUNSPELL_RULE:0-12:Possível erro ortográfico]
> *** WARNING: replacement 'videoconsola' for 'aparelho de videogame' from one of [/pt/pt-PT/replace.txt] isn't known to spell checker of Portuguese (Portugal): [HUNSPELL_RULE:0-12:Possível erro ortográfico]
> ```

Shouldn't we then remove those suggestions from the replacement files? I think it would be weird for the users if they received a suggestion to replace one word and then this word was marked as a spelling error.

**Comment by marcoagpinto** [comment]
@maphjo 

Heya, I can hardly wait to start creating new rules.

I have been making a list of ideas and the list is growing.

😄 😄 😄 😄 😄 😄 😄
