### ISSUE TITLE
Where is the dogs?

### ISSUE THREAD

**Issue by qtxwang** [languagetool-org/languagetool#883]
The language tool says no error?  I tried multiple times but I must have missed something.

**Comment by danielnaber** [comment]
Probably there's no pattern for this error. You can find how to write patterns at http://wiki.languagetool.org/development-overview and contribute one.

**Comment by qtxwang** [comment]
Okay, I will try to come up with some rules. It appears the tool need some rules to detect plural/singular errors. Another example of false negative: My teacher teach us a lot.

**Comment by qtxwang** [comment]
Is it possible to make Language Tool accept rules that are based on statistical usages of ordinary languages? For example, phrase "Teacher teach" happens only 0.01% percent of the time while "Teacher teaches" 99.99% (just made up numbers).

**Comment by danielnaber** [comment]
Please see http://wiki.languagetool.org/finding-errors-using-big-data for something similar - it only covers what we call "confusion pairs" so far.
