### ISSUE TITLE
Integration wich libreoffice dont work.

### ISSUE THREAD

**Issue by jw-programmer** [languagetool-org/languagetool#8837]
The integration which libreoffice is not working. Is jot showing grammar erros.

Version of extension 6.1.1
Version of libreoffice 7.5.4.2 flatpak

**Comment by danielnaber** [comment]
This is a known issue with LO 7.5.4, it will be fixed with 7.5.5. A downgrade to 7.5.3 should also fix this issue.

**Comment by jw-programmer** [comment]
Well, i dont know how do a downgrade a flatpak, so i just wait a little. I not use libreoffice for any critical in moment. Thanks.
