### ISSUE TITLE
[nl] spelling.txt limitations?

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#8838]
This morning, I get in the nightly diff:
![afbeelding](https://github.com/languagetool-org/languagetool/assets/8479998/e4114045-5146-42a8-8bc6-f708efc5a856)

Which is weird, Since I added this to spelling.txt yesterday:

London Academy of Music and Dramatic Art

If there are limitations, in the number of items in the list, or the number of tokens, I understand. These could be solved, maybe, or checked at test time.

**Comment by danielnaber** [comment]
This is not a software bug, but a problem with deployment. You can see at the bottom of the page that the latest version of LT had not been deployed to all servers yet:

![depl](https://github.com/languagetool-org/languagetool/assets/857004/25ff42af-7287-45e4-a204-6ef70a084369)

This should be resolved soon.
