### ISSUE TITLE
Synthesizer should consider removed.txt and added.txt

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#884]
[According to](https://forum.languagetool.org/t/de-das-bleistift-removed-txt-not-working/2127/6) @danielnaber the synthesizer does have its own dictionary and therefore ignores additions to removed.txt and added.txt. This can lead to wrong suggestions:

![capture](https://user-images.githubusercontent.com/30999326/35732643-81d47f5a-081a-11e8-8b23-a58d51897ae9.PNG)

In my opinion this has to be addressed. Either the synthesizer should also consider removed.txt and added.txt or at least a suggestions should never be identical to the marked tokens.

**Comment by danielnaber** [comment]
This has been implemented now. However, "Bleistift" is a special case as it's considered a compound and listing it in `removed.txt` will have no effect. This is tricky to fix.

**Comment by danielnaber** [comment]
Closing, as the main issue described in the issue title is fixed.
