### ISSUE TITLE
[en] False positive for 'guard from'

### ISSUE THREAD

**Issue by rillig** [languagetool-org/languagetool#8849]
In a C comment, I wrote:
> Extracts the multiple-inclusion guard from a conditional, if any.

Languagetool marked `guard from`, even though the word `guard` in this case is a noun, not a verb.

Another construed example:
> Meet Matt, the guard from Oklahoma.

**Comment by tiff** [comment]
Thanks, I disabled the rule. It didn't perform well https://github.com/languagetool-org/languagetool/commit/294a82dc6992ddd1cbd4a202a0dac80b41c48fa4#diff-54b065c892e9aa885ae95cc110a0fc4cc77abba8c81e0eb1c417a27261f966afR103526
