### ISSUE TITLE
[DE] Satzanfänge der wörtlichen Rede nach Doppelpunkt+Anführungsstriche oben werde fortgesetzt nicht erkannt

### ISSUE THREAD

**Issue by CaitlinMkaKatie** [languagetool-org/languagetool#8858]
![Screenshot 2023-06-21 104905](https://github.com/languagetool-org/languagetool/assets/129726921/e799912e-36fc-4bee-89f1-41b107800aa3)

**Zitat:**
> _Majid ergänzte: ”**Vorläufigen** Analysen der Terrakottaröhren aus Ardais liegen über allen Erwartungen, was die Qualität angeht. Der Ton ist besser als das, was ich von Terra kenne. Varzil, ist es in Ordnung, wenn ich die alte Technik einer Baumstammröhre den Ardais näher bringe?”_ <
#
**Fehlerbeschreibung:**
Bei jedem Prüfen wird mir angezeigt, dass entweder die Großschreibung oder die Kleinschreibung falsch ist. Das passiert im Wechsel in einem Teufelskreis ohne ein Ende. Klicke ich das Richtige (LK Deutsch Abi1991) heute ab, muss ich es morgen bei allen 700 Seiten meines Buches wieder tun, damit u.a. mein WLAN nicht in die Knie geht.
Es war nicht das erste Mal, dass ein Satz der wörtlichen Rede am Anfang oder Ende falsch als Fehler angezeigt wurde.
Ich bitte darum, dass einer einmal gründlich sich alle Regeln in Zusammenhang mit den Satzzeichen zur wörtlichen Rede in Deutsch ansieht, wie diese eingepflegt sind und ggf. anpasst.

**Comment by tiff** [comment]
Ist behoben
