### ISSUE TITLE
[de] wrong genus for "Abtestat"

### ISSUE THREAD

**Issue by NicoWeio** [languagetool-org/languagetool#8865]
> Die Mail mit **dem Abtestat** solltest du bereits von mir erhalten haben.

LT denkt hier, [_das Abtestat_](https://www.duden.de/rechtschreibung/Abtestat) sei feminin.  Für sich genommen scheint es gar nicht bekannt zu sein (vermeintlicher Rechtschreibfehler). _Antestat_ und _Testat_ haben das Problem nicht. Da das Wort _Abtestat_ aber nicht als solches im Repo zu finden ist, bin ich nicht hundertprozentig sicher, wie nun vorzugehen ist: Zu `added.txt` und `ignore.txt` hinzufügen?

**Comment by tiff** [comment]
Danke! Behoben

**Comment by NicoWeio** [comment]
For future reference: Behoben als Teil von https://github.com/languagetool-org/languagetool/commit/e435062ef5bcb9e17e188cb2dae9644fa97af4b5 und https://github.com/languagetool-org/languagetool/commit/335fc9efc4379b0989f003839c23fb5e86f55dd8
