### ISSUE TITLE
[de] false-positive in KOMMA_VOR_WIE: "Anhänge wie Fotos"

### ISSUE THREAD

**Issue by NicoWeio** [languagetool-org/languagetool#8867]
> Anhänge **wie** Fotos lassen sich in Gmail über einen Download-Button herunterladen.

oder
> Dinge **wie** diese sind schön.

triggern _KOMMA\_VOR\_WIE_, weil _Anhänge_ auch als Verb durchginge. Ich selbst sehe gerade leider keinen einfachen Weg, solche Fälle verlässlich zu berücksichtigen.

**Comment by tiff** [comment]
Behoben als Teil von https://github.com/languagetool-org/languagetool/commit/e435062ef5bcb9e17e188cb2dae9644fa97af4b5
