### ISSUE TITLE
[LO-Add-on] LibreOffice 7.5.5.1 and nightly crashes – 2023-07-01

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8887]
Heya, @FredKruse 

I have been waiting weeks for a release of 7.5.5.1, although I know that the final release will end with a .2 instead of .1.

So, I have installed it minutes ago and also installed the latest LT nightly.

Here is what happened:
![LO7551_LT_20230701](https://github.com/languagetool-org/languagetool/assets/5192600/10805c8b-55ac-42bd-8b7f-546c8442e545)

It crashed!

😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢 😢

**Comment by FredKruse** [comment]
That doesn't sound good. I'm not at home. I will test it when I'm back (a little more than a week).

**Comment by ColeBantam** [comment]
I cannot even install the current snapshots in LibO 7.5.5.1:

![LanguageTool-20230703-snapshot](https://github.com/languagetool-org/languagetool/assets/34094836/4bced771-a96b-4f87-8548-77927ca82831)

But the good news is: the Release-Version of the Plugin (6.1.1) seems to work fine in LibO 7.5.5.1:

![LanguageTool-6 1 1](https://github.com/languagetool-org/languagetool/assets/34094836/ebbf3c52-11bb-441c-8e2e-175123e2fa93)

**Comment by ColeBantam** [comment]
Update. On another System I can reproduce the above crash with the current Snapshot:

![snapshot-crash](https://github.com/languagetool-org/languagetool/assets/34094836/870c445d-cc73-4604-a8db-f44e501ac16e)

**Comment by darkseji** [comment]
Just a comment: the problem might have started in LO 7.5.4. I've just noticed that grammar checking with LT 6.1.1 is not working and I'm not able to turn it on again despite trying out all the options. Everything works fine with LO 7.5.3 and LT 6.1.1. 
![image](https://github.com/languagetool-org/languagetool/assets/63911601/3c09d4c8-f368-4669-a23e-53ad4665f456)

**Comment by FredKruse** [comment]
The problem should be solved for versions 6-2 and 6-3-snaphot. It seems, there was a change in language handling short before release of 6-2. This let an old (not clean programmed) part of code crash.
@danielnaber I created a v6.2.1 which contains the stable version 6.2 OXT. We should release it, I think.

**Comment by FredKruse** [comment]
@marcoagpinto Did you test the last nightly with LibreOffice 7.5.5.1? It should work.
