### ISSUE TITLE
[pt] Idea for rule: “NomeComum + por + Pronome + V.Inf.” → “NomeComum + por + V.Inf.” - 2023-07-07

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8909]
@ricardojosehlima

Heya,

I hope all is fine with you.

As you have noticed, there have been some difficulties to implementing rules.

Today I have installed a new Git client on my Windows and I hope tomorrow to make my first pull request using it if all works well.

The idea I had for a rule was based on a song by Iron Maiden:
```
O professor envia o mensageiro com rapidez por ele saber que o tempo é curto.
> replaces "por ele saber" with "por saber"
Os professores enviam o mensageiro com rapidez por eles saberem que o tempo é curto.
> replaces "por eles saberem" with "por saberem"
```
For: `el(a/e)(s)/est(a/e)(s)`

Is it a good idea for a rule?

Thanks!

❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by ricardojosehlima** [comment]
Hi it seems great. Marco back on track!

**Comment by marcoagpinto** [comment]
Ricardo,

My dear Brother!

There is still a lot to be done in the mission.

🤗 🤗 🤗 🤗 🤗 🤗 🤗 🤗 🤗 🤗 🤗 🤗

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Heya,

My first “pull request”.

It took me three hours to create the rule because I lost practice. 😋 

Here are the results:
```
Portuguese (Portugal): 5 total matches
Portuguese (Portugal): 599999 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```
[6.txt](https://github.com/languagetool-org/languagetool/files/11988740/6.txt)

Thanks!

😄 ❤️ 😋 😛

**Comment by ricardojosehlima** [comment]
All good!

**Comment by marcoagpinto** [comment]
Thank you, Ricardo.

😋
