### ISSUE TITLE
[pt] Idea for rule: “Remover 'o facto/fato de'” - 2023-07-12

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8926]
Heya, @ricardojosehlima

This rule seems easy to create.

Look at the sentences:
```
Isto para mitigar O FACTO DE não ter as páginas dos livros.
Isto para mitigar O FACTO DE ter as páginas dos livros.
```
Could those three words be removed for the structure:
`o fato/facto de [não] VERBOINFINITIVO_PLURAL_SINGULAR`
?

Thanks!

**Comment by ricardojosehlima** [comment]
Hi, I'm not sure if it's a good idea. Fato is a meaningful word and removing it may cause changes in the intended original meaning.

**Comment by marcoagpinto** [comment]
Ahhhhh... thanks!
