### ISSUE TITLE
LT does not reconize the word "coverture"

### ISSUE THREAD

**Issue by patchling** [languagetool-org/languagetool#894]
I have a variety of words that I use that LT does not recognize, sometimes I need a web search to get the spelling/meaning. "Coverture" is one such word.

**Comment by f-knorr** [comment]
I have added "coverture" to the dictionary and it will be online tonight. Please feel free to let us know more words still not recognized by LanguageTool here. (For the sake of simplicity, just add them to this issue.)

**Comment by patchling** [comment]
There are not very many words that I have this problem with, this just happens to be the first word that I encountered since finding your GitHub page.

**Comment by f-knorr** [comment]
OK, so I will close this issue for now. If you find more words, please reopen this issue or create a new one.

**Comment by patchling** [comment]
Gastrectomy

**Comment by MikeUnwalla** [comment]
@patchling , I added 'gastrectomy' (https://github.com/languagetool-org/languagetool/commit/fe3c59919ec25591d0b3740f307baa15b24e86e3)
