### ISSUE TITLE
[pt] LanguageTool  fails to detect very basic subject-verb agreement errors

### ISSUE THREAD

**Issue by hmslima** [languagetool-org/languagetool#8945]
See the two wrongly written sentences just below:

> Os meninos gosta das meninas

> O menino gostam das meninas 

The correct sentence should be:

> Os meninos gostam das meninas

-------------

**EXTRA**

These ones are more complicated. LT doesn't detect that the two sentences just below are wrong:

> Poderá ainda acontecer mais incentivos como esses.

> Deu dez da noite e ele ainda não chegou.

The correct forms are:

> Poderão ainda acontecer mais incentivos como esses.

> Deram dez da noite e ele ainda não chegou.

------------

I took these sentences from [here](https://blog.imaginie.com.br/erro-de-concordancia/).

**Comment by p-goulart** [comment]
Just checked, all of these are fixed, some by gGEC, some by XML. @susanaboatto I'm closing.

<img width="358" alt="Screenshot 2024-04-18 at 3 55 25 PM" src="https://github.com/languagetool-org/languagetool/assets/50704700/cb397fbc-5dca-412b-bc3e-b6c43b574372">
