### ISSUE TITLE
[pt] Idea for rule: “dá” → “confere” - 2023-07-14

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8948]
Heya, @ricardojosehlima

Yes, it is 6am, and I came up with an idea for a scientific/academic/formal rule:
`E isto tudo DÁ aleatoriedade ao jogo.`
to:
`E isto tudo CONFERE aleatoriedade ao jogo.`

I was meditating how to detect the right noun after the “dá” and I came up with words ending in:
“de” → “velocidade”, “integridade”, etc.
“ez” →”rapidez”

And after it, it should work with:
`a, as, à, às, ao, aos`

Is it a good idea?

Academic? Scientific? Formal?

Thanks!

**Comment by ricardojosehlima** [comment]
Now that seems a challenge, but it might work!

**Comment by marcoagpinto** [comment]
Ricardo!

❤️ 😄 😋

**Comment by marcoagpinto** [comment]
Ricardo, I will work on it at 5am.

But I am very happy to see it is a good idea and that it may work.

🤗 🤗 🤗 🤗 🤗

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Hello!

I couldn't wait for 5am, I was so eager.

It took me 10 minutes to write the rule.

```
Portuguese (Portugal): 52 total matches
Portuguese (Portugal): 599999 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[0.txt](https://github.com/languagetool-org/languagetool/files/12054067/0.txt)

Is this it? 20 lines of code? Do you have any suggestions to improve it, or is it good?

Thanks!

```
        <rule id='CIENTÍFICO_DAR_CONFERIR' name="[Universitário][Científico] dar → conferir" > <!-- type="style" tags="picky" tone_tags="academic"-->
            <!--
            It uses filters:
              -de → velocidade, integridade, etc.
              -ez → rapidez, etc.
            -->
            <pattern>
                <marker>
                    <token inflected='yes'>dar</token>
                </marker>
                <and>
                    <token regexp='yes'>.*de|.*ez</token>
                    <token postag='NC.+|AQ.+' postag_regexp='yes'/>
                </and>
                <token regexp='yes'>[aà]s?|aos?</token>
            </pattern>
            <message>Num contexto formal/científico, é preferível escrever 'conferir'.</message>
            <suggestion><match no='1' postag='V.+' postag_regexp='yes'>conferir</match></suggestion>
            <example correction="confere">Esta equação <marker>dá</marker> aleatoriedade ao jogo.</example>
        </rule>
```

**Comment by ricardojosehlima** [comment]
Great! In pt-br, the expressions "dar continuidade" and "dar oportunidade" are ok in formal registers, and "conferir" for both cases sounds strange, so my idea is that these two expressions should be excluded from the pt-br.

**Comment by marcoagpinto** [comment]
> Great! In pt-br, the expressions "dar continuidade" and "dar oportunidade" are ok in formal registers, and "conferir" for both cases sounds strange, so my idea is that these two expressions should be excluded from the pt-br.

Ahhhh... cool... give me 5 minutes just to open the command prompt and folders.

**Comment by marcoagpinto** [comment]
and now processing the sentences... 😋

**Comment by marcoagpinto** [comment]
Ahhhh…

I am very happy with the results!

```
Portuguese (Portugal): 22 total matches
Portuguese (Portugal): 599999 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[1.txt](https://github.com/languagetool-org/languagetool/files/12061235/1.txt)

Basically, I added to the rule:
```
                    <token regexp='yes'>.*de|.*ez
                        <exception regexp='yes'>continuidade|oportunidade</exception>
                    </token>
```

I will create a pull request in a few moments.

Now, only @p-goulart and @susanaboatto can approve changes.


Thank you, dear brother!

There is still a long way to go in the mission.

❤️ ❤️ ❤️ ❤️ 😋 😋 😋 😋 😛 😛 😛 😛
