### ISSUE TITLE
Language tool not detecting common errors.

### ISSUE THREAD

**Issue by testingYadav97** [languagetool-org/languagetool#8962]
I am trying to check the text  using 6.3 snapshot

> There should distinction between charity as well as philanthorpy, with different tax breaks at each other, based at the motivated and impact of donation

The output I receive is 

`{"software":{"name":"LanguageTool","version":"6.3-SNAPSHOT","buildDate":"2023-07-10 05:39:26 +0000","apiVersion":1,"premium":false,"status":""},"warnings":{"incompleteResults":false},"language":{"name":"English (US)","code":"en-US","detectedLanguage":{"name":"English (US)","code":"en-US","confidence":1.0,"source":null}},"matches":[{"message":"Possible spelling mistake found.","shortMessage":"Spelling mistake","replacements":[{"value":"philanthropy"}],"offset":52,"length":12,"context":{"text":"...hould distinction between charity as well as philanthorpy, with different tax breaks at each other, ba...","offset":48,"length":12},"sentence":"There should distinction between charity as well as philanthorpy, with different tax breaks at each other, based at the motivated and impact of donation","type":{"typeName":"UnknownWord"},"rule":{"id":"MORFOLOGIK_RULE_EN_US","description":"Possible spelling mistake","issueType":"misspelling","category":{"id":"TYPOS","name":"Possible Typo"}},"ignoreForIncompleteSentence":false,"contextForSureMatch":0}],"sentenceRanges":[]}`

But when I try the same input on the [ official website](https://languagetool.org/). I get a different output with 13 errors. How to implement the same model?

Note: The publicly available api and other english models (en-GB etc) on website also show the same output with just 2 errors

**Comment by danielnaber** [comment]
There's a test running on languagetool.org, there's no way to get the same results locally.
