### ISSUE TITLE
Invalidate methods in class ResultCache?

### ISSUE THREAD

**Issue by JFormDesigner** [languagetool-org/languagetool#898]
It would be great to have some 'invalidate' methods in class `ResultCache` to remove specific words/keys from the cache or invalidate the whole cache.

Especially `ResultCache.invalidate(String word)`, which removes all cache entries that contain `word` in `InputSentence.text` or in `SimpleInputSentence.text`, is needed for some "Ignore Word" functionality in a text editor (using `SpellingCheckRule.addIgnoreTokens(List<String> tokens)`.

Without any 'invalidate' method in `ResultCache`, the only way is to drop the `JLanguageTool` instance (including cache) and start with a new`JLanguageTool` instance (and new cache). But this is very slow.

To workaround this problem, I've subclassed `ResultCache` and added `void invalidate(String word)`.
See: https://github.com/JFormDesigner/markdown-writer-fx/blob/feature/spellchecker/src/main/java/org/markdownwriterfx/spellchecker/ResultCacheEx.java#L86-L120

But since there is no access to `ResultCache.matchesCache` and `sentenceCache` I ended up with overriding all methods and implement own caches. And I had to use reflection to access private fields `InputSentence.text` and `SimpleInputSentence.text`. It works for now, but it is a hack.

It would be much better to have some API in LanguageTool to invalidate parts of cache (or whole cache).

**Comment by danielnaber** [comment]
> Without any 'invalidate' method in ResultCache, the only way is to drop the JLanguageTool instance (including cache) and start with a newJLanguageTool instance (and new cache). But this is very slow.

Have you tried it? Creating a JLanguageTool instance should be very fast, we do it all the time on languagetool.org. What you should not do is create a new language every time using the constructor (e.g. `new GermanyGerman()`).

**Comment by JFormDesigner** [comment]
Sure, creating a JLanguageTool instance is fast, but I want to avoid this. I want **continue with the existing cache** and only **remove some entries from that cache** when the user uses "Ignore Word".

Background: my app is a [markdown editor](https://github.com/JFormDesigner/markdown-writer-fx) and LanguageTool is used for automatic spell/grammar checking while the user types (delayed by 500ms and in a background thread). So nearly the same text is checked very often and the cache reduces the duration dramatically (e.g. depending on text size from 1500ms to 15ms).

**Comment by danielnaber** [comment]
I have just added `protected` getter method for the fields you need. Is that good enough? I think the invalidation is a rather specific use case and I think it's acceptable that one needs to sub class `ResultCache` for that.

**Comment by JFormDesigner** [comment]
OK, that's great. Thanks.

Could you please also add `public` getters for `InputSentence.text` and `SimpleInputSentence.text`?
Or make those `final` fields `public`?
Otherwise I can not search the cache for sentences that contain a specific word.

BTW is there a reason that `InputSentence` is not a subclass of `SimpleInputSentence`?

**Comment by danielnaber** [comment]
> Could you please also add public getters for InputSentence.text and SimpleInputSentence.text

Done.

> BTW is there a reason that InputSentence is not a subclass of SimpleInputSentence?

Not sure, I think `SimpleInputSentence` is so simple with its two fields that it's not worth it.

**Comment by JFormDesigner** [comment]
Many thanks 👍
