### ISSUE TITLE
[pt] Idea for rule: “se se” → “ao se” - 2023-07-20

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#8996]
@ricardojosehlima

Heya, Ricardo,

I came up with an idea for a rule:
`Contudo, SE SE conseguir delimitar a área de treino, é viável.`
To:
` Contudo, AO SE conseguir delimitar a área de treino, é viável.`

Is it a good idea?

Should it only work with a verb after the “se se”?

Thanks!

**Comment by ricardojosehlima** [comment]
Hmmm, se indicates a condition, while ao looks like it's already done, so I don't see both sentences as synonymous.

**Comment by marcoagpinto** [comment]
Ahhhhh... thanks!
