### ISSUE TITLE
[pt] Idea for rule: “dar valor” → “valorizar” - 2023-07-20

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#9000]
@ricardojosehlima

Heya, again,

I was exercising and this popped-up on my mind:
`“Ele não dá valor à mulher.”`
to:
`“Ele não valoriza a mulher.“`

Verb “dar” + "valor” + “a(s)/o(s)/à(s)/ao(s)”

Is it a good idea?

Thanks!

**Comment by ricardojosehlima** [comment]
Sounds good!

**Comment by marcoagpinto** [comment]
Ahhhhhhhhhhh…

Dear brother, Ricardo,

Thank you!

A mission for tonight!

😄 😋 ❤️

**Comment by p-goulart** [comment]
IMO it doesn't fit any of the [tone tags](https://dev.languagetool.org/style_tone_tags#description-of-tonetags) other than the (as yet unimplemented) `shorten_it`. It doesn't make it particularly clearer, more professional-sounding, formal, more persuasive, etc.

I don't think it's a particularly useful rule, but I suppose if you want to add it, it should be set to `picky` until we have support for `shorten_it`. @susanaboatto ?

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

We are stuck on this: https://github.com/languagetool-org/languagetool/issues/9007

**Comment by susanaboatto** [comment]
I agree @p-goulart. If you add the rule, @marcoagpinto, make sure to add `<!--IDEA shorten_it-->` to it so we can tag it once `shorten_it` is active.

**Comment by marcoagpinto** [comment]
@susanaboatto 

I have created the rule but have been unable to test it because TESTRULES PT doesn't work.

I will wait until the command is working so that I can test it.

```
        <rule id='DAR_VALOR_VALORIZAR' name="Simplificar: Verbo 'dar' + valor → valorizar">
            <!-- IDEA shorten_it -->
            <pattern>
                <marker>
                    <token regexp="yes" inflected='yes'>dar</token>
                    <token>valor</token>
                    <token regexp='yes'>às?|aos?</token>
                </marker>
            </pattern>
            <message>&simplify_msg;</message>
            <suggestion><match no='1' postag='V.+' postag_regexp='yes'>valorizar</match> <match no='3' postag='SPS00:DA0(..)0' postag_replace='DA0$10'>o</match></suggestion>
            <example correction="valoriza">Ele não <marker>dá valor à</marker> mulher.</example>
        </rule>
```

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Heya, Ricardo,

TESTRULES PT is working again.

Here are the results of the rule:
```
Portuguese (Portugal): 5 total matches
Portuguese (Portugal): 599999 total sentences considered
Portuguese (Portugal): ø0.00 rule matches per sentence
```

[0.txt](https://github.com/languagetool-org/languagetool/files/12155707/0.txt)

```
        <rule id='DAR_VALOR_VALORIZAR' name="Simplificar: Verbo 'dar' + valor → valorizar" default="temp_off"> 
            <!-- IDEA shorten_it -->
            <pattern>
                <marker>
                    <token inflected='yes'>dar</token>
                    <token>valor</token>
                    <token regexp='yes'>às?|aos?</token>
                </marker>
            </pattern>
            <message>&simplify_msg;</message>
            <suggestion><match no='1' postag='V.+' postag_regexp='yes'>valorizar</match> <match no='3' postag='SPS00:DA0(..)0' postag_replace='DA0$10'>o</match></suggestion>
            <example correction="valoriza a">Ele não <marker>dá valor à</marker> mulher.</example>
            <example correction="valoriza o">Ele <marker>dá valor ao</marker> trabalho do Rui.</example>
        </rule>
```

❤️ ❤️ ❤️ ❤️ 

Thanks!
