### ISSUE TITLE
OutOfMemoryError:  Minimum server requirements for HTTP Server

### ISSUE THREAD

**Issue by RealDeviil** [languagetool-org/languagetool#902]
Hello,

I have done some searching, but I could not find the minimum server requirements for the HTTP Server:  http://wiki.languagetool.org/http-server.

I have been testing a recent build of languagetool that I compiled myself with Maven on a cheap Linux VPS. I am using this with the languagetool-website (https://github.com/languagetool-org/languagetool-website) project code to create a veritable clone of https://www.languagetool.org.  

My current VPS server specs are very meager:

> 2 X86 64bit Cores
> 2GB memory
> 200Mbit/s Unmetered

I start/run the HTTP Server with the following command:

`nohup java -cp /var/www/html/download/snapshots/languagetool/languagetool-standalone/target/LanguageTool-4.0-SNAPSHOT/LanguageTool-4.0-SNAPSHOT/languagetool-server.jar org.languagetool.server.HTTPServer --allow-origin "xxxxxxxx" --port 8081 > /var/log/java/access 2>/var/log/java/error &`

I have been logging errors, and it seems that every few weeks I run out of available memory:

```
java.lang.OutOfMemoryError: Java heap space
	at org.languagetool.server.LanguageToolHttpHandler.readerToString(LanguageToolHttpHandler.java:290)
	at org.languagetool.server.LanguageToolHttpHandler.getRequestQuery(LanguageToolHttpHandler.java:279)
	at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Obviously, I acknowledge that my current server has a very small amount of total memory. But what concerns me is, with virtually nothing else running on the server and very minimal traffic to the website (languagetool-website) that consumes the HTTP Server, available memory seems to gradually decrease over time. 

I can only fathom one or more of the following causes:

1) Current server does not have enough total memory (a given)
2) Misconfiguration or incorrect implementation of the HTTP Server
3) Possible memory leak
4) Something else?

Do you have any thoughts as to why I am receiving these periodic errors, and any recommendations concerning the minimum server requirements and optimal configuration for X amount of website (languagetool-website) traffic (consuming the HTTP Server)?

Also, would periodically restarting the HTTP Server (either via a scheduled task or by "hooking" into the Java code itself) be an adequate solution? How do you guys approach this, in general, given that any server has a finite amount of available memory?

Thank you.

**Comment by danielnaber** [comment]
You should set the memory option for the JVM. On languagetool.org, we use `-Xmx2600M`, so with 2GB RAM, you might want to try `-Xmx1000M`. We restart the process every day on languagetool.org to update to the latest build, so if there's indeed a memory leak, we wouldn't notice it.

**Comment by RealDeviil** [comment]
Hi,

Thanks for your response!

So are you suggesting that, when running the HTTP Server, the JVM's maximum heap size should ideally be set to roughly 1/2 of available physical memory? Or is there some other general rule for setting the JVM's maximum heap size (when running the HTTP Server)?

In general, if we scale up the amount of RAM, is there some limit to how high we can set the JVM's maximum heap size (or some point of diminishing returns), when running the HTTP Server?

Also, how much available RAM is there on the languagetool.org server (or servers)?

FYI - I don't have much experience with Java development or deployment, so I appreciate your patience.

Thanks again.

**Comment by danielnaber** [comment]
There's no general rule, it depends on the number of languages being used, the concurrent requests, the text length etc. 2600MB should be enough for most use cases, if you don't have that much, try with less and see how that works.

**Comment by danielnaber** [comment]
Doesn't seem to be a bug, closing.

**Comment by neorganic** [comment]
@danielnaber  Hello, when using  LT standalone via command line, how might you specify how much languages to use ? 

>  it depends on the **number of languages** being used, the concurrent requests, the text length etc.

**Comment by danielnaber** [comment]
You cannot turn off languages. But if you never send a check request with language X, no memory will be used for language X.
