### ISSUE TITLE
LT-Bugfehlermeldung Juli.2023

### ISSUE THREAD

**Issue by MasterDallun511** [languagetool-org/languagetool#9022]
Moin liebes LanguageTool

![grafik](https://github.com/languagetool-org/languagetool/assets/78316155/ae9e201d-e3ec-417b-be6c-2d383fb8814c)

Diese Fehlermeldung kam, nachdem das LibreOffice zuvor abgestürzt ist und neu gestartet wurde.

Grüße Dallun511

**Comment by FredKruse** [comment]
Vielen Dank für die Fehlermeldung.
Leider ist das ein Fehler, der von LT aus nicht korrigiert werden kann. Beim Absturz von LO scheinen Prozesse hängen geblieben zu sein, die verhindern, dass LT notwendige Verbindungen zu LO aufbaut (dadurch ist das flatPara-Objekt null).
Als Nutzer kannst du nur versuchen, noch laufende LO-Prozesse zu finden und diese zu beenden oder im Zweifelsfall Windows ganz neu starten, bevor du LO wieder aufrufst.

**Comment by MasterDallun511** [comment]
Aus diesem Grund habe ich angegeben, dass zuvor LO abgestürzt ist und die Fehlermeldung nach dem Neustart von LO kam.

Wenn du den Fehler nicht beheben kannst, weil dieser nicht in LT ist, sondern in LO ist dies nicht schlimm.

Grüße Dallun511
