### ISSUE TITLE
'to' after modal verbs in English

### ISSUE THREAD

**Issue by LeahKorol** [languagetool-org/languagetool#9029]
Hi,

In several languages, the sentence structure 'You can to do it' might be considered grammatically correct. However, in English, the usage of 'to' after modal verbs is incorrect. Presently, LT fails to identify this particular mistake.
![image](https://github.com/languagetool-org/languagetool/assets/113800719/205dba10-56ee-4b53-a643-f9e8afd6c4cb)

To improve Language Tool's accuracy, I suggest implementing a rule that flags instances of 'to' following modal verbs. 
 May I proceed with resolving this issue?

**Comment by Luisa-LT** [comment]
Hi @LeahKorol, thank you for pointing this out to us and for creating this issue. You are of course welcome to proceed with solving the problem. Please just remember to set the rule `default="temp_off"` to test it first. :-)
