### ISSUE TITLE
[en] "an URL" seems acceptable

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#9051]
if URL is pronounced like "earl"

**Comment by evan-defran-lt** [comment]
Hi @donnerpeter, thanks for the suggestion! 

For the moment, it seems that major dictionaries like [M-W](https://www.merriam-webster.com/dictionary/URL) and [Cambridge](https://dictionary.cambridge.org/dictionary/english/url?q=URL) report 'URL' pronounced as an initialism. [Wiktionary](https://en.wiktionary.org/wiki/URL) reports pronunciation as an acronym, but I'm not certain how common this is. [Google's Ngram viewer](https://books.google.com/ngrams/graph?content=a+URL%2Can+URL&year_start=1800&year_end=2019&corpus=en-2019&smoothing=3) suggests that it's not very common, at least not for now. 

This of course might change in the future!

**Comment by donnerpeter** [comment]
We (in IntelliJ) have got another similar report, now with lowercase `an url`
