### ISSUE TITLE
Do not expand the parent checkbox on double click on the checkbox

### ISSUE THREAD

**Issue by evandrocoan** [languagetool-org/languagetool#907]
It is ok to expand it when doing a double click, but not when the double click is on the check box :black_square_button: region

![back2](https://user-images.githubusercontent.com/5332158/36217683-4d88e2a8-1199-11e8-9020-90083489f3ba.gif)

**Comment by LAVEEN** [comment]
Hi,i'm working on this issue.Will it be ok if i only allow expansion  on expand/collapse icon which is  next to a node and restricting expansion  everywhere (checkbox,node text )?

**Comment by danielnaber** [comment]
> Will it be ok if i only allow expansion on expand/collapse icon which is next to a node and restricting expansion everywhere

Double click on the text should expand/collapse, I think.

**Comment by LAVEEN** [comment]
ok thanks for the info .

**Comment by LAVEEN** [comment]
hi, i have resolved the issue.But im getting this while pushing my changes

Pushing to https://github.com/languagetool-org/languagetool.git
remote: Permission to languagetool-org/languagetool.git denied to LAVEEN.
fatal: unable to access 'https://github.com/languagetool-org/languagetool.git/': The requested URL returned error: 403


Can you please help me,as this is my first push.

**Comment by LAVEEN** [comment]
Hi ,i have resolved the issue but im getting this while pushing to master branches

Username for 'https://github.com': laveen
Password for 'https://laveen@github.com': 
remote: Permission to languagetool-org/languagetool.git denied to LAVEEN.
fatal: unable to access 'https://github.com/languagetool-org/languagetool.git/': The requested URL returned error: 403

**Comment by danielnaber** [comment]
You cannot push as you're not a committer. Please create a pull request from your change (see github documentation on how to do that).

**Comment by LAVEEN** [comment]
Hi @danielnaber ,first of all thanks for the info.I was able to create pull request.

**Comment by LAVEEN** [comment]
Hi i have added two pull request for this issue.Please review this.

**Comment by evandrocoan** [comment]
You do not need to open multiple pull requests to fix the same issue. Just push new commits to your current branch. Please, close #928 and add the file to #927

From the name of you pull request branch, I assume you are using the GitHub web interface. You should use a local git client. I would recommend, using the Smartgit interface: https://www.syntevo.com/smartgit/ to handle git.

**Comment by LAVEEN** [comment]
Hi,sorry for this,but next time will make sure the everything is in place and thanks for the url

**Comment by LAVEEN** [comment]
Hi,i have push new commits to a single branch.Please have a look @danielnaber @evandrocoan .

**Comment by danielnaber** [comment]
@pminos Maybe you could have a look, as you know more about Swing than I do?

**Comment by pminos** [comment]
@danielnaber Yes, I will.

**Comment by pminos** [comment]
@danielnaber I think there is a simpler fix. We can listen for tree expansion events and cancel the event if the mouse cursor is above the checkbox.

I made a pull request (#936) if you want to review the solution.

**Comment by danielnaber** [comment]
> I think there is a simpler fix. We can listen for tree expansion events and cancel the event if the mouse cursor is above the checkbox.

Thanks, feel free to merge the PR.
