### ISSUE TITLE
[nl] another rule that does not trigger

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#9106]
![afbeelding](https://github.com/languagetool-org/languagetool/assets/8479998/ea1bc34a-2e40-4bcb-984b-a7a0d7fedcf4)

**Comment by baarsrj** [comment]
There is an entry for this in the file that forces lowercase. I don´t know if this rule has been disabled, or just is not functioning.  
Let's leave this for Mark to handle this. I think a discussion is needed.

**Comment by danielnaber** [comment]
That's `CheckCaseRule` and it's supposed to be active. Would be great if @mark-baas could have a look once he's back.

**Comment by baarsrj** [comment]
I think the abstract rule has the flaw.  There is no check for fullupper, just for firstupper.

**Comment by mark-baas** [comment]
Seems like you're right Ruud, it only triggers when it's written with firstupper. I'll check it out.

**Comment by baarsrj** [comment]
It should report any other case, except firstupper at the start of the sentence.


test entries for 'pc'
I hate my pc. : okay
I hate my Pc. : wrong
I hate my pC. : wrong
I hate my PC. : wrong
Pc is dead: okay
'Pc is dead': okay  (also for pretty quotes)
'PC is dead': wrong  (also for pretty quotes)
"Pc is dead': okay (also for pretty quotes)
"PC is dead": wrong  (also for pretty quotes)

**Comment by mark-baas** [comment]
NL_CHECKCASE seems to work again, different bad variations of 'pc' are being detected. Added PC to simple replace.

**Comment by baarsrj** [comment]
I assume you removed PC=pc from replace.txt? There are more of those words in replace. You could check the R's in the nightly for those.Good to hear the replace rule has been fixed.Op 29 aug. 2023 09:35 schreef mark-baas ***@***.***>:
NL_CHECKCASE seems to work again, different bad variations of 'pc' are being detected. Added PC to simple replace.
