### ISSUE TITLE
[en] Grammar error is not detected

### ISSUE THREAD

**Issue by DrPolaris** [languagetool-org/languagetool#9124]
![image](https://github.com/languagetool-org/languagetool/assets/54666508/032f746d-52fb-4c8f-b9fb-837fcb574eb3)
The correct usage is "She is waiting for him". Please correct me if I am wrong. 

Thank you.

**Comment by evan-defran-lt** [comment]
Hi @DrPolaris, you are correct, but it looks like LT does detect this error. 
<img width="487" alt="Screenshot 2023-09-13 at 12 47 17" src="https://github.com/languagetool-org/languagetool/assets/112640985/2ed1b2c5-9ee3-4c0c-95bb-4edb533c4a61">
