### ISSUE TITLE
look of options dialog on Kubuntu

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#914]
The options dialog does not flow very well, nor doe the boxes look okay.

**Comment by danielnaber** [comment]
Could you provide a screenshot?

**Comment by baarsrj** [comment]
![afbeelding](https://user-images.githubusercontent.com/8479998/37955033-b49a3c84-31a7-11e8-9471-92f49c53e505.png)

**Comment by baarsrj** [comment]
It is mostly the 'Moedertaal' that is positioned and sized badly.

**Comment by baarsrj** [comment]
(Sorry for the late reaction; I don't see the GIT e-mails, since there are too many of those.

**Comment by danielnaber** [comment]
@FredKruse Would you be interested in fixing this?

**Comment by pminos** [comment]
@danielnaber I can fix this easily, I just have to change the window width. But I saw that the version changed. Should I wait for the release? Do you want FredKruse to look it?

**Comment by danielnaber** [comment]
The version 4.1 has already been released, feel free to make a fix now. Thanks!
