### ISSUE TITLE
[pt] "Via Láctea" doesn't need hyphen

### ISSUE THREAD

**Issue by hmslima** [languagetool-org/languagetool#9140]
When we write the expression _"Via Láctea"_, LT (LanguageTool) points an error and says that _"Esta palavra é hifenizada."_ (This word is hyphened), but this expression doesn't need a hyphen.

**Proofs:**

* [Ciberdúvidas da Língua Portuguesa - As palavras compostas e o AO](https://ciberduvidas.iscte-iul.pt/consultorio/perguntas/as-palavras-compostas-e-o-ao/30913)
* [Dicionário Priberam](https://dicionario.priberam.org/Via-L%C3%A1ctea)
* [Dicio.com.br](https://www.dicio.com.br/lactea/)
* [Grande Dicionário da Língua Portuguesa da Porto Editora _(to check this one you'll have to acquire the book...)_](https://www.amazon.com.br/Grande-Dicion%C3%A1rio-L%C3%ADngua-Portuguesa-Editora-ebook/dp/B00HGW83U4)
* [Wikipédia - Via Láctea _(the Wikipedia article doesn't use hyphen for "Via Láctea")_](https://pt.wikipedia.org/wiki/Via_L%C3%A1ctea)

All of these sources corroborate that "Via Láctea" _(without hyphen)_ is correct. Perhaps, the expression with hyphen is grammatically acceptable, but I just want to say that there is no way that the expression without hyphen is wrong.

**Comment by iagocarmona** [comment]
Hello, can I  work on this issue ?

**Comment by p-goulart** [comment]
@iagocarmona I've committed a fix in 915e541. If you want to work on a similar issue in the future, though, just go right ahead! You can also revise that file and update it if there's more stuff there that's not quite right – just add me or @susanaboatto as reviewers of your PR.

@hmslima thanks for pointing this out! We've recently come back to working more actively on optimising the compounding logic, revising a lot of the data that's there, splitting into smaller rules, improving the messages, etc. If you notice something else that seems off, don't hesitate to make an issue.
