### ISSUE TITLE
[nl]? picky rules in style.xml

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#9141]
I get the idea those are not working.

I tried this in the editor:

Da's een echte fout.

It is one of the rules in : 
`<category id="SLORDIG" name="Slordig, maar informeel geaccepteerd" type="style" tone_tags="formal" is_goal_specific="true">
`
The rules in that group should trigger in almost every type of communication, except in chat and colloqial situations.
Imho these are not acceptable in business email. Maybe in personal email to a close, not to highly educated, friend, or a blog.  In a letter of application e.g., it would mean immediate rejection of the application form.

Anyway, these rules are not triggered in a command line test. So it is not possible to test them.

IMHO the command line test should test all rules.

Furthermore, I think there is more than formal and informal. Most used Dutch  language is not informal, nor informal. It avoids both. So in that language neither rules to promote informal, nor rules to promote formal should be triggered. Only the rules for 'too informal' or 'too formal'. But I do not see classes like that.

**Comment by mark-baas** [comment]
The attribute "is_goal_specific" has been removed, it should not have been active on this specific category. After removing it, these rules will apply to both the formal toneTag and whenever no writing goal is selected.
