### ISSUE TITLE
[nl] invalid characters in output

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#9144]
![afbeelding](https://github.com/languagetool-org/languagetool/assets/8479998/30c8c4df-4cba-4a49-87be-ffa0bf57249d)

Even after specifying UTF-8 as encoding and all settings and system in UTF-8.

System: Kubuntu
![afbeelding](https://github.com/languagetool-org/languagetool/assets/8479998/3cf8c959-2428-4ebe-b51c-2d792a41a94f)

**Comment by mark-baas** [comment]
Not sure how I can replicate this, typing it over works well. Do you have any text file with the faulty sentence @baarsrj?

**Comment by baarsrj** [comment]
This is on Linux on the command line, running 
java -jar languagetool-commandline.jar -c "UTF-8" -l nl --level PICKY --enable-temp-off test.txt > output.txt

It never was faulty, until it suddenly was. I don´t know if it is a system thing, or a LT thing.
Every 'pretty quote', and every accented char is misrepresented, making the test run hard to use.

**Comment by baarsrj** [comment]
Found out is some issue deep in KDE settings, caused by an update
