### ISSUE TITLE
[de] First suggestion for "Reisenrad" should be "Riesenrad"

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#9145]
![grafik](https://github.com/languagetool-org/languagetool/assets/30999326/8b1890f1-c641-4f80-96ed-2d7f1a875555)

The first suggestion should be "Riesenrad".

**Comment by Luisa-LT** [comment]
Danke!
https://github.com/languagetool-org/languagetool/commit/e04f554018277edddbb7aa795f3ea842d4c3fb73
