### ISSUE TITLE
Error: 'jp' not a language code known to LanguageTool

### ISSUE THREAD

**Issue by keiyukawa** [languagetool-org/languagetool#9154]
With Microsoft Word 16.16.27, I get the following error when trying to use LanguageTool:

<img width="677" alt="Screen Shot 2023-08-21 at 8 13 46 PM" src="https://github.com/languagetool-org/languagetool/assets/142470737/c8e294e4-e005-401c-af82-46cf317ba5d9">

I do see `ja-JP` in the list and am assuming it's the same thing?

**Comment by Luisa-LT** [comment]
Hi @keiyukawa, can you try using the language code "ja-JP" instead of only "jp"? If that doesn't help, can you please send a screenshot of where you entered the language code? Thanks!

**Comment by schurigeln** [comment]
@keiyukawa Thank you for bringing this to our attention. We sincerely apologize for any inconvenience caused. Rest assured, we're prioritizing your concern and will work diligently to address it promptly.

**Comment by keiyukawa** [comment]
@schurigeln This now seems to be working for me after the last update. Thank you!
