### ISSUE TITLE
How to limit the maximum request size to the language server?

### ISSUE THREAD

**Issue by evandrocoan** [languagetool-org/languagetool#916]
Because if the request is too big, the Chrome add-on just times out the server just waist this time.

Related:

1. https://github.com/languagetool-org/languagetool/issues/902 OutOfMemoryError: Minimum server requirements for HTTP Server 
1. https://github.com/languagetool-org/languagetool/issues/904 Exhaust system CPU with big text file input
1. https://forum.languagetool.org/t/maximum-text-size-limited-on-languagetool-org/1200

**Comment by danielnaber** [comment]
Use e.g. `maxTextLength=20000` in the properties file given to the server with the `--config` option.

**Comment by evandrocoan** [comment]
And if I do not use an configuration file?

I just start it with:
```python
java -cp languagetool.jar org.languagetool.gui.Main -t
```
This runs a server because on the GUI I activated the option to run a server. I just tried creating a file with:
```
echo maxTextLength=20000 > server.properties
java -cp languagetool.jar org.languagetool.gui.Main -t --config server.properties
```

It seems to not be complaining about any errors.

**Comment by evandrocoan** [comment]
What are the command line references documentation pages?

I could only find this one about `languagetool-commandline.jar`:

1. http://wiki.languagetool.org/command-line-options

**Comment by danielnaber** [comment]
> And if I do not use an configuration file?

A maximum size is not supported in that case.

> What are the command line references documentation pages?

Call `java -jar languagetool.jar --help` to get a usage.
