### ISSUE TITLE
Remove trove4j dependency

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#9203]
LanguageTool is currently using Trove4J for more memory-efficient storage. Unfortunately, this library is quite old, not maintained, and there are better alternatives. IntelliJ is using LanguageTool as a bundled grammar checker. The IDE is trying to remove Trove from classloading completely, so we'd prefer to switch to [fastutil](https://github.com/JetBrains/intellij-deps-fastutil). It has a somewhat larger jar size (6 MB), but is actively maintained and more performant.

We can prepare a pull request for this migration if there are no objections.

**Comment by SteVio89** [comment]
Hi @donnerpeter 

you can prepare a pull request for this migration. Thank you!

**Comment by donnerpeter** [comment]
@SteVio89 any updates? :)

**Comment by SteVio89** [comment]
Sorry again for the delay, we also need to change the code in our premium repository for this change. I have it on my list, but did not make it yet. I will solve this as soon as possible.

**Comment by donnerpeter** [comment]
@SteVio89  Any progress?
