### ISSUE TITLE
Firefox Addon - Other Servers don't work

### ISSUE THREAD

**Issue by H1ghSyst3m** [languagetool-org/languagetool#9217]
I can't use my own language server in Firefox.

In the settings I selected "LanguageTool server: Other server".

I entered my domain https://lgt.si......us.com/v2 and after I entered something a red "X" appeared with the error message:

Error in German: Verbindung zu https://lgt.si........us.com/v2/check fehlgeschlagen – bitte prüfen Sie Ihre Internetverbindung oder versuchen Sie es in einer Minute erneut (#1, code=0)

But the same domain works with Chrome and Edge.

**Comment by danielnaber** [comment]
It's `--allow-origin`, not `--allow-origing`. Not setting this leads to the server working for Chrome, but not for Firefox.

**Comment by H1ghSyst3m** [comment]
Sorry I just mistyped it here in GitHub

I used --allow-origin

java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 6500 --allow-origin

**Comment by danielnaber** [comment]
Please also try without the `"*"`. If that doesn't help, I don't know what the issue might be. Maybe some add-on or setting in your Firefox blocking the request.

**Comment by H1ghSyst3m** [comment]
It worked. 😊👌,

It worked after deleting `"*"`

**Comment by H1ghSyst3m** [comment]
Thanks
