### ISSUE TITLE
Long sentence rule marks whole sentence

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#923]
The `LongSentenceRule` marks the whole sentence, covering other errors. On languagetool.org, even if you ignore the rule, the other errors stay hidden (but that's another bug). I'll commit a fix that changes this behavior. 

@baarsrj  For Dutch, I suggest removing XML rules `MEER_DAN_xx_WOORDEN` and activate `LongSentenceRule` in `Dutch.java` instead (`LongSentenceRule(messages, false)` -> `LongSentenceRule(messages, true)` should be enough for that).

**Comment by danielnaber** [comment]
The new message show to the user is now "This sentence is over {0} words long at the marked position, consider revising". @MikeUnwalla Do you think that's a good English message? I thought I needed to change the message to make clear what the meaning of the marker is now.

**Comment by MikeUnwalla** [comment]
Hi @danielnaber , the message is fine. (If I understand correctly, only 1 token is marked.) A shorter message is "This sentence is x words long at... " where x is 1 more than the max number of words.

**Comment by baarsrj** [comment]
I will not object to anyone adding/activiting this rule for Dutch. Would not know how to myself. Disabled length of sentence rules in xml.

**Comment by danielnaber** [comment]
It's activated now, please test it tomorrow when it's live on languagetool.org.

**Comment by MikeUnwalla** [comment]
After I selected the style rule, it worked for the snapshot.

The rule does not work for languagetool.org. Must I select the rule? If yes, how?

**Comment by danielnaber** [comment]
> The rule does not work for languagetool.org. Must I select the rule? If yes, how?

I think the rule is only active for Dutch and Portuguese.

**Comment by danielnaber** [comment]
Fix seemed to work fine for Dutch.
