### ISSUE TITLE
Windows 10 DPI scaling problem

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#924]
I am reporting this problem for a friend.

LanguageTool suffers from the DPI scaling problem common to older Java programs running on Windows 10. Window contents appear very small (see screenshot)

![image](https://user-images.githubusercontent.com/5816160/36851496-40eb86a8-1d61-11e8-8833-9ce9b5962ca4.png)

Screenshot details:
LanguageTool.jar running on Windows 10
4k Monitor (Display 250% / Resolution 3840 x 2160 (Recommended)
Eclipse.exe running
Eclipse.exe file Properties > Compatibility setting “Override high DPI scaling behaviour”

Windows 10 does not present the Compatibility settings tab for *.jar files.

**Comment by danielnaber** [comment]
I think this is fixed with Java 9 (i.e. it's a Java issue, not a LT issue) - which version of Java is your friend using?

**Comment by MikeUnwalla** [comment]
He's using Java 8. Thanks for the clarification.

**Comment by rpin42** [comment]
I'm using Java 8. 
Java 9 is not available on Java.com yet. Do you know something about this?

**Comment by danielnaber** [comment]
It's available at https://www.oracle.com/java/java9.html
