### ISSUE TITLE
[pt] LT failing to identify the language inside tables

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#9246]
Hi,
  As can be seen in the attached image, LT wrongly identifies pt-br as the language in the table. This time it considered to be Italian, but sometimes it identifies it as Catalan. After fixing it, when closing and then opening the document again, the misidentification returns.
Using Google Docs in a Chrome, Ubuntu 20.04.
P.S.: All the "new" words (PROJEXT, CHATGPT) have already been added to dictionary.

![Captura de tela de 2023-09-04 14-39-07](https://github.com/languagetool-org/languagetool/assets/36453534/d3ae0d44-8bb0-49a9-9f3d-f905cace9b15)

**Comment by danielnaber** [comment]
Thanks for your report. Could you share the document (maybe with sensitive information removed), so we can debug this? Also, have you made sure your setting are correct as documented at https://languagetooler.freshdesk.com/en/support/solutions/articles/44001932886?

**Comment by ricardojosehlima** [comment]
Thanks for the fast answer!
In the language setting, I don't mark Mother Tongue because it appears only the flag of Portugal and am afraid to get unwanted suggestions; as for Preferred Languages, it's only pt-br and English.
Here goes the attached file, it's just my weekly schedule - you can edit it if you want it, it's only a copy, the original file is another.
https://docs.google.com/document/d/1ulaN0LaqCJ7B8TDaQdCpJFHhf3H6uLt1dFMXReWfLZA/edit?usp=sharing

**Comment by danielnaber** [comment]
Unfortunately, it's difficult to fix this. The "I" in "LING I" gets turned into lowercase and is then considered an Italian word. Other Italian words that confuse the detection: aula, parte, passo, qua, qui, de, e

**Comment by ricardojosehlima** [comment]
ok, thanks! I replaced all the new words (qua, qui, projext, discped, elet) for actual pt-br words and then it worked, LT correctly identifies it as pt-br after closing and opening it.
