### ISSUE TITLE
[Wrong suggestion] with the intention to (doing)

### ISSUE THREAD

**Issue by OrangeGirlSophie** [languagetool-org/languagetool#9257]
Hi, I notice this mistakes. The corrections should be "with the intention of doing" or "with the intention to do"
![Screenshot 2023-09-05 103440](https://github.com/languagetool-org/languagetool/assets/81448086/c96784df-1707-45b2-ae02-c173ad60a4b6)

**Comment by evan-defran-lt** [comment]
Hi @OrangeGirlSophie, thanks for flagging this to us. I made some changes, so you shouldn't get this incorrect suggestion any more.
