### ISSUE TITLE
[de] Improve suggestions for typo "schammiger"

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#9264]
![grafik](https://github.com/languagetool-org/languagetool/assets/30999326/a2e8885c-aa57-4105-9113-75c4624fb417)

I think "gammliger" shoud not be in this list at all, "schlammiger" and "schwammiger" should be the first suggestions.

**Comment by Luisa-LT** [comment]
Thank you, @Discostu36, for pointing this out. Unfortunately, the order of the suggestions is not pre-definable. If there were only 1 right suggestion, we could offer just this 1 suggestion. In this case, as there is more than just 1 correct suggestion (schlammiger/schaumiger/schwammiger...) the user can choose the most proper correction.

**Comment by Discostu36** [comment]
after some trial and error (😊 ) I have created a pull request for a partial fix to at least get the "schwammiger" suggestion
