### ISSUE TITLE
[it] Corrections for the settings page of the extension

### ISSUE THREAD

**Issue by PavanLuca** [languagetool-org/languagetool#9277]
That sentence 👇 means literally **Clearly, it works that with the synonyms**, it's not much polite and correct. I suggest **Funziona anche con i sinonimi**, that means **It also works with synonyms**.
![immagine](https://github.com/languagetool-org/languagetool/assets/123581658/9cf7b73e-a3f3-40be-9287-c12242303f3b)

---
That sentence 👇 means **This domain hasn't been added yet. Press ENTER to add it.** but there's no domain really written there to say so. The best sentence is **Non hai ancora aggiunto alcun dominio**, that means **You haven't added any domain yet**.
![immagine](https://github.com/languagetool-org/languagetool/assets/123581658/6c5c5523-6c90-4fd4-aec1-4b839727e20c)

---
disconnetto (I disconnect) 👉 disconnesso
**Disconnesso** added after **sei** becomes a second person to fit the real subject of the sentence, so you.
![immagine](https://github.com/languagetool-org/languagetool/assets/123581658/4cc2ce95-8765-43f0-b1e2-4ad2572f38f9)

---
Placeholders inside each writing field on **Personal dictionary**, **Disable the chech in some websites** and **Advanced settings (only for professional users)** haven't a typographical ellipsis and 2 of them have a space before the 3 dots, both mistakes that LanguageTool detects.

**Impostazioni avanzate (solo per utenti professionali)** 👉 **Impostazioni avanzate (per utenti esperti)**
In this context, **esperti** (**experts**) is more recommended.

**Comment by schurigeln** [comment]
✅ Those texts have been released with version `8.1.2` ![Screenshot 2023-10-11 alle 14 08 09](https://github.com/languagetool-org/languagetool/assets/15170499/208ee3a8-1914-4877-8292-552379dac549)
