### ISSUE TITLE
[nl] teveel/te veel

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#9293]
There was a rule for this, but somehow this is not triggered nowadays. It is a common, but very stupid mistake.
Yes, it will result in quite some ignores, but it is still a good rule.

Have a look at: https://onzetaal.nl/taalloket/teveel-te-veel (or many other pages about this mistake)

**Comment by mark-baas** [comment]
Maybe you came across a sentence with an undetected error? The rule hasn't been disabled and seems to work fine with my test sentences. I'll note it for improvement.

**Comment by baarsrj** [comment]
I found some hundreds of places where it should have triggered. I guess it needs a complete overhaul.
