### ISSUE TITLE
[nl] (and others) improve loading of simple replace

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#9294]
When loading simple replace, the items to be replace should be ordered having the highest number of tokens first.
The suggestions should be ordered by replacement frequency, high to low.
The first is relatively easy; counting spaces could be enough.
The second requires word group frequency data.

**Comment by baarsrj** [comment]
This is not just for Dutch. It may occur (and certainly does in Dutch) there are longer and shorter replaces, The longest will be most specific, and have to be checked first.

Until recently, this was done offline, but if it is done while loading, it is much easier to maintan

**Comment by evan-defran-lt** [comment]
> This is not just for Dutch

Understood! But we have to start somewhere, so this is where it will be :-)

**Comment by mark-baas** [comment]
This has been tested, and seems to be arranged already within the code. No matter if an entry with a high amount of tokens is at the top or the bottom of the replace file, it matches first anyway.
