### ISSUE TITLE
[pt] Idea for rule: “por momento” → “por momentos” - 2023-09-12

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#9297]
Hello, brother @ricardojosehlima

I believe that `“por momento”` is always plural (invariable).

`“Por momento vi a nossa vida a andar toda para trás.”`
`“por momento”` → `“por momentos”`

What is your opinion?

Are there any special requirements for it to be always plural?

This could be tonight's task.

❤️ ❤️ ❤️ ❤️ ❤️ 

Thank you!

**Comment by ricardojosehlima** [comment]
Hi, and the answer for pt-br is.......
drum rolling.....
neither!
We use "Por um momento". 
But plural seems more acceptable "Por momentos" >> "Por momento".

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Sorry, I fell asleep… lol 😋 😋 😋 😋 

So, it is probably a pt-PT rule only.

I will code it as pt-PT.

Thank you!
