### ISSUE TITLE
[pt] Idea for antipattern - 2023-09-12

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#9299]
Heya, @ricardojosehlima

Sorry for falling asleep… 😋 

I wanted to create an antipattern for:
`"Eu sou letras, prazer, poesia, pecado, redenção."`

![Screenshot 2023-09-12 at 16-53-29 Editor](https://github.com/languagetool-org/languagetool/assets/5192600/4166b143-a044-4df7-aa75-a49c8cf9f1a0)

![predicativo](https://github.com/languagetool-org/languagetool/assets/5192600/09e34b4f-371a-4365-9a61-18107c1219e7)

`Verb Ser + NCPlural + "," + NC`

Is it right only for pt-PT or to all variants of PT?

Thank you, my dear brother!

❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
Maybe it will work with all verbs with the form of “eu” and “nós”?

“(eu) quero letras”, “(nós) queremos letras”?

**Comment by marcoagpinto** [comment]
`"Ele É letras, poesia (...)"`

"é" should also be correct? Maybe the whole verb ser?

**Comment by ricardojosehlima** [comment]
This seems a rare construction to me, but keeping the verb in the singular seems fine.
Worth looking and check if there are false positives

**Comment by marcoagpinto** [comment]
@ricardojosehlima 

Thank you!

I will work on it tonight.

❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
It removed zero hits in 900 000 sentences.
