### ISSUE TITLE
Inconsistencies across LT variants

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#9309]
Don't all plug-ins not use the same backend as the site? I am getting very different results between the Firefox extension and the website. 

Part of it might be that rules moved from Open Source to premium?

**Comment by danielnaber** [comment]
> I am getting very different results between the Firefox extension and the website.

Could you post an example?

**Comment by baarsrj** [comment]
It might also be my memory playing trics. I will post examples when I find them. If not soon, I will close the issue.
