### ISSUE TITLE
Suggestion/error detected but not listed

### ISSUE THREAD

**Issue by kevinkuranyi** [languagetool-org/languagetool#9310]
When using LT in Overleaf, the suggestions are not shown, and I need to scroll through the entire text looking for it:

![image](https://github.com/languagetool-org/languagetool/assets/126336549/79d6e5d7-344a-4fa3-8a4b-81ad0c7a9c07)

Is this a bug?

**Comment by danielnaber** [comment]
That's not a bug, it's a known limitation that we cannot easily fix.
