### ISSUE TITLE
[de] das "persona in "in persona" wird fälschlicherweise zu "Persona" korrigiert

### ISSUE THREAD

**Issue by sterafix** [languagetool-org/languagetool#9311]
<img width="548" alt="grafik" src="https://github.com/languagetool-org/languagetool/assets/72454286/b6204c0a-203a-42e3-a48a-f0228e9ea9d9">

https://www.duden.de/rechtschreibung/in_persona

**Comment by Luisa-LT** [comment]
https://github.com/languagetool-org/languagetool/pull/9314/commits/88edda5b0eeee681df2bc27101b80d7de6c6110e
