### ISSUE TITLE
[nl] not so good example on website

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#9327]
It is not useful to make a text more complicated; this example does that:

![afbeelding](https://github.com/languagetool-org/languagetool/assets/8479998/80b5bc2c-e474-437a-ae58-a9ca5abcbaca)

**Comment by mark-baas** [comment]
I think it depends on the type of rewrite you were getting. There's General, Simplicity and Formal. If you picked a formal rewrite, I suppose it would be possible that LT would suggest more complicated synonyms. 
Currently I'm not getting this exact rewrite for any of the options.
