### ISSUE TITLE
compounds.txt case sensitivity

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#934]
compound.txt is case sensitive. For Dutch, this is inconvenient; at the start of a sentence, every word gets a capital; in other places it does not, regularly.

**Comment by f-knorr** [comment]
Could you please clarify the problem with an example.
What is the entry in compounds.txt?
What is the undesired behavior?
What is the desired behavior?

**Comment by baarsrj** [comment]
Any entry in the file has the problem. Check it on the website with:
Dit is een zee egel. (detected)
Zee egel is een woord. (not detected)

The desired behaviour is the rule to only be case sensitive when the word in compound.txt is not fully lowercase (This might be a bit different for German, since every noun is made firstupper there. Daniel?)

**Comment by baarsrj** [comment]
Thanks!
