### ISSUE TITLE
LT not working and I can't uninstall it

### ISSUE THREAD

**Issue by domi84** [languagetool-org/languagetool#937]
SO: Ubuntu 16.04
Libreoffice: 5.4.5.1
LanguageTool: 4.0

languagetool was working before, but yesterday I installed a software that update java e LT was not working anymore.
So I decided to start again. Removed all the java packages, libreoffice (and deleted libreoffice config file).
I have installed libreoffice again, and Java 8 from Oracle (using webupd8 ppa).
In Libreoffice -> Advanced "Oracle Corporation" v. 1.8.0_161 is selected (same version installed by the ppa), location /usr/lib/jvm/java-8-oracle/jre
I installed LT 4.0 (the installation took 1 moment) but doesn't work. I tried to uninstall LT, but return me this error:
`(com.sun.star.lang.IllegalArgumentException) { { { Message = "Cannot detect media-type: file:///home/domenico/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu5950ir81ei.tmp_/LanguageTool-4.0.oxt", Context = (com.sun.star.uno.XInterface) @4f98620 } }, ArgumentPosition = (short) -1 }
`
And I can't uninstall it.
What can I do?

**Comment by danielnaber** [comment]
Maybe your download of LT was incomplete. This seems to be a bug in LO, not sure we can do anything about it: https://bugs.documentfoundation.org/show_bug.cgi?id=58923

**Comment by domi84** [comment]
Mmm...interesting...
So I removed libreoffice e config file, installed LO again. I downloaded and installed LT 3.9 .
Same issue, doesn't work and I can't uninstall it:
`(com.sun.star.lang.IllegalArgumentException) { { { Message = "Cannot detect media-type: file:///home/domenico/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu9570jt8nzx.tmp_/LanguageTool-3.9(1).oxt", Context = (com.sun.star.uno.XInterface) @3a079d0 } }, ArgumentPosition = (short) -1 }`

**Comment by domi84** [comment]
Sorry guys, my fault. 
I got this issue with any extension installed in LO.
