### ISSUE TITLE
[pt-br] A proposal for user feedback in grammar "errors"

### ISSUE THREAD

**Issue by ricardojosehlima** [languagetool-org/languagetool#9383]
Hi all, especially @p-goulart and @susanaboatto,

   I have observed that LT treats what we call "grammatical errors" or "deviations from standard norm" differently. Check the three images attached
![conc_num](https://github.com/languagetool-org/languagetool/assets/36453534/d25b5255-5158-4270-a66d-4b98e8a26ebb)
![para_mim](https://github.com/languagetool-org/languagetool/assets/36453534/e6ad1ddb-1de4-44d9-bc97-2f488cb9544d)
![menas](https://github.com/languagetool-org/languagetool/assets/36453534/6a141041-9654-4226-93d6-6814b491c301)
    While "menas" receives a, say, fair treatment, it's not so for "para mim fazer" and "os menino" is not even close to fair.
    I believe Sociolinguistics has a contribution to make in such cases, using words and expressions that may enlighten the user of what it is going on in cases such as those: there is absolutely no error at all, only an inadequacy (which by its turn is socially oriented) to a certain register.
    So, I was wondering if LT would like to gather efforts to build more, say, friendly and informative feedbacks - what would lead it to be distinguished among other grammar correctors that only point out the error, by using the word "error". 
     If there are interest and time conditions to do so, I'd be glad to help with it.

**Comment by danielnaber** [comment]
@p-goulart @susanaboatto Do you think we should use the blue underline for (some of) Ricardo's examples? We use it for those cases where something isn't a grammar error, but users expect LT to make a suggestion anyway.

**Comment by p-goulart** [comment]
@danielnaber, IMO not in these cases. These are constructions that people are taught in school as **grammar** errors, and they are not matters of style *per se*. They are strongly stigmatised. Users expect prescriptive grammatical correctness, and as such, IMO they ought to remain classified as 'grammar' issues. @susanaboatto do you agree?

Brazilian Portuguese suffers from a terrible case of diglossia, so it's hard to find equivalents, but... it'd be like underlining 🇩🇪 `bestmöglichste` or 🇬🇧 `I have took` in blue. Descriptively speaking, grammatical, as some native speakers use it, but still very much a **grammar** issue as far as users are concerned, not a matter of style.

**Comment by ricardojosehlima** [comment]
Hi, @p-goulart !
   Thanks for the long answer and all the considerations within. I agree with you on "what the users want", which is for their errors to be flagged and receive a correct suggestion. My proposal may have seemed radical due to my excitement about it and also for mentioning Sociolinguistics' contributions. 
    But in reality, it would be something simpler, in the direction of what is written for "menas", but not for "os menino". A simple explanation and, yes, the idea that this is not an error, but a structure that is disregarded in some registers. That'd be all - although there could also be a link for, if the user wishes, more in depth explanations on what is going on.
   However, as you pointed out, there are some technical challenges to implement such a proposal: the single grammar file for both pt-br and pt-pt, the rule that embraces *os menino chegou and *o menino chegaram, and also the discussion of what should be told and in which tone. 
   Regarding the last, I quote you "Users do not expect a grammar corrector that says 'there is no error at all',". That was precisely my point: users don't expect that because either (a) they do not even know that or (b) they do but disagree. In any case, there could be a tool that flagged this to them: there is enough scientific basis to go against it and LT could be this space to spread this unpopular idea - that could draw attention to LT, people would discuss it, and so on.
   I understand, though, that this is a deep issue - although as I said above it'd be only something in the line of how "menas" is treated, not "para mim fazer" or "os menino". And together with the technical challenges, it may be enough to pose my proposal to rest.
   As a final note, I agree with you on the blue underlining not applying to these cases.

**Comment by p-goulart** [comment]
The issue of the joint `pt-PT`/`pt-BR` grammar files shouldn't stop us, though. It's a challenge, but only a technical one, and one I think we can definitely overcome.

I'd still be interested in hearing how you think the two other errors there could be pointed out to users. What specific kind of language? Is it simply avoiding 'erro' in favour of 'não se aceita em registros formais' or something of the sort?

Personally, I feel like the message in `para mim fazer` is detailed enough as far as the nature of error is concerned, and it doesn't have any references to any 'error'.

The one in `os menino` isn't very friendly or informative, and must definitely be changed – and it will... but first we need to know that can even detect agreement issues consistently and distinguish all the different cases ;)

**Comment by ricardojosehlima** [comment]
Hi, the plan would be to access what is flagged as grammar error and provide some simple explanations, the one in "menas" looks fine. The one in "para mim fazer", on the other hand, seems to me to mandate something that is not realistic in all scenarios - the adding of "em registros formais" could do it, along with something like "embora a preposição possa indicar a presença de "mim", em registros formais..."; and so on.
So the change of "erro" to "não é aceita em registros formais" could be the first step, and the brief explanation the second.

**Comment by p-goulart** [comment]
> The one in "para mim fazer", on the other hand, seems to me to mandate something that is not realistic in all scenarios - the adding of "em registros formais" could do it

Sorry, I'm having trouble parsing this. What exactly is this 'something' that isn't realistic? I fail to see how adding 'in formal registers' has a huge impact on the explanation itself.

> along with something like "embora a preposição possa indicar a presença de "mim", em registros formais..."

The preposition may indicate the presence of the pronoun? Apologies, I don't understand this, either.

---

At any rate, you are more than welcome to [raise a PR](https://dev.languagetool.org/pt/git) with the changes you're proposing, and we'll review it. It's not something we can prioritise straight away but, if you're keen on contributing and you have a clear vision of what must be done, you can get started without us.

**Comment by p-goulart** [comment]
For now, though, I'm closing this issue as `not planned`, as I don't think this constitutes a **specific** bug we can solve or feature request that is somehow immediately **actionable**. Changing the tone of the messages is a huge endeavour that should be broken down into multiple steps.

We can, of course continue the discussion here, as I'd love to have more ideas on how we can make these messages more inclusive and informative, but it just shouldn't be an open issue.

**Comment by ricardojosehlima** [comment]
Hi,
  As for "para mim fazer", the current message is "Na posição de sujeito, use eu no lugar de mim". This is an instruction that serves the standard register, thus my idea to add "Em registros formais, na posição de sujeito, use eu no lugar de mim." Later I thought about completing it: "Embora a preposição indique a presença de "mim" em alguns registros, em registros formais, na posição de sujeito, use eu no lugar de mim." That's it. After all, people use "para mim fazer" because of the preposition. 
  As for other suggestions, if you could point out to me an updated file containing these grammar issues, I'd be happy to scan it. I'd keep explanations simple, as in "menas" and "para mim fazer" above and then could as you said open a PR.
