### ISSUE TITLE
Crash when clicking link

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#939]
OS: (K)ubuntu, latest. 
Java: OpenJDK 8

Clicking on the url in the 'more' dialog causes a crash.
Clicking on the link 'help to make LT better' does nothing, not a crash either.

Tested with yesterdays daily build, directly from the website, on a different machine then the one i detected it on first time.

Also see https://forum.languagetool.org/t/url-not-opening/2718

**Comment by danielnaber** [comment]
@pminos Any idea?

**Comment by pminos** [comment]
On the Linux platform the [Desktop API](https://docs.oracle.com/javase/8/docs/api/java/awt/Desktop.html) depends on Gnome libraries.

I have implemented a workaround. I will commit after some tests.
