### ISSUE TITLE
[nl] rule does not work due to auto-uppercase 

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#9405]
![image](https://github.com/languagetool-org/languagetool/assets/8479998/864a54a8-c1e0-4ab6-ba46-75186ad1be83)

The auto-uppercase functionality sometimes is a pain in the.... Why was it ever added?

**Comment by mark-baas** [comment]
This works:

> <rule id="T_WKW" name="T voor 't aan begin zin">
>     <pattern>
>         <token postag="SENT_START"/>
>         <marker>
>             <token>'</token>
>             <token spacebefore="no" case_sensitive="yes">T</token>
>             <token postag_regexp="yes" postag="WKW.*"></token>
>         </marker>
>     </pattern>
>     <message>Een ingekorte 'het' aan het begin van een zin hoort anders:<suggestion>'t <match no="4" case_conversion="firstupper"/></suggestion>.</message>
>     <example correction="'t Is"><marker>'T is</marker> fout gegaan.</example>
> </rule>
