### ISSUE TITLE
incorrect warning from test routines

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#941]
The Dutch rule: _15_JARIG[2], token [1], contains duplicated disjunction part (negen) within "twee|drie|vier|vijf|zes|zeven|acht|negen|tien|elf|twaalf|dertien|veertien|(vijf|zes|zeven|acht|negen)tien".

Indeed, 'negen' is two times in the string, but it is not double, because of the parentheses

**Comment by dpelle** [comment]
Indeed, this sanity check is implemented with a simplistic way. 
I can hopefully find time this weekend to try fix this.
I noticed such warnings in the Portuguese XML file too which are probably spurious.

In the mean time, you could avoid the warning in the Dutch XML file by rewriting your regexp in a simpler way:

"twee|drie|vier|vijf|zes|zeven|acht|negen|tien|elf|twaalf|dertien|veertien|vijftien|zestien|zeventien|achttien|negentien"
