### ISSUE TITLE
[pt] Help with aborted commit

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#9448]
Hello @jaumeortola @maphjo @susanaboatto @p-goulart 

I have spent several hours working on a new rule.

I was so focused on pulling it that I forgot to create a branch.

So, while it was pulling to master mistakenly, I pressed the “Abort” button on TortoiseGit.

I was no longer able to repull it because TortoiseGit says there are no changes done.

I tried to revert, delete, etc., but nothing worked.

Could one of you help me with this commit?

Thank you!

![Screenshot 2023-10-07 103249](https://github.com/languagetool-org/languagetool/assets/5192600/b1f57198-2ff7-4f4e-a3f5-d2e23161f293)

**Comment by p-goulart** [comment]
I don't have any experience with Tortoise, so it's hard to say. It sounds like you may have committed straight to `master`. To undo a commit (but keep the local changes), we usually need to [reset](https://git-scm.com/docs/git-reset), i.e. `git reset`. The exact command depends, it should work with the SHA of the last commit *before* the one you want to undo.

Though I don't think you need to do that... If it's committed **and** there are no history conflicts, why don't you just branch off (with the usual `git checkout -b pt/grammar/NAME_OF_RULE`) and then push that?

**Comment by marcoagpinto** [comment]
@p-goulart 

Pedro, what do you mean with “branch off”?

**Comment by marcoagpinto** [comment]
@p-goulart 

I believe I have done it well.

https://github.com/languagetool-org/languagetool/pull/9449

Thank you for the help.

**Comment by p-goulart** [comment]
Yep, looks good!
