### ISSUE TITLE
[en] "finally block" adverb/adjective confusion false positive

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#9511]
`we need the block with that line number for the finally block`

**Comment by evan-defran-lt** [comment]
This appears to be related to exceptions in Java programming. Per documentation that I can find ([from Oracle](https://docs.oracle.com/javase/tutorial/essential/exceptions/finally.html), [from Microsoft](https://learn.microsoft.com/en-us/dotnet/standard/exceptions/how-to-use-finally-blocks)), the keyword _finally_ is typically rendered in in-line code, e.g., `finally` block. 

When including the backticks in LT, the rule does not trigger.

**Comment by donnerpeter** [comment]
Even the documentation you link doesn't always highlight "finally" (see the headers). Google also gives me [this](https://www.javatpoint.com/finally-block-in-exception-handling) as a second result, where it's not highlighted anywhere.

**Comment by danielnaber** [comment]
I think this is such an extreme edge case that we just need to live with the false alarm.

**Comment by donnerpeter** [comment]
OK, thanks for the reply! We'll need to suppress this on the IDE side then: https://youtrack.jetbrains.com/issue/IDEA-335887/Ignore-LanguageTools-warnings-about-finally-blocks-in-comments
