### ISSUE TITLE
[en] FP with FEWER_LESS

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#9522]
Noted in https://internal1.languagetool.org/regression-tests/via-http/2023-10-23/en-US/result_grammar_FEWER_LESS%5B1%5D.html because of my change to the POS for kWh (https://github.com/languagetool-org/languagetool/commit/10b14812d2a08382dc1b3233bc5e600edc827288).

- [x] Approximately 70% of all commercial customers who consume 1,500 kWh or **less** will pay no more than $220 per month.
- [x] Commercial customers who spend 1,500 pounds or **less** will have to pay a small premium.
- [x] We guarantee that you will pay only 150 dollars or **less**.
- [x] You can buy it for 30 euros or **less**.
- [x] You can get it for 30 euros or **less** if you shop around.

No errors and no warnings:
This task takes 30 minutes or less.
The video will start to play in 30 seconds or less.
This process takes approximately 30 days or less during the winter.

https://languagetool.org/insights/post/grammar-fewer-less/#when-to-use-%E2%80%9Cfewer%E2%80%9D is not complete. Refer to the counter-examples in https://www.merriam-webster.com/grammar/fewer-vs-less.

**Comment by AzadehSafakish** [comment]
@MikeUnwalla 

I've pushed a small fix.
To expand the exception, I would like to ask your permission to move your `currency_names` entity from Premium to OS.
It contains a lot of words that would be useful here.
