### ISSUE TITLE
Reconsider emoji-java use

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#9537]
Emoji-java library is used in a couple speller rules. But the library is not maintained and outdated: no commits since 2020.

I think spellchecking may safely ignore any non-letter characters, so you might want to exclude them with Character.isLetter(OrDigit) check. There are also various inexact character class and regex alternatives, see the answers at https://stackoverflow.com/questions/24840667/what-is-the-regex-to-extract-all-the-emojis-from-a-string.

If you need emoji and only emoji, I'd suggest using [jemoji](https://github.com/felldo/JEmoji). It's a drop-in replacement for emoji-java, but totally up to date.

**Comment by Nyabinary** [comment]
I agree, it doesn't seem wise to rely on a possible insecure and outdated library.

**Comment by jaumeortola** [comment]
A PR to remove the emoji-java dependency: https://github.com/languagetool-org/languagetool/pull/9590
I want to do more tests before merging it.

**Comment by nyabinary** [comment]
> A PR to remove the emoji-java dependency: #9590 I want to do more tests before merging it.

Any update on that btw?

**Comment by jaumeortola** [comment]
> Any update on that btw?

I think the PR can be merged. But I still had some doubts about what will happen in some scripts like Arabic.

**Comment by nyabinary** [comment]
> > Any update on that btw?
> 
> I think the PR can be merged. But I still had some doubts about what will happen in some scripts like Arabic.

It should be able to test it, though.

**Comment by jaumeortola** [comment]
Merged
