### ISSUE TITLE
Not checking the document in LibreOffice on Linux; LanguageTool ignores chosen language

### ISSUE THREAD

**Issue by rolandixor** [languagetool-org/languagetool#9556]
When I try to check the document, LanguageTool ignores the language I have chosen and defaults to Arabic. It then throws this error:

languagetool.openOffice.SpellAndGrammarCheckDialog$LtCheckDialog$9.run(SpellAndGrammarCheckDialog.java:1506) at java.base/java.lang.Thread.run(Thread.java:829)

See screenshot: https://imgur.com/a/xNU9lHz

**Comment by FredKruse** [comment]
Please try the newest nightly. The problem should be solved.

**Comment by FredKruse** [comment]
@rolandixor 
Is the problem solved? Can we close the issue?

**Comment by rolandixor** [comment]
Apologies for not following up before, forgot about this issue. Yes, it is resolved.
