### ISSUE TITLE
test issue in error message from server

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#9560]
ErrorRateTooHigh is reached by a single sentence after rule: #### the whole text contains 43 words this sentence has 27 matches

There is punctuation missing here.

(Yes, I know this is an extremely picky remark).

**Comment by Luisa-LT** [comment]
Hi @baarsrj, could you provide the sentence that causes the error?

**Comment by baarsrj** [comment]
The mistake is in the message itself.

the whole text contains 43 words this sentence has 27 matches

imho it should be:
ErrorRateTooHigh is reached by a single sentence after rule: ####. The whole text contains 43 words; this sentence has 27 matches.
or:
ErrorRateTooHigh is reached by a single sentence after rule: ####. The whole text has 27 matches and 43 words.

Note the punctuation.

I am not native English, but I strongly feel there is punctuation missing.

**Comment by Luisa-LT** [comment]
Thx for the explanation.
