### ISSUE TITLE
LanguageTool.log annoyingly dumped into $HOME

### ISSUE THREAD

**Issue by Bujiraso** [languagetool-org/languagetool#957]
I keep seeing this LanguageTool.log spawn in my home. I assume LibreOffice is running it, but I can't fully verify.

{code}
$ cat LanguageTool.log 
LT Log from Sun Mar 18 19:04:33 ADT 2018
{code}

Is this log location configurable? I don't really want it randomly appearing in my home dir all the time.

**Comment by danielnaber** [comment]
The next version will hide the file (`LanguageTool.log`). The location is not configurable.

**Comment by Bujiraso** [comment]
This should be put into an XDG path, not just home.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by Bujiraso** [comment]
XDG_DATA_HOME/LanguageTool would be fine, I think.
While home is regularly littered, it is not ideal to follow suit and add to the mess.

**Comment by udopt** [comment]
Unfortunately, LanguageTool Version 4.1, 2018-03-27, still seems to create the log file in $HOME without the dot.

**Comment by Bujiraso** [comment]
Hey @danielnaber, can this please be put into an XDG path? I'm not alone here in looking for it to move :)

It won't be dangerous or troublesome to mkdir -p $XDG_DATA_HOME/LanguageTool/ and follow that good example.

**Comment by danielnaber** [comment]
Should be fixed now, closing.
