### ISSUE TITLE
No function in CKEditor

### ISSUE THREAD

**Issue by foxly-it** [languagetool-org/languagetool#9577]
The function, to replace corrected words, does not work with the following editor.
https://ckeditor.com/ 
It can be tested here: https://ckeditor.com/ckeditor-5/demo/feature-rich/

tested with Safari extension

**Comment by tiff** [comment]
@foxly-it thanks for reporting. We are now in the process of rolling out a fix. Sorry that it took that long for us to come up with a fix.
