### ISSUE TITLE
[Feature Request] [en] Add option to show definitions via double clicks 

### ISSUE THREAD

**Issue by Nyabinary** [languagetool-org/languagetool#9586]
A feature akin to this would be extremely useful to save time from searching up definition of unknown words. Here is how Grammarly implements such a feature.
![image](https://github.com/languagetool-org/languagetool/assets/97130632/bcd6c9ec-5b4a-4029-9573-34edcc6c60d2)

**Comment by Luisa-LT** [comment]
Hi @Nyabinary, thanks for your comment. LanguageTool already has a synonym function. This can be activated in the add-on under Settings.
![image](https://github.com/languagetool-org/languagetool/assets/115984740/182b51b9-76f6-497b-8542-a12e23e92c16)

The synonyms are then displayed by double-clicking on a word.
![image](https://github.com/languagetool-org/languagetool/assets/115984740/e40a38cb-1db8-4b64-ab70-71e03dda4cce)

However, a definition is not included there, but could be a good enhancement idea. We will look into it :-)

**Comment by Luisa-LT** [comment]
Hi, actually, our team is already working on improving the synonym's feature. We will promote new features as soon as they are available :-)

**Comment by Nyabinary** [comment]
> Hi, actually, our team is already working on improving the synonym's feature. We will promote new features as soon as they are available :-)

Wait so definition is already being worked on like implemented internally?

**Comment by Luisa-LT** [comment]
We'd really like to tell you more, but, we cannot share further information just yet. I appreciate your understanding :-)

**Comment by nyabinary** [comment]
Any updates?
