### ISSUE TITLE
[LO-add-on] Null Pointer Exception on nightly 2023-11-04

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#9612]
Heya, @FredKruse 

I am getting this error in the nightly from day 4:
![lt_addon_20231104](https://github.com/languagetool-org/languagetool/assets/5192600/c1e0a35d-8d17-4eec-b91e-15627822f04e)

Thanks!

**Comment by FredKruse** [comment]
The issue should be solved. Please test it tomorrow and close the issue.
Thanks

**Comment by marcoagpinto** [comment]
It seems to be fixed!

Thanks!
