### ISSUE TITLE
[en] COMMA_COMPOUND_SENTENCE incorrect example

### ISSUE THREAD

**Issue by donnerpeter** [languagetool-org/languagetool#9619]
`I need to borrow some money so I can buy some medicine for Tom.`
The comma here seems optional, depending on the intended meaning. Likely, `so that` is meant, and then the comma is not needed.

**Comment by tiff** [comment]
Done with https://github.com/languagetool-org/languagetool/commit/71d66a0528b6db756871b60f08a0d3c06942c121
