### ISSUE TITLE
Rules don't find matches in their own IncorrectExamples 

### ISSUE THREAD

**Issue by ImmortalTurtle** [languagetool-org/languagetool#962]
I've discovered, that there are rules that don't see any errors in `IncorrectExample`s.

Rule HERE_HEAR didn't find any errors in the next sentence:
> If you do not here from me in a day...

This problem is quite rare for English and more common for other languages.

Are there already some tests checking whether `IncorrectExample`s are actually Incorrect for a `Rule`? 
If not, I can write one

**Comment by danielnaber** [comment]
How did you notice and test that? When I paste that sentence at languagetool.org, the error is found by rule `HERE_HEAR`.

**Comment by ImmortalTurtle** [comment]
Hmm, weird. Indeed so.
I've just run each `Rule` on it's own IncorrectExamples and checked whether `RuleMatches.length == 0`.
I don't know, is that because I've made a mistake somewhere or it's supposed to work like that.
There are 2 rules in Russian, IncorrectExamples of which are still not detected by languagetool.org, but that's probably because they are disabled since the rules rather concern style.
Here they are:

> Rule PNN_ON_END didn't find errors in example:
> Не для этого оно.

> Rule missing_noun_at_end didn't find errors in example:
> Так он и выбрал красивую.

**Comment by yakovru** [comment]
These two examples are detected with the default settings by languagetool.org.
It is very important to have a dot at the end of the sentence to detect this error.

**Comment by ImmortalTurtle** [comment]
I just checked and it turns out, that it's important to have a space after the dot for it to find an error. I suppose,  that's needed for LT to recognize this as a sentence?
Meaning, that if there's only "оно." in the end of the sentence, it doesn't detect an error. However, if there's "оно. " instead, it works fine.
I guess, that's not relevant when analyzing real texts, but might influence cases where the sentence with such error is the last one.

**Comment by yakovru** [comment]
Closed for Russian via https://github.com/languagetool-org/languagetool/commit/362d790b7c6b57b5e42acbf31677e8686eed5a98
