### ISSUE TITLE
[de] "auf dem Herzen" vs. "am Herzen"

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#9636]
Es kommt oft zu Verwechslungen der beiden Redewendungen "mir liegt etwas am Herzen" (es ist mir wichtig) und "mir liegt etwas auf dem Herzen" (es bedrückt mich). Es ist nicht leicht umzusetzen, aber es wäre schön, wenn LT merken würde, dass ich gerade vermutlich die falsche der beiden Redewendungen benutze.

Beispiel:
> Die Sicherheit Ihrer Kinder liegt uns auf dem Herzen

Man könnte z.B. eine Regel machen, die anschlägt, wenn man positiv besetzte Begriffe (Sicherheit, Gesundheit etc.) zusammen mit "auf dem Herzen" verwendet.

**Comment by Luisa-LT** [comment]
Hi, danke für die Idee. Wir werden es uns anschauen :-)
