### ISSUE TITLE
[en] LanguageTool gets confused between what suggestion it wants to suggest to the user (LOOP)

### ISSUE THREAD

**Issue by Nyabinary** [languagetool-org/languagetool#9676]
See here:
[Screencast from 2023-11-15 09-50-30.webm](https://github.com/languagetool-org/languagetool/assets/97130632/3b52b02e-48c1-499e-bbf4-479684e946f2)

**Comment by evan-defran-lt** [comment]
Thanks for flagging!

**Comment by Nyabinary** [comment]
> Thanks for flagging!
Here another example as well!
[Screencast from 2023-11-15 11-09-33.webm](https://github.com/languagetool-org/languagetool/assets/97130632/aef06ce5-b096-4cc5-a75e-ad19fe4cc770)

**Comment by evan-defran-lt** [comment]
Thanks again. [This commit](https://github.com/languagetool-org/languagetool/commit/3f4ab4b58361092e1d4160299e8862196478597f) takes care of the missing word.
And I think I've solved the loop problem.
