### ISSUE TITLE
[LibreOffice Plugin] Support for self-hosted language instance

### ISSUE THREAD

**Issue by bonanza123** [languagetool-org/languagetool#971]
Is it possible to use the libreoffice plugin with a self-hosted (non-local) languagetool instance?
If not, can it be added?

**Comment by danielnaber** [comment]
It's not possible yet. The add-on doesn't use a server at all but comes with all the program logic integrated.

**Comment by bonanza123** [comment]
Ahh, thanks for the clarification. In there any (rough) ETA for this?

**Comment by FredKruse** [comment]
Now an API to an HTTP / HTTPS-Server is integrated in the LibreOffice plugin. Please use the HTTP-Server of the actual snapshot to get all features.
Please test the new feature and close the issue if it works.

**Comment by bonanza123** [comment]
Thanks so much, it is working great!

**Comment by bonanza123** [comment]
@FredKruse sorry for asking a support question here, but I don't know any better place.
I'm always getting a connection refused error: https://imgur.com/a/NpYjYp5

As server, I am using my own. The URL format is like: `https://myserver.com/v2`
(which I am using with the firefox plugin). This server gives also a valid response to `curl --data "language=en-US&text=a simple test" https://myserver.com/v2/check`

What am I doing wrong?

**Comment by FredKruse** [comment]
The format of the URL must be like this: https://myserver.com  -  without /v2

**Comment by bonanza123** [comment]
@FredKruse thanks for your reply. Somehow this doesn't work for me either. Is there a way to get debug information for this plugin while playing with the settings?

**Comment by FredKruse** [comment]
@bonanza123, I think I got the problem: It seems you (just like me) forgot the port in the URL:
   https://myserver.com:port
port is most 8081

**Comment by bonanza123** [comment]
@FredKruse I still have the same problem with the following settings:
https://imgur.com/a/bnqAY7c
while the `curl` check on the same server works:
https://imgur.com/a/n3QZiWv

**Comment by bonanza123** [comment]
I guess I would a piece of the puzzle.

My server reports:

```
109.z.x.y - - [14/Mar/2020:18:37:49 +0100] "POST /v2/configinfo HTTP/1.1" 404 106 265 0.054 0.000 "-" "Java/1.8.0_242"
```

which version of the server is required for this to work?

**Comment by bonanza123** [comment]
I have upgraded to 4.8 but this does not solve the problem. Now I get
```
109.x.y.z. - - [14/Mar/2020:18:45:45 +0100] "POST /v2/configinfo HTTP/1.1" 502 157 265 4.332 4.332 "-" "Java/1.8.0_242"
```

**Comment by danielnaber** [comment]
Does it help if you start the server with `--allow-origin "*"`?

**Comment by danielnaber** [comment]
> which version of the server is required for this to work?

The code to handle `/v2/configinfo` was introduced in October 2019, so it's part of LT 4.8.

**Comment by bonanza123** [comment]
> > which version of the server is required for this to work?
> 
> The code to handle `/v2/configinfo` was introduced in October 2019, so it's part of LT 4.8.

Updating to v4.8. solved it, thanks!

**Comment by FredKruse** [comment]
It works at my localhost.
The URL-format in the Options of LO-extension is:
http://myserver:port
without the subdirectory v2, which is added intern automatically.
