### ISSUE TITLE
[nl] utf8 corruption using LT as tagger

### ISSUE THREAD

**Issue by baarsrj** [languagetool-org/languagetool#9720]
tagging a file using
java -jar languagetool-commandline.jar -t -b -l nl -c UTF-8 $CORPUS > $LTROOT/tagged.txt

results in erroneous output (Oekra?ne[Oekra?ne/ENM:LOC:LND] )

`<S> Nederland[Nederland/ENM:LOC:LND] heeft[hebben/WKW:TGW:3EP] als[als/VGW] enige[enige/ZNW:EKV,enig/BNW:STL:VRB] land[landen/WKW:TGW:1EP,land/ZNW:EKV:HET] binnen[binnen/BYW,binnen/VRZ] de[de/VNW:AWZ:EKV:DE_] EU[EU/ZNW:EKV:DE_] het[het/VNW:OND:MRV:HET,het/VNW:AWZ:EKV:HET] associatieverdrag[associatieverdrag/ZNW:EKV:HET] tussen[tussen/VRZ] de[de/VNW:AWZ:EKV:DE_] EU[EU/ZNW:EKV:DE_] en[en/VGW] Oekra?ne[Oekra?ne/ENM:LOC:LND] nog[nog/BYW] niet[nieten/WKW:TGW:1EP,nieten/WKW:TGW:3EP,niet/BYW,niet/VNW:OBP] getekend[getekend/BNW:STL:ONV,tekenen/WKW:VTD:ONV].[./ITP:PNT]~[</S>] 
`

The input is: 
Nederland heeft als enige land binnen de EU het associatieverdrag tussen de EU en Oekraïne nog niet getekend.~

This is not the first and only report on utf8 errors of LT on the command line.
This makes using it for tagging rather difficult

**Comment by danielnaber** [comment]
Does this happen on Windows? On Linux, I cannot reproduce the problem.

**Comment by baarsrj** [comment]
On linux, kubuntu, terminal set to utf-8. It is consistent in all command line output to file.Op 21 nov. 2023 20:55 schreef Daniel Naber ***@***.***>:
Does this happen on Windows? On Linux, I cannot reproduce the problem.

**Comment by danielnaber** [comment]
Are you sure the file (or that part of it) is indeed in UTF-8? Could you send it (or that part, if the file is large)?

**Comment by baarsrj** [comment]
Ther are some mentions of issues like this, caused by an update of KDE 5. I might have the same. It is strange though that only Java is sensitive for it. PHP dies not care, as ling as you set the enconding.Op 21 nov. 2023 21:13 schreef Daniel Naber ***@***.***>:
Are you sure the file (or that part of it) is indeed in UTF-8? Could you send it (or that part, if the file is large)?

**Comment by baarsrj** [comment]
[test.zip](https://github.com/languagetool-org/languagetool/files/13434742/test.zip)
This is just one sentence of the file to proof my point.
By the way, all I can find on locale settings seems to be set okay. I really would hate to have to reinstall the pc....

**Comment by danielnaber** [comment]
Is the file displayed properly using `cat test.txt`? With your file, I still cannot reproduce the issue. You could also call `java -Dfile.encoding=utf-8 -jar languagetool-commandline.jar -t -b -l nl -c UTF-8 $CORPUS > $LTROOT/tagged.txt` and see if that makes a difference.

**Comment by baarsrj** [comment]
I will try that suggestion.

**Comment by baarsrj** [comment]
That helped. What is it that makes the difference?

**Comment by danielnaber** [comment]
> What is it that makes the difference?

I think `-Dfile.encoding=utf-8` sets the default encoding, as if the operating system had that encoding. Not sure why your system doesn't have it already.
