### ISSUE TITLE
languagetool-core should not depend on logback

### ISSUE THREAD

**Issue by reckart** [languagetool-org/languagetool#974]
languagetool-core should not depend on an actual logging backend (i.e. logback). Since languagetool-core is a library and not an application, it should only depend on the SLF4J API. It should leave the choice of which actual logging backend to use to the applications which make use of the library.

**Comment by reckart** [comment]
If you need the dependency on logback for testing, then the scope should be set to "test".

**Comment by CorayThan** [comment]
This caused me a lot of issues recently. Specifically when using Spring Boot my project was picking up languagetool-core's logback.xml configuration file which caused it to not log at all. I don't want a logback.xml config file because spring boot configures logging by convention without me needing, but I now have to specify one to keep languagetool-core from hijacking my logging.

**Comment by danielnaber** [comment]
Pull request are very welcome. I'm very busy and the committer who originally added this is currently not available.

**Comment by mbspng** [comment]
@reckart I had a look at this and added `<scope>test</scope>` to the dependency entry that specifies the logger implementation:

```
<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.2.3</version>
    <scope>test</scope>
</dependency>
```

However when running a test (here `TokenAgreementAdjNounRuleTest.java`) while in advance changing `<root level="warn">` to `<root level="debug">` in `logback-test.xml` I get an error about a missing logger implementation in IntelliJ. DO you happen to knwo anything about that or can you elaborate on what setup you had in mind?

**Comment by reckart** [comment]
@mbspng I usually use log4j/log4j2 so I am not familiar with how to configure logback. Also I'm mainly using Eclipse and not IntelliJ. That said, when you set the scope "test" on a logging library, it is a good choice to put the logging configuration file into the `src/test/resources` folder of the project where your tests are. Contrary to "compile" (default scope) dependencies, "test" dependencies are not transitive. So you also need to explicitly add the logback dependency in test scope to all POMs of modules with tests or alternatively to the parent POM so that the modules may inherit it.

**Comment by mbspng** [comment]
@reckart Thanks, that was it.

**Comment by danielnaber** [comment]
Should be fixed now.

**Comment by vanackej** [comment]
Hi @danielnaber,
Changing logback scope to test is not enough, you should also move `logback.xml` file in core module from `src/main/resources` to `src/test/resources`. If you don't, `logback.xml` file is still picked up automatically and breaks every logging configuration for people using logback (including Spring Boot users, who is a large market share in Java space now).
Thanks !

**Comment by danielnaber** [comment]
File has been moved, thanks for noticing this issue.

**Comment by Hronom** [comment]
Same here, It was break logging for Spring Boot, happy that this solved, when you plan to push it to the maven central?

**Comment by danielnaber** [comment]
Next release is planned for 2018-06-26 (http://wiki.languagetool.org/roadmap)
