### ISSUE TITLE
[pt] Verb “fazer” with infinitive — 2023-11-23

### ISSUE THREAD

**Issue by marcoagpinto** [languagetool-org/languagetool#9740]
@ricardojosehlima

Heya, Brother Ricardo,

LanguageTool gives a verbal concordance error in:

Ele faz `os agentes recuar` perante o perigo.

Ela faz `os agentes contornar` obstáculos.

I believe that the verb “fazer” is a special verb, so is the above right?

Thanks!

**Comment by ricardojosehlima** [comment]
That's controversial in pt-br. Some accept singular, others the plural. I don't think this would be a straightforward rule for us and could create more confusion.

**Comment by marcoagpinto** [comment]
Ahhhh… thank you!

❤️ ❤️ ❤️ ❤️ ❤️
