### ISSUE TITLE
testrules.bat doesn't work anymore

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#975]
Since late 4.1 I can't use testrules.bat anymore. I always get the following error codes, even with the newest daily build.

[
![lt error](https://user-images.githubusercontent.com/30999326/38445465-fc288fc0-39f3-11e8-82d3-1f948d8b41e6.PNG)
](url)

**Comment by danielnaber** [comment]
Which Java version do you use? `testrules.sh/bat` hasn't been changed lately.

**Comment by danielnaber** [comment]
I guess it will work with Java 8, at least it does here.

**Comment by Discostu36** [comment]
It works with Java 8, thanks. But I guess Java 9 support should be added?

**Comment by danielnaber** [comment]
> But I guess Java 9 support should be added?

Yes.

**Comment by danielnaber** [comment]
Closing here, Java 9+ is now at #1001
