### ISSUE TITLE
The english sentence We need to do this at most every 4 hours. is given wrong correction.

### ISSUE THREAD

**Issue by blloyd75** [languagetool-org/languagetool#9756]
The above sentence is one of the few cases where "most every" is correct.  In this case, it is at most, then every.  Unfortunately, the AI sees most followed by every and flags it as an issue, suggesting to replace with almost every, which is incorrect in the above context, since at almost every 4 hours implies it should be done roughly every 4 hours, where at most states no more than once every 4 hours, but not necessarily every 4 hours.

While there may be better ways to write the above, it is not wrong and the correction is certainly wrong.

**Comment by jaumeortola** [comment]
Thank you. This is a rule (not AI), and it has been fixed: https://github.com/languagetool-org/languagetool/commit/57bfbca97cd1c8a45739791f9448519bc6833834
