### ISSUE TITLE
String Index out of range. Fresh install. Libreoffice Add-on.

### ISSUE THREAD

**Issue by LightTemplar** [languagetool-org/languagetool#976]
I've got this message, if I open some .docx files (for example this [easi_be_2015_01_tor_en.docx](https://github.com/languagetool-org/languagetool/files/1907956/easi_be_2015_01_tor_en.docx) ) in Libreoffice Writer 
Libreoffice: `Version: 6.0.3.2
Build ID: 1:6.0.3~rc2-0ubuntu0.16.04.1~lo2
CPU threads: 4; OS: Linux 4.16; UI render: default; VCL: gtk2; 
Locale: de-DE (en_US.UTF-8); Calc: group`

![image](https://user-images.githubusercontent.com/453783/38743008-4b148c48-3f3e-11e8-8da9-4b752cfe16d0.png)

**Comment by LightTemplar** [comment]
@danielnaber, could you reproduce it? Do you need some extra info?

**Comment by danielnaber** [comment]
Does this also happen with a recent daily build from https://languagetool.org/download/snapshots/?C=M;O=D?

**Comment by LightTemplar** [comment]
Yes.
![image](https://user-images.githubusercontent.com/453783/40188328-fb8557da-59f9-11e8-90f0-020fd255f587.png)

**Comment by danielnaber** [comment]
@FredKruse Any idea?

**Comment by FredKruse** [comment]
I reproduced the bug. But it will take a little bit time, I have to do some more tests.

**Comment by f-knorr** [comment]
Hi @FredKruse ,
can we close this issue according to your last commit?

**Comment by dpelle** [comment]
I could reproduce the crash with LanguageTool-4.1.oxt using the document attached by bug submitter.
I then installed LanguageTool-20180602-snapshot.oxt and I could no longer reproduce the crash.
The bug appears to be fixed.

**Comment by LightTemplar** [comment]
I agree, it was fixed
