### ISSUE TITLE
performant

### ISSUE THREAD

**Issue by ShalokShalom** [languagetool-org/languagetool#979]
![screenshot_20180414_170226](https://user-images.githubusercontent.com/6344099/38769589-a052d404-4005-11e8-9577-82f0287bdfb6.png)

Sub issue: Why is here no choice to report a false alarm?

**Comment by danielnaber** [comment]
There is, but not for spelling errors. Someone would need to deal with all the (often low quality) feedback that these menu items generate.

**Comment by ShalokShalom** [comment]
I thought so
