### ISSUE TITLE
How to disable spell check for abbreviations (in which all letters are CAPITAL)

### ISSUE THREAD

**Issue by Saltsmart** [languagetool-org/languagetool#9812]
Hello! I'm using LanguageTool and a front-end `ltex` for Visual Studio Code.
Here is a problem from the spell check:

In my research fields, many ALL CAPS are valid words, such as those conference abbreviations: AAAI, ICML, CVPR and ECCV, etc.
However those words usually result in a huge number of false positive cases, like: `'MDPI': Possible spelling mistake found.`

How to get rid of these annoying spell check results? May I disable spell check for ALL CAPS?

![image](https://user-images.githubusercontent.com/40828952/194834933-927fd5a7-a6ec-470c-a17c-130b702df86e.png)

**Comment by Luisa-LT** [comment]
Thanks for pointing this out. Unfortunately, there is not such an easy solution as it might seem. For example, if the speller is deactivated for all capitalized words, errors such as "**YOUR** THE BEST!" would no longer be detected. But we are already thinking about solutions for such issues. Meanwhile, frequently used abbreviations or words in CAPS can simply be added to your personal dictionary :-)

**Comment by danielnaber** [comment]
@evan-defran-lt AAAI, ICML, CVPR and ECCV all exist in the EN Wikipedia, maybe we could extract all 3-4 character acronyms from there (or Wikidata)?

**Comment by evan-defran-lt** [comment]
Hi @Saltsmart, 
I've added roughly 2000 acronyms/initialisms to our English dictionary: https://github.com/languagetool-org/languagetool/pull/9889/files
I'll wait until after our deployment on Tuesday to merge the PR. 
The list will likely never be fully complete, but I'll continue adding over time.
