### ISSUE TITLE
ngram data usage

### ISSUE THREAD

**Issue by sarankup** [languagetool-org/languagetool#982]
Hi,

I could interface the languagetool in my java application and it is working well. I have a question about Google's ngram data.

I could download the 8GB data provided at http://languagetool.org/download/ngram-data/ and load the unzip path as mentioned in the page http://wiki.languagetool.org/java-api. 
`langTool.activateLanguageModelRules(new File("/data/google-ngram-data"))`

Is this 8GB data is more than enough to do grammer check or should I download all ngram and generate Lucene index again? Please advise.

Thanks in advance.

**Comment by danielnaber** [comment]
The index is complete, there's no need to download and re-create it.

**Comment by sarankup** [comment]
Hi Danielnaber,

Thank you so much for your response and I do appreciate it. I wonder that the ngram data is approximately 3TB, but the LanguageTools index is 8GB. And also the document at `http://wiki.languagetool.org/finding-errors-using-big-data` briefly describe how to generate Lucene index by `org.languagetool.dev.FrequencyIndexCreator`.

As far as the 8GB is the most updated data I would be very happy.

Thanks again.

**Comment by danielnaber** [comment]
The original Google data contains information about the years in which words appeared, this has been removed, making the size much smaller.
