### ISSUE TITLE
About the release scheme

### ISSUE THREAD

**Issue by chenrui333** [languagetool-org/languagetool#9823]
👋 it looks like the 6.3 release tag got changed to `xx-branch`, raise this issue to confirm if that is intended, and if so, is there any docs that I can reference? Thanks! cc @lpla

relates to https://github.com/Homebrew/homebrew-core/pull/156293

**Comment by danielnaber** [comment]
The 6.3 release is based on `v6.3-branch`, yes, but we can't make any guarantees about the tags/branches always having a name of the same schema.

**Comment by chenrui333** [comment]
cool, thanks for confirming the 6.3 release tag.
