### ISSUE TITLE
How to contribute ? We noticed multiple mistakes in French and would like to fix them and future ones.

### ISSUE THREAD

**Issue by Sharcoux** [languagetool-org/languagetool#9846]
Hi guys.

We noticed some mistakes in French, like the following sentences being marked as correct, or correct ones are marked as incorrect:

Incorrect marked as correct:

- J'ai fée des pâtes

Correct marked as incorrect:

- L'eau entre par la bouche du poisson et ressort par les opercules.

We would like to learn how to fix those in order to fix the future ones we might encounter. Can someone explain us what would be the process to solve that? Which file should we edit and with what kind of fix? We read the documentation but it is still very not clear to me.

**Comment by Sharcoux** [comment]
I think I succeeded to get the details I needed thanks to ChatGPT. I'll open some PRs to solve "avoir fée" and others. For now, I'm not sure yet about how to handle the false positive on "entre", though.

**Comment by Sharcoux** [comment]
I suggest to replace the whole rulegroup with the following rules:

```
<rulegroup id="CONFUSION_ER_E_PAR_SIMPLIFIE" name="Simplification de commencer par (commencé par)">
    <!-- Règle Générale pour les Verbes en -er suivis de "par" -->
    <rule>
        <pattern>
            <token postag="[NJ].*" postag_regexp="yes"/>
            <marker>
                <token postag="V inf" regexp="yes">.*er$</token>
            </marker>
            <token>par</token>
        </pattern>
        <message>Un participe passé semble plus approprié ici.</message>
        <suggestion><match no="2" regexp_match="(?iu)er" regexp_replace="é"/></suggestion>
        <example correction="affiché">Menu <marker>afficher</marker> par erreur.</example>
    </rule>

    <!-- Règle Générale pour les Verbes Conjugués à la 2e Personne Singulier Présent Indicatif se terminant par "es" -->
    <rule>
        <pattern>
            <token postag="V ind pres 2 s" regexp="yes">.*es$</token>
            <token postag="P"/>
        </pattern>
        <message>Un participe passé ou une autre forme verbale pourrait être plus appropriée.</message>
        <suggestion><match no="1" postag="(V) (ind) (pres) (2) (s)" postag_regexp="yes" postag_replace="$1 ppa m p"/></suggestion>
        <suggestion><match no="1" postag="(V) (ind) (pres) (2) (s)" postag_regexp="yes" postag_replace="$1 ind pres 3 p"/></suggestion>
        <example correction="envisagés|envisagent">Les cours <marker>envisages</marker> par cet élève ne paraissent pas pertinents.</example>
    </rule>

    <!-- Règle pour les Erreurs d'Orthographe Communes -->
    <rule>
        <pattern>
            <token postag="P|V.*" postag_regexp="yes"/>
            <token>les</token>
            <marker>
                <token regexp="yes">cameras|tractes|magasines|députes|délègues|cosignes|arrives|jures|immigres|troues|lutes</token>
            </marker>
        </pattern>
        <message>Un mot correctement orthographié semble plus approprié.</message>
        <suggestion><match no="3" regexp_match="cameras" regexp_replace="caméras"/></suggestion>
        <suggestion><match no="3" regexp_match="tractes" regexp_replace="tracts"/></suggestion>
        <example correction="caméras">Il fournit les <marker>cameras</marker>.</example>
    </rule>
</rulegroup>
```

This should be enough to sum up the 25 rules of the rulegroup.

**Comment by Sharcoux** [comment]
Fixed in:
https://github.com/languagetool-org/languagetool/pull/9875
https://github.com/languagetool-org/languagetool/pull/9876

**Comment by GillouLT** [comment]
Hello Sharcoux,

We’re in the process of updating our contributing documentation, Jaume already commented on one of the PRs with good insights, here are a few tips that might be missing from the documentation:

- Make sure the PRs pass the CircleCi tests
- Add default=”temp_off” to the under development rules, this will allow you to check the behavior of a new rule or rulegroup over a corpus before it goes live
- Once the PR has been reviewed, approved and merged with “temp_off”, you can [check the matches from the rule over the corpus](https://internal1.languagetool.org/) I mentioned in the previous bullet point, this tool will allow you to have an idea of the rule performance on the next day after the PR has been merged
- "If the rule seems to have a good performance based on the corpus check, we will take care of removing the default=”temp_off"
- We also avoid directly deleting rules until we are confident that the new rule has better performance
- Oh, and here you can find the tagset for French: https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/tagset.txt

Reworking CONFUSION_ER_E_PAR is very ambitious, the current rulegroup has flaws, any attempt on improving it is very well appreciated :)

If you have any technical questions regarding the codebase and rule development in general, feel free to participate in the forum https://forum.languagetool.org/

Enjoy your day!

**Comment by Sharcoux** [comment]
Thanks a lot for the feedback. I'll keep working on those 2 rules, and I have a few more PRs to open. I suggest that we continue the discussion directly on the respective PRs. Maybe we can close this issue.

**Comment by GillouLT** [comment]
Sounds great!
