### ISSUE TITLE
4-grams 5-grams

### ISSUE THREAD

**Issue by sarankup** [languagetool-org/languagetool#985]
Hi,

I have downloaded all 4-grams and 5-grams data. I would like to generate Lucene index to be added to the Index available here [http://languagetool.org/download/ngram-data/](url)

Unfortunately, the following class is not available in the jar downloaded from [https://mvnrepository.com/artifact/org.languagetool/languagetool-core](url)
`org.languagetool.dev.FrequencyIndexCreator.`

Please advise how to add 4 and 5 grams into existing Lucene index.

Thanks in advance.

**Comment by danielnaber** [comment]
Please post questions to the forum at https://forum.languagetool.org - this is just for bugs.

**Comment by sarankup** [comment]
Sorry about that. I have moved my query to the forum. Thank you.
