### ISSUE TITLE
Many alert windows open when opening multiple files in LO 6 

### ISSUE THREAD

**Issue by textleister** [languagetool-org/languagetool#987]
Many alert windows (20+) open when opening multiple files in LO 6.0.3.2 saying:

> An error has occurred in LanguageTool 4.1 (2018-03-27 11:22):
> java.lang.NullPointerexception
> Stacktrace:
> java.lang.NullPointerexception
> ... see file attached

Unfortunately not reproducible but only occurring when multiple files are opened.

![bildschirmfoto vom 2018-04-18 11-34-11](https://user-images.githubusercontent.com/15649394/39117137-8d90ed8c-46e6-11e8-9970-a8620adb15dc.png)

**Comment by danielnaber** [comment]
@FredKruse This is fixed in the current snapshot, isn't it?

**Comment by FredKruse** [comment]
Yes, it is fixed.

**Comment by danielnaber** [comment]
@textleister Could you try a recent snapshot from https://languagetool.org/download/snapshots/?C=M;O=D?

**Comment by textleister** [comment]
@danielnaber thanks a lot. I've installed the snapshot and will give it a try.

**Comment by newwhitebear** [comment]
This mistake occurs from LT 4.1. This is fixed also LibreOffice 6.0.4.2. Java jre version 8.172 or 10.0

**Comment by danielnaber** [comment]
Should be fixed in daily builds.
