### ISSUE TITLE
Thunderbird and Firefox extensions stopped working with local languagetool.

### ISSUE THREAD

**Issue by ProfRon** [languagetool-org/languagetool#9880]
Thunderbird and Firefox extensions stopped working with local languagetool with the newest versions.

More precisely: I have installed and updated languagetool on a (Apple silicon) macbook using homebrew (and brew services). I'm using languagetool 6.3, Both the Firefox and Thunderbird extensions are version 8.3.0, installed from their extensions web sites.

I can reach my local server with curl or using the link (http://localhost:8081/v2/check?language=en-US&text=my+text) on your documenation page (https://dev.languagetool.org/http-server#testing-the-server). Languagetool returns json that looks good to me, but may not be quite what the extnesions expect – assuming that they can make a connection at all.

In any case, the GUIs do not work.  For example, while writing this text (in Firefox), I have a spinning blue check mark icon until I stop writing, then a red "x". After clicking on the red x I get the error message "Sorry, something went wrong while checking your text. Restarting your browser might solve this. (500)".  

The Error Console in Thunderbird shows (among other errors & warning)  
`sendRemoveListener on closed conduit languagetool-mailextension@languagetool.org.240 3 [ConduitsChild.sys.mjs:108](resource://gre/modules/ConduitsChild.sys.mjs)`  
That's the only thing there that seems clearly connected to language tool (but what do I know?).

What other information would be helpful?  By the way, I use languagetool for both German and Englisch - and am having this problem with both English and German.

**Comment by ProfRon** [comment]
By the way, is it correct to report these problems here (in github)? I just saw a similar, possibly related thread over at https://forum.languagetool.org/t/chrome-brave-plugin-stopped-working-with-local-server/9576 (but under windows - so that we now have similar problems on macOS, linux and Windows).

**Comment by ProfRon** [comment]
By the way, is it correct to report these problems here (in github)? I just saw a similar, possibly related thread over at https://forum.languagetool.org/t/chrome-brave-plugin-stopped-working-with-local-server/9576 (but under windows - so that we now have similar problems on macOS, linux and Windows).

By the way, I can confirm what @thatso wrote, namely, that downgrading to Firefox Extension 8.2.2 and Thunderbird Extension 8.2.1 fixes the problem (in Firefox and Thunderbird, under macOS).

**Comment by thatso** [comment]
@danielnaber: I don't want to sound rude, but @ProfRon reports an error, I confirm that the browser addon is to blame, you suggest testing a new archive for a local installation which obviously does not help for Docker installations and such, out of the blue comes someone with a private profile saying everything is ok now and you consider this as case closed. Do you see the problem here?

**Comment by ProfRon** [comment]
Sorry for not commenting, but (1) as noted above I now have a workaround and (2) little time.  I'll test version 6.3a as soon as I get a chance.  Stay tuned (please).

**Comment by AlexLJordan** [comment]
I had the same problem and 6.3a fixed it.

**Comment by ProfRon** [comment]
OK, I finally got some time.  Version 6.3a fixed the problem. I am now running LT 6.3a with extension (Thunderbird and Firefox) updated to 8.3.0, and both work now (LT just fixed an error in this post, for example).
 
Thanks to everyone (especially @thatso for providing a workaround and then insisting that I test the fix!).

**Comment by DanielSiepmann** [comment]
https://github.com/languagetool-org/languagetool/issues/9757#issuecomment-1831915062 solved the issue for myself.
