### ISSUE TITLE
Spellchecker problem: "protokolieren"

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool#993]
The spell checker does not give correct suggestions for "protokolieren", "protokolierte" etc. I'm aware that I can change that by editing` GermanSpellerRule.java`, but I don't understand why the automatic suggestions don't work with a distance of only one character. Maybe a bug?

**Comment by danielnaber** [comment]
Should be fixed now. It was a bug, but a very specific one affecting only words with `kolier` as a substring.
