### ISSUE TITLE
Correction loop

### ISSUE THREAD

**Issue by PavanLuca** [languagetool-org/languagetool#9940]
![Schermata da 2023-12-17 18-43-34](https://github.com/languagetool-org/languagetool/assets/123581658/44e8ffd9-1660-4b43-85dd-7fe4023c6107)
![Schermata da 2023-12-17 18-43-39](https://github.com/languagetool-org/languagetool/assets/123581658/f323a77d-e4d0-4bd6-8172-1d22c3ef47ef)
![Schermata da 2023-12-17 18-43-52](https://github.com/languagetool-org/languagetool/assets/123581658/2723abfa-1e78-42df-af4c-cca90a4f4ac4)

**Comment by jaumeortola** [comment]
> Yes, ok, I was saying about chatting like on normal chats, then if who can wants to add an army of bots for me there's no problem, server's not mine.

**Comment by tiff** [comment]
This has been fixed. Thanks for reporting
