### ISSUE TITLE
LongSentenceRule: incoherent behavior due to static var

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#996]
The result of checking a Dutch text  depends on the state of the system in the HTTP server use case. E.g. if a "Simple German" text has been checked before, `maxWords` is set to 12.

**Comment by FredKruse** [comment]
Yes, I think this is because the configuration of the value don't consider the language. If you stay in one language the last value should also be used to check the next text.
I have to think about a solution.

**Comment by danielnaber** [comment]
Maybe a solution that works without `static` values is most robust. The value would need to be handed through all the code though, from the initial call to the creation of the rule.

**Comment by FredKruse** [comment]
Do you have an idea, where in the code such values could be stored? I introduce the static value because I had no idea, where to introduce a variable, which can be manipulated by the configuration dialog and that can be used by a rule.

**Comment by danielnaber** [comment]
Does the value need to be stored, other than in the configuration itself? Maybe it should not be stored, but given as a parameter, whenever a new JLanguageTool is created? That's what I meant with "hand through all the code". It's just an idea, I'm not sure if it's practical.

**Comment by FredKruse** [comment]
I'm working on a solution that works analog to the disabled/enabled rules solution. A list of ruleID-value-pairs that contains all values, that has configured by the dialog. The configurable rules has than to look into the list, if the value was configured by the user.
But the mechanism has to be implemented in the main functions of all languagetool modules. 
@danielnaber What modules use the configuration dialog besides the stand-alone-version and the office-extension?

**Comment by danielnaber** [comment]
> What modules use the configuration dialog besides the stand-alone-version and the office-extension?

Those are the only ones.

**Comment by danielnaber** [comment]
@FredKruse This has been fixed, hasn't it?

**Comment by FredKruse** [comment]
@danielnaber Yes, it has been fixed
