### ISSUE TITLE
Suggestions list bug on Editor

### ISSUE THREAD

**Issue by PavanLuca** [languagetool-org/languagetool#9982]
After scrolling down from the top of the suggestions list it appears a shadow that covers overlays that are supposed to be loaded over it.
![Schermata da 2023-12-22 15-14-44](https://github.com/languagetool-org/languagetool/assets/123581658/22c5688b-fea2-4b09-acc3-171a90ca8f9b)

![Schermata da 2023-12-22 15-15-02](https://github.com/languagetool-org/languagetool/assets/123581658/f2369261-54e5-454c-97d7-443a787157e3)

![Schermata da 2023-12-22 15-22-19](https://github.com/languagetool-org/languagetool/assets/123581658/b49d98d4-5dae-4c8f-8657-333fde1ccb83)

![Schermata da 2023-12-22 15-22-36](https://github.com/languagetool-org/languagetool/assets/123581658/9629669e-740b-4e22-b62c-fec881b7b057)

**Comment by tiff** [comment]
This has been fixed. Thanks!
