### ISSUE TITLE
Term 'Score' is returned as plural.

### ISSUE THREAD

**Issue by santosh-09** [languagetool-org/languagetool#999]
Hi,

I have a requirement to pass only "words" to check  method of LanguageTool instead of sentences. I have below piece of code to determine if a given word is singular or plural:
`List<AnalyzedSentence> alList = languageTool.analyzeText(word);  //where word is  'Score'
 for (AnalyzedTokenReadings atr : alList.get(0).getTokens()) {
   for (ChunkTag ct : atr.getChunkTags()) {

	if (ct.getChunkTag().equals("B-NP-plural")) {

		pluralStart = true;
				
    }
  if (ct.getChunkTag().equals("E-NP-plural"))
 {
			
pluralEnd = true;
			
}
     isPlural = pluralStart && pluralEnd`

for the word 'Score' isPlural from above logic is returned as '**true**' whereas I was expecting it to be **false** . I think '**Scores**'  should be treated as plural and not **'score'**. Any inputs ?

**Regards,**
Santosh

**Comment by danielnaber** [comment]
Not sure why you're using the chunks here, you should try AnalyzedTokenReadings.getReadings().getPOSTag().

Please post future questions to the forum, as this is not a bug.
